
import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';import {parseExpressionAt} from 'acorn';import {createHash} from 'node:crypto';
const ROOT='/Users/fordeargamers/Projects/exoduser-migration-20261001',sha=s=>createHash('sha256').update(s).digest('hex'),startedAt=new Date().toISOString();
function visit(n,fn){if(!n||typeof n!=='object')return;fn(n);for(const k of Object.keys(n)){if(k==='start'||k==='end')continue;const v=n[k];if(Array.isArray(v))for(const z of v)visit(z,fn);else if(v&&typeof v==='object')visit(v,fn);}}
const sources=['game.html','game-easy-test.html'].map(file=>{const s=fs.readFileSync(ROOT+'/'+file,'utf8'),si=s.indexOf('const SFX='),ob=parseExpressionAt(s,si+'const SFX='.length,{ecmaVersion:'latest'}),p=ob.properties.find(p=>p.key.name==='beamStop'),ui=s.indexOf('function update(){'),u=parseExpressionAt(s,ui,{ecmaVersion:'latest'});let b;visit(u,n=>{if(n.type==='SwitchCase'&&n.test?.value==='beam'&&s.slice(n.start,n.end).includes("if(!isAct('beam')"))b=n;});assert.ok(b);const startProp=ob.properties.find(p=>p.key.name==='beamStart');const mi=s.indexOf('const _MAGIC_E_HANDLERS=');const mo=parseExpressionAt(s,mi+'const _MAGIC_E_HANDLERS='.length,{ecmaVersion:'latest'}),mp=mo.properties.find(p=>p.key.name==='omniBeam');const ei=s.indexOf("addEventListener('mouseup',");const event=parseExpressionAt(s,ei,{ecmaVersion:'latest'}).arguments[1];const ri=s.indexOf('function _r('),rn=parseExpressionAt(s,ri,{ecmaVersion:'latest'});return{file,sourceSHA:sha(s),start:s.slice(startProp.start,startProp.end),startSHA:sha(s.slice(startProp.start,startProp.end)),magic:s.slice(mp.start,mp.end),magicSHA:sha(s.slice(mp.start,mp.end)),mouseup:s.slice(event.start,event.end),mouseupSHA:sha(s.slice(event.start,event.end)),random:s.slice(ri,rn.end),method:s.slice(p.start,p.end),methodSHA:sha(s.slice(p.start,p.end)),methodLine:s.slice(0,p.start).split('\n').length,branch:s.slice(b.start,b.end),branchSHA:sha(s.slice(b.start,b.end)),branchLine:s.slice(0,b.start).split('\n').length};});

assert.equal(sources[0].start,sources[1].start);assert.equal(sources[0].method,sources[1].method);
const original=sources[0].start,startAnchor='if(!_beamLoopGain)return;',startReplacement='if(_beamLoopGain!==lg)return;';assert.equal(original.split(startAnchor).length,2);const candidate=original.replace(startAnchor,startReplacement);
const stopAnchor="if(_beamLoopSrc){try{_beamLoopGain.gain.exponentialRampToValueAtTime(.0001,actx().currentTime+.1);setTimeout(()=>{try{_beamLoopSrc.stop()}catch(e){}},150)}catch(e){}_beamLoopSrc=null;_beamLoopGain=null}";
const stopReplacement="if(_beamLoopSrc){const _stoppingBeamSrc=_beamLoopSrc;try{_beamLoopGain.gain.exponentialRampToValueAtTime(.0001,actx().currentTime+.1);setTimeout(()=>{try{_stoppingBeamSrc.stop()}catch(e){}},150)}catch(e){}_beamLoopSrc=null;_beamLoopGain=null}";
assert.equal(sources[0].method.split(stopAnchor).length,2);
const capturedStop=sources[0].method.replace(stopAnchor,stopReplacement);
if(process.argv.includes('--emit-patch')){console.log(JSON.stringify({taskId:'SOUND-memory-beam-start-end-generation-owner-1320',targetFiles:sources.map(s=>({file:s.file,sourceSHA:s.sourceSHA})),methods:[{name:'beamStart',original:original,candidate,originalSHA:sha(original),candidateSHA:sha(candidate)},{name:'beamStop',original:sources[0].method,candidate:capturedStop,originalSHA:sha(sources[0].method),candidateSHA:sha(capturedStop)}],productionApplied:false},null,2));process.exit(0);}
const scenarios=['old-ended-after-release-restart','normal-owned-ended-advance','stop-without-restart-ended'];const records=[];
for(const g of sources)for(const id of scenarios)for(const patched of [false,true]){
 const trace=[],timers=[],ended=[],nodes=[],rng=[];let gn=0;
 const ev=(type,args=[])=>trace.push({type,args});const math=Object.create(Math);math.random=()=>{rng.push(.5);return .5;};
 const audio={currentTime:10,createGain(){const id=++gn;const gain={id,gain:{value:0,exponentialRampToValueAtTime:(v,t)=>ev('fade',[id,v,t])},connect:()=>ev('gain.connect',[id])};return gain;},
 createBufferSource(){const n={id:nodes.length+1,buffer:null,loop:null,stops:0,onended:null,connect:g=>ev('source.connect',[n.id,g.id]),start:()=>ev('source.start',[n.id,n.loop]),stop:()=>{n.stops++;ev('source.stop',[n.id]);ended.push(n.onended);}};nodes.push(n);return n;}};
 const s={Math:math,P:{x:0,y:0,facing:0,s:'idle',mp:20,skills:{omniBeam:1},_beamHold:false},G:{cam:{x:0,y:0}},MB:{2:true},BINDS:{beam:'mouse2'},BINDS2:{beam:null},
 _gpActive:true,_gpAutoAim:r=>ev('autoAim',[r]),_isFused:()=>false,_addSkProf:k=>ev('skillStart',[k]),_addSkProfTick:k=>ev('skillTick',[k]),_addFuseProfTick:()=>{throw Error('unexpected fuse');},
 isAct:k=>{ev('isAct',[k]);return false;},playSample:(...a)=>ev('playSample',a),actx:()=>audio,sfxVol:()=>1,mbus:()=>({}),_audioBuffers:{beam_r1:{duration:.2},beam_r2:{duration:.2},beam_r3:{duration:.2}},
 setTimeout:(fn,ms)=>{timers.push({fn,ms});ev('timer',[ms]);return timers.length;},_beamLoopSrc:null,_beamLoopGain:null,_beamLoopNext:null,_beamOsc:null,_beamOsc2:null,_beamMod:null,_beamGain:null};
 const c=vm.createContext(s);vm.runInContext('const SFX={'+(patched?candidate:original)+','+capturedStop+'};const actualMagic={'+g.magic+'};const actualMouseUp='+g.mouseup+';'+g.random+';function actualExtractedBeamCase(sp){switch(P.s){'+g.branch+'}};globalThis.startBeam=()=>actualMagic.omniBeam();globalThis.releaseBeam=()=>{actualMouseUp({button:2,preventDefault:()=>{}});actualExtractedBeamCase(1);};',c);
 assert.equal(c.startBeam(),true);const A=nodes[0];assert.equal(A.loop,false);assert.equal(s._beamLoopSrc,A);
 if(id==='normal-owned-ended-advance'){A.onended();assert.equal(nodes.length,2);}
 else{
  c.releaseBeam();assert.equal(s.MB[2],false);assert.equal(s.P._beamHold,false);assert.equal(s.P.s,'idle');assert.equal(timers.length,1);assert.equal(timers[0].ms,150);
  if(id==='old-ended-after-release-restart'){assert.equal(c.startBeam(),true);const B=nodes[1];for(const t of timers)t.fn();for(const cb of ended)cb();assert.equal(A.stops,1);assert.equal(B.stops,0);assert.equal(nodes.length,patched?2:3);assert.equal(s._beamLoopSrc,patched?B:nodes[2]);B.onended();assert.equal(nodes.length,patched?3:4);}
  else{for(const t of timers)t.fn();for(const cb of ended)cb();assert.equal(A.stops,1);assert.equal(nodes.length,1);assert.equal(s._beamLoopSrc,null);}
 }
 records.push({file:g.file,id,patched,status:'PASS',createdSources:nodes.length,sourceStops:nodes.map(n=>n.stops),trackedSource:s._beamLoopSrc?.id||null,player:{...s.P},trace,rng});
}
const controls=[];for(const g of sources)for(const id of scenarios.filter(id=>id!=='old-ended-after-release-restart')){const[a,b]=records.filter(r=>r.file===g.file&&r.id===id);assert.deepEqual(a.trace,b.trace);assert.deepEqual(a.rng,b.rng);assert.deepEqual(a.player,b.player);controls.push({file:g.file,id,exactTrace:true,exactRNG:true,exactPlayerState:true});}
const result={taskId:'SOUND-memory-beam-start-end-generation-owner-1320',execution:{startedAt,completedAt:new Date().toISOString(),exitCode:0,executions:records.length},sources:sources.map(({method,branch,start,magic,mouseup,random,...s})=>s),patch:{startAnchor,startReplacement,originalSHA:sha(original),candidateSHA:sha(candidate),candidate,dependencyCapturedStopSHA:sha(capturedStop)},records,controls,sourcePreserved:sources.every(s=>sha(fs.readFileSync(ROOT+'/'+s.file))===s.sourceSHA),productionApplied:false,newFiles:0,nativeListening:false,status:'SOURCE_PATCH_CANDIDATE',scope:'actual full omniBeam handler→beamStart, actual mouseup handler→full update beam case→beamStop, actual registered onended closures. Enclosing event dispatch/update not executed; AudioNodes/timer/ended delivery synthetic.',policies:{sampling:'same random pool3, loop=false, gain.8 and synchronous start preserved',owner:'onended may advance only captured lg still owns current beam gain',error:'existing catches unchanged',dependency:'prior captured-stop candidate used equally in both sides, not production adopted here',native:'no real timer/audio/input/listening'},finding:'Old ended closure currently creates extra source into new gain and overwrites tracked source; owner guard prevents it while new current closure advances normally.'};console.log(JSON.stringify(result));
