import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
for(const file of ['game.html','game-easy-test.html'])test(file+' translates control keys repeatedly without replacing child elements',()=>{
 const source=fs.readFileSync(file,'utf8');let lang='en';
 const context=vm.createContext({_L:(ko,en)=>lang==='en'?en:ko,_T:s=>s==='이동'&&lang==='en'?'Move':s});
 const start=source.indexOf('function _localizedControlKey('),end=source.indexOf('function _refreshPersistentHudLanguage(',start);
 vm.runInContext(source.slice(start,end),context);
 const key={textContent:'좌클릭',dataset:{},children:[]};
 const tail={nodeType:3,textContent:' — 이동',set nodeValue(s){this.textContent=s;}};
 const row={childNodes:[key,tail],querySelector:()=>key,set innerHTML(_){throw Error('Must preserve children');}};
 context._hDivs=[row];context._hMap=[['좌클릭','이동']];
 const line=source.split('\n').find(l=>l.includes('_hDivs.forEach'));
 vm.runInContext(line,context);assert.equal(key.textContent,'LMB');assert.equal(tail.textContent,' — Move');
 lang='ko';vm.runInContext(line,context);assert.equal(key.textContent,'좌클릭');assert.equal(tail.textContent,' — 이동');
 lang='en';vm.runInContext(line,context);assert.equal(key.textContent,'LMB');assert.equal(row.childNodes[0],key);
 const begin=source.indexOf("    const rows=new Set([..._tu.querySelectorAll('.tkey')]");
 const block=source.slice(begin,source.indexOf('    });',begin)+7);
 const text=value=>({nodeType:3,textContent:value,set nodeValue(s){this.textContent=s;}});
 const makeRow=(names,descs)=>{const keys=names.map(name=>({textContent:name,dataset:{},children:[]}));const nodes=[];keys.forEach((key,i)=>nodes.push(key,text(descs[i])));const row={childNodes:nodes,querySelectorAll:()=>keys,set innerHTML(_){throw Error('Must preserve tutorial children');}};keys.forEach(key=>key.parentElement=row);return {row,keys,nodes};};
 const multi=makeRow(['SPACE','F'],[' 분노폭발 / ',' 영역스킬']);
 const plain=makeRow(['Q'],[' 데빌포스 흡수 (HP→에너지)']);
 const forge=makeRow(['G'],[' 대장간 (제작)']);
 const composite=makeRow(['L-CTRL'],[' CT스킬 (유령걸음/얼음보주)']);
 const potion=makeRow(['1~4'],[' 물약 / 스킬슬롯']);
 const hold=makeRow(['E 홀드'],[' 이동']);
 context._tu={querySelectorAll:()=>[...multi.keys,...plain.keys,...forge.keys,...hold.keys,...composite.keys,...potion.keys]};
 context._T=s=>lang==='ko'?s:({'분노폭발':'Rage Burst','영역스킬':'Area Skill','데빌포스 흡수 (HP→에너지)':'Devil Force Absorb (HP→Energy)','대장간 (제작)':'Forge (Craft)','이동':'Move','CT스킬 (유령걸음/얼음보주)':'CT Skill (Ghost Step/Ice Orb)','물약 / 스킬슬롯':'Potions / Skill Slots'}[s]||s);
 vm.runInContext("{\n"+block+"\n}",context);assert.equal(multi.nodes[1].textContent,' Rage Burst / ');assert.equal(multi.nodes[3].textContent,' Area Skill');assert.equal(plain.nodes[1].textContent,' Devil Force Absorb (HP→Energy)');assert.equal(forge.nodes[1].textContent,' Forge (Craft)');assert.equal(hold.keys[0].textContent,'E Hold');
 assert.equal(composite.nodes[1].textContent,' CT Skill (Ghost Step/Ice Orb)');assert.equal(potion.nodes[1].textContent,' Potions / Skill Slots');
 lang='ko';vm.runInContext("{\n"+block+"\n}",context);assert.equal(multi.nodes[1].textContent,' 분노폭발 / ');assert.equal(hold.keys[0].textContent,'E 홀드');
 assert.equal(multi.row.childNodes[0],multi.keys[0]);
});
