import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
const html=readFileSync(new URL('../index.html',import.meta.url),'utf8');
const fn=html.slice(html.indexOf('function _updateCharDisplay(s)'),html.indexOf('// 로비 배경 preload'));
function setup(){const nodes={};for(const id of ['enterGameBtn','charDispEmpty','charDispTitle','charDispSub','lobbyCharPreview','lobbyCharKeyart','lobbyBgImg']){const set=new Set();nodes[id]={style:{},src:'',classList:{add:(...a)=>a.forEach(x=>set.add(x)),remove:(...a)=>a.forEach(x=>set.delete(x)),toggle:(x,on)=>on?set.add(x):set.delete(x),contains:x=>set.has(x)},getAttribute(k){return this[k]},removeAttribute(k){this[k]=''},pause(){},load(){},play(){return {catch(){}}}}}const ctx=vm.createContext({$:id=>nodes[id],_selectedCharDisplay:null,_TL:x=>x,_swapLobbyBg(){},CHAR_VISUALS:[{idleVid:'warrior.mp4?v=1',poster:'warrior.jpg',job:'전사'},{portrait:'silvertail.png',job:'블레이드 댄서'}]});vm.runInContext(fn,ctx);return{nodes,update:ctx._updateCharDisplay}}
test('selected character retains ancestor art and updates identity',()=>{const {nodes:n,update}=setup();update({name:'실버',charIdx:1});assert.equal(n.lobbyBgImg.style.visibility,'');assert.equal(n.lobbyCharKeyart.src,'');assert.ok(!n.lobbyCharKeyart.classList.contains('show'));assert.equal(n.charDispTitle.textContent,'실버');assert.equal(n.charDispSub.textContent,'블레이드 댄서');assert.equal(n.enterGameBtn.disabled,false)});
test('selection clears dormant character video and its error callback',()=>{const {nodes:n,update}=setup();n.lobbyCharPreview.src='warrior.mp4';n.lobbyCharPreview.poster='warrior.jpg';n.lobbyCharPreview.onerror=()=>{throw Error('old video callback')};n.lobbyCharPreview.classList.add('show');n.lobbyCharKeyart.src='warrior.jpg';n.lobbyCharKeyart.classList.add('show');update({name:'전사',charIdx:0});assert.equal(n.lobbyCharPreview.src,'');assert.equal(n.lobbyCharPreview.poster,'');assert.equal(n.lobbyCharPreview.onerror,null);assert.equal(n.lobbyCharKeyart.src,'');assert.ok(!n.lobbyCharKeyart.classList.contains('show'));assert.ok(!n.lobbyCharPreview.classList.contains('show'))});
test('switching characters leaves no previous video fallback armed',()=>{const {nodes:n,update}=setup();update({name:'전사',charIdx:0});assert.equal(n.lobbyCharPreview.onerror,null);update({name:'실버',charIdx:1});assert.equal(n.lobbyCharPreview.onerror,null);assert.equal(n.lobbyCharKeyart.src,'');assert.equal(n.charDispTitle.textContent,'실버');assert.equal(n.charDispSub.textContent,'블레이드 댄서');assert.equal(n.lobbyBgImg.style.visibility,'')});
test('clearing selection removes selected media and restores the lobby scene',()=>{const {nodes:n,update}=setup();update({name:'실버',charIdx:1});update();assert.equal(n.lobbyBgImg.style.visibility,'');assert.equal(n.lobbyCharKeyart.src,'');assert.ok(!n.lobbyCharKeyart.classList.contains('show'));assert.equal(n.enterGameBtn.disabled,true)});
