#!/usr/bin/env python3
"""Add Phase 33d keys (intro steps + load tips) to 26 lang files"""
import re

lang_map = {
    'lang_zh.js':'ZH','lang_zht.js':'ZHT','lang_ja.js':'JA','lang_es.js':'ES',
    'lang_ru.js':'RU','lang_de.js':'DE','lang_ptbr.js':'PTBR','lang_fr.js':'FR',
    'lang_pl.js':'PL','lang_it.js':'IT','lang_uk.js':'UK','lang_tr.js':'TR',
    'lang_vi.js':'VI','lang_th.js':'TH','lang_id.js':'ID','lang_ar.js':'AR',
    'lang_sv.js':'SV','lang_da.js':'DA','lang_no.js':'NO','lang_fi.js':'FI',
    'lang_cs.js':'CS','lang_hu.js':'HU','lang_ro.js':'RO','lang_nl.js':'NL',
    'lang_el.js':'EL','lang_bg.js':'BG',
}

def find_main_end(txt, varname):
    pat = f'const {varname}=' + '{'
    start = txt.find(pat)
    if start == -1: return -1
    depth = 0; i = start + len(f'const {varname}=')
    while i < len(txt):
        if txt[i] == '{': depth += 1
        elif txt[i] == '}':
            depth -= 1
            if depth == 0: return i
        i += 1
    return -1

NEW_KEYS = {
'패링·보호막': {'zh':'格挡·护盾','zht':'格擋·護盾','ja':'パリィ・シールド','es':'Parada / Escudo','ru':'Парирование / Щит','de':'Parieren / Schild','ptbr':'Aparar / Escudo','fr':'Parade / Bouclier','pl':'Parowanie / Tarcza','it':'Parata / Scudo','uk':'Парирування / Щит','tr':'Savuşturma / Kalkan','vi':'Đỡ / Khiên','th':'ป้องกัน / โล่','id':'Parry / Perisai','ar':'صد / درع','sv':'Parering / Sköld','da':'Parering / Skjold','no':'Parering / Skjold','fi':'Torjunta / Kilpi','cs':'Parírování / Štít','hu':'Hárítás / Pajzs','ro':'Parare / Scut','nl':'Pareren / Schild','el':'Απόκρουση / Ασπίδα','bg':'Париране / Щит'},
'돌진 (적을 관통, 무적)': {'zh':'突进（穿透敌人，无敌）','zht':'突進（穿透敵人，無敵）','ja':'突進（敵貫通、無敵）','es':'Embestida (atraviesa enemigos, invencible)','ru':'Рывок (сквозь врагов, неуязвимость)','de':'Ansturm (durchbohrt Feinde, unverwundbar)','ptbr':'Investida (atravessa inimigos, invencível)','fr':'Charge (traverse les ennemis, invincible)','pl':'Szarża (przenika wrogów, nietykalność)','it':'Carica (attraversa nemici, invincibile)','uk':'Ривок (крізь ворогів, невразливість)','tr':'Atılma (düşmanları deler, yenilmez)','vi':'Lao tới (xuyên qua, bất tử)','th':'พุ่งชน (ทะลุศัตรู, อมตะ)','id':'Terjang (tembus musuh, kebal)','ar':'اندفاع (اختراق الأعداء، حصانة)','sv':'Rush (genomborrar fiender, osårbar)','da':'Stormløb (gennemborer fjender, usårbar)','no':'Stormløp (gjennomborer fiender, usårbar)','fi':'Rynnäkkö (lävistää viholliset, haavoittumaton)','cs':'Výpad (pronikne nepřáteli, nezranitelnost)','hu':'Roham (áthatol ellenségeken, sebezhetetlenség)','ro':'Asalt (străpunge inamicii, invincibil)','nl':'Bestorming (doorboort vijanden, onkwetsbaar)','el':'Εφόρμηση (διαπερνά εχθρούς, άτρωτος)','bg':'Нахлуване (пронизва врагове, неуязвим)'},
'대왕치기 (광역 기절)': {'zh':'巨力一击（范围眩晕）','zht':'巨力一擊（範圍暈眩）','ja':'大王撃（範囲スタン）','es':'Golpe Gigante (aturdimiento AoE)','ru':'Гигантский удар (АОЕ оглушение)','de':'Riesenschlag (Flächen-Betäubung)','ptbr':'Golpe Gigante (atordoamento AoE)','fr':'Frappe Géante (étourdissement de zone)','pl':'Potężne Uderzenie (ogłuszenie obszarowe)','it':'Colpo Gigante (stordimento ad area)','uk':'Гігантський удар (АОЕ оглушення)','tr':'Dev Darbe (alan sersemletme)','vi':'Đại Vương Chém (choáng diện rộng)','th':'ฟาดยักษ์ (สตัน AoE)','id':'Pukulan Raksasa (stun area)','ar':'ضربة عملاقة (صعق منطقة)','sv':'Jättesmäll (områdesbedövning)','da':'Kæmpesmæk (områdebedøvelse)','no':'Kjempesmell (områdebedøvelse)','fi':'Jättilyönti (aluetainnutus)','cs':'Obří úder (plošný omráčení)','hu':'Óriáscsapás (területi kábítás)','ro':'Lovitură Gigantică (asomare zonală)','nl':'Reuzenklap (gebiedsverdoving)','el':'Γιγαντοχτύπημα (ζάλη περιοχής)','bg':'Гигантски удар (зонов зашемет)'},
'가시덫 (슬로우+출혈)': {'zh':'荆棘陷阱（减速+出血）','zht':'荊棘陷阱（減速+出血）','ja':'棘の罠（スロウ+出血）','es':'Trampa de Púas (lento+sangrado)','ru':'Шипованная ловушка (замедление+кровотечение)','de':'Stachelfalle (Verlangsamung+Blutung)','ptbr':'Armadilha de Espinhos (lento+sangramento)','fr':'Piège épineux (ralentissement+saignement)','pl':'Kolczasta pułapka (spowolnienie+krwawienie)','it':'Trappola spinata (lento+sanguinamento)','uk':'Колюча пастка (уповільнення+кровотеча)','tr':'Dikenli tuzak (yavaşlatma+kanama)','vi':'Bẫy gai (chậm+chảy máu)','th':'กับดักหนาม (ช้า+เลือดไหล)','id':'Jebakan duri (lambat+pendarahan)','ar':'فخ شوكي (إبطاء+نزيف)','sv':'Taggfälla (långsam+blödning)','da':'Tornfælde (langsom+blødning)','no':'Tornfelle (sakte+blødning)','fi':'Piikkiloukku (hidastus+verenvuoto)','cs':'Trnová past (zpomalení+krvácení)','hu':'Tüskéscsapda (lassítás+vérzés)','ro':'Capcană cu spini (încetinire+sângerare)','nl':'Doornval (vertraging+bloeding)','el':'Αγκαθωτή παγίδα (επιβράδυνση+αιμορραγία)','bg':'Бодлив капан (забавяне+кървене)'},
'회복의 영역 (리젠 장판)': {'zh':'恢复领域（回复区域）','zht':'恢復領域（回復區域）','ja':'回復の領域（リジェンゾーン）','es':'Dominio Sagrado (zona regen)','ru':'Зона исцеления (регенерация)','de':'Heilzone (Regenerationsfeld)','ptbr':'Domínio Sagrado (zona regen)','fr':'Domaine sacré (zone de régén.)','pl':'Strefa leczenia (regen)','it':'Dominio sacro (zona regen)','uk':'Зона зцілення (регенерація)','tr':'Kutsal alan (regen bölgesi)','vi':'Vùng hồi phục (regen)','th':'โดเมนศักดิ์สิทธิ์ (ฟื้นฟู)','id':'Domain suci (zona regen)','ar':'مجال مقدس (منطقة تجديد)','sv':'Helig domän (regenzon)','da':'Hellig domæne (regenzone)','no':'Hellig domene (regensone)','fi':'Pyhä alue (regen)','cs':'Svatá doména (regen zóna)','hu':'Szent zóna (regen)','ro':'Domeniu sacru (zonă regen)','nl':'Heilig domein (regenzone)','el':'Ιερός τομέας (αναγέν.)','bg':'Свещен домейн (регенерация)'},
'얼음보주 (무적+빙결)': {'zh':'冰珠（无敌+冰冻）','zht':'冰珠（無敵+冰凍）','ja':'氷珠（無敵+凍結）','es':'Orbe de Hielo (invencible+congelar)','ru':'Ледяная сфера (неуязвимость+заморозка)','de':'Eiskugel (unverwundbar+einfrieren)','ptbr':'Orbe de Gelo (invencível+congelar)','fr':'Orbe de glace (invincible+gel)','pl':'Lodowa kula (nietykalność+zamrożenie)','it':'Sfera di ghiaccio (invincibile+congelamento)','uk':'Крижана куля (невразливість+заморозка)','tr':'Buz küresi (yenilmez+dondurma)','vi':'Cầu băng (bất tử+đông đá)','th':'ลูกแก้วน้ำแข็ง (อมตะ+แช่แข็ง)','id':'Bola es (kebal+beku)','ar':'كرة جليد (حصانة+تجميد)','sv':'Iskula (osårbar+frysning)','da':'Iskugle (usårbar+frysning)','no':'Iskule (usårbar+frysing)','fi':'Jääpallo (haavoittumaton+jäädytys)','cs':'Ledová koule (nezranitelnost+zmrazení)','hu':'Jéggömb (sebezhetetlenség+fagyasztás)','ro':'Sferă de gheață (invincibil+înghețare)','nl':'IJsbol (onkwetsbaar+bevriezing)','el':'Παγόσφαιρα (άτρωτος+πάγωμα)','bg':'Ледена сфера (неуязвим+замразяване)'},
'석궁 자동발사': {'zh':'弩自动射击','zht':'弩自動射擊','ja':'クロスボウ自動発射','es':'Ballesta automática','ru':'Авто арбалет','de':'Auto Armbrust','ptbr':'Besta automática','fr':'Arbalète automatique','pl':'Auto kusza','it':'Balestra automatica','uk':'Авто арбалет','tr':'Otomatik tatar','vi':'Nỏ tự động','th':'หน้าไม้อัตโนมัติ','id':'Panah otomatis','ar':'قوس آلي','sv':'Automatiskt armborst','da':'Automatisk armbrøst','no':'Automatisk armbrøst','fi':'Automaattinen jousiase','cs':'Automatická kuše','hu':'Automatikus számszeríj','ro':'Arbaletă automată','nl':'Automatisch kruisboog','el':'Αυτόματη βαλλίστρα','bg':'Автоматичен арбалет'},
'선택 스킬 슬롯': {'zh':'可选技能栏','zht':'可選技能欄','ja':'スキルスロット選択','es':'Ranuras de habilidad','ru':'Слоты навыков','de':'Skill-Slots','ptbr':'Slots de habilidade','fr':'Emplacements de compétences','pl':'Sloty umiejętności','it':'Slot abilità','uk':'Слоти навичок','tr':'Beceri yuvaları','vi':'Ô kỹ năng','th':'สล็อตสกิล','id':'Slot skill','ar':'خانات المهارات','sv':'Färdighetsplatser','da':'Evnepladser','no':'Evneplasser','fi':'Taitopaikat','cs':'Sloty dovedností','hu':'Képesség helyek','ro':'Sloturi abilități','nl':'Vaardigheidsslots','el':'Θέσεις ικανοτήτων','bg':'Слотове за умения'},
'(펫이 자동 수거)': {'zh':'（宠物自动拾取）','zht':'（寵物自動拾取）','ja':'（ペット自動回収）','es':'(mascota recoge auto)','ru':'(питомец собирает авто)','de':'(Haustier sammelt auto)','ptbr':'(pet coleta auto)','fr':'(familier collecte auto)','pl':'(zwierzak zbiera auto)','it':'(pet raccoglie auto)','uk':'(улюбленець збирає авто)','tr':'(evcil oto toplar)','vi':'(pet tự nhặt)','th':'(เพ็ทเก็บอัตโนมัติ)','id':'(pet otomatis ambil)','ar':'(الحيوان يجمع تلقائياً)','sv':'(husdjur samlar auto)','da':'(kæledyr samler auto)','no':'(kjæledyr samler auto)','fi':'(lemmikki kerää auto)','cs':'(mazlíček sbírá auto)','hu':'(kedvenc gyűjt auto)','ro':'(animalul colectează auto)','nl':'(huisdier verzamelt auto)','el':'(κατοικίδιο μαζεύει αυτ.)','bg':'(любимец събира авто)'},
'물약은 설정한 HP% 이하 시 자동 사용': {'zh':'药水在HP低于设定%时自动使用','zht':'藥水在HP低於設定%時自動使用','ja':'ポーションは設定HP%以下で自動使用','es':'Pociones se usan auto al bajar del HP% configurado','ru':'Зелья авто-используются при HP ниже заданного %','de':'Tränke werden bei HP unter eingestelltem % automatisch genutzt','ptbr':'Poções usam auto quando HP cai abaixo do % configurado','fr':'Les potions s\'utilisent auto sous le HP% défini','pl':'Mikstury auto-użycie poniżej ustawionego HP%','it':'Pozioni auto sotto HP% impostato','uk':'Зілля авто-використовуються при HP нижче заданого %','tr':'İksirler ayarlanan HP% altında otomatik kullanılır','vi':'Thuốc tự dùng khi HP dưới % đã đặt','th':'ยาใช้อัตโนมัติเมื่อ HP ต่ำกว่า % ที่ตั้ง','id':'Ramuan otomatis saat HP di bawah % yang diatur','ar':'الجرعات تستخدم تلقائياً عند انخفاض HP عن النسبة المحددة','sv':'Drycker auto-används när HP faller under inställd %','da':'Eliksirer auto-bruges når HP falder under indstillet %','no':'Eliksirer auto-brukes når HP faller under innstilt %','fi':'Juomat auto-käyttö kun HP laskee alle asetetun %','cs':'Lektvary se auto-použijí při HP pod nastaveným %','hu':'Bájitalok auto-használat HP beállított % alatt','ro':'Poțiunile se folosesc auto când HP scade sub % setat','nl':'Drankjes auto-gebruik als HP onder ingesteld % valt','el':'Τα φίλτρα χρησιμοποιούνται αυτ. κάτω από το HP%','bg':'Отварите се използват авто при HP под зададения %'},
'💡 Shift로 작살 돌진! 적을 관통하며 무적': {'zh':'💡 Shift突进！穿透敌人，无敌','zht':'💡 Shift突進！穿透敵人，無敵','ja':'💡 Shiftで突進！敵を貫通、無敵','es':'💡 ¡Shift para embestir! Atraviesa enemigos, invencible','ru':'💡 Shift для рывка! Сквозь врагов, неуязвимость','de':'💡 Shift zum Ansturm! Durch Feinde, unverwundbar','ptbr':'💡 Shift para investir! Atravessa inimigos, invencível','fr':'💡 Shift pour charger ! Traverse les ennemis, invincible','pl':'💡 Shift do szarży! Przenika wrogów, nietykalność','it':'💡 Shift per caricare! Attraversa nemici, invincibile','uk':'💡 Shift для ривка! Крізь ворогів, невразливість','tr':'💡 Shift ile atıl! Düşmanları deler, yenilmez','vi':'💡 Shift lao tới! Xuyên qua, bất tử','th':'💡 Shift พุ่งชน! ทะลุศัตรู, อมตะ','id':'💡 Shift terjang! Tembus musuh, kebal','ar':'💡 Shift للاندفاع! اختراق الأعداء، حصانة','sv':'💡 Shift för rush! Genom fiender, osårbar','da':'💡 Shift for stormløb! Gennem fjender, usårbar','no':'💡 Shift for stormløp! Gjennom fiender, usårbar','fi':'💡 Shift rynnäkköön! Lävistää viholliset, haavoittumaton','cs':'💡 Shift pro výpad! Pronikne nepřáteli, nezranitelnost','hu':'💡 Shift rohamhoz! Áthatol ellenségeken, sebezhetetlenség','ro':'💡 Shift pentru asalt! Străpunge inamicii, invincibil','nl':'💡 Shift voor bestorming! Door vijanden, onkwetsbaar','el':'💡 Shift για εφόρμηση! Διαπερνά εχθρούς, άτρωτος','bg':'💡 Shift за нахлуване! Пронизва врагове, неуязвим'},
'💡 Q로 보호막 발동 — 기본 흡수율 70%, 패링 성공 시 HP/ST/MP/기동게이지 회복': {'zh':'💡 Q发动护盾 — 基本吸收率70%，格挡成功恢复HP/ST/MP/机动槽','zht':'💡 Q發動護盾 — 基本吸收率70%，格擋成功恢復HP/ST/MP/機動槽','ja':'💡 Qでシールド発動 — 基本吸収率70%、パリィ成功時HP/ST/MP/機動ゲージ回復','es':'💡 Q para Escudo — absorción 70%, parada recupera HP/ST/MP/Carga','ru':'💡 Q для щита — поглощение 70%, парирование восстанавливает HP/ST/MP/Заряд','de':'💡 Q für Schild — 70% Absorption, Parieren heilt HP/ST/MP/Ladung','ptbr':'💡 Q para Escudo — absorção 70%, aparar recupera HP/ST/MP/Carga','fr':'💡 Q pour Bouclier — absorption 70%, parade récupère HP/ST/MP/Charge','pl':'💡 Q na Tarczę — absorpcja 70%, parowanie regeneruje HP/ST/MP/Ładunek','it':'💡 Q per Scudo — assorbimento 70%, parata recupera HP/ST/MP/Carica','uk':'💡 Q для щита — поглинання 70%, парирування відновлює HP/ST/MP/Заряд','tr':'💡 Q ile Kalkan — %70 emme, savuşturma HP/ST/MP/Şarj yeniler','vi':'💡 Q cho Khiên — hấp thụ 70%, đỡ hồi HP/ST/MP/Sạc','th':'💡 Q โล่ — ดูดซับ 70%, ป้องสำเร็จฟื้น HP/ST/MP/ชาร์จ','id':'💡 Q untuk Perisai — serap 70%, parry pulihkan HP/ST/MP/Isi','ar':'💡 Q للدرع — امتصاص 70%، الصد يستعيد HP/ST/MP/شحن','sv':'💡 Q för Sköld — 70% absorption, parering återhämtar HP/ST/MP/Laddning','da':'💡 Q for Skjold — 70% absorption, parering gendanner HP/ST/MP/Opladning','no':'💡 Q for Skjold — 70% absorpsjon, parering gjenoppretter HP/ST/MP/Ladning','fi':'💡 Q Kilvelle — 70% absorptio, torjunta palauttaa HP/ST/MP/Lataus','cs':'💡 Q pro Štít — 70% absorpce, parírování obnovuje HP/ST/MP/Nabití','hu':'💡 Q Pajzshoz — 70% elnyelés, hárítás visszatölti HP/ST/MP/Töltés','ro':'💡 Q pentru Scut — absorbție 70%, parare recuperează HP/ST/MP/Încărcare','nl':'💡 Q voor Schild — 70% absorptie, pareren herstelt HP/ST/MP/Lading','el':'💡 Q για Ασπίδα — 70% απορρόφηση, απόκρουση ανακτά HP/ST/MP/Φόρτιση','bg':'💡 Q за Щит — 70% абсорбция, париране възстановява HP/ST/MP/Заряд'},
'💡 속성 약점을 찌르면 데미지 2배!': {'zh':'💡 攻击属性弱点伤害翻倍！','zht':'💡 攻擊屬性弱點傷害翻倍！','ja':'💡 属性弱点を突けばダメージ2倍！','es':'💡 ¡Golpea debilidades elementales para 2x daño!','ru':'💡 Бей по стихийным слабостям — урон x2!','de':'💡 Element-Schwächen treffen = 2x Schaden!','ptbr':'💡 Acerte fraquezas elementais para 2x dano!','fr':'💡 Frappez les faiblesses élémentaires pour 2x dégâts !','pl':'💡 Trafiaj w słabości żywiołów — 2x obrażenia!','it':'💡 Colpisci le debolezze elementali per 2x danni!','uk':'💡 Вдар по стихійній слабкості — урон x2!','tr':'💡 Eleman zayıflıklarına vur — 2x hasar!','vi':'💡 Đánh vào điểm yếu thuộc tính — sát thương x2!','th':'💡 ตีจุดอ่อนธาตุ — ดาเมจ 2 เท่า!','id':'💡 Serang kelemahan elemen — 2x damage!','ar':'💡 اضرب نقاط الضعف العنصرية — ضرر مضاعف!','sv':'💡 Träffa elementsvaghet — 2x skada!','da':'💡 Ram elementsvaghed — 2x skade!','no':'💡 Treff elementsvakhet — 2x skade!','fi':'💡 Osu elementtiheikkouteen — 2x vahinko!','cs':'💡 Zasáhni elementální slabinu — 2x poškození!','hu':'💡 Találd el az elemi gyengeséget — 2x sebzés!','ro':'💡 Lovește slăbiciunea elementală — 2x daune!','nl':'💡 Raak elementzwakte — 2x schade!','el':'💡 Χτύπα στοιχειακή αδυναμία — 2x ζημιά!','bg':'💡 Удари елементалната слабост — 2x щети!'},
'💡 ESC로 설정 — 난이도, 자동물약 조절': {'zh':'💡 ESC设置 — 难度、自动药水调整','zht':'💡 ESC設定 — 難度、自動藥水調整','ja':'💡 ESCで設定 — 難易度、自動ポーション調整','es':'💡 ESC para ajustes — dificultad, pociones auto','ru':'💡 ESC для настроек — сложность, автозелья','de':'💡 ESC für Einstellungen — Schwierigkeit, Auto-Tränke','ptbr':'💡 ESC para configurações — dificuldade, poções auto','fr':'💡 ESC pour paramètres — difficulté, potions auto','pl':'💡 ESC ustawienia — trudność, auto-mikstury','it':'💡 ESC impostazioni — difficoltà, pozioni auto','uk':'💡 ESC налаштування — складність, автозілля','tr':'💡 ESC ayarlar — zorluk, otomatik iksirler','vi':'💡 ESC cài đặt — độ khó, thuốc tự động','th':'💡 ESC ตั้งค่า — ความยาก, ยาอัตโนมัติ','id':'💡 ESC pengaturan — kesulitan, ramuan otomatis','ar':'💡 ESC للإعدادات — الصعوبة، جرعات تلقائية','sv':'💡 ESC inställningar — svårighet, auto-drycker','da':'💡 ESC indstillinger — sværhed, auto-eliksirer','no':'💡 ESC innstillinger — vanskelighet, auto-eliksirer','fi':'💡 ESC asetukset — vaikeus, auto-juomat','cs':'💡 ESC nastavení — obtížnost, auto-lektvary','hu':'💡 ESC beállítások — nehézség, auto-bájitalok','ro':'💡 ESC setări — dificultate, poțiuni auto','nl':'💡 ESC instellingen — moeilijkheid, auto-drankjes','el':'💡 ESC ρυθμίσεις — δυσκολία, αυτ. φίλτρα','bg':'💡 ESC настройки — трудност, авто-отвари'},
'💡 대왕치기로 기절 회복 + 포이즈를 깎아 그로기 유발!': {'zh':'💡 巨力一击恢复眩晕 + 削减韧性触发虚弱！','zht':'💡 巨力一擊恢復暈眩 + 削減韌性觸發虛弱！','ja':'💡 大王撃でスタン回復 + ポイズ削りでグロッキー誘発！','es':'💡 ¡Golpe Gigante: recupera aturdimiento + rompe poise para groggy!','ru':'💡 Гигантский удар: снимает оглушение + ломает стойку для грогги!','de':'💡 Riesenschlag: Betäubung aufheben + Haltung brechen für Groggy!','ptbr':'💡 Golpe Gigante: recupera atordoamento + quebra poise para groggy!','fr':'💡 Frappe Géante: récupère étourdissement + brise la posture pour groggy !','pl':'💡 Potężne Uderzenie: zdejmuje ogłuszenie + łamie postawę na groggy!','it':'💡 Colpo Gigante: recupero stordimento + rompe postura per groggy!','uk':'💡 Гігантський удар: знімає оглушення + ламає стійкість для грогі!','tr':'💡 Dev Darbe: sersemlik kurtarma + duruş kırma ile groggy!','vi':'💡 Đại Vương Chém: hồi choáng + phá thế gây groggy!','th':'💡 ฟาดยักษ์: ฟื้นจากสตัน + ทำลายท่าทางเพื่อ Groggy!','id':'💡 Pukulan Raksasa: pulih stun + hancurkan poise untuk groggy!','ar':'💡 ضربة عملاقة: استعادة الصعق + كسر التوازن للدوخة!','sv':'💡 Jättesmäll: bedövning åter + kross hållning för groggy!','da':'💡 Kæmpesmæk: bedøvelse ophævet + bryd holdning for groggy!','no':'💡 Kjempesmell: bedøvelse opphevet + bryt holdning for groggy!','fi':'💡 Jättilyönti: tainnutuksesta toipuminen + asennon murtaminen groggyyn!','cs':'💡 Obří úder: obnovení z omráčení + zlomení postoje pro groggy!','hu':'💡 Óriáscsapás: kábultság feloldása + tartás megtörése groggyra!','ro':'💡 Lovitură Gigantică: recuperare asomare + sparge postura pentru groggy!','nl':'💡 Reuzenklap: verdoving herstellen + houding breken voor groggy!','el':'💡 Γιγαντοχτύπημα: ανάκτηση από ζάλη + σπάσιμο στάσης για groggy!','bg':'💡 Гигантски удар: възстановяване от зашемет + чупене на стойка за groggy!'},
'💡 그로기 상태에서 기본 데미지 1.5배': {'zh':'💡 虚弱状态下基础伤害1.5倍','zht':'💡 虛弱狀態下基礎傷害1.5倍','ja':'💡 グロッキー状態で基本ダメージ1.5倍','es':'💡 Estado groggy = 1.5x daño base','ru':'💡 В состоянии грогги базовый урон x1.5','de':'💡 Groggy-Zustand = 1.5x Grundschaden','ptbr':'💡 Estado groggy = 1.5x dano base','fr':'💡 État groggy = 1.5x dégâts de base','pl':'💡 Stan groggy = 1.5x obrażenia bazowe','it':'💡 Stato groggy = 1.5x danni base','uk':'💡 Стан грогі = 1.5x базовий урон','tr':'💡 Groggy durumu = 1.5x temel hasar','vi':'💡 Trạng thái groggy = 1.5x sát thương cơ bản','th':'💡 สถานะ Groggy = ดาเมจพื้นฐาน 1.5 เท่า','id':'💡 Status groggy = 1.5x damage dasar','ar':'💡 حالة الدوخة = 1.5x ضرر أساسي','sv':'💡 Groggy-tillstånd = 1.5x grundskada','da':'💡 Groggy-tilstand = 1.5x grundskade','no':'💡 Groggy-tilstand = 1.5x grunnsskade','fi':'💡 Groggy-tila = 1.5x perusvahinko','cs':'💡 Stav groggy = 1.5x základní poškození','hu':'💡 Groggy állapot = 1.5x alapsebzés','ro':'💡 Stare groggy = 1.5x daune de bază','nl':'💡 Groggy-status = 1.5x basisschade','el':'💡 Κατάσταση groggy = 1.5x βασική ζημιά','bg':'💡 Състояние groggy = 1.5x базови щети'},
'💡 탄막은 패링하면 되돌려 보낸다!': {'zh':'💡 弹幕格挡后反弹回去！','zht':'💡 彈幕格擋後反彈回去！','ja':'💡 弾幕はパリィで跳ね返す！','es':'💡 ¡Parar balas las devuelve!','ru':'💡 Парируй пули — отразятся назад!','de':'💡 Kugeln parieren = zurückschicken!','ptbr':'💡 Aparar balas as reflete de volta!','fr':'💡 Parer les projectiles les renvoie !','pl':'💡 Parowanie kul odbija je z powrotem!','it':'💡 Parare proiettili li rimanda indietro!','uk':'💡 Парируй кулі — відіб\'ються назад!','tr':'💡 Mermileri savuştur — geri döner!','vi':'💡 Đỡ đạn — bật ngược lại!','th':'💡 ป้องกระสุน — สะท้อนกลับ!','id':'💡 Parry peluru — memantul balik!','ar':'💡 صد الرصاص يعكسها!','sv':'💡 Parera kulor — studsar tillbaka!','da':'💡 Parer kugler — retur!','no':'💡 Parer kuler — tilbake!','fi':'💡 Torju luoteja — kimpoavat takaisin!','cs':'💡 Paríruj střely — odrazí se zpět!','hu':'💡 Hárítsd a lövedékeket — visszapattannak!','ro':'💡 Parează gloanțele — se întorc!','nl':'💡 Pareer kogels — kaatsen terug!','el':'💡 Απόκρουσε βλήματα — αναπηδούν πίσω!','bg':'💡 Парирай куршумите — отскачат обратно!'},
'💡 Ctrl 얼음보주 — 무적! 재입력으로 즉시 폭파': {'zh':'💡 Ctrl冰珠 — 无敌！再按即爆','zht':'💡 Ctrl冰珠 — 無敵！再按即爆','ja':'💡 Ctrl氷珠 — 無敵！再入力で即爆発','es':'💡 Ctrl Orbe Hielo — ¡invencible! Re-pulsa para romper','ru':'💡 Ctrl Ледяная сфера — неуязвимость! Повтор для взрыва','de':'💡 Ctrl Eiskugel — unverwundbar! Erneut drücken zum Zerbrechen','ptbr':'💡 Ctrl Orbe Gelo — invencível! Repressione para estilhaçar','fr':'💡 Ctrl Orbe Glace — invincible ! Rappuyez pour briser','pl':'💡 Ctrl Lodowa kula — nietykalność! Ponownie naciśnij, by rozbić','it':'💡 Ctrl Sfera Ghiaccio — invincibile! Ripremi per frantumare','uk':'💡 Ctrl Крижана куля — невразливість! Повтор для вибуху','tr':'💡 Ctrl Buz küresi — yenilmez! Tekrar bas, patlat','vi':'💡 Ctrl Cầu băng — bất tử! Nhấn lại để nổ','th':'💡 Ctrl ลูกแก้วน้ำแข็ง — อมตะ! กดอีกครั้งเพื่อระเบิด','id':'💡 Ctrl Bola es — kebal! Tekan lagi untuk pecahkan','ar':'💡 Ctrl كرة جليد — حصانة! اضغط مجدداً للتفجير','sv':'💡 Ctrl Iskula — osårbar! Tryck igen för att krossa','da':'💡 Ctrl Iskugle — usårbar! Tryk igen for at knuse','no':'💡 Ctrl Iskule — usårbar! Trykk igjen for å knuse','fi':'💡 Ctrl Jääpallo — haavoittumaton! Paina uudelleen murskataksesi','cs':'💡 Ctrl Ledová koule — nezranitelnost! Stiskni znovu pro rozbití','hu':'💡 Ctrl Jéggömb — sebezhetetlenség! Nyomd újra a szétzúzáshoz','ro':'💡 Ctrl Sferă de gheață — invincibil! Apasă din nou pentru a sparge','nl':'💡 Ctrl IJsbol — onkwetsbaar! Druk opnieuw om te breken','el':'💡 Ctrl Παγόσφαιρα — άτρωτος! Πατήστε ξανά για θρυμματισμό','bg':'💡 Ctrl Ледена сфера — неуязвим! Натиснете отново за разбиване'},
'💡 합체 스킬로 더 강한 공격을 만들어보세요': {'zh':'💡 合体技能创造更强的攻击','zht':'💡 合體技能創造更強的攻擊','ja':'💡 合体スキルでより強い攻撃を作ろう','es':'💡 ¡Fusiona habilidades para ataques más fuertes!','ru':'💡 Объединяй навыки для мощных атак!','de':'💡 Fusioniere Skills für stärkere Angriffe!','ptbr':'💡 Funda habilidades para ataques mais fortes!','fr':'💡 Fusionnez des compétences pour des attaques plus fortes !','pl':'💡 Łącz umiejętności w potężniejsze ataki!','it':'💡 Fondi abilità per attacchi più forti!','uk':'💡 Об\'єднуй навички для потужніших атак!','tr':'💡 Becerileri birleştir, güçlü saldırılar yarat!','vi':'💡 Kết hợp kỹ năng tạo đòn tấn công mạnh hơn!','th':'💡 รวมสกิลสร้างการโจมตีที่แรงกว่า!','id':'💡 Gabungkan skill untuk serangan lebih kuat!','ar':'💡 ادمج المهارات لهجمات أقوى!','sv':'💡 Smält samman färdigheter för starkare attacker!','da':'💡 Sammensmelt evner for stærkere angreb!','no':'💡 Smelt sammen evner for sterkere angrep!','fi':'💡 Yhdistä taitoja vahvempiin hyökkäyksiin!','cs':'💡 Slučte dovednosti pro silnější útoky!','hu':'💡 Olvaszd össze a képességeket erősebb támadásokért!','ro':'💡 Fuzionează abilitățile pentru atacuri mai puternice!','nl':'💡 Smelt vaardigheden samen voor sterkere aanvallen!','el':'💡 Συγχώνευσε ικανότητες για ισχυρότερες επιθέσεις!','bg':'💡 Слей умения за по-силни атаки!'},
'💡 엘리트 몬스터는 특수 능력을 가지고 있다': {'zh':'💡 精英怪物拥有特殊能力','zht':'💡 精英怪物擁有特殊能力','ja':'💡 エリートモンスターは特殊能力を持つ','es':'💡 Los monstruos élite tienen habilidades especiales','ru':'💡 Элитные монстры имеют особые способности','de':'💡 Elite-Monster haben Spezialfähigkeiten','ptbr':'💡 Monstros elite têm habilidades especiais','fr':'💡 Les monstres élites ont des capacités spéciales','pl':'💡 Elitarne potwory mają specjalne zdolności','it':'💡 I mostri élite hanno abilità speciali','uk':'💡 Елітні монстри мають особливі здібності','tr':'💡 Elit canavarların özel yetenekleri var','vi':'💡 Quái vật tinh anh có kỹ năng đặc biệt','th':'💡 มอนสเตอร์อีลิทมีความสามารถพิเศษ','id':'💡 Monster elite punya kemampuan khusus','ar':'💡 الوحوش النخبة لديها قدرات خاصة','sv':'💡 Elitmonster har specialförmågor','da':'💡 Elitemontre har særlige evner','no':'💡 Elitemonstre har spesielle evner','fi':'💡 Eliittihirviöillä on erikoiskykyjä','cs':'💡 Elitní příšery mají speciální schopnosti','hu':'💡 Az elitszörnyek különleges képességekkel bírnak','ro':'💡 Monștrii de elită au abilități speciale','nl':'💡 Elite monsters hebben speciale vaardigheden','el':'💡 Τα ελίτ τέρατα έχουν ειδικές ικανότητες','bg':'💡 Елитните чудовища имат специални умения'},
'💡 보스의 패턴을 읽고 패링 타이밍을 잡아라': {'zh':'💡 读懂Boss模式，把握格挡时机','zht':'💡 讀懂Boss模式，把握格擋時機','ja':'💡 ボスのパターンを読んでパリィタイミングを掴め','es':'💡 Lee los patrones del jefe, calcula tu parada','ru':'💡 Читай паттерны босса, лови тайминг парирования','de':'💡 Lies Boss-Muster, finde den Parier-Timing','ptbr':'💡 Leia padrões do chefe, acerte o timing de aparar','fr':'💡 Lisez les patterns du boss, trouvez le timing de parade','pl':'💡 Czytaj wzorce bossa, łap timing parowania','it':'💡 Leggi i pattern del boss, trova il timing di parata','uk':'💡 Читай патерни боса, лови тайминг парирування','tr':'💡 Patronun kalıplarını oku, savuşturma zamanını yakala','vi':'💡 Đọc pattern boss, bắt timing đỡ đòn','th':'💡 อ่านแพทเทิร์นบอส จับจังหวะป้องกัน','id':'💡 Baca pola bos, tangkap waktu parry','ar':'💡 اقرأ أنماط الزعيم، التقط توقيت الصد','sv':'💡 Läs bossens mönster, hitta pareringstiming','da':'💡 Læs bossens mønstre, find pareringstiming','no':'💡 Les bossens mønstre, finn pareringstiming','fi':'💡 Lue pomon kuviot, löydä torjuntatiming','cs':'💡 Čti vzory bosse, chyť timing parírování','hu':'💡 Olvasd a főnök mintáit, kapd el a hárítás időzítését','ro':'💡 Citește tiparele bossului, nimerește timing-ul de parare','nl':'💡 Lees bosspatronen, vind het pareer-timing','el':'💡 Διάβασε τα μοτίβα του boss, βρες τον χρόνο απόκρουσης','bg':'💡 Прочети моделите на боса, улови тайминга за париране'},
'💡 인벤토리(TAB)에서 장비를 비교하고 장착': {'zh':'💡 在背包(TAB)中比较并装备','zht':'💡 在背包(TAB)中比較並裝備','ja':'💡 インベントリ(TAB)で装備を比較・装着','es':'💡 TAB para inventario — compara y equipa','ru':'💡 Инвентарь(TAB) — сравнивай и надевай снаряжение','de':'💡 Inventar(TAB) — Ausrüstung vergleichen und anlegen','ptbr':'💡 Inventário(TAB) — compare e equipe','fr':'💡 Inventaire(TAB) — comparez et équipez','pl':'💡 Ekwipunek(TAB) — porównuj i zakładaj','it':'💡 Inventario(TAB) — confronta ed equipaggia','uk':'💡 Інвентар(TAB) — порівнюй та одягай','tr':'💡 Envanter(TAB) — karşılaştır ve kuşan','vi':'💡 Túi đồ(TAB) — so sánh và trang bị','th':'💡 กระเป๋า(TAB) — เปรียบเทียบและสวมใส่','id':'💡 Inventaris(TAB) — bandingkan dan kenakan','ar':'💡 المخزون(TAB) — قارن وارتدِ','sv':'💡 Inventarium(TAB) — jämför och utrusta','da':'💡 Inventar(TAB) — sammenlign og udstyr','no':'💡 Inventar(TAB) — sammenlign og utstyr','fi':'💡 Tavaraluettelo(TAB) — vertaa ja varusta','cs':'💡 Inventář(TAB) — porovnej a nasaď','hu':'💡 Felszerelés(TAB) — hasonlítsd össze és viseld','ro':'💡 Inventar(TAB) — compară și echipează','nl':'💡 Inventaris(TAB) — vergelijk en draag','el':'💡 Αποθήκη(TAB) — σύγκρινε κι εξόπλισε','bg':'💡 Инвентар(TAB) — сравни и екипирай'},
'💡 대장간에서 장비를 강화하고 분해하세요': {'zh':'💡 在铁匠铺强化和分解装备','zht':'💡 在鐵匠鋪強化和分解裝備','ja':'💡 鍛冶場で装備を強化・分解','es':'💡 Mejora y desmantela equipo en la forja','ru':'💡 Улучшай и разбирай снаряжение в кузнице','de':'💡 Verbessere und zerlege Ausrüstung in der Schmiede','ptbr':'💡 Melhore e desmonte equipamento na forja','fr':'💡 Améliorez et démontez l\'équipement à la forge','pl':'💡 Ulepszaj i rozkładaj ekwipunek w kuźni','it':'💡 Potenzia e smantella equipaggiamento alla forgia','uk':'💡 Покращуй та розбирай спорядження в кузні','tr':'💡 Demircide ekipman geliştir ve parçala','vi':'💡 Nâng cấp và phân hủy trang bị tại lò rèn','th':'💡 อัพเกรดและรื้อถอนอุปกรณ์ที่โรงตีเหล็ก','id':'💡 Tingkatkan dan bongkar perlengkapan di pandai besi','ar':'💡 طور وفكك المعدات في المسبك','sv':'💡 Uppgradera och demontera utrustning i smedjan','da':'💡 Opgrader og adskil udstyr i smedjen','no':'💡 Oppgrader og demonter utstyr i smia','fi':'💡 Paranna ja pura varusteita pajassa','cs':'💡 Vylepšuj a rozebírej vybavení v kovárně','hu':'💡 Fejleszd és bontsd a felszerelést a kovácsban','ro':'💡 Îmbunătățește și dezmembrează echipamentul la fierărie','nl':'💡 Verbeter en ontmantel uitrusting in de smederij','el':'💡 Αναβάθμισε κι αποσυναρμολόγησε εξοπλισμό στο σιδηρουργείο','bg':'💡 Подобри и разглоби екипировка в ковачницата'},
'💡 R키를 누르면 펫이 아이템을 자동으로 주워줍니다': {'zh':'💡 按R键宠物自动拾取物品','zht':'💡 按R鍵寵物自動拾取物品','ja':'💡 Rキーでペットがアイテムを自動回収','es':'💡 Pulsa R — tu mascota recoge items automáticamente','ru':'💡 Нажми R — питомец собирает предметы автоматически','de':'💡 Drücke R — dein Haustier sammelt Items automatisch','ptbr':'💡 Pressione R — seu pet coleta itens automaticamente','fr':'💡 Appuyez R — votre familier collecte les objets automatiquement','pl':'💡 Naciśnij R — zwierzak zbiera przedmioty automatycznie','it':'💡 Premi R — il tuo pet raccoglie oggetti automaticamente','uk':'💡 Натисни R — улюбленець збирає предмети автоматично','tr':'💡 R\'ye bas — evcil hayvanın eşyaları otomatik toplar','vi':'💡 Nhấn R — pet tự nhặt vật phẩm','th':'💡 กด R — เพ็ทเก็บไอเทมอัตโนมัติ','id':'💡 Tekan R — pet otomatis ambil item','ar':'💡 اضغط R — حيوانك يجمع الأغراض تلقائياً','sv':'💡 Tryck R — ditt husdjur samlar föremål automatiskt','da':'💡 Tryk R — dit kæledyr samler genstande automatisk','no':'💡 Trykk R — kjæledyret ditt samler gjenstander automatisk','fi':'💡 Paina R — lemmikkisi kerää esineet automaattisesti','cs':'💡 Stiskni R — mazlíček sbírá předměty automaticky','hu':'💡 Nyomd R-t — kedvenced automatikusan gyűjti a tárgyakat','ro':'💡 Apasă R — animalul tău colectează obiecte automat','nl':'💡 Druk R — je huisdier verzamelt items automatisch','el':'💡 Πάτα R — το κατοικίδιό σου μαζεύει αντικείμενα αυτόματα','bg':'💡 Натисни R — любимецът ти събира предмети автоматично'},
'💡 물약은 설정한 HP% 이하에서 자동 사용': {'zh':'💡 药水在HP低于设定%时自动使用','zht':'💡 藥水在HP低於設定%時自動使用','ja':'💡 ポーションは設定HP%以下で自動使用','es':'💡 Pociones se usan auto al bajar del HP% configurado','ru':'💡 Зелья авто-используются при HP ниже заданного %','de':'💡 Tränke werden bei HP unter eingestelltem % automatisch genutzt','ptbr':'💡 Poções usam auto quando HP cai abaixo do % configurado','fr':'💡 Les potions s\'utilisent auto sous le HP% défini','pl':'💡 Mikstury auto-użycie poniżej ustawionego HP%','it':'💡 Pozioni auto sotto HP% impostato','uk':'💡 Зілля авто-використовуються при HP нижче заданого %','tr':'💡 İksirler ayarlanan HP% altında otomatik kullanılır','vi':'💡 Thuốc tự dùng khi HP dưới % đã đặt','th':'💡 ยาใช้อัตโนมัติเมื่อ HP ต่ำกว่า % ที่ตั้ง','id':'💡 Ramuan otomatis saat HP di bawah % yang diatur','ar':'💡 الجرعات تستخدم تلقائياً عند انخفاض HP','sv':'💡 Drycker auto-används när HP faller under inställd %','da':'💡 Eliksirer auto-bruges når HP falder under indstillet %','no':'💡 Eliksirer auto-brukes når HP faller under innstilt %','fi':'💡 Juomat auto-käyttö kun HP laskee alle asetetun %','cs':'💡 Lektvary se auto-použijí při HP pod nastaveným %','hu':'💡 Bájitalok auto-használat HP beállított % alatt','ro':'💡 Poțiunile se folosesc auto când HP scade sub % setat','nl':'💡 Drankjes auto-gebruik als HP onder ingesteld % valt','el':'💡 Τα φίλτρα χρησιμοποιούνται αυτ. κάτω από το HP%','bg':'💡 Отварите се използват авто при HP под зададения %'},
'💡 집중 스킬(홀드)은 시전 중 기절 면역!': {'zh':'💡 集中技能（按住）施放时免疫眩晕！','zht':'💡 集中技能（按住）施放時免疫暈眩！','ja':'💡 集中スキル（ホールド）は詠唱中スタン免疫！','es':'💡 ¡Habilidades de canalización son inmunes al aturdimiento!','ru':'💡 Каналируемые навыки дают иммунитет к оглушению!','de':'💡 Kanal-Skills geben Betäubungsimmunität!','ptbr':'💡 Habilidades canalizadas dão imunidade a atordoamento!','fr':'💡 Les compétences canalisées donnent l\'immunité étourdissement !','pl':'💡 Umiejętności kanałowe dają odporność na ogłuszenie!','it':'💡 Le abilità canalizzate danno immunità stordimento!','uk':'💡 Навички каналізації дають імунітет до оглушення!','tr':'💡 Kanalize beceriler sersemletme bağışıklığı verir!','vi':'💡 Kỹ năng tập trung (giữ) miễn nhiễm choáng!','th':'💡 สกิลจดจ่อ (กดค้าง) ป้องกันสตัน!','id':'💡 Skill fokus (tahan) kebal stun!','ar':'💡 المهارات المستمرة تمنح حصانة من الصعق!','sv':'💡 Kanaliserade färdigheter ger bedövningsimmunitet!','da':'💡 Kanaliserede evner giver bedøvelsesimmunitet!','no':'💡 Kanaliserte evner gir bedøvelsesimmunitet!','fi':'💡 Kanavoivat taidot antavat tainnutusimmuniteetin!','cs':'💡 Kanalované dovednosti dávají imunitu vůči omráčení!','hu':'💡 Csatornázott képességek kábítás-immunitást adnak!','ro':'💡 Abilitățile canalizate oferă imunitate la asomare!','nl':'💡 Gekanaliseerde vaardigheden geven verdovingsimmuniteit!','el':'💡 Οι διοχετευόμενες ικανότητες δίνουν αντοχή σε ζάλη!','bg':'💡 Каналните умения дават имунитет към зашемет!'},
}

for fname, code_upper in sorted(lang_map.items()):
    code = code_upper.lower()
    varname = f'_{code_upper}'
    with open(fname, 'r', encoding='utf-8') as f:
        txt = f.read()
    main_end = find_main_end(txt, varname)
    if main_end < 0: continue
    entries = []
    for ko_key, lang_dict in NEW_KEYS.items():
        if f"'{ko_key}'" not in txt[:main_end]:
            val = lang_dict.get(code, '')
            if not val: continue
            val_esc = val.replace("'", "\\'")
            entries.append(f"'{ko_key}':'{val_esc}'")
    if not entries: continue
    insert_text = ',\n'.join(entries) + ','
    before = txt[:main_end].rstrip()
    if not before.endswith(','): before += ','
    txt = before + '\n' + insert_text + '\n' + txt[main_end:]
    with open(fname, 'w', encoding='utf-8', newline='\n') as f:
        f.write(txt)
    print(f'{fname}: +{len(entries)} keys')

print('Done!')
