const fs=require('fs');

const entries = {
  '닫기 [V]': {en:'Close [V]',de:'Schließen [V]',es:'Cerrar [V]',fr:'Fermer [V]',it:'Chiudi [V]',ptbr:'Fechar [V]',ru:'Закрыть [V]',ja:'閉じる [V]',zh:'关闭 [V]',zht:'關閉 [V]',ar:'إغلاق [V]',bg:'Затвори [V]',cs:'Zavřít [V]',da:'Luk [V]',el:'Κλείσιμο [V]',fi:'Sulje [V]',hu:'Bezárás [V]',id:'Tutup [V]',nl:'Sluiten [V]',no:'Lukk [V]',pl:'Zamknij [V]',ro:'Închide [V]',sv:'Stäng [V]',th:'ปิด [V]',tr:'Kapat [V]',uk:'Закрити [V]',vi:'Đóng [V]'},
  '닫기 [C]': {en:'Close [C]',de:'Schließen [C]',es:'Cerrar [C]',fr:'Fermer [C]',it:'Chiudi [C]',ptbr:'Fechar [C]',ru:'Закрыть [C]',ja:'閉じる [C]',zh:'关闭 [C]',zht:'關閉 [C]',ar:'إغلاق [C]',bg:'Затвори [C]',cs:'Zavřít [C]',da:'Luk [C]',el:'Κλείσιμο [C]',fi:'Sulje [C]',hu:'Bezárás [C]',id:'Tutup [C]',nl:'Sluiten [C]',no:'Lukk [C]',pl:'Zamknij [C]',ro:'Închide [C]',sv:'Stäng [C]',th:'ปิด [C]',tr:'Kapat [C]',uk:'Закрити [C]',vi:'Đóng [C]'},
  '\u26e7 시전...': {en:'\u26e7 Casting...',de:'\u26e7 Wirken...',es:'\u26e7 Lanzando...',fr:'\u26e7 Incantation...',it:'\u26e7 Lancio...',ptbr:'\u26e7 Conjurando...',ru:'\u26e7 Каст...',ja:'\u26e7 詠唱...',zh:'\u26e7 施法...',zht:'\u26e7 施法...',ar:'\u26e7 يلقي...',bg:'\u26e7 Магия...',cs:'\u26e7 Kouzlení...',da:'\u26e7 Kaster...',el:'\u26e7 Ξόρκι...',fi:'\u26e7 Loitsu...',hu:'\u26e7 Varázslás...',id:'\u26e7 Melafalkan...',nl:'\u26e7 Casten...',no:'\u26e7 Kaster...',pl:'\u26e7 Rzucanie...',ro:'\u26e7 Incantație...',sv:'\u26e7 Kastar...',th:'\u26e7 ร่าย...',tr:'\u26e7 Büyü...',uk:'\u26e7 Каст...',vi:'\u26e7 Thi Triển...'},
  // Also add the 19 that were in _EN but not pushed to lang files
  ' 스킬 해제': {en:' Skill Release',de:' Skill lösen',es:' Liberar habilidad',fr:' Relâcher compétence',it:' Rilascia abilità',ptbr:' Liberar habilidade',ru:' Отмена навыка',ja:' スキル解除',zh:' 技能解除',zht:' 技能解除',ar:' تحرير المهارة',bg:' Освобождаване',cs:' Uvolnit dovednost',da:' Frigør evne',el:' Απελευθέρωση',fi:' Vapauta taito',hu:' Képesség elengedése',id:' Lepas Skill',nl:' Vaardigheid lossen',no:' Slipp evne',pl:' Zwolnij umiejętność',ro:' Eliberare abilitate',sv:' Släpp förmåga',th:' ปล่อยสกิล',tr:' Yetenek Bırak',uk:' Відпустити навичку',vi:' Thả Kỹ Năng'},
  ' 자동 ON': {en:' Auto ON',de:' Auto AN',es:' Auto ON',fr:' Auto ON',it:' Auto ON',ptbr:' Auto ON',ru:' Авто ВКЛ',ja:' 自動 ON',zh:' 自动 ON',zht:' 自動 ON',ar:' تلقائي ON',bg:' Авто ВКЛ',cs:' Auto ZAP',da:' Auto TIL',el:' Αυτόματο ON',fi:' Auto PÄÄL',hu:' Automatikus BE',id:' Otomatis ON',nl:' Auto AAN',no:' Auto PÅ',pl:' Auto WŁ',ro:' Auto ON',sv:' Auto PÅ',th:' อัตโนมัติ เปิด',tr:' Otomatik AÇIK',uk:' Авто УВІМК',vi:' Tự Động BẬT'},
  ' 자동 OFF': {en:' Auto OFF',de:' Auto AUS',es:' Auto OFF',fr:' Auto OFF',it:' Auto OFF',ptbr:' Auto OFF',ru:' Авто ВЫКЛ',ja:' 自動 OFF',zh:' 自动 OFF',zht:' 自動 OFF',ar:' تلقائي OFF',bg:' Авто ИЗКЛ',cs:' Auto VYP',da:' Auto FRA',el:' Αυτόματο OFF',fi:' Auto POIS',hu:' Automatikus KI',id:' Otomatis OFF',nl:' Auto UIT',no:' Auto AV',pl:' Auto WYŁ',ro:' Auto OFF',sv:' Auto AV',th:' อัตโนมัติ ปิด',tr:' Otomatik KAPALI',uk:' Авто ВИМК',vi:' Tự Động TẮT'},
  '☠중독!': {en:'☠Poison!',de:'☠Gift!',es:'☠Veneno!',fr:'☠Poison!',it:'☠Veleno!',ptbr:'☠Veneno!',ru:'☠Отравление!',ja:'☠中毒!',zh:'☠中毒!',zht:'☠中毒!',ar:'☠سم!',bg:'☠Отрова!',cs:'☠Jed!',da:'☠Gift!',el:'☠Δηλητήριο!',fi:'☠Myrkky!',hu:'☠Méreg!',id:'☠Racun!',nl:'☠Gif!',no:'☠Gift!',pl:'☠Trucizna!',ro:'☠Otravă!',sv:'☠Gift!',th:'☠พิษ!',tr:'☠Zehir!',uk:'☠Отрута!',vi:'☠Độc!'},
  '🚀 미사일!': {en:'🚀 Missile!',de:'🚀 Rakete!',es:'🚀 Misil!',fr:'🚀 Missile!',it:'🚀 Missile!',ptbr:'🚀 Míssil!',ru:'🚀 Ракета!',ja:'🚀 ミサイル!',zh:'🚀 导弹!',zht:'🚀 飛彈!',ar:'🚀 صاروخ!',bg:'🚀 Ракета!',cs:'🚀 Raketa!',da:'🚀 Missil!',el:'🚀 Πύραυλος!',fi:'🚀 Ohjus!',hu:'🚀 Rakéta!',id:'🚀 Misil!',nl:'🚀 Raket!',no:'🚀 Missil!',pl:'🚀 Pocisk!',ro:'🚀 Rachetă!',sv:'🚀 Missil!',th:'🚀 ขีปนาวุธ!',tr:'🚀 Füze!',uk:'🚀 Ракета!',vi:'🚀 Tên Lửa!'},
  '🔥분노+': {en:'🔥Rage+',de:'🔥Wut+',es:'🔥Furia+',fr:'🔥Rage+',it:'🔥Furia+',ptbr:'🔥Fúria+',ru:'🔥Ярость+',ja:'🔥激怒+',zh:'🔥狂怒+',zht:'🔥狂怒+',ar:'🔥غضب+',bg:'🔥Ярост+',cs:'🔥Zuřivost+',da:'🔥Raseri+',el:'🔥Οργή+',fi:'🔥Raivo+',hu:'🔥Düh+',id:'🔥Amukan+',nl:'🔥Woede+',no:'🔥Raseri+',pl:'🔥Furia+',ro:'🔥Furie+',sv:'🔥Raseri+',th:'🔥คลั่ง+',tr:'🔥Öfke+',uk:'🔥Лють+',vi:'🔥Cuồng Nộ+'},
  '🔥분노 ': {en:'🔥Rage ',de:'🔥Wut ',es:'🔥Furia ',fr:'🔥Rage ',it:'🔥Furia ',ptbr:'🔥Fúria ',ru:'🔥Ярость ',ja:'🔥激怒 ',zh:'🔥狂怒 ',zht:'🔥狂怒 ',ar:'🔥غضب ',bg:'🔥Ярост ',cs:'🔥Zuřivost ',da:'🔥Raseri ',el:'🔥Οργή ',fi:'🔥Raivo ',hu:'🔥Düh ',id:'🔥Amukan ',nl:'🔥Woede ',no:'🔥Raseri ',pl:'🔥Furia ',ro:'🔥Furie ',sv:'🔥Raseri ',th:'🔥คลั่ง ',tr:'🔥Öfke ',uk:'🔥Лють ',vi:'🔥Cuồng Nộ '},
  '💀 ': {en:'💀 ',de:'💀 ',es:'💀 ',fr:'💀 ',it:'💀 ',ptbr:'💀 ',ru:'💀 ',ja:'💀 ',zh:'💀 ',zht:'💀 ',ar:'💀 ',bg:'💀 ',cs:'💀 ',da:'💀 ',el:'💀 ',fi:'💀 ',hu:'💀 ',id:'💀 ',nl:'💀 ',no:'💀 ',pl:'💀 ',ro:'💀 ',sv:'💀 ',th:'💀 ',tr:'💀 ',uk:'💀 ',vi:'💀 '},
  '🔥부활!': {en:'🔥Revive!',de:'🔥Wiederbelebung!',es:'🔥Revivir!',fr:'🔥Résurrection!',it:'🔥Resurrezione!',ptbr:'🔥Reviver!',ru:'🔥Воскрешение!',ja:'🔥復活!',zh:'🔥复活!',zht:'🔥復活!',ar:'🔥إحياء!',bg:'🔥Възкресяване!',cs:'🔥Vzkříšení!',da:'🔥Genoplivning!',el:'🔥Αναβίωση!',fi:'🔥Herätys!',hu:'🔥Feltámadás!',id:'🔥Kebangkitan!',nl:'🔥Herleving!',no:'🔥Gjenoppliving!',pl:'🔥Wskrzeszenie!',ro:'🔥Înviere!',sv:'🔥Återupplivning!',th:'🔥ฟื้นคืน!',tr:'🔥Diriliş!',uk:'🔥Воскресіння!',vi:'🔥Hồi Sinh!'},
  '✟ 신의영역!': {en:'✟ Divine Domain!',de:'✟ Göttliche Domäne!',es:'✟ Dominio divino!',fr:'✟ Domaine divin!',it:'✟ Dominio divino!',ptbr:'✟ Domínio divino!',ru:'✟ Божественная область!',ja:'✟ 神の領域!',zh:'✟ 神之领域!',zht:'✟ 神之領域!',ar:'✟ مجال إلهي!',bg:'✟ Божествен домейн!',cs:'✟ Božská doména!',da:'✟ Guddommeligt domæne!',el:'✟ Θεϊκό πεδίο!',fi:'✟ Jumalallinen alue!',hu:'✟ Isteni tartomány!',id:'✟ Domain Ilahi!',nl:'✟ Goddelijk domein!',no:'✟ Guddommelig domene!',pl:'✟ Boska domena!',ro:'✟ Domeniu divin!',sv:'✟ Gudomlig domän!',th:'✟ อาณาจักรศักดิ์สิทธิ์!',tr:'✟ İlahi Alan!',uk:'✟ Божественна область!',vi:'✟ Lĩnh Vực Thần Thánh!'},
  '🎮 게임패드 버튼 설정': {en:'🎮 Gamepad Button Config',de:'🎮 Gamepad-Tasten',es:'🎮 Config. botones mando',fr:'🎮 Config manette',it:'🎮 Config pulsanti gamepad',ptbr:'🎮 Config botões controle',ru:'🎮 Настройка геймпада',ja:'🎮 ゲームパッドボタン設定',zh:'🎮 手柄按键设置',zht:'🎮 手把按鍵設定',ar:'🎮 إعدادات أزرار اللعبة',bg:'🎮 Настройки на бутоните',cs:'🎮 Nastavení tlačítek',da:'🎮 Gamepad-knapindstillinger',el:'🎮 Ρύθμιση κουμπιών',fi:'🎮 Ohjainpainikkeet',hu:'🎮 Gamepad gombok',id:'🎮 Pengaturan Tombol Gamepad',nl:'🎮 Gamepad-knoppen',no:'🎮 Gamepad-knappinnstillinger',pl:'🎮 Ustawienia przycisków pada',ro:'🎮 Configurare butoane gamepad',sv:'🎮 Spelkontrollknappar',th:'🎮 ตั้งค่าปุ่มเกมแพด',tr:'🎮 Gamepad Düğme Ayarı',uk:'🎮 Налаштування кнопок геймпада',vi:'🎮 Cài Đặt Nút Tay Cầm'},
  'B슬롯 스킬': {en:'B-Slot Skill',de:'B-Slot Fähigkeit',es:'Habilidad ranura B',fr:'Compétence slot B',it:'Abilità slot B',ptbr:'Habilidade slot B',ru:'Навык слота B',ja:'Bスロットスキル',zh:'B槽技能',zht:'B槽技能',ar:'مهارة فتحة B',bg:'B-слот умение',cs:'Dovednost B-slotu',da:'B-slot evne',el:'Ικανότητα B-slot',fi:'B-paikan taito',hu:'B-hely képesség',id:'Skill Slot B',nl:'B-slot vaardigheid',no:'B-plass evne',pl:'Umiejętność B-slotu',ro:'Abilitate slot B',sv:'B-plats förmåga',th:'สกิลช่อง B',tr:'B-Slot Yetenek',uk:'Навичка B-слоту',vi:'Kỹ Năng Ô B'},
  '우클릭 스킬': {en:'R-Click Skill',de:'Rechtsklick-Fähigkeit',es:'Habilidad clic derecho',fr:'Compétence clic droit',it:'Abilità clic destro',ptbr:'Habilidade clique direito',ru:'Навык ПКМ',ja:'右クリックスキル',zh:'右键技能',zht:'右鍵技能',ar:'مهارة النقر الأيمن',bg:'Умение десен клик',cs:'Dovednost pravého kliku',da:'Højreklik-evne',el:'Ικανότητα δεξιού κλικ',fi:'Oikeaklikkaus-taito',hu:'Jobb klikk képesség',id:'Skill Klik Kanan',nl:'Rechtsklik-vaardigheid',no:'Høyreklikk-evne',pl:'Umiejętność prawego przycisku',ro:'Abilitate clic dreapta',sv:'Högerklick-förmåga',th:'สกิลคลิกขวา',tr:'Sağ Tık Yetenek',uk:'Навичка ПКМ',vi:'Kỹ Năng Chuột Phải'},
  '패링': {en:'Parry',de:'Parade',es:'Parada',fr:'Parade',it:'Parata',ptbr:'Aparar',ru:'Парирование',ja:'パリィ',zh:'弹反',zht:'彈反',ar:'صد',bg:'Парирне',cs:'Parírování',da:'Parering',el:'Απόκρουση',fi:'Torjunta',hu:'Hárítás',id:'Parry',nl:'Pareren',no:'Parering',pl:'Parowanie',ro:'Parare',sv:'Parering',th:'แพร์รี่',tr:'Savuşturma',uk:'Парирування',vi:'Đỡ Đòn'},
  '돌진/작살': {en:'Dash/Harpoon',de:'Ansturm/Harpune',es:'Embestida/Arpón',fr:'Charge/Harpon',it:'Carica/Arpione',ptbr:'Investida/Arpão',ru:'Рывок/Гарпун',ja:'突進/銛',zh:'突进/鱼叉',zht:'突進/魚叉',ar:'اندفاع/حربة',bg:'Пробив/Харпун',cs:'Výpad/Harpuna',da:'Fremstød/Harpun',el:'Εφόρμηση/Καμάκι',fi:'Syöksy/Harppuuna',hu:'Roham/Szigony',id:'Seruduk/Tombak',nl:'Bestorming/Harpoen',no:'Fremstøt/Harpun',pl:'Szarża/Harpun',ro:'Asalt/Harpon',sv:'Framstöt/Harpun',th:'พุ่ง/ฉมวก',tr:'Atılma/Zıpkın',uk:'Ривок/Гарпун',vi:'Lao/Lao Thương'},
  '줍기': {en:'Pick Up',de:'Aufheben',es:'Recoger',fr:'Ramasser',it:'Raccogliere',ptbr:'Pegar',ru:'Подобрать',ja:'拾う',zh:'拾取',zht:'拾取',ar:'التقاط',bg:'Вземи',cs:'Sebrat',da:'Saml op',el:'Μάζεψε',fi:'Poimi',hu:'Felvétel',id:'Ambil',nl:'Oprapen',no:'Plukk opp',pl:'Podnieś',ro:'Ridică',sv:'Plocka upp',th:'เก็บ',tr:'Topla',uk:'Підібрати',vi:'Nhặt'},
  '고정': {en:'Lock',de:'Fixieren',es:'Fijar',fr:'Verrouiller',it:'Bloccare',ptbr:'Fixar',ru:'Закрепить',ja:'固定',zh:'锁定',zht:'鎖定',ar:'تثبيت',bg:'Заключи',cs:'Zamknout',da:'Lås',el:'Κλείδωμα',fi:'Lukitse',hu:'Rögzítés',id:'Kunci',nl:'Vergrendelen',no:'Lås',pl:'Zablokuj',ro:'Blochează',sv:'Lås',th:'ล็อค',tr:'Kilitle',uk:'Закріпити',vi:'Khóa'},
  '⟨ 키 입력... ⟩': {en:'⟨ Press Key... ⟩',de:'⟨ Taste drücken... ⟩',es:'⟨ Pulsa tecla... ⟩',fr:'⟨ Appuyer... ⟩',it:'⟨ Premi tasto... ⟩',ptbr:'⟨ Pressione tecla... ⟩',ru:'⟨ Нажмите клавишу... ⟩',ja:'⟨ キーを押す... ⟩',zh:'⟨ 按键... ⟩',zht:'⟨ 按鍵... ⟩',ar:'⟨ اضغط مفتاح... ⟩',bg:'⟨ Натисни клавиш... ⟩',cs:'⟨ Stiskni klávesu... ⟩',da:'⟨ Tryk tast... ⟩',el:'⟨ Πατήστε πλήκτρο... ⟩',fi:'⟨ Paina näppäintä... ⟩',hu:'⟨ Nyomj gombot... ⟩',id:'⟨ Tekan tombol... ⟩',nl:'⟨ Druk toets... ⟩',no:'⟨ Trykk tast... ⟩',pl:'⟨ Naciśnij klawisz... ⟩',ro:'⟨ Apasă tasta... ⟩',sv:'⟨ Tryck tangent... ⟩',th:'⟨ กดปุ่ม... ⟩',tr:'⟨ Tuşa bas... ⟩',uk:'⟨ Натисніть клавішу... ⟩',vi:'⟨ Nhấn phím... ⟩'},
  '패드 키 초기화': {en:'Reset Pad Keys',de:'Pad-Tasten zurücksetzen',es:'Restablecer botones',fr:'Réinitialiser manette',it:'Reset tasti pad',ptbr:'Resetar botões',ru:'Сброс кнопок геймпада',ja:'パッドキーリセット',zh:'重置手柄按键',zht:'重置手把按鍵',ar:'إعادة تعيين أزرار اللعبة',bg:'Нулиране на бутоните',cs:'Resetovat tlačítka',da:'Nulstil gamepad-knapper',el:'Επαναφορά κουμπιών',fi:'Nollaa ohjainpainikkeet',hu:'Gamepad gombok visszaállítása',id:'Reset Tombol Gamepad',nl:'Gamepad-knoppen resetten',no:'Tilbakestill gamepad-knapper',pl:'Resetuj przyciski pada',ro:'Resetare butoane gamepad',sv:'Återställ spelkontrollknappar',th:'รีเซ็ตปุ่มเกมแพด',tr:'Gamepad Düğmelerini Sıfırla',uk:'Скинути кнопки геймпада',vi:'Đặt Lại Phím Tay Cầm'},
  '패드 키 초기화 완료': {en:'Pad Keys Reset Done',de:'Pad-Tasten zurückgesetzt',es:'Botones restablecidos',fr:'Manette réinitialisée',it:'Tasti pad resettati',ptbr:'Botões resetados',ru:'Кнопки геймпада сброшены',ja:'パッドキーリセット完了',zh:'手柄按键已重置',zht:'手把按鍵已重置',ar:'تم إعادة تعيين الأزرار',bg:'Бутоните са нулирани',cs:'Tlačítka resetována',da:'Gamepad-knapper nulstillet',el:'Κουμπιά επαναφέρθηκαν',fi:'Ohjainpainikkeet nollattu',hu:'Gamepad gombok visszaállítva',id:'Tombol Gamepad Direset',nl:'Gamepad-knoppen gereset',no:'Gamepad-knapper tilbakestilt',pl:'Przyciski pada zresetowane',ro:'Butoane gamepad resetate',sv:'Spelkontrollknappar återställda',th:'รีเซ็ตปุ่มเกมแพดเสร็จ',tr:'Gamepad Düğmeleri Sıfırlandı',uk:'Кнопки геймпада скинуто',vi:'Đã Đặt Lại Phím Tay Cầm'},
  '다음 구역': {en:'Next Zone',de:'Nächste Zone',es:'Siguiente zona',fr:'Zone suivante',it:'Zona successiva',ptbr:'Próxima zona',ru:'Следующая зона',ja:'次のエリア',zh:'下一区域',zht:'下一區域',ar:'المنطقة التالية',bg:'Следваща зона',cs:'Další zóna',da:'Næste zone',el:'Επόμενη ζώνη',fi:'Seuraava alue',hu:'Következő zóna',id:'Zona Berikutnya',nl:'Volgende zone',no:'Neste sone',pl:'Następna strefa',ro:'Zona următoare',sv:'Nästa zon',th:'โซนถัดไป',tr:'Sonraki Bölge',uk:'Наступна зона',vi:'Khu Vực Tiếp'},
  '쓰러짐...': {en:'Falling...',de:'Zusammenbruch...',es:'Cayendo...',fr:'Chute...',it:'Cadendo...',ptbr:'Caindo...',ru:'Падение...',ja:'倒れる...',zh:'倒下...',zht:'倒下...',ar:'سقوط...',bg:'Пада...',cs:'Padá...',da:'Falder...',el:'Πέφτει...',fi:'Kaatuu...',hu:'Elesik...',id:'Jatuh...',nl:'Valt...',no:'Faller...',pl:'Pada...',ro:'Cade...',sv:'Faller...',th:'ล้ม...',tr:'Düşüyor...',uk:'Падає...',vi:'Ngã...'}
};

const langMap = {
  'lang_ar.js':'ar','lang_bg.js':'bg','lang_cs.js':'cs','lang_da.js':'da',
  'lang_de.js':'de','lang_el.js':'el','lang_es.js':'es','lang_fi.js':'fi',
  'lang_fr.js':'fr','lang_hu.js':'hu','lang_id.js':'id','lang_it.js':'it',
  'lang_ja.js':'ja','lang_nl.js':'nl','lang_no.js':'no','lang_pl.js':'pl',
  'lang_ptbr.js':'ptbr','lang_ro.js':'ro','lang_ru.js':'ru','lang_sv.js':'sv',
  'lang_th.js':'th','lang_tr.js':'tr','lang_uk.js':'uk','lang_vi.js':'vi',
  'lang_zh.js':'zh','lang_zht.js':'zht'
};

let totalAdded = 0;
for(const [file, lang] of Object.entries(langMap)){
  let content = fs.readFileSync(file,'utf8');
  let added = 0;
  const lastBrace = content.lastIndexOf('};');
  let insert = '';
  for(const [ko, trans] of Object.entries(entries)){
    if(!content.includes("'"+ko+"'")){
      insert += "'"+ko+"':'"+trans[lang]+"',\n";
      added++;
    }
  }
  if(added>0){
    content = content.slice(0,lastBrace) + insert + content.slice(lastBrace);
    fs.writeFileSync(file, content, 'utf8');
    totalAdded += added;
    console.log(file+': +'+added+' entries');
  } else {
    console.log(file+': already complete');
  }
}
console.log('Total added: '+totalAdded);
