// Phase 37: SKILL_LIST desc (51) + SKILL_REC_PATH desc (17) → 26 lang files
'use strict';
const fs = require('fs');

// [ko, zh, ja, en]
// zht derived from zh via toTrad(); es/fr/de/ptbr/it/id/17others use en
const P = [
// ── SKILL_REC_PATH desc (17) ──
['핵심 광역기 — 먼저 배워서 정리력 확보',
 '核心范围技——优先学习提升清场效率',
 'コアAoE——先に習得して雑魚処理能力を確保',
 'Core AoE — learn first for mob clearing'],
['악의 사냥 + 보호자 → 합체: 칼날 해방',
 '恶意追猎+守护者→融合：刃之解放',
 '悪意の狩り+守護者→融合：刃の解放',
 'Malice Hunt + Guardian → Fuse: Blade Liberation'],
['폭독혈 추가 → 합체: 독혈 해방 (칼날+독)',
 '毒血爆发追加→融合：毒血解放(刃+毒)',
 '毒血爆発追加→融合：毒血解放(刃+毒)',
 'Plague Burst → Fuse: Plague Liberation (blade+poison)'],
['충돌+화염 → 합체: 사슬기동 (무적이동 핵심)',
 '冲撞+火焰→融合：锁链突进(无敌移动核心)',
 '衝突+炎→融合：鎖機動(無敵移動コア)',
 'Impact+Flame → Fuse: Chain Breach (invincible dash core)'],
['사슬 체인 확장 → 기동:파쇄/기동:전폭',
 '锁链扩展→机动：粉碎/机动：雷击',
 '鎖チェーン拡張→機動：粉砕/機動：雷爆',
 'Chain expansion → Slam/Thunder combos'],
['필살기 1개 선택! 신성폭발(넉백) / 블랙(흡인) / 용암(화상) / 처형(보스킬)',
 '必杀技选1！神圣爆炸(击退)/黑星(吸引)/熔岩(燃烧)/处决(BOSS杀)',
 '必殺技1個選択！聖爆発(ノックバック)/ブラック(吸引)/溶岩(火傷)/処刑(ボスキル)',
 'Pick 1 ultimate! Holy Blast(knockback) / Black Star(pull) / Lava(burn) / Execution(boss kill)'],
['멸살광선+만화방창+원소추적탄+전격이동 → 합체: 추적빔',
 '灭杀光线+弹幕+元素追踪弹+闪电移动→融合：追踪光束',
 '滅殺光線+弾幕+元素追跡弾+電撃移動→融合：追跡ビーム',
 'Omni Beam+Barrage+Elem Missile+Blink → Fuse: Tracking Beam'],
['회전참+기폭+대왕치기 → 합체: 지진폭풍',
 '旋转斩+起爆+大王锤→融合：地震风暴',
 '回転斬+起爆+大王打ち→融合：地震嵐',
 'Whirlwind+Detonate+Giant Slam → Fuse: Slam Storm'],
['칼등치기 + 칼등날개 → 합체: 처내기 강화',
 '盾拍+盾翼→融合：反拍强化',
 '盾払い+盾翼→融合：迎撃強化',
 'Blade Parry + Shield Wing → Fuse: Parry Enhanced'],
['해골무덤 + 악의폭풍 → 합체: 해골번개',
 '骸骨墓+恶意风暴→融合：骸骨闪电',
 '骸骨墓+悪意嵐→融合：骸骨雷',
 'Bone Wall + Malice Storm → Fuse: Bone Lightning'],
['폭풍소환 + 얼음보주 → 합체: 얼음폭풍',
 '暴风召唤+冰宝珠→融합：冰暴风',
 '嵐召喚+氷宝珠→融合：氷嵐',
 'Malice Mortar + Ice Orb → Fuse: Ice Mortar'],
['유령화 이동 + 전기 폭발',
 '幽灵化移动+电气爆炸',
 '幽霊化移動+電気爆発',
 'Ghost phase movement + electric burst'],
['회복 + 구속 → 합체: 결계의 영역',
 '回复+束缚→融合：结界领域',
 '回復+束縛→融合：結界領域',
 'Recovery + Prison → Fuse: Ward Domain'],
['지진폭풍+추적암전 → 6단합체: 폭풍빔',
 '地震风暴+追踪暗电→6段融합：风暴光束',
 '地震嵐+追跡暗転→6段融合：嵐ビーム',
 'Slam Storm → 6-Fuse: Storm Beam'],
['아이스스톰 추가 → 합체: 신성빙결',
 '冰风暴追加→融合：神圣冰结',
 'アイスストーム追加→融合：聖なる氷結',
 'Ice Storm → Fuse: Holy Ice'],
['암흑기둥 + 가시덫 → 합체: 기둥가시. 대왕치기2는 기둥강타/지옥강타용',
 '暗柱+尖刺陷阱→融합：柱刺。大王锤2用于柱锤/地狱锤',
 '暗転柱+スパイクトラップ→融合：柱スパイク。大王打ち2は柱打ち/地獄打ち用',
 'Dark Pillar + Spike Trap → Fuse: Pillar Spike. Giant Slam 2 for Pillar Slam/Inferno Slam'],
['기동칼날개 추가 → 5단합체: 기동:칼날개',
 '机动刃翼追加→5段融합：机动：刃翼',
 '機動刃翼追加→5段融合：機動：刃翼',
 'Chain Bladewing → 5-Fuse: Maneuver:Bladewing'],

// ── SKILL_LIST desc (51) ──
['STR 스케일. 3회 충전 + Lv3마다 사거리 1단계↑(최대4단). 이동 중 무적, 통과 적에 데미지+그로기 (쿨 5초)',
 'STR比例。3次蓄力，每Lv3射程↑1阶(最大4阶)。移动中无敌，穿过敌人时伤害+击晕 (CD 5秒)',
 'STRスケール。3回チャージ+Lv3ごとに射程1段階↑(最大4段)。移動中無敵、通過した敵にダメ+グロッキー (CD 5秒)',
 'STR scale. 3 stocks + range tier up every Lv3 (max 4). Invincible while moving, DMG+groggy on pass-through (CD 5s)'],
['INT 스케일. 이동 경로에 화염길 생성(3초 DOT). 통과 적 화상. MP 소모. 합체 시 착지 폭발',
 'INT比例。冲刺路径生成火焰轨迹(3秒DOT)。灼烧经过敌人。消耗MP。融합时落地爆炸',
 'INTスケール。ダッシュ経路に炎の軌跡(3秒DOT)。通過した敵を火傷。MP消費。融合時着地爆発',
 'INT scale. Fire trail on dash path (3s DOT). Burns passed enemies. MP cost. Fuse: landing explosion'],
['5초간 유령화 — 무적+이동. 통과한 적/탄막 수만큼 종료 시 암전 폭발(+10%/회) + 전기줄기 방사(3회 체인). 카운트 캡=Lv×5(최대50). 쿨 20초. Lv당 뎀+15% 범위+10',
 '5秒幽灵化——无敌+移动。结束时每穿过1个敌人/弹幕触发暗电爆炸(+10%/次)+电弧放射(3连锁)。计数上限=Lv×5(最大50)。CD 20秒。每Lv伤害+15% 范围+10',
 '5秒間幽霊化——無敵+移動。通過した敵/弾幕の数だけ終了時に暗転爆発(+10%/回)+電気の束放射(3回チェーン)。カウント上限=Lv×5(最大50)。CD 20秒。Lvごとダメ+15% 範囲+10',
 '5s ghost form — invincible+move. Blackout explosion on end (+10%/enemy passed) + lightning arc (3 chains). Count cap=Lv×5 (max 50). CD 20s. Per Lv DMG+15% range+10'],
['[이동기] 방향키 더블탭으로 발동. 경직/기절 중에도 탈출 가능. 500유닛 순간이동, 무적(15프레임). MP(10+Lv×5). 1렙10충전, 렙당+1. 쿨 8초→Lv당-0.5초(최소3초). 착지 시 전류장판(10초+Lv×0.5초): INT 틱뎀 + 방어력↓(1렙10%, 렙당+5%, 캡50%)',
 '[移动技] 方向键双击激活。可从僵直/晕眩脱离。500单位瞬移，无敌(15帧)。MP(10+Lv×5)。Lv1=10充能，每Lv+1。CD 8秒→每Lv-0.5秒(最少3秒)。落地时电流区域(10秒+Lv×0.5秒)：INT持续伤害+防御↓(Lv1=10%，每Lv+5%，上限50%)',
 '[移動技] 方向キー2回タップで発動。硬直/気絶中でも脱出可能。500ユニット瞬間移動、無敵(15フレーム)。MP(10+Lv×5)。Lv1=10チャージ、Lvごと+1。CD 8秒→Lvごと-0.5秒(最少3秒)。着地時電流フィールド(10秒+Lv×0.5秒)：INTティックダメ+防御↓(Lv1=10%、Lvごと+5%、上限50%)',
 '[Mobility] Double-tap to activate. Escapes stagger/stun. 500-unit blink, invincible 15f. MP(10+Lv×5). Lv1=10 stocks, +1/Lv. CD 8s→-0.5s/Lv (min 3s). Landing shock field(10s+Lv×0.5s): INT tick DMG + DEF↓(Lv1=10%, +5%/Lv, cap 50%)'],
['좌클 스킬: 기본공격에 3단 콤보 초승달 검기 추가. ST 10+Lv당2. Lv당 뎀+10% 거리+15px',
 '左键技能：基础攻击增加3连击月牙气刃。ST 10+每Lv2。每Lv伤害+10% 距离+15px',
 '左クリックスキル：基本攻撃に3段コンボ三日月気刃を追加。ST 10+Lvごと2。Lvごとダメ+10% 距離+15px',
 'LMB skill: adds 3-hit crescent ki blade combo to basic attack. ST 10+2/Lv. Per Lv DMG+10% range+15px'],
['[기본: E] 어둠 마법 오브 발사. 범위폭발. 넉백 0.5%. Lv당 크기+50% (뎀은 _skMul 계수 적용)',
 '[默认: E] 发射暗魔法球。范围爆炸。击退0.5%。每Lv大小+50%(伤害使用_skMul系数)',
 '[デフォルト: E] 闇魔法オーブ発射。範囲爆発。ノックバック0.5%。Lvごとサイズ+50%(ダメは_skMul係数)',
 '[Default: E] Dark magic orb fired. AoE explosion. Knockback 0.5%. Per Lv size+50% (DMG uses _skMul)'],
['무기 홀드 → 전진 회전 공격. 360도 광역, ST 지속소모. Lv당 범위+5 뎀+5%',
 '长按武器→前进旋转攻击。360°范围，持续消耗ST。每Lv范围+5 伤害+5%',
 '武器ホールド→前進回転攻撃。360度範囲、STを継続消費。Lvごと範囲+5 ダメ+5%',
 'Hold weapon → forward spin attack. 360° AoE, continuous ST drain. Per Lv range+5 DMG+5%'],
['패링 3초 홀드 → 흡수 데미지 광역 폭발. Lv당 범위+15 (1렙150, 10렙285)',
 '格挡3秒长按→将吸收伤害以范围爆炸释放。每Lv范围+15(Lv1: 150, Lv10: 285)',
 'パリィ3秒ホールド→吸収ダメを範囲爆発。Lvごと範囲+15(Lv1: 150, Lv10: 285)',
 'Parry 3s hold → absorbed DMG AoE explosion. Per Lv range+15 (Lv1: 150, Lv10: 285)'],
['우클 처내기 강화. Lv당 반사 데미지 +10%. 홀드 시 연사',
 '右键反击强化。每Lv反伤+10%。长按连射',
 '右クリック迎撃強化。Lvごと反射ダメ+10%。ホールドで連射',
 'RMB swipe enhanced. Per Lv reflect DMG +10%. Hold for rapid fire'],
['[고정: T 자동] 물리 바늘 3방향 3발 발사. 관통 없음',
 '[固定: T自动] 物理针3方向各3发。无穿透',
 '[固定: T自動] 物理針3方向3発発射。貫通なし',
 '[Fixed: T auto] 3 physical needles 3-way spread. No pierce'],
['[고정: E] 1발 직선 레이저. +만화방창 → 만화광선(3발 꽈배기). +원소추적탄 → 추적암전(6발 유도)',
 '[固定: E] 1发直线激光。+弹幕→螺旋光线(3发)。+元素追踪弹→追踪暗闪(6发追踪)',
 '[固定: E] 1発直線レーザー。+弾幕→螺旋光線(3発)。+元素追跡弾→追跡暗転(6発誘導)',
 '[Fixed: E] 1 straight laser. +Barrage → Omni Beam (3 spiral). +Elem Seeker → Homing Dark (6 homing)'],
['E탭 마법을 6원소 유도 미사일로 변경. 곡선 궤적으로 적을 추적. 레벨당 사거리+20 (뎀은 _skMul 계수 적용)',
 'E键魔法变为6元素追踪导弹。曲线轨迹追踪敌人。每Lv射程+20(伤害使用_skMul系数)',
 'Eタップ魔法を6元素誘導ミサイルに変更。曲線軌道で敵を追跡。Lvごと射程+20(ダメは_skMul係数)',
 'Changes E-tap magic to 6-element homing missiles. Curved trajectory tracking enemies. Per Lv range+20 (DMG uses _skMul)'],
['3초마다 악의 구체 생성(1렙 2개). 몸에 밀착하여 적 투사체를 자동 방어(파괴). 레벨당 구체+1',
 '每3秒生成恶意球(Lv1=2个)。环绕身体自动拦截(摧毁)敌方弹幕。每Lv球数+1',
 '3秒ごとに悪意球生成(Lv1=2個)。身体に密着して敵弾を自動防御(破壊)。Lvごと球+1',
 'Spawns malice orbs every 3s (Lv1: 2 orbs). Orbits body, auto-blocks (destroys) enemy projectiles. Per Lv orb+1'],
['유도 물리 칼날 1발 (악의30+ST50). 관통률 800+Lv×20+장비. 지속뎀 5초. 쿨 15초',
 '1枚追踪物理刃(恶意30+ST50)。穿透率800+Lv×20+装备。持续伤害5秒。CD 15秒',
 '誘導物理刃1発(悪意30+ST50)。貫通率800+Lv×20+装備。継続ダメ5秒。CD 15秒',
 '1 homing physical blade (malice 30 + ST 50). Pierce 800+Lv×20+gear. DOT 5s. CD 15s'],
['어둠 소용돌이 소환 (마우스 조준 설치, MP 소모, 쿨 11초, INT 스케일링, 1렙 200범위 +30/렙, 5초 지속, 적 흡인)',
 '召唤暗黑漩涡(鼠标瞄准放置，消耗MP，CD 11秒，INT比例，Lv1范围200 +30/Lv，持续5秒，吸引敌人)',
 '暗黒渦召喚(マウス照準設置、MP消費、CD 11秒、INTスケール、Lv1範囲200 +30/Lv、5秒持続、敵吸引)',
 'Summon dark vortex (mouse-aim placement, MP cost, CD 11s, INT scale, Lv1 range 200 +30/Lv, 5s duration, pulls enemies)'],
['포격식 조준 → 원형 해골무덤 소환. 2스택 (15초/1충전, Lv10→3스택). 둘레에서 뼈가 솟아 공간을 감쌈. 솟을 때 데미지. 적/투사체 차단. 악의 12. Lv당 범위+5% 지속+0.3초',
 '炮击瞄准→召唤圆形骸骨墓。2层叠加(15秒/1充能，Lv10→3层)。骸骨从周围升起包围空间。升起时伤害。阻挡敌人/弹幕。恶意12。每Lv范围+5% 持续+0.3秒',
 '砲撃照準→円形骸骨墓召喚。2スタック(15秒/1チャージ、Lv10→3スタック)。周囲から骨が隆起して空間を囲む。隆起時ダメ。敵/弾幕をブロック。悪意12。Lvごと範囲+5% 持続+0.3秒',
 'Artillery-aim → circular bone tomb. 2 stocks (15s/charge, Lv10→3 stocks). Bones rise around perimeter. DMG on rise. Blocks enemies/projectiles. Malice 12. Per Lv range+5% duration+0.3s'],
['오망성 시전 → 신성 빛기둥 대폭발. 범위 1500+Lv×100px. 범위 끝까지 넉백(주 성능). 거리감쇠 50%. 스턴 2초. Lv당 뎀+10%. (MP 30%, 쿨 120초)',
 '五芒星施法→神圣光柱大爆炸。范围1500+Lv×100px。范围末端击退(主功能)。50%距离衰减。晕眩2秒。每Lv伤害+10%。(MP 30%，CD 120秒)',
 '五芒星詠唱→聖なる光柱大爆発。範囲1500+Lv×100px。範囲端までノックバック(主要性能)。50%距離減衰。スタン2秒。Lvごとダメ+10%。(MP 30%、CD 120秒)',
 'Pentagram cast → holy light pillar mega-explosion. Range 1500+Lv×100px. Full-range knockback (main feature). 50% distance falloff. Stun 2s. Per Lv DMG+10%. (MP 30%, CD 120s)'],
['검은 오망성 소환. 7초(+Lv당0.5초) 강력 흡인 (데미지 없음, 순수 유틸). 범위 1500+Lv×100px. 흡인력 기본5+Lv당0.5. (MP 30%, 쿨 120초)',
 '召唤黑色五芒星。7秒(+0.5秒/Lv)强力吸引(无伤害，纯辅助)。范围1500+Lv×100px。吸力基础5+0.5/Lv。(MP 30%，CD 120秒)',
 '黒い五芒星召喚。7秒(+0.5秒/Lv)強力吸引(ダメなし、純ユーティリティ)。範囲1500+Lv×100px。吸引力基本5+0.5/Lv。(MP 30%、CD 120秒)',
 'Summon black pentagram. 7s (+0.5s/Lv) strong pull (no DMG, pure utility). Range 1500+Lv×100px. Pull force base 5+0.5/Lv. (MP 30%, CD 120s)'],
['빨간 오망성 시전 → 범위 1500+Lv×100px 화염폭발+10초간 화상. 틱당 적 최대HP 1.75%(+Lv당+1.5%). 10초 20틱. 거리감쇠 30%. Lv당 초기뎀+10%. (MP 30%, 쿨 120초)',
 '红色五芒星施法→范围1500+Lv×100px火焰爆炸+10秒燃烧。每跳对敌最大HP造成1.75%(+1.5%/Lv)伤害。10秒20跳。30%距离衰减。每Lv初始伤害+10%。(MP 30%，CD 120秒)',
 '赤い五芒星詠唱→範囲1500+Lv×100px炎爆発+10秒燃焼。ティックごとに敵最大HP 1.75%(+1.5%/Lv)ダメ。10秒20ティック。30%距離減衰。Lvごと初期ダメ+10%。(MP 30%、CD 120秒)',
 'Red pentagram cast → range 1500+Lv×100px fire explosion+10s burn. Per tick enemy maxHP 1.75%(+1.5%/Lv). 10s 20 ticks. 30% distance falloff. Per Lv initial DMG+10%. (MP 30%, CD 120s)'],
['X키: 그로기 보스 전용. 보스 현재HP 20%(+2%/Lv) + 무기뎀×30(+21%/Lv, 20Lv=150배) + 보스HP 30% 순수뎀. 섬광 돌진 연출. HP/MP/ST 10% 소모. 쿨 5초',
 'X键：专用于击晕BOSS。BOSS当前HP 20%(+2%/Lv)+武器伤害×30(+21%/Lv，20Lv=150倍)+BOSS HP 30%纯伤。闪光冲刺演出。消耗HP/MP/ST各10%。CD 5秒',
 'Xキー：グロッキーボス専用。ボス現在HP 20%(+2%/Lv)+武器ダメ×30(+21%/Lv、20Lv=150倍)+ボスHP 30%純粋ダメ。閃光突進演出。HP/MP/ST 10%消費。CD 5秒',
 'X key: Groggy boss only. Boss current HP 20%(+2%/Lv) + weapon DMG×30(+21%/Lv, Lv20=150×) + boss HP 30% pure DMG. Flash dash. HP/MP/ST 10% cost. CD 5s'],
['얼음 속에 들어가 무적 상태. 다시 누르면 파쇄 → 얼음칼날 48발 부채꼴 방사 (MP 40, 쿨 20초). Lv당 칼날+2 뎀+15%',
 '进入冰块无敌状态。再次按下碎裂→48枚冰刃扇形放射(MP 40，CD 20秒)。每Lv冰刃+2 伤害+15%',
 '氷の中に入り無敵状態。再押しで破砕→氷刃48発扇形放射(MP 40、CD 20秒)。Lvごと刃+2 ダメ+15%',
 'Enter ice — invincible. Re-press to shatter → 48 ice blades fan spread (MP 40, CD 20s). Per Lv blades+2 DMG+15%'],
['[고정: T 자동] 초고속 바늘 연발. 1렙 2발, 5렙마다 +1발. 관통 없음. ST 8. 쿨 1.5초. Lv당 뎀+100%',
 '[固定: T自动] 超高速连续射针。Lv1=2发，每5Lv+1发。无穿透。ST 8。CD 1.5秒。每Lv伤害+100%',
 '[固定: T自動] 超高速連続針。Lv1=2発、5Lvごとに+1発。貫通なし。ST 8。CD 1.5秒。Lvごとダメ+100%',
 '[Fixed: T auto] Ultra-fast needles burst. Lv1 2 shots, +1 per 5 levels. No pierce. ST 8. CD 1.5s'],
['E홀드: 직선 관통 레이저 채널링. MP 8+Lv/초 지속소모. 폭160+(Lv×10)px, 사거리1200+Lv×80. 관통+감전. Lv당 뎀+21%',
 'E长按：直线穿透激光引导。持续消耗MP 8+Lv/秒。宽160+(Lv×10)px，射程1200+Lv×80。穿透+感电。每Lv伤害+21%',
 'Eホールド：直線貫通レーザーチャネリング。MP 8+Lv/秒継続消費。幅160+(Lv×10)px、射程1200+Lv×80。貫通+感電。Lvごとダメ+21%',
 'E hold: Straight piercing laser channeling. MP 8+Lv/s drain. Width 160+(Lv×10)px, range 1200+Lv×80. Pierce+shock. Per Lv DMG+21%'],
['E탭: 화염 유도빔 발사. MP10. 쿨1초(DEX 스케일). 100% 관통+유도+화상. Lv당 사거리+50 뎀+12%',
 'E点按：发射火焰追踪光束。MP 10。CD 1秒(DEX比例)。100%穿透+追踪+燃烧。每Lv射程+50 伤害+12%',
 'Eタップ：炎誘導ビーム発射。MP 10。CD 1秒(DEXスケール)。100%貫通+誘導+火傷。Lvごと射程+50 ダメ+12%',
 'E tap: fire homing beam. MP 10. CD 1s (DEX scale). 100% pierce+homing+burn. Per Lv range+50 DMG+12%'],
['E: 10초간 대지 진동. 범위 내 용암 기둥이 순차적으로 솟아올라 화상+틱 데미지. MP 100. 쿨 12초. Lv당 범위+10% 뎀+12%',
 'E：10秒大地震动。范围内岩浆柱依次升起——燃烧+持续伤害。MP 100。CD 12秒。每Lv范围+10% 伤害+12%',
 'E：10秒間大地振動。範囲内に溶岩柱が順次隆起——火傷+ティックダメ。MP 100。CD 12秒。Lvごと範囲+10% ダメ+12%',
 'E: 10s ground tremor. Lava pillars rise sequentially in range — burn+tick DMG. MP 100. CD 12s. Per Lv range+10% DMG+12%'],
['독혈 칼날 1발 발사: 관통률 기본 800+Lv×20 + 장비 bowPierce×300/패시브 pPierce×30 반영, +100 보정. 전염+마지막 적 처형. 감염 사망 시 폭발+연쇄 전염. 악의 15. 사거리 4000. 쿨 15초(Lv당-0.5초)',
 '发射1枚毒血刃：基础穿透率800+Lv×20，含bowPierce×300和pPierce×30加成，+100修正。传染+处决最后目标。感染死亡→爆炸+连锁传染。恶意15。射程4000。CD 15秒(每Lv-0.5秒)',
 '毒血刃1発発射：基本貫通率800+Lv×20、bowPierce×300とpPierce×30適用、+100補正。伝染+最後の敵処刑。感染死亡時爆発+連鎖伝染。悪意15。射程4000。CD 15秒(Lvごと-0.5秒)',
 'Fire 1 poison-blood blade: base pierce rate 800+Lv×20 with bowPierce×300 and pPierce×30 scaling, plus +100 bonus. Plague+execute last enemy. Infected death → explosion+chain plague. Malice 15. Range 4000. CD 15s (-0.5s/Lv)'],
['마우스 조준 설치. 쿨 20초. 화면 내 클릭 위치에 암전나선 (3초, 10틱, 틱당 100+Lv*20). Lv당 범위+22. 같은 지역 중복 불가',
 '鼠标瞄准放置。CD 20秒。在点击位置放置暗电漩涡(3秒，10跳，每跳100+Lv*20)。每Lv范围+22。同区域不可叠加',
 'マウス照準設置。CD 20秒。クリック位置に暗転螺旋(3秒、10ティック、ティックごとに100+Lv*20)。Lvごと範囲+22。同区域重複不可',
 'Mouse-aim placement. CD 20s. Dark spiral at click pos (3s, 10 ticks, 100+Lv*20/tick). Per Lv range+22. No stacking same area'],
['현재 위치에 9개 기둥 순차 발동. 5초간 악의 기둥을 소환하여 반경 내 적에게 지속 암전 데미지+감속. 범위 250+(Lv-1)×22. 대왕치기와 합체→기둥강타. 쿨 15초',
 '当前位置依次激活9根柱子。5秒暗柱对范围内敌人持续暗电伤害+减速。范围250+(Lv-1)×22。与大王锤融합→柱锤。CD 15秒',
 '現在位置に9本の柱を順次発動。5秒間悪意柱を召喚して半径内の敵に継続暗転ダメ+減速。範囲250+(Lv-1)×22。大王打ちと融合→柱打ち。CD 15秒',
 '9 pillars activate sequentially at current pos. 5s dark pillars deal sustained dark DMG+slow to enemies in radius. Range 250+(Lv-1)×22. Fuses with Giant Slam → Pillar Strike. CD 15s'],
['현재 위치에 회복의 영역 설치 (12초 지속). 땅 위: HP/MP/ST 초당+10 리젠 + 회복력 2배 + 쿨다운 속도 2배. 쿨 30초. Lv당 범위+20 지속+0.5초',
 '在当前位置设置圣域(持续12秒)。区域内：HP/MP/ST每秒+10回复+2倍恢复+2倍CD速度。CD 30秒。每Lv范围+20 持续+0.5秒',
 '現在位置に聖域設置(12秒持続)。地面上：HP/MP/ST毎秒+10回復+回復力2倍+CD速度2倍。CD 30秒。Lvごと範囲+20 持続+0.5秒',
 'Place holy domain at current pos (12s duration). On ground: HP/MP/ST +10/s regen + 2x recovery + 2x CD speed. CD 30s. Per Lv range+20 duration+0.5s'],
['범위 내 몬스터 부활력 -15%~30%(Lv1=15%, Lv10=30%). Lv1 범위400, Lv10 범위697. Lv당 범위+33. 쿨 30초. 지속 10초',
 '范围内怪物复活力-15%~30%(Lv1=15%，Lv10=30%)。Lv1范围400，Lv10范围697。每Lv范围+33。CD 30秒。持续10秒',
 '範囲内モンスターの復活力-15%~30%(Lv1=15%、Lv10=30%)。Lv1範囲400、Lv10範囲697。Lvごと範囲+33。CD 30秒。持続10秒',
 'Monsters in range: revive power -15%~30%(Lv1=15%, Lv10=30%). Lv1 range 400, Lv10 range 697. Per Lv range+33. CD 30s. Duration 10s'],
['마우스 조준 설치. 2스택 (15초/1충전, Lv10→3스택). 범위 내 빙결 저항 -50%, 빙결 게이지 급속 축적. 3초 지속. MP 40. Lv당 범위+22 축적+10%',
 '鼠标瞄准放置。2层叠加(15秒/1充能，Lv10→3层)。范围内冰冻抗性-50%，冰冻槽快速积累。持续3秒。MP 40。每Lv范围+22 积累+10%',
 'マウス照準設置。2スタック(15秒/1チャージ、Lv10→3スタック)。範囲内凍結抵抗-50%、凍結ゲージ急速蓄積。3秒持続。MP 40。Lvごと範囲+22 蓄積+10%',
 'Mouse-aim placement. 2 stocks (15s/charge, Lv10→3 stocks). Freeze resist -50% in range, rapid freeze gauge buildup. 3s duration. MP 40. Per Lv range+22 buildup+10%'],
['땅을 내리쳐 원형 진동파 발생(범위400). 일반몹에게 큰 포이즈 피해, 보스 체간 파괴에 강함. 회전기폭과 합체→지진폭풍!',
 '猛击地面→产生圆形震动波(范围400)。对普通怪造成大量体势伤害，擅长破坏BOSS体势。与旋转起爆融합→地震风暴！',
 '地面を叩いて円形振動波発生(範囲400)。一般モブに大きなポイズダメ、ボス体幹破壊に強い。回転起爆と融合→地震嵐！',
 'Slam ground → circular shockwave (range 400). High poise DMG to mobs, strong posture break vs bosses. Fuses with Whirlwind Detonate → Earthquake Storm!'],
['땅을 내리쳐 원형 진동파 발생(범위400). 일반몹에게 큰 포이즈 피해, 보스 체간 파괴에 강함. 악의기둥과 합체→기둥강타!',
 '猛击地面→产生圆形震动波(范围400)。对普通怪造成大量体势伤害，擅长破坏BOSS体势。与暗柱融합→柱锤！',
 '地面を叩いて円形振動波発生(範囲400)。一般モブに大きなポイズダメ、ボス体幹破壊に強い。悪意柱と融合→柱打ち！',
 'Slam ground → circular shockwave (range 400). High poise DMG to mobs, strong posture break vs bosses. Fuses with Dark Pillar → Pillar Slam!'],
['사슬기동 중 E → 즉시 착지하며 화염폭발. 범위200~350 INT 스케일 화염 마법데미지+넉백. 이동거리에 비례해 데미지↑(최대 x4.0). MP 소모. Lv당 범위+16 뎀+12%',
 '锁链冲刺中E→立即落地并火焰爆炸。范围200~350 INT比例火焰魔法伤害+击退。伤害随移动距离增加(最大×4.0)。消耗MP。每Lv范围+16 伤害+12%',
 '鎖機動中E→即着地して炎爆発。範囲200~350 INTスケール炎魔法ダメ+ノックバック。移動距離に比例してダメ↑(最大×4.0)。MP消費。Lvごと範囲+16 ダメ+12%',
 'During chain dash E → instant land with fire explosion. Range 200~350 INT scale fire magic DMG+knockback. DMG scales with travel distance (max x4.0). MP cost. Per Lv range+16 DMG+12%'],
['사슬기동 중 우클릭 → 땅 내려찍기. 범위200~350 데미지x8 그로기x6. 이동거리 비례 최대x6. 일반몹 즉시 기절(5초), 보스 체간 대량 삭감. Lv당 범위+16 데미지+15% 그로기+15%',
 '锁链冲刺中右键→猛击地面。范围200~350 伤害×8 击晕×6。距离比例最大×6。普通怪立即晕眩(5秒)，大幅削减BOSS体势。每Lv范围+16 伤害+15% 击晕+15%',
 '鎖機動中右クリック→地面叩き。範囲200~350 ダメ×8 グロッキー×6。移動距離比例最大×6。一般モブ即座に気絶(5秒)、ボス体幹大量削減。Lvごと範囲+16 ダメ+15% グロッキー+15%',
 'During chain dash RMB → ground slam. Range 200~350 DMG x8 groggy x6. Distance scale max x6. Instant stun mobs (5s), massive boss posture break. Per Lv range+16 DMG+15% groggy+15%'],
['[히든: 5성 dimRush 합체] 사슬기동 중 좌클릭 → 이동 중 전방 광역 베기+출혈. STR 스케일 물리데미지. 다단히트. Lv당 뎀+12% 범위+15',
 '[隐藏：5星dimRush融합] 锁链冲刺中左键→移动中前方范围斩击+出血。STR比例物理伤害。多段命中。每Lv伤害+12% 范围+15',
 '[隠し：5星dimRush融合] 鎖機動中左クリック→移動中前方範囲斬り+出血。STRスケール物理ダメ。多段ヒット。Lvごとダメ+12% 範囲+15',
 '[Hidden: 5-star dimRush fuse] During chain dash LMB → forward AoE slash+bleed while moving. STR scale physical DMG. Multi-hit. Per Lv DMG+12% range+15'],
['[히든: 암전나선 합체] Q 홀드 시 보호막이 점점 커지며 HP 초당 10% 회복. 보호막 크기에 비례해 데미지 감소. MP 소모',
 '[隐藏：暗电漩涡融합] Q长按时护盾逐渐扩大，HP每秒回复10%。伤害减免随护盾大小增加。消耗MP',
 '[隠し：暗転螺旋融合] Qホールド時シールドが徐々に拡大し、HP毎秒10%回復。ダメ減少はシールドサイズに比例。MP消費',
 '[Hidden: Dark Spiral fuse] Q hold: shield grows over time + HP 10%/s regen. DMG reduction scales with shield size. MP cost'],
['[히든: 암전나선 합체] E로 조준, 클릭 설치. 에너지 쐐기를 지상에 꽂아 회전+데미지. MP100. 1차지 쿨10초. 5초+Lv당0.5초 지속. Lv당 거리+50',
 '[隐藏：暗电漩涡融합] E瞄准，点击放置。将能量楔插入地面——旋转+伤害。MP 100。1充能CD 10秒。持续5秒+0.5秒/Lv。每Lv距离+50',
 '[隠し：暗転螺旋融合] Eで照準、クリックで設置。エネルギー楔を地面に打ち込み回転+ダメ。MP 100。1チャージCD 10秒。5秒+0.5秒/Lv持続。Lvごと距離+50',
 '[Hidden: Dark Spiral fuse] E to aim, click to place. Energy wedge planted on ground — rotates+DMG. MP 100. 1 charge CD 10s. 5s+0.5s/Lv duration. Per Lv range+50'],
['[고정: 칼등치기 합체] 보유 시 칼등치기에 전방 충격파 자동 발동. 제자리 처내기. 쿨 5초. Lv당 뎀+12% 범위+20',
 '[固定：格挡融합] 持有时格挡自动触发前方冲击波。原地反击。CD 5秒。每Lv伤害+12% 范围+20',
 '[固定：盾払い融合] 保有時に盾払いが前方衝撃波を自動発動。その場で迎撃。CD 5秒。Lvごとダメ+12% 範囲+20',
 '[Fixed: Blade Parry fuse] When owned, swipe auto-triggers forward shockwave. Stationary swipe. CD 5s. Per Lv DMG+12% range+20'],
['현재 위치에 파쇄 영역 설치 (10초). 범위 내 적 물리방어력 -10%. 쿨 25초. Lv당 범위+22 효과+1% 지속+0.3초',
 '在当前位置设置破碎领域(10秒)。范围内敌人物理防御-10%。CD 25秒。每Lv范围+22 效果+1% 持续+0.3秒',
 '現在位置に破砕領域設置(10秒)。範囲内敵物理防御-10%。CD 25秒。Lvごと範囲+22 効果+1% 持続+0.3秒',
 'Place shatter domain at current pos (10s). Enemy phys DEF -10% in range. CD 25s. Per Lv range+22 effect+1% duration+0.3s'],
['현재 위치에 침식 영역 설치 (10초). 범위 내 적 마법저항력 -10%. 쿨 25초. Lv당 범위+22 효과+1% 지속+0.3초',
 '在当前位置设置腐蚀领域(10秒)。范围内敌人魔法抗性-10%。CD 25秒。每Lv范围+22 效果+1% 持续+0.3秒',
 '現在位置に腐食領域設置(10秒)。範囲内敵魔法抵抗-10%。CD 25秒。Lvごと範囲+22 効果+1% 持続+0.3秒',
 'Place corrosion domain at current pos (10s). Enemy magic resist -10% in range. CD 25s. Per Lv range+22 effect+1% duration+0.3s'],
['현재 위치에 관통 영역 설치 (10초). 범위 내 적 투사체저항력 -10%. 쿨 25초. Lv당 범위+22 효과+1% 지속+0.3초',
 '在当前位置设置穿透领域(10秒)。范围内敌人弹幕抗性-10%。CD 25秒。每Lv范围+22 效果+1% 持续+0.3秒',
 '現在位置に貫通領域設置(10秒)。範囲内敵弾幕抵抗-10%。CD 25秒。Lvごと範囲+22 効果+1% 持続+0.3秒',
 'Place pierce domain at current pos (10s). Enemy projectile resist -10% in range. CD 25s. Per Lv range+22 effect+1% duration+0.3s'],
['현재 위치에 부활 영역 설치 (10초). 영역 안에서 부활력 +10%. 쿨 25초. Lv당 범위+22 효과+1% 지속+0.3초',
 '在当前位置设置复活领域(10秒)。领域内复活力+10%。CD 25秒。每Lv范围+22 效果+1% 持续+0.3秒',
 '現在位置に復活領域設置(10秒)。領域内で復活力+10%。CD 25秒。Lvごと範囲+22 効果+1% 持続+0.3秒',
 'Place revival domain at current pos (10s). Revive power +10% inside zone. CD 25s. Per Lv range+22 effect+1% duration+0.3s'],
['[고정: Space] 현재 위치에 가시덫 설치 (1렙 반경200, 10렙398). 슬로우 70%(+2%/Lv, 최대90%)+출혈. INT×magicRef×3(+10%/Lv). 악의 10, 쿨 10초. Lv당 범위+22',
 '[固定: Space] 在当前位置设置尖刺陷阱(Lv1半径200，Lv10=398)。减速70%(+2%/Lv，最大90%)+出血。INT×magicRef×3(+10%/Lv)。恶意10，CD 10秒。每Lv范围+22',
 '[固定: Space] 現在位置にスパイクトラップ設置(Lv1半径200、Lv10=398)。スロー70%(+2%/Lv、最大90%)+出血。INT×magicRef×3(+10%/Lv)。悪意10、CD 10秒。Lvごと範囲+22',
 '[Fixed: Space] Place spike trap at current pos (Lv1 radius 200, Lv10 398). Slow 70%(+2%/Lv, max 90%)+bleed. INT×magicRef×3(+10%/Lv). Malice 10, CD 10s. Per Lv range+22'],
['[고정: E, Lv300 해금] 유도 파란콩 50발 순차 발사 (5초간). MP 100(+1.5/Lv) 소모. 적 추적. 쿨 5초. Lv당 사거리+30 (뎀은 _skMul 계수 적용)',
 '[固定: E，Lv300解锁] 50枚追踪蓝豆依次发射(5秒内)。消耗MP 100(+1.5/Lv)。追踪敌人。CD 5秒。每Lv射程+30(伤害使用_skMul系数)',
 '[固定: E、Lv300解放] 誘導青弾50発順次発射(5秒間)。MP 100(+1.5/Lv)消費。敵追跡。CD 5秒。Lvごと射程+30(ダメは_skMul係数)',
 '[Fixed: E, unlock Lv300] 50 homing blue shots fired sequentially (over 5s). MP 100(+1.5/Lv) cost. Tracks enemies. CD 5s. Per Lv range+30 (DMG uses _skMul)'],
['[히든: E, Lv700 해금] 홀드 시 3단계 차지 범위폭발 (0.5/1.0/1.5초). 범위 600/1000/1400px. 3단 만충 자동폭발. INT 스케일, 무속성',
 '[隐藏: E，Lv700解锁] 长按3阶段蓄力范围爆炸(0.5/1.0/1.5秒)。范围600/1000/1400px。3阶满充自动爆炸。INT比例，无属性',
 '[隠し: E、Lv700解放] ホールドで3段階チャージ範囲爆発(0.5/1.0/1.5秒)。範囲600/1000/1400px。3段満チャージ自動爆発。INTスケール、無属性',
 '[Hidden: E, unlock Lv700] Hold for 3-stage charge AoE explosion (0.5/1.0/1.5s). Range 600/1000/1400px. Stage 3 full charge auto-detonates. INT scale, no element'],
['유령 허수아비를 소환하여 유도탄막 어그로를 끈다. 탄막을 흡수해 자원 축적 (기본 20개, Lv당+3). 1개당 HP/MP/ST 각 100. R키로 회수. 쿨 10초',
 '召唤幽灵稻草人吸引追踪弹幕仇恨。吸收弹幕积累资源(基础20个，每Lv+3)。每吸收1个：HP/MP/ST各+100。R键召回。CD 10秒',
 '幽霊かかしを召喚して誘導弾幕のヘイトを引く。弾幕を吸収して資源蓄積(基本20個、Lv+3)。1個ごとHP/MP/ST各+100。Rキーで回収。CD 10秒',
 'Summon phantom scarecrow to draw homing projectile aggro. Absorbs projectiles for resource buildup (base 20, +3/Lv). Per absorbed: HP/MP/ST +100 each. R key to retrieve. CD 10s'],
['폭발 허수아비 설치. 탄막을 흡수하고 재입력 시 폭발! 1스택당 (INT마법뎀+탄막뎀)×10 마법데미지. 범위 250+흡수×25 (최대1000). 최대흡수 1렙20~20렙60. 쿨 10초',
 '放置爆炸稻草人。吸收弹幕后再次输入引爆！每层(INT魔法伤+弹幕伤)×10魔法伤害。范围250+吸收×25(最大1000)。最大吸收Lv1=20~Lv20=60。CD 10秒',
 '爆発かかし設置。弾幕を吸収後再入力で爆発！1スタックごとに(INT魔法ダメ+弾幕ダメ)×10魔法ダメ。範囲250+吸収×25(最大1000)。最大吸収Lv1=20~Lv20=60。CD 10秒',
 'Place explosive scarecrow. Absorbs projectiles, re-press to detonate! Per stack: (INT magic DMG + proj DMG)×10. Range 250+absorbed×25 (max 1000). Max absorb Lv1=20~Lv20=60. CD 10s'],
['[선택: 1~4번, Lv500 해금] 현재 위치에 공성쇠뇌 터렛 설치. 재입력 시 철거. 설치 중 플레이어 석궁 사용 불가 (터렛만 발사). 데미지+50%, 공속+50%, 사거리+50%. ST 100. 쿨 10초. Lv당 뎀+5% 공속+5% 사거리+5%',
 '[选择: 1~4键，Lv500解锁] 在当前位置部署攻城弩炮台。再次输入拆除。部署中玩家弩不可用(仅炮台发射)。伤害+50%，攻速+50%，射程+50%。ST 100。CD 10秒。每Lv伤害+5% 攻速+5% 射程+5%',
 '[選択: 1~4番、Lv500解放] 現在位置に攻城弩砲台設置。再入力で解体。設置中プレイヤー弩使用不可(砲台のみ発射)。ダメ+50%、攻速+50%、射程+50%。ST 100。CD 10秒。Lvごとダメ+5% 攻速+5% 射程+5%',
 '[Select: 1~4, unlock Lv500] Deploy siege crossbow turret at current pos. Re-press to dismantle. While deployed: player crossbow disabled (turret fires only). DMG+50%, ATK SPD+50%, range+50%. ST 100. CD 10s. Per Lv DMG+5% ATK SPD+5% range+5%'],
['[Ctrl, Lv500 해금] 발동 시 3초 전 상태로 되돌린다. 위치/HP/MP/ST 완전 복원. Lv당 되감기+0.105초 (1렙 3초, 20렙 5초). MP 50(+5/Lv, 20렙150). 쿨 45초',
 '[Ctrl，Lv500解锁] 激活时回到3秒前的状态。完全恢复位置/HP/MP/ST。每Lv回溯+0.105秒(Lv1=3秒，Lv20=5秒)。MP 50(+5/Lv，Lv20=150)。CD 45秒',
 '[Ctrl、Lv500解放] 発動時3秒前の状態に戻す。位置/HP/MP/ST完全復元。Lvごと巻き戻し+0.105秒(Lv1=3秒、Lv20=5秒)。MP 50(+5/Lv、Lv20=150)。CD 45秒',
 '[Ctrl, unlock Lv500] Rewind to state from 3s ago. Restores position/HP/MP/ST. Per Lv rewind+0.105s (Lv1=3s, Lv20=5s). MP 50(+5/Lv, Lv20=150). CD 45s'],
['[선택: 1~4번] 마우스 조준 → 전기창을 땅에 꽂는다. 5스택(12초/1충전, Lv10→6스택). 창끼리 600px 이내면 전류 아크 발생, 경로 위 적에게 감전 틱 데미지. MP 50. 지속 10초(+0.5초/Lv). Lv당 아크뎀+10%',
 '[选择: 1~4键] 鼠标瞄准→将电矛插入地面。5层叠加(12秒/1充能，Lv10→6层)。矛之间600px内产生电弧，对路径上敌人造成感电持续伤害。MP 50。持续10秒(+0.5秒/Lv)。每Lv弧伤+10%',
 '[選択: 1~4番] マウス照準→電気槍を地面に打ち込む。5スタック(12秒/1チャージ、Lv10→6スタック)。槍同士600px以内で電気アーク発生、経路上の敵に感電ティックダメ。MP 50。持続10秒(+0.5秒/Lv)。Lvごとアークダメ+10%',
 '[Select: 1~4] Mouse aim → plant electric spear on ground. 5 stocks (12s/charge, Lv10→6). Spears within 600px create lightning arcs dealing shock tick DMG to enemies on path. MP 50. Duration 10s (+0.5s/Lv). Per Lv arc DMG+10%'],
];

// Traditional Chinese conversion from Simplified
function toTrad(s) {
  const map = {'伤':'傷','动':'動','范':'範','传':'傳','发':'發','复':'復','无':'無',
    '锁':'鎖','链':'鏈','踪':'蹤','电':'電','冻':'凍','烧':'燒','选':'選',
    '击':'擊','连':'連','长':'長','强':'強','转':'轉','弹':'彈','触':'觸',
    '积':'積','减':'減','拦':'攔','换':'換','还':'還','环':'環','会':'會',
    '对':'對','开':'開','关':'關','战':'戰','闪':'閃','赵':'趙','剑':'劍',
    '险':'險','来':'來','给':'給','时':'時','样':'樣','时':'時','们':'們',
    '气':'氣','过':'過','这':'這','进':'進','带':'帶','号':'號','属':'屬',
    '场':'場','势':'勢','积':'積','两':'兩','为':'為','产':'產','层':'層',
    '处':'處','从':'從','窗':'窗','叠':'疊','后':'後','级':'級','扩':'擴'};
  return s.split('').map(c=>map[c]||c).join('');
}

// Lang file marker (value of '스테이지' key differs per lang)
const LANG_STAGE = {
  zh:'关卡', ja:'ステージ', zht:'關卡',
  es:'Fase', fr:'Étape', de:'Stufe', ptbr:'Fase', it:'Fase', id:'Tahap',
  ru:'Уровень', vi:'Giai đoạn', th:'ด่าน', tr:'Aşama', pl:'Etap',
  cs:'Fáze', hu:'Szakasz', bg:'Ниво', el:'Φάση', fi:'Vaihe',
  sv:'Nivå', da:'Niveau', no:'Nivå', nl:'Fase', ro:'Etapă',
  uk:'Рівень', ar:'المرحلة', el:'Στάδιο',
};

const HELL = 'G:/hell';

for (const [lang, stage] of Object.entries(LANG_STAGE)) {
  const file = `${HELL}/lang_${lang}.js`;
  let content = fs.readFileSync(file, 'utf8');

  // Build insert lines
  const lines = [];
  for (const [ko, zh, ja, en] of P) {
    let val;
    if (lang === 'zh') val = zh;
    else if (lang === 'ja') val = ja;
    else if (lang === 'zht') val = toTrad(zh);
    else val = en; // all others use English
    lines.push(`'${ko}':'${val}',`);
  }

  const marker = `'스테이지':'${stage}',`;
  if (!content.includes(marker)) {
    console.error(`[SKIP] ${lang}: marker not found`);
    continue;
  }
  // Avoid double-insert
  const firstKey = P[0][0];
  if (content.includes(`'${firstKey}':`)) {
    console.log(`[SKIP] ${lang}: already inserted`);
    continue;
  }

  const insert = `// --- Phase 37: skill desc ---\n` + lines.join('\n') + '\n';
  content = content.replace(marker, insert + marker);
  fs.writeFileSync(file, content, 'utf8');
  console.log(`[OK] ${lang} — ${P.length} entries`);
}
console.log('Phase 37 done.');
