# -*- coding: utf-8 -*-
# CAT-67: Steam 위시리스트 3항목 → 23개 _LOBBY_* 테이블
# CAT-68: CIN_LINES 22개 언어 추가

with open('G:/hell/index.html', 'r', encoding='utf-8') as f:
    content = f.read()

KO1 = '여러분의 Steam 찜 하나가\\nEXODUSER: HELL LORD의\\n다음 여정을 만듭니다'
KO2 = '공식 출시 소식을 가장 먼저 받아보세요'
KO3 = 'STEAM 위시리스트 추가'

# ═══ CAT-67: Steam Wishlist 3 entries per table ═══
# (lang, any_key_translation, enter_translation, w1, w2, w3)
lobby_data = [
    ('FR',
     'Appuyez sur une touche pour continuer',
     'Entrer',
     'Votre ajout à la liste de souhaits Steam\\nfaçonne le prochain chapitre de\\nEXODUSER: HELL LORD',
     'Soyez le premier informé du lancement officiel',
     'AJOUTER À LA LISTE DE SOUHAITS STEAM'),
    ('IT',
     'Premi un tasto per continuare',
     'Entra',
     "Il tuo supporto nella lista dei desideri Steam\\ndà forma al prossimo capitolo di\\nEXODUSER: HELL LORD",
     "Sii il primo a sapere del lancio ufficiale",
     'AGGIUNGI ALLA LISTA DEI DESIDERI STEAM'),
    ('PTBR',
     'Pressione qualquer tecla para continuar',
     'Entrar',
     'Seu apoio na lista de desejos Steam\\nmolda o próximo capítulo de\\nEXODUSER: HELL LORD',
     'Seja o primeiro a saber do lançamento',
     'ADICIONAR À LISTA DE DESEJOS STEAM'),
    ('RO',
     'Apasă orice tastă pentru a continua',
     'Intră',
     'Sprijinul tău pe lista de dorințe Steam\\nmodelează următorul capitol al\\nEXODUSER: HELL LORD',
     'Fii primul care află când lansăm',
     'ADAUGĂ PE LISTA DE DORINȚE STEAM'),
    ('DE',
     'Beliebige Taste drücken zum Fortfahren',
     'Eintreten',
     'Deine Steam-Wunschliste-Unterstützung\\ngestaltet das nächste Kapitel von\\nEXODUSER: HELL LORD',
     'Sei der Erste, der vom offiziellen Launch erfährt',
     'ZUR STEAM-WUNSCHLISTE HINZUFÜGEN'),
    ('NL',
     'Druk op een toets om door te gaan',
     'Betreden',
     'Jouw Steam-verlanglijst-steun\\nvormt het volgende hoofdstuk van\\nEXODUSER: HELL LORD',
     'Wees de eerste die weet wanneer we lanceren',
     'TOEVOEGEN AAN STEAM-VERLANGLIJST'),
    ('SV',
     'Tryck valfri tangent för att fortsätta',
     'Gå in',
     'Ditt stöd på Steam önskelista\\nformar nästa kapitel av\\nEXODUSER: HELL LORD',
     'Bli den första att veta när vi lanserar',
     'LÄGG TILL PÅ STEAM ÖNSKELISTA'),
    ('DA',
     'Tryk en vilkårlig tast for at fortsætte',
     'Gå ind',
     'Din Steam-ønskeliste-støtte\\nformer det næste kapitel af\\nEXODUSER: HELL LORD',
     'Vær den første til at vide, hvornår vi lancerer',
     'TILFØJ TIL STEAM-ØNSKELISTE'),
    ('NO',
     'Trykk en vilkårlig tast for å fortsette',
     'Gå inn',
     'Din støtte på Steam ønskeliste\\nformer neste kapittel av\\nEXODUSER: HELL LORD',
     'Vær den første til å vite når vi lanserer',
     'LEGG TIL PÅ STEAM ØNSKELISTE'),
    ('RU',
     'Нажмите любую клавишу для продолжения',
     'Войти',
     'Ваша поддержка через список желаний Steam\\nформирует следующую главу\\nEXODUSER: HELL LORD',
     'Узнайте об официальном выходе первыми',
     'ДОБАВИТЬ В СПИСОК ЖЕЛАНИЙ STEAM'),
    ('UK',
     'Натисніть будь-яку клавішу для продовження',
     'Увійти',
     'Ваша підтримка через список бажань Steam\\nформує наступний розділ\\nEXODUSER: HELL LORD',
     'Дізнайтеся про офіційний вихід першими',
     'ДОДАТИ ДО СПИСКУ БАЖАНЬ STEAM'),
    ('PL',
     'Naciśnij dowolny klawisz, aby kontynuować',
     'Wejdź',
     'Twoje wsparcie na liście życzeń Steam\\nkształtuje następny rozdział\\nEXODUSER: HELL LORD',
     'Bądź pierwszym, który dowie się o premierze',
     'DODAJ DO LISTY ŻYCZEŃ STEAM'),
    ('CS',
     'Stiskni libovolnou klávesu pro pokračování',
     'Vstoupit',
     'Tvoje podpora přes Steam seznam přání\\nformuje další kapitolu\\nEXODUSER: HELL LORD',
     'Buď první, kdo se dozví o officiálním launchi',
     'PŘIDAT NA SEZNAM PŘÁNÍ STEAM'),
    ('HU',
     'Nyomj meg egy gombot a folytatáshoz',
     'Belépés',
     'A Steam kívánságlistán való támogatásod\\nformálja a következő fejezetet:\\nEXODUSER: HELL LORD',
     'Légy az első, aki értesül a megjelenésről',
     'HOZZÁADÁS A STEAM KÍVÁNSÁGLISTÁHOZ'),
    ('BG',
     'Натиснете произволен клавиш за продължаване',
     'Влезте',
     'Вашата подкрепа в списъка с желания Steam\\nформира следващата глава на\\nEXODUSER: HELL LORD',
     'Бъдете първите, които разберат за излизането',
     'ДОБАВЯНЕ В СПИСЪКА С ЖЕЛАНИЯ STEAM'),
    ('EL',
     'Πατήστε οποιοδήποτε πλήκτρο για συνέχεια',
     'Εισαγωγή',
     'Η υποστήριξή σου στη λίστα επιθυμιών Steam\\nδιαμορφώνει το επόμενο κεφάλαιο του\\nEXODUSER: HELL LORD',
     'Μάθε πρώτος για την επίσημη κυκλοφορία',
     'ΠΡΟΣΘΗΚΗ ΣΤΗ ΛΙΣΤΑ ΕΠΙΘΥΜΙΩΝ STEAM'),
    ('FI',
     'Paina mitä tahansa näppäintä jatkaaksesi',
     'Siirry',
     'Steam-toivelistasi tuki\\nmuokkaa seuraavaa lukua:\\nEXODUSER: HELL LORD',
     'Ole ensimmäinen, joka saa tietää julkaisusta',
     'LISÄÄ STEAM-TOIVELISTALLE'),
    ('TR',
     'Devam etmek için herhangi bir tuşa basın',
     'Gir',
     "Steam istek listenizdeki desteğiniz\\nEXODUSER: HELL LORD\\'un\\nsonraki bölümünü şekillendiriyor",
     'Resmi çıkışı ilk öğrenen siz olun',
     'STEAM İSTEK LİSTESİNE EKLE'),
    ('AR',
     'اضغط أي مفتاح للمتابعة',
     'دخول',
     'دعمكم في قائمة الرغبات على Steam\\nيشكّل الفصل القادم من\\nEXODUSER: HELL LORD',
     'كونوا أول من يعلم بالإطلاق الرسمي',
     'أضف إلى قائمة الرغبات على STEAM'),
    ('VI',
     'Nhấn phím bất kỳ để tiếp tục',
     'Vào',
     'Sự ủng hộ của bạn trên danh sách yêu thích Steam\\nsẽ định hình chương tiếp theo của\\nEXODUSER: HELL LORD',
     'Là người đầu tiên biết khi chúng tôi ra mắt',
     'THÊM VÀO DANH SÁCH YÊU THÍCH STEAM'),
    ('TH',
     'กดปุ่มใดก็ได้เพื่อดำเนินการต่อ',
     'เข้า',
     'การสนับสนุนของคุณใน Steam Wishlist\\nกำหนดรูปร่างบทถัดไปของ\\nEXODUSER: HELL LORD',
     'เป็นคนแรกที่รู้เมื่อเราเปิดตัว',
     'เพิ่มใน STEAM WISHLIST'),
    ('ID',
     'Tekan tombol apa saja untuk melanjutkan',
     'Masuk',
     'Dukunganmu di daftar keinginan Steam\\nmembentuk babak berikutnya dari\\nEXODUSER: HELL LORD',
     'Jadilah yang pertama mengetahui saat kami meluncur',
     'TAMBAHKAN KE DAFTAR KEINGINAN STEAM'),
    ('ZHT',
     '按任意鍵繼續',
     '進入',
     '您在Steam願望清單的支持\\n將塑造\\nEXODUSER: HELL LORD的下一章',
     '搶先獲得官方發布消息',
     '加入STEAM願望清單'),
]

for (lang, any_key, enter, w1, w2, w3) in lobby_data:
    old = f"  '아무 키나 눌러 계속':'{any_key}',\n  '입장':'{enter}',\n}};"
    new = (f"  '아무 키나 눌러 계속':'{any_key}',\n"
           f"  '입장':'{enter}',\n"
           f"  '{KO1}':'{w1}',\n"
           f"  '{KO2}':'{w2}',\n"
           f"  '{KO3}':'{w3}',\n"
           f"}};")
    if old in content:
        content = content.replace(old, new)
        print(f'CAT-67 ✓ {lang}')
    else:
        print(f'CAT-67 ✗ {lang} — NOT FOUND')

# ═══ CAT-68: CIN_LINES 22-language additions ═══
# LANG ORDER: fr, it, ptbr, ro, de, nl, sv, da, no, ru, uk, pl, cs, hu, bg, el, fi, tr, ar, vi, th, id, zht

# Step 1: blank entries — global replace
blank_old = "text:'',en:'',zh:'',ja:'',es:''"
blank_new = ("text:'',en:'',zh:'',ja:'',es:'',"
             "fr:'',it:'',ptbr:'',ro:'',de:'',nl:'',sv:'',da:'',no:'',"
             "ru:'',uk:'',pl:'',cs:'',hu:'',bg:'',el:'',fi:'',tr:'',ar:'',vi:'',th:'',id:'',zht:''")
count_blank = content.count(blank_old)
content = content.replace(blank_old, blank_new)
print(f'CAT-68 blank ✓ {count_blank} entries')

# Step 2: non-blank entries — match by es:'...' text
# Format: ('es_text', 'fr', 'it', 'ptbr', 'ro', 'de', 'nl', 'sv', 'da', 'no', 'ru', 'uk', 'pl', 'cs', 'hu', 'bg', 'el', 'fi', 'tr', 'ar', 'vi', 'th', 'id', 'zht')
cin_lines = [
    ('Un hombre que regresó vivo de la guerra.',
     'Un homme revenu vivant de la guerre.',
     'Un uomo tornato vivo dalla guerra.',
     'Um homem que voltou vivo da guerra.',
     'Un om care s-a întors viu din război.',
     'Ein Mann, der lebend vom Krieg zurückkehrte.',
     'Een man die levend terugkeerde van de oorlog.',
     'En man som återvände levande från kriget.',
     'En mand, der vendte levende hjem fra krigen.',
     'En mann som vendte levende tilbake fra krigen.',
     'Мужчина, вернувшийся живым с войны.',
     'Чоловік, який повернувся живим з війни.',
     'Mężczyzna, który wrócił żywy z wojny.',
     'Muž, který se vrátil živý z války.',
     'Egy férfi, aki élve tért vissza a háborúból.',
     'Мъж, завърнал се жив от войната.',
     'Ένας άνδρας που επέστρεψε ζωντανός από τον πόλεμο.',
     'Mies, joka palasi elossa sodasta.',
     'Savaştan sağ dönen bir adam.',
     'رجلٌ عاد حياً من الحرب.',
     'Một người đàn ông trở về sống sót từ chiến tranh.',
     'ชายผู้รอดชีวิตกลับมาจากสงคราม',
     'Seorang pria yang kembali hidup dari perang.',
     '一個從戰場活著回來的男人。'),
    ('Pero su hogar había sido reducido a cenizas.',
     "Mais sa maison avait brûlé jusqu'au néant.",
     'Ma la sua casa era bruciata fino al nulla.',
     'Mas sua casa havia queimado até o nada.',
     'Dar casa lui arsese până la nimic.',
     'Doch sein Heim war zu Asche verbrannt.',
     'Maar zijn thuis was tot niets verbrand.',
     'Men hans hem hade brunnit till intet.',
     'Men hans hjem var brændt til intet.',
     'Men hjemmet hans hadde brent ned til ingenting.',
     'Но его дом сгорел дотла.',
     'Але його дім згорів дотла.',
     'Ale jego dom spalił się doszczętnie.',
     'Ale jeho domov shořel do tla.',
     'De otthona hamuvá égett.',
     'Но домът му беше изгорял до пепел.',
     'Αλλά το σπίτι του είχε καεί ολοσχερώς.',
     'Mutta hänen kotinsa oli palanut tuhkaksi.',
     'Ama evi yanıp kül olmuştu.',
     'لكن منزله كان قد احترق حتى الرماد.',
     'Nhưng ngôi nhà của anh đã bị thiêu rụi hoàn toàn.',
     'แต่บ้านของเขาถูกเผาจนวอดวาย',
     'Tetapi rumahnya telah terbakar habis.',
     '但家園已化為灰燼。'),
    ('Killu, once a neighbor and friend, had crushed his family.',
     'Killu, jadis voisin et ami, avait écrasé sa famille.',
     'Killu, un tempo vicino e amico, aveva distrutto la sua famiglia.',
     'Killu, outrora vizinho e amigo, havia esmagado sua família.',
     'Killu, odinioară vecin și prieten, îi zdrobise familia.',
     'Killu, einst Nachbar und Freund, hatte seine Familie vernichtet.',
     'Killu, ooit een buur en vriend, had zijn familie verpletterd.',
     'Killu, en gång granne och vän, hade krossat hans familj.',
     'Killu, engang nabo og ven, havde knust hans familie.',
     'Killu, en gang nabo og venn, hadde knust familien hans.',
     'Киллу, некогда сосед и друг, уничтожил его семью.',
     'Кіллу, колись сусід і друг, знищив його родину.',
     'Killu, niegdyś sąsiad i przyjaciel, zniszczył jego rodzinę.',
     'Killu, někdejší soused a přítel, rozdrtil jeho rodinu.',
     'Killu, egykor szomszéd és barát, összetörte a családját.',
     'Килу, някога съсед и приятел, беше смазал семейството му.',
     'Ο Κίλλου, κάποτε γείτονας και φίλος, είχε συντρίψει την οικογένειά του.',
     'Killu, entinen naapuri ja ystävä, oli murskannut hänen perheensä.',
     'Killu, bir zamanlar komşusu ve dostu, ailesini ezdi geçti.',
     'كيلو، الجار والصديق يوماً، سحق عائلته.',
     'Killu, người hàng xóm và bạn bè, đã nghiền nát gia đình anh.',
     'คิลลู เพื่อนบ้านและมิตรสหายในอดีต ทำลายครอบครัวของเขา',
     'Killu, yang dulu tetangga dan teman, menghancurkan keluarganya.',
     '曾是鄰居和朋友的基路，摧毀了他的家族。'),
    ('His wife was taken as a servant and suffered unspeakable horrors,',
     "Sa femme fut emmenée comme servante et souffrit d'horreurs indicibles,",
     'Sua moglie fu portata come serva e subì orrori indicibili,',
     'Sua esposa foi levada como serva e sofreu horrores indescritíveis,',
     'Soția lui a fost luată ca servitoare și a suferit orori de nespus,',
     'Seine Frau wurde als Dienerin verschleppt und erlitt unsägliche Gräuel,',
     'Zijn vrouw werd als dienstmeid meegenomen en leed onuitsprekelijke gruwelen,',
     'Hans hustru togs som tjänstefolk och utsattes för outsägliga fasor,',
     'Hans kone blev taget som tjener og led ubeskrivelige rædsler,',
     'Konen hans ble tatt som tjener og led ubeskrivelige grusomheter,',
     'Его жену взяли в служанки и подвергли несказанным ужасам,',
     'Його дружину забрали як служницю і вона зазнала невимовних жахів,',
     'Jego żona została wzięta jako służąca i cierpiała niewyobrażalne okropności,',
     'Jeho žena byla odvlečena jako služka a trpěla nevýslovnými hrůzami,',
     'Feleségét szolgálónak vitték és kimondhatatlan borzalmakat szenvedett,',
     'Жена му беше взета за прислужница и претърпя неописуеми ужаси,',
     'Η γυναίκα του πάρθηκε ως υπηρέτρια και υπέφερε αναπόφευκτες φρίκες,',
     'Hänen vaimonsa otettiin palvelijaksi ja kärsi sanomattomista kauhuksista,',
     'Karısı hizmetçi olarak götürüldü ve tarif edilemez korkunçluklar yaşadı,',
     'أُخذت زوجته خادمةً فعانت أهوالاً لا توصف،',
     'Vợ anh bị bắt làm nô lệ và phải chịu đựng những điều kinh khủng không thể nói lên,',
     'ภรรยาของเขาถูกพาไปเป็นทาสรับใช้และต้องทนทุกข์ทรมานอย่างแสนสาหัส',
     'Istrinya dibawa sebagai pelayan dan menderita kengerian yang tak terucapkan,',
     '妻子被掳為奴僕，受盡種種凌辱，'),
    ('until she could bear no more and took her own life.',
     "jusqu'à ce qu'elle ne puisse plus supporter et se soit donné la mort.",
     'finché non poteva sopportare più e si tolse la vita.',
     'até que não conseguiu mais suportar e tirou a própria vida.',
     'până nu a mai putut suporta și s-a sinucis.',
     'bis sie nicht mehr konnte und sich das Leben nahm.',
     'totdat ze het niet meer kon dragen en een einde aan haar leven maakte.',
     'tills hon inte kunde bära mer och tog sitt eget liv.',
     'indtil hun ikke kunne bære mere og tog sit eget liv.',
     'til hun ikke orket mer og tok sitt eget liv.',
     'пока она не смогла больше терпеть и покончила с жизнью.',
     'поки вона більше не могла терпіти і позбавила себе життя.',
     'aż nie mogła dłużej wytrzymać i odebrała sobie życie.',
     'dokud nemohla snést více a vzala si život.',
     'míg nem bírta tovább és elvette saját életét.',
     'докато не можа да понесе повече и се самоуби.',
     'μέχρι που δεν άντεχε άλλο και αυτοκτόνησε.',
     'kunnes hän ei jaksanut enää ja otti oman henkensä.',
     'ta ki artık dayanamayıp kendi canına kıyana kadar.',
     'حتى لم تعد تحتمل فأنهت حياتها بنفسها.',
     'cho đến khi không thể chịu đựng thêm và tự kết liễu cuộc đời.',
     'จนกระทั่งเธอทนไม่ไหวอีกต่อไปและลงมือปลิดชีพตัวเอง',
     'hingga ia tidak bisa menanggung lagi dan mengakhiri hidupnya.',
     '最終不堪忍受，自絕了生命。'),
    ("His children were sold into slavery \u2014 their fate unknown.",
     'Ses enfants furent vendus comme esclaves \u2014 leur sort inconnu.',
     'I suoi figli furono venduti come schiavi \u2014 il loro destino sconosciuto.',
     'Seus filhos foram vendidos como escravos \u2014 seu destino, desconhecido.',
     'Copiii lui au fost vânduți ca sclavi \u2014 soarta lor necunoscută.',
     'Seine Kinder wurden als Sklaven verkauft \u2014 ihr Schicksal unbekannt.',
     'Zijn kinderen werden als slaven verkocht \u2014 hun lot onbekend.',
     'Hans barn såldes som slavar \u2014 deras öde okänt.',
     'Hans børn blev solgt som slaver \u2014 deres skæbne ukendt.',
     'Barna hans ble solgt som slaver \u2014 skjebnen ukjent.',
     'Его дети были проданы в рабство \u2014 их судьба неизвестна.',
     'Його дітей продали в рабство \u2014 їхня доля невідома.',
     'Jego dzieci zostały sprzedane w niewolę \u2014 ich los nieznany.',
     'Jeho děti byly prodány do otroctví \u2014 jejich osud neznámý.',
     'Gyermekeit rabszolgának adták el \u2014 sorsuk ismeretlen.',
     'Децата му бяха продадени в робство \u2014 съдбата им неизвестна.',
     'Τα παιδιά του πουλήθηκαν ως σκλάβοι \u2014 η μοίρα τους άγνωστη.',
     'Hänen lapsensa myytiin orjiksi \u2014 heidän kohtalonsa tuntematon.',
     'Çocukları köle olarak satıldı \u2014 kaderleri bilinmiyor.',
     'بيع أطفاله عبيداً \u2014 مجهول المصير.',
     'Con cái của anh bị bán làm nô lệ \u2014 số phận của họ không ai biết.',
     'ลูกๆ ของเขาถูกขายเป็นทาส \u2014 ชะตากรรมของพวกเขาไม่มีใครรู้',
     'Anak-anaknya dijual sebagai budak \u2014 nasib mereka tidak diketahui.',
     '孩子們被賣為奴隸，下落不明。'),
    ('His elderly parents were imprisoned and starved to death.',
     'Ses vieux parents furent emprisonnés et moururent de faim.',
     'I suoi anziani genitori furono imprigionati e morirono di fame.',
     'Seus pais idosos foram encarcerados e morreram de fome.',
     'Părinții lui bătrâni au fost închiși și au murit de foame.',
     'Seine alten Eltern wurden eingesperrt und verhungerten.',
     'Zijn bejaarde ouders werden gevangengezet en stierven van de honger.',
     'Hans gamla föräldrar fängslades och svalt ihjäl.',
     'Hans gamle forældre blev fængslet og sultede ihjel.',
     'Foreldrene hans ble fengslet og sultet i hjel.',
     'Его пожилые родители были заключены в тюрьму и умерли от голода.',
     "Його літні батьки були ув'язнені і померли від голоду.",
     'Jego starzy rodzice zostali uwięzieni i zagłodzeni na śmierć.',
     'Jeho staří rodiče byli uvězněni a zemřeli hlady.',
     'Idős szüleit bebörtönözték és éhen haltak.',
     'Старите му родители бяха затворени и умряха от глад.',
     'Οι ηλικιωμένοι γονείς του φυλακίστηκαν και πέθαναν από πείνα.',
     'Hänen vanhat vanhempansa vangittiin ja kuolivat nälkään.',
     'Yaşlı ebeveynleri hapsedildi ve açlıktan öldü.',
     'سُجن والداه العجوزان ومات جوعاً.',
     'Cha mẹ già của anh bị cầm tù và chết đói.',
     'พ่อแม่ผู้เฒ่าของเขาถูกจับขังและอดอาหารจนตาย',
     'Orang tua tuanya dipenjarakan dan mati kelaparan.',
     '年邁的父母被關進牢獄，活活餓死。'),
    ('Everyone in the Killu household knew.',
     'Tous dans la maison de Killu le savaient.',
     'Tutti nella casa di Killu lo sapevano.',
     'Todos na casa de Killu sabiam.',
     'Toți din casa lui Killu știau.',
     'Alle im Haus von Killu wussten es.',
     'Iedereen in het huis van Killu wist het.',
     'Alla i Killus hushåll visste.',
     'Alle i Killus husstand vidste det.',
     'Alle i Killus husstand visste det.',
     'Все в доме Киллу знали.',
     'Всі в домі Кіллу знали.',
     'Wszyscy w domu Killu wiedzieli.',
     'Všichni v Killuově domě věděli.',
     'Mindenki Killu házában tudta.',
     'Всички в дома на Килу знаеха.',
     'Όλοι στο σπίτι του Κίλλου ήξεραν.',
     'Kaikki Killun taloudessa tiesivät.',
     'Killu hanedanındaki herkes biliyordu.',
     'كل من في بيت كيلو كان يعلم.',
     'Tất cả mọi người trong gia đình Killu đều biết.',
     'ทุกคนในตระกูลคิลลูรู้ดี',
     'Semua orang di keluarga Killu tahu.',
     '基路家族的所有人都知道。'),
    ('Thirty-one of them saw everything and looked away.',
     'Trente et un d\'entre eux ont tout vu et ont détourné le regard.',
     "Trentuno di loro videro tutto e guardarono dall'altra parte.",
     'Trinta e um deles viram tudo e desviaram o olhar.',
     'Treizeci și unu dintre ei au văzut totul și au întors privirea.',
     'Einunddreißig von ihnen sahen alles und schauten weg.',
     'Een en dertig van hen zagen alles en keken de andere kant op.',
     'Trettioett av dem såg allt och tittade bort.',
     'Enogtredivet af dem så alt og så den anden vej.',
     'Trettien av dem så alt og så den andre veien.',
     'Тридцать один из них видел всё и отвернулся.',
     'Тридцять один із них бачили всe і відвернулися.',
     'Trzydziestu jeden z nich widziało wszystko i odwróciło wzrok.',
     'Třicet jedna z nich vidělo vše a odvrátilo pohled.',
     'Harmincegy közülük mindent látott és elfordult.',
     'Тридесет и един от тях видяха всичко и погледнаха настрани.',
     'Τριάντα ένας από αυτούς είδε τα πάντα και κοίταξε αλλού.',
     'Kolmekymmentäyksi heistä näki kaiken ja katsoi poispäin.',
     'Otuz birisi her şeyi gördü ve görmezden geldi.',
     'واحد وثلاثون منهم رأوا كل شيء وتجاهلوه.',
     'Ba mươi mốt người trong số họ thấy tất cả và nhìn đi chỗ khác.',
     'สามสิบเอ็ดคนในหมู่พวกเขาเห็นทุกอย่างแต่แกล้งทำเป็นไม่รู้',
     'Tiga puluh satu dari mereka melihat segalanya dan berpaling.',
     '三十一人目睹一切，卻視而不見。'),
    ('That night, he killed every last one of them.',
     'Cette nuit-là, il les tua tous jusqu\'au dernier.',
     "Quella notte, li uccise tutti fino all'ultimo.",
     'Naquela noite, ele matou todos até o último.',
     'În acea noapte, i-a ucis pe toți până la ultimul.',
     'In jener Nacht tötete er sie alle bis auf den letzten.',
     'Die nacht doodde hij ze allemaal tot de laatste.',
     'Den natten dödade han var och en av dem.',
     'Den nat dræbte han dem alle til den sidste.',
     'Den natten drepte han dem alle til siste mann.',
     'Той ночью он убил всех до единого.',
     'Тієї ночі він убив усіх до останнього.',
     'Tej nocy zabił ich wszystkich do jednego.',
     'Tu noc je všechny do jednoho zabil.',
     'Azon az éjszakán mindet megölte az utolsóig.',
     'Онази нощ той уби всеки от тях до последния.',
     'Εκείνη τη νύχτα, τους σκότωσε όλους μέχρι τον τελευταίο.',
     'Sinä yönä hän tappoi jokaisen heistä viimeistä myöten.',
     'O gece, hepsini sonuncusuna kadar öldürdü.',
     'في تلك الليلة، قتل كل واحد منهم حتى آخرهم.',
     'Đêm đó, anh giết tất cả bọn họ đến người cuối cùng.',
     'คืนนั้น เขาสังหารพวกเขาทุกคนจนคนสุดท้าย',
     'Malam itu, ia membunuh semua orang hingga yang terakhir.',
     '那天夜裡，他殺光了基路全族。'),
    ("He cut off Killu's limbs with a blade,",
     'Il coupa les membres de Killu avec une lame,',
     'Tagliò le membra di Killu con una lama,',
     'Ele cortou os membros de Killu com uma lâmina,',
     'I-a tăiat membrele lui Killu cu o lamă,',
     'Er schlug Killus Gliedmaßen mit einer Klinge ab,',
     "Hij sneed Killu's ledematen af met een mes,",
     'Han högg av Killus lemmar med ett blad,',
     'Han huggede Killus lemmer af med en klinge,',
     'Han hugget av Killus lemmer med et blad,',
     'Он отрубил Киллу конечности клинком,',
     'Він відрубав Кіллу кінцівки клинком,',
     'Odciął kończyny Killu ostrzem,',
     'Usekal Killuovi končetiny čepelí,',
     'Pengével levágta Killu végtagjait,',
     'Отряза крайниците на Килу с острие,',
     'Έκοψε τα άκρα του Κίλλου με λεπίδα,',
     'Hän irrotti Killun raajat terällä,',
     "Killu'nun uzuvlarını bir bıçakla kesti,",
     'قطع أطراف كيلو بالسيف،',
     'Anh cắt đứt tay chân của Killu bằng lưỡi dao,',
     'เขาตัดแขนขาของคิลลูด้วยดาบ',
     'Ia memotong anggota tubuh Killu dengan pisau,',
     '用刀砍斷了基路的四肢，'),
    ('cauterized the wounds with fire,',
     'cautérisé les plaies avec du feu,',
     'cauterizzò le ferite con il fuoco,',
     'cauterizou as feridas com fogo,',
     'a cauterizat rănile cu foc,',
     'die Wunden mit Feuer kauterisiert,',
     'de wonden gecauteriseerd met vuur,',
     'kauteriserade såren med eld,',
     'kauteriserede sårene med ild,',
     'kauteriserte sårene med ild,',
     'прижёг раны огнём,',
     'припік рани вогнем,',
     'kauteryzował rany ogniem,',
     'kauterizoval rány ohněm,',
     'tűzzel kauterizálta a sebeket,',
     'каутеризира раните с огън,',
     'καυτηρίασε τις πληγές με φωτιά,',
     'kauterisoi haavat tulella,',
     'yaraları ateşle dağladı,',
     'وكوى الجراح بالنار،',
     'đốt cháy vết thương bằng lửa,',
     'จี้แผลด้วยไฟ',
     'membakar luka dengan api,',
     '用火為他止住了血，'),
    ('and kept him alive for a long, long time.',
     'et l\'a maintenu en vie pendant longtemps, très longtemps.',
     'e lo tenne in vita per un lungo, lunghissimo tempo.',
     'e o manteve vivo por um longo, longo tempo.',
     'și l-a ținut în viață mult, mult timp.',
     'und ihn lange, lange am Leben gehalten.',
     'en hem lang, lang in leven gehouden.',
     'och höll honom vid liv länge, länge.',
     'og holdt ham i live i lang, lang tid.',
     'og holdt ham i live i lang, lang tid.',
     'и держал его живым долго, очень долго.',
     'і тримав його живим довго, дуже довго.',
     'i trzymał go przy życiu przez długi, bardzo długi czas.',
     'a udržoval ho naživu dlouho, velmi dlouho.',
     'és sokáig, nagyon sokáig életben tartotta.',
     'и го държа жив дълго, много дълго.',
     'και τον κράτησε ζωντανό για πολύ, πολύ καιρό.',
     'ja piti hänet elossa pitkään, hyvin pitkään.',
     've onu uzun, uzun süre hayatta tuttu.',
     'وأبقاه حياً لفترة طويلة، طويلة جداً.',
     'và giữ anh ta sống sót trong một thời gian dài, rất dài.',
     'และรักษาชีวิตเขาไว้นานมาก นานมากจริงๆ',
     'dan membuatnya tetap hidup untuk waktu yang lama, sangat lama.',
     '讓他活了很久很久。'),
    ('"Remember."',
     '"Souviens-toi."',
     '"Ricorda."',
     '"Lembra."',
     '"Amintește-ți."',
     '"Erinnere dich."',
     '"Onthoud het."',
     '"Kom ihåg."',
     '"Husk det."',
     '"Husk det."',
     '"Запомни."',
     '"Пам\'ятай."',
     '"Pamiętaj."',
     '"Pamatuj si."',
     '"Emlékezz."',
     '"Помни."',
     '"Θυμήσου."',
     '"Muista."',
     '"Unutma."',
     '"تذكّر."',
     '"Hãy nhớ lấy."',
     '"จงจำไว้"',
     '"Ingat."',
     '"記住。"'),
    ('"And regret it even in hell."',
     '"Et regrette-le même en enfer."',
     '"E pentiti anche all\'inferno."',
     '"E se arrependa mesmo no inferno."',
     '"Și regretă chiar și în iad."',
     '"Und bereue es noch in der Hölle."',
     '"En betreur het zelfs in de hel."',
     '"Och ångra det även i helvetet."',
     '"Og fortryd det selv i helvede."',
     '"Og angre det selv i helvete."',
     '"И сожалей об этом даже в аду."',
     '"І жалкуй про це навіть у пеклі."',
     '"I żałuj tego nawet w piekle."',
     '"A lituji toho i v pekle."',
     '"És bánd meg még a pokolban is."',
     '"И съжалявай за това дори в ада."',
     '"Και να το μετανιώσεις ακόμα και στην κόλαση."',
     '"Ja katuvan sitä jopa helvetissä."',
     '"Ve cehennemde bile pişman ol."',
     '"وانتدم على ذلك حتى في الجحيم."',
     '"Và hãy hối hận về điều đó ngay cả khi ở địa ngục."',
     '"และจงเสียใจแม้ในนรก"',
     '"Dan sesali bahkan di neraka."',
     '"在地獄裡也要後悔。"'),
    ('And so he fell into hell.',
     'Et ainsi il tomba en enfer.',
     "Et ainsi il tomba en enfer.",
     'E assim ele caiu no inferno.',
     'Și astfel căzu în iad.',
     'Und so fiel er in die Hölle.',
     'En zo viel hij in de hel.',
     'Och så föll han ned i helvetet.',
     'Og således faldt han ned i helvede.',
     'Og slik falt han ned i helvete.',
     'И так он упал в ад.',
     'І так він впав у пекло.',
     'I tak wpadł do piekła.',
     'A tak padl do pekla.',
     'És így esett a pokolba.',
     'И така той падна в ада.',
     'Και έτσι έπεσε στην κόλαση.',
     'Ja niin hän putosi helvettiin.',
     'Ve böylece cehenneme düştü.',
     'وهكذا سقط في الجحيم.',
     'Và thế là anh rơi xuống địa ngục.',
     'แล้วเขาก็ตกลงไปในนรก',
     'Dan begitulah ia jatuh ke neraka.',
     '然後，他墜入了地獄。'),
    ('"...This is but one tale among countless avengers."',
     '"...Ceci n\'est qu\'une histoire parmi d\'innombrables vengeurs."',
     '"...Questa è solo una storia tra innumerevoli vendicatori."',
     '"...Esta é apenas uma história entre incontáveis vingadores."',
     '"...Aceasta este doar o poveste dintre nenumărații răzbunători."',
     '"...Dies ist nur eine Geschichte unter zahllosen Rächern."',
     '"...Dit is slechts één verhaal onder talloze wrekers."',
     '"...Detta är bara en berättelse bland oräkneliga hämndare."',
     '"...Dette er blot én fortælling blandt utallige hævnere."',
     '"...Dette er bare én fortelling blant utallige hevnere."',
     '"...Это лишь одна история среди бесчисленных мстителей."',
     '"...Це лише одна історія серед незліченних месників."',
     '"...To tylko jedna historia wśród niezliczonych mścicieli."',
     '"...Toto je jen jeden příběh z nespočetných mstitelů."',
     '"...Ez csupán egyetlen történet számtalan bosszúálló közül."',
     '"...Това е само една история сред безброй отмъстители."',
     '"...Αυτή είναι μόνο μια ιστορία ανάμεσα σε αμέτρητους εκδικητές."',
     '"...Tämä on vain yksi tarina lukemattomien kostajaein joukossa."',
     '"...Bu, sayısız intikamcı arasındaki tek bir hikayedir."',
     '"...هذه مجرد حكاية واحدة بين منتقمين لا يحصون."',
     '"...Đây chỉ là một câu chuyện trong vô số những người báo thù."',
     '"...นี่เป็นเพียงเรื่องราวหนึ่งในหมู่ผู้แก้แค้นนับไม่ถ้วน"',
     '"...Ini hanyalah satu kisah di antara banyak pendendam."',
     '"……這不過是無數復仇者中一人的故事。"'),
    ('"Every day, new souls fall into hell\'s labyrinth."',
     '"Chaque jour, de nouvelles âmes tombent dans le labyrinthe de l\'enfer."',
     '"Ogni giorno, nuove anime cadono nel labirinto dell\'inferno."',
     '"Todo dia, novas almas caem no labirinto do inferno."',
     '"În fiecare zi, suflete noi cad în labirintul iadului."',
     '"Jeden Tag fallen neue Seelen in das Labyrinth der Hölle."',
     '"Elke dag vallen nieuwe zielen in het labyrint van de hel."',
     '"Varje dag faller nya själar in i helvetets labyrint."',
     '"Hver dag falder nye sjæle ned i helvedes labyrint."',
     '"Hver dag faller nye sjeler ned i helvetets labyrint."',
     '"Каждый день новые души падают в лабиринт ада."',
     '"Щодня нові душі падають у лабіринт пекла."',
     '"Każdego dnia nowe dusze wpadają do labiryntu piekła."',
     '"Každý den padají nové duše do labyrintu pekla."',
     '"Minden nap új lelkek esnek a pokol labirintusába."',
     '"Всеки ден нови души падат в лабиринта на ада."',
     '"Κάθε μέρα, νέες ψυχές πέφτουν στον λαβύρινθο της κόλασης."',
     '"Joka päivä uusia sieluja putoaa helvetin labyrinttiin."',
     '"Her gün, cehennemin labirentine yeni ruhlar düşüyor."',
     '"كل يوم تسقط أرواح جديدة في متاهة الجحيم."',
     '"Mỗi ngày, những linh hồn mới rơi vào mê cung của địa ngục."',
     '"ทุกวัน จิตวิญญาณใหม่ตกลงสู่เขาวงกตของนรก"',
     '"Setiap hari, jiwa-jiwa baru jatuh ke dalam labirin neraka."',
     '"每天都有新的靈魂墜入地獄的迷宮。"'),
    ('"Those consumed by rage, driven mad by injustice, those who lost love..."',
     '"Ceux consumés par la rage, rendus fous par l\'injustice, ceux qui ont perdu l\'amour..."',
     '"Quelli consumati dalla rabbia, impazziti dall\'ingiustizia, quelli che hanno perso l\'amore..."',
     '"Aqueles consumidos pela raiva, enlouquecidos pela injustiça, aqueles que perderam o amor..."',
     '"Cei mistuiți de furie, nebuni de nedreptate, cei care au pierdut iubirea..."',
     '"Die vom Zorn Verzehrten, vom Unrecht in den Wahnsinn Getriebenen, die die Liebe verloren..."',
     '"Die verteerd werden door woede, gek gemaakt door onrecht, degenen die de liefde verloren..."',
     '"De som förtärdes av raseri, drevs till galenskap av orättvisa, de som förlorade kärleken..."',
     '"De der fortæres af raseri, drives til vanvid af uretfærdighed, de der mister kærlighed..."',
     '"De som fortæres av raseri, drives til galskap av urettferdighet, de som mistet kjærligheten..."',
     '"Те, кого пожирал гнев, кого сводила с ума несправедливость, кто потерял любовь..."',
     '"Ті, кого пожирав гнів, кого зводила з розуму несправедливість, хто втратив любов..."',
     '"Ci strawieni gniewem, doprowadzeni do szaleństwa przez niesprawiedliwość, ci którzy utracili miłość..."',
     '"Ti strávení hněvem, hnáni k šílenství nespravedlností, ti kteří ztratili lásku..."',
     '"Akiket az elméjük emésztett, az igazságtalanság megőrjítette, akik elveszítették a szerelmet..."',
     '"Тези, изпепелени от гняв, побъркани от несправедливост, тези, загубили любовта..."',
     '"Εκείνοι που κατακλύστηκαν από μανία, τρελάθηκαν από αδικία, εκείνοι που έχασαν την αγάπη..."',
     '"Ne joita raivo kulutti, oikeudenmukaisuuden puute ajoi hulluksi, ne jotka menettivät rakkauden..."',
     '"Öfkeyle yakıp yıkılanlar, haksızlıkla delirtilmiş olanlar, sevgisini kaybedenler..."',
     '"أولئك الذين أحرقهم الغضب، أجنّهم الظلم، والذين فقدوا الحب..."',
     '"Những người bị cơn thịnh nộ thiêu đốt, điên loạn vì bất công, những người đã mất đi tình yêu..."',
     '"ผู้ที่ถูกความโกรธเผาไหม้ บ้าคลั่งเพราะความอยุติธรรม ผู้ที่สูญเสียความรัก..."',
     '"Mereka yang dilahap amarah, dilanda kegilaan oleh ketidakadilan, mereka yang kehilangan cinta..."',
     '"被憤怒填滿的人、因冤屈而瘋狂的人、失去愛的人……"'),
    ('"Why have you come to hell?"',
     '"Pourquoi es-tu venu en enfer ?"',
     '"Perché sei venuto all\'inferno?"',
     '"Por que você veio ao inferno?"',
     '"De ce ai venit în iad?"',
     '"Warum bist du in die Hölle gekommen?"',
     '"Waarom ben je naar de hel gekomen?"',
     '"Varför har du kommit till helvetet?"',
     '"Hvorfor er du kommet til helvede?"',
     '"Hvorfor har du kommet til helvete?"',
     '"Зачем ты пришёл в ад?"',
     '"Навіщо ти прийшов до пекла?"',
     '"Dlaczego przyszedłeś do piekła?"',
     '"Proč jsi přišel do pekla?"',
     '"Miért jöttél a pokolba?"',
     '"Защо дойде в ада?"',
     '"Γιατί ήρθες στην κόλαση;"',
     '"Miksi olet tullut helvettiin?"',
     '"Neden cehenneme geldin?"',
     '"لماذا أتيتَ إلى الجحيم؟"',
     '"Tại sao ngươi lại đến địa ngục?"',
     '"เจ้ามาสู่นรกทำไม?"',
     '"Mengapa kamu datang ke neraka?"',
     '"你為什麼來到地獄？"'),
    ('"Escape from hell, sinner."',
     '"Échappe de l\'enfer, pécheur."',
     '"Fuggi dall\'inferno, peccatore."',
     '"Escape do inferno, pecador."',
     '"Evadează din iad, păcătosule."',
     '"Entfliehe der Hölle, Sünder."',
     '"Ontvlucht de hel, zondaar."',
     '"Fly från helvetet, syndare."',
     '"Flygt fra helvede, synder."',
     '"Flykt fra helvete, synder."',
     '"Сбеги из ада, грешник."',
     '"Тікай з пекла, грішник."',
     '"Ucieknij z piekła, grzeszniku."',
     '"Uteč z pekla, hříšníku."',
     '"Menekülj el a pokolból, bűnös."',
     '"Избягай от ада, грешнику."',
     '"Δράπε από την κόλαση, αμαρτωλέ."',
     '"Pakene helvetistä, syntinen."',
     '"Cehennemden kaç, günahkâr."',
     '"اهرب من الجحيم أيها المذنب."',
     '"Trốn thoát khỏi địa ngục, kẻ tội lỗi."',
     '"หลบหนีออกจากนรกซะ คนบาป"',
     '"Larilah dari neraka, pendosa."',
     '"逃出地獄吧，罪人。"'),
]

LANG_KEYS = ['fr','it','ptbr','ro','de','nl','sv','da','no','ru','uk','pl','cs','hu','bg','el','fi','tr','ar','vi','th','id','zht']

for entry in cin_lines:
    es_text = entry[0]
    translations = entry[1:]  # 23 values: fr, it, ptbr, ro, de, nl, sv, da, no, ru, uk, pl, cs, hu, bg, el, fi, tr, ar, vi, th, id, zht

    # Build the new lang fields string
    lang_fields = ','.join(f"{k}:'{v}'" for k, v in zip(LANG_KEYS, translations))

    # Find es:'...' followed by comma, and insert new fields after it
    old_es = f"es:'{es_text}',"
    new_es = f"es:'{es_text}',{lang_fields},"

    if old_es in content:
        content = content.replace(old_es, new_es)
        print(f'CAT-68 ✓ {es_text[:40]}...')
    else:
        print(f'CAT-68 ✗ NOT FOUND: {es_text[:40]}...')

with open('G:/hell/index.html', 'w', encoding='utf-8') as f:
    f.write(content)

print('Done!')
