// Translation generator for ar, vi, th, id
const fs = require('fs');
const data = JSON.parse(fs.readFileSync('_en_data.json','utf8'));

// Translation tables: EN -> {ar, vi, th, id}
// We translate from English meanings to each target language

const translations = {};

// Build translation map from English values
const enEntries = Object.entries(data.main);

// For each language, we need a map from Korean key -> translated value
const ar = {}, vi = {}, th = {}, id = {};

for (const [k, en] of enEntries) {
  ar[k] = translateToAr(k, en);
  vi[k] = translateToVi(k, en);
  th[k] = translateToTh(k, en);
  id[k] = translateToId(k, en);
}

function translateToAr(k, en) {
  const m = arMap[en];
  if (m !== undefined) return m;
  // Check if it starts with emoji
  const emojiMatch = en.match(/^([\p{Emoji_Presentation}\p{Emoji}\u200d\ufe0f\u20e3\u2600-\u27bf\u2b50\u2b55\u231a-\u23ff\u2702-\u27b0\u2934-\u2935\u25aa-\u25fe\u2190-\u21ff\u2300-\u23ff\u2460-\u24ff\u2500-\u25ff\u2700-\u27bf\u2900-\u297f\u2b00-\u2bff\u3000-\u303f\u3200-\u33ff]+\s?)/u);
  if (emojiMatch) {
    const prefix = emojiMatch[1];
    const rest = en.slice(prefix.length);
    const translated = arMap[rest];
    if (translated !== undefined) return prefix + translated;
  }
  return en; // fallback to English
}
function translateToVi(k, en) {
  const m = viMap[en];
  if (m !== undefined) return m;
  const emojiMatch = en.match(/^([\p{Emoji_Presentation}\p{Emoji}\u200d\ufe0f\u20e3\u2600-\u27bf\u2b50\u2b55\u231a-\u23ff\u2702-\u27b0\u2934-\u2935\u25aa-\u25fe\u2190-\u21ff\u2300-\u23ff\u2460-\u24ff\u2500-\u25ff\u2700-\u27bf\u2900-\u297f\u2b00-\u2bff\u3000-\u303f\u3200-\u33ff]+\s?)/u);
  if (emojiMatch) {
    const prefix = emojiMatch[1];
    const rest = en.slice(prefix.length);
    const translated = viMap[rest];
    if (translated !== undefined) return prefix + translated;
  }
  return en;
}
function translateToTh(k, en) {
  const m = thMap[en];
  if (m !== undefined) return m;
  const emojiMatch = en.match(/^([\p{Emoji_Presentation}\p{Emoji}\u200d\ufe0f\u20e3\u2600-\u27bf\u2b50\u2b55\u231a-\u23ff\u2702-\u27b0\u2934-\u2935\u25aa-\u25fe\u2190-\u21ff\u2300-\u23ff\u2460-\u24ff\u2500-\u25ff\u2700-\u27bf\u2900-\u297f\u2b00-\u2bff\u3000-\u303f\u3200-\u33ff]+\s?)/u);
  if (emojiMatch) {
    const prefix = emojiMatch[1];
    const rest = en.slice(prefix.length);
    const translated = thMap[rest];
    if (translated !== undefined) return prefix + translated;
  }
  return en;
}
function translateToId(k, en) {
  const m = idMap[en];
  if (m !== undefined) return m;
  const emojiMatch = en.match(/^([\p{Emoji_Presentation}\p{Emoji}\u200d\ufe0f\u20e3\u2600-\u27bf\u2b50\u2b55\u231a-\u23ff\u2702-\u27b0\u2934-\u2935\u25aa-\u25fe\u2190-\u21ff\u2300-\u23ff\u2460-\u24ff\u2500-\u25ff\u2700-\u27bf\u2900-\u297f\u2b00-\u2bff\u3000-\u303f\u3200-\u33ff]+\s?)/u);
  if (emojiMatch) {
    const prefix = emojiMatch[1];
    const rest = en.slice(prefix.length);
    const translated = idMap[rest];
    if (translated !== undefined) return prefix + translated;
  }
  return en;
}

// ===== ARABIC translations =====
const arMap = {
// Stage/Boss
'Rotten Forest':'الغابة المتعفنة','Forest Warden':'حارس الغابة','Toxic Mushroom Giant':'عملاق الفطر السام','Forest Hunter':'صياد الغابة','Parasitic Beast':'الوحش الطفيلي',
'CH1 — Rotten Forest':'الفصل 1 — الغابة المتعفنة','CH2 — Worm Nest':'الفصل 2 — عش الديدان','CH3 — Ice Cavern':'الفصل 3 — كهف الجليد',
'CH4 — Infernal Wastes':'الفصل 4 — أراضي اللهب','CH5 — Hell Legion':'الفصل 5 — فيلق الجحيم','CH6 — Apostle\'s Den':'الفصل 6 — وكر الرسول','CH7 — Hell Citadel':'الفصل 7 — قلعة الجحيم',
'Escaped!':'هربت!','kills':'قتل','Kills':'قتل','EXP':'خبرة','Max Combo':'أقصى كومبو',
// Tutorial Crow
"Wake up. The goddess didn't send you here to die.":'استيقظ. الإلهة لم ترسلك هنا لتموت.',
"Good, you've got instinct. Keep swinging!":'جيد، لديك غريزة. واصل الضرب!',
"Press Shift. That's the harpoon. Stick it and ride!":'اضغط Shift. هذا الحربون. اغرسه وانطلق!',
"You're invincible while the harpoon pulls you. Use it when things get rough.":'أنت لا تُقهر أثناء سحب الحربون. استخدمه عند الخطر.',
'...Hurts? Of course. This is hell.':'...يؤلم؟ بالطبع. هذا الجحيم.',
'Press Q! Create a shield with malice.':'اضغط Q! اصنع درعاً بالحقد.',
'Forget surviving without a shield.':'انسَ البقاء بدون درع.',
'Right click to parry. Press it right before the enemy hits!':'انقر يميناً للصد. اضغطه قبل ضربة العدو مباشرة!',
"Can't parry? Just hit them. Not dying is enough.":'لا تستطيع الصد؟ اضربهم فقط. عدم الموت يكفي.',
"There you go! You're getting the hang of it.":'هكذا! بدأت تتقنها.',
'One down.':'واحد سقط.',
"That's the ghost crossbow. Say hello.":'هذا القوس الشبحي. قل مرحباً.',
"Don't fear red bullets. Malice is strong.":'لا تخف من الطلقات الحمراء. الحقد قوي.',
'Parry them back, use Q shield too! Master your malice!':'اصدها، استخدم درع Q أيضاً! أتقن حقدك!',
"Rainbow shots can't be parried! Dodge!":'الطلقات القوسية لا يمكن صدها! تفادَ!',
"You're bleeding out. Shift. Get out.":'تنزف. Shift. اخرج.',
'You have potions! Number keys!':'لديك جرعات! مفاتيح الأرقام!',
'Right click. Strike when their wrist bends.':'انقر يميناً. اضرب عندما ينثني معصمهم.',
'Red bullets are chunks of malice. Deflect and use them.':'الطلقات الحمراء كتل حقد. اصدها واستخدمها.',
'Just dodge the rainbow! Parry everything else!':'تفادَ القوس فقط! اصد كل شيء آخر!',
'Q shield can parry too!':'درع Q يمكنه الصد أيضاً!',
'Danger! Shift chain dash to escape!!':'خطر! Shift اندفاع سلسلة للهروب!!',
'Shift! Chain dash is movement! Invincible while pulled!':'Shift! اندفاع السلسلة حركة! لا تُقهر أثناء السحب!',
'Skill points ready! Press K to learn skills!':'نقاط المهارة جاهزة! اضغط K لتعلم المهارات!',
'Read the elements. Hit weaknesses for double damage.':'اقرأ العناصر. اضرب نقاط الضعف لضرر مضاعف.',
'Press K! You can learn skills!':'اضغط K! يمكنك تعلم المهارات!',
'Press C for stats! Passives too~':'اضغط C للإحصائيات! والسلبيات أيضاً~',
'Press G. Upgrade gear at the forge.':'اضغط G. طوّر العتاد في المسبك.',
'F key is a skill slot too! Use L to assign~':'مفتاح F خانة مهارة أيضاً! استخدم L للتعيين~',
"Z. That's your ultimate. Use it wisely.":'Z. هذه ضربتك القصوى. استخدمها بحكمة.',
'L-CTRL for Ghost Walk or Ice Orb!':'L-CTRL للمشي الشبحي أو كرة الجليد!',
'Press L. Organize your skill slots.':'اضغط L. نظّم خانات مهاراتك.',
"Bag's about to burst! Press V to stash!":'الحقيبة على وشك الانفجار! اضغط V للتخزين!',
'ESC for settings! Difficulty, auto-potions~':'ESC للإعدادات! الصعوبة، الجرعات التلقائية~',
// Tutorial Cat
'...Still alive. Try hitting those with left click.':'...لا تزال حياً. حاول ضرب تلك بالنقر الأيسر.',
'...You can hit. But can you dodge?':'...تستطيع الضرب. لكن هل تستطيع التفادي؟',
"Hmph, miss the harpoon and it's wasted.":'همف، أخطئ الحربون وسيضيع.',
'...Just luck. Probably.':'...مجرد حظ. ربما.',
'...Smells like meat. Not bad.':'...رائحة لحم. ليست سيئة.',
"...It can't talk.":'...لا يستطيع الكلام.',
"Touch them because they're pretty? You'll die.":'تلمسهم لأنهم جميلون؟ ستموت.',
'Throw the harpoon! Invincible while pulled!':'ارمِ الحربون! لا تُقهر أثناء السحب!',
"...Drink or don't. It's your life.":'...اشرب أو لا. حياتك.',
"That's a parry! Timing is everything~":'هذا صد! التوقيت هو كل شيء~',
'Fire beats Ice! Lightning beats Dark! Remember!':'النار تغلب الجليد! البرق يغلب الظلام! تذكّر!',
"...Frozen ones don't last long.":'...المجمدون لا يدومون طويلاً.',
'Frozen! 1.5x damage while frozen!':'مجمد! 1.5× ضرر أثناء التجمد!',
"...Choose your power. You can't have it all.":'...اختر قوتك. لا يمكنك الحصول على الكل.',
'Raise your stats. If you want to live.':'ارفع إحصائياتك. إن أردت البقاء.',
'Good gear needs upgrades for true potential!':'العتاد الجيد يحتاج تطويراً لإمكانيته الحقيقية!',
'...Fill your slots. Empty hands mean death.':'...املأ خاناتك. الأيدي الفارغة تعني الموت.',
'Press Z for massive damage! Long cooldown, time it!':'اضغط Z لضرر هائل! فترة تهدئة طويلة، وقّتها!',
'Ctrl. One more card for emergencies.':'Ctrl. ورقة إضافية للطوارئ.',
'So many skills~ Use L to assign!':'الكثير من المهارات~ استخدم L للتعيين!',
"...Stash what's too good to drop.":'...خزّن ما هو ثمين جداً لرميه.',
'...Surviving alone is impressive. Check settings.':'...البقاء وحده مثير للإعجاب. تحقق من الإعدادات.',
// System
'Not enough MP!':'لا يكفي MP!','Not enough ST!':'لا يكفي ST!','Not enough Malice!':'لا يكفي حقد!',
'Charging...':'جارٍ الشحن...','Cancel':'إلغاء','Select an item':'اختر عنصراً',
'Malice depleted...':'نفد الحقد...','Inscription found...':'عُثر على نقش...',
'HP Potion!':'جرعة HP!','HP Potion +1':'جرعة HP +1','HP Potion +2':'جرعة HP +2',
'HP/MP/ST Restored!':'تم استعادة HP/MP/ST!','Chest Opened!':'فُتح الصندوق!',
'Drowning!':'غرق!','Blood Pool!':'بركة دم!','Toxic Blood!':'دم سام!','Grabbed!':'أُمسك!',
'Combo End':'نهاية الكومبو',
// Status
'Frozen!':'مجمد!','Burning!':'احتراق!','Poison!':'سم!','Shocked!':'صُعق!',
'Stunned!':'مذهول!','Sealed!':'مختوم!','Pierce!':'اختراق!',
// Skills
'Ki Slash':'قطع الطاقة','Malice Orb':'كرة الحقد','Whirlwind':'الزوبعة','Detonate':'تفجير',
'Blade Parry':'صد النصل','Needle Barrage':'وابل الإبر','Annihilation Beam':'شعاع الإبادة',
'Elemental Seeker':'الباحث العنصري','Malice Guardian':'حارس الحقد','Malice Hunt':'صيد الحقد',
'Vortex Summon':'استدعاء الدوامة','Bone Tomb':'قبر العظام','Holy Blast':'انفجار مقدس',
'Black Star':'النجم الأسود','Lava Summon':'استدعاء الحمم','Execution':'إعدام','Demon Revive':'بعث شيطاني',
'Crimson Bloom':'الزهرة القرمزية','Ice Orb':'كرة الجليد','Ghost Walk':'المشي الشبحي',
'Needle Barrage II':'وابل الإبر II','Arcane Barrage':'وابل سحري','Arc Laser':'ليزر القوس','Hellfire Beam':'شعاع نار الجحيم',
'Inferno Array':'مصفوفة الجحيم','Plague Blade':'نصل الوباء','Malice Storm':'عاصفة الحقد',
'Dark Pillar':'عمود الظلام','Sacred Domain':'نطاق مقدس','Binding Domain':'نطاق القيد',
'Ice Storm':'عاصفة الجليد','Giant Slam':'ضربة عملاقة','Giant Slam II':'ضربة عملاقة II',
'Chain Blaze':'اشتعال السلسلة','Chain Crush':'سحق السلسلة','Chain Bladewing':'جناح نصل السلسلة',
'Aegis of Peace':'درع السلام','Repentance':'التوبة','Shield Wing':'جناح الدرع',
'Blast Shot':'طلقة انفجارية','Shatter Domain':'نطاق التحطيم','Corrosion Domain':'نطاق التآكل',
'Piercing Domain':'نطاق الاختراق','Revival Domain':'نطاق البعث','Spike Trap':'فخ الأشواك',
'Azure Rain':'المطر الأزرق','Burst Loop':'حلقة الانفجار','Phantom Decoy':'فزاعة شبحية','Explosive Decoy':'فزاعة متفجرة',
'Siege Crossbow':'قوس الحصار','Chain Dash: Impact':'اندفاع السلسلة: صدم',
'Chain Dash: Flame':'اندفاع السلسلة: لهب','Flash Step':'خطوة البرق',
// Skill activation
'Bladewing!':'جناح النصل!','Chain Blaze!':'اشتعال السلسلة!','Chain Crush!':'سحق السلسلة!',
'Chain Dash!':'اندفاع السلسلة!','Chain Flame!':'لهب السلسلة!',
'Harpoon!':'حربون!','Enter!':'دخول!','Rain Lightning!':'أمطار البرق!',
'Arcane Barrage!':'وابل سحري!',
'Arc Laser!':'ليزر القوس!','Laser Off':'إيقاف الليزر','MP depleted — Laser Off':'نفد MP — إيقاف الليزر',
'Focus...':'تركيز...','Casting...':'جارٍ التنفيذ...',
'Needle Barrage!':'وابل الإبر!','Needle Burst!':'انفجار الإبر!','Blade!':'نصل!',
'Landing!':'هبوط!','Poise Break!':'كسر التوازن!',
'Chain Burst Ready!':'انفجار السلسلة جاهز!','Chain Blaze Ready!':'اشتعال السلسلة جاهز!',
'Chain Crush Ready!':'سحق السلسلة جاهز!',
'Ghost Flame ON':'شعلة شبحية مفعّلة','Ghost Flame OFF':'شعلة شبحية متوقفة',
'Bladewing AUTO ON':'جناح النصل تلقائي مفعّل','Bladewing AUTO OFF':'جناح النصل تلقائي متوقف',
'Auto Burst!':'انفجار تلقائي!','Rapid Fire Off':'إيقاف الرشق',
'Pull Mode':'وضع السحب','Push Mode':'وضع الدفع',
// Skill tooltips
'Wing Strike':'ضربة الجناح','Parry':'صد',
'Shift: Harpoon throw → pull':'Shift: رمي الحربون → سحب',
'Shift: Flame trail+burn':'Shift: أثر لهب+حرق',
'CT: Lightning form+Ghost Walk (CD 4s)':'CT: شكل البرق+مشي شبحي (تهدئة 4 ث)',
'CT: Ice sphere+freeze (re-press: shatter)':'CT: كرة جليد+تجميد (إعادة: تحطيم)',
// HUD
'Melee':'قتال قريب','Guard':'حارس','Harpoon':'حربون','Magic':'سحر','Shield':'درع','Ghost':'شبح',
'Skills':'مهارات','Forge':'مسبك','Inv':'حقيبة',
// Menu
'Inventory':'المخزون','Forge of Vengeance':'مسبك الانتقام','Passive Skills':'مهارات سلبية',
'Combat Skills':'مهارات قتالية','Character Select':'اختيار الشخصية',
// Elements
'Physical':'فيزيائي','Fire':'نار','Ice':'جليد','Dark':'ظلام','Lightning':'برق','Holy':'مقدس','Earth':'أرض',
// Passives
'Strength':'قوة','Dexterity':'رشاقة','Intelligence':'ذكاء','Luck':'حظ',
'Onslaught':'هجوم كاسح','Fortitude':'صلابة','Breakthrough':'اختراق','Retaliation':'انتقام',
'Arcane Surge':'موجة سحرية','Precision Shot':'تصويب دقيق','Protection':'حماية','Guardian Spirit':'روح الحارس',
'Recovery':'تعافي','Vital Strike':'ضربة حيوية','Plunder':'نهب','Penetration':'اختراق',
'Mana Recovery':'استعادة المانا','Crossbow Mastery':'إتقان القوس','Berserker':'محارب هائج','Tracker':'متعقب',
'Physical Pen.':'اختراق فيزيائي','Magic Pen.':'اختراق سحري',
// Weapons
'Rusty Greatsword':'سيف عظيم صدئ','Steel Greatsword':'سيف عظيم فولاذي','Obsidian Greatsword':'سيف عظيم سبجي',
'Worn Crossbow':'قوس بالٍ','Steel Crossbow':'قوس فولاذي','Obsidian Crossbow':'قوس سبجي',
'Greatsword':'سيف عظيم','Crossbow':'قوس','Repeater':'رشاش','Arcane Crossbow':'قوس سحري',
// Misc
'Malice Extract':'استخلاص الحقد','Malice':'حقد','Ultimate':'ضربة قصوى','Ultimate Unset':'إلغاء الضربة القصوى',
'Transfer':'نقل','Enhance':'تعزيز','Opened!':'فُتح!',
"Goddess's Blessing":'بركة الإلهة',
'Overload!':'حمل زائد!',
// Affixes
'Venomous':'سام','Flaming':'ملتهب','Frigid':'متجمد','Voltaic':'كهربائي','Accursed':'ملعون',
'Piercing':'خارق','Furious':'غاضب','Shattering':'محطّم','Chaining':'متسلسل',
'Slaying':'قاتل','Explosive':'متفجر','Focused':'مركّز','Swift':'سريع','Deflecting':'صاد',
"Stalker's":'المتربص','Supreme':'أعلى','Mindful':'واعي',
'Stalwart':'صامد','Warding':'واقي','Vital':'حيوي','Hastened':'مسرّع',
'Fire Guard':'حارس النار','Ice Guard':'حارس الجليد','Lightning Guard':'حارس البرق','Dark Guard':'حارس الظلام','Poison Guard':'حارس السم','All Guard':'حارس الكل',
'Ironclad':'مدرّع','Reflecting':'عاكس','Thorned':'شوكي','Absorbing':'ماص','Enduring':'صبور',
'Desperate':'يائس','Retaliating':'منتقم',
'Parry Blast':'انفجار الصد','Stagger Blast':'انفجار الترنح','Converter':'محوّل','Purifying':'مطهّر',
'Unyielding':'لا يلين','Reviving':'مُحيي',
'Looting':'ناهب','Seasoned':'خبير','Golden':'ذهبي','Potent':'فعّال','Chained':'مقيّد',
'Sanctifying':'مقدّس','Cyclic':'دوري',
'Vigorous':'حيوي','Regenerating':'متجدد','Healing':'شافي',
'Arcane':'سحري','Efficient':'موفّر','Soulbound':'مرتبط بالروح',
'Keen':'حاد','Brutal':'وحشي','Ruinous':'مدمّر',
// Settings
'Game Settings':'إعدادات اللعبة','Screen Shake':'اهتزاز الشاشة','Particle Amount':'كمية الجسيمات',
'SFX Volume':'مستوى المؤثرات','Music Volume':'مستوى الموسيقى','Difficulty':'الصعوبة',
'Auto Potion':'جرعة تلقائية','Min Pickup Grade':'أدنى رتبة التقاط','Min Pickup Tier':'أدنى فئة التقاط',
'FPS Limit':'حد FPS','Resolution Scale':'مقياس الدقة','Pet Auto-Collect':'جمع تلقائي للحيوان',
'Display Settings':'إعدادات العرض','Display Mode':'وضع العرض','Boss AI Debug':'تصحيح ذكاء الزعيم',
'Ghost Flame Size':'حجم الشعلة الشبحية','Brightness':'السطوع','Ghost Glow':'توهج شبحي',
'Bladewing AUTO':'جناح النصل تلقائي',
'Normal':'عادي','Hard':'صعب','Hell':'جحيم','or above':'أو أعلى','Disabled':'معطّل',
'Windowed':'نافذة','Borderless':'بلا حدود','Fullscreen':'شاشة كاملة',
'Settings':'إعدادات','Key Bindings (Click to Change)':'ربط المفاتيح (انقر للتغيير)',
// Key Guide
'LMB Weapon Attack':'نقر أيسر هجوم سلاح','RMB Tap Blade Parry':'نقر أيمن صد النصل',
'RMB Hold Continuous Parry':'ضغط أيمن صد متواصل','SHIFT Harpoon Launch':'SHIFT إطلاق الحربون',
'Move':'تحرك','Pick Up Item':'التقاط عنصر','Stats (Stats/Passives)':'إحصائيات (إحصائيات/سلبيات)',
'Dismantle':'تفكيك','Craft':'صنع',
// Death
'Death':'موت','Revive':'بعث','To Lobby':'إلى الردهة',
// Inventory
'No space in bag!':'لا مساحة في الحقيبة!','Bag is full!':'الحقيبة ممتلئة!',
'Storage is full!':'المخزن ممتلئ!','Quick slot is full!':'الخانة السريعة ممتلئة!',
'Crystal pouch is full!':'حقيبة البلورات ممتلئة!','Crystal pouch full!':'حقيبة البلورات ممتلئة!',
'Not enough Malice!':'لا يكفي حقد!','Bag is empty':'الحقيبة فارغة',
'Storage is empty':'المخزن فارغ','Empty':'فارغ','No affix':'بدون لاحقة',
'Equipped!':'تم التجهيز!','Unequipped':'تم الخلع','Deposit':'إيداع','Withdraw':'سحب',
'Currently equipped':'مجهّز حالياً','None — Craft one!':'لا شيء — اصنع واحداً!',
'No points to reset':'لا نقاط لإعادة التعيين','Key settings reset':'تم إعادة تعيين المفاتيح',
// Forge
'Craft chance':'فرصة الصنع','Craft cost':'تكلفة الصنع','Malice owned':'الحقد المملوك',
// Canvas
'Boss Room':'غرفة الزعيم','Sanctuary':'ملاذ','Recover':'تعافي','Ignite':'إشعال',
'Stele':'مسلة','Read':'قراءة','Destroy':'تدمير','Altar':'مذبح','Pray':'صلاة',
'Debris':'حطام','Open':'فتح','Gatekeeper':'حارس البوابة',
'Resurrection judging...':'جارٍ حكم البعث...','Detonate ready!':'التفجير جاهز!',
'Escape':'هروب','Mash':'ضرب متكرر',
'Tracking Lightning':'برق متتبع','Luminescence Beam':'شعاع مضيء','Final Magic':'السحر الأخير',
'Watching':'مراقبة','Standby':'انتظار','Active':'نشط','Can install':'يمكن التثبيت',
'Breach imminent!':'اختراق وشيك!','Absorbing...':'جارٍ الامتصاص...',
'Done — re-input to collect':'تم — أعد الإدخال للجمع',
'Burn':'حرق','Pull':'سحب','Push':'دفع',
'tier':'مستوى',
// Skill panel
'Learned!':'تعلّمت!','Reset!':'إعادة تعيين!','Set!':'تم التعيين!','Recall':'استرجاع',
'Unfuse':'فك الدمج','Reset':'إعادة تعيين','Refund':'استرداد',
'Click partner!':'انقر الشريك!','SP needed!':'تحتاج SP!',
'Can fuse when learning same gem skill':'يمكن الدمج عند تعلم نفس مهارة الجوهرة',
'Expand to reset':'وسّع لإعادة التعيين','Slot:':'خانة:',
// Stats
'SP Left':'SP متبقية','Died from hit':'مات من ضربة','Level':'مستوى','Max HP':'أقصى HP',
// Enemies
'Wandering Knight':'الفارس الشارد','Treasure Demon':'شيطان الكنز','Mirror Apostle':'رسول المرآة',
'Merchant Demon':'شيطان التاجر','Chained Prisoner':'السجين المقيّد','Time Apostle':'رسول الزمن',
'Greed Apostle':'رسول الجشع','Cursed Twins':'التوأم الملعون','Dimensional Rift':'صدع بُعدي',
'Death Itself':'الموت ذاته',
// Crystals
'HP Crystal':'بلورة HP','ST Crystal':'بلورة ST','MP Crystal':'بلورة MP',
'ATK Crystal':'بلورة ATK','DEF Crystal':'بلورة DEF','Speed Crystal':'بلورة السرعة',
'Crit Crystal':'بلورة الحرج','CritDmg Crystal':'بلورة ضرر الحرج','Fire Crystal':'بلورة النار',
'Ice Crystal':'بلورة الجليد','Dark Crystal':'بلورة الظلام','Lightning Crystal':'بلورة البرق',
'Holy Crystal':'بلورة مقدسة','Life Crystal':'بلورة الحياة','Stamina Crystal':'بلورة التحمل',
'Mana Crystal':'بلورة المانا','Luck Crystal':'بلورة الحظ',
'Fragment':'شظية','Shard':'قطعة','Pure Crystal':'بلورة نقية','Perfect Crystal':'بلورة مثالية',
'Crystal Pouch':'حقيبة البلورات','No crystals':'لا بلورات','Dust':'غبار',
'All':'الكل','Stat':'إحصاء','Elem':'عنصر','Util':'أداة',
'Current':'حالي','Max enhanced (+20)':'أقصى تعزيز (+20)','After enhance':'بعد التعزيز',
'Synthesize':'تركيب',
'3 crystals of same type & grade → upgrade 1 grade (enhance reset)':'3 بلورات من نفس النوع والرتبة → ترقية 1 رتبة (إعادة تعيين التعزيز)',
'No synthesizable crystals (need 3 of same type & grade)':'لا بلورات قابلة للتركيب (تحتاج 3 من نفس النوع والرتبة)',
'Crystal Decompose → Crystal Dust':'تفكيك بلورة → غبار بلوري',
'No crystals to decompose':'لا بلورات للتفكيك',
'Craft Crystal (Dust → Crystal)':'صنع بلورة (غبار → بلورة)',
'Detach':'فصل','Empty slot':'خانة فارغة',
'Select crystal then click':'اختر بلورة ثم انقر','Click to equip selected crystal':'انقر لتجهيز البلورة المختارة',
'Obtained!':'حصلت!','Crafted!':'صُنعت!','Synthesized!':'رُكّبت!','Bulk Synth to Top':'تركيب جماعي للأعلى','Bulk synth done':'اكتمل التركيب الجماعي',
// Stages
'Worm Nest':'عش الديدان','Ice Cavern':'كهف الجليد','Infernal Wastes':'أراضي اللهب',
'Hell Legion':'فيلق الجحيم',"Apostle's Den":'وكر الرسول','Hell Citadel':'قلعة الجحيم',
// Misc
'Exoduser Warrior':'محارب إكسودوسر','Poise':'توازن',
'Hell Storage':'مخزن الجحيم','Selective Dismantle':'تفكيك انتقائي','Junk':'خردة',
'Cannot recover!':'لا يمكن الاستعادة!','Important-locked':'مقفل مهم',
'Auto-equipped!':'تجهيز تلقائي!','Dismantled! Dust +':'فُكّك! غبار +',
'Aegis':'درع','Quake Storm':'عاصفة زلزالية','Whirl-Det':'تفجير دوراني',
'Attack':'هجوم','Barrier':'حاجز',
'Merged into fused skill':'دُمج في مهارة مدمجة','Cannot use inside Ice Orb!':'لا يمكن الاستخدام داخل كرة الجليد!',
'Shift+key to detonate':'Shift+مفتاح للتفجير',
'Cooldown...':'فترة تهدئة...','Casting...':'جارٍ التنفيذ...',
'Not enough Malice! (12)':'لا يكفي حقد! (12)','Not enough Malice! (15)':'لا يكفي حقد! (15)',
'Not enough Malice! (20)':'لا يكفي حقد! (20)','Not enough Malice! (10)':'لا يكفي حقد! (10)',
'Not enough HP!':'لا يكفي HP!',
'Click ultimate slot to assign!':'انقر خانة الضربة القصوى للتعيين!',
'Learn an ultimate skill':'تعلّم مهارة قصوى',
'Merged into RMB (blade parry)':'دُمج في النقر الأيمن (صد النصل)',
'Set to T (auto crossbow)':'عيّن على T (قوس تلقائي)',
'Siege crossbow dismantled → portable':'قوس الحصار فُكّك → محمول',
'Not enough ST! (100)':'لا يكفي ST! (100)',
'HP 99%+!':'HP 99%+!','No groggy boss!':'لا زعيم مترنح!',
'Already in storm zone!':'بالفعل في منطقة العاصفة!','Already in ice storm zone!':'بالفعل في منطقة عاصفة الجليد!',
'Azure Rain unlocked!':'المطر الأزرق مفتوح!','Burst Loop unlocked!':'حلقة الانفجار مفتوحة!',
'Phantom Decoy unlocked!':'الفزاعة الشبحية مفتوحة!',
'CD ':'تهدئة ','Overload ':'حمل زائد ',
'Blue Bean!':'حبة زرقاء!','Red→Blue Bean!':'حمراء→حبة زرقاء!',
'Rainbow→Blue Bean!':'قوس قزح→حبة زرقاء!',
'Rare':'نادر','Slot':'خانة',
'Success Rate':'نسبة النجاح','AI Auto-Enhance':'تعزيز تلقائي ذكي','Max enhancement reached!':'بلغ أقصى تعزيز!',
'Max enhanced':'أقصى تعزيز','Recovery':'تعافي',
'No items to dismantle.':'لا عناصر للتفكيك.',
'Craft':'صنع',
'Posture':'وضعية','Hover over an item or left-click to select':'مرر فوق عنصر أو انقر أيسر للاختيار',
'Poison':'سم','Mine':'لغم','Trap':'فخ','Coral Spike':'شوكة مرجانية',
'Projectile':'قذيفة','DoT':'ضرر مستمر','Rare Mob':'وحش نادر',
'Zone':'منطقة','Spike!':'شوكة!',
// Hell circles
'Limbo':'الأعراف','Lust':'الشهوة','Gluttony':'النهم','Greed':'الجشع','Wrath':'الغضب','Heresy':'الهرطقة','Violence':'العنف',
'Rage!':'غضب!','Greed!':'جشع!','Rage Burst!':'انفجار الغضب!','Abyssal Rage!':'غضب الهاوية!',
"Twin's Rage!":'غضب التوأم!',
'Spawn Hole':'حفرة الاستدعاء',
'Defeated!':'هُزم!','Crown On':'وضع التاج','Crown Off':'خلع التاج',
'Bare':'يد عارية','None':'لا شيء','Armor':'درع','Boots':'حذاء',
// Elite
'Magic':'سحر','Champion':'بطل',
'Frozen':'مجمد','Haste':'عجلة','Slam':'ضربة','Regen':'تجدد','Venom':'سم','Summon':'استدعاء',
'Parasite':'طفيلي','Split':'انقسام','Lava Trail':'أثر حمم','Death Blast':'انفجار الموت',
'Fire Chain':'سلسلة نار','Frenzy':'هياج','Teleport':'انتقال آني',
'Vortex':'دوامة','Phantom':'شبح','Shock Reflect':'انعكاس صدمة','Electrify':'صعق',
'Thunder':'رعد','Chain Lightning':'برق متسلسل','Ally Undying':'حليف خالد',
'Soul Devour':'التهام الروح','Time Warp':'انحراف الزمن','Chaos Mutate':'تحور الفوضى',
'Avenger':'منتقم','Magic Sentinel':'حارس سحري','Illusionist':'ساحر الأوهام',
'War Cry':'صيحة حرب','Heal':'شفاء','Swiftness':'سرعة','Guardian':'حارس',
// Character
'Dark fantasy warrior. Greatsword + Black armor':'محارب خيال مظلم. سيف عظيم + درع أسود',
// Phase 11
'Chain:Enhanced!':'سلسلة:معززة!',
'Chain Drive: Flame!':'قيادة السلسلة: لهب!',
'Achieved!':'تحقق!',
'ST':'ST','Insufficient!':'غير كافٍ!',
'Hit':'ضربة',
'Pull Mode':'وضع السحب','Push Mode':'وضع الدفع',
'Red bean absorb':'امتصاص الحبة الحمراء',
'Absorb':'امتصاص',
'Homing Blast!':'انفجار موجّه!',
'Reflect Blast!':'انفجار منعكس!',
'Repentance Return!':'عودة التوبة!',
'Repentance!':'التوبة!',
'Wave!':'موجة!',
'Lightning!':'برق!',
'Dark!':'ظلام!',
'Dark Spear!':'رمح الظلام!',
'Light Spear!':'رمح النور!',
'summoned!':'استُدعي!',
'placed!':'وُضع!',
'Boss Groggy!':'الزعيم مترنح!',
'Groggy!':'ترنح!',
'Bonus':'مكافأة',
'Lightning Helix!':'لولب البرق!',
'Quake Storm!':'عاصفة زلزالية!',
'SP Slot':'خانة SP',
'F Slot':'خانة F',
'Plague Liberation!':'تحرير الوباء!',
'Blade Liberation!':'تحرير النصل!',
'Inferno Slam!':'ضربة الجحيم!',
'Giant Slam!':'ضربة عملاقة!',
'Ward Domain!':'نطاق الحماية!','Water Domain!':'نطاق الماء!','Shatter Domain!':'نطاق التحطيم!','Corrode Domain!':'نطاق التآكل!','Pierce Domain!':'نطاق الاختراق!','Sovereign Domain!':'نطاق السيادة!',
'Sacred Domain!':'نطاق مقدس!',
'Critical...!':'حرج...!',
'Detonate!':'تفجير!','Force Detonate!':'تفجير إجباري!','Auto Detonate!':'تفجير تلقائي!',
'Whirl Detonate!':'تفجير دوراني!','Release Detonate!':'تفجير الإطلاق!','Quake Detonate!':'تفجير زلزالي!',
'Crown of Chaos':'تاج الفوضى',
'Crown of Omnipotence':'تاج القدرة المطلقة',
'Demon Bracelet':'سوار الشيطان',
'Life Bracelet':'سوار الحياة',
'Top→Bottom Wave!':'موجة أعلى→أسفل!','Right→Left Wave!':'موجة يمين→يسار!',
'Bottom→Top Wave!':'موجة أسفل→أعلى!','Left→Right Wave!':'موجة يسار→يمين!',
'Invincible!':'لا يُقهر!',
'Counter!':'مضاد!',
'Absorb!':'امتصاص!','Counter Shot!':'طلقة مضادة!',
'Curse! Drop rate -50%':'لعنة! نسبة الإسقاط -50%','Flee!':'هروب!',
'Phase!':'مرحلة!','Guard!':'حراسة!',
'Recall HP+':'استرجاع HP+','Mobile Return':'عودة متحركة',
'Weakness!':'ضعف!','Resist!':'مقاومة!',
'Combo End: ':'نهاية الكومبو: ',
'Malice +':'حقد +',
'Curse ':'لعنة ','Fizzle...':'فشل...','Misfire...':'إخفاق...',
'Harpoon Weakness!':'ضعف الحربون!',
'Plague x':'وباء x','Absorb Complete!':'اكتمل الامتصاص!',
'Revive Success!':'نجح البعث!','Revive Failed...':'فشل البعث...',
'Coral Spike':'شوكة مرجانية','Dimensional Shift!':'انتقال بُعدي!',
'Stun Released':'تم تحرير الذهول',
'Not enough Malice':'لا يكفي حقد','No skills learned':'لا مهارات مكتسبة',
'Expand':'توسيع','Collapse':'طي',
' not met!':' غير مستوفى!',' Unfused!':' فُك الدمج!',
' Auto ON':' تلقائي مفعّل',' Auto OFF':' تلقائي متوقف',' skill unset':' مهارة غير معيّنة',
'Close':'إغلاق','Equipped':'مجهّز','Stored Item':'عنصر مخزّن',
'Click to select · ESC to close':'انقر للاختيار · ESC للإغلاق',
'Selected':'مختار',
'Not enough Malice! (30)':'لا يكفي حقد! (30)',
'Not enough MP! (40)':'لا يكفي MP! (40)','Not enough MP! (100)':'لا يكفي MP! (100)','Not enough MP! (10)':'لا يكفي MP! (10)',
'Not enough MP! (':'لا يكفي MP! (',
'Casting...':'جارٍ التنفيذ...',
'Enter!':'دخول!',
'Harpoon!':'حربون!',
'Level too low! (Req: Lv.':'المستوى منخفض! (المطلوب: Lv.',
' Equipped!':' تم التجهيز!',
' Unequipped':' تم الخلع',
'Malice Extract: +':'استخلاص الحقد: +',
'F Slot unset':'خانة F غير معيّنة',
'Focus...':'تركيز...',
'Arcane Barrage!':'وابل سحري!',
'Frozen!':'مجمد!','Poison!':'سم!','Shocked!':'صُعق!','Burning!':'احتراق!',
'Goddess Blessing — SP+5 AP+3':'بركة الإلهة — SP+5 AP+3',
'Bladewing!':'جناح النصل!',
'Fire Pierce!':'اختراق ناري!',
'Pierce!':'اختراق!',
'Blade!':'نصل!',
'Landing!':'هبوط!',
'Stunned!':'مذهول!',
'Poise Break!':'كسر التوازن!',
'Chain Crush! T':'سحق السلسلة! T',
'Chain Blaze!':'اشتعال السلسلة!',
'Chain Blaze! T':'اشتعال السلسلة! T',
' x':' x',
'Chain Burst! x':'انفجار السلسلة! x',
'Blaze x3!':'اشتعال x3!','Blaze x6!':'اشتعال x6!','Blaze x9!':'اشتعال x9!','Blaze Detonate! ':'تفجير الاشتعال! ',
'Chain Blaze Ready!':'اشتعال السلسلة جاهز!',
'Chain Crush Ready!':'سحق السلسلة جاهز!',
'Chain Burst Ready!':'انفجار السلسلة جاهز!',
'Overload! 5s':'حمل زائد! 5 ث',
'Auto Burst!':'انفجار تلقائي!',
'Shield Wing!':'جناح الدرع!',
'Explosion!':'انفجار!',
'Homing Reflect!':'انعكاس موجّه!',
'Blue Bean!':'حبة زرقاء!',
'Reflect!':'انعكاس!',
'Azure Rain OFF':'المطر الأزرق متوقف',
'Azure Rain ON!':'المطر الأزرق مفعّل!',
'Inferno Array!':'مصفوفة الجحيم!',
'Hellfire Beam!':'شعاع نار الجحيم!',
'Peace Shockwave! ':'موجة صدم السلام! ',
'Current Release!':'إطلاق التيار!',
'Rain Lightning!':'أمطار البرق!',
'AoE!':'مساحي!',
'Fire Zone!':'منطقة نار!',
'Finisher!':'إنهاء!',
'Returned from Hell!':'عاد من الجحيم!',
'Permanent Death!':'موت دائم!',
'Execution! ':'إعدام! ',
'Mine!':'لغم!',
'Trap!':'فخ!',
'Use RMB! -':'استخدم الأيمن! -',
'Use Q! -':'استخدم Q! -',
'Rainbow Blast! ':'انفجار قوس قزح! ',
'White Ball!':'كرة بيضاء!',
'Dark Ball!':'كرة ظلام!',
'Ice Floor!':'أرضية جليد!',
'Slow!':'بطء!',
'Plague Execution!':'إعدام الوباء!',
'Plague Finale!':'نهاية الوباء!',
'Rift Demon!':'شيطان الصدع!',
'Auto-Recall HP+':'استرجاع تلقائي HP+',
'MP low — Rapid Fire Off':'MP منخفض — إيقاف الرشق',
'MP low — Azure Rain OFF':'MP منخفض — إيقاف المطر الأزرق',
'Reflect!':'انعكاس!',
'Repentance Return!':'عودة التوبة!',
'Bone Lightning!':'برق العظام!',
'Malice Storm!':'عاصفة الحقد!',
'Ice Storm!':'عاصفة الجليد!',
'Lightning Blast!':'انفجار البرق!',
'Rain Lightning! x':'أمطار البرق! x',
'Escape!':'هروب!',
'Shield!':'درع!',
'Ice Orb!':'كرة الجليد!',
'Deploy!':'نشر!',
'Freeze Vortex!':'دوامة التجمد!',
'Freeze Blast!':'انفجار التجمد!',
'Vortex!':'دوامة!',
'Mega Blast!':'انفجار ضخم!',
'Time Warp!':'انحراف الزمن!','Cooldown!':'تهدئة!',
'Shatter!':'تحطيم!',
'Donut!':'دونات!','Annihilation!':'إبادة!',
'Wave!':'موجة!','Bind!':'قيد!','Counter!':'مضاد!',
'Clone!':'نسخة!','Clone Destroyed!':'دُمّرت النسخة!','Weapon Liberation!':'تحرير السلاح!',
'Prison!':'سجن!','Mark ':'علامة ',
'Shake!':'اهتزاز!','AoE Fire!':'نار مساحية!',
'Spread!':'انتشار!','Charge!':'اندفاع!',
'Leap!':'قفز!','Laser!':'ليزر!',
'Shockwave!':'موجة صدم!','Summon!':'استدعاء!',
'Meteor Shower!':'أمطار نيازك!','Grab!':'إمساك!',
'Whirlwind!':'زوبعة!','Mine!':'لغم!',
'Vacuum!':'سحب!','Red Bean Storm!':'عاصفة الحبة الحمراء!',
'Bean Rain!':'أمطار الحبوب!',
'Fan Shockwave!':'موجة صدم مروحية!',
'Annihilation Laser!':'ليزر الإبادة!',
'Tracking Zone!':'منطقة تتبع!',
'Elemental Shot!':'طلقة عنصرية!',
'Sword Ki!':'طاقة السيف!','Reaping Slash!':'قطع الحصاد!',
'Spiral Shot!':'طلقة حلزونية!','Thrust!':'طعنة!',
'Hell Pillar!':'عمود الجحيم!',
'Phantom Blade!':'نصل الشبح!',
'Counter Stance!':'وضعية المضاد!',
'Combo!':'كومبو!','Darkness!':'ظلام!',
'Clone!':'نسخة!','Rift!':'صدع!',
'Ripple!':'تموّج!','Homing Mine!':'لغم موجّه!',
'Rewind!':'ترجيع!','Gravity Field!':'حقل جاذبية!',
'Wall Push!':'دفع الجدار!','Poison Fog!':'ضباب السم!',
'Prison!':'سجن!','Chain Lightning!':'برق متسلسل!',
'Orbital Shot!':'طلقة مدارية!','Shield Charge!':'اندفاع الدرع!',
'Bind!':'قيد!',
'Steal!':'سرقة!',
'Lava Zone!':'منطقة حمم!',
'Fire Barrage!':'وابل نار!',
'Lightning Veil!':'حجاب البرق!',
'Come to Me!':'تعال إليّ!',
'Safe!':'آمن!',
'Annihilation Blast!':'انفجار الإبادة!',
'Wedge Extinction!':'انقراض الوتد!',
'Malice+100':'حقد+100',
'Parry Blast!':'انفجار الصد!',
'Rift Collision! ':'تصادم الصدع! ',
'Wall Collision! ':'تصادم الجدار! ',
'Phantom!':'شبح!',
'Thunder!':'رعد!','Beam!':'شعاع!',
'Illusion!':'وهم!',
'Curse!':'لعنة!',
'Spawn!':'تفريخ!',
'Frenzy!':'هياج!',
'Frost!':'صقيع!','Freeze Wave!':'موجة تجمد!',
'Ice Demon!':'شيطان الجليد!',
// Mob actions
'Shockwave!':'موجة صدم!','Poison Fog!':'ضباب السم!',
'Flurry!':'وابل!','Roar!':'زئير!','Enhance!':'تعزيز!',
'Tail!':'ذيل!','Stealth...':'تخفّي...','Ambush!':'كمين!',
'Poison Gas!':'غاز سام!','Dissolve...':'تحلل...',
'Smash!':'سحق!','Secrete!':'إفراز!','Whip!':'سوط!',
'Bleed!':'نزيف!','Dive!':'انقضاض!','Discharge!':'تفريغ!',
'Impact!':'صدم!','Heal!':'شفاء!','Ritual!':'طقس!',
'Hellfire!':'نار الجحيم!','Dragged!':'سُحب!','Tongue!':'لسان!',
'Gaze!':'تحديق!','Fall!':'سقوط!','Blood Drop!':'قطرة دم!',
'Rise!':'نهوض!','Sweep!':'كنس!','Crouch':'انحناء',
'Bone Blade!':'نصل العظام!','Slow!':'بطء!','Scream!':'صراخ!',
'Volcano Shot!':'طلقة بركانية!','Self-Destruct!':'تدمير ذاتي!','Envelop!':'تغليف!',
'Slam!':'ضربة!','Breath!':'نَفَس!',
'Flight!':'طيران!','Lava Rain!':'أمطار حمم!','Water Jet!':'نفاثة ماء!',
'Light...':'نور...','Swallow!':'ابتلاع!','Paralyze!':'شلل!',
'Pincer Slam!':'ضربة كماشة!',
'Seize!':'قبض!','Coil!':'لف!','Fragment!':'شظية!',
'Scratch!':'خدش!','Parasite!':'طفيلي!',
'Abyssal Release!':'تحرير الهاوية!','Tentacle Barrage!':'وابل المجسات!',
'Trident!':'ثلاثي الشعب!','Tsunami!':'تسونامي!',
'Creak!':'صرير!','Chain!':'سلسلة!',
'Mane!':'عُرف!','Terror!':'رعب!','Drain!':'امتصاص!',
'Slash!':'قطع!','Riiing!!':'رنين!!','Split!':'انقسام!',
'Triple Slash!':'قطع ثلاثي!','Parry!':'صد!',
'...Copy...':'...نسخ...','Imbalance...Curse!':'عدم توازن...لعنة!',
'Balance...Enhance!':'توازن...تعزيز!',
'Pillar of Judgment!':'عمود الحكم!','Death Sentence!':'حكم الإعدام!',
'Pain Liberation!':'تحرير الألم!','Feel this too!':'اشعر بهذا أيضاً!',
'Greatsword Frenzy!':'هياج السيف العظيم!','Tentacle!':'مجس!',
'Omni-Beam!':'شعاع شامل!','Dodge!':'تفادَ!',
// Merchant/rare
'[F] Shop':'[F] متجر','Trade Success!':'نجحت الصفقة!',
'Not enough Malice! (':'لا يكفي حقد! (',
'The merchant leaves...':'التاجر يغادر...',
'Chain Liberation!':'تحرير السلسلة!','Full Liberation!':'تحرير كامل!',
'Time Rewind!':'ترجيع الزمن!','Switch!':'تبديل!',
'Revive ':'بعث ','Rift!':'صدع!','...Vanished':'...اختفى',
'Scythe Slash!':'قطع المنجل!','Death Sentence!':'حكم الإعدام!',
'Executing sentence...':'تنفيذ الحكم...',
'Parry!':'صد!','Stagger!':'ترنح!',
'Grabbed!':'أُمسك!','Throw!':'رمي!',
'Vortex Explosion!':'انفجار الدوامة!',
'Teleport!':'انتقال آني!','Stunned! 5s':'مذهول! 5 ث',
'Thrust Counter!':'طعنة مضادة!','Explosion!':'انفجار!',
'Counter Failed':'فشل المضاد','Steal Counter!':'سرقة مضادة!',
'Weapon Seal!':'ختم السلاح!','Nom!':'نام!',
// Stage/room
'Fused!':'دُمج!','Exit opened!':'فُتح المخرج!',
'Treasure chest appeared!':'ظهر صندوق كنز!','Exit':'مخرج',
'Gatekeeper still alive!':'حارس البوابة لا يزال حياً!',
'Time Attack ':'هجوم زمني ',
'Kill Rate ':'نسبة القتل ',
'Undying Protection':'حماية خالدة',
'Phantom Vanished!':'اختفى الشبح!',
'Revive Power ':'قوة البعث ',
'Holy Suppress! (':'قمع مقدس! (',
'Revive Failed (':'فشل البعث (',
'Co-Revive!':'بعث مشترك!',
'Holy Suppress!':'قمع مقدس!',
'Gatekeeper Defeated!':'هُزم حارس البوابة!',
'Boss Room Open!':'غرفة الزعيم مفتوحة!',
'Debris appeared!':'ظهر حطام!',
'Rift opened!':'فُتح الصدع!',
'Revenge!':'انتقام!','Plague Blood!':'دم الوباء!',
'Final Freeze!':'تجمد نهائي!','Ice Demon Defeated!':'هُزم شيطان الجليد!',
'Separate!':'انفصال!','Bone Fragment!':'شظية عظم!',
'Fetus Defeated!':'هُزم الجنين!','Overlord Defeated!':'هُزم المسيطر!',
'Lava!':'حمم!','Fire Dragon Defeated!':'هُزم التنين الناري!',
'Final Scream!':'صرخة أخيرة!','Oxidize...':'تأكسد...',
'Judge Defeated!':'هُزم القاضي!','Pain King Defeated!':'هُزم ملك الألم!',
'Water!':'ماء!','Fragment Explosion!':'انفجار الشظايا!',
'Leviathan Defeated!':'هُزم الوحش البحري!','High Apostle Defeated!':'هُزم الرسول الأعلى!',
'Poison Pool!':'بركة السم!','Electric Field!':'حقل كهربائي!',
'Weapon Drop!':'سقوط سلاح!','Treasure Found!':'عُثر على كنز!',
'Merchant Pouch +':'حقيبة التاجر +',
'Shard of Binding!':'شظية القيد!','Time Fragment!':'شظية الزمن!',
'Curse Lifted!':'رُفعت اللعنة!','Dimensional Crystal!':'بلورة بُعدية!',
'Legendary Item!':'عنصر أسطوري!','Overcome Death!':'تغلّب على الموت!',
'Mega Blast!':'انفجار ضخم!','Enhance!':'تعزيز!',
'Gear ':'عتاد ',
'Tremor!':'رجفة!','Invincible!':'لا يُقهر!',
'Ghost!':'شبح!',
'Focus Cancel!':'إلغاء التركيز!','Focus!':'تركيز!',
'Aegis ':'درع ','Shield ':'درع ','Spin Shield ':'درع دوراني ',
'One-hit Cap!':'حد الضربة الواحدة!',
'Shield Destroy!':'تدمير الدرع!',
'Unyielding!':'لا يلين!',
'1-life Revive!':'بعث حياة واحدة!',
'Sentry Recall':'استرجاع الحارس',
'Demon Revive!':'بعث شيطاني!',
'No skills to assign':'لا مهارات للتعيين',
'No Blade!':'لا نصل!',
'Malice Hunt!':'صيد الحقد!',
'Ice Vortex!':'دوامة الجليد!',
'Vortex Summon!':'استدعاء الدوامة!',
'Bone Tomb!':'قبر العظام!',
'Crimson Bloom!':'الزهرة القرمزية!',
'Blast Shot!':'طلقة انفجارية!',
'Needle Burst!':'انفجار الإبر!',
'Flash Step!':'خطوة البرق!',
'Absorbed by pillar thorn':'امتصه شوك العمود',
'Spike Trap!':'فخ الأشواك!',
'Ghost Gun!':'مسدس شبحي!','Ghost Gun Blast!':'انفجار المسدس الشبحي!',
'Thunder Spear!':'رمح الرعد!',
'Siege Crossbow Placed!':'وُضع قوس الحصار!',
'Phantom Decoy!':'فزاعة شبحية!',
'Explosive Decoy!':'فزاعة متفجرة!',
'Stored!':'مخزّن!','Storing...':'جارٍ التخزين...','Full! Re-press→Explode':'ممتلئ! أعد الضغط→انفجار',
'Explode! ':'انفجار! ',' DMG':' ضرر',
'Plague Blade!':'نصل الوباء!',
'Wing Strike!':'ضربة الجناح!',
'Shield Wing!':'جناح الدرع!',
'Dark Pillar!':'عمود الظلام!',
'Pillar Thorn!':'شوك العمود!',
'Inferno Slam!':'ضربة الجحيم!',
'Posture Break!':'كسر الوضعية!',
'Poise Destroy!':'تدمير التوازن!',
'Ghost Walk!':'المشي الشبحي!',
'Binding Domain!':'نطاق القيد!',
'Holy Blast!':'انفجار مقدس!',
'Black Star!':'النجم الأسود!',
'Lava Summon!':'استدعاء الحمم!',
'Ultimate Assigned!':'تم تعيين الضربة القصوى!',
'Complete':'مكتمل','Can Fuse':'يمكن الدمج','Insufficient':'غير كافٍ',
'SP needed! (':'تحتاج SP! (',
'Hidden: Aegis of Peace unlocked!':'مخفي: درع السلام مفتوح!',
'Hidden: Repentance unlocked!':'مخفي: التوبة مفتوحة!',
'Assigned':'معيّن',
'Fuse Lv.':'مستوى الدمج',
'Can fuse when learning same gem skill':'يمكن الدمج عند تعلم نفس مهارة الجوهرة',
'Bag → Storage':'حقيبة → مخزن',
'Storage → Bag':'مخزن → حقيبة',
'Selected':'مختار',
'Waiting... ':'انتظار... ',
'Wait ':'انتظار ',
'Sub':'فرعي',
'Reset Key Bindings (or F5)':'إعادة تعيين المفاتيح (أو F5)',
'Press any key or mouse button (ESC = cancel)':'اضغط أي مفتاح أو زر ماوس (ESC = إلغاء)',
'WebGPU Active':'WebGPU نشط','WebGL2 Active':'WebGL2 نشط',
'Measuring...':'جارٍ القياس...',
'Load Failed':'فشل التحميل',
'Important-locked items cannot be selected for salvage!':'العناصر المقفلة المهمة لا يمكن اختيارها للتفكيك!',
'Enhance Gear (on fail, materials lost)':'تعزيز العتاد (عند الفشل، تضيع المواد)',
'Enhancement Bonus Applied':'تم تطبيق مكافأة التعزيز',
'Enhancement Failed!':'فشل التعزيز!',
'No equipped gear.':'لا عتاد مجهّز.',
'Enough':'كافٍ','Need More':'تحتاج المزيد',
'Select Gear':'اختر العتاد','Set Target':'حدد الهدف',
'Invest Malice':'استثمر الحقد','Auto Attempt':'محاولة تلقائية',
'Target Enhancement':'التعزيز المستهدف',
'Est. Malice Needed':'الحقد المقدّر المطلوب',
'Owned':'مملوك','Start Enhance':'بدء التعزيز',
'Select gear above':'اختر العتاد أعلاه',
'Potion Enhance (max level 10)':'تعزيز الجرعة (أقصى مستوى 10)',
'Required':'مطلوب',
'Malice Furnace — Grind gear into malice':'فرن الحقد — اطحن العتاد إلى حقد',
'Select All':'اختر الكل','Deselect All':'إلغاء اختيار الكل',
'Rare or Below':'نادر أو أقل',
'Affix Reroll!':'إعادة رمي اللاحقة!',
'Heroic':'بطولي','Legendary':'أسطوري',
'Weapon Type':'نوع السلاح','Bow Type':'نوع القوس',
'Not enough ST':'لا يكفي ST',
'Enraged!':'غاضب!',
// Pet dialogues
"...I'm not following you. Just going the same way.":'...لست أتبعك. فقط نفس الطريق.',
'The air changed. More decay.':'تغيّر الهواء. مزيد من التعفن.',
'Demon territory from here. ...Do as you wish.':'أرض شياطين من هنا. ...افعل ما شئت.',
'...That smell. Rotting flesh.':'...تلك الرائحة. لحم متعفن.',
"Stay too long and you'll go mad. Me too.":'ابقَ طويلاً وستجنّ. وأنا أيضاً.',
"What's at the end of this road? ...I don't want to know.":'ما في نهاية هذا الطريق؟ ...لا أريد أن أعرف.',
'...This is the end. No turning back.':'...هذه النهاية. لا عودة.',
// Idle tips
'Stick the harpoon in the ground and get pulled.':'اغرس الحربون في الأرض وانجذب.',
'Try throwing the harpoon with Shift!':'حاول رمي الحربون بـ Shift!',
'Parry restores ST. Free resources.':'الصد يستعيد ST. موارد مجانية.',
'Parry a lot and ST is never a problem~':'اصد كثيراً ولن يكون ST مشكلة~',
'Dismantling gear gives Malice. Even junk is resources.':'تفكيك العتاد يعطي حقداً. حتى الخردة موارد.',
'Open TAB and salvage unused gear!':'افتح TAB وفكّك العتاد غير المستخدم!',
'Groggy enemies take 1.5x damage.':'الأعداء المترنحون يتلقون 1.5× ضرر.',
'When they kneel, hit with everything!':'عندما يركعون، اضرب بكل شيء!',
'Elements have counters. Fire is weak to Ice, Lightning to Dark.':'العناصر لها مضادات. النار ضعيفة أمام الجليد، البرق أمام الظلام.',
'Try switching weapon elements!':'حاول تبديل عناصر الأسلحة!',
'Frozen enemies take 1.5x damage.':'الأعداء المجمدون يتلقون 1.5× ضرر.',
"Freeze then hit — that's the basics!":'جمّد ثم اضرب — هذا الأساس!',
'Boss red attacks are parryable. Rainbow is dodge only.':'هجمات الزعيم الحمراء قابلة للصد. القوسية للتفادي فقط.',
'Watch the colors! Parry red, dodge rainbow!':'راقب الألوان! اصد الأحمر، تفادَ القوسي!',
'VIT raises max HP. Invest if you want to survive.':'VIT يرفع أقصى HP. استثمر إن أردت البقاء.',
'STR for melee, DEX for bows, INT for magic! Focus one!':'STR للقتال القريب، DEX للأقواس، INT للسحر! ركّز على واحد!',
'Hold E for beam. Tap E for projectile.':'اضغط E مطولاً للشعاع. انقر E للقذيفة.',
'Watch your MP with magic! Beam drains fast!':'راقب MP مع السحر! الشعاع يستنزف بسرعة!',
'Hecter and Deroy auto-collect items in range.':'هكتر وديروي يجمعان العناصر تلقائياً في المدى.',
'Thank us~ Items rot if nobody picks them up.':'اشكرنا~ العناصر تتعفن إن لم يلتقطها أحد.',
'LCK boosts rare drop rate.':'LCK يزيد نسبة الإسقاط النادر.',
"It's all luck~ Try raising LCK!":'كله حظ~ حاول رفع LCK!',
'Enhancement boosts ATK fast! Just need Malice!':'التعزيز يرفع ATK بسرعة! فقط تحتاج حقداً!',
'Enhancement chance starts at 99% for +1. Drops as it goes.':'فرصة التعزيز تبدأ 99% لـ +1. تنخفض مع التقدم.',
"On fail, only Malice is lost~ Gear survives!":'عند الفشل، يضيع الحقد فقط~ العتاد يبقى!',
'Forge can craft gear too. 30000 Malice for Heroic+.':'المسبك يصنع عتاداً أيضاً. 30000 حقد للبطولي+.',
'Random, but you might get something great!':'عشوائي، لكن قد تحصل على شيء عظيم!',
'Shield needs magic, HP needs physical to be effective.':'الدرع يحتاج سحراً، HP يحتاج فيزيائياً ليكون فعّالاً.',
'Wrong type only does 50%! Switch weapons!':'النوع الخاطئ 50% فقط! بدّل الأسلحة!',
'Gear with prefix/suffix gets special effects.':'العتاد مع البادئة/اللاحقة يحصل على تأثيرات خاصة.',
'Only on Heroic+ gear! Enhance the good rolls!':'فقط على عتاد بطولي+! عزّز الجيد!',
'Enhancement auto-transfers to new gear. Just costs Malice.':'التعزيز ينتقل تلقائياً للعتاد الجديد. فقط يكلف حقداً.',
'Equip better gear right away! Enhancement carries over!':'جهّز العتاد الأفضل فوراً! التعزيز ينتقل!',
'You need to parry to absorb resources!':'تحتاج للصد لامتصاص الموارد!',
'Try F-key Sacred Domain. Resources fill up.':'جرّب F-key نطاق مقدس. الموارد تمتلئ.',
'When enemies get close, use Space! Use Spike Trap!':'عندما يقترب الأعداء، استخدم Space! استخدم فخ الأشواك!',
'Stun them! Groggy means 1.5x damage!':'أذهلهم! الترنح يعني 1.5× ضرر!',
'Use key 1 Giant Slam to push them back!':'استخدم مفتاح 1 ضربة عملاقة لدفعهم!',
'It kneels.':'يركع.',
'Now! Press the attack!!':'الآن! هاجم!!',
'Got skill points! Press K to learn skills!':'لديك نقاط مهارة! اضغط K لتعلم المهارات!',
'...Without power, this is where it ends.':'...بدون قوة، هنا تنتهي.',
"...Salvage what you don't need.":'...فكّك ما لا تحتاجه.',
"So many items~ We'll collect for you!":'الكثير من العناصر~ سنجمعها لك!',
'Out of Malice.':'نفد الحقد.',
'Open TAB and salvage gear! Even junk becomes Malice!':'افتح TAB وفكّك العتاد! حتى الخردة تصبح حقداً!',
'Nice gear! Press G for the forge!':'عتاد جيد! اضغط G للمسبك!',
"...Without enhancement, it's just scrap.":'...بدون تعزيز، مجرد خردة.',
"...Don't stop. The goddess doesn't wait.":'...لا تتوقف. الإلهة لا تنتظر.',
"Let's move on~ I don't wanna stay here either.":'لنتحرك~ لا أريد البقاء هنا أيضاً.',
'...The smell is thick. Something big is here.':'...الرائحة كثيفة. شيء كبير هنا.',
'Ready? Check your potions!':'مستعد؟ تحقق من جرعاتك!',
'Press TAB. Open your bag and equip your gear.':'اضغط TAB. افتح حقيبتك وجهّز عتادك.',
'Picked it up? Equip it! TAB!':'التقطته؟ جهّزه! TAB!',
'G. You can craft potions at the forge too.':'G. يمكنك صنع جرعات في المسبك أيضاً.',
'Craft potions with Malice! Press G!':'اصنع جرعات بالحقد! اضغط G!',
'Stunned! Press Ctrl!':'مذهول! اضغط Ctrl!',
'Ctrl Ghost Walk to escape!':'Ctrl مشي شبحي للهروب!',
'Ctrl Ice Orb to escape!':'Ctrl كرة الجليد للهروب!',
'Red bullets: RMB parry. Rainbow: Q parry.':'طلقات حمراء: صد أيمن. قوسية: صد Q.',
'Everything else can be parried with RMB!':'كل شيء آخر يمكن صده بالأيمن!',
'Red=RMB, Rainbow=Q parry. Deflect the rest.':'أحمر=أيمن، قوسي=Q صد. اصد الباقي.',
'Rainbow with Q! Everything else with RMB!':'القوسي بـ Q! كل شيء آخر بالأيمن!',
'Fall back! Drink potions and recover somewhere safe.':'تراجع! اشرب الجرعات وتعافَ في مكان آمن.',
'No resources? Running is the answer!':'لا موارد؟ الهروب هو الحل!',
'Space! Pin them with Spike Trap!':'Space! ثبّتهم بفخ الأشواك!',
'Too many melee! Create distance!':'كثير من القتال القريب! ابتعد!',
"...Get surrounded and it's over. Break out.":'...التطويق يعني النهاية. اخرج.',
'Use key 1 Giant Slam to sweep them!':'استخدم مفتاح 1 ضربة عملاقة لاكتساحهم!',
'Groggy triggers 1.5x damage!':'الترنح يفعّل 1.5× ضرر!',
"Use Whirlwind or AoE! One-by-one and you're dead.":'استخدم الزوبعة أو المساحي! واحداً تلو الآخر وستموت.',
"When they clump, that's your chance!":'عندما يتجمعون، هذه فرصتك!',
'Try E for magic attacks! You need magic to break Malice shields!':'جرّب E للهجمات السحرية! تحتاج سحراً لكسر دروع الحقد!',
'Shields need magic, HP needs physical. Wrong type does no damage.':'الدروع تحتاج سحراً، HP يحتاج فيزيائياً. النوع الخاطئ لا يضر.',
'Press L to assign skills to slots.':'اضغط L لتعيين المهارات في الخانات.',
'Press C. Passive points have stacked up.':'اضغط C. نقاط السلبيات تراكمت.',
'Press C! Passives make you way stronger!':'اضغط C! السلبيات تجعلك أقوى بكثير!',
"Low on stamina. Don't overdo it.":'التحمل منخفض. لا تبالغ.',
'No ST means no skills! Pull back!':'لا ST يعني لا مهارات! تراجع!',
'Open TAB gear menu. We picked up an item!':'افتح قائمة TAB. التقطنا عنصراً!',
'Something good dropped! Open TAB to check!':'سقط شيء جيد! افتح TAB للتحقق!',
'They say Malice addiction turns you into a demon with revival power. Like that one.':'يقولون إدمان الحقد يحوّلك لشيطان بقوة البعث. مثل ذاك.',
'Maybe you too...?':'ربما أنت أيضاً...؟',
'If damage is lacking, enhance your weapons!!':'إن كان الضرر ناقصاً، عزّز أسلحتك!!',
"G key for forge. Without enhancement, you'll keep dying here.":'مفتاح G للمسبك. بدون تعزيز، ستستمر في الموت هنا.',
'No time. Move.':'لا وقت. تحرّك.',
"Don't just stand there!":'لا تقف هكذا!',
'...What are you waiting for?':'...ماذا تنتظر؟',
"Let's go! Monsters are waiting!":'هيا! الوحوش تنتظر!',
'Staying here too long is dangerous.':'البقاء هنا طويلاً خطير.',
"Gotta move! Stand still and they'll surround you!":'تحرّك! توقف وسيحيطون بك!',
"Rest after you're dead.":'استرح بعد موتك.',
'No resting while alive!':'لا راحة وأنت حي!',
'Enemies are closing in. Move fast.':'الأعداء يقتربون. تحرّك بسرعة.',
"They'll smell you. Hurry!":'سيشمّونك. أسرع!',
'...You are still alive, right?':'...لا تزال حياً، صحيح؟',
'Did you fall asleep...?':'هل نمت...؟',
'...The trees are rotting. This is the entrance to hell.':'...الأشجار تتعفن. هذا مدخل الجحيم.',
"The stench is awful... Let's pass through quickly.":'الرائحة مروعة... لنمر بسرعة.',
'Careful. Worm nest. They crawl from walls and floors.':'حذر. عش الديدان. يزحفون من الجدران والأرضيات.',
'Ugh... I hate bugs! Stomp them!':'أف... أكره الحشرات! ادهسهم!',
'...The air is freezing. Fire works here.':'...الهواء متجمد. النار تعمل هنا.',
"Cold... Watch out for freeze! Get frozen and it's over.":'برد... احذر التجمد! تجمّد وانتهى الأمر.',
'Lava. Step on the ground and you burn alive.':'حمم. ادخل الأرض واحترق حياً.',
'So hot! Why is everything so red here!':'حار جداً! لماذا كل شيء أحمر هنا!',
"...The legion. Too many. Without AoE you'll be overwhelmed.":'...الفيلق. كثيرون جداً. بدون مساحي ستُغمر.',
'Crawling everywhere... Gross. Wipe them all at once!':'يزحفون في كل مكان... مقزز. امسحهم دفعة واحدة!',
"Apostle's territory. These ones are smart.":'أرض الرسول. هؤلاء أذكياء.',
'Patterns got complex... Focus!':'الأنماط أصبحت معقدة... ركّز!',
'...This is it. The heart of hell. Abandon hope of return.':'...هذه هي. قلب الجحيم. تخلَّ عن أمل العودة.',
'This is the end... Brace yourself.':'هذه النهاية... استعد.',
};

// I'll generate the other languages with the same approach
// Due to the massive size, let me just output the file

function generateFile(langCode, langUpper, langName, mainMap, pfxMap, baseMap) {
  let out = `// 지옥의 길 — ${langName}\n`;
  out += `const _${langUpper}={\n`;

  const entries = Object.entries(data.main);
  for (let i = 0; i < entries.length; i++) {
    const [k, en] = entries[i];
    const v = mainMap[k] || en;
    const kEsc = k.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
    const vEsc = v.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
    out += `'${kEsc}':'${vEsc}'`;
    if (i < entries.length - 1) out += ',';
    out += '\n';
  }
  out += '};\n';

  // PFX
  out += `const _${langUpper}_PFX={\n`;
  const pfxEntries = Object.entries(data.pfx);
  for (let i = 0; i < pfxEntries.length; i++) {
    const [k, en] = pfxEntries[i];
    const v = pfxMap[k] || en;
    const kEsc = k.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
    const vEsc = v.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
    out += `'${kEsc}':'${vEsc}'`;
    if (i < pfxEntries.length - 1) out += ',';
    out += '\n';
  }
  out += '};\n';

  // BASE
  out += `const _${langUpper}_BASE={\n`;
  const baseEntries = Object.entries(data.base);
  for (let i = 0; i < baseEntries.length; i++) {
    const [k, en] = baseEntries[i];
    const v = baseMap[k] || en;
    const kEsc = k.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
    const vEsc = v.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
    out += `'${kEsc}':'${vEsc}'`;
    if (i < baseEntries.length - 1) out += ',';
    out += '\n';
  }
  out += '};\n';

  return out;
}

// For now just generate AR
fs.writeFileSync('lang/ar.js', generateFile('ar', 'AR', 'العربية (ar)', ar, arPfx, arBase));
console.log('AR done:', Object.keys(ar).length, 'entries');

// AR PFX and BASE
const arPfx = {
'녹슨':'صدئ','강철':'فولاذ','흑요석':'سبج','미스릴':'ميثريل','심판의':'الحكم','천벌의':'العقاب الإلهي','파멸의':'الدمار',
'불꽃':'لهب','화염':'جحيم','염화':'نار جهنم','지옥불':'لظى','지옥화':'لظى','지옥':'لظى','멸화의':'إبادة',
'냉기':'صقيع','빙결':'متجمد','빙하':'جليدي','서리의':'ضباب','서리':'ضباب','영겁빙':'جليد أبدي',
'그림자':'ظل','암흑':'ظلام','심연':'سحيق','나락의':'هاوية','나락':'هاوية','무간의':'فراغ',
'전기':'شرارة','낙뢰':'رعد','암전':'برق','뇌신의':'إله العواصف','뇌신':'إله العواصف','만뢰의':'آلاف الرعود',
'축복':'مبارك','성광':'نور مقدس','신성':'مقدس','천사의':'ملائكي','신벌의':'عقاب إلهي',
'낡은':'بالٍ','천':'قماش','가죽':'جلد','강철사':'نسيج فولاذي','은':'فضة','은사':'خيط فضي','화염의':'ناري','빙결의':'جليدي','암흑의':'مظلم','암전의':'برقي'
};

const arBase = {
'대검':'سيف عظيم','석궁':'قوس','연사석궁':'رشاش','마력석궁':'قوس سحري',
'견갑':'درع كتف','대견갑':'درع كتف كبير','전투화':'حذاء قتالي','갑옷':'درع','갑주':'درع',
'왕관':'تاج','장갑':'قفازات','건틀릿':'قفازات حديدية','바지':'سروال','각반':'واقي ساق',
'허리띠':'حزام','벨트':'حزام','부적':'تميمة','목걸이':'قلادة','반지':'خاتم',
'망토':'عباءة','팔찌':'سوار','귀걸이':'قرط'
};

fs.writeFileSync('lang/ar.js', generateFile('ar', 'AR', 'العربية (ar)', ar, arPfx, arBase));
console.log('AR generated');
