#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""CAT-92 번역 삽입 스크립트 — 16개 키를 26개 lang_*.js 에 추가"""

import os
import re

BASE = r"G:/hell"

# 26개 언어 코드 → var 이름 매핑
LANG_MAP = {
    "zh":   "_ZH",
    "ja":   "_JA",
    "zht":  "_ZHT",
    "es":   "_ES",
    "ru":   "_RU",
    "de":   "_DE",
    "ptbr": "_PTBR",
    "fr":   "_FR",
    "pl":   "_PL",
    "it":   "_IT",
    "uk":   "_UK",
    "tr":   "_TR",
    "vi":   "_VI",
    "th":   "_TH",
    "id":   "_ID",
    "ar":   "_AR",
    "sv":   "_SV",
    "da":   "_DA",
    "no":   "_NO",
    "fi":   "_FI",
    "cs":   "_CS",
    "hu":   "_HU",
    "ro":   "_RO",
    "nl":   "_NL",
    "el":   "_EL",
    "bg":   "_BG",
}

# CAT-92 16개 키 → 언어별 번역
# key: Korean string → {lang_code: translation}
TRANSLATIONS = {
    "흑요염 파괴자": {
        "zh":   "黑焰破坏者",
        "ja":   "黒炎の破壊者",
        "zht":  "黑炎破壞者",
        "es":   "Destructor de Llamas de Obsidiana",
        "ru":   "Разрушитель Чёрного Пламени",
        "de":   "Zerstörer des Obsidianfeuers",
        "ptbr": "Destruidor das Chamas de Obsidiana",
        "fr":   "Destructeur des Flammes d'Obsidienne",
        "pl":   "Niszczyciel Czarnego Płomienia",
        "it":   "Distruttore della Fiamma d'Ossidiana",
        "uk":   "Руйнівник Чорного Полум'я",
        "tr":   "Obsidyen Alev Yok Edicisi",
        "vi":   "Kẻ Hủy Diệt Ngọn Lửa Đen",
        "th":   "ผู้ทำลายเปลวไฟออบซิเดียน",
        "id":   "Penghancur Api Obsidian",
        "ar":   "مدمر اللهب الأسود",
        "sv":   "Obsidianlågeförstöraren",
        "da":   "Obsidianflammens Ødelægger",
        "no":   "Obsidianflammens Ødelegger",
        "fi":   "Obsidiaanitulen Tuhoaja",
        "cs":   "Ničitel Obsidiánových Plamenů",
        "hu":   "Obszidián Láng Pusztítója",
        "ro":   "Distrugătorul Flăcărilor de Obsidian",
        "nl":   "Verwoester van het Obsidiaan Vuur",
        "el":   "Καταστροφέας Φλόγας Οψιδίου",
        "bg":   "Разрушителят на Черния Пламък",
    },
    "방어↓": {
        "zh":   "防御↓",
        "ja":   "防御↓",
        "zht":  "防禦↓",
        "es":   "DEF↓",
        "ru":   "ЗАЩ↓",
        "de":   "VER↓",
        "ptbr": "DEF↓",
        "fr":   "DEF↓",
        "pl":   "OBR↓",
        "it":   "DIF↓",
        "uk":   "ЗАХ↓",
        "tr":   "SAV↓",
        "vi":   "GIÁ↓",
        "th":   "ป้อง↓",
        "id":   "DEF↓",
        "ar":   "دفاع↓",
        "sv":   "FÖRSV↓",
        "da":   "FORSV↓",
        "no":   "FORS↓",
        "fi":   "PUOL↓",
        "cs":   "OBR↓",
        "hu":   "VÉD↓",
        "ro":   "APĂ↓",
        "nl":   "VERD↓",
        "el":   "ΆΜΥ↓",
        "bg":   "ЗАЩ↓",
    },
    "⚡ 연격!": {
        "zh":   "⚡ 连击！",
        "ja":   "⚡ 連撃！",
        "zht":  "⚡ 連擊！",
        "es":   "⚡ ¡Golpe rápido!",
        "ru":   "⚡ Стремительный удар!",
        "de":   "⚡ Schnellangriff!",
        "ptbr": "⚡ Golpe Rápido!",
        "fr":   "⚡ Frappe rapide !",
        "pl":   "⚡ Błyskawiczny cios!",
        "it":   "⚡ Colpo rapido!",
        "uk":   "⚡ Швидкий удар!",
        "tr":   "⚡ Hızlı Vuruş!",
        "vi":   "⚡ Đòn Tốc Chiến!",
        "th":   "⚡ โจมตีรวดเร็ว!",
        "id":   "⚡ Serangan Cepat!",
        "ar":   "⚡ ضربة سريعة!",
        "sv":   "⚡ Snabbattack!",
        "da":   "⚡ Hurtigangrep!",
        "no":   "⚡ Hurtigangrep!",
        "fi":   "⚡ Nopea isku!",
        "cs":   "⚡ Rychlý úder!",
        "hu":   "⚡ Gyors csapás!",
        "ro":   "⚡ Lovitură rapidă!",
        "nl":   "⚡ Snelle aanval!",
        "el":   "⚡ Γρήγορη επίθεση!",
        "bg":   "⚡ Бърз удар!",
    },
    "⚔ 난타!": {
        "zh":   "⚔ 乱打！",
        "ja":   "⚔ 乱打！",
        "zht":  "⚔ 亂打！",
        "es":   "⚔ ¡Lluvia de golpes!",
        "ru":   "⚔ Шквал ударов!",
        "de":   "⚔ Trommelfeuer!",
        "ptbr": "⚔ Barragem!",
        "fr":   "⚔ Volée de coups !",
        "pl":   "⚔ Seria ciosów!",
        "it":   "⚔ Raffica!",
        "uk":   "⚔ Шквал ударів!",
        "tr":   "⚔ Çarpışma!",
        "vi":   "⚔ Mưa Đòn!",
        "th":   "⚔ ฝนหมัด!",
        "id":   "⚔ Serangan Bertubi!",
        "ar":   "⚔ وابل من الضربات!",
        "sv":   "⚔ Hagelskur!",
        "da":   "⚔ Haglbyge!",
        "no":   "⚔ Haglbyge!",
        "fi":   "⚔ Iskuryöppy!",
        "cs":   "⚔ Úder za úderem!",
        "hu":   "⚔ Csapáseső!",
        "ro":   "⚔ Rafală de lovituri!",
        "nl":   "⚔ Hagel van slagen!",
        "el":   "⚔ Επιθέσεις!",
        "bg":   "⚔ Поредица от удари!",
    },
    "💥 강타!": {
        "zh":   "💥 重击！",
        "ja":   "💥 強打！",
        "zht":  "💥 重擊！",
        "es":   "💥 ¡Golpazo!",
        "ru":   "💥 Сокрушительный удар!",
        "de":   "💥 Wuchtschlag!",
        "ptbr": "💥 Pancada!",
        "fr":   "💥 Coup violent !",
        "pl":   "💥 Mocny cios!",
        "it":   "💥 Colpo potente!",
        "uk":   "💥 Нищівний удар!",
        "tr":   "💥 Güçlü Vuruş!",
        "vi":   "💥 Đòn Mạnh!",
        "th":   "💥 โจมตีหนัก!",
        "id":   "💥 Hantaman!",
        "ar":   "💥 ضربة قوية!",
        "sv":   "💥 Hårt slag!",
        "da":   "💥 Hårdt slag!",
        "no":   "💥 Hardt slag!",
        "fi":   "💥 Raskas isku!",
        "cs":   "💥 Silný úder!",
        "hu":   "💥 Erős csapás!",
        "ro":   "💥 Lovitură puternică!",
        "nl":   "💥 Zware slag!",
        "el":   "💥 Δυνατό χτύπημα!",
        "bg":   "💥 Силен удар!",
    },
    "🌀 휘두르기!": {
        "zh":   "🌀 横扫！",
        "ja":   "🌀 薙ぎ払い！",
        "zht":  "🌀 橫掃！",
        "es":   "🌀 ¡Barrido!",
        "ru":   "🌀 Размах!",
        "de":   "🌀 Schwung!",
        "ptbr": "🌀 Varredura!",
        "fr":   "🌀 Balayage !",
        "pl":   "🌀 Zamach!",
        "it":   "🌀 Falciata!",
        "uk":   "🌀 Розмах!",
        "tr":   "🌀 Savurma!",
        "vi":   "🌀 Quét!",
        "th":   "🌀 กวาด!",
        "id":   "🌀 Sapuan!",
        "ar":   "🌀 كنسة!",
        "sv":   "🌀 Svep!",
        "da":   "🌀 Fejning!",
        "no":   "🌀 Fei!",
        "fi":   "🌀 Pyyhkäisy!",
        "cs":   "🌀 Švih!",
        "hu":   "🌀 Söprés!",
        "ro":   "🌀 Baleaj!",
        "nl":   "🌀 Zwiep!",
        "el":   "🌀 Σάρωση!",
        "bg":   "🌀 Замах!",
    },
    "독사": {
        "zh":   "毒蛇",
        "ja":   "毒蛇",
        "zht":  "毒蛇",
        "es":   "Serpiente venenosa",
        "ru":   "Ядовитая змея",
        "de":   "Giftschlange",
        "ptbr": "Cobra Venenosa",
        "fr":   "Serpent venimeux",
        "pl":   "Jadowity wąż",
        "it":   "Serpente velenoso",
        "uk":   "Отруйна змія",
        "tr":   "Zehirli Yılan",
        "vi":   "Rắn độc",
        "th":   "งูพิษ",
        "id":   "Ular Berbisa",
        "ar":   "أفعى سامة",
        "sv":   "Giftorm",
        "da":   "Giftslange",
        "no":   "Giftslange",
        "fi":   "Myrkkykyy",
        "cs":   "Jedovatý had",
        "hu":   "Mérges kígyó",
        "ro":   "Șarpe veninos",
        "nl":   "Gifslang",
        "el":   "Δηλητηριώδες φίδι",
        "bg":   "Отровна змия",
    },
    "🐍 독사!": {
        "zh":   "🐍 毒蛇！",
        "ja":   "🐍 毒蛇！",
        "zht":  "🐍 毒蛇！",
        "es":   "🐍 ¡Serpiente venenosa!",
        "ru":   "🐍 Ядовитая змея!",
        "de":   "🐍 Giftschlange!",
        "ptbr": "🐍 Cobra Venenosa!",
        "fr":   "🐍 Serpent venimeux !",
        "pl":   "🐍 Jadowity wąż!",
        "it":   "🐍 Serpente velenoso!",
        "uk":   "🐍 Отруйна змія!",
        "tr":   "🐍 Zehirli Yılan!",
        "vi":   "🐍 Rắn độc!",
        "th":   "🐍 งูพิษ!",
        "id":   "🐍 Ular Berbisa!",
        "ar":   "🐍 أفعى سامة!",
        "sv":   "🐍 Giftorm!",
        "da":   "🐍 Giftslange!",
        "no":   "🐍 Giftslange!",
        "fi":   "🐍 Myrkkykyy!",
        "cs":   "🐍 Jedovatý had!",
        "hu":   "🐍 Mérges kígyó!",
        "ro":   "🐍 Șarpe veninos!",
        "nl":   "🐍 Gifslang!",
        "el":   "🐍 Δηλητηριώδες φίδι!",
        "bg":   "🐍 Отровна змия!",
    },
    "더블탭 or Shift+방향키! 전격이동으로 탈출해!": {
        "zh":   "双击或Shift+方向键！冲刺逃脱！",
        "ja":   "ダブルタップかShift+方向キー！ダッシュで脱出！",
        "zht":  "雙擊或Shift+方向鍵！衝刺脫逃！",
        "es":   "¡Doble toque o Shift+Dirección! ¡Dash para escapar!",
        "ru":   "Двойной тап или Shift+Направление! Рывок для побега!",
        "de":   "Doppeltippen oder Shift+Richtung! Dash zur Flucht!",
        "ptbr": "Toque duplo ou Shift+Direção! Avance para escapar!",
        "fr":   "Double pression ou Shift+Direction ! Dash pour fuir !",
        "pl":   "Podwójne stuknięcie lub Shift+Kierunek! Dash by uciec!",
        "it":   "Doppio tocco o Shift+Direzione! Scatta per scappare!",
        "uk":   "Подвійний тап або Shift+Напрямок! Ривок для втечі!",
        "tr":   "Çift Dokunuş veya Shift+Yön! Kaçmak için Dash!",
        "vi":   "Nhấn đúp hoặc Shift+Hướng! Lao để thoát!",
        "th":   "แตะสองครั้งหรือ Shift+ทิศทาง! แดชเพื่อหนี!",
        "id":   "Ketuk dua kali atau Shift+Arah! Dash untuk kabur!",
        "ar":   "انقر مرتين أو Shift+اتجاه! اندفع للهروب!",
        "sv":   "Dubbeltryck eller Shift+Riktning! Dash för att fly!",
        "da":   "Dobbelttryk eller Shift+Retning! Dash for at flygte!",
        "no":   "Dobbelttrykk eller Shift+Retning! Dash for å flykte!",
        "fi":   "Kaksoisnapautus tai Shift+Suunta! Liuku paetaksesi!",
        "cs":   "Dvojité klepnutí nebo Shift+Směr! Dash k útěku!",
        "hu":   "Dupla érintés vagy Shift+Irány! Dash a meneküléshez!",
        "ro":   "Dublu tap sau Shift+Direcție! Dash să scapi!",
        "nl":   "Dubbeltik of Shift+Richting! Dash om te ontsnappen!",
        "el":   "Διπλό πάτημα ή Shift+Κατεύθυνση! Dash για απόδραση!",
        "bg":   "Двойно докосване или Shift+Посока! Тире за бягство!",
    },
    "👻 공성유령!": {
        "zh":   "👻 攻城幽灵！",
        "ja":   "👻 攻城幽霊！",
        "zht":  "👻 攻城幽靈！",
        "es":   "👻 ¡Fantasma Asediador!",
        "ru":   "👻 Призрак Осады!",
        "de":   "👻 Belagerungsgeist!",
        "ptbr": "👻 Fantasma Sitiador!",
        "fr":   "👻 Fantôme Assiégeant !",
        "pl":   "👻 Upiór Oblężniczy!",
        "it":   "👻 Fantasma assediante!",
        "uk":   "👻 Привид облоги!",
        "tr":   "👻 Kuşatma Hayaleti!",
        "vi":   "👻 Bóng Ma Vây Hãm!",
        "th":   "👻 ผีล้อม!",
        "id":   "👻 Hantu Pengepung!",
        "ar":   "👻 شبح الحصار!",
        "sv":   "👻 Belägringsande!",
        "da":   "👻 Belejringsånd!",
        "no":   "👻 Beleiriingsånd!",
        "fi":   "👻 Piirityshaamu!",
        "cs":   "👻 Obléhací přízrak!",
        "hu":   "👻 Ostromkísértet!",
        "ro":   "👻 Fantoma Asediului!",
        "nl":   "👻 Belegerings-geest!",
        "el":   "👻 Φάντασμα πολιορκίας!",
        "bg":   "👻 Обсаден призрак!",
    },
    "💥 공성유령 폭발!": {
        "zh":   "💥 攻城幽灵爆炸！",
        "ja":   "💥 攻城幽霊爆発！",
        "zht":  "💥 攻城幽靈爆炸！",
        "es":   "💥 ¡Explosión del Fantasma Asediador!",
        "ru":   "💥 Взрыв Призрака Осады!",
        "de":   "💥 Belagerungsgeist-Explosion!",
        "ptbr": "💥 Explosão do Fantasma Sitiador!",
        "fr":   "💥 Explosion du Fantôme Assiégeant !",
        "pl":   "💥 Eksplozja Upiora Oblężniczego!",
        "it":   "💥 Esplosione del fantasma assediante!",
        "uk":   "💥 Вибух привида облоги!",
        "tr":   "💥 Kuşatma Hayaleti Patlaması!",
        "vi":   "💥 Vụ Nổ Bóng Ma Vây Hãm!",
        "th":   "💥 ผีล้อมระเบิด!",
        "id":   "💥 Ledakan Hantu Pengepung!",
        "ar":   "💥 انفجار شبح الحصار!",
        "sv":   "💥 Belägringsandeexplosion!",
        "da":   "💥 Belejringsåndeksplosion!",
        "no":   "💥 Beleiriingsåndeksplosjon!",
        "fi":   "💥 Piirityshaamu räjähtää!",
        "cs":   "💥 Výbuch obléhacího přízraku!",
        "hu":   "💥 Ostromkísértet robbanás!",
        "ro":   "💥 Explozia Fantomei Asediului!",
        "nl":   "💥 Belegerings-geest explosie!",
        "el":   "💥 Έκρηξη Φαντάσματος Πολιορκίας!",
        "bg":   "💥 Взрив на обсадения призрак!",
    },
    "프레임 표시 (FPS)": {
        "zh":   "显示帧率 (FPS)",
        "ja":   "フレーム表示 (FPS)",
        "zht":  "顯示幀率 (FPS)",
        "es":   "Mostrar FPS",
        "ru":   "Показать FPS",
        "de":   "FPS anzeigen",
        "ptbr": "Mostrar FPS",
        "fr":   "Afficher FPS",
        "pl":   "Pokaż FPS",
        "it":   "Mostra FPS",
        "uk":   "Показати FPS",
        "tr":   "FPS Göster",
        "vi":   "Hiển thị FPS",
        "th":   "แสดง FPS",
        "id":   "Tampilkan FPS",
        "ar":   "عرض FPS",
        "sv":   "Visa FPS",
        "da":   "Vis FPS",
        "no":   "Vis FPS",
        "fi":   "Näytä FPS",
        "cs":   "Zobrazit FPS",
        "hu":   "FPS megjelenítése",
        "ro":   "Arată FPS",
        "nl":   "Toon FPS",
        "el":   "Εμφάνιση FPS",
        "bg":   "Покажи FPS",
    },
    "데모 종료": {
        "zh":   "演示结束",
        "ja":   "デモ終了",
        "zht":  "演示結束",
        "es":   "Fin del Demo",
        "ru":   "Конец демо",
        "de":   "Demo-Ende",
        "ptbr": "Fim do Demo",
        "fr":   "Fin de la démo",
        "pl":   "Koniec dema",
        "it":   "Fine della demo",
        "uk":   "Кінець демо",
        "tr":   "Demo Sonu",
        "vi":   "Kết thúc Demo",
        "th":   "จบเดโม",
        "id":   "Akhir Demo",
        "ar":   "نهاية العرض التوضيحي",
        "sv":   "Demo slut",
        "da":   "Demo slut",
        "no":   "Demo slutt",
        "fi":   "Demo loppu",
        "cs":   "Konec dema",
        "hu":   "Demo vége",
        "ro":   "Sfârșit demo",
        "nl":   "Demo einde",
        "el":   "Τέλος δοκιμαστικής έκδοσης",
        "bg":   "Край на демото",
    },
    "여기까지 데모입니다...": {
        "zh":   "演示到此结束...",
        "ja":   "ここまでがデモです...",
        "zht":  "演示到此結束...",
        "es":   "Aquí termina el demo...",
        "ru":   "На этом демо заканчивается...",
        "de":   "Hier endet die Demo...",
        "ptbr": "Aqui termina o demo...",
        "fr":   "Voici la fin de la démo...",
        "pl":   "To koniec dema...",
        "it":   "Questa è la fine della demo...",
        "uk":   "Демо закінчується тут...",
        "tr":   "Demo burada bitiyor...",
        "vi":   "Demo kết thúc tại đây...",
        "th":   "นี่คือจุดสิ้นสุดของเดโม...",
        "id":   "Demo berakhir di sini...",
        "ar":   "ينتهي العرض التوضيحي هنا...",
        "sv":   "Demon slutar här...",
        "da":   "Demoen slutter her...",
        "no":   "Demoen slutter her...",
        "fi":   "Demo loppuu tähän...",
        "cs":   "Demo končí zde...",
        "hu":   "A demo itt ér véget...",
        "ro":   "Demo-ul se termină aici...",
        "nl":   "De demo eindigt hier...",
        "el":   "Το demo τελειώνει εδώ...",
        "bg":   "Демото свършва тук...",
    },
    "STEAM 위시리스트로 응원해 주세요!": {
        "zh":   "请在Steam心愿单中支持我们！",
        "ja":   "Steamのウィッシュリストで応援してください！",
        "zht":  "請在Steam願望清單中支持我們！",
        "es":   "¡Apóyanos añadiéndolo a tu lista de deseos en Steam!",
        "ru":   "Поддержите нас, добавив в список желаний Steam!",
        "de":   "Unterstütze uns mit einem Wunschlisten-Eintrag auf Steam!",
        "ptbr": "Apoie-nos adicionando à lista de desejos na Steam!",
        "fr":   "Soutenez-nous en ajoutant à la liste de souhaits Steam !",
        "pl":   "Wesprzyj nas dodając do listy życzeń Steam!",
        "it":   "Supportaci aggiungendo ai desideri su Steam!",
        "uk":   "Підтримай нас, додавши до списку бажань Steam!",
        "tr":   "Steam İstek Listesine ekleyerek bizi destekleyin!",
        "vi":   "Hãy ủng hộ chúng tôi bằng cách thêm vào danh sách ước muốn trên Steam!",
        "th":   "สนับสนุนเราด้วยการเพิ่มในรายการ Wishlist ของ Steam!",
        "id":   "Dukung kami dengan menambahkan ke Daftar Keinginan Steam!",
        "ar":   "ادعمنا بإضافتنا إلى قائمة رغبات Steam!",
        "sv":   "Stöd oss genom att lägga till på Steam-önskelistan!",
        "da":   "Støt os ved at tilføje til Steam-ønskelisten!",
        "no":   "Støtt oss ved å legge til Steam-ønskelisten!",
        "fi":   "Tue meitä lisäämällä Steam-toivelistalle!",
        "cs":   "Podpořte nás přidáním do seznamu přání na Steamu!",
        "hu":   "Támogass minket a Steam kívánságlistára való felvétellel!",
        "ro":   "Susține-ne adăugând la lista de dorințe Steam!",
        "nl":   "Steun ons door toe te voegen aan de Steam-verlanglijst!",
        "el":   "Υποστήριξέ μας προσθέτοντας στη λίστα επιθυμιών Steam!",
        "bg":   "Подкрепете ни, като добавите в Steam списъка с желания!",
    },
    "STEAM 위시리스트": {
        "zh":   "Steam心愿单",
        "ja":   "Steam ウィッシュリスト",
        "zht":  "Steam願望清單",
        "es":   "Lista de deseos de Steam",
        "ru":   "Список желаний Steam",
        "de":   "Steam-Wunschliste",
        "ptbr": "Lista de Desejos da Steam",
        "fr":   "Liste de souhaits Steam",
        "pl":   "Lista życzeń Steam",
        "it":   "Lista dei desideri Steam",
        "uk":   "Список бажань Steam",
        "tr":   "Steam İstek Listesi",
        "vi":   "Danh sách ước muốn Steam",
        "th":   "Steam Wishlist",
        "id":   "Daftar Keinginan Steam",
        "ar":   "قائمة رغبات Steam",
        "sv":   "Steam-önskelista",
        "da":   "Steam-ønskeliste",
        "no":   "Steam-ønskeliste",
        "fi":   "Steam-toivelista",
        "cs":   "Seznam přání Steam",
        "hu":   "Steam kívánságlista",
        "ro":   "Lista de dorințe Steam",
        "nl":   "Steam-verlanglijst",
        "el":   "Λίστα επιθυμιών Steam",
        "bg":   "Steam списък с желания",
    },
}

def process_file(lang_code):
    filepath = os.path.join(BASE, f"lang_{lang_code}.js")
    if not os.path.exists(filepath):
        print(f"[SKIP] {filepath} not found")
        return

    with open(filepath, "r", encoding="utf-8") as f:
        content = f.read()

    # Find which keys are missing
    missing = []
    for ko_key in TRANSLATIONS:
        # Check if this Korean key exists in the file
        if ko_key not in content:
            missing.append(ko_key)

    if not missing:
        print(f"[OK]   lang_{lang_code}.js — all keys present")
        return

    # Build insertion block
    lines = ["", "// --- CAT-92 sync ---"]
    for ko_key in missing:
        val = TRANSLATIONS[ko_key].get(lang_code, "")
        if val:
            # Escape single quotes in key and value
            esc_key = ko_key.replace("'", "\\'")
            esc_val = val.replace("'", "\\'")
            lines.append(f"'{esc_key}':'{esc_val}',")

    insert_block = "\n".join(lines) + "\n"

    # Insert before final `};`
    # Find last occurrence of `};`
    last_close = content.rfind("};")
    if last_close == -1:
        print(f"[ERR]  lang_{lang_code}.js — could not find closing }}")
        return

    new_content = content[:last_close] + insert_block + content[last_close:]

    with open(filepath, "w", encoding="utf-8") as f:
        f.write(new_content)

    print(f"[ADD]  lang_{lang_code}.js — inserted {len(missing)} keys: {missing}")

for lang_code in LANG_MAP:
    process_file(lang_code)

print("\nDone.")
