// 지옥의 길 — Norsk (no)
const _NO={
// --- Stage / Boss ---
'썩은 숲':'Råtten Skog','숲의 감시자':'Skogvakt','독버섯 거인':'Giftsopp Kjempe','숲의 사냥꾼':'Skogsjeger','숲의 기생수':'Parasittisk Udyr',
'1장 — 썩은 숲':'KAP1 — Råtten Skog','2장 — 벌레굴':'KAP2 — Ormehull','3장 — 얼음굴':'KAP3 — Ishule',
'4장 — 고통의 화염지대':'KAP4 — Infernalsk Ødemark','5장 — 지옥의 군단':'KAP5 — Helvedes Legion','6장 — 사도의 마굴':'KAP6 — Apostelens Hule','7장 — 지옥성':'KAP7 — Helvetesfestning',
'탈출!':'Rømte!','처치':'Kills','경험치':'EXP','최대콤보':'Maks Kombo',
// --- Tutorial (Crow) ---
'일어나. 여신이 널 여기 보낸 건 죽으라고가 아니야.':'Reis deg. Gudinnen sendte deg ikke hit for å dø.',
'좋아, 감각이 있군. 계속 쳐!':'Bra, du har instinkt. Fortsett å slå!',
'Shift를 눌러. 작살이다. 땅에 꽂아서 끌려가!':'Trykk Shift. Det er harpunen. Stikk den inn og bli dradd!',
'작살로 끌려가는 중엔 무적이다. 위험할 때 쓰면 좋아.':'Du er usårbar mens harpunen drar deg. Bruk det i fare.',
'...아파? 당연하지. 여긴 지옥이야.':'...Gjør det vondt? Selvfølgelig. Dette er helvete.',
'Q를 눌러! 악의로 보호막을 만들 수 있다.':'Trykk Q! Lag et skjold med ondskap.',
'보호막 없이 버틸 생각은 버려.':'Glem å overleve uten skjold.',
'우클릭이 패링이다. 적 공격이 닿기 직전에 눌러!':'Høyreklikk for å parere. Trykk rett før fienden treffer!',
'못 하겠으면 때려. 안 죽으면 그만이야.':'Kan du ikke parere? Slå dem bare. Å ikke dø er nok.',
'됐어! 감 잡았구나.':'Der! Du skjønner det.',
'하나 죽었군.':'En ned.',
'유령쇠뇼야. 인사해.':'Det er geistarmbrøsten. Si hei.',
'빨간 탄을 무서워하지 마. 악의가 강하다.':'Frykt ikke røde kuler. Ondskap er sterk.',
'패링으로 돌려주고, Q 보호막도 써! 악의를 잘 굴려!':'Parér dem tilbake, bruk Q-skjold også! Behersk din ondskap!',
'무지개빛은 패링 불가! 피해!':'Regnbuesskudd kan ikke pareres! Unngå!',
'피가 새고 있다. Shift. 빠져.':'Du blør ut. Shift. Bort herfra.',
'물약 있잖아! 숫자키!':'Du har drikker! Talltaster!',
'우클릭. 적 손목이 꺾일 때 쳐.':'Høyreklikk. Slå når håndleddet bøyer.',
'빨간 탄은 악의 덩어리다. 쳐내서 이용해.':'Røde kuler er klumper av ondskap. Slå dem tilbake og bruk dem.',
'무지개빛만 피하면 돼! 나머지는 다 패링!':'Unngå bare regnbuen! Parér alt annet!',
'Q 보호막도 패링이 가능해!':'Q-skjoldet kan også parere!',
'위험해! 쉬프트 사슬기동으로 피해!!':'Fare! Shift kjededash for å rømme!!',
'쉬프트! 사슬기동은 이동기야! 끌려가면서 무적이라고!':'Shift! Kjededash er bevegelse! Usårbar mens du dras!',
'스킬포인트가 쌓였어! K 눌러서 스킬 배우자!':'Ferdighetspoeng klart! Trykk K for å lære ferdigheter!',
'속성을 읽어. 약점을 찌르면 두 배로 썩는다.':'Les elementene. Treffe svakheter for dobbel skade.',
'K를 눌러봐! 스킬을 배울 수 있어!':'Trykk K! Du kan lære ferdigheter!',
'C 눌러서 능력치 찍어! 패시브도 있어~':'Trykk C for stats! Passive også~',
'G를 눌러. 대장간에서 장비를 강화할 수 있다.':'Trykk G. Oppgrader utstyr ved smia.',
'F키도 스킬 슬롯이야! 스킬 많으면 L로 배정해봐~':'F er også et ferdighets-spor! Bruk L til å tildele~',
'Z. 필살기다. 아껴 써라.':'Z. Det er ditt ultimat. Bruk det klokt.',
'L-CTRL로 유령걸음이나 얼음보주 쓸 수 있어!':'L-CTRL for Åndevandring eller Iskule!',
'L을 눌러. 스킬 슬롯을 정리해야 한다.':'Trykk L. Organiser ferdighets-sporene dine.',
'가방 터지겠다! V 눌러서 창고에 넣어둬!':'Vesken sprekker! Trykk V for å lagre!',
'ESC로 설정 열 수 있어! 난이도 바꾸기, 자동물약 조절~':'ESC for innstillinger! Vanskelighetsgrad, auto-drikker~',
// --- Tutorial (Cat) ---
'...아직 살아있네. 좌클릭으로 저것들 쳐봐.':'...Fortsatt i live. Prøv å treffe dem med venstreklikk.',
'...치는 건 할 줄 아네. 피하는 건?':'...Du kan slå. Men kan du unngå?',
'흥, 작살 못 맞추면 헛수고야.':'Hmph, mister harpunen og det er bortkastet.',
'...운이 좋았을 뿐이야. 아마.':'...Bare flaks. Sannsynligvis.',
'...고기 냄새. 싫진 않네.':'...Lukter kjøtt. Ikke ille.',
'...말은 못해.':'...Den kan ikke snakke.',
'예쁘다고 만지면 죽어.':'Røre dem fordi de er vakre? Du dør.',
'작살 던져! 끌려가면 무적이야!':'Kast harpunen! Usårbar mens du dras!',
'...마시든 말든. 네 목숨이니까.':'...Drikk eller ikke. Det er livet ditt.',
'그게 패링이야! 타이밍이 전부야~':'Det er en parering! Timing er alt~',
'화염엔 빙결! 암전엔 암흑! 기억해!':'Ild slår Is! Lyn slår Mørke! Husk!',
'...얼어붙은 놈은 오래 안 간다.':'...Frosne fiender varer ikke lenge.',
'얼었어! 빙결 중 1.5배야!':'Fryst! 1,5x skade mens fryst!',
'...힘을 골라라. 전부 가질 순 없다.':'...Velg din kraft. Du kan ikke ha alt.',
'스탯을 올려. 살고 싶으면.':'Hev statistikkene dine. Hvis du vil leve.',
'좋은 장비는 강화해야 진짜 힘을 발휘해!':'Godt utstyr trenger oppgraderinger for sitt sanne potensial!',
'...슬롯을 채워. 빈 손은 죽음이다.':'...Fyll sporene. Tomme hender betyr død.',
'Z 누르면 대박! 쿨타임 길어서 타이밍 봐야 해!':'Trykk Z for enorm skade! Lang nedkjøling, tidsinnstill det!',
'Ctrl. 위기에 쓸 카드가 하나 늘었군.':'Ctrl. Enda et kort for nødsituasjoner.',
'스킬이 많아졌네~ L로 어디에 뭘 넣을지 골라!':'Så mange ferdigheter~ Bruk L til å tildele!',
'...버리기 아까운 건 창고에.':'...Lagre det som er for godt til å miste.',
'...살아남은 것만으로도 대단하군. 설정을 확인해.':'...Bare å overleve er imponerende. Sjekk innstillinger.',
// --- System Messages ---
'MP 부족!':'Ikke nok MP!','ST 부족!':'Ikke nok ST!','악의 부족!':'Ikke nok Ondskap!',
'충전 중...':'Lader...','캔슬':'Avbryt','아이템 선택 필요':'Velg et element',
'악의 소진...':'Ondskap uttømt...','비문 발견...':'Inskripsjon funnet...',
'HP물약!':'HP Drikk!','HP물약 +1':'HP Drikk +1','HP물약 +2':'HP Drikk +2',
'HP/MP/ST 회복!':'HP/MP/ST Gjenopprettet!','보물상자 개봉!':'Kiste Åpnet!',
'익사!':'Drukner!','피웅덩이!':'Blodpøl!','독혈!':'Giftig Blod!','잡힘!':'Grepet!',
'콤보 종료':'Kombo Slutt',
// --- Status Effects ---
'빙결!':'Fryst!','화상!':'Brennende!','독!':'Gift!','감전!':'Sjokket!',
'기절!':'Bedøvet!','봉인됨!':'Forseglet!','관통!':'Gjennomboret!',
// --- Skill Names ---
'기검참':'Ki Hugg','악의구':'Ondskapsball','회전참':'Hvirvelvind','기폭팔':'Detonér',
'칼등 처내기':'Klingeparering','만화방창':'Nålstorm','멸살광선':'Utryddelsesstråle',
'원소추적탄':'Elementjeger','악의 보호자':'Ondskaps Vokter','악의 사냥':'Ondskaps Jakt',
'폭풍소환':'Hvirvelvindskalling','해골무덤':'Bengrav','신성폭발':'Hellig Eksplosjon',
'블랙':'Sort Stjerne','용암소환':'Lava Kalling','처형':'Henrettelse','악마화 부활':'Demon Oppstandelse',
'붉은꽃':'Karmosinblomstring','얼음보주':'Iskule','뇌전걸음':'Åndevandring',
'만화방창 II':'Nålstorm II','마력연사':'Magisk Beskytning','마력광선':'Magisk Laser','업화선':'Helvetesstråle',
'지옥진':'Inferno Formasjon','폭독칼날':'Pestklinge','악의폭풍':'Ondskaps Storm',
'악의기둥':'Mørk Søyle','회복의 영역':'Hellig Domene','구속의 영역':'Bindende Domene',
'아이스스톰':'Isstorm','대왕치기':'Kjempeslag','대왕치기 2':'Kjempeslag II',
'기동불꽃':'Kjedelue','기동파괴':'Kjededestruction','기동칼날개':'Kjedevingeklinge',
'평화의보호':'Fredens Skjold','참회':'Anger','칼등날개':'Skjoldvinge',
'폭산탄':'Eksplosivt Skudd','파쇄의 영역':'Knusningsdomene','침식의 영역':'Erosjonsdomene',
'관통의 영역':'Gjennomboringsdomene','부활의 영역':'Oppstandelsesdomene','가시덫':'Tornefelle',
'푸른비':'Asurblå Regn','버스트루프':'Utbruddsloop','유령 허수아비':'Fantom Lokkedue','폭발 허수아비':'Eksplosiv Lokkedue',
'공성쇠뇼':'Beleiringsarmbrøst','사슬기동:충돌':'Kjededash: Kollisjon',
'사슬기동:화염':'Kjededash: Flamme','전격이동':'Lynsteg',
// --- Skill Activation ---
'기동칼날개!':'Vingeklinge!','기동불꽃!':'Kjedelue!','기동파괴!':'Kjededestruction!',
'사슬이동:강화!':'Kjededash!','사슬기동:화염!':'Kjedeflamme!',
'작살!':'Harpun!','진입!':'Inngang!','레인라이트닝!':'Regnlyn!',
'마력연사!':'Magisk Beskytning!','🔷 마력광선!':'🔷 Magisk Laser!','광선 해제':'Laser Av','MP 부족 — 광선 해제':'MP tomt — Laser Av','집중...':'Fokus...','시전...':'Støpning...',
'만화방창!':'Nålstorm!','바늘출!':'Nålutbrudd!','칼날!':'Klinge!',
'착지!':'Landing!','체간삭감!':'Holdning Brudd!',
'기동전폭 준비!':'Kjede Eksplosjon Klar!','기동불꽃 준비!':'Kjedelue Klar!',
'기동파괴 준비!':'Kjededestruction Klar!',
'유령불꽃 ON':'Åndeflamme PÅ','유령불꽃 OFF':'Åndeflamme AV',
'기동칼날개 AUTO ON':'Vingeklinge AUTO PÅ','기동칼날개 AUTO OFF':'Vingeklinge AUTO AV',
'자동 버스트!':'Auto Utbrudd!','연사 해제':'Hurtigild Av',
'당기기 모드':'Trekkemodus','밀어내기 모드':'Dyttemodus',
// --- Skill Slot Tooltips ---
'날개치기':'Vingeslag','처내기':'Parér',
'Shift: 작살 발사 → 끌려감':'Shift: Harpunkast → dradd',
'Shift: 화염길+화상':'Shift: Flamspor+brannsår',
'CT: 전류변신+뇌전걸음 (쿨4초)':'CT: Lynform+Åndevandring (CD 4s)',
'CT: 방어구체+빙결 (재입력: 파쇄)':'CT: Iskule+frysing (gjenta: knusing)',
// --- HUD ---
'근접':'Nærkamp','견갑':'Skjold','작살':'Harpun','마법':'Magi','보막':'Skjold','유령':'Ånd',
'스킬':'Ferdigheter','대장':'Smi','인벤':'Inv',
// --- Menu ---
'인벤토리':'Inventar','복수의 대장간':'Hevnens Smie','패시브 스킬':'Passive Ferdigheter',
'전투 스킬':'Kampferdigheter','캐릭터 선택':'Karaktervalg',
// --- Elements ---
'물리':'Fysisk','화염':'Ild','빙결':'Is','암흑':'Mørke','암전':'Lyn','신성':'Hellig','대지':'Jord',
// --- Passives ---
'힘':'Styrke','민첩':'Fingernemhet','지능':'Intelligens','행운':'Flaks',
'맹공':'Angrep','철벽':'Festning','돌파':'Gjennombrudd','반격':'Motangrep',
'마력폭주':'Magisk Raseri','정밀사격':'Presisjonsskyting','수호':'Beskyttelse','수호신':'Skytsånd',
'회복력':'Restitusjon','급소':'Vital Treff','약탈':'Plyndring','관통':'Gjennomtrengning',
'마력회복':'Mana Restitusjon','쇠뇌력':'Armbrøstbeherskelse','광전사':'Berserk','추적자':'Sporer',
'물리관통':'Fysisk Pen.','마법관통':'Magisk Pen.',
// --- Weapons (Tier 0) ---
'녹슨 대검':'Rustet Tohandsssverd','강철 대검':'Stål Tohandsssverd','흑요석 대검':'Obsidian Tohandsssverd',
'낡은 석궁':'Slitt Armbrøst','강철 석궁':'Stål Armbrøst','흑요석 석궁':'Obsidian Armbrøst',
'대검':'Tohandsssverd','석궁':'Armbrøst','연사석궁':'Repeterarmbrøst','마력석궁':'Magisk Armbrøst',
// --- Misc ---
'악의 추출':'Ondskap Ekstraksjon','악의':'Ondskap','필살기':'Ultimat','필살기 해제':'Ultimat Tomt',
'이전':'Overføring','강화':'Forbedring','개봉!':'Åpnet!',
'여신의 가호':'Gudinnens Velsignelse',
'과부하!':'Overbelastning!',
// --- Affix Names ---
'맹독의':'Giftig','불꽃의':'Flammende','냉기의':'Frysende','번개의':'Elektrisk','암흑의':'Forbannet',
'관통의':'Gjennomborende','광폭의':'Rasende','파쇄의':'Knusende','연쇄의':'Kjedet',
'학살의':'Slaktende','폭발의':'Eksplosiv','집중의':'Fokusert','쾌속의':'Rask','패리의':'Pareringsende',
'추적자의':"Sporernes",'작살의':'Harpun','궁극의':'Ytterste','집중력의':'Oppmerksom',
'강인의':'Seig','수호의':'Voktende','활력의':'Vital','신속의':'Hastig',
'화염수호':'Ildvakt','빙결수호':'Isvakt','암전수호':'Lynvakt','암흑수호':'Mørkevakt','독수호':'Giftvakt','전원소수호':'Allvakt',
'강철의':'Jernhard','반사의':'Reflekterende','가시의':'Tornet','흡수의':'Absorberende','인내의':'Utholdende',
'위기의':'Desperat','피격반격의':'Hevnende',
'패링폭발의':'Pareringseksplosjon','스태거폭발의':'Staggereksplosjon','원소전환의':'Konverter','정화의':'Rensende',
'불굴의':'Ubrytelig','부활의':'Oppstående',
'약탈의':'Plyndrende','경험의':'Erfaren','골드의':'Gyllen','포션강화의':'Potent','사슬의':'Kjedet',
'진혼의':'Hellende','윤회의':'Syklisk',
'생명력의':'Livskraftig','재생의':'Regenererende','치유의':'Helende',
'마력의':'Magisk','절약의':'Effektiv','영혼의':'Sjelebundet',
'예리한':'Skarp','맹렬한':'Brutal','파멸의':'Fordervelig',
// --- Settings UI ---
'게임 설정':'Spillinnstillinger','화면 흔들림':'Skjermristing','파티클 양':'Partikkel Mengde',
'효과음 볼륨':'Lydeffekt Volum','음악 볼륨':'Musikk Volum','난이도':'Vanskelighetsgrad',
'자동 물약':'Auto Drikk','최소 줍기 등급':'Min Opphenting Rang','최소 줍기 티어':'Min Opphenting Tier',
'FPS 제한':'FPS Grense','해상도 스케일':'Oppløsningsskala','펫 자동수거':'Kjæledyr Auto-Samle',
'화면 설정':'Visningsinnstillinger','화면 모드':'Visningsmodus','보스 AI 디버그':'Boss AI Debug',
'유령불꽃 크기':'Åndeflamme Størrelse','화면 명암':'Lysstyrke','유령 글로우':'Ånd Glød',
'기동:칼날개 AUTO':'Vingeklinge AUTO',
'일반':'Normal','어려움':'Vanskelig','지옥':'Helvete','이상':'eller høyere','사용 안 함':'Deaktivert',
'창 모드':'Vindu','보더리스':'Kantløst','전체화면':'Fullskjerm',
'설정':'Innstillinger','조작 키 설정 (클릭하여 변경)':'Tastebinding (Klikk for å endre)',
// --- Key Guide ---
'좌클릭 무기 공격':'LMB Våpenangrep','우클릭 탭 칼등 처내기':'RMB Trykk Klingeparering',
'우클릭 홀드 연속 처내기':'RMB Hold Kontinuerlig Parering','SHIFT 작살 발사':'SHIFT Harpunavfyring',
'이동':'Bevegelse','아이템 줍기':'Plukke opp Gjenstand','능력치 (스탯/패시브)':'Stats (Stats/Passive)',
// --- Forge ---
'복수의 대장간':'Hevnens Smie','강화':'Forbedring','분해':'Demontering','제작':'Fremstilling',
// --- Death Screen ---
'사망':'Død','부활':'Oppstandelse','로비로':'Til Lobby',
// --- Inventory/Storage ---
'가방에 공간이 없습니다!':'Ingen plass i veske!','가방이 가득 찼습니다!':'Veske er full!',
'창고가 가득 찼습니다!':'Lager er fullt!','퀵슬롯이 가득 찼습니다!':'Hurtig-spor er fullt!',
'결정 주머니가 가득 찼습니다!':'Krystallpung er full!','결정 주머니 가득!':'Krystallpung full!',
'악의가 부족합니다!':'Ikke nok Ondskap!','가방이 비어있습니다':'Veske er tom',
'창고가 비어있습니다':'Lager er tomt','비어있음':'Tom','어픽스 없음':'Ingen affix',
'장착!':'Utrustet!','해제':'Avmontert','보관':'Lagre','꺼내기':'Hent',
'현재 장착':'Nåværende utstyrt','없음 — 제작하세요!':'Ingen — Fremstill en!',
'리셋할 포인트가 없습니다':'Ingen poeng å nullstille',
'키 설정 초기화 완료':'Tastinnstillinger nullstilt',
// --- Forge/Craft ---
'제작 확률':'Fremstillingschanse','제작 비용':'Fremstillingskostnader','보유 악의':'Ondskap eid',
// --- Canvas UI ---
'보스방':'Bossrom','안식처':'Helligdom','회복':'Restitusjon','점화':'Antennelse',
'비석':'Stele','읽기':'Les','파괴':'Ødelegg','제단':'Alter','기원':'Bønn',
'잔해':'Vrak','열기':'Åpne','문지기':'Portvakt',
'부활 판정 중...':'Oppstandelsesvurdering...','기폭 준비!':'Detonering Klar!',
'탈출':'Flukt','연타':'Mash',
'추적암전':'Sporende Lyn','만화방창':'Luminansstråle','최종 마법':'Endelig Magi',
'감시중':'Overvåker','대기':'Standby','작동중':'Aktiv','설치 가능':'Kan installere',
'균열 임박!':'Sprekk forestående!','흡수 중...':'Absorberer...',
'흡수 완료 — 재입력으로 회수':'Ferdig — gjenta for å samle inn',
'화상':'Brannsår','당기기':'Trekk','밀어내기':'Dytt',
'단계':'tier','단':'tier',
// --- Skill Panel ---
'습득!':'Lært!','리셋!':'Nullstilt!','세팅!':'Innstilt!','회수':'Tilbakekall',
'합체 해제':'Defusjonér','리셋':'Nullstill','환불':'Refusjon',
'파트너 클릭!':'Klikk partner!','SP부족!':'SP nødvendig!',
'같은 보석 스킬 습득 시 합체 가능':'Kan fusjonere ved innlæring av samme juvelferdigheit',
'펼쳐서 초기화':'Utvid for å nullstille','슬롯:':'Spor:',
// --- Stats ---
'남은 SP':'SP Gjenværende','처치':'Kills','경험치':'EXP','최대콤보':'Maks Kombo',
'맞아서 사망':'Døde av treff','레벨':'Nivå','최대HP':'Maks HP',
// --- Enemy Names ---
'방랑 기사':'Vandrende Ridder','보물 악마':'Skattdemon','거울의 사도':'Speilapostel',
'상인 악마':'Handelsdemon','사슬의 죄수':'Kjedet Fange','시간의 사도':'Tidsapostel',
'탐욕의 사도':'Griskhetens Apostel','저주받은 쌍둥이':'Forbannede Tvillinger','차원 균열체':'Dimensjonal Sprekk',
'죽음 그 자체':'Døden Selv',
// --- Crystals ---
'HP결정':'HP Krystall','ST결정':'ST Krystall','MP결정':'MP Krystall',
'ATK결정':'ATK Krystall','DEF결정':'DEF Krystall','속도결정':'Hastighetskrystall',
'크리결정':'Krit Krystall','치명결정':'KritSkade Krystall','화염결정':'Ildkrystall',
'냉기결정':'Iskrystall','암흑결정':'Mørkekrystall','번개결정':'Lynkrystall',
'신성결정':'Hellig Krystall','생명결정':'Livskrystall','기력결정':'Utholdenhets Krystall',
'마력결정':'Mana Krystall','행운결정':'Flakskrystall',
'조각':'Fragment','파편':'Splint','순수결정':'Ren Krystall','완전결정':'Perfekt Krystall',
'결정 주머니':'Krystallpung','결정이 없습니다':'Ingen krystaller','가루':'Støv',
'전체':'Alle','스탯':'Stat','원소':'Elem','유틸':'Util',
'현재':'Nåværende','최대 강화 달성 (+20)':'Maks forbedret (+20)','강화 시':'Etter forbedring',
'강화':'Forbedring','합성':'Syntese','제작':'Fremstilling',
'같은 종류·같은 성급 결정 3개 → 1성급 상승 (강화 리셋)':'3 krystaller av samme type og rang → 1 rang oppgradering (forbedring nullstilt)',
'합성 가능한 결정이 없습니다 (같은 종류·성급 3개 필요)':'Ingen krystaller å syntetisere (trenger 3 av samme type og rang)',
'결정 분해 → 결정 가루':'Krystall Demontering → Krystallstøv',
'분해할 결정이 없습니다':'Ingen krystaller å demontere',
'결정 제작 (가루 → 결정)':'Fremstill Krystall (Støv → Krystall)',
'탈착':'Frakoble','빈 슬롯':'Tomt spor',
'결정 선택 후 클릭':'Velg krystall klikk deretter','클릭하여 선택결정 장착':'Klikk for å utruste valgt krystall',
'획득!':'Oppnådd!','제작!':'Fremstilt!','합성!':'Syntetisert!','최상위 일괄합성':'Bulk Synth til Topp','일괄합성 완료':'Bulk synth ferdig',
// --- Stage Names ---
'벌레굴':'Ormehull','얼음굴':'Ishule','고통의 화염지대':'Infernalsk Ødemark',
'지옥의 군단':'Helvedes Legion','사도의 마굴':'Apostelens Hule','지옥성':'Helvetesfestning',
// --- Misc ---
'엑소듀서 전사':'Exoduser Kriger','포이즈':'Holdning',
'신성폭발':'Hellig Eksplosjon','뇌전걸음':'Åndevandring',
'지옥창고':'Helveteslager','선택분해':'Selektiv Demontering','쓰레기':'Søppel',
'복구 불가!':'Kan ikke gjenopprette!','중요잠금':'Viktig-låst',
// --- Phase 9 additions ---
'획득!':'Oppnådd!','자동 장착!':'Auto-utrustet!','분해! 가루 +':'Demontert! Støv +',
'추적암전':'Sporende Lyn','암전':'Lyn',
'평화보호':'Skjold','지진폭풍':'Jordskjelvstorm','회전기폭':'Hvirvelfostering',
'공격':'Angrep','보호막':'Skjold','필살기':'Ultimat',
'합체 스킬로 통합됨':'Sammenslått til fusjonert ferdighet','얼음보주 안에선 사용 불가!':'Kan ikke brukes inni Iskule!',
'Shift+키로 폭파':'Shift+tast for å detonere','취소':'Avbryt','충전 중...':'Lader...',
'쿨다운 중...':'Nedkjøling...','시전 중...':'Støpning...','악의 부족!':'Ikke nok Ondskap!',
'악의 부족! (12)':'Ikke nok Ondskap! (12)','악의 부족! (15)':'Ikke nok Ondskap! (15)',
'악의 부족! (20)':'Ikke nok Ondskap! (20)','악의 부족! (10)':'Ikke nok Ondskap! (10)',
'ST 부족!':'Ikke nok ST!','HP 부족!':'Ikke nok HP!',
'필살기 슬롯 클릭하여 배정!':'Klikk ultimat-spor for å tildele!',
'필살기 스킬을 습득하세요':'Lær en ultimat ferdighet',
'우클릭(칼등치기)에 합체됨':'Sammenslått til RMB (klingeparering)',
'T(석궁자동)에 세팅하세요':'Still inn på T (auto armbrøst)',
'공성쇠뇼 철거 → 이동식':'Beleiringsarmbrøst demontert → bærbar',
'ST 부족! (100)':'Ikke nok ST! (100)',
'HP 99% 이상!':'HP 99%+!','그로기 보스 없음!':'Ingen bedøvet boss!',
'이미 폭풍 지역!':'Allerede i stormsone!','이미 빙풍 지역!':'Allerede i isstormsone!',
'💎 푸른비 해금!':'💎 Asurblå Regn låst opp!','💫 버스트루프 해금!':'💫 Utbruddsloop låst opp!',
'👻 유령 허수아비 해금!':'👻 Fantom Lokkedue låst opp!',
'쿨 ':'CD ','과부하 ':'Overbelastning ',
'🕊️💎 블루콩!':'🕊️💎 Blå Bønne!','🛡️💎 빨콩→블루콩!':'🛡️💎 Rød→Blå Bønne!',
'🛡️💎 무지개→블루콩!':'🛡️💎 Regnbue→Blå Bønne!',
'레어':'Sjelden','슬롯':'Spor',
'성공률':'Suksessrate','AI 자동 강화':'AI Auto-Forbedring','최대 강화 달성!':'Maks forbedring oppnådd!',
'최대 강화':'Maks forbedret','회복량':'Gjenopprettingmengde','현재 장착':'Nåværende utstyrt',
'없음 — 제작하세요!':'Ingen — Fremstill en!','제작 확률':'Fremstillingschanse',
'분해할 아이템이 없습니다.':'Ingen gjenstander å demontere.','🔨 제작':'🔨 Fremstill',
'체간':'Holdning','아이템에 마우스를 올리거나 좌클릭으로 선택하세요':'Hold musen over en gjenstand eller venstreklikk for å velge',
// --- Phase 10 ---
'중독':'Forgiftning','지뢰':'Mine','함정':'Felle','산호가시':'Korallpigg',
'투사체':'Prosjektil','도트':'DoT','레어몹':'Sjelden Mob',
'처치':'kills','경험치':'EXP','최대콤보':'Maks Kombo',
'구역':'Sone','가시!':'Pigg!',
// --- Hell circle ---
'림보':'Limbo','색욕':'Vellyst','탐식':'Grådighet','탐욕':'Griskhet','분노':'Vrede','이단':'Kjetteri','폭력':'Vold',
'분노!':'Raseri!','탐욕!':'Griskhet!','💀 분노 폭발!':'💀 Raseriutbrudd!','심연의 분노!':'Avgrunns Raseri!','쌍둥이의 분노!':'Tvillingenes Raseri!',
// --- HUD ---
'소환굴':'Spawngrop',
'레어':'Sjelden','처치!':'Beseiret!','왕관 착용':'Krone På','왕관 해제':'Krone Av',
'맨손':'Bare Hender','없음':'Ingen','갑옷':'Rustning','부츠':'Støvler',
// --- Elite / Mod / Aura ---
'매직':'Magisk','챔피언':'Mester',
'빙결':'Fryst','초속':'Hast','강타':'Slag','재생':'Regenerasjon','맹독':'Gift','소환':'Kalling',
'기생':'Parasitt','분열':'Deling','용암자취':'Lavaspor','사망폭발':'Dødseksplosjon',
'화염사슬':'Ildkjede','광전':'Raseri','텔레포트':'Teleportasjon','보호막':'Barriere',
'소용돌이':'Hvirvelvind','환영':'Fantom','전격반사':'Sjokkrefleks','감전':'Elektrificering',
'낙뢰':'Torden','연쇄전격':'Kjedeblixt','동료불사':'Alliert Udødelig',
'영혼포식':'Sjeleoppslukker','시간왜곡':'Tidsforvrengning','혼돈변이':'Kaosmutasjon',
'복수자':'Hevner','마법보초':'Magisk Vakt','환영술사':'Illusjonist',
'함성':'Krigsskriket','치유':'Helbredelse','신속':'Hurtighet','수호':'Vokter',
// --- Character ---
'다크 판타지 전사. 거대검+검은 갑옷':'Mørk fantasy kriger. Tohandsssverd + Sort rustning',
// --- Phase 11 ---
'⚡ 사슬이동:강화!':'⚡ Kjede:Forsterket!',
'⚡ 사슬기동:화염!':'⚡ Kjede Drive: Flamme!',
'달성!':'Oppnådd!',
'ST':'ST','부족!':'Utilstrekkelig!',
'타':'Treff',
'🌀 당기기 모드':'🌀 Trekkemodus',
'💥 밀어내기 모드':'💥 Dyttemodus',
'🕊️빨콩 흡수':'🕊️Rød bønne absorbere',
'🕊️흡수':'🕊️Absorbere',
'💎유도 폭발!':'💎Styrt eksplosjon!',
'💥반사 폭발!':'💥Reflekseksplosjon!',
'⚡⚡ 참회 귀환!':'⚡⚡ Anger Tilbakekomst!',
'⚡ 참회!':'⚡ Anger!',
'파도!':'Bølge!',
'암전!':'Lyn!',
'암흑!':'Mørke!',
'암흑창!':'Mørkespyd!',
'빛창!':'Lysspyd!',
'체 소환!':'Kalt!',
'개 설치!':'Plassert!',
'💥 보스 그로기!':'💥 Boss Bedøvet!',
'💥 그로기!':'💥 Bedøvet!',
'보상':'Bonus',
'⚡ 암전나선!':'⚡ Lynspiral!',
'🌋 지진폭풍!':'🌋 Jordskjelvstorm!',
'SP슬롯':'SP Spor',
'F슬롯':'F Spor',
'⚔🩸 독혈해방!':'⚔🩸 Pestblodsfreleelse!',
'⚔ 칼날 해방!':'⚔ Klingefrigjøring!',
'🔨🌋 지옥강타!':'🔨🌋 Helvetesslag!',
'🔨 대왕치기!':'🔨 Kjempeslag!',
'✟ 결계의 영역!':'✟ Vaktdomene!','✟ 물의 영역!':'✟ Vanndomene!','✟ 파쇄의 영역!':'✟ Knusningsdomene!','✟ 침식의 영역!':'✟ Erosjonsdomene!','✟ 관통의 영역!':'✟ Gjennomboringsdomene!','✟ 권능의 영역!':'✟ Suverentdomene!',
'🛡 회복의 영역!':'🛡 Hellig Domene!',
'임계...!':'Kritisk...!',
'기폭팔!':'Detonér!','강제기폭!':'Tvungen Detonering!','자동기폭!':'Auto Detonering!',
'회전기폭!':'Hvirvelfostering!','해제기폭!':'Frigjørings Detonering!','지진기폭!':'Jordskjelvdetonering!',
'혼돈의 왕관':'Kaosens Krone',
'전지전능의 왕관':'Alvitendes Krone',
'악마의 팔찌':'Demonarmbånd',
'생명의 팔찌':'Livsarmbånd',
// --- wave direction names ---
'🌊 위→아래 파도!':'🌊 Opp→Ned Bølge!','🌊 오른→왼 파도!':'🌊 Høyre→Venstre Bølge!',
'🌊 아래→위 파도!':'🌊 Ned→Opp Bølge!','🌊 왼→오른 파도!':'🌊 Venstre→Høyre Bølge!',
// --- Phase 12 ---
'⚡ 사슬이동:강화!':'⚡ Kjede:Forsterket!','⚡ 사슬기동:화염!':'⚡ Kjede Drive: Flamme!',
'🌀 당기기 모드':'🌀 Trekkemodus','💥 밀어내기 모드':'💥 Dyttemodus',
'💎유도 폭발!':'💎Styrt Eksplosjon!','💥반사 폭발!':'💥Reflekseksplosjon!',
'⚡⚡ 참회 귀환!':'⚡⚡ Anger Tilbakekomst!','⚡ 참회!':'⚡ Anger!',
'암전!':'Lyn!','암흑!':'Mørke!','암흑창!':'Mørkespyd!','빛창!':'Lysspyd!',
'💥 보스 그로기!':'💥 Boss Bedøvet!','💥 그로기!':'💥 Bedøvet!',
'⚡ 암전나선!':'⚡ Lynspiral!','🌋 지진폭풍!':'🌋 Jordskjelvstorm!',
'⚔🩸 독혈해방!':'⚔🩸 Pestblodsfreleelse!','⚔ 칼날 해방!':'⚔ Klingefrigjøring!',
'🔨🌋 지옥강타!':'🔨🌋 Helvetesslag!','🔨 대왕치기!':'🔨 Kjempeslag!',
'✟ 결계의 영역!':'✟ Vaktdomene!','✟ 물의 영역!':'✟ Vanndomene!','✟ 파쇄의 영역!':'✟ Knusningsdomene!','✟ 침식의 영역!':'✟ Erosjonsdomene!','✟ 관통의 영역!':'✟ Gjennomboringsdomene!','✟ 권능의 영역!':'✟ Suverentdomene!','🛡 회복의 영역!':'🛡 Hellig Domene!',
'파도!':'Bølge!',
// --- rare mob / special ---
'무적!':'Usårbar!','🪞 반격!':'🪞 Motangrep!','💢 반격!':'💢 Motangrep!',
'흡수!':'Absorbere!','반격 발사!':'Motangrep Skyting!',
'저주! 드랍률 -50%':'Forbannelse! Droppsjanse -50%','도망!':'Flykt!',
'위상!':'Fase!','방어!':'Forsvar!',
'회수 HP+':'Tilbakekall HP+','이동식 복귀':'Bærbar Tilbakekomst','캔슬':'Avbryt',
'약점!':'Svakhet!','저항!':'Motstand!','관통!':'Gjennomboret!',
'유령불꽃 OFF':'Åndeflamme AV','유령불꽃 ON':'Åndeflamme PÅ',
'기동칼날개 AUTO ON':'Vingeklinge AUTO PÅ','기동칼날개 AUTO OFF':'Vingeklinge AUTO AV',
'콤보 종료: ':'Kombo Slutt: ','익사!':'Drukner!',
'피웅덩이!':'Blodpøl!','독혈!':'Giftig Blod!','비문 발견...':'Inskripsjon funnet...',
'보물상자 개봉!':'Kiste Åpnet!','악의 +':'Ondskap +','잡힘!':'Grepet!',
'저주 ':'Forbannelse ','충전 중...':'Lader...','불발...':'Forsøk mislyktes...',
'작살 약점!':'Harpun Svakhet!',
'전염 x':'Pest x','흡수 완료!':'Absorpsjon Fullført!',
'부활 성공!':'Oppstandelse Lyktes!','부활 실패...':'Oppstandelse Mislyktes...',
'산호가시':'Korallpigg','가시!':'Pigg!','차원 이동!':'Dimensjonalt Skifte!','독!':'Gift!',
'탈출!':'Rømte!','기절 해제':'Bedøvning Opphevet',
'아이템 선택 필요':'Velg en gjenstand','악의 부족':'Ikke nok Ondskap','악의 소진...':'Ondskap uttømt...',
'스킬 미습득':'Ingen ferdigheter lært','펼치기':'Utvid','접기':'Kollaps',
'조건 미달!':' ikke oppfylt!','해제!':' Defusjonert!',
'슬롯':'Spor','자동 ON':' Auto PÅ','자동 OFF':' Auto AV','스킬 해제':' ferdighet avmontert',
'필살기':'Ultimat','필살기 해제':'Ultimat Tomt',
'연사 해제':'Hurtigild Av',
'닫기':'Lukk','장착 중':'Utrustet','보관 아이템':'Lagret Gjenstand',
// --- Phase 13 ---
'클릭으로 선택 · ESC로 닫기':'Klikk for å velge · ESC for å lukke',
'선택됨':'Valgt',
'MP 부족!':'Ikke nok MP!','악의 부족! (30)':'Ikke nok Ondskap! (30)',
'MP 부족! (40)':'Ikke nok MP! (40)','MP 부족! (100)':'Ikke nok MP! (100)','MP 부족! (10)':'Ikke nok MP! (10)',
'MP 부족! (':'Ikke nok MP! (',
'✟ 시전...':'✟ Støpning...','🌋 시전...':'🌋 Støpning...','⛧ 시전...':'⛧ Støpning...',
'❄ 진입!':'❄ Inngang!',
'🔱 작살!':'🔱 Harpun!',
'레벨 부족! (요구: Lv.':'Nivå for lavt! (Krav: Lv.',
' 장착!':' Utrustet!',
'가방에 공간이 없습니다!':'Ingen plass i veske!',
' 해제':' Avmontert',
'👿 악의 추출: +':'👿 Ondskap Ekstraksjon: +',
'F 슬롯 해제':'F Spor avmontert',
'💫 집중...':'💫 Fokus...',
'⚡ 마력연사!':'⚡ Magisk Beskytning!',
'❄빙결!':'❄Fryst!','🟢독!':'🟢Gift!','⚡감전!':'⚡Sjokket!','🔥화상!':'🔥Brennende!',
'✦ 여신의 가호 — SP+5 AP+3':'✦ Gudinnens Velsignelse — SP+5 AP+3',
'⚔ 기동칼날개!':'⚔ Vingeklinge!',
'🔥 화염관통!':'🔥 Ildgjennomboret!',
'🔱 관통!':'🔱 Gjennomboret!',
'⚔ 칼날!':'⚔ Klinge!',
'💥 착지!':'💥 Landing!',
'💫 기절!':'💫 Bedøvet!',
'⚡ 체간삭감!':'⚡ Holdningsbrudd!',
'⚡ 기동파괴! ':'⚡ Kjededestruction! T',
'🔥 기동불꽃!':'🔥 Kjedelue!',
'🔥 기동불꽃! ':'🔥 Kjedelue! T',
'단계 ×':' x',
'⚡ 기동전폭! x':'⚡ Kjede Eksplosjon! x',
'🔥🔥 3중폭!':'🔥🔥 Flamme x3!','🔥🔥🔥 6중폭!':'🔥🔥🔥 Flamme x6!','🔥🔥🔥🔥 9중폭!':'🔥🔥🔥🔥 Flamme x9!','💥 불꽃폭발! ':'💥 Flammedetonering! ',
'🔥 기동불꽃 준비!':'🔥 Kjedelue Klar!',
'🔨 기동파괴 준비!':'🔨 Kjededestruction Klar!',
'⚡ 기동전폭 준비!':'⚡ Kjede Eksplosjon Klar!',
'콤보 종료: ':'Kombo Slutt: ',
'중독':'Forgiftning',
'⚡ 과부하! 5초':'⚡ Overbelastning! 5s',
'💫 자동 버스트!':'💫 Auto Utbrudd!',
'🔨 칼등날개!':'🔨 Skjoldvinge!',
'💥폭발!':'💥Eksplosjon!',
'🛡️💎 유도반사!':'🛡️💎 Styrt Refleks!',
'⚡💎 블루콩!':'⚡💎 Blå Bønne!',
'💎 블루콩!':'💎 Blå Bønne!',
'⚡반사!':'⚡Refleks!',
'💎 푸른비 OFF':'💎 Asurblå Regn AV',
'💎 푸른비 ON!':'💎 Asurblå Regn PÅ!',
'🔥 지옥진!':'🔥 Inferno Formasjon!',
'🔥 업화선!':'🔥 Helvetesstråle!',
'✦ 평화 충격파! ':'✦ Fredens Sjokkbølge! ',
'⚡ 전류 방출!':'⚡ Strøm Frigjøring!',
'⚡⚡ 레인라이트닝!':'⚡⚡ Regnlyn!',
'💫 광역!':'💫 Område!',
'🔥 불장판!':'🔥 Ildsone!',
'💫 피니셔!':'💫 Avslutter!',
'☠ 지옥에서 귀환!':'☠ Kom tilbake fra Helvete!',
'☠ 완전 사망!':'☠ Permanent Død!',
'⚔ 처형! ':'⚔ Henrettelse! ',
'💥 지뢰!':'💥 Mine!',
'⚠ 함정!':'⚠ Felle!',
'❌ 우클릭으로! -':'❌ Bruk RMB! -',
'❌ Q키로! -':'❌ Bruk Q! -',
'💥무지개 폭발! ':'💥Regnbueeksplosjon! ',
'🛡️💎 블루콩!':'🛡️💎 Blå Bønne!',
'⬜화이트볼!':'⬜Hvit Ball!',
'✨💎 블루콩!':'✨💎 Blå Bønne!',
'💜다크볼!':'💜Mørk Ball!',
'❄빙판!':'❄Isgulv!',
'🌨빙결!':'🌨Fryst!',
'🕸둔화!':'🕸Langsom!',
'⚠트랩!':'⚠Felle!',
'💀 역병 처형!':'💀 Pesthenrettelse!',
'💥 역병 Finale!':'💥 Pest Finale!',
'⚔ 균열 악마!':'⚔ Sprekkdemon!',
'자동회수 HP+':'Auto-Tilbakekall HP+',
'MP 부족 — 연사 해제':'MP lavt — Hurtigild Av',
'MP 부족 — 푸른비 OFF':'MP lavt — Asurblå Regn AV',
'🛡️반사!':'🛡️Refleks!',
'⚡🦴 참회 귀환!':'⚡🦴 Anger Tilbakekomst!',
'🦴⚡해골번개!':'🦴⚡Benlyn!',
'⚡악의폭풍!':'⚡Ondskaps Storm!',
'❄아이스스톰!':'❄Isstorm!',
'⚡ 암전폭발!':'⚡ Lyneksplosjon!',
'⚡ 레인라이트닝! x':'⚡ Regnlyn! x',
'❄ 탈출!':'❄ Flukt!',
'⚡쉴드!':'⚡Skjold!',
'❄🌪️ 얼음보주!':'❄🌪️ Iskule!',
'🌪️ 전개!':'🌪️ Deployment!',
'❄ 빙결흡인!':'❄ Fryssugning!',
'❄☄ 빙결폭발!':'❄☄ Fryseksplosjon!',
'☄️ 흡인!':'☄️ Sugning!',
'☄️ 대폭발!':'☄️ Megaeksplosjon!',
'❄ 얼음보주!':'❄ Iskule!','⏳ 시간왜곡!':'⏳ Tidsforvrengning!','쿨다운!':'Nedkjøling!',
'❄ 파쇄!':'❄ Knusing!',
'☄️💥 대폭발!':'☄️💥 Megaeksplosjon!',
'반사!':'Refleks!',
// --- boss moves ---
'💀 도넛!':'💀 Smultring!','💀 전멸!':'💀 Tilintetgjøring!',
'🌊 파도!':'🌊 Bølge!','속박!':'Binde!','반격!':'Motangrep!',
'분신!':'Klon!','분신 파괴!':'Klon Ødelagt!','무기 해방!':'Våpenfrigjøring!',
'❄프리즌!':'❄Fengsel!','⚡ 증표 ':'⚡ Merking ',
'흔들!':'Riste!','⚠ 광역 발사!':'⚠ Område Ild!',
'🔥 확산!':'🔥 Spredning!','⚠ 돌진!':'⚠ Angrep!',
'🦅 도약!':'🦅 Hopp!','⚡ 레이저!':'⚡ Laser!',
'🌊 충격파!':'🌊 Sjokkbølge!','👹 소환!':'👹 Kalling!',
'☄ 유성우!':'☄ Meteorregn!','🖐 잡기!':'🖐 Grep!',
'🌀 회전참!':'🌀 Hvirvelvind!','💣 지뢰!':'💣 Mine!',
'🌀 흡인!':'🌀 Vakuum!','🔴 빨간콩 폭풍!':'🔴 Rød Bønne Storm!',
'🔴🔴 콩 비!':'🔴🔴 Bønne Regn!',
'🌊 부채꼴 충격파!':'🌊 Vifte Sjokkbølge!',
'✴ 멸광 레이저!':'✴ Utryddelseslaser!',
'🔴 추적 장판!':'🔴 Sporsone!',
'💥 속성탄!':'💥 Elementskudd!',
'⚔ 검기!':'⚔ Sverd Ki!','⚔ 재단참!':'⚔ Høst Hugg!',
'🌀 나선탄!':'🌀 Spiralskudd!','⚠ 찌르기!':'⚠ Stikk!',
'🔥🔥 지옥기둥!':'🔥🔥 Helvetessøyle!',
'⚔ 환영검!':'⚔ Fantomsverd!',
'💢 반격자세!':'💢 Motangrepsposisjon!',
'⚔ 연격!':'⚔ Kombo!','🌑 암흑!':'🌑 Mørke!',
'👥 분신!':'👥 Klon!','🌋 균열!':'🌋 Sprekk!',
'🌊 파동!':'🌊 Ripple!','💣 추적지뢰!':'💣 Sporende Mine!',
'⏪ 되감기!':'⏪ Spole tilbake!','🌀 중력장!':'🌀 Gravitasjonsfelt!',
'🔨 벽밀기!':'🔨 Veggskyv!','☠ 독안개!':'☠ Gifttåke!',
'⛓ 감옥!':'⛓ Fengsel!','⚡ 연쇄번개!':'⚡ Kjedeblix!',
'🔮 궤도탄!':'🔮 Orbitalt Skudd!','🛡 방패돌진!':'🛡 Skjoldangrep!',
'🪞 반격자세!':'🪞 Motangrepsposisjon!','⚓ 속박!':'⚓ Binde!',
'👤 분신!':'👤 Klon!','🖐 탈취!':'🖐 Stjele!',
'🔥🔥 용암 지대!':'🔥🔥 Lavasone!',
'🌧🌧 화염 폭격!':'🌧🌧 Ildbarrage!',
'⚡⚡ 전격 장막!':'⚡⚡ Lyngardinen!',
'💀 내 곁으로!':'💀 Kom til meg!',
'⭕ 안전!':'⭕ Trygg!',
'💀💀 전멸 폭발!':'💀💀 Tilintetgjøringseksplosjon!',
'⚡ 쐐기 소멸!':'⚡ Kile Tilintetgjøring!',
'🌊충격파!':'🌊Sjokkbølge!',
'👿악의+100':'👿Ondskap+100',
'💥패링폭발!':'💥Pareringseksplosjon!',
'균열 충돌! ':'Sprekk Kollisjon! ',
'벽 충돌! ':'Vegg Kollisjon! ',
'소환!':'Kalling!','환영!':'Fantom!',
'⚡낙뢰!':'⚡Torden!','⚡빔!':'⚡Stråle!',
'환영술!':'Illusjon!','💀소환!':'💀Kalling!',
'🔮주술!':'🔮Forbannelse!','🩸산란!':'🩸Formering!',
'💢광폭!':'💢Raseri!','🕷산란!':'🕷Formering!',
'❄서리!':'❄Frost!','❄빙결파!':'❄Frysningsbølge!',
'💀빙마!':'💀Isdemon!',
// --- mob actions ---
'돌진!':'Angrep!','충격파!':'Sjokkbølge!','독안개!':'Gifttåke!',
'연타!':'Salve!','포효!':'Brøl!','강화!':'Forsterket!',
'꼬리!':'Hale!','은신...':'Sniker...','기습!':'Bakhold!',
'산란!':'Formering!','독가스!':'Giftgass!','소멸...':'Oppløser...',
'강타!':'Slag!','분비!':'Utskillelse!','채찍!':'Pisk!',
'출혈!':'Blødning!','급강하!':'Dykking!','방출!':'Utladning!',
'충격!':'Påvirkning!','치유!':'Helbredelse!','의식!':'Ritual!',
'지옥불!':'Helvetesild!','끌려감!':'Dradd!','혀!':'Tunge!',
'응시!':'Stirrer!','낙하!':'Fall!','핏방울!':'Bloddråpe!',
'일어남!':'Reiser seg!','휩쓸기!':'Feier!','웅크림':'Krøller seg',
'뼈칼날!':'Benklinge!','감속!':'Senk farten!','비명!':'Skrik!',
'화산탄!':'Vulkanskudd!','자폭!':'Selvødeleggelse!','감싸기!':'Omslut!',
'잡기!':'Grep!','내리찍기!':'Nedslag!','브레스!':'Pust!',
'비행!':'Flykt!','용암비!':'Lavaregn!','물뿜기!':'Vannstråle!',
'빛...':'Lys...','삼키기!':'Svelg!','마비!':'Lammelse!',
'방전!':'Utladning!','집게찍기!':'Tangslag!','찍기!':'Nedslag!',
'붙잡기!':'Grep!','감아올리기!':'Rulle opp!','파편!':'Fragment!',
'할퀴기!':'Klore!','기생충!':'Parasitt!',
'심연 해방!':'Avgrunns Frigjøring!','촉수난타!':'Tentakkelstorm!',
'삼지창!':'Trefork!','소용돌이!':'Hvirvelvind!','해일!':'Tsunami!',
'끼걱!':'Knarring!','폭발!':'Eksplosjon!','체인!':'Kjede!',
'갈기!':'Man!','공포!':'Terror!','흡혈!':'Tapping!',
'베기!':'Hugg!','비이이명!!':'Riiing!!','분열!':'Deling!',
'3연참!':'Triple Hugg!','패링!':'Parering!',
'...복사...':'...Kopiering...','불균형...저주!':'Ubalanse...Forbannelse!',
'저주!':'Forbannelse!','균형...강화!':'Balanse...Forsterket!',
'심판의 기둥!':'Domssøyle!','처형 선고!':'Dødsdom!',
'고통의 해방!':'Smertsfrigjøring!','너도 느껴봐라!':'Kjenn dette også!',
'대검난무!':'Tohandsssverd Raseri!','촉수!':'Tentakel!',
'전방위 빔!':'Omni-Stråle!','회피!':'Unngå!',
// --- rare mob / merchant ---
'[F] 상점':'[F] Butikk','거래 성공!':'Handel Lyktes!',
'악의 부족! (':'Ikke nok Ondskap! (',
'상인이 떠납니다...':'Kjøpmannen drar...',
'사슬 해방!':'Kjedefrigjøring!','완전 해방!':'Full Frigjøring!',
'⏪ 시간 되감기!':'⏪ Tidsspoling!','전환!':'Bytte!',
'부활 ':'Oppstandelse ','🌀균열!':'🌀Sprekk!','...사라짐':'...Forsvant',
'낫 베기!':'Ljå Hugg!','☠ 죽음의 선고!':'☠ Dødsdom!',
'선고 집행...':'Utfører dom...',
'⚡패링!':'⚡Parering!','경직!':'Stagger!',
'⚠ 잡혔다!':'⚠ Grepet!','💥 내던지기!':'💥 Kast!',
'💥 소용돌이 폭발!':'💥 Hvirvelvind Eksplosjon!',
'👻 순간이동!':'👻 Teleportasjon!','💫 기절! 5초':'💫 Bedøvet! 5s',
'찌르기 반격!':'Stikk Motangrep!','💢 폭발!':'💢 Eksplosjon!',
'반격 실패':'Motangrep Mislyktes','탈취 반격!':'Stjele Motangrep!',
'무기 봉인!':'Våpentetting!','냠!':'Nom!',
// --- stage/room/map ---
'합체!':'Fusjonert!','출구가 열렸다!':'Utgang åpnet!',
'보물상자 출현!':'Skattekiste dukket opp!','출구':'Utgang',
'⚠ 문지기가 살아있다!':'⚠ Portvakt fortsatt i live!',
'⏱ 타임어택 ':'⏱ Tidsangrep ',
'처치율 ':'Kill-andel ',
'무적!':'Usårbar!','불사 보호':'Udødelig Beskyttelse',
'빙결!':'Fryst!','환영 소멸!':'Fantom Forsvant!',
'부활력 ':'Oppstandelseskraft ',
'✟ 신성력 억제! (':'✟ Hellig Undertrykkelse! (',
'부활 실패 (':'Oppstandelse Mislyktes (',
'⚡순간이동!':'⚡Teleportasjon!',
'👻 동반부활!':'👻 Med-Oppstandelse!',
'✟ 신성력 억제!':'✟ Hellig Undertrykkelse!',
'💀 부활 판정 중...':'💀 Oppstandelsesvurdering...',
'⚔ 문지기 처치!':'⚔ Portvakt Beseiret!',
'🚪 보스방 개방!':'🚪 Bossrom Åpnet!',
'잔해 출현!':'Vrak dukket opp!',
'🌀균열 발생!':'🌀Sprekk åpnet!',
'🔥복수!':'🔥Hevn!','💥폭독혈!':'💥Pestblod!',
'빙판!':'Isgulv!','❄빙결파!':'❄Frysningsbølge!',
'❄최종빙결!':'❄Endelig Frysing!','빙마 처치!':'Isdemon Beseiret!',
'분리!':'Skill!','뼈 파편!':'Benfragment!',
'태아 처치!':'Foster Beseiret!','지배자 처치!':'Overherre Beseiret!',
'용암!':'Lava!','화룡 처치!':'Ilddrage Beseiret!',
'최후의 비명!':'Siste Skrik!','산화...':'Oksidisering...',
'심판자 처치!':'Dommer Beseiret!','고통의 왕 처치!':'Smertkonge Beseiret!',
'수역!':'Vann!','파편 폭발!':'Fragmenteksplosjon!',
'거대어 처치!':'Leviathan Beseiret!','대사도 처치!':'Høye Apostel Beseiret!',
'독웅덩이!':'Giftpøl!','화염장판!':'Ildsone!','전기장!':'Elektrisk Felt!',
'무기 드롭!':'Våpendropp!','보물 발견!':'Skatt Funnet!',
'상인의 주머니 +':'Kjøpmannens Pung +',
'속박의 파편!':'Bindingssplint!','시간의 조각!':'Tidsfragment!',
'저주 해제!':'Forbannelse Opphevet!','차원의 결정!':'Dimensjonal Krystall!',
'전설 아이템!':'Legendarisk Gjenstand!','죽음을 이겨냈다!':'Overvant Døden!',
'💥대폭발!':'💥Megaeksplosjon!','⚡강화!':'⚡Forsterket!',
// --- combat/defense ---
'장비 ':'Utstyr ',
'💫 진동!':'💫 Vibrasjon!','❄ 무적!':'❄ Usårbar!',
'\u{1F47B} 유령!':'\u{1F47B} Ånd!',
'집중 해제!':'Fokus Avbryt!','집중!':'Fokus!',
'🕊️ 평화보호 ':'🕊️ Fredens Skjold ',
'🛡 보호막 ':'🛡 Skjold ',
'🌀 회전보호막 ':'🌀 Snurrskjold ',
'💥한방캡!':'💥Ett-Slag Grense!',
'⚡쉴드 파괴!':'⚡Skjeldødeleggelse!',
'💀 불굴!':'💀 Ubrytelig!',
'💀 1회부활!':'💀 1-Liv Oppstandelse!',
'감시 회수':'Vakt Tilbakekall',
'악마화 부활!':'Demonisk Oppstandelse!',
// --- skill panel ---
'기검참':'Ki Hugg','날개치기':'Vingeslag',
'배정 가능한 스킬 없음':'Ingen ferdigheter å tildele',
'칼날 없음!':'Ingen Klinge!',
'⚔ 악의사냥!':'⚔ Ondskaps Jakt!',
'❄🌪️ 얼음소용돌이!':'❄🌪️ Ishvirvelvind!',
'🌪️ 폭풍소환!':'🌪️ Hvirvelvindskalling!',
'\u{1F9B4} 해골무덤!':'\u{1F9B4} Bengrav!',
'🌹 붉은꽃!':'🌹 Karmosinblomstring!',
'💥 폭산탄!':'💥 Eksplosivt Skudd!',
'🪡 바늘출!':'🪡 Nålutbrudd!',
'⚡ 전격이동!':'⚡ Lynsteg!',
'기둥가시로 흡수됨':'Absorbert av søylepigg',
'🌿 가시덫!':'🌿 Tornefelle!',
'👻 유령총!':'👻 Åndepistol!','💥 유령총 폭발!':'💥 Åndepistol Eksplosjon!',
'⚡ 전격의창!':'⚡ Torderspyd!',
'🏹 공성쇠뇼 설치!':'🏹 Beleiringsarmbrøst Plassert!',
'👻 유령 허수아비!':'👻 Fantom Lokkedue!',
'💥 폭발 허수아비!':'💥 Eksplosiv Lokkedue!',
'축적!':'Lagret!','축적 중...':'Lagrer...','만충! 재입력→폭발':'Full! Gjenta→Eksplosjon',
'폭발! ':'Eksplosjon! ','불발...':'Forsøk mislyktes...','뎀':' SKA',
'🩸 폭독칼날!':'🩸 Pestklinge!',
'⚡날개치기!':'⚡Vingeslag!',
'🗡 칼등날개!':'🗡 Skjoldvinge!',
'🏛️ 악의기둥!':'🏛️ Mørk Søyle!',
'🌿 기둥가시!':'🌿 Søylepigg!',
'🌋 지옥강타!':'🌋 Helvetesslag!',
'💥 체간 붕괴!':'💥 Holdningskollaps!',
'💫 포이즈 파괴!':'💫 Holdningsødeleggelse!',
'⚡ 뇌전걸음!':'⚡ Åndevandring!',
'✟ 구속의 영역!':'✟ Bindende Domene!',
'✟ 신성폭발!':'✟ Hellig Eksplosjon!',
'⛧ 블랙!':'⛧ Sort Stjerne!',
'🌋 용암소환!':'🌋 Lava Kalling!',
'필살기 배정!':'Ultimat Tildelt!',
'완료':'Fullført','합체 가능':'Kan Fusjonere','부족':'Utilstrekkelig',
'SP 부족! (':'SP nødvendig! (',
'🕊️ 히든: 평화의보호 해금!':'🕊️ Skjult: Fredens Skjold låst opp!',
'⚡ 히든: 참회 해금!':'⚡ Skjult: Anger låst opp!',
'배정됨':'Tildelt',
'합체 Lv.':'Fusjons Lv.',
'◆ 같은 보석 스킬 습득 시 합체 가능':'◆ Kan fusjonere ved innlæring av samme juvelferdigheit',
// --- inventory/forge/storage ---
'▼ 가방 → 창고 보관':'▼ Veske → Lager',
'▲ 창고 → 가방 꺼내기':'▲ Lager → Veske',
'✓ 선택됨':'✓ Valgt',
'⟨ 입력 대기... ⟩':'⟨ Venter... ⟩',
'⟨ 대기 ⟩':'⟨ Vent ⟩',
'보조':'Sub',
'키 설정 초기화 (또는 F5 키)':'Nullstill tastebinding (eller F5)',
'아무 키 또는 마우스 버튼을 누르세요 (ESC = 취소)':'Trykk en tast eller museknapp (ESC = avbryt)',
'WebGPU 활성':'WebGPU Aktiv','WebGL2 활성':'WebGL2 Aktiv',
'측정 중...':'Måler...',
'불러오기 실패':'Innlasting Mislyktes',
'장착':'Utrustet',
'🔒 중요잠금 아이템은 분해 선택 불가!':'🔒 Viktig-låste gjenstander kan ikke velges for demontering!',
'장비 강화 (실패 시 재료만 소멸)':'Forbedre Utstyr (ved feil mister bare materialer)',
'강화 보너스 적용':'Forbedring Bonus Anvendt',
'강화 실패!':'Forbedring Mislyktes!',
'장착된 장비가 없습니다.':'Ingen utstyr utrustet.',
'충분':'Nok','더 필요':'Trenger Mer',
'장비 선택':'Velg Utstyr','목표치 설정':'Angi Mål',
'악의 투입':'Invester Ondskap','자동 시도':'Auto Forsøk',
'목표 강화치':'Mål Forbedring',
'예상 필요 악의':'Estimert Ondskap Nødvendig',
'보유':'Eid','강화 시작':'Start Forbedring',
'위에서 장비를 선택하세요':'Velg utstyr ovenfor',
'⬆ 물약 강화 (최대 10단)':'⬆ Forbedre Drikk (maks nivå 10)',
'필요':'Nødvendig',
'악의의 분해로 — 장비를 악의로 갈아버려라':'Ondskap Ovn — Mal utstyr til ondskap',
'전체 선택':'Velg Alle','전체 해제':'Fjern Alle',
'희귀 이하':'Sjelden eller Lavere',
'어픽스 리롤!':'Affix Omrulling!',
'결정 분해 → 결정 가루':'Krystall Demontering → Krystallstøv',
'결정 제작 (가루 → 결정)':'Fremstill Krystall (Støv → Krystall)',
'물리':'Fysisk','영웅':'Heroisk','전설':'Legendarisk',
'무기 타입':'Våpentype','활 타입':'Buetype',
'보스방':'Bossrom','ST 부족':'Ikke nok ST',
// --- Phase 14 ---
'💀 광폭화!':'💀 Rasende!',
'...따라오는 거 아니야. 같은 방향일 뿐이지.':'...Jeg følger deg ikke. Bare samme retning.',
'공기가 달라졌어. 더 썩었군.':'Luften har endret seg. Mer forråtnelse.',
'여기부터는 악마 영역이야. ...맘대로 해.':'Demonenes territorium herfra. ...Gjør som du vil.',
'...이 냄새. 살점이 썩는 냄새야.':'...Den lukten. Rånende kjøtt.',
'여기 오래 있으면 미쳐. 나도, 너도.':'For lenge her og du blir gal. Det gjør jeg også.',
'이 길의 끝에 뭐가 있을까. ...알고 싶지도 않어.':'Hva er i slutten av denne veien? ...Vil ikke vite.',
'...여기가 끝이야. 돌아갈 길은 없어.':'...Dette er slutten. Ingen vei tilbake.',
// --- idle tips ---
'작살을 땅에 꽂으면 끌려간다.':'Stikk harpunen i bakken og bli dradd.',
'Shift로 작살 던져봐!':'Prøv å kaste harpunen med Shift!',
'패링 성공하면 ST가 회복된다. 공짜 자원이야.':'Parering gjenoppretter ST. Gratis ressurser.',
'패링 많이 하면 ST 걱정 없어~':'Parér mye og ST er aldri et problem~',
'장비 분해하면 악의를 얻는다. 쓰레기도 자원이야.':'Demonter utstyr for Ondskap. Selv søppel er ressurser.',
'TAB 열어서 안 쓰는 장비 분해해!':'Åpne TAB og demonter ubrukt utstyr!',
'그로기 상태의 적에겐 1.5배 데미지가 들어간다.':'Bedøvede fiender tar 1,5x skade.',
'무릎 꿇으면 전력으로 때려!':'Når de kneler, slå med alt!',
'속성 상성이 있다. 화염은 빙결에 약하고, 암전은 암흑에 약하다.':'Elementer har motparter. Ild er svak mot Is, Lyn mot Mørke.',
'무기 속성 바꿔가면서 싸워봐!':'Prøv å bytte våpenelementer!',
'빙결된 적은 1.5배 데미지를 받는다.':'Frosne fiender tar 1,5x skade.',
'얼리고 때리는 게 기본이야!':'Frys og slå — det er det grunnleggende!',
'보스의 빨간 공격은 패링 가능. 보라빛은 회피만.':'Røde bossangrep kan pareres. Regnbue unngå bare.',
'색깔 잘 봐! 빨강은 받아치고 무지개는 피해!':'Se farger! Parér rødt, unngå regnbuen!',
'VIT를 올리면 최대 HP가 오른다. 죽기 싫으면 찍어.':'VIT hever maks HP. Invester hvis du vil leve.',
'STR은 근접, DEX는 활, INT는 마법! 골고루 말고 하나만!':'STR for nærkamp, DEX for buer, INT for magi! Fokuser på ett!',
'E를 꾹 누르면 빔이 나간다. 짧게 누르면 투사체.':'Hold E for stråle. Trykk E for prosjektil.',
'마법 쓸 때 MP 잘 봐! 빔은 연속으로 깎여!':'Se opp med MP med magi! Stråle tømmer raskt!',
'핵터와 디로이가 아이템을 주워준다. 수거 범위 안이면.':'Hecter og Deroy samler automatisk gjenstander innen rekkevidde.',
'우리한테 고마워해~ 안 주우면 썩잖아.':'Takk oss~ Gjenstander råtner hvis ingen plukker dem opp.',
'LCK를 올리면 레어 드롭률이 오른다.':'LCK øker sjelden droppsjanse.',
'운빨 게임이긴 하지~ LCK 올려봐!':'Det er alt flaks~ Prøv å heve LCK!',
'강화하면 공격력이 쭉쭉 올라가! 악의만 있으면 돼!':'Forbedring øker ATK raskt! Trenger bare Ondskap!',
'강화 확률은 +1에서 99%. 높을수록 떨어진다.':'Forbedringschanse starter ved 99% for +1. Synker etter det.',
'실패하면 악의만 날아가~ 장비는 안 부서져!':'Ved feil mister bare Ondskap~ Utstyr overlever!',
'대장간에서 장비 제작도 된다. 악의 30000개면 영웅급 이상.':'Smia kan også fremstille. 30000 Ondskap for Heroisk+.',
'랜덤이지만 좋은 거 나올 수도 있어!':'Tilfeldig, men kanskje noe bra!',
'쉴드는 마법으로, HP는 물리로 깎아야 제대로 먹힌다.':'Skjold trenger magi, HP trenger fysisk.',
'반대로 치면 50%만 들어가! 무기 바꿔가면서 싸워!':'Feil type gir bare 50%! Bytt våpen!',
'장비에 접두사, 접미사가 붙으면 특수 효과가 생긴다.':'Utstyr med for-/etterstavelse får spesialeffekter.',
'영웅급 이상 장비에만 붙어! 좋은 거 나오면 강화해!':'Bare på Heroisk+ utstyr! Forbedre gode resultater!',
'강화는 장비를 바꿔도 자동 이전된다. 악의만 있으면.':'Forbedring overføres automatisk. Koster bare Ondskap.',
'더 좋은 장비 나오면 바로 장착해! 강화 수치 그대로 옮겨가!':'Utrust bedre gear straks! Forbedring overføres!',
// --- Phase 14 additional tutorial ---
'패링을 써야 자원을 흡수한다고!':'Du må parere for å absorbere ressurser!',
'F키 회복의 영역을 써봐. 자원이 차올라.':'Prøv F-tast Hellig Domene. Ressurser fylles opp.',
'적이 근접하면 스페이스키야! 가시덫을 활용해!':'Når fiender kommer nær, bruk Mellomromstast! Bruk Tornefelle!',
'기절시켜! 그로기가 터지면 데미지가 1.5배야!':'Bedøv dem! Bedøvning gir 1,5x skade!',
'1번 대왕치기로 밀어버려!':'Bruk tast 1 Kjempeslag for å skyve dem tilbake!',
'무릎 꿇었다.':'Det kneler.',
'지금이야! 몰아쳐!!':'Nå! Driv på angrepet!!',
'스킬 포인트 있어! K 눌러서 스킬 찍어봐!':'Ferdighetspoeng tilgjengelig! Trykk K for å lære!',
'...힘이 없으면 여기서 끝이야.':'...Uten kraft slutter det her.',
'...쓸 거 아니면 분해해.':'...Demonter det du ikke trenger.',
'아이템 넘쳐나네~ 우리가 주워줄게!':'Så mange gjenstander~ Vi samler for deg!',
'악의가 바닥이다.':'Ondskap oppbrukt.',
'TAB 열어서 장비 분해해! 쓰레기도 악의가 돼!':'Åpne TAB og demonter utstyr! Selv søppel blir Ondskap!',
'좋은 장비가 있네! G 눌러서 대장간 가봐!':'Godt utstyr! Trykk G for smia!',
'...강화 안 하면 그냥 고철이야.':'...Uten forbedring er det bare skrap.',
'...멈추지 마. 여신은 기다리지 않는다.':'...Stopp ikke. Gudinnen venter ikke.',
'앞으로 가자~ 나도 여기 오래 있기 싫어.':'La oss gå videre~ Jeg vil heller ikke bli lenge her.',
'...냄새가 짙다. 큰 놈이 있어.':'...Lukten er sterk. Noe stort er her.',
'준비됐어? 물약 확인하고!':'Klar? Sjekk drikkene dine!',
// --- Phase 15 ---
'TAB을 눌러. 가방을 열고 장비를 입어야 한다.':'Trykk TAB. Åpne vesken og ta på utstyret.',
'주웠으면 껴야지! TAB!':'Plukket det opp? Ta det på! TAB!',
'G. 대장간에서 물약도 제작할 수 있다.':'G. Du kan også fremstille drikker ved smia.',
'악의로 물약 만들어! G키야!':'Fremstill drikker med Ondskap! G-tast!',
'기절이야! Ctrl 눌러!':'Bedøvet! Trykk Ctrl!',
'Ctrl 유령걸음으로 탈출!':'Ctrl Åndevandring for å rømme!',
'Ctrl 얼음보주로 탈출!':'Ctrl Iskule for å rømme!',
'빨간 탄은 우클릭 패링. 무지개는 Q 패링.':'Røde kuler: RMB parér. Regnbue: Q parér.',
'나머지는 전부 우클릭 패링 가능해!':'Alt annet kan pareres med RMB!',
'빨강=우클릭, 무지개=Q 패링. 나머진 다 쳐내.':'Rødt=RMB, Regnbue=Q parér. Avverg resten.',
'무지개는 Q로 패링! 나머지는 전부 우클릭!':'Regnbue med Q! Alt annet RMB!',
'빠져! 물약 마시고 안전한 곳에서 회복해.':'Trekk deg tilbake! Drikk drikker og komm deg et trygt sted.',
'자원 없으면 도망가는 게 답이야!':'Ingen ressurser? Flukt er svaret!',
'스페이스! 가시덫으로 적 묶어버려!':'Mellomromstast! Bind dem med Tornefelle!',
'근접이 너무 많아! 거리 벌려!':'For mange nærkampere! Skap avstand!',
'...둘러싸이면 끝이야. 빠져나와.':'...Omringet og det er slutt. Bryt ut.',
'1번 대왕치기로 쓸어버려!':'Bruk tast 1 Kjempeslag for å feie dem bort!',
'그로기 터지면 데미지 1.5배!':'Bedøvning gir 1,5x skade!',
'회전참이나 광역기로 몰아! 한 놈씩 상대하면 죽어.':'Bruk Hvirvelvind eller Område! En etter en og du dør.',
'뭉쳐있을 때가 기회야!':'Når de klumper seg, er det din sjanse!',
'E로 마력공격을 해봐! 악의 쉴드를 해제할려면 마법 공격을 해야 해!':'Prøv E for magiangrep! Du trenger magi for å bryte Ondskaps skjoldene!',
'쉴드는 마법으로, HP는 물리로. 반대로 치면 데미지 안 들어간다.':'Skjoldene med magi, HP med fysisk. Feil type gir ingen skade.',
'L키로 스킬 슬롯에 넣어야 쓸 수 있어.':'Trykk L for å tildele ferdigheter til spor.',
'C키를 눌러. 패시브 포인트가 쌓여있다.':'Trykk C. Passive poeng har akkumulert.',
'C키! 패시브 올리면 진짜 강해져!':'Trykk C! Passive gjør deg mye sterkere!',
'스태미나가 부족하다. 무리하지 마.':'Lavt utholdenhet. Overdriv det ikke.',
'ST 없으면 스킬 못 써! 잠깐 빠져!':'Ingen ST betyr ingen ferdigheter! Kort tilbaketrekking!',
'탭 장비창을 열어봐. 아이템을 주워왔어!':'Åpne TAB utstyrsmeny. Vi plukket opp en gjenstand!',
'좋은 거 나왔다! TAB 열어서 확인해봐!':'Noe bra droppet! Åpne TAB for å sjekke!',
'악의에 중독되면 악마가 돼서 부활력이 생긴대. 저 녀석처럼.':'De sier Ondskapsavhengighet gjør deg til en demon med oppstandelseskraft. Som den der.',
'혹시 너도...?':'Kanskje du også...?',
'데미지가 부족하면 무기류 강화를 해야해!!':'Hvis skade mangler, forbedre våpnene!!',
'G키 대장간. 강화 안 하면 여기서 계속 죽어.':'G-tast smia. Uten forbedring fortsetter du å dø her.',
'시간이 없어. 움직여.':'Ingen tid. Beveg deg.',
'멍하게 서있으면 안 돼!':'Stå ikke bare der!',
'...뭘 기다리는 거야?':'...Hva venter du på?',
'가자가자! 몬스터가 기다려!':'La oss gå! Monstre venter!',
'여기 오래 있으면 위험해.':'Å bli for lenge her er farlig.',
'움직여야 해! 가만있으면 둘러싸여!':'Må bevege seg! Stå stille og de omringer deg!',
'쉬는 건 죽고 나서 해.':'Hvil etter du er død.',
'살아있을 때 쉬면 안 돼!':'Ingen hvil mens du lever!',
'적이 몰려오고 있어. 빨리 움직여.':'Fiender er på vei. Beveg deg raskt.',
'냄새 맡고 올 거야. 빨리!':'De lukter deg. Skynd deg!',
'...아직 살아있는 거 맞지?':'...Du lever fortsatt, ikke sant?',
'혹시 잠든 거야...?':'Sovnet du...?',
// --- Chapter entry ---
'...나무가 썩어가고 있어. 여기는 지옥의 입구야.':'...Trærne råtner. Dette er inngangen til helvete.',
'냄새 지독해... 빨리 지나가자.':'Stankeen er forferdelig... La oss passere raskt.',
'조심해. 벌레굴이다. 벽이랑 바닥에서 기어나와.':'Forsiktig. Ormehull. De kryper fra vegger og gulv.',
'으으... 벌레 싫어! 밟아버려!':'Ugh... Jeg hater insekter! Tramp på dem!',
'...공기가 얼어붙는다. 여기선 화염이 먹힌다.':'...Luften fryser. Ild fungerer her.',
'추워... 빙결 조심해! 얼면 끝이야.':'Kaldt... Se opp for frysing! Frys og det er slutt.',
'용암이다. 바닥을 밟으면 타 죽어.':'Lava. Tramp på gulvet og du brenner ihjel.',
'뜨거워! 여기 왜 이렇게 빨래!':'Så varmt! Hvorfor er alt så rødt her!',
'...군단이다. 수가 많아. 광역기 없으면 밀려.':'...Legionen. For mange. Uten Område blir du overveldет.',
'우글우글... 징그러워. 한꺼번에 쓸어!':'Overalt mylder... Ekle. Fei dem alle bort på én gang!',
'사도의 영역이야. 여기 놈들은 머리가 좋아.':'Apostelens territorium. Disse er kloke.',
'패턴이 복잡해졌어... 집중해!':'Mønstre ble komplekse... Fokuser!',
'...끝이다. 지옥의 심장부. 살아 돌아가는 건 포기해라.':'...Dette er det. Helvetets hjerte. Gi opp håpet om tilbakekomst.',
'여기가 마지막이야... 각오해.':'Dette er slutten... Forbered deg.',
// --- Remaining ---
'단계 ×':' x',
'⚡ 기동전폭! x':'⚡ Kjede Eksplosjon! x',
'🔥🔥 3중폭!':'🔥🔥 Flamme x3!','🔥🔥🔥 6중폭!':'🔥🔥🔥 Flamme x6!','🔥🔥🔥🔥 9중폭!':'🔥🔥🔥🔥 Flamme x9!','💥 불꽃폭발! ':'💥 Flammedetonering! ',
'🔥 기동불꽃 준비!':'🔥 Kjedelue Klar!',
'🔨 기동파괴 준비!':'🔨 Kjededestruction Klar!',
'⚡ 기동전폭 준비!':'⚡ Kjede Eksplosjon Klar!',
'⚡ 기동파괴! ':'⚡ Kjededestruction! T',
'🔥 기동불꽃!':'🔥 Kjedelue!',
'🔥 기동불꽃! ':'🔥 Kjedelue! T',
'❄빙결!':'❄Fryst!','🟢독!':'🟢Gift!','⚡감전!':'⚡Sjokket!','🔥화상!':'🔥Brennende!',
'✦ 여신의 가호 — SP+5 AP+3':'✦ Gudinnens Velsignelse — SP+5 AP+3',
'⚔ 기동칼날개!':'⚔ Vingeklinge!',
'🔥 화염관통!':'🔥 Ildgjennomboret!',
'🔱 관통!':'🔱 Gjennomboret!',
'⚔ 칼날!':'⚔ Klinge!',
'💥 착지!':'💥 Landing!',
'💫 기절!':'💫 Bedøvet!',
'⚡ 체간삭감!':'⚡ Holdningsbrudd!',
'클릭으로 선택 · ESC로 닫기':'Klikk for å velge · ESC for å lukke',
'선택됨':'Valgt',
'악의 부족! (30)':'Ikke nok Ondskap! (30)',
'MP 부족! (40)':'Ikke nok MP! (40)','MP 부족! (100)':'Ikke nok MP! (100)','MP 부족! (10)':'Ikke nok MP! (10)',
'MP 부족! (':'Ikke nok MP! (',
'✟ 시전...':'✟ Støpning...','🌋 시전...':'🌋 Støpning...','⛧ 시전...':'⛧ Støpning...',
'❄ 진입!':'❄ Inngang!',
'🔱 작살!':'🔱 Harpun!',
'레벨 부족! (요구: Lv.':'Nivå for lavt! (Krav: Lv.',
' 장착!':' Utrustet!',
' 해제':' Avmontert',
'👿 악의 추출: +':'👿 Ondskap Ekstraksjon: +',
'F 슬롯 해제':'F Spor avmontert',
'💫 집중...':'💫 Fokus...',
'⚡ 마력연사!':'⚡ Magisk Beskytning!',
'🪞 반격!':'🪞 Motangrep!','💢 반격!':'💢 Motangrep!',
'흡수!':'Absorbere!','반격 발사!':'Motangrep Skyting!',
'저주! 드랍률 -50%':'Forbannelse! Droppsjanse -50%','도망!':'Flykt!',
'위상!':'Fase!','방어!':'Forsvar!',
'회수 HP+':'Tilbakekall HP+','이동식 복귀':'Bærbar Tilbakekomst',
'약점!':'Svakhet!','저항!':'Motstand!',
'콤보 종료: ':'Kombo Slutt: ',
'악의 +':'Ondskap +',
'저주 ':'Forbannelse ','불발...':'Forsøk mislyktes...',
'작살 약점!':'Harpun Svakhet!',
'전염 x':'Pest x','흡수 완료!':'Absorpsjon Fullført!',
'부활 성공!':'Oppstandelse Lyktes!','부활 실패...':'Oppstandelse Mislyktes...',
'차원 이동!':'Dimensjonalt Skifte!',
'기절 해제':'Bedøvning Opphevet',
'악의 부족':'Ikke nok Ondskap',
'스킬 미습득':'Ingen ferdigheter lært','펼치기':'Utvid','접기':'Kollaps',
'조건 미달!':' ikke oppfylt!','해제!':' Defusjonert!',
'자동 ON':' Auto PÅ','자동 OFF':' Auto AV','스킬 해제':' ferdighet avmontert',
'닫기':'Lukk','장착 중':'Utrustet','보관 아이템':'Lagret Gjenstand',
'🔨 제작':'🔨 Fremstill',
'분해할 아이템이 없습니다.':'Ingen gjenstander å demontere.',
'스킬 미습득':'Ingen ferdigheter lært',
'석궁 자동발사 (T)':'Armbrøst automatisk (T)',
'버스트루프 당기기 (H)':'Burst-løkke trekke (H)',
'결정 자동합성':'Krystall auto-syntese',
'결정 자동강화':'Krystall auto-forbedring',
'✓ 설정 자동 저장':'✓ Innstillinger auto-lagret',
'세팅 프리셋 저장/불러오기':'Lagre/last forhåndsinnstilling',
'세팅1 저장':'Lagre forhåndsinnstilling 1','세팅1':'Forhåndsinnstilling 1',
'세팅2 저장':'Lagre forhåndsinnstilling 2','세팅2':'Forhåndsinnstilling 2',
'재진단':'Re-diagnostisere',
'게임 리셋 (처음부터)':'Tilbakestill spill (fra starten)',
'캐릭터 선택 (로비)':'Karaktervalg (Lobby)',
'닫기 [ESC]':'Lukk [ESC]','닫기 [G]':'Lukk [G]','닫기 [V]':'Lukk [V]','닫기 [C]':'Lukk [C]',
'전체화면 (F11)':'Fullskjerm (F11)',
'정말 모든 진행을 초기화하시겠습니까?':'Er du sikker på å tilbakestille all fremgang?',
'검출 중...':'Oppdager...',
'마우스 커서':'Musepeker','그래픽 품질':'Grafikkvalitet','하드웨어 진단':'Maskinvare diagnostikk',
'BGM 선택':'BGM-valg',
'자동 (스테이지별)':'Automatisk (per fase)','전체 랜덤':'Alt tilfeldig','로비':'Lobby',
'1장 랜덤':'Kapittel 1 tilfeldig','2장 랜덤':'Kapittel 2 tilfeldig','3장 랜덤':'Kapittel 3 tilfeldig',
'4장 랜덤':'Kapittel 4 tilfeldig','5장 랜덤':'Kapittel 5 tilfeldig','6장 랜덤':'Kapittel 6 tilfeldig','7장 랜덤':'Kapittel 7 tilfeldig',
'보스':'Sjef','최종보스':'Sluttsjef',
'대장간 랜덤':'Smed tilfeldig','사망 랜덤':'Død tilfeldig','승리 랜덤':'Seier tilfeldig',
'지옥 추락 사망 징글':'Helvede-fall-dødsjingle','탈출 성공':'Flukt vellykket',
'── 1장 - 썩은 숲 ──':'── CH1 - Rotten Forest ──','── 2장 - 벌레굴 ──':'── CH2 - Worm Nest ──',
'── 3장 - 얼음굴 ──':'── CH3 - Ice Cavern ──','── 4장 - 화염지대 ──':'── CH4 - Infernal Wastes ──',
'── 5장 - 지옥군단 ──':'── CH5 - Hell Legion ──','── 6장 - 사도마굴 ──':'── CH6 - Apostle Den ──',
'── 7장 - 지옥성 ──':'── CH7 - Hell Citadel ──','── 공통 ──':'── Common ──',
'⌨ 조작법':'⌨ Kontroller','클릭하면 닫힘':'Klikk for å lukke',
'전투력':'KV','가방':'Bag','결정':'Krystall',
'↕ 정렬':'↕ Sorter','쓰레기 전체선택':'Velg alt søppel','쓰레기 전부 분해':'Demonter alt søppel',
'창고':'Lager','스탯 포인트':'Attributtpoeng','능력치 요약':'Statsoversikt','올 리셋':'Tilbakestill alt',
'대장간':'Smed','스킬':'Ferdigheter','능력치':'Attributter',
'좌클스킬 (클릭 전환)':'VK-ferdighet (klikk for å bytte)','우클스킬 (클릭 전환)':'HK-ferdighet (klikk for å bytte)',
'이동스킬 (클릭 전환)':'Bevegelseferdighet (klikk for å bytte)','마법스킬 (클릭 전환)':'Magiferdighet (klikk for å bytte)',
'영역스킬 (클릭 전환)':'Områdeferdighet (klikk for å bytte)','피보호막 (클릭 전환)':'Blodskjold (klikk for å bytte)',
'CT스킬 (클릭 전환)':'CT-ferdighet (klikk for å bytte)','[C] 능력치':'[C] Attributter',
'무기 공격':'Våpenangrep','칼등 처내기 (투사체 반사, 홀드 연사)':'Parere (reflekterer projektiler, hold=salve)',
'연속 처내기':'Kontinuerlig parere','영역 스킬 (폭풍소환 등)':'Områdeferdighet (Hvirvelvind etc)',
'작살 발사':'Skyte harpun','마법 (탭=투사체, 홀드=빔)':'Magi (trykk=prosjektil, hold=stråle)',
'데빌포스 흡수':'Absorbere djevelkraft','물약 / 스킬슬롯':'Drikker / Ferdighetsslots',
'스킬슬롯 5 / 필살기 / CT스킬':'Slot 5 / Ultimat / CT-ferdighet','스킬 슬롯 배정':'Slottildeling',
'공성쇠뇌':'Beleirigsarmbue',
'만화광선':'Lysstråle',
'공성쇠뇌 철거 → 이동식':'Beleirigsarmbue demontert → bærbar',
'🏹 공성쇠뇌 설치!':'🏹 Beleirigsarmbue Plassert!',
'뜨거워! 여기 왜 이렇게 빨개!':'Så varmt! Hvorfor er alt så rødt her!',
'유령쇠뇌야. 인사해.':'Det er den spøkelsesarmbrøsten. Si hei.',
// --- Phase 27 additions ---
'위로 이동':'Beveg opp','아래로 이동':'Beveg ned','왼쪽 이동':'Beveg venstre','오른쪽 이동':'Beveg høyre',
'칼등 처내기 (탭=처내기, 홀드=연사)':'Klingeparering (trykk=parering, hold=salve)',
'영역 스킬':'Områdeferdighet','작살 이동':'Harpun Dash',
'유령불꽃 켜기/끄기':'Spøkelsesflamme Av/På','기동칼날개 자동 켜기/끄기':'Klingevinge Auto Av/På',
'해상도':'Oppløsning',
'빛이 꺼졌다':'Lyset Slokner','누군가는 너를 기다리고 있다':'Noen venter på deg',
'다시 일어서라':'Reis deg igjen','로비로 돌아가기':'Gå tilbake til Lobbyen',
'☠ 사망 리플레이':'☠ Dødsreprise',
'지옥의 시련을 견뎌냈다':'Du har utholdt Helvedes prøvelse',
'계속 전투':'Fortsett kamp','난이도를 선택하라':'Velg vanskelighetsgrad',
'나중에 설정(ESC)에서 변경 가능':'Kan endres i Innstillinger (ESC) senere',
'일괄합성':'Massesyntes','일괄강화+합성':'Masseforbedring+Syntes',
'자원 부족!':'Ressurser Lav!',' 뎀':' Skd',
'합체 폭발!':'Fusjonsdetonasjon!',
'MP 부족! (50)':'Ikke nok MP! (50)',
'부활력 고갈!':'Oppstandelse Oppbrukt!','☠ 부활력 고갈!':'☠ Oppstandelse Oppbrukt!',
'독안개':'Gifttåke','뇌전창':'Tordenspyd',
'🔥 업화선 시전...':'🔥 Helvedestråle støping...',
'💥 기동파괴 그로기!':'💥 Kjedeknusing Groggy!',
'💥 칼등 그로기!':'💥 Klingeparering Groggy!',
'⚡ 순간이동 준비!':'⚡ Teleportering Klar!',
'👿악의+1000':'👿Ondskap+1000',
'💀 내려찍기!':'💀 Nedsmell!',
'✟ 신성력 억제! +':'✟ Hellig Kraft Undertrykt! +',
'✟ 신성력 억제!':'✟ Hellig Kraft Undertrykt!',
'✟ 신성력 억제! (':'✟ Hellig Kraft Undertrykt! (',
'💥 지진그로기!':'💥 Jordskjelv-Groggy!',
'💥 기폭그로기!':'💥 Detonasjons-Groggy!',
'폭발! ×':'Eksplosjon! ×','⚫ 기둥강타!':'⚫ Søyleslag!',
'💥 대왕치기 그로기!':'💥 Kolossalt Groggy!',
'💫 미니스턴!':'💫 Mini Stun!','⚡ 뇌전창!':'⚡ Tordenspyd!',
'…절반이다. 정신차려.':'…Halvt liv. Ta deg sammen.',
'…죽기 직전이다. 한 발만 더.':'…Nesten død. Ett slag til.',
'…다음 한 방이 마지막이야.':'…Neste slag er det siste.',
'기절! ':'Bedøvet! ',
'마력이 빈다. 평타 섞어.':'MP renner ut. Bland inn normalangrep.',
'그랩이다. 거리를 둬.':'Gripeangep. Hold avstand.',
'광역기다. 멀어져.':'Områdeangrep. Kom deg unna.',
'…아파? 당연하지. 여긴 지옥이야.':'…Vondt? Selvfølgelig. Her er helvete.',
'F키도 스킬 슬롯이야!':'F er også et ferdighetsspor!',
'L-CTRL로 유령걸음/얼음보주!':'L-CTRL for Spøkelsesgange / Iskule!',
'V 눌러서 창고에 넣어둬!':'Trykk V for å lagre!',
'ESC로 설정! 난이도/자동물약!':'ESC for innstillinger! Vanskelighet/Auto-drikke!',
'잡몹이다. 먼저 정리해.':'Vanlige fiender. Rydd dem først.',
'…얼어붙은 놈은 오래 안 간다.':'…En frossen fiende varer ikke lenge.',
'…냄새가 짙다. 큰 놈이 있어.':'…Lukten er tykk. Noe stort er nær.',
'쉴드는 마법으로, HP는 물리로.':'Skjold tar magi, HP tar fysisk.',
'스페이스! 가시덫으로 적 묶어!':'Mellomrom! Fang fiender med Tornefelle!',
'근접 너무 많아! 거리 벌려!':'For mange på nært hold! Spre deg!',
'회전참이나 광역기로 몰아!':'Bruk Virvelhugg eller Område!',
'F 눌러! 회복의 영역 깔아!':'Trykk F! Legg ut Hellig Domene!',
'F키 회복의 영역을 써봐.':'Prøv F-tast Hellig Domene.',
'빠져! 물약 마시고 회복해.':'Trekk deg tilbake! Drikk drikke og restituér.',
'쉬프트! 사슬기동은 이동기야!':'Shift! Kjededash er et bevegelsesverktøy!',
'스킬포인트 쌓였어! K 눌러!':'Ferdighetspoeng klar! Trykk K!',
'스킬 포인트 있어! K!':'Ferdighetspoeng! K!',
'C키. 패시브 포인트가 쌓여있다.':'C-tast. Passive poeng har bygget seg opp.',
'…쓸 거 아니면 분해해.':'…Demonter det du ikke vil bruke.',
'…강화 안 하면 그냥 고철이야.':'…Uten forbedring er det bare skrap.',
'빨간 탄은 우클릭. 무지개는 Q.':'Røde kuler: høyreklikk. Regnbue: Q.',
'빨강=우클릭, 무지개=Q.':'Rød=høyreklikk, regnbue=Q.',
'…멈추지 마. 여신은 기다리지 않는다.':'…Stopp ikke. Gudinnen venter ikke.',
'패턴이 바뀐다. 거리를 둬.':'Mønsteret endrer seg. Hold avstand.',
'미쳐가고 있어. 광폭화다.':'Det blir galt. Raseri-modus.',
'마지막이야! 끝장내!':'Siste fase! Gjør det ferdig!',
'…끝났다. 다음으로.':'…Ferdig. Videre.',
'다 잡았다! 포탈 어딨어?':'Alle fanget! Hvor er portalen?',
'근육으로 만든 빌드군. 베고 부숴.':'Muskel-build. Hogg og knus.',
'활을 쥐었군. 거리를 둬.':'Bue i hånd. Hold avstand.',
'마법사군. MP 관리부터 배워라.':'Magiker. Lær MP-styring først.',
'운에 기댄 빌드군. …드롭은 좋겠어.':'Lykkebasert build. …I det minste blir drops gode.',
'…VIT가 너무 낮아. 한 방에 죽는다.':'…VIT er for lavt. Du dør av ett slag.',
'다 찍으면 다 약해진다. 하나만 골라.':'Maks alt og du er svak overalt. Velg ett.',
'…3단. 적이 강해져. 정신 차려.':'…Trinn 3. Fiender sterkere. Fokuser.',
'5단이다. …너도 강해졌단 뜻이야.':'Trinn 5. …Det betyr at du også har blitt sterkere.',
'…7단. 아직 살아있단 게 신기하군.':'…Trinn 7. Fortsatt i live. Overraskende.',
'10단. …너는 이제 인간이 아니야.':'Trinn 10. …Du er ikke lenger menneskelig.',
'…일반으로 내려왔군. 가끔은 쉬어가야지.':'…Tilbake til Normal. Av og til trenger man en pause.',
'…이게 진짜 패링이야.':'…Det er en ekte parering.',
'…피가 묻기 시작했군.':'…Blodet begynner å renne.',
'100. 너는 인간이 아니야.':'100. Du er ikke menneskelig.',
'…피 흘리며 베는군.':'…Hogger gjennom blod.',
'빨간콩이 푸르게 변했다. 그게 너의 무기야.':'Den røde kulen ble blå. Det er ditt våpen.',
'무지개를 받아쳤군. 그건 진짜 어렵다.':'Parrerte en regnbue. Det er virkelig vanskelig.',
'…너무 빨라. 닿기 직전에 눌러.':'…For raskt. Trykk rett før kontakt.',
'악의가 가득 찼다. 풀어내.':'Ondskapene er full. Slipp den løs.',
'작살이 살을 뚫었어. 끌고 와.':'Harpunen trengte gjennom kjøttet. Dra den inn.',
'…풀차지군. 멀리 던져버려.':'…Fulladet. Kast den langt.',
'…빈틈을 그대로 빠져나갔다.':'…Glei rett gjennom åpningen.',
'…일반 잡몹이 아니야. 모디파이어 붙었군.':'…Ikke en vanlig fiende. Den har en modifikator.',
'엘리트 하나 처리.':'Elite ned.',
'…큰 놈이다. 일반 잡몹 정리부터.':'…Stor en. Rydd de vanlige fiendene først.',
'미니보스 처리. 다음 길로.':'Mini-boss ned. Videre til neste vei.',
'한 번에 다섯. 깔끔해.':'Fem på én gang. Ryddig.',
'100강. 이제 뭔가 다르게 보이는군.':'+100. Ting ser annerledes ut nå.',
'…운이 없는 날이야.':'…Uheldig dag.',
'…전설이다. 이런 건 처음 본다.':'…Legendarisk. Aldri sett en slik.',
'…죽었다 살아났네. 여신은 너를 포기 안 했어.':'…Døde og kom tilbake. Gudinnen ga ikke opp deg.',
'…또야? 패턴 좀 외워!':'…Igjen? Lær mønsteret!',
'…한 번도 안 죽고. 그건 진짜 실력이야.':'…Ikke død én gang. Det er ekte ferdighet.',
'…ACT1을 끝냈다. 진짜 시작은 여기서부터야.':'…ACT1 ferdig. Den ekte starten er herfra.',
'모든 보스를 무너뜨렸다. 너는 지옥의 일부야.':'Alle bosser falt. Du er en del av helvete.',
'…30초. 너 진짜 미쳤구나.':'…30 sekunder. Du er virkelig gal.',
'…빠르군. 효율적이야.':'…Rask. Effektiv.',
'신기록이다.':'Ny rekord.',
'탭 장비창을 열어봐.':'Åpne utstyrsvinduet med TAB.',
'데미지 부족하면 무기 강화!':'Ikke nok skade? Forbedre våpenet ditt!',
// --- Loading screen ---
'불러오는 중...':'Laster...',
'로딩중...':'Laster...',
'맵과 몬스터 불러오는 중...':'Laster kart og monstre...',
'기본 데이터 준비 중...':'Forbereder grunndata...',
'저장 데이터 불러오는 중...':'Laster lagrede data...',
'몬스터 스킨 로딩...':'Laster monsterskins...',
'맵과 몬스터 생성 중...':'Genererer kart og monstre...',
'맵 에셋 로딩...':'Laster kartressurser...',
'맵 환경 준비 중...':'Forbereder kartmiljøet...',
'주변 청크 준비 중...':'Forbereder nærliggende chunks...',
'맵 캐시 생성 중...':'Bygger kartsøk...',
'미니맵 빌드 중...':'Bygger minimap...',
// Phase 28
' 으로 탈출!':' — flykt!',
'100명?! 미쳤어!':'100 kills?! Galskapelig!',
'10단 최고난이도! 너 진짜 광기야!':'Vanskelighetsgrad 10 maks! Fullstendig gal!',
'1분 안에 클리어! 빠르네!':'Bane klart på 1 min! Så raskt!',
'30초!! 스피드런 가능해!':'30 sekunder!! Speedrun-potensial!',
'3단! 보상도 좋아지지만 죽기 쉬워!':'Vanskelighetsgrad 3! Bedre belønninger men lettere å dø!',
'50명! 학살자야!':'50 kills! Slakter!',
'5단!! 진짜 게이머 인증!':'Vanskelighetsgrad 5!! Ekte spiller sertifisert!',
'7단!! 다른 사람들 이 정도 못 와!':'Vanskelighetsgrad 7!! Andre kommer ikke så langt!',
'ACT1 완주! 우리가 진짜 해냈어!':'AKT 1 fullført! Vi klarte det virkelig!',
'Ctrl 얼음보주로 탈출하라.':'Ctrl — flykt med Isskule.',
'Ctrl 유령걸음으로 탈출하라.':'Ctrl — flykt med Spøkelsesvandring.',
'C키! 패시브 강해져!':'Tast C! Passive blir sterkere!',
'DEX 빌드! 거리에서 패고, 추적탄 좋아!':'DEX-build! Avstandsangrep, sporende prosjektiler!',
'E로 마력공격을 해봐!':'Prøv magisk angrep med E!',
'G 눌러서 대장간 가봐!':'Trykk G — smedjen!',
'G키 대장간. 강화 안 하면 계속 죽어.':'G — smedjen. Ingen oppgraderinger, fortsett å dø.',
'HP 70%! 조심해!':'HP 70%! Vær forsiktig!',
'INT 빌드! 빔이랑 폭발 마법! MP 잘 봐!':'INT-build! Stråler og eksplosiv magi! Hold øye med MP!',
'LCK 높아! 레어 드롭률 미친 거 알지?':'Høyt LCK! Drop-sjansene er gale!',
'L로 어디에 뭘 넣을지 골라!':'Trykk L — velg ferdighetsslot-layout!',
'MP 부족! 평타로 패면서 회복해!':'MP lavt! Slå for å hente deg!',
'ST 없으면 스킬 못 써!':'Ingen ST, ingen ferdigheter!',
'STR 빌드! 회전참, 회오리, 광역기 추천!':'STR-build! Rotasjonshugst, hvirvelstorm, AoE!',
'VIT 좀 찍어! HP 너무 적어!':'Legg til VIT! HP for lavt!',
'Z 누르면 대박! 쿨타임 길어!':'Trykk Z for ultimat! Lang avkjøling!',
'…고기 냄새. 싫진 않네.':'…Blodlukt. Ikke dårlig.',
'…둘러싸이면 끝이야.':'…Omringet betyr død.',
'…말은 못해.':'…Kan ikke snakke.',
'…버리기 아까운 건 창고에.':'…Verdifulle ting i lageret.',
'…빈틈을 노려.':'…Vent på åpninger.',
'…설정을 확인해.':'…Sjekk innstillinger.',
'…슬롯을 채워. 빈 손은 죽음이다.':'…Fyll slots. Tomme hender er død.',
'…아직 살아있네. 좌클릭으로 저것들 쳐봐.':'…Fortsatt i live. Venstreklikk for å slå dem.',
'…운이 좋았을 뿐이야. 아마.':'…Bare flaks. Sannsynligvis.',
'…치는 건 할 줄 아네. 피하는 건?':'…Kan slå. Kan unngå?',
'…힘을 골라라. 전부 가질 순 없다.':'…Velg din styrke. Kan ikke ha alt.',
'골고루 안 돼! 하나로 밀어!':'Ikke spre! Sats på ett!',
'그로기 터지면 1.5배!':'Groggy = 1,5x skade!',
'길이 열렸다.':'Veien er åpen.',
'나머진 전부 우클릭 패링 가능!':'Resten — høyreklikk parer!',
'나머진 전부 우클릭!':'Resten — høyreklikk!',
'다섯 번 연속! 내가 본 인간 중 최고!':'Fem på rad! Det beste jeg har sett!',
'다음엔 죽지 마!':'Ikke dø neste gang!',
'더블탭 전격이동으로 탈출하라.':'Dobbelttrykk dash for å flykte.',
'소환수 왔어! 먼저 처리해야 해!':'Besvergeøser! Rydd dem først!',
'스킬 없으면 방향키 연타뿐이야.':'Ingen ferdigheter? Bare spam piltaster.',
'신기록!! 스트리머한테 보내!':'Ny rekord!! Send til streamer!',
'아이템 넘쳐! 우리가 주워줄게!':'Vesken full! Vi plukker opp for deg!',
'안 죽고 깼어! 진짜 천재 맞네!':'Klart uten dødsfall! Ekte geni!',
'앞으로 가자~':'Fremover~',
'우리가 해냈어! 다음 챕터 가자!':'Vi klarte det! Neste kapittel!',
'일반 모드! 편하게 즐기자!':'Normal modus! Ta det med ro!',
'자원이 반이다. F키로 회복해.':'Ressurser halvt. Trykk F for å hente deg.',
'잡힌다! 옆으로 빠져!':'Fanges! Unngå til siden!',
'장비 분해해! 쓰레기도 악의!':'Demonter utstyr! Søppel gir også ondskap!',
'전부 다 잡았어! 우리가 지옥의 왕이야!':'Alt ryddet! Helvetes konger!',
'좋은 거 나왔다! TAB!':'Godt loot! TAB!',
'죽기 직전에 죽이다니! 멋져!':'Drepte rett før døden! Imponerende!',
'체력 반 남았어! 물약 마실 타이밍!':'Halvt HP! Tid for trylledrikk!',
'큰 거 온다! 도망쳐!':'Stort angrep! Løp!',
'패링으로 돌려주고, Q 보호막도 써!':'Parer og reflekter, bruk Q-skjold!',
'패턴이 빨라졌어!':'Mønstre raskere!',
'한 대만 맞아도 죽어! 패링이든 회피든!!':'Ett treff = død! Parer eller unngå!!',
'한 방이면 죽어! 도망쳐!!':'Ett skudd dreper! Løp!!',
'화염엔 빙결! 암전엔 암흑!':'Ild → frost! Tomrom → skygge!',
'── 2장 - 벌레굴 ──':'── CH2 - Worm Nest ──',
'── 4장 - 화염지대 ──':'── CH4 - Infernal Wastes ──',
'── 6장 - 사도마굴 ──':'── CH6 - Apostle Den ──',
'── 공통 ──':'── Common ──',
'난이도를 선택하라':'Velg vanskelighetsgrad',
'☠ 부활력 고갈!':'☠ Gjenopplivning Oppbrukt!',
'⏳⚡ 시간걸음!':'⏳⚡ Tidssteg!',
'블룸 효과':'Bloom-effekt',
'잔상 트레일':'Etterbildespor',
'슬래시 이펙트':'Slash-effekt',
'후처리 효과':'Etterbehandling',
'사망 이펙트':'Dødseffekt',
'동적 조명':'Dynamisk belysning',
'횃불 조명 (어둠)':'Fakkelbelysning (mørke)',
'앰비언트 파티클':'Omgivelsespartikler',
'안개 효과':'Tåkeeffekt',
'필름 그레인':'Filmkorn',
'캐릭터 외곽선':'Karakterkontur',
'리롤':'Kast om',
'물약':'Eliksir',
'으로 탈출!':'for å flykte!',
'Shift 작살':'Shift Harpun',
'더블탭 전격이동':'Dobbeltrykk — Lynglimt',
'Ctrl 유령걸음':'Ctrl Spøkelsegang',
'Ctrl 얼음보주':'Ctrl Iskule',
'🔴화염→빙결 2배 | 🔵빙결→화염 2배 | ⚪물리=중립 | 악마 처치 시 악의 영혼 드롭':'🔴Ild→Is 2× | 🔵Is→Ild 2× | ⚪Fys=Nøytral | Drep demoner for ondskapssjeler',
  '미구현':'N/A',
  '스탯 총량':'Total statistik',
  '장비':'utstyr',
  '공속':'atkhast',
  '크리':'krit',
  '크리뎀':'kritskade',
  '근성':'Utholdenhet',
  '종합 지표':'Oversikt',
  '근접 DPS':'Nærkamp DPS',
  '공격력×공속×크리':'ATK×Hast×Krit',
  '활 DPS':'Bue DPS',
  '마법 DPS':'Magi DPS',
  '유효 HP (EHP)':'Eff. HP (EHP)',
  '쉴드':'Skjold',
  '장비 파워':'Utstyrsstyrke',
  '근접 공격력':'Nærkamp ATK',
  '기본':'base',
  '무기':'våpen',
  '패시브':'passiv',
  '활 공격력':'Bue ATK',
  '정밀':'Prec',
  '마법 공격력':'Magi ATK',
  '왕관':'krone',
  '마력':'Arkan',
  '공격속도':'Angrepshastighet',
  '크리티컬':'Kritisk',
  '데미지':'skade',
  '확률':'Rate',
  '어픽스':'affix',
  '레거시':'arv',
  '추가뎀':'ekstra skade',
  '패링 카운터뎀':'Parry motskade',
  '우클공속':'Høyreklikkhastighet',
  '무지개탄DR':'Regnbue DR',
  '포이즈파괴':'Bryte Poise',
  '방어관통':'Rustningsgjennomtr.',
  '관통력':'Gjennomtrengning',
  '속성':'Elementer',
  '무기속성':'Våpenelement',
  '독':'Gift',
  '초':'s',
  '암흑저주':'Mørk forbannelse',
  '원소집중':'Element fokus',
  '원소전환':'Elementkonvert.',
  '방어':'Forsvar',
  '물리방어':'Fysisk forsvar',
  '감소':'red',
  '캡':'tak',
  '장갑':'hansker',
  '바지':'bukser',
  '속성방어':'Element forsvar',
  '목걸이':'halskjede',
  '반지1':'ring1',
  '반지2':'ring2',
  '반사':'Refleksjon',
  '가시':'Torner',
  '배리어':'Barriere',
  '보호막 흡수':'Skjoldabsorpsjon',
  '속성 저항':'Element motstand',
  'CC저항':'CC motstand',
  '생존':'Overlevelse',
  '장비HP':'Utstyr-HP',
  '임플':'Impl.',
  '에너지쉴드':'Energiskjold',
  '리젠':'Regen',
  '스태미나':'Stamina',
  '성장':'Vekst',
  'MP%어픽스':'MP% affix',
  '이동속도':'Bevegelseshastighet',
  '한방캡':'Ettskyts-tak',
  '최대HP의33%':'33% Maks HP',
  '비용/효율':'Kostnad/Eff',
  '근접ST':'Nærkamp ST',
  '활ST':'Bue ST',
  '마법MP':'Magi MP',
  '작살사거리':'Harpun rekkevidde',
  '기동게이지':'Drive-måler',
  '쿨감':'CDR',
  '쇠뇌뎀':'Armbrostskade',
  '쇠뇌공속':'Armbrosthastighet',
  '기타':'Diverse',
  '물약쿨':'Drikke-CD',
  '회복+':'Restitusjon+',
  '드롭':'Drop',
  '경험치+':'EXP+',
  '골드+':'Gull+',
  '기동:칼날개':'Drive:Klinge',
  '기동:전폭':'Drive:Slag',
  '기동:기습':'Drive:Bakhold',
  '충전스킬':'Ladeskill',
  '사슬게이지':'Kjede-måler',
  '특수 효과':'Spesialeffekter',
  '처치뎀+':'Kill-skade+',
  '위기뎀+':'Krise-skade+',
  '피격반격':'Treff-konter',
  '풍요(적HP≥70%뎀+)':'Overflod(HP≥70%+)',
  '약자포식(적HP≤30%뎀+)':'Rovdyr(HP≤30%+)',
  '패링폭발':'Paréringseksplosjon',
  '체간파괴+':'Bryte Poise+',
  '콤보뎀+':'Kombo-skade+',
  '작살뎀+':'Harpun-skade+',
  '스킬뎀+':'Skill-skade+',
  '패리+':'Parering+',
  '체인':'Kjede',
  '정화':'Rensing',
  '회':'×',
  '불굴':'Utholdenhet',
  '신성력':'Hellig kraft',
  '악마력(부활력)':'Demonskraft',
  '자연':'Natur',
  '악마성':'Demonicitet',
  '인간성':'Menneskelighet',
  '전투 통계':'Kamstatistikk',
  '핵터':'Hecter',
'디로이':'Deroy',
'물리 ATK +1, MAX HP +5, HP리젠 +0.002':'Phys ATK +1, MAX HP +5, HP regen +0.002',
'석궁 ATK +1, 공격속도 +0.05%, MAX ST +2, ST리젠 +0.005, 회피 +0.05%':'Bow ATK +1, ATK speed +0.05%, MAX ST +2, ST regen +0.005, Dodge +0.05%',
'마법 ATK +1, MAX MP +2, MP리젠 +0.005, MAX 쉴드 +5':'Magic ATK +1, MAX MP +2, MP regen +0.005, MAX Shield +5',
'크리확률 +0.025%, 크리뎀 +0.2%, 드롭률 +0.15%':'Crit rate +0.025%, Crit DMG +0.2%, Drop rate +0.15%',
'근접뎀 +15%, ST비용 -4%/lv (최대-40%)':'Melee DMG +15%, ST cost -4%/lv (max -40%)',
'작살 사거리 +2%/lv, 기동게이지 회복 +3%/lv':'Harpoon range +2%/lv, Mobility gauge recovery +3%/lv',
'카운터뎀 +50%/lv, 우클릭 공속 +10%/lv, 무지개탄 피해감소 +10%/lv (최대50%)':'Counter DMG +50%/lv, RMB ATK speed +10%/lv, Rainbow shot DMG reduction +10%/lv (max 50%)',
'마법뎀 +15%, MP비용 -4%, 시전속도 +8%/lv':'Magic DMG +15%, MP cost -4%, Cast speed +8%/lv',
'투사체뎀 +15%, 공속 +10%, 사거리 +8%, ST비용 -4%/lv':'Projectile DMG +15%, ATK speed +10%, Range +8%, ST cost -4%/lv',
'보호막 흡수 +2%/lv (기본70→최대90%), 보호막 중 HP리젠 +0.1%/lv':'Shield absorb +2%/lv (base 70 to max 90%), HP regen during shield +0.1%/lv',
'HP/ST리젠 +3%/lv, 물약쿨 -3%/lv':'HP/ST regen +3%/lv, Potion cooldown -3%/lv',
'크리률 +2%, 크리뎀 +8%/lv':'Crit rate +2%, Crit DMG +8%/lv',
'아이템 드롭률 +8%/lv':'Item drop rate +8%/lv',
'투사체 관통률 +5%/lv, 관통횟수 +1/lv, 관통뎀감소 완화':'Projectile pierce rate +5%/lv, Pierce count +1/lv, Pierce DMG falloff reduced',
'MP리젠 +3%/lv, 쉴드리젠 +3%/lv, 쉴드쿨 -3%/lv':'MP regen +3%/lv, Shield regen +3%/lv, Shield cooldown -3%/lv',
'자동쇠뇌 뎀 +5%/lv, 공속 +5%/lv':'Auto crossbow DMG +5%/lv, ATK speed +5%/lv',
'물리뎀 +15%/lv, HP +3%/lv, ST소모 -5%/lv':'Phys DMG +15%/lv, HP +3%/lv, ST cost -5%/lv',
'적에게 약점노출 디버프. 직접 공격 시 스택+1, 스택당 피격뎀 +3%. 최대 Lv×5 중첩 (1렙5, 10렙50). 초당 20% 감소, 5초 미피격 시 리셋. DOT/장판 제외':'Weakness debuff on enemies. +1 stack per direct hit, +3% DMG/stack. Max Lv×5 (Lv1=5, Lv10=50). -20%/s decay, reset after 5s. DOT excluded',
'물리→쉴드 패널티 관통 +5%/lv (기본10%, 10lv=60%)':'Phys to Shield penalty pierce +5%/lv (base 10%, lv10=60%)',
'마법→HP 패널티 관통 +5%/lv (기본10%, 10lv=60%)':'Magic to HP penalty pierce +5%/lv (base 10%, lv10=60%)',
'적 HP 70%↑: 뎀+20%/lv, 회복력+5%/lv (합연산)':'Enemy HP≥70%: DMG+20%/lv, Recovery+5%/lv (additive)',
'적HP 30%↓: 뎀+20%/lv. 내HP 30%↓: 회복력+10%/lv, 이속+5%/lv (합연산)':'Enemy HP≤30%: DMG+20%/lv. My HP≤30%: Recovery+10%/lv, Move SPD+5%/lv (additive)',
'DOT 틱뎀 +15%/lv, DOT 지속시간 +10%/lv, DOT 축적률 +5%/lv':'DOT tick DMG +15%/lv, DOT duration +10%/lv, DOT pool rate +5%/lv',
'MP +50/lv, MP회복 +1%/lv':'MP +50/lv, MP regen +1%/lv',
'ST +50/lv, ST회복 +1%/lv':'ST +50/lv, ST regen +1%/lv',
'악의 드롭 +8%/lv':'Malice drop +8%/lv',
'HP +300/lv':'HP +300/lv',
'DEF +20/lv':'DEF +20/lv',
'엘리트/보스 추가뎀 +10%/lv':'Elite/Boss bonus DMG +10%/lv',
'부활력 -10/lv, 전체 데미지 +5%/lv, HP/MP/ST +100/lv':'Revive power -10/lv, All DMG +5%/lv, HP/MP/ST +100/lv',
'부활확률 +2%/lv, 부활HP +5%/lv, 부활쿨 -30초/lv':'Revive chance +2%/lv, Revive HP +5%/lv, Revive CD -30s/lv',
// --- Phase 37: skill desc ---
'핵심 광역기 — 먼저 배워서 정리력 확보':'Core AoE — learn first for mob clearing',
'악의 사냥 + 보호자 → 합체: 칼날 해방':'Malice Hunt + Guardian → Fuse: Blade Liberation',
'폭독혈 추가 → 합체: 독혈 해방 (칼날+독)':'Plague Burst → Fuse: Plague Liberation (blade+poison)',
'충돌+화염 → 합체: 사슬기동 (무적이동 핵심)':'Impact+Flame → Fuse: Chain Breach (invincible dash core)',
'사슬 체인 확장 → 기동:파쇄/기동:전폭':'Chain expansion → Slam/Thunder combos',
'필살기 1개 선택! 신성폭발(넉백) / 블랙(흡인) / 용암(화상) / 처형(보스킬)':'Pick 1 ultimate! Holy Blast(knockback) / Black Star(pull) / Lava(burn) / Execution(boss kill)',
'멸살광선+만화방창+원소추적탄+전격이동 → 합체: 추적빔':'Omni Beam+Barrage+Elem Missile+Blink → Fuse: Tracking Beam',
'회전참+기폭+대왕치기 → 합체: 지진폭풍':'Whirlwind+Detonate+Giant Slam → Fuse: Slam Storm',
'칼등치기 + 칼등날개 → 합체: 처내기 강화':'Blade Parry + Shield Wing → Fuse: Parry Enhanced',
'해골무덤 + 악의폭풍 → 합체: 해골번개':'Bone Wall + Malice Storm → Fuse: Bone Lightning',
'폭풍소환 + 얼음보주 → 합체: 얼음폭풍':'Malice Mortar + Ice Orb → Fuse: Ice Mortar',
'유령화 이동 + 전기 폭발':'Ghost phase movement + electric burst',
'회복 + 구속 → 합체: 결계의 영역':'Recovery + Prison → Fuse: Ward Domain',
'지진폭풍+추적암전 → 6단합체: 폭풍빔':'Slam Storm → 6-Fuse: Storm Beam',
'아이스스톰 추가 → 합체: 신성빙결':'Ice Storm → Fuse: Holy Ice',
'암흑기둥 + 가시덫 → 합체: 기둥가시. 대왕치기2는 기둥강타/지옥강타용':'Dark Pillar + Spike Trap → Fuse: Pillar Spike. Giant Slam 2 for Pillar Slam/Inferno Slam',
'기동칼날개 추가 → 5단합체: 기동:칼날개':'Chain Bladewing → 5-Fuse: Maneuver:Bladewing',
'STR 스케일. 3회 충전 + Lv3마다 사거리 1단계↑(최대4단). 이동 중 무적, 통과 적에 데미지+그로기 (쿨 5초)':'STR scale. 3 stocks + range tier up every Lv3 (max 4). Invincible while moving, DMG+groggy on pass-through (CD 5s)',
'INT 스케일. 이동 경로에 화염길 생성(3초 DOT). 통과 적 화상. MP 소모. 합체 시 착지 폭발':'INT scale. Fire trail on dash path (3s DOT). Burns passed enemies. MP cost. Fuse: landing explosion',
'5초간 유령화 — 무적+이동. 통과한 적/탄막 수만큼 종료 시 암전 폭발(+10%/회) + 전기줄기 방사(3회 체인). 카운트 캡=Lv×5(최대50). 쿨 20초. Lv당 뎀+15% 범위+10':'5s ghost form — invincible+move. Blackout explosion on end (+10%/enemy passed) + lightning arc (3 chains). Count cap=Lv×5 (max 50). CD 20s. Per Lv DMG+15% range+10',
'[이동기] 방향키 더블탭으로 발동. 경직/기절 중에도 탈출 가능. 500유닛 순간이동, 무적(15프레임). MP(10+Lv×5). 1렙10충전, 렙당+1. 쿨 8초→Lv당-0.5초(최소3초). 착지 시 전류장판(10초+Lv×0.5초): INT 틱뎀 + 방어력↓(1렙10%, 렙당+5%, 캡50%)':'[Mobility] Double-tap to activate. Escapes stagger/stun. 500-unit blink, invincible 15f. MP(10+Lv×5). Lv1=10 stocks, +1/Lv. CD 8s→-0.5s/Lv (min 3s). Landing shock field(10s+Lv×0.5s): INT tick DMG + DEF↓(Lv1=10%, +5%/Lv, cap 50%)',
'좌클 스킬: 기본공격에 3단 콤보 초승달 검기 추가. ST 10+Lv당2. Lv당 뎀+10% 거리+15px':'LMB skill: adds 3-hit crescent ki blade combo to basic attack. ST 10+2/Lv. Per Lv DMG+10% range+15px',
'[기본: E] 어둠 마법 오브 발사. 범위폭발. 넉백 0.5%. Lv당 크기+50% (뎀은 _skMul 계수 적용)':'[Default: E] Dark magic orb fired. AoE explosion. Knockback 0.5%. Per Lv size+50% (DMG uses _skMul)',
'무기 홀드 → 전진 회전 공격. 360도 광역, ST 지속소모. Lv당 범위+5 뎀+5%':'Hold weapon → forward spin attack. 360° AoE, continuous ST drain. Per Lv range+5 DMG+5%',
'패링 3초 홀드 → 흡수 데미지 광역 폭발. Lv당 범위+15 (1렙150, 10렙285)':'Parry 3s hold → absorbed DMG AoE explosion. Per Lv range+15 (Lv1: 150, Lv10: 285)',
'우클 처내기 강화. Lv당 반사 데미지 +10%. 홀드 시 연사':'RMB swipe enhanced. Per Lv reflect DMG +10%. Hold for rapid fire',
'[고정: T 자동] 물리 바늘 3방향 3발 발사. 관통 없음':'[Fixed: T auto] 3 physical needles 3-way spread. No pierce',
'[고정: E] 1발 직선 레이저. +만화방창 → 만화광선(3발 꽈배기). +원소추적탄 → 추적암전(6발 유도)':'[Fixed: E] 1 straight laser. +Barrage → Omni Beam (3 spiral). +Elem Seeker → Homing Dark (6 homing)',
'E탭 마법을 6원소 유도 미사일로 변경. 곡선 궤적으로 적을 추적. 레벨당 사거리+20 (뎀은 _skMul 계수 적용)':'Changes E-tap magic to 6-element homing missiles. Curved trajectory tracking enemies. Per Lv range+20 (DMG uses _skMul)',
'3초마다 악의 구체 생성(1렙 2개). 몸에 밀착하여 적 투사체를 자동 방어(파괴). 레벨당 구체+1':'Spawns malice orbs every 3s (Lv1: 2 orbs). Orbits body, auto-blocks (destroys) enemy projectiles. Per Lv orb+1',
'유도 물리 칼날 1발 (악의30+ST50). 관통률 800+Lv×20+장비. 지속뎀 5초. 쿨 15초':'1 homing physical blade (malice 30 + ST 50). Pierce 800+Lv×20+gear. DOT 5s. CD 15s',
'어둠 소용돌이 소환 (마우스 조준 설치, MP 소모, 쿨 11초, INT 스케일링, 1렙 200범위 +30/렙, 5초 지속, 적 흡인)':'Summon dark vortex (mouse-aim placement, MP cost, CD 11s, INT scale, Lv1 range 200 +30/Lv, 5s duration, pulls enemies)',
'포격식 조준 → 원형 해골무덤 소환. 2스택 (15초/1충전, Lv10→3스택). 둘레에서 뼈가 솟아 공간을 감쌈. 솟을 때 데미지. 적/투사체 차단. 악의 12. Lv당 범위+5% 지속+0.3초':'Artillery-aim → circular bone tomb. 2 stocks (15s/charge, Lv10→3 stocks). Bones rise around perimeter. DMG on rise. Blocks enemies/projectiles. Malice 12. Per Lv range+5% duration+0.3s',
'오망성 시전 → 신성 빛기둥 대폭발. 범위 1500+Lv×100px. 범위 끝까지 넉백(주 성능). 거리감쇠 50%. 스턴 2초. Lv당 뎀+10%. (MP 30%, 쿨 120초)':'Pentagram cast → holy light pillar mega-explosion. Range 1500+Lv×100px. Full-range knockback (main feature). 50% distance falloff. Stun 2s. Per Lv DMG+10%. (MP 30%, CD 120s)',
'검은 오망성 소환. 7초(+Lv당0.5초) 강력 흡인 (데미지 없음, 순수 유틸). 범위 1500+Lv×100px. 흡인력 기본5+Lv당0.5. (MP 30%, 쿨 120초)':'Summon black pentagram. 7s (+0.5s/Lv) strong pull (no DMG, pure utility). Range 1500+Lv×100px. Pull force base 5+0.5/Lv. (MP 30%, CD 120s)',
'빨간 오망성 시전 → 범위 1500+Lv×100px 화염폭발+10초간 화상. 틱당 적 최대HP 1.75%(+Lv당+1.5%). 10초 20틱. 거리감쇠 30%. Lv당 초기뎀+10%. (MP 30%, 쿨 120초)':'Red pentagram cast → range 1500+Lv×100px fire explosion+10s burn. Per tick enemy maxHP 1.75%(+1.5%/Lv). 10s 20 ticks. 30% distance falloff. Per Lv initial DMG+10%. (MP 30%, CD 120s)',
'X키: 그로기 보스 전용. 보스 현재HP 20%(+2%/Lv) + 무기뎀×30(+21%/Lv, 20Lv=150배) + 보스HP 30% 순수뎀. 섬광 돌진 연출. HP/MP/ST 10% 소모. 쿨 5초':'X key: Groggy boss only. Boss current HP 20%(+2%/Lv) + weapon DMG×30(+21%/Lv, Lv20=150×) + boss HP 30% pure DMG. Flash dash. HP/MP/ST 10% cost. CD 5s',
'얼음 속에 들어가 무적 상태. 다시 누르면 파쇄 → 얼음칼날 48발 부채꼴 방사 (MP 40, 쿨 20초). Lv당 칼날+2 뎀+15%':'Enter ice — invincible. Re-press to shatter → 48 ice blades fan spread (MP 40, CD 20s). Per Lv blades+2 DMG+15%',
'[고정: T 자동] 초고속 바늘 연발. 1렙 2발, 5렙마다 +1발. 관통 없음. ST 8. 쿨 1.5초. Lv당 뎀+100%':'[Fixed: T auto] Ultra-fast needles burst. Lv1 2 shots, +1 per 5 levels. No pierce. ST 8. CD 1.5s',
'E홀드: 직선 관통 레이저 채널링. MP 8+Lv/초 지속소모. 폭160+(Lv×10)px, 사거리1200+Lv×80. 관통+감전. Lv당 뎀+21%':'E hold: Straight piercing laser channeling. MP 8+Lv/s drain. Width 160+(Lv×10)px, range 1200+Lv×80. Pierce+shock. Per Lv DMG+21%',
'E탭: 화염 유도빔 발사. MP10. 쿨1초(DEX 스케일). 100% 관통+유도+화상. Lv당 사거리+50 뎀+12%':'E tap: fire homing beam. MP 10. CD 1s (DEX scale). 100% pierce+homing+burn. Per Lv range+50 DMG+12%',
'E: 10초간 대지 진동. 범위 내 용암 기둥이 순차적으로 솟아올라 화상+틱 데미지. MP 100. 쿨 12초. Lv당 범위+10% 뎀+12%':'E: 10s ground tremor. Lava pillars rise sequentially in range — burn+tick DMG. MP 100. CD 12s. Per Lv range+10% DMG+12%',
'독혈 칼날 1발 발사: 관통률 기본 800+Lv×20 + 장비 bowPierce×300/패시브 pPierce×30 반영, +100 보정. 전염+마지막 적 처형. 감염 사망 시 폭발+연쇄 전염. 악의 15. 사거리 4000. 쿨 15초(Lv당-0.5초)':'Fire 1 poison-blood blade: base pierce rate 800+Lv×20 with bowPierce×300 and pPierce×30 scaling, plus +100 bonus. Plague+execute last enemy. Infected death → explosion+chain plague. Malice 15. Range 4000. CD 15s (-0.5s/Lv)',
'마우스 조준 설치. 쿨 20초. 화면 내 클릭 위치에 암전나선 (3초, 10틱, 틱당 100+Lv*20). Lv당 범위+22. 같은 지역 중복 불가':'Mouse-aim placement. CD 20s. Dark spiral at click pos (3s, 10 ticks, 100+Lv*20/tick). Per Lv range+22. No stacking same area',
'현재 위치에 9개 기둥 순차 발동. 5초간 악의 기둥을 소환하여 반경 내 적에게 지속 암전 데미지+감속. 범위 250+(Lv-1)×22. 대왕치기와 합체→기둥강타. 쿨 15초':'9 pillars activate sequentially at current pos. 5s dark pillars deal sustained dark DMG+slow to enemies in radius. Range 250+(Lv-1)×22. Fuses with Giant Slam → Pillar Strike. CD 15s',
'현재 위치에 회복의 영역 설치 (12초 지속). 땅 위: HP/MP/ST 초당+10 리젠 + 회복력 2배 + 쿨다운 속도 2배. 쿨 30초. Lv당 범위+20 지속+0.5초':'Place holy domain at current pos (12s duration). On ground: HP/MP/ST +10/s regen + 2x recovery + 2x CD speed. CD 30s. Per Lv range+20 duration+0.5s',
'범위 내 몬스터 부활력 -15%~30%(Lv1=15%, Lv10=30%). Lv1 범위400, Lv10 범위697. Lv당 범위+33. 쿨 30초. 지속 10초':'Monsters in range: revive power -15%~30%(Lv1=15%, Lv10=30%). Lv1 range 400, Lv10 range 697. Per Lv range+33. CD 30s. Duration 10s',
'마우스 조준 설치. 2스택 (15초/1충전, Lv10→3스택). 범위 내 빙결 저항 -50%, 빙결 게이지 급속 축적. 3초 지속. MP 40. Lv당 범위+22 축적+10%':'Mouse-aim placement. 2 stocks (15s/charge, Lv10→3 stocks). Freeze resist -50% in range, rapid freeze gauge buildup. 3s duration. MP 40. Per Lv range+22 buildup+10%',
'땅을 내리쳐 원형 진동파 발생(범위400). 일반몹에게 큰 포이즈 피해, 보스 체간 파괴에 강함. 회전기폭과 합체→지진폭풍!':'Slam ground → circular shockwave (range 400). High poise DMG to mobs, strong posture break vs bosses. Fuses with Whirlwind Detonate → Earthquake Storm!',
'땅을 내리쳐 원형 진동파 발생(범위400). 일반몹에게 큰 포이즈 피해, 보스 체간 파괴에 강함. 악의기둥과 합체→기둥강타!':'Slam ground → circular shockwave (range 400). High poise DMG to mobs, strong posture break vs bosses. Fuses with Dark Pillar → Pillar Slam!',
'사슬기동 중 E → 즉시 착지하며 화염폭발. 범위200~350 INT 스케일 화염 마법데미지+넉백. 이동거리에 비례해 데미지↑(최대 x4.0). MP 소모. Lv당 범위+16 뎀+12%':'During chain dash E → instant land with fire explosion. Range 200~350 INT scale fire magic DMG+knockback. DMG scales with travel distance (max x4.0). MP cost. Per Lv range+16 DMG+12%',
'사슬기동 중 우클릭 → 땅 내려찍기. 범위200~350 데미지x8 그로기x6. 이동거리 비례 최대x6. 일반몹 즉시 기절(5초), 보스 체간 대량 삭감. Lv당 범위+16 데미지+15% 그로기+15%':'During chain dash RMB → ground slam. Range 200~350 DMG x8 groggy x6. Distance scale max x6. Instant stun mobs (5s), massive boss posture break. Per Lv range+16 DMG+15% groggy+15%',
'[히든: 5성 dimRush 합체] 사슬기동 중 좌클릭 → 이동 중 전방 광역 베기+출혈. STR 스케일 물리데미지. 다단히트. Lv당 뎀+12% 범위+15':'[Hidden: 5-star dimRush fuse] During chain dash LMB → forward AoE slash+bleed while moving. STR scale physical DMG. Multi-hit. Per Lv DMG+12% range+15',
'[히든: 암전나선 합체] Q 홀드 시 보호막이 점점 커지며 HP 초당 10% 회복. 보호막 크기에 비례해 데미지 감소. MP 소모':'[Hidden: Dark Spiral fuse] Q hold: shield grows over time + HP 10%/s regen. DMG reduction scales with shield size. MP cost',
'[히든: 암전나선 합체] E로 조준, 클릭 설치. 에너지 쐐기를 지상에 꽂아 회전+데미지. MP100. 1차지 쿨10초. 5초+Lv당0.5초 지속. Lv당 거리+50':'[Hidden: Dark Spiral fuse] E to aim, click to place. Energy wedge planted on ground — rotates+DMG. MP 100. 1 charge CD 10s. 5s+0.5s/Lv duration. Per Lv range+50',
'[고정: 칼등치기 합체] 보유 시 칼등치기에 전방 충격파 자동 발동. 제자리 처내기. 쿨 5초. Lv당 뎀+12% 범위+20':'[Fixed: Blade Parry fuse] When owned, swipe auto-triggers forward shockwave. Stationary swipe. CD 5s. Per Lv DMG+12% range+20',
'현재 위치에 파쇄 영역 설치 (10초). 범위 내 적 물리방어력 -10%. 쿨 25초. Lv당 범위+22 효과+1% 지속+0.3초':'Place shatter domain at current pos (10s). Enemy phys DEF -10% in range. CD 25s. Per Lv range+22 effect+1% duration+0.3s',
'현재 위치에 침식 영역 설치 (10초). 범위 내 적 마법저항력 -10%. 쿨 25초. Lv당 범위+22 효과+1% 지속+0.3초':'Place corrosion domain at current pos (10s). Enemy magic resist -10% in range. CD 25s. Per Lv range+22 effect+1% duration+0.3s',
'현재 위치에 관통 영역 설치 (10초). 범위 내 적 투사체저항력 -10%. 쿨 25초. Lv당 범위+22 효과+1% 지속+0.3초':'Place pierce domain at current pos (10s). Enemy projectile resist -10% in range. CD 25s. Per Lv range+22 effect+1% duration+0.3s',
'현재 위치에 부활 영역 설치 (10초). 영역 안에서 부활력 +10%. 쿨 25초. Lv당 범위+22 효과+1% 지속+0.3초':'Place revival domain at current pos (10s). Revive power +10% inside zone. CD 25s. Per Lv range+22 effect+1% duration+0.3s',
'[고정: Space] 현재 위치에 가시덫 설치 (1렙 반경200, 10렙398). 슬로우 70%(+2%/Lv, 최대90%)+출혈. INT×magicRef×3(+10%/Lv). 악의 10, 쿨 10초. Lv당 범위+22':'[Fixed: Space] Place spike trap at current pos (Lv1 radius 200, Lv10 398). Slow 70%(+2%/Lv, max 90%)+bleed. INT×magicRef×3(+10%/Lv). Malice 10, CD 10s. Per Lv range+22',
'[고정: E, Lv300 해금] 유도 파란콩 50발 순차 발사 (5초간). MP 100(+1.5/Lv) 소모. 적 추적. 쿨 5초. Lv당 사거리+30 (뎀은 _skMul 계수 적용)':'[Fixed: E, unlock Lv300] 50 homing blue shots fired sequentially (over 5s). MP 100(+1.5/Lv) cost. Tracks enemies. CD 5s. Per Lv range+30 (DMG uses _skMul)',
'[히든: E, Lv700 해금] 홀드 시 3단계 차지 범위폭발 (0.5/1.0/1.5초). 범위 600/1000/1400px. 3단 만충 자동폭발. INT 스케일, 무속성':'[Hidden: E, unlock Lv700] Hold for 3-stage charge AoE explosion (0.5/1.0/1.5s). Range 600/1000/1400px. Stage 3 full charge auto-detonates. INT scale, no element',
'유령 허수아비를 소환하여 유도탄막 어그로를 끈다. 탄막을 흡수해 자원 축적 (기본 20개, Lv당+3). 1개당 HP/MP/ST 각 100. R키로 회수. 쿨 10초':'Summon phantom scarecrow to draw homing projectile aggro. Absorbs projectiles for resource buildup (base 20, +3/Lv). Per absorbed: HP/MP/ST +100 each. R key to retrieve. CD 10s',
'폭발 허수아비 설치. 탄막을 흡수하고 재입력 시 폭발! 1스택당 (INT마법뎀+탄막뎀)×10 마법데미지. 범위 250+흡수×25 (최대1000). 최대흡수 1렙20~20렙60. 쿨 10초':'Place explosive scarecrow. Absorbs projectiles, re-press to detonate! Per stack: (INT magic DMG + proj DMG)×10. Range 250+absorbed×25 (max 1000). Max absorb Lv1=20~Lv20=60. CD 10s',
'[선택: 1~4번, Lv500 해금] 현재 위치에 공성쇠뇌 터렛 설치. 재입력 시 철거. 설치 중 플레이어 석궁 사용 불가 (터렛만 발사). 데미지+50%, 공속+50%, 사거리+50%. ST 100. 쿨 10초. Lv당 뎀+5% 공속+5% 사거리+5%':'[Select: 1~4, unlock Lv500] Deploy siege crossbow turret at current pos. Re-press to dismantle. While deployed: player crossbow disabled (turret fires only). DMG+50%, ATK SPD+50%, range+50%. ST 100. CD 10s. Per Lv DMG+5% ATK SPD+5% range+5%',
'[Ctrl, Lv500 해금] 발동 시 3초 전 상태로 되돌린다. 위치/HP/MP/ST 완전 복원. Lv당 되감기+0.105초 (1렙 3초, 20렙 5초). MP 50(+5/Lv, 20렙150). 쿨 45초':'[Ctrl, unlock Lv500] Rewind to state from 3s ago. Restores position/HP/MP/ST. Per Lv rewind+0.105s (Lv1=3s, Lv20=5s). MP 50(+5/Lv, Lv20=150). CD 45s',
'[선택: 1~4번] 마우스 조준 → 전기창을 땅에 꽂는다. 5스택(12초/1충전, Lv10→6스택). 창끼리 600px 이내면 전류 아크 발생, 경로 위 적에게 감전 틱 데미지. MP 50. 지속 10초(+0.5초/Lv). Lv당 아크뎀+10%':'[Select: 1~4] Mouse aim → plant electric spear on ground. 5 stocks (12s/charge, Lv10→6). Spears within 600px create lightning arcs dealing shock tick DMG to enemies on path. MP 50. Duration 10s (+0.5s/Lv). Per Lv arc DMG+10%',
'성능 등급:':'Perf Grade:',
'벤치 FPS:':'Bench FPS:',
// --- CAT-82: skill panel labels ---
'스킬 정보':'Skill Info',
'타입':'Type',
'미습득':'Not Learned',
'SP 비용':'SP Cost',
'악의 비용':'Malice Cost',
'쿨다운':'Cooldown',
'요구 레벨':'Req. Lv',
'기본 참조뎀':'Base Reference',
'스탯 배율':'Stat Mult',
'패시브 배율':'Passive Mult',
'레벨 배율':'Skill Lv Mult',
'예상 평균 뎀':'Estimated Avg DMG',
'치명타':'Critical',
'치명타 확률':'Crit Rate',
'치명타 배율':'Crit Dmg',
'유효 배율':'Effective Mult',
'스킬 고유':'Skill Specific',
'1타 배율':'1-Hit Mult',
'2타 배율':'2-Hit Mult',
'3타 배율':'3-Hit Mult',
'레벨당 뎀':'Per Lv DMG',
'검기 거리':'Crescent Range',
'레벨당 거리':'Lv Range Bonus',
'ST/틱':'ST/Tick',
'레벨당 크기':'Per Lv Size',
'넉백':'Knockback',
'충전 시간':'Charge Time',
'레벨당 범위':'Per Lv Range',
'관통률':'Pierce Rate',
'지속뎀':'DOT Duration',
'무한':'Infinite',
'타격 형식':'AoE Type',
'진동파':'Shockwave',
'스태거':'Stagger',
'높음':'High',
'스톡':'Stocks',
'기둥 수':'Pillars',
'지속':'Duration',
'반경':'Radius',
'슬로우':'Slow',
'활':'Bow',
// --- CAT-83: affix desc labels ---
'독 DoT':'Poison DoT',
'화상 DoT':'Fire DoT',
'빙결 DoT+감속':'Ice DoT+Slow',
'연쇄전격':'Chain Lightning',
'저주(힐차단)':'Curse(Heal Block)',
'방어무시':'Armor Ignore',
'치명타율':'Crit Rate',
'스태거+':'Stagger+',
'체인타겟+':'Chain Target+',
'처치 후 뎀+':'Kill DMG+',
'크리폭발(ATK×)':'Crit Explode(ATK×)',
'원소뎀+':'Elem DMG+',
'공격속도+':'Atk Spd+',
'패리보너스+':'Parry Bonus+',
'추적콤보+10':'Track Combo+10',
'작살뎀+':'Harpoon DMG+',
'스킬뎀+':'Skill DMG+',
'쿨다운-':'CD-',
'방어력+':'DEF+',
'쉴드+':'Shield+',
'이동속도+':'Move Spd+',
'크리확률+':'Crit Rate+',
'크리배율+':'Crit Dmg+',
'화염저항':'Fire Res',
'빙결저항':'Ice Res',
'암전저항':'Lightning Res',
'암흑저항':'Dark Res',
'독저항':'Poison Res',
'전원소저항':'All Elem Res',
'물리DR':'Phys DR',
'반사%':'Reflect%',
'가시뎀':'Thorns DMG',
'배리어':'Barrier',
'CC저항':'CC Resist',
'위기뎀+':'Crisis DMG+',
'피격반격':'Hit Counter',
'패링폭발(ATK×)':'Parry Burst(ATK×)',
'체간파괴뎀+':'Poise Break DMG+',
'원소전환':'Elem Convert',
'상태이상해제':'Status Clear',
'불굴(1회생존)':'Tenacity(Survive×1)',
'부활(HP회복)':'Revive(HP Restore)',
'드롭률+':'Drop Rate+',
'경험치+':'EXP+',
'골드+':'Gold+',
'포션회복+':'Potion Heal+',
'사슬게이지+':'Chain Gauge+',
'부활억제':'Anti-Revive',
'부활력+':'Revival Pow+',
'부활쿨-':'Revival CD-',
'최대HP%+':'Max HP%+',
'HP리젠+':'HP Regen+',
'회복력+':'Heal Pow+',
'마법뎀+':'Magic DMG+',
'MP소비-':'MP Cost-',
'화염뎀%+':'Fire DMG%+',
'화염관통%':'Fire Pen%',
'적중화상':'On-Hit Burn',
'크리화폭':'Crit Fire Burst',
'화상지속+':'Burn Duration+',
'화염뎀보너스':'Fire DMG Bonus',
'빙결뎀%+':'Ice DMG%+',
'빙결관통%':'Ice Pen%',
'적중빙결':'On-Hit Freeze',
'크리빙폭':'Crit Ice Burst',
'빙결지속+':'Freeze Duration+',
'빙결뎀보너스':'Ice DMG Bonus',
'뇌전뎀%+':'Lightning DMG%+',
'뇌전관통%':'Lightning Pen%',
'적중감전':'On-Hit Shock',
'크리뇌폭':'Crit Lightning Burst',
'감전지속+':'Shock Duration+',
'뇌전뎀보너스':'Lightning DMG Bonus',
'암흑뎀%+':'Dark DMG%+',
'암흑관통%':'Dark Pen%',
'적중저주':'On-Hit Curse',
'크리암폭':'Crit Dark Burst',
'저주지속+':'Curse Duration+',
'암흑뎀보너스':'Dark DMG Bonus',
'독뎀%+':'Poison DMG%+',
'독관통%':'Poison Pen%',
'적중중독':'On-Hit Poison',
'크리독폭':'Crit Poison Burst',
'독지속+':'Poison Duration+',
'독뎀보너스':'Poison DMG Bonus',
'근접뎀%+':'Melee DMG%+',
'원거리뎀%+':'Ranged DMG%+',
'마법뎀%+':'Magic DMG%+',
'빔뎀%+':'Beam DMG%+',
'DoT뎀%+':'DoT DMG%+',
'투사체뎀%+':'Proj DMG%+',
'범위반경+':'AoE Radius+',
'근접크리+':'Melee Crit+',
'마법크리+':'Magic Crit+',
'석궁크리+':'Xbow Crit+',
'근접공속+':'Melee Spd+',
'석궁공속+':'Xbow Spd+',
'시전속도+':'Cast Spd+',
'전속성관통':'All Elem Pen',
'쉴드관통':'Shield Pen',
'방어력깎기':'Armor Shred',
'투사체속도+':'Proj Speed+',
'적중시화구':'On-Hit Fireball',
'적중시연쇄뇌격':'On-Hit Chain Lightning',
'적중빙결%':'On-Hit Freeze%',
'적중스턴%':'On-Hit Stun%',
'적중중독%':'On-Hit Poison%',
'적중출혈%':'On-Hit Bleed%',
'적중약화%':'On-Hit Weaken%',
'적중감속%':'On-Hit Slow%',
'적중표적%':'On-Hit Mark%',
'크리폭발(HP%)':'Crit Explode(HP%)',
'크리연쇄(HP%)':'Crit Chain(HP%)',
'크리빙결%':'Crit Freeze%',
'크리HP+':'Crit HP+',
'크리MP+':'Crit MP+',
'크리쉴드+':'Crit Shield+',
'피격방어+':'Hit DEF+',
'반격가시':'Counter Thorns',
'빙결파동%':'Ice Nova%',
'자동암흑막':'Auto Dark Shield',
'주기치유':'Periodic Heal',
'시체폭발%':'Corpse Explode%',
'회피뎀+':'Dodge DMG+',
'패링폭발%':'Parry Burst%',
'블록HP+':'Block HP+',
'블록MP+':'Block MP+',
'회전참뎀+':'Whirlwind DMG+',
'옴니빔뎀+':'Omni Beam DMG+',
'화구뎀+':'Fireball DMG+',
'미사일뎀+':'Missile DMG+',
'청탄뎀+':'Blue Shot DMG+',
'폭렬탄뎀+':'Blast Shot DMG+',
'지옥광선뎀+':'Hell Ray DMG+',
'악의폭풍뎀+':'Malice Storm DMG+',
'연쇄참뎀+':'Chain Slash DMG+',
'거인강타뎀+':'Giant Slam DMG+',
'유령보행뎀+':'Ghost Walk DMG+',
'악의박격뎀+':'Malice Mortar DMG+',
'화염오라뎀+':'Fire Aura DMG+',
'빙구뎀+':'Ice Orb DMG+',
'화염빔뎀+':'Fire Beam DMG+',
'악의사냥뎀+':'Malice Hunt DMG+',
'암흑기둥뎀+':'Dark Pillar DMG+',
'역병뎀+':'Plague DMG+',
'가시오라뎀+':'Spike Aura DMG+',
'연쇄돌격뎀+':'Chain Assault DMG+',
'회피확률+':'Dodge Rate+',
'회피쿨-':'Dodge CD-',
'쉴드%+':'Shield%+',
'쉴드리젠%+':'Shield Regen%+',
'쉴드쿨-':'Shield CD-',
'HP리젠%+':'HP Regen%+',
'ST리젠+':'ST Regen+',
'ST리젠%+':'ST Regen%+',
'MP리젠+':'MP Regen+',
'MP리젠%+':'MP Regen%+',
'화염DR':'Fire DR',
'빙결DR':'Ice DR',
'뇌전DR':'Lightning DR',
'암흑DR':'Dark DR',
'독DR':'Poison DR',
'전체DR':'All DR',
'엘리트DR':'Elite DR',
'스턴저항':'Stun Res',
'감속저항':'Slow Res',
'넉백저항':'KB Res',
'돌진거리+':'Dash Range+',
'돌진쿨-':'Dash CD-',
'전투이속+':'Combat MSpd+',
'비전투이속+':'Out-Combat MSpd+',
'습득범위+':'Pickup Range+',
'전스탯+':'All Stats+',
'적중자원+':'On-Hit Resource+',
'화염최대저항+':'Fire Max Res+',
'빙결최대저항+':'Ice Max Res+',
'뇌전최대저항+':'Lightning Max Res+',
'암흑최대저항+':'Dark Max Res+',
'독최대저항+':'Poison Max Res+',
'스킬쿨-':'Skill CD-',
'물약쿨-':'Potion CD-',
'강화성공+':'Craft Rate+',
'악의획득+':'Malice Gain+',
'악마화뎀+':'Demon DMG+',
'악마화DR':'Demon DR',
'영혼수확+':'Soul Harvest+',
'생명흡혈%':'Life Leech%',
'과치유→쉴드':'Overheal→Shield',
'만마나뎀+':'Full MP DMG+',
'이동DR':'Move DR',
'정지뎀+':'Stationary DMG+',
'회피후뎀+':'After Dodge DMG+',
'패링쉴드+':'Parry Shield+',
'콤보보너스+':'Combo Bonus+',
'HP≥70%뎀+':'HP≥70% DMG+',
'적HP≤30%뎀+':'Foe HP≤30% DMG+',
'HP100%뎀+':'HP100% DMG+',
'HP≤35%뎀+':'HP≤35% DMG+',
'적HP≤20%뎀+':'Foe HP≤20% DMG+',
'근접뎀+':'Melee DMG+',
'원거리뎀+':'Ranged DMG+',
'스턴적뎀+':'vs Stunned DMG+',
'빙결적뎀+':'vs Frozen DMG+',
'화상적뎀+':'vs Burning DMG+',
'중독적뎀+':'vs Poisoned DMG+',
'저주적뎀+':'vs Cursed DMG+',
'감속적뎀+':'vs Slowed DMG+',
'보스뎀+':'Boss DMG+',
'엘리트뎀+':'Elite DMG+',
'일반몹뎀+':'Mob DMG+',
'선제뎀+':'First Strike DMG+',
'물리흡혈%':'Phys Leech%',
'마나흡수%':'Mana Leech%',
'ST흡수%':'ST Leech%',
'적중HP+':'On-Hit HP+',
'처치HP+':'On-Kill HP+',
'처치MP+':'On-Kill MP+',
'처치ST+':'On-Kill ST+',
'처치시폭발':'On-Kill Explode',
'처치이속+':'On-Kill MSpd+',
'HP≥70%방어+':'HP≥70% DEF+',
'HP≤50%이속+':'HP≤50% MSpd+',
'DoT피해감소':'DoT DMG Reduce',
'보스피해감소':'Boss DMG Reduce',
'근접피해감소':'Melee DMG Reduce',
'원거리피해감소':'Ranged DMG Reduce',
'처치HP회복':'On-Kill HP Restore',
'처치쉴드회복':'On-Kill Shield Restore',
'ST소비-':'ST Cost-',
'HP≥70%공격+':'HP≥70% ATK+',
'HP≤35%흡혈':'HP≤35% Leech',
'보스추가뎀':'vs Boss DMG+',
'엘리트추가뎀':'vs Elite DMG+',
'공격력+':'ATK+',
'크리뎀+':'Crit DMG+',
// --- CAT-84/85/86: affix names + implicit + legendary ---
'물리방패의':'Physical Shield',
'지속의':'Stamina',
'마나의':'Mana',
'원소수호의':'Elem Guard',
'행운의':'Fortune',
'근성의':'Grit',
'풍요의':'Abundance',
'약자포식의':'Predator',
'만혈의':'Full Life',
'사선의':'Low Life',
'처형의':'Execute',
'근접살의':'Melee DMG',
'원거리의':'Ranged',
'경직파의':'Stagger Break',
'동파의':'Freeze Strike',
'연소의':'Burning',
'맹독살의':'Venom Slayer',
'저주살의':'Curse Slayer',
'구속의':'Binding',
'왕살의':'Boss Slayer',
'정예살의':'Elite Slayer',
'군살의':'Mob Slayer',
'선제의':'First Strike',
'흡혈의':'Vampirism',
'흡마의':'Mana Leech',
'흡정의':'Stamina Leech',
'타격재생의':'Hit Regen',
'처치회복의':'Kill Recovery',
'처치흡마의':'Kill Mana Leech',
'처치활력의':'Kill Stamina',
'처치폭발의':'Kill Explosion',
'처치질주의':'Kill Sprint',
'건강방어의':'Healthy Defense',
'중상보호의':'Wounded Shield',
'위기질주의':'Crisis Sprint',
'지속피해방어의':'DoT DR',
'왕피해방어의':'Boss DMG DR',
'근접방어의':'Close DR',
'원거리방어의':'Ranged DR',
'처치생명의':'Kill HP',
'처치수호의':'Kill Shield',
'화염강화의':'Fire Amp',
'화염관통의':'Fire Pierce',
'발화의':'Ignition',
'화염폭발의':'Fire Burst',
'맹화의':'Blaze',
'화염의힘':'Fire Power',
'빙결강화의':'Ice Amp',
'빙결관통의':'Ice Pierce',
'동결의':'Freeze',
'빙결폭발의':'Ice Burst',
'영빙의':'Permafrost',
'빙결의힘':'Ice Power',
'뇌전강화의':'Thunder Amp',
'뇌전관통의':'Thunder Pierce',
'감전의':'Shock',
'뇌전폭발의':'Thunder Burst',
'낙뢰의':'Thunderbolt',
'뇌전의힘':'Thunder Power',
'암흑강화의':'Dark Amp',
'암흑관통의':'Dark Pierce',
'침식의':'Erosion',
'암흑폭발의':'Dark Burst',
'심연의':'Abyss',
'암흑의힘':'Dark Power',
'맹독강화의':'Venom Amp',
'독관통의':'Poison Pierce',
'중독의':'Poisoning',
'독폭발의':'Poison Burst',
'맹독지속의':'Venom Duration',
'독의힘':'Poison Power',
'격투의':'Melee',
'원사의':'Ranged Shot',
'주술의':'Spell',
'광선의':'Beam',
'탄도의':'Ballistic',
'확산의':'AoE Radius',
'근접회심의':'Melee Crit',
'마법회심의':'Spell Crit',
'사격회심의':'Ranged Crit',
'근접쾌속의':'Melee Speed',
'사격쾌속의':'Ranged Speed',
'영창의':'Chanting',
'전속성관통의':'All-Elem Pierce',
'쉴드파괴의':'Shield Bypass',
'갑옷분쇄의':'Armor Shred',
'탄속의':'Proj Speed',
'화구발사의':'Fireball Launch',
'연쇄뇌격의':'Chain Lightning',
'동결타의':'Freeze Strike',
'경직타의':'Stagger Strike',
'독침의':'Poison Sting',
'출혈의':'Bleed',
'약화의':'Weakness',
'둔화의':'Slow',
'표적의':'Marking',
'회심폭발의':'Crit Explosion',
'회심연쇄의':'Crit Chain',
'회심빙결의':'Crit Freeze',
'회심치유의':'Crit Heal',
'회심영력의':'Crit Mana',
'회심수호의':'Crit Shield',
'피격강화의':'Hit Boost',
'반격가시의':'Counter Thorns',
'빙결파동의':'Ice Nova',
'암흑보호의':'Dark Shield',
'치유파동의':'Heal Pulse',
'시체폭발의':'Corpse Explosion',
'회피반격의':'Dodge Counter',
'패링폭파의':'Parry Shatter',
'블록치유의':'Block Heal',
'블록영력의':'Block Mana',
'회전참강화':'Spin Slash Boost',
'옴니빔강화':'Omni Beam Boost',
'화구강화':'Fireball Boost',
'미사일강화':'Missile Boost',
'청탄강화':'Blue Shot Boost',
'폭렬탄강화':'Burst Shot Boost',
'지옥광선강화':'Hellray Boost',
'악의폭풍강화':'Malice Storm Boost',
'연쇄참강화':'Chain Slash Boost',
'거인강타강화':'Giant Slam Boost',
'유령보행강화':'Ghost Walk Boost',
'악의박격강화':'Malice Mortar Boost',
'화염오라강화':'Fire Aura Boost',
'빙구강화':'Ice Orb Boost',
'화염빔강화':'Fire Beam Boost',
'악의사냥강화':'Malice Hunt Boost',
'암흑기둥강화':'Dark Pillar Boost',
'역병강화':'Plague Boost',
'가시오라강화':'Thorn Aura Boost',
'연쇄돌격강화':'Chain Assault Boost',
'회피의':'Evasion',
'회피쿨감의':'Dodge CD Red',
'수호력의':'Shield Power',
'수호재생의':'Shield Regen',
'수호쿨감의':'Shield CD Red',
'재생력의':'Regen Power',
'활력재생의':'Stamina Regen',
'마력재생의':'Mana Regen',
'화염보호의':'Fire Shield',
'빙결보호의':'Ice Shield',
'뇌전보호의':'Thunder Shield',
'해독의':'Antidote',
'만물보호의':'All Protection',
'정예보호의':'Elite Shield',
'경직저항의':'Stagger Resist',
'빙결저항의':'Freeze Resist',
'감속저항의':'Slow Resist',
'넉백저항의':'Knockback Resist',
'돌진거리의':'Dash Range',
'돌진쿨감의':'Dash CD Red',
'전투질주의':'Combat Sprint',
'평화질주의':'Peace Sprint',
'습득범위의':'Pickup Radius',
'힘의':'Strength',
'민첩의':'Dexterity',
'지능의':'Intelligence',
'만능의':'Versatile',
'지구력의':'Max Stamina',
'마나력의':'Mana Power',
'타격자원의':'Hit Resource',
'화염한계의':'Fire Cap',
'빙결한계의':'Ice Cap',
'뇌전한계의':'Thunder Cap',
'암흑한계의':'Dark Cap',
'독한계의':'Poison Cap',
'스킬쿨감의':'Skill CD Red',
'물약쿨감의':'Potion CD Red',
'장인의':'Craftsmanship',
'탐욕의':'Greed',
'수련의':'Training',
'수집의':'Gathering',
'악마의힘':'Demon Power',
'악마보호의':'Demon Shield',
'영혼수확의':'Soul Harvest',
'생명흡수의':'Life Absorption',
'과치유수호의':'Overheal Shield',
'만마력의':'Full Mana DMG',
'이동방어의':'Moving DR',
'정지공세의':'Stationary Boost',
'회피공세의':'Post-Dodge Boost',
'패링보호의':'Parry Shield',
'콤보폭발의':'Combo Burst',
'물리타격의':'Phys Strike',
'화염타격의':'Fire Strike',
'빙결타격의':'Ice Strike',
'뇌전타격의':'Thunder Strike',
'암흑타격의':'Dark Strike',
'독타격의':'Poison Strike',
'최소공격의':'Min ATK',
'최대공격의':'Max ATK',
'전투력의':'Combat Power',
'무기사거리의':'Weapon Range',
'활사거리의':'Bow Range',
'이중타의':'Double Strike',
'다중발사의':'Multi Shot',
'관통횟수의':'Pierce Count',
'관통유지의':'Pierce Keep',
'연쇄유지의':'Chain Keep',
'범위확장의':'Splash Range',
'범위피해의':'Splash DMG',
'돌진공격의':'Dash ATK',
'반격공격의':'Counter ATK',
'후방타의':'Backstab',
'침식가속의':'Erosion Speed',
'출혈지속의':'Bleed Duration',
'마법타격의':'Magic Strike',
'주문증폭의':'Spell Amp',
'연살뎀의':'Kill Streak DMG',
'연살속의':'Kill Streak Speed',
'기세의':'Momentum',
'정지공격의':'Static Strike',
'이동공격의':'Mobile Strike',
'패링공세의':'Post-Parry Boost',
'임사폭발의':'Near-Death Burst',
'만기력공의':'Full Stamina ATK',
'만마력공의':'Full Mana ATK',
'신선처치의':'Fresh Kill',
'경직연장의':'Stagger Extension',
'빙결연장의':'Freeze Extension',
'둔화강화의':'Slow Amp',
'독중첩의':'Poison Stack',
'출혈중첩의':'Bleed Stack',
'발화강화의':'Ignite Amp',
'동상강화의':'Frostbite Amp',
'감전강화의':'Shock Amp',
'사선회심의':'Low HP Crit',
'갑옷강화의':'Armor Boost',
'블록흡수의':'Block Absorb',
'방패타격의':'Shield Bash',
'방패경직의':'Shield Stagger',
'격투속의':'Brawl Speed',
'격투회심의':'Brawl Crit',
'격투경직의':'Brawl Stagger',
'하반재생의':'Leg Regen',
'CC단축의':'CC Duration Red',
'돌진타의':'Dash Strike',
'돌진범위의':'Dash AoE',
'은신질주의':'Stealth Sprint',
'회피감쇠의':'Dodge DR',
'속성감쇠의':'Elem DR',
'마나왕관의':'Mana Helm',
'시전왕관의':'Cast Helm',
'쿨감왕관의':'CD Helm',
'경험왕관의':'EXP Helm',
'공생의':'Symbiosis',
'수질의':'Body-Soul',
'회심흡의':'Crit Leech',
'체마의':'HP-Mana',
'체기의':'HP-Stamina',
'마기의':'Mana-Stamina',
'전재생의':'All Regen',
'힘민의':'STR-DEX',
'힘지의':'STR-INT',
'민지의':'DEX-INT',
'운근의':'Fortune-Grit',
'수확의':'Harvest',
'빙화의':'Ice-Fire',
'뇌암의':'Thunder-Dark',
'근마의':'Blade-Magic',
'속성침식의':'Elem Erosion',
'화염반지의':'Fire Ring',
'빙결반지의':'Ice Ring',
'뇌전반지의':'Thunder Ring',
'암흑반지의':'Dark Ring',
'독반지의':'Poison Ring',
'콤보반지의':'Combo Ring',
'처치마나의':'Kill Mana',
'관통반지의':'Pierce Ring',
'만능목걸이의':'Allround Necklace',
'회심목걸이의':'Crit Necklace',
'관통목걸이의':'Pierce Necklace',
'스킬목걸이의':'Skill Necklace',
'콤보한계의':'Combo Max',
'처치치유의':'Kill Heal',
'지구벨트의':'Stamina Belt',
'포션벨트의':'Potion Belt',
'활력벨트의':'Vitality Belt',
'탐욕벨트의':'Greed Belt',
'마나띠의':'Mana Band',
'시전띠의':'Cast Band',
'마력띠의':'Magic Band',
'주술띠의':'Spell Band',
'속성띠의':'Elem Band',
'전사의힘':'Warrior Power',
'전사생명의':'Warrior Life',
'전사흡혈의':'Warrior Leech',
'전사인내의':'Warrior Poise',
'마법사의힘':'Mage Power',
'마법사마나의':'Mage Mana',
'마법사수호의':'Mage Shield',
'마법사속성의':'Mage Elem',
'궁수의힘':'Archer Power',
'궁수사거리의':'Archer Range',
'궁수관통의':'Archer Pierce',
'궁수질주의':'Archer Sprint',
'탱크생명의':'Tank Life',
'탱크방어의':'Tank Defense',
'탱크블록의':'Tank Block',
'탱크가시의':'Tank Thorns',
'암살회심의':'Assassin Crit',
'암살후방의':'Assassin Backstab',
'암살독의':'Assassin Poison',
'암살회피의':'Assassin Dodge',
'종결자의':'The Ender',
'생존자의':'Survivor',
'종결수호의':'End Shield',
'종결회심의':'End Crit',
'종결공격의':'End ATK',
'종결저항의':'End Resistance',
'종결파괴의':'End Destruction',
'종결보호의':'End Protection',
'종결흡혈의':'End Leech',
'종결인내의':'End Poise',
'종결쿨감의':'End CD Red',
'종결경험의':'End EXP',
'종결약탈의':'End Loot',
'종결악의의':'End Malice',
'종결힘의':'End STR',
'종결민첩의':'End DEX',
'종결지능의':'End INT',
'종결행운의':'End LCK',
'종결근성의':'End Grit',
'종결연살의':'End Kill Chain',
'건강공세의':'Healthy Offense',
'중상폭발의':'Wounded Burst',
'중상흡혈의':'Wounded Leech',
'토벌의':'Vanguard',
'정예토벌의':'Elite Vanguard',
'극대화의':'Maximize',
'공격력 +X%':'ATK +X%',
'관통 확률 +X%':'Pierce Chance +X%',
'방어율 +X%':'Block Rate +X%',
'물리 피해감소 +X%':'Phys DR +X%',
'최대 HP +X':'Max HP +X',
'공격속도 +X%':'ATK Speed +X%',
'상태이상 저항 +X%':'Status Resist +X%',
'이동속도 +X%':'Move Speed +X%',
'원소 저항 +X%':'Elem Resist +X%',
'최대 HP +X%':'Max HP +X%',
'회피 쿨다운 -X%':'Dodge CD -X%',
'물약 쿨다운 -X%':'Potion CD -X%',
'부활력 +X%':'Revive Power +X%',
'마법 데미지 +X%':'Magic DMG +X%',
'전설 특수':'Legendary Special',
'5타 콤보 완성 시 데빌포스 20% 즉시 충전':'5-hit combo: instantly charge DevilForce 20%',
'처치 시 이속 +40%(3초) + 다음 공격 크리 보장':'Kill: MoveSpd +40%(3s) + next attack guaranteed Crit',
'스태거 발동 시 범위 충격파 (ATK×120%)':'Stagger: AoE shockwave (ATK×120%)',
'스태거 발동 시 범위 충격파 (ATK×100%)':'Stagger: AoE shockwave (ATK×100%)',
'강타 시 적 넉백 거리 2배 + 벽충돌 추가뎀':'Heavy hit: Knockback ×2 + wall collision bonus DMG',
'출혈 대상 크리 시 잔여 DoT×300% 즉시 폭발':'Crit vs Bleeding: remaining DoT×300% instant explosion',
'작살 착지 타격 수만큼 데미지 +20% 중첩(최대5)':'Javelin landing hits: stack +20% DMG (max 5)',
'치명타 시 추가 투사체 1발 발사':'Crit: fire 1 additional projectile',
'패리 성공 시 반격 데미지 ×2':'Parry: counter DMG ×2',
'피격 시 3초 쿨로 HP 5% 즉시 회복':'On Hit (3s CD): restore 5% HP instantly',
'스킬 사용 시 20% 확률로 쿨다운 미소모':'Using skills: 20% chance no cooldown consumed',
'공격속도 +20% + 기본공격에 랜덤 원소 추가':'ATK Speed +20% + basic attacks add random element',
'이동 중 지속 HP 재생 (초당 HP의 1%)':'While moving: HP regen (1% HP/sec)',
'회피 직후 첫 공격 데미지 +80%':'First attack after Dodge: DMG +80%',
'패리 타이밍 판정 +50% 확대':'Parry timing window +50% expanded',
'원소 반응 발동 시 추가 폭발 (ATK×80%)':'Elemental reaction: bonus explosion (ATK×80%)',
'처치 시 데빌포스 5% 회복':'Kill: restore 5% DevilForce',
'HP 50% 이하 시 전 스킬 쿨다운 -30%':'Below 50% HP: all skill CD -30%',
'물약 사용 시 5초간 피해 +15%':'Using Potion: DMG +15% for 5s',
'암묵':'Implicit',
'낡은 악마의 팔찌':'Worn Demon Bracelet',
'흑요석 악마의 팔찌':'Obsidian Demon Bracelet',
'미스릴 악마의 팔찌':'Mithril Demon Bracelet',
'낡은 생명의 팔찌':'Worn Life Bracelet',
'확인':'Confirm',
'조작법':'Controls',
'살아남으려면 익혀라':'Master this to survive',
'전투':'Combat',
'이동 / 상호작용':'Move / Interact',
'메뉴':'Menu',
'시스템':'System',
'아무 키를 눌러 시작':'Press any key to start',
'스테이지':'Nivå',
'💪 힘 (STR)':'💪 STR',
'🏹 민첩 (DEX)':'🏹 DEX',
'🔮 지능 (INT)':'🔮 INT',
'🍀 행운 (LCK)':'🍀 LCK',
'⚔️ 맹공':'⚔️ Onslaught',
'🔱 돌파':'🔱 Breakthrough',
'⚡ 반격':'⚡ Retaliation',
'🔮 마력폭주':'🔮 Mana Surge',
'🎯 정밀사격':'🎯 Precision',
'🛡 수호신':'🛡 Aegis',
'💚 회복력':'💚 Recovery',
'💥 급소':'💥 Vital Strike',
'🎁 약탈':'🎁 Plunder',
'🔱 관통':'🔱 Pierce',
'💠 마력회복':'💠 Mana Recovery',
'🏹 쇠뇌력':'🏹 Crossbow Mastery',
'⚔ 광전사':'⚔ Berserker',
'🎯 추적자':'🎯 Tracker',
'🗡 물리관통':'🗡 Phys Penetration',
'🔮 마법관통':'🔮 Magic Penetration',
'🌿 풍요':'🌿 Abundance',
'🐺 약자포식':'🐺 Predator',
'☠ 침식':'☠ Corrosion',
'💎 마력그릇':'💎 Mana Vessel',
'💪 힘의그릇':'💪 Stamina Vessel',
'👿 악의중독':'👿 Malice Addict',
'❤️ 강인':'❤️ Fortify',
'🛡 철벽':'🛡 Iron Wall',
'🎯 사냥꾼':'🎯 Hunter',
'✦ 인간성':'✦ Humanity',
'☠ 악마성':'☠ Demon',
'1. 악의폭풍':'1. Malice Storm',
'2. 칼날 계열':'2. Blade Skills',
'3. 역병 확장':'3. Plague Expand',
'4. 이동스킬 마스터':'4. Movement Master',
'5. 사슬 확장':'5. Chain Expand',
'6. 💀 필살기 선택':'6. 💀 Ultimate Pick',
'7. 멸살+만화+원소+전격이동':'7. Beam+Barrage+Elem+Blink',
'8. 회전참+기폭+대왕':'8. Whirl+Det+Giant',
'9. 방패 합체':'9. Shield Fuse',
'10. 해골무덤+악의폭풍':'10. Bone Wall+Malice Storm',
'11. 폭풍소환+얼음보주':'11. Storm+Ice Orb',
'12. 뇌전걸음':'12. Ghost Walk',
'13. 신성 영역':'13. Holy Domain',
'14. 6단합체: 폭풍빔':'14. 6-Fuse: Storm Beam',
'15. 신성+빙결':'15. Holy+Ice',
'16. 암흑+가시+대왕2':'16. Dark+Spike+Slam2',
'17. 사슬 최종':'17. Chain Final',
'⚡ 이동스킬':'⚡ Movement',
'⚔️ 물리':'⚔️ Physical',
'🛡️ 방어':'🛡️ Defense',
'🔮 마법':'🔮 Magic',
'🏹 석궁/투사체':'🏹 Crossbow/Projectile',
'⚙️ 영역':'⚙️ Domain',
'💀 필살기':'💀 Ultimate',
'⭐ 추천':'⭐ Recommend',
'⚔ 공격':'⚔ Attack',
'🛡 방어':'🛡 Defense',
'⚙ 특수':'⚙ Special',
  '👻 공성허수아비!':'👻 Siege Scarecrow!',
  '💥 공성허수아비 폭발!':'💥 Siege Scarecrow Blast!',
};

const _NO_PFX={
'녹슨':'Rustet','강철':'Stål','흑요석':'Obsidian','미스릴':'Mithril','심판의':'Dom','천벌의':'Guddommelig Vrede','파멸의':'Ødeleggelse',
'불꽃':'Flamme','화염':'Inferno','염화':'Helvetesild','지옥불':'Helvetesglød','지옥화':'Helvetesglød','지옥':'Helvetesglød','멸화의':'Utryddende',
'냉기':'Frost','빙결':'Fryst','빙하':'Glasial','서리의':'Rim','서리':'Rim','영겁빙':'Evig Is',
'그림자':'Skygge','암흑':'Mørke','심연':'Avgrunn','나락의':'Nether','나락':'Nether','무간의':'Tomrom',
'전기':'Gnist','낙뢰':'Torden','암전':'Lyn','뇌신의':'Stormguden','뇌신':'Stormguden','만뢰의':'Tusen Tordener',
'축복':'Velsignet','성광':'Hellig Lys','신성':'Sakral','천사의':'Engelaktig','신벌의':'Guddommelig Dom',
'낡은':'Slitt','천':'Stoff','가죽':'Lær','강철사':'Stålvevd','은':'Sølv','은사':'Sølvtråd','화염의':'Inferno','빙결의':'Fryst','암흑의':'Mørke','암전의':'Lyn'
};
const _NO_BASE={
'대검':'Tohandsssverd','석궁':'Armbrøst','연사석궁':'Repeterarmbrøst','마력석궁':'Magisk Armbrøst',
'견갑':'Skjold','대견갑':'Stort Skjold','전투화':'Kampstøvler','갑옷':'Rustning','갑주':'Rustning',
'왕관':'Krone','장갑':'Hansker','건틀릿':'Panservotter','바지':'Bukser','각반':'Benbeskyttelse',
'허리띠':'Belte','벨트':'Belte','부적':'Talisman','목걸이':'Halskjede','반지':'Ring',
'망토':'Kappe','팔찌':'Armbånd','귀걸이':'Øredobb',
  '⚡ 연격!':'⚡ Rapid Strike!',
  '⚔ 난타!':'⚔ Barrage!',
  '💥 강타!':'💥 Slam!',
  '🌀 휘두르기!':'🌀 Sweep!',
  '방어↓':'DEF↓',
// --- Demo End Screen ---
'데모 종료':'Slutt på Demo',
'여기까지 데모입니다. 정식 출시를 기대해주세요!':'Dette er slutten på demoen. Vi ser frem til den fulle lanseringen!',
'STEAM 위시리스트로 응원해 주세요!':'Støtt oss ved å legge til spillet på ønskelisten din på Steam!',
'STEAM 위시리스트':'Steam-ønskeliste',

// --- CAT-92 sync ---
'흑요염 파괴자':'Obsidianflammens Ødelegger',
'독사':'Giftslange',
'🐍 독사!':'🐍 Giftslange!',
'더블탭 or Shift+방향키! 전격이동으로 탈출해!':'Dobbelttrykk eller Shift+Retning! Dash for å flykte!',
'👻 공성유령!':'👻 Beleiriingsånd!',
'💥 공성유령 폭발!':'💥 Beleiriingsåndeksplosjon!',
'프레임 표시 (FPS)':'Vis FPS',
'여기까지 데모입니다...':'Demoen slutter her...',
'투구 착용':'Hjelm utstyrt',
'투구 해제':'Hjelm fjernet',
'✟ 신성한 결계!':'✟ Hellig Barriere!',
'혼돈의 투구':'Kaoshjelm',
'전지전능의 투구':'Allmektighetens hjelm',
'방향키 연타':'Trykk piltaster raskt',
'까마귀와 고양이가 아이템을 주워준다. 수거 범위 안이면.':'Ravnen og katten samler gjenstander. Hvis innenfor rekkevidde.',
'Ctrl 얼음보주로 탈출! 없으면 방향키 연타!':'Ctrl — Iskule for flukt! Ingen? Trykk piltaster!',
'💥 폭발 허수아비!':'💥 Eksplosivt fugleskremsel!',
'👻 유령총!':'👻 Spøkelsesspistol!',
' 뎀 ':' SKD ',
'기절!  ':'Bedøvet!  ',
'투구':'Hjelm',
'악마팔찌':'Demonarmbband',
'생명팔찌':'Livsarmbband',
'👻 유령!':'👻 Spøkelse!',
'🦴 해골무덤!':'🦴 Beinhaug!',
};