// 지옥의 길 — Polski (pl)
const _PL={
// --- Stage / Boss ---
'썩은 숲':'Zgniły Las','숲의 감시자':'Strażnik Lasu','독버섯 거인':'Olbrzym Trujących Grzybów','숲의 사냥꾼':'Leśny Łowca','숲의 기생수':'Leśny Pasożyt',
'1장 — 썩은 숲':'ROZ1 — Zgniły Las','2장 — 벌레굴':'ROZ2 — Nora Robaków','3장 — 얼음굴':'ROZ3 — Lodowa Jaskinia',
'4장 — 고통의 화염지대':'ROZ4 — Piekielna Pustkowie','5장 — 지옥의 군단':'ROZ5 — Legion Piekieł','6장 — 사도의 마굴':'ROZ6 — Kryjówka Apostoła','7장 — 지옥성':'ROZ7 — Piekielna Cytadela',
'탈출!':'Uciekł!','처치':'Zabicia','경험치':'EXP','최대콤보':'Maks. Kombo',
// --- Tutorial (Crow) ---
'일어나. 여신이 널 여기 보낸 건 죽으라고가 아니야.':'Wstawaj. Bogini nie wysłała cię tutaj, żebyś umarł.',
'좋아, 감각이 있군. 계속 쳐!':'Dobrze, masz instynkt. Bij dalej!',
'Shift를 눌러. 작살이다. 땅에 꽂아서 끌려가!':'Wciśnij Shift. To harpun. Wbij go i daj się wciągnąć!',
'작살로 끌려가는 중엔 무적이다. 위험할 때 쓰면 좋아.':'Jesteś nieśmiertelny gdy harpun cię ciągnie. Używaj w niebezpieczeństwie.',
'...아파? 당연하지. 여긴 지옥이야.':'...Boli? Oczywiście. To jest piekło.',
'Q를 눌러! 악의로 보호막을 만들 수 있다.':'Wciśnij Q! Stwórz tarczę ze Złości.',
'보호막 없이 버틸 생각은 버려.':'Zapomnij o przeżyciu bez tarczy.',
'우클릭이 패링이다. 적 공격이 닿기 직전에 눌러!':'PPM to parowanie. Wciśnij tuż przed uderzeniem wroga!',
'못 하겠으면 때려. 안 죽으면 그만이야.':'Nie możesz parować? Po prostu bij. Niepotrzebne tylko nie umierać.',
'됐어! 감 잡았구나.':'No proszę! Łapiesz to.',
'하나 죽었군.':'Jeden mniej.',
'유령쇠뇌야. 인사해.':'To kusza ducha. Przywitaj się.',
'빨간 탄을 무서워하지 마. 악의가 강하다.':'Nie bój się czerwonych kul. Złość jest silna.',
'패링으로 돌려주고, Q 보호막도 써! 악의를 잘 굴려!':'Odbijaj je z powrotem, używaj też tarczy Q! Opanuj swoją Złość!',
'무지개빛은 패링 불가! 피해!':'Tęczowych pocisków nie można odbić! Unikaj!',
'피가 새고 있다. Shift. 빠져.':'Krwawisz. Shift. Uciekaj.',
'물약 있잖아! 숫자키!':'Masz miksturę! Klawisze numeryczne!',
'우클릭. 적 손목이 꺾일 때 쳐.':'PPM. Uderz gdy ich nadgarstek się zgina.',
'빨간 탄은 악의 덩어리다. 쳐내서 이용해.':'Czerwone kule to bryły Złości. Odbijaj i używaj.',
'무지개빛만 피하면 돼! 나머지는 다 패링!':'Unikaj tylko tęczy! Wszystko inne — paruj!',
'Q 보호막도 패링이 가능해!':'Tarcza Q też może parować!',
'위험해! 쉬프트 사슬기동으로 피해!!':'Niebezpieczeństwo! Shift — skok łańcuchowy do ucieczki!!',
'쉬프트! 사슬기동은 이동기야! 끌려가면서 무적이라고!':'Shift! Skok łańcuchowy to ruch! Nieśmiertelny gdy wciągany!',
'스킬포인트가 쌓였어! K 눌러서 스킬 배우자!':'Punkty umiejętności gotowe! Wciśnij K by nauczyć umiejętności!',
'속성을 읽어. 약점을 찌르면 두 배로 썩는다.':'Czytaj żywioły. Trafiaj w słabości — podwójne obrażenia.',
'K를 눌러봐! 스킬을 배울 수 있어!':'Wciśnij K! Możesz nauczyć umiejętności!',
'C 눌러서 능력치 찍어! 패시브도 있어~':'Wciśnij C dla statystyk! Są też pasywne~',
'G를 눌러. 대장간에서 장비를 강화할 수 있다.':'Wciśnij G. Ulepszaj ekwipunek w kuźni.',
'F키도 스킬 슬롯이야! 스킬 많으면 L로 배정해봐~':'Klawisz F to też slot umiejętności! Użyj L do przypisania~',
'Z. 필살기다. 아껴 써라.':'Z. To twój ostateczny atak. Używaj mądrze.',
'L-CTRL로 유령걸음이나 얼음보주 쓸 수 있어!':'L-CTRL dla Kroku Ducha lub Lodowej Sfery!',
'L을 눌러. 스킬 슬롯을 정리해야 한다.':'Wciśnij L. Uporządkuj sloty umiejętności.',
'가방 터지겠다! V 눌러서 창고에 넣어둬!':'Torba zaraz pęknie! Wciśnij V by schować w magazynie!',
'ESC로 설정 열 수 있어! 난이도 바꾸기, 자동물약 조절~':'ESC dla ustawień! Trudność, auto-mikstury~',
// --- Tutorial (Cat) ---
'...아직 살아있네. 좌클릭으로 저것들 쳐봐.':'...Jeszcze żyjesz. Spróbuj uderzyć tamte lewym przyciskiem.',
'...치는 건 할 줄 아네. 피하는 건?':'...Uderzać umiesz. A unikać?',
'흥, 작살 못 맞추면 헛수고야.':'Hmph, chybisz harpunem — zmarnowane.',
'...운이 좋았을 뿐이야. 아마.':'...Po prostu szczęście. Pewnie.',
'...고기 냄새. 싫진 않네.':'...Śmierdzi mięsem. Niezłe.',
'...말은 못해.':'...Ono nie może mówić.',
'예쁘다고 만지면 죽어.':'Dotkniesz bo ładne — umrzesz.',
'작살 던져! 끌려가면 무적이야!':'Rzuć harpun! Nieśmiertelny gdy wciągany!',
'...마시든 말든. 네 목숨이니까.':'...Pij albo nie. To twoje życie.',
'그게 패링이야! 타이밍이 전부야~':'To jest parowanie! Timing to wszystko~',
'화염엔 빙결! 암전엔 암흑! 기억해!':'Ogień bije Lód! Błyskawica bije Ciemność! Pamiętaj!',
'...얼어붙은 놈은 오래 안 간다.':'...Zamrożeni długo nie wytrzymają.',
'얼었어! 빙결 중 1.5배야!':'Zamrożony! 1.5x obrażeń gdy zamrożony!',
'...힘을 골라라. 전부 가질 순 없다.':'...Wybierz swoją siłę. Nie możesz mieć wszystkiego.',
'스탯을 올려. 살고 싶으면.':'Podnoś statystyki. Jeśli chcesz żyć.',
'좋은 장비는 강화해야 진짜 힘을 발휘해!':'Dobry ekwipunek wymaga ulepszenia dla pełnej mocy!',
'...슬롯을 채워. 빈 손은 죽음이다.':'...Wypełnij sloty. Puste ręce to śmierć.',
'Z 누르면 대박! 쿨타임 길어서 타이밍 봐야 해!':'Wciśnij Z — masowe obrażenia! Długi czas odnowienia, wybierz moment!',
'Ctrl. 위기에 쓸 카드가 하나 늘었군.':'Ctrl. Jeszcze jedna karta na sytuacje awaryjne.',
'스킬이 많아졌네~ L로 어디에 뭘 넣을지 골라!':'Tyle umiejętności~ Użyj L do przypisania!',
'...버리기 아까운 건 창고에.':'...To co szkoda wyrzucić — do magazynu.',
'...살아남은 것만으로도 대단하군. 설정을 확인해.':'...Sam fakt przeżycia jest imponujący. Sprawdź ustawienia.',
// --- System Messages ---
'MP 부족!':'Za mało MP!','ST 부족!':'Za mało ST!','악의 부족!':'Za mało Złości!',
'충전 중...':'Ładowanie...','캔슬':'Anuluj','아이템 선택 필요':'Wybierz przedmiot',
'악의 소진...':'Złość wyczerpana...','비문 발견...':'Znaleziono inskrypcję...',
'HP물약!':'Mikst. HP!','HP물약 +1':'Mikst. HP +1','HP물약 +2':'Mikst. HP +2',
'HP/MP/ST 회복!':'HP/MP/ST Przywrócone!','보물상자 개봉!':'Skrzynia Otwarta!',
'익사!':'Tonięcie!','피웅덩이!':'Kałuża Krwi!','독혈!':'Toksyczna Krew!','잡힘!':'Złapany!',
'콤보 종료':'Koniec Kombo',
// --- Status Effects ---
'빙결!':'Zamrożony!','화상!':'Płonący!','독!':'Trucizna!','감전!':'Wstrząs!',
'기절!':'Ogłuszony!','봉인됨!':'Opieczętowany!','관통!':'Przebicie!',
// --- Skill Names ---
'기검참':'Cięcie Ki','악의구':'Kula Złości','회전참':'Wicher','기폭팔':'Detonacja',
'칼등 처내기':'Parowanie Klingą','만화방창':'Salwa Igieł','멸살광선':'Promień Zagłady',
'원소추적탄':'Szukający Pocisk Żywiołów','악의 보호자':'Strażnik Złości','악의 사냥':'Polowanie Złości',
'폭풍소환':'Przywołanie Wichru','해골무덤':'Grobowiec Kości','신성폭발':'Wybuch Święty',
'블랙':'Czarna Gwiazda','용암소환':'Przywołanie Lawy','처형':'Egzekucja','악마화 부활':'Odrodzenie Demona',
'붉은꽃':'Szkarłatny Kwiat','얼음보주':'Lodowa Sfera','뇌전걸음':'Krok Ducha',
'만화방창 II':'Salwa Igieł II','마력연사':'Strzał Arkanowy','마력광선':'Laser Arkanowy','업화선':'Promień Piekielnego Ognia',
'지옥진':'Piekielna Formacja','폭독칼날':'Zaraza Ostrze','악의폭풍':'Burza Złości',
'악의기둥':'Ciemny Filar','회복의 영역':'Święta Domena','구속의 영역':'Domena Więzienia',
'아이스스톰':'Lodowa Burza','대왕치기':'Wielkie Uderzenie','대왕치기 2':'Wielkie Uderzenie II',
'기동불꽃':'Łańcuchowy Płomień','기동파괴':'Łańcuchowe Zniszczenie','기동칼날개':'Łańcuchowe Skrzydła Ostrza',
'평화의보호':'Egida Pokoju','참회':'Skrucha','칼등날개':'Skrzydło-Tarcza',
'폭산탄':'Wybuchowy Strzał','파쇄의 영역':'Domena Roztrzaskania','침식의 영역':'Domena Korozji',
'관통의 영역':'Domena Przebicia','부활의 영역':'Domena Odrodzenia','가시덫':'Kolczasta Pułapka',
'푸른비':'Błękitny Deszcz','버스트루프':'Pętla Wybuchu','유령 허수아비':'Zjawowa Przynęta','폭발 허수아비':'Wybuchowa Przynęta',
'공성쇠뇌':'Oblężnicza Kusza','사슬기동:충돌':'Łańcuchowy Skok: Uderzenie',
'사슬기동:화염':'Łańcuchowy Skok: Płomień','전격이동':'Błyskawiczny Krok',
// --- Skill Activation ---
'기동칼날개!':'Skrzydła Ostrza!','기동불꽃!':'Łańcuchowy Płomień!','기동파괴!':'Łańcuchowe Zniszczenie!',
'사슬이동:강화!':'Łańcuchowy Skok!','사슬기동:화염!':'Łańcuchowy Płomień!',
'작살!':'Harpun!','진입!':'Wejście!','레인라이트닝!':'Deszcz Błyskawic!',
'마력연사!':'Strzał Arkanowy!','🔷 마력광선!':'🔷 Laser Arkanowy!','광선 해제':'Laser Wyłączony','MP 부족 — 광선 해제':'MP wyczerpane — Laser Wyłączony','집중...':'Koncentracja...','시전...':'Rzucanie...',
'만화방창!':'Salwa Igieł!','바늘출!':'Wybuch Igieł!','칼날!':'Ostrze!',
'착지!':'Lądowanie!','체간삭감!':'Przełamanie Postawy!',
'기동전폭 준비!':'Łańcuchowy Wybuch Gotowy!','기동불꽃 준비!':'Łańcuchowy Płomień Gotowy!',
'기동파괴 준비!':'Łańcuchowe Zniszczenie Gotowe!',
'유령불꽃 ON':'Płomień Ducha WŁ','유령불꽃 OFF':'Płomień Ducha WYŁ',
'기동칼날개 AUTO ON':'Skrzydła Ostrza AUTO WŁ','기동칼날개 AUTO OFF':'Skrzydła Ostrza AUTO WYŁ',
'자동 버스트!':'Auto Wybuch!','연사 해제':'Szybki Ogień Wyłączony',
'당기기 모드':'Tryb Przyciągania','밀어내기 모드':'Tryb Odpychania',
// --- Skill Slot Tooltips ---
'날개치기':'Uderzenie Skrzydłem','처내기':'Parowanie',
'Shift: 작살 발사 → 끌려감':'Shift: Rzut harpunem → przyciąganie',
'Shift: 화염길+화상':'Shift: Ślad ognia+oparzenie',
'CT: 전류변신+뇌전걸음 (쿨4초)':'CT: Forma błyskawicy+Krok Ducha (CD 4s)',
'CT: 방어구체+빙결 (재입력: 파쇄)':'CT: Lodowa sfera+zamrożenie (ponowne wciśnięcie: rozbicie)',
// --- HUD ---
'근접':'Walka w zwarciu','견갑':'Tarcza','작살':'Harpun','마법':'Magia','보막':'Osłona','유령':'Duch',
'스킬':'Umiej.','대장':'Kuźnia','인벤':'Ekwip.',
// --- Menu ---
'인벤토리':'Ekwipunek','복수의 대장간':'Kuźnia Zemsty','패시브 스킬':'Umiejętności Pasywne',
'전투 스킬':'Umiejętności Bojowe','캐릭터 선택':'Wybór Postaci',
// --- Elements ---
'물리':'Fizyczny','화염':'Ogień','빙결':'Lód','암흑':'Ciemność','암전':'Błyskawica','신성':'Święty','대지':'Ziemia',
// --- Passives ---
'힘':'Siła','민첩':'Zręczność','지능':'Inteligencja','행운':'Szczęście',
'맹공':'Natarcie','철벽':'Forteca','돌파':'Przełom','반격':'Kontratak',
'마력폭주':'Arkanowa Fala','정밀사격':'Precyzyjny Strzał','수호':'Ochrona','수호신':'Duch Strażnik',
'회복력':'Regeneracja','급소':'Krytyczny Cios','약탈':'Grabież','관통':'Przebicie',
'마력회복':'Odnawianie MP','쇠뇌력':'Mistrzostwo Kuszy','광전사':'Berserker','추적자':'Tropiciel',
'물리관통':'Prz. Fizyczne','마법관통':'Prz. Magiczne',
// --- Weapons (Tier 0) ---
'녹슨 대검':'Zardzewiały Dwuręcznik','강철 대검':'Stalowy Dwuręcznik','흑요석 대검':'Obsydianowy Dwuręcznik',
'낡은 석궁':'Zużyta Kusza','강철 석궁':'Stalowa Kusza','흑요석 석궁':'Obsydianowa Kusza',
'대검':'Dwuręcznik','석궁':'Kusza','연사석궁':'Repetier','마력석궁':'Arkanowa Kusza',
// --- Misc ---
'악의 추출':'Ekstrakcja Złości','악의':'Złość','필살기':'Ostateczny','필살기 해제':'Ostateczny Odwołany',
'이전':'Przenieś','강화':'Ulepsz','개봉!':'Otwarte!',
'여신의 가호':'Błogosławieństwo Bogini',
'과부하!':'Przeciążenie!',
// --- Affix Names ---
'맹독의':'Jadowity','불꽃의':'Płonący','냉기의':'Lodowy','번개의':'Elektryczny','암흑의':'Przeklęty',
'관통의':'Przebijający','광폭의':'Szalony','파쇄의':'Miażdżący','연쇄의':'Łańcuchowy',
'학살의':'Masakrujący','폭발의':'Wybuchowy','집중의':'Skupiony','쾌속의':'Szybki','패리의':'Odbijający',
'추적자의':'Tropiciela','작살의':'Harpun','궁극의':'Najwyższy','집중력의':'Uważny',
'강인의':'Wytrwały','수호의':'Ochronny','활력의':'Żywotny','신속의':'Przyspieszony',
'화염수호':'Ochrona Ognia','빙결수호':'Ochrona Lodu','암전수호':'Ochrona Błysk.','암흑수호':'Ochrona Ciemności','독수호':'Ochrona Trucizny','전원소수호':'Ochrona Wszystkiego',
'강철의':'Żelazny','반사의':'Odbijający','가시의':'Kolczasty','흡수의':'Wchłaniający','인내의':'Cierpliwy',
'위기의':'Desperacki','피격반격의':'Odpowiadający',
'패링폭발의':'Wybuch Parowania','스태거폭발의':'Wybuch Zataczania','원소전환의':'Konwerter','정화의':'Oczyszczający',
'불굴의':'Nieugięty','부활의':'Odradzający',
'약탈의':'Rabuś','경험의':'Doświadczony','골드의':'Złoty','포션강화의':'Silny','사슬의':'Łańcuchowy',
'진혼의':'Uświęcający','윤회의':'Cykliczny',
'생명력의':'Żywotny','재생의':'Regenerujący','치유의':'Uzdrawiający',
'마력의':'Arkanowy','절약의':'Wydajny','영혼의':'Duszy',
'예리한':'Ostry','맹렬한':'Brutalny','파멸의':'Zgubny',
// --- Settings UI ---
'게임 설정':'Ustawienia Gry','화면 흔들림':'Trzęsienie Ekranu','파티클 양':'Ilość Cząsteczek',
'효과음 볼륨':'Głośność Efektów','음악 볼륨':'Głośność Muzyki','난이도':'Trudność',
'자동 물약':'Auto Mikstura','최소 줍기 등급':'Min. Poziom Zbierania','최소 줍기 티어':'Min. Tier Zbierania',
'FPS 제한':'Limit FPS','해상도 스케일':'Skala Rozdzielczości','펫 자동수거':'Auto Zbieranie przez Zwierzaka',
'화면 설정':'Ustawienia Ekranu','화면 모드':'Tryb Ekranu','보스 AI 디버그':'Debug AI Bossa',
'유령불꽃 크기':'Rozmiar Płomienia Ducha','화면 명암':'Jasność','유령 글로우':'Blask Ducha',
'기동:칼날개 AUTO':'Skrzydła Ostrza AUTO',
'일반':'Normalny','어려움':'Trudny','지옥':'Piekło','이상':'lub wyżej','사용 안 함':'Wyłączone',
'창 모드':'Okno','보더리스':'Bez Ramki','전체화면':'Pełny Ekran',
'설정':'Ustawienia','조작 키 설정 (클릭하여 변경)':'Klawisze Sterowania (kliknij by zmienić)',
// --- Key Guide ---
'좌클릭 무기 공격':'LMB Atak Bronią','우클릭 탭 칼등 처내기':'PPM Kliknięcie — Parowanie Klingą',
'우클릭 홀드 연속 처내기':'PPM Przytrzymanie — Ciągłe Parowanie','SHIFT 작살 발사':'SHIFT Wystrzał Harpuna',
'이동':'Ruch','아이템 줍기':'Podnieś Przedmiot','능력치 (스탯/패시브)':'Statystyki (Stat/Pasywne)',
// --- Forge ---
'복수의 대장간':'Kuźnia Zemsty','강화':'Ulepsz','분해':'Rozłóż','제작':'Wytwarza',
// --- Death Screen ---
'사망':'Śmierć','부활':'Odrodź','로비로':'Do Lobby',
// --- Inventory/Storage ---
'가방에 공간이 없습니다!':'Brak miejsca w torbie!','가방이 가득 찼습니다!':'Torba pełna!',
'창고가 가득 찼습니다!':'Magazyn pełny!','퀵슬롯이 가득 찼습니다!':'Szybki slot pełny!',
'결정 주머니가 가득 찼습니다!':'Woreczek kryształów pełny!','결정 주머니 가득!':'Woreczek kryształów pełny!',
'악의가 부족합니다!':'Za mało Złości!','가방이 비어있습니다':'Torba pusta',
'창고가 비어있습니다':'Magazyn pusty','비어있음':'Pusty','어픽스 없음':'Brak Afiksów',
'장착!':'Założono!','해제':'Zdarto','보관':'Przechowaj','꺼내기':'Wyjmij',
'현재 장착':'Aktualnie założone','없음 — 제작하세요!':'Brak — Wytworz!',
'리셋할 포인트가 없습니다':'Brak punktów do zresetowania',
'키 설정 초기화 완료':'Klawisze zresetowane',
// --- Forge/Craft ---
'제작 확률':'Szansa Wytworzenia','제작 비용':'Koszt Wytworzenia','보유 악의':'Posiadana Złość',
// --- Canvas UI ---
'보스방':'Sala Bossa','안식처':'Sanktuarium','회복':'Odnawianie','점화':'Zapłon',
'비석':'Stela','읽기':'Czytaj','파괴':'Zniszcz','제단':'Ołtarz','기원':'Modlitwa',
'잔해':'Szczątki','열기':'Otwórz','문지기':'Odźwierny',
'부활 판정 중...':'Ocenianie zmartwychwstania...','기폭 준비!':'Detonacja Gotowa!',
'탈출':'Ucieczka','연타':'Mash',
'추적암전':'Śledzące Błyskawice','만화광선':'Promień Świetlisty','최종 마법':'Końcowa Magia',
'감시중':'Obserwuje','대기':'Czeka','작동중':'Aktywny','설치 가능':'Można zainstalować',
'균열 임박!':'Szczelina blisko!','흡수 중...':'Wchłanianie...',
'흡수 완료 — 재입력으로 회수':'Gotowe — ponowny wpis by zebrać',
'화상':'Oparzenie','당기기':'Przyciągnij','밀어내기':'Odepchnij',
'단계':'poziom','단':'poz.',
// --- Skill Panel ---
'습득!':'Nauczono!','리셋!':'Zresetowano!','세팅!':'Ustawiono!','회수':'Wycofaj',
'합체 해제':'Rozdziel','리셋':'Resetuj','환불':'Zwrot',
'파트너 클릭!':'Kliknij partnera!','SP부족!':'Potrzeba SP!',
'같은 보석 스킬 습득 시 합체 가능':'Można scalić przy nauce tej samej umiejętności klejnotu',
'펼쳐서 초기화':'Rozwiń by resetować','슬롯:':'Slot:',
// --- Stats ---
'남은 SP':'Pozostało SP','처치':'Zabicia','경험치':'EXP','최대콤보':'Maks. Kombo',
'맞아서 사망':'Śmierć od ciosu','레벨':'Poziom','최대HP':'Maks. HP',
// --- Enemy Names ---
'방랑 기사':'Wędrowny Rycerz','보물 악마':'Demon Skarbu','거울의 사도':'Apostoł Lustra',
'상인 악마':'Demon Handlarz','사슬의 죄수':'Zakuty Więzień','시간의 사도':'Apostoł Czasu',
'탐욕의 사도':'Apostoł Chciwości','저주받은 쌍둥이':'Przeklęte Bliźnięta','차원 균열체':'Stworzenie Szczeliny',
'죽음 그 자체':'Sama Śmierć',
// --- Crystals ---
'HP결정':'Kryształ HP','ST결정':'Kryształ ST','MP결정':'Kryształ MP',
'ATK결정':'Kryształ ATK','DEF결정':'Kryształ DEF','속도결정':'Kryształ Szybk.',
'크리결정':'Kryształ Krit.','치명결정':'Kryształ Obra. Krit.','화염결정':'Kryształ Ognia',
'냉기결정':'Kryształ Lodu','암흑결정':'Kryształ Ciemności','번개결정':'Kryształ Błysk.',
'신성결정':'Kryształ Świętości','생명결정':'Kryształ Życia','기력결정':'Kryształ Wytrzymałości',
'마력결정':'Kryształ Many','행운결정':'Kryształ Szczęścia',
'조각':'Odłamek','파편':'Fragment','순수결정':'Czysty Kryształ','완전결정':'Doskonały Kryształ',
'결정 주머니':'Woreczek Kryształów','결정이 없습니다':'Brak kryształów','가루':'Pył',
'전체':'Wszystkie','스탯':'Stat','원소':'Żyw.','유틸':'Użytk.',
'현재':'Aktualny','최대 강화 달성 (+20)':'Maks. ulepszenie osiągnięte (+20)','강화 시':'Po ulepszeniu',
'강화':'Ulepsz','합성':'Syntetyzuj','제작':'Wytwarza',
'같은 종류·같은 성급 결정 3개 → 1성급 상승 (강화 리셋)':'3 kryształy tego samego typu i klasy → awans o 1 klasę (reset ulepszenia)',
'합성 가능한 결정이 없습니다 (같은 종류·성급 3개 필요)':'Brak kryształów do syntezy (potrzeba 3 tego samego typu i klasy)',
'결정 분해 → 결정 가루':'Rozłożenie Kryształu → Pył Kryształu',
'분해할 결정이 없습니다':'Brak kryształów do rozłożenia',
'결정 제작 (가루 → 결정)':'Wytworzenie Kryształu (Pył → Kryształ)',
'탈착':'Odepnij','빈 슬롯':'Pusty slot',
'결정 선택 후 클릭':'Wybierz kryształ i kliknij','클릭하여 선택결정 장착':'Kliknij by założyć wybrany kryształ',
'획득!':'Zdobyto!','제작!':'Wytworzone!','합성!':'Zsyntetyzowane!','최상위 일괄합성':'Masowa Synteza do Maks.','일괄합성 완료':'Masowa Synteza Zakończona',
// --- Stage Names ---
'벌레굴':'Nora Robaków','얼음굴':'Lodowa Jaskinia','고통의 화염지대':'Piekielna Pustkowie',
'지옥의 군단':'Legion Piekieł','사도의 마굴':'Kryjówka Apostoła','지옥성':'Piekielna Cytadela',
// --- Misc ---
'엑소듀서 전사':'Wojownik Exoduser','포이즈':'Postawa',
'신성폭발':'Wybuch Święty','뇌전걸음':'Krok Ducha',
'지옥창고':'Piekielny Magazyn','선택분해':'Selektywne Rozkładanie','쓰레기':'Śmieci',
'복구 불가!':'Nie można przywrócić!','중요잠금':'Ważne-zablokowane',
// --- Phase 9 additions ---
'획득!':'Zdobyto!','자동 장착!':'Auto Założono!','분해! 가루 +':'Rozłożono! Pył +',
'추적암전':'Śledzące Błyskawice','암전':'Błyskawica',
'평화보호':'Egida','지진폭풍':'Burza Trzęsienia','회전기폭':'Wirująca Detonacja',
'공격':'Atak','보호막':'Tarcza','필살기':'Ostateczny',
'합체 스킬로 통합됨':'Scalone w scalonym umiejętnościach','얼음보주 안에선 사용 불가!':'Nie można używać wewnątrz Lodowej Sfery!',
'Shift+키로 폭파':'Shift+klawisz by zdetonować','취소':'Anuluj','충전 중...':'Ładowanie...',
'쿨다운 중...':'Czas odnowienia...','시전 중...':'Rzucanie...','악의 부족!':'Za mało Złości!',
'악의 부족! (12)':'Za mało Złości! (12)','악의 부족! (15)':'Za mało Złości! (15)',
'악의 부족! (20)':'Za mało Złości! (20)','악의 부족! (10)':'Za mało Złości! (10)',
'ST 부족!':'Za mało ST!','HP 부족!':'Za mało HP!',
'필살기 슬롯 클릭하여 배정!':'Kliknij slot ostatecznego by przypisać!',
'필살기 스킬을 습득하세요':'Naucz się umiejętności ostatecznej',
'우클릭(칼등치기)에 합체됨':'Scalone z PPM (parowanie klingą)',
'T(석궁자동)에 세팅하세요':'Ustaw na T (auto kusza)',
'공성쇠뇌 철거 → 이동식':'Oblężnicza kusza rozłożona → przenośna',
'ST 부족! (100)':'Za mało ST! (100)',
'HP 99% 이상!':'HP 99%+!','그로기 보스 없음!':'Brak bossa w groggy!',
'이미 폭풍 지역!':'Już w strefie burzy!','이미 빙풍 지역!':'Już w strefie lodowej burzy!',
'💎 푸른비 해금!':'💎 Błękitny Deszcz odblokowany!','💫 버스트루프 해금!':'💫 Pętla Wybuchu odblokowana!',
'👻 유령 허수아비 해금!':'👻 Zjawowa Przynęta odblokowana!',
'쿨 ':'CD ','과부하 ':'Przeciąż. ',
'🕊️💎 블루콩!':'🕊️💎 Niebieska Kulka!','🛡️💎 빨콩→블루콩!':'🛡️💎 Czerwona→Niebieska Kulka!',
'🛡️💎 무지개→블루콩!':'🛡️💎 Tęczowa→Niebieska Kulka!',
'레어':'Rzadki','슬롯':'Slot',
'성공률':'Wskaźnik Sukcesu','AI 자동 강화':'Auto Ulepszanie AI','최대 강화 달성!':'Maks. ulepszenie osiągnięte!',
'최대 강화':'Maks. ulepszone','회복량':'Regeneracja','현재 장착':'Aktualnie założone',
'없음 — 제작하세요!':'Brak — Wytworz!','제작 확률':'Szansa Wytworzenia',
'분해할 아이템이 없습니다.':'Brak przedmiotów do rozłożenia.','🔨 제작':'🔨 Wytwarza',
'체간':'Postawa','아이템에 마우스를 올리거나 좌클릭으로 선택하세요':'Najedź na przedmiot lub kliknij lewym przyciskiem by wybrać',
// --- Phase 10 ---
'중독':'Trucizna','지뢰':'Mina','함정':'Pułapka','산호가시':'Koralowy Kolec',
'투사체':'Pocisk','도트':'DoT','레어몹':'Rzadki Potwór',
'처치':'zabicia','경험치':'EXP','최대콤보':'Maks. Kombo',
'구역':'Strefa','가시!':'Kolec!',
// --- Hell circle / palette names ---
'림보':'Limbo','색욕':'Pożądanie','탐식':'Obżarstwo','탐욕':'Chciwość','분노':'Gniew','이단':'Herezja','폭력':'Przemoc',
'분노!':'Wściekłość!','탐욕!':'Chciwość!','💀 분노 폭발!':'💀 Wybuch Wściekłości!','심연의 분노!':'Gniew Otchłani!','쌍둥이의 분노!':'Gniew Bliźniąt!',
// --- HUD / misc ---
'소환굴':'Nora Przywołania',
'레어':'Rzadki','처치!':'Pokonano!','왕관 착용':'Korona Założona','왕관 해제':'Korona Zdjęta',
'맨손':'Gołe Ręce','없음':'Brak','갑옷':'Zbroja','부츠':'Buty',
// --- Elite / Mod / Aura ---
'매직':'Magiczny','챔피언':'Mistrz',
'빙결':'Zamrożony','초속':'Przyspieszenie','강타':'Cios','재생':'Regeneracja','맹독':'Trucizna','소환':'Przywołanie',
'기생':'Pasożyt','분열':'Podział','용암자취':'Lawa Ślad','사망폭발':'Wybuch Śmierci',
'화염사슬':'Ognisty Łańcuch','광전':'Szał','텔레포트':'Teleport','보호막':'Bariera',
'소용돌이':'Wir','환영':'Zjawa','전격반사':'Odbicie Szoku','감전':'Elektryczny',
'낙뢰':'Grzmot','연쇄전격':'Łańcuchowe Błyskawice','동료불사':'Nieśmiertelna Pomoc',
'영혼포식':'Pożeracz Dusz','시간왜곡':'Zakrzywienie Czasu','혼돈변이':'Chaotyczna Mutacja',
'복수자':'Mściciel','마법보초':'Magiczna Straż','환영술사':'Iluzjonista',
'함성':'Okrzyk Bojowy','치유':'Leczenie','신속':'Szybkość','수호':'Straż',
// --- Character ---
'다크 판타지 전사. 거대검+검은 갑옷':'Wojownik dark fantasy. Dwuręcznik + Czarna Zbroja',
// --- Phase 11 ---
'⚡ 사슬이동:강화!':'⚡ Łańcuch: Wzmocniony!',
'⚡ 사슬기동:화염!':'⚡ Łańcuchowy Skok: Płomień!',
'달성!':'Osiągnięto!',
'ST':'ST','부족!':'Za mało!',
'타':'Trafienie',
'🌀 당기기 모드':'🌀 Tryb Przyciągania',
'💥 밀어내기 모드':'💥 Tryb Odpychania',
'🕊️빨콩 흡수':'🕊️Wchłonięcie Czerwonej Kulki',
'🕊️흡수':'🕊️Wchłonięcie',
'💎유도 폭발!':'💎Kierowany Wybuch!',
'💥반사 폭발!':'💥Odbity Wybuch!',
'⚡⚡ 참회 귀환!':'⚡⚡ Powrót Skruchy!',
'⚡ 참회!':'⚡ Skrucha!',
'파도!':'Fala!',
'암전!':'Błyskawica!',
'암흑!':'Ciemność!',
'암흑창!':'Ciemna Włócznia!',
'빛창!':'Świetlna Włócznia!',
'체 소환!':'przywołano!',
'개 설치!':'zainstalowano!',
'💥 보스 그로기!':'💥 Boss w Groggy!',
'💥 그로기!':'💥 Groggy!',
'보상':'Bonus',
'⚡ 암전나선!':'⚡ Błyskawicowa Spirala!',
'🌋 지진폭풍!':'🌋 Burza Trzęsienia!',
'SP슬롯':'SP Slot',
'F슬롯':'F Slot',
'⚔🩸 독혈해방!':'⚔🩸 Wyzwolenie Zarazistej Krwi!',
'⚔ 칼날 해방!':'⚔ Wyzwolenie Ostrza!',
'🔨🌋 지옥강타!':'🔨🌋 Piekielny Cios!',
'🔨 대왕치기!':'🔨 Wielkie Uderzenie!',
'✟ 결계의 영역!':'✟ Domena Ward!','✟ 물의 영역!':'✟ Domena Wody!','✟ 파쇄의 영역!':'✟ Domena Roztrzaskania!','✟ 침식의 영역!':'✟ Domena Korozji!','✟ 관통의 영역!':'✟ Domena Przebicia!','✟ 권능의 영역!':'✟ Suwerenna Domena!',
'🛡 회복의 영역!':'🛡 Święta Domena!',
'임계...!':'Krytyczny...!',
'기폭팔!':'Detonacja!','강제기폭!':'Wymuszona Detonacja!','자동기폭!':'Auto Detonacja!',
'회전기폭!':'Wirująca Detonacja!','해제기폭!':'Detonacja Wyzwolenia!','지진기폭!':'Detonacja Trzęsienia!',
'혼돈의 왕관':'Korona Chaosu',
'전지전능의 왕관':'Korona Wszechmocy',
'악마의 팔찌':'Bransoletka Demona',
'생명의 팔찌':'Bransoletka Życia',
// --- wave direction names ---
'🌊 위→아래 파도!':'🌊 Fala Góra→Dół!','🌊 오른→왼 파도!':'🌊 Fala Prawo→Lewo!',
'🌊 아래→위 파도!':'🌊 Fala Dół→Góra!','🌊 왼→오른 파도!':'🌊 Fala Lewo→Prawo!',
// --- Phase 12 ---
'🌀 당기기 모드':'🌀 Tryb Przyciągania','💥 밀어내기 모드':'💥 Tryb Odpychania',
'💎유도 폭발!':'💎Kierowany Wybuch!','💥반사 폭발!':'💥Odbity Wybuch!',
'⚡⚡ 참회 귀환!':'⚡⚡ Powrót Skruchy!','⚡ 참회!':'⚡ Skrucha!',
'암전!':'Błyskawica!','암흑!':'Ciemność!','암흑창!':'Ciemna Włócznia!','빛창!':'Świetlna Włócznia!',
'💥 보스 그로기!':'💥 Boss w Groggy!','💥 그로기!':'💥 Groggy!',
'⚡ 암전나선!':'⚡ Błyskawicowa Spirala!','🌋 지진폭풍!':'🌋 Burza Trzęsienia!',
'⚔🩸 독혈해방!':'⚔🩸 Wyzwolenie Zarazistej Krwi!','⚔ 칼날 해방!':'⚔ Wyzwolenie Ostrza!',
'🔨🌋 지옥강타!':'🔨🌋 Piekielny Cios!','🔨 대왕치기!':'🔨 Wielkie Uderzenie!',
'✟ 결계의 영역!':'✟ Domena Ward!','✟ 물의 영역!':'✟ Domena Wody!','✟ 파쇄의 영역!':'✟ Domena Roztrzaskania!','✟ 침식의 영역!':'✟ Domena Korozji!','✟ 관통의 영역!':'✟ Domena Przebicia!','✟ 권능의 영역!':'✟ Suwerenna Domena!','🛡 회복의 영역!':'🛡 Święta Domena!',
'파도!':'Fala!',
// --- rare mob / special ---
'무적!':'Nieśmiertelny!','🪞 반격!':'🪞 Kontratak!','💢 반격!':'💢 Kontratak!',
'흡수!':'Wchłonięcie!','반격 발사!':'Odbity Strzał!',
'저주! 드랍률 -50%':'Klątwa! Szansa dropu -50%','도망!':'Ucieka!',
'위상!':'Faza!','방어!':'Obrona!',
'회수 HP+':'Odwołanie HP+','이동식 복귀':'Mobilny Powrót','캔슬':'Anuluj',
'약점!':'Słabość!','저항!':'Odporność!','관통!':'Przebicie!',
'유령불꽃 OFF':'Płomień Ducha WYŁ','유령불꽃 ON':'Płomień Ducha WŁ',
'기동칼날개 AUTO ON':'Skrzydła Ostrza AUTO WŁ','기동칼날개 AUTO OFF':'Skrzydła Ostrza AUTO WYŁ',
'콤보 종료: ':'Koniec Kombo: ','익사!':'Tonięcie!',
'피웅덩이!':'Kałuża Krwi!','독혈!':'Toksyczna Krew!','비문 발견...':'Znaleziono inskrypcję...',
'보물상자 개봉!':'Skrzynia Otwarta!','악의 +':'Złość +','잡힘!':'Złapany!',
'저주 ':'Klątwa ','충전 중...':'Ładowanie...','불발...':'Niewypał...',
'작살 약점!':'Słabość na Harpun!',
'전염 x':'Zaraza x','흡수 완료!':'Wchłonięcie Zakończone!',
'부활 성공!':'Odrodzenie Udane!','부활 실패...':'Odrodzenie Nieudane...',
'산호가시':'Koralowy Kolec','가시!':'Kolec!','차원 이동!':'Przesunięcie Wymiarowe!','독!':'Trucizna!',
'탈출!':'Uciekł!','기절 해제':'Ogłuszenie Zdjęte',
'아이템 선택 필요':'Wybierz przedmiot','악의 부족':'Za mało Złości','악의 소진...':'Złość wyczerpana...',
'스킬 미습득':'Brak wyuczonych umiejętności','펼치기':'Rozwiń','접기':'Zwiń',
'조건 미달!':' nie spełnione!','해제!':' Rozdzielono!',
'슬롯':'Slot','자동 ON':' Auto WŁ','자동 OFF':' Auto WYŁ','스킬 해제':' umiejętność usunięta',
'필살기':'Ostateczny','필살기 해제':'Ostateczny Odwołany',
'연사 해제':'Szybki Ogień Wyłączony',
'닫기':'Zamknij','장착 중':'Założone','보관 아이템':'Przechowywany Przedmiot',
// --- Phase 13 ---
'클릭으로 선택 · ESC로 닫기':'Kliknij by wybrać · ESC by zamknąć',
'선택됨':'Wybrano',
'MP 부족!':'Za mało MP!','악의 부족! (30)':'Za mało Złości! (30)',
'MP 부족! (40)':'Za mało MP! (40)','MP 부족! (100)':'Za mało MP! (100)','MP 부족! (10)':'Za mało MP! (10)',
'MP 부족! (':'Za mało MP! (',
'✟ 시전...':'✟ Rzucanie...','🌋 시전...':'🌋 Rzucanie...','⛧ 시전...':'⛧ Rzucanie...',
'❄ 진입!':'❄ Wejście!',
'🔱 작살!':'🔱 Harpun!',
'레벨 부족! (요구: Lv.':'Poziom za niski! (Wymóg: Poz.',
' 장착!':' Założono!',
'가방에 공간이 없습니다!':'Brak miejsca w torbie!',
' 해제':' Zdarto',
'👿 악의 추출: +':'👿 Ekstrakcja Złości: +',
'F 슬롯 해제':'F Slot Usunięty',
'💫 집중...':'💫 Koncentracja...',
'⚡ 마력연사!':'⚡ Strzał Arkanowy!',
'❄빙결!':'❄Zamrożony!','🟢독!':'🟢Trucizna!','⚡감전!':'⚡Wstrząs!','🔥화상!':'🔥Płonący!',
'✦ 여신의 가호 — SP+5 AP+3':'✦ Błogosławieństwo Bogini — SP+5 AP+3',
'⚔ 기동칼날개!':'⚔ Skrzydła Ostrza!',
'🔥 화염관통!':'🔥 Przebicie Ogniem!',
'🔱 관통!':'🔱 Przebicie!',
'⚔ 칼날!':'⚔ Ostrze!',
'💥 착지!':'💥 Lądowanie!',
'💫 기절!':'💫 Ogłuszony!',
'⚡ 체간삭감!':'⚡ Przełamanie Postawy!',
'⚡ 기동파괴! ':'⚡ Łańcuchowe Zniszczenie! T',
'🔥 기동불꽃!':'🔥 Łańcuchowy Płomień!',
'🔥 기동불꽃! ':'🔥 Łańcuchowy Płomień! T',
'단계 ×':' x',
'⚡ 기동전폭! x':'⚡ Łańcuchowy Wybuch! x',
'🔥🔥 3중폭!':'🔥🔥 Potrójny Płomień!','🔥🔥🔥 6중폭!':'🔥🔥🔥 Sześciokrotny Płomień!','🔥🔥🔥🔥 9중폭!':'🔥🔥🔥🔥 Dziewięciokrotny Płomień!','💥 불꽃폭발! ':'💥 Wybuch Płomieni! ',
'🔥 기동불꽃 준비!':'🔥 Łańcuchowy Płomień Gotowy!',
'🔨 기동파괴 준비!':'🔨 Łańcuchowe Zniszczenie Gotowe!',
'⚡ 기동전폭 준비!':'⚡ Łańcuchowy Wybuch Gotowy!',
'콤보 종료: ':'Koniec Kombo: ',
'중독':'Trucizna',
'⚡ 과부하! 5초':'⚡ Przeciążenie! 5s',
'💫 자동 버스트!':'💫 Auto Wybuch!',
'🔨 칼등날개!':'🔨 Skrzydło-Tarcza!',
'💥폭발!':'💥Wybuch!',
'🛡️💎 유도반사!':'🛡️💎 Kierowane Odbicie!',
'⚡💎 블루콩!':'⚡💎 Niebieska Kulka!',
'💎 블루콩!':'💎 Niebieska Kulka!',
'⚡반사!':'⚡Odbicie!',
'💎 푸른비 OFF':'💎 Błękitny Deszcz WYŁ',
'💎 푸른비 ON!':'💎 Błękitny Deszcz WŁ!',
'🔥 지옥진!':'🔥 Piekielna Formacja!',
'🔥 업화선!':'🔥 Promień Piekielnego Ognia!',
'✦ 평화 충격파! ':'✦ Fala Uderzeniowa Pokoju! ',
'⚡ 전류 방출!':'⚡ Wyładowanie Prądu!',
'⚡⚡ 레인라이트닝!':'⚡⚡ Deszcz Błyskawic!',
'💫 광역!':'💫 AOE!',
'🔥 불장판!':'🔥 Strefa Ognia!',
'💫 피니셔!':'💫 Finisher!',
'☠ 지옥에서 귀환!':'☠ Powrót z Piekła!',
'☠ 완전 사망!':'☠ Trwała Śmierć!',
'⚔ 처형! ':'⚔ Egzekucja! ',
'💥 지뢰!':'💥 Mina!',
'⚠ 함정!':'⚠ Pułapka!',
'❌ 우클릭으로! -':'❌ Użyj PPM! -',
'❌ Q키로! -':'❌ Użyj Q! -',
'💥무지개 폭발! ':'💥Tęczowy Wybuch! ',
'🛡️💎 블루콩!':'🛡️💎 Niebieska Kulka!',
'⬜화이트볼!':'⬜Biała Kula!',
'✨💎 블루콩!':'✨💎 Niebieska Kulka!',
'💜다크볼!':'💜Ciemna Kula!',
'❄빙판!':'❄Lodowa Podłoga!',
'🌨빙결!':'🌨Zamrożony!',
'🕸둔화!':'🕸Spowolnienie!',
'⚠트랩!':'⚠Pułapka!',
'💀 역병 처형!':'💀 Zarazista Egzekucja!',
'💥 역병 Finale!':'💥 Zarazisty Finał!',
'⚔ 균열 악마!':'⚔ Demon Szczeliny!',
'자동회수 HP+':'Auto Odwołanie HP+',
'MP 부족 — 연사 해제':'MP niskie — Szybki Ogień Wyłączony',
'MP 부족 — 푸른비 OFF':'MP niskie — Błękitny Deszcz WYŁ',
'🛡️반사!':'🛡️Odbicie!',
'⚡🦴 참회 귀환!':'⚡🦴 Powrót Skruchy!',
'🦴⚡해골번개!':'🦴⚡Kościana Błyskawica!',
'⚡악의폭풍!':'⚡Burza Złości!',
'❄아이스스톰!':'❄Lodowa Burza!',
'⚡ 암전폭발!':'⚡ Wybuch Błyskawicy!',
'⚡ 레인라이트닝! x':'⚡ Deszcz Błyskawic! x',
'❄ 탈출!':'❄ Ucieczka!',
'⚡쉴드!':'⚡Tarcza!',
'❄🌪️ 얼음보주!':'❄🌪️ Lodowa Sfera!',
'🌪️ 전개!':'🌪️ Rozwinięcie!',
'❄ 빙결흡인!':'❄ Lodowy Wir!',
'❄☄ 빙결폭발!':'❄☄ Wybuch Zamrożenia!',
'☄️ 흡인!':'☄️ Wir!',
'☄️ 대폭발!':'☄️ Mega Wybuch!',
'❄ 얼음보주!':'❄ Lodowa Sfera!','⏳ 시간왜곡!':'⏳ Zakrzywienie Czasu!','쿨다운!':'Czas Odnowienia!',
'❄ 파쇄!':'❄ Roztrzaskanie!',
'☄️💥 대폭발!':'☄️💥 Mega Wybuch!',
'반사!':'Odbicie!',
// --- Phase 13: boss moves ---
'💀 도넛!':'💀 Donut!','💀 전멸!':'💀 Zagłada!',
'🌊 파도!':'🌊 Fala!','속박!':'Okowanie!','반격!':'Kontratak!',
'분신!':'Klon!','분신 파괴!':'Klon Zniszczony!','무기 해방!':'Wyzwolenie Broni!',
'❄프리즌!':'❄Więzienie!','⚡ 증표 ':'⚡ Znak ',
'흔들!':'Wstrząs!','⚠ 광역 발사!':'⚠ Atak Obszarowy!',
'🔥 확산!':'🔥 Rozszerzenie!','⚠ 돌진!':'⚠ Szarża!',
'🦅 도약!':'🦅 Skok!','⚡ 레이저!':'⚡ Laser!',
'🌊 충격파!':'🌊 Fala Uderzeniowa!','👹 소환!':'👹 Przywołanie!',
'☄ 유성우!':'☄ Deszcz Meteorów!','🖐 잡기!':'🖐 Chwycenie!',
'🌀 회전참!':'🌀 Wicher!','💣 지뢰!':'💣 Mina!',
'🌀 흡인!':'🌀 Ssanie!','🔴 빨간콩 폭풍!':'🔴 Burza Czerwonych Kulek!',
'🔴🔴 콩 비!':'🔴🔴 Deszcz Kulek!',
'🌊 부채꼴 충격파!':'🌊 Wachlarzowa Fala Uderzeniowa!',
'✴ 멸광 레이저!':'✴ Laser Zagłady!',
'🔴 추적 장판!':'🔴 Śledzenie Strefy!',
'💥 속성탄!':'💥 Pocisk Żywiołów!',
'⚔ 검기!':'⚔ Ki Miecza!','⚔ 재단참!':'⚔ Żnące Cięcie!',
'🌀 나선탄!':'🌀 Spiralny Pocisk!','⚠ 찌르기!':'⚠ Pchnięcie!',
'🔥🔥 지옥기둥!':'🔥🔥 Piekielny Filar!',
'⚔ 환영검!':'⚔ Zjawowy Miecz!',
'💢 반격자세!':'💢 Postawa Kontrataku!',
'⚔ 연격!':'⚔ Kombo!','🌑 암흑!':'🌑 Ciemność!',
'👥 분신!':'👥 Klon!','🌋 균열!':'🌋 Szczelina!',
'🌊 파동!':'🌊 Fala!','💣 추적지뢰!':'💣 Śledzące Miny!',
'⏪ 되감기!':'⏪ Przewinięcie!','🌀 중력장!':'🌀 Pole Grawitacyjne!',
'🔨 벽밀기!':'🔨 Pchnięcie Ściany!','☠ 독안개!':'☠ Trująca Mgła!',
'⛓ 감옥!':'⛓ Więzienie!','⚡ 연쇄번개!':'⚡ Łańcuchowe Błyskawice!',
'🔮 궤도탄!':'🔮 Pocisk Orbitalny!','🛡 방패돌진!':'🛡 Szarża z Tarczą!',
'🪞 반격자세!':'🪞 Postawa Kontrataku!','⚓ 속박!':'⚓ Okowanie!',
'👤 분신!':'👤 Klon!','🖐 탈취!':'🖐 Kradzież!',
'🔥🔥 용암 지대!':'🔥🔥 Strefa Lawy!',
'🌧🌧 화염 폭격!':'🌧🌧 Ostrzał Ogniem!',
'⚡⚡ 전격 장막!':'⚡⚡ Zasłona Błyskawic!',
'💀 내 곁으로!':'💀 Do Mnie!',
'⭕ 안전!':'⭕ Bezpiecznie!',
'💀💀 전멸 폭발!':'💀💀 Wybuch Zagłady!',
'⚡ 쐐기 소멸!':'⚡ Klin Zagłady!',
'🌊충격파!':'🌊Fala Uderzeniowa!',
'👿악의+100':'👿Złość+100',
'💥패링폭발!':'💥Wybuch Parowania!',
'균열 충돌! ':'Zderzenie Szczeliny! ',
'벽 충돌! ':'Zderzenie Ściany! ',
'소환!':'Przywołanie!','환영!':'Zjawa!',
'⚡낙뢰!':'⚡Grzmot!','⚡빔!':'⚡Promień!',
'환영술!':'Iluzja!','💀소환!':'💀Przywołanie!',
'🔮주술!':'🔮Klątwa!','🩸산란!':'🩸Tarło!',
'💢광폭!':'💢Szał!','🕷산란!':'🕷Tarło!',
'❄서리!':'❄Szron!','❄빙결파!':'❄Fala Zamrożenia!',
'💀빙마!':'💀Lodowy Demon!',
// --- Phase 13: mob actions ---
'돌진!':'Szarża!','충격파!':'Fala Uderzeniowa!','독안개!':'Trująca Mgła!',
'연타!':'Seria!','포효!':'Ryk!','강화!':'Wzmocnienie!',
'꼬리!':'Ogon!','은신...':'Ukrycie...','기습!':'Zasadzka!',
'산란!':'Tarło!','독가스!':'Trujący Gaz!','소멸...':'Zanikanie...',
'강타!':'Roztrzaskanie!','분비!':'Wydzielina!','채찍!':'Bicz!',
'출혈!':'Krwawienie!','급강하!':'Nurkowanie!','방출!':'Wyładowanie!',
'충격!':'Impakt!','치유!':'Leczenie!','의식!':'Rytuał!',
'지옥불!':'Piekielny Ogień!','끌려감!':'Wciągnięty!','혀!':'Język!',
'응시!':'Spojrzenie!','낙하!':'Upadek!','핏방울!':'Kropla Krwi!',
'일어남!':'Wstaje!','휩쓸기!':'Zmiatanie!','웅크림':'Kucanie',
'뼈칼날!':'Kościane Ostrze!','감속!':'Spowolnienie!','비명!':'Krzyk!',
'화산탄!':'Wulkaniczny Pocisk!','자폭!':'Samozniszczenie!','감싸기!':'Owijanie!',
'잡기!':'Chwycenie!','내리찍기!':'Przybijanie!','브레스!':'Oddech!',
'비행!':'Lot!','용암비!':'Deszcz Lawy!','물뿜기!':'Strumień Wody!',
'빛...':'Światło...','삼키기!':'Połknięcie!','마비!':'Paraliż!',
'방전!':'Wyładowanie!','집게찍기!':'Uderzenie Szczypcami!','찍기!':'Uderzenie!',
'붙잡기!':'Pojmanie!','감아올리기!':'Owinięcie!','파편!':'Fragment!',
'할퀴기!':'Drapanie!','기생충!':'Pasożyt!',
'심연 해방!':'Wyzwolenie Otchłani!','촉수난타!':'Salwa Macek!',
'삼지창!':'Trójząb!','소용돌이!':'Wir!','해일!':'Tsunami!',
'끼걱!':'Skrzypienie!','폭발!':'Wybuch!','체인!':'Łańcuch!',
'갈기!':'Grzywa!','공포!':'Terror!','흡혈!':'Drenaż!',
'베기!':'Cięcie!','비이이명!!':'Dzwonienie!!','분열!':'Podział!',
'3연참!':'Potrójne Cięcie!','패링!':'Parowanie!',
'...복사...':'...Kopia...','불균형...저주!':'Nierównowaga...Klątwa!',
'저주!':'Klątwa!','균형...강화!':'Równowaga...Wzmocnienie!',
'심판의 기둥!':'Filar Sądu!','처형 선고!':'Wyrok Śmierci!',
'고통의 해방!':'Wyzwolenie Bólu!','너도 느껴봐라!':'Poczuj to też!',
'대검난무!':'Szał Dwuręcznika!','촉수!':'Macka!',
'전방위 빔!':'Promień Wielokierunkowy!','회피!':'Unik!',
// --- Phase 13: rare mob / merchant ---
'[F] 상점':'[F] Sklep','거래 성공!':'Handel Udany!',
'악의 부족! (':'Za mało Złości! (',
'상인이 떠납니다...':'Handlarz odchodzi...',
'사슬 해방!':'Wyzwolenie Łańcucha!','완전 해방!':'Pełne Wyzwolenie!',
'⏪ 시간 되감기!':'⏪ Przewinięcie Czasu!','전환!':'Przełączenie!',
'부활 ':'Odrodzenie ','🌀균열!':'🌀Szczelina!','...사라짐':'...Zniknął',
'낫 베기!':'Cięcie Kosą!','☠ 죽음의 선고!':'☠ Wyrok Śmierci!',
'선고 집행...':'Wykonywanie wyroku...',
'⚡패링!':'⚡Parowanie!','경직!':'Zatrzymanie!',
'⚠ 잡혔다!':'⚠ Złapany!','💥 내던지기!':'💥 Rzut!',
'💥 소용돌이 폭발!':'💥 Wybuch Wiru!',
'👻 순간이동!':'👻 Teleport!','💫 기절! 5초':'💫 Ogłuszony! 5s',
'찌르기 반격!':'Kontratak Pchnięciem!','💢 폭발!':'💢 Wybuch!',
'반격 실패':'Kontratak Nieudany','탈취 반격!':'Kontratak Kradzieży!',
'무기 봉인!':'Broń Opieczętowana!','냠!':'Mniam!',
// --- Phase 13: stage/room/map ---
'합체!':'Scalono!','출구가 열렸다!':'Wyjście się otworzyło!',
'보물상자 출현!':'Skrzynia skarbów pojawiła się!','출구':'Wyjście',
'⚠ 문지기가 살아있다!':'⚠ Odźwierny wciąż żyje!',
'⏱ 타임어택 ':'⏱ Atak Czasowy ',
'처치율 ':'Wskaźnik Zabić ',
'무적!':'Nieśmiertelny!','불사 보호':'Ochrona Nieśmiertelności',
'빙결!':'Zamrożony!','환영 소멸!':'Zjawa Znikła!',
'부활력 ':'Siła Odrodzenia ',
'✟ 신성력 억제! (':'✟ Tłumienie Świętej Siły! (',
'부활 실패 (':'Odrodzenie Nieudane (',
'⚡순간이동!':'⚡Teleport!',
'👻 동반부활!':'👻 Wspólne Odrodzenie!',
'✟ 신성력 억제!':'✟ Tłumienie Świętej Siły!',
'💀 부활 판정 중...':'💀 Ocenianie zmartwychwstania...',
'⚔ 문지기 처치!':'⚔ Odźwierny Pokonany!',
'🚪 보스방 개방!':'🚪 Sala Bossa Otwarta!',
'잔해 출현!':'Szczątki pojawiły się!',
'🌀균열 발생!':'🌀Szczelina otwarta!',
'🔥복수!':'🔥Zemsta!','💥폭독혈!':'💥Zarazista Krew!',
'빙판!':'Lodowa Podłoga!','❄빙결파!':'❄Fala Zamrożenia!',
'❄최종빙결!':'❄Ostateczne Zamrożenie!','빙마 처치!':'Lodowy Demon Pokonany!',
'분리!':'Rozdzielenie!','뼈 파편!':'Kościany Fragment!',
'태아 처치!':'Płód Pokonany!','지배자 처치!':'Władca Pokonany!',
'용암!':'Lawa!','화룡 처치!':'Ognisty Smok Pokonany!',
'최후의 비명!':'Ostatni Krzyk!','산화...':'Utlenianie...',
'심판자 처치!':'Sędzia Pokonany!','고통의 왕 처치!':'Król Bólu Pokonany!',
'수역!':'Woda!','파편 폭발!':'Wybuch Fragmentów!',
'거대어 처치!':'Lewiatan Pokonany!','대사도 처치!':'Wielki Apostoł Pokonany!',
'독웅덩이!':'Trująca Kałuża!','화염장판!':'Strefa Ognia!','전기장!':'Pole Elektryczne!',
'무기 드롭!':'Broń Upuszczona!','보물 발견!':'Skarb Znaleziony!',
'상인의 주머니 +':'Torba Handlarza +',
'속박의 파편!':'Fragment Okowania!','시간의 조각!':'Kawałek Czasu!',
'저주 해제!':'Klątwa Zdjęta!','차원의 결정!':'Kryształ Wymiarowy!',
'전설 아이템!':'Legendarny Przedmiot!','죽음을 이겨냈다!':'Śmierć Pokonana!',
'💥대폭발!':'💥Mega Wybuch!','⚡강화!':'⚡Wzmocnienie!',
// --- Phase 13: combat/defense ---
'장비 ':'Ekwipunek ',
'💫 진동!':'💫 Wibracje!','❄ 무적!':'❄ Nieśmiertelny!',
'\u{1F47B} 유령!':'\u{1F47B} Duch!',
'집중 해제!':'Koncentracja Anulowana!','집중!':'Koncentracja!',
'🕊️ 평화보호 ':'🕊️ Egida ',
'🛡 보호막 ':'🛡 Tarcza ',
'🌀 회전보호막 ':'🌀 Wirująca Tarcza ',
'💥한방캡!':'💥Limit Jednego Uderzenia!',
'⚡쉴드 파괴!':'⚡Tarcza Zniszczona!',
'💀 불굴!':'💀 Nieugięty!',
'💀 1회부활!':'💀 1-razowe Odrodzenie!',
'감시 회수':'Odwołanie Straży',
'악마화 부활!':'Odrodzenie Demona!',
// --- Phase 13: skill panel ---
'기검참':'Cięcie Ki','날개치기':'Uderzenie Skrzydłem',
'배정 가능한 스킬 없음':'Brak umiejętności do przypisania',
'칼날 없음!':'Brak Ostrza!',
'⚔ 악의사냥!':'⚔ Polowanie Złości!',
'❄🌪️ 얼음소용돌이!':'❄🌪️ Lodowy Wir!',
'🌪️ 폭풍소환!':'🌪️ Przywołanie Wichru!',
'\u{1F9B4} 해골무덤!':'\u{1F9B4} Grobowiec Kości!',
'🌹 붉은꽃!':'🌹 Szkarłatny Kwiat!',
'💥 폭산탄!':'💥 Wybuchowy Strzał!',
'🪡 바늘출!':'🪡 Wybuch Igieł!',
'⚡ 전격이동!':'⚡ Błyskawiczny Krok!',
'기둥가시로 흡수됨':'Wchłonięty przez Kolec Filaru',
'🌿 가시덫!':'🌿 Kolczasta Pułapka!',
'👻 유령총!':'👻 Pistolet Ducha!','💥 유령총 폭발!':'💥 Wybuch Pistoletu Ducha!',
'⚡ 전격의창!':'⚡ Włócznia Gromu!',
'🏹 공성쇠뇌 설치!':'🏹 Oblężnicza Kusza Zainstalowana!',
'👻 유령 허수아비!':'👻 Zjawowa Przynęta!',
'💥 폭발 허수아비!':'💥 Wybuchowa Przynęta!',
'축적!':'Nagromadzono!','축적 중...':'Nagromadzanie...','만충! 재입력→폭발':'Pełny! Ponowne wciśnięcie→Wybuch',
'폭발! ':'Wybuch! ','불발...':'Niewypał...','뎀':' OBR',
'🩸 폭독칼날!':'🩸 Zaraza Ostrze!',
'⚡날개치기!':'⚡Uderzenie Skrzydłem!',
'🗡 칼등날개!':'🗡 Skrzydło-Tarcza!',
'🏛️ 악의기둥!':'🏛️ Ciemny Filar!',
'🌿 기둥가시!':'🌿 Kolec Filaru!',
'🌋 지옥강타!':'🌋 Piekielny Cios!',
'💥 체간 붕괴!':'💥 Przełamanie Postawy!',
'💫 포이즈 파괴!':'💫 Zniszczenie Postawy!',
'⚡ 뇌전걸음!':'⚡ Krok Ducha!',
'✟ 구속의 영역!':'✟ Domena Więzienia!',
'✟ 신성폭발!':'✟ Wybuch Święty!',
'⛧ 블랙!':'⛧ Czarna Gwiazda!',
'🌋 용암소환!':'🌋 Przywołanie Lawy!',
'필살기 배정!':'Ostateczny Przypisany!',
'완료':'Gotowe','합체 가능':'Można Scalić','부족':'Za Mało',
'SP 부족! (':'Za mało SP! (',
'🕊️ 히든: 평화의보호 해금!':'🕊️ Ukryte: Egida Pokoju Odblokowana!',
'⚡ 히든: 참회 해금!':'⚡ Ukryte: Skrucha Odblokowana!',
'배정됨':'Przypisano',
'합체 Lv.':'Poz. Scalenia.',
'◆ 같은 보석 스킬 습득 시 합체 가능':'◆ Można scalić przy nauce tej samej umiejętności klejnotu',
// --- Phase 13: inventory/forge/storage ---
'▼ 가방 → 창고 보관':'▼ Torba → Magazyn',
'▲ 창고 → 가방 꺼내기':'▲ Magazyn → Torba',
'✓ 선택됨':'✓ Wybrano',
'⟨ 입력 대기... ⟩':'⟨ Oczekiwanie... ⟩',
'⟨ 대기 ⟩':'⟨ Czekaj ⟩',
'보조':'Pom.',
'키 설정 초기화 (또는 F5 키)':'Resetuj klawisze (lub F5)',
'아무 키 또는 마우스 버튼을 누르세요 (ESC = 취소)':'Wciśnij dowolny klawisz lub przycisk myszy (ESC = anuluj)',
'WebGPU 활성':'WebGPU Aktywny','WebGL2 활성':'WebGL2 Aktywny',
'측정 중...':'Pomiar...',
'불러오기 실패':'Błąd Ładowania',
'장착':'Założone',
'🔒 중요잠금 아이템은 분해 선택 불가!':'🔒 Ważne-zablokowane przedmioty nie mogą być wybrane do rozkładania!',
'장비 강화 (실패 시 재료만 소멸)':'Ulepszanie Ekwipunku (przy niepowodzeniu tylko materiały znikają)',
'강화 보너스 적용':'Bonus Ulepszenia Zastosowany',
'강화 실패!':'Ulepszanie Nieudane!',
'장착된 장비가 없습니다.':'Brak założonego ekwipunku.',
'충분':'Wystarczająco','더 필요':'Potrzeba Więcej',
'장비 선택':'Wybierz Ekwipunek','목표치 설정':'Ustaw Cel',
'악의 투입':'Zainwestuj Złość','자동 시도':'Auto Próba',
'목표 강화치':'Docelowe Ulepszenie',
'예상 필요 악의':'Szac. Potrzebna Złość',
'보유':'Posiadane','강화 시작':'Zacznij Ulepszać',
'위에서 장비를 선택하세요':'Wybierz ekwipunek powyżej',
'⬆ 물약 강화 (최대 10단)':'⬆ Ulepszanie Mikstury (maks. poz. 10)',
'필요':'Wymagane',
'악의의 분해로 — 장비를 악의로 갈아버려라':'Piec Złości — Przemieniaj ekwipunek w Złość',
'전체 선택':'Zaznacz Wszystko','전체 해제':'Odznacz Wszystko',
'희귀 이하':'Rzadki lub Niżej',
'어픽스 리롤!':'Reroll Afiksów!',
'결정 분해 → 결정 가루':'Rozłożenie Kryształu → Pył Kryształu',
'결정 제작 (가루 → 결정)':'Wytworzenie Kryształu (Pył → Kryształ)',
'물리':'Fizyczny','영웅':'Heroiczny','전설':'Legendarny',
'무기 타입':'Typ Broni','활 타입':'Typ Łuku',
'보스방':'Sala Bossa','ST 부족':'Za mało ST',
// --- Phase 14: boss phase labels ---
'💀 광폭화!':'💀 Rozwścieczony!',
// --- Phase 14: chapter pet dialogue ---
'...따라오는 거 아니야. 같은 방향일 뿐이지.':'...Nie idę za tobą. Po prostu w tym samym kierunku.',
'공기가 달라졌어. 더 썩었군.':'Powietrze się zmieniło. Więcej zgnilizny.',
'여기부터는 악마 영역이야. ...맘대로 해.':'Stąd to terytorium demonów. ...Rób co chcesz.',
'...이 냄새. 살점이 썩는 냄새야.':'...Ten zapach. Gnijące mięso.',
'여기 오래 있으면 미쳐. 나도, 너도.':'Zostaniesz za długo — oszalejesz. Ja też.',
'이 길의 끝에 뭐가 있을까. ...알고 싶지도 않어.':'Co jest na końcu tej drogi? ...Nie chcę wiedzieć.',
'...여기가 끝이야. 돌아갈 길은 없어.':'...To koniec. Nie ma drogi powrotnej.',
// --- Phase 14: idle tips (crow) ---
'작살을 땅에 꽂으면 끌려간다.':'Wbij harpun w ziemię a zostaniesz wciągnięty.',
'Shift로 작살 던져봐!':'Spróbuj rzucić harpunem Shiftem!',
'패링 성공하면 ST가 회복된다. 공짜 자원이야.':'Parowanie przywraca ST. Darmowe zasoby.',
'패링 많이 하면 ST 걱정 없어~':'Paruj często i ST nigdy nie będzie problemem~',
'장비 분해하면 악의를 얻는다. 쓰레기도 자원이야.':'Rozkładanie ekwipunku daje Złość. Nawet śmieci to zasoby.',
'TAB 열어서 안 쓰는 장비 분해해!':'Otwórz TAB i rozłóż nieużywany ekwipunek!',
'그로기 상태의 적에겐 1.5배 데미지가 들어간다.':'Wrogowie w groggy otrzymują 1.5x obrażeń.',
'무릎 꿧으면 전력으로 때려!':'Gdy klękają — bij z całej siły!',
'속성 상성이 있다. 화염은 빙결에 약하고, 암전은 암흑에 약하다.':'Żywioły mają słabości. Ogień słaby na Lód, Błyskawica na Ciemność.',
'무기 속성 바꿔가면서 싸워봐!':'Spróbuj zmieniać żywioł broni podczas walki!',
'빙결된 적은 1.5배 데미지를 받는다.':'Zamrożeni wrogowie otrzymują 1.5x obrażeń.',
'얼리고 때리는 게 기본이야!':'Zamroź i bij — to podstawy!',
'보스의 빨간 공격은 패링 가능. 보라빛은 회피만.':'Czerwone ataki bossa — paruj. Tęczowe — tylko unikaj.',
'색깔 잘 봐! 빨강은 받아치고 무지개는 피해!':'Patrz na kolory! Czerwone — odbij, tęcza — unikaj!',
'VIT를 올리면 최대 HP가 오른다. 죽기 싫으면 찍어.':'VIT podnosi maks. HP. Zainwestuj jeśli chcesz żyć.',
'STR은 근접, DEX는 활, INT는 마법! 골고루 말고 하나만!':'STR dla walki w zwarciu, DEX dla łuków, INT dla magii! Skup się na jednym!',
'E를 꾹 누르면 빔이 나간다. 짧게 누르면 투사체.':'Przytrzymaj E dla lasera. Krótkie wciśnięcie — pocisk.',
'마법 쓸 때 MP 잘 봐! 빔은 연속으로 깎여!':'Pilnuj MP przy magii! Laser szybko zużywa!',
'핵터와 디로이가 아이템을 주워준다. 수거 범위 안이면.':'Hecter i Deroy auto zbierają przedmioty w zasięgu.',
'우리한테 고마워해~ 안 주우면 썩잖아.':'Dziękuj nam~ Przedmioty zgniją jeśli nikt nie zbierze.',
'LCK를 올리면 레어 드롭률이 오른다.':'LCK podnosi szansę rzadkiego dropu.',
'운빨 게임이긴 하지~ LCK 올려봐!':'To gra szczęścia~ Spróbuj podnieść LCK!',
'강화하면 공격력이 쭉쭉 올라가! 악의만 있으면 돼!':'Ulepszenie szybko podnosi ATK! Potrzeba tylko Złości!',
'강화 확률은 +1에서 99%. 높을수록 떨어진다.':'Szansa ulepszenia zaczyna się od 99% przy +1. Spada dalej.',
'실패하면 악의만 날아가~ 장비는 안 부서져!':'Przy niepowodzeniu tylko Złość znika~ Ekwipunek przeżywa!',
'대장간에서 장비 제작도 된다. 악의 30000개면 영웅급 이상.':'Kuźnia może też tworzyć ekwipunek. 30000 Złości na Heroiczny+.',
'랜덤이지만 좋은 거 나올 수도 있어!':'Losowo, ale może wypaść coś świetnego!',
'쉴드는 마법으로, HP는 물리로 깎아야 제대로 먹힌다.':'Tarcza wymaga magii, HP — fizycznego dla skuteczności.',
'반대로 치면 50%만 들어가! 무기 바꿔가면서 싸워!':'Zły typ daje tylko 50%! Zmieniaj broń!',
'장비에 접두사, 접미사가 붙으면 특수 효과가 생긴다.':'Ekwipunek z przedrostkiem/przyrostkiem dostaje specjalne efekty.',
'영웅급 이상 장비에만 붙어! 좋은 거 나오면 강화해!':'Tylko na Heroicznym+ ekwipunku! Ulepszaj dobre!',
'강화는 장비를 바꿔도 자동 이전된다. 악의만 있으면.':'Ulepszenie auto przenosi się na nowy ekwipunek. Tylko Złość potrzebna.',
'더 좋은 장비 나오면 바로 장착해! 강화 수치 그대로 옮겨가!':'Zakładaj lepszy ekwipunek od razu! Ulepszenie się przenosi!',
// --- Phase 14: additional tutorial lines ---
'패링을 써야 자원을 흡수한다고!':'Musisz parować by wchłaniać zasoby!',
'F키 회복의 영역을 써봐. 자원이 차올라.':'Spróbuj klawisza F Święta Domena. Zasoby się uzupełniają.',
'적이 근접하면 스페이스키야! 가시덫을 활용해!':'Gdy wrogowie blisko — Spacja! Używaj Kolczastej Pułapki!',
'기절시켜! 그로기가 터지면 데미지가 1.5배야!':'Ogłusz! Groggy oznacza 1.5x obrażeń!',
'1번 대왕치기로 밀어버려!':'Użyj klawisza 1 Wielkie Uderzenie by odepchnąć!',
'무릎 꿧었다.':'Klęczą.',
'지금이야! 몰아쳐!!':'Teraz! Naciskaj atak!!',
'스킬 포인트 있어! K 눌러서 스킬 찍어봐!':'Masz punkty umiejętności! Wciśnij K by nauczyć!',
'...힘이 없으면 여기서 끝이야.':'...Bez siły — tu koniec.',
'...쓸 거 아니면 분해해.':'...Rozłóż to czego nie potrzebujesz.',
'아이템 넘쳐나네~ 우리가 주워줄게!':'Tyle przedmiotów~ My zbierzemy!',
'악의가 바닥이다.':'Złość wyczerpana.',
'TAB 열어서 장비 분해해! 쓰레기도 악의가 돼!':'Otwórz TAB i rozłóż ekwipunek! Nawet śmieci stają się Złością!',
'좋은 장비가 있네! G 눌러서 대장간 가봐!':'Dobry ekwipunek! Wciśnij G dla kuźni!',
'...강화 안 하면 그냥 고철이야.':'...Bez ulepszenia — tylko złom.',
'...멈추지 마. 여신은 기다리지 않는다.':'...Nie zatrzymuj się. Bogini nie czeka.',
'앞으로 가자~ 나도 여기 오래 있기 싫어.':'Chodźmy~ Ja też nie chcę tu zostawać.',
'...냄새가 짙다. 큰 놈이 있어.':'...Zapach jest silny. Coś dużego tu jest.',
'준비됐어? 물약 확인하고!':'Gotowy? Sprawdź mikstury!',
// --- Phase 14: element names ---
'물리':'Fizyczny','화염':'Ogień',
// --- Phase 15: pet dialogue ---
'TAB을 눌러. 가방을 열고 장비를 입어야 한다.':'Wciśnij TAB. Otwórz torbę i załóż ekwipunek.',
'주웅으면 껴야지! TAB!':'Podniosłeś — zakładaj! TAB!',
'G. 대장간에서 물약도 제작할 수 있다.':'G. W kuźni też można tworzyć mikstury.',
'악의로 물약 만들어! G키야!':'Twórz mikstury ze Złości! Klawisz G!',
'기절이야! Ctrl 눌러!':'Ogłuszony! Wciśnij Ctrl!',
'Ctrl 유령걸음으로 탈출!':'Ctrl Krok Ducha do ucieczki!',
'Ctrl 얼음보주로 탈출!':'Ctrl Lodowa Sfera do ucieczki!',
'빨간 탄은 우클릭 패링. 무지개는 Q 패링.':'Czerwone kule: PPM parowanie. Tęcza: Q parowanie.',
'나머지는 전부 우클릭 패링 가능해!':'Wszystko inne można odbić PPM!',
'빨강=우클릭, 무지개=Q 패링. 나머진 다 쳐내.':'Czerwone=PPM, Tęcza=Q parowanie. Resztę — odbijaj.',
'무지개는 Q로 패링! 나머지는 전부 우클릭!':'Tęcza Q! Wszystko inne — PPM!',
'빠져! 물약 마시고 안전한 곳에서 회복해.':'Wycofaj się! Pij mikstury i odnawiaj się w bezpiecznym miejscu.',
'자원 없으면 도망가는 게 답이야!':'Brak zasobów? Uciekaj!',
'스페이스! 가시덫으로 적 묶어버려!':'Spacja! Zwiąż ich Kolczastą Pułapką!',
'근접이 너무 많아! 거리 벌려!':'Za dużo walki w zwarciu! Zwiększ dystans!',
'...둘러싸이면 끝이야. 빠져나와.':'...Otoczą — koniec. Wyrwij się.',
'1번 대왕치기로 쓸어버려!':'Użyj klawisza 1 Wielkie Uderzenie by zmieść!',
'그로기 터지면 데미지 1.5배!':'Groggy daje 1.5x obrażeń!',
'회전참이나 광역기로 몰아! 한 놈씩 상대하면 죽어.':'Użyj Wichru lub AOE! Jeden na jeden — śmierć.',
'뭉쳐있을 때가 기회야!':'Gdy się skupiają — to twoja szansa!',
'E로 마력공격을 해봐! 악의 쉴드를 해제할려면 마법 공격을 해야 해!':'Spróbuj E dla magicznych ataków! Potrzeba magii by złamać tarczę Złości!',
'쉴드는 마법으로, HP는 물리로. 반대로 치면 데미지 안 들어간다.':'Tarcza — magia, HP — fizyczne. Zły typ nie daje obrażeń.',
'L키로 스킬 슬롯에 넣어야 쓸 수 있어.':'Wciśnij L by przypisać umiejętności do slotów.',
'C키를 눌러. 패시브 포인트가 쌓여있다.':'Wciśnij C. Nakumulowały się pasywne punkty.',
'C키! 패시브 올리면 진짜 강해져!':'Wciśnij C! Pasywne czynią cię znacznie silniejszym!',
'스태미나가 부족하다. 무리하지 마.':'Wytrzymałość niska. Nie przemęczaj się.',
'ST 없으면 스킬 못 써! 잠깐 빠져!':'Brak ST — brak umiejętności! Wycofaj się!',
'탭 장비창을 열어봐. 아이템을 주워왔어!':'Otwórz menu ekwipunku TAB. Zebraliśmy przedmiot!',
'좋은 거 나왔다! TAB 열어서 확인해봐!':'Wypadło coś dobrego! Otwórz TAB by sprawdzić!',
'악의에 중독되면 악마가 돼서 부활력이 생긴대. 저 녀석처럼.':'Mówią że uzależnienie od Złości zamienia w demona z siłą odrodzenia. Jak tamten.',
'혹시 너도...?':'Może ty też...?',
'데미지가 부족하면 무기류 강화를 해야해!!':'Jeśli obrażeń brakuje — ulepszaj broń!!',
'G키 대장간. 강화 안 하면 여기서 계속 죽어.':'Klawisz G — kuźnia. Bez ulepszenia będziesz tu ciągle umierał.',
'시간이 없어. 움직여.':'Brak czasu. Ruszaj się.',
'멍하게 서있으면 안 돼!':'Nie stój tak po prostu!',
'...뭘 기다리는 거야?':'...Na co czekasz?',
'가자가자! 몬스터가 기다려!':'Chodźmy! Potwory czekają!',
'여기 오래 있으면 위험해.':'Zostanie tu zbyt długo jest niebezpieczne.',
'움직여야 해! 가만있으면 둘러싸여!':'Trzeba się ruszać! Stój i zostaniesz otoczony!',
'쉬는 건 죽고 나서 해.':'Odpoczywaj po śmierci.',
'살아있을 때 쉬면 안 돼!':'Nie odpoczywaj gdy żyjesz!',
'적이 몰려오고 있어. 빨리 움직여.':'Wrogowie nadchodzą. Ruszaj szybciej.',
'냄새 맡고 올 거야. 빨리!':'Wywęszą i przyjdą. Szybciej!',
'...아직 살아있는 거 맞지?':'...Jeszcze żyjesz, prawda?',
'혹시 잠든 거야...?':'Zasnąłeś...?',
'...나무가 썩어가고 있어. 여기는 지옥의 입구야.':'...Drzewa gniją. To wejście do piekła.',
'냄새 지독해... 빨리 지나가자.':'Okropny zapach... Przejdźmy szybko.',
'조심해. 벌레굴이다. 벽이랑 바닥에서 기어나와.':'Ostrożnie. Nora robaków. Pełzają ze ścian i podłóg.',
'으으... 벌레 싫어! 밟아버려!':'Ej... Nienawidzę robaków! Depcz je!',
'...공기가 얼어붙는다. 여기선 화염이 먹힌다.':'...Powietrze zamarza. Ogień działa tutaj.',
'추워... 빙결 조심해! 얼면 끝이야.':'Zimno... Uważaj na zamrożenie! Zamarzniesz — koniec.',
'용암이다. 바닥을 밟으면 타 죽어.':'Lawa. Nadepniesz — spłoniesz.',
'뜨거워! 여기 왜 이렇게 빨개!':'Gorąco! Dlaczego tu wszystko takie czerwone!',
'...군단이다. 수가 많아. 광역기 없으면 밀려.':'...Legion. Jest ich za dużo. Bez AOE zostaniesz przytłoczony.',
'우글우글... 징그러워. 한꺼번에 쓸어!':'Roją się... Obrzydliwe. Zmieć wszystkich naraz!',
'사도의 영역이야. 여기 놈들은 머리가 좋아.':'Terytorium apostołów. Ci są mądrzy.',
'패턴이 복잡해졌어... 집중해!':'Wzorce się skomplikowały... Skup się!',
'...끝이다. 지옥의 심장부. 살아 돌아가는 건 포기해라.':'...Oto jest. Serce piekła. Porzuć nadzieję na powrót żywym.',
'여기가 마지막이야... 각오해.':'To ostatnie... Szykuj się.',
'닫기':'Zamknij','장착 중':'Założone','보관 아이템':'Przechowywany Przedmiot',
'🔨 제작':'🔨 Wytwarza',
'분해할 아이템이 없습니다.':'Brak przedmiotów do rozłożenia.',
'스킬 미습득':'Brak wyuczonych umiejętności',
'석궁 자동발사 (T)':'Kusza automatyczna (T)',
'버스트루프 당기기 (H)':'Pętla wybuchu przyciąganie (H)',
'결정 자동합성':'Kryształ auto-synteza',
'결정 자동강화':'Kryształ auto-wzmocnienie',
'✓ 설정 자동 저장':'✓ Ustawienia zapisane automatycznie',
'세팅 프리셋 저장/불러오기':'Zapisz/wczytaj ustawienie wstępne',
'세팅1 저장':'Zapisz Ustawienie 1','세팅1':'Ustawienie 1',
'세팅2 저장':'Zapisz Ustawienie 2','세팅2':'Ustawienie 2',
'재진단':'Ponowna diagnostyka',
'게임 리셋 (처음부터)':'Resetuj grę (od początku)',
'캐릭터 선택 (로비)':'Wybór postaci (Lobby)',
'닫기 [ESC]':'Zamknij [ESC]','닫기 [G]':'Zamknij [G]','닫기 [V]':'Zamknij [V]','닫기 [C]':'Zamknij [C]',
'전체화면 (F11)':'Pełny ekran (F11)',
'정말 모든 진행을 초기화하시겠습니까?':'Na pewno chcesz zresetować wszystkie postępy?',
'검출 중...':'Wykrywanie...',
'마우스 커서':'Kursor myszy','그래픽 품질':'Jakość grafiki','하드웨어 진단':'Diagnostyka sprzętu',
'BGM 선택':'Wybór BGM',
'자동 (스테이지별)':'Automatyczny (wg etapu)','전체 랜덤':'Wszystko losowo','로비':'Lobby',
'1장 랜덤':'Rozdz. 1 losowo','2장 랜덤':'Rozdz. 2 losowo','3장 랜덤':'Rozdz. 3 losowo',
'4장 랜덤':'Rozdz. 4 losowo','5장 랜덤':'Rozdz. 5 losowo','6장 랜덤':'Rozdz. 6 losowo','7장 랜덤':'Rozdz. 7 losowo',
'보스':'Szef','최종보스':'Końcowy szef',
'대장간 랜덤':'Kuźnia losowo','사망 랜덤':'Śmierć losowo','승리 랜덤':'Zwycięstwo losowo',
'지옥 추락 사망 징글':'Dżingiel śmierci w piekle','탈출 성공':'Ucieczka udana',
'── 1장 - 썩은 숲 ──':'── CH1 - Rotten Forest ──','── 2장 - 벌레굴 ──':'── CH2 - Worm Nest ──',
'── 3장 - 얼음굴 ──':'── CH3 - Ice Cavern ──','── 4장 - 화염지대 ──':'── CH4 - Infernal Wastes ──',
'── 5장 - 지옥군단 ──':'── CH5 - Hell Legion ──','── 6장 - 사도마굴 ──':'── CH6 - Apostle Den ──',
'── 7장 - 지옥성 ──':'── CH7 - Hell Citadel ──','── 공통 ──':'── Common ──',
'⌨ 조작법':'⌨ Sterowanie','클릭하면 닫힘':'Kliknij aby zamknąć',
'전투력':'PS','가방':'Torba','결정':'Kryształ',
'↕ 정렬':'↕ Sortuj','쓰레기 전체선택':'Zaznacz cały złom','쓰레기 전부 분해':'Rozmontuj cały złom',
'창고':'Magazyn','스탯 포인트':'Punkty atrybutu','능력치 요약':'Podsumowanie statystyk','올 리셋':'Resetuj wszystko',
'대장간':'Kuźnia','스킬':'Umiejętności','능력치':'Atrybuty',
'좌클스킬 (클릭 전환)':'Umiej. LPM (klik aby zmienić)','우클스킬 (클릭 전환)':'Umiej. PPM (klik aby zmienić)',
'이동스킬 (클릭 전환)':'Umiej. ruchu (klik aby zmienić)','마법스킬 (클릭 전환)':'Umiej. magii (klik aby zmienić)',
'영역스킬 (클릭 전환)':'Umiej. obszaru (klik aby zmienić)','피보호막 (클릭 전환)':'Tarcza krwi (klik aby zmienić)',
'CT스킬 (클릭 전환)':'Umiej. CT (klik aby zmienić)','[C] 능력치':'[C] Atrybuty',
'무기 공격':'Atak bronią','칼등 처내기 (투사체 반사, 홀드 연사)':'Parowanie (odbija pociski, trzymaj=salwa)',
'연속 처내기':'Ciągłe parowanie','영역 스킬 (폭풍소환 등)':'Umiej. obszaru (Wir itp)',
'작살 발사':'Strzał harpunem','마법 (탭=투사체, 홀드=빔)':'Magia (tap=pocisk, trzymaj=promień)',
'데빌포스 흡수':'Wchłoń Siłę Diabła','물약 / 스킬슬롯':'Mikstury / Sloty umiejętności',
'스킬슬롯 5 / 필살기 / CT스킬':'Slot 5 / Ulti / Umiej. CT','스킬 슬롯 배정':'Przypisanie slotu',
'무릎 꿇으면 전력으로 때려!':'Kiedy klękają, bij z całej siły!',
'무릎 꿇었다.':'Klęka.',
'주웠으면 껴야지! TAB!':'Podniosłeś? Załóż! TAB!',
// --- Phase 27 additions ---
'위로 이동':'Ruch w górę','아래로 이동':'Ruch w dół','왼쪽 이동':'Ruch w lewo','오른쪽 이동':'Ruch w prawo',
'칼등 처내기 (탭=처내기, 홀드=연사)':'Parowanie (tap=paruj, trzymaj=salwa)',
'영역 스킬':'Umiejętność obszaru','작살 이동':'Skok harpunem',
'유령불꽃 켜기/끄기':'Duch Płomień Wł/Wył','기동칼날개 자동 켜기/끄기':'Auto-Ostrze Wł/Wył',
'해상도':'Rozdzielczość',
'빛이 꺼졌다':'Światło gaśnie','누군가는 너를 기다리고 있다':'Ktoś na ciebie czeka',
'다시 일어서라':'Wstań ponownie','로비로 돌아가기':'Powrót do lobby',
'☠ 사망 리플레이':'☠ Replay śmierci',
'지옥의 시련을 견뎌냈다':'Przetrwałeś próbę piekła','계속 전투':'Kontynuuj walkę',
'난이도를 선택하라':'Wybierz trudność',
'나중에 설정(ESC)에서 변경 가능':'Można zmienić później w Ustawieniach (ESC)',
'일괄합성':'Masowa fuzja','일괄강화+합성':'Masowe ulepszenie+fuzja',
'자원 부족!':'Brak zasobów!',' 뎀':' DMG',
'합체 폭발!':'Eksplozja fuzji!','MP 부족! (50)':'MP za mało! (50)',
'부활력 고갈!':'Wyczerpano Odrodzenie!','☠ 부활력 고갈!':'☠ Wyczerpano Odrodzenie!',
'독안개':'Trująca Mgła','뇌전창':'Włócznia Pioruna',
'🔥 업화선 시전...':'🔥 Rzucanie Smugi Piekła...',
'💥 기동파괴 그로기!':'💥 Groggy Łańcuchowego Zniszczenia!',
'💥 칼등 그로기!':'💥 Groggy Parowania!',
'⚡ 순간이동 준비!':'⚡ Teleport Gotowy!',
'👿악의+1000':'👿Złość+1000',
'💀 내려찍기!':'💀 Miażdżenie!',
'✟ 신성력 억제! +':'✟ Wstrzymano Siłę Świętą! +',
'✟ 신성력 억제!':'✟ Wstrzymano Siłę Świętą!',
'✟ 신성력 억제! (':'✟ Wstrzymano Siłę Świętą! (',
'💥 지진그로기!':'💥 Groggy Trzęsienia!',
'💥 기폭그로기!':'💥 Groggy Eksplozji!',
'폭발! ×':'Eksplozja! ×',
'⚫ 기둥강타!':'⚫ Uderzenie Filarem!',
'💥 대왕치기 그로기!':'💥 Groggy Kolosa!',
'💫 미니스턴!':'💫 Mini Ogłuszenie!',
'⚡ 뇌전창!':'⚡ Włócznia Pioruna!',
'…절반이다. 정신차려.':'…Połowa zdrowia. Skupiaj się.',
'…죽기 직전이다. 한 발만 더.':'…Prawie martwi. Jeszcze jeden cios.',
'…다음 한 방이 마지막이야.':'…Następny cios będzie ostatni.',
'기절! ':'Ogłuszony! ',
'마력이 빈다. 평타 섞어.':'MP się kończy. Mieszaj ze zwykłymi.',
'그랩이다. 거리를 둬.':'Chwyt. Zachowaj dystans.',
'광역기다. 멀어져.':'Atak obszarowy. Oddal się.',
'…아파? 당연하지. 여긴 지옥이야.':'…Boli? Oczywiście. To jest piekło.',
'F키도 스킬 슬롯이야!':'Klawisz F to też slot!',
'L-CTRL로 유령걸음/얼음보주!':'L-CTRL na Krok Ducha/Lodową Sferę!',
'V 눌러서 창고에 넣어둬!':'Wciśnij V by odłożyć do magazynu!',
'ESC로 설정! 난이도/자동물약!':'ESC dla ustawień! Trudność/Auto-mikstury!',
'잡몹이다. 먼저 정리해.':'Zwykłe potwory. Najpierw wyczyść.',
'…얼어붙은 놈은 오래 안 간다.':'…Zamrożony nie przetrwa długo.',
'…냄새가 짙다. 큰 놈이 있어.':'…Mocny zapach. Coś dużego w pobliżu.',
'쉴드는 마법으로, HP는 물리로.':'Tarcza bierze magię, HP bierze fizyczne.',
'스페이스! 가시덫으로 적 묶어!':'Space! Zwiąż wrogów Kolczastą Pułapką!',
'근접 너무 많아! 거리 벌려!':'Za dużo wrogów w zwarciu! Rozejdź się!',
'회전참이나 광역기로 몰아!':'Użyj Wirującego Cięcia lub AOE!',
'F 눌러! 회복의 영역 깔아!':'F! Rozłóż Świętą Domenę!',
'F키 회복의 영역을 써봐.':'Spróbuj F-key Świętej Domeny.',
'빠져! 물약 마시고 회복해.':'Odskocz! Wypij miksturę i wylecz się.',
'쉬프트! 사슬기동은 이동기야!':'Shift! Skok łańcuchowy to ruch!',
'스킬포인트 쌓였어! K 눌러!':'Punkty umiejętności się zebrały! Wciśnij K!',
'스킬 포인트 있어! K!':'Masz punkty umiejętności! K!',
'C키. 패시브 포인트가 쌓여있다.':'Klawisz C. Punkty pasywne czekają.',
'…쓸 거 아니면 분해해.':'…Rozłóż to co niepotrzebne.',
'…강화 안 하면 그냥 고철이야.':'…Bez ulepszenia to tylko złom.',
'빨간 탄은 우클릭. 무지개는 Q.':'Czerwone kule: PPM. Tęcza: Q.',
'빨강=우클릭, 무지개=Q.':'Czerwone=PPM, tęcza=Q.',
'…멈추지 마. 여신은 기다리지 않는다.':'…Nie zatrzymuj się. Bogini nie czeka.',
'패턴이 바뀐다. 거리를 둬.':'Wzorzec się zmienia. Zachowaj dystans.',
'미쳐가고 있어. 광폭화다.':'Szaleje. Wściekłość.',
'마지막이야! 끝장내!':'Ostatnia faza! Dobij go!',
'…끝났다. 다음으로.':'…To koniec. Dalej.',
'다 잡았다! 포탈 어딨어?':'Wszystko zabite! Gdzie portal?',
'근육으로 만든 빌드군. 베고 부숴.':'Zbudowany na mięśniach. Tnij i miażdż.',
'활을 쥐었군. 거리를 둬.':'Ma łuk. Zachowaj dystans.',
'마법사군. MP 관리부터 배워라.':'Czarodziej. Najpierw naucz się zarządzać MP.',
'운에 기댄 빌드군. …드롭은 좋겠어.':'Oparto na szczęście. …Chociaż looty będą fajne.',
'…VIT가 너무 낮아. 한 방에 죽는다.':'…VIT za niskie. Zginiasz od jednego ciosu.',
'다 찍으면 다 약해진다. 하나만 골라.':'Maksuj wszystko i wszędzie słabniesz. Wybierz jedno.',
'…3단. 적이 강해져. 정신 차려.':'…Etap 3. Wrogowie mocniejsi. Skupiaj się.',
'5단이다. …너도 강해졌단 뜻이야.':'Etap 5. …To znaczy że też się wzmocniłeś.',
'…7단. 아직 살아있단 게 신기하군.':'…Etap 7. Ciągle żyjesz. Zdumiewające.',
'10단. …너는 이제 인간이 아니야.':'Etap 10. …Już nie jesteś człowiekiem.',
'…일반으로 내려왔군. 가끔은 쉬어가야지.':'…Spadłeś do Normalnego. Czasem trzeba odpocząć.',
'…이게 진짜 패링이야.':'…To jest prawdziwe parowanie.',
'…피가 묻기 시작했군.':'…Krew zaczyna się przelewa.',
'100. 너는 인간이 아니야.':'100. Nie jesteś człowiekiem.',
'…피 흘리며 베는군.':'…Tniesz przez krew.',
'빨간콩이 푸르게 변했다. 그게 너의 무기야.':'Czerwona kula stała się niebieska. To twoja broń.',
'무지개를 받아쳤군. 그건 진짜 어렵다.':'Odbiłeś tęczę. To naprawdę trudne.',
'…너무 빨라. 닿기 직전에 눌러.':'…Za szybko. Wciśnij tuż przed kontaktem.',
'악의가 가득 찼다. 풀어내.':'Złość jest pełna. Uwolnij.',
'작살이 살을 뚫었어. 끌고 와.':'Harpun przebił ciało. Przyciągnij go.',
'…풀차지군. 멀리 던져버려.':'…Pełne naładowanie. Rzuć daleko.',
'…빈틈을 그대로 빠져나갔다.':'…Wyślizgnął się przez lukę.',
'…일반 잡몹이 아니야. 모디파이어 붙었군.':'…Nie zwykły potwór. Ma modyfikator.',
'엘리트 하나 처리.':'Elita pokonana.',
'…큰 놈이다. 일반 잡몹 정리부터.':'…Duży jeden. Najpierw wyczyść zwykłe.',
'미니보스 처리. 다음 길로.':'Mini-boss pokonany. Dalej.',
'한 번에 다섯. 깔끔해.':'Pięć naraz. Schludnie.',
'100강. 이제 뭔가 다르게 보이는군.':'+100. Teraz wszystko wygląda inaczej.',
'…운이 없는 날이야.':'…Pechowy dzień.',
'…전설이다. 이런 건 처음 본다.':'…Legendarny. Pierwszy raz coś takiego.',
'…죽었다 살아났네. 여신은 너를 포기 안 했어.':'…Umarłeś i wróciłeś. Bogini cię nie porzuciła.',
'…또야? 패턴 좀 외워!':'…Znowu? Naucz się wzorca!',
'…한 번도 안 죽고. 그건 진짜 실력이야.':'…Ani razu nie zginąłeś. To prawdziwa umiejętność.',
'…ACT1을 끝냈다. 진짜 시작은 여기서부터야.':'…Koniec AKTU1. Prawdziwy początek tu się zaczyna.',
'모든 보스를 무너뜨렸다. 너는 지옥의 일부야.':'Wszyscy bossowie pokonani. Jesteś częścią piekła.',
'…30초. 너 진짜 미쳤구나.':'…30 sekund. Naprawdę oszalałeś.',
'…빠르군. 효율적이야.':'…Szybko. Efektywnie.',
'신기록이다.':'Nowy rekord.',
'탭 장비창을 열어봐.':'Otwórz okno ekwipunku przez TAB.',
'데미지 부족하면 무기 강화!':'Za mało obrażeń? Ulepsz broń!',
// --- Loading screen ---
'불러오는 중...':'Wczytywanie...',
'로딩중...':'Ładowanie...',
'맵과 몬스터 불러오는 중...':'Wczytywanie mapy i potworów...',
'기본 데이터 준비 중...':'Przygotowanie podstawowych danych...',
'저장 데이터 불러오는 중...':'Wczytywanie danych zapisu...',
'몬스터 스킨 로딩...':'Ładowanie skinów potworów...',
'맵과 몬스터 생성 중...':'Generowanie mapy i potworów...',
'맵 에셋 로딩...':'Ładowanie zasobów mapy...',
'맵 환경 준비 중...':'Przygotowanie środowiska mapy...',
'주변 청크 준비 중...':'Przygotowanie pobliskich chunków...',
'맵 캐시 생성 중...':'Budowanie pamięci podręcznej mapy...',
'미니맵 빌드 중...':'Budowanie minimapy...',
// Phase 28
' 으로 탈출!':' — do ucieczki!',
'100명?! 미쳤어!':'100 zabójstw?! Szaleństwo!',
'10단 최고난이도! 너 진짜 광기야!':'Trudność 10 maks! Kompletny wariat!',
'1분 안에 클리어! 빠르네!':'Etap w 1 min! Jak szybko!',
'30초!! 스피드런 가능해!':'30 sekund!! Potencjał speedruna!',
'3단! 보상도 좋아지지만 죽기 쉬워!':'Trudność 3! Lepsze nagrody, ale łatwiej zginąć!',
'50명! 학살자야!':'50 zabójstw! Rzeźnik!',
'5단!! 진짜 게이머 인증!':'Trudność 5!! Prawdziwy gracz potwierdzony!',
'7단!! 다른 사람들 이 정도 못 와!':'Trudność 7!! Inni tak daleko nie dochodzą!',
'ACT1 완주! 우리가 진짜 해냈어!':'AKT 1 ukończony! Naprawdę to zrobiliśmy!',
'Ctrl 얼음보주로 탈출하라.':'Ctrl — uciekaj Lodową Kulą.',
'Ctrl 유령걸음으로 탈출하라.':'Ctrl — uciekaj Krokiem Ducha.',
'C키! 패시브 강해져!':'Klawisz C! Pasywne stają się silniejsze!',
'DEX 빌드! 거리에서 패고, 추적탄 좋아!':'Build DEX! Ataki z dystansu, pociski śledzące!',
'E로 마력공격을 해봐!':'Spróbuj magicznego ataku klawiszem E!',
'G 눌러서 대장간 가봐!':'Naciśnij G — kuźnia!',
'G키 대장간. 강화 안 하면 계속 죽어.':'G — kuźnia. Brak ulepszeń, ciągła śmierć.',
'HP 70%! 조심해!':'HP 70%! Uważaj!',
'INT 빌드! 빔이랑 폭발 마법! MP 잘 봐!':'Build INT! Wiązki i eksplozywna magia! Pilnuj MP!',
'LCK 높아! 레어 드롭률 미친 거 알지?':'Wysokie LCK! Szanse dropu rzadkości są szalone!',
'L로 어디에 뭘 넣을지 골라!':'Naciśnij L — wybierz układ slotów umiejętności!',
'MP 부족! 평타로 패면서 회복해!':'MP mało! Bij zwykłymi atakami, by odzyskać!',
'ST 없으면 스킬 못 써!':'Brak ST — brak umiejętności!',
'STR 빌드! 회전참, 회오리, 광역기 추천!':'Build STR! Wirujący cios, wicher, AoE!',
'VIT 좀 찍어! HP 너무 적어!':'Dodaj VIT! HP zbyt niskie!',
'Z 누르면 대박! 쿨타임 길어!':'Naciśnij Z dla ulti! Długi czas odnowienia!',
'…고기 냄새. 싫진 않네.':'…Zapach krwi. Nieźle.',
'…둘러싸이면 끝이야.':'…Otoczony oznacza koniec.',
'…말은 못해.':'…Nie mogę mówić.',
'…버리기 아까운 건 창고에.':'…Cenne rzeczy do magazynu.',
'…빈틈을 노려.':'…Czekaj na otwarte.',
'…설정을 확인해.':'…Sprawdź ustawienia.',
'…슬롯을 채워. 빈 손은 죽음이다.':'…Wypełnij sloty. Puste ręce to śmierć.',
'…아직 살아있네. 좌클릭으로 저것들 쳐봐.':'…Jeszcze żywy. Lewy klik, by ich uderzyć.',
'…운이 좋았을 뿐이야. 아마.':'…Po prostu szczęście. Chyba.',
'…치는 건 할 줄 아네. 피하는 건?':'…Uderzyć potrafisz. A unikać?',
'…힘을 골라라. 전부 가질 순 없다.':'…Wybierz swoją siłę. Nie możesz mieć wszystkiego.',
'골고루 안 돼! 하나로 밀어!':'Nie rozpraszaj! Skup na jednym!',
'그로기 터지면 1.5배!':'Groggy = 1,5x obrażeń!',
'길이 열렸다.':'Droga otwarta.',
'나머진 전부 우클릭 패링 가능!':'Reszta — paruj prawym klikiem!',
'나머진 전부 우클릭!':'Reszta — prawy klik!',
'다섯 번 연속! 내가 본 인간 중 최고!':'Pięć z rzędu! Najlepszy, jakiego widziałem!',
'다음엔 죽지 마!':'Następnym razem nie giń!',
'더블탭 전격이동으로 탈출하라.':'Podwójne tapnięcie — skok do ucieczki.',
'소환수 왔어! 먼저 처리해야 해!':'Przywołańcy! Najpierw się z nimi rozpraw!',
'스킬 없으면 방향키 연타뿐이야.':'Brak umiejętności? Po prostu spamuj strzałkami.',
'신기록!! 스트리머한테 보내!':'Nowy rekord!! Wyślij streamerowi!',
'아이템 넘쳐! 우리가 주워줄게!':'Torba pełna! Zbierzemy dla ciebie!',
'안 죽고 깼어! 진짜 천재 맞네!':'Ukończono bez śmierci! Prawdziwy geniusz!',
'앞으로 가자~':'Ruszajmy naprzód~',
'우리가 해냈어! 다음 챕터 가자!':'Zrobiliśmy to! Następny rozdział!',
'일반 모드! 편하게 즐기자!':'Tryb normalny! Ciesz się spokojnie!',
'자원이 반이다. F키로 회복해.':'Zasoby na połowie. Naciśnij F, by odzyskać.',
'잡힌다! 옆으로 빠져!':'Łapią! Uchyl się w bok!',
'장비 분해해! 쓰레기도 악의!':'Rozkładaj ekwipunek! Śmieci też dają złośliwość!',
'전부 다 잡았어! 우리가 지옥의 왕이야!':'Wszystko wyczyszczone! Królowie piekła!',
'좋은 거 나왔다! TAB!':'Dobry łup! TAB!',
'죽기 직전에 죽이다니! 멋져!':'Zabił tuż przed śmiercią! Niesamowite!',
'체력 반 남았어! 물약 마실 타이밍!':'Połowa HP! Czas na miksturę!',
'큰 거 온다! 도망쳐!':'Duży atak! Uciekaj!',
'패링으로 돌려주고, Q 보호막도 써!':'Paruj i odbijaj, użyj tarczy Q!',
'패턴이 빨라졌어!':'Wzorce szybsze!',
'한 대만 맞아도 죽어! 패링이든 회피든!!':'Jeden hit = śmierć! Paruj lub unikaj!!',
'한 방이면 죽어! 도망쳐!!':'Jeden strzał zabija! Uciekaj!!',
'화염엔 빙결! 암전엔 암흑!':'Ogień → mróz! Pustka → cień!',
'── 2장 - 벌레굴 ──':'── CH2 - Worm Nest ──',
'── 4장 - 화염지대 ──':'── CH4 - Infernal Wastes ──',
'── 6장 - 사도마굴 ──':'── CH6 - Apostle Den ──',
'── 공통 ──':'── Common ──',
'☠ 부활력 고갈!':'☠ Wskrzeszenie Wyczerpane!',
'⏳⚡ 시간걸음!':'⏳⚡ Krok Czasu!',
};

_PL_PFX={
'녹슨':'Zardzewiały','강철':'Stalowy','흑요석':'Obsydianowy','미스릴':'Mithrylowy','심판의':'Sądu','천벌의':'Boskiego Gniewu','파멸의':'Zagłady',
'불꽃':'Płomienny','화염':'Piekielny','염화':'Ogniowy','지옥불':'Piekłoogień','지옥화':'Piekłoogień','지옥':'Piekłoogień','멸화의':'Unicestwiający',
'냉기':'Mroźny','빙결':'Zamrożony','빙하':'Lodowcowy','서리의':'Szronowy','서리':'Szronowy','영겁빙':'Wiecznie Lodowy',
'그림자':'Cienisty','암흑':'Ciemny','심연':'Otchłanny','나락의':'Podziemny','나락':'Podziemny','무간의':'Próżniowy',
'전기':'Iskrowy','낙뢰':'Gromowy','암전':'Błyskawicowy','뇌신의':'Boga Burzy','뇌신':'Boga Burzy','만뢰의':'Tysiącgromowy',
'축복':'Błogosławiony','성광':'Świętoluministy','신성':'Sakralny','천사의':'Anielski','신벌의':'Bosko-sądowy',
'낡은':'Zużyty','천':'Tkaninowy','가죽':'Skórzany','강철사':'Stalowotkaniny','은':'Srebrny','은사':'Srebrnoniciowy','화염의':'Piekielny','빙결의':'Zamrożony','암흑의':'Ciemny','암전의':'Błyskawicowy'
};
const _PL_PFX={
'녹슨':'Zardzewiały','강철':'Stalowy','흑요석':'Obsydianowy','미스릴':'Mithrylowy','심판의':'Sądu','천벌의':'Boskiego Gniewu','파멸의':'Zgubny',
'불꽃':'Płomienny','화염':'Ogień','염화':'Ogniowy','지옥불':'Piekłoogień','지옥화':'Piekłoogień','지옥':'Piekło','멸화의':'Unicestwiający',
'냉기':'Mroźny','빙결':'Lód','빙하':'Lodowcowy','서리의':'Szronowy','서리':'Szronowy','영겁빙':'Wiecznie Lodowy',
'그림자':'Cienisty','암흑':'Ciemność','심연':'Otchłanny','나락의':'Podziemny','나락':'Podziemny','무간의':'Próżniowy',
'전기':'Iskrowy','낙뢰':'Grzmot','암전':'Błyskawica','뇌신의':'Boga Burzy','뇌신':'Boga Burzy','만뢰의':'Tysiącgromowy',
'축복':'Błogosławiony','성광':'Świętoluministy','신성':'Święty','천사의':'Anielski','신벌의':'Bosko-sądowy',
'낡은':'Zużyty','천':'Tkaninowy','가죽':'Skórzany','강철사':'Stalowotkaniny','은':'Srebrny','은사':'Srebrnoniciowy',
'화염의':'Piekielny','빙결의':'Zamrożony','암흑의':'Przeklęty','암전의':'Błyskawicowy'};
const _PL_BASE={
'대검':'Dwuręcznik','석궁':'Kusza','연사석궁':'Repetier','마력석궁':'Arkanowa Kusza',
'견갑':'Tarcza','대견갑':'Wielka Tarcza','전투화':'Buty Bojowe','갑옷':'Zbroja','갑주':'Zbroja',
'왕관':'Korona','장갑':'Rękawice','건틀릿':'Rękawice Pancerne','바지':'Spodnie','각반':'Nagolenniki',
'허리띠':'Pas','벨트':'Pas','부적':'Talizman','목걸이':'Naszyjnik','반지':'Pierścień',
'망토':'Peleryna','팔찌':'Bransoletka','귀걸이':'Kolczyk'
};
