// 지옥의 길 — Italiano (it)
const _IT={
'썩은 숲':'Foresta Marcia',
'숲의 감시자':'Guardiano della Foresta',
'독버섯 거인':'Gigante Fungo Tossico',
'숲의 사냥꾼':'Cacciatore della Foresta',
'숲의 기생수':'Bestia Parassita',
'1장 — 썩은 숲':'CAP1 — Foresta Marcia',
'2장 — 벌레굴':'CAP2 — Nido di Vermi',
'3장 — 얼음굴':'CAP3 — Caverna di Ghiaccio',
'4장 — 고통의 화염지대':'CAP4 — Landa Infernale',
'5장 — 지옥의 군단':'CAP5 — Legione Infernale',
'6장 — 사도의 마굴':'CAP6 — Tana dell\'Apostolo',
'7장 — 지옥성':'CAP7 — Cittadella Infernale',
'탈출!':'Fuggito!',
'처치':'Uccisioni',
'경험치':'ESP',
'최대콤보':'Combo Max',
'일어나. 여신이 널 여기 보낸 건 죽으라고가 아니야.':'Svegliati. La dea non ti ha mandato qui per morire.',
'좋아, 감각이 있군. 계속 쳐!':'Bene, hai istinto. Continua a colpire!',
'Shift를 눌러. 작살이다. 땅에 꽂아서 끌려가!':'Premi Shift. È il rampone. Conficcalo e fatti trascinare!',
'작살로 끌려가는 중엔 무적이다. 위험할 때 쓰면 좋아.':'Sei invincibile mentre il rampone ti trascina. Usalo nei momenti critici.',
'...아파? 당연하지. 여긴 지옥이야.':'...Fa male? Ovvio. Questo è l\'inferno.',
'Q를 눌러! 악의로 보호막을 만들 수 있다.':'Premi Q! Crea uno scudo con la malizia.',
'보호막 없이 버틸 생각은 버려.':'Scordati di sopravvivere senza scudo.',
'우클릭이 패링이다. 적 공격이 닿기 직전에 눌러!':'Clic destro per parare. Appena prima che il nemico colpisca!',
'못 하겠으면 때려. 안 죽으면 그만이야.':'Non riesci? Colpisci. L\'importante è non morire.',
'됐어! 감 잡았구나.':'Ecco! Stai capendo.',
'하나 죽었군.':'Uno in meno.',
'유령쇠뇌야. 인사해.':'È la balestra fantasma. Salutala.',
'빨간 탄을 무서워하지 마. 악의가 강하다.':'Non temere i proiettili rossi. La malizia è forte.',
'패링으로 돌려주고, Q 보호막도 써! 악의를 잘 굴려!':'Respingili con la parata e usa lo scudo Q! Gestisci la malizia!',
'무지개빛은 패링 불가! 피해!':'I colpi arcobaleno non si parano! Schiva!',
'피가 새고 있다. Shift. 빠져.':'Stai sanguinando. Shift. Scappa.',
'물약 있잖아! 숫자키!':'Hai pozioni! Tasti numerici!',
'우클릭. 적 손목이 꺾일 때 쳐.':'Clic destro. Colpisci quando il polso si piega.',
'빨간 탄은 악의 덩어리다. 쳐내서 이용해.':'I proiettili rossi sono blocchi di malizia. Deviali e usali.',
'무지개빛만 피하면 돼! 나머지는 다 패링!':'Schiva solo l\'arcobaleno! Para tutto il resto!',
'Q 보호막도 패링이 가능해!':'Lo scudo Q può anche parare!',
'위험해! 쉬프트 사슬기동으로 피해!!':'Pericolo! Shift catena per fuggire!!',
'쉬프트! 사슬기동은 이동기야! 끌려가면서 무적이라고!':'Shift! La catena è movimento! Invincibile mentre ti trascina!',
'스킬포인트가 쌓였어! K 눌러서 스킬 배우자!':'Punti abilità pronti! Premi K!',
'속성을 읽어. 약점을 찌르면 두 배로 썩는다.':'Leggi gli elementi. Colpire debolezze fa il doppio danno.',
'K를 눌러봐! 스킬을 배울 수 있어!':'Premi K! Puoi imparare abilità!',
'C 눌러서 능력치 찍어! 패시브도 있어~':'Premi C per le stats! Anche i passivi~',
'G를 눌러. 대장간에서 장비를 강화할 수 있다.':'Premi G. Potenzia l\'equipaggiamento alla forgia.',
'F키도 스킬 슬롯이야! 스킬 많으면 L로 배정해봐~':'Anche F è uno slot! Usa L per assegnare~',
'Z. 필살기다. 아껴 써라.':'Z. La tua mossa finale. Usala con saggezza.',
'L-CTRL로 유령걸음이나 얼음보주 쓸 수 있어!':'L-CTRL per Passo Fantasma o Sfera di Ghiaccio!',
'L을 눌러. 스킬 슬롯을 정리해야 한다.':'Premi L. Organizza gli slot.',
'가방 터지겠다! V 눌러서 창고에 넣어둬!':'Lo zaino sta esplodendo! Premi V!',
'ESC로 설정 열 수 있어! 난이도 바꾸기, 자동물약 조절~':'ESC per le impostazioni! Difficoltà, pozioni auto~',
'...아직 살아있네. 좌클릭으로 저것들 쳐봐.':'...Ancora vivo. Colpiscili con clic sinistro.',
'...치는 건 할 줄 아네. 피하는 건?':'...Sai colpire. E schivare?',
'흥, 작살 못 맞추면 헛수고야.':'Hmph, manca il rampone e sprechi tutto.',
'...운이 좋았을 뿐이야. 아마.':'...Solo fortuna. Probabilmente.',
'...고기 냄새. 싫진 않네.':'...Odore di carne. Non male.',
'...말은 못해.':'...Non può parlare.',
'예쁘다고 만지면 죽어.':'Li tocchi perché sono belli? Morirai.',
'작살 던져! 끌려가면 무적이야!':'Lancia il rampone! Invincibile mentre ti trascinano!',
'...마시든 말든. 네 목숨이니까.':'...Bevi o no. È la tua vita.',
'그게 패링이야! 타이밍이 전부야~':'Quella è una parata! Il tempismo è tutto~',
'화염엔 빙결! 암전엔 암흑! 기억해!':'Fuoco vs Ghiaccio! Fulmine vs Oscurità! Ricorda!',
'...얼어붙은 놈은 오래 안 간다.':'...I congelati non durano.',
'얼었어! 빙결 중 1.5배야!':'Congelato! 1.5x danni!',
'...힘을 골라라. 전부 가질 순 없다.':'...Scegli il tuo potere. Non puoi avere tutto.',
'스탯을 올려. 살고 싶으면.':'Alza le stats. Se vuoi vivere.',
'좋은 장비는 강화해야 진짜 힘을 발휘해!':'L\'equipaggiamento buono va potenziato!',
'...슬롯을 채워. 빈 손은 죽음이다.':'...Riempi gli slot. Mani vuote = morte.',
'Z 누르면 대박! 쿨타임 길어서 타이밍 봐야 해!':'Z per danni enormi! Lungo cooldown, tempismo!',
'Ctrl. 위기에 쓸 카드가 하나 늘었군.':'Ctrl. Una carta in più per le emergenze.',
'스킬이 많아졌네~ L로 어디에 뭘 넣을지 골라!':'Tante abilità~ Usa L per assegnare!',
'...버리기 아까운 건 창고에.':'...Metti nel deposito ciò che vale.',
'...살아남은 것만으로도 대단하군. 설정을 확인해.':'...Sopravvivere è già impressionante. Controlla le impostazioni.',
'MP 부족!':'MP insufficiente!',
'ST 부족!':'ST insufficiente!',
'악의 부족!':'Malizia insufficiente!',
'충전 중...':'Caricamento...',
'캔슬':'Annulla',
'아이템 선택 필요':'Seleziona un oggetto',
'악의 소진...':'Malizia esaurita...',
'비문 발견...':'Iscrizione trovata...',
'HP물약!':'Pozione HP!',
'HP물약 +1':'Pozione HP +1',
'HP물약 +2':'Pozione HP +2',
'HP/MP/ST 회복!':'HP/MP/ST ripristinato!',
'보물상자 개봉!':'Forziere aperto!',
'익사!':'Annegamento!',
'피웅덩이!':'Pozza di sangue!',
'독혈!':'Sangue tossico!',
'잡힘!':'Afferrato!',
'콤보 종료':'Fine combo',
'빙결!':'Congelato!',
'화상!':'Bruciatura!',
'독!':'Veleno!',
'감전!':'Folgorato!',
'기절!':'Stordito!',
'봉인됨!':'Sigillato!',
'관통!':'Penetrazione!',
'기검참':'Fendente Ki',
'악의구':'Sfera Malizia',
'회전참':'Turbine',
'기폭팔':'Detonazione',
'칼등 처내기':'Parata di Lama',
'만화방창':'Raffica di Aghi',
'멸살광선':'Raggio Annientamento',
'원소추적탄':'Cercatore Elementale',
'악의 보호자':'Guardiano Malizia',
'악의 사냥':'Caccia Malizia',
'폭풍소환':'Evocazione Vortice',
'해골무덤':'Tomba d\'Ossa',
'신성폭발':'Esplosione Sacra',
'블랙':'Stella Nera',
'용암소환':'Evocazione Lava',
'처형':'Esecuzione',
'악마화 부활':'Resurrezione Demoniaca',
'붉은꽃':'Fiore Cremisi',
'얼음보주':'Sfera di Ghiaccio',
'뇌전걸음':'Passo Fantasma',
'만화방창 II':'Raffica di Aghi II',
'마력연사':'Raffica Arcana',
'마력광선':'Laser Arcano',
'업화선':'Raggio Infernale',
'지옥진':'Formazione Infernale',
'폭독칼날':'Lama Pestilente',
'악의폭풍':'Tempesta Malizia',
'악의기둥':'Pilastro Oscuro',
'회복의 영역':'Dominio Sacro',
'구속의 영역':'Dominio Vincolante',
'아이스스톰':'Tempesta di Ghiaccio',
'대왕치기':'Colpo Gigante',
'대왕치기 2':'Colpo Gigante II',
'기동불꽃':'Fiamma a Catena',
'기동파괴':'Distruzione a Catena',
'기동칼날개':'Ala di Lama',
'평화의보호':'Egida della Pace',
'참회':'Pentimento',
'칼등날개':'Ala Scudo',
'폭산탄':'Colpo Esplosivo',
'파쇄의 영역':'Dominio Frantumazione',
'침식의 영역':'Dominio Corrosione',
'관통의 영역':'Dominio Penetrazione',
'부활의 영역':'Dominio Resurrezione',
'가시덫':'Trappola di Spine',
'푸른비':'Pioggia Azzurra',
'버스트루프':'Ciclo Raffica',
'유령 허수아비':'Esca Fantasma',
'폭발 허수아비':'Esca Esplosiva',
'공성쇠뇌':'Balestra d\'Assedio',
'사슬기동:충돌':'Catena: Impatto',
'사슬기동:화염':'Catena: Fiamma',
'전격이동':'Passo Fulmine',
'기동칼날개!':'Ala Lama!',
'기동불꽃!':'Fiamma Catena!',
'기동파괴!':'Distruzione a Catena!',
'사슬이동:강화!':'Catena Potenziata!',
'사슬기동:화염!':'Catena: Fiamma!',
'작살!':'Rampone!',
'진입!':'Ingresso!',
'레인라이트닝!':'Pioggia Fulmini!',
'마력연사!':'Raffica Arcana!',
'🔷 마력광선!':'🔷 Laser Arcano!',
'광선 해제':'Laser disattivato',
'MP 부족 — 광선 해제':'MP esaurito — Laser disattivato',
'집중...':'Concentrazione...',
'시전...':'Lancio...',
'만화방창!':'Raffica di Aghi!',
'바늘출!':'Scarica di Aghi!',
'칼날!':'Lama!',
'착지!':'Atterraggio!',
'체간삭감!':'Postura spezzata!',
'기동전폭 준비!':'Esplosione Catena pronta!',
'기동불꽃 준비!':'Fiamma Catena pronta!',
'기동파괴 준비!':'Distruzione Catena pronta!',
'유령불꽃 ON':'Fiamma Fantasma ON',
'유령불꽃 OFF':'Fiamma Fantasma OFF',
'기동칼날개 AUTO ON':'Ala Lama AUTO ON',
'기동칼날개 AUTO OFF':'Ala Lama AUTO OFF',
'자동 버스트!':'Raffica auto!',
'연사 해제':'Fuoco rapido disatt.',
'당기기 모드':'Modalità Tirare',
'밀어내기 모드':'Modalità Spingere',
'날개치기':'Colpo Ala',
'처내기':'Parata',
'Shift: 작살 발사 → 끌려감':'Shift: Rampone → trascinamento',
'Shift: 화염길+화상':'Shift: Scia fuoco+bruciatura',
'CT: 전류변신+뇌전걸음 (쿨4초)':'CT: Forma fulmine+Passo Fantasma (CD 4s)',
'CT: 방어구체+빙결 (재입력: 파쇄)':'CT: Sfera ghiaccio+congela (ri-premere: frantuma)',
'근접':'Mischia',
'견갑':'Guardia',
'작살':'Rampone',
'마법':'Magia',
'보막':'Scudo',
'유령':'Fantasma',
'스킬':'Abilità',
'대장':'Forgia',
'인벤':'Inv',
'인벤토리':'Inventario',
'복수의 대장간':'Forgia della Vendetta',
'패시브 스킬':'Abilità Passive',
'전투 스킬':'Abilità Combattimento',
'캐릭터 선택':'Selezione Personaggio',
'물리':'Fisico',
'화염':'Fuoco',
'빙결':'Congelato',
'암흑':'Oscurità',
'암전':'Fulmine',
'신성':'Sacro',
'대지':'Terra',
'힘':'Forza',
'민첩':'Destrezza',
'지능':'Intelligenza',
'행운':'Fortuna',
'맹공':'Assalto',
'철벽':'Fermezza',
'돌파':'Sfondamento',
'반격':'Ritorsione',
'마력폭주':'Impeto Arcano',
'정밀사격':'Tiro Preciso',
'수호':'Guardiano',
'수호신':'Spirito Guardiano',
'회복력':'Recupero',
'급소':'Colpo Vitale',
'약탈':'Saccheggio',
'관통':'Penetrazione',
'마력회복':'Recupero Mana',
'쇠뇌력':'Maestria Balestra',
'광전사':'Berserker',
'추적자':'Inseguitore',
'물리관통':'Pen. Fisica',
'마법관통':'Pen. Magica',
'녹슨 대검':'Spadone Arrugginito',
'강철 대검':'Spadone d\'Acciaio',
'흑요석 대검':'Spadone Ossidiana',
'낡은 석궁':'Balestra Logora',
'강철 석궁':'Balestra d\'Acciaio',
'흑요석 석궁':'Balestra Ossidiana',
'대검':'Spadone',
'석궁':'Balestra',
'연사석궁':'Balestra Ripetizione',
'마력석궁':'Balestra Arcana',
'악의 추출':'Estrazione Malizia',
'악의':'Malizia',
'필살기':'Colpo Finale',
'필살기 해제':'Colpo Finale rimosso',
'이전':'Trasferire',
'강화':'Potenziare',
'개봉!':'Aperto!',
'여신의 가호':'Benedizione della Dea',
'과부하!':'Sovraccarico!',
'맹독의':'Velenoso',
'불꽃의':'Fiammeggiante',
'냉기의':'Gelido',
'번개의':'Voltaico',
'암흑의':'Maledetto',
'관통의':'Penetrante',
'광폭의':'Furioso',
'파쇄의':'Frantumate',
'연쇄의':'Concatenato',
'학살의':'Massacrante',
'폭발의':'Esplosivo',
'집중의':'Concentrato',
'쾌속의':'Rapido',
'패리의':'Deflettente',
'추적자의':'dell\'Inseguitore',
'작살의':'Rampone',
'궁극의':'Supremo',
'집중력의':'Attento',
'강인의':'Tenace',
'수호의':'Protettivo',
'활력의':'Vitale',
'신속의':'Accelerato',
'화염수호':'Guardia Fuoco',
'빙결수호':'Guardia Ghiaccio',
'암전수호':'Guardia Fulmine',
'암흑수호':'Guardia Oscurità',
'독수호':'Guardia Veleno',
'전원소수호':'Guardia Totale',
'강철의':'Corazzato',
'반사의':'Riflettente',
'가시의':'Spinoso',
'흡수의':'Assorbente',
'인내의':'Resistente',
'위기의':'Disperato',
'피격반격의':'Contrattaccante',
'패링폭발의':'Esplosione Parata',
'스태거폭발의':'Esplosione Barcollamento',
'원소전환의':'Convertitore',
'정화의':'Purificatore',
'불굴의':'Irremovibile',
'부활의':'Rianimatore',
'약탈의':'Saccheggiante',
'경험의':'Esperto',
'골드의':'Dorato',
'포션강화의':'Potente',
'사슬의':'Incatenato',
'진혼의':'Santificante',
'윤회의':'Ciclico',
'생명력의':'Vigoroso',
'재생의':'Rigenerante',
'치유의':'Curativo',
'마력의':'Arcano',
'절약의':'Efficiente',
'영혼의':'dell\'Anima',
'예리한':'Affilato',
'맹렬한':'Brutale',
'파멸의':'Rovinoso',
'게임 설정':'Impostazioni Gioco',
'화면 흔들림':'Vibrazione Schermo',
'파티클 양':'Quantità Particelle',
'효과음 볼륨':'Volume Effetti',
'음악 볼륨':'Volume Musica',
'난이도':'Difficoltà',
'자동 물약':'Pozione Auto',
'최소 줍기 등급':'Grado Min. Raccolta',
'최소 줍기 티어':'Tier Min. Raccolta',
'FPS 제한':'Limite FPS',
'해상도 스케일':'Scala Risoluzione',
'펫 자동수거':'Auto-Raccolta Pet',
'화면 설정':'Impostazioni Schermo',
'화면 모드':'Modalità Schermo',
'보스 AI 디버그':'Debug IA Boss',
'유령불꽃 크기':'Dimensione Fiamma Fantasma',
'화면 명암':'Luminosità',
'유령 글로우':'Bagliore Fantasma',
'기동:칼날개 AUTO':'Ala Lama AUTO',
'일반':'Normale',
'어려움':'Difficile',
'지옥':'Inferno',
'이상':'o superiore',
'사용 안 함':'Disattivato',
'창 모드':'Finestra',
'보더리스':'Senza Bordi',
'전체화면':'Schermo Intero',
'설정':'Impostazioni',
'조작 키 설정 (클릭하여 변경)':'Tasti (Clicca per Cambiare)',
'좌클릭 무기 공격':'Clic Sin Attacco Arma',
'우클릭 탭 칼등 처내기':'Clic Destro Parata Lama',
'우클릭 홀드 연속 처내기':'Tenere Destro Parata Continua',
'SHIFT 작살 발사':'SHIFT Lancia Rampone',
'이동':'Movimento',
'아이템 줍기':'Raccogliere Oggetto',
'능력치 (스탯/패시브)':'Attributi (Stats/Passivi)',
'분해':'Smontare',
'제작':'Fabbricare',
'사망':'Morte',
'부활':'Resurrezione',
'로비로':'Alla Lobby',
'가방에 공간이 없습니다!':'Nessuno spazio!',
'가방이 가득 찼습니다!':'Zaino pieno!',
'창고가 가득 찼습니다!':'Deposito pieno!',
'퀵슬롯이 가득 찼습니다!':'Slot rapido pieno!',
'결정 주머니가 가득 찼습니다!':'Sacca cristalli piena!',
'결정 주머니 가득!':'Sacca cristalli piena!',
'악의가 부족합니다!':'Malizia insufficiente!',
'가방이 비어있습니다':'Zaino vuoto',
'창고가 비어있습니다':'Deposito vuoto',
'비어있음':'Vuoto',
'어픽스 없음':'Nessun affisso',
'장착!':'Equipaggiato!',
'해제':'Rimosso',
'보관':'Depositare',
'꺼내기':'Ritirare',
'현재 장착':'Equipaggiato attuale',
'없음 — 제작하세요!':'Nessuno — Fabbricane uno!',
'리셋할 포인트가 없습니다':'Nessun punto da resettare',
'키 설정 초기화 완료':'Tasti resettati',
'제작 확률':'Prob. fabbricazione',
'제작 비용':'Costo fabbricazione',
'보유 악의':'Malizia posseduta',
'보스방':'Stanza Boss',
'안식처':'Santuario',
'회복':'Recupero',
'점화':'Accendere',
'비석':'Stele',
'읽기':'Leggere',
'파괴':'Distruggere',
'제단':'Altare',
'기원':'Pregare',
'잔해':'Macerie',
'열기':'Aprire',
'문지기':'Guardiano',
'부활 판정 중...':'Giudizio resurrezione...',
'기폭 준비!':'Detonazione pronta!',
'탈출':'Fuggire',
'연타':'Premere',
'추적암전':'Fulmine Tracciante',
'만화광선':'Raggio Luminescente',
'최종 마법':'Magia Finale',
'감시중':'Sorveglianza',
'대기':'Attesa',
'작동중':'Attivo',
'설치 가능':'Installabile',
'균열 임박!':'Breccia imminente!',
'흡수 중...':'Assorbimento...',
'흡수 완료 — 재입력으로 회수':'Fatto — ri-premere per raccogliere',
'화상':'Bruciatura',
'당기기':'Tirare',
'밀어내기':'Spingere',
'단계':'livello',
'단':'livello',
'습득!':'Appreso!',
'리셋!':'Resettato!',
'세팅!':'Impostato!',
'회수':'Recuperare',
'합체 해제':'Defondere',
'리셋':'Resettare',
'환불':'Rimborso',
'파트너 클릭!':'Clicca partner!',
'SP부족!':'SP insufficiente!',
'같은 보석 스킬 습득 시 합체 가능':'Fondibile imparando stessa gemma',
'펼쳐서 초기화':'Espandi per resettare',
'슬롯:':'Slot:',
'남은 SP':'SP Rimanenti',
'맞아서 사망':'Morto per colpo',
'레벨':'Livello',
'최대HP':'HP Massimi',
'방랑 기사':'Cavaliere Errante',
'보물 악마':'Demone Tesoro',
'거울의 사도':'Apostolo Specchio',
'상인 악마':'Demone Mercante',
'사슬의 죄수':'Prigioniero Incatenato',
'시간의 사도':'Apostolo del Tempo',
'탐욕의 사도':'Apostolo Avidità',
'저주받은 쌍둥이':'Gemelli Maledetti',
'차원 균열체':'Entità Dimensionale',
'죽음 그 자체':'La Morte in Persona',
'HP결정':'Cristallo HP',
'ST결정':'Cristallo ST',
'MP결정':'Cristallo MP',
'ATK결정':'Cristallo ATK',
'DEF결정':'Cristallo DEF',
'속도결정':'Cristallo Velocità',
'크리결정':'Cristallo Critico',
'치명결정':'Cristallo DannoCrit',
'화염결정':'Cristallo Fuoco',
'냉기결정':'Cristallo Ghiaccio',
'암흑결정':'Cristallo Oscurità',
'번개결정':'Cristallo Fulmine',
'신성결정':'Cristallo Sacro',
'생명결정':'Cristallo Vita',
'기력결정':'Cristallo Resistenza',
'마력결정':'Cristallo Mana',
'행운결정':'Cristallo Fortuna',
'조각':'Frammento',
'파편':'Scheggia',
'순수결정':'Cristallo Puro',
'완전결정':'Cristallo Perfetto',
'결정 주머니':'Sacca Cristalli',
'결정이 없습니다':'Nessun cristallo',
'가루':'Polvere',
'전체':'Tutto',
'스탯':'Statistiche',
'원소':'Elemento',
'유틸':'Utilità',
'현재':'Attuale',
'최대 강화 달성 (+20)':'Potenz. max (+20)',
'강화 시':'Dopo potenziamento',
'합성':'Sintetizzare',
'같은 종류·같은 성급 결정 3개 → 1성급 상승 (강화 리셋)':'3 cristalli stesso tipo e grado → sale 1 grado (potenziamento reset)',
'합성 가능한 결정이 없습니다 (같은 종류·성급 3개 필요)':'Nessun cristallo sintetizzabile (servono 3)',
'결정 분해 → 결정 가루':'Decomporre Cristallo → Polvere',
'분해할 결정이 없습니다':'Nessun cristallo da decomporre',
'결정 제작 (가루 → 결정)':'Fabbricare Cristallo (Polvere → Cristallo)',
'탈착':'Staccare',
'빈 슬롯':'Slot vuoto',
'결정 선택 후 클릭':'Seleziona cristallo poi clicca',
'클릭하여 선택결정 장착':'Clicca per equipaggiare cristallo',
'획득!':'Ottenuto!',
'제작!':'Fabbricato!',
'합성!':'Sintetizzato!',
'최상위 일괄합성':'Sintesi massiva',
'일괄합성 완료':'Sintesi massiva completata',
'벌레굴':'Nido di Vermi',
'얼음굴':'Caverna di Ghiaccio',
'고통의 화염지대':'Landa Infernale',
'지옥의 군단':'Legione Infernale',
'사도의 마굴':'Tana dell\'Apostolo',
'지옥성':'Cittadella Infernale',
'엑소듀서 전사':'Guerriero Exoduser',
'포이즈':'Postura',
'지옥창고':'Deposito Infernale',
'선택분해':'Smontaggio Selettivo',
'쓰레기':'Spazzatura',
'복구 불가!':'Irrecuperabile!',
'중요잠금':'Blocco importante',
'자동 장착!':'Auto-equipaggiato!',
'분해! 가루 +':'Smontato! Polvere +',
'평화보호':'Egida',
'지진폭풍':'Tempesta Sismica',
'회전기폭':'Turbine-Det',
'공격':'Attacco',
'보호막':'Barriera',
'합체 스킬로 통합됨':'Fuso in abilità combinata',
'얼음보주 안에선 사용 불가!':'Non utilizzabile nella Sfera di Ghiaccio!',
'Shift+키로 폭파':'Shift+tasto per detonare',
'취소':'Annulla',
'쿨다운 중...':'Raffreddamento...',
'시전 중...':'Lancio...',
'악의 부족! (12)':'Malizia insuff.! (12)',
'악의 부족! (15)':'Malizia insuff.! (15)',
'악의 부족! (20)':'Malizia insuff.! (20)',
'악의 부족! (10)':'Malizia insuff.! (10)',
'HP 부족!':'HP insufficiente!',
'필살기 슬롯 클릭하여 배정!':'Clicca slot colpo finale!',
'필살기 스킬을 습득하세요':'Impara un colpo finale',
'우클릭(칼등치기)에 합체됨':'Fuso clic destro (parata)',
'T(석궁자동)에 세팅하세요':'Imposta su T (balestra auto)',
'공성쇠뇌 철거 → 이동식':'Balestra assedio smontata → portatile',
'ST 부족! (100)':'ST insuff.! (100)',
'HP 99% 이상!':'HP 99%+!',
'그로기 보스 없음!':'Nessun boss stordito!',
'이미 폭풍 지역!':'Già in zona tempesta!',
'이미 빙풍 지역!':'Già in zona ghiaccio!',
'💎 푸른비 해금!':'💎 Pioggia Azzurra sbloccata!',
'💫 버스트루프 해금!':'💫 Ciclo Raffica sbloccato!',
'👻 유령 허수아비 해금!':'👻 Esca Fantasma sbloccata!',
'쿨 ':'CD ',
'과부하 ':'Sovraccarico ',
'🕊️💎 블루콩!':'🕊️💎 Fagiolo Blu!',
'🛡️💎 빨콩→블루콩!':'🛡️💎 Rosso→Blu!',
'🛡️💎 무지개→블루콩!':'🛡️💎 Arcobaleno→Blu!',
'레어':'Raro',
'슬롯':'Slot',
'성공률':'Tasso Successo',
'AI 자동 강화':'Potenziamento Auto IA',
'최대 강화 달성!':'Potenziamento max raggiunto!',
'최대 강화':'Potenziamento max',
'회복량':'Recupero',
'분해할 아이템이 없습니다.':'Nessun oggetto da smontare.',
'🔨 제작':'🔨 Fabbricare',
'체간':'Postura',
'아이템에 마우스를 올리거나 좌클릭으로 선택하세요':'Passa sopra o clic sinistro per selezionare',
'중독':'Veleno',
'지뢰':'Mina',
'함정':'Trappola',
'산호가시':'Spina Corallo',
'투사체':'Proiettile',
'도트':'DoT',
'레어몹':'Mob Raro',
'구역':'Zona',
'가시!':'Spina!',
'림보':'Limbo',
'색욕':'Lussuria',
'탐식':'Gola',
'탐욕':'Avidità',
'분노':'Ira',
'이단':'Eresia',
'폭력':'Violenza',
'분노!':'Furia!',
'탐욕!':'Avidità!',
'💀 분노 폭발!':'💀 Esplosione Furia!',
'심연의 분노!':'Furia Abissale!',
'쌍둥이의 분노!':'Furia del Gemello!',
'소환굴':'Tana Evocazione',
'처치!':'Eliminato!',
'왕관 착용':'Corona Indossata',
'왕관 해제':'Corona Rimossa',
'맨손':'Mani Nude',
'없음':'Nessuno',
'갑옷':'Armatura',
'부츠':'Stivali',
'매직':'Magia',
'챔피언':'Campione',
'초속':'Celerità',
'강타':'Schianto',
'재생':'Rigenerazione',
'맹독':'Veleno',
'소환':'Evocazione',
'기생':'Parassita',
'분열':'Scissione',
'용암자취':'Scia Lava',
'사망폭발':'Esplosione Mortale',
'화염사슬':'Catena Fuoco',
'광전':'Frenesia',
'텔레포트':'Teletrasporto',
'소용돌이':'Vortice',
'환영':'Fantasma',
'전격반사':'Riflesso Shock',
'감전':'Folgorazione',
'낙뢰':'Tuono',
'연쇄전격':'Fulmine Catena',
'동료불사':'Alleato Immortale',
'영혼포식':'Divoratore Anime',
'시간왜곡':'Distorsione Temporale',
'혼돈변이':'Mutazione Caotica',
'복수자':'Vendicatore',
'마법보초':'Sentinella Magica',
'환영술사':'Illusionista',
'함성':'Grido Guerra',
'치유':'Cura',
'신속':'Rapidità',
'다크 판타지 전사. 거대검+검은 갑옷':'Guerriero dark fantasy. Spadone + Armatura nera',
'⚡ 사슬이동:강화!':'⚡ Catena: Potenziata!',
'⚡ 사슬기동:화염!':'⚡ Catena: Fiamma!',
'달성!':'Raggiunto!',
'ST':'ST',
'부족!':'Insufficiente!',
'타':'Colpo',
'🌀 당기기 모드':'🌀 Modalità Tirare',
'💥 밀어내기 모드':'💥 Modalità Spingere',
'🕊️빨콩 흡수':'🕊️Assorbimento fagiolo rosso',
'🕊️흡수':'🕊️Assorbimento',
'💎유도 폭발!':'💎Esplosione guidata!',
'💥반사 폭발!':'💥Esplosione riflesso!',
'⚡⚡ 참회 귀환!':'⚡⚡ Ritorno Pentimento!',
'⚡ 참회!':'⚡ Pentimento!',
'파도!':'Onda!',
'암전!':'Fulmine!',
'암흑!':'Oscurità!',
'암흑창!':'Lancia Oscura!',
'빛창!':'Lancia di Luce!',
'체 소환!':'evocato!',
'개 설치!':'piazzato!',
'💥 보스 그로기!':'💥 Boss Stordito!',
'💥 그로기!':'💥 Stordito!',
'보상':'Bonus',
'⚡ 암전나선!':'⚡ Elica Fulmine!',
'🌋 지진폭풍!':'🌋 Tempesta Sismica!',
'SP슬롯':'Slot SP',
'F슬롯':'Slot F',
'⚔🩸 독혈해방!':'⚔🩸 Liberazione Peste!',
'⚔ 칼날 해방!':'⚔ Liberazione Lama!',
'🔨🌋 지옥강타!':'🔨🌋 Colpo Infernale!',
'🔨 대왕치기!':'🔨 Colpo Gigante!',
'✟ 결계의 영역!':'✟ Dominio Protezione!',
'✟ 물의 영역!':'✟ Dominio Acqua!',
'✟ 파쇄의 영역!':'✟ Dominio Frantumazione!',
'✟ 침식의 영역!':'✟ Dominio Corrosione!',
'✟ 관통의 영역!':'✟ Dominio Penetrazione!',
'✟ 권능의 영역!':'✟ Dominio Sovrano!',
'🛡 회복의 영역!':'🛡 Sacred Domain!',
'임계...!':'Critico...!',
'기폭팔!':'Detonare!',
'강제기폭!':'Detonazione forzata!',
'자동기폭!':'Detonazione auto!',
'회전기폭!':'Turbine detonare!',
'해제기폭!':'Rilascio detonare!',
'지진기폭!':'Sisma detonare!',
'혼돈의 왕관':'Corona del Caos',
'전지전능의 왕관':'Corona dell\'Onnipotenza',
'악마의 팔찌':'Bracciale Demoniaco',
'생명의 팔찌':'Bracciale della Vita',
'🌊 위→아래 파도!':'🌊 Onda Alto→Basso!',
'🌊 오른→왼 파도!':'🌊 Onda Destra→Sinistra!',
'🌊 아래→위 파도!':'🌊 Onda Basso→Alto!',
'🌊 왼→오른 파도!':'🌊 Onda Sinistra→Destra!',
'무적!':'Invincibile!',
'🪞 반격!':'🪞 Contrattacco!',
'💢 반격!':'💢 Contrattacco!',
'흡수!':'Assorbimento!',
'반격 발사!':'Colpo contrat.!',
'저주! 드랍률 -50%':'Maledizione! Drop -50%',
'도망!':'Fuga!',
'위상!':'Fase!',
'방어!':'Guardia!',
'회수 HP+':'Recuperare HP+',
'이동식 복귀':'Ritorno Mobile',
'약점!':'Debolezza!',
'저항!':'Resistenza!',
'콤보 종료: ':'Fine combo: ',
'악의 +':'Malizia +',
'저주 ':'Maledizione ',
'불발...':'Mancato...',
'작살 약점!':'Debolezza Rampone!',
'전염 x':'Peste x',
'흡수 완료!':'Assorbimento completo!',
'부활 성공!':'Resurrezione riuscita!',
'부활 실패...':'Resurrezione fallita...',
'차원 이동!':'Spostamento Dimensionale!',
'기절 해제':'Stordimento rimosso',
'악의 부족':'Malizia insufficiente',
'스킬 미습득':'Nessuna abilità',
'펼치기':'Espandi',
'접기':'Comprimi',
'조건 미달!':' non soddisfatta!',
'해제!':' Defuso!',
'자동 ON':' Auto ON',
'자동 OFF':' Auto OFF',
'스킬 해제':' abilità rimossa',
'닫기':'Chiudi',
'장착 중':'Equipaggiato',
'보관 아이템':'Oggetto depositato',
'클릭으로 선택 · ESC로 닫기':'Clicca per selezionare · ESC per chiudere',
'선택됨':'Selezionato',
'악의 부족! (30)':'Malizia insuff.! (30)',
'MP 부족! (40)':'MP insuff.! (40)',
'MP 부족! (100)':'MP insuff.! (100)',
'MP 부족! (10)':'MP insuff.! (10)',
'MP 부족! (':'MP insuff.! (',
'✟ 시전...':'✟ Lancio...',
'🌋 시전...':'🌋 Lancio...',
'⛧ 시전...':'⛧ Lancio...',
'❄ 진입!':'❄ Ingresso!',
'🔱 작살!':'🔱 Rampone!',
'레벨 부족! (요구: Lv.':'Livello basso! (Req: Lv.',
' 장착!':' Equipaggiato!',
' 해제':' Rimosso',
'👿 악의 추출: +':'👿 Estrazione Malizia: +',
'F 슬롯 해제':'Slot F rimosso',
'💫 집중...':'💫 Concentrazione...',
'⚡ 마력연사!':'⚡ Raffica Arcana!',
'❄빙결!':'❄Congelato!',
'🟢독!':'🟢Veleno!',
'⚡감전!':'⚡Folgorato!',
'🔥화상!':'🔥Bruciatura!',
'✦ 여신의 가호 — SP+5 AP+3':'✦ Benedizione Dea — SP+5 AP+3',
'⚔ 기동칼날개!':'⚔ Ala Lama!',
'🔥 화염관통!':'🔥 Penetrazione Fuoco!',
'🔱 관통!':'🔱 Penetrazione!',
'⚔ 칼날!':'⚔ Lama!',
'💥 착지!':'💥 Atterraggio!',
'💫 기절!':'💫 Stordito!',
'⚡ 체간삭감!':'⚡ Postura spezzata!',
'⚡ 기동파괴! ':'⚡ Distruzione Catena! T',
'🔥 기동불꽃!':'🔥 Fiamma Catena!',
'🔥 기동불꽃! ':'🔥 Fiamma Catena! T',
'단계 ×':' x',
'⚡ 기동전폭! x':'⚡ Esplosione Catena! x',
'🔥🔥 3중폭!':'🔥🔥 Fiamma x3!',
'🔥🔥🔥 6중폭!':'🔥🔥🔥 Fiamma x6!',
'🔥🔥🔥🔥 9중폭!':'🔥🔥🔥🔥 Fiamma x9!',
'💥 불꽃폭발! ':'💥 Detonazione Fiamma! ',
'🔥 기동불꽃 준비!':'🔥 Fiamma Catena pronta!',
'🔨 기동파괴 준비!':'🔨 Distruzione Catena pronta!',
'⚡ 기동전폭 준비!':'⚡ Esplosione Catena pronta!',
'⚡ 과부하! 5초':'⚡ Sovraccarico! 5s',
'💫 자동 버스트!':'💫 Raffica auto!',
'🔨 칼등날개!':'🔨 Ala Scudo!',
'💥폭발!':'💥Esplosione!',
'🛡️💎 유도반사!':'🛡️💎 Riflesso Guidato!',
'⚡💎 블루콩!':'⚡💎 Fagiolo Blu!',
'💎 블루콩!':'💎 Fagiolo Blu!',
'⚡반사!':'⚡Riflesso!',
'💎 푸른비 OFF':'💎 Pioggia Azzurra OFF',
'💎 푸른비 ON!':'💎 Pioggia Azzurra ON!',
'🔥 지옥진!':'🔥 Formazione Infernale!',
'🔥 업화선!':'🔥 Raggio Infernale!',
'✦ 평화 충격파! ':'✦ Onda Pace! ',
'⚡ 전류 방출!':'⚡ Rilascio Corrente!',
'⚡⚡ 레인라이트닝!':'⚡⚡ Pioggia Fulmini!',
'💫 광역!':'💫 AoE!',
'🔥 불장판!':'🔥 Zona Fuoco!',
'💫 피니셔!':'💫 Finisher!',
'☠ 지옥에서 귀환!':'☠ Ritorno dall\'Inferno!',
'☠ 완전 사망!':'☠ Morte Permanente!',
'⚔ 처형! ':'⚔ Esecuzione! ',
'💥 지뢰!':'💥 Mina!',
'⚠ 함정!':'⚠ Trappola!',
'❌ 우클릭으로! -':'❌ Usa Clic Destro! -',
'❌ Q키로! -':'❌ Usa Q! -',
'💥무지개 폭발! ':'💥Esplosione Arcobaleno! ',
'🛡️💎 블루콩!':'🛡️💎 Fagiolo Blu!',
'⬜화이트볼!':'⬜White Ball!',
'✨💎 블루콩!':'✨💎 Fagiolo Blu!',
'💜다크볼!':'💜Palla Oscura!',
'❄빙판!':'❄Pavimento Ghiaccio!',
'🌨빙결!':'🌨Congelato!',
'🕸둔화!':'🕸Rallentato!',
'⚠트랩!':'⚠Trappola!',
'💀 역병 처형!':'💀 Esecuzione Peste!',
'💥 역병 Finale!':'💥 Finale Peste!',
'⚔ 균열 악마!':'⚔ Demone Faglia!',
'자동회수 HP+':'Auto-Recuperare HP+',
'MP 부족 — 연사 해제':'MP basso — Fuoco rapido OFF',
'MP 부족 — 푸른비 OFF':'MP basso — Pioggia Azzurra OFF',
'🛡️반사!':'🛡️Riflesso!',
'⚡🦴 참회 귀환!':'⚡🦴 Ritorno Pentimento!',
'🦴⚡해골번개!':'🦴⚡Fulmine Ossa!',
'⚡악의폭풍!':'⚡Tempesta Malizia!',
'❄아이스스톰!':'❄Tempesta Ghiaccio!',
'⚡ 암전폭발!':'⚡ Esplosione Fulmine!',
'⚡ 레인라이트닝! x':'⚡ Pioggia Fulmini! x',
'❄ 탈출!':'❄ Fuggire!',
'⚡쉴드!':'⚡Scudo!',
'❄🌪️ 얼음보주!':'❄🌪️ Sfera Ghiaccio!',
'🌪️ 전개!':'🌪️ Dispiegamento!',
'❄ 빙결흡인!':'❄ Vortice Ghiaccio!',
'❄☄ 빙결폭발!':'❄☄ Esplosione Ghiaccio!',
'☄️ 흡인!':'☄️ Vortice!',
'☄️ 대폭발!':'☄️ Mega Esplosione!',
'❄ 얼음보주!':'❄ Sfera Ghiaccio!',
'⏳ 시간왜곡!':'⏳ Time Warp!',
'쿨다운!':'Raffreddamento!',
'❄ 파쇄!':'❄ Frantumazione!',
'☄️💥 대폭발!':'☄️💥 Mega Esplosione!',
'반사!':'Riflesso!',
'💀 도넛!':'💀 Ciambella!',
'💀 전멸!':'💀 Annientamento!',
'🌊 파도!':'🌊 Onda!',
'속박!':'Vincolo!',
'반격!':'Contrattacco!',
'분신!':'Clone!',
'분신 파괴!':'Clone distrutto!',
'무기 해방!':'Liberazione arma!',
'❄프리즌!':'❄Prigione!',
'⚡ 증표 ':'⚡ Segno ',
'흔들!':'Scossa!',
'⚠ 광역 발사!':'⚠ Fuoco AoE!',
'🔥 확산!':'🔥 Propagazione!',
'⚠ 돌진!':'⚠ Carica!',
'🦅 도약!':'🦅 Salto!',
'⚡ 레이저!':'⚡ Laser!',
'🌊 충격파!':'🌊 Onda d\'urto!',
'👹 소환!':'👹 Evocazione!',
'☄ 유성우!':'☄ Pioggia meteoriti!',
'🖐 잡기!':'🖐 Afferrare!',
'🌀 회전참!':'🌀 Turbine!',
'💣 지뢰!':'💣 Mina!',
'🌀 흡인!':'🌀 Aspirazione!',
'🔴 빨간콩 폭풍!':'🔴 Tempesta Fagiolo Rosso!',
'🔴🔴 콩 비!':'🔴🔴 Pioggia Fagioli!',
'🌊 부채꼴 충격파!':'🌊 Onda ventaglio!',
'✴ 멸광 레이저!':'✴ Laser Annientamento!',
'🔴 추적 장판!':'🔴 Zona Tracciamento!',
'💥 속성탄!':'💥 Colpo Elementale!',
'⚔ 검기!':'⚔ Ki Spada!',
'⚔ 재단참!':'⚔ Fendente Mietitore!',
'🌀 나선탄!':'🌀 Colpo Spirale!',
'⚠ 찌르기!':'⚠ Stoccata!',
'🔥🔥 지옥기둥!':'🔥🔥 Pilastro Infernale!',
'⚔ 환영검!':'⚔ Lama Fantasma!',
'💢 반격자세!':'💢 Postura Contrat.!',
'⚔ 연격!':'⚔ Combo!',
'🌑 암흑!':'🌑 Oscurità!',
'👥 분신!':'👥 Clone!',
'🌋 균열!':'🌋 Faglia!',
'🌊 파동!':'🌊 Ondulazione!',
'💣 추적지뢰!':'💣 Mina tracciante!',
'⏪ 되감기!':'⏪ Rewind!',
'🌀 중력장!':'🌀 Campo gravitazionale!',
'🔨 벽밀기!':'🔨 Spingere muro!',
'☠ 독안개!':'☠ Nebbia velenosa!',
'⛓ 감옥!':'⛓ Prigione!',
'⚡ 연쇄번개!':'⚡ Fulmine a catena!',
'🔮 궤도탄!':'🔮 Colpo orbitale!',
'🛡 방패돌진!':'🛡 Carica scudo!',
'🪞 반격자세!':'🪞 Postura Contrat.!',
'⚓ 속박!':'⚓ Vincolo!',
'👤 분신!':'👤 Clone!',
'🖐 탈취!':'🖐 Furto!',
'🔥🔥 용암 지대!':'🔥🔥 Zona lava!',
'🌧🌧 화염 폭격!':'🌧🌧 Raffica fuoco!',
'⚡⚡ 전격 장막!':'⚡⚡ Velo fulmine!',
'💀 내 곁으로!':'💀 Vieni da me!',
'⭕ 안전!':'⭕ Sicuro!',
'💀💀 전멸 폭발!':'💀💀 Esplosione Annientamento!',
'⚡ 쐐기 소멸!':'⚡ Estinzione Cuneo!',
'🌊충격파!':'🌊Onda d\'urto!',
'👿악의+100':'👿Malizia+100',
'💥패링폭발!':'💥Esplosione Parata!',
'균열 충돌! ':'Collisione faglia! ',
'벽 충돌! ':'Collisione muro! ',
'소환!':'Evocazione!',
'환영!':'Fantasma!',
'⚡낙뢰!':'⚡Tuono!',
'⚡빔!':'⚡Raggio!',
'환영술!':'Illusione!',
'💀소환!':'💀Evocazione!',
'🔮주술!':'🔮Maledizione!',
'🩸산란!':'🩸Generazione!',
'💢광폭!':'💢Frenesia!',
'🕷산란!':'🕷Generazione!',
'❄서리!':'❄Gelo!',
'❄빙결파!':'❄Onda Ghiaccio!',
'💀빙마!':'💀Demone Ghiaccio!',
'돌진!':'Carica!',
'충격파!':'Onda d\'urto!',
'독안개!':'Nebbia velenosa!',
'연타!':'Raffica!',
'포효!':'Ruggito!',
'강화!':'Potenziamento!',
'꼬리!':'Coda!',
'은신...':'Furtività...',
'기습!':'Imboscata!',
'산란!':'Generazione!',
'독가스!':'Gas velenoso!',
'소멸...':'Dissoluzione...',
'강타!':'Schianto!',
'분비!':'Secrezione!',
'채찍!':'Frusta!',
'출혈!':'Sanguinamento!',
'급강하!':'Picchiata!',
'방출!':'Scarica!',
'충격!':'Impatto!',
'치유!':'Cura!',
'의식!':'Rituale!',
'지옥불!':'Fuoco infernale!',
'끌려감!':'Trascinato!',
'혀!':'Lingua!',
'응시!':'Sguardo!',
'낙하!':'Caduta!',
'핏방울!':'Goccia sangue!',
'일어남!':'Alzarsi!',
'휩쓸기!':'Spazzata!',
'웅크림':'Accovacciato',
'뼈칼날!':'Lama d\'osso!',
'감속!':'Rallentato!',
'비명!':'Urlo!',
'화산탄!':'Colpo vulcanico!',
'자폭!':'Autodistruzione!',
'감싸기!':'Avvolgere!',
'잡기!':'Afferrare!',
'내리찍기!':'Colpo!',
'브레스!':'Soffio!',
'비행!':'Volo!',
'용암비!':'Pioggia lava!',
'물뿜기!':'Getto acqua!',
'빛...':'Luce...',
'삼키기!':'Ingoiare!',
'마비!':'Paralisi!',
'방전!':'Scarica!',
'집게찍기!':'Tenaglia!',
'찍기!':'Colpo!',
'붙잡기!':'Afferrare!',
'감아올리기!':'Avvolgere!',
'파편!':'Frammento!',
'할퀴기!':'Graffio!',
'기생충!':'Parassita!',
'심연 해방!':'Liberazione abissale!',
'촉수난타!':'Raffica tentacoli!',
'삼지창!':'Tridente!',
'소용돌이!':'Vortice!',
'해일!':'Tsunami!',
'끼걱!':'Scricchiolio!',
'폭발!':'Esplosione!',
'체인!':'Catena!',
'갈기!':'Criniera!',
'공포!':'Terrore!',
'흡혈!':'Drenaggio!',
'베기!':'Fendente!',
'비이이명!!':'Driiiin!!',
'분열!':'Scissione!',
'3연참!':'Triplo fendente!',
'패링!':'Parata!',
'...복사...':'...Copia...',
'불균형...저주!':'Squilibrio...Maledizione!',
'저주!':'Maledizione!',
'균형...강화!':'Equilibrio...Potenziamento!',
'심판의 기둥!':'Pilastro del Giudizio!',
'처형 선고!':'Sentenza Morte!',
'고통의 해방!':'Liberazione dolore!',
'너도 느껴봐라!':'Senti anche tu!',
'대검난무!':'Frenesia spadone!',
'촉수!':'Tentacolo!',
'전방위 빔!':'Raggio totale!',
'회피!':'Schivata!',
'[F] 상점':'[F] Negozio',
'거래 성공!':'Commercio riuscito!',
'악의 부족! (':'Malizia insuff.! (',
'상인이 떠납니다...':'Il mercante se ne va...',
'사슬 해방!':'Liberazione catena!',
'완전 해방!':'Liberazione totale!',
'⏪ 시간 되감기!':'⏪ Time Rewind!',
'전환!':'Cambio!',
'부활 ':'Resurrezione ',
'🌀균열!':'🌀Faglia!',
'...사라짐':'...Scomparso',
'낫 베기!':'Fendente falce!',
'☠ 죽음의 선고!':'☠ Sentenza Morte!',
'선고 집행...':'Esecuzione sentenza...',
'⚡패링!':'⚡Parata!',
'경직!':'Barcollamento!',
'⚠ 잡혔다!':'⚠ Afferrato!',
'💥 내던지기!':'💥 Lancio!',
'💥 소용돌이 폭발!':'💥 Esplosione Vortice!',
'👻 순간이동!':'👻 Teletrasporto!',
'💫 기절! 5초':'💫 Stordito! 5s',
'찌르기 반격!':'Contrattacco spinta!',
'💢 폭발!':'💢 Esplosione!',
'반격 실패':'Contrattacco fallito',
'탈취 반격!':'Contrattacco furto!',
'무기 봉인!':'Sigillo arma!',
'냠!':'Gnam!',
'합체!':'Fuso!',
'출구가 열렸다!':'Uscita aperta!',
'보물상자 출현!':'Forziere apparso!',
'출구':'Uscita',
'⚠ 문지기가 살아있다!':'⚠ Guardiano ancora vivo!',
'⏱ 타임어택 ':'⏱ Time Attack ',
'처치율 ':'Tasso Elim. ',
'불사 보호':'Protezione immortale',
'환영 소멸!':'Fantasma scomparso!',
'부활력 ':'Potere Resurrezione ',
'✟ 신성력 억제! (':'✟ Soppressione Sacra! (',
'부활 실패 (':'Resurrezione fallita (',
'⚡순간이동!':'⚡Teletrasporto!',
'👻 동반부활!':'👻 Co-Resurrezione!',
'✟ 신성력 억제!':'✟ Soppressione Sacra!',
'💀 부활 판정 중...':'💀 Giudizio resurrezione...',
'⚔ 문지기 처치!':'⚔ Guardiano Eliminato!',
'🚪 보스방 개방!':'🚪 Stanza Boss Aperta!',
'잔해 출현!':'Macerie apparse!',
'🌀균열 발생!':'🌀Faglia aperta!',
'🔥복수!':'🔥Vendetta!',
'💥폭독혈!':'💥Sangue Peste!',
'빙판!':'Pavimento Ghiaccio!',
'❄최종빙결!':'❄Congelamento Finale!',
'빙마 처치!':'Demone Ghiaccio Eliminato!',
'분리!':'Separazione!',
'뼈 파편!':'Frammento osso!',
'태아 처치!':'Feto Eliminato!',
'지배자 처치!':'Signore Eliminato!',
'용암!':'Lava!',
'화룡 처치!':'Drago Fuoco Eliminato!',
'최후의 비명!':'Urlo Finale!',
'산화...':'Ossidazione...',
'심판자 처치!':'Giudice Eliminato!',
'고통의 왕 처치!':'Re Dolore Eliminato!',
'수역!':'Acqua!',
'파편 폭발!':'Esplosione frammento!',
'거대어 처치!':'Leviatano Eliminato!',
'대사도 처치!':'Alto Apostolo Eliminato!',
'독웅덩이!':'Pozza veleno!',
'화염장판!':'Zona Fuoco!',
'전기장!':'Campo elettrico!',
'무기 드롭!':'Arma caduta!',
'보물 발견!':'Tesoro trovato!',
'상인의 주머니 +':'Sacca mercante +',
'속박의 파편!':'Scheggia vincolo!',
'시간의 조각!':'Frammento tempo!',
'저주 해제!':'Maledizione rimossa!',
'차원의 결정!':'Cristallo dimensionale!',
'전설 아이템!':'Oggetto leggendario!',
'죽음을 이겨냈다!':'Superare la morte!',
'💥대폭발!':'💥Mega Esplosione!',
'⚡강화!':'⚡Potenziamento!',
'장비 ':'Equipagg. ',
'💫 진동!':'💫 Tremore!',
'❄ 무적!':'❄ Invincibile!',
'👻 유령!':'👻 Fantasma!',
'집중 해제!':'Concentrazione annullata!',
'집중!':'Concentrazione!',
'🕊️ 평화보호 ':'🕊️ Egida ',
'🛡 보호막 ':'🛡 Scudo ',
'🌀 회전보호막 ':'🌀 Scudo Rotante ',
'💥한방캡!':'💥Limite un colpo!',
'⚡쉴드 파괴!':'⚡Scudo distrutto!',
'💀 불굴!':'💀 Irremovibile!',
'💀 1회부활!':'💀 1 vita resurrezione!',
'감시 회수':'Recupera sentinella',
'악마화 부활!':'Resurrezione demoniaca!',
'배정 가능한 스킬 없음':'Nessuna abilità da assegnare',
'칼날 없음!':'Nessuna lama!',
'⚔ 악의사냥!':'⚔ Caccia Malizia!',
'❄🌪️ 얼음소용돌이!':'❄🌪️ Vortice Ghiaccio!',
'🌪️ 폭풍소환!':'🌪️ Evocazione Vortice!',
'🦴 해골무덤!':'🦴 Tomba Ossa!',
'🌹 붉은꽃!':'🌹 Fiore Cremisi!',
'💥 폭산탄!':'💥 Colpo Esplosivo!',
'🪡 바늘출!':'🪡 Scarica di Aghi!',
'⚡ 전격이동!':'⚡ Passo Fulmine!',
'기둥가시로 흡수됨':'Assorbito da spina pilastro',
'🌿 가시덫!':'🌿 Trappola Spine!',
'👻 유령총!':'👻 Pistola Fantasma!',
'💥 유령총 폭발!':'💥 Esplosione Pistola Fantasma!',
'⚡ 전격의창!':'⚡ Lancia Tuono!',
'🏹 공성쇠뇌 설치!':'🏹 Balestra Assedio piazzata!',
'👻 유령 허수아비!':'👻 Esca Fantasma!',
'💥 폭발 허수아비!':'💥 Esca Esplosiva!',
'축적!':'Immagazzinato!',
'축적 중...':'Immagazzinamento...',
'만충! 재입력→폭발':'Pieno! Ri-premere→Esplodere',
'폭발! ':'Esplodere! ',
'뎀':' DMG',
'🩸 폭독칼날!':'🩸 Lama Pestilente!',
'⚡날개치기!':'⚡Colpo Ala!',
'🗡 칼등날개!':'🗡 Ala Scudo!',
'🏛️ 악의기둥!':'🏛️ Pilastro Oscuro!',
'🌿 기둥가시!':'🌿 Spina Pilastro!',
'🌋 지옥강타!':'🌋 Colpo Infernale!',
'💥 체간 붕괴!':'💥 Postura Spezzata!',
'💫 포이즈 파괴!':'💫 Postura Distrutta!',
'⚡ 뇌전걸음!':'⚡ Passo Fantasma!',
'✟ 구속의 영역!':'✟ Dominio Vincolante!',
'✟ 신성폭발!':'✟ Esplosione Sacra!',
'⛧ 블랙!':'⛧ Stella Nera!',
'🌋 용암소환!':'🌋 Evocazione Lava!',
'필살기 배정!':'Colpo finale assegnato!',
'완료':'Completo',
'합체 가능':'Può Fondere',
'부족':'Insufficiente',
'SP 부족! (':'SP insuff.! (',
'🕊️ 히든: 평화의보호 해금!':'🕊️ Nascosto: Egida della Pace sbloccata!',
'⚡ 히든: 참회 해금!':'⚡ Nascosto: Pentimento sbloccato!',
'배정됨':'Assegnato',
'합체 Lv.':'Fusione Lv.',
'◆ 같은 보석 스킬 습득 시 합체 가능':'◆ Fondibile imparando stessa gemma',
'▼ 가방 → 창고 보관':'▼ Zaino → Deposito',
'▲ 창고 → 가방 꺼내기':'▲ Deposito → Zaino',
'✓ 선택됨':'✓ Selezionato',
'⟨ 입력 대기... ⟩':'⟨ Waiting... ⟩',
'⟨ 대기 ⟩':'⟨ Wait ⟩',
'보조':'Secondario',
'키 설정 초기화 (또는 F5 키)':'Resetta tasti (o F5)',
'아무 키 또는 마우스 버튼을 누르세요 (ESC = 취소)':'Premi un tasto o bottone (ESC = annulla)',
'WebGPU 활성':'WebGPU Attivo',
'WebGL2 활성':'WebGL2 Attivo',
'측정 중...':'Misurazione...',
'불러오기 실패':'Caricamento fallito',
'장착':'Equipaggiato',
'🔒 중요잠금 아이템은 분해 선택 불가!':'🔒 Oggetti con blocco importante non selezionabili!',
'장비 강화 (실패 시 재료만 소멸)':'Potenzia equipagg. (se fallisce, materiali persi)',
'강화 보너스 적용':'Bonus potenziamento applicato',
'강화 실패!':'Potenziamento fallito!',
'장착된 장비가 없습니다.':'Nessun equipagg.',
'충분':'Sufficiente',
'더 필요':'Serve di più',
'장비 선택':'Seleziona equipagg.',
'목표치 설정':'Imposta obiettivo',
'악의 투입':'Investi malizia',
'자동 시도':'Tentativo auto',
'목표 강화치':'Potenziamento obiettivo',
'예상 필요 악의':'Malizia est. necessaria',
'보유':'Posseduto',
'강화 시작':'Inizia potenziamento',
'위에서 장비를 선택하세요':'Seleziona equipagg. sopra',
'⬆ 물약 강화 (최대 10단)':'⬆ Potenzia Pozione (max livello 10)',
'필요':'Richiesto',
'악의의 분해로 — 장비를 악의로 갈아버려라':'Fornace Malizia — Macina equipagg.',
'전체 선택':'Seleziona tutto',
'전체 해제':'Deseleziona tutto',
'희귀 이하':'Raro o inferiore',
'어픽스 리롤!':'Rilancia affisso!',
'영웅':'Eroico',
'전설':'Leggendario',
'무기 타입':'Tipo Arma',
'활 타입':'Tipo Arco',
'ST 부족':'ST insufficiente',
'💀 광폭화!':'💀 Infuriato!',
'...따라오는 거 아니야. 같은 방향일 뿐이지.':'...Non ti seguo. Stessa direzione e basta.',
'공기가 달라졌어. 더 썩었군.':'L\'aria è cambiata. Più marcio.',
'여기부터는 악마 영역이야. ...맘대로 해.':'Territorio demoniaco da qui. ...Fai come vuoi.',
'...이 냄새. 살점이 썩는 냄새야.':'...Quell\'odore. Carne in decomposizione.',
'여기 오래 있으면 미쳐. 나도, 너도.':'Resta troppo e impazzirai. Anch\'io.',
'이 길의 끝에 뭐가 있을까. ...알고 싶지도 않어.':'What\'s at the end of this road? ...I don\'t want to know.',
'...여기가 끝이야. 돌아갈 길은 없어.':'...Questa è la fine. Nessun ritorno.',
'작살을 땅에 꽂으면 끌려간다.':'Conficca il rampone nel suolo e sarai trascinato.',
'Shift로 작살 던져봐!':'Prova a lanciare il rampone con Shift!',
'패링 성공하면 ST가 회복된다. 공짜 자원이야.':'Parare recupera ST. Risorse gratuite.',
'패링 많이 하면 ST 걱정 없어~':'Para spesso e niente problemi di ST~',
'장비 분해하면 악의를 얻는다. 쓰레기도 자원이야.':'Smontare equipaggiamento dà Malizia. Anche la spazzatura è risorsa.',
'TAB 열어서 안 쓰는 장비 분해해!':'Apri TAB e smonta l\'equipaggiamento inutilizzato!',
'그로기 상태의 적에겐 1.5배 데미지가 들어간다.':'I nemici storditi subiscono 1.5x danni.',
'무릎 꿇으면 전력으로 때려!':'Quando si inginocchiano, colpisci con tutto!',
'속성 상성이 있다. 화염은 빙결에 약하고, 암전은 암흑에 약하다.':'Gli elementi hanno contatori. Fuoco debole a Ghiaccio, Fulmine a Oscurità.',
'무기 속성 바꿔가면서 싸워봐!':'Prova a cambiare l\'elemento dell\'arma!',
'빙결된 적은 1.5배 데미지를 받는다.':'I nemici congelati subiscono 1.5x danni.',
'얼리고 때리는 게 기본이야!':'Congela e colpisci — è la base!',
'보스의 빨간 공격은 패링 가능. 보라빛은 회피만.':'Gli attacchi rossi del boss si parano. Arcobaleno, solo schivare.',
'색깔 잘 봐! 빨강은 받아치고 무지개는 피해!':'Guarda i colori! Para il rosso, schiva l\'arcobaleno!',
'VIT를 올리면 최대 HP가 오른다. 죽기 싫으면 찍어.':'VIT alza gli HP massimi. Investi se vuoi sopravvivere.',
'STR은 근접, DEX는 활, INT는 마법! 골고루 말고 하나만!':'STR mischia, DEX arco, INT magia! Concentrati su uno!',
'E를 꾹 누르면 빔이 나간다. 짧게 누르면 투사체.':'Tieni E per il raggio. Premi breve per proiettile.',
'마법 쓸 때 MP 잘 봐! 빔은 연속으로 깎여!':'Controlla il MP con la magia! Il raggio drena velocemente!',
'핵터와 디로이가 아이템을 주워준다. 수거 범위 안이면.':'Hecter e Deroy raccolgono oggetti nel raggio.',
'우리한테 고마워해~ 안 주우면 썩잖아.':'Ringraziaci~ Se nessuno raccoglie, marciscono.',
'LCK를 올리면 레어 드롭률이 오른다.':'LCK aumenta il tasso di drop raro.',
'운빨 게임이긴 하지~ LCK 올려봐!':'È un gioco di fortuna~ Alza LCK!',
'강화하면 공격력이 쭉쭉 올라가! 악의만 있으면 돼!':'Potenziare alza l\'ATK velocemente! Serve solo Malizia!',
'강화 확률은 +1에서 99%. 높을수록 떨어진다.':'Probabilità di potenziamento inizia al 99% per +1. Diminuisce salendo.',
'실패하면 악의만 날아가~ 장비는 안 부서져!':'Se fallisci, solo la Malizia è persa~ L\'equipaggiamento sopravvive!',
'대장간에서 장비 제작도 된다. 악의 30000개면 영웅급 이상.':'La forgia può fabbricare equipaggiamento. 30000 Malizia per Eroico+.',
'랜덤이지만 좋은 거 나올 수도 있어!':'È casuale, ma potrebbe uscire qualcosa di buono!',
'쉴드는 마법으로, HP는 물리로 깎아야 제대로 먹힌다.':'Scudo con magia, HP con fisico per essere efficace.',
'반대로 치면 50%만 들어가! 무기 바꿔가면서 싸워!':'Il tipo sbagliato fa solo 50%! Cambia arma!',
'장비에 접두사, 접미사가 붙으면 특수 효과가 생긴다.':'L\'equipaggiamento con prefisso/suffisso ha effetti speciali.',
'영웅급 이상 장비에만 붙어! 좋은 거 나오면 강화해!':'Solo su equipaggiamento Eroico+! Potenzia quelli buoni!',
'강화는 장비를 바꿔도 자동 이전된다. 악의만 있으면.':'Il potenziamento si trasferisce automaticamente. Costa solo Malizia.',
'더 좋은 장비 나오면 바로 장착해! 강화 수치 그대로 옮겨가!':'Equipaggia l\'equipaggiamento migliore subito! Il potenziamento si trasferisce!',
'패링을 써야 자원을 흡수한다고!':'Devi parare per assorbire le risorse!',
'F키 회복의 영역을 써봐. 자원이 차올라.':'Prova F Dominio Sacro. Le risorse si riempiono.',
'적이 근접하면 스페이스키야! 가시덫을 활용해!':'Quando si avvicinano, Spazio! Usa Trappola di Spine!',
'기절시켜! 그로기가 터지면 데미지가 1.5배야!':'Stordiscili! Stordito significa 1.5x danni!',
'1번 대왕치기로 밀어버려!':'Usa tasto 1 Colpo Gigante per respingere!',
'무릎 꿇었다.':'Si inginocchia.',
'지금이야! 몰아쳐!!':'Adesso! Attacca!!',
'스킬 포인트 있어! K 눌러서 스킬 찍어봐!':'Hai punti! Premi K per le abilità!',
'...힘이 없으면 여기서 끝이야.':'...Senza potere, finisce qui.',
'...쓸 거 아니면 분해해.':'...Se non lo usi, smontalo.',
'아이템 넘쳐나네~ 우리가 주워줄게!':'Tanti oggetti~ Li raccoglieremo!',
'악의가 바닥이다.':'Senza Malizia.',
'TAB 열어서 장비 분해해! 쓰레기도 악의가 돼!':'Apri TAB e smonta! Anche la spazzatura diventa Malizia!',
'좋은 장비가 있네! G 눌러서 대장간 가봐!':'Buon equipaggiamento! Premi G per la forgia!',
'...강화 안 하면 그냥 고철이야.':'...Senza potenziamento, è solo rottame.',
'...멈추지 마. 여신은 기다리지 않는다.':'...Non fermarti. La dea non aspetta.',
'앞으로 가자~ 나도 여기 오래 있기 싫어.':'Andiamo avanti~ Neanch\'io voglio restare!',
'...냄새가 짙다. 큰 놈이 있어.':'...L\'odore è denso. Qualcosa di grosso.',
'준비됐어? 물약 확인하고!':'Pronto? Controlla le pozioni!',
'TAB을 눌러. 가방을 열고 장비를 입어야 한다.':'Premi TAB. Apri lo zaino e equipaggiati.',
'주웠으면 껴야지! TAB!':'L\'hai raccolto? Equipaggialo! TAB!',
'G. 대장간에서 물약도 제작할 수 있다.':'G. Puoi fabbricare pozioni alla forgia.',
'악의로 물약 만들어! G키야!':'Fabbrica pozioni con la Malizia! Tasto G!',
'기절이야! Ctrl 눌러!':'Stordito! Premi Ctrl!',
'Ctrl 유령걸음으로 탈출!':'Ctrl Passo Fantasma per fuggire!',
'Ctrl 얼음보주로 탈출!':'Ctrl Sfera di Ghiaccio per fuggire!',
'빨간 탄은 우클릭 패링. 무지개는 Q 패링.':'Proiettili rossi: parata clic destro. Arcobaleno: Q.',
'나머지는 전부 우클릭 패링 가능해!':'Tutto il resto si para con clic destro!',
'빨강=우클릭, 무지개=Q 패링. 나머진 다 쳐내.':'Rosso=clic destro, Arcobaleno=Q. Devia il resto.',
'무지개는 Q로 패링! 나머지는 전부 우클릭!':'Arcobaleno con Q! Tutto il resto clic destro!',
'빠져! 물약 마시고 안전한 곳에서 회복해.':'Indietreggia! Bevi pozioni e recupera.',
'자원 없으면 도망가는 게 답이야!':'Senza risorse? Fuggire è la risposta!',
'스페이스! 가시덫으로 적 묶어버려!':'Spazio! Blocca i nemici con la Trappola!',
'근접이 너무 많아! 거리 벌려!':'Troppa mischia! Crea distanza!',
'...둘러싸이면 끝이야. 빠져나와.':'...Se ti circondano, è finita. Esci.',
'1번 대왕치기로 쓸어버려!':'Usa tasto 1 Colpo Gigante per spazzare!',
'그로기 터지면 데미지 1.5배!':'Stordito attiva 1.5x danni!',
'회전참이나 광역기로 몰아! 한 놈씩 상대하면 죽어.':'Usa Turbine o AoE! Uno per uno e muori!',
'뭉쳐있을 때가 기회야!':'Quando si raggruppano, è la tua occasione!',
'E로 마력공격을 해봐! 악의 쉴드를 해제할려면 마법 공격을 해야 해!':'Prova E per gli attacchi magici! Serve magia per rompere gli scudi!',
'쉴드는 마법으로, HP는 물리로. 반대로 치면 데미지 안 들어간다.':'Scudo con magia, HP con fisico. Al contrario non fa danni.',
'L키로 스킬 슬롯에 넣어야 쓸 수 있어.':'Premi L per assegnare abilità agli slot.',
'C키를 눌러. 패시브 포인트가 쌓여있다.':'Premi C. I punti passivi si sono accumulati.',
'C키! 패시브 올리면 진짜 강해져!':'C! I passivi ti rendono molto più forte!',
'스태미나가 부족하다. 무리하지 마.':'Resistenza insufficiente. Non sforzarti.',
'ST 없으면 스킬 못 써! 잠깐 빠져!':'Senza ST niente abilità! Indietreggia!',
'탭 장비창을 열어봐. 아이템을 주워왔어!':'Apri TAB. Abbiamo raccolto un oggetto!',
'좋은 거 나왔다! TAB 열어서 확인해봐!':'È caduto qualcosa di buono! Apri TAB!',
'악의에 중독되면 악마가 돼서 부활력이 생긴대. 저 녀석처럼.':'Dicono che la dipendenza dalla Malizia ti trasforma in demone con potere di resurrezione. Come quello.',
'혹시 너도...?':'Forse anche tu...?',
'데미지가 부족하면 무기류 강화를 해야해!!':'Se manca danno, potenzia le armi!!',
'G키 대장간. 강화 안 하면 여기서 계속 죽어.':'G per la forgia. Senza potenziamenti, morirai qui.',
'시간이 없어. 움직여.':'Non c\'è tempo. Muoviti.',
'멍하게 서있으면 안 돼!':'Non restare fermo!',
'...뭘 기다리는 거야?':'...Cosa aspetti?',
'가자가자! 몬스터가 기다려!':'Andiamo! I mostri aspettano!',
'여기 오래 있으면 위험해.':'Restare qui troppo a lungo è pericoloso.',
'움직여야 해! 가만있으면 둘러싸여!':'Muoviti! Resta fermo e ti circondano!',
'쉬는 건 죽고 나서 해.':'Riposa dopo la morte.',
'살아있을 때 쉬면 안 돼!':'Niente riposo finché sei vivo!',
'적이 몰려오고 있어. 빨리 움직여.':'I nemici si avvicinano. Muoviti veloce.',
'냄새 맡고 올 거야. 빨리!':'Ti fiuteranno! Veloce!',
'...아직 살아있는 거 맞지?':'...Sei ancora vivo, vero?',
'혹시 잠든 거야...?':'Ti sei addormentato...?',
'...나무가 썩어가고 있어. 여기는 지옥의 입구야.':'...Gli alberi marciscono. Questo è l\'ingresso dell\'inferno.',
'냄새 지독해... 빨리 지나가자.':'Il fetore è orribile... Passiamo veloce.',
'조심해. 벌레굴이다. 벽이랑 바닥에서 기어나와.':'Attento. Nido di vermi. Escono da muri e pavimento.',
'으으... 벌레 싫어! 밟아버려!':'Ugh... Odio gli insetti! Calpestali!',
'...공기가 얼어붙는다. 여기선 화염이 먹힌다.':'...L\'aria gela. Il fuoco funziona qui.',
'추워... 빙결 조심해! 얼면 끝이야.':'Freddo... Attenzione al congelamento! Se ti congeli, è finita!',
'용암이다. 바닥을 밟으면 타 죽어.':'Lava. Calpesta il suolo e brucerai vivo.',
'뜨거워! 여기 왜 이렇게 빨개!':'Che caldo! Perché tutto è così rosso?!',
'...군단이다. 수가 많아. 광역기 없으면 밀려.':'...La legione. Troppi. Senza AoE sarai sopraffatto.',
'우글우글... 징그러워. 한꺼번에 쓸어!':'Brulicano ovunque... Disgustoso. Spazzali via tutti!',
'사도의 영역이야. 여기 놈들은 머리가 좋아.':'Territorio dell\'Apostolo. Questi sono intelligenti.',
'패턴이 복잡해졌어... 집중해!':'I pattern sono diventati complessi... Concentrati!',
'...끝이다. 지옥의 심장부. 살아 돌아가는 건 포기해라.':'...Questa è la fine. Il cuore dell\'inferno. Abbandona ogni speranza.',
'여기가 마지막이야... 각오해.':'Questa è la fine... Preparati.',
'석궁 자동발사 (T)':'Balestra automatica (T)',
'버스트루프 당기기 (H)':'Ciclo esplosivo attirare (H)',
'결정 자동합성':'Sintesi automatica cristallo',
'결정 자동강화':'Potenziamento automatico cristallo',
'✓ 설정 자동 저장':'✓ Impostazioni salvate automaticamente',
'세팅 프리셋 저장/불러오기':'Salva/carica preimpostazione',
'세팅1 저장':'Salva Preimpostazione 1','세팅1':'Preimpostazione 1',
'세팅2 저장':'Salva Preimpostazione 2','세팅2':'Preimpostazione 2',
'재진단':'Ri-diagnostica',
'게임 리셋 (처음부터)':'Reimposta gioco (dall\'inizio)',
'캐릭터 선택 (로비)':'Selezione personaggio (Lobby)',
'닫기 [ESC]':'Chiudi [ESC]','닫기 [G]':'Chiudi [G]','닫기 [V]':'Chiudi [V]','닫기 [C]':'Chiudi [C]',
'전체화면 (F11)':'Schermo intero (F11)',
'정말 모든 진행을 초기화하시겠습니까?':'Vuoi davvero reimpostare tutti i progressi?',
'검출 중...':'Rilevamento...',
'마우스 커서':'Cursore del mouse','그래픽 품질':'Qualità grafica','하드웨어 진단':'Diagnostica hardware',
'BGM 선택':'Selezione BGM',
'자동 (스테이지별)':'Automatico (per stage)','전체 랜덤':'Tutto casuale','로비':'Lobby',
'1장 랜덤':'Capitolo 1 casuale','2장 랜덤':'Capitolo 2 casuale','3장 랜덤':'Capitolo 3 casuale',
'4장 랜덤':'Capitolo 4 casuale','5장 랜덤':'Capitolo 5 casuale','6장 랜덤':'Capitolo 6 casuale','7장 랜덤':'Capitolo 7 casuale',
'보스':'Boss','최종보스':'Boss finale',
'대장간 랜덤':'Fucina casuale','사망 랜덤':'Morte casuale','승리 랜덤':'Vittoria casuale',
'지옥 추락 사망 징글':'Jingle morte caduta inferno','탈출 성공':'Fuga riuscita',
'── 1장 - 썩은 숲 ──':'── CH1 - Rotten Forest ──',
'── 2장 - 벌레굴 ──':'── CH2 - Worm Nest ──',
'── 3장 - 얼음굴 ──':'── CH3 - Ice Cavern ──',
'── 4장 - 화염지대 ──':'── CH4 - Infernal Wastes ──',
'── 5장 - 지옥군단 ──':'── CH5 - Hell Legion ──',
'── 6장 - 사도마굴 ──':'── CH6 - Apostle Den ──',
'── 7장 - 지옥성 ──':'── CH7 - Hell Citadel ──',
'── 공통 ──':'── Common ──',
'⌨ 조작법':'⌨ Controlli','클릭하면 닫힘':'Clicca per chiudere',
'전투력':'PC','가방':'Borsa','결정':'Cristallo',
'↕ 정렬':'↕ Ordina','쓰레기 전체선택':'Seleziona tutto il ciarpame','쓰레기 전부 분해':'Smantella tutto il ciarpame',
'창고':'Magazzino','스탯 포인트':'Punti attributo','능력치 요약':'Riepilogo statistiche','올 리셋':'Azzera tutto',
'대장간':'Fucina','스킬':'Abilità','능력치':'Statistiche',
'좌클스킬 (클릭 전환)':'Abilità clic sinistro (clic per cambiare)','우클스킬 (클릭 전환)':'Abilità clic destro (clic per cambiare)',
'이동스킬 (클릭 전환)':'Abilità movimento (clic per cambiare)','마법스킬 (클릭 전환)':'Abilità magia (clic per cambiare)',
'영역스킬 (클릭 전환)':'Abilità area (clic per cambiare)','피보호막 (클릭 전환)':'Scudo di sangue (clic per cambiare)',
'CT스킬 (클릭 전환)':'Abilità CT (clic per cambiare)','[C] 능력치':'[C] Statistiche',
'무기 공격':'Attacco con arma','칼등 처내기 (투사체 반사, 홀드 연사)':'Parata (respinge proiettili, tieni=raffica)',
'연속 처내기':'Parata continua','영역 스킬 (폭풍소환 등)':'Abilità area (Vortice ecc)',
'작살 발사':'Sparare arpione','마법 (탭=투사체, 홀드=빔)':'Magia (tocco=proiettile, tieni=raggio)',
'데빌포스 흡수':'Assorbire Forza Demoniaca','물약 / 스킬슬롯':'Pozioni / Slot abilità',
'스킬슬롯 5 / 필살기 / CT스킬':'Slot 5 / Definitiva / Abilità CT','스킬 슬롯 배정':'Assegnazione slot',
// --- Phase 27 additions ---
'위로 이동':'Muovi Su','아래로 이동':'Muovi Giù','왼쪽 이동':'Muovi Sinistra','오른쪽 이동':'Muovi Destra',
'칼등 처내기 (탭=처내기, 홀드=연사)':'Parata (tap=para, tieni=raffica)',
'영역 스킬':'Abilità area','작살 이동':'Scatto arpione',
'유령불꽃 켜기/끄기':'Fantasma Fiamma On/Off','기동칼날개 자동 켜기/끄기':'Lame-ali Auto On/Off',
'해상도':'Risoluzione',
'빛이 꺼졌다':'La Luce Svanisce','누군가는 너를 기다리고 있다':'Qualcuno ti aspetta',
'다시 일어서라':'Rialzati','로비로 돌아가기':'Torna alla lobby',
'☠ 사망 리플레이':'☠ Replay morte',
'지옥의 시련을 견뎌냈다':'Hai superato la prova dell\'inferno','계속 전투':'Continua a combattere',
'난이도를 선택하라':'Scegli la difficoltà',
'나중에 설정(ESC)에서 변경 가능':'Modificabile in Impostazioni (ESC)',
'일괄합성':'Fusione massiva','일괄강화+합성':'Potenziamento+Fusione massivi',
'자원 부족!':'Risorse insufficienti!',' 뎀':' DMG',
'합체 폭발!':'Esplosione di fusione!','MP 부족! (50)':'MP insufficiente! (50)',
'부활력 고갈!':'Resurrezione esaurita!','☠ 부활력 고갈!':'☠ Resurrezione esaurita!',
'독안개':'Nebbia Velenosa','뇌전창':'Lancia del Tuono',
'🔥 업화선 시전...':'🔥 Raggio dell\'Inferno in canalizzazione...',
'💥 기동파괴 그로기!':'💥 Groggy Catena Crush!',
'💥 칼등 그로기!':'💥 Groggy Parata!',
'⚡ 순간이동 준비!':'⚡ Teletrasporto Pronto!',
'👿악의+1000':'👿Malizia+1000',
'💀 내려찍기!':'💀 Schianto!',
'✟ 신성력 억제! +':'✟ Sacro Soppresso! +',
'✟ 신성력 억제!':'✟ Sacro Soppresso!',
'✟ 신성력 억제! (':'✟ Sacro Soppresso! (',
'💥 지진그로기!':'💥 Groggy Terremoto!',
'💥 기폭그로기!':'💥 Groggy Esplosione!',
'폭발! ×':'Esplosione! ×',
'⚫ 기둥강타!':'⚫ Colpo del Pilastro!',
'💥 대왕치기 그로기!':'💥 Groggy Colossale!',
'💫 미니스턴!':'💫 Mini Stordimento!',
'⚡ 뇌전창!':'⚡ Lancia del Tuono!',
'…절반이다. 정신차려.':'…Metà salute. Concentrati.',
'…죽기 직전이다. 한 발만 더.':'…Quasi morto. Un altro colpo.',
'…다음 한 방이 마지막이야.':'…Il prossimo colpo è l\'ultimo.',
'기절! ':'Stordito! ',
'마력이 빈다. 평타 섞어.':'MP sta finendo. Mescola gli attacchi normali.',
'그랩이다. 거리를 둬.':'Attacco presa. Mantieni distanza.',
'광역기다. 멀어져.':'Attacco area. Allontanati.',
'…아파? 당연하지. 여긴 지옥이야.':'…Fa male? Ovvio. Questo è l\'inferno.',
'F키도 스킬 슬롯이야!':'Anche F è uno slot abilità!',
'L-CTRL로 유령걸음/얼음보주!':'L-CTRL per Passo Fantasma/Sfera di Ghiaccio!',
'V 눌러서 창고에 넣어둬!':'Premi V per mettere in magazzino!',
'ESC로 설정! 난이도/자동물약!':'ESC per impostazioni! Difficoltà/Auto-pozione!',
'잡몹이다. 먼저 정리해.':'Mostri normali. Prima elimina quelli.',
'…얼어붙은 놈은 오래 안 간다.':'…Un congelato non durerà a lungo.',
'…냄새가 짙다. 큰 놈이 있어.':'…L\'odore è forte. Qualcosa di grande nelle vicinanze.',
'쉴드는 마법으로, HP는 물리로.':'Lo scudo subisce magia, HP subisce fisico.',
'스페이스! 가시덫으로 적 묶어!':'Space! Intrappola i nemici con Trappola Spine!',
'근접 너무 많아! 거리 벌려!':'Troppi in mischia! Allontanati!',
'회전참이나 광역기로 몰아!':'Usa Fendente Rotante o AOE!',
'F 눌러! 회복의 영역 깔아!':'F! Piazza il Dominio Sacro!',
'F키 회복의 영역을 써봐.':'Prova F-key Dominio Sacro.',
'빠져! 물약 마시고 회복해.':'Indietro! Bevi una pozione e recupera.',
'쉬프트! 사슬기동은 이동기야!':'Shift! La catena è un movimento!',
'스킬포인트 쌓였어! K 눌러!':'Punti abilità accumulati! Premi K!',
'스킬 포인트 있어! K!':'Hai punti abilità! K!',
'C키. 패시브 포인트가 쌓여있다.':'Tasto C. I punti passivi si sono accumulati.',
'…쓸 거 아니면 분해해.':'…Smantella quello che non usi.',
'…강화 안 하면 그냥 고철이야.':'…Senza potenziamento è solo rottame.',
'빨간 탄은 우클릭. 무지개는 Q.':'Proiettili rossi: clic destro. Arcobaleno: Q.',
'빨강=우클릭, 무지개=Q.':'Rosso=clic destro, arcobaleno=Q.',
'…멈추지 마. 여신은 기다리지 않는다.':'…Non fermarti. La dea non aspetta.',
'패턴이 바뀐다. 거리를 둬.':'Il pattern cambia. Mantieni distanza.',
'미쳐가고 있어. 광폭화다.':'Sta impazzendo. Furia.',
'마지막이야! 끝장내!':'Fase finale! Finiscilo!',
'…끝났다. 다음으로.':'…È finita. Avanti.',
'다 잡았다! 포탈 어딨어?':'Tutti eliminati! Dov\'è il portale?',
'근육으로 만든 빌드군. 베고 부숴.':'Build muscolosa. Taglia e spacca.',
'활을 쥐었군. 거리를 둬.':'Ha un arco. Mantieni distanza.',
'마법사군. MP 관리부터 배워라.':'Un mago. Prima impara a gestire l\'MP.',
'운에 기댄 빌드군. …드롭은 좋겠어.':'Build basata sulla fortuna. …Almeno i drop saranno buoni.',
'…VIT가 너무 낮아. 한 방에 죽는다.':'…VIT troppo bassa. Muori in un colpo.',
'다 찍으면 다 약해진다. 하나만 골라.':'Maximi tutto e sei debole ovunque. Scegline uno.',
'…3단. 적이 강해져. 정신 차려.':'…Stadio 3. I nemici si rafforzano. Concentrati.',
'5단이다. …너도 강해졌단 뜻이야.':'Stadio 5. …Significa che anche tu sei cresciuto.',
'…7단. 아직 살아있단 게 신기하군.':'…Stadio 7. Ancora vivo. Sorprendente.',
'10단. …너는 이제 인간이 아니야.':'Stadio 10. …Non sei più umano.',
'…일반으로 내려왔군. 가끔은 쉬어가야지.':'…Sceso a Normale. A volte bisogna riposarsi.',
'…이게 진짜 패링이야.':'…Questa è una vera parata.',
'…피가 묻기 시작했군.':'…Il sangue comincia a scorrere.',
'100. 너는 인간이 아니야.':'100. Non sei umano.',
'…피 흘리며 베는군.':'…Tagli attraverso il sangue.',
'빨간콩이 푸르게 변했다. 그게 너의 무기야.':'Il fagiolo rosso è diventato blu. È la tua arma.',
'무지개를 받아쳤군. 그건 진짜 어렵다.':'Hai parato un arcobaleno. È davvero difficile.',
'…너무 빨라. 닿기 직전에 눌러.':'…Troppo veloce. Premi appena prima del contatto.',
'악의가 가득 찼다. 풀어내.':'La malizia è piena. Rilasciala.',
'작살이 살을 뚫었어. 끌고 와.':'L\'arpione ha trafitto la carne. Trascina.',
'…풀차지군. 멀리 던져버려.':'…Carica piena. Lancia lontano.',
'…빈틈을 그대로 빠져나갔다.':'…Scivolato proprio attraverso la falla.',
'…일반 잡몹이 아니야. 모디파이어 붙었군.':'…Non è un mostro normale. Ha un modificatore.',
'엘리트 하나 처리.':'Elite abbattuto.',
'…큰 놈이다. 일반 잡몹 정리부터.':'…Un pezzo grosso. Prima elimina i normali.',
'미니보스 처리. 다음 길로.':'Mini-boss abbattuto. Avanti.',
'한 번에 다섯. 깔끔해.':'Cinque in una volta. Pulito.',
'100강. 이제 뭔가 다르게 보이는군.':'+100. Le cose sembrano diverse ora.',
'…운이 없는 날이야.':'…Giornata sfortunata.',
'…전설이다. 이런 건 처음 본다.':'…Leggendario. Non ho mai visto niente del genere.',
'…죽었다 살아났네. 여신은 너를 포기 안 했어.':'…Morto e tornato. La dea non ti ha abbandonato.',
'…또야? 패턴 좀 외워!':'…Ancora? Impara il pattern!',
'…한 번도 안 죽고. 그건 진짜 실력이야.':'…Mai morto. Questa è vera abilità.',
'…ACT1을 끝냈다. 진짜 시작은 여기서부터야.':'…ATTO1 completato. Il vero inizio è qui.',
'모든 보스를 무너뜨렸다. 너는 지옥의 일부야.':'Tutti i boss caduti. Sei parte dell\'inferno.',
'…30초. 너 진짜 미쳤구나.':'…30 secondi. Sei davvero pazzo.',
'…빠르군. 효율적이야.':'…Veloce. Efficiente.',
'신기록이다.':'Nuovo record.',
'탭 장비창을 열어봐.':'Apri la finestra equipaggiamento con TAB.',
'데미지 부족하면 무기 강화!':'Danno insufficiente? Potenzia l\'arma!',
// --- Loading screen ---
'불러오는 중...':'Caricamento...',
'로딩중...':'Caricamento...',
'맵과 몬스터 불러오는 중...':'Caricamento mappa e mostri...',
'기본 데이터 준비 중...':'Preparazione dati di base...',
'저장 데이터 불러오는 중...':'Caricamento dati salvati...',
'몬스터 스킨 로딩...':'Caricamento skin dei mostri...',
'맵과 몬스터 생성 중...':'Generazione mappa e mostri...',
'맵 에셋 로딩...':'Caricamento risorse mappa...',
'맵 환경 준비 중...':'Preparazione ambiente mappa...',
'주변 청크 준비 중...':'Preparazione chunk vicini...',
'맵 캐시 생성 중...':'Costruzione cache mappa...',
'미니맵 빌드 중...':'Costruzione minimappa...',
// Phase 28
' 으로 탈출!':' per scappare!',
'100명?! 미쳤어!':'100 nemici?! Sei pazzo!',
'10단 최고난이도! 너 진짜 광기야!':'Difficoltà 10 al massimo! Sei completamente folle!',
'1분 안에 클리어! 빠르네!':'Livello completato in 1 min! Così veloce!',
'30초!! 스피드런 가능해!':'30 secondi!! Potenziale speedrun!',
'3단! 보상도 좋아지지만 죽기 쉬워!':'Diff 3! Ricompense migliori ma più facile morire!',
'50명! 학살자야!':'50 nemici! Sei un massacratore!',
'5단!! 진짜 게이머 인증!':'Diff 5!! Vero gamer certificato!',
'7단!! 다른 사람들 이 정도 못 와!':'Diff 7!! Gli altri non arrivano così lontano!',
'ACT1 완주! 우리가 진짜 해냈어!':'ACT1 completato! Ce l\'abbiamo davvero fatta!',
'Ctrl 얼음보주로 탈출하라.':'Ctrl — scappa con l\'Orbe di Ghiaccio.',
'Ctrl 유령걸음으로 탈출하라.':'Ctrl — scappa con il Passo Fantasma.',
'C키! 패시브 강해져!':'Tasto C! I passivi diventano più forti!',
'DEX 빌드! 거리에서 패고, 추적탄 좋아!':'Build DES! Attacca a distanza, i proiettili guidati sono ottimi!',
'E로 마력공격을 해봐!':'Prova l\'attacco magico con E!',
'G 눌러서 대장간 가봐!':'Premi G per visitare la fucina!',
'G키 대장간. 강화 안 하면 계속 죽어.':'G — fucina. Senza potenziamenti, continuerai a morire.',
'HP 70%! 조심해!':'HP 70%! Stai attento!',
'INT 빌드! 빔이랑 폭발 마법! MP 잘 봐!':'Build INT! Raggi e magia esplosiva! Tieni d\'occhio il MP!',
'LCK 높아! 레어 드롭률 미친 거 알지?':'FOR alta! Sai che i tassi di drop sono folli, vero?',
'L로 어디에 뭘 넣을지 골라!':'Premi L per scegliere cosa va in ogni slot!',
'MP 부족! 평타로 패면서 회복해!':'MP basso! Colpisci con attacchi base per recuperare!',
'ST 없으면 스킬 못 써!':'Senza ST, nessuna abilità!',
'STR 빌드! 회전참, 회오리, 광역기 추천!':'Build FOR! Colpo rotante, turbine, AoE raccomandato!',
'VIT 좀 찍어! HP 너무 적어!':'Aggiungi un po\' di VIT! L\'HP è troppo basso!',
'Z 누르면 대박! 쿨타임 길어!':'Premi Z per il colpo forte! Ma il cooldown è lungo!',
'…고기 냄새. 싫진 않네.':'…Odore di sangue. Non è sgradevole.',
'…둘러싸이면 끝이야.':'…Vieni circondato ed è finita.',
'…말은 못해.':'…Non riesco a parlare.',
'…버리기 아까운 건 창고에.':'…Ciò che vale la pena tenere va nel magazzino.',
'…빈틈을 노려.':'…Cerca le aperture.',
'…설정을 확인해.':'…Controlla le tue impostazioni.',
'…슬롯을 채워. 빈 손은 죽음이다.':'…Riempi i tuoi slot. Le mani vuote significano morte.',
'…아직 살아있네. 좌클릭으로 저것들 쳐봐.':'…Ancora vivo. Prova a colpirli con il clic sinistro.',
'…운이 좋았을 뿐이야. 아마.':'…Solo fortuna. Probabilmente.',
'…치는 건 할 줄 아네. 피하는 건?':'…Sai come colpire. E schivare?',
'…힘을 골라라. 전부 가질 순 없다.':'…Scegli la tua forza. Non si può avere tutto.',
'골고루 안 돼! 하나로 밀어!':'Non distribuire le statistiche! Punta su una!',
'그로기 터지면 1.5배!':'Stordito = 1,5x danni!',
'길이 열렸다.':'Il percorso è aperto.',
'나머진 전부 우클릭 패링 가능!':'Tutto il resto può essere parato con il clic destro!',
'나머진 전부 우클릭!':'Tutto il resto — clic destro!',
'다섯 번 연속! 내가 본 인간 중 최고!':'Cinque di fila! Il miglior umano che abbia mai visto!',
'다음엔 죽지 마!':'Non morire la prossima volta!',
'더블탭 전격이동으로 탈출하라.':'Doppio tocco per scivolare e scappare.',
'소환수 왔어! 먼저 처리해야 해!':'Evocazioni in arrivo! Eliminale prima!',
'스킬 없으면 방향키 연타뿐이야.':'Nessuna abilità? Tieni premuti i tasti direzionali.',
'신기록!! 스트리머한테 보내!':'Nuovo record!! Mandalo a uno streamer!',
'아이템 넘쳐! 우리가 주워줄게!':'Borsa piena! Raccoglieremo le cose per te!',
'안 죽고 깼어! 진짜 천재 맞네!':'Completato senza morire! Vero genio!',
'앞으로 가자~':'Andiamo avanti~',
'우리가 해냈어! 다음 챕터 가자!':'Ce l\'abbiamo fatta! Al prossimo capitolo!',
'일반 모드! 편하게 즐기자!':'Modalità normale! Godiamocela tranquilli!',
'자원이 반이다. F키로 회복해.':'Risorse a metà. Premi F per recuperare.',
'잡힌다! 옆으로 빠져!':'Sto per essere afferrato! Muoviti di lato!',
'장비 분해해! 쓰레기도 악의!':'Smantella l\'equipaggiamento! Anche la spazzatura dà malizia!',
'전부 다 잡았어! 우리가 지옥의 왕이야!':'Li abbiamo presi tutti! Siamo i re dell\'inferno!',
'좋은 거 나왔다! TAB!':'Bottino buono caduto! TAB!',
'죽기 직전에 죽이다니! 멋져!':'Uccidere prima di morire! Fantastico!',
'체력 반 남았어! 물약 마실 타이밍!':'Metà HP rimasti! Ora di bere una pozione!',
'큰 거 온다! 도망쳐!':'Grande attacco in arrivo! Scappa!',
'패링으로 돌려주고, Q 보호막도 써!':'Para per riflettere, e usa anche lo scudo Q!',
'패턴이 빨라졌어!':'I pattern si sono accelerati!',
'한 대만 맞아도 죽어! 패링이든 회피든!!':'Un colpo e muori! Para o schiva!!',
'한 방이면 죽어! 도망쳐!!':'Un colpo uccide! Scappa!!',
'화염엔 빙결! 암전엔 암흑!':'Fuoco → gelo! Vuoto → ombra!',
'👻 유령!':'👻 Fantasma!',
'🦴 해골무덤!':'🦴 Tomba di Ossa!',
'☠ 부활력 고갈!':'☠ Resurrezione Esaurita!',
};

const _IT_PFX={
'녹슨':'Arrugginito','강철':'Acciaio','흑요석':'Ossidiana','미스릴':'Mithril','심판의':'Giudizio','천벌의':'Ira Divina','파멸의':'Distruzione','불꽃':'Fiamma','화염':'Inferno','염화':'Fuoco Infernale','지옥불':'Fiamma Infernale','지옥화':'Fiamma Infernale','지옥':'Fiamma Infernale','멸화의':'Annientante','냉기':'Gelo','빙결':'Congelato','빙하':'Glaciale','서리의':'Brina','서리':'Brina','영겁빙':'Ghiaccio Eterno','그림자':'Ombra','암흑':'Oscuro','심연':'Abissale','나락의':'Infero','나락':'Infero','무간의':'Vuoto','전기':'Scintilla','낙뢰':'Tuono','암전':'Fulmine','뇌신의':'Dio Tuono','뇌신':'Dio Tuono','만뢰의':'Mille Tuoni','축복':'Benedetto','성광':'Luce Sacra','신성':'Sacro','천사의':'Angelico','신벌의':'Giudizio Divino','낡은':'Logoro','천':'Tela','가죽':'Pelle','강철사':'Trama Acciaio','은':'Argento','은사':'Filo d\'Argento','화염의':'Inferno','빙결의':'Congelato','암흑의':'Oscuro','암전의':'Fulmine'
};
const _IT_BASE={
'대검':'Spadone','석궁':'Balestra','연사석궁':'Balestra Ripetizione','마력석궁':'Balestra Arcana','견갑':'Scudo','대견갑':'Grande Scudo','전투화':'Stivali Combattimento','갑옷':'Armatura','갑주':'Armatura','왕관':'Corona','장갑':'Guanti','건틀릿':'Guanti Corazzati','바지':'Pantaloni','각반':'Schinieri','허리띠':'Cintura','벨트':'Cintura','부적':'Talismano','목걸이':'Collana','반지':'Anello','망토':'Mantello','팔찌':'Bracciale','귀걸이':'Orecchino'
};
