// 지옥의 길 — Bahasa Indonesia (id)
const _ID={
'썩은 숲':'Hutan Busuk',
'숲의 감시자':'Penjaga Hutan',
'독버섯 거인':'Raksasa Jamur Beracun',
'숲의 사냥꾼':'Pemburu Hutan',
'숲의 기생수':'Makhluk Parasit',
'1장 — 썩은 숲':'Bab1 — Hutan Busuk',
'2장 — 벌레굴':'Bab2 — Sarang Cacing',
'3장 — 얼음굴':'Bab3 — Gua Es',
'4장 — 고통의 화염지대':'Bab4 — Tanah Neraka',
'5장 — 지옥의 군단':'Bab5 — Legiun Neraka',
'6장 — 사도의 마굴':'Bab6 — Sarang Rasul',
'7장 — 지옥성':'Bab7 — Benteng Neraka',
'탈출!':'Kabur!',
'처치':'tewas',
'경험치':'EXP',
'최대콤보':'Kombo Maks',
'일어나. 여신이 널 여기 보낸 건 죽으라고가 아니야.':'Bangun. Dewi tidak mengirimmu ke sini untuk mati.',
'좋아, 감각이 있군. 계속 쳐!':'Bagus, kau punya insting. Terus serang!',
'Shift를 눌러. 작살이다. 땅에 꽂아서 끌려가!':'Tekan Shift. Itu tombak. Tancapkan dan meluncur!',
'작살로 끌려가는 중엔 무적이다. 위험할 때 쓰면 좋아.':'Kau kebal saat ditarik tombak. Gunakan saat bahaya.',
'...아파? 당연하지. 여긴 지옥이야.':'...Sakit? Tentu saja. Ini neraka.',
'Q를 눌러! 악의로 보호막을 만들 수 있다.':'Tekan Q! Buat perisai dengan kebencian.',
'보호막 없이 버틸 생각은 버려.':'Lupakan bertahan tanpa perisai.',
'우클릭이 패링이다. 적 공격이 닿기 직전에 눌러!':'Klik kanan untuk parry. Tekan tepat sebelum musuh menyerang!',
'못 하겠으면 때려. 안 죽으면 그만이야.':'Tidak bisa parry? Pukul saja. Tidak mati sudah cukup.',
'됐어! 감 잡았구나.':'Nah! Mulai terbiasa.',
'하나 죽었군.':'Satu tumbang.',
'유령쇠뇌야. 인사해.':'Itu panah hantu. Sapa dia.',
'빨간 탄을 무서워하지 마. 악의가 강하다.':'Jangan takut peluru merah. Kebencian itu kuat.',
'패링으로 돌려주고, Q 보호막도 써! 악의를 잘 굴려!':'Parry balik, pakai perisai Q juga! Kuasai kebencianmu!',
'무지개빛은 패링 불가! 피해!':'Tembakan pelangi tidak bisa di-parry! Menghindar!',
'피가 새고 있다. Shift. 빠져.':'Kau berdarah. Shift. Keluar.',
'물약 있잖아! 숫자키!':'Kau punya ramuan! Tombol angka!',
'우클릭. 적 손목이 꺾일 때 쳐.':'Klik kanan. Serang saat pergelangan mereka menekuk.',
'빨간 탄은 악의 덩어리다. 쳐내서 이용해.':'Peluru merah gumpalan kebencian. Tangkis dan gunakan.',
'무지개빛만 피하면 돼! 나머지는 다 패링!':'Cukup hindari pelangi! Parry sisanya!',
'Q 보호막도 패링이 가능해!':'Perisai Q juga bisa parry!',
'위험해! 쉬프트 사슬기동으로 피해!!':'Bahaya! Shift rantai untuk kabur!!',
'쉬프트! 사슬기동은 이동기야! 끌려가면서 무적이라고!':'Shift! Dash rantai gerakan! Kebal saat ditarik!',
'스킬포인트가 쌓였어! K 눌러서 스킬 배우자!':'Poin skill siap! Tekan K untuk belajar skill!',
'속성을 읽어. 약점을 찌르면 두 배로 썩는다.':'Baca elemen. Serang kelemahan untuk damage ganda.',
'K를 눌러봐! 스킬을 배울 수 있어!':'Tekan K! Belajar skill!',
'C 눌러서 능력치 찍어! 패시브도 있어~':'Tekan C untuk stat! Pasif juga~',
'G를 눌러. 대장간에서 장비를 강화할 수 있다.':'Tekan G. Tingkatkan perlengkapan di pandai besi.',
'F키도 스킬 슬롯이야! 스킬 많으면 L로 배정해봐~':'Tombol F juga slot skill! Pakai L untuk atur~',
'Z. 필살기다. 아껴 써라.':'Z. Itu jurus pamungkas. Gunakan dengan bijak.',
'L-CTRL로 유령걸음이나 얼음보주 쓸 수 있어!':'L-CTRL untuk Ghost Walk atau Ice Orb!',
'L을 눌러. 스킬 슬롯을 정리해야 한다.':'Tekan L. Atur slot skill.',
'가방 터지겠다! V 눌러서 창고에 넣어둬!':'Tas hampir penuh! Tekan V untuk simpan!',
'ESC로 설정 열 수 있어! 난이도 바꾸기, 자동물약 조절~':'ESC untuk pengaturan! Kesulitan, auto-potion~',
'...아직 살아있네. 좌클릭으로 저것들 쳐봐.':'...Masih hidup. Coba pukul mereka dengan klik kiri.',
'...치는 건 할 줄 아네. 피하는 건?':'...Bisa mukul. Tapi bisa menghindar?',
'흥, 작살 못 맞추면 헛수고야.':'Hmph, meleset tombaknnya dan sia-sia.',
'...운이 좋았을 뿐이야. 아마.':'...Cuma keberuntungan. Mungkin.',
'...고기 냄새. 싫진 않네.':'...Baunya seperti daging. Lumayan.',
'...말은 못해.':'...Dia tidak bisa bicara.',
'예쁘다고 만지면 죽어.':'Sentuh karena cantik? Kau akan mati.',
'작살 던져! 끌려가면 무적이야!':'Lempar tombak! Kebal saat ditarik!',
'...마시든 말든. 네 목숨이니까.':'...Minum atau tidak. Hidupmu.',
'그게 패링이야! 타이밍이 전부야~':'Itu parry! Timing adalah segalanya~',
'화염엔 빙결! 암전엔 암흑! 기억해!':'Api mengalahkan Es! Petir mengalahkan Gelap! Ingat!',
'...얼어붙은 놈은 오래 안 간다.':'...Yang beku tidak bertahan lama.',
'얼었어! 빙결 중 1.5배야!':'Beku! 1.5x damage saat beku!',
'...힘을 골라라. 전부 가질 순 없다.':'...Pilih kekuatanmu. Tidak bisa punya semuanya.',
'스탯을 올려. 살고 싶으면.':'Naikkan stat. Kalau mau hidup.',
'좋은 장비는 강화해야 진짜 힘을 발휘해!':'Perlengkapan bagus perlu upgrade!',
'...슬롯을 채워. 빈 손은 죽음이다.':'...Isi slot. Tangan kosong berarti mati.',
'Z 누르면 대박! 쿨타임 길어서 타이밍 봐야 해!':'Tekan Z untuk damage besar! Cooldown lama!',
'Ctrl. 위기에 쓸 카드가 하나 늘었군.':'Ctrl. Satu kartu lagi untuk darurat.',
'스킬이 많아졌네~ L로 어디에 뭘 넣을지 골라!':'Banyak skill~ Pakai L untuk atur!',
'...버리기 아까운 건 창고에.':'...Simpan yang terlalu bagus untuk dibuang.',
'...살아남은 것만으로도 대단하군. 설정을 확인해.':'...Bertahan saja sudah hebat. Cek pengaturan.',
'MP 부족!':'MP tidak cukup!',
'ST 부족!':'ST tidak cukup!',
'악의 부족!':'Kebencian tidak cukup!',
'충전 중...':'Mengisi...',
'캔슬':'Batal',
'아이템 선택 필요':'Pilih item',
'악의 소진...':'Kebencian habis...',
'비문 발견...':'Prasasti ditemukan...',
'HP물약!':'Ramuan HP!',
'HP물약 +1':'Ramuan HP +1',
'HP물약 +2':'Ramuan HP +2',
'HP/MP/ST 회복!':'HP/MP/ST Pulih!',
'보물상자 개봉!':'Peti Dibuka!',
'익사!':'Tenggelam!',
'피웅덩이!':'Kolam Darah!',
'독혈!':'Darah Beracun!',
'잡힘!':'Tercengkeram!',
'콤보 종료':'Kombo Selesai',
'빙결!':'Beku!',
'화상!':'Terbakar!',
'독!':'Racun!',
'감전!':'Tersengat!',
'기절!':'Terkejut!',
'봉인됨!':'Tersegel!',
'관통!':'Tembus!',
'기검참':'Ki Slash',
'악의구':'Bola Kebencian',
'회전참':'Angin Puyuh',
'기폭팔':'Ledakkan',
'칼등 처내기':'Parry Pisau',
'만화방창':'Hujan Jarum',
'멸살광선':'Sinar Pemusnah',
'원소추적탄':'Pencari Elemen',
'악의 보호자':'Penjaga Kebencian',
'악의 사냥':'Buru Kebencian',
'폭풍소환':'Panggil Pusaran',
'해골무덤':'Makam Tulang',
'\u{1F47B} 유령!':'\u{1F47B} Hantu!',
'\u{1F9B4} 해골무덤!':'\u{1F9B4} Makam Tulang!',
'신성폭발':'Ledakan Suci',
'블랙':'Bintang Hitam',
'용암소환':'Panggil Lava',
'처형':'Eksekusi',
'악마화 부활':'Kebangkitan Iblis',
'붉은꽃':'Mekar Merah',
'얼음보주':'Bola Es',
'뇌전걸음':'Langkah Hantu',
'만화방창 II':'Hujan Jarum II',
'마력연사':'Tembakan Sihir',
'마력광선':'Laser Busur',
'업화선':'Sinar Api Neraka',
'지옥진':'Formasi Neraka',
'폭독칼날':'Pisau Wabah',
'악의폭풍':'Badai Kebencian',
'악의기둥':'Pilar Gelap',
'회복의 영역':'Domain Suci',
'구속의 영역':'Domain Pengikat',
'아이스스톰':'Badai Es',
'대왕치기':'Hantaman Raksasa',
'대왕치기 2':'Hantaman Raksasa II',
'기동불꽃':'Rantai Kobaran',
'기동파괴':'Rantai Remuk',
'기동칼날개':'Rantai Sayap Pisau',
'평화의보호':'Perisai Kedamaian',
'참회':'Pertobatan',
'칼등날개':'Sayap Perisai',
'폭산탄':'Tembakan Ledak',
'파쇄의 영역':'Domain Penghancur',
'침식의 영역':'Domain Korosi',
'관통의 영역':'Domain Tembus',
'부활의 영역':'Domain Kebangkitan',
'가시덫':'Jebakan Duri',
'푸른비':'Hujan Biru',
'버스트루프':'Lingkaran Ledak',
'유령 허수아비':'Umpan Hantu',
'폭발 허수아비':'Umpan Peledak',
'공성쇠뇌':'Panah Pengepungan',
'사슬기동:충돌':'Dash Rantai: Benturan',
'사슬기동:화염':'Dash Rantai: Api',
'전격이동':'Langkah Kilat',
'기동칼날개!':'Sayap Pisau!',
'기동불꽃!':'Rantai Kobaran!',
'기동파괴!':'Rantai Remuk!',
'사슬이동:강화!':'Dash Rantai!',
'사슬기동:화염!':'Api Rantai!',
'작살!':'Tombak!',
'진입!':'Masuk!',
'레인라이트닝!':'Hujan Petir!',
'마력연사!':'Tembakan Sihir!',
'🔷 마력광선!':'🔷 Arc Laser!',
'광선 해제':'Laser Mati',
'MP 부족 — 광선 해제':'MP habis — Laser Mati',
'집중...':'Fokus...',
'시전...':'Menggunakan...',
'만화방창!':'Hujan Jarum!',
'바늘출!':'Ledakan Jarum!',
'칼날!':'Pisau!',
'착지!':'Mendarat!',
'체간삭감!':'Keseimbangan Break!',
'기동전폭 준비!':'Rantai Ledak Siap!',
'기동불꽃 준비!':'Rantai Api Siap!',
'기동파괴 준비!':'Rantai Remuk Siap!',
'유령불꽃 ON':'Api Hantu ON',
'유령불꽃 OFF':'Api Hantu OFF',
'기동칼날개 AUTO ON':'Sayap Pisau AUTO ON',
'기동칼날개 AUTO OFF':'Sayap Pisau AUTO OFF',
'자동 버스트!':'Ledakan Otomatis!',
'연사 해제':'Tembakan Cepat Mati',
'당기기 모드':'Mode Tarik',
'밀어내기 모드':'Mode Dorong',
'날개치기':'Serangan Sayap',
'처내기':'Parry',
'Shift: 작살 발사 → 끌려감':'Shift: Lempar tombak → tarik',
'Shift: 화염길+화상':'Shift: Jejak api+bakar',
'CT: 전류변신+뇌전걸음 (쿨4초)':'CT: Bentuk petir+Langkah Hantu (CD 4d)',
'CT: 방어구체+빙결 (재입력: 파쇄)':'CT: Bola es+beku (tekan lagi: pecah)',
'근접':'Jarak Dekat',
'견갑':'Penjaga',
'작살':'Tombak',
'마법':'Sihir',
'보막':'Perisai',
'유령':'Hantu',
'스킬':'Skill',
'대장':'Pandai Besi',
'인벤':'Tas',
'인벤토리':'Inventaris',
'복수의 대장간':'Pandai Besi Dendam',
'패시브 스킬':'Skill Pasif',
'전투 스킬':'Skill Tempur',
'캐릭터 선택':'Pilih Karakter',
'물리':'Fisik',
'화염':'Api',
'빙결':'Beku',
'암흑':'Gelap',
'암전':'Petir',
'신성':'Suci',
'대지':'Tanah',
'힘':'Kekuatan',
'민첩':'Ketangkasan',
'지능':'Kecerdasan',
'행운':'Keberuntungan',
'맹공':'Serangan Gencar',
'철벽':'Ketabahan',
'돌파':'Terobosan',
'반격':'Pembalasan',
'마력폭주':'Lonjakan Sihir',
'정밀사격':'Tembakan Presisi',
'수호':'Penjaga',
'수호신':'Roh Penjaga',
'회복력':'Pemulihan',
'급소':'Serangan Vital',
'약탈':'Rampasan',
'관통':'Penetrasi',
'마력회복':'Pemulihan Mana',
'쇠뇌력':'Penguasaan Panah',
'광전사':'Berserker',
'추적자':'Pelacak',
'물리관통':'Penetrasi Fisik',
'마법관통':'Penetrasi Sihir',
'녹슨 대검':'Pedang Besar Berkarat',
'강철 대검':'Pedang Besar Baja',
'흑요석 대검':'Pedang Besar Obsidian',
'낡은 석궁':'Panah Silang Usang',
'강철 석궁':'Panah Silang Baja',
'흑요석 석궁':'Panah Silang Obsidian',
'대검':'Pedang Besar',
'석궁':'Panah Silang',
'연사석궁':'Panah Tembak',
'마력석궁':'Panah Sihir',
'악의 추출':'Ekstrak Kebencian',
'악의':'Kebencian',
'필살기':'Jurus Pamungkas',
'필살기 해제':'Lepas Jurus Pamungkas',
'이전':'Transfer',
'강화':'Tingkatkan',
'개봉!':'Dibuka!',
'여신의 가호':'Berkah Dewi',
'과부하!':'Kelebihan Beban!',
'맹독의':'Beracun',
'불꽃의':'Menyala',
'냉기의':'Sangat Dingin',
'번개의':'Voltaik',
'암흑의':'Terkutuk',
'관통의':'Menembus',
'광폭의':'Berang',
'파쇄의':'Penghancur',
'연쇄의':'Berantai',
'학살의':'Pembunuh',
'폭발의':'Peledak',
'집중의':'Terfokus',
'쾌속의':'Cepat',
'패리의':'Membelokkan',
'추적자의':'Penguntit',
'작살의':'Tombak',
'궁극의':'Tertinggi',
'집중력의':'Cermat',
'강인의':'Tangguh',
'수호의':'Penjagaan',
'활력의':'Vital',
'신속의':'Dipercepat',
'화염수호':'Penjaga Api',
'빙결수호':'Penjaga Es',
'암전수호':'Penjaga Petir',
'암흑수호':'Penjaga Gelap',
'독수호':'Penjaga Racun',
'전원소수호':'Penjaga Semua',
'강철의':'Berlapis Besi',
'반사의':'Memantulkan',
'가시의':'Berduri',
'흡수의':'Menyerap',
'인내의':'Bertahan',
'위기의':'Putus Asa',
'피격반격의':'Membalas',
'패링폭발의':'Ledakan Parry',
'스태거폭발의':'Ledakan Terhuyung',
'원소전환의':'Pengubah',
'정화의':'Memurnikan',
'불굴의':'Pantang Menyerah',
'부활의':'Membangkitkan',
'약탈의':'Menjarah',
'경험의':'Berpengalaman',
'골드의':'Emas',
'포션강화의':'Ampuh',
'사슬의':'Terrantai',
'진혼의':'Menguduskan',
'윤회의':'Siklik',
'생명력의':'Kuat',
'재생의':'Beregenerasi',
'치유의':'Penyembuhan',
'마력의':'Sihir',
'절약의':'Efisien',
'영혼의':'Terikat Jiwa',
'예리한':'Tajam',
'맹렬한':'Brutal',
'파멸의':'Merusak',
'게임 설정':'Pengaturan Game',
'화면 흔들림':'Guncangan Layar',
'파티클 양':'Jumlah Partikel',
'효과음 볼륨':'Volume SFX',
'음악 볼륨':'Volume Musik',
'난이도':'Kesulitan',
'자동 물약':'Ramuan Otomatis',
'최소 줍기 등급':'Grade Ambil Min',
'최소 줍기 티어':'Tier Ambil Min',
'FPS 제한':'Batas FPS',
'해상도 스케일':'Skala Resolusi',
'펫 자동수거':'Pet Auto-Kumpul',
'화면 설정':'Pengaturan Tampilan',
'화면 모드':'Mode Tampilan',
'보스 AI 디버그':'Debug AI Bos',
'유령불꽃 크기':'Ukuran Api Hantu',
'화면 명암':'Kecerahan',
'유령 글로우':'Cahaya Hantu',
'기동:칼날개 AUTO':'Sayap Pisau AUTO',
'일반':'Normal',
'어려움':'Sulit',
'지옥':'Neraka',
'이상':'atau lebih',
'사용 안 함':'Nonaktif',
'창 모드':'Berjendela',
'보더리스':'Tanpa Batas',
'전체화면':'Layar Penuh',
'설정':'Pengaturan',
'조작 키 설정 (클릭하여 변경)':'Pengaturan Tombol (Klik untuk Ubah)',
'좌클릭 무기 공격':'Klik Kiri Serangan',
'우클릭 탭 칼등 처내기':'Klik Kanan Parry',
'우클릭 홀드 연속 처내기':'Tahan Klik Kanan Parry Terus',
'SHIFT 작살 발사':'SHIFT Luncurkan Tombak',
'이동':'Bergerak',
'아이템 줍기':'Ambil Item',
'능력치 (스탯/패시브)':'Stat (Stat/Pasif)',
'분해':'Bongkar',
'제작':'Buat',
'사망':'Kematian',
'부활':'Hidupkan',
'로비로':'Ke Lobi',
'가방에 공간이 없습니다!':'Tas tidak ada tempat!',
'가방이 가득 찼습니다!':'Tas penuh!',
'창고가 가득 찼습니다!':'Gudang penuh!',
'퀵슬롯이 가득 찼습니다!':'Slot cepat penuh!',
'결정 주머니가 가득 찼습니다!':'Kantong kristal penuh!',
'결정 주머니 가득!':'Kantong kristal penuh!',
'악의가 부족합니다!':'Kebencian tidak cukup!',
'가방이 비어있습니다':'Tas kosong',
'창고가 비어있습니다':'Gudang kosong',
'비어있음':'Kosong',
'어픽스 없음':'Tidak ada afiks',
'장착!':'Terpasang!',
'해제':'Dilepas',
'보관':'Simpan',
'꺼내기':'Tarik',
'현재 장착':'Sedang dipakai',
'없음 — 제작하세요!':'Tidak ada — Buat satu!',
'리셋할 포인트가 없습니다':'Tidak ada poin untuk reset',
'키 설정 초기화 완료':'Pengaturan tombol direset',
'제작 확률':'Peluang buat',
'제작 비용':'Biaya buat',
'보유 악의':'Kebencian dimiliki',
'보스방':'Ruang Bos',
'안식처':'Tempat Perlindungan',
'회복':'Pulih',
'점화':'Nyalakan',
'비석':'Prasasti',
'읽기':'Baca',
'파괴':'Hancurkan',
'제단':'Altar',
'기원':'Berdoa',
'잔해':'Puing',
'열기':'Buka',
'문지기':'Penjaga Gerbang',
'부활 판정 중...':'Menilai kebangkitan...',
'기폭 준비!':'Siap ledakkan!',
'탈출':'Kabur',
'연타':'Tekan Berulang',
'추적암전':'Petir Pelacak',
'만화광선':'Sinar Luminesen',
'최종 마법':'Sihir Terakhir',
'감시중':'Mengawasi',
'대기':'Siaga',
'작동중':'Aktif',
'설치 가능':'Bisa dipasang',
'균열 임박!':'Pembobolan segera!',
'흡수 중...':'Menyerap...',
'흡수 완료 — 재입력으로 회수':'Selesai — tekan lagi untuk kumpul',
'화상':'Bakar',
'당기기':'Tarik',
'밀어내기':'Dorong',
'단계':'tingkat',
'단':'tingkat',
'습득!':'Dipelajari!',
'리셋!':'Reset!',
'세팅!':'Diatur!',
'회수':'Tarik Kembali',
'합체 해제':'Lepas Fusi',
'리셋':'Reset',
'환불':'Pengembalian',
'파트너 클릭!':'Klik pasangan!',
'SP부족!':'Butuh SP!',
'같은 보석 스킬 습득 시 합체 가능':'Bisa fusi saat belajar skill gem yang sama',
'펼쳐서 초기화':'Perluas untuk reset',
'슬롯:':'Slot:',
'남은 SP':'SP Tersisa',
'맞아서 사망':'Mati terkena pukulan',
'레벨':'Level',
'최대HP':'HP Maks',
'방랑 기사':'Ksatria Pengembara',
'보물 악마':'Iblis Harta',
'거울의 사도':'Rasul Cermin',
'상인 악마':'Iblis Pedagang',
'사슬의 죄수':'Tahanan Terrantai',
'시간의 사도':'Rasul Waktu',
'탐욕의 사도':'Rasul Keserakahan',
'저주받은 쌍둥이':'Kembar Terkutuk',
'차원 균열체':'Retakan Dimensi',
'죽음 그 자체':'Kematian Itu Sendiri',
'HP결정':'Kristal HP',
'ST결정':'Kristal ST',
'MP결정':'Kristal MP',
'ATK결정':'Kristal ATK',
'DEF결정':'Kristal DEF',
'속도결정':'Kristal Kecepatan',
'크리결정':'Kristal Kritis',
'치명결정':'Kristal CritDmg',
'화염결정':'Kristal Api',
'냉기결정':'Kristal Es',
'암흑결정':'Kristal Gelap',
'번개결정':'Kristal Petir',
'신성결정':'Kristal Suci',
'생명결정':'Kristal Nyawa',
'기력결정':'Kristal Stamina',
'마력결정':'Kristal Mana',
'행운결정':'Kristal Keberuntungan',
'조각':'Fragmen',
'파편':'Pecahan',
'순수결정':'Kristal Murni',
'완전결정':'Kristal Sempurna',
'결정 주머니':'Kantong Kristal',
'결정이 없습니다':'Tidak ada kristal',
'가루':'Debu',
'전체':'Semua',
'스탯':'Stat',
'원소':'Elemen',
'유틸':'Utilitas',
'현재':'Saat Ini',
'최대 강화 달성 (+20)':'Peningkatan maks (+20)',
'강화 시':'Setelah peningkatan',
'합성':'Sintesis',
'같은 종류·같은 성급 결정 3개 → 1성급 상승 (강화 리셋)':'3 kristal tipe & grade sama → naik 1 grade (reset peningkatan)',
'합성 가능한 결정이 없습니다 (같은 종류·성급 3개 필요)':'Tidak ada kristal yang bisa disintesis (butuh 3 tipe & grade sama)',
'결정 분해 → 결정 가루':'Urai Kristal → Debu Kristal',
'분해할 결정이 없습니다':'Tidak ada kristal untuk diurai',
'결정 제작 (가루 → 결정)':'Buat Kristal (Debu → Kristal)',
'탈착':'Lepas',
'빈 슬롯':'Slot kosong',
'결정 선택 후 클릭':'Pilih kristal lalu klik',
'클릭하여 선택결정 장착':'Klik untuk pasang kristal yang dipilih',
'획득!':'Diperoleh!',
'제작!':'Dibuat!',
'합성!':'Disintesis!',
'최상위 일괄합성':'Sintesis Massal ke Atas',
'일괄합성 완료':'Sintesis massal selesai',
'벌레굴':'Sarang Cacing',
'얼음굴':'Gua Es',
'고통의 화염지대':'Tanah Neraka',
'지옥의 군단':'Legiun Neraka',
'사도의 마굴':'Sarang Rasul',
'지옥성':'Benteng Neraka',
'엑소듀서 전사':'Pejuang Exoduser',
'포이즈':'Keseimbangan',
'지옥창고':'Gudang Neraka',
'선택분해':'Bongkar Selektif',
'쓰레기':'Sampah',
'복구 불가!':'Tidak bisa dipulihkan!',
'중요잠금':'Terkunci Penting',
'자동 장착!':'Auto terpasang!',
'분해! 가루 +':'Dibongkar! Debu +',
'평화보호':'Perisai',
'지진폭풍':'Badai Gempa',
'회전기폭':'Putar-Ledak',
'공격':'Serangan',
'보호막':'Penghalang',
'합체 스킬로 통합됨':'Digabung ke skill fusi',
'얼음보주 안에선 사용 불가!':'Tidak bisa digunakan di dalam Ice Orb!',
'Shift+키로 폭파':'Shift+tombol untuk meledakkan',
'취소':'Batal',
'쿨다운 중...':'Cooldown...',
'시전 중...':'Menggunakan...',
'악의 부족! (12)':'Kebencian tidak cukup! (12)',
'악의 부족! (15)':'Kebencian tidak cukup! (15)',
'악의 부족! (20)':'Kebencian tidak cukup! (20)',
'악의 부족! (10)':'Kebencian tidak cukup! (10)',
'HP 부족!':'HP tidak cukup!',
'필살기 슬롯 클릭하여 배정!':'Klik slot jurus pamungkas untuk atur!',
'필살기 스킬을 습득하세요':'Pelajari skill pamungkas',
'우클릭(칼등치기)에 합체됨':'Digabung ke Klik Kanan (parry pisau)',
'T(석궁자동)에 세팅하세요':'Atur ke T (panah otomatis)',
'공성쇠뇌 철거 → 이동식':'Panah pengepungan dibongkar → portabel',
'ST 부족! (100)':'ST tidak cukup! (100)',
'HP 99% 이상!':'HP 99%+!',
'그로기 보스 없음!':'Tidak ada bos groggy!',
'이미 폭풍 지역!':'Sudah di zona badai!',
'이미 빙풍 지역!':'Sudah di zona badai es!',
'💎 푸른비 해금!':'💎 Azure Rain unlocked!',
'💫 버스트루프 해금!':'💫 Burst Loop unlocked!',
'👻 유령 허수아비 해금!':'👻 Hantu Decoy unlocked!',
'쿨 ':'CD ',
'과부하 ':'Kelebihan Beban ',
'🕊️💎 블루콩!':'🕊️💎 Blue Bean!',
'🛡️💎 빨콩→블루콩!':'🛡️💎 Red→Blue Bean!',
'🛡️💎 무지개→블루콩!':'🛡️💎 Rainbow→Blue Bean!',
'레어':'Langka',
'슬롯':'Slot',
'성공률':'Tingkat Keberhasilan',
'AI 자동 강화':'AI Auto-Tingkatkan',
'최대 강화 달성!':'Peningkatan maks tercapai!',
'최대 강화':'Peningkatan maks',
'회복량':'Pemulihan',
'분해할 아이템이 없습니다.':'Tidak ada item untuk dibongkar.',
'🔨 제작':'🔨 Buat',
'체간':'Postur',
'아이템에 마우스를 올리거나 좌클릭으로 선택하세요':'Arahkan ke item atau klik kiri untuk memilih',
'중독':'Racun',
'지뢰':'Ranjau',
'함정':'Jebakan',
'산호가시':'Duri Karang',
'투사체':'Proyektil',
'도트':'DoT',
'레어몹':'Mob Langka',
'구역':'Zona',
'가시!':'Duri!',
'림보':'Limbo',
'색욕':'Nafsu',
'탐식':'Rakus',
'탐욕':'Keserakahan',
'분노':'Murka',
'이단':'Sesat',
'폭력':'Kekerasan',
'분노!':'Amukan!',
'탐욕!':'Serakah!',
'💀 분노 폭발!':'💀 Amukan Burst!',
'심연의 분노!':'Amukan Jurang!',
'쌍둥이의 분노!':'Amukan Kembar!',
'소환굴':'Lubang Spawn',
'처치!':'Dikalahkan!',
'왕관 착용':'Mahkota On',
'왕관 해제':'Mahkota Off',
'맨손':'Kosong',
'없음':'Tidak Ada',
'갑옷':'Baju Besi',
'부츠':'Sepatu',
'매직':'Sihir',
'챔피언':'Juara',
'초속':'Cepat',
'강타':'Hantam',
'재생':'Regen',
'맹독':'Bisa',
'소환':'Panggil',
'기생':'Parasit',
'분열':'Belah',
'용암자취':'Jejak Lava',
'사망폭발':'Ledakan Kematian',
'화염사슬':'Rantai Api',
'광전':'Mengamuk',
'텔레포트':'Teleportasi',
'소용돌이':'Pusaran',
'환영':'Hantu',
'전격반사':'Pantulan Kejut',
'감전':'Setrum',
'낙뢰':'Guntur',
'연쇄전격':'Petir Berantai',
'동료불사':'Sekutu Abadi',
'영혼포식':'Pemakan Jiwa',
'시간왜곡':'Distorsi Waktu',
'혼돈변이':'Mutasi Kekacauan',
'복수자':'Pembalas',
'마법보초':'Penjaga Sihir',
'환영술사':'Penyihir Ilusi',
'함성':'Seruan Perang',
'치유':'Sembuh',
'신속':'Kelincahan',
'다크 판타지 전사. 거대검+검은 갑옷':'Pejuang fantasi gelap. Pedang besar + Baju besi hitam',
'⚡ 사슬이동:강화!':'⚡ Chain:Enhanced!',
'⚡ 사슬기동:화염!':'⚡ Rantai Drive: Flame!',
'달성!':'Tercapai!',
'ST':'ST',
'부족!':'Tidak Cukup!',
'타':'Pukulan',
'🌀 당기기 모드':'🌀 Tarik Mode',
'💥 밀어내기 모드':'💥 Dorong Mode',
'🕊️빨콩 흡수':'🕊️Red bean absorb',
'🕊️흡수':'🕊️Absorb',
'💎유도 폭발!':'💎Homing Ledakan!',
'💥반사 폭발!':'💥Reflect Ledakan!',
'⚡⚡ 참회 귀환!':'⚡⚡ Repentance Return!',
'⚡ 참회!':'⚡ Repentance!',
'파도!':'Gelombang!',
'암전!':'Petir!',
'암흑!':'Gelap!',
'암흑창!':'Tombak Gelap!',
'빛창!':'Tombak Cahaya!',
'체 소환!':'Dipanggil!',
'개 설치!':'Dipasang!',
'💥 보스 그로기!':'💥 Boss Groggy!',
'💥 그로기!':'💥 Groggy!',
'보상':'Bonus',
'⚡ 암전나선!':'⚡ Petir Helix!',
'🌋 지진폭풍!':'🌋 Quake Storm!',
'SP슬롯':'Slot SP',
'F슬롯':'Slot F',
'⚔🩸 독혈해방!':'⚔🩸 Plague Liberation!',
'⚔ 칼날 해방!':'⚔ Blade Liberation!',
'🔨🌋 지옥강타!':'🔨🌋 Inferno Hantam!',
'🔨 대왕치기!':'🔨 Giant Hantam!',
'✟ 결계의 영역!':'✟ Ward Domain!',
'✟ 물의 영역!':'✟ Air Domain!',
'✟ 파쇄의 영역!':'✟ Pecahkan Domain!',
'✟ 침식의 영역!':'✟ Corrode Domain!',
'✟ 관통의 영역!':'✟ Pierce Domain!',
'✟ 권능의 영역!':'✟ Sovereign Domain!',
'🛡 회복의 영역!':'🛡 Sacred Domain!',
'임계...!':'Kritis...!',
'기폭팔!':'Ledakan!',
'강제기폭!':'Paksa Ledak!',
'자동기폭!':'Ledak Otomatis!',
'회전기폭!':'Putar Ledak!',
'해제기폭!':'Lepas Ledak!',
'지진기폭!':'Gempa Ledak!',
'혼돈의 왕관':'Mahkota Kekacauan',
'전지전능의 왕관':'Mahkota Kemahakuasaan',
'악마의 팔찌':'Gelang Iblis',
'생명의 팔찌':'Gelang Nyawa',
'🌊 위→아래 파도!':'🌊 Top→Bottom Gelombang!',
'🌊 오른→왼 파도!':'🌊 Right→Left Gelombang!',
'🌊 아래→위 파도!':'🌊 Bottom→Top Gelombang!',
'🌊 왼→오른 파도!':'🌊 Left→Right Gelombang!',
'무적!':'Tak Terkalahkan!',
'🪞 반격!':'🪞 Serangan Balik!',
'💢 반격!':'💢 Serangan Balik!',
'흡수!':'Serap!',
'반격 발사!':'Tembakan Balik!',
'저주! 드랍률 -50%':'Kutukan! Drop rate -50%',
'도망!':'Kabur!',
'위상!':'Fase!',
'방어!':'Jaga!',
'회수 HP+':'Tarik Kembali HP+',
'이동식 복귀':'Kembali Mobile',
'약점!':'Kelemahan!',
'저항!':'Tahan!',
'콤보 종료: ':'Kombo Selesai: ',
'악의 +':'Kebencian +',
'저주 ':'Kutukan ',
'불발...':'Gagal...',
'작살 약점!':'Kelemahan Tombak!',
'전염 x':'Wabah x',
'흡수 완료!':'Serap Selesai!',
'부활 성공!':'Bangkit Berhasil!',
'부활 실패...':'Bangkit Gagal...',
'차원 이동!':'Perpindahan Dimensi!',
'기절 해제':'Stun Dilepas',
'악의 부족':'Kebencian tidak cukup',
'스킬 미습득':'Belum ada skill',
'펼치기':'Perluas',
'접기':'Tutup',
'조건 미달!':' tidak terpenuhi!',
'해제!':' Difusi Dilepas!',
'자동 ON':' Auto ON',
'자동 OFF':' Auto OFF',
'스킬 해제':' skill belum diatur',
'닫기':'Tutup',
'장착 중':'Terpasang',
'보관 아이템':'Item Tersimpan',
'클릭으로 선택 · ESC로 닫기':'Klik untuk pilih · ESC tutup',
'선택됨':'Terpilih',
'악의 부족! (30)':'Kebencian tidak cukup! (30)',
'MP 부족! (40)':'MP tidak cukup! (40)',
'MP 부족! (100)':'MP tidak cukup! (100)',
'MP 부족! (10)':'MP tidak cukup! (10)',
'MP 부족! (':'MP tidak cukup! (',
'✟ 시전...':'✟ Casting...',
'🌋 시전...':'🌋 Casting...',
'⛧ 시전...':'⛧ Casting...',
'❄ 진입!':'❄ Masuk!',
'🔱 작살!':'🔱 Tombak!',
'레벨 부족! (요구: Lv.':'Level terlalu rendah! (Butuh: Lv.',
' 장착!':' Terpasang!',
' 해제':' Dilepas',
'👿 악의 추출: +':'👿 Kebencian Extract: +',
'F 슬롯 해제':'Slot F belum diatur',
'💫 집중...':'💫 Focus...',
'⚡ 마력연사!':'⚡ Sihir Barrage!',
'❄빙결!':'❄Frozen!',
'🟢독!':'🟢Poison!',
'⚡감전!':'⚡Shocked!',
'🔥화상!':'🔥Burning!',
'✦ 여신의 가호 — SP+5 AP+3':'✦ Goddess Blessing — SP+5 AP+3',
'⚔ 기동칼날개!':'⚔ Sayap Pisau!',
'🔥 화염관통!':'🔥 Api Pierce!',
'🔱 관통!':'🔱 Pierce!',
'⚔ 칼날!':'⚔ Blade!',
'💥 착지!':'💥 Mendarat!',
'💫 기절!':'💫 Terkejut!',
'⚡ 체간삭감!':'⚡ Keseimbangan Break!',
'⚡ 기동파괴! ':'⚡ Rantai Crush! T',
'🔥 기동불꽃!':'🔥 Rantai Blaze!',
'🔥 기동불꽃! ':'🔥 Rantai Blaze! T',
'단계 ×':' x',
'⚡ 기동전폭! x':'⚡ Rantai Burst! x',
'🔥🔥 3중폭!':'🔥🔥 Blaze x3!',
'🔥🔥🔥 6중폭!':'🔥🔥🔥 Blaze x6!',
'🔥🔥🔥🔥 9중폭!':'🔥🔥🔥🔥 Blaze x9!',
'💥 불꽃폭발! ':'💥 Blaze Detonate! ',
'🔥 기동불꽃 준비!':'🔥 Rantai Blaze Ready!',
'🔨 기동파괴 준비!':'🔨 Rantai Crush Ready!',
'⚡ 기동전폭 준비!':'⚡ Rantai Burst Ready!',
'⚡ 과부하! 5초':'⚡ Kelebihan Beban! 5s',
'💫 자동 버스트!':'💫 Auto Burst!',
'🔨 칼등날개!':'🔨 Perisai Wing!',
'💥폭발!':'💥Explosion!',
'🛡️💎 유도반사!':'🛡️💎 Homing Pantulan!',
'⚡💎 블루콩!':'⚡💎 Blue Bean!',
'💎 블루콩!':'💎 Blue Bean!',
'⚡반사!':'⚡Reflect!',
'💎 푸른비 OFF':'💎 Azure Rain OFF',
'💎 푸른비 ON!':'💎 Azure Rain ON!',
'🔥 지옥진!':'🔥 Inferno Array!',
'🔥 업화선!':'🔥 Api Neraka Beam!',
'✦ 평화 충격파! ':'✦ Peace Gelombang Kejut! ',
'⚡ 전류 방출!':'⚡ Saat Ini Release!',
'⚡⚡ 레인라이트닝!':'⚡⚡ Rain Petir!',
'💫 광역!':'💫 AoE!',
'🔥 불장판!':'🔥 Api Zona!',
'💫 피니셔!':'💫 Finisher!',
'☠ 지옥에서 귀환!':'☠ Returned from Neraka!',
'☠ 완전 사망!':'☠ Permanent Kematian!',
'⚔ 처형! ':'⚔ Execution! ',
'💥 지뢰!':'💥 Ranjau!',
'⚠ 함정!':'⚠ Jebakan!',
'❌ 우클릭으로! -':'❌ Use RMB! -',
'❌ Q키로! -':'❌ Use Q! -',
'💥무지개 폭발! ':'💥Rainbow Ledakan! ',
'🛡️💎 블루콩!':'🛡️💎 Blue Bean!',
'⬜화이트볼!':'⬜White Ball!',
'✨💎 블루콩!':'✨💎 Blue Bean!',
'💜다크볼!':'💜Dark Ball!',
'❄빙판!':'❄Ice Floor!',
'🌨빙결!':'🌨Frozen!',
'🕸둔화!':'🕸Slow!',
'⚠트랩!':'⚠Trap!',
'💀 역병 처형!':'💀 Plague Execution!',
'💥 역병 Finale!':'💥 Plague Finale!',
'⚔ 균열 악마!':'⚔ Retakan Demon!',
'자동회수 HP+':'Auto-Tarik HP+',
'MP 부족 — 연사 해제':'MP rendah — Tembakan Cepat Mati',
'MP 부족 — 푸른비 OFF':'MP rendah — Hujan Biru OFF',
'🛡️반사!':'🛡️Reflect!',
'⚡🦴 참회 귀환!':'⚡🦴 Repentance Return!',
'🦴⚡해골번개!':'🦴⚡Bone Petir!',
'⚡악의폭풍!':'⚡Malice Storm!',
'❄아이스스톰!':'❄Ice Storm!',
'⚡ 암전폭발!':'⚡ Petir Ledakan!',
'⚡ 레인라이트닝! x':'⚡ Rain Petir! x',
'❄ 탈출!':'❄ Kabur!',
'⚡쉴드!':'⚡Shield!',
'❄🌪️ 얼음보주!':'❄🌪️ Es Orb!',
'🌪️ 전개!':'🌪️ Kerahkan!',
'❄ 빙결흡인!':'❄ Freeze Pusaran!',
'❄☄ 빙결폭발!':'❄☄ Freeze Ledakan!',
'☄️ 흡인!':'☄️ Pusaran!',
'☄️ 대폭발!':'☄️ Mega Ledakan!',
'❄ 얼음보주!':'❄ Es Orb!',
'⏳ 시간왜곡!':'⏳ Time Warp!',
'쿨다운!':'Cooldown!',
'❄ 파쇄!':'❄ Pecahkan!',
'☄️💥 대폭발!':'☄️💥 Mega Ledakan!',
'반사!':'Pantulan!',
'💀 도넛!':'💀 Donat!',
'💀 전멸!':'💀 Pemusnahan!',
'🌊 파도!':'🌊 Gelombang!',
'속박!':'Ikat!',
'반격!':'Serangan Balik!',
'분신!':'Klon!',
'분신 파괴!':'Klon Dihancurkan!',
'무기 해방!':'Pembebasan Senjata!',
'❄프리즌!':'❄Prison!',
'⚡ 증표 ':'⚡ Mark ',
'흔들!':'Goyang!',
'⚠ 광역 발사!':'⚠ AoE Api!',
'🔥 확산!':'🔥 Menyebar!',
'⚠ 돌진!':'⚠ Serbu!',
'🦅 도약!':'🦅 Lompat!',
'⚡ 레이저!':'⚡ Laser!',
'🌊 충격파!':'🌊 Gelombang Kejut!',
'👹 소환!':'👹 Panggil!',
'☄ 유성우!':'☄ Meteor Shower!',
'🖐 잡기!':'🖐 Cengkeram!',
'🌀 회전참!':'🌀 Puting Beliung!',
'💣 지뢰!':'💣 Ranjau!',
'🌀 흡인!':'🌀 Vakum!',
'🔴 빨간콩 폭풍!':'🔴 Red Bean Storm!',
'🔴🔴 콩 비!':'🔴🔴 Bean Rain!',
'🌊 부채꼴 충격파!':'🌊 Fan Gelombang Kejut!',
'✴ 멸광 레이저!':'✴ Pemusnahan Laser!',
'🔴 추적 장판!':'🔴 Tracking Zona!',
'💥 속성탄!':'💥 Elemental Shot!',
'⚔ 검기!':'⚔ Sword Ki!',
'⚔ 재단참!':'⚔ Reaping Tebas!',
'🌀 나선탄!':'🌀 Spiral Shot!',
'⚠ 찌르기!':'⚠ Tusukan!',
'🔥🔥 지옥기둥!':'🔥🔥 Neraka Pillar!',
'⚔ 환영검!':'⚔ Hantu Blade!',
'💢 반격자세!':'💢 Serangan Balik Stance!',
'⚔ 연격!':'⚔ Combo!',
'🌑 암흑!':'🌑 Kegelapan!',
'👥 분신!':'👥 Klon!',
'🌋 균열!':'🌋 Retakan!',
'🌊 파동!':'🌊 Riak!',
'💣 추적지뢰!':'💣 Homing Ranjau!',
'⏪ 되감기!':'⏪ Mundur!',
'🌀 중력장!':'🌀 Gravity Field!',
'🔨 벽밀기!':'🔨 Wall Dorong!',
'☠ 독안개!':'☠ Racun Fog!',
'⛓ 감옥!':'⛓ Penjara!',
'⚡ 연쇄번개!':'⚡ Rantai Petir!',
'🔮 궤도탄!':'🔮 Orbital Shot!',
'🛡 방패돌진!':'🛡 Perisai Serbu!',
'🪞 반격자세!':'🪞 Serangan Balik Stance!',
'⚓ 속박!':'⚓ Ikat!',
'👤 분신!':'👤 Klon!',
'🖐 탈취!':'🖐 Curi!',
'🔥🔥 용암 지대!':'🔥🔥 Lava Zona!',
'🌧🌧 화염 폭격!':'🌧🌧 Api Barrage!',
'⚡⚡ 전격 장막!':'⚡⚡ Petir Veil!',
'💀 내 곁으로!':'💀 Come to Me!',
'⭕ 안전!':'⭕ Aman!',
'💀💀 전멸 폭발!':'💀💀 Pemusnahan Ledakan!',
'⚡ 쐐기 소멸!':'⚡ Wedge Extinction!',
'🌊충격파!':'🌊Shockwave!',
'👿악의+100':'👿Malice+100',
'💥패링폭발!':'💥Parry Ledakan!',
'균열 충돌! ':'Tabrakan Retakan! ',
'벽 충돌! ':'Tabrakan Dinding! ',
'소환!':'Panggil!',
'환영!':'Hantu!',
'⚡낙뢰!':'⚡Thunder!',
'⚡빔!':'⚡Beam!',
'환영술!':'Ilusi!',
'💀소환!':'💀Summon!',
'🔮주술!':'🔮Curse!',
'🩸산란!':'🩸Spawn!',
'💢광폭!':'💢Frenzy!',
'🕷산란!':'🕷Spawn!',
'❄서리!':'❄Frost!',
'❄빙결파!':'❄Freeze Gelombang!',
'💀빙마!':'💀Ice Demon!',
'돌진!':'Serbu!',
'충격파!':'Gelombang Kejut!',
'독안개!':'Kabut Racun!',
'연타!':'Serangan Beruntun!',
'포효!':'Raungan!',
'강화!':'Tingkatkan!',
'꼬리!':'Ekor!',
'은신...':'Sembunyi...',
'기습!':'Penyergapan!',
'산란!':'Bertelur!',
'독가스!':'Gas Racun!',
'소멸...':'Larut...',
'강타!':'Hantam!',
'분비!':'Sekresi!',
'채찍!':'Cambuk!',
'출혈!':'Pendarahan!',
'급강하!':'Menukik!',
'방출!':'Lepaskan!',
'충격!':'Dampak!',
'치유!':'Sembuh!',
'의식!':'Ritual!',
'지옥불!':'Api Neraka!',
'끌려감!':'Ditarik!',
'혀!':'Lidah!',
'응시!':'Tatapan!',
'낙하!':'Jatuh!',
'핏방울!':'Tetes Darah!',
'일어남!':'Bangkit!',
'휩쓸기!':'Sapu!',
'웅크림':'Merunduk',
'뼈칼날!':'Pisau Tulang!',
'감속!':'Lambat!',
'비명!':'Teriakan!',
'화산탄!':'Tembakan Gunung Api!',
'자폭!':'Hancur Diri!',
'감싸기!':'Selimuti!',
'잡기!':'Cengkeram!',
'내리찍기!':'Hantam!',
'브레스!':'Nafas!',
'비행!':'Terbang!',
'용암비!':'Hujan Lava!',
'물뿜기!':'Semburan Air!',
'빛...':'Cahaya...',
'삼키기!':'Telan!',
'마비!':'Lumpuh!',
'방전!':'Lepaskan!',
'집게찍기!':'Hantaman Jepit!',
'찍기!':'Hantam!',
'붙잡기!':'Tangkap!',
'감아올리기!':'Lilit!',
'파편!':'Fragmen!',
'할퀴기!':'Cakaran!',
'기생충!':'Parasit!',
'심연 해방!':'Pembebasan Jurang!',
'촉수난타!':'Hujan Tentakel!',
'삼지창!':'Trisula!',
'소용돌이!':'Pusaran!',
'해일!':'Tsunami!',
'끼걱!':'Berderit!',
'폭발!':'Ledakan!',
'체인!':'Rantai!',
'갈기!':'Surai!',
'공포!':'Teror!',
'흡혈!':'Sedot!',
'베기!':'Tebas!',
'비이이명!!':'Riiing!!',
'분열!':'Belah!',
'3연참!':'Tiga Tebasan!',
'패링!':'Parry!',
'...복사...':'..Menyalin...',
'불균형...저주!':'Ketidakseimbangan...Kutukan!',
'저주!':'Kutukan!',
'균형...강화!':'Seimbang...Tingkatkan!',
'심판의 기둥!':'Pilar Penghakiman!',
'처형 선고!':'Hukuman Mati!',
'고통의 해방!':'Pembebasan Rasa Sakit!',
'너도 느껴봐라!':'Rasakan ini juga!',
'대검난무!':'Amukan Pedang Besar!',
'촉수!':'Tentakel!',
'전방위 빔!':'Sinar Segala Arah!',
'회피!':'Hindar!',
'[F] 상점':'[F] Toko',
'거래 성공!':'Perdagangan Berhasil!',
'악의 부족! (':'Kebencian tidak cukup! (',
'상인이 떠납니다...':'Pedagang pergi...',
'사슬 해방!':'Pembebasan Rantai!',
'완전 해방!':'Pembebasan Penuh!',
'⏪ 시간 되감기!':'⏪ Time Mundur!',
'전환!':'Ganti!',
'부활 ':'Bangkit ',
'🌀균열!':'🌀Rift!',
'...사라짐':'...Menghilang',
'낫 베기!':'Tebasan Sabit!',
'☠ 죽음의 선고!':'☠ Kematian Sentence!',
'선고 집행...':'Menjalankan hukuman...',
'⚡패링!':'⚡Parry!',
'경직!':'Terhuyung!',
'⚠ 잡혔다!':'⚠ Grabbed!',
'💥 내던지기!':'💥 Throw!',
'💥 소용돌이 폭발!':'💥 Pusaran Ledakan!',
'👻 순간이동!':'👻 Teleportasi!',
'💫 기절! 5초':'💫 Terkejut! 5s',
'찌르기 반격!':'Tusukan Balik!',
'💢 폭발!':'💢 Ledakan!',
'반격 실패':'Serangan Balik Gagal',
'탈취 반격!':'Curi Balik!',
'무기 봉인!':'Segel Senjata!',
'냠!':'Nyam!',
'합체!':'Difusi!',
'출구가 열렸다!':'Pintu keluar terbuka!',
'보물상자 출현!':'Peti harta muncul!',
'출구':'Keluar',
'⚠ 문지기가 살아있다!':'⚠ Penjaga Gerbang still alive!',
'⏱ 타임어택 ':'⏱ Time Serangan ',
'처치율 ':'Rasio Tewas ',
'불사 보호':'Perlindungan Abadi',
'환영 소멸!':'Hantu Menghilang!',
'부활력 ':'Kekuatan Bangkit ',
'✟ 신성력 억제! (':'✟ Suci Suppress! (',
'부활 실패 (':'Bangkit Gagal (',
'⚡순간이동!':'⚡Teleport!',
'👻 동반부활!':'👻 Co-Revive!',
'✟ 신성력 억제!':'✟ Suci Suppress!',
'💀 부활 판정 중...':'💀 Resurrection judging...',
'⚔ 문지기 처치!':'⚔ Penjaga Gerbang Defeated!',
'🚪 보스방 개방!':'🚪 Boss Room Buka!',
'잔해 출현!':'Puing Muncul!',
'🌀균열 발생!':'🌀Rift opened!',
'🔥복수!':'🔥Revenge!',
'💥폭독혈!':'💥Plague Blood!',
'빙판!':'Lantai Es!',
'❄최종빙결!':'❄Final Freeze!',
'빙마 처치!':'Iblis Es Dikalahkan!',
'분리!':'Pisahkan!',
'뼈 파편!':'Fragmen Tulang!',
'태아 처치!':'Janin Dikalahkan!',
'지배자 처치!':'Penguasa Dikalahkan!',
'용암!':'Lava!',
'화룡 처치!':'Naga Api Dikalahkan!',
'최후의 비명!':'Teriakan Akhir!',
'산화...':'Teroksidasi...',
'심판자 처치!':'Hakim Dikalahkan!',
'고통의 왕 처치!':'Raja Kesakitan Dikalahkan!',
'수역!':'Air!',
'파편 폭발!':'Ledakan Fragmen!',
'거대어 처치!':'Leviathan Dikalahkan!',
'대사도 처치!':'Rasul Tinggi Dikalahkan!',
'독웅덩이!':'Kolam Racun!',
'화염장판!':'Zona Api!',
'전기장!':'Medan Listrik!',
'무기 드롭!':'Senjata Jatuh!',
'보물 발견!':'Harta Ditemukan!',
'상인의 주머니 +':'Kantong Pedagang +',
'속박의 파편!':'Pecahan Pengikat!',
'시간의 조각!':'Fragmen Waktu!',
'저주 해제!':'Kutukan Diangkat!',
'차원의 결정!':'Kristal Dimensi!',
'전설 아이템!':'Item Legendaris!',
'죽음을 이겨냈다!':'Mengalahkan Kematian!',
'💥대폭발!':'💥Mega Ledakan!',
'⚡강화!':'⚡Enhance!',
'장비 ':'Perlengkapan ',
'💫 진동!':'💫 Tremor!',
'❄ 무적!':'❄ Tak Terkalahkan!',
'집중 해제!':'Fokus Batal!',
'집중!':'Fokus!',
'🕊️ 평화보호 ':'🕊️ Aegis ',
'🛡 보호막 ':'🛡 Perisai ',
'🌀 회전보호막 ':'🌀 Spin Perisai ',
'💥한방캡!':'💥One-hit Cap!',
'⚡쉴드 파괴!':'⚡Shield Hancurkan!',
'💀 불굴!':'💀 Pantang Menyerah!',
'💀 1회부활!':'💀 1-life Hidupkan!',
'감시 회수':'Tarik Kembali Penjaga',
'악마화 부활!':'Kebangkitan Iblis!',
'배정 가능한 스킬 없음':'Tidak ada skill untuk diatur',
'칼날 없음!':'Tidak Ada Pisau!',
'⚔ 악의사냥!':'⚔ Kebencian Hunt!',
'❄🌪️ 얼음소용돌이!':'❄🌪️ Es Pusaran!',
'🌪️ 폭풍소환!':'🌪️ Pusaran Panggil!',
'🌹 붉은꽃!':'🌹 Crimson Bloom!',
'💥 폭산탄!':'💥 Ledakan Shot!',
'🪡 바늘출!':'🪡 Needle Burst!',
'⚡ 전격이동!':'⚡ Flash Step!',
'기둥가시로 흡수됨':'Diserap oleh duri pilar',
'🌿 가시덫!':'🌿 Spike Jebakan!',
'⚡ 전격의창!':'⚡ Guntur Spear!',
'🏹 공성쇠뇌 설치!':'🏹 Siege Panah Silang Placed!',
'👻 유령 허수아비!':'👻 Hantu Decoy!',
'💥 폭발 허수아비!':'💥 Peledak Decoy!',
'축적!':'Tersimpan!',
'축적 중...':'Menyimpan...',
'만충! 재입력→폭발':'Penuh! Tekan lagi→Meledak',
'폭발! ':'Meledak! ',
'뎀':' DMG',
'🩸 폭독칼날!':'🩸 Plague Blade!',
'⚡날개치기!':'⚡Wing Strike!',
'🗡 칼등날개!':'🗡 Perisai Wing!',
'🏛️ 악의기둥!':'🏛️ Gelap Pillar!',
'🌿 기둥가시!':'🌿 Pillar Thorn!',
'🌋 지옥강타!':'🌋 Inferno Hantam!',
'💥 체간 붕괴!':'💥 Postur Break!',
'💫 포이즈 파괴!':'💫 Keseimbangan Hancurkan!',
'⚡ 뇌전걸음!':'⚡ Hantu Walk!',
'✟ 구속의 영역!':'✟ Binding Domain!',
'✟ 신성폭발!':'✟ Suci Ledakan!',
'⛧ 블랙!':'⛧ Black Star!',
'🌋 용암소환!':'🌋 Lava Panggil!',
'필살기 배정!':'Jurus Pamungkas Diatur!',
'완료':'Selesai',
'합체 가능':'Bisa Fusi',
'부족':'Tidak Cukup',
'SP 부족! (':'Butuh SP! (',
'🕊️ 히든: 평화의보호 해금!':'🕊️ Hidden: Aegis of Peace unlocked!',
'⚡ 히든: 참회 해금!':'⚡ Hidden: Repentance unlocked!',
'배정됨':'Ditugaskan',
'합체 Lv.':'Level Fusi',
'◆ 같은 보석 스킬 습득 시 합체 가능':'◆ Bisa fusi saat belajar skill gem yang sama',
'▼ 가방 → 창고 보관':'▼ Tas → Gudang',
'▲ 창고 → 가방 꺼내기':'▲ Gudang → Tas',
'✓ 선택됨':'✓ Terpilih',
'⟨ 입력 대기... ⟩':'⟨ Menunggu... ⟩',
'⟨ 대기 ⟩':'⟨ Tunggu ⟩',
'보조':'Sub',
'키 설정 초기화 (또는 F5 키)':'Reset Tombol (atau F5)',
'아무 키 또는 마우스 버튼을 누르세요 (ESC = 취소)':'Tekan tombol apapun (ESC = batal)',
'WebGPU 활성':'WebGPU Aktif',
'WebGL2 활성':'WebGL2 Aktif',
'측정 중...':'Mengukur...',
'불러오기 실패':'Gagal Memuat',
'장착':'Terpasang',
'🔒 중요잠금 아이템은 분해 선택 불가!':'🔒 Item terkunci penting tidak bisa dipilih untuk bongkar!',
'장비 강화 (실패 시 재료만 소멸)':'Tingkatkan Perlengkapan (gagal',
'강화 보너스 적용':'Bonus Peningkatan Diterapkan',
'강화 실패!':'Peningkatan Gagal!',
'장착된 장비가 없습니다.':'Tidak ada perlengkapan terpasang.',
'충분':'Cukup',
'더 필요':'Butuh Lebih',
'장비 선택':'Pilih Perlengkapan',
'목표치 설정':'Atur Target',
'악의 투입':'Investasi Kebencian',
'자동 시도':'Percobaan Otomatis',
'목표 강화치':'Target Peningkatan',
'예상 필요 악의':'Est. Kebencian Dibutuhkan',
'보유':'Dimiliki',
'강화 시작':'Mulai Tingkatkan',
'위에서 장비를 선택하세요':'Pilih perlengkapan di atas',
'⬆ 물약 강화 (최대 10단)':'⬆ Potion Enhance (max level 10)',
'필요':'Dibutuhkan',
'악의의 분해로 — 장비를 악의로 갈아버려라':'Tungku Kebencian — Giling perlengkapan jadi kebencian',
'전체 선택':'Pilih Semua',
'전체 해제':'Hapus Semua Pilihan',
'희귀 이하':'Langka atau Dibawah',
'어픽스 리롤!':'Reroll Afiks!',
'영웅':'Heroik',
'전설':'Legendaris',
'무기 타입':'Tipe Senjata',
'활 타입':'Tipe Busur',
'ST 부족':'ST tidak cukup',
'💀 광폭화!':'💀 Enraged!',
'...따라오는 거 아니야. 같은 방향일 뿐이지.':'...I\'m not following you. Just going the same way.',
'공기가 달라졌어. 더 썩었군.':'The air changed. More decay.',
'여기부터는 악마 영역이야. ...맘대로 해.':'Demon territory from here. ...Do as you wish.',
'...이 냄새. 살점이 썩는 냄새야.':'...That smell. Rotting flesh.',
'여기 오래 있으면 미쳐. 나도, 너도.':'Stay too long and you\'ll go mad. Me too.',
'이 길의 끝에 뭐가 있을까. ...알고 싶지도 않어.':'What\'s at the end of this road? ...I don\'t want to know.',
'...여기가 끝이야. 돌아갈 길은 없어.':'...This is the end. No turning back.',
'작살을 땅에 꽂으면 끌려간다.':'Stick the harpoon in the ground and get pulled.',
'Shift로 작살 던져봐!':'Try throwing the harpoon with Shift!',
'패링 성공하면 ST가 회복된다. 공짜 자원이야.':'Parry restores ST. Free resources.',
'패링 많이 하면 ST 걱정 없어~':'Parry a lot and ST is never a problem~',
'장비 분해하면 악의를 얻는다. 쓰레기도 자원이야.':'Dismantling gear gives Malice. Even junk is resources.',
'TAB 열어서 안 쓰는 장비 분해해!':'Open TAB and salvage unused gear!',
'그로기 상태의 적에겐 1.5배 데미지가 들어간다.':'Groggy enemies take 1.5x damage.',
'무릎 꿇으면 전력으로 때려!':'When they kneel, hit with everything!',
'속성 상성이 있다. 화염은 빙결에 약하고, 암전은 암흑에 약하다.':'Elements have counters. Fire is weak to Ice, Lightning to Dark.',
'무기 속성 바꿔가면서 싸워봐!':'Try switching weapon elements!',
'빙결된 적은 1.5배 데미지를 받는다.':'Frozen enemies take 1.5x damage.',
'얼리고 때리는 게 기본이야!':'Freeze then hit — that\'s the basics!',
'보스의 빨간 공격은 패링 가능. 보라빛은 회피만.':'Boss red attacks are parryable. Rainbow is dodge only.',
'색깔 잘 봐! 빨강은 받아치고 무지개는 피해!':'Watch the colors! Parry red, dodge rainbow!',
'VIT를 올리면 최대 HP가 오른다. 죽기 싫으면 찍어.':'VIT raises max HP. Invest if you want to survive.',
'STR은 근접, DEX는 활, INT는 마법! 골고루 말고 하나만!':'STR for melee, DEX for bows, INT for magic! Focus one!',
'E를 꾹 누르면 빔이 나간다. 짧게 누르면 투사체.':'Hold E for beam. Tap E for projectile.',
'마법 쓸 때 MP 잘 봐! 빔은 연속으로 깎여!':'Watch your MP with magic! Beam drains fast!',
'핵터와 디로이가 아이템을 주워준다. 수거 범위 안이면.':'Hecter and Deroy auto-collect items in range.',
'우리한테 고마워해~ 안 주우면 썩잖아.':'Thank us~ Items rot if nobody picks them up.',
'LCK를 올리면 레어 드롭률이 오른다.':'LCK boosts rare drop rate.',
'운빨 게임이긴 하지~ LCK 올려봐!':'It\'s all luck~ Try raising LCK!',
'강화하면 공격력이 쭉쭉 올라가! 악의만 있으면 돼!':'Enhancement boosts ATK fast! Just need Malice!',
'강화 확률은 +1에서 99%. 높을수록 떨어진다.':'Enhancement chance starts at 99% for +1. Drops as it goes.',
'실패하면 악의만 날아가~ 장비는 안 부서져!':'On fail, only Malice is lost~ Gear survives!',
'대장간에서 장비 제작도 된다. 악의 30000개면 영웅급 이상.':'Forge can craft gear too. 30000 Malice for Heroic+.',
'랜덤이지만 좋은 거 나올 수도 있어!':'Random, but you might get something great!',
'쉴드는 마법으로, HP는 물리로 깎아야 제대로 먹힌다.':'Shield needs magic, HP needs physical to be effective.',
'반대로 치면 50%만 들어가! 무기 바꿔가면서 싸워!':'Wrong type only does 50%! Switch weapons!',
'장비에 접두사, 접미사가 붙으면 특수 효과가 생긴다.':'Gear with prefix/suffix gets special effects.',
'영웅급 이상 장비에만 붙어! 좋은 거 나오면 강화해!':'Only on Heroic+ gear! Enhance the good rolls!',
'강화는 장비를 바꿔도 자동 이전된다. 악의만 있으면.':'Enhancement auto-transfers to new gear. Just costs Malice.',
'더 좋은 장비 나오면 바로 장착해! 강화 수치 그대로 옮겨가!':'Equip better gear right away! Enhancement carries over!',
'패링을 써야 자원을 흡수한다고!':'You need to parry to absorb resources!',
'F키 회복의 영역을 써봐. 자원이 차올라.':'Try F-key Sacred Domain. Resources fill up.',
'적이 근접하면 스페이스키야! 가시덫을 활용해!':'When enemies get close, use Space! Use Spike Trap!',
'기절시켜! 그로기가 터지면 데미지가 1.5배야!':'Stun them! Groggy means 1.5x damage!',
'1번 대왕치기로 밀어버려!':'Use key 1 Giant Slam to push them back!',
'무릎 꿇었다.':'Dia berlutut.',
'지금이야! 몰아쳐!!':'Sekarang! Serang!!',
'스킬 포인트 있어! K 눌러서 스킬 찍어봐!':'Got skill points! Press K to learn skills!',
'...힘이 없으면 여기서 끝이야.':'...Without power, this is where it ends.',
'...쓸 거 아니면 분해해.':'...Salvage what you don\'t need.',
'아이템 넘쳐나네~ 우리가 주워줄게!':'So many items~ We\'ll collect for you!',
'악의가 바닥이다.':'Kebencian habis.',
'TAB 열어서 장비 분해해! 쓰레기도 악의가 돼!':'Open TAB and salvage gear! Even junk becomes Malice!',
'좋은 장비가 있네! G 눌러서 대장간 가봐!':'Nice gear! Press G for the forge!',
'...강화 안 하면 그냥 고철이야.':'...Without enhancement, it\'s just scrap.',
'...멈추지 마. 여신은 기다리지 않는다.':'...Don\'t stop. The goddess doesn\'t wait.',
'앞으로 가자~ 나도 여기 오래 있기 싫어.':'Let\'s move on~ I don\'t wanna stay here either.',
'...냄새가 짙다. 큰 놈이 있어.':'...The smell is thick. Something big is here.',
'준비됐어? 물약 확인하고!':'Ready? Check your potions!',
'TAB을 눌러. 가방을 열고 장비를 입어야 한다.':'Press TAB. Open your bag and equip your gear.',
'주웠으면 껴야지! TAB!':'Picked it up? Equip it! TAB!',
'G. 대장간에서 물약도 제작할 수 있다.':'G. You can craft potions at the forge too.',
'악의로 물약 만들어! G키야!':'Craft potions with Malice! Press G!',
'기절이야! Ctrl 눌러!':'Terkejut! Press Ctrl!',
'Ctrl 유령걸음으로 탈출!':'Ctrl Ghost Walk to escape!',
'Ctrl 얼음보주로 탈출!':'Ctrl Ice Orb to escape!',
'빨간 탄은 우클릭 패링. 무지개는 Q 패링.':'Red bullets: RMB parry. Rainbow: Q parry.',
'나머지는 전부 우클릭 패링 가능해!':'Everything else can be parried with RMB!',
'빨강=우클릭, 무지개=Q 패링. 나머진 다 쳐내.':'Red=RMB, Rainbow=Q parry. Deflect the rest.',
'무지개는 Q로 패링! 나머지는 전부 우클릭!':'Rainbow with Q! Everything else with RMB!',
'빠져! 물약 마시고 안전한 곳에서 회복해.':'Fall back! Drink potions and recover somewhere safe.',
'자원 없으면 도망가는 게 답이야!':'No resources? Running is the answer!',
'스페이스! 가시덫으로 적 묶어버려!':'Space! Pin them with Spike Trap!',
'근접이 너무 많아! 거리 벌려!':'Too many melee! Create distance!',
'...둘러싸이면 끝이야. 빠져나와.':'...Get surrounded and it\'s over. Break out.',
'1번 대왕치기로 쓸어버려!':'Use key 1 Giant Slam to sweep them!',
'그로기 터지면 데미지 1.5배!':'Groggy triggers 1.5x damage!',
'회전참이나 광역기로 몰아! 한 놈씩 상대하면 죽어.':'Use Whirlwind or AoE! One-by-one and you\'re dead.',
'뭉쳐있을 때가 기회야!':'When they clump, that\'s your chance!',
'E로 마력공격을 해봐! 악의 쉴드를 해제할려면 마법 공격을 해야 해!':'Try E for magic attacks! You need magic to break Malice shields!',
'쉴드는 마법으로, HP는 물리로. 반대로 치면 데미지 안 들어간다.':'Shields need magic, HP needs physical. Wrong type does no damage.',
'L키로 스킬 슬롯에 넣어야 쓸 수 있어.':'Press L to assign skills to slots.',
'C키를 눌러. 패시브 포인트가 쌓여있다.':'Press C. Passive points have stacked up.',
'C키! 패시브 올리면 진짜 강해져!':'Press C! Passives make you way stronger!',
'스태미나가 부족하다. 무리하지 마.':'Low on stamina. Don\'t overdo it.',
'ST 없으면 스킬 못 써! 잠깐 빠져!':'No ST means no skills! Pull back!',
'탭 장비창을 열어봐. 아이템을 주워왔어!':'Open TAB gear menu. We picked up an item!',
'좋은 거 나왔다! TAB 열어서 확인해봐!':'Something good dropped! Open TAB to check!',
'악의에 중독되면 악마가 돼서 부활력이 생긴대. 저 녀석처럼.':'They say Malice addiction turns you into a demon with revival power. Like that one.',
'혹시 너도...?':'Mungkin kamu juga...?',
'데미지가 부족하면 무기류 강화를 해야해!!':'If damage is lacking, enhance your weapons!!',
'G키 대장간. 강화 안 하면 여기서 계속 죽어.':'G key for forge. Without enhancement, you\'ll keep dying here.',
'시간이 없어. 움직여.':'No time. Bergerak.',
'멍하게 서있으면 안 돼!':'Don\'t just stand there!',
'...뭘 기다리는 거야?':'...What are you waiting for?',
'가자가자! 몬스터가 기다려!':'Let\'s go! Monsters are waiting!',
'여기 오래 있으면 위험해.':'Staying here too long is dangerous.',
'움직여야 해! 가만있으면 둘러싸여!':'Gotta move! Stand still and they\'ll surround you!',
'쉬는 건 죽고 나서 해.':'Rest after you\'re dead.',
'살아있을 때 쉬면 안 돼!':'No resting while alive!',
'적이 몰려오고 있어. 빨리 움직여.':'Enemies are closing in. Move fast.',
'냄새 맡고 올 거야. 빨리!':'They\'ll smell you. Hurry!',
'...아직 살아있는 거 맞지?':'...You are still alive, right?',
'혹시 잠든 거야...?':'Did you fall asleep...?',
'...나무가 썩어가고 있어. 여기는 지옥의 입구야.':'...The trees are rotting. This is the entrance to hell.',
'냄새 지독해... 빨리 지나가자.':'The stench is awful... Let\'s pass through quickly.',
'조심해. 벌레굴이다. 벽이랑 바닥에서 기어나와.':'Careful. Worm nest. They crawl from walls and floors.',
'으으... 벌레 싫어! 밟아버려!':'Ugh... I hate bugs! Stomp them!',
'...공기가 얼어붙는다. 여기선 화염이 먹힌다.':'...The air is freezing. Fire works here.',
'추워... 빙결 조심해! 얼면 끝이야.':'Cold... Watch out for freeze! Get frozen and it\'s over.',
'용암이다. 바닥을 밟으면 타 죽어.':'Lava. Step on the ground and you burn alive.',
'뜨거워! 여기 왜 이렇게 빨개!':'So hot! Why is everything so red here!',
'...군단이다. 수가 많아. 광역기 없으면 밀려.':'...The legion. Too many. Without AoE you\'ll be overwhelmed.',
'우글우글... 징그러워. 한꺼번에 쓸어!':'Crawling everywhere... Gross. Wipe them all at once!',
'사도의 영역이야. 여기 놈들은 머리가 좋아.':'Apostle\'s territory. These ones are smart.',
'패턴이 복잡해졌어... 집중해!':'Patterns got complex... Fokus!',
'...끝이다. 지옥의 심장부. 살아 돌아가는 건 포기해라.':'...This is it. The heart of hell. Abandon hope of return.',
'여기가 마지막이야... 각오해.':'This is the end... Brace yourself.',
'석궁 자동발사 (T)':'Busur otomatis (T)',
'버스트루프 당기기 (H)':'Loop ledakan tarik (H)',
'결정 자동합성':'Kristal sintesis otomatis',
'결정 자동강화':'Kristal penguatan otomatis',
'✓ 설정 자동 저장':'✓ Pengaturan tersimpan otomatis',
'세팅 프리셋 저장/불러오기':'Simpan/muat prasetel',
'세팅1 저장':'Simpan Prasetel 1','세팅1':'Prasetel 1',
'세팅2 저장':'Simpan Prasetel 2','세팅2':'Prasetel 2',
'재진단':'Diagnosa ulang',
'게임 리셋 (처음부터)':'Reset game (dari awal)',
'캐릭터 선택 (로비)':'Pilih karakter (Lobi)',
'닫기 [ESC]':'Tutup [ESC]','닫기 [G]':'Tutup [G]','닫기 [V]':'Tutup [V]','닫기 [C]':'Tutup [C]',
'전체화면 (F11)':'Layar penuh (F11)',
'정말 모든 진행을 초기화하시겠습니까?':'Yakin ingin mereset semua kemajuan?',
'검출 중...':'Mendeteksi...',
'마우스 커서':'Kursor mouse','그래픽 품질':'Kualitas grafis','하드웨어 진단':'Diagnostik perangkat keras',
'BGM 선택':'Pilihan BGM',
'자동 (스테이지별)':'Otomatis (per tahap)','전체 랜덤':'Semua acak','로비':'Lobi',
'1장 랜덤':'Bab 1 acak','2장 랜덤':'Bab 2 acak','3장 랜덤':'Bab 3 acak',
'4장 랜덤':'Bab 4 acak','5장 랜덤':'Bab 5 acak','6장 랜덤':'Bab 6 acak','7장 랜덤':'Bab 7 acak',
'보스':'Bos','최종보스':'Bos akhir',
'대장간 랜덤':'Pandai besi acak','사망 랜덤':'Kematian acak','승리 랜덤':'Kemenangan acak',
'지옥 추락 사망 징글':'Jingle kematian jatuh neraka','탈출 성공':'Pelarian berhasil',
'── 1장 - 썩은 숲 ──':'── CH1 - Rotten Forest ──','── 2장 - 벌레굴 ──':'── CH2 - Worm Nest ──',
'── 3장 - 얼음굴 ──':'── CH3 - Ice Cavern ──','── 4장 - 화염지대 ──':'── CH4 - Infernal Wastes ──',
'── 5장 - 지옥군단 ──':'── CH5 - Hell Legion ──','── 6장 - 사도마굴 ──':'── CH6 - Apostle Den ──',
'── 7장 - 지옥성 ──':'── CH7 - Hell Citadel ──','── 공통 ──':'── Common ──',
'⌨ 조작법':'⌨ Kontrol','클릭하면 닫힘':'Klik untuk menutup',
'전투력':'KP','가방':'Tas','결정':'Kristal',
'↕ 정렬':'↕ Urutkan','쓰레기 전체선택':'Pilih semua sampah','쓰레기 전부 분해':'Uraikan semua sampah',
'창고':'Gudang','스탯 포인트':'Poin atribut','능력치 요약':'Ringkasan statistik','올 리셋':'Reset semua',
'대장간':'Pandai besi','스킬':'Kemampuan','능력치':'Atribut',
'좌클스킬 (클릭 전환)':'Kemamp. klik kiri (klik ganti)','우클스킬 (클릭 전환)':'Kemamp. klik kanan (klik ganti)',
'이동스킬 (클릭 전환)':'Kemamp. gerak (klik ganti)','마법스킬 (클릭 전환)':'Kemamp. sihir (klik ganti)',
'영역스킬 (클릭 전환)':'Kemamp. area (klik ganti)','피보호막 (클릭 전환)':'Perisai darah (klik ganti)',
'CT스킬 (클릭 전환)':'Kemamp. CT (klik ganti)','[C] 능력치':'[C] Atribut',
'무기 공격':'Serangan senjata','칼등 처내기 (투사체 반사, 홀드 연사)':'Parri (memantulkan proyektil, tahan=salvo)',
'연속 처내기':'Parri berkelanjutan','영역 스킬 (폭풍소환 등)':'Kemamp. area (Pusaran dll)',
'작살 발사':'Tembak harpun','마법 (탭=투사체, 홀드=빔)':'Sihir (ketuk=proyektil, tahan=sinar)',
'데빌포스 흡수':'Serap kekuatan iblis','물약 / 스킬슬롯':'Ramuan / Slot kemampuan',
'스킬슬롯 5 / 필살기 / CT스킬':'Slot 5 / Ultimate / Kemamp. CT','스킬 슬롯 배정':'Penetapan slot',
// --- Phase 27 additions ---
'위로 이동':'Gerak Atas','아래로 이동':'Gerak Bawah','왼쪽 이동':'Gerak Kiri','오른쪽 이동':'Gerak Kanan',
'칼등 처내기 (탭=처내기, 홀드=연사)':'Parri (ketuk=parri, tahan=salvo)',
'영역 스킬':'Kemampuan area','작살 이동':'Lompat Tombak',
'유령불꽃 켜기/끄기':'Api Hantu Nyala/Mati','기동칼날개 자동 켜기/끄기':'Sayap-Bilah Otomatis Nyala/Mati',
'해상도':'Resolusi',
'빛이 꺼졌다':'Cahaya Memudar','누군가는 너를 기다리고 있다':'Seseorang menunggumu',
'다시 일어서라':'Bangkit Lagi','로비로 돌아가기':'Kembali ke Lobi',
'☠ 사망 리플레이':'☠ Ulang kematian',
'지옥의 시련을 견뎌냈다':'Kamu telah bertahan dari cobaan Neraka','계속 전투':'Lanjut Bertarung',
'난이도를 선택하라':'Pilih Kesulitan',
'나중에 설정(ESC)에서 변경 가능':'Bisa diubah nanti di Pengaturan (ESC)',
'일괄합성':'Gabung Massal','일괄강화+합성':'Tingkatkan+Gabung Massal',
'자원 부족!':'Sumber Daya Kurang!',' 뎀':' DMG',
'합체 폭발!':'Ledakan Gabungan!','MP 부족! (50)':'MP Kurang! (50)',
'부활력 고갈!':'Kebangkitan Habis!','☠ 부활력 고갈!':'☠ Kebangkitan Habis!',
'독안개':'Kabut Racun','뇌전창':'Tombak Petir',
'🔥 업화선 시전...':'🔥 Sinar Api Neraka menyalur...',
'💥 기동파괴 그로기!':'💥 Rantai Hancur Groggy!',
'💥 칼등 그로기!':'💥 Parri Groggy!',
'⚡ 순간이동 준비!':'⚡ Teleportasi Siap!',
'👿악의+1000':'👿Kedengkian+1000',
'💀 내려찍기!':'💀 Hantam Bawah!',
'✟ 신성력 억제! +':'✟ Kekuatan Suci Ditekan! +',
'✟ 신성력 억제!':'✟ Kekuatan Suci Ditekan!',
'✟ 신성력 억제! (':'✟ Kekuatan Suci Ditekan! (',
'💥 지진그로기!':'💥 Gempa Groggy!',
'💥 기폭그로기!':'💥 Ledakan Groggy!',
'폭발! ×':'Ledakan! ×',
'⚫ 기둥강타!':'⚫ Hantam Tiang!',
'💥 대왕치기 그로기!':'💥 Hantam Raja Groggy!',
'💫 미니스턴!':'💫 Stun Kecil!',
'⚡ 뇌전창!':'⚡ Tombak Petir!',
'…절반이다. 정신차려.':'…Setengah nyawa. Fokus.',
'…죽기 직전이다. 한 발만 더.':'…Hampir mati. Satu serangan lagi.',
'…다음 한 방이 마지막이야.':'…Serangan berikutnya yang terakhir.',
'기절! ':'Terpingsan! ',
'마력이 빈다. 평타 섞어.':'MP hampir habis. Campur serangan normal.',
'그랩이다. 거리를 둬.':'Serangan cengkeram. Jaga jarak.',
'광역기다. 멀어져.':'Serangan area. Menjauh.',
'…아파? 당연하지. 여긴 지옥이야.':'…Sakit? Tentu saja. Ini Neraka.',
'F키도 스킬 슬롯이야!':'Tombol F juga slot kemampuan!',
'L-CTRL로 유령걸음/얼음보주!':'L-CTRL untuk Langkah Hantu/Bola Es!',
'V 눌러서 창고에 넣어둬!':'Tekan V untuk simpan ke gudang!',
'ESC로 설정! 난이도/자동물약!':'ESC untuk pengaturan! Kesulitan/Ramuan otomatis!',
'잡몹이다. 먼저 정리해.':'Monster biasa. Bersihkan dulu.',
'…얼어붙은 놈은 오래 안 간다.':'…Yang membeku tidak akan bertahan lama.',
'…냄새가 짙다. 큰 놈이 있어.':'…Baunya kuat. Ada sesuatu yang besar di dekat sini.',
'쉴드는 마법으로, HP는 물리로.':'Perisai kena sihir, HP kena fisik.',
'스페이스! 가시덫으로 적 묶어!':'Space! Jebak musuh dengan Perangkap Duri!',
'근접 너무 많아! 거리 벌려!':'Terlalu banyak jarak dekat! Menyebar!',
'회전참이나 광역기로 몰아!':'Gunakan Tebasan Putar atau AOE!',
'F 눌러! 회복의 영역 깔아!':'Tekan F! Pasang Wilayah Suci!',
'F키 회복의 영역을 써봐.':'Coba tombol F Wilayah Suci.',
'빠져! 물약 마시고 회복해.':'Mundur! Minum ramuan dan pulih.',
'쉬프트! 사슬기동은 이동기야!':'Shift! Lompatan Rantai adalah gerakan!',
'스킬포인트 쌓였어! K 눌러!':'Poin kemampuan terkumpul! Tekan K!',
'스킬 포인트 있어! K!':'Ada poin kemampuan! K!',
'C키. 패시브 포인트가 쌓여있다.':'Tombol C. Poin pasif sudah terkumpul.',
'…쓸 거 아니면 분해해.':'…Uraikan yang tidak akan dipakai.',
'…강화 안 하면 그냥 고철이야.':'…Tanpa peningkatan itu hanya besi tua.',
'빨간 탄은 우클릭. 무지개는 Q.':'Peluru merah: klik kanan. Pelangi: Q.',
'빨강=우클릭, 무지개=Q.':'Merah=klik kanan, pelangi=Q.',
'…멈추지 마. 여신은 기다리지 않는다.':'…Jangan berhenti. Dewi tidak menunggu.',
'패턴이 바뀐다. 거리를 둬.':'Pola berubah. Jaga jarak.',
'미쳐가고 있어. 광폭화다.':'Sedang gila. Mode mengamuk.',
'마지막이야! 끝장내!':'Fase terakhir! Habiskan!',
'…끝났다. 다음으로.':'…Selesai. Selanjutnya.',
'다 잡았다! 포탈 어딨어?':'Semua terbunuh! Di mana portalnya?',
'근육으로 만든 빌드군. 베고 부숴.':'Build otot. Tebas dan hancurkan.',
'활을 쥐었군. 거리를 둬.':'Pegang busur. Jaga jarak.',
'마법사군. MP 관리부터 배워라.':'Penyihir. Pertama pelajari manajemen MP.',
'운에 기댄 빌드군. …드롭은 좋겠어.':'Build berdasarkan keberuntungan. …Setidaknya drop bagus.',
'…VIT가 너무 낮아. 한 방에 죽는다.':'…VIT terlalu rendah. Mati dalam satu pukulan.',
'다 찍으면 다 약해진다. 하나만 골라.':'Max semua dan lemah di mana-mana. Pilih satu.',
'…3단. 적이 강해져. 정신 차려.':'…Tahap 3. Musuh menguat. Fokus.',
'5단이다. …너도 강해졌단 뜻이야.':'Tahap 5. …Artinya kamu juga menguat.',
'…7단. 아직 살아있단 게 신기하군.':'…Tahap 7. Masih hidup. Mengejutkan.',
'10단. …너는 이제 인간이 아니야.':'Tahap 10. …Kamu bukan manusia lagi.',
'…일반으로 내려왔군. 가끔은 쉬어가야지.':'…Turun ke Normal. Kadang perlu istirahat.',
'…이게 진짜 패링이야.':'…Inilah parri yang sebenarnya.',
'…피가 묻기 시작했군.':'…Darah mulai mengalir.',
'100. 너는 인간이 아니야.':'100. Kamu bukan manusia.',
'…피 흘리며 베는군.':'…Menebas menembus darah.',
'빨간콩이 푸르게 변했다. 그게 너의 무기야.':'Biji merah berubah biru. Itu senjatamu.',
'무지개를 받아쳤군. 그건 진짜 어렵다.':'Memparri pelangi. Itu memang sulit.',
'…너무 빨라. 닿기 직전에 눌러.':'…Terlalu cepat. Tekan tepat sebelum menyentuh.',
'악의가 가득 찼다. 풀어내.':'Kedengkian sudah penuh. Lepaskan.',
'작살이 살을 뚫었어. 끌고 와.':'Tombak menembus daging. Tarik masuk.',
'…풀차지군. 멀리 던져버려.':'…Penuh charge. Lempar jauh.',
'…빈틈을 그대로 빠져나갔다.':'…Lolos melewati celah.',
'…일반 잡몹이 아니야. 모디파이어 붙었군.':'…Bukan monster biasa. Ada modifier.',
'엘리트 하나 처리.':'Satu elite dikalahkan.',
'…큰 놈이다. 일반 잡몹 정리부터.':'…Yang besar itu. Bersihkan yang biasa dulu.',
'미니보스 처리. 다음 길로.':'Mini-bos dikalahkan. Lanjut jalan.',
'한 번에 다섯. 깔끔해.':'Lima sekaligus. Rapi.',
'100강. 이제 뭔가 다르게 보이는군.':'+100. Sekarang segalanya terlihat berbeda.',
'…운이 없는 날이야.':'…Hari sial.',
'…전설이다. 이런 건 처음 본다.':'…Legendaris. Belum pernah lihat yang seperti ini.',
'…죽었다 살아났네. 여신은 너를 포기 안 했어.':'…Mati dan kembali. Dewi tidak menyerah padamu.',
'…또야? 패턴 좀 외워!':'…Lagi? Hafalkan polanya!',
'…한 번도 안 죽고. 그건 진짜 실력이야.':'…Tidak pernah mati. Itu kemampuan sejati.',
'…ACT1을 끝냈다. 진짜 시작은 여기서부터야.':'…ACT1 selesai. Awal yang sebenarnya di sini.',
'모든 보스를 무너뜨렸다. 너는 지옥의 일부야.':'Semua bos jatuh. Kamu adalah bagian dari Neraka.',
'…30초. 너 진짜 미쳤구나.':'…30 detik. Kamu benar-benar gila.',
'…빠르군. 효율적이야.':'…Cepat. Efisien.',
'신기록이다.':'Rekor baru.',
'탭 장비창을 열어봐.':'Buka jendela perlengkapan dengan TAB.',
'데미지 부족하면 무기 강화!':'Kerusakan kurang? Tingkatkan senjata!',
// --- Loading screen ---
'불러오는 중...':'Memuat...',
'로딩중...':'Memuat...',
'맵과 몬스터 불러오는 중...':'Memuat peta dan monster...',
'기본 데이터 준비 중...':'Menyiapkan data dasar...',
'저장 데이터 불러오는 중...':'Memuat data simpanan...',
'몬스터 스킨 로딩...':'Memuat skin monster...',
'맵과 몬스터 생성 중...':'Membuat peta dan monster...',
'맵 에셋 로딩...':'Memuat aset peta...',
'맵 환경 준비 중...':'Menyiapkan lingkungan peta...',
'주변 청크 준비 중...':'Menyiapkan chunk sekitar...',
'맵 캐시 생성 중...':'Membangun cache peta...',
'미니맵 빌드 중...':'Membangun minimap...',
// Phase 28
' 으로 탈출!':' untuk kabur!',
'100명?! 미쳤어!':'100 korban?! Gila!',
'10단 최고난이도! 너 진짜 광기야!':'Kesulitan 10 maks! Benar-benar gila!',
'1분 안에 클리어! 빠르네!':'Selesai dalam 1 menit! Cepat sekali!',
'30초!! 스피드런 가능해!':'30 detik!! Potensi speedrun!',
'3단! 보상도 좋아지지만 죽기 쉬워!':'Kesulitan 3! Hadiah lebih baik tapi mudah mati!',
'50명! 학살자야!':'50 korban! Pembantai!',
'5단!! 진짜 게이머 인증!':'Kesulitan 5!! Gamer sejati tersertifikasi!',
'7단!! 다른 사람들 이 정도 못 와!':'Kesulitan 7!! Yang lain tidak sampai sejauh ini!',
'ACT1 완주! 우리가 진짜 해냈어!':'ACT1 selesai! Kita benar-benar berhasil!',
'Ctrl 얼음보주로 탈출하라.':'Ctrl — kabur dengan Ice Orb.',
'Ctrl 유령걸음으로 탈출하라.':'Ctrl — kabur dengan Ghost Walk.',
'C키! 패시브 강해져!':'Tombol C! Pasif makin kuat!',
'DEX 빌드! 거리에서 패고, 추적탄 좋아!':'Build DEX! Serangan jarak jauh, peluru pengintai!',
'E로 마력공격을 해봐!':'Coba serangan sihir dengan E!',
'G 눌러서 대장간 가봐!':'Tekan G — pandai besi!',
'G키 대장간. 강화 안 하면 계속 죽어.':'G — pandai besi. Tanpa upgrade, terus mati.',
'HP 70%! 조심해!':'HP 70%! Hati-hati!',
'INT 빌드! 빔이랑 폭발 마법! MP 잘 봐!':'Build INT! Sihir sinar dan ledakan! Pantau MP!',
'LCK 높아! 레어 드롭률 미친 거 알지?':'LCK tinggi! Tingkat drop langka gila-gilaan!',
'L로 어디에 뭘 넣을지 골라!':'Tekan L — pilih pengaturan slot skill!',
'MP 부족! 평타로 패면서 회복해!':'MP rendah! Pukul untuk memulihkan!',
'ST 없으면 스킬 못 써!':'Tanpa ST, tanpa skill!',
'STR 빌드! 회전참, 회오리, 광역기 추천!':'Build STR! Tebasan putar, pusaran, AoE!',
'VIT 좀 찍어! HP 너무 적어!':'Tambah VIT! HP terlalu rendah!',
'Z 누르면 대박! 쿨타임 길어!':'Tekan Z untuk ultimate! Cooldown panjang!',
'…고기 냄새. 싫진 않네.':'…Bau darah. Tidak buruk.',
'…둘러싸이면 끝이야.':'…Dikepung berarti tamat.',
'…말은 못해.':'…Tidak bisa bicara.',
'…버리기 아까운 건 창고에.':'…Simpan barang berharga di gudang.',
'…빈틈을 노려.':'…Perhatikan celah.',
'…설정을 확인해.':'…Periksa pengaturan.',
'…슬롯을 채워. 빈 손은 죽음이다.':'…Isi slot. Tangan kosong berarti mati.',
'…아직 살아있네. 좌클릭으로 저것들 쳐봐.':'…Masih hidup. Klik kiri untuk memukul.',
'…운이 좋았을 뿐이야. 아마.':'…Hanya beruntung. Mungkin.',
'…치는 건 할 줄 아네. 피하는 건?':'…Bisa memukul. Bisa menghindar?',
'…힘을 골라라. 전부 가질 순 없다.':'…Pilih kekuatanmu. Tidak bisa punya semua.',
'골고루 안 돼! 하나로 밀어!':'Jangan menyebar! Fokus satu stat!',
'그로기 터지면 1.5배!':'Groggy = kerusakan 1.5x!',
'길이 열렸다.':'Jalan terbuka.',
'나머진 전부 우클릭 패링 가능!':'Sisanya — klik kanan parry!',
'나머진 전부 우클릭!':'Sisanya — klik kanan!',
'다섯 번 연속! 내가 본 인간 중 최고!':'Lima kali berturut-turut! Terbaik yang pernah kulihat!',
'다음엔 죽지 마!':'Jangan mati lagi!',
'소환수 왔어! 먼저 처리해야 해!':'Monster dipanggil! Bereskan mereka dulu!',
'스킬 없으면 방향키 연타뿐이야.':'Tanpa skill? Spam tombol panah saja.',
'신기록!! 스트리머한테 보내!':'Rekor baru!! Kirim ke streamer!',
'아이템 넘쳐! 우리가 주워줄게!':'Tas penuh! Kami yang akan memungut!',
'안 죽고 깼어! 진짜 천재 맞네!':'Selesai tanpa mati! Jenius sejati!',
'앞으로 가자~':'Ayo maju~',
'우리가 해냈어! 다음 챕터 가자!':'Kita berhasil! Chapter berikutnya!',
'일반 모드! 편하게 즐기자!':'Mode normal! Santai saja!',
'자원이 반이다. F키로 회복해.':'Sumber daya setengah. Tekan F untuk pulih.',
'잡힌다! 옆으로 빠져!':'Tertangkap! Hindari ke samping!',
'장비 분해해! 쓰레기도 악의!':'Hancurkan perlengkapan! Sampah pun beri malice!',
'전부 다 잡았어! 우리가 지옥의 왕이야!':'Semua dibersihkan! Kita raja neraka!',
'좋은 거 나왔다! TAB!':'Loot bagus! TAB!',
'죽기 직전에 죽이다니! 멋져!':'Membunuh tepat sebelum mati! Keren!',
'체력 반 남았어! 물약 마실 타이밍!':'HP setengah! Waktunya minum ramuan!',
'큰 거 온다! 도망쳐!':'Serangan besar datang! Lari!',
'패링으로 돌려주고, Q 보호막도 써!':'Parry dan pantulkan, pakai perisai Q juga!',
'패턴이 빨라졌어!':'Pola semakin cepat!',
'한 대만 맞아도 죽어! 패링이든 회피든!!':'Satu pukulan = mati! Parry atau hindari!!',
'한 방이면 죽어! 도망쳐!!':'Satu tembakan membunuh! Lari!!',
'화염엔 빙결! 암전엔 암흑!':'Api → es! Kekosongan → bayangan!',
'── 2장 - 벌레굴 ──':'── CH2 - Worm Nest ──',
'── 4장 - 화염지대 ──':'── CH4 - Infernal Wastes ──',
'── 6장 - 사도마굴 ──':'── CH6 - Apostle Den ──',
'── 공통 ──':'── Common ──',
'☠ 부활력 고갈!':'☠ Kebangkitan Habis!',
'⏳⚡ 시간걸음!':'⏳⚡ Langkah Waktu!',
'블룸 효과':'Efek Bloom',
'잔상 트레일':'Jejak Bayangan',
'슬래시 이펙트':'Efek Tebas',
'후처리 효과':'Efek Pasca-proses',
'사망 이펙트':'Efek Kematian',
'동적 조명':'Pencahayaan Dinamis',
'횃불 조명 (어둠)':'Cahaya Obor (Gelap)',
'앰비언트 파티클':'Partikel Ambient',
'안개 효과':'Efek Kabut',
'필름 그레인':'Butiran Film',
'캐릭터 외곽선':'Garis Tepi Karakter',
'리롤':'Lempar Ulang',
'물약':'Ramuan',
'으로 탈출!':'untuk kabur!',
'Shift 작살':'Shift Tombak',
'더블탭 전격이동':'Ketuk Dua Kali — Melesat',
'Ctrl 유령걸음':'Ctrl Langkah Hantu',
'Ctrl 얼음보주':'Ctrl Bola Es',
'🔴화염→빙결 2배 | 🔵빙결→화염 2배 | ⚪물리=중립 | 악마 처치 시 악의 영혼 드롭':'🔴Api→Es 2× | 🔵Es→Api 2× | ⚪Fis=Netral | Bunuh iblis untuk jiwa kejahatan',
  '미구현':'N/A',
  '스탯 총량':'Total statistik',
  '장비':'perlengkapan',
  '공속':'kec.serangan',
  '크리':'kritis',
  '크리뎀':'dmg kritis',
  '근성':'Keteguhan',
  '종합 지표':'Ikhtisar',
  '근접 DPS':'DPS jarak dekat',
  '공격력×공속×크리':'ATK×Kec×Kritis',
  '활 DPS':'DPS busur',
  '마법 DPS':'DPS sihir',
  '유효 HP (EHP)':'HP efektif (EHP)',
  '쉴드':'Perisai',
  '장비 파워':'Kekuatan equip',
  '근접 공격력':'ATK jarak dekat',
  '기본':'dasar',
  '무기':'senjata',
  '패시브':'pasif',
  '활 공격력':'ATK busur',
  '정밀':'Presisi',
  '마법 공격력':'ATK sihir',
  '왕관':'mahkota',
  '마력':'Sihir',
  '공격속도':'Kecepatan serangan',
  '크리티컬':'Kritis',
  '데미지':'kerusakan',
  '확률':'Probabilitas',
  '어픽스':'afiks',
  '레거시':'warisan',
  '추가뎀':'bonus kerusakan',
  '패링 카운터뎀':'DMG Parry Counter',
  '우클공속':'Kecepatan klik kanan',
  '무지개탄DR':'DR pelangi',
  '포이즈파괴':'Hancurkan Poise',
  '방어관통':'Penetrasi armor',
  '관통력':'Penetrasi',
  '속성':'Elemen',
  '무기속성':'Elemen senjata',
  '독':'Racun',
  '초':'s',
  '암흑저주':'Kutukan gelap',
  '원소집중':'Fokus elemen',
  '원소전환':'Konversi elemen',
  '방어':'Pertahanan',
  '물리방어':'DEF fisik',
  '감소':'pengur.',
  '캡':'batas',
  '장갑':'sarung tangan',
  '바지':'celana',
  '속성방어':'DEF elemen',
  '목걸이':'kalung',
  '반지1':'cincin1',
  '반지2':'cincin2',
  '반사':'Pantul',
  '가시':'Duri',
  '배리어':'Penghalang',
  '보호막 흡수':'Penyerapan perisai',
  '속성 저항':'Resistensi elemen',
  'CC저항':'Resistensi CC',
  '생존':'Ketahanan hidup',
  '장비HP':'HP equip',
  '임플':'Impl.',
  '에너지쉴드':'Perisai energi',
  '리젠':'Regen',
  '스태미나':'Stamina',
  '성장':'Pertumbuhan',
  'MP%어픽스':'Afiks MP%',
  '이동속도':'Kecepatan gerak',
  '한방캡':'Batas satu pukulan',
  '최대HP의33%':'33% HP maks',
  '비용/효율':'Biaya/Efisiensi',
  '근접ST':'ST jarak dekat',
  '활ST':'ST busur',
  '마법MP':'MP sihir',
  '작살사거리':'Jangkauan harpun',
  '기동게이지':'Bar Drive',
  '쿨감':'CDR',
  '쇠뇌뎀':'DMG Xbow',
  '쇠뇌공속':'Kec. Xbow',
  '기타':'Lainnya',
  '물약쿨':'CD ramuan',
  '회복+':'Pemulihan+',
  '드롭':'Drop',
  '경험치+':'EXP+',
  '골드+':'Emas+',
  '기동:칼날개':'Drive:Pisau',
  '기동:전폭':'Drive:Serangan',
  '기동:기습':'Drive:Penyergapan',
  '충전스킬':'Skill charge',
  '사슬게이지':'Bar rantai',
  '특수 효과':'Efek khusus',
  '처치뎀+':'DMG bunuh+',
  '위기뎀+':'DMG krisis+',
  '피격반격':'Balas serangan',
  '풍요(적HP≥70%뎀+)':'Kelimpahan(HP≥70%+)',
  '약자포식(적HP≤30%뎀+)':'Predator(HP≤30%+)',
  '패링폭발':'Ledakan Parry',
  '체간파괴+':'Hancurkan Poise+',
  '콤보뎀+':'DMG combo+',
  '작살뎀+':'DMG harpun+',
  '스킬뎀+':'DMG skill+',
  '패리+':'Parri+',
  '체인':'Rantai',
  '정화':'Pembersihan',
  '회':'×',
  '불굴':'Keteguhan',
  '신성력':'Kekuatan suci',
  '악마력(부활력)':'Kekuatan setan',
  '자연':'Alam',
  '악마성':'Sifat setan',
  '인간성':'Kemanusiaan',
  '전투 통계':'Statistik tempur',
  '핵터':'Hecter',
'디로이':'Deroy',
// --- Phase 37: skill desc ---
'성능 등급:':'Perf Grade:',
'벤치 FPS:':'Bench FPS:',
// --- CAT-82: skill panel labels ---
'스킬 정보':'Skill Info',
'타입':'Type',
'미습득':'Not Learned',
'SP 비용':'SP Cost',
'악의 비용':'Malice Cost',
'쿨다운':'Cooldown',
'요구 레벨':'Req. Lv',
'기본 참조뎀':'Base Reference',
'스탯 배율':'Stat Mult',
'패시브 배율':'Passive Mult',
'레벨 배율':'Skill Lv Mult',
'예상 평균 뎀':'Estimated Avg DMG',
'치명타':'Critical',
'치명타 확률':'Crit Rate',
'치명타 배율':'Crit Dmg',
'유효 배율':'Effective Mult',
'스킬 고유':'Skill Specific',
'1타 배율':'1-Hit Mult',
'2타 배율':'2-Hit Mult',
'3타 배율':'3-Hit Mult',
'레벨당 뎀':'Per Lv DMG',
'검기 거리':'Crescent Range',
'레벨당 거리':'Lv Range Bonus',
'ST/틱':'ST/Tick',
'레벨당 크기':'Per Lv Size',
'넉백':'Knockback',
'충전 시간':'Charge Time',
'레벨당 범위':'Per Lv Range',
'관통률':'Pierce Rate',
'지속뎀':'DOT Duration',
'무한':'Infinite',
'타격 형식':'AoE Type',
'진동파':'Shockwave',
'스태거':'Stagger',
'높음':'High',
'스톡':'Stocks',
'기둥 수':'Pillars',
'지속':'Duration',
'반경':'Radius',
'슬로우':'Slow',
'활':'Bow',
// --- CAT-83: affix desc labels ---
'독 DoT':'Poison DoT',
'화상 DoT':'Fire DoT',
'빙결 DoT+감속':'Ice DoT+Slow',
'연쇄전격':'Chain Lightning',
'저주(힐차단)':'Curse(Heal Block)',
'방어무시':'Armor Ignore',
'치명타율':'Crit Rate',
'스태거+':'Stagger+',
'체인타겟+':'Chain Target+',
'처치 후 뎀+':'Kill DMG+',
'크리폭발(ATK×)':'Crit Explode(ATK×)',
'원소뎀+':'Elem DMG+',
'공격속도+':'Atk Spd+',
'패리보너스+':'Parry Bonus+',
'추적콤보+10':'Track Combo+10',
'작살뎀+':'Harpoon DMG+',
'스킬뎀+':'Skill DMG+',
'쿨다운-':'CD-',
'방어력+':'DEF+',
'쉴드+':'Shield+',
'이동속도+':'Move Spd+',
'크리확률+':'Crit Rate+',
'크리배율+':'Crit Dmg+',
'화염저항':'Fire Res',
'빙결저항':'Ice Res',
'암전저항':'Lightning Res',
'암흑저항':'Dark Res',
'독저항':'Poison Res',
'전원소저항':'All Elem Res',
'물리DR':'Phys DR',
'반사%':'Reflect%',
'가시뎀':'Thorns DMG',
'배리어':'Barrier',
'CC저항':'CC Resist',
'위기뎀+':'Crisis DMG+',
'피격반격':'Hit Counter',
'패링폭발(ATK×)':'Parry Burst(ATK×)',
'체간파괴뎀+':'Poise Break DMG+',
'원소전환':'Elem Convert',
'상태이상해제':'Status Clear',
'불굴(1회생존)':'Tenacity(Survive×1)',
'부활(HP회복)':'Revive(HP Restore)',
'드롭률+':'Drop Rate+',
'경험치+':'EXP+',
'골드+':'Gold+',
'포션회복+':'Potion Heal+',
'사슬게이지+':'Chain Gauge+',
'부활억제':'Anti-Revive',
'부활력+':'Revival Pow+',
'부활쿨-':'Revival CD-',
'최대HP%+':'Max HP%+',
'HP리젠+':'HP Regen+',
'회복력+':'Heal Pow+',
'마법뎀+':'Magic DMG+',
'MP소비-':'MP Cost-',
'화염뎀%+':'Fire DMG%+',
'화염관통%':'Fire Pen%',
'적중화상':'On-Hit Burn',
'크리화폭':'Crit Fire Burst',
'화상지속+':'Burn Duration+',
'화염뎀보너스':'Fire DMG Bonus',
'빙결뎀%+':'Ice DMG%+',
'빙결관통%':'Ice Pen%',
'적중빙결':'On-Hit Freeze',
'크리빙폭':'Crit Ice Burst',
'빙결지속+':'Freeze Duration+',
'빙결뎀보너스':'Ice DMG Bonus',
'뇌전뎀%+':'Lightning DMG%+',
'뇌전관통%':'Lightning Pen%',
'적중감전':'On-Hit Shock',
'크리뇌폭':'Crit Lightning Burst',
'감전지속+':'Shock Duration+',
'뇌전뎀보너스':'Lightning DMG Bonus',
'암흑뎀%+':'Dark DMG%+',
'암흑관통%':'Dark Pen%',
'적중저주':'On-Hit Curse',
'크리암폭':'Crit Dark Burst',
'저주지속+':'Curse Duration+',
'암흑뎀보너스':'Dark DMG Bonus',
'독뎀%+':'Poison DMG%+',
'독관통%':'Poison Pen%',
'적중중독':'On-Hit Poison',
'크리독폭':'Crit Poison Burst',
'독지속+':'Poison Duration+',
'독뎀보너스':'Poison DMG Bonus',
'근접뎀%+':'Melee DMG%+',
'원거리뎀%+':'Ranged DMG%+',
'마법뎀%+':'Magic DMG%+',
'빔뎀%+':'Beam DMG%+',
'DoT뎀%+':'DoT DMG%+',
'투사체뎀%+':'Proj DMG%+',
'범위반경+':'AoE Radius+',
'근접크리+':'Melee Crit+',
'마법크리+':'Magic Crit+',
'석궁크리+':'Xbow Crit+',
'근접공속+':'Melee Spd+',
'석궁공속+':'Xbow Spd+',
'시전속도+':'Cast Spd+',
'전속성관통':'All Elem Pen',
'쉴드관통':'Shield Pen',
'방어력깎기':'Armor Shred',
'투사체속도+':'Proj Speed+',
'적중시화구':'On-Hit Fireball',
'적중시연쇄뇌격':'On-Hit Chain Lightning',
'적중빙결%':'On-Hit Freeze%',
'적중스턴%':'On-Hit Stun%',
'적중중독%':'On-Hit Poison%',
'적중출혈%':'On-Hit Bleed%',
'적중약화%':'On-Hit Weaken%',
'적중감속%':'On-Hit Slow%',
'적중표적%':'On-Hit Mark%',
'크리폭발(HP%)':'Crit Explode(HP%)',
'크리연쇄(HP%)':'Crit Chain(HP%)',
'크리빙결%':'Crit Freeze%',
'크리HP+':'Crit HP+',
'크리MP+':'Crit MP+',
'크리쉴드+':'Crit Shield+',
'피격방어+':'Hit DEF+',
'반격가시':'Counter Thorns',
'빙결파동%':'Ice Nova%',
'자동암흑막':'Auto Dark Shield',
'주기치유':'Periodic Heal',
'시체폭발%':'Corpse Explode%',
'회피뎀+':'Dodge DMG+',
'패링폭발%':'Parry Burst%',
'블록HP+':'Block HP+',
'블록MP+':'Block MP+',
'회전참뎀+':'Whirlwind DMG+',
'옴니빔뎀+':'Omni Beam DMG+',
'화구뎀+':'Fireball DMG+',
'미사일뎀+':'Missile DMG+',
'청탄뎀+':'Blue Shot DMG+',
'폭렬탄뎀+':'Blast Shot DMG+',
'지옥광선뎀+':'Hell Ray DMG+',
'악의폭풍뎀+':'Malice Storm DMG+',
'연쇄참뎀+':'Chain Slash DMG+',
'거인강타뎀+':'Giant Slam DMG+',
'유령보행뎀+':'Ghost Walk DMG+',
'악의박격뎀+':'Malice Mortar DMG+',
'화염오라뎀+':'Fire Aura DMG+',
'빙구뎀+':'Ice Orb DMG+',
'화염빔뎀+':'Fire Beam DMG+',
'악의사냥뎀+':'Malice Hunt DMG+',
'암흑기둥뎀+':'Dark Pillar DMG+',
'역병뎀+':'Plague DMG+',
'가시오라뎀+':'Spike Aura DMG+',
'연쇄돌격뎀+':'Chain Assault DMG+',
'회피확률+':'Dodge Rate+',
'회피쿨-':'Dodge CD-',
'쉴드%+':'Shield%+',
'쉴드리젠%+':'Shield Regen%+',
'쉴드쿨-':'Shield CD-',
'HP리젠%+':'HP Regen%+',
'ST리젠+':'ST Regen+',
'ST리젠%+':'ST Regen%+',
'MP리젠+':'MP Regen+',
'MP리젠%+':'MP Regen%+',
'화염DR':'Fire DR',
'빙결DR':'Ice DR',
'뇌전DR':'Lightning DR',
'암흑DR':'Dark DR',
'독DR':'Poison DR',
'전체DR':'All DR',
'엘리트DR':'Elite DR',
'스턴저항':'Stun Res',
'감속저항':'Slow Res',
'넉백저항':'KB Res',
'돌진거리+':'Dash Range+',
'돌진쿨-':'Dash CD-',
'전투이속+':'Combat MSpd+',
'비전투이속+':'Out-Combat MSpd+',
'습득범위+':'Pickup Range+',
'전스탯+':'All Stats+',
'적중자원+':'On-Hit Resource+',
'화염최대저항+':'Fire Max Res+',
'빙결최대저항+':'Ice Max Res+',
'뇌전최대저항+':'Lightning Max Res+',
'암흑최대저항+':'Dark Max Res+',
'독최대저항+':'Poison Max Res+',
'스킬쿨-':'Skill CD-',
'물약쿨-':'Potion CD-',
'강화성공+':'Craft Rate+',
'악의획득+':'Malice Gain+',
'악마화뎀+':'Demon DMG+',
'악마화DR':'Demon DR',
'영혼수확+':'Soul Harvest+',
'생명흡혈%':'Life Leech%',
'과치유→쉴드':'Overheal→Shield',
'만마나뎀+':'Full MP DMG+',
'이동DR':'Move DR',
'정지뎀+':'Stationary DMG+',
'회피후뎀+':'After Dodge DMG+',
'패링쉴드+':'Parry Shield+',
'콤보보너스+':'Combo Bonus+',
'HP≥70%뎀+':'HP≥70% DMG+',
'적HP≤30%뎀+':'Foe HP≤30% DMG+',
'HP100%뎀+':'HP100% DMG+',
'HP≤35%뎀+':'HP≤35% DMG+',
'적HP≤20%뎀+':'Foe HP≤20% DMG+',
'근접뎀+':'Melee DMG+',
'원거리뎀+':'Ranged DMG+',
'스턴적뎀+':'vs Stunned DMG+',
'빙결적뎀+':'vs Frozen DMG+',
'화상적뎀+':'vs Burning DMG+',
'중독적뎀+':'vs Poisoned DMG+',
'저주적뎀+':'vs Cursed DMG+',
'감속적뎀+':'vs Slowed DMG+',
'보스뎀+':'Boss DMG+',
'엘리트뎀+':'Elite DMG+',
'일반몹뎀+':'Mob DMG+',
'선제뎀+':'First Strike DMG+',
'물리흡혈%':'Phys Leech%',
'마나흡수%':'Mana Leech%',
'ST흡수%':'ST Leech%',
'적중HP+':'On-Hit HP+',
'처치HP+':'On-Kill HP+',
'처치MP+':'On-Kill MP+',
'처치ST+':'On-Kill ST+',
'처치시폭발':'On-Kill Explode',
'처치이속+':'On-Kill MSpd+',
'HP≥70%방어+':'HP≥70% DEF+',
'HP≤50%이속+':'HP≤50% MSpd+',
'DoT피해감소':'DoT DMG Reduce',
'보스피해감소':'Boss DMG Reduce',
'근접피해감소':'Melee DMG Reduce',
'원거리피해감소':'Ranged DMG Reduce',
'처치HP회복':'On-Kill HP Restore',
'처치쉴드회복':'On-Kill Shield Restore',
'ST소비-':'ST Cost-',
'HP≥70%공격+':'HP≥70% ATK+',
'HP≤35%흡혈':'HP≤35% Leech',
'보스추가뎀':'vs Boss DMG+',
'엘리트추가뎀':'vs Elite DMG+',
'공격력+':'ATK+',
'크리뎀+':'Crit DMG+',
// --- CAT-84/85/86: affix names + implicit + legendary ---
'물리방패의':'Physical Shield',
'지속의':'Stamina',
'마나의':'Mana',
'원소수호의':'Elem Guard',
'행운의':'Fortune',
'근성의':'Grit',
'풍요의':'Abundance',
'약자포식의':'Predator',
'만혈의':'Full Life',
'사선의':'Low Life',
'처형의':'Execute',
'근접살의':'Melee DMG',
'원거리의':'Ranged',
'경직파의':'Stagger Break',
'동파의':'Freeze Strike',
'연소의':'Burning',
'맹독살의':'Venom Slayer',
'저주살의':'Curse Slayer',
'구속의':'Binding',
'왕살의':'Boss Slayer',
'정예살의':'Elite Slayer',
'군살의':'Mob Slayer',
'선제의':'First Strike',
'흡혈의':'Vampirism',
'흡마의':'Mana Leech',
'흡정의':'Stamina Leech',
'타격재생의':'Hit Regen',
'처치회복의':'Kill Recovery',
'처치흡마의':'Kill Mana Leech',
'처치활력의':'Kill Stamina',
'처치폭발의':'Kill Explosion',
'처치질주의':'Kill Sprint',
'건강방어의':'Healthy Defense',
'중상보호의':'Wounded Shield',
'위기질주의':'Crisis Sprint',
'지속피해방어의':'DoT DR',
'왕피해방어의':'Boss DMG DR',
'근접방어의':'Close DR',
'원거리방어의':'Ranged DR',
'처치생명의':'Kill HP',
'처치수호의':'Kill Shield',
'화염강화의':'Fire Amp',
'화염관통의':'Fire Pierce',
'발화의':'Ignition',
'화염폭발의':'Fire Burst',
'맹화의':'Blaze',
'화염의힘':'Fire Power',
'빙결강화의':'Ice Amp',
'빙결관통의':'Ice Pierce',
'동결의':'Freeze',
'빙결폭발의':'Ice Burst',
'영빙의':'Permafrost',
'빙결의힘':'Ice Power',
'뇌전강화의':'Thunder Amp',
'뇌전관통의':'Thunder Pierce',
'감전의':'Shock',
'뇌전폭발의':'Thunder Burst',
'낙뢰의':'Thunderbolt',
'뇌전의힘':'Thunder Power',
'암흑강화의':'Dark Amp',
'암흑관통의':'Dark Pierce',
'침식의':'Erosion',
'암흑폭발의':'Dark Burst',
'심연의':'Abyss',
'암흑의힘':'Dark Power',
'맹독강화의':'Venom Amp',
'독관통의':'Poison Pierce',
'중독의':'Poisoning',
'독폭발의':'Poison Burst',
'맹독지속의':'Venom Duration',
'독의힘':'Poison Power',
'격투의':'Melee',
'원사의':'Ranged Shot',
'주술의':'Spell',
'광선의':'Beam',
'탄도의':'Ballistic',
'확산의':'AoE Radius',
'근접회심의':'Melee Crit',
'마법회심의':'Spell Crit',
'사격회심의':'Ranged Crit',
'근접쾌속의':'Melee Speed',
'사격쾌속의':'Ranged Speed',
'영창의':'Chanting',
'전속성관통의':'All-Elem Pierce',
'쉴드파괴의':'Shield Bypass',
'갑옷분쇄의':'Armor Shred',
'탄속의':'Proj Speed',
'화구발사의':'Fireball Launch',
'연쇄뇌격의':'Chain Lightning',
'동결타의':'Freeze Strike',
'경직타의':'Stagger Strike',
'독침의':'Poison Sting',
'출혈의':'Bleed',
'약화의':'Weakness',
'둔화의':'Slow',
'표적의':'Marking',
'회심폭발의':'Crit Explosion',
'회심연쇄의':'Crit Chain',
'회심빙결의':'Crit Freeze',
'회심치유의':'Crit Heal',
'회심영력의':'Crit Mana',
'회심수호의':'Crit Shield',
'피격강화의':'Hit Boost',
'반격가시의':'Counter Thorns',
'빙결파동의':'Ice Nova',
'암흑보호의':'Dark Shield',
'치유파동의':'Heal Pulse',
'시체폭발의':'Corpse Explosion',
'회피반격의':'Dodge Counter',
'패링폭파의':'Parry Shatter',
'블록치유의':'Block Heal',
'블록영력의':'Block Mana',
'회전참강화':'Spin Slash Boost',
'옴니빔강화':'Omni Beam Boost',
'화구강화':'Fireball Boost',
'미사일강화':'Missile Boost',
'청탄강화':'Blue Shot Boost',
'폭렬탄강화':'Burst Shot Boost',
'지옥광선강화':'Hellray Boost',
'악의폭풍강화':'Malice Storm Boost',
'연쇄참강화':'Chain Slash Boost',
'거인강타강화':'Giant Slam Boost',
'유령보행강화':'Ghost Walk Boost',
'악의박격강화':'Malice Mortar Boost',
'화염오라강화':'Fire Aura Boost',
'빙구강화':'Ice Orb Boost',
'화염빔강화':'Fire Beam Boost',
'악의사냥강화':'Malice Hunt Boost',
'암흑기둥강화':'Dark Pillar Boost',
'역병강화':'Plague Boost',
'가시오라강화':'Thorn Aura Boost',
'연쇄돌격강화':'Chain Assault Boost',
'회피의':'Evasion',
'회피쿨감의':'Dodge CD Red',
'수호력의':'Shield Power',
'수호재생의':'Shield Regen',
'수호쿨감의':'Shield CD Red',
'재생력의':'Regen Power',
'활력재생의':'Stamina Regen',
'마력재생의':'Mana Regen',
'화염보호의':'Fire Shield',
'빙결보호의':'Ice Shield',
'뇌전보호의':'Thunder Shield',
'해독의':'Antidote',
'만물보호의':'All Protection',
'정예보호의':'Elite Shield',
'경직저항의':'Stagger Resist',
'빙결저항의':'Freeze Resist',
'감속저항의':'Slow Resist',
'넉백저항의':'Knockback Resist',
'돌진거리의':'Dash Range',
'돌진쿨감의':'Dash CD Red',
'전투질주의':'Combat Sprint',
'평화질주의':'Peace Sprint',
'습득범위의':'Pickup Radius',
'힘의':'Strength',
'민첩의':'Dexterity',
'지능의':'Intelligence',
'만능의':'Versatile',
'지구력의':'Max Stamina',
'마나력의':'Mana Power',
'타격자원의':'Hit Resource',
'화염한계의':'Fire Cap',
'빙결한계의':'Ice Cap',
'뇌전한계의':'Thunder Cap',
'암흑한계의':'Dark Cap',
'독한계의':'Poison Cap',
'스킬쿨감의':'Skill CD Red',
'물약쿨감의':'Potion CD Red',
'장인의':'Craftsmanship',
'탐욕의':'Greed',
'수련의':'Training',
'수집의':'Gathering',
'악마의힘':'Demon Power',
'악마보호의':'Demon Shield',
'영혼수확의':'Soul Harvest',
'생명흡수의':'Life Absorption',
'과치유수호의':'Overheal Shield',
'만마력의':'Full Mana DMG',
'이동방어의':'Moving DR',
'정지공세의':'Stationary Boost',
'회피공세의':'Post-Dodge Boost',
'패링보호의':'Parry Shield',
'콤보폭발의':'Combo Burst',
'물리타격의':'Phys Strike',
'화염타격의':'Fire Strike',
'빙결타격의':'Ice Strike',
'뇌전타격의':'Thunder Strike',
'암흑타격의':'Dark Strike',
'독타격의':'Poison Strike',
'최소공격의':'Min ATK',
'최대공격의':'Max ATK',
'전투력의':'Combat Power',
'무기사거리의':'Weapon Range',
'활사거리의':'Bow Range',
'이중타의':'Double Strike',
'다중발사의':'Multi Shot',
'관통횟수의':'Pierce Count',
'관통유지의':'Pierce Keep',
'연쇄유지의':'Chain Keep',
'범위확장의':'Splash Range',
'범위피해의':'Splash DMG',
'돌진공격의':'Dash ATK',
'반격공격의':'Counter ATK',
'후방타의':'Backstab',
'침식가속의':'Erosion Speed',
'출혈지속의':'Bleed Duration',
'마법타격의':'Magic Strike',
'주문증폭의':'Spell Amp',
'연살뎀의':'Kill Streak DMG',
'연살속의':'Kill Streak Speed',
'기세의':'Momentum',
'정지공격의':'Static Strike',
'이동공격의':'Mobile Strike',
'패링공세의':'Post-Parry Boost',
'임사폭발의':'Near-Death Burst',
'만기력공의':'Full Stamina ATK',
'만마력공의':'Full Mana ATK',
'신선처치의':'Fresh Kill',
'경직연장의':'Stagger Extension',
'빙결연장의':'Freeze Extension',
'둔화강화의':'Slow Amp',
'독중첩의':'Poison Stack',
'출혈중첩의':'Bleed Stack',
'발화강화의':'Ignite Amp',
'동상강화의':'Frostbite Amp',
'감전강화의':'Shock Amp',
'사선회심의':'Low HP Crit',
'갑옷강화의':'Armor Boost',
'블록흡수의':'Block Absorb',
'방패타격의':'Shield Bash',
'방패경직의':'Shield Stagger',
'격투속의':'Brawl Speed',
'격투회심의':'Brawl Crit',
'격투경직의':'Brawl Stagger',
'하반재생의':'Leg Regen',
'CC단축의':'CC Duration Red',
'돌진타의':'Dash Strike',
'돌진범위의':'Dash AoE',
'은신질주의':'Stealth Sprint',
'회피감쇠의':'Dodge DR',
'속성감쇠의':'Elem DR',
'마나왕관의':'Mana Helm',
'시전왕관의':'Cast Helm',
'쿨감왕관의':'CD Helm',
'경험왕관의':'EXP Helm',
'공생의':'Symbiosis',
'수질의':'Body-Soul',
'회심흡의':'Crit Leech',
'체마의':'HP-Mana',
'체기의':'HP-Stamina',
'마기의':'Mana-Stamina',
'전재생의':'All Regen',
'힘민의':'STR-DEX',
'힘지의':'STR-INT',
'민지의':'DEX-INT',
'운근의':'Fortune-Grit',
'수확의':'Harvest',
'빙화의':'Ice-Fire',
'뇌암의':'Thunder-Dark',
'근마의':'Blade-Magic',
'속성침식의':'Elem Erosion',
'화염반지의':'Fire Ring',
'빙결반지의':'Ice Ring',
'뇌전반지의':'Thunder Ring',
'암흑반지의':'Dark Ring',
'독반지의':'Poison Ring',
'콤보반지의':'Combo Ring',
'처치마나의':'Kill Mana',
'관통반지의':'Pierce Ring',
'만능목걸이의':'Allround Necklace',
'회심목걸이의':'Crit Necklace',
'관통목걸이의':'Pierce Necklace',
'스킬목걸이의':'Skill Necklace',
'콤보한계의':'Combo Max',
'처치치유의':'Kill Heal',
'지구벨트의':'Stamina Belt',
'포션벨트의':'Potion Belt',
'활력벨트의':'Vitality Belt',
'탐욕벨트의':'Greed Belt',
'마나띠의':'Mana Band',
'시전띠의':'Cast Band',
'마력띠의':'Magic Band',
'주술띠의':'Spell Band',
'속성띠의':'Elem Band',
'전사의힘':'Warrior Power',
'전사생명의':'Warrior Life',
'전사흡혈의':'Warrior Leech',
'전사인내의':'Warrior Poise',
'마법사의힘':'Mage Power',
'마법사마나의':'Mage Mana',
'마법사수호의':'Mage Shield',
'마법사속성의':'Mage Elem',
'궁수의힘':'Archer Power',
'궁수사거리의':'Archer Range',
'궁수관통의':'Archer Pierce',
'궁수질주의':'Archer Sprint',
'탱크생명의':'Tank Life',
'탱크방어의':'Tank Defense',
'탱크블록의':'Tank Block',
'탱크가시의':'Tank Thorns',
'암살회심의':'Assassin Crit',
'암살후방의':'Assassin Backstab',
'암살독의':'Assassin Poison',
'암살회피의':'Assassin Dodge',
'종결자의':'The Ender',
'생존자의':'Survivor',
'종결수호의':'End Shield',
'종결회심의':'End Crit',
'종결공격의':'End ATK',
'종결저항의':'End Resistance',
'종결파괴의':'End Destruction',
'종결보호의':'End Protection',
'종결흡혈의':'End Leech',
'종결인내의':'End Poise',
'종결쿨감의':'End CD Red',
'종결경험의':'End EXP',
'종결약탈의':'End Loot',
'종결악의의':'End Malice',
'종결힘의':'End STR',
'종결민첩의':'End DEX',
'종결지능의':'End INT',
'종결행운의':'End LCK',
'종결근성의':'End Grit',
'종결연살의':'End Kill Chain',
'건강공세의':'Healthy Offense',
'중상폭발의':'Wounded Burst',
'중상흡혈의':'Wounded Leech',
'토벌의':'Vanguard',
'정예토벌의':'Elite Vanguard',
'극대화의':'Maximize',
'공격력 +X%':'ATK +X%',
'관통 확률 +X%':'Pierce Chance +X%',
'방어율 +X%':'Block Rate +X%',
'물리 피해감소 +X%':'Phys DR +X%',
'최대 HP +X':'Max HP +X',
'공격속도 +X%':'ATK Speed +X%',
'상태이상 저항 +X%':'Status Resist +X%',
'이동속도 +X%':'Move Speed +X%',
'원소 저항 +X%':'Elem Resist +X%',
'최대 HP +X%':'Max HP +X%',
'회피 쿨다운 -X%':'Dodge CD -X%',
'물약 쿨다운 -X%':'Potion CD -X%',
'부활력 +X%':'Revive Power +X%',
'마법 데미지 +X%':'Magic DMG +X%',
'전설 특수':'Legendary Special',
'5타 콤보 완성 시 데빌포스 20% 즉시 충전':'5-hit combo: instantly charge DevilForce 20%',
'처치 시 이속 +40%(3초) + 다음 공격 크리 보장':'Kill: MoveSpd +40%(3s) + next attack guaranteed Crit',
'스태거 발동 시 범위 충격파 (ATK×120%)':'Stagger: AoE shockwave (ATK×120%)',
'스태거 발동 시 범위 충격파 (ATK×100%)':'Stagger: AoE shockwave (ATK×100%)',
'강타 시 적 넉백 거리 2배 + 벽충돌 추가뎀':'Heavy hit: Knockback ×2 + wall collision bonus DMG',
'출혈 대상 크리 시 잔여 DoT×300% 즉시 폭발':'Crit vs Bleeding: remaining DoT×300% instant explosion',
'작살 착지 타격 수만큼 데미지 +20% 중첩(최대5)':'Javelin landing hits: stack +20% DMG (max 5)',
'치명타 시 추가 투사체 1발 발사':'Crit: fire 1 additional projectile',
'패리 성공 시 반격 데미지 ×2':'Parry: counter DMG ×2',
'피격 시 3초 쿨로 HP 5% 즉시 회복':'On Hit (3s CD): restore 5% HP instantly',
'스킬 사용 시 20% 확률로 쿨다운 미소모':'Using skills: 20% chance no cooldown consumed',
'공격속도 +20% + 기본공격에 랜덤 원소 추가':'ATK Speed +20% + basic attacks add random element',
'이동 중 지속 HP 재생 (초당 HP의 1%)':'While moving: HP regen (1% HP/sec)',
'회피 직후 첫 공격 데미지 +80%':'First attack after Dodge: DMG +80%',
'패리 타이밍 판정 +50% 확대':'Parry timing window +50% expanded',
'원소 반응 발동 시 추가 폭발 (ATK×80%)':'Elemental reaction: bonus explosion (ATK×80%)',
'처치 시 데빌포스 5% 회복':'Kill: restore 5% DevilForce',
'HP 50% 이하 시 전 스킬 쿨다운 -30%':'Below 50% HP: all skill CD -30%',
'물약 사용 시 5초간 피해 +15%':'Using Potion: DMG +15% for 5s',
'암묵':'Implicit',
'낡은 악마의 팔찌':'Worn Demon Bracelet',
'흑요석 악마의 팔찌':'Obsidian Demon Bracelet',
'미스릴 악마의 팔찌':'Mithril Demon Bracelet',
'낡은 생명의 팔찌':'Worn Life Bracelet',
'확인':'Confirm',
'조작법':'Controls',
'살아남으려면 익혀라':'Master this to survive',
'전투':'Combat',
'이동 / 상호작용':'Move / Interact',
'메뉴':'Menu',
'시스템':'System',
'아무 키를 눌러 시작':'Press any key to start',
'스테이지':'Tahap',
'💪 힘 (STR)':'💪 STR',
'🏹 민첩 (DEX)':'🏹 DEX',
'🔮 지능 (INT)':'🔮 INT',
'🍀 행운 (LCK)':'🍀 LCK',
'⚔️ 맹공':'⚔️ Onslaught',
'🔱 돌파':'🔱 Breakthrough',
'⚡ 반격':'⚡ Retaliation',
'🔮 마력폭주':'🔮 Mana Surge',
'🎯 정밀사격':'🎯 Precision',
'🛡 수호신':'🛡 Aegis',
'💚 회복력':'💚 Recovery',
'💥 급소':'💥 Vital Strike',
'🎁 약탈':'🎁 Plunder',
'🔱 관통':'🔱 Pierce',
'💠 마력회복':'💠 Mana Recovery',
'🏹 쇠뇌력':'🏹 Crossbow Mastery',
'⚔ 광전사':'⚔ Berserker',
'🎯 추적자':'🎯 Tracker',
'🗡 물리관통':'🗡 Phys Penetration',
'🔮 마법관통':'🔮 Magic Penetration',
'🌿 풍요':'🌿 Abundance',
'🐺 약자포식':'🐺 Predator',
'☠ 침식':'☠ Corrosion',
'💎 마력그릇':'💎 Mana Vessel',
'💪 힘의그릇':'💪 Stamina Vessel',
'👿 악의중독':'👿 Malice Addict',
'❤️ 강인':'❤️ Fortify',
'🛡 철벽':'🛡 Iron Wall',
'🎯 사냥꾼':'🎯 Hunter',
'✦ 인간성':'✦ Humanity',
'☠ 악마성':'☠ Demon',
'1. 악의폭풍':'1. Malice Storm',
'2. 칼날 계열':'2. Blade Skills',
'3. 역병 확장':'3. Plague Expand',
'4. 이동스킬 마스터':'4. Movement Master',
'5. 사슬 확장':'5. Chain Expand',
'6. 💀 필살기 선택':'6. 💀 Ultimate Pick',
'7. 멸살+만화+원소+전격이동':'7. Beam+Barrage+Elem+Blink',
'8. 회전참+기폭+대왕':'8. Whirl+Det+Giant',
'9. 방패 합체':'9. Shield Fuse',
'10. 해골무덤+악의폭풍':'10. Bone Wall+Malice Storm',
'11. 폭풍소환+얼음보주':'11. Storm+Ice Orb',
'12. 뇌전걸음':'12. Ghost Walk',
'13. 신성 영역':'13. Holy Domain',
'14. 6단합체: 폭풍빔':'14. 6-Fuse: Storm Beam',
'15. 신성+빙결':'15. Holy+Ice',
'16. 암흑+가시+대왕2':'16. Dark+Spike+Slam2',
'17. 사슬 최종':'17. Chain Final',
'⚡ 이동스킬':'⚡ Movement',
'⚔️ 물리':'⚔️ Physical',
'🛡️ 방어':'🛡️ Defense',
'🔮 마법':'🔮 Magic',
'🏹 석궁/투사체':'🏹 Crossbow/Projectile',
'⚙️ 영역':'⚙️ Domain',
'💀 필살기':'💀 Ultimate',
'⭐ 추천':'⭐ Recommend',
'⚔ 공격':'⚔ Attack',
'🛡 방어':'🛡 Defense',
'⚙ 특수':'⚙ Special',
  '👻 공성유령!':'👻 Hantu Pengepungan!',

'STEAM 위시리스트':'Daftar Keinginan Steam',
'STEAM 위시리스트로 응원해 주세요!':'Dukung kami dengan menambahkan ke daftar keinginan Steam!',
'⚔ 난타!':'⚔ Barrage!',
'⚡ 연격!':'⚡ Rapid Strike!',
'더블탭 or Shift+방향키! 전격이동으로 탈출해!':'Ketuk dua kali atau Shift+Arah! Dash untuk kabur!',
'데모 종료':'Akhir Demo',
'독사':'Ular Berbisa',
'방어↓':'DEF↓',
'여기까지 데모입니다. 정식 출시를 기대해주세요!':'Ini adalah akhir dari demo. Nantikan rilis penuhnya!',
'프레임 표시 (FPS)':'Tampilkan FPS',
'흑요염 파괴자':'Penghancur Api Obsidian',
'🌀 휘두르기!':'🌀 Sweep!',
'🐍 독사!':'🐍 Ular Berbisa!',
'💥 강타!':'💥 Slam!',
'💥 공성유령 폭발!':'💥 Ledakan Hantu Pengepung!',
'목표 달성!':'Target tercapai!',
'악의 고갈':'Kebencian habis',
'시도':'Percobaan',
'소비':'Terpakai',
'목표':'Target',
'미달':'Belum tercapai',
'악의를 더 모아 재시도하세요':'Kumpulkan lebih banyak Kebencian dan coba lagi',
'습득':'Pelajari',
'레벨업':'Naik Lv',
'⚡기동+10':'⚡Dash+10',
'게임 종료':'Keluar game',
'영역스킬':'Skill area',
'석궁자동':'Panah otomatis',
'데빌포스 흡수 (HP→에너지)':'Serap Kekuatan Iblis (HP→Energi)',
'스킬슬롯 5':'Slot skill 5',
'CT스킬 (유령걸음/얼음보주)':'Skill CT (Langkah Hantu/Bola Es)',
'스킬 (전투스킬 습득)':'Skill (Pertempuran)',
'대장간 (제작)':'Pandai besi (Craft)',
'클릭하여 계속':'Klik untuk lanjut',
'클릭하여 시작':'Klik untuk mulai',
'SPACE 길게 눌러 건너뛰기':'Tahan SPACE untuk lewati',
'패링·보호막':'Parry / Perisai',
'돌진 (적을 관통, 무적)':'Terjang (tembus musuh, kebal)',
'대왕치기 (광역 기절)':'Pukulan Raksasa (stun area)',
'가시덫 (슬로우+출혈)':'Jebakan duri (lambat+pendarahan)',
'회복의 영역 (리젠 장판)':'Domain suci (zona regen)',
'얼음보주 (무적+빙결)':'Bola es (kebal+beku)',
'석궁 자동발사':'Panah otomatis',
'선택 스킬 슬롯':'Slot skill',
'(펫이 자동 수거)':'(pet otomatis ambil)',
'물약은 설정한 HP% 이하 시 자동 사용':'Ramuan otomatis saat HP di bawah % yang diatur',
'💡 Shift로 작살 돌진! 적을 관통하며 무적':'💡 Shift terjang! Tembus musuh, kebal',
'💡 Q로 보호막 발동 — 기본 흡수율 70%, 패링 성공 시 HP/ST/MP/기동게이지 회복':'💡 Q untuk Perisai — serap 70%, parry pulihkan HP/ST/MP/Isi',
'💡 속성 약점을 찌르면 데미지 2배!':'💡 Serang kelemahan elemen — 2x damage!',
'💡 ESC로 설정 — 난이도, 자동물약 조절':'💡 ESC pengaturan — kesulitan, ramuan otomatis',
'💡 대왕치기로 기절 회복 + 포이즈를 깎아 그로기 유발!':'💡 Pukulan Raksasa: pulih stun + hancurkan poise untuk groggy!',
'💡 그로기 상태에서 기본 데미지 1.5배':'💡 Status groggy = 1.5x damage dasar',
'💡 탄막은 패링하면 되돌려 보낸다!':'💡 Parry peluru — memantul balik!',
'💡 Ctrl 얼음보주 — 무적! 재입력으로 즉시 폭파':'💡 Ctrl Bola es — kebal! Tekan lagi untuk pecahkan',
'💡 합체 스킬로 더 강한 공격을 만들어보세요':'💡 Gabungkan skill untuk serangan lebih kuat!',
'💡 엘리트 몬스터는 특수 능력을 가지고 있다':'💡 Monster elite punya kemampuan khusus',
'💡 보스의 패턴을 읽고 패링 타이밍을 잡아라':'💡 Baca pola bos, tangkap waktu parry',
'💡 인벤토리(TAB)에서 장비를 비교하고 장착':'💡 Inventaris(TAB) — bandingkan dan kenakan',
'💡 대장간에서 장비를 강화하고 분해하세요':'💡 Tingkatkan dan bongkar perlengkapan di pandai besi',
'💡 R키를 누르면 펫이 아이템을 자동으로 주워줍니다':'💡 Tekan R — pet otomatis ambil item',
'💡 물약은 설정한 HP% 이하에서 자동 사용':'💡 Ramuan otomatis saat HP di bawah % yang diatur',
'💡 집중 스킬(홀드)은 시전 중 기절 면역!':'💡 Skill fokus (tahan) kebal stun!',
'🎮 전체 조작 가이드':'🎮 Panduan Kontrol',
'무기 공격 (좌클릭)':'Serang (Klik Kiri)',
'B슬롯 스킬 (Space)':'Skill Slot B (Space)',
'우클릭 스킬 (RMB)':'Skill Klik Kanan (RMB)',
'패링 (Q)':'Parry (Q)',
'돌진/작살 (Shift)':'Dash/Tombak (Shift)',
'Ctrl 스킬':'Skill Ctrl',
'필살기 (Z)':'Ultimate (Z)',
'F 슬롯 스킬':'Skill Slot F',
'스킬 슬롯 1':'Slot 1',
'스킬 슬롯 2':'Slot 2',
'스킬 슬롯 3':'Slot 3',
'스킬 슬롯 4':'Slot 4',
'처형 (X)':'Eksekusi (X)',
'방향 + 마법 자동발동 (E)':'Arah + Sihir otomatis (E)',
'마법 (E)':'Sihir (E)',
'줍기 (R)':'Ambil (R)',
'스킬창':'Skill',
'이동 (WASD)':'Gerak (WASD)',
};

const _ID_PFX={'녹슨':'Berkarat','강철':'Baja','흑요석':'Obsidian','미스릴':'Mithril','심판의':'Penghakiman','천벌의':'Murka Ilahi','파멸의':'Kehancuran','불꽃':'Api','화염':'Neraka Api','염화':'Api Neraka','지옥불':'Kobaran Neraka','지옥화':'Kobaran Neraka','지옥':'Kobaran Neraka','멸화의':'Pemusnah','냉기':'Es','빙결':'Beku','빙하':'Glasial','서리의':'Embun Beku','서리':'Embun Beku','영겁빙':'Es Abadi','그림자':'Bayangan','암흑':'Kegelapan','심연':'Jurang','나락의':'Alam Bawah','나락':'Alam Bawah','무간의':'Kehampaan','전기':'Percik','낙뢰':'Guntur','암전':'Petir','뇌신의':'Dewa Badai','뇌신':'Dewa Badai','만뢰의':'Seribu Petir','축복':'Terberkati','성광':'Cahaya Suci','신성':'Sakral','천사의':'Malaikat','신벌의':'Hukuman Ilahi','낡은':'Usang','천':'Kain','가죽':'Kulit','강철사':'Rajut Baja','은':'Perak','은사':'Benang Perak','화염의':'Neraka Api','빙결의':'Beku','암흑의':'Kegelapan','암전의':'Petir'};
const _ID_BASE={'대검':'Pedang Besar','석궁':'Panah Silang','연사석궁':'Panah Tembak','마력석궁':'Panah Sihir','견갑':'Pelindung Bahu','대견갑':'Pelindung Bahu Besar','전투화':'Sepatu Tempur','갑옷':'Baju Besi','갑주':'Baju Besi','왕관':'Mahkota','장갑':'Sarung Tangan','건틀릿':'Sarung Besi','바지':'Celana','각반':'Pelindung Kaki','허리띠':'Ikat Pinggang','벨트':'Ikat Pinggang','부적':'Jimat','목걸이':'Kalung','반지':'Cincin','망토':'Jubah','악마팔찌':'Demon Bracelet','생명팔찌':'Life Bracelet','팔찌':'Gelang','귀걸이':'Anting',
'투구 착용':'Helm dipasang',
'투구 해제':'Helm dilepas',
'혼돈의 투구':'Helm Kekacauan',
'전지전능의 투구':'Helm Mahakuasa',
'방향키 연타':'Tekan panah berulang',
'까마귀와 고양이가 아이템을 주워준다. 수거 범위 안이면.':'Gagak dan kucing mengambil item. Jika dalam jangkauan.',
'Ctrl 얼음보주로 탈출! 없으면 방향키 연타!':'Ctrl — Orb Es untuk kabur! Tidak ada? Tekan panah!',
'💥 폭발 허수아비!':'💥 Orang-orangan Meledak!',
' 뎀 ':' KER ',
'투구':'Helm',
};