const _DE={
// --- Stage / Boss ---
'썩은 숲':'Fauliger Wald','숲의 감시자':'Waldwächter','독버섯 거인':'Giftpilz-Koloss','숲의 사냥꾼':'Waldjäger','숲의 기생수':'Parasitische Bestie',
'1장 — 썩은 숲':'Kap. 1 — Fauliger Wald','2장 — 벌레굴':'Kap. 2 — Wurmnest','3장 — 얼음굴':'Kap. 3 — Eishöhle',
'4장 — 고통의 화염지대':'Kap. 4 — Flammenöde der Qual','5장 — 지옥의 군단':'Kap. 5 — Höllenlegion','6장 — 사도의 마굴':'Kap. 6 — Schlund des Apostels','7장 — 지옥성':'Kap. 7 — Höllenfeste',
'탈출!':'Entkommen!','처치':'Getötet','경험치':'EP','최대콤보':'Max-Kombo',
// --- Tutorial (Crow) ---
'일어나. 여신이 널 여기 보낸 건 죽으라고가 아니야.':'Steh auf. Die Göttin hat dich nicht zum Sterben hergeschickt.',
'좋아, 감각이 있군. 계속 쳐!':'Gut, du hast Instinkt. Schlag weiter zu!',
'Shift를 눌러. 작살이다. 땅에 꽂아서 끌려가!':'Drück Shift. Das ist die Harpune. Ramm sie rein und lass dich ziehen!',
'작살로 끌려가는 중엔 무적이다. 위험할 때 쓰면 좋아.':'Während die Harpune dich zieht, bist du unverwundbar. Nutz es in der Not.',
'...아파? 당연하지. 여긴 지옥이야.':'...Schmerzt es? Natürlich. Das hier ist die Hölle.',
'Q를 눌러! 악의로 보호막을 만들 수 있다.':'Drück Q! Erschaffe einen Schild aus Bosheit.',
'보호막 없이 버틸 생각은 버려.':'Vergiss es, ohne Schild zu überleben.',
'우클릭이 패링이다. 적 공격이 닿기 직전에 눌러!':'Rechtsklick ist Parade. Drück kurz bevor der Feind trifft!',
'못 하겠으면 때려. 안 죽으면 그만이야.':'Kannst du nicht parieren? Dann schlag zu. Hauptsache, du stirbst nicht.',
'됐어! 감 잡았구나.':'So ist\'s recht! Du bekommst den Dreh raus.',
'하나 죽었군.':'Einer weniger.',
'유령쇠뇌야. 인사해.':'Das ist die Geisterarmbrust. Sag Hallo.',
'빨간 탄을 무서워하지 마. 악의가 강하다.':'Fürchte die roten Geschosse nicht. Bosheit ist mächtig.',
'패링으로 돌려주고, Q 보호막도 써! 악의를 잘 굴려!':'Pariere sie zurück, nutz auch den Q-Schild! Beherrsche deine Bosheit!',
'무지개빛은 패링 불가! 피해!':'Regenbogengeschosse sind nicht parierbar! Ausweichen!',
'피가 새고 있다. Shift. 빠져.':'Du blutest aus. Shift. Rückzug.',
'물약 있잖아! 숫자키!':'Du hast Tränke! Zifferntasten!',
'우클릭. 적 손목이 꺾일 때 쳐.':'Rechtsklick. Schlag zu, wenn das Handgelenk des Feindes einknickt.',
'빨간 탄은 악의 덩어리다. 쳐내서 이용해.':'Rote Geschosse sind geballte Bosheit. Schlag sie zurück und nutze sie.',
'무지개빛만 피하면 돼! 나머지는 다 패링!':'Weich nur dem Regenbogen aus! Alles andere: parieren!',
'Q 보호막도 패링이 가능해!':'Der Q-Schild kann auch parieren!',
'위험해! 쉬프트 사슬기동으로 피해!!':'Gefahr! Shift-Kettensturm zum Ausweichen!!',
'쉬프트! 사슬기동은 이동기야! 끌려가면서 무적이라고!':'Shift! Kettensturm ist ein Bewegungsskill! Unverwundbar beim Ziehen!',
'스킬포인트가 쌓였어! K 눌러서 스킬 배우자!':'Fähigkeitspunkte bereit! Drück K, um Fähigkeiten zu erlernen!',
'속성을 읽어. 약점을 찌르면 두 배로 썩는다.':'Lies die Elemente. Triff Schwächen für doppelten Schaden.',
'K를 눌러봐! 스킬을 배울 수 있어!':'Drück K! Du kannst Fähigkeiten erlernen!',
'C 눌러서 능력치 찍어! 패시브도 있어~':'Drück C für Attribute! Passive gibt\'s auch~',
'G를 눌러. 대장간에서 장비를 강화할 수 있다.':'Drück G. Verbessere Ausrüstung in der Schmiede.',
'F키도 스킬 슬롯이야! 스킬 많으면 L로 배정해봐~':'F-Taste ist auch ein Fähigkeits-Slot! Nutz L zum Zuweisen~',
'Z. 필살기다. 아껴 써라.':'Z. Das ist dein Ultimativ. Setze es weise ein.',
'L-CTRL로 유령걸음이나 얼음보주 쓸 수 있어!':'L-CTRL für Geisterschritt oder Eiskugel!',
'L을 눌러. 스킬 슬롯을 정리해야 한다.':'Drück L. Ordne deine Fähigkeits-Slots.',
'가방 터지겠다! V 눌러서 창고에 넣어둬!':'Der Beutel platzt! Drück V für das Lager!',
'ESC로 설정 열 수 있어! 난이도 바꾸기, 자동물약 조절~':'ESC für Einstellungen! Schwierigkeit, Auto-Tränke~',
// --- Tutorial (Cat) ---
'...아직 살아있네. 좌클릭으로 저것들 쳐봐.':'...Noch am Leben. Versuch die mit Linksklick zu schlagen.',
'...치는 건 할 줄 아네. 피하는 건?':'...Zuschlagen kannst du. Aber ausweichen?',
'흥, 작살 못 맞추면 헛수고야.':'Hmph, verfehlst du die Harpune, war\'s umsonst.',
'...운이 좋았을 뿐이야. 아마.':'...Nur Glück gehabt. Wahrscheinlich.',
'...고기 냄새. 싫진 않네.':'...Riecht nach Fleisch. Nicht übel.',
'...말은 못해.':'...Es kann nicht sprechen.',
'예쁘다고 만지면 죽어.':'Anfassen, weil\'s hübsch ist? Du stirbst.',
'작살 던져! 끌려가면 무적이야!':'Wirf die Harpune! Unverwundbar beim Ziehen!',
'...마시든 말든. 네 목숨이니까.':'...Trink oder lass es. Es ist dein Leben.',
'그게 패링이야! 타이밍이 전부야~':'Das ist eine Parade! Timing ist alles~',
'화염엔 빙결! 암전엔 암흑! 기억해!':'Feuer schlägt Eis! Blitz schlägt Finsternis! Merk dir das!',
'...얼어붙은 놈은 오래 안 간다.':'...Gefrorene halten nicht lange durch.',
'얼었어! 빙결 중 1.5배야!':'Gefroren! 1,5-facher Schaden bei Frost!',
'...힘을 골라라. 전부 가질 순 없다.':'...Wähle deine Macht. Du kannst nicht alles haben.',
'스탯을 올려. 살고 싶으면.':'Steigere deine Werte. Wenn du leben willst.',
'좋은 장비는 강화해야 진짜 힘을 발휘해!':'Gute Ausrüstung muss verbessert werden, um ihre wahre Kraft zu entfalten!',
'...슬롯을 채워. 빈 손은 죽음이다.':'...Füll deine Slots. Leere Hände bedeuten Tod.',
'Z 누르면 대박! 쿨타임 길어서 타이밍 봐야 해!':'Drück Z für verheerenden Schaden! Lange Abklingzeit, achte aufs Timing!',
'Ctrl. 위기에 쓸 카드가 하나 늘었군.':'Ctrl. Eine Karte mehr für den Notfall.',
'스킬이 많아졌네~ L로 어디에 뭘 넣을지 골라!':'So viele Fähigkeiten~ Nutz L zum Zuweisen!',
'...버리기 아까운 건 창고에.':'...Was zu schade zum Wegwerfen ist, ins Lager.',
'...살아남은 것만으로도 대단하군. 설정을 확인해.':'...Allein zu überleben ist beeindruckend. Prüfe die Einstellungen.',
// --- System Messages ---
'MP 부족!':'Nicht genug MP!','ST 부족!':'Nicht genug ST!','악의 부족!':'Nicht genug Bosheit!',
'충전 중...':'Lade auf...','캔슬':'Abbruch','아이템 선택 필요':'Gegenstand auswählen',
'악의 소진...':'Bosheit erschöpft...','비문 발견...':'Inschrift entdeckt...',
'HP물약!':'HP-Trank!','HP물약 +1':'HP-Trank +1','HP물약 +2':'HP-Trank +2',
'HP/MP/ST 회복!':'HP/MP/ST wiederhergestellt!','보물상자 개봉!':'Truhe geöffnet!',
'익사!':'Ertrinken!','피웅덩이!':'Blutlache!','독혈!':'Giftblut!','잡힘!':'Gepackt!',
'콤보 종료':'Kombo beendet',
// --- Status Effects ---
'빙결!':'Gefroren!','화상!':'Verbrennung!','독!':'Gift!','감전!':'Schock!',
'기절!':'Betäubt!','봉인됨!':'Versiegelt!','관통!':'Durchschlag!',
// --- Skill Names ---
'기검참':'Ki-Hieb','악의구':'Bosheitskugel','회전참':'Wirbelwind','기폭팔':'Detonation',
'칼등 처내기':'Klingenparade','만화방창':'Nadelsperre','멸살광선':'Vernichtungsstrahl',
'원소추적탄':'Elementarsucher','악의 보호자':'Bosheitswächter','악의 사냥':'Bosheitsjagd',
'폭풍소환':'Wirbelsturm','해골무덤':'Knochengruft','신성폭발':'Heilige Explosion',
'블랙':'Schwarzer Stern','용암소환':'Lavabeschwörung','처형':'Hinrichtung','악마화 부활':'Dämonische Auferstehung',
'붉은꽃':'Purpurblüte','얼음보주':'Eiskugel','뇌전걸음':'Geisterschritt',
'만화방창 II':'Nadelsperre II','마력연사':'Arkaner Hagel','마력광선':'Arkaner Laser','업화선':'Höllenfeuerstrahl',
'지옥진':'Inferno-Formation','폭독칼날':'Seuchenklinge','악의폭풍':'Bosheitssturm',
'악의기둥':'Finsternissäule','회복의 영역':'Heilige Domäne','구속의 영역':'Fesselnde Domäne',
'아이스스톰':'Eissturm','대왕치기':'Titanenschlag','대왕치기 2':'Titanenschlag II',
'기동불꽃':'Kettenflamme','기동파괴':'Kettenbrecher','기동칼날개':'Kettenklingenflügel',
'평화의보호':'Ägide des Friedens','참회':'Buße','칼등날개':'Schildflügel',
'폭산탄':'Splitterschuss','파쇄의 영역':'Zerschmetternde Domäne','침식의 영역':'Korrodierende Domäne',
'관통의 영역':'Durchdringende Domäne','부활의 영역':'Domäne der Auferstehung','가시덫':'Dornenfalle',
'푸른비':'Azurregen','버스트루프':'Ausbruchsschleife','유령 허수아비':'Phantomlockvogel','폭발 허수아비':'Sprenglockvogel',
'공성쇠뇌':'Belagerungsarmbrust','사슬기동:충돌':'Kettensturm: Aufprall',
'사슬기동:화염':'Kettensturm: Flamme','전격이동':'Blitzschritt',
// --- Skill Activation ---
'기동칼날개!':'Klingenflügel!','기동불꽃!':'Kettenflamme!','기동파괴!':'Kettenbrecher!',
'사슬이동:강화!':'Kettensturm!','사슬기동:화염!':'Kettenflamme!',
'작살!':'Harpune!','진입!':'Eintreten!','레인라이트닝!':'Blitzregen!',
'마력연사!':'Arkaner Hagel!','🔷 마력광선!':'🔷 Arkaner Laser!','광선 해제':'Laser aus','MP 부족 — 광선 해제':'MP erschöpft — Laser aus','집중...':'Fokus...','시전...':'Wirken...',
'만화방창!':'Nadelsperre!','바늘출!':'Nadelschuss!','칼날!':'Klinge!',
'착지!':'Landung!','체간삭감!':'Haltungsbruch!',
'기동전폭 준비!':'Kettenexplosion bereit!','기동불꽃 준비!':'Kettenflamme bereit!',
'기동파괴 준비!':'Kettenbrecher bereit!',
'유령불꽃 ON':'Geisterflamme AN','유령불꽃 OFF':'Geisterflamme AUS',
'기동칼날개 AUTO ON':'Klingenflügel AUTO AN','기동칼날개 AUTO OFF':'Klingenflügel AUTO AUS',
'자동 버스트!':'Auto-Ausbruch!','연사 해제':'Schnellfeuer aus',
'당기기 모드':'Ziehmodus','밀어내기 모드':'Stoßmodus',
// --- Skill Slot Tooltips ---
'날개치기':'Flügelschlag','처내기':'Parade',
'Shift: 작살 발사 → 끌려감':'Shift: Harpunenwurf → Ziehen',
'Shift: 화염길+화상':'Shift: Feuerpfad+Verbrennung',
'CT: 전류변신+뇌전걸음 (쿨4초)':'CT: Blitzform+Geisterschritt (AZ 4s)',
'CT: 방어구체+빙결 (재입력: 파쇄)':'CT: Eissphäre+Frost (erneut: Zerschmettern)',
// --- HUD ---
'근접':'Nahkampf','견갑':'Schild','작살':'Harpune','마법':'Magie','보막':'Schild','유령':'Geist',
'스킬':'Fähigk.','대장':'Schmiede','인벤':'Inv.',
// --- Menu ---
'인벤토리':'Inventar','복수의 대장간':'Schmiede der Vergeltung','패시브 스킬':'Passive Fähigkeiten',
'전투 스킬':'Kampffähigkeiten','캐릭터 선택':'Charakterwahl',
// --- Elements ---
'물리':'Physisch','화염':'Feuer','빙결':'Eis','암흑':'Finsternis','암전':'Blitz','신성':'Heilig','대지':'Erde',
// --- Passives ---
'힘':'Stärke','민첩':'Geschick','지능':'Intelligenz','행운':'Glück',
'맹공':'Ansturm','철벽':'Bollwerk','돌파':'Durchbruch','반격':'Vergeltung',
'마력폭주':'Arkaner Rausch','정밀사격':'Präzisionsschuss','수호':'Beschützung','수호신':'Schutzgeist',
'회복력':'Regeneration','급소':'Vitaltreffer','약탈':'Plünderung','관통':'Durchschlag',
'마력회복':'Manaregeneration','쇠뇌력':'Armbrustmeisterschaft','광전사':'Berserker','추적자':'Verfolger',
'물리관통':'Phys. Durchdr.','마법관통':'Mag. Durchdr.',
// --- Weapons (Tier 0) ---
'녹슨 대검':'Rostiges Großschwert','강철 대검':'Stahl-Großschwert','흑요석 대검':'Obsidian-Großschwert',
'낡은 석궁':'Abgenutzte Armbrust','강철 석궁':'Stahl-Armbrust','흑요석 석궁':'Obsidian-Armbrust',
'대검':'Großschwert','석궁':'Armbrust','연사석궁':'Schnellfeuer-Armbrust','마력석궁':'Arkane Armbrust',
// --- Misc ---
'악의 추출':'Bosheitsextraktion','악의':'Bosheit','필살기':'Ultimativ','필살기 해제':'Ultimativ entfernt',
'이전':'Übertragen','강화':'Verstärken','개봉!':'Geöffnet!',
'여신의 가호':'Segen der Göttin',
'과부하!':'Überlast!',
// --- Affix Names ---
'맹독의':'Giftig','불꽃의':'Flammend','냉기의':'Frostig','번개의':'Voltaisch','암흑의':'Verflucht',
'관통의':'Durchbohrend','광폭의':'Rasend','파쇄의':'Zerschmetternd','연쇄의':'Kettenreaktiv',
'학살의':'Mordend','폭발의':'Explosiv','집중의':'Fokussiert','쾌속의':'Flink','패리의':'Parierend',
'추적자의':'Des Verfolgers','작살의':'Harpunen-','궁극의':'Höchst','집중력의':'Achtsam',
'강인의':'Standhaft','수호의':'Schützend','활력의':'Vital','신속의':'Beschleunigt',
'화염수호':'Feuerschutz','빙결수호':'Eisschutz','암전수호':'Blitzschutz','암흑수호':'Finsternisschutz','독수호':'Giftschutz','전원소수호':'Allschutz',
'강철의':'Gepanzert','반사의':'Reflektierend','가시의':'Dornig','흡수의':'Absorbierend','인내의':'Ausdauernd',
'위기의':'Verzweifelt','피격반격의':'Vergeltend',
'패링폭발의':'Paradeexplosion','스태거폭발의':'Taumelexplosion','원소전환의':'Konvertierend','정화의':'Läuternd',
'불굴의':'Unbeugsam','부활의':'Wiederbelebend',
'약탈의':'Plündernd','경험의':'Erfahren','골드의':'Golden','포션강화의':'Trankverstärkend','사슬의':'Verkettet',
'진혼의':'Weihend','윤회의':'Zyklisch',
'생명력의':'Lebenskräftig','재생의':'Regenerierend','치유의':'Heilend',
'마력의':'Arkan','절약의':'Sparsam','영혼의':'Seelengebunden',
'예리한':'Scharf','맹렬한':'Brutal','파멸의':'Verheerend',
// --- Settings UI ---
'게임 설정':'Spieleinstellungen','화면 흔들림':'Bildschirmwackeln','파티클 양':'Partikelmenge',
'효과음 볼륨':'Effektlautstärke','음악 볼륨':'Musiklautstärke','난이도':'Schwierigkeit',
'자동 물약':'Auto-Trank','최소 줍기 등급':'Min. Aufhebe-Stufe','최소 줍기 티어':'Min. Aufhebe-Tier',
'FPS 제한':'FPS-Limit','해상도 스케일':'Auflösungsskalierung','펫 자동수거':'Begleiter-Autosammeln',
'화면 설정':'Anzeigeeinstellungen','화면 모드':'Anzeigemodus','보스 AI 디버그':'Boss-KI-Debug',
'유령불꽃 크기':'Geisterflammen-Größe','화면 명암':'Helligkeit','유령 글로우':'Geisterleuchten',
'기동:칼날개 AUTO':'Klingenflügel AUTO',
'일반':'Normal','어려움':'Schwer','지옥':'Hölle','이상':'oder höher','사용 안 함':'Deaktiviert',
'창 모드':'Fenstermodus','보더리스':'Randlos','전체화면':'Vollbild',
'설정':'Einstellungen','조작 키 설정 (클릭하여 변경)':'Tastenbelegung (Klick zum Ändern)',
// --- Key Guide ---
'좌클릭 무기 공격':'LMT Waffenangriff','우클릭 탭 칼등 처내기':'RMT Klingenparade',
'우클릭 홀드 연속 처내기':'RMT gehalten: Dauerparade','SHIFT 작살 발사':'SHIFT Harpunenwurf',
'이동':'Bewegen','아이템 줍기':'Gegenstand aufheben','능력치 (스탯/패시브)':'Attribute (Stats/Passive)',
// --- Forge ---
'복수의 대장간':'Schmiede der Vergeltung','분해':'Zerlegen','제작':'Herstellen',
// --- Death Screen ---
'사망':'Tod','부활':'Wiederbelebung','로비로':'Zur Lobby',
// --- Inventory/Storage ---
'가방에 공간이 없습니다!':'Kein Platz im Beutel!','가방이 가득 찼습니다!':'Beutel ist voll!',
'창고가 가득 찼습니다!':'Lager ist voll!','퀵슬롯이 가득 찼습니다!':'Schnellslot ist voll!',
'결정 주머니가 가득 찼습니다!':'Kristallbeutel ist voll!','결정 주머니 가득!':'Kristallbeutel voll!',
'악의가 부족합니다!':'Nicht genug Bosheit!','가방이 비어있습니다':'Beutel ist leer',
'창고가 비어있습니다':'Lager ist leer','비어있음':'Leer','어픽스 없음':'Kein Affix',
'장착!':'Angelegt!','해제':'Abgelegt','보관':'Einlagern','꺼내기':'Herausnehmen',
'현재 장착':'Derzeit angelegt','없음 — 제작하세요!':'Keins — Stelle eins her!',
'리셋할 포인트가 없습니다':'Keine Punkte zum Zurücksetzen',
'키 설정 초기화 완료':'Tastenbelegung zurückgesetzt',
// --- Forge/Craft ---
'제작 확률':'Herstellungschance','제작 비용':'Herstellungskosten','보유 악의':'Bosheit vorhanden',
// --- Canvas UI ---
'보스방':'Bossraum','안식처':'Zuflucht','회복':'Erholung','점화':'Entzünden',
'비석':'Stele','읽기':'Lesen','파괴':'Zerstören','제단':'Altar','기원':'Beten',
'잔해':'Trümmer','열기':'Öffnen','문지기':'Torwächter',
'부활 판정 중...':'Auferstehungsurteil...','기폭 준비!':'Detonation bereit!',
'탈출':'Flucht','연타':'Hämmern',
'추적암전':'Verfolgungsblitz','만화광선':'Leuchtstrahl','최종 마법':'Endgültige Magie',
'감시중':'Überwacht','대기':'Bereitschaft','작동중':'Aktiv','설치 가능':'Aufstellbar',
'균열 임박!':'Riss steht bevor!','흡수 중...':'Absorbiere...',
'흡수 완료 — 재입력으로 회수':'Fertig — erneut drücken zum Einsammeln',
'화상':'Verbrennung','당기기':'Ziehen','밀어내기':'Stoßen',
'단계':'Stufe','단':'Stufe',
// --- Skill Panel ---
'습득!':'Erlernt!','리셋!':'Zurückgesetzt!','세팅!':'Gesetzt!','회수':'Einziehen',
'합체 해제':'Fusion lösen','리셋':'Zurücksetzen','환불':'Rückerstattung',
'파트너 클릭!':'Partner klicken!','SP부족!':'SP nötig!',
'같은 보석 스킬 습득 시 합체 가능':'Fusion möglich bei gleichem Edelstein-Skill',
'펼쳐서 초기화':'Aufklappen zum Zurücksetzen','슬롯:':'Slot:',
// --- Stats ---
'남은 SP':'Verbl. SP','맞아서 사망':'Durch Treffer gestorben','레벨':'Stufe','최대HP':'Max HP',
// --- Enemy Names ---
'방랑 기사':'Wandernder Ritter','보물 악마':'Schatzdämon','거울의 사도':'Apostel des Spiegels',
'상인 악마':'Händlerdämon','사슬의 죄수':'Kettengefangener','시간의 사도':'Apostel der Zeit',
'탐욕의 사도':'Apostel der Gier','저주받은 쌍둥이':'Verfluchte Zwillinge','차원 균열체':'Dimensionsriss',
'죽음 그 자체':'Der Tod selbst',
// --- Crystals ---
'HP결정':'HP-Kristall','ST결정':'ST-Kristall','MP결정':'MP-Kristall',
'ATK결정':'ATK-Kristall','DEF결정':'DEF-Kristall','속도결정':'Tempo-Kristall',
'크리결정':'Krit-Kristall','치명결정':'KritSchd-Kristall','화염결정':'Feuer-Kristall',
'냉기결정':'Eis-Kristall','암흑결정':'Finsternis-Kristall','번개결정':'Blitz-Kristall',
'신성결정':'Heilig-Kristall','생명결정':'Lebens-Kristall','기력결정':'Ausdauer-Kristall',
'마력결정':'Mana-Kristall','행운결정':'Glücks-Kristall',
'조각':'Fragment','파편':'Splitter','순수결정':'Reiner Kristall','완전결정':'Perfekter Kristall',
'결정 주머니':'Kristallbeutel','결정이 없습니다':'Keine Kristalle','가루':'Staub',
'전체':'Alle','스탯':'Stat','원소':'Elem','유틸':'Util',
'현재':'Aktuell','최대 강화 달성 (+20)':'Max verstärkt (+20)','강화 시':'Nach Verstärkung',
'합성':'Synthetisieren',
'같은 종류·같은 성급 결정 3개 → 1성급 상승 (강화 리셋)':'3 Kristalle gleicher Art & Stufe → 1 Stufe höher (Verstärkung zurückgesetzt)',
'합성 가능한 결정이 없습니다 (같은 종류·성급 3개 필요)':'Keine synthetisierbaren Kristalle (3 gleicher Art & Stufe nötig)',
'결정 분해 → 결정 가루':'Kristall zerlegen → Kristallstaub',
'분해할 결정이 없습니다':'Keine Kristalle zum Zerlegen',
'결정 제작 (가루 → 결정)':'Kristall herstellen (Staub → Kristall)',
'탈착':'Entfernen','빈 슬롯':'Leerer Slot',
'결정 선택 후 클릭':'Kristall wählen, dann klicken','클릭하여 선택결정 장착':'Klicken, um gewählten Kristall einzusetzen',
'획득!':'Erhalten!','제작!':'Hergestellt!','합성!':'Synthetisiert!','최상위 일괄합성':'Massen-Synthese','일괄합성 완료':'Massen-Synthese abgeschlossen',
// --- Stage Names ---
'벌레굴':'Wurmnest','얼음굴':'Eishöhle','고통의 화염지대':'Flammenöde der Qual',
'지옥의 군단':'Höllenlegion','사도의 마굴':'Schlund des Apostels','지옥성':'Höllenfeste',
// --- Misc ---
'엑소듀서 전사':'Exoduser-Krieger','포이즈':'Haltung',
'신성폭발':'Heilige Explosion','뇌전걸음':'Geisterschritt',
'지옥창고':'Höllenlager','선택분해':'Selektives Zerlegen','쓰레기':'Schrott',
'복구 불가!':'Nicht wiederherstellbar!','중요잠금':'Wichtig-gesperrt',
// --- Phase 9 additions ---
'자동 장착!':'Auto-angelegt!','분해! 가루 +':'Zerlegt! Staub +',
'추적암전':'Verfolgungsblitz','암전':'Blitz',
'평화보호':'Ägide','지진폭풍':'Erdbebensturm','회전기폭':'Wirbel-Det.',
'공격':'Angriff','보호막':'Schild','합체 스킬로 통합됨':'In Fusionsfähigkeit integriert','얼음보주 안에선 사용 불가!':'Nicht nutzbar in der Eiskugel!',
'Shift+키로 폭파':'Shift+Taste zum Sprengen','취소':'Abbruch','충전 중...':'Lade auf...',
'쿨다운 중...':'Abklingzeit...','시전 중...':'Wirke...','악의 부족!':'Nicht genug Bosheit!',
'악의 부족! (12)':'Nicht genug Bosheit! (12)','악의 부족! (15)':'Nicht genug Bosheit! (15)',
'악의 부족! (20)':'Nicht genug Bosheit! (20)','악의 부족! (10)':'Nicht genug Bosheit! (10)',
'ST 부족!':'Nicht genug ST!','HP 부족!':'Nicht genug HP!',
'필살기 슬롯 클릭하여 배정!':'Ultimativ-Slot anklicken zum Zuweisen!',
'필살기 스킬을 습득하세요':'Erlerne eine Ultimativ-Fähigkeit',
'우클릭(칼등치기)에 합체됨':'In RMT (Klingenparade) integriert',
'T(석궁자동)에 세팅하세요':'Auf T (Auto-Armbrust) setzen',
'공성쇠뇌 철거 → 이동식':'Belagerungsarmbrust abgebaut → tragbar',
'ST 부족! (100)':'Nicht genug ST! (100)',
'HP 99% 이상!':'HP 99%+!','그로기 보스 없음!':'Kein benommener Boss!',
'이미 폭풍 지역!':'Bereits in Sturmzone!','이미 빙풍 지역!':'Bereits in Eissturmzone!',
'💎 푸른비 해금!':'💎 Azurregen freigeschaltet!','💫 버스트루프 해금!':'💫 Ausbruchsschleife freigeschaltet!',
'👻 유령 허수아비 해금!':'👻 Phantomlockvogel freigeschaltet!',
'쿨 ':'AZ ','과부하 ':'Überlast ',
'🕊️💎 블루콩!':'🕊️💎 Blaue Bohne!','🛡️💎 빨콩→블루콩!':'🛡️💎 Rot→Blaue Bohne!',
'🛡️💎 무지개→블루콩!':'🛡️💎 Regenbogen→Blaue Bohne!',
'레어':'Selten','슬롯':'Slot',
'성공률':'Erfolgsrate','AI 자동 강화':'KI-Auto-Verstärkung','최대 강화 달성!':'Max. Verstärkung erreicht!',
'최대 강화':'Max verstärkt','회복량':'Heilungsmenge','현재 장착':'Derzeit angelegt',
'없음 — 제작하세요!':'Keins — Stelle eins her!','제작 확률':'Herstellungschance',
'분해할 아이템이 없습니다.':'Keine Gegenstände zum Zerlegen.','🔨 제작':'🔨 Herstellen',
'체간':'Haltung','아이템에 마우스를 올리거나 좌클릭으로 선택하세요':'Über einen Gegenstand fahren oder Linksklick zum Auswählen',
// --- Phase 10: death/levelup/intro screen ---
'중독':'Gift','지뢰':'Mine','함정':'Falle','산호가시':'Korallenspitze',
'투사체':'Projektil','도트':'DoT','레어몹':'Seltener Mob',
'구역':'Zone','가시!':'Spitze!',
// --- Hell circle / palette names ---
'림보':'Limbus','색욕':'Wollust','탐식':'Völlerei','탐욕':'Gier','분노':'Zorn','이단':'Häresie','폭력':'Gewalt',
'분노!':'Zorn!','탐욕!':'Gier!','💀 분노 폭발!':'💀 Zornexplosion!','심연의 분노!':'Abgrundszorn!','쌍둥이의 분노!':'Zorn der Zwillinge!',
// --- HUD / misc ---
'소환굴':'Beschwörungsgrube',
'처치!':'Besiegt!','왕관 착용':'Krone aufsetzen','왕관 해제':'Krone abnehmen',
'맨손':'Bloße Hände','없음':'Keine','갑옷':'Rüstung','부츠':'Stiefel',
// --- Elite / Mod / Aura ---
'매직':'Magisch','챔피언':'Champion',
'빙결':'Gefroren','초속':'Eile','강타':'Schmettern','재생':'Regeneration','맹독':'Gift','소환':'Beschwören',
'기생':'Parasit','분열':'Teilung','용암자취':'Lavaspur','사망폭발':'Todesexplosion',
'화염사슬':'Feuerkette','광전':'Raserei','텔레포트':'Teleport','보호막':'Barriere',
'소용돌이':'Wirbel','환영':'Phantom','전격반사':'Schockreflexion','감전':'Elektrisieren',
'낙뢰':'Donner','연쇄전격':'Kettenblitz','동료불사':'Verbündeten-Unsterblichkeit',
'영혼포식':'Seelenverschlingen','시간왜곡':'Zeitverzerrung','혼돈변이':'Chaosmutation',
'복수자':'Rächer','마법보초':'Magischer Wächter','환영술사':'Illusionist',
'함성':'Schlachtruf','치유':'Heilung','신속':'Schnelligkeit','수호':'Wächter',
// --- Character ---
'다크 판타지 전사. 거대검+검은 갑옷':'Dunkler Fantasy-Krieger. Großschwert + Schwarze Rüstung',
// --- Phase 11: missing addTxt/showPH/notify translations ---
'⚡ 사슬이동:강화!':'⚡ Kette:Verstärkt!',
'⚡ 사슬기동:화염!':'⚡ Kettensturm: Flamme!',
'달성!':'Erreicht!',
'ST':'ST','부족!':'Unzureichend!',
'타':'Treffer',
'🌀 당기기 모드':'🌀 Ziehmodus',
'💥 밀어내기 모드':'💥 Stoßmodus',
'🕊️빨콩 흡수':'🕊️Rote Bohne absorbiert',
'🕊️흡수':'🕊️Absorbiert',
'💎유도 폭발!':'💎Lenkexplosion!',
'💥반사 폭발!':'💥Reflexionsexplosion!',
'⚡⚡ 참회 귀환!':'⚡⚡ Buße-Rückkehr!',
'⚡ 참회!':'⚡ Buße!',
'파도!':'Welle!',
'암전!':'Blitz!',
'암흑!':'Finsternis!',
'암흑창!':'Finsternislanze!',
'빛창!':'Lichtlanze!',
'체 소환!':'beschworen!',
'개 설치!':'platziert!',
'💥 보스 그로기!':'💥 Boss Benommen!',
'💥 그로기!':'💥 Benommen!',
'보상':'Bonus',
'⚡ 암전나선!':'⚡ Blitzhelix!',
'🌋 지진폭풍!':'🌋 Erdbebensturm!',
'SP슬롯':'SP-Slot',
'F슬롯':'F-Slot',
'⚔🩸 독혈해방!':'⚔🩸 Seuchenbefreiung!',
'⚔ 칼날 해방!':'⚔ Klingenbefreiung!',
'🔨🌋 지옥강타!':'🔨🌋 Inferno-Hieb!',
'🔨 대왕치기!':'🔨 Titanenschlag!',
'✟ 신성한 결계!':'✟ Heilige Barriere!',
'🛡 회복의 영역!':'🛡 Heilige Domäne!',
'기폭팔!':'Detonation!','강제기폭!':'Erzwungene Detonation!','자동기폭!':'Auto-Detonation!',
'회전기폭!':'Wirbel-Detonation!','해제기폭!':'Auslöse-Detonation!','지진기폭!':'Erdbeben-Detonation!',
'혼돈의 왕관':'Krone des Chaos',
'전지전능의 왕관':'Krone der Allmacht',
'악마의 팔찌':'Dämonenarmreif',
'생명의 팔찌':'Armreif des Lebens',
// --- wave direction names (full addTxt strings) ---
'🌊 위→아래 파도!':'🌊 Oben→Unten Welle!','🌊 오른→왼 파도!':'🌊 Rechts→Links Welle!',
'🌊 아래→위 파도!':'🌊 Unten→Oben Welle!','🌊 왼→오른 파도!':'🌊 Links→Rechts Welle!',
// --- Phase 12: remaining addTxt/UI translations ---
// --- rare mob / special ---
'무적!':'Unverwundbar!','🪞 반격!':'🪞 Konter!','💢 반격!':'💢 Konter!',
'흡수!':'Absorbiert!','반격 발사!':'Konterschuss!',
'저주! 드랍률 -50%':'Fluch! Droprate -50%','도망!':'Flucht!',
'위상!':'Phase!','방어!':'Verteidigung!',
'회수 HP+':'Einzug HP+','이동식 복귀':'Tragbar zurück','캔슬':'Abbruch',
'약점!':'Schwäche!','저항!':'Resistenz!','관통!':'Durchschlag!',
'콤보 종료: ':'Kombo beendet: ','익사!':'Ertrinken!',
'피웅덩이!':'Blutlache!','독혈!':'Giftblut!','비문 발견...':'Inschrift entdeckt...',
'보물상자 개봉!':'Truhe geöffnet!','악의 +':'Bosheit +','잡힘!':'Gepackt!',
'저주 ':'Fluch ','불발...':'Fehlschuss...',
'작살 약점!':'Harpunen-Schwäche!',
'전염 x':'Seuche x','흡수 완료!':'Absorption abgeschlossen!',
'부활 성공!':'Wiederbelebung gelungen!','부활 실패...':'Wiederbelebung fehlgeschlagen...',
'산호가시':'Korallenspitze','차원 이동!':'Dimensionssprung!','독!':'Gift!',
'탈출!':'Entkommen!','기절 해제':'Betäubung aufgehoben',
'아이템 선택 필요':'Gegenstand auswählen','악의 부족':'Nicht genug Bosheit','악의 소진...':'Bosheit erschöpft...',
'스킬 미습득':'Keine Fähigkeiten erlernt','펼치기':'Aufklappen','접기':'Einklappen',
'조건 미달!':' nicht erfüllt!','해제!':' Gelöst!',
'자동 ON':' Auto AN','자동 OFF':' Auto AUS','스킬 해제':' Fähigkeit entfernt',
'닫기':'Schließen','장착 중':'Angelegt','보관 아이템':'Lager-Gegenstand',
// --- Phase 13: massive batch — skill activation ---
'클릭으로 선택 · ESC로 닫기':'Klick zum Wählen · ESC zum Schließen',
'선택됨':'Ausgewählt',
'악의 부족! (30)':'Nicht genug Bosheit! (30)',
'MP 부족! (40)':'Nicht genug MP! (40)','MP 부족! (100)':'Nicht genug MP! (100)','MP 부족! (10)':'Nicht genug MP! (10)',
'MP 부족! (':'Nicht genug MP! (',
'✟ 시전...':'✟ Wirke...','🌋 시전...':'🌋 Wirke...','⛧ 시전...':'⛧ Wirke...',
'❄ 진입!':'❄ Eintreten!',
'🔱 작살!':'🔱 Harpune!',
'레벨 부족! (요구: Lv.':'Stufe zu niedrig! (Ben.: Lv.',
' 장착!':' Angelegt!',
' 해제':' Abgelegt',
'👿 악의 추출: +':'👿 Bosheitsextraktion: +',
'F 슬롯 해제':'F-Slot entfernt',
'💫 집중...':'💫 Fokus...',
'⚡ 마력연사!':'⚡ Arkaner Hagel!',
'❄빙결!':'❄Gefroren!','🟢독!':'🟢Gift!','⚡감전!':'⚡Schock!','🔥화상!':'🔥Verbrennung!',
'✦ 여신의 가호 — SP+5 AP+3':'✦ Segen der Göttin — SP+5 AP+3',
'⚔ 기동칼날개!':'⚔ Klingenflügel!',
'🔥 화염관통!':'🔥 Feuerdurchschlag!',
'🔱 관통!':'🔱 Durchschlag!',
'⚔ 칼날!':'⚔ Klinge!',
'💥 착지!':'💥 Landung!',
'💫 기절!':'💫 Betäubt!',
'⚡ 체간삭감!':'⚡ Haltungsbruch!',
'⚡ 기동파괴! ':'⚡ Kettenbrecher! ',
'🔥 기동불꽃!':'🔥 Kettenflamme!',
'🔥 기동불꽃! ':'🔥 Kettenflamme! ',
'단계 ×':' x',
'⚡ 기동전폭! x':'⚡ Kettenexplosion! x',
'🔥🔥 3중폭!':'🔥🔥 3-fach!','🔥🔥🔥 6중폭!':'🔥🔥🔥 6-fach!','🔥🔥🔥🔥 9중폭!':'🔥🔥🔥🔥 9-fach!','💥 불꽃폭발! ':'💥 Flammenexplosion! ',
'🔥 기동불꽃 준비!':'🔥 Kettenflamme bereit!',
'🔨 기동파괴 준비!':'🔨 Kettenbrecher bereit!',
'⚡ 기동전폭 준비!':'⚡ Kettenexplosion bereit!',
'중독':'Gift',
'⚡ 과부하! 5초':'⚡ Überlast! 5s',
'💫 자동 버스트!':'💫 Auto-Ausbruch!',
'🔨 칼등날개!':'🔨 Schildflügel!',
'💥폭발!':'💥Explosion!',
'🛡️💎 유도반사!':'🛡️💎 Lenk-Reflexion!',
'⚡💎 블루콩!':'⚡💎 Blaue Bohne!',
'💎 블루콩!':'💎 Blaue Bohne!',
'⚡반사!':'⚡Reflexion!',
'💎 푸른비 OFF':'💎 Azurregen AUS',
'💎 푸른비 ON!':'💎 Azurregen AN!',
'🔥 지옥진!':'🔥 Inferno-Formation!',
'🔥 업화선!':'🔥 Höllenfeuerstrahl!',
'✦ 평화 충격파! ':'✦ Friedensschockwelle! ',
'⚡ 전류 방출!':'⚡ Stromentladung!',
'⚡⚡ 레인라이트닝!':'⚡⚡ Blitzregen!',
'💫 광역!':'💫 Flächenangriff!',
'🔥 불장판!':'🔥 Feuerzone!',
'💫 피니셔!':'💫 Finisher!',
'☠ 지옥에서 귀환!':'☠ Aus der Hölle zurückgekehrt!',
'☠ 완전 사망!':'☠ Endgültiger Tod!',
'⚔ 처형! ':'⚔ Hinrichtung! ',
'💥 지뢰!':'💥 Mine!',
'⚠ 함정!':'⚠ Falle!',
'❌ 우클릭으로! -':'❌ Rechtsklick! -',
'❌ Q키로! -':'❌ Q-Taste! -',
'💥무지개 폭발! ':'💥Regenbogenexplosion! ',
'🛡️💎 블루콩!':'🛡️💎 Blaue Bohne!',
'⬜화이트볼!':'⬜Weißkugel!',
'✨💎 블루콩!':'✨💎 Blaue Bohne!',
'💜다크볼!':'💜Dunkelkugel!',
'❄빙판!':'❄Eisfläche!',
'🌨빙결!':'🌨Gefroren!',
'🕸둔화!':'🕸Verlangsamung!',
'⚠트랩!':'⚠Falle!',
'💀 역병 처형!':'💀 Seuchen-Hinrichtung!',
'💥 역병 Finale!':'💥 Seuchen-Finale!',
'⚔ 균열 악마!':'⚔ Rissdämon!',
'자동회수 HP+':'Auto-Einzug HP+',
'MP 부족 — 연사 해제':'MP niedrig — Schnellfeuer aus',
'MP 부족 — 푸른비 OFF':'MP niedrig — Azurregen AUS',
'🛡️반사!':'🛡️Reflexion!',
'⚡🦴 참회 귀환!':'⚡🦴 Buße-Rückkehr!',
'🦴⚡해골번개!':'🦴⚡Knochenblitz!',
'⚡악의폭풍!':'⚡Bosheitssturm!',
'❄아이스스톰!':'❄Eissturm!',
'⚡ 암전폭발!':'⚡ Blitzexplosion!',
'⚡ 레인라이트닝! x':'⚡ Blitzregen! x',
'❄ 탈출!':'❄ Flucht!',
'⚡쉴드!':'⚡Schild!',
'❄🌪️ 얼음보주!':'❄🌪️ Eiskugel!',
'🌪️ 전개!':'🌪️ Entfalten!',
'❄ 빙결흡인!':'❄ Frostwirbel!',
'❄☄ 빙결폭발!':'❄☄ Frostexplosion!',
'☄️ 흡인!':'☄️ Wirbel!',
'☄️ 대폭발!':'☄️ Mega-Explosion!',
'❄ 얼음보주!':'❄ Eiskugel!',
'❄ 파쇄!':'❄ Zerschmettern!',
'☄️💥 대폭발!':'☄️💥 Mega-Explosion!',
'반사!':'Reflexion!',
// --- Phase 13: boss moves ---
'💀 도넛!':'💀 Donut!','💀 전멸!':'💀 Vernichtung!',
'🌊 파도!':'🌊 Welle!','속박!':'Fesselung!','반격!':'Konter!',
'분신!':'Doppelgänger!','분신 파괴!':'Doppelgänger zerstört!','무기 해방!':'Waffenbefreiung!',
'❄프리즌!':'❄Gefängnis!','⚡ 증표 ':'⚡ Zeichen ',
'흔들!':'Erschütterung!','⚠ 광역 발사!':'⚠ Flächenfeuer!',
'🔥 확산!':'🔥 Ausbreitung!','⚠ 돌진!':'⚠ Sturmangriff!',
'🦅 도약!':'🦅 Sprung!','⚡ 레이저!':'⚡ Laser!',
'🌊 충격파!':'🌊 Schockwelle!','👹 소환!':'👹 Beschwörung!',
'☄ 유성우!':'☄ Meteorregen!','🖐 잡기!':'🖐 Griff!',
'🌀 회전참!':'🌀 Wirbelwind!','💣 지뢰!':'💣 Mine!',
'🌀 흡인!':'🌀 Vakuum!','🔴 빨간콩 폭풍!':'🔴 Rote-Bohnen-Sturm!',
'🔴🔴 콩 비!':'🔴🔴 Bohnenregen!',
'🌊 부채꼴 충격파!':'🌊 Fächerschockwelle!',
'✴ 멸광 레이저!':'✴ Vernichtungslaser!',
'🔴 추적 장판!':'🔴 Verfolgungszone!',
'💥 속성탄!':'💥 Elementargeschoss!',
'⚔ 검기!':'⚔ Schwert-Ki!','⚔ 재단참!':'⚔ Erntehieb!',
'🌀 나선탄!':'🌀 Spiralgeschoss!','⚠ 찌르기!':'⚠ Stoß!',
'🔥🔥 지옥기둥!':'🔥🔥 Höllensäule!',
'⚔ 환영검!':'⚔ Phantomklinge!',
'💢 반격자세!':'💢 Konterhaltung!',
'⚔ 연격!':'⚔ Kombo!','🌑 암흑!':'🌑 Finsternis!',
'👥 분신!':'👥 Doppelgänger!','🌋 균열!':'🌋 Riss!',
'🌊 파동!':'🌊 Woge!','💣 추적지뢰!':'💣 Verfolgungsmine!',
'⏪ 되감기!':'⏪ Zurückspulen!','🌀 중력장!':'🌀 Gravitationsfeld!',
'🔨 벽밀기!':'🔨 Wandstoß!','☠ 독안개!':'☠ Giftnebel!',
'⛓ 감옥!':'⛓ Kerker!','⚡ 연쇄번개!':'⚡ Kettenblitz!',
'🔮 궤도탄!':'🔮 Orbitalgeschoss!','🛡 방패돌진!':'🛡 Schildsturm!',
'🪞 반격자세!':'🪞 Konterhaltung!','⚓ 속박!':'⚓ Fesselung!',
'👤 분신!':'👤 Doppelgänger!','🖐 탈취!':'🖐 Diebstahl!',
'🔥🔥 용암 지대!':'🔥🔥 Lavazone!',
'🌧🌧 화염 폭격!':'🌧🌧 Feuerbombardement!',
'⚡⚡ 전격 장막!':'⚡⚡ Blitzschleier!',
'💀 내 곁으로!':'💀 Komm zu mir!',
'⭕ 안전!':'⭕ Sicher!',
'💀💀 전멸 폭발!':'💀💀 Vernichtungsexplosion!',
'⚡ 쐐기 소멸!':'⚡ Keil-Auslöschung!',
'🌊충격파!':'🌊Schockwelle!',
'👿악의+100':'👿Bosheit+100',
'💥패링폭발!':'💥Paradeexplosion!',
'균열 충돌! ':'Riss-Kollision! ',
'벽 충돌! ':'Wand-Kollision! ',
'소환!':'Beschwörung!','환영!':'Phantom!',
'⚡낙뢰!':'⚡Donner!','⚡빔!':'⚡Strahl!',
'환영술!':'Illusion!','💀소환!':'💀Beschwörung!',
'🔮주술!':'🔮Fluch!','🩸산란!':'🩸Brut!',
'💢광폭!':'💢Raserei!','🕷산란!':'🕷Brut!',
'❄서리!':'❄Reif!','❄빙결파!':'❄Frostwelle!',
'💀빙마!':'💀Eisdämon!',
// --- Phase 13: mob actions ---
'돌진!':'Sturmangriff!','충격파!':'Schockwelle!','독안개!':'Giftnebel!',
'연타!':'Hagel!','포효!':'Gebrüll!','강화!':'Verstärkt!',
'꼬리!':'Schwanz!','은신...':'Tarnung...','기습!':'Hinterhalt!',
'산란!':'Brut!','독가스!':'Giftgas!','소멸...':'Auflösung...',
'강타!':'Schmettern!','분비!':'Absonderung!','채찍!':'Peitsche!',
'출혈!':'Blutung!','급강하!':'Sturzflug!','방출!':'Entladung!',
'충격!':'Aufprall!','치유!':'Heilung!','의식!':'Ritual!',
'지옥불!':'Höllenfeuer!','끌려감!':'Weggezogen!','혀!':'Zunge!',
'응시!':'Starren!','낙하!':'Absturz!','핏방울!':'Blutstropfen!',
'일어남!':'Auferstehung!','휩쓸기!':'Fegen!','웅크림':'Ducken',
'뼈칼날!':'Knochenklinge!','감속!':'Verlangsamung!','비명!':'Schrei!',
'화산탄!':'Vulkangeschoss!','자폭!':'Selbstzerstörung!','감싸기!':'Umhüllen!',
'잡기!':'Griff!','내리찍기!':'Schmetterer!','브레스!':'Odem!',
'비행!':'Flug!','용암비!':'Lavaregen!','물뿜기!':'Wasserstrahl!',
'빛...':'Licht...','삼키기!':'Verschlingen!','마비!':'Lähmung!',
'방전!':'Entladung!','집게찍기!':'Zangenhieb!','찍기!':'Schmetterer!',
'붙잡기!':'Ergreifen!','감아올리기!':'Umschlingen!','파편!':'Splitter!',
'할퀴기!':'Kratzen!','기생충!':'Parasit!',
'심연 해방!':'Abgrundbefreiung!','촉수난타!':'Tentakelhagel!',
'삼지창!':'Dreizack!','소용돌이!':'Wirbel!','해일!':'Tsunami!',
'끼걱!':'Knarzen!','폭발!':'Explosion!','체인!':'Kette!',
'갈기!':'Mähne!','공포!':'Terror!','흡혈!':'Blutsaugen!',
'베기!':'Hieb!','비이이명!!':'Kliiiirr!!','분열!':'Teilung!',
'3연참!':'Dreifachhieb!','패링!':'Parade!',
'...복사...':'...Kopie...','불균형...저주!':'Ungleichgewicht...Fluch!',
'저주!':'Fluch!','균형...강화!':'Gleichgewicht...Verstärkung!',
'심판의 기둥!':'Säule des Gerichts!','처형 선고!':'Todesurteil!',
'고통의 해방!':'Befreiung des Schmerzes!','너도 느껴봐라!':'Spüre es auch!',
'대검난무!':'Großschwert-Raserei!','촉수!':'Tentakel!',
'전방위 빔!':'Rundstrahl!','회피!':'Ausweichen!',
// --- Phase 13: rare mob / merchant ---
'[F] 상점':'[F] Laden','거래 성공!':'Handel erfolgreich!',
'악의 부족! (':'Nicht genug Bosheit! (',
'상인이 떠납니다...':'Der Händler verschwindet...',
'사슬 해방!':'Kettenbefreiung!','완전 해방!':'Vollständige Befreiung!',
'⏪ 시간 되감기!':'⏪ Zeitrückspulung!','전환!':'Wechsel!',
'부활 ':'Wiederbelebung ','🌀균열!':'🌀Riss!','...사라짐':'...Verschwunden',
'낫 베기!':'Sensenhieb!','☠ 죽음의 선고!':'☠ Todesurteil!',
'선고 집행...':'Urteil vollstreckt...',
'⚡패링!':'⚡Parade!','경직!':'Taumeln!',
'⚠ 잡혔다!':'⚠ Gepackt!','💥 내던지기!':'💥 Wurf!',
'💥 소용돌이 폭발!':'💥 Wirbelexplosion!',
'👻 순간이동!':'👻 Teleport!','💫 기절! 5초':'💫 Betäubt! 5s',
'찌르기 반격!':'Stoß-Konter!','💢 폭발!':'💢 Explosion!',
'반격 실패':'Konter fehlgeschlagen','탈취 반격!':'Diebstahl-Konter!',
'무기 봉인!':'Waffe versiegelt!','냠!':'Mampf!',
// --- Phase 13: stage/room/map ---
'합체!':'Fusioniert!','출구가 열렸다!':'Ausgang offen!',
'보물상자 출현!':'Schatztruhe erschienen!','출구':'Ausgang',
'⚠ 문지기가 살아있다!':'⚠ Torwächter noch am Leben!',
'⏱ 타임어택 ':'⏱ Zeitangriff ',
'처치율 ':'Tötungsrate ',
'불사 보호':'Untoten-Schutz',
'빙결!':'Gefroren!','환영 소멸!':'Phantom verschwunden!',
'부활력 ':'Wiederbelebungskraft ',
'✟ 신성력 억제! (':'✟ Heilige Unterdrückung! (',
'부활 실패 (':'Wiederbelebung fehlgeschlagen (',
'⚡순간이동!':'⚡Teleport!',
'👻 동반부활!':'👻 Gemeinsame Wiederbelebung!',
'✟ 신성력 억제!':'✟ Heilige Unterdrückung!',
'💀 부활 판정 중...':'💀 Auferstehungsurteil...',
'⚔ 문지기 처치!':'⚔ Torwächter besiegt!',
'🚪 보스방 개방!':'🚪 Bossraum offen!',
'잔해 출현!':'Trümmer erschienen!',
'🌀균열 발생!':'🌀Riss geöffnet!',
'🔥복수!':'🔥Rache!','💥폭독혈!':'💥Seuchenblut!',
'빙판!':'Eisfläche!','❄빙결파!':'❄Frostwelle!',
'❄최종빙결!':'❄Endgültige Vereisung!','빙마 처치!':'Eisdämon besiegt!',
'분리!':'Trennung!','뼈 파편!':'Knochensplitter!',
'태아 처치!':'Fötus besiegt!','지배자 처치!':'Gebieter besiegt!',
'용암!':'Lava!','화룡 처치!':'Feuerdrache besiegt!',
'최후의 비명!':'Letzter Schrei!','산화...':'Oxidation...',
'심판자 처치!':'Richter besiegt!','고통의 왕 처치!':'König des Schmerzes besiegt!',
'수역!':'Gewässer!','파편 폭발!':'Splitterexplosion!',
'거대어 처치!':'Leviathan besiegt!','대사도 처치!':'Hoher Apostel besiegt!',
'독웅덩이!':'Giftpfütze!','화염장판!':'Feuerzone!','전기장!':'Elektrofeld!',
'무기 드롭!':'Waffendrop!','보물 발견!':'Schatz gefunden!',
'상인의 주머니 +':'Händlerbeutel +',
'속박의 파편!':'Splitter der Fesselung!','시간의 조각!':'Zeitfragment!',
'저주 해제!':'Fluch aufgehoben!','차원의 결정!':'Dimensionskristall!',
'전설 아이템!':'Legendärer Gegenstand!','죽음을 이겨냈다!':'Den Tod bezwungen!',
'💥대폭발!':'💥Mega-Explosion!','⚡강화!':'⚡Verstärkt!',
// --- Phase 13: combat/defense ---
'장비 ':'Ausrüstung ',
'💫 진동!':'💫 Beben!','❄ 무적!':'❄ Unverwundbar!',
'\u{1F47B} 유령!':'\u{1F47B} Geist!',
'집중 해제!':'Fokus aufgehoben!',
'🕊️ 평화보호 ':'🕊️ Ägide ',
'🛡 보호막 ':'🛡 Schild ',
'🌀 회전보호막 ':'🌀 Wirbelschild ',
'💥한방캡!':'💥Eintrefferlimit!',
'⚡쉴드 파괴!':'⚡Schild zerstört!',
'💀 불굴!':'💀 Unbeugsam!',
'💀 1회부활!':'💀 Einmal-Wiederbelebung!',
'감시 회수':'Wachposten einziehen',
'악마화 부활!':'Dämonische Auferstehung!',
// --- Phase 13: skill panel ---
'기검참':'Ki-Hieb','날개치기':'Flügelschlag',
'배정 가능한 스킬 없음':'Keine zuweisbaren Fähigkeiten',
'칼날 없음!':'Keine Klinge!',
'⚔ 악의사냥!':'⚔ Bosheitsjagd!',
'❄🌪️ 얼음소용돌이!':'❄🌪️ Eiswirbel!',
'🌪️ 폭풍소환!':'🌪️ Wirbelsturm!',
'\u{1F9B4} 해골무덤!':'\u{1F9B4} Knochengruft!',
'🌹 붉은꽃!':'🌹 Purpurblüte!',
'💥 폭산탄!':'💥 Splitterschuss!',
'🪡 바늘출!':'🪡 Nadelschuss!',
'⚡ 전격이동!':'⚡ Blitzschritt!',
'기둥가시로 흡수됨':'Von Säulendorn absorbiert',
'🌿 가시덫!':'🌿 Dornenfalle!',
'👻 공성유령!':'👻 Belagerungsgeist!',
'🏹 공성쇠뇌 설치!':'🏹 Belagerungsarmbrust aufgestellt!',
'👻 유령 허수아비!':'👻 Phantomlockvogel!',
'💥 폭발 허수아비!':'💥 Sprenglockvogel!',
'축적!':'Gespeichert!','축적 중...':'Speichere...','만충! 재입력→폭발':'Voll! Erneut→Explosion',
'폭발! ':'Explosion! ','불발...':'Fehlzündung...','뎀':' SCHD',
'🩸 폭독칼날!':'🩸 Seuchenklinge!',
'⚡날개치기!':'⚡Flügelschlag!',
'🗡 칼등날개!':'🗡 Schildflügel!',
'🏛️ 악의기둥!':'🏛️ Finsternissäule!',
'🌿 기둥가시!':'🌿 Säulendorn!',
'🌋 지옥강타!':'🌋 Inferno-Hieb!',
'💥 체간 붕괴!':'💥 Haltungszusammenbruch!',
'💫 포이즈 파괴!':'💫 Haltung zerstört!',
'⚡ 뇌전걸음!':'⚡ Geisterschritt!',
'✟ 구속의 영역!':'✟ Fesselnde Domäne!',
'✟ 신성폭발!':'✟ Heilige Explosion!',
'⛧ 블랙!':'⛧ Schwarzer Stern!',
'🌋 용암소환!':'🌋 Lavabeschwörung!',
'필살기 배정!':'Ultimativ zugewiesen!',
'완료':'Abgeschlossen','합체 가능':'Fusion möglich','부족':'Unzureichend',
'SP 부족! (':'SP nötig! (',
'🕊️ 히든: 평화의보호 해금!':'🕊️ Versteckt: Ägide des Friedens freigeschaltet!',
'⚡ 히든: 참회 해금!':'⚡ Versteckt: Buße freigeschaltet!',
'배정됨':'Zugewiesen',
'합체 Lv.':'Fusions-Lv.',
'◆ 같은 보석 스킬 습득 시 합체 가능':'◆ Fusion möglich bei gleichem Edelstein-Skill',
// --- Phase 13: inventory/forge/storage ---
'▼ 가방 → 창고 보관':'▼ Beutel → Lager einlagern',
'▲ 창고 → 가방 꺼내기':'▲ Lager → Beutel herausnehmen',
'✓ 선택됨':'✓ Ausgewählt',
'⟨ 입력 대기... ⟩':'⟨ Warte... ⟩',
'⟨ 대기 ⟩':'⟨ Warte ⟩',
'보조':'Neben',
'키 설정 초기화 (또는 F5 키)':'Tastenbelegung zurücksetzen (oder F5)',
'아무 키 또는 마우스 버튼을 누르세요 (ESC = 취소)':'Beliebige Taste oder Maustaste drücken (ESC = Abbruch)',
'WebGPU 활성':'WebGPU aktiv','WebGL2 활성':'WebGL2 aktiv',
'측정 중...':'Messe...',
'불러오기 실패':'Laden fehlgeschlagen',
'장착':'Angelegt',
'🔒 중요잠금 아이템은 분해 선택 불가!':'🔒 Wichtig-gesperrte Gegenstände können nicht zerlegt werden!',
'장비 강화 (실패 시 재료만 소멸)':'Ausrüstung verstärken (bei Misserfolg nur Material verloren)',
'강화 보너스 적용':'Verstärkungsbonus angewendet',
'강화 실패!':'Verstärkung fehlgeschlagen!',
'장착된 장비가 없습니다.':'Keine angelegte Ausrüstung.',
'충분':'Genug','더 필요':'Mehr nötig',
'장비 선택':'Ausrüstung wählen','목표치 설정':'Ziel festlegen',
'악의 투입':'Bosheit investieren','자동 시도':'Auto-Versuch',
'목표 강화치':'Ziel-Verstärkung',
'예상 필요 악의':'Geschätzte Bosheit benötigt',
'보유':'Vorhanden','강화 시작':'Verstärkung starten',
'위에서 장비를 선택하세요':'Ausrüstung oben wählen',
'⬆ 물약 강화 (최대 10단)':'⬆ Trank verstärken (max. Stufe 10)',
'필요':'Benötigt',
'악의의 분해로 — 장비를 악의로 갈아버려라':'Bosheitsofen — Zermahle Ausrüstung zu Bosheit',
'전체 선택':'Alle wählen','전체 해제':'Alle abwählen',
'희귀 이하':'Selten oder niedriger',
'어픽스 리롤!':'Affix-Neuwurf!',
'물리':'Physisch','영웅':'Heroisch','전설':'Legendär',
'무기 타입':'Waffentyp','활 타입':'Bogentyp',
'보스방':'Bossraum','ST 부족':'Nicht genug ST',
// --- Phase 14: boss phase labels ---
'💀 광폭화!':'💀 Raserei!',
// --- Phase 14: chapter pet dialogue ---
'...따라오는 거 아니야. 같은 방향일 뿐이지.':'...Ich folge dir nicht. Wir gehen nur in dieselbe Richtung.',
'공기가 달라졌어. 더 썩었군.':'Die Luft hat sich verändert. Noch fauliger.',
'여기부터는 악마 영역이야. ...맘대로 해.':'Ab hier ist Dämonengebiet. ...Mach, was du willst.',
'...이 냄새. 살점이 썩는 냄새야.':'...Dieser Gestank. Verrottendes Fleisch.',
'여기 오래 있으면 미쳐. 나도, 너도.':'Bleib zu lange und du wirst wahnsinnig. Ich auch.',
'이 길의 끝에 뭐가 있을까. ...알고 싶지도 않어.':'Was am Ende dieses Weges liegt? ...Ich will es nicht wissen.',
'...여기가 끝이야. 돌아갈 길은 없어.':'...Das ist das Ende. Es gibt kein Zurück.',
// --- Phase 14: idle tips (crow) ---
'작살을 땅에 꽂으면 끌려간다.':'Ramm die Harpune in den Boden und lass dich ziehen.',
'Shift로 작살 던져봐!':'Wirf die Harpune mit Shift!',
'패링 성공하면 ST가 회복된다. 공짜 자원이야.':'Erfolgreiche Parade stellt ST wieder her. Kostenlose Ressourcen.',
'패링 많이 하면 ST 걱정 없어~':'Pariere viel und ST ist nie ein Problem~',
'장비 분해하면 악의를 얻는다. 쓰레기도 자원이야.':'Zerlegte Ausrüstung gibt Bosheit. Selbst Schrott ist Ressource.',
'TAB 열어서 안 쓰는 장비 분해해!':'Öffne TAB und zerlege ungenutzte Ausrüstung!',
'그로기 상태의 적에겐 1.5배 데미지가 들어간다.':'Benommene Feinde nehmen 1,5-fachen Schaden.',
'무릎 꿇으면 전력으로 때려!':'Wenn sie knien, schlag mit allem zu!',
'속성 상성이 있다. 화염은 빙결에 약하고, 암전은 암흑에 약하다.':'Elemente haben Konter. Feuer ist schwach gegen Eis, Blitz gegen Finsternis.',
'무기 속성 바꿔가면서 싸워봐!':'Wechsle die Waffenelemente im Kampf!',
'빙결된 적은 1.5배 데미지를 받는다.':'Gefrorene Feinde nehmen 1,5-fachen Schaden.',
'얼리고 때리는 게 기본이야!':'Einfrieren und zuschlagen — das sind die Grundlagen!',
'보스의 빨간 공격은 패링 가능. 보라빛은 회피만.':'Rote Bossangriffe sind parierbar. Regenbogen nur ausweichen.',
'색깔 잘 봐! 빨강은 받아치고 무지개는 피해!':'Achte auf die Farbe! Rot parieren, Regenbogen ausweichen!',
'VIT를 올리면 최대 HP가 오른다. 죽기 싫으면 찍어.':'VIT erhöht max HP. Investiere, wenn du überleben willst.',
'STR은 근접, DEX는 활, INT는 마법! 골고루 말고 하나만!':'STR für Nahkampf, DEX für Bogen, INT für Magie! Fokussiere eins!',
'E를 꾹 누르면 빔이 나간다. 짧게 누르면 투사체.':'Halte E für Strahl. Kurz drücken für Projektil.',
'마법 쓸 때 MP 잘 봐! 빔은 연속으로 깎여!':'Achte auf MP bei Magie! Strahl verbraucht schnell!',
'핵터와 디로이가 아이템을 주워준다. 수거 범위 안이면.':'Hecter und Deroy sammeln Gegenstände in Reichweite.',
'우리한테 고마워해~ 안 주우면 썩잖아.':'Sei uns dankbar~ Ungesammelt verrottet es.',
'LCK를 올리면 레어 드롭률이 오른다.':'LCK erhöht die Droprate seltener Gegenstände.',
'운빨 게임이긴 하지~ LCK 올려봐!':'Es ist alles Glück~ Versuch LCK zu erhöhen!',
'강화하면 공격력이 쭉쭉 올라가! 악의만 있으면 돼!':'Verstärkung steigert ATK schnell! Braucht nur Bosheit!',
'강화 확률은 +1에서 99%. 높을수록 떨어진다.':'Verstärkungschance startet bei 99% für +1. Sinkt danach.',
'실패하면 악의만 날아가~ 장비는 안 부서져!':'Bei Misserfolg geht nur Bosheit verloren~ Ausrüstung bleibt!',
'대장간에서 장비 제작도 된다. 악의 30000개면 영웅급 이상.':'Die Schmiede kann auch herstellen. 30000 Bosheit für Heroisch+.',
'랜덤이지만 좋은 거 나올 수도 있어!':'Zufällig, aber vielleicht kommt was Gutes!',
'쉴드는 마법으로, HP는 물리로 깎아야 제대로 먹힌다.':'Schilde brauchen Magie, HP braucht Physisch.',
'반대로 치면 50%만 들어가! 무기 바꿔가면서 싸워!':'Falscher Typ macht nur 50%! Wechsle die Waffen!',
'장비에 접두사, 접미사가 붙으면 특수 효과가 생긴다.':'Ausrüstung mit Präfix/Suffix hat Spezialeffekte.',
'영웅급 이상 장비에만 붙어! 좋은 거 나오면 강화해!':'Nur bei Heroisch+! Gute Würfe verstärken!',
'강화는 장비를 바꿔도 자동 이전된다. 악의만 있으면.':'Verstärkung überträgt sich automatisch. Kostet nur Bosheit.',
'더 좋은 장비 나오면 바로 장착해! 강화 수치 그대로 옮겨가!':'Bessere Ausrüstung sofort anlegen! Verstärkung überträgt sich!',
// --- Phase 14: additional tutorial lines ---
'패링을 써야 자원을 흡수한다고!':'Du musst parieren, um Ressourcen zu absorbieren!',
'F키 회복의 영역을 써봐. 자원이 차올라.':'Versuch F-Taste Heilige Domäne. Ressourcen füllen sich.',
'적이 근접하면 스페이스키야! 가시덫을 활용해!':'Wenn Feinde nah kommen, Leertaste! Nutze die Dornenfalle!',
'기절시켜! 그로기가 터지면 데미지가 1.5배야!':'Betäube sie! Benommen bedeutet 1,5-fach Schaden!',
'1번 대왕치기로 밀어버려!':'Taste 1 Titanenschlag zum Wegstoßen!',
'무릎 꿇었다.':'Es kniet nieder.',
'지금이야! 몰아쳐!!':'Jetzt! Voller Angriff!!',
'스킬 포인트 있어! K 눌러서 스킬 찍어봐!':'Fähigkeitspunkte vorhanden! Drück K zum Erlernen!',
'...힘이 없으면 여기서 끝이야.':'...Ohne Stärke endet es hier.',
'...쓸 거 아니면 분해해.':'...Was du nicht brauchst, zerlege es.',
'아이템 넘쳐나네~ 우리가 주워줄게!':'So viele Gegenstände~ Wir sammeln für dich!',
'악의가 바닥이다.':'Bosheit aufgebraucht.',
'TAB 열어서 장비 분해해! 쓰레기도 악의가 돼!':'Öffne TAB und zerlege! Selbst Schrott wird zu Bosheit!',
'좋은 장비가 있네! G 눌러서 대장간 가봐!':'Gute Ausrüstung! Drück G für die Schmiede!',
'...강화 안 하면 그냥 고철이야.':'...Ohne Verstärkung ist es nur Altmetall.',
'...멈추지 마. 여신은 기다리지 않는다.':'...Bleib nicht stehen. Die Göttin wartet nicht.',
'앞으로 가자~ 나도 여기 오래 있기 싫어.':'Gehen wir weiter~ Ich will auch nicht lange hierbleiben.',
'...냄새가 짙다. 큰 놈이 있어.':'...Der Gestank ist dicht. Etwas Großes ist hier.',
'준비됐어? 물약 확인하고!':'Bereit? Tränke prüfen!',
// --- Phase 15: missing pet dialogue translations ---
// ── Tutorial: firstItem, potionCraft ──
'TAB을 눌러. 가방을 열고 장비를 입어야 한다.':'Drück TAB. Öffne den Beutel und leg Ausrüstung an.',
'주웠으면 껴야지! TAB!':'Aufgehoben? Dann anziehen! TAB!',
'G. 대장간에서 물약도 제작할 수 있다.':'G. In der Schmiede kannst du auch Tränke herstellen.',
'악의로 물약 만들어! G키야!':'Stelle Tränke aus Bosheit her! G-Taste!',
// ── Stun warning ──
'기절이야! Ctrl 눌러!':'Betäubt! Drück Ctrl!',
'Ctrl 유령걸음으로 탈출!':'Ctrl Geisterschritt zur Flucht!',
'Ctrl 얼음보주로 탈출!':'Ctrl Eiskugel zur Flucht!',
// ── Parry guide ──
'빨간 탄은 우클릭 패링. 무지개는 Q 패링.':'Rote Geschosse: RMT Parade. Regenbogen: Q Parade.',
'나머지는 전부 우클릭 패링 가능해!':'Alles andere kann mit RMT pariert werden!',
'빨강=우클릭, 무지개=Q 패링. 나머진 다 쳐내.':'Rot=RMT, Regenbogen=Q Parade. Den Rest parieren.',
'무지개는 Q로 패링! 나머지는 전부 우클릭!':'Regenbogen mit Q! Alles andere mit RMT!',
// ── Resource / combat ──
'빠져! 물약 마시고 안전한 곳에서 회복해.':'Rückzug! Trank trinken und sicher erholen.',
'자원 없으면 도망가는 게 답이야!':'Keine Ressourcen? Fliehen ist die Antwort!',
'스페이스! 가시덫으로 적 묶어버려!':'Leertaste! Feinde mit Dornenfalle fesseln!',
'근접이 너무 많아! 거리 벌려!':'Zu viele Nahkämpfer! Abstand schaffen!',
'...둘러싸이면 끝이야. 빠져나와.':'...Umzingelt und es ist vorbei. Brich aus.',
'1번 대왕치기로 쓸어버려!':'Taste 1 Titanenschlag zum Wegfegen!',
'그로기 터지면 데미지 1.5배!':'Benommen bringt 1,5-fach Schaden!',
'회전참이나 광역기로 몰아! 한 놈씩 상대하면 죽어.':'Wirbelwind oder Fläche! Einzeln kämpfen heißt sterben.',
'뭉쳐있을 때가 기회야!':'Wenn sie sich sammeln, ist die Chance da!',
'E로 마력공격을 해봐! 악의 쉴드를 해제할려면 마법 공격을 해야 해!':'Versuch E für Magieangriff! Bosheitsschilde brauchen Magie!',
'쉴드는 마법으로, HP는 물리로. 반대로 치면 데미지 안 들어간다.':'Schilde brauchen Magie, HP braucht Physisch. Falscher Typ macht keinen Schaden.',
// ── Skill / passive / stamina hints ──
'L키로 스킬 슬롯에 넣어야 쓸 수 있어.':'Drück L, um Fähigkeiten den Slots zuzuweisen.',
'C키를 눌러. 패시브 포인트가 쌓여있다.':'Drück C. Passive Punkte haben sich angesammelt.',
'C키! 패시브 올리면 진짜 강해져!':'C-Taste! Passive machen dich wirklich stärker!',
'스태미나가 부족하다. 무리하지 마.':'Ausdauer ist niedrig. Übertreib es nicht.',
'ST 없으면 스킬 못 써! 잠깐 빠져!':'Ohne ST keine Fähigkeiten! Kurz zurückziehen!',
// ── Item pickup (line 9324) ──
'탭 장비창을 열어봐. 아이템을 주워왔어!':'Öffne TAB-Ausrüstungsmenü. Wir haben etwas aufgesammelt!',
'좋은 거 나왔다! TAB 열어서 확인해봐!':'Etwas Gutes gefallen! Öffne TAB zum Prüfen!',
// ── Revive tutorial (line 22486) ──
'악의에 중독되면 악마가 돼서 부활력이 생긴대. 저 녀석처럼.':'Man sagt, Bosheitsucht macht dich zum Dämon mit Wiederbelebungskraft. Wie jener dort.',
'혹시 너도...?':'Vielleicht du auch...?',
// ── Revive tip (line 30541) ──
'데미지가 부족하면 무기류 강화를 해야해!!':'Wenn der Schaden nicht reicht, verstärke deine Waffen!!',
'G키 대장간. 강화 안 하면 여기서 계속 죽어.':'G-Taste Schmiede. Ohne Verstärkung stirbst du hier immer wieder.',
// ── Idle nag lines ──
'시간이 없어. 움직여.':'Keine Zeit. Beweg dich.',
'멍하게 서있으면 안 돼!':'Steh nicht einfach rum!',
'...뭘 기다리는 거야?':'...Worauf wartest du?',
'가자가자! 몬스터가 기다려!':'Los los! Die Monster warten!',
'여기 오래 있으면 위험해.':'Zu lange hierbleiben ist gefährlich.',
'움직여야 해! 가만있으면 둘러싸여!':'Beweg dich! Stillstehen und sie umzingeln dich!',
'쉬는 건 죽고 나서 해.':'Ruh dich aus, wenn du tot bist.',
'살아있을 때 쉬면 안 돼!':'Keine Ruhe, solange du lebst!',
'적이 몰려오고 있어. 빨리 움직여.':'Feinde rücken an. Beeil dich.',
'냄새 맡고 올 거야. 빨리!':'Sie werden dich riechen. Schnell!',
'...아직 살아있는 거 맞지?':'...Du bist noch am Leben, oder?',
'혹시 잠든 거야...?':'Bist du eingeschlafen...?',
// ── Chapter entry dialogues ──
'...나무가 썩어가고 있어. 여기는 지옥의 입구야.':'...Die Bäume verfaulen. Das ist der Eingang zur Hölle.',
'냄새 지독해... 빨리 지나가자.':'Der Gestank ist furchtbar... Gehen wir schnell weiter.',
'조심해. 벌레굴이다. 벽이랑 바닥에서 기어나와.':'Vorsicht. Wurmnest. Sie kriechen aus Wänden und Böden.',
'으으... 벌레 싫어! 밟아버려!':'Ugh... Ich hasse Ungeziefer! Zertritt sie!',
'...공기가 얼어붙는다. 여기선 화염이 먹힌다.':'...Die Luft gefriert. Hier wirkt Feuer.',
'추워... 빙결 조심해! 얼면 끝이야.':'Kalt... Vorsicht vor Frost! Gefroren und es ist vorbei.',
'용암이다. 바닥을 밟으면 타 죽어.':'Lava. Tritt auf den Boden und du verbrennst.',
'뜨거워! 여기 왜 이렇게 빨개!':'So heiß! Warum ist hier alles so rot!',
'...군단이다. 수가 많아. 광역기 없으면 밀려.':'...Die Legion. Zu viele. Ohne Flächenangriff wirst du überrannt.',
'우글우글... 징그러워. 한꺼번에 쓸어!':'Überall Gewimmel... Ekelhaft. Feg sie alle auf einmal weg!',
'사도의 영역이야. 여기 놈들은 머리가 좋아.':'Gebiet des Apostels. Diese hier sind klug.',
'패턴이 복잡해졌어... 집중해!':'Die Muster sind komplexer geworden... Konzentrier dich!',
'...끝이다. 지옥의 심장부. 살아 돌아가는 건 포기해라.':'...Das ist es. Das Herz der Hölle. Gib die Hoffnung auf Rückkehr auf.',
'여기가 마지막이야... 각오해.':'Das hier ist das Ende... Mach dich bereit.',
'석궁 자동발사 (T)':'Armbrust automatisch (T)',
'버스트루프 당기기 (H)':'Burst-Schleife anziehen (H)',
'결정 자동합성':'Kristall Auto-Synthese',
'결정 자동강화':'Kristall Auto-Verstärkung',
'✓ 설정 자동 저장':'✓ Einstellungen auto gespeichert',
'세팅 프리셋 저장/불러오기':'Voreinstellung speichern/laden',
'세팅1 저장':'Voreinstellung 1 speichern','세팅1':'Voreinstellung 1',
'세팅2 저장':'Voreinstellung 2 speichern','세팅2':'Voreinstellung 2',
'재진단':'Neu diagnostizieren',
'게임 리셋 (처음부터)':'Spiel zurücksetzen (von Anfang)',
'캐릭터 선택 (로비)':'Charakterauswahl (Lobby)',
'닫기 [ESC]':'Schließen [ESC]','닫기 [G]':'Schließen [G]','닫기 [V]':'Schließen [V]','닫기 [C]':'Schließen [C]',
'전체화면 (F11)':'Vollbild (F11)',
'정말 모든 진행을 초기화하시겠습니까?':'Wirklich alle Fortschritte zurücksetzen?',
'검출 중...':'Erkennung...',
'마우스 커서':'Mauszeiger','그래픽 품질':'Grafikqualität','하드웨어 진단':'Hardware-Diagnose',
'BGM 선택':'BGM-Auswahl',
'자동 (스테이지별)':'Automatisch (pro Stage)','전체 랜덤':'Alles zufällig','로비':'Lobby',
'1장 랜덤':'Kapitel 1 zufällig','2장 랜덤':'Kapitel 2 zufällig','3장 랜덤':'Kapitel 3 zufällig',
'4장 랜덤':'Kapitel 4 zufällig','5장 랜덤':'Kapitel 5 zufällig','6장 랜덤':'Kapitel 6 zufällig','7장 랜덤':'Kapitel 7 zufällig',
'보스':'Boss','최종보스':'Endgegner',
'대장간 랜덤':'Schmiede zufällig','사망 랜덤':'Tod zufällig','승리 랜덤':'Sieg zufällig',
'지옥 추락 사망 징글':'Höllensturz-Todessignal','탈출 성공':'Flucht erfolgreich',
'── 1장 - 썩은 숲 ──':'── Kap. 1 - Fauliger Wald ──','── 2장 - 벌레굴 ──':'── Kap. 2 - Wurmnest ──',
'── 3장 - 얼음굴 ──':'── Kap. 3 - Eishöhle ──','── 4장 - 화염지대 ──':'── Kap. 4 - Flammenöde ──',
'── 5장 - 지옥군단 ──':'── Kap. 5 - Höllenlegion ──','── 6장 - 사도마굴 ──':'── Kap. 6 - Schlund des Apostels ──',
'── 7장 - 지옥성 ──':'── Kap. 7 - Höllenfeste ──','── 공통 ──':'── Allgemein ──',
'⌨ 조작법':'⌨ Steuerung','클릭하면 닫힘':'Klicken zum Schließen',
'전투력':'KP','가방':'Rucksack','결정':'Kristall',
'↕ 정렬':'↕ Sortieren','쓰레기 전체선택':'Schrott alles auswählen','쓰레기 전부 분해':'Schrott alles zerlegen',
'창고':'Lager','스탯 포인트':'Attributpunkte','능력치 요약':'Statusübersicht','올 리셋':'Alles zurücksetzen',
'대장간':'Schmiede','스킬':'Fähigkeiten','능력치':'Attribute',
'좌클스킬 (클릭 전환)':'LMB-Fähigkeit (Klick zum Wechseln)','우클스킬 (클릭 전환)':'RMB-Fähigkeit (Klick zum Wechseln)',
'이동스킬 (클릭 전환)':'Bewegungsfähigkeit (Klick zum Wechseln)','마법스킬 (클릭 전환)':'Magiefähigkeit (Klick zum Wechseln)',
'영역스킬 (클릭 전환)':'Flächenfähigkeit (Klick zum Wechseln)','피보호막 (클릭 전환)':'Blutschild (Klick zum Wechseln)',
'CT스킬 (클릭 전환)':'CT-Fähigkeit (Klick zum Wechseln)','[C] 능력치':'[C] Attribute',
'무기 공격':'Waffenangriff','칼등 처내기 (투사체 반사, 홀드 연사)':'Parade (reflektiert Projektile, Halten=Salve)',
'연속 처내기':'Fortlaufende Parade','영역 스킬 (폭풍소환 등)':'Flächenfähigkeit (Wirbelsturm usw)',
'작살 발사':'Harpune abschießen','마법 (탭=투사체, 홀드=빔)':'Magie (Tippen=Projektil, Halten=Strahl)',
'데빌포스 흡수':'Teufelskraft absorbieren','물약 / 스킬슬롯':'Tränke / Fähigkeitsslots',
'스킬슬롯 5 / 필살기 / CT스킬':'Slot 5 / Ultimativ / CT-Fähigkeit','스킬 슬롯 배정':'Slot-Zuweisung',
'✟ 결계의 영역!':'✟ Banndomäne!',
'✟ 물의 영역!':'✟ Wasserdomäne!',
'✟ 파쇄의 영역!':'✟ Splitterdomäne!',
'✟ 침식의 영역!':'✟ Ätzdomäne!',
'✟ 관통의 영역!':'✟ Durchdringdomäne!',
'✟ 권능의 영역!':'✟ Allmachtdomäne!',
'⏳ 시간왜곡!':'⏳ Zeitverzerrung!',
'쿨다운!':'Abklingzeit!',
'집중!':'Konzentration!',
'\u{1F47B} 유령총!':'\u{1F47B} Geisterpistole!',
'💥 유령총 폭발!':'💥 Geisterpistolen-Explosion!',
'⚡ 전격의창!':'⚡ Donnerlanze!',
'임계...!':'Kritisch...!',
// --- Phase 27 additions ---
// KEY BINDINGS
'위로 이동':'Hoch','아래로 이동':'Runter','왼쪽 이동':'Links','오른쪽 이동':'Rechts',
'칼등 처내기 (탭=처내기, 홀드=연사)':'Parade (Tippen=Parade, Halten=Salve)',
'영역 스킬':'Flächenfähigkeit','작살 이동':'Harpunenrückstoß',
'유령불꽃 켜기/끄기':'Geisterflamme an/aus',
'기동칼날개 자동 켜기/끄기':'Auto-Klingenflügel an/aus',
'해상도':'Auflösung',
// DEATH / LEVEL-UP / INTRO SCREEN
'빛이 꺼졌다':'Das Licht erlischt',
'누군가는 너를 기다리고 있다':'Jemand wartet auf dich',
'다시 일어서라':'Steh wieder auf',
'로비로 돌아가기':'Zurück zur Lobby',
'☠ 사망 리플레이':'☠ Todeswiederholung',
'지옥의 시련을 견뎌냈다':'Du hast die Prüfung der Hölle bestanden',
'계속 전투':'Kampf fortsetzen',
'난이도를 선택하라':'Wähle die Schwierigkeit',
'나중에 설정(ESC)에서 변경 가능':'Kann später in Einstellungen (ESC) geändert werden',
// UI
'일괄합성':'Massen-Synthese','일괄강화+합성':'Massen-Verstärkung+Synthese',
'자원 부족!':'Ressourcen knapp!',' 뎀':' SCHD',
// GAME COMBAT MESSAGES
'합체 폭발!':'Fusionsexplosion!',
'MP 부족! (50)':'Nicht genug MP! (50)',
'부활력 고갈!':'Auferstehungskraft erschöpft!',
'☠ 부활력 고갈!':'☠ Auferstehungskraft erschöpft!',
'독안개':'Giftnebel','뇌전창':'Donnerlanze',
'🔥 업화선 시전...':'🔥 Höllenfeuerstrahl wirken...',
'💥 기동파괴 그로기!':'💥 Kettenbrecher — Benommen!',
'💥 칼등 그로기!':'💥 Parade — Benommen!',
'⚡ 순간이동 준비!':'⚡ Teleport bereit!',
'👿악의+1000':'👿Bosheit+1000',
'💀 내려찍기!':'💀 Niederschmettern!',
'✟ 신성력 억제! +':'✟ Heilige Unterdrückung! +',
'✟ 신성력 억제!':'✟ Heilige Unterdrückung!',
'✟ 신성력 억제! (':'✟ Heilige Unterdrückung! (',
'💥 지진그로기!':'💥 Erdbeben-Betäubung!',
'💥 기폭그로기!':'💥 Detonations-Betäubung!',
'폭발! ×':'Explosion! ×',
'⚫ 기둥강타!':'⚫ Säulenschlag!',
'💥 대왕치기 그로기!':'💥 Titanenschlag — Benommen!',
'💫 미니스턴!':'💫 Mini-Betäubung!',
'⚡ 뇌전창!':'⚡ Donnerlanze!',
// PET DIALOGUE (crow/cat)
'…절반이다. 정신차려.':'…Hälfte. Reiß dich zusammen.',
'…죽기 직전이다. 한 발만 더.':'…Kurz vorm Tod. Noch ein Treffer.',
'…다음 한 방이 마지막이야.':'…Der nächste Treffer ist der letzte.',
'기절!  ':'Betäubt!  ',
'마력이 빈다. 평타 섞어.':'MP schwindet. Normale Angriffe mischen.',
'그랩이다. 거리를 둬.':'Greifer. Abstand halten.',
'광역기다. 멀어져.':'Fläche. Zurückweichen.',
'…아파? 당연하지. 여긴 지옥이야.':'…Schmerzt? Natürlich. Das hier ist die Hölle.',
'F키도 스킬 슬롯이야!':'F-Taste ist auch ein Slot!',
'L-CTRL로 유령걸음/얼음보주!':'L-CTRL für Geisterschritt / Eiskugel!',
'V 눌러서 창고에 넣어둬!':'Drück V fürs Lager!',
'ESC로 설정! 난이도/자동물약!':'ESC — Einstellungen! Schwierigkeit/Auto-Trank!',
'잡몹이다. 먼저 정리해.':'Normale Gegner. Erst aufräumen.',
'…얼어붙은 놈은 오래 안 간다.':'…Gefrorene halten nicht lange.',
'…냄새가 짙다. 큰 놈이 있어.':'…Der Geruch ist dicht. Etwas Großes.',
'쉴드는 마법으로, HP는 물리로.':'Schilde mit Magie, HP mit Physisch.',
'스페이스! 가시덫으로 적 묶어!':'Leertaste! Feinde mit Dornenfalle fesseln!',
'근접 너무 많아! 거리 벌려!':'Zu viele Nahkämpfer! Abstand!',
'회전참이나 광역기로 몰아!':'Wirbelwind oder Fläche einsetzen!',
'F 눌러! 회복의 영역 깔아!':'Drück F! Heilige Domäne aufstellen!',
'F키 회복의 영역을 써봐.':'Versuch F-Taste Heilige Domäne.',
'빠져! 물약 마시고 회복해.':'Rückzug! Trank trinken und erholen.',
'쉬프트! 사슬기동은 이동기야!':'Shift! Kettensturm ist Bewegung!',
'스킬포인트 쌓였어! K 눌러!':'Fähigkeitspunkte bereit! Drück K!',
'스킬 포인트 있어! K!':'Fähigkeitspunkte vorhanden! K!',
'C키. 패시브 포인트가 쌓여있다.':'C-Taste. Passive Punkte haben sich angesammelt.',
'…쓸 거 아니면 분해해.':'…Was du nicht brauchst, zerleg es.',
'…강화 안 하면 그냥 고철이야.':'…Ohne Verstärkung nur Altmetall.',
'빨간 탄은 우클릭. 무지개는 Q.':'Rot — Rechtsklick. Regenbogen — Q.',
'빨강=우클릭, 무지개=Q.':'Rot=Rechtsklick, Regenbogen=Q.',
'…멈추지 마. 여신은 기다리지 않는다.':'…Bleib nicht stehen. Die Göttin wartet nicht.',
'패턴이 바뀐다. 거리를 둬.':'Muster ändert sich. Abstand halten.',
'미쳐가고 있어. 광폭화다.':'Es rastet aus. Berserker.',
'마지막이야! 끝장내!':'Letzte Phase! Beende es!',
'…끝났다. 다음으로.':'…Vorbei. Weiter.',
'다 잡았다! 포탈 어딨어?':'Alle erledigt! Wo ist das Portal?',
'근육으로 만든 빌드군. 베고 부숴.':'Kraft-Build. Hauen und brechen.',
'활을 쥐었군. 거리를 둬.':'Bogen in Hand. Abstand halten.',
'마법사군. MP 관리부터 배워라.':'Magier. Erst MP-Verwaltung lernen.',
'운에 기댄 빌드군. …드롭은 좋겠어.':'Glücks-Build. …Wenigstens sind Drops gut.',
'…VIT가 너무 낮아. 한 방에 죽는다.':'…VIT zu niedrig. Stirbst mit einem Treffer.',
'다 찍으면 다 약해진다. 하나만 골라.':'Alles maxen und überall schwach. Nur eins wählen.',
'…3단. 적이 강해져. 정신 차려.':'…Etappe 3. Feinde stärker. Konzentrier dich.',
'5단이다. …너도 강해졌단 뜻이야.':'Etappe 5. …Heißt, du bist auch stärker geworden.',
'…7단. 아직 살아있단 게 신기하군.':'…Etappe 7. Noch am Leben. Erstaunlich.',
'10단. …너는 이제 인간이 아니야.':'Etappe 10. …Du bist kein Mensch mehr.',
'…일반으로 내려왔군. 가끔은 쉬어가야지.':'…Zurück auf Normal. Manchmal braucht man eine Pause.',
'…이게 진짜 패링이야.':'…Das ist echte Parade.',
'…피가 묻기 시작했군.':'…Blut beginnt zu fließen.',
'100. 너는 인간이 아니야.':'100. Du bist kein Mensch.',
'…피 흘리며 베는군.':'…Schneidest durch Blut.',
'빨간콩이 푸르게 변했다. 그게 너의 무기야.':'Der rote Kern wurde blau. Das ist deine Waffe.',
'무지개를 받아쳤군. 그건 진짜 어렵다.':'Regenbogen pariert. Das ist wirklich schwer.',
'…너무 빨라. 닿기 직전에 눌러.':'…Zu schnell. Drück kurz vor dem Kontakt.',
'악의가 가득 찼다. 풀어내.':'Bosheit ist voll. Entlade sie.',
'작살이 살을 뚫었어. 끌고 와.':'Die Harpune hat Fleisch durchbohrt. Zieh heran.',
'…풀차지군. 멀리 던져버려.':'…Voll geladen. Wirf es weit.',
'…빈틈을 그대로 빠져나갔다.':'…Schlüpfte direkt durch die Lücke.',
'…일반 잡몹이 아니야. 모디파이어 붙었군.':'…Kein normaler Gegner. Hat einen Modifikator.',
'엘리트 하나 처리.':'Ein Elite erledigt.',
'…큰 놈이다. 일반 잡몹 정리부터.':'…Großer. Erst normale Gegner aufräumen.',
'미니보스 처리. 다음 길로.':'Mini-Boss erledigt. Weiter.',
'한 번에 다섯. 깔끔해.':'Fünf auf einmal. Sauber.',
'100강. 이제 뭔가 다르게 보이는군.':'+100. Jetzt sieht alles anders aus.',
'…운이 없는 날이야.':'…Heute kein Glück.',
'…전설이다. 이런 건 처음 본다.':'…Legendär. Sowas noch nie gesehen.',
'…죽었다 살아났네. 여신은 너를 포기 안 했어.':'…Gestorben und zurück. Die Göttin hat nicht aufgegeben.',
'…또야? 패턴 좀 외워!':'…Schon wieder? Lern das Muster!',
'…한 번도 안 죽고. 그건 진짜 실력이야.':'…Kein einziger Tod. Das ist echtes Können.',
'…ACT1을 끝냈다. 진짜 시작은 여기서부터야.':'…AKT1 beendet. Der echte Start beginnt hier.',
'모든 보스를 무너뜨렸다. 너는 지옥의 일부야.':'Alle Bosse gefallen. Du bist nun Teil der Hölle.',
'…30초. 너 진짜 미쳤구나.':'…30 Sekunden. Du bist wirklich wahnsinnig.',
'…빠르군. 효율적이야.':'…Schnell. Effizient.',
'신기록이다.':'Neuer Rekord.',
'탭 장비창을 열어봐.':'Öffne TAB — Ausrüstung.',
'데미지 부족하면 무기 강화!':'Nicht genug Schaden? Waffe verbessern!',
// --- Loading screen ---
'불러오는 중...':'Lädt...',
'로딩중...':'Lädt...',
'맵과 몬스터 불러오는 중...':'Karte und Monster werden geladen...',
'기본 데이터 준비 중...':'Grunddaten werden vorbereitet...',
'저장 데이터 불러오는 중...':'Speicherdaten werden geladen...',
'몬스터 스킨 로딩...':'Monster-Skins werden geladen...',
'맵과 몬스터 생성 중...':'Karte und Monster werden generiert...',
'맵 에셋 로딩...':'Karten-Ressourcen werden geladen...',
'맵 환경 준비 중...':'Kartenumgebung wird vorbereitet...',
'주변 청크 준비 중...':'Benachbarte Chunks werden vorbereitet...',
'맵 캐시 생성 중...':'Karten-Cache wird erstellt...',
'미니맵 빌드 중...':'Minimap wird erstellt...',
// Phase 28
' 으로 탈출!':' zum Entkommen!',
'100명?! 미쳤어!':'100 Abschüsse?! Wahnsinn!',
'10단 최고난이도! 너 진짜 광기야!':'Schwierigkeit 10 maximal! Du bist völlig verrückt!',
'1분 안에 클리어! 빠르네!':'Stufe in 1 Min. abgeschlossen! So schnell!',
'30초!! 스피드런 가능해!':'30 Sekunden!! Speedrun-Potenzial!',
'3단! 보상도 좋아지지만 죽기 쉬워!':'Schw. 3! Bessere Belohnungen, aber leichter zu sterben!',
'50명! 학살자야!':'50 Abschüsse! Du bist ein Schlächter!',
'5단!! 진짜 게이머 인증!':'Schw. 5!! Echter Gamer bestätigt!',
'7단!! 다른 사람들 이 정도 못 와!':'Schw. 7!! Andere kommen nicht so weit!',
'ACT1 완주! 우리가 진짜 해냈어!':'ACT1 abgeschlossen! Wir haben es wirklich geschafft!',
'Ctrl 얼음보주로 탈출하라.':'Strg — entkommen mit der Eiskugel.',
'Ctrl 유령걸음으로 탈출하라.':'Strg — entkommen mit dem Geisterschritt.',
'C키! 패시브 강해져!':'C-Taste! Passive werden stärker!',
'DEX 빌드! 거리에서 패고, 추적탄 좋아!':'GES-Build! Aus der Distanz angreifen, Verfolgungsschüsse sind großartig!',
'E로 마력공격을 해봐!':'Versuche den Magieangriff mit E!',
'G 눌러서 대장간 가봐!':'Drücke G, um die Schmiede zu besuchen!',
'G키 대장간. 강화 안 하면 계속 죽어.':'G — Schmiede. Ohne Verbesserungen stirbst du weiter.',
'HP 70%! 조심해!':'HP 70 %! Vorsicht!',
'INT 빌드! 빔이랑 폭발 마법! MP 잘 봐!':'INT-Build! Strahlen und Explosionsmagie! Achte auf dein MP!',
'LCK 높아! 레어 드롭률 미친 거 알지?':'Hoher GLCK-Wert! Du weißt, dass die Drop-Raten verrückt sind, oder?',
'L로 어디에 뭘 넣을지 골라!':'Drücke L, um auszuwählen, was in jeden Slot kommt!',
'MP 부족! 평타로 패면서 회복해!':'MP niedrig! Mit Basisangriffen treffen, um zu regenerieren!',
'ST 없으면 스킬 못 써!':'Kein ST, keine Fähigkeiten!',
'STR 빌드! 회전참, 회오리, 광역기 추천!':'STR-Build! Drehschlag, Wirbelwind, AoE empfohlen!',
'VIT 좀 찍어! HP 너무 적어!':'Etwas VIT hinzufügen! HP ist viel zu niedrig!',
'Z 누르면 대박! 쿨타임 길어!':'Z drücken für das Große! Langer Cooldown allerdings!',
'…고기 냄새. 싫진 않네.':'…Blutgeruch. Nicht unangenehm.',
'…둘러싸이면 끝이야.':'…Eingekreist werden und es ist vorbei.',
'…말은 못해.':'…Kann nicht sprechen.',
'…버리기 아까운 건 창고에.':'…Was aufzubewahren sich lohnt, kommt ins Lager.',
'…빈틈을 노려.':'…Achte auf Lücken.',
'…설정을 확인해.':'…Überprüfe deine Einstellungen.',
'…슬롯을 채워. 빈 손은 죽음이다.':'…Fülle deine Slots. Leere Hände bedeuten den Tod.',
'…아직 살아있네. 좌클릭으로 저것들 쳐봐.':'…Noch am Leben. Versuche sie mit Linksklick zu treffen.',
'…운이 좋았을 뿐이야. 아마.':'…Nur Glück. Wahrscheinlich.',
'…치는 건 할 줄 아네. 피하는 건?':'…Weißt wie man trifft. Und ausweichen?',
'…힘을 골라라. 전부 가질 순 없다.':'…Wähle deine Stärke. Man kann nicht alles haben.',
'골고루 안 돼! 하나로 밀어!':'Keine Stats verteilen! Auf einen setzen!',
'그로기 터지면 1.5배!':'Taumelnd = 1,5-facher Schaden!',
'길이 열렸다.':'Der Pfad ist offen.',
'나머진 전부 우클릭 패링 가능!':'Alles andere kann mit Rechtsklick pariert werden!',
'나머진 전부 우클릭!':'Alles andere — Rechtsklick!',
'다섯 번 연속! 내가 본 인간 중 최고!':'Fünfmal hintereinander! Bester Mensch den ich je gesehen habe!',
'다음엔 죽지 마!':'Stirb beim nächsten Mal nicht!',
'더블탭 전격이동으로 탈출하라.':'Doppeltippen zum Ausweichen und Entkommen.',
'소환수 왔어! 먼저 처리해야 해!':'Beschwörungen kommen! Erst eliminieren!',
'스킬 없으면 방향키 연타뿐이야.':'Keine Fähigkeit? Einfach die Richtungstasten spammen.',
'신기록!! 스트리머한테 보내!':'Neuer Rekord!! Schick es einem Streamer!',
'아이템 넘쳐! 우리가 주워줄게!':'Tasche voll! Wir sammeln die Sachen für dich auf!',
'안 죽고 깼어! 진짜 천재 맞네!':'Ohne zu sterben abgeschlossen! Echtes Genie!',
'앞으로 가자~':'Vorwärts~',
'우리가 해냈어! 다음 챕터 가자!':'Wir haben es geschafft! Zum nächsten Kapitel!',
'일반 모드! 편하게 즐기자!':'Normalmodus! Genießen wir es entspannt!',
'자원이 반이다. F키로 회복해.':'Ressourcen bei der Hälfte. F drücken um zu erholen.',
'잡힌다! 옆으로 빠져!':'Werde gegriffen! Zur Seite bewegen!',
'장비 분해해! 쓰레기도 악의!':'Ausrüstung zerlegen! Sogar Schrott gibt Bosheit!',
'전부 다 잡았어! 우리가 지옥의 왕이야!':'Alle erwischt! Wir sind die Könige der Hölle!',
'좋은 거 나왔다! TAB!':'Gute Beute gefallen! TAB!',
'죽기 직전에 죽이다니! 멋져!':'Kurz vor dem Tod töten! Großartig!',
'체력 반 남았어! 물약 마실 타이밍!':'Halbe HP übrig! Zeit, einen Trank zu trinken!',
'큰 거 온다! 도망쳐!':'Großer Angriff kommt! Lauf!',
'패링으로 돌려주고, Q 보호막도 써!':'Parieren zum Reflektieren, und auch Q-Schild nutzen!',
'패턴이 빨라졌어!':'Muster wurden schneller!',
'한 대만 맞아도 죽어! 패링이든 회피든!!':'Ein Treffer und du stirbst! Parieren oder ausweichen!!',
'한 방이면 죽어! 도망쳐!!':'Ein Schuss tötet! Lauf!!',
'화염엔 빙결! 암전엔 암흑!':'Feuer → Frost! Leere → Schatten!',
'👻 유령총!':'👻 Geistergewehr!',
'기절! ':'Betäubt! ',
'── 2장 - 벌레굴 ──':'── Kap. 2 - Wurmnest ──',
'── 4장 - 화염지대 ──':'── Kap. 4 - Flammenöde ──',
'── 6장 - 사도마굴 ──':'── Kap. 6 - Schlund des Apostels ──',
'── 공통 ──':'── Allgemein ──',
'맞아서 사망':'Tod durch Treffer',
'강화':'Verstärken',
'합체 스킬로 통합됨':'In Fusionsskill integriert',
'처치':'Kills',
'유령불꽃 OFF':'Geisterflamme AUS',
'슬롯':'Slot',
'필살기':'Ultimativer Skill',
'연사 해제':'Schnellfeuer AUS',
'⏳⚡ 시간걸음!':'⏳⚡ Zeitschritt!',
'블룸 효과':'Bloom-Effekt',
'잔상 트레일':'Nachbild-Spur',
'슬래시 이펙트':'Hieb-Effekt',
'후처리 효과':'Nachbearbeitung',
'사망 이펙트':'Todeseffekt',
'동적 조명':'Dynamische Beleuchtung',
'횃불 조명 (어둠)':'Fackelbeleuchtung (Dunkel)',
'앰비언트 파티클':'Umgebungspartikel',
'안개 효과':'Nebeleffekt',
'필름 그레인':'Filmkorn',
'캐릭터 외곽선':'Charakterumriss',
'리롤':'Neu würfeln',
'물약':'Trank',
'으로 탈출!':'zum Entkommen!',
'Shift 작살':'Shift Harpune',
'더블탭 전격이동':'Doppeltippen — Blitz-Dash',
'Ctrl 유령걸음':'Ctrl Geisterschritt',
'Ctrl 얼음보주':'Ctrl Eisorb',
'🔴화염→빙결 2배 | 🔵빙결→화염 2배 | ⚪물리=중립 | 악마 처치 시 악의 영혼 드롭':'🔴Feuer→Eis 2× | 🔵Eis→Feuer 2× | ⚪Phys=Neutral | Töte Dämonen für Bosheitseelen',
  '미구현':'N/A',
  '스탯 총량':'Stat-Gesamtwerte',
  '장비':'Ausrüst.',
  '공속':'AngrTmp',
  '크리':'Krit',
  '크리뎀':'KritSch',
  '근성':'Zähigkeit',
  '종합 지표':'Übersicht',
  '근접 DPS':'Nahkampf DPS',
  '공격력×공속×크리':'ATK×Tmp×Krit',
  '활 DPS':'Bogen DPS',
  '마법 DPS':'Magie DPS',
  '유효 HP (EHP)':'Eff. HP (EHP)',
  '쉴드':'Schild',
  '장비 파워':'Ausrüst. Stärke',
  '근접 공격력':'Nahkampf ATK',
  '기본':'Basis',
  '무기':'Waffe',
  '패시브':'passiv',
  '활 공격력':'Bogen ATK',
  '정밀':'Präzision',
  '마법 공격력':'Magie ATK',
  '왕관':'Krone',
  '마력':'Arkanum',
  '공격속도':'Angriffsgeschw.',
  '크리티컬':'Kritisch',
  '데미지':'Sch',
  '확률':'Rate',
  '어픽스':'Affix',
  '레거시':'Vermächtnis',
  '추가뎀':'Bonus-Schaden',
  '패링 카운터뎀':'Parierkonter-Sch',
  '우클공속':'RMT-Tempo',
  '무지개탄DR':'Regenbogen-DR',
  '포이즈파괴':'Haltungsbruch',
  '방어관통':'Rüstungsdurchdr.',
  '관통력':'Durchdringung',
  '속성':'Elemente',
  '무기속성':'Waffen-Elem.',
  '독':'Gift',
  '초':'s',
  '암흑저주':'Dunkler Fluch',
  '원소집중':'Elem. Fokus',
  '원소전환':'Elem. Konvert.',
  '방어':'Verteidigung',
  '물리방어':'Phys. Vert.',
  '감소':'Reduz.',
  '캡':'Limit',
  '장갑':'Handschuhe',
  '바지':'Hose',
  '속성방어':'Elem. Vert.',
  '목걸이':'Halskette',
  '반지1':'Ring1',
  '반지2':'Ring2',
  '반사':'Reflektion',
  '가시':'Dornen',
  '배리어':'Barriere',
  '보호막 흡수':'Schildabsorption',
  '속성 저항':'Elem. Widerstand',
  'CC저항':'CC-Widerstand',
  '생존':'Überleben',
  '장비HP':'Ausrüst. HP',
  '임플':'Impl.',
  '에너지쉴드':'Energieschild',
  '리젠':'Regen',
  '스태미나':'Ausdauer',
  '성장':'Wachstum',
  'MP%어픽스':'MP%-Affix',
  '이동속도':'Bewegungsgeschw.',
  '한방캡':'Einschlag-Limit',
  '최대HP의33%':'33% Max HP',
  '비용/효율':'Kosten/Eff',
  '근접ST':'Nahkampf ST',
  '활ST':'Bogen ST',
  '마법MP':'Magie MP',
  '작살사거리':'Harpun-Reichweite',
  '기동게이지':'Schub-Anzeige',
  '쿨감':'KZ-Reduz',
  '쇠뇌뎀':'Armbrust-Schaden',
  '쇠뇌공속':'Armbrust-Geschw',
  '기타':'Sonstiges',
  '물약쿨':'Trank-CD',
  '회복+':'Heilung+',
  '드롭':'Drops',
  '경험치+':'EXP+',
  '골드+':'Gold+',
  '기동:칼날개':'Schub:Klinge',
  '기동:전폭':'Schub:Angriff',
  '기동:기습':'Schub:Hinterhalt',
  '충전스킬':'Aufladen-Skill',
  '사슬게이지':'Ketten-Anzeige',
  '특수 효과':'Spezialeffekte',
  '처치뎀+':'Kill-Schaden+',
  '위기뎀+':'Krisen-Schaden+',
  '피격반격':'Treffer-Konter',
  '풍요(적HP≥70%뎀+)':'Fülle(HP≥70%+)',
  '약자포식(적HP≤30%뎀+)':'Räuber(HP≤30%+)',
  '패링폭발':'Parier-Burst',
  '체간파괴+':'Haltungsbruch+',
  '콤보뎀+':'Kombo-Schaden+',
  '작살뎀+':'Harpun-Schaden+',
  '스킬뎀+':'Skill-Schaden+',
  '패리+':'Parieren+',
  '체인':'Kette',
  '정화':'Reinigung',
  '회':'×',
  '불굴':'Zähigkeit',
  '신성력':'Heilige Kraft',
  '악마력(부활력)':'Dämonenkraft',
  '자연':'Natur',
  '악마성':'Dämonie',
  '인간성':'Menschlichkeit',
  '전투 통계':'Kampfstatistiken',
  '핵터':'Hecter',
'디로이':'Deroy',
'물리 ATK +1, MAX HP +5, HP리젠 +0.002':'Phys. ATK +1, MAX HP +5, HP Regen +0.002',
'석궁 ATK +1, 공격속도 +0.05%, MAX ST +2, ST리젠 +0.005, 회피 +0.05%':'Bogen ATK +1, Angriffsgeschw. +0.05%, MAX ST +2, ST Regen +0.005, Ausweichen +0.05%',
'마법 ATK +1, MAX MP +2, MP리젠 +0.005, MAX 쉴드 +5':'Magie ATK +1, MAX MP +2, MP Regen +0.005, MAX Schild +5',
'크리확률 +0.025%, 크리뎀 +0.2%, 드롭률 +0.15%':'Krit. Chance +0.025%, Krit. Schaden +0.2%, Droprate +0.15%',
'근접뎀 +15%, ST비용 -4%/lv (최대-40%)':'Nahkampfschaden +15%, ST-Kosten -4%/Lv (max -40%)',
'작살 사거리 +2%/lv, 기동게이지 회복 +3%/lv':'Harpunen-Reichweite +2%/Lv, Mobilitätsgauge +3%/Lv',
'카운터뎀 +50%/lv, 우클릭 공속 +10%/lv, 무지개탄 피해감소 +10%/lv (최대50%)':'Gegenschaden +50%/Lv, Rechtsklick-Angriffsgeschw. +10%/Lv, Regenbogenkugel-Schadensreduktion +10%/Lv (max 50%)',
'마법뎀 +15%, MP비용 -4%, 시전속도 +8%/lv':'Magieschaden +15%, MP-Kosten -4%, Zauberwirkungsgeschw. +8%/Lv',
'투사체뎀 +15%, 공속 +10%, 사거리 +8%, ST비용 -4%/lv':'Projektilschaden +15%, Angriffsgeschw. +10%, Reichweite +8%, ST-Kosten -4%/Lv',
'보호막 흡수 +2%/lv (기본70→최대90%), 보호막 중 HP리젠 +0.1%/lv':'Schildabsorption +2%/Lv (Basis 70→max 90%), HP Regen mit Schild +0.1%/Lv',
'HP/ST리젠 +3%/lv, 물약쿨 -3%/lv':'HP/ST Regen +3%/Lv, Trankabklingzeit -3%/Lv',
'크리률 +2%, 크리뎀 +8%/lv':'Krit. Chance +2%, Krit. Schaden +8%/Lv',
'아이템 드롭률 +8%/lv':'Droprate +8%/Lv',
'투사체 관통률 +5%/lv, 관통횟수 +1/lv, 관통뎀감소 완화':'Projektildurchschlagsrate +5%/Lv, Durchschlagsanzahl +1/Lv, Schadensabfall Durchschlag reduziert',
'MP리젠 +3%/lv, 쉴드리젠 +3%/lv, 쉴드쿨 -3%/lv':'MP Regen +3%/Lv, Schild Regen +3%/Lv, Schildabklingzeit -3%/Lv',
'자동쇠뇌 뎀 +5%/lv, 공속 +5%/lv':'Auto-Armbrust-Schaden +5%/Lv, Angriffsgeschw. +5%/Lv',
'물리뎀 +15%/lv, HP +3%/lv, ST소모 -5%/lv':'Physischer Schaden +15%/Lv, HP +3%/Lv, ST-Verbrauch -5%/Lv',
'적에게 약점노출 디버프. 직접 공격 시 스택+1, 스택당 피격뎀 +3%. 최대 Lv×5 중첩 (1렙5, 10렙50). 초당 20% 감소, 5초 미피격 시 리셋. DOT/장판 제외':'Schwächeanfälligkeits-Debuff auf Feinden. Direktangriff +1 Stapel, +3% erlittener Schaden/Stapel. Max Lv×5 (Lv1=5, Lv10=50). -20%/s, Reset nach 5s ohne Angriff. DOT ausgenommen',
'물리→쉴드 패널티 관통 +5%/lv (기본10%, 10lv=60%)':'Physisch→Schild-Strafpenetration +5%/Lv (Basis 10%, Lv10=60%)',
'마법→HP 패널티 관통 +5%/lv (기본10%, 10lv=60%)':'Magie→HP-Strafpenetration +5%/Lv (Basis 10%, Lv10=60%)',
'적 HP 70%↑: 뎀+20%/lv, 회복력+5%/lv (합연산)':'Feind HP≥70%: Schaden+20%/Lv, Heilung+5%/Lv (additiv)',
'적HP 30%↓: 뎀+20%/lv. 내HP 30%↓: 회복력+10%/lv, 이속+5%/lv (합연산)':'Feind HP≤30%: Schaden+20%/Lv. Eigene HP≤30%: Heilung+10%/Lv, Bewegungsgeschw.+5%/Lv (additiv)',
'DOT 틱뎀 +15%/lv, DOT 지속시간 +10%/lv, DOT 축적률 +5%/lv':'DOT-Schaden +15%/Lv, DOT-Dauer +10%/Lv, DOT-Aufbaurate +5%/Lv',
'MP +50/lv, MP회복 +1%/lv':'MP +50/Lv, MP Regen +1%/Lv',
'ST +50/lv, ST회복 +1%/lv':'ST +50/Lv, ST Regen +1%/Lv',
'악의 드롭 +8%/lv':'Boshaftigkeits-Drop +8%/Lv',
'HP +300/lv':'HP +300/Lv',
'DEF +20/lv':'DEF +20/Lv',
'엘리트/보스 추가뎀 +10%/lv':'Zusatzschaden Elite/Boss +10%/Lv',
'부활력 -10/lv, 전체 데미지 +5%/lv, HP/MP/ST +100/lv':'Wiederbelebungskraft -10/Lv, Gesamtschaden +5%/Lv, HP/MP/ST +100/Lv',
'부활확률 +2%/lv, 부활HP +5%/lv, 부활쿨 -30초/lv':'Wiederbelebungschance +2%/Lv, Wiederbelebungs-HP +5%/Lv, Wiederbelebungs-CD -30s/Lv',
// --- Phase 37: skill desc ---
'핵심 광역기 — 먼저 배워서 정리력 확보':'Core AoE — learn first for mob clearing',
'악의 사냥 + 보호자 → 합체: 칼날 해방':'Malice Hunt + Guardian → Fuse: Blade Liberation',
'폭독혈 추가 → 합체: 독혈 해방 (칼날+독)':'Plague Burst → Fuse: Plague Liberation (blade+poison)',
'충돌+화염 → 합체: 사슬기동 (무적이동 핵심)':'Impact+Flame → Fuse: Chain Breach (invincible dash core)',
'사슬 체인 확장 → 기동:파쇄/기동:전폭':'Chain expansion → Slam/Thunder combos',
'필살기 1개 선택! 신성폭발(넉백) / 블랙(흡인) / 용암(화상) / 처형(보스킬)':'Pick 1 ultimate! Holy Blast(knockback) / Black Star(pull) / Lava(burn) / Execution(boss kill)',
'멸살광선+만화방창+원소추적탄+전격이동 → 합체: 추적빔':'Omni Beam+Barrage+Elem Missile+Blink → Fuse: Tracking Beam',
'회전참+기폭+대왕치기 → 합체: 지진폭풍':'Whirlwind+Detonate+Giant Slam → Fuse: Slam Storm',
'칼등치기 + 칼등날개 → 합체: 처내기 강화':'Blade Parry + Shield Wing → Fuse: Parry Enhanced',
'해골무덤 + 악의폭풍 → 합체: 해골번개':'Bone Wall + Malice Storm → Fuse: Bone Lightning',
'폭풍소환 + 얼음보주 → 합체: 얼음폭풍':'Malice Mortar + Ice Orb → Fuse: Ice Mortar',
'유령화 이동 + 전기 폭발':'Ghost phase movement + electric burst',
'회복 + 구속 → 합체: 결계의 영역':'Recovery + Prison → Fuse: Ward Domain',
'지진폭풍+추적암전 → 6단합체: 폭풍빔':'Slam Storm → 6-Fuse: Storm Beam',
'아이스스톰 추가 → 합체: 신성빙결':'Ice Storm → Fuse: Holy Ice',
'암흑기둥 + 가시덫 → 합체: 기둥가시. 대왕치기2는 기둥강타/지옥강타용':'Dark Pillar + Spike Trap → Fuse: Pillar Spike. Giant Slam 2 for Pillar Slam/Inferno Slam',
'기동칼날개 추가 → 5단합체: 기동:칼날개':'Chain Bladewing → 5-Fuse: Maneuver:Bladewing',
'STR 스케일. 3회 충전 + Lv3마다 사거리 1단계↑(최대4단). 이동 중 무적, 통과 적에 데미지+그로기 (쿨 5초)':'STR scale. 3 stocks + range tier up every Lv3 (max 4). Invincible while moving, DMG+groggy on pass-through (CD 5s)',
'INT 스케일. 이동 경로에 화염길 생성(3초 DOT). 통과 적 화상. MP 소모. 합체 시 착지 폭발':'INT scale. Fire trail on dash path (3s DOT). Burns passed enemies. MP cost. Fuse: landing explosion',
'5초간 유령화 — 무적+이동. 통과한 적/탄막 수만큼 종료 시 암전 폭발(+10%/회) + 전기줄기 방사(3회 체인). 카운트 캡=Lv×5(최대50). 쿨 20초. Lv당 뎀+15% 범위+10':'5s ghost form — invincible+move. Blackout explosion on end (+10%/enemy passed) + lightning arc (3 chains). Count cap=Lv×5 (max 50). CD 20s. Per Lv DMG+15% range+10',
'[이동기] 방향키 더블탭으로 발동. 경직/기절 중에도 탈출 가능. 500유닛 순간이동, 무적(15프레임). MP(10+Lv×5). 1렙10충전, 렙당+1. 쿨 8초→Lv당-0.5초(최소3초). 착지 시 전류장판(10초+Lv×0.5초): INT 틱뎀 + 방어력↓(1렙10%, 렙당+5%, 캡50%)':'[Mobility] Double-tap to activate. Escapes stagger/stun. 500-unit blink, invincible 15f. MP(10+Lv×5). Lv1=10 stocks, +1/Lv. CD 8s→-0.5s/Lv (min 3s). Landing shock field(10s+Lv×0.5s): INT tick DMG + DEF↓(Lv1=10%, +5%/Lv, cap 50%)',
'좌클 스킬: 기본공격에 3단 콤보 초승달 검기 추가. ST 10+Lv당2. Lv당 뎀+10% 거리+15px':'LMB skill: adds 3-hit crescent ki blade combo to basic attack. ST 10+2/Lv. Per Lv DMG+10% range+15px',
'[기본: E] 어둠 마법 오브 발사. 범위폭발. 넉백 0.5%. Lv당 크기+50% (뎀은 _skMul 계수 적용)':'[Default: E] Dark magic orb fired. AoE explosion. Knockback 0.5%. Per Lv size+50% (DMG uses _skMul)',
'무기 홀드 → 전진 회전 공격. 360도 광역, ST 지속소모. Lv당 범위+5 뎀+5%':'Hold weapon → forward spin attack. 360° AoE, continuous ST drain. Per Lv range+5 DMG+5%',
'패링 3초 홀드 → 흡수 데미지 광역 폭발. Lv당 범위+15 (1렙150, 10렙285)':'Parry 3s hold → absorbed DMG AoE explosion. Per Lv range+15 (Lv1: 150, Lv10: 285)',
'우클 처내기 강화. Lv당 반사 데미지 +10%. 홀드 시 연사':'RMB swipe enhanced. Per Lv reflect DMG +10%. Hold for rapid fire',
'[고정: T 자동] 물리 바늘 3방향 3발 발사. 관통 없음':'[Fixed: T auto] 3 physical needles 3-way spread. No pierce',
'[고정: E] 1발 직선 레이저. +만화방창 → 만화광선(3발 꽈배기). +원소추적탄 → 추적암전(6발 유도)':'[Fixed: E] 1 straight laser. +Barrage → Omni Beam (3 spiral). +Elem Seeker → Homing Dark (6 homing)',
'E탭 마법을 6원소 유도 미사일로 변경. 곡선 궤적으로 적을 추적. 레벨당 사거리+20 (뎀은 _skMul 계수 적용)':'Changes E-tap magic to 6-element homing missiles. Curved trajectory tracking enemies. Per Lv range+20 (DMG uses _skMul)',
'3초마다 악의 구체 생성(1렙 2개). 몸에 밀착하여 적 투사체를 자동 방어(파괴). 레벨당 구체+1':'Spawns malice orbs every 3s (Lv1: 2 orbs). Orbits body, auto-blocks (destroys) enemy projectiles. Per Lv orb+1',
'유도 물리 칼날 1발 (악의30+ST50). 관통률 800+Lv×20+장비. 지속뎀 5초. 쿨 15초':'1 homing physical blade (malice 30 + ST 50). Pierce 800+Lv×20+gear. DOT 5s. CD 15s',
'어둠 소용돌이 소환 (마우스 조준 설치, MP 소모, 쿨 11초, INT 스케일링, 1렙 200범위 +30/렙, 5초 지속, 적 흡인)':'Summon dark vortex (mouse-aim placement, MP cost, CD 11s, INT scale, Lv1 range 200 +30/Lv, 5s duration, pulls enemies)',
'포격식 조준 → 원형 해골무덤 소환. 2스택 (15초/1충전, Lv10→3스택). 둘레에서 뼈가 솟아 공간을 감쌈. 솟을 때 데미지. 적/투사체 차단. 악의 12. Lv당 범위+5% 지속+0.3초':'Artillery-aim → circular bone tomb. 2 stocks (15s/charge, Lv10→3 stocks). Bones rise around perimeter. DMG on rise. Blocks enemies/projectiles. Malice 12. Per Lv range+5% duration+0.3s',
'오망성 시전 → 신성 빛기둥 대폭발. 범위 1500+Lv×100px. 범위 끝까지 넉백(주 성능). 거리감쇠 50%. 스턴 2초. Lv당 뎀+10%. (MP 30%, 쿨 120초)':'Pentagram cast → holy light pillar mega-explosion. Range 1500+Lv×100px. Full-range knockback (main feature). 50% distance falloff. Stun 2s. Per Lv DMG+10%. (MP 30%, CD 120s)',
'검은 오망성 소환. 7초(+Lv당0.5초) 강력 흡인 (데미지 없음, 순수 유틸). 범위 1500+Lv×100px. 흡인력 기본5+Lv당0.5. (MP 30%, 쿨 120초)':'Summon black pentagram. 7s (+0.5s/Lv) strong pull (no DMG, pure utility). Range 1500+Lv×100px. Pull force base 5+0.5/Lv. (MP 30%, CD 120s)',
'빨간 오망성 시전 → 범위 1500+Lv×100px 화염폭발+10초간 화상. 틱당 적 최대HP 1.75%(+Lv당+1.5%). 10초 20틱. 거리감쇠 30%. Lv당 초기뎀+10%. (MP 30%, 쿨 120초)':'Red pentagram cast → range 1500+Lv×100px fire explosion+10s burn. Per tick enemy maxHP 1.75%(+1.5%/Lv). 10s 20 ticks. 30% distance falloff. Per Lv initial DMG+10%. (MP 30%, CD 120s)',
'X키: 그로기 보스 전용. 보스 현재HP 20%(+2%/Lv) + 무기뎀×30(+21%/Lv, 20Lv=150배) + 보스HP 30% 순수뎀. 섬광 돌진 연출. HP/MP/ST 10% 소모. 쿨 5초':'X key: Groggy boss only. Boss current HP 20%(+2%/Lv) + weapon DMG×30(+21%/Lv, Lv20=150×) + boss HP 30% pure DMG. Flash dash. HP/MP/ST 10% cost. CD 5s',
'얼음 속에 들어가 무적 상태. 다시 누르면 파쇄 → 얼음칼날 48발 부채꼴 방사 (MP 40, 쿨 20초). Lv당 칼날+2 뎀+15%':'Enter ice — invincible. Re-press to shatter → 48 ice blades fan spread (MP 40, CD 20s). Per Lv blades+2 DMG+15%',
'[고정: T 자동] 초고속 바늘 연발. 1렙 2발, 5렙마다 +1발. 관통 없음. ST 8. 쿨 1.5초. Lv당 뎀+100%':'[Fixed: T auto] Ultra-fast needles burst. Lv1 2 shots, +1 per 5 levels. No pierce. ST 8. CD 1.5s',
'E홀드: 직선 관통 레이저 채널링. MP 8+Lv/초 지속소모. 폭160+(Lv×10)px, 사거리1200+Lv×80. 관통+감전. Lv당 뎀+21%':'E hold: Straight piercing laser channeling. MP 8+Lv/s drain. Width 160+(Lv×10)px, range 1200+Lv×80. Pierce+shock. Per Lv DMG+21%',
'E탭: 화염 유도빔 발사. MP10. 쿨1초(DEX 스케일). 100% 관통+유도+화상. Lv당 사거리+50 뎀+12%':'E tap: fire homing beam. MP 10. CD 1s (DEX scale). 100% pierce+homing+burn. Per Lv range+50 DMG+12%',
'E: 10초간 대지 진동. 범위 내 용암 기둥이 순차적으로 솟아올라 화상+틱 데미지. MP 100. 쿨 12초. Lv당 범위+10% 뎀+12%':'E: 10s ground tremor. Lava pillars rise sequentially in range — burn+tick DMG. MP 100. CD 12s. Per Lv range+10% DMG+12%',
'독혈 칼날 1발 발사: 관통률 기본 800+Lv×20 + 장비 bowPierce×300/패시브 pPierce×30 반영, +100 보정. 전염+마지막 적 처형. 감염 사망 시 폭발+연쇄 전염. 악의 15. 사거리 4000. 쿨 15초(Lv당-0.5초)':'Fire 1 poison-blood blade: base pierce rate 800+Lv×20 with bowPierce×300 and pPierce×30 scaling, plus +100 bonus. Plague+execute last enemy. Infected death → explosion+chain plague. Malice 15. Range 4000. CD 15s (-0.5s/Lv)',
'마우스 조준 설치. 쿨 20초. 화면 내 클릭 위치에 암전나선 (3초, 10틱, 틱당 100+Lv*20). Lv당 범위+22. 같은 지역 중복 불가':'Mouse-aim placement. CD 20s. Dark spiral at click pos (3s, 10 ticks, 100+Lv*20/tick). Per Lv range+22. No stacking same area',
'현재 위치에 9개 기둥 순차 발동. 5초간 악의 기둥을 소환하여 반경 내 적에게 지속 암전 데미지+감속. 범위 250+(Lv-1)×22. 대왕치기와 합체→기둥강타. 쿨 15초':'9 pillars activate sequentially at current pos. 5s dark pillars deal sustained dark DMG+slow to enemies in radius. Range 250+(Lv-1)×22. Fuses with Giant Slam → Pillar Strike. CD 15s',
'현재 위치에 회복의 영역 설치 (12초 지속). 땅 위: HP/MP/ST 초당+10 리젠 + 회복력 2배 + 쿨다운 속도 2배. 쿨 30초. Lv당 범위+20 지속+0.5초':'Place holy domain at current pos (12s duration). On ground: HP/MP/ST +10/s regen + 2x recovery + 2x CD speed. CD 30s. Per Lv range+20 duration+0.5s',
'범위 내 몬스터 부활력 -15%~30%(Lv1=15%, Lv10=30%). Lv1 범위400, Lv10 범위697. Lv당 범위+33. 쿨 30초. 지속 10초':'Monsters in range: revive power -15%~30%(Lv1=15%, Lv10=30%). Lv1 range 400, Lv10 range 697. Per Lv range+33. CD 30s. Duration 10s',
'마우스 조준 설치. 2스택 (15초/1충전, Lv10→3스택). 범위 내 빙결 저항 -50%, 빙결 게이지 급속 축적. 3초 지속. MP 40. Lv당 범위+22 축적+10%':'Mouse-aim placement. 2 stocks (15s/charge, Lv10→3 stocks). Freeze resist -50% in range, rapid freeze gauge buildup. 3s duration. MP 40. Per Lv range+22 buildup+10%',
'땅을 내리쳐 원형 진동파 발생(범위400). 일반몹에게 큰 포이즈 피해, 보스 체간 파괴에 강함. 회전기폭과 합체→지진폭풍!':'Slam ground → circular shockwave (range 400). High poise DMG to mobs, strong posture break vs bosses. Fuses with Whirlwind Detonate → Earthquake Storm!',
'땅을 내리쳐 원형 진동파 발생(범위400). 일반몹에게 큰 포이즈 피해, 보스 체간 파괴에 강함. 악의기둥과 합체→기둥강타!':'Slam ground → circular shockwave (range 400). High poise DMG to mobs, strong posture break vs bosses. Fuses with Dark Pillar → Pillar Slam!',
'사슬기동 중 E → 즉시 착지하며 화염폭발. 범위200~350 INT 스케일 화염 마법데미지+넉백. 이동거리에 비례해 데미지↑(최대 x4.0). MP 소모. Lv당 범위+16 뎀+12%':'During chain dash E → instant land with fire explosion. Range 200~350 INT scale fire magic DMG+knockback. DMG scales with travel distance (max x4.0). MP cost. Per Lv range+16 DMG+12%',
'사슬기동 중 우클릭 → 땅 내려찍기. 범위200~350 데미지x8 그로기x6. 이동거리 비례 최대x6. 일반몹 즉시 기절(5초), 보스 체간 대량 삭감. Lv당 범위+16 데미지+15% 그로기+15%':'During chain dash RMB → ground slam. Range 200~350 DMG x8 groggy x6. Distance scale max x6. Instant stun mobs (5s), massive boss posture break. Per Lv range+16 DMG+15% groggy+15%',
'[히든: 5성 dimRush 합체] 사슬기동 중 좌클릭 → 이동 중 전방 광역 베기+출혈. STR 스케일 물리데미지. 다단히트. Lv당 뎀+12% 범위+15':'[Hidden: 5-star dimRush fuse] During chain dash LMB → forward AoE slash+bleed while moving. STR scale physical DMG. Multi-hit. Per Lv DMG+12% range+15',
'[히든: 암전나선 합체] Q 홀드 시 보호막이 점점 커지며 HP 초당 10% 회복. 보호막 크기에 비례해 데미지 감소. MP 소모':'[Hidden: Dark Spiral fuse] Q hold: shield grows over time + HP 10%/s regen. DMG reduction scales with shield size. MP cost',
'[히든: 암전나선 합체] E로 조준, 클릭 설치. 에너지 쐐기를 지상에 꽂아 회전+데미지. MP100. 1차지 쿨10초. 5초+Lv당0.5초 지속. Lv당 거리+50':'[Hidden: Dark Spiral fuse] E to aim, click to place. Energy wedge planted on ground — rotates+DMG. MP 100. 1 charge CD 10s. 5s+0.5s/Lv duration. Per Lv range+50',
'[고정: 칼등치기 합체] 보유 시 칼등치기에 전방 충격파 자동 발동. 제자리 처내기. 쿨 5초. Lv당 뎀+12% 범위+20':'[Fixed: Blade Parry fuse] When owned, swipe auto-triggers forward shockwave. Stationary swipe. CD 5s. Per Lv DMG+12% range+20',
'현재 위치에 파쇄 영역 설치 (10초). 범위 내 적 물리방어력 -10%. 쿨 25초. Lv당 범위+22 효과+1% 지속+0.3초':'Place shatter domain at current pos (10s). Enemy phys DEF -10% in range. CD 25s. Per Lv range+22 effect+1% duration+0.3s',
'현재 위치에 침식 영역 설치 (10초). 범위 내 적 마법저항력 -10%. 쿨 25초. Lv당 범위+22 효과+1% 지속+0.3초':'Place corrosion domain at current pos (10s). Enemy magic resist -10% in range. CD 25s. Per Lv range+22 effect+1% duration+0.3s',
'현재 위치에 관통 영역 설치 (10초). 범위 내 적 투사체저항력 -10%. 쿨 25초. Lv당 범위+22 효과+1% 지속+0.3초':'Place pierce domain at current pos (10s). Enemy projectile resist -10% in range. CD 25s. Per Lv range+22 effect+1% duration+0.3s',
'현재 위치에 부활 영역 설치 (10초). 영역 안에서 부활력 +10%. 쿨 25초. Lv당 범위+22 효과+1% 지속+0.3초':'Place revival domain at current pos (10s). Revive power +10% inside zone. CD 25s. Per Lv range+22 effect+1% duration+0.3s',
'[고정: Space] 현재 위치에 가시덫 설치 (1렙 반경200, 10렙398). 슬로우 70%(+2%/Lv, 최대90%)+출혈. INT×magicRef×3(+10%/Lv). 악의 10, 쿨 10초. Lv당 범위+22':'[Fixed: Space] Place spike trap at current pos (Lv1 radius 200, Lv10 398). Slow 70%(+2%/Lv, max 90%)+bleed. INT×magicRef×3(+10%/Lv). Malice 10, CD 10s. Per Lv range+22',
'[고정: E, Lv300 해금] 유도 파란콩 50발 순차 발사 (5초간). MP 100(+1.5/Lv) 소모. 적 추적. 쿨 5초. Lv당 사거리+30 (뎀은 _skMul 계수 적용)':'[Fixed: E, unlock Lv300] 50 homing blue shots fired sequentially (over 5s). MP 100(+1.5/Lv) cost. Tracks enemies. CD 5s. Per Lv range+30 (DMG uses _skMul)',
'[히든: E, Lv700 해금] 홀드 시 3단계 차지 범위폭발 (0.5/1.0/1.5초). 범위 600/1000/1400px. 3단 만충 자동폭발. INT 스케일, 무속성':'[Hidden: E, unlock Lv700] Hold for 3-stage charge AoE explosion (0.5/1.0/1.5s). Range 600/1000/1400px. Stage 3 full charge auto-detonates. INT scale, no element',
'유령 허수아비를 소환하여 유도탄막 어그로를 끈다. 탄막을 흡수해 자원 축적 (기본 20개, Lv당+3). 1개당 HP/MP/ST 각 100. R키로 회수. 쿨 10초':'Summon phantom scarecrow to draw homing projectile aggro. Absorbs projectiles for resource buildup (base 20, +3/Lv). Per absorbed: HP/MP/ST +100 each. R key to retrieve. CD 10s',
'폭발 허수아비 설치. 탄막을 흡수하고 재입력 시 폭발! 1스택당 (INT마법뎀+탄막뎀)×10 마법데미지. 범위 250+흡수×25 (최대1000). 최대흡수 1렙20~20렙60. 쿨 10초':'Place explosive scarecrow. Absorbs projectiles, re-press to detonate! Per stack: (INT magic DMG + proj DMG)×10. Range 250+absorbed×25 (max 1000). Max absorb Lv1=20~Lv20=60. CD 10s',
'[선택: 1~4번, Lv500 해금] 현재 위치에 공성쇠뇌 터렛 설치. 재입력 시 철거. 설치 중 플레이어 석궁 사용 불가 (터렛만 발사). 데미지+50%, 공속+50%, 사거리+50%. ST 100. 쿨 10초. Lv당 뎀+5% 공속+5% 사거리+5%':'[Select: 1~4, unlock Lv500] Deploy siege crossbow turret at current pos. Re-press to dismantle. While deployed: player crossbow disabled (turret fires only). DMG+50%, ATK SPD+50%, range+50%. ST 100. CD 10s. Per Lv DMG+5% ATK SPD+5% range+5%',
'[Ctrl, Lv500 해금] 발동 시 3초 전 상태로 되돌린다. 위치/HP/MP/ST 완전 복원. Lv당 되감기+0.105초 (1렙 3초, 20렙 5초). MP 50(+5/Lv, 20렙150). 쿨 45초':'[Ctrl, unlock Lv500] Rewind to state from 3s ago. Restores position/HP/MP/ST. Per Lv rewind+0.105s (Lv1=3s, Lv20=5s). MP 50(+5/Lv, Lv20=150). CD 45s',
'[선택: 1~4번] 마우스 조준 → 전기창을 땅에 꽂는다. 5스택(12초/1충전, Lv10→6스택). 창끼리 600px 이내면 전류 아크 발생, 경로 위 적에게 감전 틱 데미지. MP 50. 지속 10초(+0.5초/Lv). Lv당 아크뎀+10%':'[Select: 1~4] Mouse aim → plant electric spear on ground. 5 stocks (12s/charge, Lv10→6). Spears within 600px create lightning arcs dealing shock tick DMG to enemies on path. MP 50. Duration 10s (+0.5s/Lv). Per Lv arc DMG+10%',
'성능 등급:':'Perf Grade:',
'벤치 FPS:':'Bench FPS:',
// --- CAT-82: skill panel labels ---
'스킬 정보':'Skill Info',
'타입':'Type',
'미습득':'Not Learned',
'SP 비용':'SP Cost',
'악의 비용':'Malice Cost',
'쿨다운':'Cooldown',
'요구 레벨':'Req. Lv',
'기본 참조뎀':'Base Reference',
'스탯 배율':'Stat Mult',
'패시브 배율':'Passive Mult',
'레벨 배율':'Skill Lv Mult',
'예상 평균 뎀':'Estimated Avg DMG',
'치명타':'Critical',
'치명타 확률':'Crit Rate',
'치명타 배율':'Crit Dmg',
'유효 배율':'Effective Mult',
'스킬 고유':'Skill Specific',
'1타 배율':'1-Hit Mult',
'2타 배율':'2-Hit Mult',
'3타 배율':'3-Hit Mult',
'레벨당 뎀':'Per Lv DMG',
'검기 거리':'Crescent Range',
'레벨당 거리':'Lv Range Bonus',
'ST/틱':'ST/Tick',
'레벨당 크기':'Per Lv Size',
'넉백':'Knockback',
'충전 시간':'Charge Time',
'레벨당 범위':'Per Lv Range',
'관통률':'Pierce Rate',
'지속뎀':'DOT Duration',
'무한':'Infinite',
'타격 형식':'AoE Type',
'진동파':'Shockwave',
'스태거':'Stagger',
'높음':'High',
'스톡':'Stocks',
'기둥 수':'Pillars',
'지속':'Duration',
'반경':'Radius',
'슬로우':'Slow',
'활':'Bow',
// --- CAT-83: affix desc labels ---
'독 DoT':'Poison DoT',
'화상 DoT':'Fire DoT',
'빙결 DoT+감속':'Ice DoT+Slow',
'연쇄전격':'Chain Lightning',
'저주(힐차단)':'Curse(Heal Block)',
'방어무시':'Armor Ignore',
'치명타율':'Crit Rate',
'스태거+':'Stagger+',
'체인타겟+':'Chain Target+',
'처치 후 뎀+':'Kill DMG+',
'크리폭발(ATK×)':'Crit Explode(ATK×)',
'원소뎀+':'Elem DMG+',
'공격속도+':'Atk Spd+',
'패리보너스+':'Parry Bonus+',
'추적콤보+10':'Track Combo+10',
'작살뎀+':'Harpoon DMG+',
'스킬뎀+':'Skill DMG+',
'쿨다운-':'CD-',
'방어력+':'DEF+',
'쉴드+':'Shield+',
'이동속도+':'Move Spd+',
'크리확률+':'Crit Rate+',
'크리배율+':'Crit Dmg+',
'화염저항':'Fire Res',
'빙결저항':'Ice Res',
'암전저항':'Lightning Res',
'암흑저항':'Dark Res',
'독저항':'Poison Res',
'전원소저항':'All Elem Res',
'물리DR':'Phys DR',
'반사%':'Reflect%',
'가시뎀':'Thorns DMG',
'배리어':'Barrier',
'CC저항':'CC Resist',
'위기뎀+':'Crisis DMG+',
'피격반격':'Hit Counter',
'패링폭발(ATK×)':'Parry Burst(ATK×)',
'체간파괴뎀+':'Poise Break DMG+',
'원소전환':'Elem Convert',
'상태이상해제':'Status Clear',
'불굴(1회생존)':'Tenacity(Survive×1)',
'부활(HP회복)':'Revive(HP Restore)',
'드롭률+':'Drop Rate+',
'경험치+':'EXP+',
'골드+':'Gold+',
'포션회복+':'Potion Heal+',
'사슬게이지+':'Chain Gauge+',
'부활억제':'Anti-Revive',
'부활력+':'Revival Pow+',
'부활쿨-':'Revival CD-',
'최대HP%+':'Max HP%+',
'HP리젠+':'HP Regen+',
'회복력+':'Heal Pow+',
'마법뎀+':'Magic DMG+',
'MP소비-':'MP Cost-',
'화염뎀%+':'Fire DMG%+',
'화염관통%':'Fire Pen%',
'적중화상':'On-Hit Burn',
'크리화폭':'Crit Fire Burst',
'화상지속+':'Burn Duration+',
'화염뎀보너스':'Fire DMG Bonus',
'빙결뎀%+':'Ice DMG%+',
'빙결관통%':'Ice Pen%',
'적중빙결':'On-Hit Freeze',
'크리빙폭':'Crit Ice Burst',
'빙결지속+':'Freeze Duration+',
'빙결뎀보너스':'Ice DMG Bonus',
'뇌전뎀%+':'Lightning DMG%+',
'뇌전관통%':'Lightning Pen%',
'적중감전':'On-Hit Shock',
'크리뇌폭':'Crit Lightning Burst',
'감전지속+':'Shock Duration+',
'뇌전뎀보너스':'Lightning DMG Bonus',
'암흑뎀%+':'Dark DMG%+',
'암흑관통%':'Dark Pen%',
'적중저주':'On-Hit Curse',
'크리암폭':'Crit Dark Burst',
'저주지속+':'Curse Duration+',
'암흑뎀보너스':'Dark DMG Bonus',
'독뎀%+':'Poison DMG%+',
'독관통%':'Poison Pen%',
'적중중독':'On-Hit Poison',
'크리독폭':'Crit Poison Burst',
'독지속+':'Poison Duration+',
'독뎀보너스':'Poison DMG Bonus',
'근접뎀%+':'Melee DMG%+',
'원거리뎀%+':'Ranged DMG%+',
'마법뎀%+':'Magic DMG%+',
'빔뎀%+':'Beam DMG%+',
'DoT뎀%+':'DoT DMG%+',
'투사체뎀%+':'Proj DMG%+',
'범위반경+':'AoE Radius+',
'근접크리+':'Melee Crit+',
'마법크리+':'Magic Crit+',
'석궁크리+':'Xbow Crit+',
'근접공속+':'Melee Spd+',
'석궁공속+':'Xbow Spd+',
'시전속도+':'Cast Spd+',
'전속성관통':'All Elem Pen',
'쉴드관통':'Shield Pen',
'방어력깎기':'Armor Shred',
'투사체속도+':'Proj Speed+',
'적중시화구':'On-Hit Fireball',
'적중시연쇄뇌격':'On-Hit Chain Lightning',
'적중빙결%':'On-Hit Freeze%',
'적중스턴%':'On-Hit Stun%',
'적중중독%':'On-Hit Poison%',
'적중출혈%':'On-Hit Bleed%',
'적중약화%':'On-Hit Weaken%',
'적중감속%':'On-Hit Slow%',
'적중표적%':'On-Hit Mark%',
'크리폭발(HP%)':'Crit Explode(HP%)',
'크리연쇄(HP%)':'Crit Chain(HP%)',
'크리빙결%':'Crit Freeze%',
'크리HP+':'Crit HP+',
'크리MP+':'Crit MP+',
'크리쉴드+':'Crit Shield+',
'피격방어+':'Hit DEF+',
'반격가시':'Counter Thorns',
'빙결파동%':'Ice Nova%',
'자동암흑막':'Auto Dark Shield',
'주기치유':'Periodic Heal',
'시체폭발%':'Corpse Explode%',
'회피뎀+':'Dodge DMG+',
'패링폭발%':'Parry Burst%',
'블록HP+':'Block HP+',
'블록MP+':'Block MP+',
'회전참뎀+':'Whirlwind DMG+',
'옴니빔뎀+':'Omni Beam DMG+',
'화구뎀+':'Fireball DMG+',
'미사일뎀+':'Missile DMG+',
'청탄뎀+':'Blue Shot DMG+',
'폭렬탄뎀+':'Blast Shot DMG+',
'지옥광선뎀+':'Hell Ray DMG+',
'악의폭풍뎀+':'Malice Storm DMG+',
'연쇄참뎀+':'Chain Slash DMG+',
'거인강타뎀+':'Giant Slam DMG+',
'유령보행뎀+':'Ghost Walk DMG+',
'악의박격뎀+':'Malice Mortar DMG+',
'화염오라뎀+':'Fire Aura DMG+',
'빙구뎀+':'Ice Orb DMG+',
'화염빔뎀+':'Fire Beam DMG+',
'악의사냥뎀+':'Malice Hunt DMG+',
'암흑기둥뎀+':'Dark Pillar DMG+',
'역병뎀+':'Plague DMG+',
'가시오라뎀+':'Spike Aura DMG+',
'연쇄돌격뎀+':'Chain Assault DMG+',
'회피확률+':'Dodge Rate+',
'회피쿨-':'Dodge CD-',
'쉴드%+':'Shield%+',
'쉴드리젠%+':'Shield Regen%+',
'쉴드쿨-':'Shield CD-',
'HP리젠%+':'HP Regen%+',
'ST리젠+':'ST Regen+',
'ST리젠%+':'ST Regen%+',
'MP리젠+':'MP Regen+',
'MP리젠%+':'MP Regen%+',
'화염DR':'Fire DR',
'빙결DR':'Ice DR',
'뇌전DR':'Lightning DR',
'암흑DR':'Dark DR',
'독DR':'Poison DR',
'전체DR':'All DR',
'엘리트DR':'Elite DR',
'스턴저항':'Stun Res',
'감속저항':'Slow Res',
'넉백저항':'KB Res',
'돌진거리+':'Dash Range+',
'돌진쿨-':'Dash CD-',
'전투이속+':'Combat MSpd+',
'비전투이속+':'Out-Combat MSpd+',
'습득범위+':'Pickup Range+',
'전스탯+':'All Stats+',
'적중자원+':'On-Hit Resource+',
'화염최대저항+':'Fire Max Res+',
'빙결최대저항+':'Ice Max Res+',
'뇌전최대저항+':'Lightning Max Res+',
'암흑최대저항+':'Dark Max Res+',
'독최대저항+':'Poison Max Res+',
'스킬쿨-':'Skill CD-',
'물약쿨-':'Potion CD-',
'강화성공+':'Craft Rate+',
'악의획득+':'Malice Gain+',
'악마화뎀+':'Demon DMG+',
'악마화DR':'Demon DR',
'영혼수확+':'Soul Harvest+',
'생명흡혈%':'Life Leech%',
'과치유→쉴드':'Overheal→Shield',
'만마나뎀+':'Full MP DMG+',
'이동DR':'Move DR',
'정지뎀+':'Stationary DMG+',
'회피후뎀+':'After Dodge DMG+',
'패링쉴드+':'Parry Shield+',
'콤보보너스+':'Combo Bonus+',
'HP≥70%뎀+':'HP≥70% DMG+',
'적HP≤30%뎀+':'Foe HP≤30% DMG+',
'HP100%뎀+':'HP100% DMG+',
'HP≤35%뎀+':'HP≤35% DMG+',
'적HP≤20%뎀+':'Foe HP≤20% DMG+',
'근접뎀+':'Melee DMG+',
'원거리뎀+':'Ranged DMG+',
'스턴적뎀+':'vs Stunned DMG+',
'빙결적뎀+':'vs Frozen DMG+',
'화상적뎀+':'vs Burning DMG+',
'중독적뎀+':'vs Poisoned DMG+',
'저주적뎀+':'vs Cursed DMG+',
'감속적뎀+':'vs Slowed DMG+',
'보스뎀+':'Boss DMG+',
'엘리트뎀+':'Elite DMG+',
'일반몹뎀+':'Mob DMG+',
'선제뎀+':'First Strike DMG+',
'물리흡혈%':'Phys Leech%',
'마나흡수%':'Mana Leech%',
'ST흡수%':'ST Leech%',
'적중HP+':'On-Hit HP+',
'처치HP+':'On-Kill HP+',
'처치MP+':'On-Kill MP+',
'처치ST+':'On-Kill ST+',
'처치시폭발':'On-Kill Explode',
'처치이속+':'On-Kill MSpd+',
'HP≥70%방어+':'HP≥70% DEF+',
'HP≤50%이속+':'HP≤50% MSpd+',
'DoT피해감소':'DoT DMG Reduce',
'보스피해감소':'Boss DMG Reduce',
'근접피해감소':'Melee DMG Reduce',
'원거리피해감소':'Ranged DMG Reduce',
'처치HP회복':'On-Kill HP Restore',
'처치쉴드회복':'On-Kill Shield Restore',
'ST소비-':'ST Cost-',
'HP≥70%공격+':'HP≥70% ATK+',
'HP≤35%흡혈':'HP≤35% Leech',
'보스추가뎀':'vs Boss DMG+',
'엘리트추가뎀':'vs Elite DMG+',
'공격력+':'ATK+',
'크리뎀+':'Crit DMG+',
// --- CAT-84/85/86: affix names + implicit + legendary ---
'물리방패의':'Physical Shield',
'지속의':'Stamina',
'마나의':'Mana',
'원소수호의':'Elem Guard',
'행운의':'Fortune',
'근성의':'Grit',
'풍요의':'Abundance',
'약자포식의':'Predator',
'만혈의':'Full Life',
'사선의':'Low Life',
'처형의':'Execute',
'근접살의':'Melee DMG',
'원거리의':'Ranged',
'경직파의':'Stagger Break',
'동파의':'Freeze Strike',
'연소의':'Burning',
'맹독살의':'Venom Slayer',
'저주살의':'Curse Slayer',
'구속의':'Binding',
'왕살의':'Boss Slayer',
'정예살의':'Elite Slayer',
'군살의':'Mob Slayer',
'선제의':'First Strike',
'흡혈의':'Vampirism',
'흡마의':'Mana Leech',
'흡정의':'Stamina Leech',
'타격재생의':'Hit Regen',
'처치회복의':'Kill Recovery',
'처치흡마의':'Kill Mana Leech',
'처치활력의':'Kill Stamina',
'처치폭발의':'Kill Explosion',
'처치질주의':'Kill Sprint',
'건강방어의':'Healthy Defense',
'중상보호의':'Wounded Shield',
'위기질주의':'Crisis Sprint',
'지속피해방어의':'DoT DR',
'왕피해방어의':'Boss DMG DR',
'근접방어의':'Close DR',
'원거리방어의':'Ranged DR',
'처치생명의':'Kill HP',
'처치수호의':'Kill Shield',
'화염강화의':'Fire Amp',
'화염관통의':'Fire Pierce',
'발화의':'Ignition',
'화염폭발의':'Fire Burst',
'맹화의':'Blaze',
'화염의힘':'Fire Power',
'빙결강화의':'Ice Amp',
'빙결관통의':'Ice Pierce',
'동결의':'Freeze',
'빙결폭발의':'Ice Burst',
'영빙의':'Permafrost',
'빙결의힘':'Ice Power',
'뇌전강화의':'Thunder Amp',
'뇌전관통의':'Thunder Pierce',
'감전의':'Shock',
'뇌전폭발의':'Thunder Burst',
'낙뢰의':'Thunderbolt',
'뇌전의힘':'Thunder Power',
'암흑강화의':'Dark Amp',
'암흑관통의':'Dark Pierce',
'침식의':'Erosion',
'암흑폭발의':'Dark Burst',
'심연의':'Abyss',
'암흑의힘':'Dark Power',
'맹독강화의':'Venom Amp',
'독관통의':'Poison Pierce',
'중독의':'Poisoning',
'독폭발의':'Poison Burst',
'맹독지속의':'Venom Duration',
'독의힘':'Poison Power',
'격투의':'Melee',
'원사의':'Ranged Shot',
'주술의':'Spell',
'광선의':'Beam',
'탄도의':'Ballistic',
'확산의':'AoE Radius',
'근접회심의':'Melee Crit',
'마법회심의':'Spell Crit',
'사격회심의':'Ranged Crit',
'근접쾌속의':'Melee Speed',
'사격쾌속의':'Ranged Speed',
'영창의':'Chanting',
'전속성관통의':'All-Elem Pierce',
'쉴드파괴의':'Shield Bypass',
'갑옷분쇄의':'Armor Shred',
'탄속의':'Proj Speed',
'화구발사의':'Fireball Launch',
'연쇄뇌격의':'Chain Lightning',
'동결타의':'Freeze Strike',
'경직타의':'Stagger Strike',
'독침의':'Poison Sting',
'출혈의':'Bleed',
'약화의':'Weakness',
'둔화의':'Slow',
'표적의':'Marking',
'회심폭발의':'Crit Explosion',
'회심연쇄의':'Crit Chain',
'회심빙결의':'Crit Freeze',
'회심치유의':'Crit Heal',
'회심영력의':'Crit Mana',
'회심수호의':'Crit Shield',
'피격강화의':'Hit Boost',
'반격가시의':'Counter Thorns',
'빙결파동의':'Ice Nova',
'암흑보호의':'Dark Shield',
'치유파동의':'Heal Pulse',
'시체폭발의':'Corpse Explosion',
'회피반격의':'Dodge Counter',
'패링폭파의':'Parry Shatter',
'블록치유의':'Block Heal',
'블록영력의':'Block Mana',
'회전참강화':'Spin Slash Boost',
'옴니빔강화':'Omni Beam Boost',
'화구강화':'Fireball Boost',
'미사일강화':'Missile Boost',
'청탄강화':'Blue Shot Boost',
'폭렬탄강화':'Burst Shot Boost',
'지옥광선강화':'Hellray Boost',
'악의폭풍강화':'Malice Storm Boost',
'연쇄참강화':'Chain Slash Boost',
'거인강타강화':'Giant Slam Boost',
'유령보행강화':'Ghost Walk Boost',
'악의박격강화':'Malice Mortar Boost',
'화염오라강화':'Fire Aura Boost',
'빙구강화':'Ice Orb Boost',
'화염빔강화':'Fire Beam Boost',
'악의사냥강화':'Malice Hunt Boost',
'암흑기둥강화':'Dark Pillar Boost',
'역병강화':'Plague Boost',
'가시오라강화':'Thorn Aura Boost',
'연쇄돌격강화':'Chain Assault Boost',
'회피의':'Evasion',
'회피쿨감의':'Dodge CD Red',
'수호력의':'Shield Power',
'수호재생의':'Shield Regen',
'수호쿨감의':'Shield CD Red',
'재생력의':'Regen Power',
'활력재생의':'Stamina Regen',
'마력재생의':'Mana Regen',
'화염보호의':'Fire Shield',
'빙결보호의':'Ice Shield',
'뇌전보호의':'Thunder Shield',
'해독의':'Antidote',
'만물보호의':'All Protection',
'정예보호의':'Elite Shield',
'경직저항의':'Stagger Resist',
'빙결저항의':'Freeze Resist',
'감속저항의':'Slow Resist',
'넉백저항의':'Knockback Resist',
'돌진거리의':'Dash Range',
'돌진쿨감의':'Dash CD Red',
'전투질주의':'Combat Sprint',
'평화질주의':'Peace Sprint',
'습득범위의':'Pickup Radius',
'힘의':'Strength',
'민첩의':'Dexterity',
'지능의':'Intelligence',
'만능의':'Versatile',
'지구력의':'Max Stamina',
'마나력의':'Mana Power',
'타격자원의':'Hit Resource',
'화염한계의':'Fire Cap',
'빙결한계의':'Ice Cap',
'뇌전한계의':'Thunder Cap',
'암흑한계의':'Dark Cap',
'독한계의':'Poison Cap',
'스킬쿨감의':'Skill CD Red',
'물약쿨감의':'Potion CD Red',
'장인의':'Craftsmanship',
'탐욕의':'Greed',
'수련의':'Training',
'수집의':'Gathering',
'악마의힘':'Demon Power',
'악마보호의':'Demon Shield',
'영혼수확의':'Soul Harvest',
'생명흡수의':'Life Absorption',
'과치유수호의':'Overheal Shield',
'만마력의':'Full Mana DMG',
'이동방어의':'Moving DR',
'정지공세의':'Stationary Boost',
'회피공세의':'Post-Dodge Boost',
'패링보호의':'Parry Shield',
'콤보폭발의':'Combo Burst',
'물리타격의':'Phys Strike',
'화염타격의':'Fire Strike',
'빙결타격의':'Ice Strike',
'뇌전타격의':'Thunder Strike',
'암흑타격의':'Dark Strike',
'독타격의':'Poison Strike',
'최소공격의':'Min ATK',
'최대공격의':'Max ATK',
'전투력의':'Combat Power',
'무기사거리의':'Weapon Range',
'활사거리의':'Bow Range',
'이중타의':'Double Strike',
'다중발사의':'Multi Shot',
'관통횟수의':'Pierce Count',
'관통유지의':'Pierce Keep',
'연쇄유지의':'Chain Keep',
'범위확장의':'Splash Range',
'범위피해의':'Splash DMG',
'돌진공격의':'Dash ATK',
'반격공격의':'Counter ATK',
'후방타의':'Backstab',
'침식가속의':'Erosion Speed',
'출혈지속의':'Bleed Duration',
'마법타격의':'Magic Strike',
'주문증폭의':'Spell Amp',
'연살뎀의':'Kill Streak DMG',
'연살속의':'Kill Streak Speed',
'기세의':'Momentum',
'정지공격의':'Static Strike',
'이동공격의':'Mobile Strike',
'패링공세의':'Post-Parry Boost',
'임사폭발의':'Near-Death Burst',
'만기력공의':'Full Stamina ATK',
'만마력공의':'Full Mana ATK',
'신선처치의':'Fresh Kill',
'경직연장의':'Stagger Extension',
'빙결연장의':'Freeze Extension',
'둔화강화의':'Slow Amp',
'독중첩의':'Poison Stack',
'출혈중첩의':'Bleed Stack',
'발화강화의':'Ignite Amp',
'동상강화의':'Frostbite Amp',
'감전강화의':'Shock Amp',
'사선회심의':'Low HP Crit',
'갑옷강화의':'Armor Boost',
'블록흡수의':'Block Absorb',
'방패타격의':'Shield Bash',
'방패경직의':'Shield Stagger',
'격투속의':'Brawl Speed',
'격투회심의':'Brawl Crit',
'격투경직의':'Brawl Stagger',
'하반재생의':'Leg Regen',
'CC단축의':'CC Duration Red',
'돌진타의':'Dash Strike',
'돌진범위의':'Dash AoE',
'은신질주의':'Stealth Sprint',
'회피감쇠의':'Dodge DR',
'속성감쇠의':'Elem DR',
'마나왕관의':'Mana Helm',
'시전왕관의':'Cast Helm',
'쿨감왕관의':'CD Helm',
'경험왕관의':'EXP Helm',
'공생의':'Symbiosis',
'수질의':'Body-Soul',
'회심흡의':'Crit Leech',
'체마의':'HP-Mana',
'체기의':'HP-Stamina',
'마기의':'Mana-Stamina',
'전재생의':'All Regen',
'힘민의':'STR-DEX',
'힘지의':'STR-INT',
'민지의':'DEX-INT',
'운근의':'Fortune-Grit',
'수확의':'Harvest',
'빙화의':'Ice-Fire',
'뇌암의':'Thunder-Dark',
'근마의':'Blade-Magic',
'속성침식의':'Elem Erosion',
'화염반지의':'Fire Ring',
'빙결반지의':'Ice Ring',
'뇌전반지의':'Thunder Ring',
'암흑반지의':'Dark Ring',
'독반지의':'Poison Ring',
'콤보반지의':'Combo Ring',
'처치마나의':'Kill Mana',
'관통반지의':'Pierce Ring',
'만능목걸이의':'Allround Necklace',
'회심목걸이의':'Crit Necklace',
'관통목걸이의':'Pierce Necklace',
'스킬목걸이의':'Skill Necklace',
'콤보한계의':'Combo Max',
'처치치유의':'Kill Heal',
'지구벨트의':'Stamina Belt',
'포션벨트의':'Potion Belt',
'활력벨트의':'Vitality Belt',
'탐욕벨트의':'Greed Belt',
'마나띠의':'Mana Band',
'시전띠의':'Cast Band',
'마력띠의':'Magic Band',
'주술띠의':'Spell Band',
'속성띠의':'Elem Band',
'전사의힘':'Warrior Power',
'전사생명의':'Warrior Life',
'전사흡혈의':'Warrior Leech',
'전사인내의':'Warrior Poise',
'마법사의힘':'Mage Power',
'마법사마나의':'Mage Mana',
'마법사수호의':'Mage Shield',
'마법사속성의':'Mage Elem',
'궁수의힘':'Archer Power',
'궁수사거리의':'Archer Range',
'궁수관통의':'Archer Pierce',
'궁수질주의':'Archer Sprint',
'탱크생명의':'Tank Life',
'탱크방어의':'Tank Defense',
'탱크블록의':'Tank Block',
'탱크가시의':'Tank Thorns',
'암살회심의':'Assassin Crit',
'암살후방의':'Assassin Backstab',
'암살독의':'Assassin Poison',
'암살회피의':'Assassin Dodge',
'종결자의':'The Ender',
'생존자의':'Survivor',
'종결수호의':'End Shield',
'종결회심의':'End Crit',
'종결공격의':'End ATK',
'종결저항의':'End Resistance',
'종결파괴의':'End Destruction',
'종결보호의':'End Protection',
'종결흡혈의':'End Leech',
'종결인내의':'End Poise',
'종결쿨감의':'End CD Red',
'종결경험의':'End EXP',
'종결약탈의':'End Loot',
'종결악의의':'End Malice',
'종결힘의':'End STR',
'종결민첩의':'End DEX',
'종결지능의':'End INT',
'종결행운의':'End LCK',
'종결근성의':'End Grit',
'종결연살의':'End Kill Chain',
'건강공세의':'Healthy Offense',
'중상폭발의':'Wounded Burst',
'중상흡혈의':'Wounded Leech',
'토벌의':'Vanguard',
'정예토벌의':'Elite Vanguard',
'극대화의':'Maximize',
'공격력 +X%':'ATK +X%',
'관통 확률 +X%':'Pierce Chance +X%',
'방어율 +X%':'Block Rate +X%',
'물리 피해감소 +X%':'Phys DR +X%',
'최대 HP +X':'Max HP +X',
'공격속도 +X%':'ATK Speed +X%',
'상태이상 저항 +X%':'Status Resist +X%',
'이동속도 +X%':'Move Speed +X%',
'원소 저항 +X%':'Elem Resist +X%',
'최대 HP +X%':'Max HP +X%',
'회피 쿨다운 -X%':'Dodge CD -X%',
'물약 쿨다운 -X%':'Potion CD -X%',
'부활력 +X%':'Revive Power +X%',
'마법 데미지 +X%':'Magic DMG +X%',
'전설 특수':'Legendary Special',
'5타 콤보 완성 시 데빌포스 20% 즉시 충전':'5-hit combo: instantly charge DevilForce 20%',
'처치 시 이속 +40%(3초) + 다음 공격 크리 보장':'Kill: MoveSpd +40%(3s) + next attack guaranteed Crit',
'스태거 발동 시 범위 충격파 (ATK×120%)':'Stagger: AoE shockwave (ATK×120%)',
'스태거 발동 시 범위 충격파 (ATK×100%)':'Stagger: AoE shockwave (ATK×100%)',
'강타 시 적 넉백 거리 2배 + 벽충돌 추가뎀':'Heavy hit: Knockback ×2 + wall collision bonus DMG',
'출혈 대상 크리 시 잔여 DoT×300% 즉시 폭발':'Crit vs Bleeding: remaining DoT×300% instant explosion',
'작살 착지 타격 수만큼 데미지 +20% 중첩(최대5)':'Javelin landing hits: stack +20% DMG (max 5)',
'치명타 시 추가 투사체 1발 발사':'Crit: fire 1 additional projectile',
'패리 성공 시 반격 데미지 ×2':'Parry: counter DMG ×2',
'피격 시 3초 쿨로 HP 5% 즉시 회복':'On Hit (3s CD): restore 5% HP instantly',
'스킬 사용 시 20% 확률로 쿨다운 미소모':'Using skills: 20% chance no cooldown consumed',
'공격속도 +20% + 기본공격에 랜덤 원소 추가':'ATK Speed +20% + basic attacks add random element',
'이동 중 지속 HP 재생 (초당 HP의 1%)':'While moving: HP regen (1% HP/sec)',
'회피 직후 첫 공격 데미지 +80%':'First attack after Dodge: DMG +80%',
'패리 타이밍 판정 +50% 확대':'Parry timing window +50% expanded',
'원소 반응 발동 시 추가 폭발 (ATK×80%)':'Elemental reaction: bonus explosion (ATK×80%)',
'처치 시 데빌포스 5% 회복':'Kill: restore 5% DevilForce',
'HP 50% 이하 시 전 스킬 쿨다운 -30%':'Below 50% HP: all skill CD -30%',
'물약 사용 시 5초간 피해 +15%':'Using Potion: DMG +15% for 5s',
'암묵':'Implicit',
'낡은 악마의 팔찌':'Worn Demon Bracelet',
'흑요석 악마의 팔찌':'Obsidian Demon Bracelet',
'미스릴 악마의 팔찌':'Mithril Demon Bracelet',
'낡은 생명의 팔찌':'Worn Life Bracelet',
'확인':'Confirm',
'조작법':'Controls',
'살아남으려면 익혀라':'Master this to survive',
'전투':'Combat',
'이동 / 상호작용':'Move / Interact',
'메뉴':'Menu',
'시스템':'System',
'아무 키를 눌러 시작':'Press any key to start',
'스테이지':'Stufe',
'💪 힘 (STR)':'💪 STR',
'🏹 민첩 (DEX)':'🏹 DEX',
'🔮 지능 (INT)':'🔮 INT',
'🍀 행운 (LCK)':'🍀 LCK',
'⚔️ 맹공':'⚔️ Ansturm',
'🔱 돌파':'🔱 Durchbruch',
'⚡ 반격':'⚡ Vergeltung',
'🔮 마력폭주':'🔮 Manaüberfluss',
'🎯 정밀사격':'🎯 Präzisionsschuss',
'🛡 수호신':'🛡 Göttliche Ägide',
'💚 회복력':'💚 Regeneration',
'💥 급소':'💥 Kritischer Treffer',
'🎁 약탈':'🎁 Plünderung',
'🔱 관통':'🔱 Durchdringung',
'💠 마력회복':'💠 Mana-Erholung',
'🏹 쇠뇌력':'🏹 Armbrustmeisterschaft',
'⚔ 광전사':'⚔ Berserker',
'🎯 추적자':'🎯 Verfolger',
'🗡 물리관통':'🗡 Physische Durchdringung',
'🔮 마법관통':'🔮 Magische Durchdringung',
'🌿 풍요':'🌿 Fülle',
'🐺 약자포식':'🐺 Räuber',
'☠ 침식':'☠ Korrosion',
'💎 마력그릇':'💎 Mana-Reservoir',
'💪 힘의그릇':'💪 Ausdauer-Reservoir',
'👿 악의중독':'👿 Bosheitsvergiftung',
'❤️ 강인':'❤️ Robustheit',
'🛡 철벽':'🛡 Eiserne Mauer',
'🎯 사냥꾼':'🎯 Jäger',
'✦ 인간성':'✦ Menschlichkeit',
'☠ 악마성':'☠ Dämon',
'1. 악의폭풍':'1. Bosheitssturm',
'2. 칼날 계열':'2. Klingen-Skills',
'3. 역병 확장':'3. Seuchen-Ausbau',
'4. 이동스킬 마스터':'4. Bewegungsmeister',
'5. 사슬 확장':'5. Ketten-Ausbau',
'6. 💀 필살기 선택':'6. 💀 Ultimativ-Wahl',
'7. 멸살+만화+원소+전격이동':'7. Strahl+Nadel+Elem+Blitz',
'8. 회전참+기폭+대왕':'8. Wirbel+Detonation+Titan',
'9. 방패 합체':'9. Schild-Fusion',
'10. 해골무덤+악의폭풍':'10. Knochen+Bosheitssturm',
'11. 폭풍소환+얼음보주':'11. Sturm+Eiskugel',
'12. 뇌전걸음':'12. Geisterschritt',
'13. 신성 영역':'13. Heilige Domäne',
'14. 6단합체: 폭풍빔':'14. Fusion×6: Sturmstrahl',
'15. 신성+빙결':'15. Sakral+Frost',
'16. 암흑+가시+대왕2':'16. Finsternis+Dornen+Titan2',
'17. 사슬 최종':'17. Ketten-Finale',
'⚡ 이동스킬':'⚡ Bewegung',
'⚔️ 물리':'⚔️ Physisch',
'🛡️ 방어':'🛡️ Verteidigung',
'🔮 마법':'🔮 Magie',
'🏹 석궁/투사체':'🏹 Armbrust/Projektil',
'⚙️ 영역':'⚙️ Domäne',
'💀 필살기':'💀 Ultimativ',
'⭐ 추천':'⭐ Empfohlen',
'⚔ 공격':'⚔ Angriff',
'🛡 방어':'🛡 Verteidigung',
'⚙ 특수':'⚙ Spezial',
  '👻 공성허수아비!':'👻 Belagerungs-Vogelscheuche!',
  '💥 공성허수아비 폭발!':'💥 Vogelscheuchen-Explosion!',
};

const _DE_PFX={'녹슨':'Rostig','강철':'Stahl','흑요석':'Obsidian','미스릴':'Mithril','심판의':'Richter-','천벌의':'Göttlicher Zorn','파멸의':'Vernichtung',
'불꽃':'Flammen','화염':'Inferno','염화':'Höllenfeuer','지옥불':'Höllenbrand','지옥화':'Höllenbrand','지옥':'Höllenbrand','멸화의':'Vernichtend',
'냉기':'Frost','빙결':'Eisgebunden','빙하':'Glazial','서리의':'Reif','서리':'Reif','영겁빙':'Ewiges Eis',
'그림자':'Schatten','암흑':'Finster','심연':'Abgrund','나락의':'Nether','나락':'Nether','무간의':'Leere',
'전기':'Funken','낙뢰':'Donner','암전':'Blitz','뇌신의':'Sturmgott','뇌신':'Sturmgott','만뢰의':'Myriadendonner',
'축복':'Gesegnet','성광':'Heiliges Licht','신성':'Sakral','천사의':'Engel','신벌의':'Göttliches Urteil',
'낡은':'Abgenutzt','천':'Stoff','가죽':'Leder','강철사':'Stahlfaser','은':'Silber','은사':'Silberfaden','화염의':'Inferno','빙결의':'Eisgebunden','암흑의':'Finster','암전의':'Blitz'};
const _DE_BASE={'대검':'Großschwert','석궁':'Armbrust','연사석궁':'Schnellfeuer-Armbrust','마력석궁':'Arkane Armbrust',
'견갑':'Schulterplatte','대견갑':'Große Schulterplatte','전투화':'Kampfstiefel','갑옷':'Rüstung','갑주':'Panzerung',
'왕관':'Krone','장갑':'Handschuhe','건틀릿':'Panzerhandschuhe','바지':'Hose','각반':'Beinschienen',
'허리띠':'Gürtel','벨트':'Gürtel','부적':'Talisman','목걸이':'Halskette','반지':'Ring',
'망토':'Umhang','악마팔찌':'Demon Bracelet','생명팔찌':'Life Bracelet','팔찌':'Armreif','귀걸이':'Ohrring'};
