// 지옥의 길 — Suomi (fi)
const _FI={
'썩은 숲':'Mätä Metsä',
'숲의 감시자':'Metsänvartija',
'독버섯 거인':'Myrkkysieniläinen',
'숲의 사냥꾼':'Metsästäjä',
'숲의 기생수':'Loispeto',
'1장 — 썩은 숲':'L1 — Mätä Metsä',
'2장 — 벌레굴':'L2 — Matojen Pesä',
'3장 — 얼음굴':'L3 — Jääluola',
'4장 — 고통의 화염지대':'L4 — Helvetin Erämaa',
'5장 — 지옥의 군단':'L5 — Helvetin Legioona',
'6장 — 사도의 마굴':'L6 — Apostolin Luola',
'7장 — 지옥성':'L7 — Helvetin Linnake',
'탈출!':'Pakeni!',
'처치':'tapot',
'경험치':'KOK',
'최대콤보':'Maksimikombo',
'일어나. 여신이 널 여기 보낸 건 죽으라고가 아니야.':'Herää. Jumalatar ei lähettänyt sinua kuolemaan.',
'좋아, 감각이 있군. 계속 쳐!':'Hyvä, sinulla on vaistoa. Jatka!',
'Shift를 눌러. 작살이다. 땅에 꽂아서 끌려가!':'Paina Shift. Se on harppuuna. Kiinnitä ja ratsasta!',
'작살로 끌려가는 중엔 무적이다. 위험할 때 쓰면 좋아.':'Olet haavoittumaton harppuunan vetäessä. Käytä vaarassa.',
'...아파? 당연하지. 여긴 지옥이야.':'...Sattuu? Tietenkin. Tämä on helvetti.',
'Q를 눌러! 악의로 보호막을 만들 수 있다.':'Paina Q! Luo kilpi ilkeydellä.',
'보호막 없이 버틸 생각은 버려.':'Unohda selviytyminen ilman kilpeä.',
'우클릭이 패링이다. 적 공격이 닿기 직전에 눌러!':'Oikea klikkaus torjuu. Paina juuri ennen osumaa!',
'못 하겠으면 때려. 안 죽으면 그만이야.':'Etkö osaa torjua? Lyö vain. Riittää ettei kuole.',
'됐어! 감 잡았구나.':'Siinä se! Alat oppia.',
'하나 죽었군.':'Yksi nurin.',
'유령쇠뇌야. 인사해.':'Se on haamuvarsisjousi. Tervehdi.',
'빨간 탄을 무서워하지 마. 악의가 강하다.':'Älä pelkää punaisia. Ilkeys on voimakasta.',
'패링으로 돌려주고, Q 보호막도 써! 악의를 잘 굴려!':'Torju takaisin, käytä Q-kilpeä! Hallitse ilkeyttä!',
'무지개빛은 패링 불가! 피해!':'Sateenkaaria ei voi torjua! Väistä!',
'피가 새고 있다. Shift. 빠져.':'Vuodat verta. Shift. Pois.',
'물약 있잖아! 숫자키!':'Sinulla on juomia! Numeronäppäimet!',
'우클릭. 적 손목이 꺾일 때 쳐.':'Oikea klikkaus. Lyö kun ranne taipuu.',
'빨간 탄은 악의 덩어리다. 쳐내서 이용해.':'Punaiset ammukset ovat ilkeyden palasia. Torju ja käytä.',
'무지개빛만 피하면 돼! 나머지는 다 패링!':'Väistä sateenkaaret! Torju kaikki muu!',
'Q 보호막도 패링이 가능해!':'Q-kilpi voi myös torjua!',
'위험해! 쉬프트 사슬기동으로 피해!!':'Vaara! Shift ketjupyrähdys!',
'쉬프트! 사슬기동은 이동기야! 끌려가면서 무적이라고!':'Shift! Ketjupyrähdys = liike! Haavoittumaton!',
'스킬포인트가 쌓였어! K 눌러서 스킬 배우자!':'Taitopisteet valmiina! Paina K!',
'속성을 읽어. 약점을 찌르면 두 배로 썩는다.':'Lue elementit. Heikkoudet = tuplavahinkoa.',
'K를 눌러봐! 스킬을 배울 수 있어!':'Paina K! Opi taitoja!',
'C 눌러서 능력치 찍어! 패시브도 있어~':'C tilastoihin! Passiiveja~',
'G를 눌러. 대장간에서 장비를 강화할 수 있다.':'Paina G. Paranna varusteita pajalla.',
'F키도 스킬 슬롯이야! 스킬 많으면 L로 배정해봐~':'F on myös taitopaikka! L asettaa~',
'Z. 필살기다. 아껴 써라.':'Z. Äärimmäinen. Käytä viisaasti.',
'L-CTRL로 유령걸음이나 얼음보주 쓸 수 있어!':'L-CTRL Haamukävelyyn tai Jääpalloon!',
'L을 눌러. 스킬 슬롯을 정리해야 한다.':'Paina L. Järjestä taitopaikat.',
'가방 터지겠다! V 눌러서 창고에 넣어둬!':'Laukku täynnä! V varastoon!',
'ESC로 설정 열 수 있어! 난이도 바꾸기, 자동물약 조절~':'ESC asetukset! Vaikeus, autojuomat~',
'...아직 살아있네. 좌클릭으로 저것들 쳐봐.':'...Vielä elossa. Vasemmalla klikkauksella.',
'...치는 건 할 줄 아네. 피하는 건?':'...Osaat lyödä. Mutta väistää?',
'흥, 작살 못 맞추면 헛수고야.':'Hmph, harppuunaohi = hukkaan.',
'...운이 좋았을 뿐이야. 아마.':'...Pelkkää tuuria. Luultavasti.',
'...고기 냄새. 싫진 않네.':'...Tuoksuu lihalta. Ei huono.',
'...말은 못해.':'...Se ei voi puhua.',
'예쁘다고 만지면 죽어.':'Kosketat koska kauniita? Kuolet.',
'작살 던져! 끌려가면 무적이야!':'Heitä harppuuna! Haavoittumaton!',
'...마시든 말든. 네 목숨이니까.':'...Juo tai älä. Sinun henkesi.',
'그게 패링이야! 타이밍이 전부야~':'Se on pareeraus! Ajoitus on kaikki kaikessa~',
'화염엔 빙결! 암전엔 암흑! 기억해!':'Tuli > Jää! Salama > Pimeä! Muista!',
'...얼어붙은 놈은 오래 안 간다.':'...Jäätyneet eivät kestä kauan.',
'얼었어! 빙결 중 1.5배야!':'Jäätynyt! 1.5× vahinkoa!',
'...힘을 골라라. 전부 가질 순 없다.':'...Valitse voimasi. Et saa kaikkea.',
'스탯을 올려. 살고 싶으면.':'Nosta tilastoja. Jos haluat elää.',
'좋은 장비는 강화해야 진짜 힘을 발휘해!':'Hyvät varusteet tarvitsevat parannuksia!',
'...슬롯을 채워. 빈 손은 죽음이다.':'...Täytä paikat. Tyhjät kädet = kuolema.',
'Z 누르면 대박! 쿨타임 길어서 타이밍 봐야 해!':'Z massiiviseen vahinkoon! Pitkä jäähtymisaika!',
'Ctrl. 위기에 쓸 카드가 하나 늘었군.':'Ctrl. Yksi kortti lisää hätään.',
'스킬이 많아졌네~ L로 어디에 뭘 넣을지 골라!':'Niin monta taitoa~ L asettaa!',
'...버리기 아까운 건 창고에.':'...Varastoi arvokkaat.',
'...살아남은 것만으로도 대단하군. 설정을 확인해.':'...Jo selviytyminen vaikuttavaa. Asetukset.',
'MP 부족!':'MP ei riitä!',
'ST 부족!':'ST ei riitä!',
'악의 부족!':'Ilkeys ei riitä!',
'충전 중...':'Lataus...',
'캔슬':'Peruuta',
'아이템 선택 필요':'Valitse esine',
'악의 소진...':'Ilkeys loppui...',
'비문 발견...':'Kirjoitus löydetty...',
'HP물약!':'HP-juoma!',
'HP물약 +1':'HP-juoma +1',
'HP물약 +2':'HP-juoma +2',
'HP/MP/ST 회복!':'HP/MP/ST Palautettu!',
'보물상자 개봉!':'Arkku Avattu!',
'익사!':'Hukkuminen!',
'피웅덩이!':'Verilampi!',
'독혈!':'Myrkkyinen Veri!',
'잡힘!':'Tartuttu!',
'콤보 종료':'Kombo Loppu',
'빙결!':'Jäätynyt!',
'화상!':'Palaa!',
'독!':'Myrkky!',
'감전!':'Sähköisku!',
'기절!':'Tainnutus!',
'봉인됨!':'Sinetöity!',
'관통!':'Läpäisy!',
'기검참':'Energialeikkaus',
'악의구':'Ilkeyden Pallo',
'회전참':'Pyörremyrsky',
'기폭팔':'Räjäytys',
'칼등 처내기':'Miekantorjunta',
'만화방창':'Neulasuihku',
'멸살광선':'Tuhoamissäde',
'원소추적탄':'Elementaalinen Etsijä',
'악의 보호자':'Ilkeyden Vartija',
'악의 사냥':'Ilkeyden Metsästys',
'폭풍소환':'Pyörrekutsuminen',
'해골무덤':'Luuhauta',
'\u{1F47B} 유령!':'\u{1F47B} Haamu!',
'\u{1F9B4} 해골무덤!':'\u{1F9B4} Luuhauta!',
'신성폭발':'Pyhä Räjähdys',
'블랙':'Musta Tähti',
'용암소환':'Laavakutsuminen',
'처형':'Teloitus',
'악마화 부활':'Demon Herätys',
'붉은꽃':'Purppurakukka',
'얼음보주':'Jää Orb',
'뇌전걸음':'Haamukävely',
'만화방창 II':'Neulasuihku II',
'마력연사':'Taikasuihku',
'마력광선':'Kaarilaser',
'업화선':'Helvetintulisäde',
'지옥진':'Helvetinrivistö',
'폭독칼날':'Ruttomiekka',
'악의폭풍':'Ilkeysmyrsky',
'악의기둥':'Pimeä Pylväs',
'회복의 영역':'Pyhä Alue',
'구속의 영역':'Sitouttava Alue',
'아이스스톰':'Jää Storm',
'대왕치기':'Giant Isku',
'대왕치기 2':'Jätti-isku II',
'기동불꽃':'Ketjuliekki',
'기동파괴':'Ketjumurskaus',
'기동칼날개':'Ketjumiekansiipi',
'평화의보호':'Rauhan Egidi',
'참회':'Katumus',
'칼등날개':'Kilpi Wing',
'폭산탄':'Räjähdyslaukaus',
'파쇄의 영역':'Murskausalue',
'침식의 영역':'Syövytysalue',
'관통의 영역':'Läpäisyalue',
'부활의 영역':'Herätysalue',
'가시덫':'Spike Ansa',
'푸른비':'Taivaansade',
'버스트루프':'Räjähdyssilmukka',
'유령 허수아비':'Haamu Decoy',
'폭발 허수아비':'Räjähtävä Houkutin',
'공성쇠뇌':'Piiritysvarsijousi',
'사슬기동:충돌':'Ketjusyöksy: Isku',
'사슬기동:화염':'Ketjusyöksy: Liekki',
'전격이동':'Välähdysaskel',
'기동칼날개!':'Miekansiipi!',
'기동불꽃!':'Ketjuliekki!',
'기동파괴!':'Ketjumurskaus!',
'사슬이동:강화!':'Ketjusyöksy!',
'사슬기동:화염!':'Ketjuliekki!',
'작살!':'Harppuuna!',
'진입!':'Sisään!',
'레인라이트닝!':'Rain Salama!',
'마력연사!':'Taikasuihku!',
'🔷 마력광선!':'🔷 Kaarilaser!',
'광선 해제':'Laser Pois',
'MP 부족 — 광선 해제':'MP loppui — Laser Pois',
'집중...':'Keskittyminen...',
'시전...':'Loitsiminen...',
'만화방창!':'Neulasuihku!',
'바늘출!':'Neulapurske!',
'칼날!':'Miekka!',
'착지!':'Laskeutuminen!',
'체간삭감!':'Asennon murto!',
'기동전폭 준비!':'Ketjuräjähdys Valmis!',
'기동불꽃 준비!':'Ketjuliekki Valmis!',
'기동파괴 준비!':'Ketjumurskaus Valmis!',
'유령불꽃 ON':'Haamuliekki ON',
'유령불꽃 OFF':'Haamuliekki OFF',
'기동칼날개 AUTO ON':'Miekansiipi AUTO ON',
'기동칼날개 AUTO OFF':'Miekansiipi AUTO OFF',
'자동 버스트!':'Automaattipurske!',
'연사 해제':'Rapid Tuli Off',
'당기기 모드':'Veto Mode',
'밀어내기 모드':'Työntö Mode',
'날개치기':'Siipiisku',
'처내기':'Torjunta',
'Shift: 작살 발사 → 끌려감':'Shift: Harppuunaheitto → veto',
'Shift: 화염길+화상':'Shift: Liekkijälki+palo',
'CT: 전류변신+뇌전걸음 (쿨4초)':'CT: Salamamuoto+Haamukävely (JÄ 4s)',
'CT: 방어구체+빙결 (재입력: 파쇄)':'CT: Jääpallo+jäätyminen (uudelleen: murskaus)',
'근접':'Lähit.',
'견갑':'Kilpi',
'작살':'Harppuuna',
'마법':'Taianomainen',
'보막':'Kilpi',
'유령':'Haamu',
'스킬':'Taidot',
'대장':'Paja',
'인벤':'Laukku',
'인벤토리':'Varusteet',
'복수의 대장간':'Koston Paja',
'패시브 스킬':'Passiivitaidot',
'전투 스킬':'Taistelutaidot',
'캐릭터 선택':'Hahmon Valinta',
'물리':'Fyysinen',
'화염':'Tuli',
'빙결':'Jäätynyt',
'암흑':'Pimeä',
'암전':'Salama',
'신성':'Pyhä',
'대지':'Maa',
'힘':'Voima',
'민첩':'Ketteryys',
'지능':'Älykkyys',
'행운':'Onni',
'맹공':'Rynnäkkö',
'철벽':'Lujuus',
'돌파':'Läpimurto',
'반격':'Vastaisku',
'마력폭주':'Taikapurske',
'정밀사격':'Tarkkuuslaukaus',
'수호':'Suojelija',
'수호신':'Suojelushenki',
'회복력':'Palautuminen',
'급소':'Kriittinen Isku',
'약탈':'Ryöstö',
'관통':'Läpäisy',
'마력회복':'Manan Palautus',
'쇠뇌력':'Varsijousiton Taito',
'광전사':'Berserki',
'추적자':'Jäljittäjä',
'물리관통':'Fyysinen Läpäisy',
'마법관통':'Taikainen Läpäisy',
'녹슨 대검':'Ruosteinen Suuri Miekka',
'강철 대검':'Teräksinen Suuri Miekka',
'흑요석 대검':'Obsidiaani Suuri Miekka',
'낡은 석궁':'Kulunut Varsijousi',
'강철 석궁':'Teräksinen Varsijousi',
'흑요석 석궁':'Obsidiaani Varsijousi',
'대검':'Suuri Miekka',
'석궁':'Varsijousi',
'연사석궁':'Sarjajousi',
'마력석궁':'Taikajousi',
'악의 추출':'Ilkeyden Uuttaminen',
'악의':'Ilkeys',
'필살기':'Äärimmäinen',
'필살기 해제':'Äärimmäinen Tyhjä',
'이전':'Siirto',
'강화':'Paranna',
'개봉!':'Avattu!',
'여신의 가호':'Jumalattaren Siunaus',
'과부하!':'Ylikuormitus!',
'맹독의':'Myrkyllinen',
'불꽃의':'Liekehtiä',
'냉기의':'Jääkylmä',
'번개의':'Sähköinen',
'암흑의':'Kirottu',
'관통의':'Läpäisevä',
'광폭의':'Raivoisa',
'파쇄의':'Murskaava',
'연쇄의':'Ketjuava',
'학살의':'Tappava',
'폭발의':'Räjähtävä',
'집중의':'Keskittynyt',
'쾌속의':'Nopea',
'패리의':'Torjuva',
'추적자의':'Jäljittäjän',
'작살의':'Harppuuna',
'궁극의':'Ylivoimainen',
'집중력의':'Tietoinen',
'강인의':'Järkkymätön',
'수호의':'Suojaava',
'활력의':'Elinvoimainen',
'신속의':'Nopeutettu',
'화염수호':'Tulisuoja',
'빙결수호':'Jääsuoja',
'암전수호':'Salamasuoja',
'암흑수호':'Pimeäsuoja',
'독수호':'Myrkkysuoja',
'전원소수호':'Yleissuoja',
'강철의':'Raudoitettu',
'반사의':'Heijastava',
'가시의':'Piikikkäs',
'흡수의':'Imevä',
'인내의':'Kestävä',
'위기의':'Epätoivoinen',
'피격반격의':'Kostavaa',
'패링폭발의':'Torjuntaräjähdys',
'스태거폭발의':'Horjutusräjähdys',
'원소전환의':'Muuntaja',
'정화의':'Puhdistava',
'불굴의':'Peräänantamaton',
'부활의':'Elvyttävä',
'약탈의':'Ryöstävä',
'경험의':'Kokenut',
'골드의':'Kultainen',
'포션강화의':'Voimakas',
'사슬의':'Ketjutettu',
'진혼의':'Pyhittävä',
'윤회의':'Syklinen',
'생명력의':'Elinvoimainen',
'재생의':'Uudistuva',
'치유의':'Parantava',
'마력의':'Taikuuden',
'절약의':'Taloudellinen',
'영혼의':'Sielunside',
'예리한':'Terävä',
'맹렬한':'Julma',
'파멸의':'Tuhoisa',
'게임 설정':'Pelin Asetukset',
'화면 흔들림':'Näytön Tärinä',
'파티클 양':'Hiukkasmäärä',
'효과음 볼륨':'SFX Äänenvoimakkuus',
'음악 볼륨':'Musiikin Äänenvoim.',
'난이도':'Vaikeus',
'자동 물약':'Autom. Juoma',
'최소 줍기 등급':'Vähim. Keräystaso',
'최소 줍기 티어':'Vähim. Keräystier',
'FPS 제한':'FPS Raja',
'해상도 스케일':'Resoluutioskaalaus',
'펫 자동수거':'Lemmikin Autokeräys',
'화면 설정':'Näyttöasetukset',
'화면 모드':'Näyttötila',
'보스 AI 디버그':'Pomo AI Debug',
'유령불꽃 크기':'Haamuliekin Koko',
'화면 명암':'Kirkkaus',
'유령 글로우':'Haamun Hohde',
'기동:칼날개 AUTO':'Miekansiipi AUTO',
'일반':'Normaali',
'어려움':'Vaikea',
'지옥':'Helvetti',
'이상':'tai yli',
'사용 안 함':'Pois',
'창 모드':'Ikkunoitu',
'보더리스':'Reunaton',
'전체화면':'Koko näyttö',
'설정':'Asetukset',
'조작 키 설정 (클릭하여 변경)':'Näppäinasetukset (Klikkaa muuttaaksesi)',
'좌클릭 무기 공격':'Vasen Klikkaus Hyökkäys',
'우클릭 탭 칼등 처내기':'Oikea Klikkaus Miekantorjunta',
'우클릭 홀드 연속 처내기':'Oikea Klikkaus Jatkuva Torjunta',
'SHIFT 작살 발사':'SHIFT Harppuunaheitto',
'이동':'Liiku',
'아이템 줍기':'Nosta Esine',
'능력치 (스탯/패시브)':'Tilastot (Tilastot/Passiivit)',
'분해':'Pura',
'제작':'Valmista',
'사망':'Kuolema',
'부활':'Herätys',
'로비로':'Aulaan',
'가방에 공간이 없습니다!':'Ei tilaa laukussa!',
'가방이 가득 찼습니다!':'Laukku täynnä!',
'창고가 가득 찼습니다!':'Varasto täynnä!',
'퀵슬롯이 가득 찼습니다!':'Pikapaikka täynnä!',
'결정 주머니가 가득 찼습니다!':'Kristalli pouch is full!',
'결정 주머니 가득!':'Kristalli pouch full!',
'악의가 부족합니다!':'Ilkeys ei riitä!',
'가방이 비어있습니다':'Laukku tyhjä',
'창고가 비어있습니다':'Varasto tyhjä',
'비어있음':'Tyhjä',
'어픽스 없음':'Ei ominaisuutta',
'장착!':'Varustettu!',
'해제':'Riisuttu',
'보관':'Talleta',
'꺼내기':'Nosta',
'현재 장착':'Nykyinen varuste',
'없음 — 제작하세요!':'Ei mitään — Valmista!',
'리셋할 포인트가 없습니다':'Ei pisteitä nollattavaksi',
'키 설정 초기화 완료':'Näppäinasetukset nollattu',
'제작 확률':'Valmistusmahdollisuus',
'제작 비용':'Valmistuskustannus',
'보유 악의':'Ilkeyttä omistettu',
'보스방':'Pomoluola',
'안식처':'Turvapaikka',
'회복':'Palautuminen',
'점화':'Sytytys',
'비석':'Kivipaasi',
'읽기':'Lue',
'파괴':'Tuhoa',
'제단':'Alttari',
'기원':'Rukoile',
'잔해':'Rauniot',
'열기':'Avaa',
'문지기':'Portinvartija',
'부활 판정 중...':'Herätyspäätös...',
'기폭 준비!':'Räjäytys valmis!',
'탈출':'Pakene',
'연타':'Naputtele',
'추적암전':'Tracking Salama',
'만화광선':'Valosäde',
'최종 마법':'Lopullinen Taika',
'감시중':'Tarkkailu',
'대기':'Valmiustila',
'작동중':'Aktiivinen',
'설치 가능':'Voi asentaa',
'균열 임박!':'Murtuma lähestyy!',
'흡수 중...':'Imeminen...',
'흡수 완료 — 재입력으로 회수':'Valmis — uudelleen keräämiseksi',
'화상':'Palo',
'당기기':'Veto',
'밀어내기':'Työntö',
'단계':'taso',
'단':'taso',
'습득!':'Opittu!',
'리셋!':'Nollaus!',
'세팅!':'Asetettu!',
'회수':'Palautus',
'합체 해제':'Erota',
'리셋':'Nollaus',
'환불':'Palautus',
'파트너 클릭!':'Klikkaa paria!',
'SP부족!':'SP tarvitaan!',
'같은 보석 스킬 습득 시 합체 가능':'Yhdistä samalla jalokivitaidolla',
'펼쳐서 초기화':'Laajenna nollaamaan',
'슬롯:':'Paikka:',
'남은 SP':'SP Jäljellä',
'맞아서 사망':'Kuoli osumasta',
'레벨':'Taso',
'최대HP':'Max HP',
'방랑 기사':'Vaeltava Ritari',
'보물 악마':'Aarredemonni',
'거울의 사도':'Peilin Apostoli',
'상인 악마':'Kauppiasdemonni',
'사슬의 죄수':'Kahlittu Vanki',
'시간의 사도':'Ajan Apostoli',
'탐욕의 사도':'Ahneuden Apostoli',
'저주받은 쌍둥이':'Kirotut Kaksoset',
'차원 균열체':'Ulottuvuushalkeama',
'죽음 그 자체':'Itse Kuolema',
'HP결정':'HP Kristalli',
'ST결정':'ST Kristalli',
'MP결정':'MP Kristalli',
'ATK결정':'HYÖ Kristalli',
'DEF결정':'PUO Kristalli',
'속도결정':'Nopeus Kristalli',
'크리결정':'Kriitti Kristalli',
'치명결정':'KriitVah Kristalli',
'화염결정':'Tuli Kristalli',
'냉기결정':'Jää Kristalli',
'암흑결정':'Pimeä Kristalli',
'번개결정':'Salama Kristalli',
'신성결정':'Pyhä Kristalli',
'생명결정':'Elämä Kristalli',
'기력결정':'Kestävyys Kristalli',
'마력결정':'Mana Kristalli',
'행운결정':'Onni Kristalli',
'조각':'Sirpale',
'파편':'Siru',
'순수결정':'Puhdas Kristalli',
'완전결정':'Täydellinen Kristalli',
'결정 주머니':'Kristallipussi',
'결정이 없습니다':'Ei kristalleja',
'가루':'Pöly',
'전체':'Kaikki',
'스탯':'Tilasto',
'원소':'Elem..',
'유틸':'Apul.',
'현재':'Nykyinen',
'최대 강화 달성 (+20)':'Maks parannus (+20)',
'강화 시':'Parannuksen jälkeen',
'합성':'Syntetisoi',
'같은 종류·같은 성급 결정 3개 → 1성급 상승 (강화 리셋)':'3 samaa tyyppiä & astetta → 1 asteen nosto (parannus nollautuu)',
'합성 가능한 결정이 없습니다 (같은 종류·성급 3개 필요)':'Ei syntetisoitavia (tarvitaan 3 samaa tyyppiä & astetta)',
'결정 분해 → 결정 가루':'Kristallin Hajoaminen → Pöly',
'분해할 결정이 없습니다':'Ei purettavia kristalleja',
'결정 제작 (가루 → 결정)':'Kristallin Valmistus (Pöly → Kristalli)',
'탈착':'Irroita',
'빈 슬롯':'Tyhjä slot',
'결정 선택 후 클릭':'Valitse kristalli ja klikkaa',
'클릭하여 선택결정 장착':'Klikkaa varustaaksesi kristallin',
'획득!':'Saatu!',
'제작!':'Valmistettu!',
'합성!':'Syntetisoitu!',
'최상위 일괄합성':'Massasynteesi Huipulle',
'일괄합성 완료':'Massasynteesi valmis',
'벌레굴':'Matojen Pesä',
'얼음굴':'Jää Cavern',
'고통의 화염지대':'Helvetin Erämaa',
'지옥의 군단':'Helvetti Legion',
'사도의 마굴':'Apostolin Luola',
'지옥성':'Helvetin Linnake',
'엑소듀서 전사':'Exoduser-soturi',
'포이즈':'Asento',
'지옥창고':'Helvetin Varasto',
'선택분해':'Valikoiva Purku',
'쓰레기':'Romu',
'복구 불가!':'Ei voi palauttaa!',
'중요잠금':'Tärkeä-lukittu',
'자동 장착!':'Automaattivarustus!',
'분해! 가루 +':'Purettu! Pöly +',
'평화보호':'Egidi',
'지진폭풍':'Maanjäristys',
'회전기폭':'Pyör.-Räjäytys',
'공격':'Hyökkäys',
'보호막':'Este',
'합체 스킬로 통합됨':'Yhdistetty taitoon',
'얼음보주 안에선 사용 불가!':'Cannot use inside Jää Orb!',
'Shift+키로 폭파':'Shift+näppäin räjäyttää',
'취소':'Peruuta',
'쿨다운 중...':'Jäähtyminen...',
'시전 중...':'Loitsiminen...',
'악의 부족! (12)':'Ilkeys ei riitä! (12)',
'악의 부족! (15)':'Ilkeys ei riitä! (15)',
'악의 부족! (20)':'Ilkeys ei riitä! (20)',
'악의 부족! (10)':'Ilkeys ei riitä! (10)',
'HP 부족!':'HP ei riitä!',
'필살기 슬롯 클릭하여 배정!':'Klikkaa äärimmäispaikkaa!',
'필살기 스킬을 습득하세요':'Opi äärimmäinen taito',
'우클릭(칼등치기)에 합체됨':'Yhdistetty oik. klikkaukseen',
'T(석궁자동)에 세팅하세요':'Aseta T:hen (autovarsijousi)',
'공성쇠뇌 철거 → 이동식':'Piiritysjousi → kannettava',
'ST 부족! (100)':'ST ei riitä! (100)',
'HP 99% 이상!':'HP 99%+!',
'그로기 보스 없음!':'Ei tokkuraista pomoa!',
'이미 폭풍 지역!':'Jo myrskyvyöhykkeellä!',
'이미 빙풍 지역!':'Jo jäämyrskyssä!',
'💎 푸른비 해금!':'💎 Taivaansade avattu!',
'💫 버스트루프 해금!':'💫 Räjähdyssilmukka avattu!',
'👻 유령 허수아비 해금!':'👻 Haamuhoukutin avattu!',
'쿨 ':'JÄ ',
'과부하 ':'Ylikuormitus ',
'🕊️💎 블루콩!':'🕊️💎 Sininen Papu!',
'🛡️💎 빨콩→블루콩!':'🛡️💎 Pun.→Sini Papu!',
'🛡️💎 무지개→블루콩!':'🛡️💎 Sateenkaari→Sini Papu!',
'레어':'Harvinainen',
'슬롯':'Paikka',
'성공률':'Onnistumisprosentti',
'AI 자동 강화':'AI Automaattiparannus',
'최대 강화 달성!':'Maks parannus saavutettu!',
'최대 강화':'Maks parannettu',
'회복량':'Palautuminen',
'분해할 아이템이 없습니다.':'Ei purettavia esineitä.',
'🔨 제작':'🔨 Valmista',
'체간':'Asento',
'아이템에 마우스를 올리거나 좌클릭으로 선택하세요':'Vie hiiri päälle tai vasemmalla valitse',
'중독':'Myrkky',
'지뢰':'Miina',
'함정':'Ansa',
'산호가시':'Korallipiikit',
'투사체':'Ammus',
'도트':'DoT',
'레어몹':'Harvinainen Hirviö',
'구역':'Vyöhyke',
'가시!':'Piikki!',
'림보':'Limbo',
'색욕':'Himo',
'탐식':'Ylensyönti',
'탐욕':'Ahneus',
'분노':'Viha',
'이단':'Harhaoppi',
'폭력':'Väkivalta',
'분노!':'Raivo!',
'탐욕!':'Ahneus!',
'💀 분노 폭발!':'💀 Raivopurske!',
'심연의 분노!':'Syvyyden Raivo!',
'쌍둥이의 분노!':'Kaksosten Raivo!',
'소환굴':'Kutsuaukko',
'처치!':'Kukistettu!',
'왕관 착용':'Kruunu On',
'왕관 해제':'Kruunu Off',
'맨손':'Paljas',
'없음':'Ei mitään',
'갑옷':'Haarniska',
'부츠':'Saappaat',
'매직':'Taianomainen',
'챔피언':'Mestari',
'초속':'Nopeus',
'강타':'Isku',
'재생':'Uud.',
'맹독':'Myrkky',
'소환':'Kutsuminen',
'기생':'Loinen',
'분열':'Halkeama',
'용암자취':'Laavajälki',
'사망폭발':'Kuolemanräjähdys',
'화염사슬':'Tuli Chain',
'광전':'Raivoisa',
'텔레포트':'Teleportti',
'소용돌이':'Pyörre',
'환영':'Haamu',
'전격반사':'Sähköheijastus',
'감전':'Sähköistä',
'낙뢰':'Ukkonen',
'연쇄전격':'Chain Salama',
'동료불사':'Kuolematon Liittolainen',
'영혼포식':'Sielun Syönti',
'시간왜곡':'Aikavääristymä',
'혼돈변이':'Kaaos Mutaatio',
'복수자':'Kostaja',
'마법보초':'Taika-vartija',
'환영술사':'Illusionisti',
'함성':'Sotahuuto',
'치유':'Parantaa',
'신속':'Vikkelys',
'다크 판타지 전사. 거대검+검은 갑옷':'Synkän fantasian soturi. Suuri miekka + Musta haarniska',
'⚡ 사슬이동:강화!':'⚡ Ketju:Vahvistettu!',
'⚡ 사슬기동:화염!':'⚡ Ketjuajo: Liekki!',
'달성!':'Saavutettu!',
'ST':'ST',
'부족!':'Riittämätön!',
'타':'Osuma',
'🌀 당기기 모드':'🌀 Veto Mode',
'💥 밀어내기 모드':'💥 Työntö Mode',
'🕊️빨콩 흡수':'🕊️Punainen papu imeytys',
'🕊️흡수':'🕊️Imeytys',
'💎유도 폭발!':'💎Hakeutuva Räjähdys!',
'💥반사 폭발!':'💥Heijastusräjähdys!',
'⚡⚡ 참회 귀환!':'⚡⚡ Katumus Paluu!',
'⚡ 참회!':'⚡ Katumus!',
'파도!':'Aalto!',
'암전!':'Salama!',
'암흑!':'Pimeä!',
'암흑창!':'Pimeä Spear!',
'빛창!':'Valokeihäs!',
'체 소환!':'kutsuttu!',
'개 설치!':'asetettu!',
'💥 보스 그로기!':'💥 Pomo Tokkura!',
'💥 그로기!':'💥 Tokkura!',
'보상':'Bonus',
'⚡ 암전나선!':'⚡ Salama Helix!',
'🌋 지진폭풍!':'🌋 Maanjäristys!',
'SP슬롯':'SP Paikka',
'F슬롯':'F Paikka',
'⚔🩸 독혈해방!':'⚔🩸 Ruttovapautus!',
'⚔ 칼날 해방!':'⚔ Miekkavapautus!',
'🔨🌋 지옥강타!':'🔨🌋 Inferno Isku!',
'🔨 대왕치기!':'🔨 Giant Isku!',
'✟ 결계의 영역!':'✟ Suojaalue!',
'✟ 물의 영역!':'✟ Vesialue!',
'✟ 파쇄의 영역!':'✟ Murskausalue!',
'✟ 침식의 영역!':'✟ Syövytysalue!',
'✟ 관통의 영역!':'✟ Läpäisyalue!',
'✟ 권능의 영역!':'✟ Hallitsija-alue!',
'🛡 회복의 영역!':'🛡 Pyhä Alue!',
'임계...!':'Kriittinen...!',
'기폭팔!':'Räjäytys!',
'강제기폭!':'Pakotettu Räjäytys!',
'자동기폭!':'Automaattiräjäytys!',
'회전기폭!':'Pyörimisräjäytys!',
'해제기폭!':'Vapautusräjäytys!',
'지진기폭!':'Maanjäristysräjäytys!',
'혼돈의 왕관':'Kaaoksen Kruunu',
'전지전능의 왕관':'Kaikkivaltiuden Kruunu',
'악마의 팔찌':'Demoni Rannekoru',
'생명의 팔찌':'Elämän Rannekoru',
'🌊 위→아래 파도!':'🌊 Ylä→Ala Aalto!',
'🌊 오른→왼 파도!':'🌊 Oikea→Vasen Aalto!',
'🌊 아래→위 파도!':'🌊 Ala→Ylä Aalto!',
'🌊 왼→오른 파도!':'🌊 Vasen→Oikea Aalto!',
'무적!':'Haavoittumaton!',
'🪞 반격!':'🪞 Vasta!',
'💢 반격!':'💢 Vasta!',
'흡수!':'Imeytys!',
'반격 발사!':'Vastalaukaus!',
'저주! 드랍률 -50%':'Kirous! Pudotus -50%',
'도망!':'Pako!',
'위상!':'Vaihe!',
'방어!':'Kilpi!',
'회수 HP+':'Palautus HP+',
'이동식 복귀':'Liikkuva Paluu',
'약점!':'Heikkous!',
'저항!':'Vastustus!',
'콤보 종료: ':'Kombo End: ',
'악의 +':'Ilkeys +',
'저주 ':'Kirous ',
'불발...':'Sutkahti...',
'작살 약점!':'Harppuunaheikkous!',
'전염 x':'Rutto x',
'흡수 완료!':'Imeytys Valmis!',
'부활 성공!':'Herätys Onnistui!',
'부활 실패...':'Herätys Epäonnistui...',
'차원 이동!':'Ulottuvuussiirto!',
'기절 해제':'Tainnutus Ohi',
'악의 부족':'Ilkeys ei riitä',
'스킬 미습득':'Ei opittuja taitoja',
'펼치기':'Laajenna',
'접기':'Supista',
'조건 미달!':' ei täyty!',
'해제!':' Erotettu!',
'자동 ON':' Auto ON',
'자동 OFF':' Auto OFF',
'스킬 해제':' taito tyhjä',
'닫기':'Sulje',
'장착 중':'Varustettu',
'보관 아이템':'Varastoitu Esine',
'클릭으로 선택 · ESC로 닫기':'Klikkaa valitaksesi · ESC sulje',
'선택됨':'Valittu',
'악의 부족! (30)':'Ilkeys ei riitä! (30)',
'MP 부족! (40)':'MP ei riitä! (40)',
'MP 부족! (100)':'MP ei riitä! (100)',
'MP 부족! (10)':'MP ei riitä! (10)',
'MP 부족! (':'MP ei riitä! (',
'✟ 시전...':'✟ Loitsiminen...',
'🌋 시전...':'🌋 Loitsiminen...',
'⛧ 시전...':'⛧ Loitsiminen...',
'❄ 진입!':'❄ Sisään!',
'🔱 작살!':'🔱 Harppuuna!',
'레벨 부족! (요구: Lv.':'Taso liian alhainen! (Vaad: Taso',
' 장착!':' Varustettu!',
' 해제':' Riisuttu',
'👿 악의 추출: +':'👿 Ilkeyden Uuttaminen: +',
'F 슬롯 해제':'F Paikka tyhjä',
'💫 집중...':'💫 Keskittyminen...',
'⚡ 마력연사!':'⚡ Taikasuihku!',
'❄빙결!':'❄Jäätynyt!',
'🟢독!':'🟢Myrkky!',
'⚡감전!':'⚡Sähköisku!',
'🔥화상!':'🔥Palaa!',
'✦ 여신의 가호 — SP+5 AP+3':'✦ Jumalattaren Siunaus — SP+5 AP+3',
'⚔ 기동칼날개!':'⚔ Miekansiipi!',
'🔥 화염관통!':'🔥 Tuliläpäisy!',
'🔱 관통!':'🔱 Läpäisy!',
'⚔ 칼날!':'⚔ Miekka!',
'💥 착지!':'💥 Laskeutuminen!',
'💫 기절!':'💫 Tainnutus!',
'⚡ 체간삭감!':'⚡ Asennon Murto!',
'⚡ 기동파괴! ':'⚡ Ketjumurskaus! ',
'🔥 기동불꽃!':'🔥 Ketjuliekki!',
'🔥 기동불꽃! ':'🔥 Ketjuliekki! ',
'단계 ×':' x',
'⚡ 기동전폭! x':'⚡ Ketjuräjähdys! x',
'🔥🔥 3중폭!':'🔥🔥 Liekki x3!',
'🔥🔥🔥 6중폭!':'🔥🔥🔥 Liekki x6!',
'🔥🔥🔥🔥 9중폭!':'🔥🔥🔥🔥 Liekki x9!',
'💥 불꽃폭발! ':'💥 Liekkiäjäytys! ',
'🔥 기동불꽃 준비!':'🔥 Ketjuliekki Valmis!',
'🔨 기동파괴 준비!':'🔨 Ketjumurskaus Valmis!',
'⚡ 기동전폭 준비!':'⚡ Ketjuräjähdys Valmis!',
'⚡ 과부하! 5초':'⚡ Ylikuormitus! 5s',
'💫 자동 버스트!':'💫 Automaattipurske!',
'🔨 칼등날개!':'🔨 Kilpisiipi!',
'💥폭발!':'💥Räjähdys!',
'🛡️💎 유도반사!':'🛡️💎 Hakeutuva Heijastus!',
'⚡💎 블루콩!':'⚡💎 Sininen Papu!',
'💎 블루콩!':'💎 Sininen Papu!',
'⚡반사!':'⚡Heijastus!',
'💎 푸른비 OFF':'💎 Taivaansade OFF',
'💎 푸른비 ON!':'💎 Taivaansade ON!',
'🔥 지옥진!':'🔥 Helvetinrivistö!',
'🔥 업화선!':'🔥 Helvetintulisäde!',
'✦ 평화 충격파! ':'✦ Rauhan Shokkiaalto! ',
'⚡ 전류 방출!':'⚡ Virranvapautus!',
'⚡⚡ 레인라이트닝!':'⚡⚡ Salamasade!',
'💫 광역!':'💫 Aluevaikutus!',
'🔥 불장판!':'🔥 Tulialue!',
'💫 피니셔!':'💫 Viimeistelijä!',
'☠ 지옥에서 귀환!':'☠ Paluu Helvetistä!',
'☠ 완전 사망!':'☠ Pysyvä Kuolema!',
'⚔ 처형! ':'⚔ Teloitus! ',
'💥 지뢰!':'💥 Miina!',
'⚠ 함정!':'⚠ Ansa!',
'❌ 우클릭으로! -':'❌ Oikea klikkaus! -',
'❌ Q키로! -':'❌ Q! -',
'💥무지개 폭발! ':'💥Sateenkaariräjähdys! ',
'🛡️💎 블루콩!':'🛡️💎 Sininen Papu!',
'⬜화이트볼!':'⬜Valkoinen Pallo!',
'✨💎 블루콩!':'✨💎 Sininen Papu!',
'💜다크볼!':'💜Pimeä Pallo!',
'❄빙판!':'❄Jäälattia!',
'🌨빙결!':'🌨Jäätynyt!',
'🕸둔화!':'🕸Hidas!',
'⚠트랩!':'⚠Ansa!',
'💀 역병 처형!':'💀 Ruttoteloitus!',
'💥 역병 Finale!':'💥 Ruttofinaali!',
'⚔ 균열 악마!':'⚔ Halkeamademonni!',
'자동회수 HP+':'Auto-Palautus HP+',
'MP 부족 — 연사 해제':'MP matala — Sarjatuli Pois',
'MP 부족 — 푸른비 OFF':'MP matala — Taivaansade OFF',
'🛡️반사!':'🛡️Heijastus!',
'⚡🦴 참회 귀환!':'⚡🦴 Katumus Paluu!',
'🦴⚡해골번개!':'🦴⚡Luusalama!',
'⚡악의폭풍!':'⚡Ilkeysmyrsky!',
'❄아이스스톰!':'❄Jäämyrsky!',
'⚡ 암전폭발!':'⚡ Salamaäjähdys!',
'⚡ 레인라이트닝! x':'⚡ Salamasade! x',
'❄ 탈출!':'❄ Pakene!',
'⚡쉴드!':'⚡Kilpi!',
'❄🌪️ 얼음보주!':'❄🌪️ Jääpallo!',
'🌪️ 전개!':'🌪️ Avaus!',
'❄ 빙결흡인!':'❄ Jääpyörre!',
'❄☄ 빙결폭발!':'❄☄ Jääräjähdys!',
'☄️ 흡인!':'☄️ Pyörre!',
'☄️ 대폭발!':'☄️ Megaäjähdys!',
'❄ 얼음보주!':'❄ Jääpallo!',
'⏳ 시간왜곡!':'⏳ Aikavääristymä!',
'쿨다운!':'Jäähtyminen!',
'❄ 파쇄!':'❄ Murskaus!',
'☄️💥 대폭발!':'☄️💥 Megaäjähdys!',
'반사!':'Heijastus!',
'💀 도넛!':'💀 Donitsi!',
'💀 전멸!':'💀 Tuho!',
'🌊 파도!':'🌊 Aalto!',
'속박!':'Sido!',
'반격!':'Vasta!',
'분신!':'Klooni!',
'분신 파괴!':'Klooni Tuhottu!',
'무기 해방!':'Asevapautus!',
'❄프리즌!':'❄Vankila!',
'⚡ 증표 ':'⚡ Merkki ',
'흔들!':'Tärinä!',
'⚠ 광역 발사!':'⚠ AoE Tuli!',
'🔥 확산!':'🔥 Leviäminen!',
'⚠ 돌진!':'⚠ Rynnäkkö!',
'🦅 도약!':'🦅 Loikka!',
'⚡ 레이저!':'⚡ Laser!',
'🌊 충격파!':'🌊 Shokkiaalto!',
'👹 소환!':'👹 Kutsuminen!',
'☄ 유성우!':'☄ Meteoriittisade!',
'🖐 잡기!':'🖐 Tarttuminen!',
'🌀 회전참!':'🌀 Pyörremyrsky!',
'💣 지뢰!':'💣 Miina!',
'🌀 흡인!':'🌀 Imu!',
'🔴 빨간콩 폭풍!':'🔴 Punapapumyrsky!',
'🔴🔴 콩 비!':'🔴🔴 Papusade!',
'🌊 부채꼴 충격파!':'🌊 Viuhka-aalto!',
'✴ 멸광 레이저!':'✴ Tuhoamislaser!',
'🔴 추적 장판!':'🔴 Seurantavyöhyke!',
'💥 속성탄!':'💥 Elementaalilaukaus!',
'⚔ 검기!':'⚔ Miekkaenergia!',
'⚔ 재단참!':'⚔ Niittoviilto!',
'🌀 나선탄!':'🌀 Kierteisammus!',
'⚠ 찌르기!':'⚠ Pisto!',
'🔥🔥 지옥기둥!':'🔥🔥 Helvetinpylväs!',
'⚔ 환영검!':'⚔ Haamumiekka!',
'💢 반격자세!':'💢 Vastaasento!',
'⚔ 연격!':'⚔ Kombo!',
'🌑 암흑!':'🌑 Pimeys!',
'👥 분신!':'👥 Klooni!',
'🌋 균열!':'🌋 Halkeama!',
'🌊 파동!':'🌊 Väreily!',
'💣 추적지뢰!':'💣 Hakeutuva Miina!',
'⏪ 되감기!':'⏪ Kelaus!',
'🌀 중력장!':'🌀 Painovoimakenttä!',
'🔨 벽밀기!':'🔨 Seinätyöntö!',
'☠ 독안개!':'☠ Myrkkyinen Sumu!',
'⛓ 감옥!':'⛓ Vankila!',
'⚡ 연쇄번개!':'⚡ Ketjusalama!',
'🔮 궤도탄!':'🔮 Kiertoammus!',
'🛡 방패돌진!':'🛡 Kilpihyökkäys!',
'🪞 반격자세!':'🪞 Vastaasento!',
'⚓ 속박!':'⚓ Sido!',
'👤 분신!':'👤 Klooni!',
'🖐 탈취!':'🖐 Varastus!',
'🔥🔥 용암 지대!':'🔥🔥 Laava-alue!',
'🌧🌧 화염 폭격!':'🌧🌧 Tulisade!',
'⚡⚡ 전격 장막!':'⚡⚡ Salamaverho!',
'💀 내 곁으로!':'💀 Tule Luokseni!',
'⭕ 안전!':'⭕ Turvallinen!',
'💀💀 전멸 폭발!':'💀💀 Tuhoamisräjähdys!',
'⚡ 쐐기 소멸!':'⚡ Kiilan Tuho!',
'🌊충격파!':'🌊Shokkiaalto!',
'👿악의+100':'👿Ilkeys+100',
'💥패링폭발!':'💥Torjuntaräjähdys!',
'균열 충돌! ':'Halkeamatörmäys! ',
'벽 충돌! ':'Seinätörmäys! ',
'소환!':'Kutsuminen!',
'환영!':'Haamu!',
'⚡낙뢰!':'⚡Ukkonen!',
'⚡빔!':'⚡Säde!',
'환영술!':'Illuusio!',
'💀소환!':'💀Kutsuminen!',
'🔮주술!':'🔮Kirous!',
'🩸산란!':'🩸Kutu!',
'💢광폭!':'💢Raivoisa!',
'🕷산란!':'🕷Kutu!',
'❄서리!':'❄Pakkanen!',
'❄빙결파!':'❄Jääaalto!',
'💀빙마!':'💀Jäädemonni!',
'돌진!':'Rynnäkkö!',
'충격파!':'Shokkiaalto!',
'독안개!':'Myrkkyinen Sumu!',
'연타!':'Ryöppy!',
'포효!':'Karjunta!',
'강화!':'Parannus!',
'꼬리!':'Häntä!',
'은신...':'Piiloutuminen...',
'기습!':'Väijytys!',
'산란!':'Kutu!',
'독가스!':'Myrkkykaasu!',
'소멸...':'Liukeneminen...',
'강타!':'Murskaus!',
'분비!':'Eritys!',
'채찍!':'Piiska!',
'출혈!':'Vuoto!',
'급강하!':'Syöksy!',
'방출!':'Purkaus!',
'충격!':'Isku!',
'치유!':'Parantaa!',
'의식!':'Rituaali!',
'지옥불!':'Helvetintuli!',
'끌려감!':'Vedetty!',
'혀!':'Kieli!',
'응시!':'Katse!',
'낙하!':'Putoaminen!',
'핏방울!':'Veripisara!',
'일어남!':'Nousu!',
'휩쓸기!':'Pyyhkäisy!',
'웅크림':'Kyykky',
'뼈칼날!':'Luumiekka!',
'감속!':'Hidas!',
'비명!':'Huuto!',
'화산탄!':'Tulivuorilaukaus!',
'자폭!':'Itsetuho!',
'감싸기!':'Kääriminen!',
'잡기!':'Tarttuminen!',
'내리찍기!':'Isku!',
'브레스!':'Henkäys!',
'비행!':'Lento!',
'용암비!':'Laavasade!',
'물뿜기!':'Vesisuihku!',
'빛...':'Valo...',
'삼키기!':'Niele!',
'마비!':'Halvaannus!',
'방전!':'Purkaus!',
'집게찍기!':'Pincer Isku!',
'찍기!':'Isku!',
'붙잡기!':'Tartu!',
'감아올리기!':'Kierto!',
'파편!':'Sirpale!',
'할퀴기!':'Raapaisu!',
'기생충!':'Loinen!',
'심연 해방!':'Syvyyden Vapautus!',
'촉수난타!':'Lonkerosuihku!',
'삼지창!':'Kolmikärki!',
'소용돌이!':'Pyörre!',
'해일!':'Tsunami!',
'끼걱!':'Natina!',
'폭발!':'Räjähdys!',
'체인!':'Ketju!',
'갈기!':'Harja!',
'공포!':'Kauhu!',
'흡혈!':'Imeytys!',
'베기!':'Viilto!',
'비이이명!!':'Kilinä!!',
'분열!':'Halkeama!',
'3연참!':'Kolmoisviilto!',
'패링!':'Torjunta!',
'...복사...':'...Kopiointi...',
'불균형...저주!':'Epätasapaino...Kirous!',
'저주!':'Kirous!',
'균형...강화!':'Balance...Paranna!',
'심판의 기둥!':'Tuomion Pylväs!',
'처형 선고!':'Kuolemantuomio!',
'고통의 해방!':'Kivun Vapautus!',
'너도 느껴봐라!':'Tunne tämä!',
'대검난무!':'Suurmiekkahurjastelu!',
'촉수!':'Lonkero!',
'전방위 빔!':'Kaikkisäde!',
'회피!':'Väistö!',
'[F] 상점':'[F] Kauppa',
'거래 성공!':'Kauppa Onnistui!',
'악의 부족! (':'Ilkeys ei riitä! (',
'상인이 떠납니다...':'Kauppias lähtee...',
'사슬 해방!':'Ketjuvapautus!',
'완전 해방!':'Täysvapautus!',
'⏪ 시간 되감기!':'⏪ Ajan Kelaus!',
'전환!':'Vaihto!',
'부활 ':'Herätys ',
'🌀균열!':'🌀Halkeama!',
'...사라짐':'...Katosi',
'낫 베기!':'Viikateisku!',
'☠ 죽음의 선고!':'☠ Kuolemantuomio!',
'선고 집행...':'Täytäntöönpano...',
'⚡패링!':'⚡Torjunta!',
'경직!':'Horjunta!',
'⚠ 잡혔다!':'⚠ Tartuttu!',
'💥 내던지기!':'💥 Heitto!',
'💥 소용돌이 폭발!':'💥 Pyörreräjähdys!',
'👻 순간이동!':'👻 Teleportti!',
'💫 기절! 5초':'💫 Tainnutus! 5s',
'찌르기 반격!':'Pistovastasiirto!',
'💢 폭발!':'💢 Räjähdys!',
'반격 실패':'Vasta Epäonnistui',
'탈취 반격!':'Varastus Vasta!',
'무기 봉인!':'Asesinetöinti!',
'냠!':'Nam!',
'합체!':'Yhdistetty!',
'출구가 열렸다!':'Uloskäynti avautui!',
'보물상자 출현!':'Aarrearkku ilmestyi!',
'출구':'Uloskäynti',
'⚠ 문지기가 살아있다!':'⚠ Portinvartija vielä elossa!',
'⏱ 타임어택 ':'⏱ Aikahyökkäys ',
'처치율 ':'Tappoaste ',
'불사 보호':'Kuolematon Suoja',
'환영 소멸!':'Haamu Katosi!',
'부활력 ':'Herätysvoima ',
'✟ 신성력 억제! (':'✟ Pyhä Tukahdutus! (',
'부활 실패 (':'Herätys Epäonnistui (',
'⚡순간이동!':'⚡Teleportti!',
'👻 동반부활!':'👻 Yhteisherätys!',
'✟ 신성력 억제!':'✟ Pyhä Tukahdutus!',
'💀 부활 판정 중...':'💀 Herätyspäätös...',
'⚔ 문지기 처치!':'⚔ Portinvartija Kukistettu!',
'🚪 보스방 개방!':'🚪 Pomoluola Auki!',
'잔해 출현!':'Rauniot ilmestyivät!',
'🌀균열 발생!':'🌀Halkeama avautui!',
'🔥복수!':'🔥Kosto!',
'💥폭독혈!':'💥Ruttoveri!',
'빙판!':'Jäälattia!',
'❄최종빙결!':'❄Lopullinen Jäätyminen!',
'빙마 처치!':'Jäädemonni Kukistettu!',
'분리!':'Erottuminen!',
'뼈 파편!':'Luusirpale!',
'태아 처치!':'Sikiö Kukistettu!',
'지배자 처치!':'Ylivalta Kukistettu!',
'용암!':'Laava!',
'화룡 처치!':'Tulilohikäärme Kukistettu!',
'최후의 비명!':'Viimeinen Huuto!',
'산화...':'Hapettuminen...',
'심판자 처치!':'Tuomari Kukistettu!',
'고통의 왕 처치!':'Kivun Kuningas Kukistettu!',
'수역!':'Vesi!',
'파편 폭발!':'Sirpaleräjähdys!',
'거대어 처치!':'Leviathan Kukistettu!',
'대사도 처치!':'Yliapostoli Kukistettu!',
'독웅덩이!':'Myrkkylammikko!',
'화염장판!':'Tulialue!',
'전기장!':'Sähkökenttä!',
'무기 드롭!':'Asepudotus!',
'보물 발견!':'Aarre Löydetty!',
'상인의 주머니 +':'Kauppiaan Pussi +',
'속박의 파편!':'Sitoumisen Siru!',
'시간의 조각!':'Ajan Sirpale!',
'저주 해제!':'Kirous Poistettu!',
'차원의 결정!':'Ulottuvuuskristalli!',
'전설 아이템!':'Legendaarinen Esine!',
'죽음을 이겨냈다!':'Kuoleman Voitto!',
'💥대폭발!':'💥Megaäjähdys!',
'⚡강화!':'⚡Parannus!',
'장비 ':'Varuste ',
'💫 진동!':'💫 Tärinä!',
'❄ 무적!':'❄ Haavoittumaton!',
'👻 유령!':'👻 Haamu!',
'집중 해제!':'Keskittyminen Peruttu!',
'집중!':'Keskittyminen!',
'🕊️ 평화보호 ':'🕊️ Egidi ',
'🛡 보호막 ':'🛡 Kilpi ',
'🌀 회전보호막 ':'🌀 Pyörivä Kilpi ',
'💥한방캡!':'💥Yhden Osumaraja!',
'⚡쉴드 파괴!':'⚡Kilpi Tuhottu!',
'💀 불굴!':'💀 Peräänantamaton!',
'💀 1회부활!':'💀 1-elämä Herätys!',
'감시 회수':'Vartijapalautus',
'악마화 부활!':'Demoniherätys!',
'배정 가능한 스킬 없음':'Ei asetettavia taitoja',
'칼날 없음!':'Ei Miekkaa!',
'⚔ 악의사냥!':'⚔ Ilkeyden Metsästys!',
'❄🌪️ 얼음소용돌이!':'❄🌪️ Jääpyörre!',
'🌪️ 폭풍소환!':'🌪️ Pyörrecutsuminen!',
'🦴 해골무덤!':'🦴 Luuhauta!',
'🌹 붉은꽃!':'🌹 Purppurakukka!',
'💥 폭산탄!':'💥 Räjähdyslaukaus!',
'🪡 바늘출!':'🪡 Neulapurske!',
'⚡ 전격이동!':'⚡ Välähdysaskel!',
'기둥가시로 흡수됨':'Pylvään okaimeytyy',
'🌿 가시덫!':'🌿 Piikkiansa!',
'👻 유령총!':'👻 Haamuase!',
'💥 유령총 폭발!':'💥 Haamuaseräjähdys!',
'⚡ 전격의창!':'⚡ Ukkoskeihäs!',
'🏹 공성쇠뇌 설치!':'🏹 Piiritysjousi Asetettu!',
'👻 유령 허수아비!':'👻 Haamuhoukutin!',
'💥 폭발 허수아비!':'💥 Räjähtävä Houkutin!',
'축적!':'Varastoitu!',
'축적 중...':'Varastointi...',
'만충! 재입력→폭발':'Täynnä! Uudelleen→Räjähdys',
'폭발! ':'Räjähdys! ',
'뎀':' VAH',
'🩸 폭독칼날!':'🩸 Ruttomiekka!',
'⚡날개치기!':'⚡Siipiisku!',
'🗡 칼등날개!':'🗡 Kilpisiipi!',
'🏛️ 악의기둥!':'🏛️ Pimeä Pylväs!',
'🌿 기둥가시!':'🌿 Pylvään Oka!',
'🌋 지옥강타!':'🌋 Helvetinisku!',
'💥 체간 붕괴!':'💥 Asennon Murto!',
'💫 포이즈 파괴!':'💫 Asennon Tuho!',
'⚡ 뇌전걸음!':'⚡ Haamukävely!',
'✟ 구속의 영역!':'✟ Sitouttava Alue!',
'✟ 신성폭발!':'✟ Pyhä Räjähdys!',
'⛧ 블랙!':'⛧ Musta Tähti!',
'🌋 용암소환!':'🌋 Laavakutsuminen!',
'필살기 배정!':'Äärimmäinen Asetettu!',
'완료':'Valmis',
'합체 가능':'Yhdistettävissä',
'부족':'Riittämätön',
'SP 부족! (':'SP tarvitaan! (',
'🕊️ 히든: 평화의보호 해금!':'🕊️ Piilotettu: Rauhan Egidi avattu!',
'⚡ 히든: 참회 해금!':'⚡ Piilotettu: Katumus avattu!',
'배정됨':'Asetettu',
'합체 Lv.':'Yhdist. Taso',
'◆ 같은 보석 스킬 습득 시 합체 가능':'◆ Yhdistä opettelemalla sama jalokivitaito',
'▼ 가방 → 창고 보관':'▼ Laukku → Varasto',
'▲ 창고 → 가방 꺼내기':'▲ Varasto → Laukku',
'✓ 선택됨':'✓ Valittu',
'⟨ 입력 대기... ⟩':'⟨ Odottaa... ⟩',
'⟨ 대기 ⟩':'⟨ Odota ⟩',
'보조':'Ala',
'키 설정 초기화 (또는 F5 키)':'Nollaa Näppäinasetukset (tai F5)',
'아무 키 또는 마우스 버튼을 누르세요 (ESC = 취소)':'Paina näppäintä tai hiirtä (ESC = peruuta)',
'WebGPU 활성':'WebGPU Aktiivinen',
'WebGL2 활성':'WebGL2 Aktiivinen',
'측정 중...':'Mittaus...',
'불러오기 실패':'Lataus Epäonnistui',
'장착':'Varustettu',
'🔒 중요잠금 아이템은 분해 선택 불가!':'🔒 Lukittuja esineitä ei voi purkaa!',
'장비 강화 (실패 시 재료만 소멸)':'Paranna Varustetta (epäonnistuminen: materiaalit menetetään)',
'강화 보너스 적용':'Parannusbonus Käytetty',
'강화 실패!':'Parannus Epäonnistui!',
'장착된 장비가 없습니다.':'Ei varustettuja esineitä.',
'충분':'Riittävä',
'더 필요':'Tarvitaan Lisää',
'장비 선택':'Valitse Varuste',
'목표치 설정':'Aseta Tavoite',
'악의 투입':'Panosta Ilkeyttä',
'자동 시도':'Automaattiyritys',
'목표 강화치':'Tavoiteparannus',
'예상 필요 악의':'Arvioitu Ilkeys',
'보유':'Omistettu',
'강화 시작':'Aloita Parannus',
'위에서 장비를 선택하세요':'Valitse varuste ylhäältä',
'⬆ 물약 강화 (최대 10단)':'⬆ Juoma Paranna (max level 10)',
'필요':'Tarvitaan',
'악의의 분해로 — 장비를 악의로 갈아버려라':'Ilkeyssulatusuuni — Jauha varusteita ilkeydeksi',
'전체 선택':'Valitse Kaikki',
'전체 해제':'Poista Valinnat',
'희귀 이하':'Harvinainen tai Alempi',
'어픽스 리롤!':'Ominaisuuden Uudelleenheitto!',
'영웅':'Sankarillinen',
'전설':'Legendaarinen',
'무기 타입':'Asetyyppi',
'활 타입':'Jousityyppi',
'ST 부족':'ST ei riitä',
'💀 광폭화!':'💀 Raivoissaan!',
'...따라오는 거 아니야. 같은 방향일 뿐이지.':'...En seuraa sinua. Sama suunta vain.',
'공기가 달라졌어. 더 썩었군.':'Ilma muuttui. Enemmän mätää.',
'여기부터는 악마 영역이야. ...맘대로 해.':'Demonialuetta tästä. ...Tee miten haluat.',
'...이 냄새. 살점이 썩는 냄새야.':'...Se haju. Mätänevä liha.',
'여기 오래 있으면 미쳐. 나도, 너도.':'Liian kauan ja tulet hulluksi. Minäkin.',
'이 길의 끝에 뭐가 있을까. ...알고 싶지도 않어.':'Mitä tien päässä on? ...En halua tietää.',
'...여기가 끝이야. 돌아갈 길은 없어.':'...Tämä on loppu. Ei paluuta.',
'작살을 땅에 꽂으면 끌려간다.':'Kiinnitä harppuuna maahan ja vedetään.',
'Shift로 작살 던져봐!':'Kokeile heittää harppuuna Shiftillä!',
'패링 성공하면 ST가 회복된다. 공짜 자원이야.':'Torjunta palauttaa ST. Ilmaisia.',
'패링 많이 하면 ST 걱정 없어~':'Torju paljon eikä ST lopu~',
'장비 분해하면 악의를 얻는다. 쓰레기도 자원이야.':'Purkaminen antaa ilkeyttä. Romukin resursseja.',
'TAB 열어서 안 쓰는 장비 분해해!':'Avaa TAB ja pura käyttämättömiä!',
'그로기 상태의 적에겐 1.5배 데미지가 들어간다.':'Tokkurat viholliset 1.5× vahinkoa.',
'무릎 꿇으면 전력으로 때려!':'Kun polvistavat, lyö kaikella!',
'속성 상성이 있다. 화염은 빙결에 약하고, 암전은 암흑에 약하다.':'Elementeillä on vastakohtia. Tuli→Jää, Salama→Pimeä.',
'무기 속성 바꿔가면서 싸워봐!':'Kokeile vaihtaa aseelementtejä!',
'빙결된 적은 1.5배 데미지를 받는다.':'Jäätyneet viholliset ottavat 1.5× vahinkoa.',
'얼리고 때리는 게 기본이야!':'Jäädytä ja lyö — perusteet!',
'보스의 빨간 공격은 패링 가능. 보라빛은 회피만.':'Pomonpunaiset hyökkäykset torjuttavissa. Sateenkaari vain väistö.',
'색깔 잘 봐! 빨강은 받아치고 무지개는 피해!':'Katso värejä! Punainen torjutaan, sateenkaari väistetään!',
'VIT를 올리면 최대 HP가 오른다. 죽기 싫으면 찍어.':'VIT nostaa max HP. Panosta elääksesi.',
'STR은 근접, DEX는 활, INT는 마법! 골고루 말고 하나만!':'STR lähit., DEX jousi, INT taika! Yksi!',
'E를 꾹 누르면 빔이 나간다. 짧게 누르면 투사체.':'Pidä E = säde. Napautus E = ammus.',
'마법 쓸 때 MP 잘 봐! 빔은 연속으로 깎여!':'Katso MP:tä taikuudessa! Säde kuluttaa nopeasti!',
'핵터와 디로이가 아이템을 주워준다. 수거 범위 안이면.':'Hecter ja Deroy keräävät esineitä.',
'우리한테 고마워해~ 안 주우면 썩잖아.':'Kiitä meitä~ Esineet mätänevät muuten.',
'LCK를 올리면 레어 드롭률이 오른다.':'LCK nostaa harvinaisten pudotusta.',
'운빨 게임이긴 하지~ LCK 올려봐!':'Tuuria~ Kokeile LCK:ta!',
'강화하면 공격력이 쭉쭉 올라가! 악의만 있으면 돼!':'Parannus nostaa HYÖ:tä! Vain ilkeyttä tarvitaan!',
'강화 확률은 +1에서 99%. 높을수록 떨어진다.':'Parannusmahdollisuus 99% +1:ssä. Laskee.',
'실패하면 악의만 날아가~ 장비는 안 부서져!':'Epäonnistumisessa vain ilkeys menetetään~ Varusteet pysyvät!',
'대장간에서 장비 제작도 된다. 악의 30000개면 영웅급 이상.':'Paja voi myös valmistaa. 30000 ilkeyttä Sankarilliseen+.',
'랜덤이지만 좋은 거 나올 수도 있어!':'Satunnainen, mutta ehkä jotain hyvää!',
'쉴드는 마법으로, HP는 물리로 깎아야 제대로 먹힌다.':'Kilpi tarvitsee taikuutta, HP fyysistä.',
'반대로 치면 50%만 들어가! 무기 바꿔가면서 싸워!':'Väärä tyyppi 50%! Vaihda asetta!',
'장비에 접두사, 접미사가 붙으면 특수 효과가 생긴다.':'Varusteilla etu/jälkiliitteellä erikoistehosteita.',
'영웅급 이상 장비에만 붙어! 좋은 거 나오면 강화해!':'Vain Sankarillisissa+! Paranna hyviä!',
'강화는 장비를 바꿔도 자동 이전된다. 악의만 있으면.':'Parannus siirtyy automaattisesti. Maksaa ilkeyttä.',
'더 좋은 장비 나오면 바로 장착해! 강화 수치 그대로 옮겨가!':'Varusta heti parempi! Parannus siirtyy!',
'패링을 써야 자원을 흡수한다고!':'Torju absorboiman resursseja!',
'F키 회복의 영역을 써봐. 자원이 차올라.':'Kokeile F Pyhä Alue. Resurssit täyttyvät.',
'적이 근접하면 스페이스키야! 가시덫을 활용해!':'Kun viholliset tulevat lähelle, Space! Piikkiansa!',
'기절시켜! 그로기가 터지면 데미지가 1.5배야!':'Tainnuta! Tokkura = 1.5× vahinkoa!',
'1번 대왕치기로 밀어버려!':'1 Jätti-isku työntää taakse!',
'무릎 꿇었다.':'Se polvistuu.',
'지금이야! 몰아쳐!!':'Nyt! Hyökkää!!',
'스킬 포인트 있어! K 눌러서 스킬 찍어봐!':'Taitopisteitä! Paina K!',
'...힘이 없으면 여기서 끝이야.':'...Ilman voimaa tässä se loppuu.',
'...쓸 거 아니면 분해해.':'...Pura mitä et tarvitse.',
'아이템 넘쳐나네~ 우리가 주워줄게!':'Niin paljon esineitä~ Me keräämme!',
'악의가 바닥이다.':'Ilkeys loppu.',
'TAB 열어서 장비 분해해! 쓰레기도 악의가 돼!':'Avaa TAB ja pura varusteita! Romukin on ilkeyttä!',
'좋은 장비가 있네! G 눌러서 대장간 가봐!':'Hyvä varuste! Paina G pajalle!',
'...강화 안 하면 그냥 고철이야.':'...Ilman parannusta pelkkää romua.',
'...멈추지 마. 여신은 기다리지 않는다.':'...Älä pysähdy. Jumalatar ei odota.',
'앞으로 가자~ 나도 여기 오래 있기 싫어.':'Eteenpäin~ En haluakaan jäädä.',
'...냄새가 짙다. 큰 놈이 있어.':'...Haju on tiheä. Jotain isoa.',
'준비됐어? 물약 확인하고!':'Valmis? Tarkista juomasi!',
'TAB을 눌러. 가방을 열고 장비를 입어야 한다.':'Paina TAB. Avaa laukku ja varusta.',
'주웠으면 껴야지! TAB!':'Nostit? Varusta! TAB!',
'G. 대장간에서 물약도 제작할 수 있다.':'G. Pajassa voi valmistaa myös juomia.',
'악의로 물약 만들어! G키야!':'Valmista juomia ilkeydellä! Paina G!',
'기절이야! Ctrl 눌러!':'Tainnutettu! Paina Ctrl!',
'Ctrl 유령걸음으로 탈출!':'Ctrl Haamukävely pakoon!',
'Ctrl 얼음보주로 탈출!':'Ctrl Jääpallo pakoon!',
'빨간 탄은 우클릭 패링. 무지개는 Q 패링.':'Punaiset: oikea klikkaus. Sateenkaari: Q.',
'나머지는 전부 우클릭 패링 가능해!':'Kaikki muu torjuttavissa oikealla!',
'빨강=우클릭, 무지개=Q 패링. 나머진 다 쳐내.':'Punainen=oikea, Sateenkaari=Q. Torju loput.',
'무지개는 Q로 패링! 나머지는 전부 우클릭!':'Sateenkaari Q:lla! Kaikki muu oikealla!',
'빠져! 물약 마시고 안전한 곳에서 회복해.':'Vetäydy! Juo juomia turvallisessa paikassa.',
'자원 없으면 도망가는 게 답이야!':'Ei resursseja? Juokse!',
'스페이스! 가시덫으로 적 묶어버려!':'Space! Piikkiansalla kiinni!',
'근접이 너무 많아! 거리 벌려!':'Liian monta lähitaistelijaa! Etäisyyttä!',
'...둘러싸이면 끝이야. 빠져나와.':'...Piiritetty = ohi. Murtaudu ulos.',
'1번 대왕치기로 쓸어버려!':'1 Jätti-isku pyyhkii!',
'그로기 터지면 데미지 1.5배!':'Tokkura laukaisee 1.5× vahingon!',
'회전참이나 광역기로 몰아! 한 놈씩 상대하면 죽어.':'Käytä pyörremyrskyä tai aluevaikutusta! Yksi kerrallaan kuolet.',
'뭉쳐있을 때가 기회야!':'Kun kasaantuvat = mahdollisuus!',
'E로 마력공격을 해봐! 악의 쉴드를 해제할려면 마법 공격을 해야 해!':'Kokeile E:tä taikaiskuihin! Tarvitset taikuutta ilkeyskilpien murtamiseen!',
'쉴드는 마법으로, HP는 물리로. 반대로 치면 데미지 안 들어간다.':'Kilpi taikuutta, HP fyysistä. Väärä = ei vahinkoa.',
'L키로 스킬 슬롯에 넣어야 쓸 수 있어.':'Paina L asettaaksesi taidot paikkoihin.',
'C키를 눌러. 패시브 포인트가 쌓여있다.':'Paina C. Passiivipisteitä on kertynyt.',
'C키! 패시브 올리면 진짜 강해져!':'C! Passiivit tekevät sinut vahvemmaksi!',
'스태미나가 부족하다. 무리하지 마.':'Vähän kestävyyttä. Älä ylilyö.',
'ST 없으면 스킬 못 써! 잠깐 빠져!':'Ilman ST:tä ei taitoja! Vetäydy!',
'탭 장비창을 열어봐. 아이템을 주워왔어!':'Avaa TAB varustenäkymä. Löysimme esineen!',
'좋은 거 나왔다! TAB 열어서 확인해봐!':'Jotain hyvää putosi! Avaa TAB!',
'악의에 중독되면 악마가 돼서 부활력이 생긴대. 저 녀석처럼.':'Sanotaan ilkeyden riippuvuus tekee demonin herätysvoimin. Kuten tuo.',
'혹시 너도...?':'Ehkä sinäkin...?',
'데미지가 부족하면 무기류 강화를 해야해!!':'Jos vahinko ei riitä, paranna aseitasi!!',
'G키 대장간. 강화 안 하면 여기서 계속 죽어.':'G pajaan. Ilman parannusta kuolet täällä.',
'시간이 없어. 움직여.':'Ei aikaa. Liiku.',
'멍하게 서있으면 안 돼!':'Älä seiso paikallasi!',
'...뭘 기다리는 거야?':'...Mitä odotat?',
'가자가자! 몬스터가 기다려!':'Mennään! Hirviöt odottavat!',
'여기 오래 있으면 위험해.':'Liian kauan tässä on vaarallista.',
'움직여야 해! 가만있으면 둘러싸여!':'Liiku! Paikallaan jäät piiritetyksi!',
'쉬는 건 죽고 나서 해.':'Lepää kuoltuasi.',
'살아있을 때 쉬면 안 돼!':'Ei lepoa eläessä!',
'적이 몰려오고 있어. 빨리 움직여.':'Viholliset lähestyvät. Nopeasti.',
'냄새 맡고 올 거야. 빨리!':'Ne haistavat sinut. Nopeasti!',
'...아직 살아있는 거 맞지?':'...Olet vielä elossa, eikö?',
'혹시 잠든 거야...?':'Nukahditko...?',
'...나무가 썩어가고 있어. 여기는 지옥의 입구야.':'...Puut mätänevät. Tämä on helvetin sisäänkäynti.',
'냄새 지독해... 빨리 지나가자.':'Löyhkä on kamala... Mennään nopeasti.',
'조심해. 벌레굴이다. 벽이랑 바닥에서 기어나와.':'Varovasti. Matojen pesä. Ryömivät seinistä.',
'으으... 벌레 싫어! 밟아버려!':'Yäk... Vihaan ötököitä! Tallaa ne!',
'...공기가 얼어붙는다. 여기선 화염이 먹힌다.':'...Ilma jäätyy. Tuli toimii täällä.',
'추워... 빙결 조심해! 얼면 끝이야.':'Kylmä... Varo jäätymistä! Jäädy ja se on ohi.',
'용암이다. 바닥을 밟으면 타 죽어.':'Laavaa. Astu maahan ja palat.',
'뜨거워! 여기 왜 이렇게 빨개!':'Niin kuuma! Miksi kaikki on punaista!',
'...군단이다. 수가 많아. 광역기 없으면 밀려.':'...Legioona. Liian monta. Ilman aluevaikutusta hukut.',
'우글우글... 징그러워. 한꺼번에 쓸어!':'Ryömii kaikkialla... Ällöä. Pyyhi pois kerralla!',
'사도의 영역이야. 여기 놈들은 머리가 좋아.':'Apostolin alue. Nämä ovat älykkäitä.',
'패턴이 복잡해졌어... 집중해!':'Kaavat monimutkaistuvat... Keskity!',
'...끝이다. 지옥의 심장부. 살아 돌아가는 건 포기해라.':'...Tässä se on. Helvetin sydän. Luovu paluun toivosta.',
'여기가 마지막이야... 각오해.':'Tämä on loppu... Valmistaudu.',
'석궁 자동발사 (T)':'Varsijousi automaattinen (T)',
'버스트루프 당기기 (H)':'Purskesilmukka vetää (H)',
'결정 자동합성':'Kristalli autosynteesi',
'결정 자동강화':'Kristalli autovahvistus',
'✓ 설정 자동 저장':'✓ Asetukset tallennettu automaattisesti',
'세팅 프리셋 저장/불러오기':'Tallenna/lataa esiasetus',
'세팅1 저장':'Tallenna esiasetus 1','세팅1':'Esiasetus 1',
'세팅2 저장':'Tallenna esiasetus 2','세팅2':'Esiasetus 2',
'재진단':'Uudelleendiagnoosi',
'게임 리셋 (처음부터)':'Nollaa peli (alusta)',
'캐릭터 선택 (로비)':'Hahmonvalinta (Aula)',
'닫기 [ESC]':'Sulje [ESC]','닫기 [G]':'Sulje [G]','닫기 [V]':'Sulje [V]','닫기 [C]':'Sulje [C]',
'전체화면 (F11)':'Koko näyttö (F11)',
'정말 모든 진행을 초기화하시겠습니까?':'Haluatko todella nollata kaikki edistymisen?',
'검출 중...':'Havaitaan...',
'마우스 커서':'Hiiren kursori','그래픽 품질':'Grafiikan laatu','하드웨어 진단':'Laitteistodiagnostiikka',
'BGM 선택':'BGM-valinta',
'자동 (스테이지별)':'Automaattinen (vaiheen mukaan)','전체 랜덤':'Kaikki satunnainen','로비':'Aula',
'1장 랜덤':'Luku 1 satunnainen','2장 랜덤':'Luku 2 satunnainen','3장 랜덤':'Luku 3 satunnainen',
'4장 랜덤':'Luku 4 satunnainen','5장 랜덤':'Luku 5 satunnainen','6장 랜덤':'Luku 6 satunnainen','7장 랜덤':'Luku 7 satunnainen',
'보스':'Pomo','최종보스':'Loppupomo',
'대장간 랜덤':'Sepänpaja satunnainen','사망 랜덤':'Kuolema satunnainen','승리 랜덤':'Voitto satunnainen',
'지옥 추락 사망 징글':'Helvetin putoamiskuolema-jingle','탈출 성공':'Pako onnistui',
'── 1장 - 썩은 숲 ──':'── CH1 - Rotten Forest ──','── 2장 - 벌레굴 ──':'── CH2 - Worm Nest ──',
'── 3장 - 얼음굴 ──':'── CH3 - Ice Cavern ──','── 4장 - 화염지대 ──':'── CH4 - Infernal Wastes ──',
'── 5장 - 지옥군단 ──':'── CH5 - Hell Legion ──','── 6장 - 사도마굴 ──':'── CH6 - Apostle Den ──',
'── 7장 - 지옥성 ──':'── CH7 - Hell Citadel ──','── 공통 ──':'── Common ──',
'⌨ 조작법':'⌨ Ohjaimet','클릭하면 닫힘':'Napsauta sulkeaksesi',
'전투력':'TP','가방':'Laukku','결정':'Kristalli',
'↕ 정렬':'↕ Lajittele','쓰레기 전체선택':'Valitse kaikki roska','쓰레기 전부 분해':'Pura kaikki roska',
'창고':'Varasto','스탯 포인트':'Attribuuttipisteet','능력치 요약':'Tilastoyhteenveto','올 리셋':'Nollaa kaikki',
'대장간':'Sepänpaja','스킬':'Taidot','능력치':'Attribuutit',
'좌클스킬 (클릭 전환)':'VMB-taito (napsauta vaihtaaksesi)','우클스킬 (클릭 전환)':'OHB-taito (napsauta vaihtaaksesi)',
'이동스킬 (클릭 전환)':'Liikeystaito (napsauta vaihtaaksesi)','마법스킬 (클릭 전환)':'Taikataito (napsauta vaihtaaksesi)',
'영역스킬 (클릭 전환)':'Aluestaito (napsauta vaihtaaksesi)','피보호막 (클릭 전환)':'Verikilpi (napsauta vaihtaaksesi)',
'CT스킬 (클릭 전환)':'CT-taito (napsauta vaihtaaksesi)','[C] 능력치':'[C] Attribuutit',
'무기 공격':'Asehyökkäys','칼등 처내기 (투사체 반사, 홀드 연사)':'Torjunta (heijastaa ammuks., pidä=sarja)',
'연속 처내기':'Jatkuva torjunta','영역 스킬 (폭풍소환 등)':'Aluestaito (Pyörremyrsky jne)',
'작살 발사':'Ampua harpuuni','마법 (탭=투사체, 홀드=빔)':'Taikuus (napautus=ammus, pidä=säde)',
'데빌포스 흡수':'Absorboida paholaisenvoima','물약 / 스킬슬롯':'Juomat / Taitopaikat',
'스킬슬롯 5 / 필살기 / CT스킬':'Paikka 5 / Loppuhyökkäys / CT-taito','스킬 슬롯 배정':'Paikantarjous',
// --- Phase 27 additions ---
'위로 이동':'Liiku ylös','아래로 이동':'Liiku alas','왼쪽 이동':'Liiku vasemmalle','오른쪽 이동':'Liiku oikealle',
'칼등 처내기 (탭=처내기, 홀드=연사)':'Terän torjunta (napauta=torju, pidä=sarjatuli)',
'영역 스킬':'Aluetaito','작살 이동':'Harpuuni Dash',
'유령불꽃 켜기/끄기':'Haamuflamma Pois/Päällä','기동칼날개 자동 켜기/끄기':'Terässipi Auto Pois/Päällä',
'해상도':'Resoluutio',
'빛이 꺼졌다':'Valo Sammuu','누군가는 너를 기다리고 있다':'Joku odottaa sinua',
'다시 일어서라':'Nouse uudelleen','로비로 돌아가기':'Palaa Aulaan',
'☠ 사망 리플레이':'☠ Kuolemantoisto',
'지옥의 시련을 견뎌냈다':'Olet kestänyt Helvetin koettelemuksen',
'계속 전투':'Jatka taistelua','난이도를 선택하라':'Valitse vaikeustaso',
'나중에 설정(ESC)에서 변경 가능':'Voidaan muuttaa Asetuksissa (ESC) myöhemmin',
'일괄합성':'Massasynteesi','일괄강화+합성':'Massaparannnus+Synteesi',
'자원 부족!':'Resurssit Vähissä!',' 뎀':' Vah',
'합체 폭발!':'Fuusiodetonaatio!',
'MP 부족! (50)':'Ei tarpeeksi MP! (50)',
'부활력 고갈!':'Ylösnousemus Loppu!','☠ 부활력 고갈!':'☠ Ylösnousemus Loppu!',
'독안개':'Myrkkyusva','뇌전창':'Ukkoskeihäs',
'🔥 업화선 시전...':'🔥 Helvetinsäde lataus...',
'💥 기동파괴 그로기!':'💥 Ketjumurskaus Groggy!',
'💥 칼등 그로기!':'💥 Terätorjunta Groggy!',
'⚡ 순간이동 준비!':'⚡ Teleportaatio Valmis!',
'👿악의+1000':'👿Pahuus+1000',
'💀 내려찍기!':'💀 Alashakku!',
'✟ 신성력 억제! +':'✟ Pyhä Voima Tukahdutettu! +',
'✟ 신성력 억제!':'✟ Pyhä Voima Tukahdutettu!',
'✟ 신성력 억제! (':'✟ Pyhä Voima Tukahdutettu! (',
'💥 지진그로기!':'💥 Maanjäristys-Groggy!',
'💥 기폭그로기!':'💥 Detonaatio-Groggy!',
'폭발! ×':'Räjähdys! ×','⚫ 기둥강타!':'⚫ Pylväshakku!',
'💥 대왕치기 그로기!':'💥 Kolosseaalinen Groggy!',
'💫 미니스턴!':'💫 Mini Stun!','⚡ 뇌전창!':'⚡ Ukkoskeihäs!',
'…절반이다. 정신차려.':'…Puolet jäljellä. Kerää itsesi.',
'…죽기 직전이다. 한 발만 더.':'…Melkein kuollut. Yksi isku lisää.',
'…다음 한 방이 마지막이야.':'…Seuraava isku on viimeinen.',
'기절! ':'Tainnoksissa! ',
'마력이 빈다. 평타 섞어.':'MP loppuu. Sekoita normaali-iskuja.',
'그랩이다. 거리를 둬.':'Tartuntahyökkäys. Pidä etäisyyttä.',
'광역기다. 멀어져.':'Aluehyökkäys. Mene kauemmas.',
'…아파? 당연하지. 여긴 지옥이야.':'…Sattuu? Tietysti. Tämä on helvetti.',
'F키도 스킬 슬롯이야!':'F on myös taitopaikka!',
'L-CTRL로 유령걸음/얼음보주!':'L-CTRL Haamuaskeleille / Jääkuulalle!',
'V 눌러서 창고에 넣어둬!':'Paina V tallentaaksesi!',
'ESC로 설정! 난이도/자동물약!':'ESC asetuksiin! Vaikeus/Autojuomat!',
'잡몹이다. 먼저 정리해.':'Tavalliset viholliset. Siivoa ne ensin.',
'…얼어붙은 놈은 오래 안 간다.':'…Jäätynyt vihollinen ei kestä kauan.',
'…냄새가 짙다. 큰 놈이 있어.':'…Haju on vahva. Jotain isoa on lähellä.',
'쉴드는 마법으로, HP는 물리로.':'Kilpi ottaa taikaa, HP ottaa fyysistä.',
'스페이스! 가시덫으로 적 묶어!':'Välilyönti! Sidota viholliset Piikkiansalla!',
'근접 너무 많아! 거리 벌려!':'Liikaa lähellä! Hajaannu!',
'회전참이나 광역기로 몰아!':'Käytä Pyörräiskua tai Alue-iskua!',
'F 눌러! 회복의 영역 깔아!':'Paina F! Aseta Pyhä Alue!',
'F키 회복의 영역을 써봐.':'Kokeile F-näppäin Pyhää Aluetta.',
'빠져! 물약 마시고 회복해.':'Peräänny! Juo juomia ja toivu.',
'쉬프트! 사슬기동은 이동기야!':'Shift! Ketjudash on liikkumistyökalu!',
'스킬포인트 쌓였어! K 눌러!':'Taitopisteitä kertynyt! Paina K!',
'스킬 포인트 있어! K!':'Taitopisteitä! K!',
'C키. 패시브 포인트가 쌓여있다.':'C-näppäin. Passiivipisteitä on kertynyt.',
'…쓸 거 아니면 분해해.':'…Pura mitä et aio käyttää.',
'…강화 안 하면 그냥 고철이야.':'…Ilman parannusta se on pelkkää romua.',
'빨간 탄은 우클릭. 무지개는 Q.':'Punaiset ammukset: hiiren oikea. Sateenkaari: Q.',
'빨강=우클릭, 무지개=Q.':'Punainen=oikea hiiri, sateenkaari=Q.',
'…멈추지 마. 여신은 기다리지 않는다.':'…Älä pysähdy. Jumalatar ei odota.',
'패턴이 바뀐다. 거리를 둬.':'Kaava muuttuu. Pidä etäisyyttä.',
'미쳐가고 있어. 광폭화다.':'Se menee hulluksi. Raivotila.',
'마지막이야! 끝장내!':'Viimeinen vaihe! Lopeta se!',
'…끝났다. 다음으로.':'…Valmis. Eteenpäin.',
'다 잡았다! 포탈 어딨어?':'Kaikki kiinni! Missä portaali on?',
'근육으로 만든 빌드군. 베고 부숴.':'Lihasrakenne. Leikkaa ja murskaa.',
'활을 쥐었군. 거리를 둬.':'Jousi kädessä. Pidä etäisyyttä.',
'마법사군. MP 관리부터 배워라.':'Taikuri. Opettele ensin MP-hallinta.',
'운에 기댄 빌드군. …드롭은 좋겠어.':'Onnekas rakenne. …Ainakin tipot ovat hyviä.',
'…VIT가 너무 낮아. 한 방에 죽는다.':'…VIT on liian matala. Kuolet yhteen iskuun.',
'다 찍으면 다 약해진다. 하나만 골라.':'Maksimoide kaikki ja olet heikko kaikkialla. Valitse yksi.',
'…3단. 적이 강해져. 정신 차려.':'…Taso 3. Viholliset vahvistuvat. Keskity.',
'5단이다. …너도 강해졌단 뜻이야.':'Taso 5. …Se tarkoittaa että sinäkin olet vahvistunut.',
'…7단. 아직 살아있단 게 신기하군.':'…Taso 7. Yhä elossa. Yllättävää.',
'10단. …너는 이제 인간이 아니야.':'Taso 10. …Et ole enää ihminen.',
'…일반으로 내려왔군. 가끔은 쉬어가야지.':'…Takaisin Normaaliin. Joskus tarvitsee tauon.',
'…이게 진짜 패링이야.':'…Se on aito torjunta.',
'…피가 묻기 시작했군.':'…Veri alkaa valua.',
'100. 너는 인간이 아니야.':'100. Et ole ihminen.',
'…피 흘리며 베는군.':'…Leikkaa veren läpi.',
'빨간콩이 푸르게 변했다. 그게 너의 무기야.':'Punainen kuula muuttui siniseksi. Se on aseesi.',
'무지개를 받아쳤군. 그건 진짜 어렵다.':'Torjuit sateenkaaren. Se on todella vaikeaa.',
'…너무 빨라. 닿기 직전에 눌러.':'…Liian nopea. Paina juuri ennen kosketusta.',
'악의가 가득 찼다. 풀어내.':'Pahuus on täynnä. Vapauta se.',
'작살이 살을 뚫었어. 끌고 와.':'Harpuuni lävisti lihan. Vedä se sisään.',
'…풀차지군. 멀리 던져버려.':'…Täyteen ladattu. Heitä kauas.',
'…빈틈을 그대로 빠져나갔다.':'…Liukui suoraan aukon läpi.',
'…일반 잡몹이 아니야. 모디파이어 붙었군.':'…Ei tavallinen vihollinen. Sillä on modifikaattori.',
'엘리트 하나 처리.':'Eliitti alas.',
'…큰 놈이다. 일반 잡몹 정리부터.':'…Iso yksi. Siivoa tavalliset viholliset ensin.',
'미니보스 처리. 다음 길로.':'Mini-bossi alas. Seuraavalle tielle.',
'한 번에 다섯. 깔끔해.':'Viisi kerralla. Siististi.',
'100강. 이제 뭔가 다르게 보이는군.':'+100. Asiat näyttävät erilaisilta nyt.',
'…운이 없는 날이야.':'…Huono onni tänään.',
'…전설이다. 이런 건 처음 본다.':'…Legendaarinen. En ole koskaan nähnyt sellaista.',
'…죽었다 살아났네. 여신은 너를 포기 안 했어.':'…Kuoli ja palasi. Jumalatar ei luovuttanut sinusta.',
'…또야? 패턴 좀 외워!':'…Taas? Opettele kaava!',
'…한 번도 안 죽고. 그건 진짜 실력이야.':'…Ei kertaakaan kuollut. Se on todellista taitoa.',
'…ACT1을 끝냈다. 진짜 시작은 여기서부터야.':'…ACT1 valmis. Todellinen alku on täältä.',
'모든 보스를 무너뜨렸다. 너는 지옥의 일부야.':'Kaikki bossit kaatuivat. Olet osa helvettiä.',
'…30초. 너 진짜 미쳤구나.':'…30 sekuntia. Olet todella hullu.',
'…빠르군. 효율적이야.':'…Nopea. Tehokas.',
'신기록이다.':'Uusi ennätys.',
'탭 장비창을 열어봐.':'Avaa varusteikkuna TAB:lla.',
'데미지 부족하면 무기 강화!':'Ei tarpeeksi vahinkoa? Paranna asettasi!',
// --- Loading screen ---
'불러오는 중...':'Ladataan...',
'로딩중...':'Ladataan...',
'맵과 몬스터 불러오는 중...':'Ladataan karttaa ja hirviöitä...',
'기본 데이터 준비 중...':'Valmistellaan perustietoja...',
'저장 데이터 불러오는 중...':'Ladataan tallennustietoja...',
'몬스터 스킨 로딩...':'Ladataan hirviöiden skinnit...',
'맵과 몬스터 생성 중...':'Luodaan karttaa ja hirviöitä...',
'맵 에셋 로딩...':'Ladataan kartan resursseja...',
'맵 환경 준비 중...':'Valmistellaan kartan ympäristöä...',
'주변 청크 준비 중...':'Valmistellaan läheisiä chunkkeja...',
'맵 캐시 생성 중...':'Rakennetaan kartan välimuistia...',
'미니맵 빌드 중...':'Rakennetaan minikarttaa...',
// Phase 28
' 으로 탈출!':' — pakene!',
'100명?! 미쳤어!':'100 tappoa?! Hullua!',
'10단 최고난이도! 너 진짜 광기야!':'Vaikeus 10 maks! Täysin hullu!',
'1분 안에 클리어! 빠르네!':'Kenttä läpi 1 min! Niin nopeasti!',
'30초!! 스피드런 가능해!':'30 sekuntia!! Speedrun-potentiaali!',
'3단! 보상도 좋아지지만 죽기 쉬워!':'Vaikeus 3! Paremmat palkinnot mutta helpompi kuolla!',
'50명! 학살자야!':'50 tappoa! Teurastaja!',
'5단!! 진짜 게이머 인증!':'Vaikeus 5!! Aito pelaaja sertifioitu!',
'7단!! 다른 사람들 이 정도 못 와!':'Vaikeus 7!! Muut eivät pääse näin pitkälle!',
'ACT1 완주! 우리가 진짜 해냈어!':'AKT 1 valmis! Me todella teimme sen!',
'Ctrl 얼음보주로 탈출하라.':'Ctrl — pakene Jääkuulalla.',
'Ctrl 유령걸음으로 탈출하라.':'Ctrl — pakene Aavekävelyllä.',
'C키! 패시브 강해져!':'C-näppäin! Passiiviset vahvistuvat!',
'DEX 빌드! 거리에서 패고, 추적탄 좋아!':'DEX-build! Etäisyysiskut, seuraavat ammukset!',
'E로 마력공격을 해봐!':'Kokeile taikahyökkäystä E:llä!',
'G 눌러서 대장간 가봐!':'Paina G — paja!',
'G키 대장간. 강화 안 하면 계속 죽어.':'G — paja. Ei päivityksiä, jatkuvaa kuolemista.',
'HP 70%! 조심해!':'HP 70%! Ole varovainen!',
'INT 빌드! 빔이랑 폭발 마법! MP 잘 봐!':'INT-build! Säteet ja räjähtävä magia! Katso MP!',
'LCK 높아! 레어 드롭률 미친 거 알지?':'Korkea LCK! Harvinaisten putoamismahdollisuudet ovat hullut!',
'L로 어디에 뭘 넣을지 골라!':'Paina L — valitse taitopaikka-asettelu!',
'MP 부족! 평타로 패면서 회복해!':'MP vähissä! Lyö palautuaksesi!',
'ST 없으면 스킬 못 써!':'Ei ST, ei taitoja!',
'STR 빌드! 회전참, 회오리, 광역기 추천!':'STR-build! Pyörähyökkäys, pyörremyrsky, AoE!',
'VIT 좀 찍어! HP 너무 적어!':'Lisää VIT! HP liian vähäinen!',
'Z 누르면 대박! 쿨타임 길어!':'Paina Z ultimatelle! Pitkä jäähtymisaika!',
'…고기 냄새. 싫진 않네.':'…Veren tuoksu. Ei paha.',
'…둘러싸이면 끝이야.':'…Ympäröity tarkoittaa kuolemaa.',
'…말은 못해.':'…En voi puhua.',
'…버리기 아까운 건 창고에.':'…Arvokkaat tavarat varastoon.',
'…빈틈을 노려.':'…Odota aukkoja.',
'…설정을 확인해.':'…Tarkista asetukset.',
'…슬롯을 채워. 빈 손은 죽음이다.':'…Täytä paikat. Tyhjät kädet ovat kuolema.',
'…아직 살아있네. 좌클릭으로 저것들 쳐봐.':'…Yhä elossa. Napsauta vasemmalla lyödäksesi heitä.',
'…운이 좋았을 뿐이야. 아마.':'…Vain tuuria. Todennäköisesti.',
'…치는 건 할 줄 아네. 피하는 건?':'…Voi lyödä. Voiko väistää?',
'…힘을 골라라. 전부 가질 순 없다.':'…Valitse voimasi. Et voi omistaa kaikkea.',
'골고루 안 돼! 하나로 밀어!':'Älä hajauta! Panosta yhteen!',
'그로기 터지면 1.5배!':'Groggy = 1,5x vahinko!',
'길이 열렸다.':'Polku on auki.',
'나머진 전부 우클릭 패링 가능!':'Loput — oikea napsautus paree!',
'나머진 전부 우클릭!':'Loput — oikea napsautus!',
'다섯 번 연속! 내가 본 인간 중 최고!':'Viisi peräkkäin! Paras jonka olen nähnyt!',
'다음엔 죽지 마!':'Älä kuole seuraavalla kerralla!',
'더블탭 전격이동으로 탈출하라.':'Tuplanapauta dash paetaksesi.',
'소환수 왔어! 먼저 처리해야 해!':'Kutsutut! Selvitä ne ensin!',
'스킬 없으면 방향키 연타뿐이야.':'Ei taitoja? Vain spämmää nuolinäppäimiä.',
'신기록!! 스트리머한테 보내!':'Uusi ennätys!! Lähetä striimaajaalle!',
'아이템 넘쳐! 우리가 주워줄게!':'Laukku täynnä! Me poimimme sinulle!',
'안 죽고 깼어! 진짜 천재 맞네!':'Läpäisty ilman kuolemia! Aito nero!',
'앞으로 가자~':'Mennään eteenpäin~',
'우리가 해냈어! 다음 챕터 가자!':'Me teimme sen! Seuraava luku!',
'일반 모드! 편하게 즐기자!':'Normaali tila! Nauti rauhassa!',
'자원이 반이다. F키로 회복해.':'Resurssit puoliksi. Paina F palautuaksesi.',
'잡힌다! 옆으로 빠져!':'Otetaan kiinni! Väistä sivulle!',
'장비 분해해! 쓰레기도 악의!':'Pura varusteet! Roskakin antaa pahuutta!',
'전부 다 잡았어! 우리가 지옥의 왕이야!':'Kaikki selvitetty! Helvetin kuninkaat!',
'좋은 거 나왔다! TAB!':'Hyvää lootia! TAB!',
'죽기 직전에 죽이다니! 멋져!':'Tappo juuri ennen kuolemaa! Upeaa!',
'체력 반 남았어! 물약 마실 타이밍!':'Puolet HP! Juoma-aika!',
'큰 거 온다! 도망쳐!':'Iso hyökkäys! Juokse!',
'패링으로 돌려주고, Q 보호막도 써!':'Paree ja heijasta, käytä Q-kilpeä!',
'패턴이 빨라졌어!':'Kaavat nopeutuivat!',
'한 대만 맞아도 죽어! 패링이든 회피든!!':'Yksi osuma = kuolema! Paree tai väistä!!',
'한 방이면 죽어! 도망쳐!!':'Yksi laukaus tappaa! Juokse!!',
'화염엔 빙결! 암전엔 암흑!':'Tuli → pakkanen! Tyhjyys → varjo!',
'👻 유령!':'👻 Haamu!',
'🦴 해골무덤!':'🦴 Luuhautu!',
'── 2장 - 벌레굴 ──':'── CH2 - Worm Nest ──',
'── 4장 - 화염지대 ──':'── CH4 - Infernal Wastes ──',
'── 6장 - 사도마굴 ──':'── CH6 - Apostle Den ──',
'── 공통 ──':'── Common ──',
'난이도를 선택하라':'Valitse vaikeustaso',
'☠ 부활력 고갈!':'☠ Herääminen Käytetty!',
'⏳⚡ 시간걸음!':'⏳⚡ Aikaaskel!',
'블룸 효과':'Bloom-efekti',
'잔상 트레일':'Jälkikuvaraita',
'슬래시 이펙트':'Viiltoefekti',
'후처리 효과':'Jälkikäsittely',
'사망 이펙트':'Kuolinefekti',
'동적 조명':'Dynaaminen valaistus',
'횃불 조명 (어둠)':'Soihtuvalot (pimeys)',
'앰비언트 파티클':'Ympäristöhiukkaset',
'안개 효과':'Sumuefekti',
'필름 그레인':'Filmijyvä',
'캐릭터 외곽선':'Hahmon ääriviiva',
'리롤':'Heita uudelleen',
'물약':'Juoma',
'으로 탈출!':'paetaksesi!',
'Shift 작살':'Shift Harppuuna',
'더블탭 전격이동':'Kaksoisnäppäys — Salama-piikata',
'Ctrl 유령걸음':'Ctrl Aaveaskellus',
'Ctrl 얼음보주':'Ctrl Jääpallo',
'🔴화염→빙결 2배 | 🔵빙결→화염 2배 | ⚪물리=중립 | 악마 처치 시 악의 영혼 드롭':'🔴Tuli→Jää 2× | 🔵Jää→Tuli 2× | ⚪Fys=Neutraali | Tapa demoneja pahuuden sieluista',
  '미구현':'N/A',
  '스탯 총량':'Kokonaistilastot',
  '장비':'varustus',
  '공속':'hyökkäysnopeus',
  '크리':'kriitti',
  '크리뎀':'kriittivahinko',
  '근성':'Sitkeys',
  '종합 지표':'Yleiskatsaus',
  '근접 DPS':'Lähitaistelu DPS',
  '공격력×공속×크리':'ATK×Nop×Krit',
  '활 DPS':'Jousi DPS',
  '마법 DPS':'Taika DPS',
  '유효 HP (EHP)':'Tehokas HP (EHP)',
  '쉴드':'Kilpi',
  '장비 파워':'Varustuksen voima',
  '근접 공격력':'Lähitaistelu ATK',
  '기본':'perus',
  '무기':'ase',
  '패시브':'passiivinen',
  '활 공격력':'Jousi ATK',
  '정밀':'Tarkkuus',
  '마법 공격력':'Taika ATK',
  '왕관':'kruunu',
  '마력':'Arkaani',
  '공격속도':'Hyökkäysnopeus',
  '크리티컬':'Kriittinen',
  '데미지':'vahinko',
  '확률':'Todennäköisyys',
  '어픽스':'affiksi',
  '레거시':'perintö',
  '추가뎀':'lisävahinko',
  '패링 카운터뎀':'Torjunta vastaiskuvahinko',
  '우클공속':'Oikea klikin nopeus',
  '무지개탄DR':'Sateenkaari DR',
  '포이즈파괴':'Rikkoa Poise',
  '방어관통':'Haarniston läpäisy',
  '관통력':'Läpäisykyky',
  '속성':'Elementit',
  '무기속성':'Aseen elementti',
  '독':'Myrkky',
  '초':'s',
  '암흑저주':'Pimeä kirous',
  '원소집중':'Elementtifokus',
  '원소전환':'Elementtimuunnos',
  '방어':'Puolustus',
  '물리방어':'Fyysinen puolustus',
  '감소':'vähenee',
  '캡':'raja',
  '장갑':'käsineet',
  '바지':'housut',
  '속성방어':'Elementtipuolustus',
  '목걸이':'kaulakoru',
  '반지1':'sormus1',
  '반지2':'sormus2',
  '반사':'Heijastus',
  '가시':'Piikit',
  '배리어':'Este',
  '보호막 흡수':'Kilven absorptio',
  '속성 저항':'Elementtivastustus',
  'CC저항':'CC-vastustus',
  '생존':'Eloonjääminen',
  '장비HP':'Varustus HP',
  '임플':'Impl.',
  '에너지쉴드':'Energiakilpi',
  '리젠':'Regen',
  '스태미나':'Kestävyys',
  '성장':'Kasvu',
  'MP%어픽스':'MP%-affiksi',
  '이동속도':'Liikkumisnopeus',
  '한방캡':'Yksiosuma-raja',
  '최대HP의33%':'33% Max HP',
  '비용/효율':'Kustannus/Teho',
  '근접ST':'Lähitaistelu ST',
  '활ST':'Jousi ST',
  '마법MP':'Taika MP',
  '작살사거리':'Harppunan kantama',
  '기동게이지':'Drive-mittari',
  '쿨감':'CDR',
  '쇠뇌뎀':'Varsijousivahinko',
  '쇠뇌공속':'Varsijousinopeus',
  '기타':'Muut',
  '물약쿨':'Juoma-CD',
  '회복+':'Toipuminen+',
  '드롭':'Drop',
  '경험치+':'EXP+',
  '골드+':'Kulta+',
  '기동:칼날개':'Drive:Terä',
  '기동:전폭':'Drive:Isku',
  '기동:기습':'Drive:Väijytys',
  '충전스킬':'Lataustaito',
  '사슬게이지':'Ketju-mittari',
  '특수 효과':'Erikoisefektit',
  '처치뎀+':'Tappovahinko+',
  '위기뎀+':'Kriisivahinko+',
  '피격반격':'Osuma-vastaisku',
  '풍요(적HP≥70%뎀+)':'Runsaus(HP≥70%+)',
  '약자포식(적HP≤30%뎀+)':'Saalistaja(HP≤30%+)',
  '패링폭발':'Torjuntaräjähdys',
  '체간파괴+':'Rikkoa Poise+',
  '콤보뎀+':'Kombovahinko+',
  '작살뎀+':'Harppunahtavahinko+',
  '스킬뎀+':'Taitovalhinko+',
  '패리+':'Torjunta+',
  '체인':'Ketju',
  '정화':'Puhdistus',
  '회':'×',
  '불굴':'Sinnikkyys',
  '신성력':'Pyhä voima',
  '악마력(부활력)':'Demonin voima',
  '자연':'Luonto',
  '악마성':'Demonisuus',
  '인간성':'Ihmisyys',
  '전투 통계':'Taistelustatistiikka',
  '핵터':'Hecter',
'디로이':'Deroy',
'물리 ATK +1, MAX HP +5, HP리젠 +0.002':'Phys ATK +1, MAX HP +5, HP regen +0.002',
'석궁 ATK +1, 공격속도 +0.05%, MAX ST +2, ST리젠 +0.005, 회피 +0.05%':'Bow ATK +1, ATK speed +0.05%, MAX ST +2, ST regen +0.005, Dodge +0.05%',
'마법 ATK +1, MAX MP +2, MP리젠 +0.005, MAX 쉴드 +5':'Magic ATK +1, MAX MP +2, MP regen +0.005, MAX Shield +5',
'크리확률 +0.025%, 크리뎀 +0.2%, 드롭률 +0.15%':'Crit rate +0.025%, Crit DMG +0.2%, Drop rate +0.15%',
'근접뎀 +15%, ST비용 -4%/lv (최대-40%)':'Melee DMG +15%, ST cost -4%/lv (max -40%)',
'작살 사거리 +2%/lv, 기동게이지 회복 +3%/lv':'Harpoon range +2%/lv, Mobility gauge recovery +3%/lv',
'카운터뎀 +50%/lv, 우클릭 공속 +10%/lv, 무지개탄 피해감소 +10%/lv (최대50%)':'Counter DMG +50%/lv, RMB ATK speed +10%/lv, Rainbow shot DMG reduction +10%/lv (max 50%)',
'마법뎀 +15%, MP비용 -4%, 시전속도 +8%/lv':'Magic DMG +15%, MP cost -4%, Cast speed +8%/lv',
'투사체뎀 +15%, 공속 +10%, 사거리 +8%, ST비용 -4%/lv':'Projectile DMG +15%, ATK speed +10%, Range +8%, ST cost -4%/lv',
'보호막 흡수 +2%/lv (기본70→최대90%), 보호막 중 HP리젠 +0.1%/lv':'Shield absorb +2%/lv (base 70 to max 90%), HP regen during shield +0.1%/lv',
'HP/ST리젠 +3%/lv, 물약쿨 -3%/lv':'HP/ST regen +3%/lv, Potion cooldown -3%/lv',
'크리률 +2%, 크리뎀 +8%/lv':'Crit rate +2%, Crit DMG +8%/lv',
'아이템 드롭률 +8%/lv':'Item drop rate +8%/lv',
'투사체 관통률 +5%/lv, 관통횟수 +1/lv, 관통뎀감소 완화':'Projectile pierce rate +5%/lv, Pierce count +1/lv, Pierce DMG falloff reduced',
'MP리젠 +3%/lv, 쉴드리젠 +3%/lv, 쉴드쿨 -3%/lv':'MP regen +3%/lv, Shield regen +3%/lv, Shield cooldown -3%/lv',
'자동쇠뇌 뎀 +5%/lv, 공속 +5%/lv':'Auto crossbow DMG +5%/lv, ATK speed +5%/lv',
'물리뎀 +15%/lv, HP +3%/lv, ST소모 -5%/lv':'Phys DMG +15%/lv, HP +3%/lv, ST cost -5%/lv',
'적에게 약점노출 디버프. 직접 공격 시 스택+1, 스택당 피격뎀 +3%. 최대 Lv×5 중첩 (1렙5, 10렙50). 초당 20% 감소, 5초 미피격 시 리셋. DOT/장판 제외':'Weakness debuff on enemies. +1 stack per direct hit, +3% DMG/stack. Max Lv×5 (Lv1=5, Lv10=50). -20%/s decay, reset after 5s. DOT excluded',
'물리→쉴드 패널티 관통 +5%/lv (기본10%, 10lv=60%)':'Phys to Shield penalty pierce +5%/lv (base 10%, lv10=60%)',
'마법→HP 패널티 관통 +5%/lv (기본10%, 10lv=60%)':'Magic to HP penalty pierce +5%/lv (base 10%, lv10=60%)',
'적 HP 70%↑: 뎀+20%/lv, 회복력+5%/lv (합연산)':'Enemy HP≥70%: DMG+20%/lv, Recovery+5%/lv (additive)',
'적HP 30%↓: 뎀+20%/lv. 내HP 30%↓: 회복력+10%/lv, 이속+5%/lv (합연산)':'Enemy HP≤30%: DMG+20%/lv. My HP≤30%: Recovery+10%/lv, Move SPD+5%/lv (additive)',
'DOT 틱뎀 +15%/lv, DOT 지속시간 +10%/lv, DOT 축적률 +5%/lv':'DOT tick DMG +15%/lv, DOT duration +10%/lv, DOT pool rate +5%/lv',
'MP +50/lv, MP회복 +1%/lv':'MP +50/lv, MP regen +1%/lv',
'ST +50/lv, ST회복 +1%/lv':'ST +50/lv, ST regen +1%/lv',
'악의 드롭 +8%/lv':'Malice drop +8%/lv',
'HP +300/lv':'HP +300/lv',
'DEF +20/lv':'DEF +20/lv',
'엘리트/보스 추가뎀 +10%/lv':'Elite/Boss bonus DMG +10%/lv',
'부활력 -10/lv, 전체 데미지 +5%/lv, HP/MP/ST +100/lv':'Revive power -10/lv, All DMG +5%/lv, HP/MP/ST +100/lv',
'부활확률 +2%/lv, 부활HP +5%/lv, 부활쿨 -30초/lv':'Revive chance +2%/lv, Revive HP +5%/lv, Revive CD -30s/lv',
// --- Phase 37: skill desc ---
'핵심 광역기 — 먼저 배워서 정리력 확보':'Core AoE — learn first for mob clearing',
'악의 사냥 + 보호자 → 합체: 칼날 해방':'Malice Hunt + Guardian → Fuse: Blade Liberation',
'폭독혈 추가 → 합체: 독혈 해방 (칼날+독)':'Plague Burst → Fuse: Plague Liberation (blade+poison)',
'충돌+화염 → 합체: 사슬기동 (무적이동 핵심)':'Impact+Flame → Fuse: Chain Breach (invincible dash core)',
'사슬 체인 확장 → 기동:파쇄/기동:전폭':'Chain expansion → Slam/Thunder combos',
'필살기 1개 선택! 신성폭발(넉백) / 블랙(흡인) / 용암(화상) / 처형(보스킬)':'Pick 1 ultimate! Holy Blast(knockback) / Black Star(pull) / Lava(burn) / Execution(boss kill)',
'멸살광선+만화방창+원소추적탄+전격이동 → 합체: 추적빔':'Omni Beam+Barrage+Elem Missile+Blink → Fuse: Tracking Beam',
'회전참+기폭+대왕치기 → 합체: 지진폭풍':'Whirlwind+Detonate+Giant Slam → Fuse: Slam Storm',
'칼등치기 + 칼등날개 → 합체: 처내기 강화':'Blade Parry + Shield Wing → Fuse: Parry Enhanced',
'해골무덤 + 악의폭풍 → 합체: 해골번개':'Bone Wall + Malice Storm → Fuse: Bone Lightning',
'폭풍소환 + 얼음보주 → 합체: 얼음폭풍':'Malice Mortar + Ice Orb → Fuse: Ice Mortar',
'유령화 이동 + 전기 폭발':'Ghost phase movement + electric burst',
'회복 + 구속 → 합체: 결계의 영역':'Recovery + Prison → Fuse: Ward Domain',
'지진폭풍+추적암전 → 6단합체: 폭풍빔':'Slam Storm → 6-Fuse: Storm Beam',
'아이스스톰 추가 → 합체: 신성빙결':'Ice Storm → Fuse: Holy Ice',
'암흑기둥 + 가시덫 → 합체: 기둥가시. 대왕치기2는 기둥강타/지옥강타용':'Dark Pillar + Spike Trap → Fuse: Pillar Spike. Giant Slam 2 for Pillar Slam/Inferno Slam',
'기동칼날개 추가 → 5단합체: 기동:칼날개':'Chain Bladewing → 5-Fuse: Maneuver:Bladewing',
'STR 스케일. 3회 충전 + Lv3마다 사거리 1단계↑(최대4단). 이동 중 무적, 통과 적에 데미지+그로기 (쿨 5초)':'STR scale. 3 stocks + range tier up every Lv3 (max 4). Invincible while moving, DMG+groggy on pass-through (CD 5s)',
'INT 스케일. 이동 경로에 화염길 생성(3초 DOT). 통과 적 화상. MP 소모. 합체 시 착지 폭발':'INT scale. Fire trail on dash path (3s DOT). Burns passed enemies. MP cost. Fuse: landing explosion',
'5초간 유령화 — 무적+이동. 통과한 적/탄막 수만큼 종료 시 암전 폭발(+10%/회) + 전기줄기 방사(3회 체인). 카운트 캡=Lv×5(최대50). 쿨 20초. Lv당 뎀+15% 범위+10':'5s ghost form — invincible+move. Blackout explosion on end (+10%/enemy passed) + lightning arc (3 chains). Count cap=Lv×5 (max 50). CD 20s. Per Lv DMG+15% range+10',
'[이동기] 방향키 더블탭으로 발동. 경직/기절 중에도 탈출 가능. 500유닛 순간이동, 무적(15프레임). MP(10+Lv×5). 1렙10충전, 렙당+1. 쿨 8초→Lv당-0.5초(최소3초). 착지 시 전류장판(10초+Lv×0.5초): INT 틱뎀 + 방어력↓(1렙10%, 렙당+5%, 캡50%)':'[Mobility] Double-tap to activate. Escapes stagger/stun. 500-unit blink, invincible 15f. MP(10+Lv×5). Lv1=10 stocks, +1/Lv. CD 8s→-0.5s/Lv (min 3s). Landing shock field(10s+Lv×0.5s): INT tick DMG + DEF↓(Lv1=10%, +5%/Lv, cap 50%)',
'좌클 스킬: 기본공격에 3단 콤보 초승달 검기 추가. ST 10+Lv당2. Lv당 뎀+10% 거리+15px':'LMB skill: adds 3-hit crescent ki blade combo to basic attack. ST 10+2/Lv. Per Lv DMG+10% range+15px',
'[기본: E] 어둠 마법 오브 발사. 범위폭발. 넉백 0.5%. Lv당 크기+50% (뎀은 _skMul 계수 적용)':'[Default: E] Dark magic orb fired. AoE explosion. Knockback 0.5%. Per Lv size+50% (DMG uses _skMul)',
'무기 홀드 → 전진 회전 공격. 360도 광역, ST 지속소모. Lv당 범위+5 뎀+5%':'Hold weapon → forward spin attack. 360° AoE, continuous ST drain. Per Lv range+5 DMG+5%',
'패링 3초 홀드 → 흡수 데미지 광역 폭발. Lv당 범위+15 (1렙150, 10렙285)':'Parry 3s hold → absorbed DMG AoE explosion. Per Lv range+15 (Lv1: 150, Lv10: 285)',
'우클 처내기 강화. Lv당 반사 데미지 +10%. 홀드 시 연사':'RMB swipe enhanced. Per Lv reflect DMG +10%. Hold for rapid fire',
'[고정: T 자동] 물리 바늘 3방향 3발 발사. 관통 없음':'[Fixed: T auto] 3 physical needles 3-way spread. No pierce',
'[고정: E] 1발 직선 레이저. +만화방창 → 만화광선(3발 꽈배기). +원소추적탄 → 추적암전(6발 유도)':'[Fixed: E] 1 straight laser. +Barrage → Omni Beam (3 spiral). +Elem Seeker → Homing Dark (6 homing)',
'E탭 마법을 6원소 유도 미사일로 변경. 곡선 궤적으로 적을 추적. 레벨당 사거리+20 (뎀은 _skMul 계수 적용)':'Changes E-tap magic to 6-element homing missiles. Curved trajectory tracking enemies. Per Lv range+20 (DMG uses _skMul)',
'3초마다 악의 구체 생성(1렙 2개). 몸에 밀착하여 적 투사체를 자동 방어(파괴). 레벨당 구체+1':'Spawns malice orbs every 3s (Lv1: 2 orbs). Orbits body, auto-blocks (destroys) enemy projectiles. Per Lv orb+1',
'유도 물리 칼날 1발 (악의30+ST50). 관통률 800+Lv×20+장비. 지속뎀 5초. 쿨 15초':'1 homing physical blade (malice 30 + ST 50). Pierce 800+Lv×20+gear. DOT 5s. CD 15s',
'어둠 소용돌이 소환 (마우스 조준 설치, MP 소모, 쿨 11초, INT 스케일링, 1렙 200범위 +30/렙, 5초 지속, 적 흡인)':'Summon dark vortex (mouse-aim placement, MP cost, CD 11s, INT scale, Lv1 range 200 +30/Lv, 5s duration, pulls enemies)',
'포격식 조준 → 원형 해골무덤 소환. 2스택 (15초/1충전, Lv10→3스택). 둘레에서 뼈가 솟아 공간을 감쌈. 솟을 때 데미지. 적/투사체 차단. 악의 12. Lv당 범위+5% 지속+0.3초':'Artillery-aim → circular bone tomb. 2 stocks (15s/charge, Lv10→3 stocks). Bones rise around perimeter. DMG on rise. Blocks enemies/projectiles. Malice 12. Per Lv range+5% duration+0.3s',
'오망성 시전 → 신성 빛기둥 대폭발. 범위 1500+Lv×100px. 범위 끝까지 넉백(주 성능). 거리감쇠 50%. 스턴 2초. Lv당 뎀+10%. (MP 30%, 쿨 120초)':'Pentagram cast → holy light pillar mega-explosion. Range 1500+Lv×100px. Full-range knockback (main feature). 50% distance falloff. Stun 2s. Per Lv DMG+10%. (MP 30%, CD 120s)',
'검은 오망성 소환. 7초(+Lv당0.5초) 강력 흡인 (데미지 없음, 순수 유틸). 범위 1500+Lv×100px. 흡인력 기본5+Lv당0.5. (MP 30%, 쿨 120초)':'Summon black pentagram. 7s (+0.5s/Lv) strong pull (no DMG, pure utility). Range 1500+Lv×100px. Pull force base 5+0.5/Lv. (MP 30%, CD 120s)',
'빨간 오망성 시전 → 범위 1500+Lv×100px 화염폭발+10초간 화상. 틱당 적 최대HP 1.75%(+Lv당+1.5%). 10초 20틱. 거리감쇠 30%. Lv당 초기뎀+10%. (MP 30%, 쿨 120초)':'Red pentagram cast → range 1500+Lv×100px fire explosion+10s burn. Per tick enemy maxHP 1.75%(+1.5%/Lv). 10s 20 ticks. 30% distance falloff. Per Lv initial DMG+10%. (MP 30%, CD 120s)',
'X키: 그로기 보스 전용. 보스 현재HP 20%(+2%/Lv) + 무기뎀×30(+21%/Lv, 20Lv=150배) + 보스HP 30% 순수뎀. 섬광 돌진 연출. HP/MP/ST 10% 소모. 쿨 5초':'X key: Groggy boss only. Boss current HP 20%(+2%/Lv) + weapon DMG×30(+21%/Lv, Lv20=150×) + boss HP 30% pure DMG. Flash dash. HP/MP/ST 10% cost. CD 5s',
'얼음 속에 들어가 무적 상태. 다시 누르면 파쇄 → 얼음칼날 48발 부채꼴 방사 (MP 40, 쿨 20초). Lv당 칼날+2 뎀+15%':'Enter ice — invincible. Re-press to shatter → 48 ice blades fan spread (MP 40, CD 20s). Per Lv blades+2 DMG+15%',
'[고정: T 자동] 초고속 바늘 연발. 1렙 2발, 5렙마다 +1발. 관통 없음. ST 8. 쿨 1.5초. Lv당 뎀+100%':'[Fixed: T auto] Ultra-fast needles burst. Lv1 2 shots, +1 per 5 levels. No pierce. ST 8. CD 1.5s',
'E홀드: 직선 관통 레이저 채널링. MP 8+Lv/초 지속소모. 폭160+(Lv×10)px, 사거리1200+Lv×80. 관통+감전. Lv당 뎀+21%':'E hold: Straight piercing laser channeling. MP 8+Lv/s drain. Width 160+(Lv×10)px, range 1200+Lv×80. Pierce+shock. Per Lv DMG+21%',
'E탭: 화염 유도빔 발사. MP10. 쿨1초(DEX 스케일). 100% 관통+유도+화상. Lv당 사거리+50 뎀+12%':'E tap: fire homing beam. MP 10. CD 1s (DEX scale). 100% pierce+homing+burn. Per Lv range+50 DMG+12%',
'E: 10초간 대지 진동. 범위 내 용암 기둥이 순차적으로 솟아올라 화상+틱 데미지. MP 100. 쿨 12초. Lv당 범위+10% 뎀+12%':'E: 10s ground tremor. Lava pillars rise sequentially in range — burn+tick DMG. MP 100. CD 12s. Per Lv range+10% DMG+12%',
'독혈 칼날 1발 발사: 관통률 기본 800+Lv×20 + 장비 bowPierce×300/패시브 pPierce×30 반영, +100 보정. 전염+마지막 적 처형. 감염 사망 시 폭발+연쇄 전염. 악의 15. 사거리 4000. 쿨 15초(Lv당-0.5초)':'Fire 1 poison-blood blade: base pierce rate 800+Lv×20 with bowPierce×300 and pPierce×30 scaling, plus +100 bonus. Plague+execute last enemy. Infected death → explosion+chain plague. Malice 15. Range 4000. CD 15s (-0.5s/Lv)',
'마우스 조준 설치. 쿨 20초. 화면 내 클릭 위치에 암전나선 (3초, 10틱, 틱당 100+Lv*20). Lv당 범위+22. 같은 지역 중복 불가':'Mouse-aim placement. CD 20s. Dark spiral at click pos (3s, 10 ticks, 100+Lv*20/tick). Per Lv range+22. No stacking same area',
'현재 위치에 9개 기둥 순차 발동. 5초간 악의 기둥을 소환하여 반경 내 적에게 지속 암전 데미지+감속. 범위 250+(Lv-1)×22. 대왕치기와 합체→기둥강타. 쿨 15초':'9 pillars activate sequentially at current pos. 5s dark pillars deal sustained dark DMG+slow to enemies in radius. Range 250+(Lv-1)×22. Fuses with Giant Slam → Pillar Strike. CD 15s',
'현재 위치에 회복의 영역 설치 (12초 지속). 땅 위: HP/MP/ST 초당+10 리젠 + 회복력 2배 + 쿨다운 속도 2배. 쿨 30초. Lv당 범위+20 지속+0.5초':'Place holy domain at current pos (12s duration). On ground: HP/MP/ST +10/s regen + 2x recovery + 2x CD speed. CD 30s. Per Lv range+20 duration+0.5s',
'범위 내 몬스터 부활력 -15%~30%(Lv1=15%, Lv10=30%). Lv1 범위400, Lv10 범위697. Lv당 범위+33. 쿨 30초. 지속 10초':'Monsters in range: revive power -15%~30%(Lv1=15%, Lv10=30%). Lv1 range 400, Lv10 range 697. Per Lv range+33. CD 30s. Duration 10s',
'마우스 조준 설치. 2스택 (15초/1충전, Lv10→3스택). 범위 내 빙결 저항 -50%, 빙결 게이지 급속 축적. 3초 지속. MP 40. Lv당 범위+22 축적+10%':'Mouse-aim placement. 2 stocks (15s/charge, Lv10→3 stocks). Freeze resist -50% in range, rapid freeze gauge buildup. 3s duration. MP 40. Per Lv range+22 buildup+10%',
'땅을 내리쳐 원형 진동파 발생(범위400). 일반몹에게 큰 포이즈 피해, 보스 체간 파괴에 강함. 회전기폭과 합체→지진폭풍!':'Slam ground → circular shockwave (range 400). High poise DMG to mobs, strong posture break vs bosses. Fuses with Whirlwind Detonate → Earthquake Storm!',
'땅을 내리쳐 원형 진동파 발생(범위400). 일반몹에게 큰 포이즈 피해, 보스 체간 파괴에 강함. 악의기둥과 합체→기둥강타!':'Slam ground → circular shockwave (range 400). High poise DMG to mobs, strong posture break vs bosses. Fuses with Dark Pillar → Pillar Slam!',
'사슬기동 중 E → 즉시 착지하며 화염폭발. 범위200~350 INT 스케일 화염 마법데미지+넉백. 이동거리에 비례해 데미지↑(최대 x4.0). MP 소모. Lv당 범위+16 뎀+12%':'During chain dash E → instant land with fire explosion. Range 200~350 INT scale fire magic DMG+knockback. DMG scales with travel distance (max x4.0). MP cost. Per Lv range+16 DMG+12%',
'사슬기동 중 우클릭 → 땅 내려찍기. 범위200~350 데미지x8 그로기x6. 이동거리 비례 최대x6. 일반몹 즉시 기절(5초), 보스 체간 대량 삭감. Lv당 범위+16 데미지+15% 그로기+15%':'During chain dash RMB → ground slam. Range 200~350 DMG x8 groggy x6. Distance scale max x6. Instant stun mobs (5s), massive boss posture break. Per Lv range+16 DMG+15% groggy+15%',
'[히든: 5성 dimRush 합체] 사슬기동 중 좌클릭 → 이동 중 전방 광역 베기+출혈. STR 스케일 물리데미지. 다단히트. Lv당 뎀+12% 범위+15':'[Hidden: 5-star dimRush fuse] During chain dash LMB → forward AoE slash+bleed while moving. STR scale physical DMG. Multi-hit. Per Lv DMG+12% range+15',
'[히든: 암전나선 합체] Q 홀드 시 보호막이 점점 커지며 HP 초당 10% 회복. 보호막 크기에 비례해 데미지 감소. MP 소모':'[Hidden: Dark Spiral fuse] Q hold: shield grows over time + HP 10%/s regen. DMG reduction scales with shield size. MP cost',
'[히든: 암전나선 합체] E로 조준, 클릭 설치. 에너지 쐐기를 지상에 꽂아 회전+데미지. MP100. 1차지 쿨10초. 5초+Lv당0.5초 지속. Lv당 거리+50':'[Hidden: Dark Spiral fuse] E to aim, click to place. Energy wedge planted on ground — rotates+DMG. MP 100. 1 charge CD 10s. 5s+0.5s/Lv duration. Per Lv range+50',
'[고정: 칼등치기 합체] 보유 시 칼등치기에 전방 충격파 자동 발동. 제자리 처내기. 쿨 5초. Lv당 뎀+12% 범위+20':'[Fixed: Blade Parry fuse] When owned, swipe auto-triggers forward shockwave. Stationary swipe. CD 5s. Per Lv DMG+12% range+20',
'현재 위치에 파쇄 영역 설치 (10초). 범위 내 적 물리방어력 -10%. 쿨 25초. Lv당 범위+22 효과+1% 지속+0.3초':'Place shatter domain at current pos (10s). Enemy phys DEF -10% in range. CD 25s. Per Lv range+22 effect+1% duration+0.3s',
'현재 위치에 침식 영역 설치 (10초). 범위 내 적 마법저항력 -10%. 쿨 25초. Lv당 범위+22 효과+1% 지속+0.3초':'Place corrosion domain at current pos (10s). Enemy magic resist -10% in range. CD 25s. Per Lv range+22 effect+1% duration+0.3s',
'현재 위치에 관통 영역 설치 (10초). 범위 내 적 투사체저항력 -10%. 쿨 25초. Lv당 범위+22 효과+1% 지속+0.3초':'Place pierce domain at current pos (10s). Enemy projectile resist -10% in range. CD 25s. Per Lv range+22 effect+1% duration+0.3s',
'현재 위치에 부활 영역 설치 (10초). 영역 안에서 부활력 +10%. 쿨 25초. Lv당 범위+22 효과+1% 지속+0.3초':'Place revival domain at current pos (10s). Revive power +10% inside zone. CD 25s. Per Lv range+22 effect+1% duration+0.3s',
'[고정: Space] 현재 위치에 가시덫 설치 (1렙 반경200, 10렙398). 슬로우 70%(+2%/Lv, 최대90%)+출혈. INT×magicRef×3(+10%/Lv). 악의 10, 쿨 10초. Lv당 범위+22':'[Fixed: Space] Place spike trap at current pos (Lv1 radius 200, Lv10 398). Slow 70%(+2%/Lv, max 90%)+bleed. INT×magicRef×3(+10%/Lv). Malice 10, CD 10s. Per Lv range+22',
'[고정: E, Lv300 해금] 유도 파란콩 50발 순차 발사 (5초간). MP 100(+1.5/Lv) 소모. 적 추적. 쿨 5초. Lv당 사거리+30 (뎀은 _skMul 계수 적용)':'[Fixed: E, unlock Lv300] 50 homing blue shots fired sequentially (over 5s). MP 100(+1.5/Lv) cost. Tracks enemies. CD 5s. Per Lv range+30 (DMG uses _skMul)',
'[히든: E, Lv700 해금] 홀드 시 3단계 차지 범위폭발 (0.5/1.0/1.5초). 범위 600/1000/1400px. 3단 만충 자동폭발. INT 스케일, 무속성':'[Hidden: E, unlock Lv700] Hold for 3-stage charge AoE explosion (0.5/1.0/1.5s). Range 600/1000/1400px. Stage 3 full charge auto-detonates. INT scale, no element',
'유령 허수아비를 소환하여 유도탄막 어그로를 끈다. 탄막을 흡수해 자원 축적 (기본 20개, Lv당+3). 1개당 HP/MP/ST 각 100. R키로 회수. 쿨 10초':'Summon phantom scarecrow to draw homing projectile aggro. Absorbs projectiles for resource buildup (base 20, +3/Lv). Per absorbed: HP/MP/ST +100 each. R key to retrieve. CD 10s',
'폭발 허수아비 설치. 탄막을 흡수하고 재입력 시 폭발! 1스택당 (INT마법뎀+탄막뎀)×10 마법데미지. 범위 250+흡수×25 (최대1000). 최대흡수 1렙20~20렙60. 쿨 10초':'Place explosive scarecrow. Absorbs projectiles, re-press to detonate! Per stack: (INT magic DMG + proj DMG)×10. Range 250+absorbed×25 (max 1000). Max absorb Lv1=20~Lv20=60. CD 10s',
'[선택: 1~4번, Lv500 해금] 현재 위치에 공성쇠뇌 터렛 설치. 재입력 시 철거. 설치 중 플레이어 석궁 사용 불가 (터렛만 발사). 데미지+50%, 공속+50%, 사거리+50%. ST 100. 쿨 10초. Lv당 뎀+5% 공속+5% 사거리+5%':'[Select: 1~4, unlock Lv500] Deploy siege crossbow turret at current pos. Re-press to dismantle. While deployed: player crossbow disabled (turret fires only). DMG+50%, ATK SPD+50%, range+50%. ST 100. CD 10s. Per Lv DMG+5% ATK SPD+5% range+5%',
'[Ctrl, Lv500 해금] 발동 시 3초 전 상태로 되돌린다. 위치/HP/MP/ST 완전 복원. Lv당 되감기+0.105초 (1렙 3초, 20렙 5초). MP 50(+5/Lv, 20렙150). 쿨 45초':'[Ctrl, unlock Lv500] Rewind to state from 3s ago. Restores position/HP/MP/ST. Per Lv rewind+0.105s (Lv1=3s, Lv20=5s). MP 50(+5/Lv, Lv20=150). CD 45s',
'[선택: 1~4번] 마우스 조준 → 전기창을 땅에 꽂는다. 5스택(12초/1충전, Lv10→6스택). 창끼리 600px 이내면 전류 아크 발생, 경로 위 적에게 감전 틱 데미지. MP 50. 지속 10초(+0.5초/Lv). Lv당 아크뎀+10%':'[Select: 1~4] Mouse aim → plant electric spear on ground. 5 stocks (12s/charge, Lv10→6). Spears within 600px create lightning arcs dealing shock tick DMG to enemies on path. MP 50. Duration 10s (+0.5s/Lv). Per Lv arc DMG+10%',
'성능 등급:':'Perf Grade:',
'벤치 FPS:':'Bench FPS:',
// --- CAT-82: skill panel labels ---
'스킬 정보':'Skill Info',
'타입':'Type',
'미습득':'Not Learned',
'SP 비용':'SP Cost',
'악의 비용':'Malice Cost',
'쿨다운':'Cooldown',
'요구 레벨':'Req. Lv',
'기본 참조뎀':'Base Reference',
'스탯 배율':'Stat Mult',
'패시브 배율':'Passive Mult',
'레벨 배율':'Skill Lv Mult',
'예상 평균 뎀':'Estimated Avg DMG',
'치명타':'Critical',
'치명타 확률':'Crit Rate',
'치명타 배율':'Crit Dmg',
'유효 배율':'Effective Mult',
'스킬 고유':'Skill Specific',
'1타 배율':'1-Hit Mult',
'2타 배율':'2-Hit Mult',
'3타 배율':'3-Hit Mult',
'레벨당 뎀':'Per Lv DMG',
'검기 거리':'Crescent Range',
'레벨당 거리':'Lv Range Bonus',
'ST/틱':'ST/Tick',
'레벨당 크기':'Per Lv Size',
'넉백':'Knockback',
'충전 시간':'Charge Time',
'레벨당 범위':'Per Lv Range',
'관통률':'Pierce Rate',
'지속뎀':'DOT Duration',
'무한':'Infinite',
'타격 형식':'AoE Type',
'진동파':'Shockwave',
'스태거':'Stagger',
'높음':'High',
'스톡':'Stocks',
'기둥 수':'Pillars',
'지속':'Duration',
'반경':'Radius',
'슬로우':'Slow',
'활':'Bow',
// --- CAT-83: affix desc labels ---
'독 DoT':'Poison DoT',
'화상 DoT':'Fire DoT',
'빙결 DoT+감속':'Ice DoT+Slow',
'연쇄전격':'Chain Lightning',
'저주(힐차단)':'Curse(Heal Block)',
'방어무시':'Armor Ignore',
'치명타율':'Crit Rate',
'스태거+':'Stagger+',
'체인타겟+':'Chain Target+',
'처치 후 뎀+':'Kill DMG+',
'크리폭발(ATK×)':'Crit Explode(ATK×)',
'원소뎀+':'Elem DMG+',
'공격속도+':'Atk Spd+',
'패리보너스+':'Parry Bonus+',
'추적콤보+10':'Track Combo+10',
'작살뎀+':'Harpoon DMG+',
'스킬뎀+':'Skill DMG+',
'쿨다운-':'CD-',
'방어력+':'DEF+',
'쉴드+':'Shield+',
'이동속도+':'Move Spd+',
'크리확률+':'Crit Rate+',
'크리배율+':'Crit Dmg+',
'화염저항':'Fire Res',
'빙결저항':'Ice Res',
'암전저항':'Lightning Res',
'암흑저항':'Dark Res',
'독저항':'Poison Res',
'전원소저항':'All Elem Res',
'물리DR':'Phys DR',
'반사%':'Reflect%',
'가시뎀':'Thorns DMG',
'배리어':'Barrier',
'CC저항':'CC Resist',
'위기뎀+':'Crisis DMG+',
'피격반격':'Hit Counter',
'패링폭발(ATK×)':'Parry Burst(ATK×)',
'체간파괴뎀+':'Poise Break DMG+',
'원소전환':'Elem Convert',
'상태이상해제':'Status Clear',
'불굴(1회생존)':'Tenacity(Survive×1)',
'부활(HP회복)':'Revive(HP Restore)',
'드롭률+':'Drop Rate+',
'경험치+':'EXP+',
'골드+':'Gold+',
'포션회복+':'Potion Heal+',
'사슬게이지+':'Chain Gauge+',
'부활억제':'Anti-Revive',
'부활력+':'Revival Pow+',
'부활쿨-':'Revival CD-',
'최대HP%+':'Max HP%+',
'HP리젠+':'HP Regen+',
'회복력+':'Heal Pow+',
'마법뎀+':'Magic DMG+',
'MP소비-':'MP Cost-',
'화염뎀%+':'Fire DMG%+',
'화염관통%':'Fire Pen%',
'적중화상':'On-Hit Burn',
'크리화폭':'Crit Fire Burst',
'화상지속+':'Burn Duration+',
'화염뎀보너스':'Fire DMG Bonus',
'빙결뎀%+':'Ice DMG%+',
'빙결관통%':'Ice Pen%',
'적중빙결':'On-Hit Freeze',
'크리빙폭':'Crit Ice Burst',
'빙결지속+':'Freeze Duration+',
'빙결뎀보너스':'Ice DMG Bonus',
'뇌전뎀%+':'Lightning DMG%+',
'뇌전관통%':'Lightning Pen%',
'적중감전':'On-Hit Shock',
'크리뇌폭':'Crit Lightning Burst',
'감전지속+':'Shock Duration+',
'뇌전뎀보너스':'Lightning DMG Bonus',
'암흑뎀%+':'Dark DMG%+',
'암흑관통%':'Dark Pen%',
'적중저주':'On-Hit Curse',
'크리암폭':'Crit Dark Burst',
'저주지속+':'Curse Duration+',
'암흑뎀보너스':'Dark DMG Bonus',
'독뎀%+':'Poison DMG%+',
'독관통%':'Poison Pen%',
'적중중독':'On-Hit Poison',
'크리독폭':'Crit Poison Burst',
'독지속+':'Poison Duration+',
'독뎀보너스':'Poison DMG Bonus',
'근접뎀%+':'Melee DMG%+',
'원거리뎀%+':'Ranged DMG%+',
'마법뎀%+':'Magic DMG%+',
'빔뎀%+':'Beam DMG%+',
'DoT뎀%+':'DoT DMG%+',
'투사체뎀%+':'Proj DMG%+',
'범위반경+':'AoE Radius+',
'근접크리+':'Melee Crit+',
'마법크리+':'Magic Crit+',
'석궁크리+':'Xbow Crit+',
'근접공속+':'Melee Spd+',
'석궁공속+':'Xbow Spd+',
'시전속도+':'Cast Spd+',
'전속성관통':'All Elem Pen',
'쉴드관통':'Shield Pen',
'방어력깎기':'Armor Shred',
'투사체속도+':'Proj Speed+',
'적중시화구':'On-Hit Fireball',
'적중시연쇄뇌격':'On-Hit Chain Lightning',
'적중빙결%':'On-Hit Freeze%',
'적중스턴%':'On-Hit Stun%',
'적중중독%':'On-Hit Poison%',
'적중출혈%':'On-Hit Bleed%',
'적중약화%':'On-Hit Weaken%',
'적중감속%':'On-Hit Slow%',
'적중표적%':'On-Hit Mark%',
'크리폭발(HP%)':'Crit Explode(HP%)',
'크리연쇄(HP%)':'Crit Chain(HP%)',
'크리빙결%':'Crit Freeze%',
'크리HP+':'Crit HP+',
'크리MP+':'Crit MP+',
'크리쉴드+':'Crit Shield+',
'피격방어+':'Hit DEF+',
'반격가시':'Counter Thorns',
'빙결파동%':'Ice Nova%',
'자동암흑막':'Auto Dark Shield',
'주기치유':'Periodic Heal',
'시체폭발%':'Corpse Explode%',
'회피뎀+':'Dodge DMG+',
'패링폭발%':'Parry Burst%',
'블록HP+':'Block HP+',
'블록MP+':'Block MP+',
'회전참뎀+':'Whirlwind DMG+',
'옴니빔뎀+':'Omni Beam DMG+',
'화구뎀+':'Fireball DMG+',
'미사일뎀+':'Missile DMG+',
'청탄뎀+':'Blue Shot DMG+',
'폭렬탄뎀+':'Blast Shot DMG+',
'지옥광선뎀+':'Hell Ray DMG+',
'악의폭풍뎀+':'Malice Storm DMG+',
'연쇄참뎀+':'Chain Slash DMG+',
'거인강타뎀+':'Giant Slam DMG+',
'유령보행뎀+':'Ghost Walk DMG+',
'악의박격뎀+':'Malice Mortar DMG+',
'화염오라뎀+':'Fire Aura DMG+',
'빙구뎀+':'Ice Orb DMG+',
'화염빔뎀+':'Fire Beam DMG+',
'악의사냥뎀+':'Malice Hunt DMG+',
'암흑기둥뎀+':'Dark Pillar DMG+',
'역병뎀+':'Plague DMG+',
'가시오라뎀+':'Spike Aura DMG+',
'연쇄돌격뎀+':'Chain Assault DMG+',
'회피확률+':'Dodge Rate+',
'회피쿨-':'Dodge CD-',
'쉴드%+':'Shield%+',
'쉴드리젠%+':'Shield Regen%+',
'쉴드쿨-':'Shield CD-',
'HP리젠%+':'HP Regen%+',
'ST리젠+':'ST Regen+',
'ST리젠%+':'ST Regen%+',
'MP리젠+':'MP Regen+',
'MP리젠%+':'MP Regen%+',
'화염DR':'Fire DR',
'빙결DR':'Ice DR',
'뇌전DR':'Lightning DR',
'암흑DR':'Dark DR',
'독DR':'Poison DR',
'전체DR':'All DR',
'엘리트DR':'Elite DR',
'스턴저항':'Stun Res',
'감속저항':'Slow Res',
'넉백저항':'KB Res',
'돌진거리+':'Dash Range+',
'돌진쿨-':'Dash CD-',
'전투이속+':'Combat MSpd+',
'비전투이속+':'Out-Combat MSpd+',
'습득범위+':'Pickup Range+',
'전스탯+':'All Stats+',
'적중자원+':'On-Hit Resource+',
'화염최대저항+':'Fire Max Res+',
'빙결최대저항+':'Ice Max Res+',
'뇌전최대저항+':'Lightning Max Res+',
'암흑최대저항+':'Dark Max Res+',
'독최대저항+':'Poison Max Res+',
'스킬쿨-':'Skill CD-',
'물약쿨-':'Potion CD-',
'강화성공+':'Craft Rate+',
'악의획득+':'Malice Gain+',
'악마화뎀+':'Demon DMG+',
'악마화DR':'Demon DR',
'영혼수확+':'Soul Harvest+',
'생명흡혈%':'Life Leech%',
'과치유→쉴드':'Overheal→Shield',
'만마나뎀+':'Full MP DMG+',
'이동DR':'Move DR',
'정지뎀+':'Stationary DMG+',
'회피후뎀+':'After Dodge DMG+',
'패링쉴드+':'Parry Shield+',
'콤보보너스+':'Combo Bonus+',
'HP≥70%뎀+':'HP≥70% DMG+',
'적HP≤30%뎀+':'Foe HP≤30% DMG+',
'HP100%뎀+':'HP100% DMG+',
'HP≤35%뎀+':'HP≤35% DMG+',
'적HP≤20%뎀+':'Foe HP≤20% DMG+',
'근접뎀+':'Melee DMG+',
'원거리뎀+':'Ranged DMG+',
'스턴적뎀+':'vs Stunned DMG+',
'빙결적뎀+':'vs Frozen DMG+',
'화상적뎀+':'vs Burning DMG+',
'중독적뎀+':'vs Poisoned DMG+',
'저주적뎀+':'vs Cursed DMG+',
'감속적뎀+':'vs Slowed DMG+',
'보스뎀+':'Boss DMG+',
'엘리트뎀+':'Elite DMG+',
'일반몹뎀+':'Mob DMG+',
'선제뎀+':'First Strike DMG+',
'물리흡혈%':'Phys Leech%',
'마나흡수%':'Mana Leech%',
'ST흡수%':'ST Leech%',
'적중HP+':'On-Hit HP+',
'처치HP+':'On-Kill HP+',
'처치MP+':'On-Kill MP+',
'처치ST+':'On-Kill ST+',
'처치시폭발':'On-Kill Explode',
'처치이속+':'On-Kill MSpd+',
'HP≥70%방어+':'HP≥70% DEF+',
'HP≤50%이속+':'HP≤50% MSpd+',
'DoT피해감소':'DoT DMG Reduce',
'보스피해감소':'Boss DMG Reduce',
'근접피해감소':'Melee DMG Reduce',
'원거리피해감소':'Ranged DMG Reduce',
'처치HP회복':'On-Kill HP Restore',
'처치쉴드회복':'On-Kill Shield Restore',
'ST소비-':'ST Cost-',
'HP≥70%공격+':'HP≥70% ATK+',
'HP≤35%흡혈':'HP≤35% Leech',
'보스추가뎀':'vs Boss DMG+',
'엘리트추가뎀':'vs Elite DMG+',
'공격력+':'ATK+',
'크리뎀+':'Crit DMG+',
// --- CAT-84/85/86: affix names + implicit + legendary ---
'물리방패의':'Physical Shield',
'지속의':'Stamina',
'마나의':'Mana',
'원소수호의':'Elem Guard',
'행운의':'Fortune',
'근성의':'Grit',
'풍요의':'Abundance',
'약자포식의':'Predator',
'만혈의':'Full Life',
'사선의':'Low Life',
'처형의':'Execute',
'근접살의':'Melee DMG',
'원거리의':'Ranged',
'경직파의':'Stagger Break',
'동파의':'Freeze Strike',
'연소의':'Burning',
'맹독살의':'Venom Slayer',
'저주살의':'Curse Slayer',
'구속의':'Binding',
'왕살의':'Boss Slayer',
'정예살의':'Elite Slayer',
'군살의':'Mob Slayer',
'선제의':'First Strike',
'흡혈의':'Vampirism',
'흡마의':'Mana Leech',
'흡정의':'Stamina Leech',
'타격재생의':'Hit Regen',
'처치회복의':'Kill Recovery',
'처치흡마의':'Kill Mana Leech',
'처치활력의':'Kill Stamina',
'처치폭발의':'Kill Explosion',
'처치질주의':'Kill Sprint',
'건강방어의':'Healthy Defense',
'중상보호의':'Wounded Shield',
'위기질주의':'Crisis Sprint',
'지속피해방어의':'DoT DR',
'왕피해방어의':'Boss DMG DR',
'근접방어의':'Close DR',
'원거리방어의':'Ranged DR',
'처치생명의':'Kill HP',
'처치수호의':'Kill Shield',
'화염강화의':'Fire Amp',
'화염관통의':'Fire Pierce',
'발화의':'Ignition',
'화염폭발의':'Fire Burst',
'맹화의':'Blaze',
'화염의힘':'Fire Power',
'빙결강화의':'Ice Amp',
'빙결관통의':'Ice Pierce',
'동결의':'Freeze',
'빙결폭발의':'Ice Burst',
'영빙의':'Permafrost',
'빙결의힘':'Ice Power',
'뇌전강화의':'Thunder Amp',
'뇌전관통의':'Thunder Pierce',
'감전의':'Shock',
'뇌전폭발의':'Thunder Burst',
'낙뢰의':'Thunderbolt',
'뇌전의힘':'Thunder Power',
'암흑강화의':'Dark Amp',
'암흑관통의':'Dark Pierce',
'침식의':'Erosion',
'암흑폭발의':'Dark Burst',
'심연의':'Abyss',
'암흑의힘':'Dark Power',
'맹독강화의':'Venom Amp',
'독관통의':'Poison Pierce',
'중독의':'Poisoning',
'독폭발의':'Poison Burst',
'맹독지속의':'Venom Duration',
'독의힘':'Poison Power',
'격투의':'Melee',
'원사의':'Ranged Shot',
'주술의':'Spell',
'광선의':'Beam',
'탄도의':'Ballistic',
'확산의':'AoE Radius',
'근접회심의':'Melee Crit',
'마법회심의':'Spell Crit',
'사격회심의':'Ranged Crit',
'근접쾌속의':'Melee Speed',
'사격쾌속의':'Ranged Speed',
'영창의':'Chanting',
'전속성관통의':'All-Elem Pierce',
'쉴드파괴의':'Shield Bypass',
'갑옷분쇄의':'Armor Shred',
'탄속의':'Proj Speed',
'화구발사의':'Fireball Launch',
'연쇄뇌격의':'Chain Lightning',
'동결타의':'Freeze Strike',
'경직타의':'Stagger Strike',
'독침의':'Poison Sting',
'출혈의':'Bleed',
'약화의':'Weakness',
'둔화의':'Slow',
'표적의':'Marking',
'회심폭발의':'Crit Explosion',
'회심연쇄의':'Crit Chain',
'회심빙결의':'Crit Freeze',
'회심치유의':'Crit Heal',
'회심영력의':'Crit Mana',
'회심수호의':'Crit Shield',
'피격강화의':'Hit Boost',
'반격가시의':'Counter Thorns',
'빙결파동의':'Ice Nova',
'암흑보호의':'Dark Shield',
'치유파동의':'Heal Pulse',
'시체폭발의':'Corpse Explosion',
'회피반격의':'Dodge Counter',
'패링폭파의':'Parry Shatter',
'블록치유의':'Block Heal',
'블록영력의':'Block Mana',
'회전참강화':'Spin Slash Boost',
'옴니빔강화':'Omni Beam Boost',
'화구강화':'Fireball Boost',
'미사일강화':'Missile Boost',
'청탄강화':'Blue Shot Boost',
'폭렬탄강화':'Burst Shot Boost',
'지옥광선강화':'Hellray Boost',
'악의폭풍강화':'Malice Storm Boost',
'연쇄참강화':'Chain Slash Boost',
'거인강타강화':'Giant Slam Boost',
'유령보행강화':'Ghost Walk Boost',
'악의박격강화':'Malice Mortar Boost',
'화염오라강화':'Fire Aura Boost',
'빙구강화':'Ice Orb Boost',
'화염빔강화':'Fire Beam Boost',
'악의사냥강화':'Malice Hunt Boost',
'암흑기둥강화':'Dark Pillar Boost',
'역병강화':'Plague Boost',
'가시오라강화':'Thorn Aura Boost',
'연쇄돌격강화':'Chain Assault Boost',
'회피의':'Evasion',
'회피쿨감의':'Dodge CD Red',
'수호력의':'Shield Power',
'수호재생의':'Shield Regen',
'수호쿨감의':'Shield CD Red',
'재생력의':'Regen Power',
'활력재생의':'Stamina Regen',
'마력재생의':'Mana Regen',
'화염보호의':'Fire Shield',
'빙결보호의':'Ice Shield',
'뇌전보호의':'Thunder Shield',
'해독의':'Antidote',
'만물보호의':'All Protection',
'정예보호의':'Elite Shield',
'경직저항의':'Stagger Resist',
'빙결저항의':'Freeze Resist',
'감속저항의':'Slow Resist',
'넉백저항의':'Knockback Resist',
'돌진거리의':'Dash Range',
'돌진쿨감의':'Dash CD Red',
'전투질주의':'Combat Sprint',
'평화질주의':'Peace Sprint',
'습득범위의':'Pickup Radius',
'힘의':'Strength',
'민첩의':'Dexterity',
'지능의':'Intelligence',
'만능의':'Versatile',
'지구력의':'Max Stamina',
'마나력의':'Mana Power',
'타격자원의':'Hit Resource',
'화염한계의':'Fire Cap',
'빙결한계의':'Ice Cap',
'뇌전한계의':'Thunder Cap',
'암흑한계의':'Dark Cap',
'독한계의':'Poison Cap',
'스킬쿨감의':'Skill CD Red',
'물약쿨감의':'Potion CD Red',
'장인의':'Craftsmanship',
'탐욕의':'Greed',
'수련의':'Training',
'수집의':'Gathering',
'악마의힘':'Demon Power',
'악마보호의':'Demon Shield',
'영혼수확의':'Soul Harvest',
'생명흡수의':'Life Absorption',
'과치유수호의':'Overheal Shield',
'만마력의':'Full Mana DMG',
'이동방어의':'Moving DR',
'정지공세의':'Stationary Boost',
'회피공세의':'Post-Dodge Boost',
'패링보호의':'Parry Shield',
'콤보폭발의':'Combo Burst',
'물리타격의':'Phys Strike',
'화염타격의':'Fire Strike',
'빙결타격의':'Ice Strike',
'뇌전타격의':'Thunder Strike',
'암흑타격의':'Dark Strike',
'독타격의':'Poison Strike',
'최소공격의':'Min ATK',
'최대공격의':'Max ATK',
'전투력의':'Combat Power',
'무기사거리의':'Weapon Range',
'활사거리의':'Bow Range',
'이중타의':'Double Strike',
'다중발사의':'Multi Shot',
'관통횟수의':'Pierce Count',
'관통유지의':'Pierce Keep',
'연쇄유지의':'Chain Keep',
'범위확장의':'Splash Range',
'범위피해의':'Splash DMG',
'돌진공격의':'Dash ATK',
'반격공격의':'Counter ATK',
'후방타의':'Backstab',
'침식가속의':'Erosion Speed',
'출혈지속의':'Bleed Duration',
'마법타격의':'Magic Strike',
'주문증폭의':'Spell Amp',
'연살뎀의':'Kill Streak DMG',
'연살속의':'Kill Streak Speed',
'기세의':'Momentum',
'정지공격의':'Static Strike',
'이동공격의':'Mobile Strike',
'패링공세의':'Post-Parry Boost',
'임사폭발의':'Near-Death Burst',
'만기력공의':'Full Stamina ATK',
'만마력공의':'Full Mana ATK',
'신선처치의':'Fresh Kill',
'경직연장의':'Stagger Extension',
'빙결연장의':'Freeze Extension',
'둔화강화의':'Slow Amp',
'독중첩의':'Poison Stack',
'출혈중첩의':'Bleed Stack',
'발화강화의':'Ignite Amp',
'동상강화의':'Frostbite Amp',
'감전강화의':'Shock Amp',
'사선회심의':'Low HP Crit',
'갑옷강화의':'Armor Boost',
'블록흡수의':'Block Absorb',
'방패타격의':'Shield Bash',
'방패경직의':'Shield Stagger',
'격투속의':'Brawl Speed',
'격투회심의':'Brawl Crit',
'격투경직의':'Brawl Stagger',
'하반재생의':'Leg Regen',
'CC단축의':'CC Duration Red',
'돌진타의':'Dash Strike',
'돌진범위의':'Dash AoE',
'은신질주의':'Stealth Sprint',
'회피감쇠의':'Dodge DR',
'속성감쇠의':'Elem DR',
'마나왕관의':'Mana Helm',
'시전왕관의':'Cast Helm',
'쿨감왕관의':'CD Helm',
'경험왕관의':'EXP Helm',
'공생의':'Symbiosis',
'수질의':'Body-Soul',
'회심흡의':'Crit Leech',
'체마의':'HP-Mana',
'체기의':'HP-Stamina',
'마기의':'Mana-Stamina',
'전재생의':'All Regen',
'힘민의':'STR-DEX',
'힘지의':'STR-INT',
'민지의':'DEX-INT',
'운근의':'Fortune-Grit',
'수확의':'Harvest',
'빙화의':'Ice-Fire',
'뇌암의':'Thunder-Dark',
'근마의':'Blade-Magic',
'속성침식의':'Elem Erosion',
'화염반지의':'Fire Ring',
'빙결반지의':'Ice Ring',
'뇌전반지의':'Thunder Ring',
'암흑반지의':'Dark Ring',
'독반지의':'Poison Ring',
'콤보반지의':'Combo Ring',
'처치마나의':'Kill Mana',
'관통반지의':'Pierce Ring',
'만능목걸이의':'Allround Necklace',
'회심목걸이의':'Crit Necklace',
'관통목걸이의':'Pierce Necklace',
'스킬목걸이의':'Skill Necklace',
'콤보한계의':'Combo Max',
'처치치유의':'Kill Heal',
'지구벨트의':'Stamina Belt',
'포션벨트의':'Potion Belt',
'활력벨트의':'Vitality Belt',
'탐욕벨트의':'Greed Belt',
'마나띠의':'Mana Band',
'시전띠의':'Cast Band',
'마력띠의':'Magic Band',
'주술띠의':'Spell Band',
'속성띠의':'Elem Band',
'전사의힘':'Warrior Power',
'전사생명의':'Warrior Life',
'전사흡혈의':'Warrior Leech',
'전사인내의':'Warrior Poise',
'마법사의힘':'Mage Power',
'마법사마나의':'Mage Mana',
'마법사수호의':'Mage Shield',
'마법사속성의':'Mage Elem',
'궁수의힘':'Archer Power',
'궁수사거리의':'Archer Range',
'궁수관통의':'Archer Pierce',
'궁수질주의':'Archer Sprint',
'탱크생명의':'Tank Life',
'탱크방어의':'Tank Defense',
'탱크블록의':'Tank Block',
'탱크가시의':'Tank Thorns',
'암살회심의':'Assassin Crit',
'암살후방의':'Assassin Backstab',
'암살독의':'Assassin Poison',
'암살회피의':'Assassin Dodge',
'종결자의':'The Ender',
'생존자의':'Survivor',
'종결수호의':'End Shield',
'종결회심의':'End Crit',
'종결공격의':'End ATK',
'종결저항의':'End Resistance',
'종결파괴의':'End Destruction',
'종결보호의':'End Protection',
'종결흡혈의':'End Leech',
'종결인내의':'End Poise',
'종결쿨감의':'End CD Red',
'종결경험의':'End EXP',
'종결약탈의':'End Loot',
'종결악의의':'End Malice',
'종결힘의':'End STR',
'종결민첩의':'End DEX',
'종결지능의':'End INT',
'종결행운의':'End LCK',
'종결근성의':'End Grit',
'종결연살의':'End Kill Chain',
'건강공세의':'Healthy Offense',
'중상폭발의':'Wounded Burst',
'중상흡혈의':'Wounded Leech',
'토벌의':'Vanguard',
'정예토벌의':'Elite Vanguard',
'극대화의':'Maximize',
'공격력 +X%':'ATK +X%',
'관통 확률 +X%':'Pierce Chance +X%',
'방어율 +X%':'Block Rate +X%',
'물리 피해감소 +X%':'Phys DR +X%',
'최대 HP +X':'Max HP +X',
'공격속도 +X%':'ATK Speed +X%',
'상태이상 저항 +X%':'Status Resist +X%',
'이동속도 +X%':'Move Speed +X%',
'원소 저항 +X%':'Elem Resist +X%',
'최대 HP +X%':'Max HP +X%',
'회피 쿨다운 -X%':'Dodge CD -X%',
'물약 쿨다운 -X%':'Potion CD -X%',
'부활력 +X%':'Revive Power +X%',
'마법 데미지 +X%':'Magic DMG +X%',
'전설 특수':'Legendary Special',
'5타 콤보 완성 시 데빌포스 20% 즉시 충전':'5-hit combo: instantly charge DevilForce 20%',
'처치 시 이속 +40%(3초) + 다음 공격 크리 보장':'Kill: MoveSpd +40%(3s) + next attack guaranteed Crit',
'스태거 발동 시 범위 충격파 (ATK×120%)':'Stagger: AoE shockwave (ATK×120%)',
'스태거 발동 시 범위 충격파 (ATK×100%)':'Stagger: AoE shockwave (ATK×100%)',
'강타 시 적 넉백 거리 2배 + 벽충돌 추가뎀':'Heavy hit: Knockback ×2 + wall collision bonus DMG',
'출혈 대상 크리 시 잔여 DoT×300% 즉시 폭발':'Crit vs Bleeding: remaining DoT×300% instant explosion',
'작살 착지 타격 수만큼 데미지 +20% 중첩(최대5)':'Javelin landing hits: stack +20% DMG (max 5)',
'치명타 시 추가 투사체 1발 발사':'Crit: fire 1 additional projectile',
'패리 성공 시 반격 데미지 ×2':'Parry: counter DMG ×2',
'피격 시 3초 쿨로 HP 5% 즉시 회복':'On Hit (3s CD): restore 5% HP instantly',
'스킬 사용 시 20% 확률로 쿨다운 미소모':'Using skills: 20% chance no cooldown consumed',
'공격속도 +20% + 기본공격에 랜덤 원소 추가':'ATK Speed +20% + basic attacks add random element',
'이동 중 지속 HP 재생 (초당 HP의 1%)':'While moving: HP regen (1% HP/sec)',
'회피 직후 첫 공격 데미지 +80%':'First attack after Dodge: DMG +80%',
'패리 타이밍 판정 +50% 확대':'Parry timing window +50% expanded',
'원소 반응 발동 시 추가 폭발 (ATK×80%)':'Elemental reaction: bonus explosion (ATK×80%)',
'처치 시 데빌포스 5% 회복':'Kill: restore 5% DevilForce',
'HP 50% 이하 시 전 스킬 쿨다운 -30%':'Below 50% HP: all skill CD -30%',
'물약 사용 시 5초간 피해 +15%':'Using Potion: DMG +15% for 5s',
'암묵':'Implicit',
'낡은 악마의 팔찌':'Worn Demon Bracelet',
'흑요석 악마의 팔찌':'Obsidian Demon Bracelet',
'미스릴 악마의 팔찌':'Mithril Demon Bracelet',
'낡은 생명의 팔찌':'Worn Life Bracelet',
'확인':'Confirm',
'조작법':'Controls',
'살아남으려면 익혀라':'Master this to survive',
'전투':'Combat',
'이동 / 상호작용':'Move / Interact',
'메뉴':'Menu',
'시스템':'System',
'아무 키를 눌러 시작':'Press any key to start',
'스테이지':'Vaihe',
'💪 힘 (STR)':'💪 STR',
'🏹 민첩 (DEX)':'🏹 DEX',
'🔮 지능 (INT)':'🔮 INT',
'🍀 행운 (LCK)':'🍀 LCK',
'⚔️ 맹공':'⚔️ Onslaught',
'🔱 돌파':'🔱 Breakthrough',
'⚡ 반격':'⚡ Retaliation',
'🔮 마력폭주':'🔮 Mana Surge',
'🎯 정밀사격':'🎯 Precision',
'🛡 수호신':'🛡 Aegis',
'💚 회복력':'💚 Recovery',
'💥 급소':'💥 Vital Strike',
'🎁 약탈':'🎁 Plunder',
'🔱 관통':'🔱 Pierce',
'💠 마력회복':'💠 Mana Recovery',
'🏹 쇠뇌력':'🏹 Crossbow Mastery',
'⚔ 광전사':'⚔ Berserker',
'🎯 추적자':'🎯 Tracker',
'🗡 물리관통':'🗡 Phys Penetration',
'🔮 마법관통':'🔮 Magic Penetration',
'🌿 풍요':'🌿 Abundance',
'🐺 약자포식':'🐺 Predator',
'☠ 침식':'☠ Corrosion',
'💎 마력그릇':'💎 Mana Vessel',
'💪 힘의그릇':'💪 Stamina Vessel',
'👿 악의중독':'👿 Malice Addict',
'❤️ 강인':'❤️ Fortify',
'🛡 철벽':'🛡 Iron Wall',
'🎯 사냥꾼':'🎯 Hunter',
'✦ 인간성':'✦ Humanity',
'☠ 악마성':'☠ Demon',
'1. 악의폭풍':'1. Malice Storm',
'2. 칼날 계열':'2. Blade Skills',
'3. 역병 확장':'3. Plague Expand',
'4. 이동스킬 마스터':'4. Movement Master',
'5. 사슬 확장':'5. Chain Expand',
'6. 💀 필살기 선택':'6. 💀 Ultimate Pick',
'7. 멸살+만화+원소+전격이동':'7. Beam+Barrage+Elem+Blink',
'8. 회전참+기폭+대왕':'8. Whirl+Det+Giant',
'9. 방패 합체':'9. Shield Fuse',
'10. 해골무덤+악의폭풍':'10. Bone Wall+Malice Storm',
'11. 폭풍소환+얼음보주':'11. Storm+Ice Orb',
'12. 뇌전걸음':'12. Ghost Walk',
'13. 신성 영역':'13. Holy Domain',
'14. 6단합체: 폭풍빔':'14. 6-Fuse: Storm Beam',
'15. 신성+빙결':'15. Holy+Ice',
'16. 암흑+가시+대왕2':'16. Dark+Spike+Slam2',
'17. 사슬 최종':'17. Chain Final',
'⚡ 이동스킬':'⚡ Movement',
'⚔️ 물리':'⚔️ Physical',
'🛡️ 방어':'🛡️ Defense',
'🔮 마법':'🔮 Magic',
'🏹 석궁/투사체':'🏹 Crossbow/Projectile',
'⚙️ 영역':'⚙️ Domain',
'💀 필살기':'💀 Ultimate',
'⭐ 추천':'⭐ Recommend',
'⚔ 공격':'⚔ Attack',
'🛡 방어':'🛡 Defense',
'⚙ 특수':'⚙ Special',
  '👻 공성허수아비!':'👻 Siege Scarecrow!',
  '💥 공성허수아비 폭발!':'💥 Siege Scarecrow Blast!',
};


const _FI_PFX={'녹슨':'Ruosteinen','강철':'Teräksinen','흑요석':'Obsidiaani','미스릴':'Mithriili','심판의':'Tuomion','천벌의':'Jumalan Vihan','파멸의':'Tuhon','불꽃':'Liekin','화염':'Helvetintuli','염화':'Helvetintuli','지옥불':'Helvetinliekki','지옥화':'Helvetinliekki','지옥':'Helvetinliekki','멸화의':'Tuhoava','냉기':'Pakkanen','빙결':'Jäätynyt','빙하':'Jäätikön','서리의':'Huurteen','서리':'Huurteen','영겁빙':'Ikijään','그림자':'Varjon','암흑':'Pimeä','심연':'Syvyyden','나락의':'Tuonelan','나락':'Tuonelan','무간의':'Tyhjyyden','전기':'Kipinän','낙뢰':'Ukkosen','암전':'Salaman','뇌신의':'Ukkosjumalan','뇌신':'Ukkosjumalan','만뢰의':'Tuhansien Salamoiden','축복':'Siunattu','성광':'Pyhä Valo','신성':'Pyhä','천사의':'Enkelien','신벌의':'Jumalan Tuomion','낡은':'Kulunut','천':'Kangas','가죽':'Nahka','강철사':'Teräslanka','은':'Hopea','은사':'Hopealanka','화염의':'Helvetintuli','빙결의':'Jäätynyt','암흑의':'Pimeä','암전의':'Salaman'};
const _FI_BASE={'대검':'Suuri Miekka','석궁':'Varsijousi','연사석궁':'Sarjajousi','마력석궁':'Taikajousi','견갑':'Kilpi','대견갑':'Iso Kilpi','전투화':'Taistelukengät','갑옷':'Haarniska','갑주':'Panssari','왕관':'Kruunu','장갑':'Käsineet','건틀릿':'Rautakäsineet','바지':'Housut','각반':'Säärystimet','허리띠':'Vyö','벨트':'Vyö','부적':'Talismaani','목걸이':'Kaulakoru','반지':'Sormus','망토':'Viitta','악마팔찌':'Demon Bracelet','생명팔찌':'Life Bracelet','팔찌':'Rannekoru','귀걸이':'Korvakoru'};
