const _DE={
// --- Stage / Boss ---
'썩은 숲':'Fauliger Wald','숲의 감시자':'Waldwächter','독버섯 거인':'Giftpilz-Koloss','숲의 사냥꾼':'Waldjäger','숲의 기생수':'Parasitische Bestie',
'1장 — 썩은 숲':'Kap. 1 — Fauliger Wald','2장 — 벌레굴':'Kap. 2 — Wurmnest','3장 — 얼음굴':'Kap. 3 — Eishöhle',
'4장 — 고통의 화염지대':'Kap. 4 — Flammenöde der Qual','5장 — 지옥의 군단':'Kap. 5 — Höllenlegion','6장 — 사도의 마굴':'Kap. 6 — Schlund des Apostels','7장 — 지옥성':'Kap. 7 — Höllenfeste',
'탈출!':'Entkommen!','처치':'Getötet','경험치':'EP','최대콤보':'Max-Kombo',
// --- Tutorial (Crow) ---
'일어나. 여신이 널 여기 보낸 건 죽으라고가 아니야.':'Steh auf. Die Göttin hat dich nicht zum Sterben hergeschickt.',
'좋아, 감각이 있군. 계속 쳐!':'Gut, du hast Instinkt. Schlag weiter zu!',
'Shift를 눌러. 작살이다. 땅에 꽂아서 끌려가!':'Drück Shift. Das ist die Harpune. Ramm sie rein und lass dich ziehen!',
'작살로 끌려가는 중엔 무적이다. 위험할 때 쓰면 좋아.':'Während die Harpune dich zieht, bist du unverwundbar. Nutz es in der Not.',
'...아파? 당연하지. 여긴 지옥이야.':'...Schmerzt es? Natürlich. Das hier ist die Hölle.',
'Q를 눌러! 악의로 보호막을 만들 수 있다.':'Drück Q! Erschaffe einen Schild aus Bosheit.',
'보호막 없이 버틸 생각은 버려.':'Vergiss es, ohne Schild zu überleben.',
'우클릭이 패링이다. 적 공격이 닿기 직전에 눌러!':'Rechtsklick ist Parade. Drück kurz bevor der Feind trifft!',
'못 하겠으면 때려. 안 죽으면 그만이야.':'Kannst du nicht parieren? Dann schlag zu. Hauptsache, du stirbst nicht.',
'됐어! 감 잡았구나.':'So ist\'s recht! Du bekommst den Dreh raus.',
'하나 죽었군.':'Einer weniger.',
'유령쇠뇌야. 인사해.':'Das ist die Geisterarmbrust. Sag Hallo.',
'빨간 탄을 무서워하지 마. 악의가 강하다.':'Fürchte die roten Geschosse nicht. Bosheit ist mächtig.',
'패링으로 돌려주고, Q 보호막도 써! 악의를 잘 굴려!':'Pariere sie zurück, nutz auch den Q-Schild! Beherrsche deine Bosheit!',
'무지개빛은 패링 불가! 피해!':'Regenbogengeschosse sind nicht parierbar! Ausweichen!',
'피가 새고 있다. Shift. 빠져.':'Du blutest aus. Shift. Rückzug.',
'물약 있잖아! 숫자키!':'Du hast Tränke! Zifferntasten!',
'우클릭. 적 손목이 꺾일 때 쳐.':'Rechtsklick. Schlag zu, wenn das Handgelenk des Feindes einknickt.',
'빨간 탄은 악의 덩어리다. 쳐내서 이용해.':'Rote Geschosse sind geballte Bosheit. Schlag sie zurück und nutze sie.',
'무지개빛만 피하면 돼! 나머지는 다 패링!':'Weich nur dem Regenbogen aus! Alles andere: parieren!',
'Q 보호막도 패링이 가능해!':'Der Q-Schild kann auch parieren!',
'위험해! 쉬프트 사슬기동으로 피해!!':'Gefahr! Shift-Kettensturm zum Ausweichen!!',
'쉬프트! 사슬기동은 이동기야! 끌려가면서 무적이라고!':'Shift! Kettensturm ist ein Bewegungsskill! Unverwundbar beim Ziehen!',
'스킬포인트가 쌓였어! K 눌러서 스킬 배우자!':'Fähigkeitspunkte bereit! Drück K, um Fähigkeiten zu erlernen!',
'속성을 읽어. 약점을 찌르면 두 배로 썩는다.':'Lies die Elemente. Triff Schwächen für doppelten Schaden.',
'K를 눌러봐! 스킬을 배울 수 있어!':'Drück K! Du kannst Fähigkeiten erlernen!',
'C 눌러서 능력치 찍어! 패시브도 있어~':'Drück C für Attribute! Passive gibt\'s auch~',
'G를 눌러. 대장간에서 장비를 강화할 수 있다.':'Drück G. Verbessere Ausrüstung in der Schmiede.',
'F키도 스킬 슬롯이야! 스킬 많으면 L로 배정해봐~':'F-Taste ist auch ein Fähigkeits-Slot! Nutz L zum Zuweisen~',
'Z. 필살기다. 아껴 써라.':'Z. Das ist dein Ultimativ. Setze es weise ein.',
'L-CTRL로 유령걸음이나 얼음보주 쓸 수 있어!':'L-CTRL für Geisterschritt oder Eiskugel!',
'L을 눌러. 스킬 슬롯을 정리해야 한다.':'Drück L. Ordne deine Fähigkeits-Slots.',
'가방 터지겠다! V 눌러서 창고에 넣어둬!':'Der Beutel platzt! Drück V für das Lager!',
'ESC로 설정 열 수 있어! 난이도 바꾸기, 자동물약 조절~':'ESC für Einstellungen! Schwierigkeit, Auto-Tränke~',
// --- Tutorial (Cat) ---
'...아직 살아있네. 좌클릭으로 저것들 쳐봐.':'...Noch am Leben. Versuch die mit Linksklick zu schlagen.',
'...치는 건 할 줄 아네. 피하는 건?':'...Zuschlagen kannst du. Aber ausweichen?',
'흥, 작살 못 맞추면 헛수고야.':'Hmph, verfehlst du die Harpune, war\'s umsonst.',
'...운이 좋았을 뿐이야. 아마.':'...Nur Glück gehabt. Wahrscheinlich.',
'...고기 냄새. 싫진 않네.':'...Riecht nach Fleisch. Nicht übel.',
'...말은 못해.':'...Es kann nicht sprechen.',
'예쁘다고 만지면 죽어.':'Anfassen, weil\'s hübsch ist? Du stirbst.',
'작살 던져! 끌려가면 무적이야!':'Wirf die Harpune! Unverwundbar beim Ziehen!',
'...마시든 말든. 네 목숨이니까.':'...Trink oder lass es. Es ist dein Leben.',
'그게 패링이야! 타이밍이 전부야~':'Das ist eine Parade! Timing ist alles~',
'화염엔 빙결! 암전엔 암흑! 기억해!':'Feuer schlägt Eis! Blitz schlägt Finsternis! Merk dir das!',
'...얼어붙은 놈은 오래 안 간다.':'...Gefrorene halten nicht lange durch.',
'얼었어! 빙결 중 1.5배야!':'Gefroren! 1,5-facher Schaden bei Frost!',
'...힘을 골라라. 전부 가질 순 없다.':'...Wähle deine Macht. Du kannst nicht alles haben.',
'스탯을 올려. 살고 싶으면.':'Steigere deine Werte. Wenn du leben willst.',
'좋은 장비는 강화해야 진짜 힘을 발휘해!':'Gute Ausrüstung muss verbessert werden, um ihre wahre Kraft zu entfalten!',
'...슬롯을 채워. 빈 손은 죽음이다.':'...Füll deine Slots. Leere Hände bedeuten Tod.',
'Z 누르면 대박! 쿨타임 길어서 타이밍 봐야 해!':'Drück Z für verheerenden Schaden! Lange Abklingzeit, achte aufs Timing!',
'Ctrl. 위기에 쓸 카드가 하나 늘었군.':'Ctrl. Eine Karte mehr für den Notfall.',
'스킬이 많아졌네~ L로 어디에 뭘 넣을지 골라!':'So viele Fähigkeiten~ Nutz L zum Zuweisen!',
'...버리기 아까운 건 창고에.':'...Was zu schade zum Wegwerfen ist, ins Lager.',
'...살아남은 것만으로도 대단하군. 설정을 확인해.':'...Allein zu überleben ist beeindruckend. Prüfe die Einstellungen.',
// --- System Messages ---
'MP 부족!':'Nicht genug MP!','ST 부족!':'Nicht genug ST!','악의 부족!':'Nicht genug Bosheit!',
'충전 중...':'Lade auf...','캔슬':'Abbruch','아이템 선택 필요':'Gegenstand auswählen',
'악의 소진...':'Bosheit erschöpft...','비문 발견...':'Inschrift entdeckt...',
'HP물약!':'HP-Trank!','HP물약 +1':'HP-Trank +1','HP물약 +2':'HP-Trank +2',
'HP/MP/ST 회복!':'HP/MP/ST wiederhergestellt!','보물상자 개봉!':'Truhe geöffnet!',
'익사!':'Ertrinken!','피웅덩이!':'Blutlache!','독혈!':'Giftblut!','잡힘!':'Gepackt!',
'콤보 종료':'Kombo beendet',
// --- Status Effects ---
'빙결!':'Gefroren!','화상!':'Verbrennung!','독!':'Gift!','감전!':'Schock!',
'기절!':'Betäubt!','봉인됨!':'Versiegelt!','관통!':'Durchschlag!',
// --- Skill Names ---
'기검참':'Ki-Hieb','악의구':'Bosheitskugel','회전참':'Wirbelwind','기폭팔':'Detonation',
'칼등 처내기':'Klingenparade','만화방창':'Nadelsperre','멸살광선':'Vernichtungsstrahl',
'원소추적탄':'Elementarsucher','악의 보호자':'Bosheitswächter','악의 사냥':'Bosheitsjagd',
'폭풍소환':'Wirbelsturm','해골무덤':'Knochengruft','신성폭발':'Heilige Explosion',
'블랙':'Schwarzer Stern','용암소환':'Lavabeschwörung','처형':'Hinrichtung','악마화 부활':'Dämonische Auferstehung',
'붉은꽃':'Purpurblüte','얼음보주':'Eiskugel','뇌전걸음':'Geisterschritt',
'만화방창 II':'Nadelsperre II','마력연사':'Arkaner Hagel','마력광선':'Arkaner Laser','업화선':'Höllenfeuerstrahl',
'지옥진':'Inferno-Formation','폭독칼날':'Seuchenklinge','악의폭풍':'Bosheitssturm',
'악의기둥':'Finsternissäule','회복의 영역':'Heilige Domäne','구속의 영역':'Fesselnde Domäne',
'아이스스톰':'Eissturm','대왕치기':'Titanenschlag','대왕치기 2':'Titanenschlag II',
'기동불꽃':'Kettenflamme','기동파괴':'Kettenbrecher','기동칼날개':'Kettenklingenflügel',
'평화의보호':'Ägide des Friedens','참회':'Buße','칼등날개':'Schildflügel',
'폭산탄':'Splitterschuss','파쇄의 영역':'Zerschmetternde Domäne','침식의 영역':'Korrodierende Domäne',
'관통의 영역':'Durchdringende Domäne','부활의 영역':'Domäne der Auferstehung','가시덫':'Dornenfalle',
'푸른비':'Azurregen','버스트루프':'Ausbruchsschleife','유령 허수아비':'Phantomlockvogel','폭발 허수아비':'Sprenglockvogel',
'공성쇠뇌':'Belagerungsarmbrust','사슬기동:충돌':'Kettensturm: Aufprall',
'사슬기동:화염':'Kettensturm: Flamme','전격이동':'Blitzschritt',
// --- Skill Activation ---
'기동칼날개!':'Klingenflügel!','기동불꽃!':'Kettenflamme!','기동파괴!':'Kettenbrecher!',
'사슬이동:강화!':'Kettensturm!','사슬기동:화염!':'Kettenflamme!',
'작살!':'Harpune!','진입!':'Eintreten!','레인라이트닝!':'Blitzregen!',
'마력연사!':'Arkaner Hagel!','🔷 마력광선!':'🔷 Arkaner Laser!','광선 해제':'Laser aus','MP 부족 — 광선 해제':'MP erschöpft — Laser aus','집중...':'Fokus...','시전...':'Wirken...',
'만화방창!':'Nadelsperre!','바늘출!':'Nadelschuss!','칼날!':'Klinge!',
'착지!':'Landung!','체간삭감!':'Haltungsbruch!',
'기동전폭 준비!':'Kettenexplosion bereit!','기동불꽃 준비!':'Kettenflamme bereit!',
'기동파괴 준비!':'Kettenbrecher bereit!',
'유령불꽃 ON':'Geisterflamme AN','유령불꽃 OFF':'Geisterflamme AUS',
'기동칼날개 AUTO ON':'Klingenflügel AUTO AN','기동칼날개 AUTO OFF':'Klingenflügel AUTO AUS',
'자동 버스트!':'Auto-Ausbruch!','연사 해제':'Schnellfeuer aus',
'당기기 모드':'Ziehmodus','밀어내기 모드':'Stoßmodus',
// --- Skill Slot Tooltips ---
'날개치기':'Flügelschlag','처내기':'Parade',
'Shift: 작살 발사 → 끌려감':'Shift: Harpunenwurf → Ziehen',
'Shift: 화염길+화상':'Shift: Feuerpfad+Verbrennung',
'CT: 전류변신+뇌전걸음 (쿨4초)':'CT: Blitzform+Geisterschritt (AZ 4s)',
'CT: 방어구체+빙결 (재입력: 파쇄)':'CT: Eissphäre+Frost (erneut: Zerschmettern)',
// --- HUD ---
'근접':'Nahkampf','견갑':'Schild','작살':'Harpune','마법':'Magie','보막':'Schild','유령':'Geist',
'스킬':'Fähigk.','대장':'Schmiede','인벤':'Inv.',
// --- Menu ---
'인벤토리':'Inventar','복수의 대장간':'Schmiede der Vergeltung','패시브 스킬':'Passive Fähigkeiten',
'전투 스킬':'Kampffähigkeiten','캐릭터 선택':'Charakterwahl',
// --- Elements ---
'물리':'Physisch','화염':'Feuer','빙결':'Eis','암흑':'Finsternis','암전':'Blitz','신성':'Heilig','대지':'Erde',
// --- Passives ---
'힘':'Stärke','민첩':'Geschick','지능':'Intelligenz','행운':'Glück',
'맹공':'Ansturm','철벽':'Bollwerk','돌파':'Durchbruch','반격':'Vergeltung',
'마력폭주':'Arkaner Rausch','정밀사격':'Präzisionsschuss','수호':'Beschützung','수호신':'Schutzgeist',
'회복력':'Regeneration','급소':'Vitaltreffer','약탈':'Plünderung','관통':'Durchschlag',
'마력회복':'Manaregeneration','쇠뇌력':'Armbrustmeisterschaft','광전사':'Berserker','추적자':'Verfolger',
'물리관통':'Phys. Durchdr.','마법관통':'Mag. Durchdr.',
// --- Weapons (Tier 0) ---
'녹슨 대검':'Rostiges Großschwert','강철 대검':'Stahl-Großschwert','흑요석 대검':'Obsidian-Großschwert',
'낡은 석궁':'Abgenutzte Armbrust','강철 석궁':'Stahl-Armbrust','흑요석 석궁':'Obsidian-Armbrust',
'대검':'Großschwert','석궁':'Armbrust','연사석궁':'Schnellfeuer-Armbrust','마력석궁':'Arkane Armbrust',
// --- Misc ---
'악의 추출':'Bosheitsextraktion','악의':'Bosheit','필살기':'Ultimativ','필살기 해제':'Ultimativ entfernt',
'이전':'Übertragen','강화':'Verstärken','개봉!':'Geöffnet!',
'여신의 가호':'Segen der Göttin',
'과부하!':'Überlast!',
// --- Affix Names ---
'맹독의':'Giftig','불꽃의':'Flammend','냉기의':'Frostig','번개의':'Voltaisch','암흑의':'Verflucht',
'관통의':'Durchbohrend','광폭의':'Rasend','파쇄의':'Zerschmetternd','연쇄의':'Kettenreaktiv',
'학살의':'Mordend','폭발의':'Explosiv','집중의':'Fokussiert','쾌속의':'Flink','패리의':'Parierend',
'추적자의':'Des Verfolgers','작살의':'Harpunen-','궁극의':'Höchst','집중력의':'Achtsam',
'강인의':'Standhaft','수호의':'Schützend','활력의':'Vital','신속의':'Beschleunigt',
'화염수호':'Feuerschutz','빙결수호':'Eisschutz','암전수호':'Blitzschutz','암흑수호':'Finsternisschutz','독수호':'Giftschutz','전원소수호':'Allschutz',
'강철의':'Gepanzert','반사의':'Reflektierend','가시의':'Dornig','흡수의':'Absorbierend','인내의':'Ausdauernd',
'위기의':'Verzweifelt','피격반격의':'Vergeltend',
'패링폭발의':'Paradeexplosion','스태거폭발의':'Taumelexplosion','원소전환의':'Konvertierend','정화의':'Läuternd',
'불굴의':'Unbeugsam','부활의':'Wiederbelebend',
'약탈의':'Plündernd','경험의':'Erfahren','골드의':'Golden','포션강화의':'Trankverstärkend','사슬의':'Verkettet',
'진혼의':'Weihend','윤회의':'Zyklisch',
'생명력의':'Lebenskräftig','재생의':'Regenerierend','치유의':'Heilend',
'마력의':'Arkan','절약의':'Sparsam','영혼의':'Seelengebunden',
'예리한':'Scharf','맹렬한':'Brutal','파멸의':'Verheerend',
// --- Settings UI ---
'게임 설정':'Spieleinstellungen','화면 흔들림':'Bildschirmwackeln','파티클 양':'Partikelmenge',
'효과음 볼륨':'Effektlautstärke','음악 볼륨':'Musiklautstärke','난이도':'Schwierigkeit',
'자동 물약':'Auto-Trank','최소 줍기 등급':'Min. Aufhebe-Stufe','최소 줍기 티어':'Min. Aufhebe-Tier',
'FPS 제한':'FPS-Limit','해상도 스케일':'Auflösungsskalierung','펫 자동수거':'Begleiter-Autosammeln',
'화면 설정':'Anzeigeeinstellungen','화면 모드':'Anzeigemodus','보스 AI 디버그':'Boss-KI-Debug',
'유령불꽃 크기':'Geisterflammen-Größe','화면 명암':'Helligkeit','유령 글로우':'Geisterleuchten',
'기동:칼날개 AUTO':'Klingenflügel AUTO',
'일반':'Normal','어려움':'Schwer','지옥':'Hölle','이상':'oder höher','사용 안 함':'Deaktiviert',
'창 모드':'Fenstermodus','보더리스':'Randlos','전체화면':'Vollbild',
'설정':'Einstellungen','조작 키 설정 (클릭하여 변경)':'Tastenbelegung (Klick zum Ändern)',
// --- Key Guide ---
'좌클릭 무기 공격':'LMT Waffenangriff','우클릭 탭 칼등 처내기':'RMT Klingenparade',
'우클릭 홀드 연속 처내기':'RMT gehalten: Dauerparade','SHIFT 작살 발사':'SHIFT Harpunenwurf',
'이동':'Bewegen','아이템 줍기':'Gegenstand aufheben','능력치 (스탯/패시브)':'Attribute (Stats/Passive)',
// --- Forge ---
'복수의 대장간':'Schmiede der Vergeltung','분해':'Zerlegen','제작':'Herstellen',
// --- Death Screen ---
'사망':'Tod','부활':'Wiederbelebung','로비로':'Zur Lobby',
// --- Inventory/Storage ---
'가방에 공간이 없습니다!':'Kein Platz im Beutel!','가방이 가득 찼습니다!':'Beutel ist voll!',
'창고가 가득 찼습니다!':'Lager ist voll!','퀵슬롯이 가득 찼습니다!':'Schnellslot ist voll!',
'결정 주머니가 가득 찼습니다!':'Kristallbeutel ist voll!','결정 주머니 가득!':'Kristallbeutel voll!',
'악의가 부족합니다!':'Nicht genug Bosheit!','가방이 비어있습니다':'Beutel ist leer',
'창고가 비어있습니다':'Lager ist leer','비어있음':'Leer','어픽스 없음':'Kein Affix',
'장착!':'Angelegt!','해제':'Abgelegt','보관':'Einlagern','꺼내기':'Herausnehmen',
'현재 장착':'Derzeit angelegt','없음 — 제작하세요!':'Keins — Stelle eins her!',
'리셋할 포인트가 없습니다':'Keine Punkte zum Zurücksetzen',
'키 설정 초기화 완료':'Tastenbelegung zurückgesetzt',
// --- Forge/Craft ---
'제작 확률':'Herstellungschance','제작 비용':'Herstellungskosten','보유 악의':'Bosheit vorhanden',
// --- Canvas UI ---
'보스방':'Bossraum','안식처':'Zuflucht','회복':'Erholung','점화':'Entzünden',
'비석':'Stele','읽기':'Lesen','파괴':'Zerstören','제단':'Altar','기원':'Beten',
'잔해':'Trümmer','열기':'Öffnen','문지기':'Torwächter',
'부활 판정 중...':'Auferstehungsurteil...','기폭 준비!':'Detonation bereit!',
'탈출':'Flucht','연타':'Hämmern',
'추적암전':'Verfolgungsblitz','만화광선':'Leuchtstrahl','최종 마법':'Endgültige Magie',
'감시중':'Überwacht','대기':'Bereitschaft','작동중':'Aktiv','설치 가능':'Aufstellbar',
'균열 임박!':'Riss steht bevor!','흡수 중...':'Absorbiere...',
'흡수 완료 — 재입력으로 회수':'Fertig — erneut drücken zum Einsammeln',
'화상':'Verbrennung','당기기':'Ziehen','밀어내기':'Stoßen',
'단계':'Stufe','단':'Stufe',
// --- Skill Panel ---
'습득!':'Erlernt!','리셋!':'Zurückgesetzt!','세팅!':'Gesetzt!','회수':'Einziehen',
'합체 해제':'Fusion lösen','리셋':'Zurücksetzen','환불':'Rückerstattung',
'파트너 클릭!':'Partner klicken!','SP부족!':'SP nötig!',
'같은 보석 스킬 습득 시 합체 가능':'Fusion möglich bei gleichem Edelstein-Skill',
'펼쳐서 초기화':'Aufklappen zum Zurücksetzen','슬롯:':'Slot:',
// --- Stats ---
'남은 SP':'Verbl. SP','맞아서 사망':'Durch Treffer gestorben','레벨':'Stufe','최대HP':'Max HP',
// --- Enemy Names ---
'방랑 기사':'Wandernder Ritter','보물 악마':'Schatzdämon','거울의 사도':'Apostel des Spiegels',
'상인 악마':'Händlerdämon','사슬의 죄수':'Kettengefangener','시간의 사도':'Apostel der Zeit',
'탐욕의 사도':'Apostel der Gier','저주받은 쌍둥이':'Verfluchte Zwillinge','차원 균열체':'Dimensionsriss',
'죽음 그 자체':'Der Tod selbst',
// --- Crystals ---
'HP결정':'HP-Kristall','ST결정':'ST-Kristall','MP결정':'MP-Kristall',
'ATK결정':'ATK-Kristall','DEF결정':'DEF-Kristall','속도결정':'Tempo-Kristall',
'크리결정':'Krit-Kristall','치명결정':'KritSchd-Kristall','화염결정':'Feuer-Kristall',
'냉기결정':'Eis-Kristall','암흑결정':'Finsternis-Kristall','번개결정':'Blitz-Kristall',
'신성결정':'Heilig-Kristall','생명결정':'Lebens-Kristall','기력결정':'Ausdauer-Kristall',
'마력결정':'Mana-Kristall','행운결정':'Glücks-Kristall',
'조각':'Fragment','파편':'Splitter','순수결정':'Reiner Kristall','완전결정':'Perfekter Kristall',
'결정 주머니':'Kristallbeutel','결정이 없습니다':'Keine Kristalle','가루':'Staub',
'전체':'Alle','스탯':'Stat','원소':'Elem','유틸':'Util',
'현재':'Aktuell','최대 강화 달성 (+20)':'Max verstärkt (+20)','강화 시':'Nach Verstärkung',
'합성':'Synthetisieren',
'같은 종류·같은 성급 결정 3개 → 1성급 상승 (강화 리셋)':'3 Kristalle gleicher Art & Stufe → 1 Stufe höher (Verstärkung zurückgesetzt)',
'합성 가능한 결정이 없습니다 (같은 종류·성급 3개 필요)':'Keine synthetisierbaren Kristalle (3 gleicher Art & Stufe nötig)',
'결정 분해 → 결정 가루':'Kristall zerlegen → Kristallstaub',
'분해할 결정이 없습니다':'Keine Kristalle zum Zerlegen',
'결정 제작 (가루 → 결정)':'Kristall herstellen (Staub → Kristall)',
'탈착':'Entfernen','빈 슬롯':'Leerer Slot',
'결정 선택 후 클릭':'Kristall wählen, dann klicken','클릭하여 선택결정 장착':'Klicken, um gewählten Kristall einzusetzen',
'획득!':'Erhalten!','제작!':'Hergestellt!','합성!':'Synthetisiert!','최상위 일괄합성':'Massen-Synthese','일괄합성 완료':'Massen-Synthese abgeschlossen',
// --- Stage Names ---
'벌레굴':'Wurmnest','얼음굴':'Eishöhle','고통의 화염지대':'Flammenöde der Qual',
'지옥의 군단':'Höllenlegion','사도의 마굴':'Schlund des Apostels','지옥성':'Höllenfeste',
// --- Misc ---
'엑소듀서 전사':'Exoduser-Krieger','포이즈':'Haltung',
'신성폭발':'Heilige Explosion','뇌전걸음':'Geisterschritt',
'지옥창고':'Höllenlager','선택분해':'Selektives Zerlegen','쓰레기':'Schrott',
'복구 불가!':'Nicht wiederherstellbar!','중요잠금':'Wichtig-gesperrt',
// --- Phase 9 additions ---
'자동 장착!':'Auto-angelegt!','분해! 가루 +':'Zerlegt! Staub +',
'추적암전':'Verfolgungsblitz','암전':'Blitz',
'평화보호':'Ägide','지진폭풍':'Erdbebensturm','회전기폭':'Wirbel-Det.',
'공격':'Angriff','보호막':'Schild','합체 스킬로 통합됨':'In Fusionsfähigkeit integriert','얼음보주 안에선 사용 불가!':'Nicht nutzbar in der Eiskugel!',
'Shift+키로 폭파':'Shift+Taste zum Sprengen','취소':'Abbruch','충전 중...':'Lade auf...',
'쿨다운 중...':'Abklingzeit...','시전 중...':'Wirke...','악의 부족!':'Nicht genug Bosheit!',
'악의 부족! (12)':'Nicht genug Bosheit! (12)','악의 부족! (15)':'Nicht genug Bosheit! (15)',
'악의 부족! (20)':'Nicht genug Bosheit! (20)','악의 부족! (10)':'Nicht genug Bosheit! (10)',
'ST 부족!':'Nicht genug ST!','HP 부족!':'Nicht genug HP!',
'필살기 슬롯 클릭하여 배정!':'Ultimativ-Slot anklicken zum Zuweisen!',
'필살기 스킬을 습득하세요':'Erlerne eine Ultimativ-Fähigkeit',
'우클릭(칼등치기)에 합체됨':'In RMT (Klingenparade) integriert',
'T(석궁자동)에 세팅하세요':'Auf T (Auto-Armbrust) setzen',
'공성쇠뇌 철거 → 이동식':'Belagerungsarmbrust abgebaut → tragbar',
'ST 부족! (100)':'Nicht genug ST! (100)',
'HP 99% 이상!':'HP 99%+!','그로기 보스 없음!':'Kein benommener Boss!',
'이미 폭풍 지역!':'Bereits in Sturmzone!','이미 빙풍 지역!':'Bereits in Eissturmzone!',
'💎 푸른비 해금!':'💎 Azurregen freigeschaltet!','💫 버스트루프 해금!':'💫 Ausbruchsschleife freigeschaltet!',
'👻 유령 허수아비 해금!':'👻 Phantomlockvogel freigeschaltet!',
'쿨 ':'AZ ','과부하 ':'Überlast ',
'🕊️💎 블루콩!':'🕊️💎 Blaue Bohne!','🛡️💎 빨콩→블루콩!':'🛡️💎 Rot→Blaue Bohne!',
'🛡️💎 무지개→블루콩!':'🛡️💎 Regenbogen→Blaue Bohne!',
'레어':'Selten','슬롯':'Slot',
'성공률':'Erfolgsrate','AI 자동 강화':'KI-Auto-Verstärkung','최대 강화 달성!':'Max. Verstärkung erreicht!',
'최대 강화':'Max verstärkt','회복량':'Heilungsmenge','현재 장착':'Derzeit angelegt',
'없음 — 제작하세요!':'Keins — Stelle eins her!','제작 확률':'Herstellungschance',
'분해할 아이템이 없습니다.':'Keine Gegenstände zum Zerlegen.','🔨 제작':'🔨 Herstellen',
'체간':'Haltung','아이템에 마우스를 올리거나 좌클릭으로 선택하세요':'Über einen Gegenstand fahren oder Linksklick zum Auswählen',
// --- Phase 10: death/levelup/intro screen ---
'중독':'Gift','지뢰':'Mine','함정':'Falle','산호가시':'Korallenspitze',
'투사체':'Projektil','도트':'DoT','레어몹':'Seltener Mob',
'구역':'Zone','가시!':'Spitze!',
// --- Hell circle / palette names ---
'림보':'Limbus','색욕':'Wollust','탐식':'Völlerei','탐욕':'Gier','분노':'Zorn','이단':'Häresie','폭력':'Gewalt',
'분노!':'Zorn!','탐욕!':'Gier!','💀 분노 폭발!':'💀 Zornexplosion!','심연의 분노!':'Abgrundszorn!','쌍둥이의 분노!':'Zorn der Zwillinge!',
// --- HUD / misc ---
'소환굴':'Beschwörungsgrube',
'처치!':'Besiegt!','왕관 착용':'Krone aufsetzen','왕관 해제':'Krone abnehmen',
'맨손':'Bloße Hände','없음':'Keine','갑옷':'Rüstung','부츠':'Stiefel',
// --- Elite / Mod / Aura ---
'매직':'Magisch','챔피언':'Champion',
'빙결':'Gefroren','초속':'Eile','강타':'Schmettern','재생':'Regeneration','맹독':'Gift','소환':'Beschwören',
'기생':'Parasit','분열':'Teilung','용암자취':'Lavaspur','사망폭발':'Todesexplosion',
'화염사슬':'Feuerkette','광전':'Raserei','텔레포트':'Teleport','보호막':'Barriere',
'소용돌이':'Wirbel','환영':'Phantom','전격반사':'Schockreflexion','감전':'Elektrisieren',
'낙뢰':'Donner','연쇄전격':'Kettenblitz','동료불사':'Verbündeten-Unsterblichkeit',
'영혼포식':'Seelenverschlingen','시간왜곡':'Zeitverzerrung','혼돈변이':'Chaosmutation',
'복수자':'Rächer','마법보초':'Magischer Wächter','환영술사':'Illusionist',
'함성':'Schlachtruf','치유':'Heilung','신속':'Schnelligkeit','수호':'Wächter',
// --- Character ---
'다크 판타지 전사. 거대검+검은 갑옷':'Dunkler Fantasy-Krieger. Großschwert + Schwarze Rüstung',
// --- Phase 11: missing addTxt/showPH/notify translations ---
'⚡ 사슬이동:강화!':'⚡ Kette:Verstärkt!',
'⚡ 사슬기동:화염!':'⚡ Kettensturm: Flamme!',
'달성!':'Erreicht!',
'ST':'ST','부족!':'Unzureichend!',
'타':'Treffer',
'🌀 당기기 모드':'🌀 Ziehmodus',
'💥 밀어내기 모드':'💥 Stoßmodus',
'🕊️빨콩 흡수':'🕊️Rote Bohne absorbiert',
'🕊️흡수':'🕊️Absorbiert',
'💎유도 폭발!':'💎Lenkexplosion!',
'💥반사 폭발!':'💥Reflexionsexplosion!',
'⚡⚡ 참회 귀환!':'⚡⚡ Buße-Rückkehr!',
'⚡ 참회!':'⚡ Buße!',
'파도!':'Welle!',
'암전!':'Blitz!',
'암흑!':'Finsternis!',
'암흑창!':'Finsternislanze!',
'빛창!':'Lichtlanze!',
'체 소환!':'beschworen!',
'개 설치!':'platziert!',
'💥 보스 그로기!':'💥 Boss Benommen!',
'💥 그로기!':'💥 Benommen!',
'보상':'Bonus',
'⚡ 암전나선!':'⚡ Blitzhelix!',
'🌋 지진폭풍!':'🌋 Erdbebensturm!',
'SP슬롯':'SP-Slot',
'F슬롯':'F-Slot',
'⚔🩸 독혈해방!':'⚔🩸 Seuchenbefreiung!',
'⚔ 칼날 해방!':'⚔ Klingenbefreiung!',
'🔨🌋 지옥강타!':'🔨🌋 Inferno-Hieb!',
'🔨 대왕치기!':'🔨 Titanenschlag!',
'✟ 신성한 결계!':'✟ Heilige Barriere!',
'🛡 회복의 영역!':'🛡 Heilige Domäne!',
'기폭팔!':'Detonation!','강제기폭!':'Erzwungene Detonation!','자동기폭!':'Auto-Detonation!',
'회전기폭!':'Wirbel-Detonation!','해제기폭!':'Auslöse-Detonation!','지진기폭!':'Erdbeben-Detonation!',
'혼돈의 왕관':'Krone des Chaos',
'전지전능의 왕관':'Krone der Allmacht',
'악마의 팔찌':'Dämonenarmreif',
'생명의 팔찌':'Armreif des Lebens',
// --- wave direction names (full addTxt strings) ---
'🌊 위→아래 파도!':'🌊 Oben→Unten Welle!','🌊 오른→왼 파도!':'🌊 Rechts→Links Welle!',
'🌊 아래→위 파도!':'🌊 Unten→Oben Welle!','🌊 왼→오른 파도!':'🌊 Links→Rechts Welle!',
// --- Phase 12: remaining addTxt/UI translations ---
// --- rare mob / special ---
'무적!':'Unverwundbar!','🪞 반격!':'🪞 Konter!','💢 반격!':'💢 Konter!',
'흡수!':'Absorbiert!','반격 발사!':'Konterschuss!',
'저주! 드랍률 -50%':'Fluch! Droprate -50%','도망!':'Flucht!',
'위상!':'Phase!','방어!':'Verteidigung!',
'회수 HP+':'Einzug HP+','이동식 복귀':'Tragbar zurück','캔슬':'Abbruch',
'약점!':'Schwäche!','저항!':'Resistenz!','관통!':'Durchschlag!',
'콤보 종료: ':'Kombo beendet: ','익사!':'Ertrinken!',
'피웅덩이!':'Blutlache!','독혈!':'Giftblut!','비문 발견...':'Inschrift entdeckt...',
'보물상자 개봉!':'Truhe geöffnet!','악의 +':'Bosheit +','잡힘!':'Gepackt!',
'저주 ':'Fluch ','불발...':'Fehlschuss...',
'작살 약점!':'Harpunen-Schwäche!',
'전염 x':'Seuche x','흡수 완료!':'Absorption abgeschlossen!',
'부활 성공!':'Wiederbelebung gelungen!','부활 실패...':'Wiederbelebung fehlgeschlagen...',
'산호가시':'Korallenspitze','차원 이동!':'Dimensionssprung!','독!':'Gift!',
'탈출!':'Entkommen!','기절 해제':'Betäubung aufgehoben',
'아이템 선택 필요':'Gegenstand auswählen','악의 부족':'Nicht genug Bosheit','악의 소진...':'Bosheit erschöpft...',
'스킬 미습득':'Keine Fähigkeiten erlernt','펼치기':'Aufklappen','접기':'Einklappen',
'조건 미달!':' nicht erfüllt!','해제!':' Gelöst!',
'자동 ON':' Auto AN','자동 OFF':' Auto AUS','스킬 해제':' Fähigkeit entfernt',
'닫기':'Schließen','장착 중':'Angelegt','보관 아이템':'Lager-Gegenstand',
// --- Phase 13: massive batch — skill activation ---
'클릭으로 선택 · ESC로 닫기':'Klick zum Wählen · ESC zum Schließen',
'선택됨':'Ausgewählt',
'악의 부족! (30)':'Nicht genug Bosheit! (30)',
'MP 부족! (40)':'Nicht genug MP! (40)','MP 부족! (100)':'Nicht genug MP! (100)','MP 부족! (10)':'Nicht genug MP! (10)',
'MP 부족! (':'Nicht genug MP! (',
'✟ 시전...':'✟ Wirke...','🌋 시전...':'🌋 Wirke...','⛧ 시전...':'⛧ Wirke...',
'❄ 진입!':'❄ Eintreten!',
'🔱 작살!':'🔱 Harpune!',
'레벨 부족! (요구: Lv.':'Stufe zu niedrig! (Ben.: Lv.',
' 장착!':' Angelegt!',
' 해제':' Abgelegt',
'👿 악의 추출: +':'👿 Bosheitsextraktion: +',
'F 슬롯 해제':'F-Slot entfernt',
'💫 집중...':'💫 Fokus...',
'⚡ 마력연사!':'⚡ Arkaner Hagel!',
'❄빙결!':'❄Gefroren!','🟢독!':'🟢Gift!','⚡감전!':'⚡Schock!','🔥화상!':'🔥Verbrennung!',
'✦ 여신의 가호 — SP+5 AP+3':'✦ Segen der Göttin — SP+5 AP+3',
'⚔ 기동칼날개!':'⚔ Klingenflügel!',
'🔥 화염관통!':'🔥 Feuerdurchschlag!',
'🔱 관통!':'🔱 Durchschlag!',
'⚔ 칼날!':'⚔ Klinge!',
'💥 착지!':'💥 Landung!',
'💫 기절!':'💫 Betäubt!',
'⚡ 체간삭감!':'⚡ Haltungsbruch!',
'⚡ 기동파괴! ':'⚡ Kettenbrecher! ',
'🔥 기동불꽃!':'🔥 Kettenflamme!',
'🔥 기동불꽃! ':'🔥 Kettenflamme! ',
'단계 ×':' x',
'⚡ 기동전폭! x':'⚡ Kettenexplosion! x',
'🔥🔥 3중폭!':'🔥🔥 3-fach!','🔥🔥🔥 6중폭!':'🔥🔥🔥 6-fach!','🔥🔥🔥🔥 9중폭!':'🔥🔥🔥🔥 9-fach!','💥 불꽃폭발! ':'💥 Flammenexplosion! ',
'🔥 기동불꽃 준비!':'🔥 Kettenflamme bereit!',
'🔨 기동파괴 준비!':'🔨 Kettenbrecher bereit!',
'⚡ 기동전폭 준비!':'⚡ Kettenexplosion bereit!',
'중독':'Gift',
'⚡ 과부하! 5초':'⚡ Überlast! 5s',
'💫 자동 버스트!':'💫 Auto-Ausbruch!',
'🔨 칼등날개!':'🔨 Schildflügel!',
'💥폭발!':'💥Explosion!',
'🛡️💎 유도반사!':'🛡️💎 Lenk-Reflexion!',
'⚡💎 블루콩!':'⚡💎 Blaue Bohne!',
'💎 블루콩!':'💎 Blaue Bohne!',
'⚡반사!':'⚡Reflexion!',
'💎 푸른비 OFF':'💎 Azurregen AUS',
'💎 푸른비 ON!':'💎 Azurregen AN!',
'🔥 지옥진!':'🔥 Inferno-Formation!',
'🔥 업화선!':'🔥 Höllenfeuerstrahl!',
'✦ 평화 충격파! ':'✦ Friedensschockwelle! ',
'⚡ 전류 방출!':'⚡ Stromentladung!',
'⚡⚡ 레인라이트닝!':'⚡⚡ Blitzregen!',
'💫 광역!':'💫 Flächenangriff!',
'🔥 불장판!':'🔥 Feuerzone!',
'💫 피니셔!':'💫 Finisher!',
'☠ 지옥에서 귀환!':'☠ Aus der Hölle zurückgekehrt!',
'☠ 완전 사망!':'☠ Endgültiger Tod!',
'⚔ 처형! ':'⚔ Hinrichtung! ',
'💥 지뢰!':'💥 Mine!',
'⚠ 함정!':'⚠ Falle!',
'❌ 우클릭으로! -':'❌ Rechtsklick! -',
'❌ Q키로! -':'❌ Q-Taste! -',
'💥무지개 폭발! ':'💥Regenbogenexplosion! ',
'🛡️💎 블루콩!':'🛡️💎 Blaue Bohne!',
'⬜화이트볼!':'⬜Weißkugel!',
'✨💎 블루콩!':'✨💎 Blaue Bohne!',
'💜다크볼!':'💜Dunkelkugel!',
'❄빙판!':'❄Eisfläche!',
'🌨빙결!':'🌨Gefroren!',
'🕸둔화!':'🕸Verlangsamung!',
'⚠트랩!':'⚠Falle!',
'💀 역병 처형!':'💀 Seuchen-Hinrichtung!',
'💥 역병 Finale!':'💥 Seuchen-Finale!',
'⚔ 균열 악마!':'⚔ Rissdämon!',
'자동회수 HP+':'Auto-Einzug HP+',
'MP 부족 — 연사 해제':'MP niedrig — Schnellfeuer aus',
'MP 부족 — 푸른비 OFF':'MP niedrig — Azurregen AUS',
'🛡️반사!':'🛡️Reflexion!',
'⚡🦴 참회 귀환!':'⚡🦴 Buße-Rückkehr!',
'🦴⚡해골번개!':'🦴⚡Knochenblitz!',
'⚡악의폭풍!':'⚡Bosheitssturm!',
'❄아이스스톰!':'❄Eissturm!',
'⚡ 암전폭발!':'⚡ Blitzexplosion!',
'⚡ 레인라이트닝! x':'⚡ Blitzregen! x',
'❄ 탈출!':'❄ Flucht!',
'⚡쉴드!':'⚡Schild!',
'❄🌪️ 얼음보주!':'❄🌪️ Eiskugel!',
'🌪️ 전개!':'🌪️ Entfalten!',
'❄ 빙결흡인!':'❄ Frostwirbel!',
'❄☄ 빙결폭발!':'❄☄ Frostexplosion!',
'☄️ 흡인!':'☄️ Wirbel!',
'☄️ 대폭발!':'☄️ Mega-Explosion!',
'❄ 얼음보주!':'❄ Eiskugel!',
'❄ 파쇄!':'❄ Zerschmettern!',
'☄️💥 대폭발!':'☄️💥 Mega-Explosion!',
'반사!':'Reflexion!',
// --- Phase 13: boss moves ---
'💀 도넛!':'💀 Donut!','💀 전멸!':'💀 Vernichtung!',
'🌊 파도!':'🌊 Welle!','속박!':'Fesselung!','반격!':'Konter!',
'분신!':'Doppelgänger!','분신 파괴!':'Doppelgänger zerstört!','무기 해방!':'Waffenbefreiung!',
'❄프리즌!':'❄Gefängnis!','⚡ 증표 ':'⚡ Zeichen ',
'흔들!':'Erschütterung!','⚠ 광역 발사!':'⚠ Flächenfeuer!',
'🔥 확산!':'🔥 Ausbreitung!','⚠ 돌진!':'⚠ Sturmangriff!',
'🦅 도약!':'🦅 Sprung!','⚡ 레이저!':'⚡ Laser!',
'🌊 충격파!':'🌊 Schockwelle!','👹 소환!':'👹 Beschwörung!',
'☄ 유성우!':'☄ Meteorregen!','🖐 잡기!':'🖐 Griff!',
'🌀 회전참!':'🌀 Wirbelwind!','💣 지뢰!':'💣 Mine!',
'🌀 흡인!':'🌀 Vakuum!','🔴 빨간콩 폭풍!':'🔴 Rote-Bohnen-Sturm!',
'🔴🔴 콩 비!':'🔴🔴 Bohnenregen!',
'🌊 부채꼴 충격파!':'🌊 Fächerschockwelle!',
'✴ 멸광 레이저!':'✴ Vernichtungslaser!',
'🔴 추적 장판!':'🔴 Verfolgungszone!',
'💥 속성탄!':'💥 Elementargeschoss!',
'⚔ 검기!':'⚔ Schwert-Ki!','⚔ 재단참!':'⚔ Erntehieb!',
'🌀 나선탄!':'🌀 Spiralgeschoss!','⚠ 찌르기!':'⚠ Stoß!',
'🔥🔥 지옥기둥!':'🔥🔥 Höllensäule!',
'⚔ 환영검!':'⚔ Phantomklinge!',
'💢 반격자세!':'💢 Konterhaltung!',
'⚔ 연격!':'⚔ Kombo!','🌑 암흑!':'🌑 Finsternis!',
'👥 분신!':'👥 Doppelgänger!','🌋 균열!':'🌋 Riss!',
'🌊 파동!':'🌊 Woge!','💣 추적지뢰!':'💣 Verfolgungsmine!',
'⏪ 되감기!':'⏪ Zurückspulen!','🌀 중력장!':'🌀 Gravitationsfeld!',
'🔨 벽밀기!':'🔨 Wandstoß!','☠ 독안개!':'☠ Giftnebel!',
'⛓ 감옥!':'⛓ Kerker!','⚡ 연쇄번개!':'⚡ Kettenblitz!',
'🔮 궤도탄!':'🔮 Orbitalgeschoss!','🛡 방패돌진!':'🛡 Schildsturm!',
'🪞 반격자세!':'🪞 Konterhaltung!','⚓ 속박!':'⚓ Fesselung!',
'👤 분신!':'👤 Doppelgänger!','🖐 탈취!':'🖐 Diebstahl!',
'🔥🔥 용암 지대!':'🔥🔥 Lavazone!',
'🌧🌧 화염 폭격!':'🌧🌧 Feuerbombardement!',
'⚡⚡ 전격 장막!':'⚡⚡ Blitzschleier!',
'💀 내 곁으로!':'💀 Komm zu mir!',
'⭕ 안전!':'⭕ Sicher!',
'💀💀 전멸 폭발!':'💀💀 Vernichtungsexplosion!',
'⚡ 쐐기 소멸!':'⚡ Keil-Auslöschung!',
'🌊충격파!':'🌊Schockwelle!',
'👿악의+100':'👿Bosheit+100',
'💥패링폭발!':'💥Paradeexplosion!',
'균열 충돌! ':'Riss-Kollision! ',
'벽 충돌! ':'Wand-Kollision! ',
'소환!':'Beschwörung!','환영!':'Phantom!',
'⚡낙뢰!':'⚡Donner!','⚡빔!':'⚡Strahl!',
'환영술!':'Illusion!','💀소환!':'💀Beschwörung!',
'🔮주술!':'🔮Fluch!','🩸산란!':'🩸Brut!',
'💢광폭!':'💢Raserei!','🕷산란!':'🕷Brut!',
'❄서리!':'❄Reif!','❄빙결파!':'❄Frostwelle!',
'💀빙마!':'💀Eisdämon!',
// --- Phase 13: mob actions ---
'돌진!':'Sturmangriff!','충격파!':'Schockwelle!','독안개!':'Giftnebel!',
'연타!':'Hagel!','포효!':'Gebrüll!','강화!':'Verstärkt!',
'꼬리!':'Schwanz!','은신...':'Tarnung...','기습!':'Hinterhalt!',
'산란!':'Brut!','독가스!':'Giftgas!','소멸...':'Auflösung...',
'강타!':'Schmettern!','분비!':'Absonderung!','채찍!':'Peitsche!',
'출혈!':'Blutung!','급강하!':'Sturzflug!','방출!':'Entladung!',
'충격!':'Aufprall!','치유!':'Heilung!','의식!':'Ritual!',
'지옥불!':'Höllenfeuer!','끌려감!':'Weggezogen!','혀!':'Zunge!',
'응시!':'Starren!','낙하!':'Absturz!','핏방울!':'Blutstropfen!',
'일어남!':'Auferstehung!','휩쓸기!':'Fegen!','웅크림':'Ducken',
'뼈칼날!':'Knochenklinge!','감속!':'Verlangsamung!','비명!':'Schrei!',
'화산탄!':'Vulkangeschoss!','자폭!':'Selbstzerstörung!','감싸기!':'Umhüllen!',
'잡기!':'Griff!','내리찍기!':'Schmetterer!','브레스!':'Odem!',
'비행!':'Flug!','용암비!':'Lavaregen!','물뿜기!':'Wasserstrahl!',
'빛...':'Licht...','삼키기!':'Verschlingen!','마비!':'Lähmung!',
'방전!':'Entladung!','집게찍기!':'Zangenhieb!','찍기!':'Schmetterer!',
'붙잡기!':'Ergreifen!','감아올리기!':'Umschlingen!','파편!':'Splitter!',
'할퀴기!':'Kratzen!','기생충!':'Parasit!',
'심연 해방!':'Abgrundbefreiung!','촉수난타!':'Tentakelhagel!',
'삼지창!':'Dreizack!','소용돌이!':'Wirbel!','해일!':'Tsunami!',
'끼걱!':'Knarzen!','폭발!':'Explosion!','체인!':'Kette!',
'갈기!':'Mähne!','공포!':'Terror!','흡혈!':'Blutsaugen!',
'베기!':'Hieb!','비이이명!!':'Kliiiirr!!','분열!':'Teilung!',
'3연참!':'Dreifachhieb!','패링!':'Parade!',
'...복사...':'...Kopie...','불균형...저주!':'Ungleichgewicht...Fluch!',
'저주!':'Fluch!','균형...강화!':'Gleichgewicht...Verstärkung!',
'심판의 기둥!':'Säule des Gerichts!','처형 선고!':'Todesurteil!',
'고통의 해방!':'Befreiung des Schmerzes!','너도 느껴봐라!':'Spüre es auch!',
'대검난무!':'Großschwert-Raserei!','촉수!':'Tentakel!',
'전방위 빔!':'Rundstrahl!','회피!':'Ausweichen!',
// --- Phase 13: rare mob / merchant ---
'[F] 상점':'[F] Laden','거래 성공!':'Handel erfolgreich!',
'악의 부족! (':'Nicht genug Bosheit! (',
'상인이 떠납니다...':'Der Händler verschwindet...',
'사슬 해방!':'Kettenbefreiung!','완전 해방!':'Vollständige Befreiung!',
'⏪ 시간 되감기!':'⏪ Zeitrückspulung!','전환!':'Wechsel!',
'부활 ':'Wiederbelebung ','🌀균열!':'🌀Riss!','...사라짐':'...Verschwunden',
'낫 베기!':'Sensenhieb!','☠ 죽음의 선고!':'☠ Todesurteil!',
'선고 집행...':'Urteil vollstreckt...',
'⚡패링!':'⚡Parade!','경직!':'Taumeln!',
'⚠ 잡혔다!':'⚠ Gepackt!','💥 내던지기!':'💥 Wurf!',
'💥 소용돌이 폭발!':'💥 Wirbelexplosion!',
'👻 순간이동!':'👻 Teleport!','💫 기절! 5초':'💫 Betäubt! 5s',
'찌르기 반격!':'Stoß-Konter!','💢 폭발!':'💢 Explosion!',
'반격 실패':'Konter fehlgeschlagen','탈취 반격!':'Diebstahl-Konter!',
'무기 봉인!':'Waffe versiegelt!','냠!':'Mampf!',
// --- Phase 13: stage/room/map ---
'합체!':'Fusioniert!','출구가 열렸다!':'Ausgang offen!',
'보물상자 출현!':'Schatztruhe erschienen!','출구':'Ausgang',
'⚠ 문지기가 살아있다!':'⚠ Torwächter noch am Leben!',
'⏱ 타임어택 ':'⏱ Zeitangriff ',
'처치율 ':'Tötungsrate ',
'불사 보호':'Untoten-Schutz',
'빙결!':'Gefroren!','환영 소멸!':'Phantom verschwunden!',
'부활력 ':'Wiederbelebungskraft ',
'✟ 신성력 억제! (':'✟ Heilige Unterdrückung! (',
'부활 실패 (':'Wiederbelebung fehlgeschlagen (',
'⚡순간이동!':'⚡Teleport!',
'👻 동반부활!':'👻 Gemeinsame Wiederbelebung!',
'✟ 신성력 억제!':'✟ Heilige Unterdrückung!',
'💀 부활 판정 중...':'💀 Auferstehungsurteil...',
'⚔ 문지기 처치!':'⚔ Torwächter besiegt!',
'🚪 보스방 개방!':'🚪 Bossraum offen!',
'잔해 출현!':'Trümmer erschienen!',
'🌀균열 발생!':'🌀Riss geöffnet!',
'🔥복수!':'🔥Rache!','💥폭독혈!':'💥Seuchenblut!',
'빙판!':'Eisfläche!','❄빙결파!':'❄Frostwelle!',
'❄최종빙결!':'❄Endgültige Vereisung!','빙마 처치!':'Eisdämon besiegt!',
'분리!':'Trennung!','뼈 파편!':'Knochensplitter!',
'태아 처치!':'Fötus besiegt!','지배자 처치!':'Gebieter besiegt!',
'용암!':'Lava!','화룡 처치!':'Feuerdrache besiegt!',
'최후의 비명!':'Letzter Schrei!','산화...':'Oxidation...',
'심판자 처치!':'Richter besiegt!','고통의 왕 처치!':'König des Schmerzes besiegt!',
'수역!':'Gewässer!','파편 폭발!':'Splitterexplosion!',
'거대어 처치!':'Leviathan besiegt!','대사도 처치!':'Hoher Apostel besiegt!',
'독웅덩이!':'Giftpfütze!','화염장판!':'Feuerzone!','전기장!':'Elektrofeld!',
'무기 드롭!':'Waffendrop!','보물 발견!':'Schatz gefunden!',
'상인의 주머니 +':'Händlerbeutel +',
'속박의 파편!':'Splitter der Fesselung!','시간의 조각!':'Zeitfragment!',
'저주 해제!':'Fluch aufgehoben!','차원의 결정!':'Dimensionskristall!',
'전설 아이템!':'Legendärer Gegenstand!','죽음을 이겨냈다!':'Den Tod bezwungen!',
'💥대폭발!':'💥Mega-Explosion!','⚡강화!':'⚡Verstärkt!',
// --- Phase 13: combat/defense ---
'장비 ':'Ausrüstung ',
'💫 진동!':'💫 Beben!','❄ 무적!':'❄ Unverwundbar!',
'\u{1F47B} 유령!':'\u{1F47B} Geist!',
'집중 해제!':'Fokus aufgehoben!',
'🕊️ 평화보호 ':'🕊️ Ägide ',
'🛡 보호막 ':'🛡 Schild ',
'🌀 회전보호막 ':'🌀 Wirbelschild ',
'💥한방캡!':'💥Eintrefferlimit!',
'⚡쉴드 파괴!':'⚡Schild zerstört!',
'💀 불굴!':'💀 Unbeugsam!',
'💀 1회부활!':'💀 Einmal-Wiederbelebung!',
'감시 회수':'Wachposten einziehen',
'악마화 부활!':'Dämonische Auferstehung!',
// --- Phase 13: skill panel ---
'기검참':'Ki-Hieb','날개치기':'Flügelschlag',
'배정 가능한 스킬 없음':'Keine zuweisbaren Fähigkeiten',
'칼날 없음!':'Keine Klinge!',
'⚔ 악의사냥!':'⚔ Bosheitsjagd!',
'❄🌪️ 얼음소용돌이!':'❄🌪️ Eiswirbel!',
'🌪️ 폭풍소환!':'🌪️ Wirbelsturm!',
'\u{1F9B4} 해골무덤!':'\u{1F9B4} Knochengruft!',
'🌹 붉은꽃!':'🌹 Purpurblüte!',
'💥 폭산탄!':'💥 Splitterschuss!',
'🪡 바늘출!':'🪡 Nadelschuss!',
'⚡ 전격이동!':'⚡ Blitzschritt!',
'기둥가시로 흡수됨':'Von Säulendorn absorbiert',
'🌿 가시덫!':'🌿 Dornenfalle!',
'👻 공성유령!':'👻 Belagerungsgeist!',
'🏹 공성쇠뇌 설치!':'🏹 Belagerungsarmbrust aufgestellt!',
'👻 유령 허수아비!':'👻 Phantomlockvogel!',
'💥 폭발 허수아비!':'💥 Sprenglockvogel!',
'축적!':'Gespeichert!','축적 중...':'Speichere...','만충! 재입력→폭발':'Voll! Erneut→Explosion',
'폭발! ':'Explosion! ','불발...':'Fehlzündung...','뎀':' SCHD',
'🩸 폭독칼날!':'🩸 Seuchenklinge!',
'⚡날개치기!':'⚡Flügelschlag!',
'🗡 칼등날개!':'🗡 Schildflügel!',
'🏛️ 악의기둥!':'🏛️ Finsternissäule!',
'🌿 기둥가시!':'🌿 Säulendorn!',
'🌋 지옥강타!':'🌋 Inferno-Hieb!',
'💥 체간 붕괴!':'💥 Haltungszusammenbruch!',
'💫 포이즈 파괴!':'💫 Haltung zerstört!',
'⚡ 뇌전걸음!':'⚡ Geisterschritt!',
'✟ 구속의 영역!':'✟ Fesselnde Domäne!',
'✟ 신성폭발!':'✟ Heilige Explosion!',
'⛧ 블랙!':'⛧ Schwarzer Stern!',
'🌋 용암소환!':'🌋 Lavabeschwörung!',
'필살기 배정!':'Ultimativ zugewiesen!',
'완료':'Abgeschlossen','합체 가능':'Fusion möglich','부족':'Unzureichend',
'SP 부족! (':'SP nötig! (',
'🕊️ 히든: 평화의보호 해금!':'🕊️ Versteckt: Ägide des Friedens freigeschaltet!',
'⚡ 히든: 참회 해금!':'⚡ Versteckt: Buße freigeschaltet!',
'배정됨':'Zugewiesen',
'합체 Lv.':'Fusions-Lv.',
'◆ 같은 보석 스킬 습득 시 합체 가능':'◆ Fusion möglich bei gleichem Edelstein-Skill',
// --- Phase 13: inventory/forge/storage ---
'▼ 가방 → 창고 보관':'▼ Beutel → Lager einlagern',
'▲ 창고 → 가방 꺼내기':'▲ Lager → Beutel herausnehmen',
'✓ 선택됨':'✓ Ausgewählt',
'⟨ 입력 대기... ⟩':'⟨ Warte... ⟩',
'⟨ 대기 ⟩':'⟨ Warte ⟩',
'보조':'Neben',
'키 설정 초기화 (또는 F5 키)':'Tastenbelegung zurücksetzen (oder F5)',
'아무 키 또는 마우스 버튼을 누르세요 (ESC = 취소)':'Beliebige Taste oder Maustaste drücken (ESC = Abbruch)',
'WebGPU 활성':'WebGPU aktiv','WebGL2 활성':'WebGL2 aktiv',
'측정 중...':'Messe...',
'불러오기 실패':'Laden fehlgeschlagen',
'장착':'Angelegt',
'🔒 중요잠금 아이템은 분해 선택 불가!':'🔒 Wichtig-gesperrte Gegenstände können nicht zerlegt werden!',
'장비 강화 (실패 시 재료만 소멸)':'Ausrüstung verstärken (bei Misserfolg nur Material verloren)',
'강화 보너스 적용':'Verstärkungsbonus angewendet',
'강화 실패!':'Verstärkung fehlgeschlagen!',
'장착된 장비가 없습니다.':'Keine angelegte Ausrüstung.',
'충분':'Genug','더 필요':'Mehr nötig',
'장비 선택':'Ausrüstung wählen','목표치 설정':'Ziel festlegen',
'악의 투입':'Bosheit investieren','자동 시도':'Auto-Versuch',
'목표 강화치':'Ziel-Verstärkung',
'예상 필요 악의':'Geschätzte Bosheit benötigt',
'보유':'Vorhanden','강화 시작':'Verstärkung starten',
'위에서 장비를 선택하세요':'Ausrüstung oben wählen',
'⬆ 물약 강화 (최대 10단)':'⬆ Trank verstärken (max. Stufe 10)',
'필요':'Benötigt',
'악의의 분해로 — 장비를 악의로 갈아버려라':'Bosheitsofen — Zermahle Ausrüstung zu Bosheit',
'전체 선택':'Alle wählen','전체 해제':'Alle abwählen',
'희귀 이하':'Selten oder niedriger',
'어픽스 리롤!':'Affix-Neuwurf!',
'물리':'Physisch','영웅':'Heroisch','전설':'Legendär',
'무기 타입':'Waffentyp','활 타입':'Bogentyp',
'보스방':'Bossraum','ST 부족':'Nicht genug ST',
// --- Phase 14: boss phase labels ---
'💀 광폭화!':'💀 Raserei!',
// --- Phase 14: chapter pet dialogue ---
'...따라오는 거 아니야. 같은 방향일 뿐이지.':'...Ich folge dir nicht. Wir gehen nur in dieselbe Richtung.',
'공기가 달라졌어. 더 썩었군.':'Die Luft hat sich verändert. Noch fauliger.',
'여기부터는 악마 영역이야. ...맘대로 해.':'Ab hier ist Dämonengebiet. ...Mach, was du willst.',
'...이 냄새. 살점이 썩는 냄새야.':'...Dieser Gestank. Verrottendes Fleisch.',
'여기 오래 있으면 미쳐. 나도, 너도.':'Bleib zu lange und du wirst wahnsinnig. Ich auch.',
'이 길의 끝에 뭐가 있을까. ...알고 싶지도 않어.':'Was am Ende dieses Weges liegt? ...Ich will es nicht wissen.',
'...여기가 끝이야. 돌아갈 길은 없어.':'...Das ist das Ende. Es gibt kein Zurück.',
// --- Phase 14: idle tips (crow) ---
'작살을 땅에 꽂으면 끌려간다.':'Ramm die Harpune in den Boden und lass dich ziehen.',
'Shift로 작살 던져봐!':'Wirf die Harpune mit Shift!',
'패링 성공하면 ST가 회복된다. 공짜 자원이야.':'Erfolgreiche Parade stellt ST wieder her. Kostenlose Ressourcen.',
'패링 많이 하면 ST 걱정 없어~':'Pariere viel und ST ist nie ein Problem~',
'장비 분해하면 악의를 얻는다. 쓰레기도 자원이야.':'Zerlegte Ausrüstung gibt Bosheit. Selbst Schrott ist Ressource.',
'TAB 열어서 안 쓰는 장비 분해해!':'Öffne TAB und zerlege ungenutzte Ausrüstung!',
'그로기 상태의 적에겐 1.5배 데미지가 들어간다.':'Benommene Feinde nehmen 1,5-fachen Schaden.',
'무릎 꿇으면 전력으로 때려!':'Wenn sie knien, schlag mit allem zu!',
'속성 상성이 있다. 화염은 빙결에 약하고, 암전은 암흑에 약하다.':'Elemente haben Konter. Feuer ist schwach gegen Eis, Blitz gegen Finsternis.',
'무기 속성 바꿔가면서 싸워봐!':'Wechsle die Waffenelemente im Kampf!',
'빙결된 적은 1.5배 데미지를 받는다.':'Gefrorene Feinde nehmen 1,5-fachen Schaden.',
'얼리고 때리는 게 기본이야!':'Einfrieren und zuschlagen — das sind die Grundlagen!',
'보스의 빨간 공격은 패링 가능. 보라빛은 회피만.':'Rote Bossangriffe sind parierbar. Regenbogen nur ausweichen.',
'색깔 잘 봐! 빨강은 받아치고 무지개는 피해!':'Achte auf die Farbe! Rot parieren, Regenbogen ausweichen!',
'VIT를 올리면 최대 HP가 오른다. 죽기 싫으면 찍어.':'VIT erhöht max HP. Investiere, wenn du überleben willst.',
'STR은 근접, DEX는 활, INT는 마법! 골고루 말고 하나만!':'STR für Nahkampf, DEX für Bogen, INT für Magie! Fokussiere eins!',
'E를 꾹 누르면 빔이 나간다. 짧게 누르면 투사체.':'Halte E für Strahl. Kurz drücken für Projektil.',
'마법 쓸 때 MP 잘 봐! 빔은 연속으로 깎여!':'Achte auf MP bei Magie! Strahl verbraucht schnell!',
'핵터와 디로이가 아이템을 주워준다. 수거 범위 안이면.':'Hecter und Deroy sammeln Gegenstände in Reichweite.',
'우리한테 고마워해~ 안 주우면 썩잖아.':'Sei uns dankbar~ Ungesammelt verrottet es.',
'LCK를 올리면 레어 드롭률이 오른다.':'LCK erhöht die Droprate seltener Gegenstände.',
'운빨 게임이긴 하지~ LCK 올려봐!':'Es ist alles Glück~ Versuch LCK zu erhöhen!',
'강화하면 공격력이 쭉쭉 올라가! 악의만 있으면 돼!':'Verstärkung steigert ATK schnell! Braucht nur Bosheit!',
'강화 확률은 +1에서 99%. 높을수록 떨어진다.':'Verstärkungschance startet bei 99% für +1. Sinkt danach.',
'실패하면 악의만 날아가~ 장비는 안 부서져!':'Bei Misserfolg geht nur Bosheit verloren~ Ausrüstung bleibt!',
'대장간에서 장비 제작도 된다. 악의 30000개면 영웅급 이상.':'Die Schmiede kann auch herstellen. 30000 Bosheit für Heroisch+.',
'랜덤이지만 좋은 거 나올 수도 있어!':'Zufällig, aber vielleicht kommt was Gutes!',
'쉴드는 마법으로, HP는 물리로 깎아야 제대로 먹힌다.':'Schilde brauchen Magie, HP braucht Physisch.',
'반대로 치면 50%만 들어가! 무기 바꿔가면서 싸워!':'Falscher Typ macht nur 50%! Wechsle die Waffen!',
'장비에 접두사, 접미사가 붙으면 특수 효과가 생긴다.':'Ausrüstung mit Präfix/Suffix hat Spezialeffekte.',
'영웅급 이상 장비에만 붙어! 좋은 거 나오면 강화해!':'Nur bei Heroisch+! Gute Würfe verstärken!',
'강화는 장비를 바꿔도 자동 이전된다. 악의만 있으면.':'Verstärkung überträgt sich automatisch. Kostet nur Bosheit.',
'더 좋은 장비 나오면 바로 장착해! 강화 수치 그대로 옮겨가!':'Bessere Ausrüstung sofort anlegen! Verstärkung überträgt sich!',
// --- Phase 14: additional tutorial lines ---
'패링을 써야 자원을 흡수한다고!':'Du musst parieren, um Ressourcen zu absorbieren!',
'F키 회복의 영역을 써봐. 자원이 차올라.':'Versuch F-Taste Heilige Domäne. Ressourcen füllen sich.',
'적이 근접하면 스페이스키야! 가시덫을 활용해!':'Wenn Feinde nah kommen, Leertaste! Nutze die Dornenfalle!',
'기절시켜! 그로기가 터지면 데미지가 1.5배야!':'Betäube sie! Benommen bedeutet 1,5-fach Schaden!',
'1번 대왕치기로 밀어버려!':'Taste 1 Titanenschlag zum Wegstoßen!',
'무릎 꿇었다.':'Es kniet nieder.',
'지금이야! 몰아쳐!!':'Jetzt! Voller Angriff!!',
'스킬 포인트 있어! K 눌러서 스킬 찍어봐!':'Fähigkeitspunkte vorhanden! Drück K zum Erlernen!',
'...힘이 없으면 여기서 끝이야.':'...Ohne Stärke endet es hier.',
'...쓸 거 아니면 분해해.':'...Was du nicht brauchst, zerlege es.',
'아이템 넘쳐나네~ 우리가 주워줄게!':'So viele Gegenstände~ Wir sammeln für dich!',
'악의가 바닥이다.':'Bosheit aufgebraucht.',
'TAB 열어서 장비 분해해! 쓰레기도 악의가 돼!':'Öffne TAB und zerlege! Selbst Schrott wird zu Bosheit!',
'좋은 장비가 있네! G 눌러서 대장간 가봐!':'Gute Ausrüstung! Drück G für die Schmiede!',
'...강화 안 하면 그냥 고철이야.':'...Ohne Verstärkung ist es nur Altmetall.',
'...멈추지 마. 여신은 기다리지 않는다.':'...Bleib nicht stehen. Die Göttin wartet nicht.',
'앞으로 가자~ 나도 여기 오래 있기 싫어.':'Gehen wir weiter~ Ich will auch nicht lange hierbleiben.',
'...냄새가 짙다. 큰 놈이 있어.':'...Der Gestank ist dicht. Etwas Großes ist hier.',
'준비됐어? 물약 확인하고!':'Bereit? Tränke prüfen!',
// --- Phase 15: missing pet dialogue translations ---
// ── Tutorial: firstItem, potionCraft ──
'TAB을 눌러. 가방을 열고 장비를 입어야 한다.':'Drück TAB. Öffne den Beutel und leg Ausrüstung an.',
'주웠으면 껴야지! TAB!':'Aufgehoben? Dann anziehen! TAB!',
'G. 대장간에서 물약도 제작할 수 있다.':'G. In der Schmiede kannst du auch Tränke herstellen.',
'악의로 물약 만들어! G키야!':'Stelle Tränke aus Bosheit her! G-Taste!',
// ── Stun warning ──
'기절이야! Ctrl 눌러!':'Betäubt! Drück Ctrl!',
'Ctrl 유령걸음으로 탈출!':'Ctrl Geisterschritt zur Flucht!',
'Ctrl 얼음보주로 탈출!':'Ctrl Eiskugel zur Flucht!',
// ── Parry guide ──
'빨간 탄은 우클릭 패링. 무지개는 Q 패링.':'Rote Geschosse: RMT Parade. Regenbogen: Q Parade.',
'나머지는 전부 우클릭 패링 가능해!':'Alles andere kann mit RMT pariert werden!',
'빨강=우클릭, 무지개=Q 패링. 나머진 다 쳐내.':'Rot=RMT, Regenbogen=Q Parade. Den Rest parieren.',
'무지개는 Q로 패링! 나머지는 전부 우클릭!':'Regenbogen mit Q! Alles andere mit RMT!',
// ── Resource / combat ──
'빠져! 물약 마시고 안전한 곳에서 회복해.':'Rückzug! Trank trinken und sicher erholen.',
'자원 없으면 도망가는 게 답이야!':'Keine Ressourcen? Fliehen ist die Antwort!',
'스페이스! 가시덫으로 적 묶어버려!':'Leertaste! Feinde mit Dornenfalle fesseln!',
'근접이 너무 많아! 거리 벌려!':'Zu viele Nahkämpfer! Abstand schaffen!',
'...둘러싸이면 끝이야. 빠져나와.':'...Umzingelt und es ist vorbei. Brich aus.',
'1번 대왕치기로 쓸어버려!':'Taste 1 Titanenschlag zum Wegfegen!',
'그로기 터지면 데미지 1.5배!':'Benommen bringt 1,5-fach Schaden!',
'회전참이나 광역기로 몰아! 한 놈씩 상대하면 죽어.':'Wirbelwind oder Fläche! Einzeln kämpfen heißt sterben.',
'뭉쳐있을 때가 기회야!':'Wenn sie sich sammeln, ist die Chance da!',
'E로 마력공격을 해봐! 악의 쉴드를 해제할려면 마법 공격을 해야 해!':'Versuch E für Magieangriff! Bosheitsschilde brauchen Magie!',
'쉴드는 마법으로, HP는 물리로. 반대로 치면 데미지 안 들어간다.':'Schilde brauchen Magie, HP braucht Physisch. Falscher Typ macht keinen Schaden.',
// ── Skill / passive / stamina hints ──
'L키로 스킬 슬롯에 넣어야 쓸 수 있어.':'Drück L, um Fähigkeiten den Slots zuzuweisen.',
'C키를 눌러. 패시브 포인트가 쌓여있다.':'Drück C. Passive Punkte haben sich angesammelt.',
'C키! 패시브 올리면 진짜 강해져!':'C-Taste! Passive machen dich wirklich stärker!',
'스태미나가 부족하다. 무리하지 마.':'Ausdauer ist niedrig. Übertreib es nicht.',
'ST 없으면 스킬 못 써! 잠깐 빠져!':'Ohne ST keine Fähigkeiten! Kurz zurückziehen!',
// ── Item pickup (line 9324) ──
'탭 장비창을 열어봐. 아이템을 주워왔어!':'Öffne TAB-Ausrüstungsmenü. Wir haben etwas aufgesammelt!',
'좋은 거 나왔다! TAB 열어서 확인해봐!':'Etwas Gutes gefallen! Öffne TAB zum Prüfen!',
// ── Revive tutorial (line 22486) ──
'악의에 중독되면 악마가 돼서 부활력이 생긴대. 저 녀석처럼.':'Man sagt, Bosheitsucht macht dich zum Dämon mit Wiederbelebungskraft. Wie jener dort.',
'혹시 너도...?':'Vielleicht du auch...?',
// ── Revive tip (line 30541) ──
'데미지가 부족하면 무기류 강화를 해야해!!':'Wenn der Schaden nicht reicht, verstärke deine Waffen!!',
'G키 대장간. 강화 안 하면 여기서 계속 죽어.':'G-Taste Schmiede. Ohne Verstärkung stirbst du hier immer wieder.',
// ── Idle nag lines ──
'시간이 없어. 움직여.':'Keine Zeit. Beweg dich.',
'멍하게 서있으면 안 돼!':'Steh nicht einfach rum!',
'...뭘 기다리는 거야?':'...Worauf wartest du?',
'가자가자! 몬스터가 기다려!':'Los los! Die Monster warten!',
'여기 오래 있으면 위험해.':'Zu lange hierbleiben ist gefährlich.',
'움직여야 해! 가만있으면 둘러싸여!':'Beweg dich! Stillstehen und sie umzingeln dich!',
'쉬는 건 죽고 나서 해.':'Ruh dich aus, wenn du tot bist.',
'살아있을 때 쉬면 안 돼!':'Keine Ruhe, solange du lebst!',
'적이 몰려오고 있어. 빨리 움직여.':'Feinde rücken an. Beeil dich.',
'냄새 맡고 올 거야. 빨리!':'Sie werden dich riechen. Schnell!',
'...아직 살아있는 거 맞지?':'...Du bist noch am Leben, oder?',
'혹시 잠든 거야...?':'Bist du eingeschlafen...?',
// ── Chapter entry dialogues ──
'...나무가 썩어가고 있어. 여기는 지옥의 입구야.':'...Die Bäume verfaulen. Das ist der Eingang zur Hölle.',
'냄새 지독해... 빨리 지나가자.':'Der Gestank ist furchtbar... Gehen wir schnell weiter.',
'조심해. 벌레굴이다. 벽이랑 바닥에서 기어나와.':'Vorsicht. Wurmnest. Sie kriechen aus Wänden und Böden.',
'으으... 벌레 싫어! 밟아버려!':'Ugh... Ich hasse Ungeziefer! Zertritt sie!',
'...공기가 얼어붙는다. 여기선 화염이 먹힌다.':'...Die Luft gefriert. Hier wirkt Feuer.',
'추워... 빙결 조심해! 얼면 끝이야.':'Kalt... Vorsicht vor Frost! Gefroren und es ist vorbei.',
'용암이다. 바닥을 밟으면 타 죽어.':'Lava. Tritt auf den Boden und du verbrennst.',
'뜨거워! 여기 왜 이렇게 빨개!':'So heiß! Warum ist hier alles so rot!',
'...군단이다. 수가 많아. 광역기 없으면 밀려.':'...Die Legion. Zu viele. Ohne Flächenangriff wirst du überrannt.',
'우글우글... 징그러워. 한꺼번에 쓸어!':'Überall Gewimmel... Ekelhaft. Feg sie alle auf einmal weg!',
'사도의 영역이야. 여기 놈들은 머리가 좋아.':'Gebiet des Apostels. Diese hier sind klug.',
'패턴이 복잡해졌어... 집중해!':'Die Muster sind komplexer geworden... Konzentrier dich!',
'...끝이다. 지옥의 심장부. 살아 돌아가는 건 포기해라.':'...Das ist es. Das Herz der Hölle. Gib die Hoffnung auf Rückkehr auf.',
'여기가 마지막이야... 각오해.':'Das hier ist das Ende... Mach dich bereit.',
'석궁 자동발사 (T)':'Armbrust automatisch (T)',
'버스트루프 당기기 (H)':'Burst-Schleife anziehen (H)',
'결정 자동합성':'Kristall Auto-Synthese',
'결정 자동강화':'Kristall Auto-Verstärkung',
'✓ 설정 자동 저장':'✓ Einstellungen auto gespeichert',
'세팅 프리셋 저장/불러오기':'Voreinstellung speichern/laden',
'세팅1 저장':'Voreinstellung 1 speichern','세팅1':'Voreinstellung 1',
'세팅2 저장':'Voreinstellung 2 speichern','세팅2':'Voreinstellung 2',
'재진단':'Neu diagnostizieren',
'게임 리셋 (처음부터)':'Spiel zurücksetzen (von Anfang)',
'캐릭터 선택 (로비)':'Charakterauswahl (Lobby)',
'닫기 [ESC]':'Schließen [ESC]','닫기 [G]':'Schließen [G]','닫기 [V]':'Schließen [V]','닫기 [C]':'Schließen [C]',
'전체화면 (F11)':'Vollbild (F11)',
'정말 모든 진행을 초기화하시겠습니까?':'Wirklich alle Fortschritte zurücksetzen?',
'검출 중...':'Erkennung...',
'마우스 커서':'Mauszeiger','그래픽 품질':'Grafikqualität','하드웨어 진단':'Hardware-Diagnose',
'BGM 선택':'BGM-Auswahl',
'자동 (스테이지별)':'Automatisch (pro Stage)','전체 랜덤':'Alles zufällig','로비':'Lobby',
'1장 랜덤':'Kapitel 1 zufällig','2장 랜덤':'Kapitel 2 zufällig','3장 랜덤':'Kapitel 3 zufällig',
'4장 랜덤':'Kapitel 4 zufällig','5장 랜덤':'Kapitel 5 zufällig','6장 랜덤':'Kapitel 6 zufällig','7장 랜덤':'Kapitel 7 zufällig',
'보스':'Boss','최종보스':'Endgegner',
'대장간 랜덤':'Schmiede zufällig','사망 랜덤':'Tod zufällig','승리 랜덤':'Sieg zufällig',
'지옥 추락 사망 징글':'Höllensturz-Todessignal','탈출 성공':'Flucht erfolgreich',
'── 1장 - 썩은 숲 ──':'── CH1 - Rotten Forest ──','── 2장 - 벌레굴 ──':'── CH2 - Worm Nest ──',
'── 3장 - 얼음굴 ──':'── CH3 - Ice Cavern ──','── 4장 - 화염지대 ──':'── CH4 - Infernal Wastes ──',
'── 5장 - 지옥군단 ──':'── CH5 - Hell Legion ──','── 6장 - 사도마굴 ──':'── CH6 - Apostle Den ──',
'── 7장 - 지옥성 ──':'── CH7 - Hell Citadel ──','── 공통 ──':'── Common ──',
'⌨ 조작법':'⌨ Steuerung','클릭하면 닫힘':'Klicken zum Schließen',
'전투력':'KP','가방':'Rucksack','결정':'Kristall',
'↕ 정렬':'↕ Sortieren','쓰레기 전체선택':'Schrott alles auswählen','쓰레기 전부 분해':'Schrott alles zerlegen',
'창고':'Lager','스탯 포인트':'Attributpunkte','능력치 요약':'Statusübersicht','올 리셋':'Alles zurücksetzen',
'대장간':'Schmiede','스킬':'Fähigkeiten','능력치':'Attribute',
'좌클스킬 (클릭 전환)':'LMB-Fähigkeit (Klick zum Wechseln)','우클스킬 (클릭 전환)':'RMB-Fähigkeit (Klick zum Wechseln)',
'이동스킬 (클릭 전환)':'Bewegungsfähigkeit (Klick zum Wechseln)','마법스킬 (클릭 전환)':'Magiefähigkeit (Klick zum Wechseln)',
'영역스킬 (클릭 전환)':'Flächenfähigkeit (Klick zum Wechseln)','피보호막 (클릭 전환)':'Blutschild (Klick zum Wechseln)',
'CT스킬 (클릭 전환)':'CT-Fähigkeit (Klick zum Wechseln)','[C] 능력치':'[C] Attribute',
'무기 공격':'Waffenangriff','칼등 처내기 (투사체 반사, 홀드 연사)':'Parade (reflektiert Projektile, Halten=Salve)',
'연속 처내기':'Fortlaufende Parade','영역 스킬 (폭풍소환 등)':'Flächenfähigkeit (Wirbelsturm usw)',
'작살 발사':'Harpune abschießen','마법 (탭=투사체, 홀드=빔)':'Magie (Tippen=Projektil, Halten=Strahl)',
'데빌포스 흡수':'Teufelskraft absorbieren','물약 / 스킬슬롯':'Tränke / Fähigkeitsslots',
'스킬슬롯 5 / 필살기 / CT스킬':'Slot 5 / Ultimativ / CT-Fähigkeit','스킬 슬롯 배정':'Slot-Zuweisung',
'✟ 결계의 영역!':'✟ Banndomäne!',
'✟ 물의 영역!':'✟ Wasserdomäne!',
'✟ 파쇄의 영역!':'✟ Splitterdomäne!',
'✟ 침식의 영역!':'✟ Ätzdomäne!',
'✟ 관통의 영역!':'✟ Durchdringdomäne!',
'✟ 권능의 영역!':'✟ Allmachtdomäne!',
'⏳ 시간왜곡!':'⏳ Zeitverzerrung!',
'쿨다운!':'Abklingzeit!',
'집중!':'Konzentration!',
'\u{1F47B} 유령총!':'\u{1F47B} Geisterpistole!',
'💥 유령총 폭발!':'💥 Geisterpistolen-Explosion!',
'⚡ 전격의창!':'⚡ Donnerlanze!',
'임계...!':'Critical...!',
// --- Phase 27 additions ---
// KEY BINDINGS
'위로 이동':'Hoch','아래로 이동':'Runter','왼쪽 이동':'Links','오른쪽 이동':'Rechts',
'칼등 처내기 (탭=처내기, 홀드=연사)':'Parade (Tippen=Parade, Halten=Salve)',
'영역 스킬':'Flächenfähigkeit','작살 이동':'Harpunenrückstoß',
'유령불꽃 켜기/끄기':'Geisterflamme an/aus',
'기동칼날개 자동 켜기/끄기':'Auto-Klingenflügel an/aus',
'해상도':'Auflösung',
// DEATH / LEVEL-UP / INTRO SCREEN
'빛이 꺼졌다':'Das Licht erlischt',
'누군가는 너를 기다리고 있다':'Jemand wartet auf dich',
'다시 일어서라':'Steh wieder auf',
'로비로 돌아가기':'Zurück zur Lobby',
'☠ 사망 리플레이':'☠ Todeswiederholung',
'지옥의 시련을 견뎌냈다':'Du hast die Prüfung der Hölle bestanden',
'계속 전투':'Kampf fortsetzen',
'난이도를 선택하라':'Wähle die Schwierigkeit',
'나중에 설정(ESC)에서 변경 가능':'Kann später in Einstellungen (ESC) geändert werden',
// UI
'일괄합성':'Massen-Synthese','일괄강화+합성':'Massen-Verstärkung+Synthese',
'자원 부족!':'Ressourcen knapp!',' 뎀':' SCHD',
// GAME COMBAT MESSAGES
'합체 폭발!':'Fusionsexplosion!',
'MP 부족! (50)':'Nicht genug MP! (50)',
'부활력 고갈!':'Auferstehungskraft erschöpft!',
'☠ 부활력 고갈!':'☠ Auferstehungskraft erschöpft!',
'독안개':'Giftnebel','뇌전창':'Donnerlanze',
'🔥 업화선 시전...':'🔥 Höllenfeuerstrahl wirken...',
'💥 기동파괴 그로기!':'💥 Kettenbrecher — Benommen!',
'💥 칼등 그로기!':'💥 Parade — Benommen!',
'⚡ 순간이동 준비!':'⚡ Teleport bereit!',
'👿악의+1000':'👿Bosheit+1000',
'💀 내려찍기!':'💀 Niederschmettern!',
'✟ 신성력 억제! +':'✟ Heilige Unterdrückung! +',
'✟ 신성력 억제!':'✟ Heilige Unterdrückung!',
'✟ 신성력 억제! (':'✟ Heilige Unterdrückung! (',
'💥 지진그로기!':'💥 Erdbeben-Betäubung!',
'💥 기폭그로기!':'💥 Detonations-Betäubung!',
'폭발! ×':'Explosion! ×',
'⚫ 기둥강타!':'⚫ Säulenschlag!',
'💥 대왕치기 그로기!':'💥 Titanenschlag — Benommen!',
'💫 미니스턴!':'💫 Mini-Betäubung!',
'⚡ 뇌전창!':'⚡ Donnerlanze!',
// PET DIALOGUE (crow/cat)
'…절반이다. 정신차려.':'…Hälfte. Reiß dich zusammen.',
'…죽기 직전이다. 한 발만 더.':'…Kurz vorm Tod. Noch ein Treffer.',
'…다음 한 방이 마지막이야.':'…Der nächste Treffer ist der letzte.',
'기절!  ':'Betäubt!  ',
'마력이 빈다. 평타 섞어.':'MP schwindet. Normale Angriffe mischen.',
'그랩이다. 거리를 둬.':'Greifer. Abstand halten.',
'광역기다. 멀어져.':'Fläche. Zurückweichen.',
'…아파? 당연하지. 여긴 지옥이야.':'…Schmerzt? Natürlich. Das hier ist die Hölle.',
'F키도 스킬 슬롯이야!':'F-Taste ist auch ein Slot!',
'L-CTRL로 유령걸음/얼음보주!':'L-CTRL für Geisterschritt / Eiskugel!',
'V 눌러서 창고에 넣어둬!':'Drück V fürs Lager!',
'ESC로 설정! 난이도/자동물약!':'ESC — Einstellungen! Schwierigkeit/Auto-Trank!',
'잡몹이다. 먼저 정리해.':'Normale Gegner. Erst aufräumen.',
'…얼어붙은 놈은 오래 안 간다.':'…Gefrorene halten nicht lange.',
'…냄새가 짙다. 큰 놈이 있어.':'…Der Geruch ist dicht. Etwas Großes.',
'쉴드는 마법으로, HP는 물리로.':'Schilde mit Magie, HP mit Physisch.',
'스페이스! 가시덫으로 적 묶어!':'Leertaste! Feinde mit Dornenfalle fesseln!',
'근접 너무 많아! 거리 벌려!':'Zu viele Nahkämpfer! Abstand!',
'회전참이나 광역기로 몰아!':'Wirbelwind oder Fläche einsetzen!',
'F 눌러! 회복의 영역 깔아!':'Drück F! Heilige Domäne aufstellen!',
'F키 회복의 영역을 써봐.':'Versuch F-Taste Heilige Domäne.',
'빠져! 물약 마시고 회복해.':'Rückzug! Trank trinken und erholen.',
'쉬프트! 사슬기동은 이동기야!':'Shift! Kettensturm ist Bewegung!',
'스킬포인트 쌓였어! K 눌러!':'Fähigkeitspunkte bereit! Drück K!',
'스킬 포인트 있어! K!':'Fähigkeitspunkte vorhanden! K!',
'C키. 패시브 포인트가 쌓여있다.':'C-Taste. Passive Punkte haben sich angesammelt.',
'…쓸 거 아니면 분해해.':'…Was du nicht brauchst, zerleg es.',
'…강화 안 하면 그냥 고철이야.':'…Ohne Verstärkung nur Altmetall.',
'빨간 탄은 우클릭. 무지개는 Q.':'Rot — Rechtsklick. Regenbogen — Q.',
'빨강=우클릭, 무지개=Q.':'Rot=Rechtsklick, Regenbogen=Q.',
'…멈추지 마. 여신은 기다리지 않는다.':'…Bleib nicht stehen. Die Göttin wartet nicht.',
'패턴이 바뀐다. 거리를 둬.':'Muster ändert sich. Abstand halten.',
'미쳐가고 있어. 광폭화다.':'Es rastet aus. Berserker.',
'마지막이야! 끝장내!':'Letzte Phase! Beende es!',
'…끝났다. 다음으로.':'…Vorbei. Weiter.',
'다 잡았다! 포탈 어딨어?':'Alle erledigt! Wo ist das Portal?',
'근육으로 만든 빌드군. 베고 부숴.':'Kraft-Build. Hauen und brechen.',
'활을 쥐었군. 거리를 둬.':'Bogen in Hand. Abstand halten.',
'마법사군. MP 관리부터 배워라.':'Magier. Erst MP-Verwaltung lernen.',
'운에 기댄 빌드군. …드롭은 좋겠어.':'Glücks-Build. …Wenigstens sind Drops gut.',
'…VIT가 너무 낮아. 한 방에 죽는다.':'…VIT zu niedrig. Stirbst mit einem Treffer.',
'다 찍으면 다 약해진다. 하나만 골라.':'Alles maxen und überall schwach. Nur eins wählen.',
'…3단. 적이 강해져. 정신 차려.':'…Etappe 3. Feinde stärker. Konzentrier dich.',
'5단이다. …너도 강해졌단 뜻이야.':'Etappe 5. …Heißt, du bist auch stärker geworden.',
'…7단. 아직 살아있단 게 신기하군.':'…Etappe 7. Noch am Leben. Erstaunlich.',
'10단. …너는 이제 인간이 아니야.':'Etappe 10. …Du bist kein Mensch mehr.',
'…일반으로 내려왔군. 가끔은 쉬어가야지.':'…Zurück auf Normal. Manchmal braucht man eine Pause.',
'…이게 진짜 패링이야.':'…Das ist echte Parade.',
'…피가 묻기 시작했군.':'…Blut beginnt zu fließen.',
'100. 너는 인간이 아니야.':'100. Du bist kein Mensch.',
'…피 흘리며 베는군.':'…Schneidest durch Blut.',
'빨간콩이 푸르게 변했다. 그게 너의 무기야.':'Der rote Kern wurde blau. Das ist deine Waffe.',
'무지개를 받아쳤군. 그건 진짜 어렵다.':'Regenbogen pariert. Das ist wirklich schwer.',
'…너무 빨라. 닿기 직전에 눌러.':'…Zu schnell. Drück kurz vor dem Kontakt.',
'악의가 가득 찼다. 풀어내.':'Bosheit ist voll. Entlade sie.',
'작살이 살을 뚫었어. 끌고 와.':'Die Harpune hat Fleisch durchbohrt. Zieh heran.',
'…풀차지군. 멀리 던져버려.':'…Voll geladen. Wirf es weit.',
'…빈틈을 그대로 빠져나갔다.':'…Schlüpfte direkt durch die Lücke.',
'…일반 잡몹이 아니야. 모디파이어 붙었군.':'…Kein normaler Gegner. Hat einen Modifikator.',
'엘리트 하나 처리.':'Ein Elite erledigt.',
'…큰 놈이다. 일반 잡몹 정리부터.':'…Großer. Erst normale Gegner aufräumen.',
'미니보스 처리. 다음 길로.':'Mini-Boss erledigt. Weiter.',
'한 번에 다섯. 깔끔해.':'Fünf auf einmal. Sauber.',
'100강. 이제 뭔가 다르게 보이는군.':'+100. Jetzt sieht alles anders aus.',
'…운이 없는 날이야.':'…Heute kein Glück.',
'…전설이다. 이런 건 처음 본다.':'…Legendär. Sowas noch nie gesehen.',
'…죽었다 살아났네. 여신은 너를 포기 안 했어.':'…Gestorben und zurück. Die Göttin hat nicht aufgegeben.',
'…또야? 패턴 좀 외워!':'…Schon wieder? Lern das Muster!',
'…한 번도 안 죽고. 그건 진짜 실력이야.':'…Kein einziger Tod. Das ist echtes Können.',
'…ACT1을 끝냈다. 진짜 시작은 여기서부터야.':'…AKT1 beendet. Der echte Start beginnt hier.',
'모든 보스를 무너뜨렸다. 너는 지옥의 일부야.':'Alle Bosse gefallen. Du bist nun Teil der Hölle.',
'…30초. 너 진짜 미쳤구나.':'…30 Sekunden. Du bist wirklich wahnsinnig.',
'…빠르군. 효율적이야.':'…Schnell. Effizient.',
'신기록이다.':'Neuer Rekord.',
'탭 장비창을 열어봐.':'Öffne TAB — Ausrüstung.',
'데미지 부족하면 무기 강화!':'Nicht genug Schaden? Waffe verbessern!',
// --- Loading screen ---
'불러오는 중...':'Lädt...',
'로딩중...':'Lädt...',
'맵과 몬스터 불러오는 중...':'Karte und Monster werden geladen...',
'기본 데이터 준비 중...':'Grunddaten werden vorbereitet...',
'저장 데이터 불러오는 중...':'Speicherdaten werden geladen...',
'몬스터 스킨 로딩...':'Monster-Skins werden geladen...',
'맵과 몬스터 생성 중...':'Karte und Monster werden generiert...',
'맵 에셋 로딩...':'Karten-Ressourcen werden geladen...',
'맵 환경 준비 중...':'Kartenumgebung wird vorbereitet...',
'주변 청크 준비 중...':'Benachbarte Chunks werden vorbereitet...',
'맵 캐시 생성 중...':'Karten-Cache wird erstellt...',
'미니맵 빌드 중...':'Minimap wird erstellt...',
// Phase 28
' 으로 탈출!':' zum Entkommen!',
'100명?! 미쳤어!':'100 Abschüsse?! Wahnsinn!',
'10단 최고난이도! 너 진짜 광기야!':'Schwierigkeit 10 maximal! Du bist völlig verrückt!',
'1분 안에 클리어! 빠르네!':'Stufe in 1 Min. abgeschlossen! So schnell!',
'30초!! 스피드런 가능해!':'30 Sekunden!! Speedrun-Potenzial!',
'3단! 보상도 좋아지지만 죽기 쉬워!':'Schw. 3! Bessere Belohnungen, aber leichter zu sterben!',
'50명! 학살자야!':'50 Abschüsse! Du bist ein Schlächter!',
'5단!! 진짜 게이머 인증!':'Schw. 5!! Echter Gamer bestätigt!',
'7단!! 다른 사람들 이 정도 못 와!':'Schw. 7!! Andere kommen nicht so weit!',
'ACT1 완주! 우리가 진짜 해냈어!':'ACT1 abgeschlossen! Wir haben es wirklich geschafft!',
'Ctrl 얼음보주로 탈출하라.':'Strg — entkommen mit der Eiskugel.',
'Ctrl 유령걸음으로 탈출하라.':'Strg — entkommen mit dem Geisterschritt.',
'C키! 패시브 강해져!':'C-Taste! Passive werden stärker!',
'DEX 빌드! 거리에서 패고, 추적탄 좋아!':'GES-Build! Aus der Distanz angreifen, Verfolgungsschüsse sind großartig!',
'E로 마력공격을 해봐!':'Versuche den Magieangriff mit E!',
'G 눌러서 대장간 가봐!':'Drücke G, um die Schmiede zu besuchen!',
'G키 대장간. 강화 안 하면 계속 죽어.':'G — Schmiede. Ohne Verbesserungen stirbst du weiter.',
'HP 70%! 조심해!':'HP 70 %! Vorsicht!',
'INT 빌드! 빔이랑 폭발 마법! MP 잘 봐!':'INT-Build! Strahlen und Explosionsmagie! Achte auf dein MP!',
'LCK 높아! 레어 드롭률 미친 거 알지?':'Hoher GLCK-Wert! Du weißt, dass die Drop-Raten verrückt sind, oder?',
'L로 어디에 뭘 넣을지 골라!':'Drücke L, um auszuwählen, was in jeden Slot kommt!',
'MP 부족! 평타로 패면서 회복해!':'MP niedrig! Mit Basisangriffen treffen, um zu regenerieren!',
'ST 없으면 스킬 못 써!':'Kein ST, keine Fähigkeiten!',
'STR 빌드! 회전참, 회오리, 광역기 추천!':'STR-Build! Drehschlag, Wirbelwind, AoE empfohlen!',
'VIT 좀 찍어! HP 너무 적어!':'Etwas VIT hinzufügen! HP ist viel zu niedrig!',
'Z 누르면 대박! 쿨타임 길어!':'Z drücken für das Große! Langer Cooldown allerdings!',
'…고기 냄새. 싫진 않네.':'…Blutgeruch. Nicht unangenehm.',
'…둘러싸이면 끝이야.':'…Eingekreist werden und es ist vorbei.',
'…말은 못해.':'…Kann nicht sprechen.',
'…버리기 아까운 건 창고에.':'…Was aufzubewahren sich lohnt, kommt ins Lager.',
'…빈틈을 노려.':'…Achte auf Lücken.',
'…설정을 확인해.':'…Überprüfe deine Einstellungen.',
'…슬롯을 채워. 빈 손은 죽음이다.':'…Fülle deine Slots. Leere Hände bedeuten den Tod.',
'…아직 살아있네. 좌클릭으로 저것들 쳐봐.':'…Noch am Leben. Versuche sie mit Linksklick zu treffen.',
'…운이 좋았을 뿐이야. 아마.':'…Nur Glück. Wahrscheinlich.',
'…치는 건 할 줄 아네. 피하는 건?':'…Weißt wie man trifft. Und ausweichen?',
'…힘을 골라라. 전부 가질 순 없다.':'…Wähle deine Stärke. Man kann nicht alles haben.',
'골고루 안 돼! 하나로 밀어!':'Keine Stats verteilen! Auf einen setzen!',
'그로기 터지면 1.5배!':'Taumelnd = 1,5-facher Schaden!',
'길이 열렸다.':'Der Pfad ist offen.',
'나머진 전부 우클릭 패링 가능!':'Alles andere kann mit Rechtsklick pariert werden!',
'나머진 전부 우클릭!':'Alles andere — Rechtsklick!',
'다섯 번 연속! 내가 본 인간 중 최고!':'Fünfmal hintereinander! Bester Mensch den ich je gesehen habe!',
'다음엔 죽지 마!':'Stirb beim nächsten Mal nicht!',
'더블탭 전격이동으로 탈출하라.':'Doppeltippen zum Ausweichen und Entkommen.',
'소환수 왔어! 먼저 처리해야 해!':'Beschwörungen kommen! Erst eliminieren!',
'스킬 없으면 방향키 연타뿐이야.':'Keine Fähigkeit? Einfach die Richtungstasten spammen.',
'신기록!! 스트리머한테 보내!':'Neuer Rekord!! Schick es einem Streamer!',
'아이템 넘쳐! 우리가 주워줄게!':'Tasche voll! Wir sammeln die Sachen für dich auf!',
'안 죽고 깼어! 진짜 천재 맞네!':'Ohne zu sterben abgeschlossen! Echtes Genie!',
'앞으로 가자~':'Vorwärts~',
'우리가 해냈어! 다음 챕터 가자!':'Wir haben es geschafft! Zum nächsten Kapitel!',
'일반 모드! 편하게 즐기자!':'Normalmodus! Genießen wir es entspannt!',
'자원이 반이다. F키로 회복해.':'Ressourcen bei der Hälfte. F drücken um zu erholen.',
'잡힌다! 옆으로 빠져!':'Werde gegriffen! Zur Seite bewegen!',
'장비 분해해! 쓰레기도 악의!':'Ausrüstung zerlegen! Sogar Schrott gibt Bosheit!',
'전부 다 잡았어! 우리가 지옥의 왕이야!':'Alle erwischt! Wir sind die Könige der Hölle!',
'좋은 거 나왔다! TAB!':'Gute Beute gefallen! TAB!',
'죽기 직전에 죽이다니! 멋져!':'Kurz vor dem Tod töten! Großartig!',
'체력 반 남았어! 물약 마실 타이밍!':'Halbe HP übrig! Zeit, einen Trank zu trinken!',
'큰 거 온다! 도망쳐!':'Großer Angriff kommt! Lauf!',
'패링으로 돌려주고, Q 보호막도 써!':'Parieren zum Reflektieren, und auch Q-Schild nutzen!',
'패턴이 빨라졌어!':'Muster wurden schneller!',
'한 대만 맞아도 죽어! 패링이든 회피든!!':'Ein Treffer und du stirbst! Parieren oder ausweichen!!',
'한 방이면 죽어! 도망쳐!!':'Ein Schuss tötet! Lauf!!',
'화염엔 빙결! 암전엔 암흑!':'Feuer → Frost! Leere → Schatten!',
'👻 유령총!':'👻 Geistergewehr!',
'기절! ':'Betäubt! ',
'── 2장 - 벌레굴 ──':'── CH2 - Worm Nest ──',
'── 4장 - 화염지대 ──':'── CH4 - Infernal Wastes ──',
'── 6장 - 사도마굴 ──':'── CH6 - Apostle Den ──',
'── 공통 ──':'── Common ──',
'맞아서 사망':'Tod durch Treffer',
'강화':'Verstärken',
'합체 스킬로 통합됨':'In Fusionsskill integriert',
'처치':'Kills',
'유령불꽃 OFF':'Geisterflamme AUS',
'슬롯':'Slot',
'필살기':'Ultimativer Skill',
'연사 해제':'Schnellfeuer AUS',
'⏳⚡ 시간걸음!':'⏳⚡ Zeitschritt!',
};

const _DE_PFX={'녹슨':'Rostig','강철':'Stahl','흑요석':'Obsidian','미스릴':'Mithril','심판의':'Richter-','천벌의':'Göttlicher Zorn','파멸의':'Vernichtung',
'불꽃':'Flammen','화염':'Inferno','염화':'Höllenfeuer','지옥불':'Höllenbrand','지옥화':'Höllenbrand','지옥':'Höllenbrand','멸화의':'Vernichtend',
'냉기':'Frost','빙결':'Eisgebunden','빙하':'Glazial','서리의':'Reif','서리':'Reif','영겁빙':'Ewiges Eis',
'그림자':'Schatten','암흑':'Finster','심연':'Abgrund','나락의':'Nether','나락':'Nether','무간의':'Leere',
'전기':'Funken','낙뢰':'Donner','암전':'Blitz','뇌신의':'Sturmgott','뇌신':'Sturmgott','만뢰의':'Myriadendonner',
'축복':'Gesegnet','성광':'Heiliges Licht','신성':'Sakral','천사의':'Engel','신벌의':'Göttliches Urteil',
'낡은':'Abgenutzt','천':'Stoff','가죽':'Leder','강철사':'Stahlfaser','은':'Silber','은사':'Silberfaden','화염의':'Inferno','빙결의':'Eisgebunden','암흑의':'Finster','암전의':'Blitz'};
const _DE_BASE={'대검':'Großschwert','석궁':'Armbrust','연사석궁':'Schnellfeuer-Armbrust','마력석궁':'Arkane Armbrust',
'견갑':'Schulterplatte','대견갑':'Große Schulterplatte','전투화':'Kampfstiefel','갑옷':'Rüstung','갑주':'Panzerung',
'왕관':'Krone','장갑':'Handschuhe','건틀릿':'Panzerhandschuhe','바지':'Hose','각반':'Beinschienen',
'허리띠':'Gürtel','벨트':'Gürtel','부적':'Talisman','목걸이':'Halskette','반지':'Ring',
'망토':'Umhang','팔찌':'Armreif','귀걸이':'Ohrring'};
