const _PTBR={
// --- Stage / Boss ---
'썩은 숲':'Floresta Apodrecida','숲의 감시자':'Guardião da Floresta','독버섯 거인':'Gigante Cogumelo Tóxico','숲의 사냥꾼':'Caçador da Floresta','숲의 기생수':'Besta Parasita',
'1장 — 썩은 숲':'CAP1 — Floresta Apodrecida','2장 — 벌레굴':'CAP2 — Covil de Vermes','3장 — 얼음굴':'CAP3 — Caverna de Gelo',
'4장 — 고통의 화염지대':'CAP4 — Terras Infernais','5장 — 지옥의 군단':'CAP5 — Legião Infernal','6장 — 사도의 마굴':'CAP6 — Covil do Apóstolo','7장 — 지옥성':'CAP7 — Cidadela Infernal',
'탈출!':'Escapou!','처치':'Abates','경험치':'EXP','최대콤보':'Combo Máx',
// --- Tutorial (Crow) ---
'일어나. 여신이 널 여기 보낸 건 죽으라고가 아니야.':'Levanta. A deusa não te mandou aqui pra morrer.',
'좋아, 감각이 있군. 계속 쳐!':'Bom, você tem instinto. Continua batendo!',
'Shift를 눌러. 작살이다. 땅에 꽂아서 끌려가!':'Aperta Shift. É o arpão. Crava no chão e se lança!',
'작살로 끌려가는 중엔 무적이다. 위험할 때 쓰면 좋아.':'Você fica invencível enquanto o arpão te puxa. Usa quando apertar.',
'...아파? 당연하지. 여긴 지옥이야.':'...Dói? Claro. Aqui é o inferno.',
'Q를 눌러! 악의로 보호막을 만들 수 있다.':'Aperta Q! Cria um escudo com malícia.',
'보호막 없이 버틸 생각은 버려.':'Esquece de sobreviver sem escudo.',
'우클릭이 패링이다. 적 공격이 닿기 직전에 눌러!':'Clique direito pra aparar. Aperta bem na hora que o ataque chegar!',
'못 하겠으면 때려. 안 죽으면 그만이야.':'Não consegue aparar? Só bate. Não morrer já tá bom.',
'됐어! 감 잡았구나.':'É isso aí! Tá pegando o jeito.',
'하나 죽었군.':'Caiu um.',
'유령쇠뇌야. 인사해.':'É a besta fantasma. Cumprimenta.',
'빨간 탄을 무서워하지 마. 악의가 강하다.':'Não tenha medo das balas vermelhas. A malícia é forte.',
'패링으로 돌려주고, Q 보호막도 써! 악의를 잘 굴려!':'Apara e devolve, usa o escudo Q também! Domine a malícia!',
'무지개빛은 패링 불가! 피해!':'Tiros arco-íris não podem ser aparados! Desvia!',
'피가 새고 있다. Shift. 빠져.':'Tá sangrando. Shift. Sai fora.',
'물약 있잖아! 숫자키!':'Você tem poções! Teclas numéricas!',
'우클릭. 적 손목이 꺾일 때 쳐.':'Clique direito. Ataca quando o pulso do inimigo virar.',
'빨간 탄은 악의 덩어리다. 쳐내서 이용해.':'Balas vermelhas são pedaços de malícia. Rebate e usa.',
'무지개빛만 피하면 돼! 나머지는 다 패링!':'Só desvia do arco-íris! O resto apara tudo!',
'Q 보호막도 패링이 가능해!':'O escudo Q também pode aparar!',
'위험해! 쉬프트 사슬기동으로 피해!!':'Perigo! Shift investida em cadeia pra escapar!!',
'쉬프트! 사슬기동은 이동기야! 끌려가면서 무적이라고!':'Shift! Investida em cadeia é deslocamento! Invencível enquanto puxa!',
'스킬포인트가 쌓였어! K 눌러서 스킬 배우자!':'Pontos de habilidade acumularam! Aperta K pra aprender!',
'속성을 읽어. 약점을 찌르면 두 배로 썩는다.':'Leia os elementos. Acerta a fraqueza e o dano dobra.',
'K를 눌러봐! 스킬을 배울 수 있어!':'Aperta K! Dá pra aprender habilidades!',
'C 눌러서 능력치 찍어! 패시브도 있어~':'Aperta C pra atributos! Tem passivas também~',
'G를 눌러. 대장간에서 장비를 강화할 수 있다.':'Aperta G. Melhora equipamento na forja.',
'F키도 스킬 슬롯이야! 스킬 많으면 L로 배정해봐~':'A tecla F também é slot de habilidade! Usa L pra designar~',
'Z. 필살기다. 아껴 써라.':'Z. É a suprema. Usa com sabedoria.',
'L-CTRL로 유령걸음이나 얼음보주 쓸 수 있어!':'L-CTRL pra Passo Fantasma ou Orbe de Gelo!',
'L을 눌러. 스킬 슬롯을 정리해야 한다.':'Aperta L. Organiza os slots de habilidade.',
'가방 터지겠다! V 눌러서 창고에 넣어둬!':'A bolsa vai explodir! Aperta V pra guardar no depósito!',
'ESC로 설정 열 수 있어! 난이도 바꾸기, 자동물약 조절~':'ESC abre configurações! Mudar dificuldade, poção automática~',
// --- Tutorial (Cat) ---
'...아직 살아있네. 좌클릭으로 저것들 쳐봐.':'...Ainda vivo. Tenta bater neles com clique esquerdo.',
'...치는 건 할 줄 아네. 피하는 건?':'...Sabe bater. Mas sabe desviar?',
'흥, 작살 못 맞추면 헛수고야.':'Hmpf, errou o arpão e é esforço perdido.',
'...운이 좋았을 뿐이야. 아마.':'...Foi só sorte. Provavelmente.',
'...고기 냄새. 싫진 않네.':'...Cheiro de carne. Nada mal.',
'...말은 못해.':'...Ele não fala.',
'예쁘다고 만지면 죽어.':'Achou bonito e quer tocar? Vai morrer.',
'작살 던져! 끌려가면 무적이야!':'Lança o arpão! Invencível enquanto puxa!',
'...마시든 말든. 네 목숨이니까.':'...Bebe ou não. É a tua vida.',
'그게 패링이야! 타이밍이 전부야~':'Isso é aparar! Timing é tudo~',
'화염엔 빙결! 암전엔 암흑! 기억해!':'Fogo contra Gelo! Raio contra Trevas! Lembra!',
'...얼어붙은 놈은 오래 안 간다.':'...Congelado não dura muito.',
'얼었어! 빙결 중 1.5배야!':'Congelou! 1.5x de dano enquanto congelado!',
'...힘을 골라라. 전부 가질 순 없다.':'...Escolhe teu poder. Não dá pra ter tudo.',
'스탯을 올려. 살고 싶으면.':'Sobe teus atributos. Se quiser viver.',
'좋은 장비는 강화해야 진짜 힘을 발휘해!':'Equipamento bom precisa de melhoria pra mostrar o verdadeiro poder!',
'...슬롯을 채워. 빈 손은 죽음이다.':'...Preenche os slots. Mãos vazias significam morte.',
'Z 누르면 대박! 쿨타임 길어서 타이밍 봐야 해!':'Aperta Z pra dano massivo! Recarga longa, escolhe a hora!',
'Ctrl. 위기에 쓸 카드가 하나 늘었군.':'Ctrl. Mais uma carta pra emergências.',
'스킬이 많아졌네~ L로 어디에 뭘 넣을지 골라!':'Tantas habilidades~ Usa L pra designar!',
'...버리기 아까운 건 창고에.':'...Guarda no depósito o que for bom demais pra jogar fora.',
'...살아남은 것만으로도 대단하군. 설정을 확인해.':'...Sobreviver já é impressionante. Confere as configurações.',
// --- System Messages ---
'MP 부족!':'MP insuficiente!','ST 부족!':'ST insuficiente!','악의 부족!':'Malícia insuficiente!',
'충전 중...':'Carregando...','캔슬':'Cancelar','아이템 선택 필요':'Selecione um item',
'악의 소진...':'Malícia esgotada...','비문 발견...':'Inscrição encontrada...',
'HP물약!':'Poção de HP!','HP물약 +1':'Poção de HP +1','HP물약 +2':'Poção de HP +2',
'HP/MP/ST 회복!':'HP/MP/ST Restaurados!','보물상자 개봉!':'Baú Aberto!',
'익사!':'Afogando!','피웅덩이!':'Poça de Sangue!','독혈!':'Sangue Tóxico!','잡힘!':'Agarrado!',
'콤보 종료':'Combo Encerrado',
// --- Status Effects ---
'빙결!':'Congelado!','화상!':'Queimando!','독!':'Veneno!','감전!':'Chocado!',
'기절!':'Atordoado!','봉인됨!':'Selado!','관통!':'Perfuração!',
// --- Skill Names ---
'기검참':'Corte de Ki','악의구':'Orbe de Malícia','회전참':'Redemoinho','기폭팔':'Detonação',
'칼등 처내기':'Aparar com Lâmina','만화방창':'Rajada de Agulhas','멸살광선':'Raio Aniquilador',
'원소추적탄':'Rastreador Elemental','악의 보호자':'Guardião da Malícia','악의 사냥':'Caçada da Malícia',
'폭풍소환':'Invocação de Vórtice','해골무덤':'Tumba de Ossos','신성폭발':'Explosão Sagrada',
'블랙':'Estrela Negra','용암소환':'Invocação de Lava','처형':'Execução','악마화 부활':'Ressurreição Demoníaca',
'붉은꽃':'Flor Carmesim','얼음보주':'Orbe de Gelo','뇌전걸음':'Passo Fantasma',
'만화방창 II':'Rajada de Agulhas II','마력연사':'Rajada Arcana','마력광선':'Raio Arcano','업화선':'Raio Infernal',
'지옥진':'Formação Infernal','폭독칼날':'Lâmina Pestilenta','악의폭풍':'Tempestade de Malícia',
'악의기둥':'Pilar Sombrio','회복의 영역':'Domínio Sagrado','구속의 영역':'Domínio Restritivo',
'아이스스톰':'Tempestade de Gelo','대왕치기':'Golpe Colossal','대왕치기 2':'Golpe Colossal II',
'기동불꽃':'Corrente Flamejante','기동파괴':'Corrente Destrutora','기동칼날개':'Corrente Asa-Lâmina',
'평화의보호':'Égide da Paz','참회':'Penitência','칼등날개':'Asa Escudo',
'폭산탄':'Disparo Explosivo','파쇄의 영역':'Domínio de Fragmentação','침식의 영역':'Domínio de Corrosão',
'관통의 영역':'Domínio Perfurante','부활의 영역':'Domínio de Ressurreição','가시덫':'Armadilha de Espinhos',
'푸른비':'Chuva Azul','버스트루프':'Ciclo de Explosão','유령 허수아비':'Espantalho Fantasma','폭발 허수아비':'Espantalho Explosivo',
'공성쇠뇌':'Besta de Cerco','사슬기동:충돌':'Corrente: Impacto',
'사슬기동:화염':'Corrente: Chamas','전격이동':'Avanço Relâmpago',
// --- Skill Activation ---
'기동칼날개!':'Asa-Lâmina!','기동불꽃!':'Chama em Cadeia!','기동파괴!':'Destruição em Cadeia!',
'사슬이동:강화!':'Investida em Cadeia!','사슬기동:화염!':'Chama em Cadeia!',
'작살!':'Arpão!','진입!':'Entrar!','레인라이트닝!':'Chuva de Raios!',
'마력연사!':'Rajada Arcana!','🔷 마력광선!':'🔷 Laser Arcano!','광선 해제':'Laser Desligado','MP 부족 — 광선 해제':'MP esgotado — Laser Desligado','집중...':'Foco...','시전...':'Conjurando...',
'만화방창!':'Rajada de Agulhas!','바늘출!':'Estouro de Agulhas!','칼날!':'Lâmina!',
'착지!':'Aterrissagem!','체간삭감!':'Quebra de Postura!',
'기동전폭 준비!':'Explosão em Cadeia Pronta!','기동불꽃 준비!':'Chama em Cadeia Pronta!',
'기동파괴 준비!':'Destruição em Cadeia Pronta!',
'유령불꽃 ON':'Chama Fantasma ON','유령불꽃 OFF':'Chama Fantasma OFF',
'기동칼날개 AUTO ON':'Asa-Lâmina AUTO ON','기동칼날개 AUTO OFF':'Asa-Lâmina AUTO OFF',
'자동 버스트!':'Explosão Automática!','연사 해제':'Rajada desativada',
'당기기 모드':'Modo Puxar','밀어내기 모드':'Modo Empurrar',
// --- Skill Slot Tooltips ---
'날개치기':'Golpe Asa','처내기':'Aparar',
'Shift: 작살 발사 → 끌려감':'Shift: Lançar arpão → puxar',
'Shift: 화염길+화상':'Shift: Rastro de fogo+queimadura',
'CT: 전류변신+뇌전걸음 (쿨4초)':'CT: Forma elétrica+Passo Fantasma (CD 4s)',
'CT: 방어구체+빙결 (재입력: 파쇄)':'CT: Esfera de gelo+congelar (re-pressionar: estilhaçar)',
// --- HUD ---
'근접':'Corpo','견갑':'Guarda','작살':'Arpão','마법':'Magia','보막':'Escudo','유령':'Fantasma',
'스킬':'Habilidades','대장':'Forja','인벤':'Inv',
// --- Menu ---
'인벤토리':'Inventário','복수의 대장간':'Forja da Vingança','패시브 스킬':'Habilidades Passivas',
'전투 스킬':'Habilidades de Combate','캐릭터 선택':'Seleção de Personagem',
// --- Elements ---
'물리':'Físico','화염':'Fogo','빙결':'Congelado','암흑':'Trevas','암전':'Raio','신성':'Sagrado','대지':'Terra',
// --- Passives ---
'힘':'Força','민첩':'Destreza','지능':'Inteligência','행운':'Sorte',
'맹공':'Acometida','철벽':'Fortaleza','돌파':'Ruptura','반격':'Represália',
'마력폭주':'Surto Arcano','정밀사격':'Disparo Preciso','수호':'Proteção','수호신':'Espírito Guardião',
'회복력':'Regeneração','급소':'Golpe Vital','약탈':'Saque','관통':'Penetração',
'마력회복':'Recuperação de Mana','쇠뇌력':'Maestria de Besta','광전사':'Berserker','추적자':'Rastreador',
'물리관통':'Pen. Física','마법관통':'Pen. Mágica',
// --- Weapons (Tier 0) ---
'녹슨 대검':'Espadão Enferrujado','강철 대검':'Espadão de Aço','흑요석 대검':'Espadão de Obsidiana',
'낡은 석궁':'Besta Gasta','강철 석궁':'Besta de Aço','흑요석 석궁':'Besta de Obsidiana',
'대검':'Espadão','석궁':'Besta','연사석궁':'Repetidora','마력석궁':'Besta Arcana',
// --- Misc ---
'악의 추출':'Extração de Malícia','악의':'Malícia','필살기':'Suprema','필살기 해제':'Suprema removida',
'이전':'Transferir','강화':'Melhorar','개봉!':'Aberto!',
'여신의 가호':'Bênção da Deusa',
'과부하!':'Sobrecarga!',
// --- Affix Names ---
'맹독의':'Venenoso','불꽃의':'Flamejante','냉기의':'Gélido','번개의':'Voltaico','암흑의':'Amaldiçoado',
'관통의':'Perfurante','광폭의':'Furioso','파쇄의':'Fragmentador','연쇄의':'Encadeado',
'학살의':'Exterminador','폭발의':'Explosivo','집중의':'Focado','쾌속의':'Veloz','패리의':'Desviador',
'추적자의':'do Rastreador','작살의':'do Arpão','궁극의':'Supremo','집중력의':'Concentrado',
'강인의':'Estoico','수호의':'Protetor','활력의':'Vital','신속의':'Acelerado',
'화염수호':'Guarda Ígneo','빙결수호':'Guarda Gélido','암전수호':'Guarda Elétrico','암흑수호':'Guarda Sombrio','독수호':'Guarda Tóxico','전원소수호':'Guarda Total',
'강철의':'Férreo','반사의':'Reflexivo','가시의':'Espinhoso','흡수의':'Absorvente','인내의':'Resistente',
'위기의':'Desesperado','피격반격의':'Contra-atacante',
'패링폭발의':'Explosão de Aparar','스태거폭발의':'Explosão de Tambaleo','원소전환의':'Conversor','정화의':'Purificador',
'불굴의':'Inquebrável','부활의':'Ressurreicionista',
'약탈의':'Saqueador','경험의':'Experiente','골드의':'Dourado','포션강화의':'Potencializador','사슬의':'Acorrentado',
'진혼의':'Santificador','윤회의':'Cíclico',
'생명력의':'Vigoroso','재생의':'Regenerador','치유의':'Curativo',
'마력의':'Arcano','절약의':'Eficiente','영혼의':'Anímico',
'예리한':'Afiado','맹렬한':'Brutal','파멸의':'Ruinoso',
// --- Settings UI ---
'게임 설정':'Configurações do Jogo','화면 흔들림':'Tremor de Tela','파티클 양':'Quantidade de Partículas',
'효과음 볼륨':'Volume de Efeitos','음악 볼륨':'Volume de Música','난이도':'Dificuldade',
'자동 물약':'Poção Automática','최소 줍기 등급':'Grau Mín. de Coleta','최소 줍기 티어':'Tier Mín. de Coleta',
'FPS 제한':'Limite de FPS','해상도 스케일':'Escala de Resolução','펫 자동수거':'Pet Coleta Automática',
'화면 설정':'Config. de Tela','화면 모드':'Modo de Tela','보스 AI 디버그':'Debug de IA do Boss',
'유령불꽃 크기':'Tamanho da Chama Fantasma','화면 명암':'Brilho','유령 글로우':'Brilho Fantasma',
'기동:칼날개 AUTO':'Asa-Lâmina AUTO',
'일반':'Normal','어려움':'Difícil','지옥':'Inferno','이상':'ou acima','사용 안 함':'Desativado',
'창 모드':'Janela','보더리스':'Sem Bordas','전체화면':'Tela Cheia',
'설정':'Configurações','조작 키 설정 (클릭하여 변경)':'Teclas de Atalho (Clique para Alterar)',
// --- Key Guide ---
'좌클릭 무기 공격':'LMB Ataque com Arma','우클릭 탭 칼등 처내기':'RMB Toque Aparar com Lâmina',
'우클릭 홀드 연속 처내기':'RMB Segurar Aparar Contínuo','SHIFT 작살 발사':'SHIFT Lançar Arpão',
'이동':'Mover','아이템 줍기':'Pegar Item','능력치 (스탯/패시브)':'Atributos (Stats/Passivas)',
// --- Forge ---
'복수의 대장간':'Forja da Vingança','강화':'Melhorar','분해':'Desmontar','제작':'Fabricar',
// --- Death Screen ---
'사망':'Morte','부활':'Ressuscitar','로비로':'Ao Lobby',
// --- Inventory/Storage ---
'가방에 공간이 없습니다!':'Sem espaço na bolsa!','가방이 가득 찼습니다!':'Bolsa cheia!',
'창고가 가득 찼습니다!':'Depósito cheio!','퀵슬롯이 가득 찼습니다!':'Slot rápido cheio!',
'결정 주머니가 가득 찼습니다!':'Bolsa de cristais cheia!','결정 주머니 가득!':'Bolsa de cristais cheia!',
'악의가 부족합니다!':'Malícia insuficiente!','가방이 비어있습니다':'Bolsa vazia',
'창고가 비어있습니다':'Depósito vazio','비어있음':'Vazio','어픽스 없음':'Sem afixo',
'장착!':'Equipado!','해제':'Desequipar','보관':'Guardar','꺼내기':'Retirar',
'현재 장착':'Equipado atualmente','없음 — 제작하세요!':'Nenhum — Fabrique um!',
'리셋할 포인트가 없습니다':'Sem pontos para resetar',
'키 설정 초기화 완료':'Teclas de atalho resetadas',
// --- Forge/Craft ---
'제작 확률':'Chance de fabricação','제작 비용':'Custo de fabricação','보유 악의':'Malícia possuída',
// --- Canvas UI ---
'보스방':'Sala do Boss','안식처':'Santuário','회복':'Recuperar','점화':'Ignição',
'비석':'Estela','읽기':'Ler','파괴':'Destruir','제단':'Altar','기원':'Orar',
'잔해':'Destroços','열기':'Abrir','문지기':'Guardião',
'부활 판정 중...':'Julgando ressurreição...','기폭 준비!':'Detonação pronta!',
'탈출':'Escapar','연타':'Apertar',
'추적암전':'Raio Rastreador','만화광선':'Raio Luminescente','최종 마법':'Magia Final',
'감시중':'Vigiando','대기':'Em Espera','작동중':'Ativo','설치 가능':'Pode instalar',
'균열 임박!':'Fissura iminente!','흡수 중...':'Absorvendo...',
'흡수 완료 — 재입력으로 회수':'Concluído — pressione novamente para coletar',
'화상':'Queimadura','당기기':'Puxar','밀어내기':'Empurrar',
'단계':'tier','단':'tier',
// --- Skill Panel ---
'습득!':'Aprendido!','리셋!':'Resetado!','세팅!':'Definido!','회수':'Recuperar',
'합체 해제':'Desfundir','리셋':'Resetar','환불':'Reembolsar',
'파트너 클릭!':'Clique no parceiro!','SP부족!':'SP necessário!',
'같은 보석 스킬 습득 시 합체 가능':'Pode fundir ao aprender habilidade da mesma gema',
'펼쳐서 초기화':'Expandir para resetar','슬롯:':'Slot:',
// --- Stats ---
'남은 SP':'SP Restante','처치':'Abates','경험치':'EXP','최대콤보':'Combo Máx',
'맞아서 사망':'Morto por golpe','레벨':'Nível','최대HP':'HP Máx',
// --- Enemy Names ---
'방랑 기사':'Cavaleiro Errante','보물 악마':'Demônio do Tesouro','거울의 사도':'Apóstolo do Espelho',
'상인 악마':'Demônio Mercador','사슬의 죄수':'Prisioneiro Acorrentado','시간의 사도':'Apóstolo do Tempo',
'탐욕의 사도':'Apóstolo da Ganância','저주받은 쌍둥이':'Gêmeos Amaldiçoados','차원 균열체':'Fissura Dimensional',
'죽음 그 자체':'A Própria Morte',
// --- Crystals ---
'HP결정':'Cristal de HP','ST결정':'Cristal de ST','MP결정':'Cristal de MP',
'ATK결정':'Cristal de ATK','DEF결정':'Cristal de DEF','속도결정':'Cristal de Velocidade',
'크리결정':'Cristal de Crítico','치명결정':'Cristal de Dano Crít.','화염결정':'Cristal de Fogo',
'냉기결정':'Cristal de Gelo','암흑결정':'Cristal de Trevas','번개결정':'Cristal de Raio',
'신성결정':'Cristal Sagrado','생명결정':'Cristal de Vida','기력결정':'Cristal de Stamina',
'마력결정':'Cristal de Mana','행운결정':'Cristal de Sorte',
'조각':'Fragmento','파편':'Estilha','순수결정':'Cristal Puro','완전결정':'Cristal Perfeito',
'결정 주머니':'Bolsa de Cristais','결정이 없습니다':'Sem cristais','가루':'Pó',
'전체':'Todos','스탯':'Atrib','원소':'Elem','유틸':'Util',
'현재':'Atual','최대 강화 달성 (+20)':'Melhoria máx. alcançada (+20)','강화 시':'Após melhoria',
'강화':'Melhorar','합성':'Sintetizar','제작':'Fabricar',
'같은 종류·같은 성급 결정 3개 → 1성급 상승 (강화 리셋)':'3 cristais do mesmo tipo e grau → sobe 1 grau (melhoria reseta)',
'합성 가능한 결정이 없습니다 (같은 종류·성급 3개 필요)':'Sem cristais sintetizáveis (precisa 3 do mesmo tipo e grau)',
'결정 분해 → 결정 가루':'Decompor Cristal → Pó de Cristal',
'분해할 결정이 없습니다':'Sem cristais para decompor',
'결정 제작 (가루 → 결정)':'Fabricar Cristal (Pó → Cristal)',
'탈착':'Remover','빈 슬롯':'Slot vazio',
'결정 선택 후 클릭':'Selecione cristal e clique','클릭하여 선택결정 장착':'Clique para equipar cristal selecionado',
'획득!':'Obtido!','제작!':'Fabricado!','합성!':'Sintetizado!','최상위 일괄합성':'Síntese em Massa ao Topo','일괄합성 완료':'Síntese em massa concluída',
// --- Stage Names ---
'벌레굴':'Covil de Vermes','얼음굴':'Caverna de Gelo','고통의 화염지대':'Terras Infernais',
'지옥의 군단':'Legião Infernal','사도의 마굴':'Covil do Apóstolo','지옥성':'Cidadela Infernal',
// --- Misc ---
'엑소듀서 전사':'Guerreiro Exorcista','포이즈':'Postura',
'신성폭발':'Explosão Sagrada','뇌전걸음':'Passo Fantasma',
'지옥창고':'Depósito Infernal','선택분해':'Desmonte Seletivo','쓰레기':'Lixo',
'복구 불가!':'Irrecuperável!','중요잠금':'Trava importante',
// --- Phase 9 additions ---
'획득!':'Obtido!','자동 장착!':'Equipado automaticamente!','분해! 가루 +':'Desmontado! Pó +',
'추적암전':'Raio Rastreador','암전':'Raio',
'평화보호':'Égide','지진폭풍':'Tempestade Sísmica','회전기폭':'Det. Redemoinho',
'공격':'Ataque','보호막':'Escudo','필살기':'Suprema',
'합체 스킬로 통합됨':'Integrado na habilidade fundida','얼음보주 안에선 사용 불가!':'Não pode usar dentro do Orbe de Gelo!',
'Shift+키로 폭파':'Shift+tecla para detonar','취소':'Cancelar','충전 중...':'Carregando...',
'쿨다운 중...':'Em recarga...','시전 중...':'Conjurando...','악의 부족!':'Malícia insuficiente!',
'악의 부족! (12)':'Malícia insuficiente! (12)','악의 부족! (15)':'Malícia insuficiente! (15)',
'악의 부족! (20)':'Malícia insuficiente! (20)','악의 부족! (10)':'Malícia insuficiente! (10)',
'ST 부족!':'ST insuficiente!','HP 부족!':'HP insuficiente!',
'필살기 슬롯 클릭하여 배정!':'Clique no slot da suprema para designar!',
'필살기 스킬을 습득하세요':'Aprenda uma habilidade suprema',
'우클릭(칼등치기)에 합체됨':'Fundido ao RMB (aparar com lâmina)',
'T(석궁자동)에 세팅하세요':'Defina para T (besta automática)',
'공성쇠뇌 철거 → 이동식':'Besta de cerco desmontada → portátil',
'ST 부족! (100)':'ST insuficiente! (100)',
'HP 99% 이상!':'HP 99%+!','그로기 보스 없음!':'Nenhum boss atordoado!',
'이미 폭풍 지역!':'Já na zona de tempestade!','이미 빙풍 지역!':'Já na zona de tempestade de gelo!',
'💎 푸른비 해금!':'💎 Chuva Azul desbloqueada!','💫 버스트루프 해금!':'💫 Ciclo de Explosão desbloqueado!',
'👻 유령 허수아비 해금!':'👻 Espantalho Fantasma desbloqueado!',
'쿨 ':'CD ','과부하 ':'Sobrecarga ',
'🕊️💎 블루콩!':'🕊️💎 Feijão Azul!','🛡️💎 빨콩→블루콩!':'🛡️💎 Vermelho→Feijão Azul!',
'🛡️💎 무지개→블루콩!':'🛡️💎 Arco-íris→Feijão Azul!',
'레어':'Raro','슬롯':'Slot',
'성공률':'Taxa de Sucesso','AI 자동 강화':'Melhoria Automática IA','최대 강화 달성!':'Melhoria máxima alcançada!',
'최대 강화':'Melhoria máx.','회복량':'Qtd. Recuperação','현재 장착':'Equipado atualmente',
'없음 — 제작하세요!':'Nenhum — Fabrique um!','제작 확률':'Chance de fabricação',
'분해할 아이템이 없습니다.':'Sem itens para desmontar.','🔨 제작':'🔨 Fabricar',
'체간':'Postura','아이템에 마우스를 올리거나 좌클릭으로 선택하세요':'Passe o mouse ou clique com esquerdo para selecionar',
// --- Phase 10: death/levelup/intro screen ---
'중독':'Veneno','지뢰':'Mina','함정':'Armadilha','산호가시':'Espinho de Coral',
'투사체':'Projétil','도트':'DoT','레어몹':'Mob Raro',
'처치':'Abates','경험치':'EXP','최대콤보':'Combo Máx',
'구역':'Zona','가시!':'Espinho!',
// --- Hell circle / palette names ---
'림보':'Limbo','색욕':'Luxúria','탐식':'Gula','탐욕':'Ganância','분노':'Ira','이단':'Heresia','폭력':'Violência',
'분노!':'Fúria!','탐욕!':'Ganância!','💀 분노 폭발!':'💀 Explosão de Fúria!','심연의 분노!':'Fúria Abissal!','쌍둥이의 분노!':'Fúria dos Gêmeos!',
// --- HUD / misc ---
'소환굴':'Poço de Invocação',
'레어':'Raro','처치!':'Derrotado!','왕관 착용':'Coroa On','왕관 해제':'Coroa Off',
'맨손':'Desarmado','없음':'Nenhum','갑옷':'Armadura','부츠':'Botas',
// --- Elite / Mod / Aura ---
'매직':'Mágico','챔피언':'Campeão',
'빙결':'Congelado','초속':'Acelerado','강타':'Golpe','재생':'Regen','맹독':'Veneno','소환':'Invocar',
'기생':'Parasita','분열':'Cisão','용암자취':'Rastro de Lava','사망폭발':'Explosão Mortal',
'화염사슬':'Corrente de Fogo','광전':'Frenesi','텔레포트':'Teleporte','보호막':'Barreira',
'소용돌이':'Vórtice','환영':'Ilusão','전격반사':'Reflexo de Choque','감전':'Chocado',
'낙뢰':'Trovão','연쇄전격':'Raio em Cadeia','동료불사':'Aliado Imortal',
'영혼포식':'Devorar Alma','시간왜곡':'Distorção Temporal','혼돈변이':'Mutação Caótica',
'복수자':'Vingador','마법보초':'Sentinela Mágica','환영술사':'Ilusionista',
'함성':'Grito de Guerra','치유':'Curar','신속':'Velocidade','수호':'Proteção',
// --- Character ---
'다크 판타지 전사. 거대검+검은 갑옷':'Guerreiro de fantasia sombria. Espadão + Armadura negra',
// --- Phase 11: missing addTxt/showPH/notify translations ---
'⚡ 사슬이동:강화!':'⚡ Cadeia:Reforçada!',
'⚡ 사슬기동:화염!':'⚡ Investida em Cadeia: Chamas!',
'달성!':'Alcançado!',
'ST':'ST','부족!':'Insuficiente!',
'타':'Golpe',
'🌀 당기기 모드':'🌀 Modo Puxar',
'💥 밀어내기 모드':'💥 Modo Empurrar',
'🕊️빨콩 흡수':'🕊️Absorver feijão vermelho',
'🕊️흡수':'🕊️Absorver',
'💎유도 폭발!':'💎Explosão guiada!',
'💥반사 폭발!':'💥Explosão refletida!',
'⚡⚡ 참회 귀환!':'⚡⚡ Retorno Penitente!',
'⚡ 참회!':'⚡ Penitência!',
'파도!':'Onda!',
'암전!':'Raio!',
'암흑!':'Trevas!',
'암흑창!':'Lança Sombria!',
'빛창!':'Lança de Luz!',
'체 소환!':'invocado!',
'개 설치!':'instalado!',
'💥 보스 그로기!':'💥 Boss Atordoado!',
'💥 그로기!':'💥 Atordoado!',
'보상':'Bônus',
'⚡ 암전나선!':'⚡ Hélice de Raio!',
'🌋 지진폭풍!':'🌋 Tempestade Sísmica!',
'SP슬롯':'Slot SP',
'F슬롯':'Slot F',
'⚔🩸 독혈해방!':'⚔🩸 Liberação Pestilenta!',
'⚔ 칼날 해방!':'⚔ Liberação de Lâmina!',
'🔨🌋 지옥강타!':'🔨🌋 Golpe Infernal!',
'🔨 대왕치기!':'🔨 Golpe Colossal!',
'✟ 신성한 결계!':'✟ Barreira Sagrada!',
'🛡 회복의 영역!':'🛡 Domínio Sagrado!',
'기폭팔!':'Detonar!','강제기폭!':'Detonação Forçada!','자동기폭!':'Detonação Automática!',
'회전기폭!':'Det. Redemoinho!','해제기폭!':'Det. de Liberação!','지진기폭!':'Det. Sísmica!',
'혼돈의 왕관':'Coroa do Caos',
'전지전능의 왕관':'Coroa da Onipotência',
'악마의 팔찌':'Bracelete Demoníaco',
'생명의 팔찌':'Bracelete da Vida',
// --- wave direction names (full addTxt strings) ---
'🌊 위→아래 파도!':'🌊 Onda Cima→Baixo!','🌊 오른→왼 파도!':'🌊 Onda Dir→Esq!',
'🌊 아래→위 파도!':'🌊 Onda Baixo→Cima!','🌊 왼→오른 파도!':'🌊 Onda Esq→Dir!',
// --- Phase 12: remaining addTxt/UI translations ---
'⚡ 사슬이동:강화!':'⚡ Cadeia:Reforçada!','⚡ 사슬기동:화염!':'⚡ Investida em Cadeia: Chamas!',
'🌀 당기기 모드':'🌀 Modo Puxar','💥 밀어내기 모드':'💥 Modo Empurrar',
'💎유도 폭발!':'💎Explosão Guiada!','💥반사 폭발!':'💥Explosão Refletida!',
'⚡⚡ 참회 귀환!':'⚡⚡ Retorno Penitente!','⚡ 참회!':'⚡ Penitência!',
'암전!':'Raio!','암흑!':'Trevas!','암흑창!':'Lança Sombria!','빛창!':'Lança de Luz!',
'💥 보스 그로기!':'💥 Boss Atordoado!','💥 그로기!':'💥 Atordoado!',
'⚡ 암전나선!':'⚡ Hélice de Raio!','🌋 지진폭풍!':'🌋 Tempestade Sísmica!',
'⚔🩸 독혈해방!':'⚔🩸 Liberação Pestilenta!','⚔ 칼날 해방!':'⚔ Liberação de Lâmina!',
'🔨🌋 지옥강타!':'🔨🌋 Golpe Infernal!','🔨 대왕치기!':'🔨 Golpe Colossal!',
'✟ 신성한 결계!':'✟ Barreira Sagrada!','🛡 회복의 영역!':'🛡 Domínio Sagrado!',
'파도!':'Onda!',
// --- rare mob / special ---
'무적!':'Invencível!','🪞 반격!':'🪞 Contra-ataque!','💢 반격!':'💢 Contra-ataque!',
'흡수!':'Absorver!','반격 발사!':'Tiro de Contra-ataque!',
'저주! 드랍률 -50%':'Maldição! Taxa de drop -50%','도망!':'Fugiu!',
'위상!':'Fase!','방어!':'Defesa!',
'회수 HP+':'Recuperar HP+','이동식 복귀':'Retorno Portátil','캔슬':'Cancelar',
'약점!':'Fraqueza!','저항!':'Resistência!','관통!':'Perfuração!',
'유령불꽃 OFF':'Chama Fantasma OFF','유령불꽃 ON':'Chama Fantasma ON',
'기동칼날개 AUTO ON':'Asa-Lâmina AUTO ON','기동칼날개 AUTO OFF':'Asa-Lâmina AUTO OFF',
'콤보 종료: ':'Combo Encerrado: ','익사!':'Afogando!',
'피웅덩이!':'Poça de Sangue!','독혈!':'Sangue Tóxico!','비문 발견...':'Inscrição encontrada...',
'보물상자 개봉!':'Baú Aberto!','악의 +':'Malícia +','잡힘!':'Agarrado!',
'저주 ':'Maldição ','충전 중...':'Carregando...','불발...':'Falha...',
'작살 약점!':'Fraqueza do Arpão!',
'전염 x':'Contágio x','흡수 완료!':'Absorção Completa!',
'부활 성공!':'Ressurreição bem-sucedida!','부활 실패...':'Ressurreição falhou...',
'산호가시':'Espinho de Coral','가시!':'Espinho!','차원 이동!':'Salto Dimensional!','독!':'Veneno!',
'탈출!':'Escapou!','기절 해제':'Atordoamento dissipado',
'아이템 선택 필요':'Selecione um item','악의 부족':'Malícia insuficiente','악의 소진...':'Malícia esgotada...',
'스킬 미습득':'Sem habilidades','펼치기':'Expandir','접기':'Recolher',
'조건 미달!':' não atendida!','해제!':' Desfundido!',
'슬롯':'Slot','자동 ON':'Auto ON','자동 OFF':'Auto OFF','스킬 해제':'habilidade removida',
'필살기':'Suprema','필살기 해제':'Suprema removida',
'연사 해제':'Rajada desativada',
'닫기':'Fechar','장착 중':'Equipado','보관 아이템':'Item armazenado',
// --- Phase 13: massive batch — skill activation ---
'클릭으로 선택 · ESC로 닫기':'Clique para selecionar · ESC para fechar',
'선택됨':'Selecionado',
'MP 부족!':'MP insuficiente!','악의 부족! (30)':'Malícia insuficiente! (30)',
'MP 부족! (40)':'MP insuficiente! (40)','MP 부족! (100)':'MP insuficiente! (100)','MP 부족! (10)':'MP insuficiente! (10)',
'MP 부족! (':'MP insuficiente! (',
'✟ 시전...':'✟ Conjurando...','🌋 시전...':'🌋 Conjurando...','⛧ 시전...':'⛧ Conjurando...',
'❄ 진입!':'❄ Entrar!',
'🔱 작살!':'🔱 Arpão!',
'레벨 부족! (요구: Lv.':'Nível baixo! (Req: Lv.',
' 장착!':' Equipado!',
'가방에 공간이 없습니다!':'Sem espaço na bolsa!',
' 해제':' Desequipado',
'👿 악의 추출: +':'👿 Extração de Malícia: +',
'F 슬롯 해제':'Slot F removido',
'💫 집중...':'💫 Focando...',
'⚡ 마력연사!':'⚡ Rajada Arcana!',
'❄빙결!':'❄Congelado!','🟢독!':'🟢Veneno!','⚡감전!':'⚡Chocado!','🔥화상!':'🔥Queimando!',
'✦ 여신의 가호 — SP+5 AP+3':'✦ Bênção da Deusa — SP+5 AP+3',
'⚔ 기동칼날개!':'⚔ Asa-Lâmina!',
'🔥 화염관통!':'🔥 Perfuração de Fogo!',
'🔱 관통!':'🔱 Perfuração!',
'⚔ 칼날!':'⚔ Lâmina!',
'💥 착지!':'💥 Aterrissagem!',
'💫 기절!':'💫 Atordoado!',
'⚡ 체간삭감!':'⚡ Quebra de Postura!',
'⚡ 기동파괴! ':'⚡ Destruição em Cadeia! T',
'🔥 기동불꽃!':'🔥 Chama em Cadeia!',
'🔥 기동불꽃! ':'🔥 Chama em Cadeia! T',
'단계 ×':' x',
'⚡ 기동전폭! x':'⚡ Explosão em Cadeia! x',
'🔥🔥 3중폭!':'🔥🔥 Chama x3!','🔥🔥🔥 6중폭!':'🔥🔥🔥 Chama x6!','🔥🔥🔥🔥 9중폭!':'🔥🔥🔥🔥 Chama x9!','💥 불꽃폭발! ':'💥 Explosão de Chamas! ',
'🔥 기동불꽃 준비!':'🔥 Chama em Cadeia Pronta!',
'🔨 기동파괴 준비!':'🔨 Destruição em Cadeia Pronta!',
'⚡ 기동전폭 준비!':'⚡ Explosão em Cadeia Pronta!',
'콤보 종료: ':'Combo Encerrado: ',
'중독':'Veneno',
'⚡ 과부하! 5초':'⚡ Sobrecarga! 5s',
'💫 자동 버스트!':'💫 Explosão Automática!',
'🔨 칼등날개!':'🔨 Asa-Escudo!',
'💥폭발!':'💥Explosão!',
'🛡️💎 유도반사!':'🛡️💎 Reflexo Guiado!',
'⚡💎 블루콩!':'⚡💎 Feijão Azul!',
'💎 블루콩!':'💎 Feijão Azul!',
'⚡반사!':'⚡Reflexo!',
'💎 푸른비 OFF':'💎 Chuva Azul OFF',
'💎 푸른비 ON!':'💎 Chuva Azul ON!',
'🔥 지옥진!':'🔥 Formação Infernal!',
'🔥 업화선!':'🔥 Raio Infernal!',
'✦ 평화 충격파! ':'✦ Onda de Choque da Paz! ',
'⚡ 전류 방출!':'⚡ Descarga Elétrica!',
'⚡⚡ 레인라이트닝!':'⚡⚡ Chuva de Raios!',
'💫 광역!':'💫 AoE!',
'🔥 불장판!':'🔥 Zona de Fogo!',
'💫 피니셔!':'💫 Finalizador!',
'☠ 지옥에서 귀환!':'☠ Retorno do Inferno!',
'☠ 완전 사망!':'☠ Morte Permanente!',
'⚔ 처형! ':'⚔ Execução! ',
'💥 지뢰!':'💥 Mina!',
'⚠ 함정!':'⚠ Armadilha!',
'❌ 우클릭으로! -':'❌ Use RMB! -',
'❌ Q키로! -':'❌ Use Q! -',
'💥무지개 폭발! ':'💥Explosão Arco-íris! ',
'🛡️💎 블루콩!':'🛡️💎 Feijão Azul!',
'⬜화이트볼!':'⬜Bola Branca!',
'✨💎 블루콩!':'✨💎 Feijão Azul!',
'💜다크볼!':'💜Bola Sombria!',
'❄빙판!':'❄Chão de Gelo!',
'🌨빙결!':'🌨Congelado!',
'🕸둔화!':'🕸Lentidão!',
'⚠트랩!':'⚠Armadilha!',
'💀 역병 처형!':'💀 Execução Pestilenta!',
'💥 역병 Finale!':'💥 Finale Pestilento!',
'⚔ 균열 악마!':'⚔ Demônio da Fissura!',
'자동회수 HP+':'Auto-Recuperar HP+',
'MP 부족 — 연사 해제':'MP baixo — Rajada Desligada',
'MP 부족 — 푸른비 OFF':'MP baixo — Chuva Azul OFF',
'🛡️반사!':'🛡️Reflexo!',
'⚡🦴 참회 귀환!':'⚡🦴 Retorno Penitente!',
'🦴⚡해골번개!':'🦴⚡Raio de Ossos!',
'⚡악의폭풍!':'⚡Tempestade de Malícia!',
'❄아이스스톰!':'❄Tempestade de Gelo!',
'⚡ 암전폭발!':'⚡ Explosão de Raio!',
'⚡ 레인라이트닝! x':'⚡ Chuva de Raios! x',
'❄ 탈출!':'❄ Escapar!',
'⚡쉴드!':'⚡Escudo!',
'❄🌪️ 얼음보주!':'❄🌪️ Orbe de Gelo!',
'🌪️ 전개!':'🌪️ Implantar!',
'❄ 빙결흡인!':'❄ Vórtice Congelante!',
'❄☄ 빙결폭발!':'❄☄ Explosão Congelante!',
'☄️ 흡인!':'☄️ Vórtice!',
'☄️ 대폭발!':'☄️ Mega Explosão!',
'❄ 얼음보주!':'❄ Orbe de Gelo!',
'❄ 파쇄!':'❄ Estilhaçar!',
'☄️💥 대폭발!':'☄️💥 Mega Explosão!',
'반사!':'Reflexo!',
// --- Phase 13: boss moves ---
'💀 도넛!':'💀 Rosca!','💀 전멸!':'💀 Aniquilação!',
'🌊 파도!':'🌊 Onda!','속박!':'Amarrar!','반격!':'Contra-ataque!',
'분신!':'Clone!','분신 파괴!':'Clone Destruído!','무기 해방!':'Liberação de arma!',
'❄프리즌!':'❄Prisão!','⚡ 증표 ':'⚡ Marca ',
'흔들!':'Tremer!','⚠ 광역 발사!':'⚠ Disparo AoE!',
'🔥 확산!':'🔥 Dispersão!','⚠ 돌진!':'⚠ Investida!',
'🦅 도약!':'🦅 Salto!','⚡ 레이저!':'⚡ Laser!',
'🌊 충격파!':'🌊 Onda de Choque!','👹 소환!':'👹 Invocar!',
'☄ 유성우!':'☄ Chuva de Meteoros!','🖐 잡기!':'🖐 Agarrar!',
'🌀 회전참!':'🌀 Redemoinho!','💣 지뢰!':'💣 Mina!',
'🌀 흡인!':'🌀 Vácuo!','🔴 빨간콩 폭풍!':'🔴 Tempestade de Feijão Vermelho!',
'🔴🔴 콩 비!':'🔴🔴 Chuva de Feijão!',
'🌊 부채꼴 충격파!':'🌊 Onda de Choque em Leque!',
'✴ 멸광 레이저!':'✴ Laser Aniquilador!',
'🔴 추적 장판!':'🔴 Zona Rastreadora!',
'💥 속성탄!':'💥 Tiro Elemental!',
'⚔ 검기!':'⚔ Aura de Espada!','⚔ 재단참!':'⚔ Corte Ceifador!',
'🌀 나선탄!':'🌀 Tiro Espiral!','⚠ 찌르기!':'⚠ Estocada!',
'🔥🔥 지옥기둥!':'🔥🔥 Pilar Infernal!',
'⚔ 환영검!':'⚔ Lâmina Fantasma!',
'💢 반격자세!':'💢 Postura de Contra-ataque!',
'⚔ 연격!':'⚔ Combo!','🌑 암흑!':'🌑 Trevas!',
'👥 분신!':'👥 Clone!','🌋 균열!':'🌋 Fissura!',
'🌊 파동!':'🌊 Ondulação!','💣 추적지뢰!':'💣 Mina Rastreadora!',
'⏪ 되감기!':'⏪ Rebobinar!','🌀 중력장!':'🌀 Campo Gravitacional!',
'🔨 벽밀기!':'🔨 Empurrar Parede!','☠ 독안개!':'☠ Névoa Venenosa!',
'⛓ 감옥!':'⛓ Prisão!','⚡ 연쇄번개!':'⚡ Raio em Cadeia!',
'🔮 궤도탄!':'🔮 Tiro Orbital!','🛡 방패돌진!':'🛡 Investida com Escudo!',
'🪞 반격자세!':'🪞 Postura de Contra-ataque!','⚓ 속박!':'⚓ Aprisionar!',
'👤 분신!':'👤 Clone!','🖐 탈취!':'🖐 Roubar!',
'🔥🔥 용암 지대!':'🔥🔥 Zona de Lava!',
'🌧🌧 화염 폭격!':'🌧🌧 Bombardeio de Fogo!',
'⚡⚡ 전격 장막!':'⚡⚡ Véu Elétrico!',
'💀 내 곁으로!':'💀 Venha até mim!',
'⭕ 안전!':'⭕ Seguro!',
'💀💀 전멸 폭발!':'💀💀 Explosão Aniquiladora!',
'⚡ 쐐기 소멸!':'⚡ Extinção da Cunha!',
'🌊충격파!':'🌊Onda de Choque!',
'👿악의+100':'👿Malícia+100',
'💥패링폭발!':'💥Explosão de Aparar!',
'균열 충돌! ':'Colisão de Fissura! ',
'벽 충돌! ':'Colisão com Parede! ',
'소환!':'Invocação!','환영!':'Ilusão!',
'⚡낙뢰!':'⚡Trovão!','⚡빔!':'⚡Feixe!',
'환영술!':'Ilusionismo!','💀소환!':'💀Invocar!',
'🔮주술!':'🔮Maldição!','🩸산란!':'🩸Desovar!',
'💢광폭!':'💢Frenesi!','🕷산란!':'🕷Desovar!',
'❄서리!':'❄Geada!','❄빙결파!':'❄Onda Congelante!',
'💀빙마!':'💀Demônio de Gelo!',
// --- Phase 13: mob actions ---
'돌진!':'Investida!','충격파!':'Onda de choque!','독안개!':'Névoa Tóxica!',
'연타!':'Rajada!','포효!':'Rugido!','강화!':'Reforçar!',
'꼬리!':'Cauda!','은신...':'Furtividade...','기습!':'Emboscada!',
'산란!':'Engendrar!','독가스!':'Gás Tóxico!','소멸...':'Dissolver...',
'강타!':'Golpe Forte!','분비!':'Secretar!','채찍!':'Chicote!',
'출혈!':'Sangramento!','급강하!':'Mergulho!','방출!':'Descarga!',
'충격!':'Impacto!','치유!':'Cura!','의식!':'Ritual!',
'지옥불!':'Fogo Infernal!','끌려감!':'Arrastado!','혀!':'Língua!',
'응시!':'Olhar!','낙하!':'Queda!','핏방울!':'Gota de Sangue!',
'일어남!':'Levantar!','휩쓸기!':'Varrer!','웅크림':'Agachar',
'뼈칼날!':'Lâmina de Osso!','감속!':'Lentidão!','비명!':'Grito!',
'화산탄!':'Tiro Vulcânico!','자폭!':'Autodestruição!','감싸기!':'Envolver!',
'잡기!':'Agarrar!','내리찍기!':'Esmagar!','브레스!':'Sopro!',
'비행!':'Voo!','용암비!':'Chuva de Lava!','물뿜기!':'Jato de Água!',
'빛...':'Luz...','삼키기!':'Engolir!','마비!':'Paralisia!',
'방전!':'Descarga Elétrica!','집게찍기!':'Pinça!','찍기!':'Esmagar!',
'붙잡기!':'Agarrar!','감아올리기!':'Enroscar!','파편!':'Fragmento!',
'할퀴기!':'Arranhão!','기생충!':'Parasita!',
'심연 해방!':'Liberação Abissal!','촉수난타!':'Rajada de Tentáculos!',
'삼지창!':'Tridente!','소용돌이!':'Vórtice!','해일!':'Tsunami!',
'끼걱!':'Rangido!','폭발!':'Explosão!','체인!':'Corrente!',
'갈기!':'Juba!','공포!':'Terror!','흡혈!':'Drenar!',
'베기!':'Corte!','비이이명!!':'Zumbido!!','분열!':'Cisão!',
'3연참!':'Triple Corte!','패링!':'Aparar!',
'...복사...':'...Copiar...','불균형...저주!':'Desequilíbrio...Maldição!',
'저주!':'Maldição!','균형...강화!':'Equilíbrio...Reforçar!',
'심판의 기둥!':'Pilar do Julgamento!','처형 선고!':'Sentença de Morte!',
'고통의 해방!':'Liberação da Dor!','너도 느껴봐라!':'Sinta isso também!',
'대검난무!':'Frenesi de Espadão!','촉수!':'Tentáculo!',
'전방위 빔!':'Feixe Omnidirecional!','회피!':'Esquiva!',
// --- Phase 13: rare mob / merchant ---
'[F] 상점':'[F] Loja','거래 성공!':'Comércio bem-sucedido!',
'악의 부족! (':'Malícia insuficiente! (',
'상인이 떠납니다...':'O mercador está partindo...',
'사슬 해방!':'Liberação de Correntes!','완전 해방!':'Liberação Total!',
'⏪ 시간 되감기!':'⏪ Rebobinar Tempo!','전환!':'Mudar!',
'부활 ':'Ressuscitar ','🌀균열!':'🌀Fissura!','...사라짐':'...Desapareceu',
'낫 베기!':'Corte de Foice!','☠ 죽음의 선고!':'☠ Sentença de Morte!',
'선고 집행...':'Executando sentença...',
'⚡패링!':'⚡Aparar!','경직!':'Rigidez!',
'⚠ 잡혔다!':'⚠ Agarrado!','💥 내던지기!':'💥 Arremesso!',
'💥 소용돌이 폭발!':'💥 Explosão de Vórtice!',
'👻 순간이동!':'👻 Teleporte!','💫 기절! 5초':'💫 Atordoado! 5s',
'찌르기 반격!':'Contra-ataque de Estocada!','💢 폭발!':'💢 Explosão!',
'반격 실패':'Contra-ataque Falhou','탈취 반격!':'Contra-ataque de Roubo!',
'무기 봉인!':'Arma Selada!','냠!':'Nhac!',
// --- Phase 13: stage/room/map ---
'합체!':'Fundido!','출구가 열렸다!':'Saída aberta!',
'보물상자 출현!':'Baú do tesouro apareceu!','출구':'Saída',
'⚠ 문지기가 살아있다!':'⚠ Guardião ainda vivo!',
'⏱ 타임어택 ':'⏱ Contra o Tempo ',
'처치율 ':'Taxa de Abate ',
'무적!':'Invencível!','불사 보호':'Proteção Imortal',
'빙결!':'Congelado!','환영 소멸!':'Ilusão Desvaneceu!',
'부활력 ':'Poder de Ressurreição ',
'✟ 신성력 억제! (':'✟ Supressão Sagrada! (',
'부활 실패 (':'Ressurreição Falhou (',
'⚡순간이동!':'⚡Teleporte!',
'👻 동반부활!':'👻 Co-Ressurreição!',
'✟ 신성력 억제!':'✟ Supressão Sagrada!',
'💀 부활 판정 중...':'💀 Julgando ressurreição...',
'⚔ 문지기 처치!':'⚔ Guardião Derrotado!',
'🚪 보스방 개방!':'🚪 Sala do Boss Aberta!',
'잔해 출현!':'Destroços apareceram!',
'🌀균열 발생!':'🌀Fissura aberta!',
'🔥복수!':'🔥Vingança!','💥폭독혈!':'💥Sangue Pestilento!',
'빙판!':'Chão de Gelo!','❄빙결파!':'❄Onda Congelante!',
'❄최종빙결!':'❄Congelamento Final!','빙마 처치!':'Demônio de Gelo Derrotado!',
'분리!':'Separar!','뼈 파편!':'Fragmento de Osso!',
'태아 처치!':'Feto Derrotado!','지배자 처치!':'Soberano Derrotado!',
'용암!':'Lava!','화룡 처치!':'Dragão de Fogo Derrotado!',
'최후의 비명!':'Grito Final!','산화...':'Oxidar...',
'심판자 처치!':'Juiz Derrotado!','고통의 왕 처치!':'Rei da Dor Derrotado!',
'수역!':'Água!','파편 폭발!':'Explosão de Fragmentos!',
'거대어 처치!':'Leviatã Derrotado!','대사도 처치!':'Alto Apóstolo Derrotado!',
'독웅덩이!':'Poça Venenosa!','화염장판!':'Zona de Fogo!','전기장!':'Campo Elétrico!',
'무기 드롭!':'Arma Dropou!','보물 발견!':'Tesouro Encontrado!',
'상인의 주머니 +':'Bolsa do Mercador +',
'속박의 파편!':'Estilha da Prisão!','시간의 조각!':'Fragmento do Tempo!',
'저주 해제!':'Maldição Removida!','차원의 결정!':'Cristal Dimensional!',
'전설 아이템!':'Item Lendário!','죽음을 이겨냈다!':'Superou a Morte!',
'💥대폭발!':'💥Mega Explosão!','⚡강화!':'⚡Reforçar!',
// --- Phase 13: combat/defense ---
'장비 ':'Equip. ',
'💫 진동!':'💫 Tremor!','❄ 무적!':'❄ Invencível!',
'\u{1F47B} 유령!':'\u{1F47B} Fantasma!',
'집중 해제!':'Foco Cancelado!',
'🕊️ 평화보호 ':'🕊️ Égide ',
'🛡 보호막 ':'🛡 Escudo ',
'🌀 회전보호막 ':'🌀 Escudo Giratório ',
'💥한방캡!':'💥Limite de Hit!',
'⚡쉴드 파괴!':'⚡Escudo Destruído!',
'💀 불굴!':'💀 Indomável!',
'💀 1회부활!':'💀 1 Ressurreição!',
'감시 회수':'Recuperar Sentinela',
'악마화 부활!':'Ressurreição Demoníaca!',
// --- Phase 13: skill panel ---
'기검참':'Corte de Ki','날개치기':'Golpe Asa',
'배정 가능한 스킬 없음':'Sem habilidades disponíveis',
'칼날 없음!':'Sem Lâmina!',
'⚔ 악의사냥!':'⚔ Caçada da Malícia!',
'❄🌪️ 얼음소용돌이!':'❄🌪️ Vórtice de Gelo!',
'🌪️ 폭풍소환!':'🌪️ Invocação de Vórtice!',
'\u{1F9B4} 해골무덤!':'\u{1F9B4} Tumba de Ossos!',
'🌹 붉은꽃!':'🌹 Flor Carmesim!',
'💥 폭산탄!':'💥 Tiro Explosivo!',
'🪡 바늘출!':'🪡 Estouro de Agulhas!',
'⚡ 전격이동!':'⚡ Passo Relâmpago!',
'기둥가시로 흡수됨':'Absorvido pelo espinho do pilar',
'🌿 가시덫!':'🌿 Armadilha de Espinhos!',
'👻 공성유령!':'👻 Fantasma de Cerco!',
'🏹 공성쇠뇌 설치!':'🏹 Besta de Cerco Instalada!',
'👻 유령 허수아비!':'👻 Espantalho Fantasma!',
'💥 폭발 허수아비!':'💥 Espantalho Explosivo!',
'축적!':'Armazenado!','축적 중...':'Armazenando...','만충! 재입력→폭발':'Cheio! Pressione novamente→Explodir',
'폭발! ':'Explodir! ','불발...':'Falha...','뎀':' DANO',
'🩸 폭독칼날!':'🩸 Lâmina Pestilenta!',
'⚡날개치기!':'⚡Golpe de Asa!',
'🗡 칼등날개!':'🗡 Asa-Escudo!',
'🏛️ 악의기둥!':'🏛️ Pilar Sombrio!',
'🌿 기둥가시!':'🌿 Espinho do Pilar!',
'🌋 지옥강타!':'🌋 Golpe Infernal!',
'💥 체간 붕괴!':'💥 Colapso de Postura!',
'💫 포이즈 파괴!':'💫 Postura Destruída!',
'⚡ 뇌전걸음!':'⚡ Passo Fantasma!',
'✟ 구속의 영역!':'✟ Domínio de Prisão!',
'✟ 신성폭발!':'✟ Explosão Sagrada!',
'⛧ 블랙!':'⛧ Estrela Negra!',
'🌋 용암소환!':'🌋 Invocação de Lava!',
'필살기 배정!':'Suprema Designada!',
'완료':'Concluído','합체 가능':'Pode fundir','부족':'Insuficiente',
'SP 부족! (':'SP necessário! (',
'🕊️ 히든: 평화의보호 해금!':'🕊️ Oculto: Égide da Paz desbloqueada!',
'⚡ 히든: 참회 해금!':'⚡ Oculto: Penitência desbloqueada!',
'배정됨':'Designado',
'합체 Lv.':'Fusão Nv.',
'◆ 같은 보석 스킬 습득 시 합체 가능':'◆ Pode fundir ao aprender habilidade da mesma gema',
// --- Phase 13: inventory/forge/storage ---
'▼ 가방 → 창고 보관':'▼ Bolsa → Depósito',
'▲ 창고 → 가방 꺼내기':'▲ Depósito → Bolsa',
'✓ 선택됨':'✓ Selecionado',
'⟨ 입력 대기... ⟩':'⟨ Aguardando... ⟩',
'⟨ 대기 ⟩':'⟨ Aguardar ⟩',
'보조':'Sub',
'키 설정 초기화 (또는 F5 키)':'Resetar Controles (ou tecla F5)',
'아무 키 또는 마우스 버튼을 누르세요 (ESC = 취소)':'Pressione qualquer tecla ou botão do mouse (ESC = cancelar)',
'WebGPU 활성':'WebGPU Ativo','WebGL2 활성':'WebGL2 Ativo',
'측정 중...':'Medindo...',
'불러오기 실패':'Falha ao carregar',
'장착':'Equipar',
'🔒 중요잠금 아이템은 분해 선택 불가!':'🔒 Itens travados não podem ser desmontados!',
'장비 강화 (실패 시 재료만 소멸)':'Melhorar equip. (ao falhar, só materiais são perdidos)',
'강화 보너스 적용':'Bônus de melhoria aplicado',
'강화 실패!':'Melhoria falhou!',
'장착된 장비가 없습니다.':'Sem equipamento equipado.',
'충분':'Suficiente','더 필요':'Precisa mais',
'장비 선택':'Selecionar equipamento','목표치 설정':'Definir objetivo',
'악의 투입':'Investir Malícia','자동 시도':'Tentativa automática',
'목표 강화치':'Objetivo de melhoria',
'예상 필요 악의':'Malícia estimada necessária',
'보유':'Disponível','강화 시작':'Iniciar melhoria',
'위에서 장비를 선택하세요':'Selecione equipamento acima',
'⬆ 물약 강화 (최대 10단)':'⬆ Melhorar poção (máx nível 10)',
'필요':'Necessário',
'악의의 분해로 — 장비를 악의로 갈아버려라':'Forno de Malícia — Triture equipamento em malícia',
'전체 선택':'Selecionar tudo','전체 해제':'Desmarcar tudo',
'희귀 이하':'Raro ou inferior',
'어픽스 리롤!':'Afixo relançado!',
'결정 분해 → 결정 가루':'Decompor Cristal → Pó de Cristal',
'결정 제작 (가루 → 결정)':'Fabricar Cristal (Pó → Cristal)',
'물리':'Físico','영웅':'Heroico','전설':'Lendário',
'무기 타입':'Tipo de Arma','활 타입':'Tipo de Arco',
'보스방':'Sala do Boss','ST 부족':'ST insuficiente',
// --- Phase 14: boss phase labels ---
'💀 광폭화!':'💀 Enraivecido!',
// --- Phase 14: chapter pet dialogue ---
'...따라오는 거 아니야. 같은 방향일 뿐이지.':'...Não tô te seguindo. Só vou na mesma direção.',
'공기가 달라졌어. 더 썩었군.':'O ar mudou. Mais podre.',
'여기부터는 악마 영역이야. ...맘대로 해.':'Daqui pra frente é território demoníaco. ...Faz o que quiser.',
'...이 냄새. 살점이 썩는 냄새야.':'...Esse cheiro. Carne podre.',
'여기 오래 있으면 미쳐. 나도, 너도.':'Fica muito tempo aqui e enlouquece. Eu também, você também.',
'이 길의 끝에 뭐가 있을까. ...알고 싶지도 않아.':'O que tem no fim dessa estrada? ...Nem quero saber.',
'...여기가 끝이야. 돌아갈 길은 없어.':'...Aqui é o fim. Não tem volta.',
// --- Phase 14: idle tips (crow) ---
'작살을 땅에 꽂으면 끌려간다.':'Crava o arpão no chão e é puxado.',
'Shift로 작살 던져봐!':'Tenta lançar o arpão com Shift!',
'패링 성공하면 ST가 회복된다. 공짜 자원이야.':'Aparar com sucesso recupera ST. Recurso grátis.',
'패링 많이 하면 ST 걱정 없어~':'Apara bastante e ST nunca é problema~',
'장비 분해하면 악의를 얻는다. 쓰레기도 자원이야.':'Desmontar equipamento dá Malícia. Até lixo é recurso.',
'TAB 열어서 안 쓰는 장비 분해해!':'Abre TAB e desmonta equip. que não usa!',
'그로기 상태의 적에겐 1.5배 데미지가 들어간다.':'Inimigos atordoados recebem 1.5x de dano.',
'무릎 꿇으면 전력으로 때려!':'Quando ajoelhar, bate com tudo!',
'속성 상성이 있다. 화염은 빙결에 약하고, 암전은 암흑에 약하다.':'Elementos têm vantagem. Fogo é fraco contra Gelo, Raio contra Trevas.',
'무기 속성 바꿔가면서 싸워봐!':'Tenta trocar o elemento da arma durante a luta!',
'빙결된 적은 1.5배 데미지를 받는다.':'Inimigos congelados recebem 1.5x de dano.',
'얼리고 때리는 게 기본이야!':'Congela e bate — é o básico!',
'보스의 빨간 공격은 패링 가능. 보라빛은 회피만.':'Ataques vermelhos do boss podem ser aparados. Arco-íris só desviando.',
'색깔 잘 봐! 빨강은 받아치고 무지개는 피해!':'Presta atenção nas cores! Vermelho apara, arco-íris desvia!',
'VIT를 올리면 최대 HP가 오른다. 죽기 싫으면 찍어.':'VIT aumenta HP máximo. Investe se não quer morrer.',
'STR은 근접, DEX는 활, INT는 마법! 골고루 말고 하나만!':'STR pra corpo a corpo, DEX pra arco, INT pra magia! Foca em um só!',
'E를 꾹 누르면 빔이 나간다. 짧게 누르면 투사체.':'Segura E pro feixe. Toca rápido pro projétil.',
'마법 쓸 때 MP 잘 봐! 빔은 연속으로 깎여!':'Fica de olho no MP com magia! O feixe drena rápido!',
'핵터와 디로이가 아이템을 주워준다. 수거 범위 안이면.':'Hecter e Deroy coletam itens no alcance automaticamente.',
'우리한테 고마워해~ 안 주우면 썩잖아.':'Agradece a gente~ Se não pegar, apodrece.',
'LCK를 올리면 레어 드롭률이 오른다.':'LCK aumenta a taxa de drop raro.',
'운빨 게임이긴 하지~ LCK 올려봐!':'É um jogo de sorte~ Tenta subir LCK!',
'강화하면 공격력이 쭉쭉 올라가! 악의만 있으면 돼!':'Melhoria sobe o ATK rápido! Só precisa de Malícia!',
'강화 확률은 +1에서 99%. 높을수록 떨어진다.':'Chance de melhoria começa em 99% no +1. Cai conforme sobe.',
'실패하면 악의만 날아가~ 장비는 안 부서져!':'Se falhar, só perde Malícia~ Equip. não quebra!',
'대장간에서 장비 제작도 된다. 악의 30000개면 영웅급 이상.':'A forja também fabrica equip. 30000 Malícia pra Heroico+.',
'랜덤이지만 좋은 거 나올 수도 있어!':'É aleatório, mas pode sair algo bom!',
'쉴드는 마법으로, HP는 물리로 깎아야 제대로 먹힌다.':'Escudo precisa de magia, HP precisa de físico pra ser efetivo.',
'반대로 치면 50%만 들어가! 무기 바꿔가면서 싸워!':'Tipo errado faz só 50%! Troca de arma durante a luta!',
'장비에 접두사, 접미사가 붙으면 특수 효과가 생긴다.':'Equip. com prefixo/sufixo ganha efeitos especiais.',
'영웅급 이상 장비에만 붙어! 좋은 거 나오면 강화해!':'Só em equip. Heroico+! Se sair bom, melhora!',
'강화는 장비를 바꿔도 자동 이전된다. 악의만 있으면.':'Melhoria transfere automático pra equip. novo. Só custa Malícia.',
'더 좋은 장비 나오면 바로 장착해! 강화 수치 그대로 옮겨가!':'Se sair equip. melhor, equipa na hora! Melhoria transfere junto!',
// --- Phase 14: additional tutorial lines ---
'패링을 써야 자원을 흡수한다고!':'Você precisa aparar pra absorver recursos!',
'F키 회복의 영역을 써봐. 자원이 차올라.':'Tenta usar Domínio Sagrado na tecla F. Os recursos enchem.',
'적이 근접하면 스페이스키야! 가시덫을 활용해!':'Quando inimigos chegarem perto, Espaço! Usa a Armadilha de Espinhos!',
'기절시켜! 그로기가 터지면 데미지가 1.5배야!':'Atordoa! Atordoado significa 1.5x de dano!',
'1번 대왕치기로 밀어버려!':'Usa tecla 1 Golpe Colossal pra empurrar!',
'무릎 꿇었다.':'Ajoelhou.',
'지금이야! 몰아쳐!!':'Agora! Avança!!',
'스킬 포인트 있어! K 눌러서 스킬 찍어봐!':'Tem pontos de habilidade! Aperta K pra aprender!',
'...힘이 없으면 여기서 끝이야.':'...Sem poder, acaba aqui.',
'...쓸 거 아니면 분해해.':'...Se não vai usar, desmonta.',
'아이템 넘쳐나네~ 우리가 주워줄게!':'Tantos itens~ A gente coleta pra você!',
'악의가 바닥이다.':'Sem Malícia.',
'TAB 열어서 장비 분해해! 쓰레기도 악의가 돼!':'Abre TAB e desmonta equip.! Até lixo vira Malícia!',
'좋은 장비가 있네! G 눌러서 대장간 가봐!':'Equip. bom! Aperta G pra ir à forja!',
'...강화 안 하면 그냥 고철이야.':'...Sem melhoria, é só sucata.',
'...멈추지 마. 여신은 기다리지 않는다.':'...Não para. A deusa não espera.',
'앞으로 가자~ 나도 여기 오래 있기 싫어.':'Vamos em frente~ Eu também não quero ficar aqui.',
'...냄새가 짙다. 큰 놈이 있어.':'...O cheiro tá forte. Tem algo grande aqui.',
'준비됐어? 물약 확인하고!':'Pronto? Confere as poções!',
// --- Phase 14: element names for forge/combat ---
'물리':'Físico','화염':'Fogo',
// --- Phase 15: missing pet dialogue translations (59 lines) ---
// -- Tutorial: firstItem, potionCraft --
'TAB을 눌러. 가방을 열고 장비를 입어야 한다.':'Aperta TAB. Abre a bolsa e equipa.',
'주웠으면 껴야지! TAB!':'Pegou? Equipa! TAB!',
'G. 대장간에서 물약도 제작할 수 있다.':'G. Dá pra fabricar poções na forja também.',
'악의로 물약 만들어! G키야!':'Fabrica poções com Malícia! Tecla G!',
// -- Stun warning --
'기절이야! Ctrl 눌러!':'Atordoado! Aperta Ctrl!',
'Ctrl 유령걸음으로 탈출!':'Ctrl Passo Fantasma pra escapar!',
'Ctrl 얼음보주로 탈출!':'Ctrl Orbe de Gelo pra escapar!',
// -- Parry guide --
'빨간 탄은 우클릭 패링. 무지개는 Q 패링.':'Balas vermelhas: RMB aparar. Arco-íris: Q aparar.',
'나머지는 전부 우클릭 패링 가능해!':'Todo o resto pode ser aparado com RMB!',
'빨강=우클릭, 무지개=Q 패링. 나머진 다 쳐내.':'Vermelho=RMB, Arco-íris=Q aparar. Rebate o resto.',
'무지개는 Q로 패링! 나머지는 전부 우클릭!':'Arco-íris com Q! Todo o resto com RMB!',
// -- Resource / combat --
'빠져! 물약 마시고 안전한 곳에서 회복해.':'Sai fora! Bebe poção e recupera em lugar seguro.',
'자원 없으면 도망가는 게 답이야!':'Sem recursos? Fugir é a resposta!',
'스페이스! 가시덫으로 적 묶어버려!':'Espaço! Prende eles com Armadilha de Espinhos!',
'근접이 너무 많아! 거리 벌려!':'Corpo a corpo demais! Abre distância!',
'...둘러싸이면 끝이야. 빠져나와.':'...Se cercar, acabou. Escapa.',
'1번 대왕치기로 쓸어버려!':'Usa tecla 1 Golpe Colossal pra varrer!',
'그로기 터지면 데미지 1.5배!':'Atordoado ativa 1.5x de dano!',
'회전참이나 광역기로 몰아! 한 놈씩 상대하면 죽어.':'Usa Redemoinho ou AoE! Um por um e você morre.',
'뭉쳐있을 때가 기회야!':'Quando agruparem, é a chance!',
'E로 마력공격을 해봐! 악의 쉴드를 해제할려면 마법 공격을 해야 해!':'Tenta E pra ataque mágico! Precisa de magia pra quebrar escudos de Malícia!',
'쉴드는 마법으로, HP는 물리로. 반대로 치면 데미지 안 들어간다.':'Escudo com magia, HP com físico. Tipo errado não causa dano.',
// -- Skill / passive / stamina hints --
'L키로 스킬 슬롯에 넣어야 쓸 수 있어.':'Aperta L pra colocar habilidades nos slots.',
'C키를 눌러. 패시브 포인트가 쌓여있다.':'Aperta C. Pontos passivos acumularam.',
'C키! 패시브 올리면 진짜 강해져!':'Aperta C! Passivas te deixam muito mais forte!',
'스태미나가 부족하다. 무리하지 마.':'Stamina baixa. Não exagera.',
'ST 없으면 스킬 못 써! 잠깐 빠져!':'Sem ST não usa habilidade! Recua um pouco!',
// -- Item pickup (line 9324) --
'탭 장비창을 열어봐. 아이템을 주워왔어!':'Abre TAB no menu de equip. Pegamos um item!',
'좋은 거 나왔다! TAB 열어서 확인해봐!':'Saiu algo bom! Abre TAB pra conferir!',
// -- Revive tutorial (line 22486) --
'악의에 중독되면 악마가 돼서 부활력이 생긴대. 저 녀석처럼.':'Dizem que vício em Malícia te transforma em demônio com poder de ressurreição. Como aquele ali.',
'혹시 너도...?':'Será que você também...?',
// -- Revive tip (line 30541) --
'데미지가 부족하면 무기류 강화를 해야해!!':'Se o dano tá fraco, melhora as armas!!',
'G키 대장간. 강화 안 하면 여기서 계속 죽어.':'Tecla G forja. Sem melhoria, vai morrer aqui pra sempre.',
// -- Idle nag lines --
'시간이 없어. 움직여.':'Sem tempo. Se mexe.',
'멍하게 서있으면 안 돼!':'Não fica parado aí!',
'...뭘 기다리는 거야?':'...Tá esperando o quê?',
'가자가자! 몬스터가 기다려!':'Vamos vamos! Os monstros estão esperando!',
'여기 오래 있으면 위험해.':'Ficar aqui muito tempo é perigoso.',
'움직여야 해! 가만있으면 둘러싸여!':'Tem que se mover! Parado vão te cercar!',
'쉬는 건 죽고 나서 해.':'Descansa depois de morrer.',
'살아있을 때 쉬면 안 돼!':'Não descansa enquanto tá vivo!',
'적이 몰려오고 있어. 빨리 움직여.':'Inimigos tão chegando. Se mexe rápido.',
'냄새 맡고 올 거야. 빨리!':'Vão sentir o cheiro. Rápido!',
'...아직 살아있는 거 맞지?':'...Cê ainda tá vivo, né?',
'혹시 잠든 거야...?':'Cê dormiu...?',
// -- Chapter entry dialogues --
'...나무가 썩어가고 있어. 여기는 지옥의 입구야.':'...As árvores tão apodrecendo. Aqui é a entrada do inferno.',
'냄새 지독해... 빨리 지나가자.':'O fedor tá horrível... Vamos passar rápido.',
'조심해. 벌레굴이다. 벽이랑 바닥에서 기어나와.':'Cuidado. Covil de vermes. Eles rastejam das paredes e do chão.',
'으으... 벌레 싫어! 밟아버려!':'Eca... Odeio insetos! Pisa neles!',
'...공기가 얼어붙는다. 여기선 화염이 먹힌다.':'...O ar tá congelando. Aqui fogo funciona.',
'추워... 빙결 조심해! 얼면 끝이야.':'Frio... Cuidado com congelamento! Congelou, já era.',
'용암이다. 바닥을 밟으면 타 죽어.':'Lava. Pisa no chão e morre queimado.',
'뜨거워! 여기 왜 이렇게 빨개!':'Tá quente! Por que tudo é tão vermelho aqui!',
'...군단이다. 수가 많아. 광역기 없으면 밀려.':'...É a legião. Muitos deles. Sem AoE você é esmagado.',
'우글우글... 징그러워. 한꺼번에 쓸어!':'Fervilhando... Nojento. Varre tudo de uma vez!',
'사도의 영역이야. 여기 놈들은 머리가 좋아.':'Território do Apóstolo. Esses aqui são espertos.',
'패턴이 복잡해졌어... 집중해!':'Padrões ficaram complexos... Foca!',
'...끝이다. 지옥의 심장부. 살아 돌아가는 건 포기해라.':'...É o fim. O coração do inferno. Desiste de voltar vivo.',
'여기가 마지막이야... 각오해.':'Aqui é o final... Se prepara.',
// -- ZH-only extras --
'방향키 연타':'Apertar setas repetidamente',
'Ctrl 얼음보주로 탈출! 없으면 방향키 연타!':'Ctrl Orbe de Gelo pra escapar! Se não tiver, aperta as setas!',
'석궁 자동발사 (T)':'Besta automática (T)',
'버스트루프 당기기 (H)':'Ciclo explosivo puxar (H)',
'결정 자동합성':'Síntese auto de cristais',
'결정 자동강화':'Melhoria auto de cristais',
'✓ 설정 자동 저장':'✓ Configuração salva automaticamente',
'세팅 프리셋 저장/불러오기':'Salvar/carregar predefinição',
'세팅1 저장':'Salvar Predefinição 1','세팅1':'Predefinição 1',
'세팅2 저장':'Salvar Predefinição 2','세팅2':'Predefinição 2',
'재진단':'Rediagnosticar',
'게임 리셋 (처음부터)':'Reiniciar jogo (do início)',
'캐릭터 선택 (로비)':'Seleção de personagem (Lobby)',
'닫기 [ESC]':'Fechar [ESC]','닫기 [G]':'Fechar [G]','닫기 [V]':'Fechar [V]','닫기 [C]':'Fechar [C]',
'전체화면 (F11)':'Tela cheia (F11)',
'정말 모든 진행을 초기화하시겠습니까?':'Deseja realmente reiniciar todo o progresso?',
'검출 중...':'Detectando...',
'마우스 커서':'Cursor do mouse','그래픽 품질':'Qualidade gráfica','하드웨어 진단':'Diagnóstico de hardware',
'BGM 선택':'Seleção de BGM',
'자동 (스테이지별)':'Automático (por fase)','전체 랜덤':'Tudo aleatório','로비':'Lobby',
'1장 랜덤':'Capítulo 1 aleatório','2장 랜덤':'Capítulo 2 aleatório','3장 랜덤':'Capítulo 3 aleatório',
'4장 랜덤':'Capítulo 4 aleatório','5장 랜덤':'Capítulo 5 aleatório','6장 랜덤':'Capítulo 6 aleatório','7장 랜덤':'Capítulo 7 aleatório',
'보스':'Chefe','최종보스':'Chefe final',
'대장간 랜덤':'Forja aleatória','사망 랜덤':'Morte aleatória','승리 랜덤':'Vitória aleatória',
'지옥 추락 사망 징글':'Jingle de morte na queda do inferno','탈출 성공':'Fuga bem-sucedida',
'── 1장 - 썩은 숲 ──':'── CAP1 - Floresta Apodrecida ──',
'── 2장 - 벌레굴 ──':'── CAP2 - Covil de Vermes ──',
'── 3장 - 얼음굴 ──':'── CAP3 - Caverna de Gelo ──',
'── 4장 - 화염지대 ──':'── CAP4 - Terras Infernais ──',
'── 5장 - 지옥군단 ──':'── CAP5 - Legião Infernal ──',
'── 6장 - 사도마굴 ──':'── CAP6 - Covil do Apóstolo ──',
'── 7장 - 지옥성 ──':'── CAP7 - Cidadela Infernal ──',
'── 공통 ──':'── Comum ──',
'⌨ 조작법':'⌨ Controles','클릭하면 닫힘':'Clique para fechar',
'전투력':'Poder de combate','가방':'Bolsa','결정':'Cristal',
'↕ 정렬':'↕ Ordenar','쓰레기 전체선택':'Selecionar todo lixo','쓰레기 전부 분해':'Desmontar todo lixo',
'창고':'Depósito','스탯 포인트':'Pontos de atributo','능력치 요약':'Resumo de atributos','올 리셋':'Resetar tudo',
'대장간':'Ferraria','스킬':'Habilidades','능력치':'Atributos',
'좌클스킬 (클릭 전환)':'Habilidade clique esq (clique para trocar)','우클스킬 (클릭 전환)':'Habilidade clique dir (clique para trocar)',
'이동스킬 (클릭 전환)':'Habilidade movimento (clique para trocar)','마법스킬 (클릭 전환)':'Habilidade magia (clique para trocar)',
'영역스킬 (클릭 전환)':'Habilidade área (clique para trocar)','피보호막 (클릭 전환)':'Escudo de sangue (clique para trocar)',
'CT스킬 (클릭 전환)':'Habilidade CT (clique para trocar)','[C] 능력치':'[C] Atributos',
'무기 공격':'Ataque com arma','칼등 처내기 (투사체 반사, 홀드 연사)':'Aparar (reflete projéteis, segurar=rajada)',
'연속 처내기':'Aparar contínuo','영역 스킬 (폭풍소환 등)':'Habilidade de área (Turbilhão etc)',
'작살 발사':'Disparar arpão','마법 (탭=투사체, 홀드=빔)':'Magia (toque=projétil, segurar=raio)',
'데빌포스 흡수':'Absorver Força Demoníaca','물약 / 스킬슬롯':'Poções / Slots de habilidade',
'스킬슬롯 5 / 필살기 / CT스킬':'Slot 5 / Suprema / Habilidade CT','스킬 슬롯 배정':'Atribuição de slot',
'✟ 결계의 영역!':'✟ Domínio de Barreira!',
'✟ 물의 영역!':'✟ Domínio da Água!',
'✟ 파쇄의 영역!':'✟ Domínio do Estilhaço!',
'✟ 침식의 영역!':'✟ Domínio da Corrosão!',
'✟ 관통의 영역!':'✟ Domínio da Penetração!',
'✟ 권능의 영역!':'✟ Domínio do Poder!',
'⏳ 시간왜곡!':'⏳ Distorção Temporal!',
'쿨다운!':'Recarga!',
'집중!':'Concentração!',
'\u{1F47B} 유령총!':'\u{1F47B} Pistola Fantasma!',
'💥 유령총 폭발!':'💥 Explosão de Pistola Fantasma!',
'⚡ 전격의창!':'⚡ Lança do Trovão!',
'임계...!':'Critical...!','이 길의 끝에 뭐가 있을까. ...알고 싶지도 않어.':'O que há no fim deste caminho? ...Não quero saber.',
// --- Phase 27 additions ---
// KEY BINDINGS
'위로 이동':'Mover Cima','아래로 이동':'Mover Baixo','왼쪽 이동':'Mover Esquerda','오른쪽 이동':'Mover Direita',
'칼등 처내기 (탭=처내기, 홀드=연사)':'Aparar (toque=aparar, segurar=rajada)',
'영역 스킬':'Habilidade de Área','작살 이동':'Investida de Arpão',
'유령불꽃 켜기/끄기':'Chama Fantasma Ligar/Desligar',
'기동칼날개 자동 켜기/끄기':'Auto Asa Lâmina Encadeada ligar/desligar',
'해상도':'Resolução',
// DEATH / LEVEL-UP / INTRO SCREEN
'빛이 꺼졌다':'A Luz se Apaga',
'누군가는 너를 기다리고 있다':'Alguém te espera',
'다시 일어서라':'Levante-se Novamente',
'로비로 돌아가기':'Voltar ao Lobby',
'☠ 사망 리플레이':'☠ Replay de Morte',
'지옥의 시련을 견뎌냈다':'Você suportou a provação do Inferno',
'계속 전투':'Continuar',
'난이도를 선택하라':'Escolha a Dificuldade',
'나중에 설정(ESC)에서 변경 가능':'Pode alterar em Configurações (ESC)',
// UI
'일괄합성':'Síntese em Massa','일괄강화+합성':'Melhorar+Sintetizar em Massa',
'자원 부족!':'Recursos Insuficientes!',' 뎀':' DAN',
// GAME COMBAT MESSAGES
'합체 폭발!':'Explosão de fusão!',
'MP 부족! (50)':'MP baixo! (50)',
'부활력 고갈!':'Força de ressurreição esgotada!',
'☠ 부활력 고갈!':'☠ Força de ressurreição esgotada!',
'독안개':'Névoa venenosa','뇌전창':'Lança trovão',
'🔥 업화선 시전...':'🔥 Raio do inferno conjurando...',
'💥 기동파괴 그로기!':'💥 Destruição encadeada — grogue!',
'💥 칼등 그로기!':'💥 Aparar — grogue!',
'⚡ 순간이동 준비!':'⚡ Teleporte pronto!',
'👿악의+1000':'👿Malícia+1000',
'💀 내려찍기!':'💀 Esmagar de cima!',
'✟ 신성력 억제! +':'✟ Sagrado suprimido! +',
'✟ 신성력 억제!':'✟ Sagrado suprimido!',
'✟ 신성력 억제! (':'✟ Sagrado suprimido! (',
'💥 지진그로기!':'💥 Grogue sísmico!',
'💥 기폭그로기!':'💥 Grogue detonação!',
'폭발! ×':'Explosão! ×',
'⚫ 기둥강타!':'⚫ Golpe de pilar!',
'💥 대왕치기 그로기!':'💥 Golpe titânico — grogue!',
'💫 미니스턴!':'💫 Mini atordoamento!',
'⚡ 뇌전창!':'⚡ Lança trovão!',
// PET DIALOGUE (crow/cat)
'…절반이다. 정신차려.':'…Metade. Foca.',
'…죽기 직전이다. 한 발만 더.':'…Quase morto. Mais um golpe.',
'…다음 한 방이 마지막이야.':'…O próximo golpe é o último.',
'기절!  ':'Atordoado!  ',
'마력이 빈다. 평타 섞어.':'MP caindo. Mistura ataques normais.',
'그랩이다. 거리를 둬.':'Agarrar. Mantém distância.',
'광역기다. 멀어져.':'AoE. Se afasta.',
'…아파? 당연하지. 여긴 지옥이야.':'…Dói? Claro. Aqui é o inferno.',
'F키도 스킬 슬롯이야!':'A tecla F também é slot de habilidade!',
'L-CTRL로 유령걸음/얼음보주!':'L-CTRL para Passo Fantasma / Orbe de Gelo!',
'V 눌러서 창고에 넣어둬!':'Aperta V pro depósito!',
'ESC로 설정! 난이도/자동물약!':'ESC — configurações! Dificuldade/poção automática!',
'잡몹이다. 먼저 정리해.':'Inimigos comuns. Limpa primeiro.',
'…얼어붙은 놈은 오래 안 간다.':'…Congelado não dura muito.',
'…냄새가 짙다. 큰 놈이 있어.':'…Cheiro forte. Tem algo grande por perto.',
'쉴드는 마법으로, HP는 물리로.':'Escudo com magia, HP com físico.',
'스페이스! 가시덫으로 적 묶어!':'Espaço! Prende inimigos com Armadilha de Espinhos!',
'근접 너무 많아! 거리 벌려!':'Muitos de perto! Abre espaço!',
'회전참이나 광역기로 몰아!':'Usa Corte Giratório ou AoE!',
'F 눌러! 회복의 영역 깔아!':'Aperta F! Coloca o Domínio Sagrado!',
'F키 회복의 영역을 써봐.':'Tenta a tecla F — Domínio Sagrado.',
'빠져! 물약 마시고 회복해.':'Recua! Bebe uma poção e recupera.',
'쉬프트! 사슬기동은 이동기야!':'Shift! Dash encadeado é deslocamento!',
'스킬포인트 쌓였어! K 눌러!':'Pontos de habilidade acumularam! Aperta K!',
'스킬 포인트 있어! K!':'Tem pontos de habilidade! K!',
'C키. 패시브 포인트가 쌓여있다.':'Tecla C. Pontos passivos acumulados.',
'…쓸 거 아니면 분해해.':'…Desmontar o que não vai usar.',
'…강화 안 하면 그냥 고철이야.':'…Sem melhorar é só sucata.',
'빨간 탄은 우클릭. 무지개는 Q.':'Vermelho — clique direito. Arco-íris — Q.',
'빨강=우클릭, 무지개=Q.':'Vermelho=clique direito, arco-íris=Q.',
'…멈추지 마. 여신은 기다리지 않는다.':'…Não para. A deusa não espera.',
'패턴이 바뀐다. 거리를 둬.':'O padrão está mudando. Mantém distância.',
'미쳐가고 있어. 광폭화다.':'Tá enlouquecendo. Berserk.',
'마지막이야! 끝장내!':'Última fase! Finaliza!',
'…끝났다. 다음으로.':'…Acabou. Próximo.',
'다 잡았다! 포탈 어딨어?':'Todos eliminados! Cadê o portal?',
'근육으로 만든 빌드군. 베고 부숴.':'Build de força. Corta e quebra.',
'활을 쥐었군. 거리를 둬.':'Arco em mãos. Mantém distância.',
'마법사군. MP 관리부터 배워라.':'Mago. Aprende a gerenciar MP primeiro.',
'운에 기댄 빌드군. …드롭은 좋겠어.':'Build de sorte. ...Pelo menos os drops serão bons.',
'…VIT가 너무 낮아. 한 방에 죽는다.':'…VIT muito baixo. Morre de um golpe.',
'다 찍으면 다 약해진다. 하나만 골라.':'Maxar tudo e fica fraco em tudo. Escolhe um.',
'…3단. 적이 강해져. 정신 차려.':'…Estágio 3. Inimigos mais fortes. Foca.',
'5단이다. …너도 강해졌단 뜻이야.':'Estágio 5. ...Significa que você também ficou mais forte.',
'…7단. 아직 살아있단 게 신기하군.':'…Estágio 7. Ainda vivo. Surpreendente.',
'10단. …너는 이제 인간이 아니야.':'Estágio 10. ...Você não é mais humano.',
'…일반으로 내려왔군. 가끔은 쉬어가야지.':'…Voltou pro Normal. Às vezes precisa descansar.',
'…이게 진짜 패링이야.':'…Isso é um aparar de verdade.',
'…피가 묻기 시작했군.':'…O sangue começa a escorrer.',
'100. 너는 인간이 아니야.':'100. Você não é humano.',
'…피 흘리며 베는군.':'…Cortando através do sangue.',
'빨간콩이 푸르게 변했다. 그게 너의 무기야.':'O núcleo vermelho ficou azul. Essa é a sua arma.',
'무지개를 받아쳤군. 그건 진짜 어렵다.':'Aparou um arco-íris. Isso é genuinamente difícil.',
'…너무 빨라. 닿기 직전에 눌러.':'…Rápido demais. Aperta bem antes do contato.',
'악의가 가득 찼다. 풀어내.':'Malícia está cheia. Libera.',
'작살이 살을 뚫었어. 끌고 와.':'O arpão perfurou a carne. Puxa.',
'…풀차지군. 멀리 던져버려.':'…Carga total. Joga longe.',
'…빈틈을 그대로 빠져나갔다.':'…Passou direto pela brecha.',
'…일반 잡몹이 아니야. 모디파이어 붙었군.':'…Não é inimigo comum. Tem modificador.',
'엘리트 하나 처리.':'Um elite eliminado.',
'…큰 놈이다. 일반 잡몹 정리부터.':'…Grande. Limpa os comuns primeiro.',
'미니보스 처리. 다음 길로.':'Mini-boss eliminado. Próximo caminho.',
'한 번에 다섯. 깔끔해.':'Cinco de uma vez. Limpo.',
'100강. 이제 뭔가 다르게 보이는군.':'+100. As coisas parecem diferentes agora.',
'…운이 없는 날이야.':'…Dia sem sorte.',
'…전설이다. 이런 건 처음 본다.':'…Lendário. Nunca vi um desses.',
'…죽었다 살아났네. 여신은 너를 포기 안 했어.':'…Morreu e voltou. A deusa não desistiu de você.',
'…또야? 패턴 좀 외워!':'…De novo? Aprende o padrão!',
'…한 번도 안 죽고. 그건 진짜 실력이야.':'…Nunca morreu. Isso é habilidade real.',
'…ACT1을 끝냋다. 진짜 시작은 여기서부터야.':'…ATO1 concluído. O começo de verdade é aqui.',
'모든 보스를 무너뜨렸다. 너는 지옥의 일부야.':'Todos os chefes caíram. Você é parte do inferno agora.',
'…30초. 너 진짜 미쳤구나.':'…30 segundos. Você é genuinamente insano.',
'…빠르군. 효율적이야.':'…Rápido. Eficiente.',
'신기록이다.':'Novo recorde.',
'탭 장비창을 열어봐.':'Abre o equipamento com TAB.',
'데미지 부족하면 무기 강화!':'Pouco dano? Melhora sua arma!',
// --- Loading screen ---
'불러오는 중...':'Carregando...',
'로딩중...':'Carregando...',
'맵과 몬스터 불러오는 중...':'Carregando mapa e monstros...',
'기본 데이터 준비 중...':'Preparando dados básicos...',
'저장 데이터 불러오는 중...':'Carregando dados salvos...',
'몬스터 스킨 로딩...':'Carregando skins de monstros...',
'맵과 몬스터 생성 중...':'Gerando mapa e monstros...',
'맵 에셋 로딩...':'Carregando recursos do mapa...',
'맵 환경 준비 중...':'Preparando ambiente do mapa...',
'주변 청크 준비 중...':'Preparando chunks próximos...',
'맵 캐시 생성 중...':'Construindo cache do mapa...',
'미니맵 빌드 중...':'Construindo minimapa...',
// Phase 28
' 으로 탈출!':' para escapar!',
'100명?! 미쳤어!':'100 mortes?! Que loucura!',
'10단 최고난이도! 너 진짜 광기야!':'Dificuldade 10 no máximo! Você é completamente louco!',
'1분 안에 클리어! 빠르네!':'Fase concluída em 1 min! Que rápido!',
'30초!! 스피드런 가능해!':'30 segundos!! Potencial de speedrun!',
'3단! 보상도 좋아지지만 죽기 쉬워!':'Dif 3! Melhores recompensas mas mais fácil morrer!',
'50명! 학살자야!':'50 mortes! Você é um massacrador!',
'5단!! 진짜 게이머 인증!':'Dif 5!! Gamer de verdade certificado!',
'7단!! 다른 사람들 이 정도 못 와!':'Dif 7!! Os outros não chegam tão longe!',
'ACT1 완주! 우리가 진짜 해냈어!':'ACT1 completo! A gente realmente conseguiu!',
'Ctrl 얼음보주로 탈출하라.':'Ctrl — escape com o Orbe de Gelo.',
'Ctrl 유령걸음으로 탈출하라.':'Ctrl — escape com o Passo Fantasma.',
'C키! 패시브 강해져!':'Tecla C! As passivas ficam mais fortes!',
'DEX 빌드! 거리에서 패고, 추적탄 좋아!':'Build DEX! Ataque à distância, tiros rastreadores são ótimos!',
'E로 마력공격을 해봐!':'Tente o ataque mágico com E!',
'G 눌러서 대장간 가봐!':'Pressione G para visitar a forja!',
'G키 대장간. 강화 안 하면 계속 죽어.':'G — forja. Sem melhorias, vai continuar morrendo.',
'HP 70%! 조심해!':'HP 70%! Cuidado!',
'INT 빌드! 빔이랑 폭발 마법! MP 잘 봐!':'Build INT! Raios e magia explosiva! Cuide do seu MP!',
'LCK 높아! 레어 드롭률 미친 거 알지?':'LCK alto! Você sabe que as taxas de drop são loucas, né?',
'L로 어디에 뭘 넣을지 골라!':'Pressione L para escolher o que vai em cada slot!',
'MP 부족! 평타로 패면서 회복해!':'MP baixo! Acerte com básicos para recuperar!',
'ST 없으면 스킬 못 써!':'Sem ST, sem habilidades!',
'STR 빌드! 회전참, 회오리, 광역기 추천!':'Build STR! Giro cortante, redemoinho, AoE recomendado!',
'VIT 좀 찍어! HP 너무 적어!':'Adicione um pouco de VIT! O HP está baixo demais!',
'Z 누르면 대박! 쿨타임 길어!':'Pressione Z para o golpe forte! Mas o cooldown é longo!',
'…고기 냄새. 싫진 않네.':'…Cheiro de sangue. Não é desagradável.',
'…둘러싸이면 끝이야.':'…Seja cercado e acabou.',
'…말은 못해.':'…Não consigo falar.',
'…버리기 아까운 건 창고에.':'…O que vale guardar vai para o armazém.',
'…빈틈을 노려.':'…Observe as aberturas.',
'…설정을 확인해.':'…Verifique suas configurações.',
'…슬롯을 채워. 빈 손은 죽음이다.':'…Preencha seus slots. Mãos vazias significam morte.',
'…아직 살아있네. 좌클릭으로 저것들 쳐봐.':'…Ainda vivo. Tente acertá-los com o clique esquerdo.',
'…운이 좋았을 뿐이야. 아마.':'…Só tive sorte. Provavelmente.',
'…치는 건 할 줄 아네. 피하는 건?':'…Sabe como acertar. E esquivar?',
'…힘을 골라라. 전부 가질 순 없다.':'…Escolha sua força. Não dá para ter tudo.',
'골고루 안 돼! 하나로 밀어!':'Não distribua atributos! Aposte em um!',
'그로기 터지면 1.5배!':'Grogue = 1,5x de dano!',
'길이 열렸다.':'O caminho está aberto.',
'나머진 전부 우클릭 패링 가능!':'Tudo mais pode ser aparado com o clique direito!',
'나머진 전부 우클릭!':'Tudo mais — clique direito!',
'다섯 번 연속! 내가 본 인간 중 최고!':'Cinco seguidos! O melhor humano que já vi!',
'다음엔 죽지 마!':'Não morra na próxima vez!',
'더블탭 전격이동으로 탈출하라.':'Toque duplo para escapar com o dash.',
'소환수 왔어! 먼저 처리해야 해!':'Invocações chegando! Elimine-as primeiro!',
'스킬 없으면 방향키 연타뿐이야.':'Sem habilidade? Só spam nas teclas de direção.',
'신기록!! 스트리머한테 보내!':'Novo recorde!! Manda para um streamer!',
'아이템 넘쳐! 우리가 주워줄게!':'Bolsa cheia! Nós vamos pegar as coisas para você!',
'안 죽고 깼어! 진짜 천재 맞네!':'Completou sem morrer! Gênio de verdade!',
'앞으로 가자~':'Vamos em frente~',
'우리가 해냈어! 다음 챕터 가자!':'Conseguimos! Para o próximo capítulo!',
'일반 모드! 편하게 즐기자!':'Modo normal! Vamos aproveitar tranquilos!',
'자원이 반이다. F키로 회복해.':'Recursos na metade. Pressione F para recuperar.',
'잡힌다! 옆으로 빠져!':'Sendo agarrado! Mova para o lado!',
'장비 분해해! 쓰레기도 악의!':'Desmonte equipamentos! Até lixo dá malícia!',
'전부 다 잡았어! 우리가 지옥의 왕이야!':'Pegamos todos! Somos os reis do inferno!',
'좋은 거 나왔다! TAB!':'Ótimo loot caiu! TAB!',
'죽기 직전에 죽이다니! 멋져!':'Matar bem antes de morrer! Incrível!',
'체력 반 남았어! 물약 마실 타이밍!':'Metade do HP! Hora de tomar uma poção!',
'큰 거 온다! 도망쳐!':'Grande ataque chegando! Corra!',
'패링으로 돌려주고, Q 보호막도 써!':'Apare para refletir, e use também o escudo Q!',
'패턴이 빨라졌어!':'Os padrões ficaram mais rápidos!',
'한 대만 맞아도 죽어! 패링이든 회피든!!':'Um golpe e você morre! Apare ou esquive!!',
'한 방이면 죽어! 도망쳐!!':'Um golpe mata! Corra!!',
'화염엔 빙결! 암전엔 암흑!':'Fogo → gelo! Vazio → sombra!',
'👻 유령총!':'👻 Pistola Fantasma!',
'기절! ':'Atordoado! ',
'…ACT1을 끝냈다. 진짜 시작은 여기서부터야.':'…ACT1 concluído. O verdadeiro começo começa aqui.',
'⏳⚡ 시간걸음!':'⏳⚡ Passo Temporal!',
'블룸 효과':'Efeito Bloom',
'잔상 트레일':'Rastro residual',
'슬래시 이펙트':'Efeito de corte',
'후처리 효과':'Efeitos de pós-processamento',
'사망 이펙트':'Efeito de morte',
'동적 조명':'Iluminação dinâmica',
'횃불 조명 (어둠)':'Luz de tocha (escuridão)',
'앰비언트 파티클':'Partículas ambiente',
'안개 효과':'Efeito de névoa',
'필름 그레인':'Grão de filme',
'캐릭터 외곽선':'Contorno do personagem',
'리롤':'Relançar',
'물약':'Poção',
'으로 탈출!':'para escapar!',
'Shift 작살':'Shift Arpão',
'더블탭 전격이동':'Toque duplo — Avanço relâmpago',
'Ctrl 유령걸음':'Ctrl Passo fantasma',
'Ctrl 얼음보주':'Ctrl Orbe de gelo',
'🔴화염→빙결 2배 | 🔵빙결→화염 2배 | ⚪물리=중립 | 악마 처치 시 악의 영혼 드롭':'🔴Fogo→Gelo 2× | 🔵Gelo→Fogo 2× | ⚪Fís=Neutro | Mate demônios por almas de malícia',
  '미구현':'N/A',
  '스탯 총량':'Estatísticas totais',
  '장비':'equip.',
  '공속':'vel.atq',
  '크리':'crít',
  '크리뎀':'dano crít',
  '근성':'Resistência',
  '종합 지표':'Visão geral',
  '근접 DPS':'DPS corpo',
  '공격력×공속×크리':'ATQ×Vel×Crít',
  '활 DPS':'DPS arco',
  '마법 DPS':'DPS magia',
  '유효 HP (EHP)':'HP efetivo (EHP)',
  '쉴드':'Escudo',
  '장비 파워':'Poder equip.',
  '근접 공격력':'ATQ corpo',
  '기본':'base',
  '무기':'arma',
  '패시브':'passivo',
  '활 공격력':'ATQ arco',
  '정밀':'Prec',
  '마법 공격력':'ATQ magia',
  '왕관':'coroa',
  '마력':'Arcano',
  '공격속도':'Vel. ataque',
  '크리티컬':'Crítico',
  '데미지':'Dano',
  '확률':'Prob.',
  '어픽스':'afixo',
  '레거시':'legado',
  '추가뎀':'dano extra',
  '패링 카운터뎀':'Dano contragolpe',
  '우클공속':'Vel. clique dir',
  '무지개탄DR':'DR arco-íris',
  '포이즈파괴':'Quebrar Poise',
  '방어관통':'Penetração armadura',
  '관통력':'Perfuração',
  '속성':'Elementos',
  '무기속성':'Elem. arma',
  '독':'Veneno',
  '초':'s',
  '암흑저주':'Maldição sombria',
  '원소집중':'Foco elem.',
  '원소전환':'Conv. elem.',
  '방어':'Defesa',
  '물리방어':'DEF física',
  '감소':'red',
  '캡':'limite',
  '장갑':'luvas',
  '바지':'calça',
  '속성방어':'DEF elem.',
  '목걸이':'colar',
  '반지1':'anel1',
  '반지2':'anel2',
  '반사':'Reflexo',
  '가시':'Espinhos',
  '배리어':'Barreira',
  '보호막 흡수':'Absorção escudo',
  '속성 저항':'Resistência elem',
  'CC저항':'Resistência CC',
  '생존':'Sobrevivência',
  '장비HP':'HP equip.',
  '임플':'Impl.',
  '에너지쉴드':'Escudo de energia',
  '리젠':'Regen',
  '스태미나':'Stamina',
  '성장':'Crescimento',
  'MP%어픽스':'Afixo MP%',
  '이동속도':'Vel. movimento',
  '한방캡':'Limite de um golpe',
  '최대HP의33%':'33% HP máx',
  '비용/효율':'Custo/Efic',
  '근접ST':'ST corpo',
  '활ST':'ST arco',
  '마법MP':'MP magia',
  '작살사거리':'Alcance arpão',
  '기동게이지':'Barra impulso',
  '쿨감':'CDR',
  '쇠뇌뎀':'Dano besta',
  '쇠뇌공속':'Vel besta',
  '기타':'Misc',
  '물약쿨':'CD poção',
  '회복+':'Recuperação+',
  '드롭':'Drops',
  '경험치+':'EXP+',
  '골드+':'Ouro+',
  '기동:칼날개':'Impulso:Lâmina',
  '기동:전폭':'Impulso:Ataque',
  '기동:기습':'Impulso:Emboscada',
  '충전스킬':'Habilidade carga',
  '사슬게이지':'Barra corrente',
  '특수 효과':'Efeitos especiais',
  '처치뎀+':'Dano matar+',
  '위기뎀+':'Dano crise+',
  '피격반격':'Contragolpe ao acertar',
  '풍요(적HP≥70%뎀+)':'Abundância(HP≥70%+)',
  '약자포식(적HP≤30%뎀+)':'Predador(HP≤30%+)',
  '패링폭발':'Explosão parada',
  '체간파괴+':'Quebrar Poise+',
  '콤보뎀+':'Dano combo+',
  '작살뎀+':'Dano arpão+',
  '스킬뎀+':'Dano habilidade+',
  '패리+':'Aparar+',
  '체인':'Corrente',
  '정화':'Purga',
  '회':'×',
  '불굴':'Tenacidade',
  '신성력':'Poder sagrado',
  '악마력(부활력)':'Força demônio',
  '자연':'Natureza',
  '악마성':'Demonicidade',
  '인간성':'Humanidade',
  '전투 통계':'Estatísticas combate',
  '핵터':'Hecter',
'디로이':'Deroy',
'물리 ATK +1, MAX HP +5, HP리젠 +0.002':'ATK físico +1, HP MÁX +5, Regen HP +0.002',
'석궁 ATK +1, 공격속도 +0.05%, MAX ST +2, ST리젠 +0.005, 회피 +0.05%':'ATK arco +1, Vel. ataque +0.05%, ST MÁX +2, Regen ST +0.005, Esquiva +0.05%',
'마법 ATK +1, MAX MP +2, MP리젠 +0.005, MAX 쉴드 +5':'ATK mágico +1, MP MÁX +2, Regen MP +0.005, Escudo MÁX +5',
'크리확률 +0.025%, 크리뎀 +0.2%, 드롭률 +0.15%':'Chance crítico +0.025%, Dano crítico +0.2%, Taxa de drop +0.15%',
'근접뎀 +15%, ST비용 -4%/lv (최대-40%)':'Dano corpo a corpo +15%, Custo ST -4%/nv (máx -40%)',
'작살 사거리 +2%/lv, 기동게이지 회복 +3%/lv':'Alcance arpão +2%/nv, Recuperação medidor +3%/nv',
'카운터뎀 +50%/lv, 우클릭 공속 +10%/lv, 무지개탄 피해감소 +10%/lv (최대50%)':'Dano contador +50%/nv, Vel. atq. clique dir. +10%/nv, Redução dano bala arco-íris +10%/nv (máx 50%)',
'마법뎀 +15%, MP비용 -4%, 시전속도 +8%/lv':'Dano mágico +15%, Custo MP -4%, Vel. lançamento +8%/nv',
'투사체뎀 +15%, 공속 +10%, 사거리 +8%, ST비용 -4%/lv':'Dano projétil +15%, Vel. atq. +10%, Alcance +8%, Custo ST -4%/nv',
'보호막 흡수 +2%/lv (기본70→최대90%), 보호막 중 HP리젠 +0.1%/lv':'Absorção escudo +2%/nv (base 70→máx 90%), Regen HP com escudo +0.1%/nv',
'HP/ST리젠 +3%/lv, 물약쿨 -3%/lv':'Regen HP/ST +3%/nv, Recarga poção -3%/nv',
'크리률 +2%, 크리뎀 +8%/lv':'Chance crítico +2%, Dano crítico +8%/nv',
'아이템 드롭률 +8%/lv':'Taxa de drop +8%/nv',
'투사체 관통률 +5%/lv, 관통횟수 +1/lv, 관통뎀감소 완화':'Taxa penetração projétil +5%/nv, Contagem penetração +1/nv, Redução queda dano penetração',
'MP리젠 +3%/lv, 쉴드리젠 +3%/lv, 쉴드쿨 -3%/lv':'Regen MP +3%/nv, Regen escudo +3%/nv, Recarga escudo -3%/nv',
'자동쇠뇌 뎀 +5%/lv, 공속 +5%/lv':'Dano besta auto +5%/nv, Vel. atq. +5%/nv',
'물리뎀 +15%/lv, HP +3%/lv, ST소모 -5%/lv':'Dano físico +15%/nv, HP +3%/nv, Consumo ST -5%/nv',
'적에게 약점노출 디버프. 직접 공격 시 스택+1, 스택당 피격뎀 +3%. 최대 Lv×5 중첩 (1렙5, 10렙50). 초당 20% 감소, 5초 미피격 시 리셋. DOT/장판 제외':'Debuff exposição fraqueza em inimigos. Ataque direto +1 pilha, +3% dano recebido/pilha. Máx Lv×5 (Nv1=5, Nv10=50). -20%/s, reset após 5s sem ataque. DOT excluído',
'물리→쉴드 패널티 관통 +5%/lv (기본10%, 10lv=60%)':'Penetração penalidade físico→escudo +5%/nv (base 10%, nv10=60%)',
'마법→HP 패널티 관통 +5%/lv (기본10%, 10lv=60%)':'Penetração penalidade magia→HP +5%/nv (base 10%, nv10=60%)',
'적 HP 70%↑: 뎀+20%/lv, 회복력+5%/lv (합연산)':'HP inimigo ≥70%: Dano+20%/nv, Recuperação+5%/nv (aditivo)',
'적HP 30%↓: 뎀+20%/lv. 내HP 30%↓: 회복력+10%/lv, 이속+5%/lv (합연산)':'HP inimigo ≤30%: Dano+20%/nv. Meu HP ≤30%: Recup.+10%/nv, Vel.movim.+5%/nv (aditivo)',
'DOT 틱뎀 +15%/lv, DOT 지속시간 +10%/lv, DOT 축적률 +5%/lv':'Dano DOT +15%/nv, Duração DOT +10%/nv, Taxa acumul. DOT +5%/nv',
'MP +50/lv, MP회복 +1%/lv':'MP +50/nv, Regen MP +1%/nv',
'ST +50/lv, ST회복 +1%/lv':'ST +50/nv, Regen ST +1%/nv',
'악의 드롭 +8%/lv':'Drop malícia +8%/nv',
'HP +300/lv':'HP +300/nv',
'DEF +20/lv':'DEF +20/nv',
'엘리트/보스 추가뎀 +10%/lv':'Dano adicional elite/chefe +10%/nv',
'부활력 -10/lv, 전체 데미지 +5%/lv, HP/MP/ST +100/lv':'Poder de ressurreição -10/nv, Dano total +5%/nv, HP/MP/ST +100/nv',
'부활확률 +2%/lv, 부활HP +5%/lv, 부활쿨 -30초/lv':'Prob. ressurreição +2%/nv, HP ressurreição +5%/nv, Recarga ressurreição -30s/nv',
'스테이지':'Fase',
'💪 힘 (STR)':'💪 STR',
'🏹 민첩 (DEX)':'🏹 DEX',
'🔮 지능 (INT)':'🔮 INT',
'🍀 행운 (LCK)':'🍀 LCK',
'⚔️ 맹공':'⚔️ Acometida',
'🔱 돌파':'🔱 Ruptura',
'⚡ 반격':'⚡ Represália',
'🔮 마력폭주':'🔮 Surto Arcano',
'🎯 정밀사격':'🎯 Disparo Preciso',
'🛡 수호신':'🛡 Espírito Guardião',
'💚 회복력':'💚 Regeneração',
'💥 급소':'💥 Golpe Vital',
'🎁 약탈':'🎁 Saque',
'🔱 관통':'🔱 Penetração',
'💠 마력회복':'💠 Recuperação de Mana',
'🏹 쇠뇌력':'🏹 Maestria de Besta',
'⚔ 광전사':'⚔ Berserker',
'🎯 추적자':'🎯 Rastreador',
'🗡 물리관통':'🗡 Pen. Física',
'🔮 마법관통':'🔮 Pen. Mágica',
'🌿 풍요':'🌿 Abundância',
'🐺 약자포식':'🐺 Predador',
'☠ 침식':'☠ Corrosão',
'💎 마력그릇':'💎 Recipiente de Mana',
'💪 힘의그릇':'💪 Recipiente de Vigor',
'👿 악의중독':'👿 Viciado em Malícia',
'❤️ 강인':'❤️ Tenacidade',
'🛡 철벽':'🛡 Fortaleza',
'🎯 사냥꾼':'🎯 Caçador',
'✦ 인간성':'✦ Humanidade',
'☠ 악마성':'☠ Demonicidade',
'1. 악의폭풍':'1. Tempestade de Malícia',
'2. 칼날 계열':'2. Habilidades de Lâmina',
'3. 역병 확장':'3. Expansão de Praga',
'4. 이동스킬 마스터':'4. Mestre do Movimento',
'5. 사슬 확장':'5. Expansão de Corrente',
'6. 💀 필살기 선택':'6. 💀 Escolha Suprema',
'7. 멸살+만화+원소+전격이동':'7. Raio+Rajada+Elem+Avanço',
'8. 회전참+기폭+대왕':'8. Redemoinho+Det+Colossal',
'9. 방패 합체':'9. Fusão Escudo',
'10. 해골무덤+악의폭풍':'10. Tumba+Tempestade',
'11. 폭풍소환+얼음보주':'11. Vórtice+Orbe de Gelo',
'12. 뇌전걸음':'12. Passo Fantasma',
'13. 신성 영역':'13. Domínio Sagrado',
'14. 6단합체: 폭풍빔':'14. Fusão 6: Raio Vórtice',
'15. 신성+빙결':'15. Sagrado+Gelo',
'16. 암흑+가시+대왕2':'16. Trevas+Espinhos+Colossal 2',
'17. 사슬 최종':'17. Corrente Final',
'⚡ 이동스킬':'⚡ Movimento',
'⚔️ 물리':'⚔️ Físico',
'🛡️ 방어':'🛡️ Defesa',
'🔮 마법':'🔮 Magia',
'🏹 석궁/투사체':'🏹 Besta/Projétil',
'⚙️ 영역':'⚙️ Área',
'💀 필살기':'💀 Suprema',
'⭐ 추천':'⭐ Recomendar',
'⚔ 공격':'⚔ Ataque',
'🛡 방어':'🛡 Defesa',
'⚙ 특수':'⚙ Especial',
  '👻 공성허수아비!':'👻 Espantalho de Cerco!',
  '💥 공성허수아비 폭발!':'💥 Explosão do Espantalho de Cerco!',
};

const _PTBR_PFX={'녹슨':'Enferrujado','강철':'Aço','흑요석':'Obsidiana','미스릴':'Mithril','심판의':'do Julgamento','천벌의':'da Ira Divina','파멸의':'Ruinoso',
'불꽃':'Chama','화염':'Fogo','염화':'Fogo Infernal','지옥불':'Chama Infernal','지옥화':'Chama Infernal','지옥':'Inferno','멸화의':'Aniquilante',
'냉기':'Gélido','빙결':'Congelado','빙하':'Glacial','서리의':'da Geada','서리':'Geada','영겁빙':'Gelo Eterno',
'그림자':'Sombra','암흑':'Trevas','심연':'Abissal','나락의':'do Limbo','나락':'Limbo','무간의':'do Vazio',
'전기':'Faísca','낙뢰':'Trovão','암전':'Raio','뇌신의':'do Deus do Trovão','뇌신':'Deus do Trovão','만뢰의':'Miríade de Trovões',
'축복':'Abençoado','성광':'Luz Sagrada','신성':'Sagrado','천사의':'Angélico','신벌의':'do Castigo Divino',
'낡은':'Gasto','천':'Pano','가죽':'Couro','강철사':'Fio de Aço','은':'Prata','은사':'Fio de Prata','화염의':'Inferno','빙결의':'Congelado','암흑의':'Amaldiçoado','암전의':'do Raio'};
const _PTBR_BASE={'대검':'Espadão','석궁':'Besta','연사석궁':'Repetidora','마력석궁':'Besta Arcana',
'견갑':'Guarda','대견갑':'Grande Escudo','전투화':'Botas de Combate','갑옷':'Armadura','갑주':'Armadura',
'왕관':'coroa','장갑':'luvas','건틀릿':'Manoplas','바지':'calça','각반':'Caneleiras',
'허리띠':'Cinto','벨트':'Cinto','부적':'Talismã','목걸이':'colar','반지':'Anel',
'망토':'Capa','팔찌':'Bracelete','귀걸이':'Brinco'};
