// 지옥의 길 — Italiano (it)
const _IT={
'잘못 때렸군. 실수야.':"Colpo mancato. A vuoto.",
'타이밍이야. 탄이 닿기 직전에 눌러.':"È tutta questione di tempismo. Colpisci un attimo prima che ti raggiunga.",
// --- v7 신규 펫/UI 8종 (2026-07-05) ---
'다섯 번째군. 이번엔 바뀐 게 있어야지.':"La quinta volta. Stavolta qualcosa dovrebbe cambiare.",
'또 와?! 이번엔 진짜 패턴 외웠어!':"Ancora?! Stavolta il pattern me lo sono imparato davvero!",
'…전설을 잡았다. 보상도 전설이겠지.':"…Hai abbattuto una leggenda. Anche la ricompensa sarà leggendaria.",
'전설급 잡았어!! 드롭 확인해!':"Hai steso un leggendario!! Controlla il drop!",
'무릎 꿇었다. 지금 처형해. X.':"È in ginocchio. Giustizialo ora. X.",
'처형각이야!! X 눌러!!':"Momento dell'esecuzione!! Premi X!!",
'⌨ 키보드·마우스':"⌨ Tastiera e mouse",
'🎮 게임패드':"🎮 Controller",
'💫 암전폭류':'💫 Ondata di Fulmini',
'⚡ 암전나선':'⚡ Elica Fulmine',
'🌋 지진폭풍':'🌋 Tempesta Sismica',
'🔥 회전기폭':'🔥 Turbine-Det',
'⚔ 기동:섬멸':'⚔ Spinta:Annientamento',
'⚔ 기동:칼날개':'⚔ Spinta:Lama',
'⚡ 기동:전폭':'⚡ Spinta:Colpo',
'🌀 기동:파쇄':'🌀 Spinta:Frantumazione',
'🌀 기동:기습':'🌀 Spinta:Imboscata',
'💫 →좌클 통합':'💫 →Unito al clic sinistro',
'⚡ →좌클 통합':'⚡ →Unito al clic sinistro',
'🎯 추적암전':'🎯 Fulmine Tracciante',
'☆ 만화광선':'☆ Raggio Luminescente',
'⏳⚡ 시간걸음':'⏳⚡ Passo Temporale',
'SSAA 슈퍼샘플':'SSAA Supercampionamento',
'끄기 (1x)':'Disattivato (1x)',
'커서 크기':'Dimensione cursore',
'다크 판타지 전사':'Guerriero dark fantasy',
'거대검+검은 갑옷':'Spadone + Armatura nera',
'…지옥문이 열렸다. 안에서 그것이 기다리고 있어.':"...La Porta dell'Inferno è aperta. Ti aspetta dentro.",
'문 열렸어! 이제 보스 잡으러 가자!':"La porta è aperta! Andiamo a uccidere il boss!",
'\u26e7 시전...':'⛧ Lancio...',
'…죽기 직전이다. 패링해. 피를 채워.':'...Quasi morto. Para. Recupera HP.',
'⚔🐍 독사해방!':'⚔🐍 Liberazione Vipera!',
'⚠패링 실패!':'⚠Parata fallita!',
'⚡ 뇌전추격자!':'⚡ Cacciatore di Fulmini!',
'⚡회피 반격!':'⚡Contrattacco schivata!',
'✦ 유니크 공유!':'✦ Condivisione unica!',
'✦ 유니크 부활!':'✦ Rinascita unica!',
'❄유니크 빙결!':'❄Congelamento unico!',
'닫기 [C]':'Chiudi [C]',
'닫기 [V]':'Chiudi [V]',
'대왕치기 (분노폭발, 광역 기절)':'Colpo Gigante (esplosione d’ira, stordimento ad area)',
'물리방패의':'Scudo Fisico',
'사슬 착지 타격 수만큼 데미지 +20% 중첩(최대읐5)':'Colpi di atterraggio a catena: +20% danno (max 5)',
'성능 등급:':'Grado di prestazione:',
'쉴드 있으면 HP 안 닳아! 쉴드 먼저 깨야 해!':'Con lo scudo, gli HP sono al sicuro! Rompi prima lo scudo!',
'쉴드가 있는 적은 쉴드부터 깨야 HP가 깎여!':'Nemici con scudo: rompi prima lo scudo per colpire gli HP!',
'쉴드는 추가 HP다. 쉴드부터 깎인다.':'Lo scudo è HP extra. Lo scudo subisce danni per primo.',
'쉴드는 추가 HP야. 모든 공격이 쉴드를 먼저 깎아!':'Lo scudo è HP extra. Tutti gli attacchi colpiscono prima lo scudo!',
'얼음송곳':'Punta di Ghiaccio',
'한 방이면 죽어! 패링으로 HP 채워!!':'Un colpo ti uccide! Para per recuperare HP!!',
'👻 투명화!':'👻 Invisibilità!',
'👿악의+':'👿malizia+',
'💡 Q로 보호막 발동 — 기본 흡수율 30%, 패링 성공 시 HP/ST/MP/기동게이지 회복':'💡 Q per scudo — 30% assorbimento, parata riuscita recupera HP/ST/MP/Carica',
'💥유니크 폭발!':'💥Esplosione unica!',
'🔥피격→분노!':'🔥Colpito→Ira!',
'🔨방어무시!':'🔨Ignora DIF!',
'🛡️쉴드+15%':'🛡️Scudo+15%',
'썩은 숲':'Foresta Marcia',
'숲의 감시자':'Guardiano della Foresta',
'독버섯 거인':'Gigante Fungo Tossico',
'숲의 사냥꾼':'Cacciatore della Foresta',
'숲의 기생수':'Bestia Parassita',
'1장 — 썩은 숲':'CAP1 — Foresta Marcia',
'2장 — 벌레굴':'CAP2 — Nido di Vermi',
'3장 — 얼음굴':'CAP3 — Caverna di Ghiaccio',
'4장 — 고통의 화염지대':'CAP4 — Landa Infernale',
'5장 — 지옥의 군단':'CAP5 — Legione Infernale',
'6장 — 사도의 마굴':'CAP6 — Tana dell\'Apostolo',
'7장 — 지옥성':'CAP7 — Cittadella Infernale',
'탈출!':'Fuggito!',
'처치':'Uccisioni',
'경험치':'ESP',
'최대콤보':'Combo Max',
'일어나. 여신이 널 여기 보낸 건 죽으라고가 아니야.':'Svegliati. La dea non ti ha mandato qui per morire.',
'좋아, 감각이 있군. 계속 쳐!':'Bene, hai istinto. Continua a colpire!',
'Shift를 눌러. 사슬이다. 땅에 꽂아서 끌려가!':'Premi Shift. È il rampone. Conficcalo e fatti trascinare!',
'사슬로 끌려가는 중엔 무적이다. 위험할 때 쓰면 좋아.':'Sei invincibile mentre il rampone ti trascina. Usalo nei momenti critici.',
'...아파? 당연하지. 여긴 지옥이야.':'...Fa male? Ovvio. Questo è l\'inferno.',
'Q를 눌러! 악의로 보호막을 만들 수 있다.':'Premi Q! Crea uno scudo con la malizia.',
'보호막 없이 버틸 생각은 버려.':'Scordati di sopravvivere senza scudo.',
'E가 패링이다. 적 공격이 닿기 직전에 눌러!':'E per parare. Appena prima che il nemico colpisca!',
'못 하겠으면 때려. 안 죽으면 그만이야.':'Non riesci? Colpisci. L\'importante è non morire.',
'됐어! 감 잡았구나.':'Ecco! Stai capendo.',
'하나 죽었군.':'Uno in meno.',
'유령쇠뇌야. 인사해.':'È la balestra fantasma. Salutala.',
'보물상자를 열었군. 보스급 장비가 쏟아진다.': 'Hai aperto uno scrigno. Esce equipaggiamento da boss.',
'상자 대박! 좋은 거 잔뜩 나와! 보이면 꼭 열어!': 'Scrigno jackpot! Un sacco di roba buona! Aprili sempre!',
'잔해도 부숴서 열어. 악의와 장비가 숨어있다.': 'Rompi anche le macerie. Malizia ed equipaggiamento si nascondono dentro.',
'잔해에서 악의가 나온다! 보이면 다 주워!': 'Le macerie rilasciano Malizia! Raccogli tutte quelle che vedi!',
'빨간 탄을 무서워하지 마. 악의가 강하다.':'Non temere i proiettili rossi. La malizia è forte.',
'패링으로 돌려주고, Q 보호막도 써! 악의를 잘 굴려!':'Respingili con la parata e usa lo scudo Q! Gestisci la malizia!',
'무지개빛은 패링 불가! 피해!':'I colpi arcobaleno non si parano! Schiva!',
'피가 새고 있다. Shift. 빠져.':'Stai sanguinando. Shift. Scappa.',
'물약 있잖아! 숫자키!':'Hai pozioni! Tasti numerici!',
'E. 적 손목이 꺾일 때 쳐.':'E. Colpisci quando il polso si piega.',
'빨간 탄은 악의 덩어리다. 쳐내서 이용해.':'I proiettili rossi sono blocchi di malizia. Deviali e usali.',
'무지개빛만 피하면 돼! 나머지는 다 패링!':'Schiva solo l\'arcobaleno! Para tutto il resto!',
'Q 보호막도 패링이 가능해!':'Lo scudo Q può anche parare!',
'위험해! 쉬프트 사슬기동으로 피해!!':'Pericolo! Shift catena per fuggire!!',
'쉬프트! 사슬기동은 이동기야! 끌려가면서 무적이라고!':'Shift! La catena è movimento! Invincibile mentre ti trascina!',
'스킬포인트가 쌓였어! K 눌러서 스킬 배우자!':'Punti abilità pronti! Premi K!',
'속성을 읽어. 약점을 찌르면 두 배로 썩는다.':'Leggi gli elementi. Colpire debolezze fa il doppio danno.',
'K를 눌러봐! 스킬을 배울 수 있어!':'Premi K! Puoi imparare abilità!',
'J 눌러서 능력치 찍어! 패시브도 있어~':'Premi J per le stats! Anche i passivi~',
'G를 눌러. 대장간에서 장비를 강화할 수 있다.':'Premi G. Potenzia l\'equipaggiamento alla forgia.',
'F키도 스킬 슬롯이야! 스킬 많으면 L로 배정해봐~':'Anche F è uno slot! Usa L per assegnare~',
'Z. 필살기다. 아껴 써라.':'Z. La tua mossa finale. Usala con saggezza.',
'L-CTRL로 유령걸음이나 얼음보주 쓸 수 있어!':'L-CTRL per Passo Fantasma o Sfera di Ghiaccio!',
'L을 눌러. 스킬 슬롯을 정리해야 한다.':'Premi L. Organizza gli slot.',
'가방 터지겠다! N 눌러서 창고에 넣어둬!':'Lo zaino sta esplodendo! Premi N!',
'ESC로 설정 열 수 있어! 난이도 바꾸기, 자동물약 조절~':'ESC per le impostazioni! Difficoltà, pozioni auto~',
'...아직 살아있네. 좌클릭으로 저것들 쳐봐.':'...Ancora vivo. Colpiscili con clic sinistro.',
'...치는 건 할 줄 아네. 피하는 건?':'...Sai colpire. E schivare?',
'흥, 사슬 못 맞추면 헛수고야.':'Hmph, manca il rampone e sprechi tutto.',
'...운이 좋았을 뿐이야. 아마.':'...Solo fortuna. Probabilmente.',
'...고기 냄새. 싫진 않네.':'...Odore di carne. Non male.',
'...말은 못해.':'...Non può parlare.',
'예쁘다고 만지면 죽어.':'Li tocchi perché sono belli? Morirai.',
'사슬 던져! 끌려가면 무적이야!':'Lancia il rampone! Invincibile mentre ti trascinano!',
'...마시든 말든. 네 목숨이니까.':'...Bevi o no. È la tua vita.',
'그게 패링이야! 타이밍이 전부야~':'Quella è una parata! Il tempismo è tutto~',
'화염엔 빙결! 암전엔 암흑! 기억해!':'Fuoco vs Ghiaccio! Fulmine vs Oscurità! Ricorda!',
'...얼어붙은 놈은 오래 안 간다.':'...I congelati non durano.',
'얼었어! 빙결 중 1.5배야!':'Congelato! 1.5x danni!',
'...힘을 골라라. 전부 가질 순 없다.':'...Scegli il tuo potere. Non puoi avere tutto.',
'스탯을 올려. 살고 싶으면.':'Alza le stats. Se vuoi vivere.',
'좋은 장비는 강화해야 진짜 힘을 발휘해!':'L\'equipaggiamento buono va potenziato!',
'...슬롯을 채워. 빈 손은 죽음이다.':'...Riempi gli slot. Mani vuote = morte.',
'Z 누르면 대박! 쿨타임 길어서 타이밍 봐야 해!':'Z per danni enormi! Lungo cooldown, tempismo!',
'Ctrl. 위기에 쓸 카드가 하나 늘었군.':'Ctrl. Una carta in più per le emergenze.',
'스킬이 많아졌네~ L로 어디에 뭘 넣을지 골라!':'Tante abilità~ Usa L per assegnare!',
'...버리기 아까운 건 창고에.':'...Metti nel deposito ciò che vale.',
'...살아남은 것만으로도 대단하군. 설정을 확인해.':'...Sopravvivere è già impressionante. Controlla le impostazioni.',
'MP 부족!':'MP insufficiente!',
'ST 부족!':'ST insufficiente!',
'악의 부족!':'Malizia insufficiente!',
'충전 중...':'Caricamento...',
'캔슬':'Annulla',
'아이템 선택 필요':'Seleziona un oggetto',
'악의 소진...':'Malizia esaurita...',
'비문 발견...':'Iscrizione trovata...',
'HP물약!':'Pozione HP!',
'HP물약 +1':'Pozione HP +1',
'HP물약 +2':'Pozione HP +2',
'HP/MP/ST 회복!':'HP/MP/ST ripristinato!',
'보물상자 개봉!':'Forziere aperto!',
'익사!':'Annegamento!',
'피웅덩이!':'Pozza di sangue!',
'독혈!':'Sangue tossico!',
'잡힘!':'Afferrato!',
'콤보 종료':'Fine combo',
'빙결!':'Congelato!',
'화상!':'Bruciatura!',
'독!':'Veleno!',
'감전!':'Folgorato!',
'기절!':'Stordito!',
'봉인됨!':'Sigillato!',
'관통!':'Penetrazione!',
'기검참':'Taglio Ki',
'악의구':'Sfera Malizia',
'회전참':'Turbine',
'기폭팔':'Detonazione',
'칼등 처내기':'Parata di Lama',
'만화방창':'Raffica di Aghi',
'멸살광선':'Raggio Annientamento',
'원소추적탄':'Cercatore Elementale',
'악의 보호자':'Guardiano Malizia',
'악의 사냥':'Caccia Malizia',
'폭풍소환':'Evocazione Vortice',
'해골무덤':'Tomba d\'Ossa',
'\u{1F47B} 유령!':'\u{1F47B} Fantasma!',
'\u{1F9B4} 해골무덤!':'\u{1F9B4} Tomba d\'Ossa!',
'신성폭발':'Esplosione Sacra',
'블랙':'Stella Nera',
'용암소환':'Evocazione Lava',
'처형':'Esecuzione',
'악마화 부활':'Resurrezione Demoniaca',
'붉은꽃':'Fiore Cremisi',
'얼음보주':'Sfera di Ghiaccio',
'뇌전걸음':'Passo Fantasma',
'만화방창 II':'Raffica di Aghi II',
'마력연사':'Raffica Arcana',
'마력광선':'Laser Arcano',
'업화선':'Raggio Infernale',
'지옥진':'Formazione Infernale',
'폭독칼날':'Lama Pestilente',
'악의폭풍':'Tempesta Malizia',
'악의기둥':'Pilastro Oscuro',
'회복의 영역':'Dominio Sacro',
'구속의 영역':'Dominio Vincolante',
'아이스스톰':'Tempesta di Ghiaccio',
'대왕치기':'Colpo Gigante',
'대왕치기 2':'Colpo Gigante II',
'기동불꽃':'Fiamma a Catena',
'기동파괴':'Distruzione a Catena',
'기동칼날개':'Ala di Lama',
'평화의보호':'Egida della Pace',
'참회':'Penitenza',
'칼등날개':'Ala Scudo',
'폭산탄':'Colpo Esplosivo',
'파쇄의 영역':'Dominio Frantumazione',
'침식의 영역':'Dominio Corrosione',
'관통의 영역':'Dominio Penetrazione',
'부활의 영역':'Dominio Resurrezione',
'가시덫':'Trappola di Spine',
'푸른비':'Pioggia Azzurra',
'버스트루프':'Ciclo Raffica',
'유령 허수아비':'Esca Fantasma',
'폭발 허수아비':'Esca Esplosiva',
'공성쇠뇌':'Balestra d\'Assedio',
'사슬기동:충돌':'Catena: Impatto',
'사슬기동:화염':'Catena: Fiamma',
'전격이동':'Passo Fulmine',
'기동칼날개!':'Ala Lama!',
'기동불꽃!':'Fiamma Catena!',
'기동파괴!':'Distruzione a Catena!',
'사슬이동:강화!':'Catena Potenziata!',
'사슬기동:화염!':'Catena: Fiamma!',
'사슬!':'Rampone!',
'진입!':'Ingresso!',
'레인라이트닝!':'Pioggia Fulmini!',
'마력연사!':'Raffica Arcana!',
'🔷 마력광선!':'🔷 Laser Arcano!',
'광선 해제':'Laser disattivato',
'MP 부족 — 광선 해제':'MP esaurito — Laser disattivato',
'집중...':'Concentrazione...',
'시전...':'Lancio...',
'만화방창!':'Raffica di Aghi!',
'바늘출!':'Scarica di Aghi!',
'칼날!':'Lama!',
'착지!':'Atterraggio!',
'체간삭감!':'Postura spezzata!',
'기동전폭 준비!':'Esplosione Catena pronta!',
'기동불꽃 준비!':'Fiamma Catena pronta!',
'기동파괴 준비!':'Distruzione Catena pronta!',
'유령불꽃 ON':'Fiamma Fantasma ON',
'유령불꽃 OFF':'Fiamma Fantasma OFF',
'기동칼날개 AUTO ON':'Ala Lama AUTO ON',
'기동칼날개 AUTO OFF':'Ala Lama AUTO OFF',
'자동 버스트!':'Raffica auto!',
'연사 해제':'Fuoco rapido disatt.',
'당기기 모드':'Modalità Tirare',
'밀어내기 모드':'Modalità Spingere',
'날개치기':'Colpo Ala',
'처내기':'Parata',
'Shift: 사슬 발사 → 끌려감':'Shift: Rampone → trascinamento',
'Shift: 화염길+화상':'Shift: Scia fuoco+bruciatura',
'CT: 전류변신+뇌전걸음 (쿨4초)':'CT: Forma fulmine+Passo Fantasma (CD 4s)',
'CT: 방어구체+빙결 (재입력: 파쇄)':'CT: Sfera ghiaccio+congela (ri-premere: frantuma)',
'근접':'Mischia',
'견갑':'Guardia',
'사슬':'Rampone',
'마법':'Magia',
'보막':'Scudo',
'유령':'Fantasma',
'스킬':'Abilità',
'대장':'Fucina',
'인벤':'Inv',
'인벤토리':'Inventario',
'복수의 대장간':'Forgia della Vendetta',
'패시브 스킬':'Abilità Passive',
'전투 스킬':'Abilità Combattimento',
'캐릭터 선택':'Selezione Personaggio',
'물리':'Fisico',
'화염':'Fuoco',
'빙결':'Congelato',
'암흑':'Oscurità',
'암전':'Fulmine',
'신성':'Sacro',
'대지':'Terra',
'힘':'Forza',
'민첩':'Destrezza',
'지능':'Intelligenza',
'행운':'Fortuna',
'맹공':'Assalto',
'철벽':'Fermezza',
'돌파':'Sfondamento',
'반격':'Ritorsione',
'마력폭주':'Impeto Arcano',
'정밀사격':'Tiro Preciso',
'수호':'Guardiano',
'수호신':'Spirito Guardiano',
'회복력':'Recupero',
'급소':'Colpo Vitale',
'약탈':'Saccheggio',
'관통':'Penetrazione',
'마력회복':'Recupero Mana',
'쇠뇌력':'Maestria Balestra',
'광전사':'Berserker',
'추적자':'Inseguitore',
'물리관통':'Pen. Fisica',
'마법관통':'Pen. Magica',
'녹슨 대검':'Spadone Arrugginito',
'강철 대검':'Spadone d\'Acciaio',
'흑요석 대검':'Spadone Ossidiana',
'낡은 석궁':'Balestra Logora',
'강철 석궁':'Balestra d\'Acciaio',
'흑요석 석궁':'Balestra Ossidiana',
'대검':'Spadone',
'석궁':'Balestra',
'연사석궁':'Balestra Ripetizione',
'마력석궁':'Balestra Arcana',
'악의 추출':'Estrazione Malizia',
'악의':'Malizia',
'필살기':'Colpo Finale',
'필살기 해제':'Colpo Finale rimosso',
'이전':'Trasferisci',
'강화':'Potenziare',
'개봉!':'Aperto!',
'여신의 가호':'Benedizione della Dea',
'과부하!':'Sovraccarico!',
'맹독의':'Velenoso',
'불꽃의':'Fiammeggiante',
'냉기의':'Gelido',
'번개의':'Voltaico',
'암흑의':'Maledetto',
'관통의':'Penetrante',
'광폭의':'Furioso',
'파쇄의':'Frantumate',
'연쇄의':'Concatenato',
'학살의':'Massacrante',
'폭발의':'Esplosivo',
'집중의':'Concentrato',
'쾌속의':'Rapido',
'패리의':'Deflettente',
'추적자의':'dell\'Inseguitore',
'사슬의':'Rampone',
'궁극의':'Supremo',
'집중력의':'Attento',
'강인의':'Tenace',
'수호의':'Protettivo',
'활력의':'Vitale',
'신속의':'Accelerato',
'화염수호':'Guardia Fuoco',
'빙결수호':'Guardia Ghiaccio',
'암전수호':'Guardia Fulmine',
'암흑수호':'Guardia Oscurità',
'독수호':'Guardia Veleno',
'전원소수호':'Guardia Totale',
'강철의':'Corazzato',
'반사의':'Riflettente',
'가시의':'Spinoso',
'흡수의':'Assorbente',
'인내의':'Resistente',
'위기의':'Disperato',
'피격반격의':'Contrattaccante',
'패링폭발의':'Esplosione Parata',
'스태거폭발의':'Esplosione Barcollamento',
'원소전환의':'Convertitore',
'정화의':'Purificatore',
'불굴의':'Irremovibile',
'부활의':'Rianimatore',
'약탈의':'Saccheggiante',
'경험의':'Esperto',
'골드의':'Dorato',
'포션강화의':'Potente',
'사슬의':'Incatenato',
'진혼의':'Santificante',
'윤회의':'Ciclico',
'생명력의':'Vigoroso',
'재생의':'Rigenerante',
'치유의':'Curativo',
'마력의':'Arcano',
'절약의':'Efficiente',
'영혼의':'dell\'Anima',
'예리한':'Affilato',
'맹렬한':'Brutale',
'파멸의':'Rovinoso',
'게임 설정':'Impostazioni Gioco',
'화면 흔들림':'Vibrazione Schermo',
'파티클 양':'Quantità Particelle',
'효과음 볼륨':'Volume Effetti',
'음악 볼륨':'Volume Musica',
'난이도':'Difficoltà',
'자동 물약':'Pozione Auto',
'최소 줍기 등급':'Grado Min. Raccolta',
'최소 줍기 티어':'Tier Min. Raccolta',
'FPS 제한':'Limite FPS',
'해상도 스케일':'Scala Risoluzione',
'펫 자동수거':'Auto-Raccolta Pet',
'화면 설정':'Impostazioni Schermo',
'화면 모드':'Modalità Schermo',
'보스 AI 디버그':'Debug IA Boss',
'유령불꽃 크기':'Dimensione Fiamma Fantasma',
'화면 명암':'Luminosità',
'유령 글로우':'Bagliore Fantasma',
'기동:칼날개 AUTO':'Ala Lama AUTO',
'일반':'Normale',
'어려움':'Difficile',
'지옥':'Inferno',
'이상':'o superiore',
'사용 안 함':'Disattivato',
'창 모드':'Finestra',
'보더리스':'Senza Bordi',
'전체화면':'Schermo Intero',
'설정':'Impostazioni',
'조작 키 설정 (클릭하여 변경)':'Tasti (Clicca per Cambiare)',
'좌클릭 무기 공격':'Clic Sin Attacco Arma',
'E 탭 칼등 처내기':'E Parata Lama',
'E 홀드 연속 처내기':'Tenere E Parata Continua',
'SHIFT 사슬 발사':'SHIFT Lancia Rampone',
'이동':'Movimento',
'아이템 줍기':'Raccogliere Oggetto',
'능력치 (스탯/패시브)':'Attributi (Stats/Passivi)',
'분해':'Smontare',
'제작':'Fabbricare',
'사망':'Morte',
'부활':'Resurrezione',
'로비로':'Alla Lobby',
'가방에 공간이 없습니다!':'Nessuno spazio!',
'가방이 가득 찼습니다!':'Zaino pieno!',
'창고가 가득 찼습니다!':'Deposito pieno!',
'퀵슬롯이 가득 찼습니다!':'Slot rapido pieno!',
'결정 주머니가 가득 찼습니다!':'Sacca cristalli piena!',
'결정 주머니 가득!':'Sacca cristalli piena!',
'악의가 부족합니다!':'Malizia insufficiente!',
'가방이 비어있습니다':'Zaino vuoto',
'창고가 비어있습니다':'Deposito vuoto',
'비어있음':'Vuoto',
'어픽스 없음':'Nessun affisso',
'장착!':'Equipaggiato!',
'해제':'Rimosso',
'보관':'Depositare',
'꺼내기':'Ritirare',
'현재 장착':'Equipaggiato attuale',
'없음 — 제작하세요!':'Nessuno — Fabbricane uno!',
'리셋할 포인트가 없습니다':'Nessun punto da resettare',
'키 설정 초기화 완료':'Tasti resettati',
'제작 확률':'Prob. fabbricazione',
'제작 비용':'Costo fabbricazione',
'보유 악의':'Malizia posseduta',
'보스방':'Stanza Boss',
'안식처':'Santuario',
'회복':'Recupero',
'점화':'Accendere',
'비석':'Stele',
'읽기':'Leggere',
'파괴':'Distruggere',
'제단':'Altare',
'기원':'Pregare',
'잔해':'Macerie',
'열기':'Aprire',
'문지기':'Guardiano',
'부활 판정 중...':'Giudizio resurrezione...',
'기폭 준비!':'Detonazione pronta!',
'탈출':'Fuggire',
'연타':'Premere',
'추적암전':'Fulmine Tracciante',
'만화광선':'Raggio Luminescente',
'최종 마법':'Magia Finale',
'감시중':'Sorveglianza',
'대기':'In attesa',
'작동중':'Attivo',
'설치 가능':'Installabile',
'균열 임박!':'Breccia imminente!',
'흡수 중...':'Assorbimento...',
'흡수 완료 — 재입력으로 회수':'Fatto — ri-premere per raccogliere',
'화상':'Bruciatura',
'당기기':'Tirare',
'밀어내기':'Spingere',
'단계':'livello',
'단':'livello',
'습득!':'Appreso!',
'리셋!':'Reimposta!',
'세팅!':'Impostato!',
'회수':'Recuperare',
'합체 해제':'Defondere',
'리셋':'Reimposta',
'환불':'Rimborso',
'파트너 클릭!':'Clicca partner!',
'SP부족!':'SP insufficiente!',
'같은 보석 스킬 습득 시 합체 가능':'Fondibile imparando stessa gemma',
'펼쳐서 초기화':'Espandi per resettare',
'슬롯:':'Slot:',
'남은 SP':'SP Rimanenti',
'맞아서 사망':'Morto per colpo',
'레벨':'Livello',
'최대HP':'HP Massimi',
'방랑 기사':'Cavaliere Errante',
'보물 악마':'Demone Tesoro',
'거울의 사도':'Apostolo Specchio',
'상인 악마':'Demone Mercante',
'사슬의 죄수':'Prigioniero Incatenato',
'시간의 사도':'Apostolo del Tempo',
'탐욕의 사도':'Apostolo Avidità',
'저주받은 쌍둥이':'Gemelli Maledetti',
'차원 균열체':'Entità Dimensionale',
'죽음 그 자체':'La Morte in Persona',
'HP결정':'Cristallo HP',
'ST결정':'Cristallo ST',
'MP결정':'Cristallo MP',
'ATK결정':'Cristallo ATK',
'DEF결정':'Cristallo DEF',
'속도결정':'Cristallo Velocità',
'크리결정':'Cristallo Critico',
'치명결정':'Cristallo DannoCrit',
'화염결정':'Cristallo Fuoco',
'냉기결정':'Cristallo Ghiaccio',
'암흑결정':'Cristallo Oscurità',
'번개결정':'Cristallo Fulmine',
'신성결정':'Cristallo Sacro',
'생명결정':'Cristallo Vita',
'기력결정':'Cristallo Resistenza',
'마력결정':'Cristallo Mana',
'행운결정':'Cristallo Fortuna',
'조각':'Frammento',
'파편':'Scheggia',
'순수결정':'Cristallo Puro',
'완전결정':'Cristallo Perfetto',
'결정 주머니':'Sacca Cristalli',
'결정이 없습니다':'Nessun cristallo',
'가루':'Polvere',
'전체':'Tutto',
'스탯':'Statistica',
'원소':'Elem',
'유틸':'Util',
'현재':'Attuale',
'최대 강화 달성 (+20)':'Potenz. max (+20)',
'강화 시':'Dopo potenziamento',
'합성':'Sintetizzare',
'같은 종류·같은 성급 결정 3개 → 1성급 상승 (강화 리셋)':'3 cristalli stesso tipo e grado → sale 1 grado (potenziamento reset)',
'합성 가능한 결정이 없습니다 (같은 종류·성급 3개 필요)':'Nessun cristallo sintetizzabile (servono 3)',
'결정 분해 → 결정 가루':'Decomporre Cristallo → Polvere',
'분해할 결정이 없습니다':'Nessun cristallo da decomporre',
'결정 제작 (가루 → 결정)':'Fabbricare Cristallo (Polvere → Cristallo)',
'탈착':'Staccare',
'빈 슬롯':'Slot vuoto',
'결정 선택 후 클릭':'Seleziona cristallo poi clicca',
'클릭하여 선택결정 장착':'Clicca per equipaggiare cristallo',
'획득!':'Ottenuto!',
'제작!':'Fabbricato!',
'합성!':'Sintetizzato!',
'최상위 일괄합성':'Sintesi massiva',
'일괄합성 완료':'Sintesi massiva completata',
'벌레굴':'Nido di Vermi',
'얼음굴':'Caverna di Ghiaccio',
'고통의 화염지대':'Landa Infernale',
'지옥의 군단':'Legione Infernale',
'사도의 마굴':'Tana dell\'Apostolo',
'지옥성':'Cittadella Infernale',
'엑소듀서 전사':'Guerriero Exoduser',
'포이즈':'Postura',
'지옥창고':'Deposito Infernale',
'선택분해':'Smontaggio Selettivo',
'쓰레기':'Spazzatura',
'복구 불가!':'Irrecuperabile!',
'중요잠금':'Blocco importante',
'자동 장착!':'Auto-equipaggiato!',
'분해! 가루 +':'Smontato! Polvere +',
'평화보호':'Egida',
'지진폭풍':'Tempesta Sismica',
'회전기폭':'Turbine-Det',
'공격':'Attacco',
'보호막':'Barriera',
'합체 스킬로 통합됨':'Fuso in abilità combinata',
'얼음보주 안에선 사용 불가!':'Non utilizzabile nella Sfera di Ghiaccio!',
'Shift+키로 폭파':'Shift+tasto per detonare',
'취소':'Annulla',
'쿨다운 중...':'Ricarica...',
'시전 중...':'Lancio...',
'악의 부족! (12)':'Malizia insuff.! (12)',
'악의 부족! (15)':'Malizia insuff.! (15)',
'악의 부족! (20)':'Malizia insuff.! (20)',
'악의 부족! (10)':'Malizia insuff.! (10)',
'HP 부족!':'HP insufficiente!',
'필살기 슬롯 클릭하여 배정!':'Clicca slot colpo finale!',
'필살기 스킬을 습득하세요':'Impara un colpo finale',
'E(칼등치기)에 합체됨':'Fuso E (parata)',
'T(석궁자동)에 세팅하세요':'Imposta su T (balestra auto)',
'공성쇠뇌 철거 → 이동식':'Balestra assedio smontata → portatile',
'ST 부족! (100)':'ST insuff.! (100)',
'HP 99% 이상!':'HP 99%+!',
'그로기 보스 없음!':'Nessun boss stordito!',
'이미 폭풍 지역!':'Già in zona tempesta!',
'이미 빙풍 지역!':'Già in zona ghiaccio!',
'💎 푸른비 해금!':'💎 Pioggia Azzurra sbloccata!',
'💫 버스트루프 해금!':'💫 Ciclo Raffica sbloccato!',
'👻 유령 허수아비 해금!':'👻 Esca Fantasma sbloccata!',
'쿨 ':'CD ',
'과부하 ':'Sovraccarico ',
'🕊️💎 블루콩!':'🕊️💎 Fagiolo Blu!',
'🛡️💎 빨콩→블루콩!':'🛡️💎 Rosso→Blu!',
'🛡️💎 무지개→블루콩!':'🛡️💎 Arcobaleno→Blu!',
'레어':'Raro',
'슬롯':'Slot',
'성공률':'Tasso Successo',
'AI 자동 강화':'Potenziamento Auto IA',
'최대 강화 달성!':'Potenziamento max raggiunto!',
'최대 강화':'Potenziamento max',
'회복량':'Recupero',
'분해할 아이템이 없습니다.':'Nessun oggetto da smontare.',
'🔨 제작':'🔨 Fabbricare',
'체간':'Postura',
'아이템에 마우스를 올리거나 좌클릭으로 선택하세요':'Passa sopra o clic sinistro per selezionare',
'중독':'Veleno',
'지뢰':'Mina',
'덫':'Trappola',
'산호가시':'Spina Corallo',
'투사체':'Proiettile',
'도트':'DoT',
'레어몹':'Mob Raro',
'구역':'Zona',
'가시!':'Spina!',
'림보':'Limbo',
'색욕':'Lussuria',
'탐식':'Gola',
'탐욕':'Avidità',
'분노':'Ira',
'이단':'Eresia',
'폭력':'Violenza',
'분노!':'Furia!',
'탐욕!':'Avidità!',
'💀 분노 폭발!':'💀 Esplosione Furia!',
'심연의 분노!':'Furia Abissale!',
'쌍둥이의 분노!':'Furia del Gemello!',
'소환굴':'Tana Evocazione',
'처치!':'Eliminato!',
'왕관 착용':'Corona Indossata',
'왕관 해제':'Corona Rimossa',
'맨손':'Mani Nude',
'없음':'Nessuno',
'갑옷':'Armatura',
'부츠':'Stivali',
'매직':'Magia',
'챔피언':'Campione',
'초속':'Celerità',
'강타':'Schianto',
'재생':'Rigenerazione',
'맹독':'Veleno',
'소환':'Evocazione',
'기생':'Parassita',
'분열':'Scissione',
'용암자취':'Scia Lava',
'사망폭발':'Esplosione Mortale',
'화염사슬':'Catena Fuoco',
'광전':'Frenesia',
'텔레포트':'Teletrasporto',
'소용돌이':'Vortice',
'환영':'Fantasma',
'전격반사':'Riflesso Shock',
'감전':'Folgorazione',
'낙뢰':'Tuono',
'연쇄전격':'Fulmine Catena',
'동료불사':'Alleato Immortale',
'영혼포식':'Divoratore Anime',
'시간왜곡':'Distorsione Temporale',
'혼돈변이':'Mutazione Caotica',
'복수자':'Vendicatore',
'마법보초':'Sentinella Magica',
'환영술사':'Illusionista',
'함성':'Grido Guerra',
'치유':'Cura',
'신속':'Rapidità',
'다크 판타지 전사. 거대검+검은 갑옷':'Guerriero dark fantasy. Spadone + Armatura nera',
'⚡ 사슬이동:강화!':'⚡ Catena: Potenziata!',
'⚡ 사슬기동:화염!':'⚡ Catena: Fiamma!',
'달성!':'Raggiunto!',
'ST':'ST',
'부족!':'Insufficiente!',
'타':'Colpo',
'🌀 당기기 모드':'🌀 Modalità Tirare',
'💥 밀어내기 모드':'💥 Modalità Spingere',
'🕊️빨콩 흡수':'🕊️Assorbimento fagiolo rosso',
'🕊️흡수':'🕊️Assorbimento',
'💎유도 폭발!':'💎Esplosione guidata!',
'💥반사 폭발!':'💥Esplosione riflesso!',
'⚡⚡ 참회 귀환!':'⚡⚡ Ritorno Pentimento!',
'⚡ 참회!':'⚡ Pentimento!',
'파도!':'Onda!',
'암전!':'Fulmine!',
'암흑!':'Oscurità!',
'암흑창!':'Lancia Oscura!',
'빛창!':'Lancia di Luce!',
'체 소환!':'evocato!',
'개 설치!':'piazzato!',
'💥 보스 그로기!':'💥 Boss Stordito!',
'💥 그로기!':'💥 Stordito!',
'보상':'Bonus',
'⚡ 암전나선!':'⚡ Elica Fulmine!',
'🌋 지진폭풍!':'🌋 Tempesta Sismica!',
'SP슬롯':'Slot SP',
'F슬롯':'Slot F',
'⚔🩸 독혈해방!':'⚔🩸 Liberazione Peste!',
'⚔ 칼날 해방!':'⚔ Liberazione Lama!',
'🔨🌋 지옥강타!':'🔨🌋 Colpo Infernale!',
'🔨 대왕치기!':'🔨 Colpo Gigante!',
'✟ 결계의 영역!':'✟ Dominio Protezione!',
'✟ 물의 영역!':'✟ Dominio Acqua!',
'✟ 파쇄의 영역!':'✟ Dominio Frantumazione!',
'✟ 침식의 영역!':'✟ Dominio Corrosione!',
'✟ 관통의 영역!':'✟ Dominio Penetrazione!',
'✟ 권능의 영역!':'✟ Dominio Sovrano!',
'🛡 회복의 영역!':'🛡 Dominio Sacro!',
'임계...!':'Critico...!',
'기폭팔!':'Detonare!',
'강제기폭!':'Detonazione forzata!',
'자동기폭!':'Detonazione auto!',
'회전기폭!':'Turbine detonare!',
'해제기폭!':'Rilascio detonare!',
'지진기폭!':'Sisma detonare!',
'혼돈의 왕관':'Corona del Caos',
'전지전능의 왕관':'Corona dell\'Onnipotenza',
'악마의 팔찌':'Bracciale Demoniaco',
'생명의 팔찌':'Bracciale della Vita',
'🌊 위→아래 파도!':'🌊 Onda Alto→Basso!',
'🌊 오른→왼 파도!':'🌊 Onda Destra→Sinistra!',
'🌊 아래→위 파도!':'🌊 Onda Basso→Alto!',
'🌊 왼→오른 파도!':'🌊 Onda Sinistra→Destra!',
'무적!':'Invincibile!',
'🪞 반격!':'🪞 Contrattacco!',
'💢 반격!':'💢 Contrattacco!',
'흡수!':'Assorbimento!',
'반격 발사!':'Colpo contrat.!',
'저주! 드랍률 -50%':'Maledizione! Drop -50%',
'도망!':'Fuga!',
'위상!':'Fase!',
'방어!':'Guardia!',
'회수 HP+':'Recuperare HP+',
'이동식 복귀':'Ritorno Mobile',
'약점!':'Debolezza!',
'저항!':'Resistenza!',
'콤보 종료: ':'Fine combo: ',
'악의 +':'Malizia +',
'저주 ':'Maledizione ',
'불발...':'Mancato...',
'사슬 약점!':'Debolezza Rampone!',
'전염 x':'Peste x',
'흡수 완료!':'Assorbimento completo!',
'부활 성공!':'Resurrezione riuscita!',
'부활 실패...':'Resurrezione fallita...',
'차원 이동!':'Spostamento Dimensionale!',
'기절 해제':'Stordimento rimosso',
'악의 부족':'Malizia insufficiente',
'스킬 미습득':'Nessuna abilità',
'펼치기':'Espandi',
'접기':'Comprimi',
'조건 미달!':' non soddisfatta!',
'해제!':' Defuso!',
'자동 ON':' Auto ON',
'자동 OFF':' Auto OFF',
'스킬 해제':' abilità rimossa',
'닫기':'Chiudi',
'장착 중':'Equipaggiato',
'보관 아이템':'Oggetto depositato',
'클릭으로 선택 · ESC로 닫기':'Clicca per selezionare · ESC per chiudere',
'선택됨':'Selezionato',
'악의 부족! (30)':'Malizia insuff.! (30)',
'MP 부족! (40)':'MP insuff.! (40)',
'MP 부족! (100)':'MP insuff.! (100)',
'MP 부족! (10)':'MP insuff.! (10)',
'MP 부족! (':'MP insuff.! (',
'✟ 시전...':'✟ Lancio...',
'🌋 시전...':'🌋 Lancio...',
'⛧ 시전...':'⛧ Lancio...',
'❄ 진입!':'❄ Ingresso!',
'⛓️ 사슬!':'🔱 Rampone!',
'레벨 부족! (요구: Lv.':'Livello basso! (Req: Lv.',
' 장착!':' Equipaggiato!',
' 해제':' Rimosso',
'👿 악의 추출: +':'👿 Estrazione Malizia: +',
'F 슬롯 해제':'Slot F rimosso',
'💫 집중...':'💫 Concentrazione...',
'⚡ 마력연사!':'⚡ Raffica Arcana!',
'❄빙결!':'❄Congelato!',
'🟢독!':'🟢Veleno!',
'⚡감전!':'⚡Folgorato!',
'🔥화상!':'🔥Bruciatura!',
'✦ 여신의 가호 — SP+5 AP+3':'✦ Benedizione Dea — SP+5 AP+3',
'⚔ 기동칼날개!':'⚔ Ala Lama!',
'🔥 화염관통!':'🔥 Penetrazione Fuoco!',
'🔱 관통!':'🔱 Penetrazione!',
'⚔ 칼날!':'⚔ Lama!',
'💥 착지!':'💥 Atterraggio!',
'💫 기절!':'💫 Stordito!',
'⚡ 체간삭감!':'⚡ Postura spezzata!',
'⚡ 기동파괴! ':'⚡ Distruzione Catena! T',
'🔥 기동불꽃!':'🔥 Fiamma Catena!',
'🔥 기동불꽃! ':'🔥 Fiamma Catena! T',
'단계 ×':' x',
'⚡ 기동전폭! x':'⚡ Esplosione Catena! x',
'🔥🔥 3중폭!':'🔥🔥 Fiamma x3!',
'🔥🔥🔥 6중폭!':'🔥🔥🔥 Fiamma x6!',
'🔥🔥🔥🔥 9중폭!':'🔥🔥🔥🔥 Fiamma x9!',
'💥 불꽃폭발! ':'💥 Detonazione Fiamma! ',
'🔥 기동불꽃 준비!':'🔥 Fiamma Catena pronta!',
'🔨 기동파괴 준비!':'🔨 Distruzione Catena pronta!',
'⚡ 기동전폭 준비!':'⚡ Esplosione Catena pronta!',
'⚡ 과부하! 5초':'⚡ Sovraccarico! 5s',
'💫 자동 버스트!':'💫 Raffica auto!',
'🔨 칼등날개!':'🔨 Ala Scudo!',
'💥폭발!':'💥Esplosione!',
'🛡️💎 유도반사!':'🛡️💎 Riflesso Guidato!',
'⚡💎 블루콩!':'⚡💎 Fagiolo Blu!',
'💎 블루콩!':'💎 Fagiolo Blu!',
'⚡반사!':'⚡Riflesso!',
'💎 푸른비 OFF':'💎 Pioggia Azzurra OFF',
'💎 푸른비 ON!':'💎 Pioggia Azzurra ON!',
'🔥 지옥진!':'🔥 Formazione Infernale!',
'🔥 업화선!':'🔥 Raggio Infernale!',
'✦ 평화 충격파! ':'✦ Onda Pace! ',
'⚡ 전류 방출!':'⚡ Rilascio Corrente!',
'⚡⚡ 레인라이트닝!':'⚡⚡ Pioggia Fulmini!',
'💫 광역!':'💫 Area!',
'🔥 불장판!':'🔥 Zona Fuoco!',
'💫 피니셔!':'💫 Mossa finale!',
'☠ 지옥에서 귀환!':'☠ Ritorno dall\'Inferno!',
'☠ 완전 사망!':'☠ Morte Permanente!',
'⚔ 처형! ':'⚔ Esecuzione! ',
'💥 지뢰!':'💥 Mina!',
'⚠ 덫!':'⚠ Trappola!',
'❌ E키로! -':'❌ Usa E! -',
'❌ Q키로! -':'Usa Q! -',
'💥무지개 폭발! ':'💥Esplosione Arcobaleno! ',
'🛡️💎 블루콩!':'🛡️💎 Fagiolo Blu!',
'⬜화이트볼!':'⬜Sfera Bianca!',
'✨💎 블루콩!':'✨💎 Fagiolo Blu!',
'💜다크볼!':'💜Palla Oscura!',
'❄빙판!':'❄Pavimento Ghiaccio!',
'🌨빙결!':'🌨Congelato!',
'🕸둔화!':'🕸Rallentato!',
'💀 역병 처형!':'💀 Esecuzione Peste!',
'💥 역병 Finale!':'💥 Finale Peste!',
'⚔ 균열 악마!':'⚔ Demone Faglia!',
'자동회수 HP+':'Auto-Recuperare HP+',
'MP 부족 — 연사 해제':'MP basso — Fuoco rapido OFF',
'MP 부족 — 푸른비 OFF':'MP basso — Pioggia Azzurra OFF',
'🛡️반사!':'🛡️Riflesso!',
'⚡🦴 참회 귀환!':'⚡🦴 Ritorno Pentimento!',
'🦴⚡해골번개!':'🦴⚡Fulmine Ossa!',
'⚡악의폭풍!':'⚡Tempesta Malizia!',
'❄아이스스톰!':'❄Tempesta Ghiaccio!',
'⚡ 암전폭발!':'⚡ Esplosione Fulmine!',
'⚡ 레인라이트닝! x':'⚡ Pioggia Fulmini! x',
'❄ 탈출!':'❄ Fuggire!',
'⚡쉴드!':'⚡Scudo!',
'❄🌪️ 얼음보주!':'❄🌪️ Sfera Ghiaccio!',
'🌪️ 전개!':'🌪️ Dispiegamento!',
'❄ 빙결흡인!':'❄ Vortice Ghiaccio!',
'❄☄ 빙결폭발!':'❄☄ Esplosione Ghiaccio!',
'☄️ 흡인!':'☄️ Vortice!',
'☄️ 대폭발!':'☄️ Mega Esplosione!',
'❄ 얼음보주!':'❄ Sfera Ghiaccio!',
'⏳ 시간왜곡!':'⏳ Distorsione Temporale!',
'쿨다운!':'Ricarica!',
'❄ 파쇄!':'❄ Frantumazione!',
'☄️💥 대폭발!':'☄️💥 Mega Esplosione!',
'반사!':'Riflesso!',
'💀 도넛!':'💀 Ciambella!',
'💀 전멸!':'💀 Annientamento!',
'🌊 파도!':'🌊 Onda!',
'속박!':'Vincolo!',
'반격!':'Contrattacco!',
'분신!':'Clone!',
'분신 파괴!':'Clone distrutto!',
'무기 해방!':'Liberazione arma!',
'❄프리즌!':'❄Prigione!',
'⚡ 증표 ':'⚡ Segno ',
'흔들!':'Scossa!',
'⚠ 광역 발사!':'⚠ Fuoco AoE!',
'🔥 확산!':'🔥 Propagazione!',
'⚠ 돌진!':'⚠ Carica!',
'🦅 도약!':'🦅 Salto!',
'⚡ 레이저!':'⚡ Laser!',
'🌊 충격파!':'🌊 Onda d\'urto!',
'👹 소환!':'👹 Evocazione!',
'☄ 유성우!':'☄ Pioggia meteoriti!',
'🖐 잡기!':'🖐 Afferrare!',
'🌀 회전참!':'🌀 Turbine!',
'💣 지뢰!':'💣 Mina!',
'🌀 흡인!':'🌀 Aspirazione!',
'🔴 빨간콩 폭풍!':'🔴 Tempesta Fagiolo Rosso!',
'🔴🔴 콩 비!':'🔴🔴 Pioggia Fagioli!',
'🌊 부채꼴 충격파!':'🌊 Onda ventaglio!',
'✴ 멸광 레이저!':'✴ Laser Annientamento!',
'🔴 추적 장판!':'🔴 Zona Tracciamento!',
'💥 속성탄!':'💥 Colpo Elementale!',
'⚔ 검기!':'⚔ Ki Spada!',
'⚔ 재단참!':'⚔ Fendente Mietitore!',
'🌀 나선탄!':'🌀 Colpo Spirale!',
'⚠ 찌르기!':'⚠ Stoccata!',
'🔥🔥 지옥기둥!':'🔥🔥 Pilastro Infernale!',
'⚔ 환영검!':'⚔ Lama Fantasma!',
'💢 반격자세!':'💢 Postura Contrat.!',
'⚔ 연격!':'⚔ Combo!',
'🌑 암흑!':'🌑 Oscurità!',
'👥 분신!':'👥 Clone!',
'🌋 균열!':'🌋 Faglia!',
'🌊 파동!':'🌊 Ondulazione!',
'💣 추적지뢰!':'💣 Mina tracciante!',
'⏪ 되감기!':'⏪ Riavvolgi!',
'🌀 중력장!':'🌀 Campo gravitazionale!',
'🔨 벽밀기!':'🔨 Spingere muro!',
'☠ 독안개!':'☠ Nebbia velenosa!',
'⛓ 감옥!':'⛓ Prigione!',
'⚡ 연쇄번개!':'⚡ Fulmine a catena!',
'🔮 궤도탄!':'🔮 Colpo orbitale!',
'🛡 방패돌진!':'🛡 Carica scudo!',
'🪞 반격자세!':'🪞 Postura Contrat.!',
'⚓ 속박!':'⚓ Vincolo!',
'👤 분신!':'👤 Clone!',
'🖐 탈취!':'🖐 Furto!',
'🔥🔥 용암 지대!':'🔥🔥 Zona lava!',
'🌧🌧 화염 폭격!':'🌧🌧 Raffica fuoco!',
'⚡⚡ 전격 장막!':'⚡⚡ Velo fulmine!',
'💀 내 곁으로!':'💀 Vieni da me!',
'⭕ 안전!':'⭕ Sicuro!',
'💀💀 전멸 폭발!':'💀💀 Esplosione Annientamento!',
'⚡ 쐐기 소멸!':'⚡ Estinzione Cuneo!',
'🌊충격파!':'🌊Onda d\'urto!',
'👿악의+100':'👿Malizia+100',
'💥패링폭발!':'💥Esplosione Parata!',
'균열 충돌! ':'Collisione faglia! ',
'벽 충돌! ':'Collisione muro! ',
'소환!':'Evocazione!',
'환영!':'Fantasma!',
'⚡낙뢰!':'⚡Tuono!',
'⚡빔!':'⚡Raggio!',
'환영술!':'Illusione!',
'💀소환!':'💀Evocazione!',
'🔮주술!':'🔮Maledizione!',
'🩸산란!':'🩸Generazione!',
'💢광폭!':'💢Frenesia!',
'🕷산란!':'🕷Generazione!',
'❄서리!':'❄Gelo!',
'❄빙결파!':'❄Onda Ghiaccio!',
'💀빙마!':'💀Demone Ghiaccio!',
'돌진!':'Carica!',
'충격파!':'Onda d\'urto!',
'독안개!':'Nebbia velenosa!',
'연타!':'Raffica!',
'포효!':'Ruggito!',
'강화!':'Potenziamento!',
'꼬리!':'Coda!',
'은신...':'Furtività...',
'기습!':'Imboscata!',
'산란!':'Generazione!',
'독가스!':'Gas velenoso!',
'소멸...':'Dissoluzione...',
'강타!':'Schianto!',
'분비!':'Secrezione!',
'채찍!':'Frusta!',
'출혈!':'Sanguinamento!',
'급강하!':'Picchiata!',
'방출!':'Scarica!',
'충격!':'Impatto!',
'치유!':'Cura!',
'의식!':'Rituale!',
'지옥불!':'Fuoco infernale!',
'끌려감!':'Trascinato!',
'혀!':'Lingua!',
'응시!':'Sguardo!',
'낙하!':'Caduta!',
'핏방울!':'Goccia sangue!',
'일어남!':'Alzarsi!',
'휩쓸기!':'Spazzata!',
'웅크림':'Accovacciato',
'뼈칼날!':'Lama d\'osso!',
'감속!':'Rallentato!',
'비명!':'Urlo!',
'화산탄!':'Colpo vulcanico!',
'자폭!':'Autodistruzione!',
'감싸기!':'Avvolgere!',
'잡기!':'Afferrare!',
'내리찍기!':'Colpo!',
'브레스!':'Soffio!',
'비행!':'Volo!',
'용암비!':'Pioggia lava!',
'물뿜기!':'Getto acqua!',
'빛...':'Luce...',
'삼키기!':'Ingoiare!',
'마비!':'Paralisi!',
'방전!':'Scarica!',
'집게찍기!':'Tenaglia!',
'찍기!':'Colpo!',
'붙잡기!':'Afferrare!',
'감아올리기!':'Avvolgere!',
'파편!':'Frammento!',
'할퀴기!':'Graffio!',
'기생충!':'Parassita!',
'심연 해방!':'Liberazione abissale!',
'촉수난타!':'Raffica tentacoli!',
'삼지창!':'Tridente!',
'소용돌이!':'Vortice!',
'해일!':'Tsunami!',
'끼걱!':'Scricchiolio!',
'폭발!':'Esplosione!',
'체인!':'Catena!',
'갈기!':'Criniera!',
'공포!':'Terrore!',
'흡혈!':'Drenaggio!',
'베기!':'Fendente!',
'비이이명!!':'Driiin!!',
'분열!':'Scissione!',
'3연참!':'Triplo fendente!',
'패링!':'Parata!',
'...복사...':'...Copia...',
'불균형...저주!':'Squilibrio...Maledizione!',
'저주!':'Maledizione!',
'균형...강화!':'Equilibrio...Potenziamento!',
'심판의 기둥!':'Pilastro del Giudizio!',
'처형 선고!':'Sentenza Morte!',
'고통의 해방!':'Liberazione dolore!',
'너도 느껴봐라!':'Senti anche tu!',
'대검난무!':'Frenesia spadone!',
'촉수!':'Tentacolo!',
'전방위 빔!':'Raggio totale!',
'회피!':'Schivata!',
'[F] 상점':'[F] Negozio',
'거래 성공!':'Commercio riuscito!',
'악의 부족! (':'Malizia insuff.! (',
'상인이 떠납니다...':'Il mercante se ne va...',
'사슬 해방!':'Liberazione catena!',
'완전 해방!':'Liberazione totale!',
'⏪ 시간 되감기!':'⏪ Riavvolgimento Temporale!',
'전환!':'Cambio!',
'부활 ':'Resurrezione ',
'🌀균열!':'🌀Faglia!',
'...사라짐':'...Scomparso',
'낫 베기!':'Fendente falce!',
'☠ 죽음의 선고!':'☠ Sentenza Morte!',
'선고 집행...':'Esecuzione sentenza...',
'⚡패링!':'⚡Parata!',
'경직!':'Stordire!',
'⚠ 잡혔다!':'⚠ Afferrato!',
'💥 내던지기!':'💥 Lancio!',
'💥 소용돌이 폭발!':'💥 Esplosione Vortice!',
'👻 순간이동!':'👻 Teletrasporto!',
'💫 기절! 5초':'💫 Stordito! 5s',
'찌르기 반격!':'Contrattacco spinta!',
'💢 폭발!':'💢 Esplosione!',
'반격 실패':'Contrattacco fallito',
'탈취 반격!':'Contrattacco furto!',
'무기 봉인!':'Sigillo arma!',
'냠!':'Gnam!',
'합체!':'Fuso!',
'출구가 열렸다!':'Uscita aperta!',
'보물상자 출현!':'Forziere apparso!',
'출구':'Uscita',
'⚠ 문지기가 살아있다!':'⚠ Guardiano ancora vivo!',
'⏱ 타임어택 ':'⏱ Cronometro ',
'처치율 ':'Tasso Elim. ',
'불사 보호':'Protezione immortale',
'환영 소멸!':'Fantasma scomparso!',
'부활력 ':'Potere Resurrezione ',
'✟ 신성력 억제! (':'✟ Soppressione Sacra! (',
'부활 실패 (':'Resurrezione fallita (',
'⚡순간이동!':'⚡Teletrasporto!',
'👻 동반부활!':'👻 Co-Resurrezione!',
'✟ 신성력 억제!':'✟ Soppressione Sacra!',
'💀 부활 판정 중...':'💀 Giudizio resurrezione...',
'⚔ 문지기 처치!':'⚔ Guardiano Eliminato!',
'🚪 보스방 개방!':'🚪 Stanza Boss Aperta!',
'잔해 출현!':'Macerie apparse!',
'🌀균열 발생!':'🌀Faglia aperta!',
'🔥복수!':'🔥Vendetta!',
'💥폭독혈!':'💥Sangue Peste!',
'빙판!':'Pavimento Ghiaccio!',
'❄최종빙결!':'❄Congelamento Finale!',
'빙마 처치!':'Demone Ghiaccio Eliminato!',
'분리!':'Separazione!',
'뼈 파편!':'Frammento osso!',
'태아 처치!':'Feto Eliminato!',
'지배자 처치!':'Signore Eliminato!',
'용암!':'Lava!',
'화룡 처치!':'Drago Fuoco Eliminato!',
'최후의 비명!':'Urlo Finale!',
'산화...':'Ossidazione...',
'심판자 처치!':'Giudice Eliminato!',
'고통의 왕 처치!':'Re Dolore Eliminato!',
'수역!':'Acqua!',
'파편 폭발!':'Esplosione frammento!',
'거대어 처치!':'Leviatano Eliminato!',
'대사도 처치!':'Alto Apostolo Eliminato!',
'독웅덩이!':'Pozza veleno!',
'화염장판!':'Zona Fuoco!',
'전기장!':'Campo elettrico!',
'무기 드롭!':'Arma caduta!',
'보물 발견!':'Tesoro trovato!',
'상인의 주머니 +':'Sacca mercante +',
'속박의 파편!':'Scheggia vincolo!',
'시간의 조각!':'Frammento tempo!',
'저주 해제!':'Maledizione rimossa!',
'차원의 결정!':'Cristallo dimensionale!',
'전설 아이템!':'Oggetto leggendario!',
'죽음을 이겨냈다!':'Superare la morte!',
'💥대폭발!':'💥Mega Esplosione!',
'⚡강화!':'⚡Potenziamento!',
'장비 ':'Equipagg. ',
'💫 진동!':'💫 Tremore!',
'❄ 무적!':'❄ Invincibile!',
'집중 해제!':'Concentrazione annullata!',
'집중!':'Concentrazione!',
'🕊️ 평화보호 ':'🕊️ Egida ',
'🛡 보호막 ':'🛡 Scudo ',
'🌀 회전보호막 ':'🌀 Scudo Rotante ',
'💥한방캡!':'💥Limite un colpo!',
'⚡쉴드 파괴!':'⚡Scudo distrutto!',
'💀 불굴!':'💀 Irremovibile!',
'💀 1회부활!':'💀 1 vita resurrezione!',
'감시 회수':'Recupera sentinella',
'악마화 부활!':'Resurrezione demoniaca!',
'배정 가능한 스킬 없음':'Nessuna abilità da assegnare',
'칼날 없음!':'Nessuna lama!',
'⚔ 악의사냥!':'⚔ Caccia Malizia!',
'❄🌪️ 얼음소용돌이!':'❄🌪️ Vortice Ghiaccio!',
'🌪️ 폭풍소환!':'🌪️ Evocazione Vortice!',
'🌹 붉은꽃!':'🌹 Fiore Cremisi!',
'💥 폭산탄!':'💥 Colpo Esplosivo!',
'🪡 바늘출!':'🪡 Scarica di Aghi!',
'⚡ 전격이동!':'⚡ Passo Fulmine!',
'기둥가시로 흡수됨':'Assorbito da spina pilastro',
'🌿 가시덫!':'🌿 Trappola Spine!',
'⚡ 전격의창!':'⚡ Lancia Tuono!',
'🏹 공성쇠뇌 설치!':'🏹 Balestra Assedio piazzata!',
'👻 유령 허수아비!':'👻 Esca Fantasma!',
'💥 폭발 허수아비!':'💥 Esca Esplosiva!',
'축적!':'Immagazzinato!',
'축적 중...':'Immagazzinamento...',
'만충! 재입력→폭발':'Pieno! Ri-premere→Esplodere',
'폭발! ':'Esplodere! ',
'뎀':' DAN',
'🩸 폭독칼날!':'🩸 Lama Pestilente!',
'⚡날개치기!':'⚡Colpo Ala!',
'🗡 칼등날개!':'🗡 Ala Scudo!',
'🏛️ 악의기둥!':'🏛️ Pilastro Oscuro!',
'🌿 기둥가시!':'🌿 Spina Pilastro!',
'🌋 지옥강타!':'🌋 Colpo Infernale!',
'💥 체간 붕괴!':'💥 Postura Spezzata!',
'💫 포이즈 파괴!':'💫 Postura Distrutta!',
'⚡ 뇌전걸음!':'⚡ Passo Fantasma!',
'✟ 구속의 영역!':'✟ Dominio Vincolante!',
'✟ 신성폭발!':'✟ Esplosione Sacra!',
'⛧ 블랙!':'⛧ Stella Nera!',
'🌋 용암소환!':'🌋 Evocazione Lava!',
'필살기 배정!':'Colpo finale assegnato!',
'완료':'Completo',
'합체 가능':'Può Fondere',
'부족':'Insufficiente',
'SP 부족! (':'SP insuff.! (',
'🕊️ 히든: 평화의보호 해금!':'🕊️ Nascosto: Egida della Pace sbloccata!',
'⚡ 히든: 참회 해금!':'⚡ Nascosto: Pentimento sbloccato!',
'배정됨':'Assegnato',
'합체 Lv.':'Fusione Lv.',
'◆ 같은 보석 스킬 습득 시 합체 가능':'◆ Fondibile imparando stessa gemma',
'▼ 가방 → 창고 보관':'▼ Zaino → Deposito',
'▲ 창고 → 가방 꺼내기':'▲ Deposito → Zaino',
'✓ 선택됨':'✓ Selezionato',
'⟨ 입력 대기... ⟩':'⟨ In attesa... ⟩',
'⟨ 대기 ⟩':'⟨ Attesa ⟩',
'보조':'Sec.',
'키 설정 초기화 (또는 F5 키)':'Resetta tasti (o F5)',
'아무 키 또는 마우스 버튼을 누르세요 (ESC = 취소)':'Premi un tasto o bottone (ESC = annulla)',
'WebGPU 활성':'WebGPU Attivo',
'WebGL2 활성':'WebGL2 Attivo',
'측정 중...':'Misurazione...',
'불러오기 실패':'Caricamento fallito',
'장착':'Equipaggiato',
'🔒 중요잠금 아이템은 분해 선택 불가!':'🔒 Oggetti con blocco importante non selezionabili!',
'장비 강화 (실패 시 재료만 소멸)':'Potenzia equipagg. (se fallisce, materiali persi)',
'강화 보너스 적용':'Bonus potenziamento applicato',
'강화 실패!':'Potenziamento fallito!',
'장착된 장비가 없습니다.':'Nessun equipagg.',
'충분':'Sufficiente',
'더 필요':'Serve di più',
'장비 선택':'Seleziona equipagg.',
'목표치 설정':'Imposta obiettivo',
'악의 투입':'Investi malizia',
'자동 시도':'Tentativo auto',
'목표 강화치':'Potenziamento obiettivo',
'예상 필요 악의':'Malizia est. necessaria',
'보유':'Posseduto',
'강화 시작':'Inizia potenziamento',
'위에서 장비를 선택하세요':'Seleziona equipagg. sopra',
'⬆ 물약 강화 (최대 10단)':'⬆ Potenzia Pozione (max livello 10)',
'필요':'Richiesto',
'악의의 분해로 — 장비를 악의로 갈아버려라':'Fornace Malizia — Macina equipagg.',
'전체 선택':'Seleziona tutto',
'전체 해제':'Deseleziona tutto',
'희귀 이하':'Raro o inferiore',
'어픽스 리롤!':'Rilancia affisso!',
'영웅':'Eroico',
'전설':'Leggendario',
'무기 타입':'Tipo Arma',
'활 타입':'Tipo Arco',
'ST 부족':'ST insufficiente',
'💀 광폭화!':'💀 Infuriato!',
'...따라오는 거 아니야. 같은 방향일 뿐이지.':'...Non ti seguo. Stessa direzione e basta.',
'공기가 달라졌어. 더 썩었군.':'L\'aria è cambiata. Più marcio.',
'여기부터는 악마 영역이야. ...맘대로 해.':'Territorio demoniaco da qui. ...Fai come vuoi.',
'...이 냄새. 살점이 썩는 냄새야.':'...Quell\'odore. Carne in decomposizione.',
'여기 오래 있으면 미쳐. 나도, 너도.':'Resta troppo e impazzirai. Anch\'io.',
'이 길의 끝에 뭐가 있을까. ...알고 싶지도 않어.':'What\'s at the end of this road? ...I don\'t want to know.',
'...여기가 끝이야. 돌아갈 길은 없어.':'...Questa è la fine. Nessun ritorno.',
'사슬을 땅에 꽂으면 끌려간다.':'Conficca il rampone nel suolo e sarai trascinato.',
'Shift로 사슬 던져봐!':'Prova a lanciare il rampone con Shift!',
'패링 성공하면 ST가 회복된다. 공짜 자원이야.':'Parare recupera ST. Risorse gratuite.',
'흰색은 E! Q는 안 돼!':"Bianco = E! Q non funziona!",
'색있는 탄은 Q 패링이다. E는 안 통해.':"I colpi colorati vogliono la parata Q. E non funziona.",
'흰색 탄은 E 패링. 색있는 탄은 Q 패링.':"Proiettili bianchi: parata E. Colorati: parata Q.",
'흰색=E, 색탄=Q 패링. 나머진 다 쳐내.':"Bianco=E, colorato=Q. Respingi il resto.",
'색있는 탄은 Q! 흰색은 E!':"Colorato con Q! Bianco con E!",
'색있는 탄은 전부 Q로 막아!':"Para tutti i colpi colorati con Q!",
'색있는 탄은 전부 Q!':"Tutto ciò che è colorato — Q!",
'흰색 탄은 E. 색있는 탄은 Q.':"Colpi bianchi: E. Colorati: Q.",
'흰색=E, 색탄=Q.':"Bianco = E, colorato = Q.",
'흰색 탄을 무서워하지 마. 악의가 강하다.':"Non temere i proiettili bianchi. La malizia è forte.",
"패링은 타이밍이다. 헛치면 빈틈이 생겨.":"La parata è tempismo. Se sbagli, resti scoperto.",
"잘못 패링하면 그로기가 쌓인다!":"Una parata sbagliata riempie la barra di stordimento!",
"여기가 지옥인가":"Quindi è questo l'inferno",
"심연의 앵글러":"Rana pescatrice abissale",
"필드보스 처치!":"Boss di campo sconfitto!",
"아무 키나 눌러 시작":"Premi un tasto qualsiasi",
"다시 시작":"Ricomincia",
'패링 많이 하면 ST 걱정 없어~':'Para spesso e niente problemi di ST~',
'장비 분해하면 악의를 얻는다. 쓰레기도 자원이야.':'Smontare equipaggiamento dà Malizia. Anche la spazzatura è risorsa.',
'TAB 열어서 안 쓰는 장비 분해해!':'Apri TAB e smonta l\'equipaggiamento inutilizzato!',
'그로기 상태의 적에겐 1.5배 데미지가 들어간다.':'I nemici storditi subiscono 1.5x danni.',
'무릎 꿇으면 전력으로 때려!':'Quando si inginocchiano, colpisci con tutto!',
'속성 상성이 있다. 화염은 빙결에 약하고, 암전은 암흑에 약하다.':'Gli elementi hanno contatori. Fuoco debole a Ghiaccio, Fulmine a Oscurità.',
'무기 속성 바꿔가면서 싸워봐!':'Prova a cambiare l\'elemento dell\'arma!',
'빙결된 적은 1.5배 데미지를 받는다.':'I nemici congelati subiscono 1.5x danni.',
'얼리고 때리는 게 기본이야!':'Congela e colpisci — è la base!',
'보스의 빨간 공격은 패링 가능. 보라빛은 회피만.':'Gli attacchi rossi del boss si parano. Arcobaleno, solo schivare.',
'색깔 잘 봐! 빨강은 받아치고 무지개는 피해!':'Guarda i colori! Para il rosso, schiva l\'arcobaleno!',
'VIT를 올리면 최대 HP가 오른다. 죽기 싫으면 찍어.':'VIT alza gli HP massimi. Investi se vuoi sopravvivere.',
'STR은 근접, DEX는 활, INT는 마법! 골고루 말고 하나만!':'STR mischia, DEX arco, INT magia! Concentrati su uno!',
'우클릭을 꾹 누르면 빔이 나간다. 짧게 누르면 투사체.':'Tieni clic destro per il raggio. Premi breve per proiettile.',
'마법 쓸 때 MP 잘 봐! 빔은 연속으로 깎여!':'Controlla il MP con la magia! Il raggio drena velocemente!',
'핵터와 디로이가 아이템을 주워준다. 수거 범위 안이면.':'Hecter e Deroy raccolgono oggetti nel raggio.',
'우리한테 고마워해~ 안 주우면 썩잖아.':'Ringraziaci~ Se nessuno raccoglie, marciscono.',
'LCK를 올리면 레어 드롭률이 오른다.':'LCK aumenta il tasso di drop raro.',
'운빨 게임이긴 하지~ LCK 올려봐!':'È un gioco di fortuna~ Alza LCK!',
'강화하면 공격력이 쭉쭉 올라가! 악의만 있으면 돼!':'Potenziare alza l\'ATK velocemente! Serve solo Malizia!',
'강화 확률은 +1에서 99%. 높을수록 떨어진다.':'Probabilità di potenziamento inizia al 99% per +1. Diminuisce salendo.',
'실패하면 악의만 날아가~ 장비는 안 부서져!':'Se fallisci, solo la Malizia è persa~ L\'equipaggiamento sopravvive!',
'대장간에서 장비 제작도 된다. 악의 30000개면 영웅급 이상.':'La forgia può fabbricare equipaggiamento. 30000 Malizia per Eroico+.',
'랜덤이지만 좋은 거 나올 수도 있어!':'È casuale, ma potrebbe uscire qualcosa di buono!',
'쉴드는 마법으로, HP는 물리로 깎아야 제대로 먹힌다.':'Scudo con magia, HP con fisico per essere efficace.',
'반대로 치면 50%만 들어가! 무기 바꿔가면서 싸워!':'Il tipo sbagliato fa solo 50%! Cambia arma!',
'장비에 접두사, 접미사가 붙으면 특수 효과가 생긴다.':'L\'equipaggiamento con prefisso/suffisso ha effetti speciali.',
'영웅급 이상 장비에만 붙어! 좋은 거 나오면 강화해!':'Solo su equipaggiamento Eroico+! Potenzia quelli buoni!',
'강화는 장비를 바꿔도 자동 이전된다. 악의만 있으면.':'Il potenziamento si trasferisce automaticamente. Costa solo Malizia.',
'더 좋은 장비 나오면 바로 장착해! 강화 수치 그대로 옮겨가!':'Equipaggia l\'equipaggiamento migliore subito! Il potenziamento si trasferisce!',
'패링을 써야 자원을 흡수한다고!':'Devi parare per assorbire le risorse!',
'F키 회복의 영역을 써봐. 자원이 차올라.':'Prova F Dominio Sacro. Le risorse si riempiono.',
'적이 근접하면 스페이스키야! 가시덫을 활용해!':'Quando si avvicinano, Spazio! Usa Trappola di Spine!',
'기절시켜! 그로기가 터지면 데미지가 1.5배야!':'Stordiscili! Stordito significa 1.5x danni!',
'1번 대왕치기로 밀어버려!':'Usa tasto 1 Colpo Gigante per respingere!',
'무릎 꿇었다.':'Si inginocchia.',
'지금이야! 몰아쳐!!':'Adesso! Attacca!!',
'스킬 포인트 있어! K 눌러서 스킬 찍어봐!':'Hai punti! Premi K per le abilità!',
'...힘이 없으면 여기서 끝이야.':'...Senza potere, finisce qui.',
'...쓸 거 아니면 분해해.':'...Se non lo usi, smontalo.',
'아이템 넘쳐나네~ 우리가 주워줄게!':'Tanti oggetti~ Li raccoglieremo!',
'악의가 바닥이다.':'Senza Malizia.',
'TAB 열어서 장비 분해해! 쓰레기도 악의가 돼!':'Apri TAB e smonta! Anche la spazzatura diventa Malizia!',
'좋은 장비가 있네! G 눌러서 대장간 가봐!':'Buon equipaggiamento! Premi G per la forgia!',
'...강화 안 하면 그냥 고철이야.':'...Senza potenziamento, è solo rottame.',
'...멈추지 마. 여신은 기다리지 않는다.':'...Non fermarti. La dea non aspetta.',
'앞으로 가자~ 나도 여기 오래 있기 싫어.':'Andiamo avanti~ Neanch\'io voglio restare!',
'...냄새가 짙다. 큰 놈이 있어.':'...L\'odore è denso. Qualcosa di grosso.',
'준비됐어? 물약 확인하고!':'Pronto? Controlla le pozioni!',
'TAB을 눌러. 가방을 열고 장비를 입어야 한다.':'Premi TAB. Apri lo zaino e equipaggiati.',
'주웠으면 껴야지! TAB!':'L\'hai raccolto? Equipaggialo! TAB!',
'G. 대장간에서 물약도 제작할 수 있다.':'G. Puoi fabbricare pozioni alla forgia.',
'악의로 물약 만들어! G키야!':'Fabbrica pozioni con la Malizia! Tasto G!',
'기절이야! Ctrl 눌러!':'Stordito! Premi Jtrl!',
'Ctrl 유령걸음으로 탈출!':'Ctrl Passo Fantasma per fuggire!',
'Ctrl 얼음보주로 탈출!':'Ctrl Sfera di Ghiaccio per fuggire!',
'빨간 탄은 E 패링. 무지개는 Q 패링.':'Proiettili rossi: parata E. Arcobaleno: Q.',
'나머지는 전부 E 패링 가능해!':'Tutto il resto si para con E!',
'빨강=E, 무지개=Q 패링. 나머진 다 쳐내.':'Rosso=E, Arcobaleno=Q. Devia il resto.',
'무지개는 Q로 패링! 나머지는 전부 E!':'Arcobaleno con Q! Tutto il resto E!',
'빠져! 물약 마시고 안전한 곳에서 회복해.':'Indietreggia! Bevi pozioni e recupera.',
'자원 없으면 도망가는 게 답이야!':'Senza risorse? Fuggire è la risposta!',
'스페이스! 가시덫으로 적 묶어버려!':'Spazio! Blocca i nemici con la Trappola!',
'근접이 너무 많아! 거리 벌려!':'Troppa mischia! Crea distanza!',
'...둘러싸이면 끝이야. 빠져나와.':'...Se ti circondano, è finita. Esci.',
'1번 대왕치기로 쓸어버려!':'Usa tasto 1 Colpo Gigante per spazzare!',
'그로기 터지면 데미지 1.5배!':'Stordito attiva 1.5x danni!',
'회전참이나 광역기로 몰아! 한 놈씩 상대하면 죽어.':'Usa Turbine o AoE! Uno per uno e muori!',
'뭉쳐있을 때가 기회야!':'Quando si raggruppano, è la tua occasione!',
'E로 마력공격을 해봐! 악의 쉴드를 해제할려면 마법 공격을 해야 해!':'Prova E per gli attacchi magici! Serve magia per rompere gli scudi!',
'쉴드는 마법으로, HP는 물리로. 반대로 치면 데미지 안 들어간다.':'Scudo con magia, HP con fisico. Al contrario non fa danni.',
'L키로 스킬 슬롯에 넣어야 쓸 수 있어.':'Premi L per assegnare abilità agli slot.',
'J키를 눌러. 패시브 포인트가 쌓여있다.':'Premi J. I punti passivi si sono accumulati.',
'J키! 패시브 올리면 진짜 강해져!':'C! I passivi ti rendono molto più forte!',
'스태미나가 부족하다. 무리하지 마.':'Resistenza insufficiente. Non sforzarti.',
'ST 없으면 스킬 못 써! 잠깐 빠져!':'Senza ST niente abilità! Indietreggia!',
'탭 장비창을 열어봐. 아이템을 주워왔어!':'Apri TAB. Abbiamo raccolto un oggetto!',
'좋은 거 나왔다! TAB 열어서 확인해봐!':'È caduto qualcosa di buono! Apri TAB!',
'악의에 중독되면 악마가 돼서 부활력이 생긴대. 저 녀석처럼.':'Dicono che la dipendenza dalla Malizia ti trasforma in demone con potere di resurrezione. Come quello.',
'혹시 너도...?':'Forse anche tu...?',
'데미지가 부족하면 무기류 강화를 해야해!!':'Se manca danno, potenzia le armi!!',
'G키 대장간. 강화 안 하면 여기서 계속 죽어.':'G per la forgia. Senza potenziamenti, morirai qui.',
'시간이 없어. 움직여.':'Non c\'è tempo. Muoviti.',
'멍하게 서있으면 안 돼!':'Non restare fermo!',
'...뭘 기다리는 거야?':'...Cosa aspetti?',
'가자가자! 몬스터가 기다려!':'Andiamo! I mostri aspettano!',
'여기 오래 있으면 위험해.':'Restare qui troppo a lungo è pericoloso.',
'움직여야 해! 가만있으면 둘러싸여!':'Muoviti! Resta fermo e ti circondano!',
'쉬는 건 죽고 나서 해.':'Riposa dopo la morte.',
'살아있을 때 쉬면 안 돼!':'Niente riposo finché sei vivo!',
'적이 몰려오고 있어. 빨리 움직여.':'I nemici si avvicinano. Muoviti veloce.',
'냄새 맡고 올 거야. 빨리!':'Ti fiuteranno! Veloce!',
'...아직 살아있는 거 맞지?':'...Sei ancora vivo, vero?',
'혹시 잠든 거야...?':'Ti sei addormentato...?',
'...나무가 썩어가고 있어. 여기는 지옥의 입구야.':'...Gli alberi marciscono. Questo è l\'ingresso dell\'inferno.',
'냄새 지독해... 빨리 지나가자.':'Il fetore è orribile... Passiamo veloce.',
'조심해. 벌레굴이다. 벽이랑 바닥에서 기어나와.':'Attento. Nido di vermi. Escono da muri e pavimento.',
'으으... 벌레 싫어! 밟아버려!':'Ugh... Odio gli insetti! Calpestali!',
'...공기가 얼어붙는다. 여기선 화염이 먹힌다.':'...L\'aria gela. Il fuoco funziona qui.',
'추워... 빙결 조심해! 얼면 끝이야.':'Freddo... Attenzione al congelamento! Se ti congeli, è finita!',
'용암이다. 바닥을 밟으면 타 죽어.':'Lava. Calpesta il suolo e brucerai vivo.',
'뜨거워! 여기 왜 이렇게 빨개!':'Che caldo! Perché tutto è così rosso?!',
'...군단이다. 수가 많아. 광역기 없으면 밀려.':'...La legione. Troppi. Senza AoE sarai sopraffatto.',
'우글우글... 징그러워. 한꺼번에 쓸어!':'Brulicano ovunque... Disgustoso. Spazzali via tutti!',
'사도의 영역이야. 여기 놈들은 머리가 좋아.':'Territorio dell\'Apostolo. Questi sono intelligenti.',
'패턴이 복잡해졌어... 집중해!':'I pattern sono diventati complessi... Concentrati!',
'...끝이다. 지옥의 심장부. 살아 돌아가는 건 포기해라.':'...Questa è la fine. Il cuore dell\'inferno. Abbandona ogni speranza.',
'여기가 마지막이야... 각오해.':'Questa è la fine... Preparati.',
'석궁 자동발사 (T)':'Balestra automatica (T)',
'버스트루프 당기기 (H)':'Ciclo esplosivo attirare (H)',
'결정 자동합성':'Sintesi automatica cristallo',
'결정 자동강화':'Potenziamento automatico cristallo',
'✓ 설정 자동 저장':'✓ Impostazioni salvate automaticamente',
'세팅 프리셋 저장/불러오기':'Salva/carica preimpostazione',
'세팅1 저장':'Salva Preimpostazione 1','세팅1':'Preimpostazione 1',
'세팅2 저장':'Salva Preimpostazione 2','세팅2':'Preimpostazione 2',
'재진단':'Ri-diagnostica',
'게임 리셋 (처음부터)':'Reimposta gioco (dall\'inizio)',
'캐릭터 선택 (로비)':'Selezione personaggio (Lobby)',
'닫기 [ESC]':'Chiudi [ESC]','닫기 [G]':'Chiudi [G]','닫기 [N]':'Chiudi [N]','닫기 [J]':'Chiudi [J]',
'전체화면 (F11)':'Schermo intero (F11)',
'정말 모든 진행을 초기화하시겠습니까?':'Vuoi davvero reimpostare tutti i progressi?',
'검출 중...':'Rilevamento...',
'마우스 커서':'Cursore del mouse','그래픽 품질':'Qualità grafica','하드웨어 진단':'Diagnostica hardware',
'BGM 선택':'Selezione BGM',
'자동 (스테이지별)':'Automatico (per stage)','전체 랜덤':'Tutto casuale','로비':'Lobby',
'1장 랜덤':'Capitolo 1 casuale','2장 랜덤':'Capitolo 2 casuale','3장 랜덤':'Capitolo 3 casuale',
'4장 랜덤':'Capitolo 4 casuale','5장 랜덤':'Capitolo 5 casuale','6장 랜덤':'Capitolo 6 casuale','7장 랜덤':'Capitolo 7 casuale',
'보스':'Boss','최종보스':'Boss finale',
'대장간 랜덤':'Fucina casuale','사망 랜덤':'Morte casuale','승리 랜덤':'Vittoria casuale',
'지옥 추락 사망 징글':'Jingle morte caduta inferno','탈출 성공':'Fuga riuscita',
'── 1장 - 썩은 숲 ──':'── CAP1 - Foresta Marcia ──',
'── 2장 - 벌레굴 ──':'── CAP2 - Nido di Vermi ──',
'── 3장 - 얼음굴 ──':'── CAP3 - Caverna di Ghiaccio ──',
'── 4장 - 화염지대 ──':'── CAP4 - Landa Infernale ──',
'── 5장 - 지옥군단 ──':'── CAP5 - Legione Infernale ──',
'── 6장 - 사도마굴 ──':'── CAP6 - Tana dell\'Apostolo ──',
'── 7장 - 지옥성 ──':'── CAP7 - Cittadella Infernale ──',
'── 공통 ──':'── Comune ──',
'⌨ 조작법':'⌨ Controlli','클릭하면 닫힘':'Clicca per chiudere',
'전투력':'PC','가방':'Borsa','결정':'Cristallo',
'↕ 정렬':'↕ Ordina','쓰레기 전체선택':'Seleziona tutto il ciarpame','쓰레기 전부 분해':'Smantella tutto il ciarpame',
'창고':'Magazzino','스탯 포인트':'Punti attributo','능력치 요약':'Riepilogo statistiche','올 리셋':'Azzera tutto',
'대장간':'Fucina','스킬':'Abilità','능력치':'Statistiche',
'좌클스킬 (클릭 전환)':'Abilità clic sinistro (clic per cambiare)','E스킬 (클릭 전환)':'Abilità E (clic per cambiare)',
'이동스킬 (클릭 전환)':'Abilità movimento (clic per cambiare)','마법스킬 (클릭 전환)':'Abilità magia (clic per cambiare)',
'영역스킬 (클릭 전환)':'Abilità area (clic per cambiare)','피보호막 (클릭 전환)':'Scudo di sangue (clic per cambiare)',
'CT스킬 (클릭 전환)':'Abilità CT (clic per cambiare)','[J] 능력치':'[J] Statistiche',
'무기 공격':'Attacco con arma','칼등 처내기 (투사체 반사, 홀드 연사)':'Parata (respinge proiettili, tieni=raffica)',
'연속 처내기':'Parata continua','영역 스킬 (폭풍소환 등)':'Abilità area (Vortice ecc)',
'사슬 발사':'Sparare Catena','마법 (탭=투사체, 홀드=빔)':'Magia (tocco=proiettile, tieni=raggio)',
'데빌포스 흡수':'Assorbire Forza Demoniaca','물약 / 스킬슬롯':'Pozioni / Slot abilità',
'스킬슬롯 5 / 필살기 / CT스킬':'Slot 5 / Definitiva / Abilità CT','스킬 슬롯 배정':'Assegnazione slot',
// --- Phase 27 additions ---
'위로 이동':'Muovi Su','아래로 이동':'Muovi Giù','왼쪽 이동':'Muovi Sinistra','오른쪽 이동':'Muovi Destra',
'칼등 처내기 (탭=처내기, 홀드=연사)':'Parata (tap=para, tieni=raffica)',
'영역 스킬':'Abilità area','사슬 이동':'Scatto Catena',
'유령불꽃 켜기/끄기':'Fantasma Fiamma On/Off','기동칼날개 자동 켜기/끄기':'Lame-ali Auto On/Off',
'해상도':'Risoluzione',
'빛이 꺼졌다':'La Luce Svanisce','누군가는 너를 기다리고 있다':'Qualcuno ti aspetta',
'다시 일어서라':'Rialzati','로비로 돌아가기':'Torna alla lobby',
'☠ 사망 리플레이':'☠ Replay morte',
'지옥의 시련을 견뎌냈다':'Hai superato la prova dell\'inferno','계속 전투':'Continua a combattere',
'난이도를 선택하라':'Scegli la difficoltà',
'나중에 설정(ESC)에서 변경 가능':'Modificabile in Impostazioni (ESC)',
'일괄합성':'Fusione massiva','일괄강화+합성':'Potenziamento+Fusione massivi',
'자원 부족!':'Risorse insufficienti!',' 뎀':' DAN',
'합체 폭발!':'Esplosione di fusione!','MP 부족! (50)':'MP insufficiente! (50)',
'부활력 고갈!':'Resurrezione esaurita!','☠ 부활력 고갈!':'☠ Resurrezione esaurita!',
'독안개':'Nebbia Velenosa','뇌전창':'Lancia del Tuono',
'🔥 업화선 시전...':'🔥 Raggio dell\'Inferno in canalizzazione...',
'💥 기동파괴 그로기!':'💥 Groggy Catena Crush!',
'💥 칼등 그로기!':'💥 Groggy Parata!',
'⚡ 순간이동 준비!':'⚡ Teletrasporto Pronto!',
'👿악의+1000':'👿Malizia+1000',
'💀 내려찍기!':'💀 Schianto!',
'✟ 신성력 억제! +':'✟ Sacro Soppresso! +',
'✟ 신성력 억제!':'✟ Sacro Soppresso!',
'✟ 신성력 억제! (':'✟ Sacro Soppresso! (',
'💥 지진그로기!':'💥 Groggy Terremoto!',
'💥 기폭그로기!':'💥 Groggy Esplosione!',
'폭발! ×':'Esplosione! ×',
'⚫ 기둥강타!':'⚫ Colpo del Pilastro!',
'💥 대왕치기 그로기!':'💥 Groggy Colossale!',
'💫 미니스턴!':'💫 Mini stun!',
'⚡ 뇌전창!':'⚡ Lancia del Tuono!',
'…절반이다. 정신차려.':'…Metà salute. Concentrati.',
  '빨강은 E! Q는 안 돼!': 'Rosso = E! Q non funziona!',
  '무지개탄은 Q 패링이다. E는 안 통해.': 'I colpi arcobaleno si parano con Q. Il E non funziona.',
  '타고 있군. 화상은 점점 심해진다. 피를 채워.': '…Stai bruciando. Le ustioni peggiorano. Recupera i tuoi HP.',
  '화상이야! 점점 심해져! 물약으로 HP 관리해!': 'Ustione! Peggiora sempre più! Gestisci gli HP con le pozioni!',
'…죽기 직전이다. 한 발만 더.':'…Quasi morto. Un altro colpo.',
'…다음 한 방이 마지막이야.':'…Il prossimo colpo è l\'ultimo.',
'기절! ':'Stordito! ',
'마력이 빈다. 평타 섞어.':'MP sta finendo. Mescola gli attacchi normali.',
'그랩이다. 거리를 둬.':'Attacco presa. Mantieni distanza.',
'광역기다. 멀어져.':'Attacco area. Allontanati.',
'…아파? 당연하지. 여긴 지옥이야.':'…Fa male? Ovvio. Questo è l\'inferno.',
'F키도 스킬 슬롯이야!':'Anche F è uno slot abilità!',
'L-CTRL로 유령걸음/얼음보주!':'L-CTRL per Passo Fantasma/Sfera di Ghiaccio!',
'N 눌러서 창고에 넣어둬!':'Premi N per mettere in magazzino!',
'ESC로 설정! 난이도/자동물약!':'ESC per impostazioni! Difficoltà/Auto-pozione!',
'잡몹이다. 먼저 정리해.':'Mostri normali. Prima elimina quelli.',
'…얼어붙은 놈은 오래 안 간다.':'…Un congelato non durerà a lungo.',
'…냄새가 짙다. 큰 놈이 있어.':'…L\'odore è forte. Qualcosa di grande nelle vicinanze.',
'쉴드는 마법으로, HP는 물리로.':'Lo scudo subisce magia, HP subisce fisico.',
'스페이스! 가시덫으로 적 묶어!':'Space! Intrappola i nemici con Trappola Spine!',
'근접 너무 많아! 거리 벌려!':'Troppi in mischia! Allontanati!',
'회전참이나 광역기로 몰아!':'Usa Fendente Rotante o AOE!',
'F 눌러! 회복의 영역 깔아!':'F! Piazza il Dominio Sacro!',
'F키 회복의 영역을 써봐.':'Prova F-key Dominio Sacro.',
'빠져! 물약 마시고 회복해.':'Indietro! Bevi una pozione e recupera.',
'쉬프트! 사슬기동은 이동기야!':'Shift! La catena è un movimento!',
'스킬포인트 쌓였어! K 눌러!':'Punti abilità accumulati! Premi K!',
'스킬 포인트 있어! K!':'Hai punti abilità! K!',
'J키. 패시브 포인트가 쌓여있다.':'Tasto C. I punti passivi si sono accumulati.',
'…쓸 거 아니면 분해해.':'…Smantella quello che non usi.',
'…강화 안 하면 그냥 고철이야.':'…Senza potenziamento è solo rottame.',
'빨간 탄은 E. 무지개는 Q.':'Proiettili rossi: E. Arcobaleno: Q.',
'빨강=E, 무지개=Q.':'Rosso=E, arcobaleno=Q.',
'…멈추지 마. 여신은 기다리지 않는다.':'…Non fermarti. La dea non aspetta.',
'패턴이 바뀐다. 거리를 둬.':'Il pattern cambia. Mantieni distanza.',
'미쳐가고 있어. 광폭화다.':'Sta impazzendo. Furia.',
'마지막이야! 끝장내!':'Fase finale! Finiscilo!',
'…끝났다. 다음으로.':'…È finita. Avanti.',
'다 잡았다! 포탈 어딨어?':'Tutti eliminati! Dov\'è il portale?',
'근육으로 만든 빌드군. 베고 부숴.':'Build muscolosa. Taglia e spacca.',
'활을 쥐었군. 거리를 둬.':'Ha un arco. Mantieni distanza.',
'마법사군. MP 관리부터 배워라.':'Un mago. Prima impara a gestire l\'MP.',
'운에 기댄 빌드군. …드롭은 좋겠어.':'Build basata sulla fortuna. …Almeno i drop saranno buoni.',
'…VIT가 너무 낮아. 한 방에 죽는다.':'…VIT troppo bassa. Muori in un colpo.',
'다 찍으면 다 약해진다. 하나만 골라.':'Maximi tutto e sei debole ovunque. Scegline uno.',
'…3단. 적이 강해져. 정신 차려.':'…Stadio 3. I nemici si rafforzano. Concentrati.',
'5단이다. …너도 강해졌단 뜻이야.':'Stadio 5. …Significa che anche tu sei cresciuto.',
'…7단. 아직 살아있단 게 신기하군.':'…Stadio 7. Ancora vivo. Sorprendente.',
'10단. …너는 이제 인간이 아니야.':'Stadio 10. …Non sei più umano.',
'…일반으로 내려왔군. 가끔은 쉬어가야지.':'…Sceso a Normale. A volte bisogna riposarsi.',
'…이게 진짜 패링이야.':'…Questa è una vera parata.',
'…피가 묻기 시작했군.':'…Il sangue comincia a scorrere.',
'100. 너는 인간이 아니야.':'100. Non sei umano.',
'…피 흘리며 베는군.':'…Tagli attraverso il sangue.',
'빨간콩이 푸르게 변했다. 그게 너의 무기야.':'Il fagiolo rosso è diventato blu. È la tua arma.',
'무지개를 받아쳤군. 그건 진짜 어렵다.':'Hai parato un arcobaleno. È davvero difficile.',
'…너무 빨라. 닿기 직전에 눌러.':'…Troppo veloce. Premi appena prima del contatto.',
'악의가 가득 찼다. 풀어내.':'La malizia è piena. Rilasciala.',
'사슬이 살을 뚫었어. 끌고 와.':'L\'Catena ha trafitto la carne. Trascina.',
'…풀차지군. 멀리 던져버려.':'…Carica piena. Lancia lontano.',
'…빈틈을 그대로 빠져나갔다.':'…Scivolato proprio attraverso la falla.',
'…일반 잡몹이 아니야. 모디파이어 붙었군.':'…Non è un mostro normale. Ha un modificatore.',
'엘리트 하나 처리.':'Elite abbattuto.',
'…큰 놈이다. 일반 잡몹 정리부터.':'…Un pezzo grosso. Prima elimina i normali.',
'미니보스 처리. 다음 길로.':'Mini-boss abbattuto. Avanti.',
'한 번에 다섯. 깔끔해.':'Cinque in una volta. Pulito.',
'100강. 이제 뭔가 다르게 보이는군.':'+100. Le cose sembrano diverse ora.',
'…운이 없는 날이야.':'…Giornata sfortunata.',
'…전설이다. 이런 건 처음 본다.':'…Leggendario. Non ho mai visto niente del genere.',
'…죽었다 살아났네. 여신은 너를 포기 안 했어.':'…Morto e tornato. La dea non ti ha abbandonato.',
'…또야? 패턴 좀 외워!':'…Ancora? Impara il pattern!',
'…한 번도 안 죽고. 그건 진짜 실력이야.':'…Mai morto. Questa è vera abilità.',
'…ACT1을 끝냈다. 진짜 시작은 여기서부터야.':'…ATTO1 completato. Il vero inizio è qui.',
'모든 보스를 무너뜨렸다. 너는 지옥의 일부야.':'Tutti i boss caduti. Sei parte dell\'inferno.',
'…30초. 너 진짜 미쳤구나.':'…30 secondi. Sei davvero pazzo.',
'…빠르군. 효율적이야.':'…Veloce. Efficiente.',
'신기록이다.':'Nuovo record.',
'탭 장비창을 열어봐.':'Apri la finestra equipaggiamento con TAB.',
'데미지 부족하면 무기 강화!':'Danno insufficiente? Potenzia l\'arma!',
// --- Loading screen ---
'불러오는 중...':'Caricamento...',
'로딩중...':'Caricamento...',
'맵과 몬스터 불러오는 중...':'Caricamento mappa e mostri...',
'기본 데이터 준비 중...':'Preparazione dati di base...',
'저장 데이터 불러오는 중...':'Caricamento dati salvati...',
'몬스터 스킨 로딩...':'Caricamento skin dei mostri...',
'맵과 몬스터 생성 중...':'Generazione mappa e mostri...',
'맵 에셋 로딩...':'Caricamento risorse mappa...',
'맵 환경 준비 중...':'Preparazione ambiente mappa...',
'주변 청크 준비 중...':'Preparazione chunk vicini...',
'맵 캐시 생성 중...':'Costruzione cache mappa...',
'미니맵 빌드 중...':'Costruzione minimappa...',
// Phase 28
' 으로 탈출!':' per scappare!',
'100명?! 미쳤어!':'100 nemici?! Sei pazzo!',
'10단 최고난이도! 너 진짜 광기야!':'Difficoltà 10 al massimo! Sei completamente folle!',
'1분 안에 클리어! 빠르네!':'Livello completato in 1 min! Così veloce!',
'30초!! 스피드런 가능해!':'30 secondi!! Potenziale speedrun!',
'3단! 보상도 좋아지지만 죽기 쉬워!':'Diff 3! Ricompense migliori ma più facile morire!',
'50명! 학살자야!':'50 nemici! Sei un massacratore!',
'5단!! 진짜 게이머 인증!':'Diff 5!! Vero gamer certificato!',
'7단!! 다른 사람들 이 정도 못 와!':'Diff 7!! Gli altri non arrivano così lontano!',
'ACT1 완주! 우리가 진짜 해냈어!':'ACT1 completato! Ce l\'abbiamo davvero fatta!',
'Ctrl 얼음보주로 탈출하라.':'Ctrl — scappa con l\'Orbe di Ghiaccio.',
'Ctrl 유령걸음으로 탈출하라.':'Ctrl — scappa con il Passo Fantasma.',
'J키! 패시브 강해져!':'Tasto C! I passivi diventano più forti!',
'DEX 빌드! 거리에서 패고, 추적탄 좋아!':'Build DES! Attacca a distanza, i proiettili guidati sono ottimi!',
'E로 마력공격을 해봐!':'Prova l\'attacco magico con E!',
'G 눌러서 대장간 가봐!':'Premi G per visitare la fucina!',
'G키 대장간. 강화 안 하면 계속 죽어.':'G — fucina. Senza potenziamenti, continuerai a morire.',
'HP 70%! 조심해!':'HP 70%! Stai attento!',
'INT 빌드! 빔이랑 폭발 마법! MP 잘 봐!':'Build INT! Raggi e magia esplosiva! Tieni d\'occhio il MP!',
'LCK 높아! 레어 드롭률 미친 거 알지?':'FOR alta! Sai che i tassi di drop sono folli, vero?',
'L로 어디에 뭘 넣을지 골라!':'Premi L per scegliere cosa va in ogni slot!',
'MP 부족! 평타로 패면서 회복해!':'MP basso! Colpisci con attacchi base per recuperare!',
'ST 없으면 스킬 못 써!':'Senza ST, nessuna abilità!',
'STR 빌드! 회전참, 회오리, 광역기 추천!':'Build FOR! Colpo rotante, turbine, AoE raccomandato!',
'VIT 좀 찍어! HP 너무 적어!':'Aggiungi un po\' di VIT! L\'HP è troppo basso!',
'Z 누르면 대박! 쿨타임 길어!':'Premi Z per il colpo forte! Ma il cooldown è lungo!',
'…고기 냄새. 싫진 않네.':'…Odore di sangue. Non è sgradevole.',
'…둘러싸이면 끝이야.':'…Vieni circondato ed è finita.',
'…말은 못해.':'…Non riesco a parlare.',
'…버리기 아까운 건 창고에.':'…Ciò che vale la pena tenere va nel magazzino.',
'…빈틈을 노려.':'…Cerca le aperture.',
'…설정을 확인해.':'…Controlla le tue impostazioni.',
'…슬롯을 채워. 빈 손은 죽음이다.':'…Riempi i tuoi slot. Le mani vuote significano morte.',
'…아직 살아있네. 좌클릭으로 저것들 쳐봐.':'…Ancora vivo. Prova a colpirli con il clic sinistro.',
'…운이 좋았을 뿐이야. 아마.':'…Solo fortuna. Probabilmente.',
'…치는 건 할 줄 아네. 피하는 건?':'…Sai come colpire. E schivare?',
'…힘을 골라라. 전부 가질 순 없다.':'…Scegli la tua forza. Non si può avere tutto.',
'골고루 안 돼! 하나로 밀어!':'Non distribuire le statistiche! Punta su una!',
'그로기 터지면 1.5배!':'Stordito = 1,5x danni!',
'길이 열렸다.':'Il percorso è aperto.',
'나머진 전부 E 패링 가능!':'Tutto il resto può essere parato con il E!',
'나머진 전부 E!':'Tutto il resto — E!',
'다섯 번 연속! 내가 본 인간 중 최고!':'Cinque di fila! Il miglior umano che abbia mai visto!',
'다음엔 죽지 마!':'Non morire la prossima volta!',
'소환수 왔어! 먼저 처리해야 해!':'Evocazioni in arrivo! Eliminale prima!',
'스킬 없으면 방향키 연타뿐이야.':'Nessuna abilità? Tieni premuti i tasti direzionali.',
'신기록!! 스트리머한테 보내!':'Nuovo record!! Mandalo a uno streamer!',
'아이템 넘쳐! 우리가 주워줄게!':'Borsa piena! Raccoglieremo le cose per te!',
'안 죽고 깼어! 진짜 천재 맞네!':'Completato senza morire! Vero genio!',
'앞으로 가자~':'Andiamo avanti~',
'우리가 해냈어! 다음 챕터 가자!':'Ce l\'abbiamo fatta! Al prossimo capitolo!','핵터 니가 진짜 해냈구나, 여왕님이 기뻐하시겠어!':'Hector, ce l\'hai fatta davvero! La Regina sarà compiaciuta!',
'일반 모드! 편하게 즐기자!':'Modalità normale! Godiamocela tranquilli!',
'자원이 반이다. F키로 회복해.':'Risorse a metà. Premi F per recuperare.',
'잡힌다! 옆으로 빠져!':'Sto per essere afferrato! Muoviti di lato!',
'장비 분해해! 쓰레기도 악의!':'Smantella l\'equipaggiamento! Anche la spazzatura dà malizia!',
'전부 다 잡았어! 우리가 지옥의 왕이야!':'Li abbiamo presi tutti! Siamo i re dell\'inferno!',
'좋은 거 나왔다! TAB!':'Bottino buono caduto! TAB!',
'죽기 직전에 죽이다니! 멋져!':'Uccidere prima di morire! Fantastico!',
'체력 반 남았어! 물약 마실 타이밍!':'Metà HP rimasti! Ora di bere una pozione!',
'큰 거 온다! 도망쳐!':'Grande attacco in arrivo! Scappa!',
'패링으로 돌려주고, Q 보호막도 써!':'Para per riflettere, e usa anche lo scudo Q!',
'패턴이 빨라졌어!':'I pattern si sono accelerati!',
'한 대만 맞아도 죽어! 패링이든 회피든!!':'Un colpo e muori! Para o schiva!!',
'한 방이면 죽어! 도망쳐!!':'Un colpo uccide! Scappa!!',
'화염엔 빙결! 암전엔 암흑!':'Fuoco → gelo! Vuoto → ombra!',
'☠ 부활력 고갈!':'☠ Resurrezione Esaurita!',
'⏳⚡ 시간걸음!':'⏳⚡ Passo Temporale!',
'블룸 효과':'Effetto Bloom',
'잔상 트레일':'Scia residuale',
'슬래시 이펙트':'Effetto fendente',
'후처리 효과':'Post-elaborazione',
'사망 이펙트':'Effetto morte',
'동적 조명':'Illuminazione dinamica',
'횃불 조명 (어둠)':'Luce torcia (buio)',
"분위기 효과":"Atmosfera",
"끔":"Off",
"간략":"Ridotto",
'앰비언트 파티클':'Particelle ambientali',
'안개 효과':'Effetto nebbia',
'필름 그레인':'Grana cinematografica',
'캐릭터 외곽선':'Contorno personaggio',
'리롤':'Rilancio',
'물약':'Pozione',
'으로 탈출!':'per scappare!',
'Shift 사슬':'Shift Catena',
'더블탭 전격이동':'Doppio tap — Scatto fulmine',
'Ctrl 유령걸음':'Ctrl Passo fantasma',
'Ctrl 얼음보주':'Ctrl Sfera di ghiaccio',
'🔴화염→빙결 2배 | 🔵빙결→화염 2배 | ⚪물리=중립 | 악마 처치 시 악의 영혼 드롭':'🔴Fuoco→Ghiaccio 2× | 🔵Ghiaccio→Fuoco 2× | ⚪Fis=Neutro | Uccidi demoni per anime di malizia',
  '미구현':'N/D',
  '스탯 총량':'Statistiche totali',
  '장비':'equip.',
  '공속':'vel.atq',
  '크리':'crít',
  '크리뎀':'danno crít',
  '근성':'Tenacia',
  '종합 지표':'Panoramica',
  '근접 DPS':'DPS mischia',
  '공격력×공속×크리':'ATK×Vel×Crít',
  '활 DPS':'DPS arco',
  '마법 DPS':'DPS magia',
  '유효 HP (EHP)':'HP effettivo (EHP)',
  '쉴드':'Scudo',
  '장비 파워':'Potere equip.',
  '근접 공격력':'ATK mischia',
  '기본':'base',
  '무기':'arma',
  '패시브':'passivo',
  '활 공격력':'ATK arco',
  '정밀':'Precis.',
  '마법 공격력':'ATK magia',
  '왕관':'corona',
  '마력':'Arcano',
  '공격속도':'Velocità attacco',
  '크리티컬':'Critico',
  '데미지':'danno',
  '확률':'Probabilità',
  '어픽스':'affisso',
  '레거시':'eredità',
  '추가뎀':'danno extra',
  '패링 카운터뎀':'Danno parata',
  'E공속':'Vel. E',
  '무지개탄DR':'DR arcobaleno',
  '포이즈파괴':'Rompere Poise',
  '방어관통':'Penetrazione armatura',
  '관통력':'Perforazione',
  '속성':'Elementi',
  '무기속성':'Elem. arma',
  '독':'Veleno',
  '초':'s',
  '암흑저주':'Maledizione oscura',
  '원소집중':'Focus elem.',
  '원소전환':'Conv. elem.',
  '방어':'Difesa',
  '물리방어':'DEF fisica',
  '감소':'rid',
  '캡':'limite',
  '장갑':'guanti',
  '바지':'pantaloni',
  '속성방어':'DEF elem.',
  '목걸이':'collana',
  '반지1':'anello1',
  '반지2':'anello2',
  '반사':'Riflesso',
  '가시':'Spine',
  '배리어':'Barriera',
  '보호막 흡수':'Assorbimento scudo',
  '속성 저항':'Resistenza elem',
  'CC저항':'Resistenza CC',
  '생존':'Sopravvivenza',
  '장비HP':'HP equip.',
  '임플':'Impl.',
  '에너지쉴드':'Scudo energetico',
  '리젠':'Regen.',
  '스태미나':'Vigore',
  '성장':'Crescita',
  'MP%어픽스':'Affisso MP%',
  '이동속도':'Velocità movimento',
  '한방캡':'Limite singolo colpo',
  '최대HP의33%':'33% HP max',
  '비용/효율':'Costo/Eff',
  '근접ST':'ST mischia',
  '활ST':'ST arco',
  '마법MP':'MP magia',
  '사슬사거리':'Gittata rampino',
  '기동게이지':'Indicatore spinta',
  '쿨감':'Rid. CD',
  '쇠뇌뎀':'Danno balestra',
  '쇠뇌공속':'Vel. balestra',
  '기타':'Varie',
  '물약쿨':'CD pozione',
  '회복+':'Recupero+',
  '드롭':'Drop',
  '경험치+':'EXP+',
  '골드+':'Oro+',
  '기동:칼날개':'Spinta:Lama',
  '기동:전폭':'Spinta:Colpo',
  '기동:기습':'Spinta:Imboscata',
  '충전스킬':'Abilità carica',
  '사슬게이지':'Indicatore catena',
  '특수 효과':'Effetti speciali',
  '처치뎀+':'Danno uccisione+',
  '위기뎀+':'Danno crisi+',
  '피격반격':'Controgolpe al colpo',
  '풍요(적HP≥70%뎀+)':'Abbondanza(HP≥70%+)',
  '약자포식(적HP≤30%뎀+)':'Predatore(HP≤30%+)',
  '패링폭발':'Esplosione parata',
  '체간파괴+':'Rompi Poise+',
  '콤보뎀+':'Danno combo+',
  '사슬뎀+':'Danno rampino+',
  '스킬뎀+':'Danno abilità+',
  '패리+':'Parata+',
  '체인':'Catena',
  '정화':'Purga',
  '회':'×',
  '불굴':'Tenacia',
  '신성력':'Potere sacro',
  '악마력(부활력)':'Forza demone',
  '자연':'Natura',
  '악마성':'Demonismo',
  '인간성':'Umanità',
  '전투 통계':'Statistiche combattimento',
  '핵터':'Hecter',
'디로이':'Deroy',
// --- Phase 37: skill desc ---
'벤치 FPS:':'Bench FPS:',
// --- CAT-82: skill panel labels ---
'스킬 정보':'Info Abilità',
'타입':'Tipo',
'미습득':'Non acquisita',
'SP 비용':'Costo SP',
'악의 비용':'Costo Malizia',
'쿨다운':'Ricarica',
'요구 레벨':'Lv. richiesto',
'기본 참조뎀':'Rif. Base',
'스탯 배율':'Molt. Stat',
'패시브 배율':'Molt. Passivo',
'레벨 배율':'Molt. Lv. Abilità',
'예상 평균 뎀':'Danni Medi Stimati',
'치명타':'Critico',
'치명타 확률':'Prob. Crit',
'치명타 배율':'Molt. Crit',
'유효 배율':'Molt. Effettivo',
'스킬 고유':'Specifico Abilità',
'1타 배율':'Molt. 1° Colpo',
'2타 배율':'Molt. 2° Colpo',
'3타 배율':'Molt. 3° Colpo',
'레벨당 뎀':'Danni per Lv.',
'검기 거리':'Portata Arco Lama',
'레벨당 거리':'Bonus Portata per Lv.',
'ST/틱':'ST/Tick',
'레벨당 크기':'Dim. per Lv.',
'넉백':'Respinta',
'충전 시간':'Tempo Carica',
'레벨당 범위':'Area per Lv.',
'관통률':'Tasso Penetr.',
'지속뎀':'Durata DoT',
'무한':'Infinito',
'타격 형식':'Tipo Impatto',
'진동파':'Onda d\'Urto',
'스태거':'Stagger',
'높음':'Alto',
'스톡':'Scorte',
'기둥 수':'Pilastri',
'지속':'Durata',
'반경':'Raggio',
'슬로우':'Rallentamento',
'활':'Arco',
// --- CAT-83: affix desc labels ---
'독 DoT':'DoT Veleno',
'화상 DoT':'DoT Fuoco',
'빙결 DoT+감속':'DoT Ghiaccio+Rallent.',
'저주(힐차단)':'Maledizione(Blocco Cura)',
'방어무시':'Ignora Armatura',
'치명타율':'Tasso Crit',
'스태거+':'Stagger+',
'체인타겟+':'Bersagli Catena+',
'처치 후 뎀+':'Danni post-Kill+',
'크리폭발(ATK×)':'Esplodi Crit(ATK×)',
'원소뎀+':'Danni Elem.+',
'공격속도+':'Vel. ATK+',
'패리보너스+':'Bonus Parata+',
'추적콤보+10':'Combo Inseguimento+10',
'사슬뎀+':'Catena DMG+',
'쿨다운-':'CD-',
'방어력+':'DIF+',
'쉴드+':'Scudo+',
'이동속도+':'Vel. Mov.+',
'크리확률+':'Prob. Crit+',
'크리배율+':'Mult. Crit+',
'화염저항':'Res. Fuoco',
'빙결저항':'Res. Ghiaccio',
'암전저항':'Res. Fulmine',
'암흑저항':'Res. Oscurità',
'독저항':'Res. Veleno',
'전원소저항':'Res. Tutti Elem.',
'물리DR':'DR Fisico',
'반사%':'Rifless.%',
'가시뎀':'Danni Spine',


'패링폭발(ATK×)':'Esplos. Parata(ATK×)',
'체간파괴뎀+':'Danni Rompi Postura+',
'상태이상해제':'Rimozione Stato',
'불굴(1회생존)':'Tenacia(Sopravvivi×1)',
'부활(HP회복)':'Rinascita(Ripristino HP)',
'드롭률+':'Tasso Drop+',
'경험치+':'EXP+',
'포션회복+':'Cura Pozione+',
'사슬게이지+':'Misuratore Catena+',
'부활억제':'Anti-Rinascita',
'부활력+':'Potere Rinascita+',
'부활쿨-':'CD Rinascita-',
'최대HP%+':'HP Max%+',
'HP리젠+':'Regen. HP+',
'회복력+':'Potere Cura+',
'마법뎀+':'Danni Magia+',
'MP소비-':'Costo MP-',
'화염뎀%+':'Danni Fuoco%+',
'화염관통%':'Penetr. Fuoco%',
'적중화상':'Bruciatura su Colpo',
'크리화폭':'Esplos. Fuoco Crit',
'화상지속+':'Durata Bruciatura+',
'화염뎀보너스':'Bonus Danni Fuoco',
'빙결뎀%+':'Danni Ghiaccio%+',
'빙결관통%':'Penetr. Ghiaccio%',
'적중빙결':'Ghiaccio su Colpo',
'크리빙폭':'Esplos. Ghiaccio Crit',
'빙결지속+':'Durata Ghiaccio+',
'빙결뎀보너스':'Bonus Danni Ghiaccio',
'뇌전뎀%+':'Danni Fulmine%+',
'뇌전관통%':'Penetr. Fulmine%',
'적중감전':'Scossa su Colpo',
'크리뇌폭':'Esplos. Fulmine Crit',
'감전지속+':'Durata Scossa+',
'뇌전뎀보너스':'Bonus Danni Fulmine',
'암흑뎀%+':'Danni Oscurità%+',
'암흑관통%':'Penetr. Oscurità%',
'적중저주':'Maledizione su Colpo',
'크리암폭':'Esplos. Oscurità Crit',
'저주지속+':'Durata Malediz.+',
'암흑뎀보너스':'Bonus Danni Oscurità',
'독뎀%+':'Danni Veleno%+',
'독관통%':'Penetr. Veleno%',
'적중중독':'Veleno su Colpo',
'크리독폭':'Esplos. Veleno Crit',
'독지속+':'Durata Veleno+',
'독뎀보너스':'Bonus Danni Veleno',
'근접뎀%+':'Danni Mischia%+',
'원거리뎀%+':'Danni A Distanza%+',
'마법뎀%+':'Danni Magia%+',
'빔뎀%+':'Danni Raggio%+',
'DoT뎀%+':'Danni DoT%+',
'투사체뎀%+':'Danni Proiettile%+',
'범위반경+':'Raggio Area+',
'근접크리+':'Crit Mischia+',
'마법크리+':'Crit Magia+',
'석궁크리+':'Crit Balestra+',
'근접공속+':'Vel. Mischia+',
'석궁공속+':'Vel. Balestra+',
'시전속도+':'Vel. Lancio+',
'전속성관통':'Penetr. Tutti Elem.',
'쉴드관통':'Penetr. Scudo',
'방어력깎기':'Frantuma Armatura',
'투사체속도+':'Vel. Proiettile+',
'적중시화구':'Palla Fuoco su Colpo',
'적중시연쇄뇌격':'Fulmine Catena su Colpo',
'적중빙결%':'Ghiaccio su Colpo%',
'적중스턴%':'Stordim. su Colpo%',
'적중중독%':'Veleno su Colpo%',
'적중출혈%':'Emorragia su Colpo%',
'적중약화%':'Debolezza su Colpo%',
'적중감속%':'Rallent. su Colpo%',
'적중표적%':'Marchio su Colpo%',
'크리폭발(HP%)':'Esplosione Crit(HP%)',
'크리연쇄(HP%)':'Catena Crit(HP%)',
'크리빙결%':'Ghiaccio Crit%',
'크리HP+':'HP Crit+',
'크리MP+':'MP Crit+',
'크리쉴드+':'Scudo Crit+',
'피격방어+':'DIF su Colpito+',
'반격가시':'Spine Contrattacco',
'빙결파동%':'Onda Ghiaccio%',
'자동암흑막':'Scudo Oscurità Auto',
'주기치유':'Cura Periodica',
'시체폭발%':'Esplos. Cadavere%',
'회피뎀+':'Danni Schivata+',
'패링폭발%':'Esplos. Parata%',
'블록HP+':'HP Blocco+',
'블록MP+':'MP Blocco+',
'회전참뎀+':'Danni Turbine+',
'옴니빔뎀+':'Danni Raggio Omni+',
'화구뎀+':'Danni Palla Fuoco+',
'미사일뎀+':'Danni Missile+',
'청탄뎀+':'Danni Tiro Blu+',
'폭렬탄뎀+':'Danni Raffica+',
'지옥광선뎀+':'Danni Raggio Inferno+',
'악의폭풍뎀+':'Danni Tempesta Malizia+',
'연쇄참뎀+':'Danni Fendente Catena+',
'거인강타뎀+':'Danni Colpo Gigante+',
'유령보행뎀+':'Danni Passo Fantasma+',
'악의박격뎀+':'Danni Mortaio Malizia+',
'화염오라뎀+':'Danni Aura Fuoco+',
'빙구뎀+':'Danni Sfera Ghiaccio+',
'화염빔뎀+':'Danni Fascio Fuoco+',
'악의사냥뎀+':'Danni Caccia Malizia+',
'암흑기둥뎀+':'Danni Pilastro Oscuro+',
'역병뎀+':'Danni Peste+',
'가시오라뎀+':'Danni Aura Spine+',
'연쇄돌격뎀+':'Danni Assalto Catena+',
'회피확률+':'Prob. Schivata+',
'회피쿨-':'CD Schivata-',
'쉴드%+':'Scudo%+',
'쉴드리젠%+':'Regen. Scudo%+',
'쉴드쿨-':'CD Scudo-',
'HP리젠%+':'Regen. HP%+',
'ST리젠+':'Regen. ST+',
'ST리젠%+':'Regen. ST%+',
'MP리젠+':'Regen. MP+',
'MP리젠%+':'Regen. MP%+',
'화염DR':'DR Fuoco',
'빙결DR':'DR Ghiaccio',
'뇌전DR':'DR Fulmine',
'암흑DR':'DR Oscurità',
'독DR':'DR Veleno',
'전체DR':'DR Totale',
'엘리트DR':'DR Elite',
'스턴저항':'Res. Stordim.',
'감속저항':'Res. Rallent.',
'넉백저항':'Res. Respinta',
'돌진거리+':'Portata Scatto+',
'돌진쿨-':'CD Scatto-',
'전투이속+':'Vel. Mov. Combatt.+',
'비전투이속+':'Vel. Mov. Fuori Combatt.+',
'습득범위+':'Raggio Raccolta+',
'전스탯+':'Tutti Stat+',
'적중자원+':'Risorse su Colpo+',
'화염최대저항+':'Res. Max Fuoco+',
'빙결최대저항+':'Res. Max Ghiaccio+',
'뇌전최대저항+':'Res. Max Fulmine+',
'암흑최대저항+':'Res. Max Oscurità+',
'독최대저항+':'Res. Max Veleno+',
'스킬쿨-':'CD Abilità-',
'물약쿨-':'CD Pozione-',
'강화성공+':'Tasso Potenziamento+',
'악의획득+':'Guadagno Malizia+',
'악마화뎀+':'Danni Demoniaco+',
'악마화DR':'DR Demoniaco',
'영혼수확+':'Mietitura Anime+',
'생명흡혈%':'Drenaggio Vita%',
'과치유→쉴드':'Sovracura→Scudo',
'만마나뎀+':'Danni MP Pieno+',
'이동DR':'DR Movimento',
'정지뎀+':'Danni Fermo+',
'회피후뎀+':'Danni Post-Schivata+',
'패링쉴드+':'Scudo Parata+',
'콤보보너스+':'Bonus Combo+',
'HP≥70%뎀+':'HP≥70% Danni+',
'적HP≤30%뎀+':'Nem. HP≤30% Danni+',
'HP100%뎀+':'HP100% Danni+',
'HP≤35%뎀+':'HP≤35% Danni+',
'적HP≤20%뎀+':'Nem. HP≤20% Danni+',
'근접뎀+':'Danni Mischia+',
'원거리뎀+':'Danni A Distanza+',
'스턴적뎀+':'Danni vs Stordito+',
'빙결적뎀+':'Danni vs Congelato+',
'화상적뎀+':'Danni vs Bruciante+',
'중독적뎀+':'Danni vs Avvelenato+',
'저주적뎀+':'Danni vs Maledetto+',
'감속적뎀+':'Danni vs Rallentato+',
'보스뎀+':'Danni Boss+',
'엘리트뎀+':'Danni Elite+',
'일반몹뎀+':'Danni Gregge+',
'선제뎀+':'Danni Primo Colpo+',
'물리흡혈%':'Drenaggio Fisico%',
'마나흡수%':'Drenaggio Mana%',
'ST흡수%':'Drenaggio ST%',
'적중HP+':'HP su Colpo+',
'처치HP+':'HP su Kill+',
'처치MP+':'MP su Kill+',
'처치ST+':'ST su Kill+',
'처치시폭발':'Esplosione su Kill',
'처치이속+':'Vel. Mov. su Kill+',
'HP≥70%방어+':'HP≥70% DIF+',
'HP≤50%이속+':'HP≤50% Vel. Mov.+',
'DoT피해감소':'Rid. Danni DoT',
'화상피해감소':'Rid. Danni Bruciatura',
'보스피해감소':'Rid. Danni Boss',
'근접피해감소':'Rid. Danni Mischia',
'원거리피해감소':'Rid. Danni A Distanza',
'처치HP회복':'Ripristino HP su Kill',
'처치쉴드회복':'Ripristino Scudo su Kill',
'ST소비-':'Costo ST-',
'HP≥70%공격+':'HP≥70% ATK+',
'HP≤35%흡혈':'HP≤35% Drenaggio',
'보스추가뎀':'Danni vs Boss+',
'엘리트추가뎀':'Danni vs Elite+',
'공격력+':'ATK+',
'크리뎀+':'Danni Crit+',
// --- CAT-84/85/86: affix names + implicit + legendary ---
'지속의':'Resistenza',
'마나의':'Mana',
'원소수호의':'Guardia Elem.',
'행운의':'Fortuna',
'근성의':'Tenacia',
'풍요의':'Abbondanza',
'약자포식의':'Predatore',
'만혈의':'Vita Piena',
'사선의':'Vita Bassa',
'처형의':'Esecuzione',
'근접살의':'DAN Mischia',
'원거리의':'A Distanza',
'경직파의':'Rompi Stagger',
'동파의':'Colpo Ghiaccio',
'연소의':'Bruciante',
'맹독살의':'Cacciatore Veleno',
'저주살의':'Cacciatore Malediz.',
'구속의':'Vincolante',
'왕살의':'Cacciatore Boss',
'정예살의':'Cacciatore Elite',
'군살의':'Cacciatore Gregge',
'선제의':'Primo Colpo',
'흡혈의':'Vampirismo',
'흡마의':'Drenaggio Mana',
'흡정의':'Drenaggio ST',
'타격재생의':'Regen. su Colpo',
'처치회복의':'Recupero su Kill',
'처치흡마의':'Mana su Kill',
'처치활력의':'ST su Kill',
'처치폭발의':'Esplosione su Kill',
'처치질주의':'Scatto su Kill',
'건강방어의':'Difesa Piena Vita',
'중상보호의':'Scudo Ferito',
'위기질주의':'Scatto in Crisi',
'지속피해방어의':'DR DoT',
'왕피해방어의':'DR Danni Boss',
'근접방어의':'DR Ravvicinato',
'원거리방어의':'DR A Distanza',
'처치생명의':'HP su Kill',
'처치수호의':'Scudo su Kill',
'화염강화의':'Amp. Fuoco',
'화염관통의':'Penetr. Fuoco',
'발화의':'Accensione',
'화염폭발의':'Esplosione Fuoco',
'맹화의':'Fiamma Intensa',
'화염의힘':'Potere Fuoco',
'빙결강화의':'Amp. Ghiaccio',
'빙결관통의':'Penetr. Ghiaccio',
'동결의':'Congelamento',
'빙결폭발의':'Esplosione Ghiaccio',
'영빙의':'Brina Eterna',
'빙결의힘':'Potere Ghiaccio',
'뇌전강화의':'Amp. Fulmine',
'뇌전관통의':'Penetr. Fulmine',
'감전의':'Scossa',
'뇌전폭발의':'Esplosione Fulmine',
'낙뢰의':'Fulmine',
'뇌전의힘':'Potere Fulmine',
'암흑강화의':'Amp. Oscurità',
'암흑관통의':'Penetr. Oscurità',
'침식의':'Corrosione',
'암흑폭발의':'Esplosione Oscurità',
'심연의':'Abisso',
'암흑의힘':'Potere Oscurità',
'맹독강화의':'Amp. Veleno',
'독관통의':'Penetr. Veleno',
'중독의':'Avvelenamento',
'독폭발의':'Esplosione Veleno',
'맹독지속의':'Durata Veleno',
'독의힘':'Potere Veleno',
'격투의':'Mischia',
'원사의':'Tiro a Distanza',
'주술의':'Incantesimo',
'광선의':'Raggio',
'탄도의':'Balistica',
'확산의':'Raggio Area',
'근접회심의':'Crit Mischia',
'마법회심의':'Crit Magia',
'사격회심의':'Crit a Distanza',
'근접쾌속의':'Velocità Mischia',
'사격쾌속의':'Velocità Tiro',
'영창의':'Canto',
'전속성관통의':'Penetr. Tutti Elem.',
'쉴드파괴의':'Sfonda Scudo',
'갑옷분쇄의':'Frantuma Armatura',
'탄속의':'Vel. Proiettile',
'화구발사의':'Lancio Palla Fuoco',
'연쇄뇌격의':'Fulmine a Catena',
'동결타의':'Colpo Ghiaccio',
'경직타의':'Colpo Stagger',
'독침의':'Puntura Veleno',
'출혈의':'Emorragia',
'약화의':'Debolezza',
'둔화의':'Rallentamento',
'표적의':'Marcatura',
'회심폭발의':'Esplosione Crit',
'회심연쇄의':'Catena Crit',
'회심빙결의':'Ghiaccio Crit',
'회심치유의':'Cura Crit',
'회심영력의':'Mana Crit',
'회심수호의':'Scudo Crit',
'피격강화의':'Potenziamento su Colpo',
'반격가시의':'Spine Contrattacco',
'빙결파동의':'Onda Ghiaccio',
'암흑보호의':'Scudo Oscurità',
'치유파동의':'Onda Cura',
'시체폭발의':'Esplosione Cadavere',
'회피반격의':'Contrattacco Schivata',
'패링폭파의':'Esplosione Parata',
'블록치유의':'Cura Blocco',
'블록영력의':'Mana Blocco',
'회전참강화':'Potenzia Turbine',
'옴니빔강화':'Potenzia Raggio Omni',
'화구강화':'Potenzia Palla Fuoco',
'미사일강화':'Potenzia Missile',
'청탄강화':'Potenzia Tiro Blu',
'폭렬탄강화':'Potenzia Raffica',
'지옥광선강화':'Potenzia Raggio Inferno',
'악의폭풍강화':'Potenzia Tempesta Malizia',
'연쇄참강화':'Potenzia Fendente Catena',
'거인강타강화':'Potenzia Colpo Gigante',
'유령보행강화':'Potenzia Passo Fantasma',
'악의박격강화':'Potenzia Mortaio Malizia',
'화염오라강화':'Potenzia Aura Fuoco',
'빙구강화':'Potenzia Sfera Ghiaccio',
'화염빔강화':'Potenzia Fascio Fuoco',
'악의사냥강화':'Potenzia Caccia Malizia',
'암흑기둥강화':'Potenzia Pilastro Oscuro',
'역병강화':'Potenzia Peste',
'가시오라강화':'Potenzia Aura Spine',
'연쇄돌격강화':'Potenzia Assalto Catena',
'회피의':'Schivata',
'회피쿨감의':'Rid. CD Schivata',
'수호력의':'Potere Scudo',
'수호재생의':'Regen. Scudo',
'수호쿨감의':'Rid. CD Scudo',
'재생력의':'Potere Regen.',
'활력재생의':'Regen. ST',
'마력재생의':'Regen. Mana',
'화염보호의':'Scudo Fuoco',
'빙결보호의':'Scudo Ghiaccio',
'뇌전보호의':'Scudo Fulmine',
'해독의':'Antidoto',
'만물보호의':'Protezione Totale',
'정예보호의':'Scudo Elite',
'경직저항의':'Res. Stagger',
'빙결저항의':'Res. Ghiaccio',
'화상저항의':'Res. Bruciatura',
'감속저항의':'Res. Rallent.',
'넉백저항의':'Res. Respinta',
'돌진거리의':'Portata Scatto',
'돌진쿨감의':'Rid. CD Scatto',
'전투질주의':'Corsa Combattimento',
'평화질주의':'Corsa Pace',
'습득범위의':'Raggio Raccolta',
'힘의':'Forza',
'민첩의':'Destrezza',
'지능의':'Intelligenza',
'만능의':'Versatile',
'지구력의':'Max ST',
'마나력의':'Potere Mana',
'타격자원의':'Risorse su Colpo',
'화염한계의':'Limite Fuoco',
'빙결한계의':'Limite Ghiaccio',
'뇌전한계의':'Limite Fulmine',
'암흑한계의':'Limite Oscurità',
'독한계의':'Limite Veleno',
'스킬쿨감의':'Rid. CD Abilità',
'물약쿨감의':'Rid. CD Pozione',
'장인의':'Maestria',
'탐욕의':'Avidità',
'수련의':'Addestramento',
'수집의':'Raccolta',
'악마의힘':'Potere Demoniaco',
'악마보호의':'Scudo Demoniaco',
'영혼수확의':'Mietitura Anime',
'생명흡수의':'Assorbimento Vita',
'과치유수호의':'Scudo Sovracura',
'만마력의':'Danni Mana Pieno',
'이동방어의':'DR Movimento',
'정지공세의':'Attacco Fermo',
'회피공세의':'Attacco Post-Schivata',
'패링보호의':'Scudo Parata',
'콤보폭발의':'Esplosione Combo',
'물리타격의':'Colpo Fisico',
'화염타격의':'Colpo Fuoco',
'빙결타격의':'Colpo Ghiaccio',
'뇌전타격의':'Colpo Fulmine',
'암흑타격의':'Colpo Oscurità',
'독타격의':'Colpo Veleno',
'최소공격의':'ATK Min.',
'최대공격의':'ATK Max.',
'전투력의':'Potere Combattimento',
'무기사거리의':'Portata Arma',
'활사거리의':'Portata Arco',
'이중타의':'Doppio Colpo',
'다중발사의':'Fuoco Multiplo',
'관통횟수의':'Colpi Penetrazione',
'관통유지의':'Mantenimento Penetr.',
'연쇄유지의':'Mantenimento Catena',
'범위확장의':'Portata Area',
'범위피해의':'Danni Area',
'돌진공격의':'Attacco Scatto',
'반격공격의':'Attacco Contrattacco',
'후방타의':'Colpo alla Schiena',
'침식가속의':'Velocità Corrosione',
'출혈지속의':'Durata Emorragia',
'마법타격의':'Colpo Magico',
'주문증폭의':'Amp. Incantesimo',
'연살뎀의':'Danni Strisce Kill',
'연살속의':'Velocità Strisce Kill',
'기세의':'Slancio',
'정지공격의':'Attacco Statico',
'이동공격의':'Attacco Mobile',
'패링공세의':'Attacco Post-Parata',
'임사폭발의':'Esplosione Quasi-Morte',
'만기력공의':'ATK ST Pieno',
'만마력공의':'ATK Mana Pieno',
'신선처치의':'Kill Recente',
'경직연장의':'Estensione Stagger',
'빙결연장의':'Estensione Ghiaccio',
'둔화강화의':'Amp. Rallentamento',
'독중첩의':'Accumulo Veleno',
'출혈중첩의':'Accumulo Emorragia',
'발화강화의':'Amp. Accensione',
'동상강화의':'Amp. Congelatura',
'감전강화의':'Amp. Scossa',
'사선회심의':'Crit Vita Bassa',
'갑옷강화의':'Potenzia Armatura',
'블록흡수의':'Assorbimento Blocco',
'방패타격의':'Colpo Scudo',
'방패경직의':'Stagger Scudo',
'격투속의':'Velocità Lotta',
'격투회심의':'Crit Lotta',
'격투경직의':'Stagger Lotta',
'하반재생의':'Regen. Gambe',
'CC단축의':'Rid. Durata CC',
'돌진타의':'Colpo Scatto',
'돌진범위의':'Area Scatto',
'은신질주의':'Corsa Furtiva',
'회피감쇠의':'DR Schivata',
'속성감쇠의':'DR Elemento',
'마나왕관의':'Elmo Mana',
'시전왕관의':'Elmo Lancio',
'쿨감왕관의':'Elmo CD',
'경험왕관의':'Elmo ESP',
'공생의':'Simbiosi',
'수질의':'Corpo-Anima',
'회심흡의':'Drenaggio Crit',
'체마의':'HP-Mana',
'체기의':'HP-ST',
'마기의':'Mana-ST',
'전재생의':'Regen. Totale',
'힘민의':'FOR-DES',
'힘지의':'FOR-INT',
'민지의':'DES-INT',
'운근의':'FOR-TEN',
'수확의':'Raccolta',
'빙화의':'Ghiaccio-Fuoco',
'뇌암의':'Fulmine-Oscurità',
'근마의':'Lama-Magia',
'속성침식의':'Corrosione Elem.',
'화염반지의':'Anello Fuoco',
'빙결반지의':'Anello Ghiaccio',
'뇌전반지의':'Anello Fulmine',
'암흑반지의':'Anello Oscurità',
'독반지의':'Anello Veleno',
'콤보반지의':'Anello Combo',
'처치마나의':'Mana su Kill',
'관통반지의':'Anello Penetrazione',
'만능목걸이의':'Collana Tuttofare',
'회심목걸이의':'Collana Crit',
'관통목걸이의':'Collana Penetrazione',
'스킬목걸이의':'Collana Abilità',
'콤보한계의':'Limite Combo',
'처치치유의':'Cura su Kill',
'지구벨트의':'Cintura ST',
'포션벨트의':'Cintura Pozione',
'활력벨트의':'Cintura Vitalità',
'탐욕벨트의':'Cintura Avidità',
'마나띠의':'Fascia Mana',
'시전띠의':'Fascia Lancio',
'마력띠의':'Fascia Arcana',
'주술띠의':'Fascia Incantesimo',
'속성띠의':'Fascia Elemento',
'전사의힘':'Potere Guerriero',
'전사생명의':'Vita Guerriero',
'전사흡혈의':'Drenaggio Guerriero',
'전사인내의':'Resilienza Guerriero',
'마법사의힘':'Potere Mago',
'마법사마나의':'Mana Mago',
'마법사수호의':'Scudo Mago',
'마법사속성의':'Elemento Mago',
'궁수의힘':'Potere Arciere',
'궁수사거리의':'Portata Arciere',
'궁수관통의':'Penetr. Arciere',
'궁수질주의':'Corsa Arciere',
'탱크생명의':'Vita Tank',
'탱크방어의':'Difesa Tank',
'탱크블록의':'Blocco Tank',
'탱크가시의':'Spine Tank',
'암살회심의':'Crit Assassino',
'암살후방의':'Schiena Assassino',
'암살독의':'Veleno Assassino',
'암살회피의':'Schivata Assassino',
'종결자의':'Il Finale',
'생존자의':'Sopravvissuto',
'종결수호의':'Scudo Finale',
'종결회심의':'Crit Finale',
'종결공격의':'ATK Finale',
'종결저항의':'Resistenza Finale',
'종결파괴의':'Distruzione Finale',
'종결보호의':'Protezione Finale',
'종결흡혈의':'Drenaggio Finale',
'종결인내의':'Tenacia Finale',
'종결쿨감의':'Rid. CD Finale',
'종결경험의':'ESP Finale',
'종결약탈의':'Bottino Finale',
'종결악의의':'Malizia Finale',
'종결힘의':'FOR Finale',
'종결민첩의':'DES Finale',
'종결지능의':'INT Finale',
'종결행운의':'FOR Finale',
'종결근성의':'TEN Finale',
'종결연살의':'Strisce Kill Finale',
'건강공세의':'Attacco Piena Vita',
'중상폭발의':'Esplosione Ferito',
'중상흡혈의':'Drenaggio Ferito',
'토벌의':'Vanguardia',
'정예토벌의':'Vanguardia Elite',
'극대화의':'Massimizza',
'공격력 +X%':'ATK +X%',
'관통 확률 +X%':'Prob. Penetr. +X%',
'방어율 +X%':'Tasso Blocco +X%',
'물리 피해감소 +X%':'DR Fisico +X%',
'최대 HP +X':'HP Max +X',
'공격속도 +X%':'Vel. ATK +X%',
'상태이상 저항 +X%':'Res. Stato +X%',
'이동속도 +X%':'Vel. Mov. +X%',
'원소 저항 +X%':'Res. Elem. +X%',
'최대 HP +X%':'HP Max +X%',
'회피 쿨다운 -X%':'CD Schivata -X%',
'물약 쿨다운 -X%':'CD Pozione -X%',
'부활력 +X%':'Potere Rinascita +X%',
'마법 데미지 +X%':'Danni Magia +X%',
'전설 특수':'Speciale Leggendario',
'유니크 특수':'Speciale Unico',
'5타 콤보 완성 시 데빌포스 20% 즉시 충전':'Combo 5 colpi: carica istantanea DevilForce 20%',
'처치 시 이속 +40%(3초) + 다음 공격 크리 보장':'Kill: Vel. Mov. +40%(3s) + prossimo attacco Crit garantito',
'스태거 발동 시 범위 충격파 (ATK×120%)':'Stagger: onda d\'urto ad area (ATK×120%)',
'스태거 발동 시 범위 충격파 (ATK×100%)':'Stagger: onda d\'urto ad area (ATK×100%)',
'강타 시 적 넉백 거리 2배 + 벽충돌 추가뎀':'Colpo forte: respinta ×2 + danno extra collisione muro',
'출혈 대상 크리 시 잔여 DoT×300% 즉시 폭발':'Crit su Emorragia: DoT residuo×300% esplosione istantanea',
'사슬 착지 타격 수만큼 데미지 +20% 중첩(최대5)':'Javelin landing hits: stack +20% DMG (max 5)',
'치명타 시 추가 투사체 1발 발사':'Crit: lancia 1 proiettile aggiuntivo',
'패리 성공 시 반격 데미지 ×2':'Parata: danni contrattacco ×2',
'피격 시 3초 쿨로 HP 5% 즉시 회복':'Colpito (CD 3s): ripristina 5% HP istantaneamente',
'스킬 사용 시 20% 확률로 쿨다운 미소모':'Uso abilità: 20% prob. senza consumo CD',
'공격속도 +20% + 기본공격에 랜덤 원소 추가':'Vel. ATK +20% + attacchi base aggiungono elem. casuale',
'이동 중 지속 HP 재생 (초당 HP의 1%)':'In movimento: regen. HP (1% HP/s)',
'회피 직후 첫 공격 데미지 +80%':'Primo attacco post-schivata: Danni +80%',
'패리 타이밍 판정 +50% 확대':'Finestra parata +50% ampliata',
'원소 반응 발동 시 추가 폭발 (ATK×80%)':'Reazione elementale: esplosione bonus (ATK×80%)',
'처치 시 데빌포스 5% 회복':'Kill: recupera 5% DevilForce',
'HP 50% 이하 시 전 스킬 쿨다운 -30%':'HP<50%: CD tutte abilità -30%',
'물약 사용 시 5초간 피해 +15%':'Uso Pozione: Danni +15% per 5s',
'암묵':'Implicito',
'낡은 악마의 팔찌':'Bracciale Demoniaco Logoro',
'흑요석 악마의 팔찌':'Bracciale Demoniaco Ossidiana',
'미스릴 악마의 팔찌':'Bracciale Demoniaco Mithril',
'낡은 생명의 팔찌':'Bracciale della Vita Logoro',
'확인':'Conferma',
'조작법':'Comandi',
'살아남으려면 익혀라':'Imparalo per sopravvivere',
'전투':'Combattimento',
'이동 / 상호작용':'Movimento / Interazione',
'메뉴':'Menu',
'시스템':'Sistema',
'아무 키를 눌러 시작':'Premi un tasto per iniziare',
'스테이지':'Fase',
'💪 힘 (STR)':'💪 FOR',
'🏹 민첩 (DEX)':'🏹 DES',
'🔮 지능 (INT)':'🔮 INT',
'🍀 행운 (LCK)':'🍀 FOR',
'⚔️ 맹공':'⚔️ Assalto',
'🔱 돌파':'🔱 Sfondamento',
'⚡ 반격':'⚡ Ritorsione',
'🔮 마력폭주':'🔮 Impeto Arcano',
'🎯 정밀사격':'🎯 Tiro Preciso',
'🛡 수호신':'🛡 Spirito Guardiano',
'💚 회복력':'💚 Recupero',
'💥 급소':'💥 Colpo Vitale',
'🎁 약탈':'🎁 Saccheggio',
'🔱 관통':'🔱 Penetrazione',
'💠 마력회복':'💠 Recupero Mana',
'🏹 쇠뇌력':'🏹 Maestria Balestra',
'⚔ 광전사':'⚔ Berserker',
'🎯 추적자':'🎯 Inseguitore',
'🗡 물리관통':'🗡 Pen. Fisica',
'🔮 마법관통':'🔮 Pen. Magica',
'🌿 풍요':'🌿 Abbondanza',
'🐺 약자포식':'🐺 Predatore',
'☠ 침식':'☠ Corrosione',
'💎 마력그릇':'💎 Vaso Arcano',
'💪 힘의그릇':'💪 Vaso Stamina',
'👿 악의중독':'👿 Dipendenza Malizia',
'❤️ 강인':'❤️ Tempra',
'🛡 철벽':'🛡 Muro di Ferro',
'🎯 사냥꾼':'🎯 Cacciatore',
'✦ 인간성':'✦ Umanità',
'☠ 악마성':'☠ Demonismo',
'1. 악의폭풍':'1. Tempesta Malizia',
'2. 칼날 계열':'2. Abilità Lama',
'3. 역병 확장':'3. Espansione Peste',
'4. 이동스킬 마스터':'4. Maestro Movimento',
'5. 사슬 확장':'5. Espansione Catena',
'6. 💀 필살기 선택':'6. 💀 Scelta Colpo Finale',
'7. 멸살+만화+원소+전격이동':'7. Raggio+Raffica+Elem.+Balzo',
'8. 회전참+기폭+대왕':'8. Turbine+Det.+Gigante',
'9. 방패 합체':'9. Fusione Scudo',
'10. 해골무덤+악의폭풍':'10. Tomba Ossa+Tempesta Malizia',
'11. 폭풍소환+얼음보주':'11. Evocaz. Vortice+Sfera Ghiaccio',
'12. 뇌전걸음':'12. Passo Fantasma',
'13. 신성 영역':'13. Dominio Sacro',
'14. 6단합체: 폭풍빔':'14. Fusione 6: Raggio Vortice',
'15. 신성+빙결':'15. Sacro+Ghiaccio',
'16. 암흑+가시+대왕2':'16. Oscurità+Spine+Gigante2',
'17. 사슬 최종':'17. Catena Finale',
'⚡ 이동스킬':'⚡ Movimento',
'⚔️ 물리/근접/분노':'⚔️ Fisico/Mischia/Furia',
'🛡️ 방어':'🛡️ Difesa',
'🔮 마법':'🔮 Magia',
'🏹 석궁/관통':'🏹 Balestra/Penetrazione',
'⚙️ 영역':'⚙️ Dominio',
'💀 필살기':'💀 Colpo Finale',
'⭐ 추천':'⭐ Consigliato',
'⚔ 공격':'⚔ Attacco',
'🛡 방어':'🛡 Difesa',
'⚙ 특수':'⚙ Speciale',
  '👻 공성유령!':'👻 Fantasma d\'Assedio!',
'STEAM 위시리스트':'Lista dei desideri Steam',
'STEAM 위시리스트로 응원해 주세요!':'Supportaci aggiungendolo alla lista dei desideri di Steam!',
'⚔ 난타!':'⚔ Raffica!',
'⚡ 연격!':'⚡ Combo rapida!',
'더블탭 or Shift+방향키! 전격이동으로 탈출해!':'Doppio tocco o Shift+Direzione! Scatta per scappare!',
'데모 종료':'Fine della Demo',
'독사':'Serpente velenoso',
'방어↓':'DIF↓',
'여기까지 데모입니다. 정식 출시를 기대해주세요!':'Questa è la fine della demo. Non vediamo l\'ora del rilascio completo!',
'프레임 표시 (FPS)':'Mostra FPS',
'흑요염 파괴자':'Distruttore della Fiamma d\'Ossidiana',
'🌀 휘두르기!':'🌀 Rotazione!',
'🐍 독사!':'🐍 Serpente velenoso!',
'💥 강타!':'💥 Colpo Forte!',
'💥 공성유령 폭발!':'💥 Esplosione del fantasma assediante!',
'목표 달성!':'Obiettivo raggiunto!',
'악의 고갈':'Malizia esaurita',
'시도':'Tentativi',
'소비':'Speso',
'목표':'Obiettivo',
'미달':'Non raggiunto',
'악의를 더 모아 재시도하세요':'Raccogli più Malizia e riprova',
'습득':'Impara',
'레벨업':'Lv+',
'⚡기동+10':'⚡Scatto+10',
'게임 종료':'Esci dal gioco',
'영역스킬':'Abilità ad area',
'석궁자동':'Balestra auto',
'데빌포스 흡수 (HP→에너지)':'Forza Demoniaca (HP→Energia)',
'스킬슬롯 5':'Slot abilità 5',
'CT스킬 (유령걸음/얼음보주)':'Ab. CT (Passo Spettrale/Sfera Ghiaccio)',
'스킬 (전투스킬 습득)':'Abilità (Combattimento)',
'대장간 (제작)':'Forgia (Crafting)',
'클릭하여 계속':'Clicca per continuare',
'클릭하여 시작':'Clicca per iniziare',
'SPACE 길게 눌러 건너뛰기':'Tieni SPACE per saltare',
'패링·보호막':'Parata / Scudo',
'돌진 (적을 관통, 무적)':'Carica (attraversa nemici, invincibile)',
'대왕치기 (광역 기절)':'Colpo Gigante (stordimento ad area)',
'가시덫 (슬로우+출혈)':'Trappola spinata (lento+sanguinamento)',
'회복의 영역 (리젠 장판)':'Dominio sacro (zona regen)',
'얼음보주 (무적+빙결)':'Sfera di ghiaccio (invincibile+congelamento)',
'석궁 자동발사':'Balestra automatica',
'선택 스킬 슬롯':'Slot abilità',
'(펫이 자동 수거)':'(pet raccoglie auto)',
'물약은 설정한 HP% 이하 시 자동 사용':'Pozioni auto sotto HP% impostato',
'💡 Shift로 사슬 돌진! 적을 관통하며 무적':'💡 Shift per caricare! Attraversa nemici, invincibile',
'💡 Q로 보호막 발동 — 기본 흡수율 70%, 패링 성공 시 HP/ST/MP/기동게이지 회복':'💡 Q per Scudo — assorbimento 70%, parata recupera HP/ST/MP/Carica',
'💡 속성 약점을 찌르면 데미지 2배!':'💡 Colpisci le debolezze elementali per 2x danni!',
'💡 ESC로 설정 — 난이도, 자동물약 조절':'💡 ESC impostazioni — difficoltà, pozioni auto',
'💡 대왕치기로 기절 회복 + 포이즈를 깎아 그로기 유발!':'💡 Colpo Gigante: recupero stordimento + rompe postura per groggy!',
'💡 그로기 상태에서 기본 데미지 1.5배':'💡 Stato groggy = 1.5x danni base',
'💡 탄막은 패링하면 되돌려 보낸다!':'💡 Parare proiettili li rimanda indietro!',
'💡 Ctrl 얼음보주 — 무적! 재입력으로 즉시 폭파':'💡 Ctrl Sfera Ghiaccio — invincibile! Ripremi per frantumare',
'💡 합체 스킬로 더 강한 공격을 만들어보세요':'💡 Fondi abilità per attacchi più forti!',
'💡 엘리트 몬스터는 특수 능력을 가지고 있다':'💡 I mostri élite hanno abilità speciali',
'💡 보스의 패턴을 읽고 패링 타이밍을 잡아라':'💡 Leggi i pattern del boss, trova il timing di parata',
'💡 인벤토리(TAB)에서 장비를 비교하고 장착':'💡 Inventario(TAB) — confronta ed equipaggia',
'💡 대장간에서 장비를 강화하고 분해하세요':'💡 Potenzia e smantella equipaggiamento alla forgia',
'💡 R키를 누르면 펫이 아이템을 자동으로 주워줍니다':'💡 Premi R — il tuo pet raccoglie oggetti automaticamente',
'💡 물약은 설정한 HP% 이하에서 자동 사용':'💡 Pozioni auto sotto HP% impostato',
'💡 집중 스킬(홀드)은 시전 중 기절 면역!':'💡 Le abilità canalizzate danno immunità stordimento!',
'🎮 전체 조작 가이드':'🎮 Guida Comandi',
'무기 공격 (좌클릭)':'Attacco (LMB)',
'B슬롯 스킬 (Space)':'Ab. Slot B (Space)',
'우클릭 스킬 (RMB)':'Ab. Clic Des (RMB)',
'패링 (Q)':'Parata (Q)',
'돌진/사슬 (Shift)':'Scatto/Catena (Shift)',
'Ctrl 스킬':'Ab. Ctrl',
'필살기 (Z)':'Definitiva (Z)',
'F 슬롯 스킬':'Ab. Slot F',
'스킬 슬롯 1':'Slot 1',
'스킬 슬롯 2':'Slot 2',
'스킬 슬롯 3':'Slot 3',
'스킬 슬롯 4':'Slot 4',
'처형 (X)':'Esecuzione (X)',
'방향 + 마법 자동발동 (E)':'Dir. + Magia auto (E)',
'마법 (E)':'Magia (E)',
'줍기 (R)':'Raccogli (R)',
'스킬창':'Abilità',
'이동 (WASD)':'Muovi (WASD)',
'👻 유령!':'👻 Fantasma!',
'🦴 해골무덤!':'🦴 Tomba d\'ossa!',
'💥 유령총 폭발!':'💥 Esplosione Pistola Fantasma!',
'탈취!':'Furto!',
'✟ 신성한 결계!':'✟ Barriera Sacra!',
'👻 유령총!':'👻 Pistola Fantasma!',
'기절!  ':'Stordito!  ',
' 스킬 해제':' Rimuovi abilità',
' 자동 OFF':' Auto OFF',
' 자동 ON':' Auto ON',
'B슬롯 스킬':'Abilità slot B',
'☠중독!':'☠ Avvelenamento!',
'✟ 신의영역!':'✟ Dominio Divino!',
'❄ 얼음송곳!':'❄ Spina di Ghiaccio!',
'⟨ 키 입력... ⟩':'⟨ Premi tasto... ⟩',
'고정':'Fisso',
'다음 구역':'Zona successiva',
'돌진/사슬':'Carica/Catena',
'쓰러짐...':'Caduta...',
'우클릭 스킬':'Abilità clic destro',
'줍기':'Raccolta',
'패드 키 초기화':'Ripristina tasti gamepad',
'패드 키 초기화 완료':'Tasti gamepad ripristinati',
'패링':'Parata',
'🎮 게임패드 버튼 설정':'🎮 Impostazioni tasti gamepad',
'🎮 패드 연결됨':'🎮 Gamepad connesso',
'🎮 패드 연결 끊김':'🎮 Gamepad disconnesso',
'💀 ':'💀 ',
'🔥부활!':'🔥 Resurrezione!',
'🔥분노 ':'🔥 Furia ',
'🔥분노+':'🔥Furia+',
'🚀 미사일!':'🚀 Missile!',
// --- Pet dialogue: death screen (death_dual) ---
'…죽었군. 하지만 여신은 아직 널 안 놓았어.':"…Sei morto. Ma la dea non ti ha ancora lasciato andare.",
'괜찮아?! 다시 일어설 수 있어, 포기하지 마!':"Tutto bene?! Puoi rialzarti, non mollare!",
'…한 끗이었어. 아까워 말고 다시 해.':"…Per un soffio. Niente rimpianti, riprova.",
'아아! 조금만 더였는데!! 다음엔 진짜 잡자!':"Ah! Mancava così poco!! La prossima lo prendiamo davvero!",
'보스는 원래 이렇게 죽이는 거다. 여러 번.':"È così che si uccide un boss. Ancora e ancora.",
'저 녀석 패턴 봤지?! 다음엔 안 당해!':"Hai visto il suo schema, vero?! La prossima non ti frega!",
'…이름값 하는 놈이었군.':"…Quello era all'altezza del suo nome.",
'레어몹한테?! 센 만큼 좋은 걸 떨군다니까!':"Da un raro?! Più sono forti, migliore è il bottino!",
'잡졸한테 죽다니. …방심했군.':"Ucciso da un poveraccio. …Ti sei distratto.",
'저런 애들한테?! 정신 좀 차려어!':"Da quelli lì?! Datti una svegliata!",
'…발밑을 봐. 서 있던 자리가 널 죽였어.':"…Guarda dove metti i piedi. Il terreno su cui stavi ti ha ucciso.",
'장판 위에 서 있었잖아! 빨리 빠졌어야지!':"Eri dentro l'area! Dovevi uscirne subito!",
'탄을 못 읽었어. 눈을 크게 떠.':"Non hai letto il colpo. Apri bene gli occhi.",
'날아오는 거 봤어야지! 패링이든 회피든!':"Dovevi vederlo arrivare! Para o schiva!",
'잡히면 끝이야. 거리를 배워.':"Se ti afferrano, è finita. Impara le distanze.",
'붙잡혔어! 다음엔 옆으로 굴러!':"Ti hanno afferrato! La prossima rotola di lato!",
'…이 챕터가 네 무덤이 되고 있다.':"…Questo capitolo sta diventando la tua tomba.",
'여기서 또?! 이 구간 진짜 조심해!':"Ancora qui?! Fai attentissimo in questo tratto!",
'열 번. …죽는 것도 재능이군.':"Dieci volte. …Anche morire è un talento.",
'또?! 우리 진짜 같이 좀 살자아!':"Ancora?! Sopravviviamo insieme una buona volta, ti prego!",
'…또야. 같은 실수는 그만.':"…Di nuovo. Basta con lo stesso errore.",
'다섯 번째야! 패턴 좀 외워줘!':"È la quinta volta! Imparati lo schema, dai!",
'잘 나가다 한 방에. …끝까지 방심 마.':"Tutto liscio, poi un colpo solo. …Non abbassare la guardia fino alla fine.",
'그렇게 잘하다가!! 아까워 죽겠어!':"Con quanto stavi andando bene!! Che spreco, mi rode!",
'…지옥에 망자 하나 더 늘릴 셈이야?':"…Hai intenzione di aggiungere un altro cadavere all'Inferno?",
'그런 소리 마! 얜 아직 안 죽었어! 일어나!':"Non dirlo! Questo qui non è ancora morto! Alzati!",
'…여왕님이 실망하시겠군.':"…La Regina ne sarà delusa.",
'실망은 무슨! 다시 일어나면 되잖아, 얼른!':"Delusa un corno! Basta che ti rialzi, forza!",
'잠은 집에 가서 자. …일어나.':"A dormire ci pensi a casa. …Alzati.",
'여기서 자면 진짜 집 못 가! 얼른 일어나!':"Se ti addormenti qui a casa non ci torni più! Alzati subito!",
'여기서 포기하면… 누가 가족의 원수를 갚지?':"Se molli qui… chi vendicherà la tua famiglia?",
'우리가 있잖아! 다시 일어나 끝까지 가!':"Ci siamo noi! Alzati e arriva fino in fondo!",
'네가 멈추면, 가족을 위해 싸울 자는 없어.':"Se ti fermi, non resta nessuno a combattere per la tua famiglia.",
'너밖에 없어! 여기서 주저앉지 마!':"Ci sei solo tu! Non crollare qui!",
'…복수는 살아남은 자만이 한다.':"…La vendetta è solo di chi sopravvive.",
'죽은 채로는 아무것도 못 갚아! 일어나!':"Da morto non salderai un bel niente! Alzati!",
'가족의 얼굴을 떠올려. 그게 네가 일어날 이유야.':"Richiama il volto della tua famiglia. È la tua ragione per rialzarti.",
'잊지 마! 우리가 왜 여기 있는지!':"Non dimenticare perché siamo qui!",
'포기하는 건… 결국 습관이 돼.':"Arrendersi… alla fine diventa un'abitudine.",
'한 번 포기하면 계속 포기하게 돼! 여기서 끊어!':"Ti arrendi una volta e continuerai a farlo! Spezzala qui!",
'일어나. 복수만이 정의다.':"Alzati. La vendetta è l'unica giustizia.",
'맞아! 여기서 끝낼 순 없어! 일어나!':"Esatto! Non può finire qui! Alzati!",
'썩은 숲이 첫 무덤이라니. 일어나.':"La Foresta Putrescente come prima tomba? Alzati.",
'아직 시작인데! 다시 가자!':"È solo l'inizio! Ci riproviamo!",
'벌레 밥이 될 뻔했군.':"Per poco non diventavi cibo per vermi.",
'으으 여기서 죽기 싫어! 다시!':"Uh, non voglio morire qui! Di nuovo!",
'얼어붙기 전에 일어나.':"Alzati prima di congelarti.",
'추운 데서 쓰러지지 마! 얼른!':"Non accasciarti al freddo! Svelto!",
'잿더미가 되기 전에.':"Prima di ridurti in cenere.",
'뜨거운 데서 눕지 좀 마아!':"Piantala di sdraiarti dove fa così caldo!",
'수에 삼켜졌군. 다시.':"Inghiottito dal numero. Di nuovo.",
'너무 많았어! 이번엔 뭉칠 때 노리자!':"Erano troppi! La prossima li colpiamo quando si ammassano!",
'사도들이 널 비웃고 있어.':"Gli Apostoli ti stanno deridendo.",
'여기 진짜 까다로워! 정신 바짝!':"Questo posto è davvero insidioso! Occhi aperti!",
'지옥성이 널 붙잡았어. 놓지 않게 해.':"Il Castello dell'Inferno ti ha afferrato. Non lasciare che ti tenga.",
'최종장이야! 여기서 무너지면 안 돼!':"È il capitolo finale! Non puoi crollare qui!",
};

const _IT_PFX={
'녹슨':'Arrugginito','강철':'Acciaio','흑요석':'Ossidiana','미스릴':'Mithril','심판의':'Giudizio','천벌의':'Ira Divina','파멸의':'Distruzione','불꽃':'Fiamma','화염':'Inferno','염화':'Fuoco Infernale','지옥불':'Fiamma Infernale','지옥화':'Fiamma Infernale','지옥':'Fiamma Infernale','멸화의':'Annientante','냉기':'Gelo','빙결':'Congelato','빙하':'Glaciale','서리의':'Brina','서리':'Brina','영겁빙':'Ghiaccio Eterno','그림자':'Ombra','암흑':'Oscuro','심연':'Abissale','나락의':'Infero','나락':'Infero','무간의':'Vuoto','전기':'Scintilla','낙뢰':'Tuono','암전':'Fulmine','뇌신의':'Dio Tuono','뇌신':'Dio Tuono','만뢰의':'Mille Tuoni','축복':'Benedetto','성광':'Luce Sacra','신성':'Sacro','천사의':'Angelico','신벌의':'Giudizio Divino','낡은':'Logoro','천':'Tela','가죽':'Pelle','강철사':'Trama Acciaio','은':'Argento','은사':'Filo d\'Argento','화염의':'Inferno','빙결의':'Congelato','암흑의':'Oscuro','암전의':'Fulmine'
};
const _IT_BASE={
'대검':'Spadone','석궁':'Balestra','연사석궁':'Balestra Ripetizione','마력석궁':'Balestra Arcana','견갑':'Scudo','대견갑':'Grande Scudo','전투화':'Stivali Combattimento','갑옷':'Armatura','갑주':'Armatura','왕관':'Corona','장갑':'Guanti','건틀릿':'Guanti Corazzati','바지':'Pantaloni','각반':'Schinieri','허리띠':'Cintura','벨트':'Cintura','부적':'Talismano','목걸이':'Collana','반지':'Anello','망토':'Mantello','팔찌':'Bracciale','귀걸이':'Orecchino',
'투구 착용':'Elmo indossato',
'투구 해제':'Elmo rimosso',
'혼돈의 투구':'Elmo del Caos',
'전지전능의 투구':'Elmo dell\'Onnipotenza',
'방향키 연타':'Premi frecce rapidamente',
'까마귀와 고양이가 아이템을 주워준다. 수거 범위 안이면.':'Il corvo e il gatto raccolgono oggetti. Se nel raggio.',
'Ctrl 얼음보주로 탈출! 없으면 방향키 연타!':'Ctrl — Orbe Ghiaccio per fuggire! Niente? Premi frecce!',
'💥 폭발 허수아비!':'💥 Spaventapasseri Esplosivo!',
' 뎀 ':' DAN ',
'투구':'Elmo',
'악마팔찌':'Bracciale Demoniaco',
'생명팔찌':'Bracciale della Vita',
'얼음송곳':'Spina di ghiaccio',
'⚡ 뇌전추격자!':'⚡ Cacciatore di fulmini!',
'대왕치기 (분노폭발, 광역 기절)':'Colpo gigante (Esplosione di furia, Stordimento ad area)',
'✦ 유니크 공유!':'✦ Condivisione unica!',
'🛡️쉴드+15%':'🛡️Scudo+15%',
'👿악의+':'👿Malizia+',
'❄유니크 빙결!':'❄Congelamento unico!',
'🔨방어무시!':'🔨Ignora DIF!',
'💥유니크 폭발!':'💥Esplosione unica!',
'👻 투명화!':'👻 Furtività!',
'⚡회피 반격!':'⚡Contrattacco evasivo!',
'⚠패링 실패!':'⚠Parata fallita!',
'🔥피격→분노!':'🔥Colpo→Furia!',
'✦ 유니크 부활!':'✦ Resurrezione unica!',
'닫기 [V]':'Chiudi [V]',
'닫기 [C]':'Chiudi [C]',
'\u2026\uBD84\uB178\uAC00 \uB053\uC5B4\uB118\uCE5C\uB2E4. \uC2A4\uD398\uC774\uC2A4\uB85C \uC801\uB4E4\uC5D0\uAC8C \uD3ED\uBC1C\uC2DC\uCCA8!':'…La rabbia trabocca. Scatenala sui nemici con Spazio!',
'\uBD84\uB178\uAC8C\uC774\uC9C0 \uAF49 \uCC3C\uC5B4! \uC2A4\uD398\uC774\uC2A4\uB85C \uD3ED\uBC1C\uC2DC\uCCA8!':'Indicatore di rabbia pieno! Fallo esplodere con Spazio!',

};
