// 지옥의 길 — Türkçe (tr)
const _TR={
'썩은 숲':'Çürük Orman',
'숲의 감시자':'Orman Muhafızı',
'독버섯 거인':'Zehirli Mantar Devi',
'숲의 사냥꾼':'Orman Avcısı',
'숲의 기생수':'Parazit Canavar',
'1장 — 썩은 숲':'B1 — Çürük Orman',
'2장 — 벌레굴':'B2 — Kurt Yuvası',
'3장 — 얼음굴':'B3 — Buz Mağarası',
'4장 — 고통의 화염지대':'B4 — Cehennem Çölü',
'5장 — 지옥의 군단':'B5 — Cehennem Lejyonu',
'6장 — 사도의 마굴':'B6 — Havari İni',
'7장 — 지옥성':'B7 — Cehennem Kalesi',
'탈출!':'Kaçtı!',
'처치':'öldürme',
'경험치':'DEN',
'최대콤보':'Maks Kombo',
'일어나. 여신이 널 여기 보낸 건 죽으라고가 아니야.':'Uyan. Tanrıça seni ölmek için göndermedi.',
'좋아, 감각이 있군. 계속 쳐!':'İyi, içgüdün var. Devam et!',
'Shift를 눌러. 작살이다. 땅에 꽂아서 끌려가!':'Shift bas. Bu zıpkın. Sapla ve çekilin!',
'작살로 끌려가는 중엔 무적이다. 위험할 때 쓰면 좋아.':'Zıpkın çekerken yenilmezsin. Tehlikede kullan.',
'...아파? 당연하지. 여긴 지옥이야.':'...Acıyor mu? Tabii. Burası cehennem.',
'Q를 눌러! 악의로 보호막을 만들 수 있다.':'Q bas! Kötülükle kalkan oluştur.',
'보호막 없이 버틸 생각은 버려.':'Kalkansız hayatta kalmayı unut.',
'우클릭이 패링이다. 적 공격이 닿기 직전에 눌러!':'Sağ tık savuşturma. Düşman vurmadan önce bas!',
'못 하겠으면 때려. 안 죽으면 그만이야.':'Savuşturamiyor musun? Sadece vur. Ölmemek yeter.',
'됐어! 감 잡았구나.':'İşte! Alışıyorsun.',
'하나 죽었군.':'Bir gitti.',
'유령쇠뇌야. 인사해.':'Bu hayalet tatar yayı. Merhaba de.',
'빨간 탄을 무서워하지 마. 악의가 강하다.':'Kırmızılardan korkma. Kötülük güçlü.',
'패링으로 돌려주고, Q 보호막도 써! 악의를 잘 굴려!':'Geri savuştur, Q kalkanı da kullan! Kötülüğü yönet!',
'무지개빛은 패링 불가! 피해!':'Gökkuşağı savuşturulamaz! Kaç!',
'피가 새고 있다. Shift. 빠져.':'Kanıyorsun. Shift. Çık.',
'물약 있잖아! 숫자키!':'İksirin var! Sayı tuşları!',
'우클릭. 적 손목이 꺾일 때 쳐.':'Sağ tık. Bileği büküldüğünde vur.',
'빨간 탄은 악의 덩어리다. 쳐내서 이용해.':'Kırmızılar kötülük parçaları. Saptır ve kullan.',
'무지개빛만 피하면 돼! 나머지는 다 패링!':'Sadece gökkuşağından kaç! Gerisini savuştur!',
'Q 보호막도 패링이 가능해!':'Q kalkanı da savuşturabilir!',
'위험해! 쉬프트 사슬기동으로 피해!!':'Tehlike! Shift zincir atağı!!',
'쉬프트! 사슬기동은 이동기야! 끌려가면서 무적이라고!':'Shift! Zincir atağı hareket! Yenilmez!',
'스킬포인트가 쌓였어! K 눌러서 스킬 배우자!':'Beceri puanları hazır! K bas!',
'속성을 읽어. 약점을 찌르면 두 배로 썩는다.':'Elementleri oku. Zayıflık = çift hasar.',
'K를 눌러봐! 스킬을 배울 수 있어!':'K bas! Beceri öğren!',
'C 눌러서 능력치 찍어! 패시브도 있어~':'İstatistikler C! Pasifler de~',
'G를 눌러. 대장간에서 장비를 강화할 수 있다.':'G bas. Dövücüde geliştir.',
'F키도 스킬 슬롯이야! 스킬 많으면 L로 배정해봐~':'F tuşu da beceri yuvası! L ile ata~',
'Z. 필살기다. 아껴 써라.':'Z. Son vuruşun. Akıllıca kullan.',
'L-CTRL로 유령걸음이나 얼음보주 쓸 수 있어!':'L-CTRL Hayalet Yürüyüş veya Buz Küresi!',
'L을 눌러. 스킬 슬롯을 정리해야 한다.':'L bas. Yuvaları düzenle.',
'가방 터지겠다! V 눌러서 창고에 넣어둬!':'Çanta patlayacak! V depola!',
'ESC로 설정 열 수 있어! 난이도 바꾸기, 자동물약 조절~':'ESC ayarlar! Zorluk, otomatik iksirler~',
'...아직 살아있네. 좌클릭으로 저것들 쳐봐.':'...Hâlâ hayattasın. Sol tıkla vur.',
'...치는 건 할 줄 아네. 피하는 건?':'...Vurabiliyorsun. Kaçabilir misin?',
'흥, 작살 못 맞추면 헛수고야.':'Hmph, zıpkını kaçırırsan boşa gider.',
'...운이 좋았을 뿐이야. 아마.':'...Sadece şans. Muhtemelen.',
'...고기 냄새. 싫진 않네.':'...Et gibi kokuyor. Fena değil.',
'...말은 못해.':'...Konuşamaz.',
'예쁘다고 만지면 죽어.':'Güzel diye dokunursan ölürsün.',
'작살 던져! 끌려가면 무적이야!':'Zıpkını fırlat! Çekilirken yenilmez!',
'...마시든 말든. 네 목숨이니까.':'...İç ya da içme. Senin hayatın.',
'그게 패링이야! 타이밍이 전부야~':'Bu savuşturma! Zamanlama her şey~',
'화염엔 빙결! 암전엔 암흑! 기억해!':'Ateş > Buz! Yıldırım > Karanlık! Unutma!',
'...얼어붙은 놈은 오래 안 간다.':'...Donmuşlar uzun dayanmaz.',
'얼었어! 빙결 중 1.5배야!':'Dondu! 1.5 kat hasar!',
'...힘을 골라라. 전부 가질 순 없다.':'...Gücünü seç. Hepsine sahip olamazsın.',
'스탯을 올려. 살고 싶으면.':'İstatistiklerini yükselt. Yaşamak istiyorsan.',
'좋은 장비는 강화해야 진짜 힘을 발휘해!':'İyi ekipman geliştirme ister!',
'...슬롯을 채워. 빈 손은 죽음이다.':'...Yuvaları doldur. Boş eller ölüm.',
'Z 누르면 대박! 쿨타임 길어서 타이밍 봐야 해!':'Z büyük hasar! Uzun bekleme süresi!',
'Ctrl. 위기에 쓸 카드가 하나 늘었군.':'Ctrl. Aciller için bir kart daha.',
'스킬이 많아졌네~ L로 어디에 뭘 넣을지 골라!':'Bu kadar beceri~ L ile ata!',
'...버리기 아까운 건 창고에.':'...İyi olanları depola.',
'...살아남은 것만으로도 대단하군. 설정을 확인해.':'...Hayatta kalmak etkileyici. Ayarları kontrol et.',
'MP 부족!':'Yetersiz MP!',
'ST 부족!':'Yetersiz ST!',
'악의 부족!':'Yetersiz Kötülük!',
'충전 중...':'Şarj...',
'캔슬':'İptal',
'아이템 선택 필요':'Eşya seç',
'악의 소진...':'Kötülük tükendi...',
'비문 발견...':'Yazıt bulundu...',
'HP물약!':'HP İksiri!',
'HP물약 +1':'HP İksiri +1',
'HP물약 +2':'HP İksiri +2',
'HP/MP/ST 회복!':'HP/MP/ST Yenilendi!',
'보물상자 개봉!':'Sandık Açıldı!',
'익사!':'Boğulma!',
'피웅덩이!':'Kan Gölü!',
'독혈!':'Zehirli Kan!',
'잡힘!':'Yakalandın!',
'콤보 종료':'Kombo Sonu',
'빙결!':'Dondu!',
'화상!':'Yanıyor!',
'독!':'Zehir!',
'감전!':'Şok!',
'기절!':'Sersem!',
'봉인됨!':'Mühürlendi!',
'관통!':'Delme!',
'기검참':'Enerji Kesimi',
'악의구':'Kötülük Küresi',
'회전참':'Kasırga',
'기폭팔':'Patlatma',
'칼등 처내기':'Kılıç Savuşturma',
'만화방창':'İğne Yağmuru',
'멸살광선':'İmha Işını',
'원소추적탄':'Element Avcısı',
'악의 보호자':'Kötülük Koruyucusu',
'악의 사냥':'Kötülük Avı',
'폭풍소환':'Girdap Çağırma',
'해골무덤':'Kemik Mezar',
'\u{1F47B} 유령!':'\u{1F47B} Hayalet!',
'\u{1F9B4} 해골무덤!':'\u{1F9B4} Kemik Mezar!',
'신성폭발':'Kutsal Patlama',
'블랙':'Kara Yıldız',
'용암소환':'Lav Çağırma',
'처형':'İnfaz',
'악마화 부활':'Demon Diriliş',
'붉은꽃':'Kızıl Çiçek',
'얼음보주':'Buz Orb',
'뇌전걸음':'Hayalet Yürüyüş',
'만화방창 II':'İğne Yağmuru II',
'마력연사':'Büyü Yağmuru',
'마력광선':'Yay Lazeri',
'업화선':'Cehennem Işını',
'지옥진':'Cehennem Dizilişi',
'폭독칼날':'Veba Kılıcı',
'악의폭풍':'Kötülük Fırtınası',
'악의기둥':'Karanlık Sütun',
'회복의 영역':'Kutsal Alan',
'구속의 영역':'Bağlama Alanı',
'아이스스톰':'Buz Storm',
'대왕치기':'Giant Çarpma',
'대왕치기 2':'Dev Vuruş II',
'기동불꽃':'Zincir Alevleri',
'기동파괴':'Zincir Ezme',
'기동칼날개':'Zincir Kılıç Kanadı',
'평화의보호':'Barış Kalkanı',
'참회':'Tövbe',
'칼등날개':'Kalkan Wing',
'폭산탄':'Patlama Atışı',
'파쇄의 영역':'Kırılma Alanı',
'침식의 영역':'Aşındırma Alanı',
'관통의 영역':'Delme Alanı',
'부활의 영역':'Diriliş Alanı',
'가시덫':'Spike Tuzak',
'푸른비':'Gök Yağmuru',
'버스트루프':'Patlama Döngüsü',
'유령 허수아비':'Hayalet Decoy',
'폭발 허수아비':'Patlayıcı Yem',
'공성쇠뇌':'Kuşatma Yayı',
'사슬기동:충돌':'Zincir Atılma: Çarpma',
'사슬기동:화염':'Zincir Atılma: Alev',
'전격이동':'Işık Adımı',
'기동칼날개!':'Kılıç Kanadı!',
'기동불꽃!':'Zincir Alevi!',
'기동파괴!':'Zincir Ezme!',
'사슬이동:강화!':'Zincir Atılma!',
'사슬기동:화염!':'Zincir Alevi!',
'작살!':'Zıpkın!',
'진입!':'Giriş!',
'레인라이트닝!':'Rain Yıldırım!',
'마력연사!':'Büyü Yağmuru!',
'🔷 마력광선!':'🔷 Yay Lazeri!',
'광선 해제':'Lazer Kapalı',
'MP 부족 — 광선 해제':'MP tükendi — Lazer Kapalı',
'집중...':'Odaklanma...',
'시전...':'Büyü yapılıyor...',
'만화방창!':'İğne Yağmuru!',
'바늘출!':'İğne Patlaması!',
'칼날!':'Kılıç!',
'착지!':'İniş!',
'체간삭감!':'Denge Kırılması!',
'기동전폭 준비!':'Zincir Patlaması Hazır!',
'기동불꽃 준비!':'Zincir Alevi Hazır!',
'기동파괴 준비!':'Zincir Ezme Hazır!',
'유령불꽃 ON':'Hayalet Alev AÇIK',
'유령불꽃 OFF':'Hayalet Alev KAPALI',
'기동칼날개 AUTO ON':'Kılıç Kanadı AUTO ON',
'기동칼날개 AUTO OFF':'Kılıç Kanadı AUTO OFF',
'자동 버스트!':'Otomatik Patlama!',
'연사 해제':'Rapid Ateş Off',
'당기기 모드':'Çek Mode',
'밀어내기 모드':'İt Mode',
'날개치기':'Kanat Vuruşu',
'처내기':'Savuşturma',
'Shift: 작살 발사 → 끌려감':'Shift: Zıpkın → çekme',
'Shift: 화염길+화상':'Shift: Alev izi+yanma',
'CT: 전류변신+뇌전걸음 (쿨4초)':'CT: Yıldırım formu+Hayalet Yürüyüş (BK 4sn)',
'CT: 방어구체+빙결 (재입력: 파쇄)':'CT: Buz küresi+dondurma (tekrar: paramparça)',
'근접':'Yakın',
'견갑':'Kalkan',
'작살':'Zıpkın',
'마법':'Büyülü',
'보막':'Kalkan',
'유령':'Hayalet',
'스킬':'Beceril.',
'대장':'Dövücü',
'인벤':'Çanta',
'인벤토리':'Envanter',
'복수의 대장간':'İntikam Dövücüsü',
'패시브 스킬':'Pasif Beceriler',
'전투 스킬':'Savaş Becerileri',
'캐릭터 선택':'Karakter Seçimi',
'물리':'Fiziksel',
'화염':'Ateş',
'빙결':'Donmuş',
'암흑':'Karanlık',
'암전':'Yıldırım',
'신성':'Kutsal',
'대지':'Toprak',
'힘':'Güç',
'민첩':'Çeviklik',
'지능':'Zeka',
'행운':'Şans',
'맹공':'Saldırı',
'철벽':'Dayanıklılık',
'돌파':'Atılım',
'반격':'Misilleme',
'마력폭주':'Büyü Dalgası',
'정밀사격':'Hassas Atış',
'수호':'Koruyucu',
'수호신':'Koruyucu Ruh',
'회복력':'İyileşme',
'급소':'Hayati Vuruş',
'약탈':'Yağma',
'관통':'Delme',
'마력회복':'Mana Yenileme',
'쇠뇌력':'Tatar Yayı Ustalığı',
'광전사':'Çılgın Savaşçı',
'추적자':'İzci',
'물리관통':'Fiziksel Delme',
'마법관통':'Büyü Delme',
'녹슨 대검':'Paslı Büyük Kılıç',
'강철 대검':'Çelik Büyük Kılıç',
'흑요석 대검':'Obsidyen Büyük Kılıç',
'낡은 석궁':'Eski Tatar Yayı',
'강철 석궁':'Çelik Tatar Yayı',
'흑요석 석궁':'Obsidyen Tatar Yayı',
'대검':'Büyük Kılıç',
'석궁':'Tatar Yayı',
'연사석궁':'Tekrarlı Yay',
'마력석궁':'Büyülü Tatar Yayı',
'악의 추출':'Kötülük Özütü',
'악의':'Kötülük',
'필살기':'Son Vuruş',
'필살기 해제':'Son Vuruş Boş',
'이전':'Aktarım',
'강화':'Geliştir',
'개봉!':'Açıldı!',
'여신의 가호':'Tanrıça Lütfu',
'과부하!':'Aşırı Yük!',
'맹독의':'Zehirli',
'불꽃의':'Alevli',
'냉기의':'Buz Gibi',
'번개의':'Elektrikli',
'암흑의':'Lanetli',
'관통의':'Delici',
'광폭의':'Öfkeli',
'파쇄의':'Parçalayıcı',
'연쇄의':'Zincirlenen',
'학살의':'Katleden',
'폭발의':'Patlayıcı',
'집중의':'Odaklanmış',
'쾌속의':'Hızlı',
'패리의':'Saptırıcı',
'추적자의':'İzcinin',
'작살의':'Zıpkın',
'궁극의':'Üstün',
'집중력의':'Bilinçli',
'강인의':'Sağlam',
'수호의':'Koruyan',
'활력의':'Hayati',
'신속의':'Hızlandırılmış',
'화염수호':'Ateş Koruma',
'빙결수호':'Buz Koruma',
'암전수호':'Yıldırım Koruma',
'암흑수호':'Karanlık Koruma',
'독수호':'Zehir Koruma',
'전원소수호':'Tüm Koruma',
'강철의':'Çelik Kaplı',
'반사의':'Yansıtıcı',
'가시의':'Dikenli',
'흡수의':'Emici',
'인내의':'Dayanıklı',
'위기의':'Çaresiz',
'피격반격의':'Misillemeci',
'패링폭발의':'Savuşturma Patlaması',
'스태거폭발의':'Sarsma Patlaması',
'원소전환의':'Dönüştürücü',
'정화의':'Arındırıcı',
'불굴의':'Boyun Eğmez',
'부활의':'Diriltici',
'약탈의':'Yağmacı',
'경험의':'Deneyimli',
'골드의':'Altın',
'포션강화의':'Güçlü',
'사슬의':'Zincirlenmiş',
'진혼의':'Kutsayan',
'윤회의':'Döngüsel',
'생명력의':'Canlı',
'재생의':'Yenilenen',
'치유의':'İyileştirici',
'마력의':'Büyülü',
'절약의':'Verimli',
'영혼의':'Ruh Bağlı',
'예리한':'Keskin',
'맹렬한':'Vahşi',
'파멸의':'Yıkıcı',
'게임 설정':'Oyun Ayarları',
'화면 흔들림':'Ekran Sarsıntısı',
'파티클 양':'Parçacık Miktarı',
'효과음 볼륨':'SFX Ses Seviyesi',
'음악 볼륨':'Müzik Ses Seviyesi',
'난이도':'Zorluk',
'자동 물약':'Otomatik İksir',
'최소 줍기 등급':'Min Toplama Derecesi',
'최소 줍기 티어':'Min Toplama Kademesi',
'FPS 제한':'FPS Sınırı',
'해상도 스케일':'Çözünürlük Ölçeği',
'펫 자동수거':'Evcil Oto-Toplama',
'화면 설정':'Ekran Ayarları',
'화면 모드':'Görüntü Modu',
'보스 AI 디버그':'Boss AI Hata Ayıklama',
'유령불꽃 크기':'Hayalet Alev Boyutu',
'화면 명암':'Parlaklık',
'유령 글로우':'Hayalet Parıltısı',
'기동:칼날개 AUTO':'Kılıç Kanadı AUTO',
'일반':'Normal',
'어려움':'Zor',
'지옥':'Cehennem',
'이상':'veya üstü',
'사용 안 함':'Kapalı',
'창 모드':'Pencereli',
'보더리스':'Kenarsız',
'전체화면':'Tam Ekran',
'설정':'Ayarlar',
'조작 키 설정 (클릭하여 변경)':'Tuş Atamaları (Değiştirmek için Tıkla)',
'좌클릭 무기 공격':'Sol Tık Silah Saldırısı',
'우클릭 탭 칼등 처내기':'Sağ Tık Kılıç Savuşturma',
'우클릭 홀드 연속 처내기':'Sağ Tık Sürekli Savuşturma',
'SHIFT 작살 발사':'SHIFT Zıpkın Fırlatma',
'이동':'Hareket',
'아이템 줍기':'Eşya Topla',
'능력치 (스탯/패시브)':'İstatistik (Stat/Pasif)',
'분해':'Sök',
'제작':'Üret',
'사망':'Ölüm',
'부활':'Diriliş',
'로비로':'Lobiye',
'가방에 공간이 없습니다!':'Çantada yer yok!',
'가방이 가득 찼습니다!':'Çanta dolu!',
'창고가 가득 찼습니다!':'Depo dolu!',
'퀵슬롯이 가득 찼습니다!':'Hızlı yuva dolu!',
'결정 주머니가 가득 찼습니다!':'Kristal pouch is full!',
'결정 주머니 가득!':'Kristal pouch full!',
'악의가 부족합니다!':'Yetersiz Kötülük!',
'가방이 비어있습니다':'Çanta boş',
'창고가 비어있습니다':'Depo boş',
'비어있음':'Boş',
'어픽스 없음':'Özellik yok',
'장착!':'Kuşanıldı!',
'해제':'Çıkarıldı',
'보관':'Depola',
'꺼내기':'Çıkar',
'현재 장착':'Mevcut donanım',
'없음 — 제작하세요!':'Yok — Bir tane üret!',
'리셋할 포인트가 없습니다':'Sıfırlanacak puan yok',
'키 설정 초기화 완료':'Tuş ayarları sıfırlandı',
'제작 확률':'Üretim Şansı',
'제작 비용':'Üretim Maliyeti',
'보유 악의':'Sahip olunan Kötülük',
'보스방':'Boss Odası',
'안식처':'Sığınak',
'회복':'İyileş',
'점화':'Ateşle',
'비석':'Stel',
'읽기':'Oku',
'파괴':'Yık',
'제단':'Sunak',
'기원':'Dua',
'잔해':'Enkaz',
'열기':'Aç',
'문지기':'Kapıcı',
'부활 판정 중...':'Diriliş değerlendirmesi...',
'기폭 준비!':'Patlatma hazır!',
'탈출':'Kaç',
'연타':'Tıkla',
'추적암전':'Tracking Yıldırım',
'만화광선':'Işıltı Işını',
'최종 마법':'Son Büyü',
'감시중':'İzleniyor',
'대기':'Beklemede',
'작동중':'Aktif',
'설치 가능':'Kurulabilir',
'균열 임박!':'Gedik yaklaşıyor!',
'흡수 중...':'Emiliyor...',
'흡수 완료 — 재입력으로 회수':'Tamam — tekrar bas topla',
'화상':'Yanık',
'당기기':'Çek',
'밀어내기':'İt',
'단계':'kademe',
'단':'kademe',
'습득!':'Öğrenildi!',
'리셋!':'Sıfırla!',
'세팅!':'Ayarlandı!',
'회수':'Geri Çağır',
'합체 해제':'Ayır',
'리셋':'Sıfırla',
'환불':'İade',
'파트너 클릭!':'Eşe tıkla!',
'SP부족!':'SP gerekli!',
'같은 보석 스킬 습득 시 합체 가능':'Aynı mücevher becerisi öğrenince birleştir',
'펼쳐서 초기화':'Sıfırlamak için aç',
'슬롯:':'Yuva:',
'남은 SP':'Kalan SP',
'맞아서 사망':'Vuruştan öldü',
'레벨':'Seviye',
'최대HP':'Maks HP',
'방랑 기사':'Gezgin Şövalye',
'보물 악마':'Hazine Şeytanı',
'거울의 사도':'Ayna Havarisi',
'상인 악마':'Tüccar Şeytanı',
'사슬의 죄수':'Zincirli Mahkum',
'시간의 사도':'Zaman Havarisi',
'탐욕의 사도':'Açgözlülük Havarisi',
'저주받은 쌍둥이':'Lanetli İkizler',
'차원 균열체':'Boyutsal Yarık',
'죽음 그 자체':'Ölümün Kendisi',
'HP결정':'HP Kristal',
'ST결정':'ST Kristal',
'MP결정':'MP Kristal',
'ATK결정':'SLD Kristal',
'DEF결정':'SVN Kristal',
'속도결정':'Hız Kristal',
'크리결정':'Kritik Kristal',
'치명결정':'KritHsr Kristal',
'화염결정':'Ateş Kristal',
'냉기결정':'Buz Kristal',
'암흑결정':'Karanlık Kristal',
'번개결정':'Yıldırım Kristal',
'신성결정':'Kutsal Kristal',
'생명결정':'Hayat Kristal',
'기력결정':'Dayanıklılık Kristal',
'마력결정':'Mana Kristal',
'행운결정':'Şans Kristal',
'조각':'Parça',
'파편':'Kırık',
'순수결정':'Saf Kristal',
'완전결정':'Mükemmel Kristal',
'결정 주머니':'Kristal Kesesi',
'결정이 없습니다':'Kristal yok',
'가루':'Toz',
'전체':'Tümü',
'스탯':'İstats.',
'원소':'Element',
'유틸':'Yardm.',
'현재':'Mevcut',
'최대 강화 달성 (+20)':'Maks geliştirme (+20)',
'강화 시':'Geliştirmeden sonra',
'합성':'Sentezle',
'같은 종류·같은 성급 결정 3개 → 1성급 상승 (강화 리셋)':'3 aynı tür & derece → 1 derece yükseltme (geliştirme sıfırlanır)',
'합성 가능한 결정이 없습니다 (같은 종류·성급 3개 필요)':'Sentezlenebilir kristal yok (3 aynı tür & derece gerekli)',
'결정 분해 → 결정 가루':'Kristal Ayrıştırma → Toz',
'분해할 결정이 없습니다':'Ayrıştırılacak kristal yok',
'결정 제작 (가루 → 결정)':'Kristal Üret (Toz → Kristal)',
'탈착':'Çıkar',
'빈 슬롯':'Boş slot',
'결정 선택 후 클릭':'Kristal seç sonra tıkla',
'클릭하여 선택결정 장착':'Seçili kristali kuşanmak için tıkla',
'획득!':'Elde edildi!',
'제작!':'Üretildi!',
'합성!':'Sentezlendi!',
'최상위 일괄합성':'Toplu Sentez',
'일괄합성 완료':'Toplu sentez tamam',
'벌레굴':'Kurt Yuvası',
'얼음굴':'Buz Cavern',
'고통의 화염지대':'Cehennem Çölü',
'지옥의 군단':'Cehennem Legion',
'사도의 마굴':'Havari İni',
'지옥성':'Cehennem Kalesi',
'엑소듀서 전사':'Exoduser Savaşçısı',
'포이즈':'Denge',
'지옥창고':'Cehennem Deposu',
'선택분해':'Seçmeli Söküm',
'쓰레기':'Çöp',
'복구 불가!':'Kurtarılamaz!',
'중요잠금':'Önemli-kilitli',
'자동 장착!':'Otomatik kuşanıldı!',
'분해! 가루 +':'Söküldü! Toz +',
'평화보호':'Kalkan',
'지진폭풍':'Deprem Fırtınası',
'회전기폭':'Döndür-Patlat',
'공격':'Saldırı',
'보호막':'Bariyer',
'합체 스킬로 통합됨':'Birleşik beceriye katıldı',
'얼음보주 안에선 사용 불가!':'Cannot use inside Buz Orb!',
'Shift+키로 폭파':'Shift+tuş patlatma',
'취소':'İptal',
'쿨다운 중...':'Bekleme...',
'시전 중...':'Büyü yapılıyor...',
'악의 부족! (12)':'Yetersiz Kötülük! (12)',
'악의 부족! (15)':'Yetersiz Kötülük! (15)',
'악의 부족! (20)':'Yetersiz Kötülük! (20)',
'악의 부족! (10)':'Yetersiz Kötülük! (10)',
'HP 부족!':'Yetersiz HP!',
'필살기 슬롯 클릭하여 배정!':'Son vuruş yuvasına tıkla!',
'필살기 스킬을 습득하세요':'Son vuruş becerisi öğren',
'우클릭(칼등치기)에 합체됨':'Sağ tıka birleştirildi',
'T(석궁자동)에 세팅하세요':'T\'ye ayarla (otomatik yay)',
'공성쇠뇌 철거 → 이동식':'Kuşatma yayı → taşınabilir',
'ST 부족! (100)':'Yetersiz ST! (100)',
'HP 99% 이상!':'HP 99%+!',
'그로기 보스 없음!':'Sersemleşmiş patron yok!',
'이미 폭풍 지역!':'Zaten fırtına bölgesinde!',
'이미 빙풍 지역!':'Zaten buz fırtınası bölgesinde!',
'💎 푸른비 해금!':'💎 Gök Yağmuru açıldı!',
'💫 버스트루프 해금!':'💫 Patlama Döngüsü açıldı!',
'👻 유령 허수아비 해금!':'👻 Hayalet Yem açıldı!',
'쿨 ':'BK ',
'과부하 ':'Aşırı Yük ',
'🕊️💎 블루콩!':'🕊️💎 Mavi Fasulye!',
'🛡️💎 빨콩→블루콩!':'🛡️💎 Kırmızı→Mavi Fasulye!',
'🛡️💎 무지개→블루콩!':'🛡️💎 Gökkuşağı→Mavi Fasulye!',
'레어':'Nadir',
'슬롯':'Yuva',
'성공률':'Başarı Oranı',
'AI 자동 강화':'AI Otomatik Geliştirme',
'최대 강화 달성!':'Maks geliştirme ulaşıldı!',
'최대 강화':'Maks geliştirilmiş',
'회복량':'İyileşme',
'분해할 아이템이 없습니다.':'Sökülecek eşya yok.',
'🔨 제작':'🔨 Üret',
'체간':'Duruş',
'아이템에 마우스를 올리거나 좌클릭으로 선택하세요':'Eşyanın üzerine gel veya sol tıkla',
'중독':'Zehir',
'지뢰':'Mayın',
'함정':'Tuzak',
'산호가시':'Mercan Dikeni',
'투사체':'Mermi',
'도트':'DoT',
'레어몹':'Nadir Canavar',
'구역':'Bölge',
'가시!':'Diken!',
'림보':'Araf',
'색욕':'Şehvet',
'탐식':'Oburluk',
'탐욕':'Açgözlülük',
'분노':'Gazap',
'이단':'Sapkınlık',
'폭력':'Şiddet',
'분노!':'Öfke!',
'탐욕!':'Açgözlülük!',
'💀 분노 폭발!':'💀 Öfke Patlaması!',
'심연의 분노!':'Uçurum Öfkesi!',
'쌍둥이의 분노!':'İkizlerin Öfkesi!',
'소환굴':'Çağırma Deliği',
'처치!':'Yenildi!',
'왕관 착용':'Taç Açık',
'왕관 해제':'Taç Kapalı',
'맨손':'Çıplak',
'없음':'Yok',
'갑옷':'Zırh',
'부츠':'Bot',
'매직':'Büyülü',
'챔피언':'Şampiyon',
'초속':'Acele',
'강타':'Çarpma',
'재생':'Yenilenme',
'맹독':'Zehir',
'소환':'Çağırma',
'기생':'Parazit',
'분열':'Bölünme',
'용암자취':'Lav İzi',
'사망폭발':'Ölüm Patlaması',
'화염사슬':'Ateş Chain',
'광전':'Çılgınlık',
'텔레포트':'Işınlanma',
'소용돌이':'Girdap',
'환영':'Hayalet',
'전격반사':'Şok Yansıması',
'감전':'Elektrikle',
'낙뢰':'Gök Gürültüsü',
'연쇄전격':'Chain Yıldırım',
'동료불사':'Ölümsüz Müttefik',
'영혼포식':'Ruh Yutma',
'시간왜곡':'Zaman Bükülmesi',
'혼돈변이':'Kaos Mutasyonu',
'복수자':'İntikamcı',
'마법보초':'Büyü Nöbetçisi',
'환영술사':'İllüzyonist',
'함성':'Savaş Çığlığı',
'치유':'İyileştir',
'신속':'Çeviklik',
'다크 판타지 전사. 거대검+검은 갑옷':'Karanlık fantezi savaşçısı. Büyük kılıç + Siyah zırh',
'⚡ 사슬이동:강화!':'⚡ Zincir:Güçlendirildi!',
'⚡ 사슬기동:화염!':'⚡ Zincir Sürüş: Alev!',
'달성!':'Başarıldı!',
'ST':'ST',
'부족!':'Yetersiz!',
'타':'Vuruş',
'🌀 당기기 모드':'🌀 Çek Mode',
'💥 밀어내기 모드':'💥 İt Mode',
'🕊️빨콩 흡수':'🕊️Kırmızı fasulye emme',
'🕊️흡수':'🕊️Emme',
'💎유도 폭발!':'💎Güdümlü Patlama!',
'💥반사 폭발!':'💥Yansıma Patlaması!',
'⚡⚡ 참회 귀환!':'⚡⚡ Tövbe Dönüşü!',
'⚡ 참회!':'⚡ Tövbe!',
'파도!':'Dalga!',
'암전!':'Yıldırım!',
'암흑!':'Karanlık!',
'암흑창!':'Karanlık Spear!',
'빛창!':'Işık Mızrağı!',
'체 소환!':'çağırıldı!',
'개 설치!':'yerleştirildi!',
'💥 보스 그로기!':'💥 Boss Sersem!',
'💥 그로기!':'💥 Sersem!',
'보상':'Ödül',
'⚡ 암전나선!':'⚡ Yıldırım Helix!',
'🌋 지진폭풍!':'🌋 Deprem Fırtınası!',
'SP슬롯':'SP Yuvası',
'F슬롯':'F Yuvası',
'⚔🩸 독혈해방!':'⚔🩸 Veba Özgürleşmesi!',
'⚔ 칼날 해방!':'⚔ Kılıç Özgürleşmesi!',
'🔨🌋 지옥강타!':'🔨🌋 Inferno Çarpma!',
'🔨 대왕치기!':'🔨 Giant Çarpma!',
'✟ 결계의 영역!':'✟ Koruma Alanı!',
'✟ 물의 영역!':'✟ Su Alanı!',
'✟ 파쇄의 영역!':'✟ Kırılma Alanı!',
'✟ 침식의 영역!':'✟ Aşındırma Alanı!',
'✟ 관통의 영역!':'✟ Delme Alanı!',
'✟ 권능의 영역!':'✟ Egemenlik Alanı!',
'🛡 회복의 영역!':'🛡 Kutsal Alan!',
'임계...!':'Kritik...!',
'기폭팔!':'Patlatma!',
'강제기폭!':'Zorla Patlatma!',
'자동기폭!':'Otomatik Patlatma!',
'회전기폭!':'Döndürerek Patlatma!',
'해제기폭!':'Serbest Patlatma!',
'지진기폭!':'Deprem Patlatması!',
'혼돈의 왕관':'Kaos Tacı',
'전지전능의 왕관':'Her Şeye Gücü Yeten Taç',
'악마의 팔찌':'Şeytan Bileziği',
'생명의 팔찌':'Hayat Bileziği',
'🌊 위→아래 파도!':'🌊 Üst→Alt Dalga!',
'🌊 오른→왼 파도!':'🌊 Sağ→Sol Dalga!',
'🌊 아래→위 파도!':'🌊 Alt→Üst Dalga!',
'🌊 왼→오른 파도!':'🌊 Sol→Sağ Dalga!',
'무적!':'Yenilmez!',
'🪞 반격!':'🪞 Karşı Atak!',
'💢 반격!':'💢 Karşı Atak!',
'흡수!':'Emme!',
'반격 발사!':'Karşı Atış!',
'저주! 드랍률 -50%':'Lanet! Düşüş -50%',
'도망!':'Kaçış!',
'위상!':'Faz!',
'방어!':'Kalkan!',
'회수 HP+':'Geri Çağır HP+',
'이동식 복귀':'Mobil Dönüş',
'약점!':'Zayıflık!',
'저항!':'Direnç!',
'콤보 종료: ':'Kombo End: ',
'악의 +':'Kötülük +',
'저주 ':'Lanet ',
'불발...':'Boş çıktı...',
'작살 약점!':'Zıpkın Zayıflığı!',
'전염 x':'Veba x',
'흡수 완료!':'Emme Tamamlandı!',
'부활 성공!':'Diriliş Başarılı!',
'부활 실패...':'Diriliş Başarısız...',
'차원 이동!':'Boyut Kayması!',
'기절 해제':'Sersemleme Bitti',
'악의 부족':'Yetersiz Kötülük',
'스킬 미습득':'Öğrenilmiş beceri yok',
'펼치기':'Genişlet',
'접기':'Daralt',
'조건 미달!':' karşılanmadı!',
'해제!':' Ayrıldı!',
'자동 ON':' Oto. AÇIK',
'자동 OFF':' Oto. KAPALI',
'스킬 해제':' beceri boş',
'닫기':'Kapat',
'장착 중':'Kuşanıldı',
'보관 아이템':'Depolanan Eşya',
'클릭으로 선택 · ESC로 닫기':'Seçmek için tıkla · ESC kapat',
'선택됨':'Seçildi',
'악의 부족! (30)':'Yetersiz Kötülük! (30)',
'MP 부족! (40)':'Yetersiz MP! (40)',
'MP 부족! (100)':'Yetersiz MP! (100)',
'MP 부족! (10)':'Yetersiz MP! (10)',
'MP 부족! (':'Yetersiz MP! (',
'✟ 시전...':'✟ Büyü...',
'🌋 시전...':'🌋 Büyü...',
'⛧ 시전...':'⛧ Büyü...',
'❄ 진입!':'❄ Giriş!',
'🔱 작살!':'🔱 Zıpkın!',
'레벨 부족! (요구: Lv.':'Seviye çok düşük! (Gerek: Sv.',
' 장착!':' Kuşanıldı!',
' 해제':' Çıkarıldı',
'👿 악의 추출: +':'👿 Kötülük Özütü: +',
'F 슬롯 해제':'F Yuva boş',
'💫 집중...':'💫 Odaklanma...',
'⚡ 마력연사!':'⚡ Büyü Yağmuru!',
'❄빙결!':'❄Dondu!',
'🟢독!':'🟢Zehir!',
'⚡감전!':'⚡Şok!',
'🔥화상!':'🔥Yanıyor!',
'✦ 여신의 가호 — SP+5 AP+3':'✦ Tanrıça Lütfu — SP+5 AP+3',
'⚔ 기동칼날개!':'⚔ Kılıç Kanadı!',
'🔥 화염관통!':'🔥 Ateş Delme!',
'🔱 관통!':'🔱 Delme!',
'⚔ 칼날!':'⚔ Kılıç!',
'💥 착지!':'💥 İniş!',
'💫 기절!':'💫 Sersem!',
'⚡ 체간삭감!':'⚡ Denge Kırılması!',
'⚡ 기동파괴! ':'⚡ Zincir Ezme! ',
'🔥 기동불꽃!':'🔥 Zincir Alevi!',
'🔥 기동불꽃! ':'🔥 Zincir Alevi! ',
'단계 ×':' x',
'⚡ 기동전폭! x':'⚡ Zincir Patlaması! x',
'🔥🔥 3중폭!':'🔥🔥 Alev x3!',
'🔥🔥🔥 6중폭!':'🔥🔥🔥 Alev x6!',
'🔥🔥🔥🔥 9중폭!':'🔥🔥🔥🔥 Alev x9!',
'💥 불꽃폭발! ':'💥 Alev Patlaması! ',
'🔥 기동불꽃 준비!':'🔥 Zincir Alevi Hazır!',
'🔨 기동파괴 준비!':'🔨 Zincir Ezme Hazır!',
'⚡ 기동전폭 준비!':'⚡ Zincir Patlaması Hazır!',
'⚡ 과부하! 5초':'⚡ Aşırı Yük! 5sn',
'💫 자동 버스트!':'💫 Otomatik Patlama!',
'🔨 칼등날개!':'🔨 Kalkan Kanadı!',
'💥폭발!':'💥Patlama!',
'🛡️💎 유도반사!':'🛡️💎 Güdümlü Yansıma!',
'⚡💎 블루콩!':'⚡💎 Mavi Fasulye!',
'💎 블루콩!':'💎 Mavi Fasulye!',
'⚡반사!':'⚡Yansıma!',
'💎 푸른비 OFF':'💎 Gök Yağmuru KAPALI',
'💎 푸른비 ON!':'💎 Gök Yağmuru AÇIK!',
'🔥 지옥진!':'🔥 Cehennem Dizilişi!',
'🔥 업화선!':'🔥 Cehennem Işını!',
'✦ 평화 충격파! ':'✦ Barış Şok Dalgası! ',
'⚡ 전류 방출!':'⚡ Akım Salınımı!',
'⚡⚡ 레인라이트닝!':'⚡⚡ Yıldırım Yağmuru!',
'💫 광역!':'💫 Alan Hasarı!',
'🔥 불장판!':'🔥 Ateş Bölgesi!',
'💫 피니셔!':'💫 Son Vuruş!',
'☠ 지옥에서 귀환!':'☠ Cehennemden Döndü!',
'☠ 완전 사망!':'☠ Kalıcı Ölüm!',
'⚔ 처형! ':'⚔ İnfaz! ',
'💥 지뢰!':'💥 Mayın!',
'⚠ 함정!':'⚠ Tuzak!',
'❌ 우클릭으로! -':'❌ Sağ tık kullan! -',
'❌ Q키로! -':'❌ Q kullan! -',
'💥무지개 폭발! ':'💥Gökkuşağı Patlaması! ',
'🛡️💎 블루콩!':'🛡️💎 Mavi Fasulye!',
'⬜화이트볼!':'⬜Beyaz Top!',
'✨💎 블루콩!':'✨💎 Mavi Fasulye!',
'💜다크볼!':'💜Karanlık Top!',
'❄빙판!':'❄Buz Zemin!',
'🌨빙결!':'🌨Dondu!',
'🕸둔화!':'🕸Yavaşlama!',
'⚠트랩!':'⚠Tuzak!',
'💀 역병 처형!':'💀 Veba İnfazı!',
'💥 역병 Finale!':'💥 Veba Finali!',
'⚔ 균열 악마!':'⚔ Yarık Şeytanı!',
'자동회수 HP+':'Oto-Geri Çağır HP+',
'MP 부족 — 연사 해제':'MP düşük — Seri Ateş Kapalı',
'MP 부족 — 푸른비 OFF':'MP düşük — Gök Yağmuru KAPALI',
'🛡️반사!':'🛡️Yansıma!',
'⚡🦴 참회 귀환!':'⚡🦴 Tövbe Dönüşü!',
'🦴⚡해골번개!':'🦴⚡Kemik Yıldırımı!',
'⚡악의폭풍!':'⚡Kötülük Fırtınası!',
'❄아이스스톰!':'❄Buz Fırtınası!',
'⚡ 암전폭발!':'⚡ Yıldırım Patlaması!',
'⚡ 레인라이트닝! x':'⚡ Yıldırım Yağmuru! x',
'❄ 탈출!':'❄ Kaç!',
'⚡쉴드!':'⚡Kalkan!',
'❄🌪️ 얼음보주!':'❄🌪️ Buz Küresi!',
'🌪️ 전개!':'🌪️ Yerleştir!',
'❄ 빙결흡인!':'❄ Don Girdabı!',
'❄☄ 빙결폭발!':'❄☄ Don Patlaması!',
'☄️ 흡인!':'☄️ Girdap!',
'☄️ 대폭발!':'☄️ Mega Patlama!',
'❄ 얼음보주!':'❄ Buz Küresi!',
'⏳ 시간왜곡!':'⏳ Zaman Bükülmesi!',
'쿨다운!':'Bekleme!',
'❄ 파쇄!':'❄ Paramparça!',
'☄️💥 대폭발!':'☄️💥 Mega Patlama!',
'반사!':'Yansıma!',
'💀 도넛!':'💀 Çörek!',
'💀 전멸!':'💀 İmha!',
'🌊 파도!':'🌊 Dalga!',
'속박!':'Bağla!',
'반격!':'Karşı!',
'분신!':'Klon!',
'분신 파괴!':'Klon Yok Edildi!',
'무기 해방!':'Silah Serbest!',
'❄프리즌!':'❄Hapishane!',
'⚡ 증표 ':'⚡ İşaret ',
'흔들!':'Sarsıntı!',
'⚠ 광역 발사!':'⚠ AoE Ateş!',
'🔥 확산!':'🔥 Yayılma!',
'⚠ 돌진!':'⚠ Hücum!',
'🦅 도약!':'🦅 Sıçrama!',
'⚡ 레이저!':'⚡ Lazer!',
'🌊 충격파!':'🌊 Şok Dalgası!',
'👹 소환!':'👹 Çağırma!',
'☄ 유성우!':'☄ Meteor Yağmuru!',
'🖐 잡기!':'🖐 Yakala!',
'🌀 회전참!':'🌀 Kasırga!',
'💣 지뢰!':'💣 Mayın!',
'🌀 흡인!':'🌀 Vakum!',
'🔴 빨간콩 폭풍!':'🔴 Kırmızı Fasulye Fırtınası!',
'🔴🔴 콩 비!':'🔴🔴 Fasulye Yağmuru!',
'🌊 부채꼴 충격파!':'🌊 Yelpaze Şok Dalgası!',
'✴ 멸광 레이저!':'✴ İmha Lazeri!',
'🔴 추적 장판!':'🔴 İzleme Bölgesi!',
'💥 속성탄!':'💥 Element Atışı!',
'⚔ 검기!':'⚔ Kılıç Enerjisi!',
'⚔ 재단참!':'⚔ Biçme Kesimi!',
'🌀 나선탄!':'🌀 Spiral Atış!',
'⚠ 찌르기!':'⚠ Saplama!',
'🔥🔥 지옥기둥!':'🔥🔥 Cehennem Sütunu!',
'⚔ 환영검!':'⚔ Hayalet Kılıcı!',
'💢 반격자세!':'💢 Karşı Duruşu!',
'⚔ 연격!':'⚔ Kombo!',
'🌑 암흑!':'🌑 Karanlık!',
'👥 분신!':'👥 Klon!',
'🌋 균열!':'🌋 Yarık!',
'🌊 파동!':'🌊 Dalgalanma!',
'💣 추적지뢰!':'💣 Güdümlü Mayın!',
'⏪ 되감기!':'⏪ Geri Sarma!',
'🌀 중력장!':'🌀 Yerçekimi Alanı!',
'🔨 벽밀기!':'🔨 Duvar İtme!',
'☠ 독안개!':'☠ Zehir Sisi!',
'⛓ 감옥!':'⛓ Hapishane!',
'⚡ 연쇄번개!':'⚡ Zincir Yıldırım!',
'🔮 궤도탄!':'🔮 Yörünge Atışı!',
'🛡 방패돌진!':'🛡 Kalkan Hücumu!',
'🪞 반격자세!':'🪞 Karşı Duruşu!',
'⚓ 속박!':'⚓ Bağla!',
'👤 분신!':'👤 Klon!',
'🖐 탈취!':'🖐 Çalma!',
'🔥🔥 용암 지대!':'🔥🔥 Lav Bölgesi!',
'🌧🌧 화염 폭격!':'🌧🌧 Ateş Yağmuru!',
'⚡⚡ 전격 장막!':'⚡⚡ Yıldırım Perdesi!',
'💀 내 곁으로!':'💀 Bana Gel!',
'⭕ 안전!':'⭕ Güvenli!',
'💀💀 전멸 폭발!':'💀💀 İmha Patlaması!',
'⚡ 쐐기 소멸!':'⚡ Kama Yok Oluşu!',
'🌊충격파!':'🌊Şok Dalgası!',
'👿악의+100':'👿Kötülük+100',
'💥패링폭발!':'💥Savuşturma Patlaması!',
'균열 충돌! ':'Yarık Çarpışması! ',
'벽 충돌! ':'Duvar Çarpışması! ',
'소환!':'Çağırma!',
'환영!':'Hayalet!',
'⚡낙뢰!':'⚡Gök Gürültüsü!',
'⚡빔!':'⚡Işın!',
'환영술!':'İllüzyon!',
'💀소환!':'💀Çağırma!',
'🔮주술!':'🔮Lanet!',
'🩸산란!':'🩸Yumurtlama!',
'💢광폭!':'💢Çılgınlık!',
'🕷산란!':'🕷Yumurtlama!',
'❄서리!':'❄Ayaz!',
'❄빙결파!':'❄Don Dalgası!',
'💀빙마!':'💀Buz Şeytanı!',
'돌진!':'Hücum!',
'충격파!':'Şok Dalgası!',
'독안개!':'Zehir Sisi!',
'연타!':'Seri Vuruş!',
'포효!':'Kükreme!',
'강화!':'Geliştirme!',
'꼬리!':'Kuyruk!',
'은신...':'Gizlenme...',
'기습!':'Pusu!',
'산란!':'Doğurma!',
'독가스!':'Zehirli Gaz!',
'소멸...':'Çözünme...',
'강타!':'Ezme!',
'분비!':'Salgılama!',
'채찍!':'Kırbaç!',
'출혈!':'Kanama!',
'급강하!':'Dalış!',
'방출!':'Boşalma!',
'충격!':'Darbe!',
'치유!':'İyileştir!',
'의식!':'Ritüel!',
'지옥불!':'Cehennem Ateşi!',
'끌려감!':'Sürüklendi!',
'혀!':'Dil!',
'응시!':'Bakış!',
'낙하!':'Düşüş!',
'핏방울!':'Kan Damlası!',
'일어남!':'Kalkış!',
'휩쓸기!':'Süpürme!',
'웅크림':'Çömelme',
'뼈칼날!':'Kemik Kılıcı!',
'감속!':'Yavaş!',
'비명!':'Çığlık!',
'화산탄!':'Yanardağ Atışı!',
'자폭!':'Kendini İmha!',
'감싸기!':'Sarma!',
'잡기!':'Yakala!',
'내리찍기!':'Çarpma!',
'브레스!':'Nefes!',
'비행!':'Uçuş!',
'용암비!':'Lav Yağmuru!',
'물뿜기!':'Su Jeti!',
'빛...':'Işık...',
'삼키기!':'Yut!',
'마비!':'Felç!',
'방전!':'Boşalma!',
'집게찍기!':'Pincer Çarpma!',
'찍기!':'Çarpma!',
'붙잡기!':'Yakala!',
'감아올리기!':'Sarılma!',
'파편!':'Parça!',
'할퀴기!':'Tırmalama!',
'기생충!':'Parazit!',
'심연 해방!':'Uçurum Serbest!',
'촉수난타!':'Dokunaç Yağmuru!',
'삼지창!':'Üç Çatallı!',
'소용돌이!':'Girdap!',
'해일!':'Tsunami!',
'끼걱!':'Gıcırtı!',
'폭발!':'Patlama!',
'체인!':'Zincir!',
'갈기!':'Yele!',
'공포!':'Terör!',
'흡혈!':'Emme!',
'베기!':'Kesme!',
'비이이명!!':'Çınlama!!',
'분열!':'Bölünme!',
'3연참!':'Üçlü Kesme!',
'패링!':'Savuşturma!',
'...복사...':'...Kopyalama...',
'불균형...저주!':'Dengesizlik...Lanet!',
'저주!':'Lanet!',
'균형...강화!':'Balance...Geliştir!',
'심판의 기둥!':'Yargı Sütunu!',
'처형 선고!':'Ölüm Cezası!',
'고통의 해방!':'Acı Özgürleşmesi!',
'너도 느껴봐라!':'Bunu da hisset!',
'대검난무!':'Büyük Kılıç Çılgınlığı!',
'촉수!':'Dokunaç!',
'전방위 빔!':'Çok Yönlü Işın!',
'회피!':'Kaçın!',
'[F] 상점':'[F] Mağaza',
'거래 성공!':'Ticaret Başarılı!',
'악의 부족! (':'Yetersiz Kötülük! (',
'상인이 떠납니다...':'Tüccar gidiyor...',
'사슬 해방!':'Zincir Serbest!',
'완전 해방!':'Tam Serbest!',
'⏪ 시간 되감기!':'⏪ Zaman Geri Sarma!',
'전환!':'Değiştir!',
'부활 ':'Diriliş ',
'🌀균열!':'🌀Yarık!',
'...사라짐':'...Kayboldu',
'낫 베기!':'Tırpan Kesimi!',
'☠ 죽음의 선고!':'☠ Ölüm Cezası!',
'선고 집행...':'İnfaz ediliyor...',
'⚡패링!':'⚡Savuşturma!',
'경직!':'Sarsılma!',
'⚠ 잡혔다!':'⚠ Yakalandın!',
'💥 내던지기!':'💥 Fırlatma!',
'💥 소용돌이 폭발!':'💥 Girdap Patlaması!',
'👻 순간이동!':'👻 Işınlanma!',
'💫 기절! 5초':'💫 Sersem! 5sn',
'찌르기 반격!':'Saplama Karşılığı!',
'💢 폭발!':'💢 Patlama!',
'반격 실패':'Karşı Başarısız',
'탈취 반격!':'Çalma Karşılığı!',
'무기 봉인!':'Silah Mührü!',
'냠!':'Nyam!',
'합체!':'Birleştirildi!',
'출구가 열렸다!':'Çıkış açıldı!',
'보물상자 출현!':'Hazine sandığı belirdi!',
'출구':'Çıkış',
'⚠ 문지기가 살아있다!':'⚠ Kapıcı hâlâ hayatta!',
'⏱ 타임어택 ':'⏱ Zamana Karşı ',
'처치율 ':'Öldürme Oranı ',
'불사 보호':'Ölümsüz Koruma',
'환영 소멸!':'Hayalet Kayboldu!',
'부활력 ':'Diriliş Gücü ',
'✟ 신성력 억제! (':'✟ Kutsal Baskı! (',
'부활 실패 (':'Diriliş Başarısız (',
'⚡순간이동!':'⚡Işınlanma!',
'👻 동반부활!':'👻 Ortak Diriliş!',
'✟ 신성력 억제!':'✟ Kutsal Baskı!',
'💀 부활 판정 중...':'💀 Diriliş değerlendirmesi...',
'⚔ 문지기 처치!':'⚔ Kapıcı Yenildi!',
'🚪 보스방 개방!':'🚪 Boss Odası Açıldı!',
'잔해 출현!':'Enkaz belirdi!',
'🌀균열 발생!':'🌀Yarık açıldı!',
'🔥복수!':'🔥İntikam!',
'💥폭독혈!':'💥Veba Kanı!',
'빙판!':'Buz Zemin!',
'❄최종빙결!':'❄Son Dondurma!',
'빙마 처치!':'Buz Şeytanı Yenildi!',
'분리!':'Ayrılma!',
'뼈 파편!':'Kemik Parçası!',
'태아 처치!':'Fetüs Yenildi!',
'지배자 처치!':'Efendi Yenildi!',
'용암!':'Lav!',
'화룡 처치!':'Ateş Ejderi Yenildi!',
'최후의 비명!':'Son Çığlık!',
'산화...':'Oksidasyon...',
'심판자 처치!':'Yargıç Yenildi!',
'고통의 왕 처치!':'Acı Kralı Yenildi!',
'수역!':'Su!',
'파편 폭발!':'Parça Patlaması!',
'거대어 처치!':'Leviathan Yenildi!',
'대사도 처치!':'Baş Havari Yenildi!',
'독웅덩이!':'Zehir Havuzu!',
'화염장판!':'Ateş Bölgesi!',
'전기장!':'Elektrik Alanı!',
'무기 드롭!':'Silah Düşüşü!',
'보물 발견!':'Hazine Bulundu!',
'상인의 주머니 +':'Tüccar Kesesi +',
'속박의 파편!':'Bağlama Kırığı!',
'시간의 조각!':'Zaman Parçası!',
'저주 해제!':'Lanet Kalktı!',
'차원의 결정!':'Boyutsal Kristal!',
'전설 아이템!':'Efsanevi Eşya!',
'죽음을 이겨냈다!':'Ölümü Yendin!',
'💥대폭발!':'💥Mega Patlama!',
'⚡강화!':'⚡Geliştirme!',
'장비 ':'Ekipman ',
'💫 진동!':'💫 Titreşim!',
'❄ 무적!':'❄ Yenilmez!',
'👻 유령!':'👻 Hayalet!',
'집중 해제!':'Odaklanma İptal!',
'집중!':'Odaklanma!',
'🕊️ 평화보호 ':'🕊️ Kalkan ',
'🛡 보호막 ':'🛡 Kalkan ',
'🌀 회전보호막 ':'🌀 Dönen Kalkan ',
'💥한방캡!':'💥Tek Vuruş Sınırı!',
'⚡쉴드 파괴!':'⚡Kalkan Yok Edildi!',
'💀 불굴!':'💀 Boyun Eğmez!',
'💀 1회부활!':'💀 1-can Diriliş!',
'감시 회수':'Nöbetçi Geri Çağırma',
'악마화 부활!':'Şeytan Dirilişi!',
'배정 가능한 스킬 없음':'Atanacak beceri yok',
'칼날 없음!':'Kılıç Yok!',
'⚔ 악의사냥!':'⚔ Kötülük Avı!',
'❄🌪️ 얼음소용돌이!':'❄🌪️ Buz Girdabı!',
'🌪️ 폭풍소환!':'🌪️ Girdap Çağırma!',
'🦴 해골무덤!':'🦴 Kemik Mezar!',
'🌹 붉은꽃!':'🌹 Kızıl Çiçek!',
'💥 폭산탄!':'💥 Patlama Atışı!',
'🪡 바늘출!':'🪡 İğne Patlaması!',
'⚡ 전격이동!':'⚡ Işık Adımı!',
'기둥가시로 흡수됨':'Sütun dikeni tarafından emildi',
'🌿 가시덫!':'🌿 Diken Tuzağı!',
'👻 유령총!':'👻 Hayalet Silah!',
'💥 유령총 폭발!':'💥 Hayalet Silah Patlaması!',
'⚡ 전격의창!':'⚡ Yıldırım Mızrağı!',
'🏹 공성쇠뇌 설치!':'🏹 Kuşatma Yayı Yerleştirildi!',
'👻 유령 허수아비!':'👻 Hayalet Yem!',
'💥 폭발 허수아비!':'💥 Patlayıcı Yem!',
'축적!':'Depolandı!',
'축적 중...':'Depolama...',
'만충! 재입력→폭발':'Dolu! Tekrar bas→Patlama',
'폭발! ':'Patlama! ',
'뎀':' HSR',
'🩸 폭독칼날!':'🩸 Veba Kılıcı!',
'⚡날개치기!':'⚡Kanat Vuruşu!',
'🗡 칼등날개!':'🗡 Kalkan Kanadı!',
'🏛️ 악의기둥!':'🏛️ Karanlık Sütun!',
'🌿 기둥가시!':'🌿 Sütun Dikeni!',
'🌋 지옥강타!':'🌋 Cehennem Vuruşu!',
'💥 체간 붕괴!':'💥 Duruş Kırılması!',
'💫 포이즈 파괴!':'💫 Denge Yıkımı!',
'⚡ 뇌전걸음!':'⚡ Hayalet Yürüyüş!',
'✟ 구속의 영역!':'✟ Bağlama Alanı!',
'✟ 신성폭발!':'✟ Kutsal Patlama!',
'⛧ 블랙!':'⛧ Kara Yıldız!',
'🌋 용암소환!':'🌋 Lav Çağırma!',
'필살기 배정!':'Son Vuruş Atandı!',
'완료':'Tamamlandı',
'합체 가능':'Birleştirilebilir',
'부족':'Yetersiz',
'SP 부족! (':'SP gerekli! (',
'🕊️ 히든: 평화의보호 해금!':'🕊️ Gizli: Barış Kalkanı açıldı!',
'⚡ 히든: 참회 해금!':'⚡ Gizli: Tövbe açıldı!',
'배정됨':'Atandı',
'합체 Lv.':'Birleşim Sv.',
'◆ 같은 보석 스킬 습득 시 합체 가능':'◆ Aynı mücevher becerisi öğrenince birleştir',
'▼ 가방 → 창고 보관':'▼ Çanta → Depo',
'▲ 창고 → 가방 꺼내기':'▲ Depo → Çanta',
'✓ 선택됨':'✓ Seçildi',
'⟨ 입력 대기... ⟩':'⟨ Bekleniyor... ⟩',
'⟨ 대기 ⟩':'⟨ Bekle ⟩',
'보조':'Alt',
'키 설정 초기화 (또는 F5 키)':'Tuş Sıfırlama (veya F5)',
'아무 키 또는 마우스 버튼을 누르세요 (ESC = 취소)':'Herhangi bir tuşa veya fare düğmesine bas (ESC = iptal)',
'WebGPU 활성':'WebGPU Aktif',
'WebGL2 활성':'WebGL2 Aktif',
'측정 중...':'Ölçülüyor...',
'불러오기 실패':'Yükleme Başarısız',
'장착':'Kuşanıldı',
'🔒 중요잠금 아이템은 분해 선택 불가!':'🔒 Kilitli eşyalar sökülemez!',
'장비 강화 (실패 시 재료만 소멸)':'Ekipman Geliştir (başarısız: malzeme kaybolur)',
'강화 보너스 적용':'Geliştirme Bonusu Uygulandı',
'강화 실패!':'Geliştirme Başarısız!',
'장착된 장비가 없습니다.':'Kuşanılmış ekipman yok.',
'충분':'Yeterli',
'더 필요':'Daha Fazla Gerek',
'장비 선택':'Ekipman Seç',
'목표치 설정':'Hedef Ayarla',
'악의 투입':'Kötülük Yatır',
'자동 시도':'Otomatik Deneme',
'목표 강화치':'Hedef Geliştirme',
'예상 필요 악의':'Tahmini Kötülük',
'보유':'Sahip',
'강화 시작':'Geliştirmeyi Başlat',
'위에서 장비를 선택하세요':'Yukarıdan ekipman seç',
'⬆ 물약 강화 (최대 10단)':'⬆ İksir Geliştir (max level 10)',
'필요':'Gerekli',
'악의의 분해로 — 장비를 악의로 갈아버려라':'Kötülük Fırını — Ekipmanı kötülüğe çevir',
'전체 선택':'Tümünü Seç',
'전체 해제':'Tümünü Kaldır',
'희귀 이하':'Nadir veya Alt',
'어픽스 리롤!':'Özellik Yeniden Atma!',
'영웅':'Kahramanca',
'전설':'Efsanevi',
'무기 타입':'Silah Türü',
'활 타입':'Yay Türü',
'ST 부족':'Yetersiz ST',
'💀 광폭화!':'💀 Öfkeli!',
'...따라오는 거 아니야. 같은 방향일 뿐이지.':'...Seni takip etmiyorum. Sadece aynı yöne gidiyorum.',
'공기가 달라졌어. 더 썩었군.':'Hava değişti. Daha çürük.',
'여기부터는 악마 영역이야. ...맘대로 해.':'Buradan ötesi şeytan bölgesi. ...İstediğini yap.',
'...이 냄새. 살점이 썩는 냄새야.':'...O koku. Çürüyen et.',
'여기 오래 있으면 미쳐. 나도, 너도.':'Çok kalırsan çıldırırsın. Ben de.',
'이 길의 끝에 뭐가 있을까. ...알고 싶지도 않어.':'Bu yolun sonunda ne var? ...Bilmek istemiyorum.',
'...여기가 끝이야. 돌아갈 길은 없어.':'...Bu son. Geri dönüş yok.',
'작살을 땅에 꽂으면 끌려간다.':'Zıpkını yere sapla ve çekilin.',
'Shift로 작살 던져봐!':'Shift ile zıpkını fırlatmayı dene!',
'패링 성공하면 ST가 회복된다. 공짜 자원이야.':'Savuşturma ST yeniler. Bedava.',
'패링 많이 하면 ST 걱정 없어~':'Çok savuştur, ST sorun olmaz~',
'장비 분해하면 악의를 얻는다. 쓰레기도 자원이야.':'Ekipman sökmek Kötülük verir. Çöp bile kaynak.',
'TAB 열어서 안 쓰는 장비 분해해!':'TAB aç kullanılmayanları sök!',
'그로기 상태의 적에겐 1.5배 데미지가 들어간다.':'Sersem düşmanlar 1.5 kat hasar alır.',
'무릎 꿇으면 전력으로 때려!':'Diz çöktüklerinde tüm gücünle vur!',
'속성 상성이 있다. 화염은 빙결에 약하고, 암전은 암흑에 약하다.':'Elementlerin zayıflıkları var. Ateş→Buz, Yıldırım→Karanlık.',
'무기 속성 바꿔가면서 싸워봐!':'Silah elementlerini değiştirmeyi dene!',
'빙결된 적은 1.5배 데미지를 받는다.':'Donmuş düşmanlar 1.5 kat hasar alır.',
'얼리고 때리는 게 기본이야!':'Dondur sonra vur — temel bu!',
'보스의 빨간 공격은 패링 가능. 보라빛은 회피만.':'Boss kırmızı saldırılar savuşturulabilir. Gökkuşağı sadece kaçma.',
'색깔 잘 봐! 빨강은 받아치고 무지개는 피해!':'Renklere dikkat! Kırmızı savuştur, gökkuşağı kaç!',
'VIT를 올리면 최대 HP가 오른다. 죽기 싫으면 찍어.':'VIT maks HP yükseltir. Yaşamak istiyorsan yatırım yap.',
'STR은 근접, DEX는 활, INT는 마법! 골고루 말고 하나만!':'STR yakın, DEX yay, INT büyü! Birine odaklan!',
'E를 꾹 누르면 빔이 나간다. 짧게 누르면 투사체.':'E basılı = ışın. E kısa = mermi.',
'마법 쓸 때 MP 잘 봐! 빔은 연속으로 깎여!':'Büyüde MP izle! Işın hızla boşaltır!',
'핵터와 디로이가 아이템을 주워준다. 수거 범위 안이면.':'Hecter ve Deroy menzildeki eşyaları toplar.',
'우리한테 고마워해~ 안 주우면 썩잖아.':'Bize teşekkür et~ Kimse toplamazsa çürürler.',
'LCK를 올리면 레어 드롭률이 오른다.':'LCK nadir düşüş oranını artırır.',
'운빨 게임이긴 하지~ LCK 올려봐!':'Hep şans~ LCK yükseltmeyi dene!',
'강화하면 공격력이 쭉쭉 올라가! 악의만 있으면 돼!':'Geliştirme SLD hızla artırır! Sadece Kötülük gerek!',
'강화 확률은 +1에서 99%. 높을수록 떨어진다.':'Geliştirme şansı +1 için 99%. Sonra düşer.',
'실패하면 악의만 날아가~ 장비는 안 부서져!':'Başarısızda sadece Kötülük kaybolur~ Ekipman sağlam!',
'대장간에서 장비 제작도 된다. 악의 30000개면 영웅급 이상.':'Dövücü ekipman da üretir. 30000 Kötülük ile Kahramanca+.',
'랜덤이지만 좋은 거 나올 수도 있어!':'Rastgele, ama iyi bir şey çıkabilir!',
'쉴드는 마법으로, HP는 물리로 깎아야 제대로 먹힌다.':'Kalkan büyü ister, HP fiziksel ister.',
'반대로 치면 50%만 들어가! 무기 바꿔가면서 싸워!':'Yanlış tür sadece 50%! Silah değiştir!',
'장비에 접두사, 접미사가 붙으면 특수 효과가 생긴다.':'Ön/son ekli ekipman özel efektler alır.',
'영웅급 이상 장비에만 붙어! 좋은 거 나오면 강화해!':'Sadece Kahramanca+ ekipman! İyi gelenleri geliştir!',
'강화는 장비를 바꿔도 자동 이전된다. 악의만 있으면.':'Geliştirme yeni ekipmana otomatik aktarılır. Kötülük ile.',
'더 좋은 장비 나오면 바로 장착해! 강화 수치 그대로 옮겨가!':'Daha iyi ekipmanı hemen kuşan! Geliştirme aktarılır!',
'패링을 써야 자원을 흡수한다고!':'Kaynak emmek için savuşturman lazım!',
'F키 회복의 영역을 써봐. 자원이 차올라.':'F tuşu Kutsal Alan dene. Kaynaklar dolar.',
'적이 근접하면 스페이스키야! 가시덫을 활용해!':'Düşmanlar yaklaştığında Space! Diken Tuzağı kullan!',
'기절시켜! 그로기가 터지면 데미지가 1.5배야!':'Sersemlet! Sersem = 1.5 kat hasar!',
'1번 대왕치기로 밀어버려!':'1 numaraya bas Dev Vuruş ile geri it!',
'무릎 꿇었다.':'Diz çöktü.',
'지금이야! 몰아쳐!!':'Şimdi! Saldır!!',
'스킬 포인트 있어! K 눌러서 스킬 찍어봐!':'Beceri puanları var! K bas!',
'...힘이 없으면 여기서 끝이야.':'...Güç olmadan burası son.',
'...쓸 거 아니면 분해해.':'...Gerekmeyenleri sök.',
'아이템 넘쳐나네~ 우리가 주워줄게!':'Bu kadar eşya~ Biz topluyoruz!',
'악의가 바닥이다.':'Kötülük bitti.',
'TAB 열어서 장비 분해해! 쓰레기도 악의가 돼!':'TAB aç ekipman sök! Çöp bile Kötülük olur!',
'좋은 장비가 있네! G 눌러서 대장간 가봐!':'İyi ekipman! G dövücüye!',
'...강화 안 하면 그냥 고철이야.':'...Geliştirmeden sadece hurda.',
'...멈추지 마. 여신은 기다리지 않는다.':'...Durma. Tanrıça beklemez.',
'앞으로 가자~ 나도 여기 오래 있기 싫어.':'Gidelim~ Ben de burada kalmak istemiyorum.',
'...냄새가 짙다. 큰 놈이 있어.':'...Koku yoğun. Büyük bir şey var.',
'준비됐어? 물약 확인하고!':'Hazır mısın? İksirlerini kontrol et!',
'TAB을 눌러. 가방을 열고 장비를 입어야 한다.':'TAB bas. Çantanı aç ve ekipmanını kuşan.',
'주웠으면 껴야지! TAB!':'Topladın mı? Kuşan! TAB!',
'G. 대장간에서 물약도 제작할 수 있다.':'G. Dövücüde iksir de üretebilirsin.',
'악의로 물약 만들어! G키야!':'Kötülükle iksir üret! G bas!',
'기절이야! Ctrl 눌러!':'Sersem! Ctrl bas!',
'Ctrl 유령걸음으로 탈출!':'Ctrl Hayalet Yürüyüş ile kaç!',
'Ctrl 얼음보주로 탈출!':'Ctrl Buz Küresi ile kaç!',
'빨간 탄은 우클릭 패링. 무지개는 Q 패링.':'Kırmızı: sağ tık. Gökkuşağı: Q.',
'나머지는 전부 우클릭 패링 가능해!':'Geri kalanı sağ tıkla savuşturulabilir!',
'빨강=우클릭, 무지개=Q 패링. 나머진 다 쳐내.':'Kırmızı=sağ, Gökkuşağı=Q. Gerisini saptır.',
'무지개는 Q로 패링! 나머지는 전부 우클릭!':'Gökkuşağı Q ile! Gerisi sağ tık!',
'빠져! 물약 마시고 안전한 곳에서 회복해.':'Geri çekil! İksir iç güvenli yerde iyileş.',
'자원 없으면 도망가는 게 답이야!':'Kaynak yok mu? Koşmak cevap!',
'스페이스! 가시덫으로 적 묶어버려!':'Space! Diken Tuzağı ile sabitle!',
'근접이 너무 많아! 거리 벌려!':'Çok fazla yakın dövüşçü! Mesafe aç!',
'...둘러싸이면 끝이야. 빠져나와.':'...Kuşatılırsan biter. Kır çemberi.',
'1번 대왕치기로 쓸어버려!':'1 numaraya bas Dev Vuruş ile süpür!',
'그로기 터지면 데미지 1.5배!':'Sersem 1.5 kat hasar tetikler!',
'회전참이나 광역기로 몰아! 한 놈씩 상대하면 죽어.':'Kasırga veya alan kullan! Teker teker ölürsün.',
'뭉쳐있을 때가 기회야!':'Toplandıklarında fırsatın bu!',
'E로 마력공격을 해봐! 악의 쉴드를 해제할려면 마법 공격을 해야 해!':'E ile büyü saldırısı dene! Kötülük kalkanlarını kırmak için büyü lazım!',
'쉴드는 마법으로, HP는 물리로. 반대로 치면 데미지 안 들어간다.':'Kalkan büyüyle, HP fiziksel. Yanlış tür hasar vermez.',
'L키로 스킬 슬롯에 넣어야 쓸 수 있어.':'L bas becerileri yuvalara ata.',
'C키를 눌러. 패시브 포인트가 쌓여있다.':'C bas. Pasif puanlar birikti.',
'C키! 패시브 올리면 진짜 강해져!':'C! Pasifler çok güçlendirir!',
'스태미나가 부족하다. 무리하지 마.':'Dayanıklılık düşük. Aşırıya kaçma.',
'ST 없으면 스킬 못 써! 잠깐 빠져!':'ST yoksa beceri yok! Geri çekil!',
'탭 장비창을 열어봐. 아이템을 주워왔어!':'TAB ekipman menüsünü aç. Eşya topladık!',
'좋은 거 나왔다! TAB 열어서 확인해봐!':'İyi bir şey düştü! TAB ile kontrol et!',
'악의에 중독되면 악마가 돼서 부활력이 생긴대. 저 녀석처럼.':'Kötülük bağımlılığı diriliş gücüyle şeytana dönüştürürmüş. O gibi.',
'혹시 너도...?':'Belki sen de...?',
'데미지가 부족하면 무기류 강화를 해야해!!':'Hasar yetersizse silahları geliştir!!',
'G키 대장간. 강화 안 하면 여기서 계속 죽어.':'G dövücüye. Geliştirmeden ölmeye devam edersin.',
'시간이 없어. 움직여.':'Zaman yok. Hareket et.',
'멍하게 서있으면 안 돼!':'Öyle durma!',
'...뭘 기다리는 거야?':'...Neyi bekliyorsun?',
'가자가자! 몬스터가 기다려!':'Hadi! Canavarlar bekliyor!',
'여기 오래 있으면 위험해.':'Burada çok kalmak tehlikeli.',
'움직여야 해! 가만있으면 둘러싸여!':'Hareket et! Durursun kuşatılırsın!',
'쉬는 건 죽고 나서 해.':'Öldükten sonra dinlen.',
'살아있을 때 쉬면 안 돼!':'Hayattayken dinlenme!',
'적이 몰려오고 있어. 빨리 움직여.':'Düşmanlar yaklaşıyor. Hızlan.',
'냄새 맡고 올 거야. 빨리!':'Seni koklayacaklar. Acele et!',
'...아직 살아있는 거 맞지?':'...Hâlâ hayattasın, değil mi?',
'혹시 잠든 거야...?':'Uyudun mu...?',
'...나무가 썩어가고 있어. 여기는 지옥의 입구야.':'...Ağaçlar çürüyor. Burası cehennemin girişi.',
'냄새 지독해... 빨리 지나가자.':'Koku berbat... Hızlıca geçelim.',
'조심해. 벌레굴이다. 벽이랑 바닥에서 기어나와.':'Dikkat. Kurt yuvası. Duvarlardan ve yerden gelirler.',
'으으... 벌레 싫어! 밟아버려!':'Iğrenç... Böceklerden nefret ediyorum! Ez onları!',
'...공기가 얼어붙는다. 여기선 화염이 먹힌다.':'...Hava dondurucu. Ateş burada işe yarar.',
'추워... 빙결 조심해! 얼면 끝이야.':'Soğuk... Donmaya dikkat! Donarsan biter.',
'용암이다. 바닥을 밟으면 타 죽어.':'Lav. Yere basarsan yanarsın.',
'뜨거워! 여기 왜 이렇게 빨개!':'Çok sıcak! Neden her yer kırmızı!',
'...군단이다. 수가 많아. 광역기 없으면 밀려.':'...Lejyon. Çok fazla. Alan olmadan ezilirsin.',
'우글우글... 징그러워. 한꺼번에 쓸어!':'Her yerde sürünüyorlar... İğrenç. Hepsini bir anda sil!',
'사도의 영역이야. 여기 놈들은 머리가 좋아.':'Havari bölgesi. Bunlar akıllı.',
'패턴이 복잡해졌어... 집중해!':'Kalıplar karmaşıklaştı... Odaklan!',
'...끝이다. 지옥의 심장부. 살아 돌아가는 건 포기해라.':'...Bu kadar. Cehennemin kalbi. Dönüş umudunu bırak.',
'여기가 마지막이야... 각오해.':'Bu son... Hazırlan.',
'석궁 자동발사 (T)':'Arbalest otomatik (T)',
'버스트루프 당기기 (H)':'Patlama döngüsü çekme (H)',
'결정 자동합성':'Kristal otomatik sentez',
'결정 자동강화':'Kristal otomatik güçlendirme',
'✓ 설정 자동 저장':'✓ Ayarlar otomatik kaydedildi',
'세팅 프리셋 저장/불러오기':'Ön ayar kaydet/yükle',
'세팅1 저장':'Ön ayar 1 kaydet','세팅1':'Ön ayar 1',
'세팅2 저장':'Ön ayar 2 kaydet','세팅2':'Ön ayar 2',
'재진단':'Yeniden teşhis',
'게임 리셋 (처음부터)':'Oyunu sıfırla (baştan)',
'캐릭터 선택 (로비)':'Karakter seçimi (Lobi)',
'닫기 [ESC]':'Kapat [ESC]','닫기 [G]':'Kapat [G]','닫기 [V]':'Kapat [V]','닫기 [C]':'Kapat [C]',
'전체화면 (F11)':'Tam ekran (F11)',
'정말 모든 진행을 초기화하시겠습니까?':'Tüm ilerlemeyi sıfırlamak istiyor musun?',
'검출 중...':'Algılanıyor...',
'마우스 커서':'Fare imleci','그래픽 품질':'Grafik kalitesi','하드웨어 진단':'Donanım teşhisi',
'BGM 선택':'BGM seçimi',
'자동 (스테이지별)':'Otomatik (aşamaya göre)','전체 랜덤':'Her şey rastgele','로비':'Lobi',
'1장 랜덤':'Bölüm 1 rastgele','2장 랜덤':'Bölüm 2 rastgele','3장 랜덤':'Bölüm 3 rastgele',
'4장 랜덤':'Bölüm 4 rastgele','5장 랜덤':'Bölüm 5 rastgele','6장 랜덤':'Bölüm 6 rastgele','7장 랜덤':'Bölüm 7 rastgele',
'보스':'Patron','최종보스':'Son patron',
'대장간 랜덤':'Demirci rastgele','사망 랜덤':'Ölüm rastgele','승리 랜덤':'Zafer rastgele',
'지옥 추락 사망 징글':'Cehennem düşüş ölüm jingle','탈출 성공':'Kaçış başarılı',
'── 1장 - 썩은 숲 ──':'── CH1 - Rotten Forest ──','── 2장 - 벌레굴 ──':'── CH2 - Worm Nest ──',
'── 3장 - 얼음굴 ──':'── CH3 - Ice Cavern ──','── 4장 - 화염지대 ──':'── CH4 - Infernal Wastes ──',
'── 5장 - 지옥군단 ──':'── CH5 - Hell Legion ──','── 6장 - 사도마굴 ──':'── CH6 - Apostle Den ──',
'── 7장 - 지옥성 ──':'── CH7 - Hell Citadel ──','── 공통 ──':'── Common ──',
'⌨ 조작법':'⌨ Kontroller','클릭하면 닫힘':'Kapatmak için tıkla',
'전투력':'SG','가방':'Çanta','결정':'Kristal',
'↕ 정렬':'↕ Sırala','쓰레기 전체선택':'Tüm çöpü seç','쓰레기 전부 분해':'Tüm çöpü parçala',
'창고':'Depo','스탯 포인트':'Nitelik puanları','능력치 요약':'İstatistik özeti','올 리셋':'Tümünü sıfırla',
'대장간':'Demirci','스킬':'Beceriler','능력치':'Nitelikler',
'좌클스킬 (클릭 전환)':'SMB beceri (tıkla değiştir)','우클스킬 (클릭 전환)':'SMB beceri (tıkla değiştir)',
'이동스킬 (클릭 전환)':'Hareket becerisi (tıkla değiştir)','마법스킬 (클릭 전환)':'Sihir becerisi (tıkla değiştir)',
'영역스킬 (클릭 전환)':'Alan becerisi (tıkla değiştir)','피보호막 (클릭 전환)':'Kan kalkanı (tıkla değiştir)',
'CT스킬 (클릭 전환)':'CT becerisi (tıkla değiştir)','[C] 능력치':'[C] Nitelikler',
'무기 공격':'Silah saldırısı','칼등 처내기 (투사체 반사, 홀드 연사)':'Parı (mermileri yansıtır, tut=salvo)',
'연속 처내기':'Sürekli parı','영역 스킬 (폭풍소환 등)':'Alan becerisi (Kasırga vb)',
'작살 발사':'Zıpkın at','마법 (탭=투사체, 홀드=빔)':'Sihir (dokun=mermi, tut=ışın)',
'데빌포스 흡수':'Şeytan gücü emer','물약 / 스킬슬롯':'İksirler / Beceri yuvaları',
'스킬슬롯 5 / 필살기 / CT스킬':'Yuva 5 / Ult / CT becerisi','스킬 슬롯 배정':'Yuva atama',
// --- Phase 27 additions ---
'위로 이동':'Yukarı Hareket','아래로 이동':'Aşağı Hareket','왼쪽 이동':'Sola Hareket','오른쪽 이동':'Sağa Hareket',
'칼등 처내기 (탭=처내기, 홀드=연사)':'Parı (tap=parı, tut=salvo)',
'영역 스킬':'Alan becerisi','작살 이동':'Zıpkın Sıçraması',
'유령불꽃 켜기/끄기':'Hayalet Alev Aç/Kapat','기동칼날개 자동 켜기/끄기':'Bıçak-kanat Otomatik Aç/Kapat',
'해상도':'Çözünürlük',
'빛이 꺼졌다':'Işık Söner','누군가는 너를 기다리고 있다':'Biri seni bekliyor',
'다시 일어서라':'Yeniden Kalk','로비로 돌아가기':'Lobiye Dön',
'☠ 사망 리플레이':'☠ Ölüm tekrarı',
'지옥의 시련을 견뎌냈다':'Cehennemin sınavını atlattın','계속 전투':'Savaşa Devam',
'난이도를 선택하라':'Zorluk Seç',
'나중에 설정(ESC)에서 변경 가능':'Ayarlardan (ESC) sonra değiştirilebilir',
'일괄합성':'Toplu Birleştirme','일괄강화+합성':'Toplu Güçlendirme+Birleştirme',
'자원 부족!':'Kaynak Yetersiz!',' 뎀':' DMG',
'합체 폭발!':'Birleştirme Patlaması!','MP 부족! (50)':'MP Yetersiz! (50)',
'부활력 고갈!':'Diriliş Tükendi!','☠ 부활력 고갈!':'☠ Diriliş Tükendi!',
'독안개':'Zehir Sisi','뇌전창':'Yıldırım Mızrağı',
'🔥 업화선 시전...':'🔥 Cehennem Işını yayılıyor...',
'💥 기동파괴 그로기!':'💥 Zincir Ezme Sersemledi!',
'💥 칼등 그로기!':'💥 Parı Sersemledi!',
'⚡ 순간이동 준비!':'⚡ Işınlanma Hazır!',
'👿악의+1000':'👿Kötü Niyet+1000',
'💀 내려찍기!':'💀 Ezme!',
'✟ 신성력 억제! +':'✟ Kutsal Güç Baskılandı! +',
'✟ 신성력 억제!':'✟ Kutsal Güç Baskılandı!',
'✟ 신성력 억제! (':'✟ Kutsal Güç Baskılandı! (',
'💥 지진그로기!':'💥 Deprem Sersemledi!',
'💥 기폭그로기!':'💥 Patlama Sersemledi!',
'폭발! ×':'Patlama! ×',
'⚫ 기둥강타!':'⚫ Sütun Darbesi!',
'💥 대왕치기 그로기!':'💥 Dev Darbe Sersemledi!',
'💫 미니스턴!':'💫 Mini Sersemletme!',
'⚡ 뇌전창!':'⚡ Yıldırım Mızrağı!',
'…절반이다. 정신차려.':'…Yarı can. Dikkatli ol.',
'…죽기 직전이다. 한 발만 더.':'…Neredeyse öldü. Bir vuruş daha.',
'…다음 한 방이 마지막이야.':'…Sonraki vuruş son olacak.',
'기절! ':'Sersemletildi! ',
'마력이 빈다. 평타 섞어.':'MP azalıyor. Normal saldırı karıştır.',
'그랩이다. 거리를 둬.':'Kavrama saldırısı. Mesafe koy.',
'광역기다. 멀어져.':'Alan saldırısı. Uzaklaş.',
'…아파? 당연하지. 여긴 지옥이야.':'…Acı mı? Tabii. Burası cehennem.',
'F키도 스킬 슬롯이야!':'F tuşu da beceri yuvası!',
'L-CTRL로 유령걸음/얼음보주!':'L-CTRL ile Hayalet Yürüyüş/Buz Küresi!',
'V 눌러서 창고에 넣어둬!':'V bas ve depoya koy!',
'ESC로 설정! 난이도/자동물약!':'ESC ayarlar için! Zorluk/Otomatik iksir!',
'잡몹이다. 먼저 정리해.':'Normal düşmanlar. Önce temizle.',
'…얼어붙은 놈은 오래 안 간다.':'…Dondurulmuş uzun sürmez.',
'…냄새가 짙다. 큰 놈이 있어.':'…Koku yoğun. Büyük bir şey yakında.',
'쉴드는 마법으로, HP는 물리로.':'Kalkan sihir alır, HP fiziksel alır.',
'스페이스! 가시덫으로 적 묶어!':'Space! Dikenli Tuzak ile düşmanları bağla!',
'근접 너무 많아! 거리 벌려!':'Yakında çok fazla var! Dağıl!',
'회전참이나 광역기로 몰아!':'Döner Kesim veya AOE kullan!',
'F 눌러! 회복의 영역 깔아!':'F bas! Kutsal Alan yay!',
'F키 회복의 영역을 써봐.':'F-key Kutsal Alanı dene.',
'빠져! 물약 마시고 회복해.':'Geri çekil! İksir iç ve iyileş.',
'쉬프트! 사슬기동은 이동기야!':'Shift! Zincir hamlesi bir hareket!',
'스킬포인트 쌓였어! K 눌러!':'Beceri puanları birikti! K bas!',
'스킬 포인트 있어! K!':'Beceri puanın var! K!',
'C키. 패시브 포인트가 쌓여있다.':'C tuşu. Pasif puanlar birikmiş.',
'…쓸 거 아니면 분해해.':'…Kullanmayacağını parçala.',
'…강화 안 하면 그냥 고철이야.':'…Güçlendirmeden sadece hurda.',
'빨간 탄은 우클릭. 무지개는 Q.':'Kırmızı mermiler: sağ tık. Gökkuşağı: Q.',
'빨강=우클릭, 무지개=Q.':'Kırmızı=sağ tık, gökkuşağı=Q.',
'…멈추지 마. 여신은 기다리지 않는다.':'…Durma. Tanrıça beklemez.',
'패턴이 바뀐다. 거리를 둬.':'Desen değişiyor. Mesafe koy.',
'미쳐가고 있어. 광폭화다.':'Çıldırıyor. Öfke modu.',
'마지막이야! 끝장내!':'Son aşama! Bitir!',
'…끝났다. 다음으로.':'…Bitti. Devam.',
'다 잡았다! 포탈 어딨어?':'Hepsi öldürüldü! Portal nerede?',
'근육으로 만든 빌드군. 베고 부숴.':'Kas yapısı. Kes ve ez.',
'활을 쥐었군. 거리를 둬.':'Yayı var. Mesafe koy.',
'마법사군. MP 관리부터 배워라.':'Büyücü. Önce MP yönetimini öğren.',
'운에 기댄 빌드군. …드롭은 좋겠어.':'Şansa dayalı yapı. …En azından düşürme iyi olur.',
'…VIT가 너무 낮아. 한 방에 죽는다.':'…VIT çok düşük. Tek vuruşta ölürsün.',
'다 찍으면 다 약해진다. 하나만 골라.':'Her şeyi maxla ve her yerde zayıf olursun. Birini seç.',
'…3단. 적이 강해져. 정신 차려.':'…Aşama 3. Düşmanlar güçleniyor. Dikkatli ol.',
'5단이다. …너도 강해졌단 뜻이야.':'Aşama 5. …Senin de güçlendiğin anlamına gelir.',
'…7단. 아직 살아있단 게 신기하군.':'…Aşama 7. Hâlâ hayatta. Şaşırtıcı.',
'10단. …너는 이제 인간이 아니야.':'Aşama 10. …Artık insan değilsin.',
'…일반으로 내려왔군. 가끔은 쉬어가야지.':'…Normale döndün. Bazen dinlenmek lazım.',
'…이게 진짜 패링이야.':'…İşte gerçek parı bu.',
'…피가 묻기 시작했군.':'…Kan akmaya başladı.',
'100. 너는 인간이 아니야.':'100. İnsan değilsin.',
'…피 흘리며 베는군.':'…Kan içinde kesiyorsun.',
'빨간콩이 푸르게 변했다. 그게 너의 무기야.':'Kırmızı top maviye döndü. Bu senin silahın.',
'무지개를 받아쳤군. 그건 진짜 어렵다.':'Gökkuşağını parıladın. Bu gerçekten zor.',
'…너무 빨라. 닿기 직전에 눌러.':'…Çok hızlı. Temas etmeden hemen önce bas.',
'악의가 가득 찼다. 풀어내.':'Kötü Niyet doldu. Serbest bırak.',
'작살이 살을 뚫었어. 끌고 와.':'Zıpkın eti deldi. Çek.',
'…풀차지군. 멀리 던져버려.':'…Tam şarj. Uzağa fırlat.',
'…빈틈을 그대로 빠져나갔다.':'…Boşluktan kayarak çıktı.',
'…일반 잡몹이 아니야. 모디파이어 붙었군.':'…Normal düşman değil. Değiştirici var.',
'엘리트 하나 처리.':'Bir elit indi.',
'…큰 놈이다. 일반 잡몹 정리부터.':'…Büyük biri. Önce normalleri temizle.',
'미니보스 처리. 다음 길로.':'Mini patron indi. Sonraki yola.',
'한 번에 다섯. 깔끔해.':'Beş aynı anda. Temiz.',
'100강. 이제 뭔가 다르게 보이는군.':'+100. Artık her şey farklı görünüyor.',
'…운이 없는 날이야.':'…Şanssız bir gün.',
'…전설이다. 이런 건 처음 본다.':'…Efsanevi. Böyle bir şey ilk kez görüyorum.',
'…죽었다 살아났네. 여신은 너를 포기 안 했어.':'…Öldün ve döndün. Tanrıça senden vazgeçmedi.',
'…또야? 패턴 좀 외워!':'…Yine mi? Deseni öğren!',
'…한 번도 안 죽고. 그건 진짜 실력이야.':'…Hiç ölmeden. Bu gerçek beceri.',
'…ACT1을 끝냈다. 진짜 시작은 여기서부터야.':'…AKT1 bitti. Gerçek başlangıç burada.',
'모든 보스를 무너뜨렸다. 너는 지옥의 일부야.':'Tüm patronlar devrildi. Cehennemin bir parçasısın.',
'…30초. 너 진짜 미쳤구나.':'…30 saniye. Gerçekten delirdin.',
'…빠르군. 효율적이야.':'…Hızlı. Verimli.',
'신기록이다.':'Yeni rekor.',
'탭 장비창을 열어봐.':'TAB ile ekipman penceresini aç.',
'데미지 부족하면 무기 강화!':'Hasar yetersizse silahı güçlendir!',
// --- Loading screen ---
'불러오는 중...':'Yükleniyor...',
'로딩중...':'Yükleniyor...',
'맵과 몬스터 불러오는 중...':'Harita ve canavarlar yükleniyor...',
'기본 데이터 준비 중...':'Temel veriler hazırlanıyor...',
'저장 데이터 불러오는 중...':'Kayıt verileri yükleniyor...',
'몬스터 스킨 로딩...':'Canavar skinleri yükleniyor...',
'맵과 몬스터 생성 중...':'Harita ve canavarlar oluşturuluyor...',
'맵 에셋 로딩...':'Harita kaynakları yükleniyor...',
'맵 환경 준비 중...':'Harita ortamı hazırlanıyor...',
'주변 청크 준비 중...':'Yakın chunk\'lar hazırlanıyor...',
'맵 캐시 생성 중...':'Harita önbelleği oluşturuluyor...',
'미니맵 빌드 중...':'Minimapa oluşturuluyor...',
// Phase 28
' 으로 탈출!':' ile kaç!',
'100명?! 미쳤어!':'100 öldürme?! Deli!',
'10단 최고난이도! 너 진짜 광기야!':'Zorluk 10 maks! Tamamen çılgın!',
'1분 안에 클리어! 빠르네!':'1 dakikada temizle! Çok hızlı!',
'30초!! 스피드런 가능해!':'30 saniye!! Speedrun potansiyeli!',
'3단! 보상도 좋아지지만 죽기 쉬워!':'Zorluk 3! Daha iyi ödüller ama kolay ölürsün!',
'50명! 학살자야!':'50 öldürme! Katliamcı!',
'5단!! 진짜 게이머 인증!':'Zorluk 5!! Gerçek oyuncu onaylandı!',
'7단!! 다른 사람들 이 정도 못 와!':'Zorluk 7!! Diğerleri bu kadar gelemez!',
'ACT1 완주! 우리가 진짜 해냈어!':'ACT1 tamamlandı! Gerçekten başardık!',
'Ctrl 얼음보주로 탈출하라.':'Ctrl — Buz Küresiyle kaç.',
'Ctrl 유령걸음으로 탈출하라.':'Ctrl — Hayalet Yürüyüşüyle kaç.',
'C키! 패시브 강해져!':'C tuşu! Pasifler güçleniyor!',
'DEX 빌드! 거리에서 패고, 추적탄 좋아!':'DEX yapısı! Uzak saldırılar, takip okları!',
'E로 마력공격을 해봐!':'E ile büyü saldırısı dene!',
'G 눌러서 대장간 가봐!':'G\'ye bas — demirci!',
'G키 대장간. 강화 안 하면 계속 죽어.':'G — demirci. Yükseltme yoksa ölmeye devam eder.',
'HP 70%! 조심해!':'HP %70! Dikkat et!',
'INT 빌드! 빔이랑 폭발 마법! MP 잘 봐!':'INT yapısı! Işın ve patlama büyüsü! MP\'yi izle!',
'LCK 높아! 레어 드롭률 미친 거 알지?':'Yüksek LCK! Düşüş oranları çılgın!',
'L로 어디에 뭘 넣을지 골라!':'L\'ye bas — beceri slotu düzeni seç!',
'MP 부족! 평타로 패면서 회복해!':'MP düşük! Vuruşla geri kazan!',
'ST 없으면 스킬 못 써!':'ST yok, beceri yok!',
'STR 빌드! 회전참, 회오리, 광역기 추천!':'STR yapısı! Döner kılıç, kasırga, AoE!',
'VIT 좀 찍어! HP 너무 적어!':'VIT ekle! HP çok düşük!',
'Z 누르면 대박! 쿨타임 길어!':'Nihai için Z\'ye bas! Uzun bekleme!',
'…고기 냄새. 싫진 않네.':'…Kan kokusu. Fena değil.',
'…둘러싸이면 끝이야.':'…Sarılınca bitti.',
'…말은 못해.':'…Konuşamam.',
'…버리기 아까운 건 창고에.':'…Değerli şeyleri depoya koy.',
'…빈틈을 노려.':'…Açıkları izle.',
'…설정을 확인해.':'…Ayarları kontrol et.',
'…슬롯을 채워. 빈 손은 죽음이다.':'…Slotları doldur. Boş eller ölümdür.',
'…아직 살아있네. 좌클릭으로 저것들 쳐봐.':'…Hâlâ hayatta. Sol tık ile vur.',
'…운이 좋았을 뿐이야. 아마.':'…Sadece şanslıydın. Muhtemelen.',
'…치는 건 할 줄 아네. 피하는 건?':'…Vurabiliyorsun. Ya dodge?',
'…힘을 골라라. 전부 가질 순 없다.':'…Gücünü seç. Hepsine sahip olamazsın.',
'골고루 안 돼! 하나로 밀어!':'Dağıtma! Tek stata bas!',
'그로기 터지면 1.5배!':'Groggy = 1.5x hasar!',
'길이 열렸다.':'Yol açıldı.',
'나머진 전부 우클릭 패링 가능!':'Geri kalanlar — sağ tık parry!',
'나머진 전부 우클릭!':'Geri kalanlar — sağ tık!',
'다섯 번 연속! 내가 본 인간 중 최고!':'Beş arka arkaya! Gördüğüm en iyi!',
'다음엔 죽지 마!':'Bir daha ölme!',
'더블탭 전격이동으로 탈출하라.':'Çift dokunuşla dash ile kaç.',
'소환수 왔어! 먼저 처리해야 해!':'Çağrılanlar geldi! Önce onları temizle!',
'스킬 없으면 방향키 연타뿐이야.':'Beceri yok? Sadece ok tuşlarına bas.',
'신기록!! 스트리머한테 보내!':'Yeni rekor!! Yayıncıya gönder!',
'아이템 넘쳐! 우리가 주워줄게!':'Çanta dolu! Biz toplayacağız!',
'안 죽고 깼어! 진짜 천재 맞네!':'Ölmeden temizle! Gerçek dahi!',
'앞으로 가자~':'Hadi ileri gidelim~',
'우리가 해냈어! 다음 챕터 가자!':'Başardık! Sonraki bölüme!',
'일반 모드! 편하게 즐기자!':'Normal mod! Rahat oyna!',
'자원이 반이다. F키로 회복해.':'Kaynaklar yarı. F ile geri kazan.',
'잡힌다! 옆으로 빠져!':'Yakalanıyorsun! Yana çekil!',
'장비 분해해! 쓰레기도 악의!':'Ekipmanı parçala! Çöpten bile kötülük kazanılır!',
'전부 다 잡았어! 우리가 지옥의 왕이야!':'Hepsi temizlendi! Cehennemin krallarıyız!',
'좋은 거 나왔다! TAB!':'İyi eşya! TAB!',
'죽기 직전에 죽이다니! 멋져!':'Ölmeden hemen önce öldürmek! Harika!',
'체력 반 남았어! 물약 마실 타이밍!':'HP yarıda! İksir zamanı!',
'큰 거 온다! 도망쳐!':'Büyük saldırı! Kaç!',
'패링으로 돌려주고, Q 보호막도 써!':'Parry ile yansıt, Q kalkanını da kullan!',
'패턴이 빨라졌어!':'Örüntüler hızlandı!',
'한 대만 맞아도 죽어! 패링이든 회피든!!':'Bir vuruş = ölüm! Parry ya da dodge!!',
'한 방이면 죽어! 도망쳐!!':'Tek atış öldürür! Kaç!!',
'화염엔 빙결! 암전엔 암흑!':'Ateş → buz! Boşluk → gölge!',
'👻 유령!':'👻 Hayalet!',
'🦴 해골무덤!':'🦴 Kemik Mezarı!',
'── 2장 - 벌레굴 ──':'── CH2 - Worm Nest ──',
'── 4장 - 화염지대 ──':'── CH4 - Infernal Wastes ──',
'── 6장 - 사도마굴 ──':'── CH6 - Apostle Den ──',
'── 공통 ──':'── Common ──',
'☠ 부활력 고갈!':'☠ Diriliş Tükendi!',
'⏳⚡ 시간걸음!':'⏳⚡ Zaman Adımı!',
'블룸 효과':'Bloom Efekti',
'잔상 트레일':'Artık İz',
'슬래시 이펙트':'Kesme Efekti',
'후처리 효과':'Post-işlem',
'사망 이펙트':'Ölüm Efekti',
'동적 조명':'Dinamik Işıklandırma',
'횃불 조명 (어둠)':'Meşale Işığı (Karanlık)',
'앰비언트 파티클':'Ortam Partikülleri',
'안개 효과':'Sis Efekti',
'필름 그레인':'Film Tanesi',
'캐릭터 외곽선':'Karakter Konturu',
'리롤':'Yeniden At',
'물약':'İksir',
'으로 탈출!':'kaçmak için!',
'Shift 작살':'Shift Zıpkın',
'더블탭 전격이동':'Çift Dokunuş — Şimşek Koşusu',
'Ctrl 유령걸음':'Ctrl Hayalet Adımı',
'Ctrl 얼음보주':'Ctrl Buz Küre',
'🔴화염→빙결 2배 | 🔵빙결→화염 2배 | ⚪물리=중립 | 악마 처치 시 악의 영혼 드롭':'🔴Ateş→Buz 2× | 🔵Buz→Ateş 2× | ⚪Fiz=Nötr | Kin ruhları için iblis öldür',
};


const _TR_PFX={'녹슨':'Paslı','강철':'Çelik','흑요석':'Obsidyen','미스릴':'Mithril','심판의':'Yargının','천벌의':'İlahi Gazabın','파멸의':'Yıkımın','불꽃':'Alev','화염':'Cehennem Ateşi','염화':'Cehennem Ateşi','지옥불':'Cehennem Alevi','지옥화':'Cehennem Alevi','지옥':'Cehennem Alevi','멸화의':'İmha Eden','냉기':'Ayaz','빙결':'Donmuş','빙하':'Buzul','서리의':'Kırağının','서리':'Kırağının','영겁빙':'Ebedi Buz','그림자':'Gölge','암흑':'Karanlık','심연':'Uçurum','나락의':'Cehennemin','나락':'Cehennemin','무간의':'Boşluğun','전기':'Kıvılcım','낙뢰':'Yıldırım','암전':'Şimşek','뇌신의':'Fırtına Tanrısının','뇌신':'Fırtına Tanrısının','만뢰의':'Bin Yıldırımın','축복':'Mübarek','성광':'Kutsal Işık','신성':'Kutsal','천사의':'Melek','신벌의':'İlahi Yargının','낡은':'Eski','천':'Kumaş','가죽':'Deri','강철사':'Çelik Örgü','은':'Gümüş','은사':'Gümüş İplik','화염의':'Cehennem Ateşi','빙결의':'Donmuş','암흑의':'Karanlık','암전의':'Şimşek'};
const _TR_BASE={'대검':'Büyük Kılıç','석궁':'Tatar Yayı','연사석궁':'Tekrarlı Yay','마력석궁':'Büyülü Tatar Yayı','견갑':'Kalkan','대견갑':'Büyük Kalkan','전투화':'Savaş Botu','갑옷':'Zırh','갑주':'Ağır Zırh','왕관':'Taç','장갑':'Eldiven','건틀릿':'Zırhlı Eldiven','바지':'Pantolon','각반':'Dizlik','허리띠':'Kemer','벨트':'Kemer','부적':'Tılsım','목걸이':'Kolye','반지':'Yüzük','망토':'Pelerin','팔찌':'Bilezik','귀걸이':'Küpe'};
