const _FR={
// --- Stage / Boss ---
'썩은 숲':'Forêt Putride','숲의 감시자':'Gardien de la Forêt','독버섯 거인':'Géant Champignon Toxique','숲의 사냥꾼':'Chasseur de la Forêt','숲의 기생수':'Bête Parasite',
'1장 — 썩은 숲':'CH1 — Forêt Putride','2장 — 벌레굴':'CH2 — Nid de Vers','3장 — 얼음굴':'CH3 — Caverne de Glace',
'4장 — 고통의 화염지대':'CH4 — Terres Infernales','5장 — 지옥의 군단':'CH5 — Légion Infernale','6장 — 사도의 마굴':'CH6 — Antre de l\'Apôtre','7장 — 지옥성':'CH7 — Citadelle Infernale',
'탈출!':'Échappé !','처치':'Éliminations','경험치':'EXP','최대콤보':'Combo Max',
// --- Tutorial (Crow) ---
'일어나. 여신이 널 여기 보낸 건 죽으라고가 아니야.':"Debout. La déesse ne t\'a pas envoyé ici pour mourir.",
'좋아, 감각이 있군. 계속 쳐!':"Bien, t\'as de l\'instinct. Continue à frapper !",
'Shift를 눌러. 작살이다. 땅에 꽂아서 끌려가!':"Appuie sur Shift. C\'est le harpon. Plante-le et fais-toi tracter !",
'작살로 끌려가는 중엔 무적이다. 위험할 때 쓰면 좋아.':"T\'es invincible pendant la traction du harpon. Utilise-le quand ça chauffe.",
'...아파? 당연하지. 여긴 지옥이야.':'...Ça fait mal ? Évidemment. C\'est l\'enfer ici.',
'Q를 눌러! 악의로 보호막을 만들 수 있다.':'Appuie sur Q ! Crée un bouclier avec la Malice.',
'보호막 없이 버틸 생각은 버려.':'Oublie l\'idée de survivre sans bouclier.',
'우클릭이 패링이다. 적 공격이 닿기 직전에 눌러!':'Clic droit pour la parade. Appuie juste avant que l\'ennemi te frappe !',
'못 하겠으면 때려. 안 죽으면 그만이야.':"Tu sais pas parer ? Frappe. Tant que t\'es en vie, ça suffit.",
'됐어! 감 잡았구나.':"Voilà ! Tu commences à piger.",
'하나 죽었군.':'Un de moins.',
'유령쇠뇌야. 인사해.':"C\'est l\'arbalète fantôme. Dis bonjour.",
'빨간 탄을 무서워하지 마. 악의가 강하다.':"N\'aie pas peur des projectiles rouges. La Malice est puissante.",
'패링으로 돌려주고, Q 보호막도 써! 악의를 잘 굴려!':'Renvoie-les avec la parade, utilise aussi le bouclier Q ! Maîtrise ta Malice !',
'무지개빛은 패링 불가! 피해!':"Les tirs arc-en-ciel sont imparables ! Esquive !",
'피가 새고 있다. Shift. 빠져.':"Tu saignes. Shift. Dégage.",
'물약 있잖아! 숫자키!':'T\'as des potions ! Touches numériques !',
'우클릭. 적 손목이 꺾일 때 쳐.':'Clic droit. Frappe quand le poignet de l\'ennemi ploie.',
'빨간 탄은 악의 덩어리다. 쳐내서 이용해.':'Les projectiles rouges sont des masses de Malice. Dévie-les et exploite-les.',
'무지개빛만 피하면 돼! 나머지는 다 패링!':'Esquive juste l\'arc-en-ciel ! Pare tout le reste !',
'Q 보호막도 패링이 가능해!':'Le bouclier Q peut aussi parer !',
'위험해! 쉬프트 사슬기동으로 피해!!':'Danger ! Shift pour la ruée enchaînée et esquive !!',
'쉬프트! 사슬기동은 이동기야! 끌려가면서 무적이라고!':'Shift ! La ruée enchaînée est un déplacement ! Invincible pendant la traction !',
'스킬포인트가 쌓였어! K 눌러서 스킬 배우자!':'Points de compétence accumulés ! Appuie sur K pour apprendre des compétences !',
'속성을 읽어. 약점을 찌르면 두 배로 썩는다.':'Lis les éléments. Frappe les faiblesses pour le double de dégâts.',
'K를 눌러봐! 스킬을 배울 수 있어!':'Appuie sur K ! Tu peux apprendre des compétences !',
'C 눌러서 능력치 찍어! 패시브도 있어~':'Appuie sur C pour les stats ! Y\'a aussi des passifs~',
'G를 눌러. 대장간에서 장비를 강화할 수 있다.':'Appuie sur G. Améliore ton équipement à la forge.',
'F키도 스킬 슬롯이야! 스킬 많으면 L로 배정해봐~':'La touche F est aussi un slot de compétence ! Utilise L pour assigner~',
'Z. 필살기다. 아껴 써라.':"Z. C\'est ton ultime. Utilise-le judicieusement.",
'L-CTRL로 유령걸음이나 얼음보주 쓸 수 있어!':'L-CTRL pour la Marche Fantôme ou l\'Orbe de Glace !',
'L을 눌러. 스킬 슬롯을 정리해야 한다.':'Appuie sur L. Organise tes slots de compétence.',
'가방 터지겠다! V 눌러서 창고에 넣어둬!':"Le sac va exploser ! Appuie sur V pour entreposer !",
'ESC로 설정 열 수 있어! 난이도 바꾸기, 자동물약 조절~':'ESC pour les paramètres ! Difficulté, potions auto~',
// --- Tutorial (Cat) ---
'...아직 살아있네. 좌클릭으로 저것들 쳐봐.':'...Encore en vie. Essaie de frapper ça au clic gauche.',
'...치는 건 할 줄 아네. 피하는 건?':'...Tu sais frapper. Mais esquiver ?',
'흥, 작살 못 맞추면 헛수고야.':"Hmph, rate le harpon et c\'est du gâchis.",
'...운이 좋았을 뿐이야. 아마.':'...Juste de la chance. Probablement.',
'...고기 냄새. 싫진 않네.':'...Ça sent la viande. Pas désagréable.',
'...말은 못해.':"...Il ne parle pas.",
'예쁘다고 만지면 죽어.':"Tu trouves ça joli ? Touche et tu meurs.",
'작살 던져! 끌려가면 무적이야!':"Lance le harpon ! Invincible pendant la traction !",
'...마시든 말든. 네 목숨이니까.':"...Bois ou pas. C\'est ta vie.",
'그게 패링이야! 타이밍이 전부야~':'C\'est ça la parade ! Le timing est tout~',
'화염엔 빙결! 암전엔 암흑! 기억해!':'Le Feu bat la Glace ! La Foudre bat les Ténèbres ! Retiens ça !',
'...얼어붙은 놈은 오래 안 간다.':"...Les gelés ne durent pas longtemps.",
'얼었어! 빙결 중 1.5배야!':'Gelé ! 1,5x dégâts pendant le gel !',
'...힘을 골라라. 전부 가질 순 없다.':"...Choisis ton pouvoir. Tu ne peux pas tout avoir.",
'스탯을 올려. 살고 싶으면.':'Monte tes stats. Si tu veux vivre.',
'좋은 장비는 강화해야 진짜 힘을 발휘해!':'Un bon équipement doit être amélioré pour révéler sa vraie puissance !',
'...슬롯을 채워. 빈 손은 죽음이다.':'...Remplis tes slots. Les mains vides, c\'est la mort.',
'Z 누르면 대박! 쿨타임 길어서 타이밍 봐야 해!':'Appuie sur Z pour des dégâts massifs ! Long temps de recharge, choisis le bon moment !',
'Ctrl. 위기에 쓸 카드가 하나 늘었군.':'Ctrl. Une carte de plus pour les urgences.',
'스킬이 많아졌네~ L로 어디에 뭘 넣을지 골라!':'Tant de compétences~ Utilise L pour les assigner !',
'...버리기 아까운 건 창고에.':"...Entrepose ce qui est trop bon pour être jeté.",
'...살아남은 것만으로도 대단하군. 설정을 확인해.':'...Survivre seul est déjà impressionnant. Vérifie les paramètres.',
// --- System Messages ---
'MP 부족!':'MP insuffisant !','ST 부족!':'ST insuffisant !','악의 부족!':'Malice insuffisante !',
'충전 중...':'Charge en cours...','캔슬':'Annuler','아이템 선택 필요':'Sélectionne un objet',
'악의 소진...':'Malice épuisée...','비문 발견...':'Inscription découverte...',
'HP물약!':'Potion HP !','HP물약 +1':'Potion HP +1','HP물약 +2':'Potion HP +2',
'HP/MP/ST 회복!':'HP/MP/ST restaurés !','보물상자 개봉!':'Coffre ouvert !',
'익사!':'Noyade !','피웅덩이!':'Mare de Sang !','독혈!':'Sang Toxique !','잡힘!':'Agrippé !',
'콤보 종료':'Fin du Combo',
// --- Status Effects ---
'빙결!':'Gelé !','화상!':'Brûlure !','독!':'Poison !','감전!':'Électrocuté !',
'기절!':'Étourdi !','봉인됨!':'Scellé !','관통!':'Pénétration !',
// --- Skill Names ---
'기검참':'Lame de Ki','악의구':'Orbe de Malice','회전참':'Tourbillon','기폭팔':'Détonation',
'칼등 처내기':'Parade au Dos de Lame','만화방창':'Barrage d\'Aiguilles','멸살광선':'Rayon d\'Annihilation',
'원소추적탄':'Traqueur Élémentaire','악의 보호자':'Gardien de Malice','악의 사냥':'Chasse de Malice',
'폭풍소환':'Invocation de Vortex','해골무덤':'Tombe d\'Ossements','신성폭발':'Explosion Sacrée',
'블랙':'Étoile Noire','용암소환':'Invocation de Lave','처형':'Exécution','악마화 부활':'Résurrection Démoniaque',
'붉은꽃':'Fleur Écarlate','얼음보주':'Orbe de Glace','뇌전걸음':'Marche Fantôme',
'만화방창 II':'Barrage d\'Aiguilles II','마력연사':'Rafale Arcanique','마력광선':'Laser Arcanique','업화선':'Rayon Infernal',
'지옥진':'Formation Infernale','폭독칼날':'Lame Pestilente','악의폭풍':'Tempête de Malice',
'악의기둥':'Pilier des Ténèbres','회복의 영역':'Domaine Sacré','구속의 영역':'Domaine d\'Entrave',
'아이스스톰':'Tempête de Glace','대왕치기':'Frappe Colossale','대왕치기 2':'Frappe Colossale II',
'기동불꽃':'Flamme Enchaînée','기동파괴':'Fracas Enchaîné','기동칼날개':'Aileron Enchaîné',
'평화의보호':'Égide de Paix','참회':'Repentance','칼등날개':'Aile de Bouclier',
'폭산탄':'Tir Explosif','파쇄의 영역':'Domaine de Fracture','침식의 영역':'Domaine de Corrosion',
'관통의 영역':'Domaine de Pénétration','부활의 영역':'Domaine de Résurrection','가시덫':'Piège à Pointes',
'푸른비':'Pluie d\'Azur','버스트루프':'Boucle Explosive','유령 허수아비':'Leurre Fantôme','폭발 허수아비':'Leurre Explosif',
'공성쇠뇌':'Arbalète de Siège','사슬기동:충돌':'Ruée Enchaînée : Impact',
'사슬기동:화염':'Ruée Enchaînée : Flamme','전격이동':'Pas Éclair',
// --- Skill Activation ---
'기동칼날개!':'Aileron !','기동불꽃!':'Flamme Enchaînée !','기동파괴!':'Fracas Enchaîné !',
'사슬이동:강화!':'Ruée Enchaînée !','사슬기동:화염!':'Flamme Enchaînée !',
'작살!':'Harpon !','진입!':'Entrée !','레인라이트닝!':'Pluie de Foudre !',
'마력연사!':'Rafale Arcanique !','🔷 마력광선!':'🔷 Laser Arcanique !','광선 해제':'Laser désactivé','MP 부족 — 광선 해제':'MP épuisé — Laser désactivé','집중...':'Concentration...','시전...':'Incantation...',
'만화방창!':'Barrage d\'Aiguilles !','바늘출!':'Salve d\'Aiguilles !','칼날!':'Lame !',
'착지!':'Atterrissage !','체간삭감!':'Posture réduite !',
'기동전폭 준비!':'Explosion Enchaînée prête !','기동불꽃 준비!':'Flamme Enchaînée prête !',
'기동파괴 준비!':'Fracas Enchaîné prêt !',
'유령불꽃 ON':'Flamme Fantôme ON','유령불꽃 OFF':'Flamme Fantôme OFF',
'기동칼날개 AUTO ON':'Aileron AUTO ON','기동칼날개 AUTO OFF':'Aileron AUTO OFF',
'자동 버스트!':'Explosion Auto !','연사 해제':'Rafale désactivée',
'당기기 모드':'Mode Traction','밀어내기 모드':'Mode Répulsion',
// --- Skill Slot Tooltips ---
'날개치기':'Frappe d\'Aile','처내기':'Parade',
'Shift: 작살 발사 → 끌려감':'Shift : Harpon → traction',
'Shift: 화염길+화상':'Shift : Traînée de flamme+brûlure',
'CT: 전류변신+뇌전걸음 (쿨4초)':'CT : Forme foudre+Marche Fantôme (CD 4s)',
'CT: 방어구체+빙결 (재입력: 파쇄)':'CT : Sphère de glace+gel (re-presser : fracture)',
// --- HUD ---
'근접':'Mêlée','견갑':'Garde','작살':'Harpon','마법':'Magie','보막':'Bouclier','유령':'Fantôme',
'스킬':'Compétences','대장':'Forge','인벤':'Inv',
// --- Menu ---
'인벤토리':'Inventaire','복수의 대장간':'Forge de Vengeance','패시브 스킬':'Compétences Passives',
'전투 스킬':'Compétences de Combat','캐릭터 선택':'Sélection du Personnage',
// --- Elements ---
'물리':'Physique','화염':'Feu','빙결':'Glace','암흑':'Ténèbres','암전':'Foudre','신성':'Sacré','대지':'Terre',
// --- Passives ---
'힘':'Force','민첩':'Dextérité','지능':'Intelligence','행운':'Chance',
'맹공':'Assaut','철벽':'Rempart','돌파':'Percée','반격':'Contre-attaque',
'마력폭주':'Surtension Arcanique','정밀사격':'Tir Précis','수호':'Protection','수호신':'Esprit Gardien',
'회복력':'Régénération','급소':'Frappe Vitale','약탈':'Pillage','관통':'Pénétration',
'마력회복':'Récup. de Mana','쇠뇌력':'Maîtrise d\'Arbalète','광전사':'Berserker','추적자':'Traqueur',
'물리관통':'Pén. Physique','마법관통':'Pén. Magique',
// --- Weapons (Tier 0) ---
'녹슨 대검':'Espadon Rouillé','강철 대검':'Espadon d\'Acier','흑요석 대검':'Espadon d\'Obsidienne',
'낡은 석궁':'Arbalète Usée','강철 석궁':'Arbalète d\'Acier','흑요석 석궁':'Arbalète d\'Obsidienne',
'대검':'Espadon','석궁':'Arbalète','연사석궁':'Répéteur','마력석궁':'Arbalète Arcanique',
// --- Misc ---
'악의 추출':'Extraction de Malice','악의':'Malice','필살기':'Ultime','필살기 해제':'Ultime non assigné',
'이전':'Transfert','강화':'Amélioration','개봉!':'Ouvert !',
'여신의 가호':'Bénédiction de la Déesse',
'과부하!':'Surcharge !',
// --- Affix Names ---
'맹독의':'Venimeux','불꽃의':'Enflammé','냉기의':'Givrant','번개의':'Voltaïque','암흑의':'Maudit',
'관통의':'Perforant','광폭의':'Furieux','파쇄의':'Fracassant','연쇄의':'Enchaîné',
'학살의':'Massacrant','폭발의':'Explosif','집중의':'Concentré','쾌속의':'Rapide','패리의':'Déviant',
'추적자의':'du Traqueur','작살의':'du Harpon','궁극의':'Suprême','집중력의':'Attentif',
'강인의':'Endurant','수호의':'Protecteur','활력의':'Vigoureux','신속의':'Hâtif',
'화염수호':'Garde-Feu','빙결수호':'Garde-Glace','암전수호':'Garde-Foudre','암흑수호':'Garde-Ténèbres','독수호':'Garde-Poison','전원소수호':'Garde-Totale',
'강철의':'Cuirassé','반사의':'Réfléchissant','가시의':'Épineux','흡수의':'Absorbant','인내의':'Endurant',
'위기의':'Désespéré','피격반격의':'Riposteur',
'패링폭발의':'Explosion de Parade','스태거폭발의':'Explosion de Chancellement','원소전환의':'Convertisseur','정화의':'Purificateur',
'불굴의':'Inébranlable','부활의':'Résurrecteur',
'약탈의':'Pilleur','경험의':'Aguerri','골드의':'Doré','포션강화의':'Potionneur','사슬의':'Enchaîné',
'진혼의':'Sanctificateur','윤회의':'Cyclique',
'생명력의':'Vigoureux','재생의':'Régénérant','치유의':'Guérisseur',
'마력의':'Arcanique','절약의':'Économe','영혼의':'Spirituel',
'예리한':'Acéré','맹렬한':'Brutal','파멸의':'Dévastateur',
// --- Settings UI ---
'게임 설정':'Paramètres du Jeu','화면 흔들림':'Tremblement d\'Écran','파티클 양':'Quantité de Particules',
'효과음 볼륨':'Volume des Effets','음악 볼륨':'Volume de la Musique','난이도':'Difficulté',
'자동 물약':'Potion Auto','최소 줍기 등급':'Grade Minimum de Ramassage','최소 줍기 티어':'Tier Minimum de Ramassage',
'FPS 제한':'Limite FPS','해상도 스케일':'Échelle de Résolution','펫 자동수거':'Collecte Auto des Familiers',
'화면 설정':'Paramètres d\'Affichage','화면 모드':'Mode d\'Affichage','보스 AI 디버그':'Debug IA Boss',
'유령불꽃 크기':'Taille Flamme Fantôme','화면 명암':'Luminosité','유령 글로우':'Lueur Fantôme',
'기동:칼날개 AUTO':'Aileron AUTO',
'일반':'Normal','어려움':'Difficile','지옥':'Enfer','이상':'ou plus','사용 안 함':'Désactivé',
'창 모드':'Fenêtré','보더리스':'Sans Bordure','전체화면':'Plein Écran',
'설정':'Paramètres','조작 키 설정 (클릭하여 변경)':'Configuration des Touches (Cliquer pour Modifier)',
// --- Key Guide ---
'좌클릭 무기 공격':'LMB Attaque Arme','우클릭 탭 칼등 처내기':'RMB Tap Parade au Dos de Lame',
'우클릭 홀드 연속 처내기':'RMB Maintien Parade Continue','SHIFT 작살 발사':'SHIFT Lancer de Harpon',
'이동':'Déplacement','아이템 줍기':'Ramasser un Objet','능력치 (스탯/패시브)':'Attributs (Stats/Passifs)',
// --- Forge ---
'복수의 대장간':'Forge de Vengeance','강화':'Amélioration','분해':'Démantèlement','제작':'Fabrication',
// --- Death Screen ---
'사망':'Mort','부활':'Résurrection','로비로':'Vers le Hall',
// --- Inventory/Storage ---
'가방에 공간이 없습니다!':'Plus de place dans le sac !','가방이 가득 찼습니다!':'Le sac est plein !',
'창고가 가득 찼습니다!':'L\'entrepôt est plein !','퀵슬롯이 가득 찼습니다!':'Slot rapide plein !',
'결정 주머니가 가득 찼습니다!':'La bourse de cristaux est pleine !','결정 주머니 가득!':'Bourse de cristaux pleine !',
'악의가 부족합니다!':'Malice insuffisante !','가방이 비어있습니다':'Le sac est vide',
'창고가 비어있습니다':'L\'entrepôt est vide','비어있음':'Vide','어픽스 없음':'Pas d\'affixe',
'장착!':'Équipé !','해제':'Retiré','보관':'Déposer','꺼내기':'Retirer',
'현재 장착':'Actuellement équipé','없음 — 제작하세요!':'Aucun — Fabrique-en un !',
'리셋할 포인트가 없습니다':'Pas de points à réinitialiser',
'키 설정 초기화 완료':'Configuration des touches réinitialisée',
// --- Forge/Craft ---
'제작 확률':'Chance de fabrication','제작 비용':'Coût de fabrication','보유 악의':'Malice possédée',
// --- Canvas UI ---
'보스방':'Salle du Boss','안식처':'Sanctuaire','회복':'Récupération','점화':'Ignition',
'비석':'Stèle','읽기':'Lire','파괴':'Détruire','제단':'Autel','기원':'Prier',
'잔해':'Débris','열기':'Ouvrir','문지기':'Gardien',
'부활 판정 중...':'Jugement de résurrection...','기폭 준비!':'Détonation prête !',
'탈출':'Évasion','연타':'Martèlement',
'추적암전':'Foudre Traqueuse','만화광선':'Rayon de Luminescence','최종 마법':'Magie Ultime',
'감시중':'En surveillance','대기':'En attente','작동중':'Actif','설치 가능':'Installable',
'균열 임박!':'Brèche imminente !','흡수 중...':'Absorption...',
'흡수 완료 — 재입력으로 회수':'Terminé — re-presser pour récupérer',
'화상':'Brûlure','당기기':'Traction','밀어내기':'Répulsion',
'단계':'niv','단':'niv',
// --- Skill Panel ---
'습득!':'Appris !','리셋!':'Réinitialisé !','세팅!':'Configuré !','회수':'Rappel',
'합체 해제':'Défusion','리셋':'Réinitialiser','환불':'Remboursement',
'파트너 클릭!':'Clique sur le partenaire !','SP부족!':'SP requis !',
'같은 보석 스킬 습득 시 합체 가능':'Fusion possible en apprenant la même compétence de gemme',
'펼쳐서 초기화':'Développer pour réinitialiser','슬롯:':'Slot :',
// --- Stats ---
'남은 SP':'SP restants','처치':'Éliminations','경험치':'EXP','최대콤보':'Combo Max',
'맞아서 사망':'Mort par impact','레벨':'Niveau','최대HP':'HP Max',
// --- Enemy Names ---
'방랑 기사':'Chevalier Errant','보물 악마':'Démon au Trésor','거울의 사도':'Apôtre du Miroir',
'상인 악마':'Démon Marchand','사슬의 죄수':'Prisonnier Enchaîné','시간의 사도':'Apôtre du Temps',
'탐욕의 사도':'Apôtre de l\'Avarice','저주받은 쌍둥이':'Jumeaux Maudits','차원 균열체':'Faille Dimensionnelle',
'죽음 그 자체':'La Mort en Personne',
// --- Crystals ---
'HP결정':'Cristal HP','ST결정':'Cristal ST','MP결정':'Cristal MP',
'ATK결정':'Cristal ATK','DEF결정':'Cristal DEF','속도결정':'Cristal de Vitesse',
'크리결정':'Cristal de Crit','치명결정':'Cristal de DégCrit','화염결정':'Cristal de Feu',
'냉기결정':'Cristal de Glace','암흑결정':'Cristal de Ténèbres','번개결정':'Cristal de Foudre',
'신성결정':'Cristal Sacré','생명결정':'Cristal de Vie','기력결정':'Cristal d\'Endurance',
'마력결정':'Cristal de Mana','행운결정':'Cristal de Chance',
'조각':'Fragment','파편':'Éclat','순수결정':'Cristal Pur','완전결정':'Cristal Parfait',
'결정 주머니':'Bourse de Cristaux','결정이 없습니다':'Pas de cristaux','가루':'Poudre',
'전체':'Tous','스탯':'Stats','원소':'Élém','유틸':'Util',
'현재':'Actuel','최대 강화 달성 (+20)':'Amélioration max atteinte (+20)','강화 시':'Après amélioration',
'강화':'Amélioration','합성':'Synthèse','제작':'Fabrication',
'같은 종류·같은 성급 결정 3개 → 1성급 상승 (강화 리셋)':'3 cristaux de même type et grade → monte de 1 grade (amélioration réinitialisée)',
'합성 가능한 결정이 없습니다 (같은 종류·성급 3개 필요)':'Pas de cristaux synthétisables (3 de même type et grade requis)',
'결정 분해 → 결정 가루':'Décomposer Cristal → Poudre de Cristal',
'분해할 결정이 없습니다':'Pas de cristaux à décomposer',
'결정 제작 (가루 → 결정)':'Fabrication de Cristal (Poudre → Cristal)',
'탈착':'Détacher','빈 슬롯':'Slot vide',
'결정 선택 후 클릭':'Sélectionne un cristal puis clique','클릭하여 선택결정 장착':'Clique pour équiper le cristal sélectionné',
'획득!':'Obtenu !','제작!':'Fabriqué !','합성!':'Synthétisé !','최상위 일괄합성':'Synthèse en masse max','일괄합성 완료':'Synthèse en masse terminée',
// --- Stage Names ---
'벌레굴':'Nid de Vers','얼음굴':'Caverne de Glace','고통의 화염지대':'Terres Infernales',
'지옥의 군단':'Légion Infernale','사도의 마굴':'Antre de l\'Apôtre','지옥성':'Citadelle Infernale',
// --- Misc ---
'엑소듀서 전사':'Guerrier Exoduseur','포이즈':'Posture',
'신성폭발':'Explosion Sacrée','뇌전걸음':'Marche Fantôme',
'지옥창고':'Entrepôt Infernal','선택분해':'Démantèlement Sélectif','쓰레기':'Rebut',
'복구 불가!':'Irrécupérable !','중요잠금':'Verrouillage Important',
// --- Phase 9 additions ---
'획득!':'Obtenu !','자동 장착!':'Auto-équipé !','분해! 가루 +':'Démantelé ! Poudre +',
'추적암전':'Foudre Traqueuse','암전':'Foudre',
'평화보호':'Égide','지진폭풍':'Tempête Sismique','회전기폭':'Détonation Tourbillon',
'공격':'Attaque','보호막':'Bouclier','필살기':'Ultime',
'합체 스킬로 통합됨':'Fusionné en compétence combinée','얼음보주 안에선 사용 불가!':'Inutilisable dans l\'Orbe de Glace !',
'Shift+키로 폭파':'Shift+touche pour détonation','취소':'Annuler','충전 중...':'Charge en cours...',
'쿨다운 중...':'Recharge...','시전 중...':'Incantation...','악의 부족!':'Malice insuffisante !',
'악의 부족! (12)':'Malice insuffisante ! (12)','악의 부족! (15)':'Malice insuffisante ! (15)',
'악의 부족! (20)':'Malice insuffisante ! (20)','악의 부족! (10)':'Malice insuffisante ! (10)',
'ST 부족!':'ST insuffisant !','HP 부족!':'HP insuffisant !',
'필살기 슬롯 클릭하여 배정!':'Clique sur le slot ultime pour assigner !',
'필살기 스킬을 습득하세요':'Apprends une compétence ultime',
'우클릭(칼등치기)에 합체됨':'Fusionné dans RMB (parade au dos de lame)',
'T(석궁자동)에 세팅하세요':'Assigne à T (arbalète auto)',
'공성쇠뇌 철거 → 이동식':'Arbalète de siège démontée → portable',
'ST 부족! (100)':'ST insuffisant ! (100)',
'HP 99% 이상!':'HP 99%+ !','그로기 보스 없음!':'Pas de boss étourdi !',
'이미 폭풍 지역!':'Déjà en zone de tempête !','이미 빙풍 지역!':'Déjà en zone de tempête de glace !',
'💎 푸른비 해금!':'💎 Pluie d\'Azur débloquée !','💫 버스트루프 해금!':'💫 Boucle Explosive débloquée !',
'👻 유령 허수아비 해금!':'👻 Leurre Fantôme débloqué !',
'쿨 ':'CD ','과부하 ':'Surcharge ',
'🕊️💎 블루콩!':'🕊️💎 Haricot Bleu !','🛡️💎 빨콩→블루콩!':'🛡️💎 Rouge→Bleu !',
'🛡️💎 무지개→블루콩!':'🛡️💎 Arc-en-ciel→Bleu !',
'레어':'Rare','슬롯':'Slot',
'성공률':'Taux de Réussite','AI 자동 강화':'Amélioration Auto IA','최대 강화 달성!':'Amélioration max atteinte !',
'최대 강화':'Amélioration max','회복량':'Récupération','현재 장착':'Actuellement équipé',
'없음 — 제작하세요!':'Aucun — Fabrique-en un !','제작 확률':'Chance de fabrication',
'분해할 아이템이 없습니다.':'Aucun objet à démanteler.','🔨 제작':'🔨 Fabrication',
'체간':'Posture','아이템에 마우스를 올리거나 좌클릭으로 선택하세요':'Survole un objet ou clique gauche pour sélectionner',
// --- Phase 10: death/levelup/intro screen ---
'중독':'Poison','지뢰':'Mine','함정':'Piège','산호가시':'Pointe de Corail',
'투사체':'Projectile','도트':'DpS','레어몹':'Mob Rare',
'처치':'éliminations','경험치':'EXP','최대콤보':'Combo Max',
'구역':'Zone','가시!':'Pointe !',
// --- Hell circle / palette names ---
'림보':'Limbes','색욕':'Luxure','탐식':'Gloutonnerie','탐욕':'Avarice','분노':'Colère','이단':'Hérésie','폭력':'Violence',
'분노!':'Rage !','탐욕!':'Avarice !','💀 분노 폭발!':'💀 Explosion de Rage !','심연의 분노!':'Rage Abyssale !','쌍둥이의 분노!':'Rage des Jumeaux !',
// --- HUD / misc ---
'소환굴':'Fosse d\'Invocation',
'레어':'Rare','처치!':'Éliminé !','왕관 착용':'Couronne activée','왕관 해제':'Couronne retirée',
'맨손':'Mains Nues','없음':'Aucun','갑옷':'Armure','부츠':'Bottes',
// --- Elite / Mod / Aura ---
'매직':'Magique','챔피언':'Champion',
'빙결':'Gel','초속':'Célérité','강타':'Frappe','재생':'Régénération','맹독':'Venin','소환':'Invocation',
'기생':'Parasite','분열':'Scission','용암자취':'Traînée de Lave','사망폭발':'Explosion Mortelle',
'화염사슬':'Chaîne de Feu','광전':'Frénésie','텔레포트':'Téléportation','보호막':'Barrière',
'소용돌이':'Vortex','환영':'Spectre','전격반사':'Réflexion Électrique','감전':'Électrocution',
'낙뢰':'Tonnerre','연쇄전격':'Foudre en Chaîne','동료불사':'Allié Immortel',
'영혼포식':'Dévoration d\'Âme','시간왜곡':'Distorsion Temporelle','혼돈변이':'Mutation Chaotique',
'복수자':'Vengeur','마법보초':'Sentinelle Magique','환영술사':'Illusionniste',
'함성':'Cri de Guerre','치유':'Guérison','신속':'Vélocité','수호':'Gardien',
// --- Character ---
'다크 판타지 전사. 거대검+검은 갑옷':'Guerrier de dark fantasy. Espadon + Armure Noire',
// --- Phase 11: missing addTxt/showPH/notify translations ---
'⚡ 사슬이동:강화!':'⚡ Chaîne : Renforcée !',
'⚡ 사슬기동:화염!':'⚡ Ruée Enchaînée : Flamme !',
'달성!':'Accompli !',
'ST':'ST','부족!':'Insuffisant !',
'타':'Coup',
'🌀 당기기 모드':'🌀 Mode Traction',
'💥 밀어내기 모드':'💥 Mode Répulsion',
'🕊️빨콩 흡수':'🕊️Absorption haricot rouge',
'🕊️흡수':'🕊️Absorption',
'💎유도 폭발!':'💎Explosion Guidée !',
'💥반사 폭발!':'💥Explosion Réfléchie !',
'⚡⚡ 참회 귀환!':'⚡⚡ Retour de Repentance !',
'⚡ 참회!':'⚡ Repentance !',
'파도!':'Vague !',
'암전!':'Foudre !',
'암흑!':'Ténèbres !',
'암흑창!':'Lance des Ténèbres !',
'빛창!':'Lance de Lumière !',
'체 소환!':'invoqué(s) !',
'개 설치!':'placé(s) !',
'💥 보스 그로기!':'💥 Boss Étourdi !',
'💥 그로기!':'💥 Étourdi !',
'보상':'Bonus',
'⚡ 암전나선!':'⚡ Hélice de Foudre !',
'🌋 지진폭풍!':'🌋 Tempête Sismique !',
'SP슬롯':'Slot SP',
'F슬롯':'Slot F',
'⚔🩸 독혈해방!':'⚔🩸 Libération Pestilente !',
'⚔ 칼날 해방!':'⚔ Libération de Lame !',
'🔨🌋 지옥강타!':'🔨🌋 Frappe Infernale !',
'🔨 대왕치기!':'🔨 Frappe Colossale !',
'✟ 신성한 결계!':'✟ Barrière Sacrée !',
'🛡 회복의 영역!':'🛡 Domaine Sacré !',
'기폭팔!':'Détonation !','강제기폭!':'Détonation Forcée !','자동기폭!':'Auto-Détonation !',
'회전기폭!':'Détonation Tourbillon !','해제기폭!':'Détonation de Relâche !','지진기폭!':'Détonation Sismique !',
'혼돈의 왕관':'Couronne du Chaos',
'전지전능의 왕관':'Couronne d\'Omnipotence',
'악마의 팔찌':'Bracelet Démoniaque',
'생명의 팔찌':'Bracelet de Vie',
// --- wave direction names (full addTxt strings) ---
'🌊 위→아래 파도!':'🌊 Vague Haut→Bas !','🌊 오른→왼 파도!':'🌊 Vague Droite→Gauche !',
'🌊 아래→위 파도!':'🌊 Vague Bas→Haut !','🌊 왼→오른 파도!':'🌊 Vague Gauche→Droite !',
// --- Phase 12: remaining addTxt/UI translations ---
'⚡ 사슬이동:강화!':'⚡ Chaîne : Renforcée !','⚡ 사슬기동:화염!':'⚡ Ruée Enchaînée : Flamme !',
'🌀 당기기 모드':'🌀 Mode Traction','💥 밀어내기 모드':'💥 Mode Répulsion',
'💎유도 폭발!':'💎Explosion Guidée !','💥반사 폭발!':'💥Explosion Réfléchie !',
'⚡⚡ 참회 귀환!':'⚡⚡ Retour de Repentance !','⚡ 참회!':'⚡ Repentance !',
'암전!':'Foudre !','암흑!':'Ténèbres !','암흑창!':'Lance des Ténèbres !','빛창!':'Lance de Lumière !',
'💥 보스 그로기!':'💥 Boss Étourdi !','💥 그로기!':'💥 Étourdi !',
'⚡ 암전나선!':'⚡ Hélice de Foudre !','🌋 지진폭풍!':'🌋 Tempête Sismique !',
'⚔🩸 독혈해방!':'⚔🩸 Libération Pestilente !','⚔ 칼날 해방!':'⚔ Libération de Lame !',
'🔨🌋 지옥강타!':'🔨🌋 Frappe Infernale !','🔨 대왕치기!':'🔨 Frappe Colossale !',
'✟ 신성한 결계!':'✟ Barrière Sacrée !','🛡 회복의 영역!':'🛡 Domaine Sacré !',
'파도!':'Vague !',
// --- rare mob / special ---
'무적!':'Invincible !','🪞 반격!':'🪞 Contre-attaque !','💢 반격!':'💢 Contre-attaque !',
'흡수!':'Absorption !','반격 발사!':'Tir de Riposte !',
'저주! 드랍률 -50%':'Malédiction ! Taux de butin -50%','도망!':'Fuite !',
'위상!':'Phase !','방어!':'Défense !',
'회수 HP+':'Rappel HP+','이동식 복귀':'Retour Mobile','캔슬':'Annuler',
'약점!':'Faiblesse !','저항!':'Résistance !','관통!':'Pénétration !',
'유령불꽃 OFF':'Flamme Fantôme OFF','유령불꽃 ON':'Flamme Fantôme ON',
'기동칼날개 AUTO ON':'Aileron AUTO ON','기동칼날개 AUTO OFF':'Aileron AUTO OFF',
'콤보 종료: ':'Fin du Combo : ','익사!':'Noyade !',
'피웅덩이!':'Mare de Sang !','독혈!':'Sang Toxique !','비문 발견...':'Inscription découverte...',
'보물상자 개봉!':'Coffre ouvert !','악의 +':'Malice +','잡힘!':'Agrippé !',
'저주 ':'Malédiction ','충전 중...':'Charge en cours...','불발...':'Raté...',
'작살 약점!':'Faiblesse au Harpon !',
'전염 x':'Peste x','흡수 완료!':'Absorption terminée !',
'부활 성공!':'Résurrection réussie !','부활 실패...':'Résurrection échouée...',
'산호가시':'Pointe de Corail','가시!':'Pointe !','차원 이동!':'Déplacement Dimensionnel !','독!':'Poison !',
'탈출!':'Échappé !','기절 해제':'Étourdissement levé',
'아이템 선택 필요':'Sélectionne un objet','악의 부족':'Malice insuffisante','악의 소진...':'Malice épuisée...',
'스킬 미습득':'Aucune compétence apprise','펼치기':'Développer','접기':'Réduire',
'조건 미달!':' non remplies !','해제!':' Défusionné !',
'슬롯':'Slot','자동 ON':' Auto ON','자동 OFF':' Auto OFF','스킬 해제':' compétence retirée',
'필살기':'Ultime','필살기 해제':'Ultime non assigné',
'연사 해제':'Rafale désactivée',
'닫기':'Fermer','장착 중':'Équipé','보관 아이템':'Objet Entreposé',
// --- Phase 13: massive batch — skill activation ---
'클릭으로 선택 · ESC로 닫기':'Clique pour sélectionner · ESC pour fermer',
'선택됨':'Sélectionné',
'MP 부족!':'MP insuffisant !','악의 부족! (30)':'Malice insuffisante ! (30)',
'MP 부족! (40)':'MP insuffisant ! (40)','MP 부족! (100)':'MP insuffisant ! (100)','MP 부족! (10)':'MP insuffisant ! (10)',
'MP 부족! (':'MP insuffisant ! (',
'✟ 시전...':'✟ Incantation...','🌋 시전...':'🌋 Incantation...','⛧ 시전...':'⛧ Incantation...',
'❄ 진입!':'❄ Entrée !',
'🔱 작살!':'🔱 Harpon !',
'레벨 부족! (요구: Lv.':'Niveau trop bas ! (Requis : Nv.',
' 장착!':' Équipé !',
'가방에 공간이 없습니다!':'Plus de place dans le sac !',
' 해제':' Retiré',
'👿 악의 추출: +':'👿 Extraction de Malice : +',
'F 슬롯 해제':'Slot F retiré',
'💫 집중...':'💫 Concentration...',
'⚡ 마력연사!':'⚡ Rafale Arcanique !',
'❄빙결!':'❄Gelé !','🟢독!':'🟢Poison !','⚡감전!':'⚡Électrocuté !','🔥화상!':'🔥Brûlure !',
'✦ 여신의 가호 — SP+5 AP+3':'✦ Bénédiction de la Déesse — SP+5 AP+3',
'⚔ 기동칼날개!':'⚔ Aileron !',
'🔥 화염관통!':'🔥 Pénétration de Feu !',
'🔱 관통!':'🔱 Pénétration !',
'⚔ 칼날!':'⚔ Lame !',
'💥 착지!':'💥 Atterrissage !',
'💫 기절!':'💫 Étourdi !',
'⚡ 체간삭감!':'⚡ Posture réduite !',
'⚡ 기동파괴! ':'⚡ Fracas Enchaîné ! T',
'🔥 기동불꽃!':'🔥 Flamme Enchaînée !',
'🔥 기동불꽃! ':'🔥 Flamme Enchaînée ! T',
'단계 ×':' x',
'⚡ 기동전폭! x':'⚡ Explosion Enchaînée ! x',
'🔥🔥 3중폭!':'🔥🔥 Explosion x3 !','🔥🔥🔥 6중폭!':'🔥🔥🔥 Explosion x6 !','🔥🔥🔥🔥 9중폭!':'🔥🔥🔥🔥 Explosion x9 !','💥 불꽃폭발! ':'💥 Explosion de Flamme ! ',
'🔥 기동불꽃 준비!':'🔥 Flamme Enchaînée prête !',
'🔨 기동파괴 준비!':'🔨 Fracas Enchaîné prêt !',
'⚡ 기동전폭 준비!':'⚡ Explosion Enchaînée prête !',
'콤보 종료: ':'Fin du Combo : ',
'중독':'Poison',
'⚡ 과부하! 5초':'⚡ Surcharge ! 5s',
'💫 자동 버스트!':'💫 Explosion Auto !',
'🔨 칼등날개!':'🔨 Aile de Bouclier !',
'💥폭발!':'💥Explosion !',
'🛡️💎 유도반사!':'🛡️💎 Réflexion Guidée !',
'⚡💎 블루콩!':'⚡💎 Haricot Bleu !',
'💎 블루콩!':'💎 Haricot Bleu !',
'⚡반사!':'⚡Réflexion !',
'💎 푸른비 OFF':'💎 Pluie d\'Azur OFF',
'💎 푸른비 ON!':'💎 Pluie d\'Azur ON !',
'🔥 지옥진!':'🔥 Formation Infernale !',
'🔥 업화선!':'🔥 Rayon Infernal !',
'✦ 평화 충격파! ':'✦ Onde de Choc de Paix ! ',
'⚡ 전류 방출!':'⚡ Décharge Électrique !',
'⚡⚡ 레인라이트닝!':'⚡⚡ Pluie de Foudre !',
'💫 광역!':'💫 Zone !',
'🔥 불장판!':'🔥 Zone de Feu !',
'💫 피니셔!':'💫 Coup Final !',
'☠ 지옥에서 귀환!':'☠ Retour de l\'Enfer !',
'☠ 완전 사망!':'☠ Mort Définitive !',
'⚔ 처형! ':'⚔ Exécution ! ',
'💥 지뢰!':'💥 Mine !',
'⚠ 함정!':'⚠ Piège !',
'❌ 우클릭으로! -':'❌ Utilise le clic droit ! -',
'❌ Q키로! -':'❌ Utilise Q ! -',
'💥무지개 폭발! ':'💥Explosion Arc-en-ciel ! ',
'🛡️💎 블루콩!':'🛡️💎 Haricot Bleu !',
'⬜화이트볼!':'⬜Boule Blanche !',
'✨💎 블루콩!':'✨💎 Haricot Bleu !',
'💜다크볼!':'💜Boule Ténébreuse !',
'❄빙판!':'❄Sol Gelé !',
'🌨빙결!':'🌨Gelé !',
'🕸둔화!':'🕸Ralenti !',
'⚠트랩!':'⚠Piège !',
'💀 역병 처형!':'💀 Exécution Pestilente !',
'💥 역병 Finale!':'💥 Finale Pestilente !',
'⚔ 균열 악마!':'⚔ Démon de Faille !',
'자동회수 HP+':'Auto-Rappel HP+',
'MP 부족 — 연사 해제':'MP bas — Rafale désactivée',
'MP 부족 — 푸른비 OFF':'MP bas — Pluie d\'Azur OFF',
'🛡️반사!':'🛡️Réflexion !',
'⚡🦴 참회 귀환!':'⚡🦴 Retour de Repentance !',
'🦴⚡해골번개!':'🦴⚡Foudre Osseuse !',
'⚡악의폭풍!':'⚡Tempête de Malice !',
'❄아이스스톰!':'❄Tempête de Glace !',
'⚡ 암전폭발!':'⚡ Explosion de Foudre !',
'⚡ 레인라이트닝! x':'⚡ Pluie de Foudre ! x',
'❄ 탈출!':'❄ Évasion !',
'⚡쉴드!':'⚡Bouclier !',
'❄🌪️ 얼음보주!':'❄🌪️ Orbe de Glace !',
'🌪️ 전개!':'🌪️ Déploiement !',
'❄ 빙결흡인!':'❄ Vortex de Gel !',
'❄☄ 빙결폭발!':'❄☄ Explosion de Gel !',
'☄️ 흡인!':'☄️ Vortex !',
'☄️ 대폭발!':'☄️ Méga Explosion !',
'❄ 얼음보주!':'❄ Orbe de Glace !',
'❄ 파쇄!':'❄ Fracture !',
'☄️💥 대폭발!':'☄️💥 Méga Explosion !',
'반사!':'Réflexion !',
// --- Phase 13: boss moves ---
'💀 도넛!':'💀 Donut !','💀 전멸!':'💀 Annihilation !',
'🌊 파도!':'🌊 Vague !','속박!':'Entrave !','반격!':'Contre-attaque !',
'분신!':'Clone !','분신 파괴!':'Clone Détruit !','무기 해방!':'Libération d\'Arme !',
'❄프리즌!':'❄Prison !','⚡ 증표 ':'⚡ Marque ',
'흔들!':'Secousse !','⚠ 광역 발사!':'⚠ Tir de Zone !',
'🔥 확산!':'🔥 Propagation !','⚠ 돌진!':'⚠ Charge !',
'🦅 도약!':'🦅 Bond !','⚡ 레이저!':'⚡ Laser !',
'🌊 충격파!':'🌊 Onde de Choc !','👹 소환!':'👹 Invocation !',
'☄ 유성우!':'☄ Pluie de Météores !','🖐 잡기!':'🖐 Saisie !',
'🌀 회전참!':'🌀 Tourbillon !','💣 지뢰!':'💣 Mine !',
'🌀 흡인!':'🌀 Aspiration !','🔴 빨간콩 폭풍!':'🔴 Tempête de Haricots Rouges !',
'🔴🔴 콩 비!':'🔴🔴 Pluie de Haricots !',
'🌊 부채꼴 충격파!':'🌊 Onde de Choc en Éventail !',
'✴ 멸광 레이저!':'✴ Laser d\'Annihilation !',
'🔴 추적 장판!':'🔴 Zone de Traque !',
'💥 속성탄!':'💥 Projectile Élémentaire !',
'⚔ 검기!':'⚔ Ki d\'Épée !','⚔ 재단참!':'⚔ Fauchage !',
'🌀 나선탄!':'🌀 Tir en Spirale !','⚠ 찌르기!':'⚠ Estoc !',
'🔥🔥 지옥기둥!':'🔥🔥 Pilier Infernal !',
'⚔ 환영검!':'⚔ Lame Spectrale !',
'💢 반격자세!':'💢 Posture de Contre !',
'⚔ 연격!':'⚔ Enchaînement !','🌑 암흑!':'🌑 Ténèbres !',
'👥 분신!':'👥 Clone !','🌋 균열!':'🌋 Faille !',
'🌊 파동!':'🌊 Ondulation !','💣 추적지뢰!':'💣 Mine Traqueuse !',
'⏪ 되감기!':'⏪ Rembobinage !','🌀 중력장!':'🌀 Champ Gravitationnel !',
'🔨 벽밀기!':'🔨 Poussée Murale !','☠ 독안개!':'☠ Brouillard Toxique !',
'⛓ 감옥!':'⛓ Prison !','⚡ 연쇄번개!':'⚡ Foudre en Chaîne !',
'🔮 궤도탄!':'🔮 Tir Orbital !','🛡 방패돌진!':'🛡 Charge au Bouclier !',
'🪞 반격자세!':'🪞 Posture de Contre !','⚓ 속박!':'⚓ Entrave !',
'👤 분신!':'👤 Clone !','🖐 탈취!':'🖐 Vol !',
'🔥🔥 용암 지대!':'🔥🔥 Zone de Lave !',
'🌧🌧 화염 폭격!':'🌧🌧 Bombardement de Feu !',
'⚡⚡ 전격 장막!':'⚡⚡ Voile de Foudre !',
'💀 내 곁으로!':'💀 Viens à moi !',
'⭕ 안전!':'⭕ Sûr !',
'💀💀 전멸 폭발!':'💀💀 Explosion d\'Annihilation !',
'⚡ 쐐기 소멸!':'⚡ Extinction du Coin !',
'🌊충격파!':'🌊Onde de Choc !',
'👿악의+100':'👿Malice+100',
'💥패링폭발!':'💥Explosion de Parade !',
'균열 충돌! ':'Collision de Faille ! ',
'벽 충돌! ':'Collision Murale ! ',
'소환!':'Invocation !','환영!':'Spectre !',
'⚡낙뢰!':'⚡Tonnerre !','⚡빔!':'⚡Rayon !',
'환영술!':'Illusion !','💀소환!':'💀Invocation !',
'🔮주술!':'🔮Maléfice !','🩸산란!':'🩸Ponte !',
'💢광폭!':'💢Frénésie !','🕷산란!':'🕷Ponte !',
'❄서리!':'❄Givre !','❄빙결파!':'❄Vague de Gel !',
'💀빙마!':'💀Démon de Glace !',
// --- Phase 13: mob actions ---
'돌진!':'Charge !','충격파!':'Onde de Choc !','독안개!':'Brouillard Toxique !',
'연타!':'Rafale !','포효!':'Rugissement !','강화!':'Renforcement !',
'꼬리!':'Queue !','은신...':'Furtivité...','기습!':'Embuscade !',
'산란!':'Ponte !','독가스!':'Gaz Toxique !','소멸...':'Dissolution...',
'강타!':'Frappe !','분비!':'Sécrétion !','채찍!':'Fouet !',
'출혈!':'Hémorragie !','급강하!':'Plongeon !','방출!':'Décharge !',
'충격!':'Impact !','치유!':'Guérison !','의식!':'Rituel !',
'지옥불!':'Feu Infernal !','끌려감!':'Traîné !','혀!':'Langue !',
'응시!':'Regard !','낙하!':'Chute !','핏방울!':'Goutte de Sang !',
'일어남!':'Relevé !','휩쓸기!':'Balayage !','웅크림':'Accroupi',
'뼈칼날!':'Lame d\'Os !','감속!':'Ralentissement !','비명!':'Hurlement !',
'화산탄!':'Tir Volcanique !','자폭!':'Auto-destruction !','감싸기!':'Enveloppement !',
'잡기!':'Saisie !','내리찍기!':'Écrasement !','브레스!':'Souffle !',
'비행!':'Vol !','용암비!':'Pluie de Lave !','물뿜기!':'Jet d\'Eau !',
'빛...':'Lumière...','삼키기!':'Engloutissement !','마비!':'Paralysie !',
'방전!':'Décharge !','집게찍기!':'Frappe de Pince !','찍기!':'Écrasement !',
'붙잡기!':'Agrippement !','감아올리기!':'Enroulement !','파편!':'Fragment !',
'할퀴기!':'Griffure !','기생충!':'Parasite !',
'심연 해방!':'Libération Abyssale !','촉수난타!':'Barrage de Tentacules !',
'삼지창!':'Trident !','소용돌이!':'Vortex !','해일!':'Tsunami !',
'끼걱!':'Crissement !','폭발!':'Explosion !','체인!':'Chaîne !',
'갈기!':'Crinière !','공포!':'Terreur !','흡혈!':'Drain !',
'베기!':'Tranchage !','비이이명!!':'Vrombissement !!','분열!':'Scission !',
'3연참!':'Triple Tranchage !','패링!':'Parade !',
'...복사...':'...Copie...','불균형...저주!':'Déséquilibre...Malédiction !',
'저주!':'Malédiction !','균형...강화!':'Équilibre...Renforcement !',
'심판의 기둥!':'Pilier du Jugement !','처형 선고!':'Sentence de Mort !',
'고통의 해방!':'Libération de Souffrance !','너도 느껴봐라!':'Souffre toi aussi !',
'대검난무!':'Frénésie d\'Espadon !','촉수!':'Tentacule !',
'전방위 빔!':'Rayon Omnidirectionnel !','회피!':'Esquive !',
// --- Phase 13: rare mob / merchant ---
'[F] 상점':'[F] Boutique','거래 성공!':'Transaction réussie !',
'악의 부족! (':'Malice insuffisante ! (',
'상인이 떠납니다...':'Le marchand s\'en va...',
'사슬 해방!':'Libération des Chaînes !','완전 해방!':'Libération Totale !',
'⏪ 시간 되감기!':'⏪ Rembobinage Temporel !','전환!':'Transition !',
'부활 ':'Résurrection ','🌀균열!':'🌀Faille !','...사라짐':'...Disparu',
'낫 베기!':'Fauchage !','☠ 죽음의 선고!':'☠ Sentence de Mort !',
'선고 집행...':'Exécution de la sentence...',
'⚡패링!':'⚡Parade !','경직!':'Chancellement !',
'⚠ 잡혔다!':'⚠ Attrapé !','💥 내던지기!':'💥 Projection !',
'💥 소용돌이 폭발!':'💥 Explosion du Vortex !',
'👻 순간이동!':'👻 Téléportation !','💫 기절! 5초':'💫 Étourdi ! 5s',
'찌르기 반격!':'Estoc de Riposte !','💢 폭발!':'💢 Explosion !',
'반격 실패':'Contre-attaque ratée','탈취 반격!':'Riposte de Vol !',
'무기 봉인!':'Arme Scellée !','냠!':'Miam !',
// --- Phase 13: stage/room/map ---
'합체!':'Fusionné !','출구가 열렸다!':'La sortie est ouverte !',
'보물상자 출현!':'Un coffre au trésor est apparu !','출구':'Sortie',
'⚠ 문지기가 살아있다!':'⚠ Le gardien est encore en vie !',
'⏱ 타임어택 ':'⏱ Contre-la-Montre ',
'처치율 ':'Taux d\'Élimination ',
'무적!':'Invincible !','불사 보호':'Protection d\'Immortalité',
'빙결!':'Gelé !','환영 소멸!':'Spectre Dissipé !',
'부활력 ':'Force de Résurrection ',
'✟ 신성력 억제! (':'✟ Suppression Sacrée ! (',
'부활 실패 (':'Résurrection échouée (',
'⚡순간이동!':'⚡Téléportation !',
'👻 동반부활!':'👻 Co-Résurrection !',
'✟ 신성력 억제!':'✟ Suppression Sacrée !',
'💀 부활 판정 중...':'💀 Jugement de résurrection...',
'⚔ 문지기 처치!':'⚔ Gardien Éliminé !',
'🚪 보스방 개방!':'🚪 Salle du Boss Ouverte !',
'잔해 출현!':'Des débris sont apparus !',
'🌀균열 발생!':'🌀Faille ouverte !',
'🔥복수!':'🔥Vengeance !','💥폭독혈!':'💥Sang Pestilent !',
'빙판!':'Sol Gelé !','❄빙결파!':'❄Vague de Gel !',
'❄최종빙결!':'❄Gel Final !','빙마 처치!':'Démon de Glace Éliminé !',
'분리!':'Séparation !','뼈 파편!':'Fragment d\'Os !',
'태아 처치!':'Fœtus Éliminé !','지배자 처치!':'Seigneur Éliminé !',
'용암!':'Lave !','화룡 처치!':'Dragon de Feu Éliminé !',
'최후의 비명!':'Hurlement Final !','산화...':'Oxydation...',
'심판자 처치!':'Juge Éliminé !','고통의 왕 처치!':'Roi de la Souffrance Éliminé !',
'수역!':'Zone Aquatique !','파편 폭발!':'Explosion de Fragments !',
'거대어 처치!':'Léviathan Éliminé !','대사도 처치!':'Grand Apôtre Éliminé !',
'독웅덩이!':'Mare de Poison !','화염장판!':'Zone de Feu !','전기장!':'Champ Électrique !',
'무기 드롭!':'Arme Lâchée !','보물 발견!':'Trésor Trouvé !',
'상인의 주머니 +':'Bourse du Marchand +',
'속박의 파편!':'Éclat d\'Entrave !','시간의 조각!':'Fragment de Temps !',
'저주 해제!':'Malédiction Levée !','차원의 결정!':'Cristal Dimensionnel !',
'전설 아이템!':'Objet Légendaire !','죽음을 이겨냈다!':'Tu as vaincu la Mort !',
'💥대폭발!':'💥Méga Explosion !','⚡강화!':'⚡Renforcement !',
// --- Phase 13: combat/defense ---
'장비 ':'Équipement ',
'💫 진동!':'💫 Vibration !','❄ 무적!':'❄ Invincible !',
'\u{1F47B} 유령!':'\u{1F47B} Fantôme !',
'집중 해제!':'Concentration annulée !',
'🕊️ 평화보호 ':'🕊️ Égide ',
'🛡 보호막 ':'🛡 Bouclier ',
'🌀 회전보호막 ':'🌀 Bouclier Rotatif ',
'💥한방캡!':'💥Plafond de Dégâts !',
'⚡쉴드 파괴!':'⚡Bouclier Détruit !',
'💀 불굴!':'💀 Inébranlable !',
'💀 1회부활!':'💀 Résurrection Unique !',
'감시 회수':'Rappel Sentinelle',
'악마화 부활!':'Résurrection Démoniaque !',
// --- Phase 13: skill panel ---
'기검참':'Lame de Ki','날개치기':'Frappe d\'Aile',
'배정 가능한 스킬 없음':'Aucune compétence assignable',
'칼날 없음!':'Pas de Lame !',
'⚔ 악의사냥!':'⚔ Chasse de Malice !',
'❄🌪️ 얼음소용돌이!':'❄🌪️ Vortex de Glace !',
'🌪️ 폭풍소환!':'🌪️ Invocation de Vortex !',
'\u{1F9B4} 해골무덤!':'\u{1F9B4} Tombe d\'Ossements !',
'🌹 붉은꽃!':'🌹 Fleur Écarlate !',
'💥 폭산탄!':'💥 Tir Explosif !',
'🪡 바늘출!':'🪡 Salve d\'Aiguilles !',
'⚡ 전격이동!':'⚡ Pas Éclair !',
'기둥가시로 흡수됨':'Absorbé par l\'épine du pilier',
'🌿 가시덫!':'🌿 Piège à Pointes !',
'👻 공성유령!':'👻 Fantôme de Siège !',
'🏹 공성쇠뇌 설치!':'🏹 Arbalète de Siège Placée !',
'👻 유령 허수아비!':'👻 Leurre Fantôme !',
'💥 폭발 허수아비!':'💥 Leurre Explosif !',
'축적!':'Accumulé !','축적 중...':'Accumulation...','만충! 재입력→폭발':'Plein ! Re-presser→Explosion',
'폭발! ':'Explosion ! ','불발...':'Raté...','뎀':' DÉG',
'🩸 폭독칼날!':'🩸 Lame Pestilente !',
'⚡날개치기!':'⚡Frappe d\'Aile !',
'🗡 칼등날개!':'🗡 Aile de Bouclier !',
'🏛️ 악의기둥!':'🏛️ Pilier des Ténèbres !',
'🌿 기둥가시!':'🌿 Épine du Pilier !',
'🌋 지옥강타!':'🌋 Frappe Infernale !',
'💥 체간 붕괴!':'💥 Rupture de Posture !',
'💫 포이즈 파괴!':'💫 Posture Détruite !',
'⚡ 뇌전걸음!':'⚡ Marche Fantôme !',
'✟ 구속의 영역!':'✟ Domaine d\'Entrave !',
'✟ 신성폭발!':'✟ Explosion Sacrée !',
'⛧ 블랙!':'⛧ Étoile Noire !',
'🌋 용암소환!':'🌋 Invocation de Lave !',
'필살기 배정!':'Ultime assigné !',
'완료':'Terminé','합체 가능':'Fusion possible','부족':'Insuffisant',
'SP 부족! (':'SP requis ! (',
'🕊️ 히든: 평화의보호 해금!':'🕊️ Caché : Égide de Paix débloquée !',
'⚡ 히든: 참회 해금!':'⚡ Caché : Repentance débloquée !',
'배정됨':'Assigné',
'합체 Lv.':'Fusion Nv.',
'◆ 같은 보석 스킬 습득 시 합체 가능':'◆ Fusion possible en apprenant la même compétence de gemme',
// --- Phase 13: inventory/forge/storage ---
'▼ 가방 → 창고 보관':'▼ Sac → Entrepôt',
'▲ 창고 → 가방 꺼내기':'▲ Entrepôt → Sac',
'✓ 선택됨':'✓ Sélectionné',
'⟨ 입력 대기... ⟩':'⟨ En attente... ⟩',
'⟨ 대기 ⟩':'⟨ Attente ⟩',
'보조':'Secondaire',
'키 설정 초기화 (또는 F5 키)':'Réinitialiser les Touches (ou F5)',
'아무 키 또는 마우스 버튼을 누르세요 (ESC = 취소)':'Appuie sur une touche ou un bouton souris (ESC = annuler)',
'WebGPU 활성':'WebGPU Actif','WebGL2 활성':'WebGL2 Actif',
'측정 중...':'Mesure en cours...',
'불러오기 실패':'Échec du Chargement',
'장착':'Équipé',
'🔒 중요잠금 아이템은 분해 선택 불가!':'🔒 Les objets verrouillés ne peuvent pas être sélectionnés pour démantèlement !',
'장비 강화 (실패 시 재료만 소멸)':'Améliorer l\'Équipement (en cas d\'échec, seuls les matériaux sont perdus)',
'강화 보너스 적용':'Bonus d\'Amélioration Appliqué',
'강화 실패!':'Amélioration Échouée !',
'장착된 장비가 없습니다.':'Aucun équipement porté.',
'충분':'Suffisant','더 필요':'Encore nécessaire',
'장비 선택':'Choisir l\'Équipement','목표치 설정':'Définir l\'Objectif',
'악의 투입':'Investir la Malice','자동 시도':'Tentative Auto',
'목표 강화치':'Objectif d\'Amélioration',
'예상 필요 악의':'Malice Estimée Nécessaire',
'보유':'Possédé','강화 시작':'Démarrer l\'Amélioration',
'위에서 장비를 선택하세요':'Sélectionne un équipement ci-dessus',
'⬆ 물약 강화 (최대 10단)':'⬆ Améliorer Potion (max niv. 10)',
'필요':'Requis',
'악의의 분해로 — 장비를 악의로 갈아버려라':'Fournaise de Malice — Broie l\'équipement en Malice',
'전체 선택':'Tout Sélectionner','전체 해제':'Tout Désélectionner',
'희귀 이하':'Rare ou inférieur',
'어픽스 리롤!':'Relance d\'Affixe !',
'결정 분해 → 결정 가루':'Décomposer Cristal → Poudre de Cristal',
'결정 제작 (가루 → 결정)':'Fabrication de Cristal (Poudre → Cristal)',
'물리':'Physique','영웅':'Héroïque','전설':'Légendaire',
'무기 타입':'Type d\'Arme','활 타입':'Type d\'Arc',
'보스방':'Salle du Boss','ST 부족':'ST insuffisant',
// --- Phase 14: boss phase labels ---
'💀 광폭화!':'💀 Enragé !',
// --- Phase 14: chapter pet dialogue ---
'...따라오는 거 아니야. 같은 방향일 뿐이지.':"...Je te suis pas. On va juste dans la même direction.",
'공기가 달라졌어. 더 썩었군.':"L\'air a changé. Plus de pourriture.",
'여기부터는 악마 영역이야. ...맘대로 해.':"Territoire démoniaque à partir d\'ici. ...Fais comme tu veux.",
'...이 냄새. 살점이 썩는 냄새야.':"...Cette odeur. De la chair en putréfaction.",
'여기 오래 있으면 미쳐. 나도, 너도.':"Reste trop longtemps et tu deviendras fou. Moi aussi.",
'이 길의 끝에 뭐가 있을까. ...알고 싶지도 않어.':"Qu\'y a-t-il au bout de cette route ? ...Je préfère ne pas savoir.",
'...여기가 끝이야. 돌아갈 길은 없어.':"...C\'est la fin. Pas de retour possible.",
// --- Phase 14: idle tips (crow) ---
'작살을 땅에 꽂으면 끌려간다.':'Plante le harpon dans le sol et fais-toi tracter.',
'Shift로 작살 던져봐!':'Essaie de lancer le harpon avec Shift !',
'패링 성공하면 ST가 회복된다. 공짜 자원이야.':'La parade restaure le ST. Ressources gratuites.',
'패링 많이 하면 ST 걱정 없어~':'Pare souvent et le ST n\'est plus un problème~',
'장비 분해하면 악의를 얻는다. 쓰레기도 자원이야.':'Démanteler l\'équipement donne de la Malice. Même le rebut, c\'est des ressources.',
'TAB 열어서 안 쓰는 장비 분해해!':'Ouvre TAB et démantèle l\'équipement inutile !',
'그로기 상태의 적에겐 1.5배 데미지가 들어간다.':'Les ennemis étourdis subissent 1,5x dégâts.',
'무릎 꿇으면 전력으로 때려!':'Quand ils s\'agenouillent, frappe de toutes tes forces !',
'속성 상성이 있다. 화염은 빙결에 약하고, 암전은 암흑에 약하다.':'Les éléments ont des faiblesses. Le Feu est faible contre la Glace, la Foudre contre les Ténèbres.',
'무기 속성 바꿔가면서 싸워봐!':'Essaie de changer l\'élément de ton arme en combat !',
'빙결된 적은 1.5배 데미지를 받는다.':'Les ennemis gelés subissent 1,5x dégâts.',
'얼리고 때리는 게 기본이야!':'Geler puis frapper — c\'est la base !',
'보스의 빨간 공격은 패링 가능. 보라빛은 회피만.':'Les attaques rouges du boss sont parables. L\'arc-en-ciel, esquive seulement.',
'색깔 잘 봐! 빨강은 받아치고 무지개는 피해!':'Regarde les couleurs ! Pare le rouge, esquive l\'arc-en-ciel !',
'VIT를 올리면 최대 HP가 오른다. 죽기 싫으면 찍어.':'VIT augmente les HP max. Investis si tu veux survivre.',
'STR은 근접, DEX는 활, INT는 마법! 골고루 말고 하나만!':'STR pour la mêlée, DEX pour l\'arc, INT pour la magie ! Concentre-toi sur un seul !',
'E를 꾹 누르면 빔이 나간다. 짧게 누르면 투사체.':'Maintiens E pour un rayon. Tape E pour un projectile.',
'마법 쓸 때 MP 잘 봐! 빔은 연속으로 깎여!':'Surveille ton MP avec la magie ! Le rayon draine vite !',
'핵터와 디로이가 아이템을 주워준다. 수거 범위 안이면.':'Hecter et Deroy ramassent les objets. S\'ils sont à portée.',
'우리한테 고마워해~ 안 주우면 썩잖아.':'Remercie-nous~ Les objets pourrissent si personne ne les ramasse.',
'LCK를 올리면 레어 드롭률이 오른다.':'LCK augmente le taux de butin rare.',
'운빨 게임이긴 하지~ LCK 올려봐!':'C\'est un jeu de chance~ Essaie de monter LCK !',
'강화하면 공격력이 쭉쭉 올라가! 악의만 있으면 돼!':'L\'amélioration booste l\'ATK rapidement ! Il faut juste de la Malice !',
'강화 확률은 +1에서 99%. 높을수록 떨어진다.':'Le taux d\'amélioration est de 99% pour +1. Ça baisse après.',
'실패하면 악의만 날아가~ 장비는 안 부서져!':'En cas d\'échec, seule la Malice est perdue~ L\'équipement survit !',
'대장간에서 장비 제작도 된다. 악의 30000개면 영웅급 이상.':'La forge peut aussi fabriquer de l\'équipement. 30000 Malice pour du Héroïque+.',
'랜덤이지만 좋은 거 나올 수도 있어!':'C\'est aléatoire, mais tu pourrais avoir quelque chose de génial !',
'쉴드는 마법으로, HP는 물리로 깎아야 제대로 먹힌다.':'Le bouclier se brise avec la magie, les HP avec le physique.',
'반대로 치면 50%만 들어가! 무기 바꿔가면서 싸워!':'Le mauvais type ne fait que 50% ! Change d\'arme !',
'장비에 접두사, 접미사가 붙으면 특수 효과가 생긴다.':'L\'équipement avec préfixe/suffixe gagne des effets spéciaux.',
'영웅급 이상 장비에만 붙어! 좋은 거 나오면 강화해!':'Seulement sur l\'équipement Héroïque+ ! Améliore les bons jets !',
'강화는 장비를 바꿔도 자동 이전된다. 악의만 있으면.':'L\'amélioration se transfère automatiquement au nouvel équipement. Juste besoin de Malice.',
'더 좋은 장비 나오면 바로 장착해! 강화 수치 그대로 옮겨가!':'Équipe le meilleur équipement tout de suite ! Le niveau d\'amélioration se transfert !',
// --- Phase 14: additional tutorial lines ---
'패링을 써야 자원을 흡수한다고!':'Il faut parer pour absorber les ressources !',
'F키 회복의 영역을 써봐. 자원이 차올라.':'Essaie le Domaine Sacré avec la touche F. Les ressources se remplissent.',
'적이 근접하면 스페이스키야! 가시덫을 활용해!':'Quand les ennemis sont proches, Espace ! Utilise le Piège à Pointes !',
'기절시켜! 그로기가 터지면 데미지가 1.5배야!':'Étourdis-les ! L\'état étourdi donne 1,5x dégâts !',
'1번 대왕치기로 밀어버려!':'Utilise la touche 1 Frappe Colossale pour les repousser !',
'무릎 꿇었다.':'Il s\'agenouille.',
'지금이야! 몰아쳐!!':'Maintenant ! Attaque à fond !!',
'스킬 포인트 있어! K 눌러서 스킬 찍어봐!':'Points de compétence disponibles ! Appuie sur K pour apprendre !',
'...힘이 없으면 여기서 끝이야.':'...Sans force, c\'est la fin ici.',
'...쓸 거 아니면 분해해.':'...Démantèle ce que tu n\'utilises pas.',
'아이템 넘쳐나네~ 우리가 주워줄게!':'Tant d\'objets~ On les ramasse pour toi !',
'악의가 바닥이다.':'Plus de Malice.',
'TAB 열어서 장비 분해해! 쓰레기도 악의가 돼!':'Ouvre TAB et démantèle ! Même le rebut devient de la Malice !',
'좋은 장비가 있네! G 눌러서 대장간 가봐!':'Bon équipement trouvé ! Appuie sur G pour la forge !',
'...강화 안 하면 그냥 고철이야.':'...Sans amélioration, c\'est de la ferraille.',
'...멈추지 마. 여신은 기다리지 않는다.':'...Ne t\'arrête pas. La déesse n\'attend pas.',
'앞으로 가자~ 나도 여기 오래 있기 싫어.':'Avançons~ J\'ai pas envie de rester ici non plus.',
'...냄새가 짙다. 큰 놈이 있어.':'...L\'odeur est forte. Quelque chose de gros rôde.',
'준비됐어? 물약 확인하고!':'Prêt ? Vérifie tes potions !',
// --- Phase 14: element names for forge/combat ---
'물리':'Physique','화염':'Feu',
// --- Phase 15: missing pet dialogue translations (59 lines) ---
// ── Tutorial: firstItem, potionCraft ──
'TAB을 눌러. 가방을 열고 장비를 입어야 한다.':'Appuie sur TAB. Ouvre ton sac et équipe-toi.',
'주웠으면 껴야지! TAB!':'Tu l\'as ramassé ? Équipe-le ! TAB !',
'G. 대장간에서 물약도 제작할 수 있다.':'G. Tu peux aussi fabriquer des potions à la forge.',
'악의로 물약 만들어! G키야!':'Fabrique des potions avec la Malice ! Touche G !',
// ── Stun warning ──
'기절이야! Ctrl 눌러!':'Étourdi ! Appuie sur Ctrl !',
'Ctrl 유령걸음으로 탈출!':'Ctrl Marche Fantôme pour t\'échapper !',
'Ctrl 얼음보주로 탈출!':'Ctrl Orbe de Glace pour t\'échapper !',
// ── Parry guide ──
'빨간 탄은 우클릭 패링. 무지개는 Q 패링.':'Projectiles rouges : parade RMB. Arc-en-ciel : parade Q.',
'나머지는 전부 우클릭 패링 가능해!':'Tout le reste peut être paré au clic droit !',
'빨강=우클릭, 무지개=Q 패링. 나머진 다 쳐내.':'Rouge=RMB, Arc-en-ciel=Q parade. Dévie le reste.',
'무지개는 Q로 패링! 나머지는 전부 우클릭!':'Arc-en-ciel avec Q ! Tout le reste au clic droit !',
// ── Resource / combat ──
'빠져! 물약 마시고 안전한 곳에서 회복해.':'Replie-toi ! Bois des potions et récupère en sécurité.',
'자원 없으면 도망가는 게 답이야!':'Plus de ressources ? Fuir, c\'est la bonne réponse !',
'스페이스! 가시덫으로 적 묶어버려!':'Espace ! Immobilise-les avec le Piège à Pointes !',
'근접이 너무 많아! 거리 벌려!':'Trop d\'ennemis au corps-à-corps ! Crée de la distance !',
'...둘러싸이면 끝이야. 빠져나와.':'...Si tu es encerclé, c\'est fini. Sors de là.',
'1번 대왕치기로 쓸어버려!':'Utilise la touche 1 Frappe Colossale pour les balayer !',
'그로기 터지면 데미지 1.5배!':'L\'état étourdi donne 1,5x dégâts !',
'회전참이나 광역기로 몰아! 한 놈씩 상대하면 죽어.':'Utilise le Tourbillon ou les attaques de zone ! Un par un, tu es mort.',
'뭉쳐있을 때가 기회야!':'Quand ils se regroupent, c\'est ta chance !',
'E로 마력공격을 해봐! 악의 쉴드를 해제할려면 마법 공격을 해야 해!':'Essaie E pour les attaques magiques ! Il faut de la magie pour briser les boucliers de Malice !',
'쉴드는 마법으로, HP는 물리로. 반대로 치면 데미지 안 들어간다.':'Bouclier avec la magie, HP avec le physique. Le mauvais type ne fait pas de dégâts.',
// ── Skill / passive / stamina hints ──
'L키로 스킬 슬롯에 넣어야 쓸 수 있어.':'Appuie sur L pour assigner les compétences aux slots.',
'C키를 눌러. 패시브 포인트가 쌓여있다.':'Appuie sur C. Les points passifs se sont accumulés.',
'C키! 패시브 올리면 진짜 강해져!':'Touche C ! Les passifs te rendent vraiment plus fort !',
'스태미나가 부족하다. 무리하지 마.':'Endurance trop basse. Ne force pas.',
'ST 없으면 스킬 못 써! 잠깐 빠져!':'Pas de ST, pas de compétences ! Recule un peu !',
// ── Item pickup (line 9324) ──
'탭 장비창을 열어봐. 아이템을 주워왔어!':'Ouvre TAB pour l\'inventaire. On a ramassé un objet !',
'좋은 거 나왔다! TAB 열어서 확인해봐!':'Quelque chose de bien est tombé ! Ouvre TAB pour vérifier !',
// ── Revive tutorial (line 22486) ──
'악의에 중독되면 악마가 돼서 부활력이 생긴대. 저 녀석처럼.':'On dit que l\'intoxication à la Malice te transforme en démon avec le pouvoir de résurrection. Comme celui-là.',
'혹시 너도...?':'Peut-être toi aussi... ?',
// ── Revive tip (line 30541) ──
'데미지가 부족하면 무기류 강화를 해야해!!':'Si les dégâts sont insuffisants, améliore tes armes !!',
'G키 대장간. 강화 안 하면 여기서 계속 죽어.':'Touche G pour la forge. Sans amélioration, tu mourras ici sans cesse.',
// ── Idle nag lines ──
'시간이 없어. 움직여.':'Pas le temps. Bouge.',
'멍하게 서있으면 안 돼!':'Reste pas planté là !',
'...뭘 기다리는 거야?':'...Qu\'est-ce que t\'attends ?',
'가자가자! 몬스터가 기다려!':'Allez ! Les monstres attendent !',
'여기 오래 있으면 위험해.':'Rester ici trop longtemps, c\'est dangereux.',
'움직여야 해! 가만있으면 둘러싸여!':'Il faut bouger ! Immobile, tu seras encerclé !',
'쉬는 건 죽고 나서 해.':'Tu te reposeras quand tu seras mort.',
'살아있을 때 쉬면 안 돼!':'Pas de repos tant que t\'es en vie !',
'적이 몰려오고 있어. 빨리 움직여.':'Les ennemis se rapprochent. Bouge vite.',
'냄새 맡고 올 거야. 빨리!':'Ils vont sentir ton odeur. Dépêche-toi !',
'...아직 살아있는 거 맞지?':'...T\'es encore en vie, hein ?',
'혹시 잠든 거야...?':'Tu t\'es endormi... ?',
// ── Chapter entry dialogues ──
'...나무가 썩어가고 있어. 여기는 지옥의 입구야.':'...Les arbres pourrissent. C\'est l\'entrée de l\'enfer.',
'냄새 지독해... 빨리 지나가자.':'La puanteur est terrible... Passons vite.',
'조심해. 벌레굴이다. 벽이랑 바닥에서 기어나와.':'Attention. Nid de vers. Ils rampent des murs et du sol.',
'으으... 벌레 싫어! 밟아버려!':'Beurk... Je déteste les insectes ! Écrase-les !',
'...공기가 얼어붙는다. 여기선 화염이 먹힌다.':'...L\'air se gèle. Le feu marche ici.',
'추워... 빙결 조심해! 얼면 끝이야.':'Froid... Attention au gel ! Si tu gèles, c\'est fini.',
'용암이다. 바닥을 밟으면 타 죽어.':'De la lave. Marche dessus et tu brûles vif.',
'뜨거워! 여기 왜 이렇게 빨개!':'C\'est brûlant ! Pourquoi tout est si rouge ici !',
'...군단이다. 수가 많아. 광역기 없으면 밀려.':'...C\'est la légion. Trop nombreux. Sans attaque de zone, tu seras submergé.',
'우글우글... 징그러워. 한꺼번에 쓸어!':'Ça grouille partout... Dégoûtant. Balaie-les tous d\'un coup !',
'사도의 영역이야. 여기 놈들은 머리가 좋아.':'Territoire de l\'Apôtre. Ceux-là sont malins.',
'패턴이 복잡해졌어... 집중해!':'Les patterns se sont compliqués... Concentre-toi !',
'...끝이다. 지옥의 심장부. 살아 돌아가는 건 포기해라.':'...C\'est la fin. Le cœur de l\'enfer. Abandonne tout espoir de retour.',
'여기가 마지막이야... 각오해.':'C\'est le dernier endroit... Prépare-toi.',
'석궁 자동발사 (T)':'Arbalète automatique (T)',
'버스트루프 당기기 (H)':'Boucle explosive attirer (H)',
'결정 자동합성':'Synthèse auto de cristal',
'결정 자동강화':'Amélioration auto de cristal',
'✓ 설정 자동 저장':'✓ Paramètres sauvegardés auto',
'세팅 프리셋 저장/불러오기':'Sauvegarder/charger préréglage',
'세팅1 저장':'Sauvegarder Préréglage 1','세팅1':'Préréglage 1',
'세팅2 저장':'Sauvegarder Préréglage 2','세팅2':'Préréglage 2',
'재진단':'Re-diagnostiquer',
'게임 리셋 (처음부터)':'Réinitialiser le jeu (depuis le début)',
'캐릭터 선택 (로비)':'Sélection de personnage (Lobby)',
'닫기 [ESC]':'Fermer [ESC]','닫기 [G]':'Fermer [G]','닫기 [V]':'Fermer [V]','닫기 [C]':'Fermer [C]',
'전체화면 (F11)':'Plein écran (F11)',
'정말 모든 진행을 초기화하시겠습니까?':'Voulez-vous vraiment réinitialiser toute la progression?',
'검출 중...':'Détection...',
'마우스 커서':'Curseur de souris','그래픽 품질':'Qualité graphique','하드웨어 진단':'Diagnostic matériel',
'BGM 선택':'Sélection BGM',
'자동 (스테이지별)':'Automatique (par stage)','전체 랜덤':'Tout aléatoire','로비':'Lobby',
'1장 랜덤':'Chapitre 1 aléatoire','2장 랜덤':'Chapitre 2 aléatoire','3장 랜덤':'Chapitre 3 aléatoire',
'4장 랜덤':'Chapitre 4 aléatoire','5장 랜덤':'Chapitre 5 aléatoire','6장 랜덤':'Chapitre 6 aléatoire','7장 랜덤':'Chapitre 7 aléatoire',
'보스':'Boss','최종보스':'Boss final',
'대장간 랜덤':'Forge aléatoire','사망 랜덤':'Mort aléatoire','승리 랜덤':'Victoire aléatoire',
'지옥 추락 사망 징글':'Jingle mort chute enfer','탈출 성공':'Évasion réussie',
'── 1장 - 썩은 숲 ──':'── CH1 - Rotten Forest ──',
'── 2장 - 벌레굴 ──':'── CH2 - Worm Nest ──',
'── 3장 - 얼음굴 ──':'── CH3 - Ice Cavern ──',
'── 4장 - 화염지대 ──':'── CH4 - Infernal Wastes ──',
'── 5장 - 지옥군단 ──':'── CH5 - Hell Legion ──',
'── 6장 - 사도마굴 ──':'── CH6 - Apostle Den ──',
'── 7장 - 지옥성 ──':'── CH7 - Hell Citadel ──',
'── 공통 ──':'── Common ──',
'⌨ 조작법':'⌨ Commandes','클릭하면 닫힘':'Cliquer pour fermer',
'전투력':'PC','가방':'Sac','결정':'Cristal',
'↕ 정렬':'↕ Trier','쓰레기 전체선택':'Sélectionner tout le rebut','쓰레기 전부 분해':'Désassembler tout le rebut',
'창고':'Entrepôt','스탯 포인트':'Points de stat','능력치 요약':'Résumé des stats','올 리셋':'Tout réinitialiser',
'대장간':'Forge','스킬':'Compétences','능력치':'Statistiques',
'좌클스킬 (클릭 전환)':'Compétence clic gauche (clic pour changer)','우클스킬 (클릭 전환)':'Compétence clic droit (clic pour changer)',
'이동스킬 (클릭 전환)':'Compétence déplacement (clic pour changer)','마법스킬 (클릭 전환)':'Compétence magie (clic pour changer)',
'영역스킬 (클릭 전환)':'Compétence zone (clic pour changer)','피보호막 (클릭 전환)':'Bouclier de sang (clic pour changer)',
'CT스킬 (클릭 전환)':'Compétence CT (clic pour changer)','[C] 능력치':'[C] Statistiques',
'무기 공격':'Attaque à l\'arme','칼등 처내기 (투사체 반사, 홀드 연사)':'Parade (réfléchit projectiles, maintenir=rafale)',
'연속 처내기':'Parade continue','영역 스킬 (폭풍소환 등)':'Compétence de zone (Vortex etc)',
'작살 발사':'Tirer harpon','마법 (탭=투사체, 홀드=빔)':'Magie (appui=projectile, maintenir=rayon)',
'데빌포스 흡수':'Absorber Force Démoniaque','물약 / 스킬슬롯':'Potions / Emplacements compétences',
'스킬슬롯 5 / 필살기 / CT스킬':'Emplacement 5 / Ultime / Comp. CT','스킬 슬롯 배정':'Attribution d\'emplacement',
'✟ 결계의 영역!':'✟ Domaine du Sceau!',
'✟ 물의 영역!':'✟ Domaine de l\'Eau!',
'✟ 파쇄의 영역!':'✟ Domaine du Fracas!',
'✟ 침식의 영역!':'✟ Domaine de l\'Érosion!',
'✟ 관통의 영역!':'✟ Domaine de la Percée!',
'✟ 권능의 영역!':'✟ Domaine de la Souveraineté!',
'⏳ 시간왜곡!':'⏳ Distorsion Temporelle!',
'쿨다운!':'Recharge!',
'집중!':'Concentration!',
'\u{1F47B} 유령총!':'\u{1F47B} Pistolet Fantôme!',
'💥 유령총 폭발!':'💥 Explosion du Pistolet Fantôme!',
'⚡ 전격의창!':'⚡ Lance du Tonnerre!',
'임계...!':'Critical...!',
// --- Phase 27 additions ---
// KEY BINDINGS
'위로 이동':'Déplacer vers le haut','아래로 이동':'Déplacer vers le bas','왼쪽 이동':'Déplacer à gauche','오른쪽 이동':'Déplacer à droite',
'칼등 처내기 (탭=처내기, 홀드=연사)':'Parade de lame (touche=parade, maintien=rafale)',
'영역 스킬':'Compétence de zone','작살 이동':'Dash au harpon',
'유령불꽃 켜기/끄기':'Flamme Fantôme marche/arrêt',
'기동칼날개 자동 켜기/끄기':'Aile-Lame Enchaînée auto marche/arrêt',
'해상도':'Résolution',
// DEATH / LEVEL-UP / INTRO SCREEN
'빛이 꺼졌다':'La lumière s\'éteint',
'누군가는 너를 기다리고 있다':'Quelqu\'un t\'attend',
'다시 일어서라':'Relève-toi',
'로비로 돌아가기':'Retour au lobby',
'☠ 사망 리플레이':'☠ Replay de mort',
'지옥의 시련을 견뎌냈다':'Tu as enduré l\'épreuve de l\'enfer',
'계속 전투':'Continuer le combat',
'난이도를 선택하라':'Choisis la difficulté',
'나중에 설정(ESC)에서 변경 가능':'Modifiable dans les paramètres (ESC)',
// UI
'일괄합성':'Synthèse en masse','일괄강화+합성':'Améliorer+Synthétiser en masse',
'자원 부족!':'Ressources faibles !',' 뎀':' DGT',
// GAME COMBAT MESSAGES
'합체 폭발!':'Explosion de fusion !',
'MP 부족! (50)':'MP insuffisant ! (50)',
'부활력 고갈!':'Force de résurrection épuisée !',
'☠ 부활력 고갈!':'☠ Force de résurrection épuisée !',
'독안개':'Brume empoisonnée','뇌전창':'Lance du tonnerre',
'🔥 업화선 시전...':'🔥 Rayon infernal en incantation...',
'💥 기동파괴 그로기!':'💥 Destruction enchaînée — groggy !',
'💥 칼등 그로기!':'💥 Parade — groggy !',
'⚡ 순간이동 준비!':'⚡ Téléportation prête !',
'👿악의+1000':'👿Malveillance+1000',
'💀 내려찍기!':'💀 Écrasement !',
'✟ 신성력 억제! +':'✟ Sacré supprimé ! +',
'✟ 신성력 억제!':'✟ Sacré supprimé !',
'✟ 신성력 억제! (':'✟ Sacré supprimé ! (',
'💥 지진그로기!':'💥 Groggy sismique !',
'💥 기폭그로기!':'💥 Groggy détonation !',
'폭발! ×':'Explosion ! ×',
'⚫ 기둥강타!':'⚫ Frappe de pilier !',
'💥 대왕치기 그로기!':'💥 Frappe titanesque — groggy !',
'💫 미니스턴!':'💫 Mini-étourdissement !',
'⚡ 뇌전창!':'⚡ Lance du tonnerre !',
// PET DIALOGUE (crow/cat)
'…절반이다. 정신차려.':'…À moitié. Reprends-toi.',
'…죽기 직전이다. 한 발만 더.':'…Presque mort. Encore un coup.',
'…다음 한 방이 마지막이야.':'…Le prochain coup est le dernier.',
'기절!  ':'Étourdi !  ',
'마력이 빈다. 평타 섞어.':'MP qui baisse. Mélange des attaques normales.',
'그랩이다. 거리를 둬.':'Saisie. Garde tes distances.',
'광역기다. 멀어져.':'AoE. Recule.',
'…아파? 당연하지. 여긴 지옥이야.':'…Ça fait mal ? Évidemment. C\'est l\'enfer.',
'F키도 스킬 슬롯이야!':'La touche F est aussi un slot !',
'L-CTRL로 유령걸음/얼음보주!':'L-CTRL pour Marche Fantôme / Orbe de Glace !',
'V 눌러서 창고에 넣어둬!':'Appuie sur V pour l\'entrepôt !',
'ESC로 설정! 난이도/자동물약!':'ESC — paramètres ! Difficulté/potions auto !',
'잡몹이다. 먼저 정리해.':'Ennemis normaux. Élimine-les d\'abord.',
'…얼어붙은 놈은 오래 안 간다.':'…Un congelé ne dure pas longtemps.',
'…냄새가 짙다. 큰 놈이 있어.':'…L\'odeur est forte. Quelque chose de grand est proche.',
'쉴드는 마법으로, HP는 물리로.':'Bouclier par magie, HP par physique.',
'스페이스! 가시덫으로 적 묶어!':'Espace ! Piège les ennemis avec le Piège à Épines !',
'근접 너무 많아! 거리 벌려!':'Trop de corps à corps ! Prends tes distances !',
'회전참이나 광역기로 몰아!':'Utilise Tourbillon ou AoE !',
'F 눌러! 회복의 영역 깔아!':'Appuie sur F ! Déploie le Domaine Sacré !',
'F키 회복의 영역을 써봐.':'Essaie la touche F — Domaine Sacré.',
'빠져! 물약 마시고 회복해.':'Recule ! Bois une potion et récupère.',
'쉬프트! 사슬기동은 이동기야!':'Shift ! La ruée enchaînée est un déplacement !',
'스킬포인트 쌓였어! K 눌러!':'Points de compétence accumulés ! Appuie sur K !',
'스킬 포인트 있어! K!':'Des points de compétence ! K !',
'C키. 패시브 포인트가 쌓여있다.':'Touche C. Des points passifs accumulés.',
'…쓸 거 아니면 분해해.':'…Démantèle ce dont tu n\'as pas besoin.',
'…강화 안 하면 그냥 고철이야.':'…Sans amélioration c\'est juste de la ferraille.',
'빨간 탄은 우클릭. 무지개는 Q.':'Rouge — clic droit. Arc-en-ciel — Q.',
'빨강=우클릭, 무지개=Q.':'Rouge=clic droit, arc-en-ciel=Q.',
'…멈추지 마. 여신은 기다리지 않는다.':'…N\'arrête pas. La déesse n\'attend pas.',
'패턴이 바뀐다. 거리를 둬.':'Le schéma change. Garde tes distances.',
'미쳐가고 있어. 광폭화다.':'Il devient fou. Berserk.',
'마지막이야! 끝장내!':'Dernière phase ! Termine-le !',
'…끝났다. 다음으로.':'…C\'est fini. Au suivant.',
'다 잡았다! 포탈 어딨어?':'Tous éliminés ! Où est le portail ?',
'근육으로 만든 빌드군. 베고 부숴.':'Build force. Taille et brise.',
'활을 쥐었군. 거리를 둬.':'Arc en main. Garde tes distances.',
'마법사군. MP 관리부터 배워라.':'Mage. Apprends à gérer le MP d\'abord.',
'운에 기댄 빌드군. …드롭은 좋겠어.':'Build chance. ...Au moins les drops seront bons.',
'…VIT가 너무 낮아. 한 방에 죽는다.':'…VIT trop bas. Tu meurs d\'un seul coup.',
'다 찍으면 다 약해진다. 하나만 골라.':'Tout maxer et tu es faible partout. Choisis-en un.',
'…3단. 적이 강해져. 정신 차려.':'…Étape 3. Ennemis plus forts. Concentre-toi.',
'5단이다. …너도 강해졌단 뜻이야.':'Étape 5. ...Ça veut dire que tu as aussi grandi.',
'…7단. 아직 살아있단 게 신기하군.':'…Étape 7. Encore en vie. Surprenant.',
'10단. …너는 이제 인간이 아니야.':'Étape 10. ...Tu n\'es plus humain.',
'…일반으로 내려왔군. 가끔은 쉬어가야지.':'…Retour au Normal. Parfois il faut une pause.',
'…이게 진짜 패링이야.':'…C\'est une vraie parade.',
'…피가 묻기 시작했군.':'…Le sang commence à couler.',
'100. 너는 인간이 아니야.':'100. Tu n\'es pas humain.',
'…피 흘리며 베는군.':'…Coupe à travers le sang.',
'빨간콩이 푸르게 변했다. 그게 너의 무기야.':'Le noyau rouge est devenu bleu. C\'est ton arme.',
'무지개를 받아쳤군. 그건 진짜 어렵다.':'Tu as paré un arc-en-ciel. C\'est vraiment difficile.',
'…너무 빨라. 닿기 직전에 눌러.':'…Trop rapide. Appuie juste avant le contact.',
'악의가 가득 찼다. 풀어내.':'La Malveillance est pleine. Libère-la.',
'작살이 살을 뚫었어. 끌고 와.':'Le harpon a percé la chair. Tire-le.',
'…풀차지군. 멀리 던져버려.':'…Charge complète. Lance-le loin.',
'…빈틈을 그대로 빠져나갔다.':'…A filé directement dans la brèche.',
'…일반 잡몹이 아니야. 모디파이어 붙었군.':'…Pas un ennemi ordinaire. Il a un modificateur.',
'엘리트 하나 처리.':'Un élite éliminé.',
'…큰 놈이다. 일반 잡몹 정리부터.':'…Grand ennemi. Élimine les normaux d\'abord.',
'미니보스 처리. 다음 길로.':'Mini-boss éliminé. Au prochain chemin.',
'한 번에 다섯. 깔끔해.':'Cinq d\'un coup. Propre.',
'100강. 이제 뭔가 다르게 보이는군.':'+100. Les choses semblent différentes maintenant.',
'…운이 없는 날이야.':'…Pas de chance aujourd\'hui.',
'…전설이다. 이런 건 처음 본다.':'…Légendaire. Jamais vu ça.',
'…죽었다 살아났네. 여신은 너를 포기 안 했어.':'…Mort et revenu. La déesse n\'a pas abandonné.',
'…또야? 패턴 좀 외워!':'…Encore ? Apprends le schéma !',
'…한 번도 안 죽고. 그건 진짜 실력이야.':'…Jamais mort. C\'est du vrai talent.',
'…ACT1을 끝냈다. 진짜 시작은 여기서부터야.':'…AKT1 terminé. Le vrai début commence ici.',
'모든 보스를 무너뜨렸다. 너는 지옥의 일부야.':'Tous les boss sont tombés. Tu fais partie de l\'enfer.',
'…30초. 너 진짜 미쳤구나.':'…30 secondes. Tu es vraiment fou.',
'…빠르군. 효율적이야.':'…Rapide. Efficace.',
'신기록이다.':'Nouveau record.',
'탭 장비창을 열어봐.':'Ouvre l\'équipement avec TAB.',
'데미지 부족하면 무기 강화!':'Pas assez de dégâts ? Améliore ton arme !',
// --- Loading screen ---
'불러오는 중...':'Chargement...',
'로딩중...':'Chargement...',
'맵과 몬스터 불러오는 중...':'Chargement de la carte et des monstres...',
'기본 데이터 준비 중...':'Préparation des données de base...',
'저장 데이터 불러오는 중...':'Chargement de la sauvegarde...',
'몬스터 스킨 로딩...':'Chargement des skins de monstres...',
'맵과 몬스터 생성 중...':'Génération de la carte et des monstres...',
'맵 에셋 로딩...':'Chargement des ressources de la carte...',
'맵 환경 준비 중...':'Préparation de l\'environnement de la carte...',
'주변 청크 준비 중...':'Préparation des chunks voisins...',
'맵 캐시 생성 중...':'Construction du cache de la carte...',
'미니맵 빌드 중...':'Construction de la minicarte...',
// Phase 28
' 으로 탈출!':' pour s\'échapper !',
'100명?! 미쳤어!':'100 ennemis ?! C\'est fou !',
'10단 최고난이도! 너 진짜 광기야!':'Difficulté 10 au max ! T\'es complètement fou !',
'1분 안에 클리어! 빠르네!':'Niveau terminé en 1 min ! Si rapide !',
'30초!! 스피드런 가능해!':'30 secondes !! Potentiel de speedrun !',
'3단! 보상도 좋아지지만 죽기 쉬워!':'Diff 3 ! Meilleures récompenses mais plus facile de mourir !',
'50명! 학살자야!':'50 ennemis ! T\'es un massacreur !',
'5단!! 진짜 게이머 인증!':'Diff 5 !! Vrai gamer certifié !',
'7단!! 다른 사람들 이 정도 못 와!':'Diff 7 !! Les autres n\'arrivent pas aussi loin !',
'ACT1 완주! 우리가 진짜 해냈어!':'ACT1 terminé ! On l\'a vraiment fait !',
'Ctrl 얼음보주로 탈출하라.':'Ctrl — échappez avec l\'Orbe de Glace.',
'Ctrl 유령걸음으로 탈출하라.':'Ctrl — échappez avec le Pas Fantôme.',
'C키! 패시브 강해져!':'Touche C ! Les passifs deviennent plus forts !',
'DEX 빌드! 거리에서 패고, 추적탄 좋아!':'Build DEX ! Frappez à distance, les tirs guidés sont excellents !',
'E로 마력공격을 해봐!':'Essayez l\'attaque magique avec E !',
'G 눌러서 대장간 가봐!':'Appuyez sur G pour visiter la forge !',
'G키 대장간. 강화 안 하면 계속 죽어.':'G — forge. Sans améliorations, vous continuerez à mourir.',
'HP 70%! 조심해!':'HP 70 % ! Faites attention !',
'INT 빌드! 빔이랑 폭발 마법! MP 잘 봐!':'Build INT ! Rayons et magie explosive ! Surveillez votre PM !',
'LCK 높아! 레어 드롭률 미친 거 알지?':'CHC élevé ! Vous savez que les taux de drop sont fous, non ?',
'L로 어디에 뭘 넣을지 골라!':'Appuyez sur L pour choisir ce qui va dans chaque emplacement !',
'MP 부족! 평타로 패면서 회복해!':'PM faible ! Frappez avec des attaques basiques pour récupérer !',
'ST 없으면 스킬 못 써!':'Sans ST, pas de compétences !',
'STR 빌드! 회전참, 회오리, 광역기 추천!':'Build FOR ! Coup tournoyant, tourbillon, AoE recommandé !',
'VIT 좀 찍어! HP 너무 적어!':'Ajoutez de la VIT ! Les PV sont bien trop bas !',
'Z 누르면 대박! 쿨타임 길어!':'Appuyez sur Z pour le grand truc ! Mais le temps de recharge est long !',
'…고기 냄새. 싫진 않네.':'…Odeur de sang. Pas désagréable.',
'…둘러싸이면 끝이야.':'…Être encerclé et c\'est fini.',
'…말은 못해.':'…Je ne peux pas parler.',
'…버리기 아까운 건 창고에.':'…Ce qui vaut la peine d\'être gardé va au stockage.',
'…빈틈을 노려.':'…Guettez les ouvertures.',
'…설정을 확인해.':'…Vérifiez vos paramètres.',
'…슬롯을 채워. 빈 손은 죽음이다.':'…Remplissez vos emplacements. Les mains vides signifient la mort.',
'…아직 살아있네. 좌클릭으로 저것들 쳐봐.':'…Encore en vie. Essayez de les frapper avec le clic gauche.',
'…운이 좋았을 뿐이야. 아마.':'…Juste de la chance. Probablement.',
'…치는 건 할 줄 아네. 피하는 건?':'…Vous savez frapper. Et esquiver ?',
'…힘을 골라라. 전부 가질 순 없다.':'…Choisissez votre force. On ne peut pas tout avoir.',
'골고루 안 돼! 하나로 밀어!':'Ne distribuez pas les stats ! Misez sur une seule !',
'그로기 터지면 1.5배!':'Étourdi = 1,5x de dégâts !',
'길이 열렸다.':'Le chemin est ouvert.',
'나머진 전부 우클릭 패링 가능!':'Tout le reste peut être paré avec le clic droit !',
'나머진 전부 우클릭!':'Tout le reste — clic droit !',
'다섯 번 연속! 내가 본 인간 중 최고!':'Cinq de suite ! Le meilleur humain que j\'aie jamais vu !',
'다음엔 죽지 마!':'Ne mourez pas la prochaine fois !',
'더블탭 전격이동으로 탈출하라.':'Double appui pour esquiver et s\'échapper.',
'소환수 왔어! 먼저 처리해야 해!':'Des invocations arrivent ! Éliminez-les d\'abord !',
'스킬 없으면 방향키 연타뿐이야.':'Pas de compétence ? Martelez juste les touches directionnelles.',
'신기록!! 스트리머한테 보내!':'Nouveau record !! Envoyez-le à un streamer !',
'아이템 넘쳐! 우리가 주워줄게!':'Sac plein ! Nous ramasserons les objets pour vous !',
'안 죽고 깼어! 진짜 천재 맞네!':'Terminé sans mourir ! Vrai génie !',
'앞으로 가자~':'Avançons~',
'우리가 해냈어! 다음 챕터 가자!':'On l\'a fait ! Au prochain chapitre !',
'일반 모드! 편하게 즐기자!':'Mode normal ! Profitons tranquillement !',
'자원이 반이다. F키로 회복해.':'Ressources à moitié. Appuyez sur F pour récupérer.',
'잡힌다! 옆으로 빠져!':'En train d\'être attrapé ! Bougez sur le côté !',
'장비 분해해! 쓰레기도 악의!':'Démantèlez l\'équipement ! Même les déchets donnent de la malveillance !',
'전부 다 잡았어! 우리가 지옥의 왕이야!':'On les a tous eus ! Nous sommes les rois de l\'enfer !',
'좋은 거 나왔다! TAB!':'Bon butin tombé ! TAB !',
'죽기 직전에 죽이다니! 멋져!':'Tuer juste avant de mourir ! Incroyable !',
'체력 반 남았어! 물약 마실 타이밍!':'Moitié des PV restants ! Le moment de boire une potion !',
'큰 거 온다! 도망쳐!':'Grande attaque entrante ! Fuyez !',
'패링으로 돌려주고, Q 보호막도 써!':'Parez pour refléter, et utilisez aussi le bouclier Q !',
'패턴이 빨라졌어!':'Les schémas se sont accélérés !',
'한 대만 맞아도 죽어! 패링이든 회피든!!':'Un coup et vous mourez ! Parez ou esquivez !!',
'한 방이면 죽어! 도망쳐!!':'Un coup tue ! Fuyez !!',
'화염엔 빙결! 암전엔 암흑!':'Feu → givre ! Vide → ombre !',
'👻 유령총!':'👻 Pistolet Fantôme!',
'기절! ':'Étourdi! ',
'⏳⚡ 시간걸음!':'⏳⚡ Pas dans le Temps!',
'블룸 효과':'Effet Bloom',
'잔상 트레일':'Traîne d\'image rémanente',
'슬래시 이펙트':'Effet de taille',
'후처리 효과':'Post-traitement',
'사망 이펙트':'Effet de mort',
'동적 조명':'Éclairage dynamique',
'횃불 조명 (어둠)':'Lumière torche (obscurité)',
'앰비언트 파티클':'Particules d\'ambiance',
'안개 효과':'Effet de brouillard',
'필름 그레인':'Grain cinématographique',
'캐릭터 외곽선':'Contour du personnage',
'리롤':'Relancer',
'물약':'Potion',
'으로 탈출!':'pour s\'échapper!',
'Shift 작살':'Shift Harpon',
'더블탭 전격이동':'Double appui — Dash éclair',
'Ctrl 유령걸음':'Ctrl Pas fantôme',
'Ctrl 얼음보주':'Ctrl Orbe de glace',
'🔴화염→빙결 2배 | 🔵빙결→화염 2배 | ⚪물리=중립 | 악마 처치 시 악의 영혼 드롭':'🔴Feu→Glace 2× | 🔵Glace→Feu 2× | ⚪Phys=Neutre | Tuez des démons pour des âmes de malice',
};

const _FR_PFX={'녹슨':'Rouillé','강철':'Acier','흑요석':'Obsidienne','미스릴':'Mithril','심판의':'du Jugement','천벌의':'du Châtiment Divin','파멸의':'de Destruction',
'불꽃':'Flamme','화염':'Infernal','염화':'Feu Infernal','지옥불':'Brasier Infernal','지옥화':'Brasier Infernal','지옥':'Brasier Infernal','멸화의':'d\'Annihilation',
'냉기':'Givre','빙결':'Gelé','빙하':'Glaciaire','서리의':'de Frimas','서리':'Frimas','영겁빙':'Glace Éternelle',
'그림자':'Ombre','암흑':'Ténébreux','심연':'Abyssal','나락의':'des Abîmes','나락':'Abîmes','무간의':'du Néant',
'전기':'Étincelle','낙뢰':'Tonnerre','암전':'Foudre','뇌신의':'du Dieu-Foudre','뇌신':'Dieu-Foudre','만뢰의':'Myriade de Foudre',
'축복':'Béni','성광':'Lumière Sacrée','신성':'Sacré','천사의':'Angélique','신벌의':'du Châtiment Divin',
'낡은':'Usé','천':'Tissu','가죽':'Cuir','강철사':'Fil d\'Acier','은':'Argent','은사':'Fil d\'Argent','화염의':'Infernal','빙결의':'Gelé','암흑의':'Ténébreux','암전의':'de Foudre'};
const _FR_BASE={'대검':'Espadon','석궁':'Arbalète','연사석궁':'Répéteur','마력석궁':'Arbalète Arcanique',
'견갑':'Garde','대견갑':'Grande Garde','전투화':'Bottes de Combat','갑옷':'Armure','갑주':'Armure',
'왕관':'Couronne','장갑':'Gants','건틀릿':'Gantelets','바지':'Pantalon','각반':'Jambières',
'허리띠':'Ceinture','벨트':'Ceinture','부적':'Talisman','목걸이':'Collier','반지':'Anneau',
'망토':'Cape','팔찌':'Bracelet','귀걸이':'Boucle d\'Oreille'};
