// 지옥의 길 — Tiếng Việt (vi)
const _VI={
'💫 암전폭류':'💫 Sét Bùng Phát','⚡ 암전나선':'⚡ Sét Helix','🌋 지진폭풍':'🌋 Bão Chấn','🔥 회전기폭':'🔥 Xoáy Nổ','⚔ 기동:섬멸':'⚔ Drive:Tiêu Diệt','⚔ 기동:칼날개':'⚔ Drive:Lưỡi','⚡ 기동:전폭':'⚡ Drive:Tấn công','🌀 기동:파쇄':'🌀 Drive:Nghiền','🌀 기동:기습':'🌀 Drive:Phục kích','💫 →좌클 통합':'💫 →Gộp LMB','⚡ →좌클 통합':'⚡ →Gộp LMB','🎯 추적암전':'🎯 Sét Truy Vết','☆ 만화광선':'☆ Tia Phát Quang','⏳⚡ 시간걸음':'⏳⚡ Bước Thời Gian','SSAA 슈퍼샘플':'SSAA Siêu Lấy Mẫu','끄기 (1x)':'Tắt (1x)','커서 크기':'Kích thước con trỏ','다크 판타지 전사':'Chiến binh dark fantasy','거대검+검은 갑옷':'Đại kiếm + Giáp đen',
'…지옥문이 열렸다. 안에서 그것이 기다리고 있어.':"...Cổng Địa Ngục đã mở. Nó đang chờ ngươi bên trong.",
'문 열렸어! 이제 보스 잡으러 가자!':"Cổng mở rồi! Đi giết boss thôi!",
'\u26e7 시전...':'⛧ Đang niệm...',
'…죽기 직전이다. 패링해. 피를 채워.':'...Sắp chết. Đỡ đi. Hồi HP.',
'⚔🐍 독사해방!':'⚔🐍 Giải Phóng Độc Xà!',
'⚠패링 실패!':'⚠Đỡ thất bại!',
'⚡ 뇌전추격자!':'⚡ Truy Lôi Giả!',
'⚡회피 반격!':'⚡Phản Đòn Né!',
'✦ 유니크 공유!':'✦ Chia Sẻ Unique!',
'✦ 유니크 부활!':'✦ Hồi Sinh Unique!',
'❄유니크 빙결!':'❄Đóng Băng Unique!',
'닫기 [C]':'Đóng [C]',
'닫기 [V]':'Đóng [V]',
'대왕치기 (분노폭발, 광역 기절)':'Cú Đập Khổng Lồ (bùng nộ, choáng diện rộng)',
'물리방패의':'Khiên Vật Lý',
'사슬 착지 타격 수만큼 데미지 +20% 중첩(최대읐5)':'Đòn tiếp đất chuỗi: +20% sát thương (tối đa 5)',
'성능 등급:':'Cấp hiệu năng:',
'쉴드 있으면 HP 안 닳아! 쉴드 먼저 깨야 해!':'Còn khiên thì HP an toàn! Phá khiên trước!',
'쉴드가 있는 적은 쉴드부터 깨야 HP가 깎여!':'Kẻ địch có khiên — phá khiên trước mới trừ được HP!',
'쉴드는 추가 HP다. 쉴드부터 깎인다.':'Khiên là HP cộng thêm. Khiên bị trừ trước.',
'쉴드는 추가 HP야. 모든 공격이 쉴드를 먼저 깎아!':'Khiên là HP cộng thêm. Mọi đòn đánh trúng khiên trước!',
'얼음송곳':'Gai Băng',
'한 방이면 죽어! 패링으로 HP 채워!!':'Một đòn là chết! Đỡ để hồi HP!!',
'👻 투명화!':'👻 Tàng Hình!',
'👿악의+':'👿ác ý+',
'💡 Q로 보호막 발동 — 기본 흡수율 30%, 패링 성공 시 HP/ST/MP/기동게이지 회복':'💡 Q để bật khiên — hấp thụ 30%, đỡ thành công hồi HP/ST/MP/Thanh cơ động',
'💥유니크 폭발!':'💥Nổ Unique!',
'🔥피격→분노!':'🔥Trúng→Phẫn Nộ!',
'🔨방어무시!':'🔨Bỏ Qua Phòng Thủ!',
'🛡️쉴드+15%':'🛡️Khiên+15%',
'썩은 숲':'Rừng Mục Nát',
'숲의 감시자':'Lính Canh Rừng',
'독버섯 거인':'Khổng Lồ Nấm Độc',
'숲의 사냥꾼':'Thợ Săn Rừng',
'숲의 기생수':'Thú Ký Sinh',
'1장 — 썩은 숲':'CH1 — Rừng Mục Nát',
'2장 — 벌레굴':'CH2 — Hang Giun',
'3장 — 얼음굴':'CH3 — Hang Băng',
'4장 — 고통의 화염지대':'CH4 — Vùng Lửa',
'5장 — 지옥의 군단':'CH5 — Quân Đoàn Địa Ngục',
'6장 — 사도의 마굴':'CH6 — Hang Tông Đồ',
'7장 — 지옥성':'CH7 — Thành Địa Ngục',
'탈출!':'Thoát!',
'처치':'hạ gục',
'경험치':'KN',
'최대콤보':'Combo Tối Đa',
'일어나. 여신이 널 여기 보낸 건 죽으라고가 아니야.':'Dậy đi. Nữ thần không gửi ngươi đến đây để chết.',
'좋아, 감각이 있군. 계속 쳐!':'Tốt, có bản năng đấy. Tiếp tục chém!',
'Shift를 눌러. 사슬이다. 땅에 꽂아서 끌려가!':'Nhấn Shift. Đó là lao móc. Cắm và lướt!',
'사슬로 끌려가는 중엔 무적이다. 위험할 때 쓰면 좋아.':'Bất tử khi lao kéo. Dùng lúc nguy hiểm.',
'...아파? 당연하지. 여긴 지옥이야.':'...Đau à? Dĩ nhiên. Đây là địa ngục.',
'Q를 눌러! 악의로 보호막을 만들 수 있다.':'Nhấn Q! Tạo khiên bằng ác ý.',
'보호막 없이 버틸 생각은 버려.':'Quên sống sót mà không có khiên đi.',
'우클릭이 패링이다. 적 공격이 닿기 직전에 눌러!':'Chuột phải để đỡ. Nhấn ngay trước khi địch đánh!',
'못 하겠으면 때려. 안 죽으면 그만이야.':'Không đỡ được? Cứ đánh. Không chết là đủ.',
'됐어! 감 잡았구나.':'Được rồi! Đang quen tay đấy.',
'하나 죽었군.':'Một con gục.',
'유령쇠뇌야. 인사해.':'Đó là nỏ ma. Chào nó đi.',
'빨간 탄을 무서워하지 마. 악의가 강하다.':'Đừng sợ đạn đỏ. Ác ý rất mạnh.',
'패링으로 돌려주고, Q 보호막도 써! 악의를 잘 굴려!':'Đỡ trả, dùng khiên Q! Làm chủ ác ý!',
'무지개빛은 패링 불가! 피해!':'Đạn cầu vồng không đỡ được! Né!',
'피가 새고 있다. Shift. 빠져.':'Đang chảy máu. Shift. Thoát ra.',
'물약 있잖아! 숫자키!':'Có thuốc mà! Phím số!',
'우클릭. 적 손목이 꺾일 때 쳐.':'Chuột phải. Đánh khi cổ tay chúng gập.',
'빨간 탄은 악의 덩어리다. 쳐내서 이용해.':'Đạn đỏ là cục ác ý. Đỡ và tận dụng.',
'무지개빛만 피하면 돼! 나머지는 다 패링!':'Chỉ cần né cầu vồng! Đỡ hết phần còn lại!',
'Q 보호막도 패링이 가능해!':'Khiên Q cũng đỡ được!',
'위험해! 쉬프트 사슬기동으로 피해!!':'Nguy hiểm! Shift lướt xích thoát!!',
'쉬프트! 사슬기동은 이동기야! 끌려가면서 무적이라고!':'Shift! Lướt xích là di chuyển! Bất tử khi bị kéo!',
'스킬포인트가 쌓였어! K 눌러서 스킬 배우자!':'Điểm kỹ năng sẵn! Nhấn K học kỹ năng!',
'속성을 읽어. 약점을 찌르면 두 배로 썩는다.':'Đọc nguyên tố. Đánh điểm yếu gấp đôi sát thương.',
'K를 눌러봐! 스킬을 배울 수 있어!':'Nhấn K! Học kỹ năng!',
'J 눌러서 능력치 찍어! 패시브도 있어~':'Nhấn C xem chỉ số! Cả nội tại~',
'G를 눌러. 대장간에서 장비를 강화할 수 있다.':'Nhấn G. Nâng cấp trang bị ở lò rèn.',
'F키도 스킬 슬롯이야! 스킬 많으면 L로 배정해봐~':'Phím F cũng là ô kỹ năng! Dùng L để gán~',
'Z. 필살기다. 아껴 써라.':'Z. Tuyệt chiêu. Dùng khôn ngoan.',
'L-CTRL로 유령걸음이나 얼음보주 쓸 수 있어!':'L-CTRL để Bước Ma hoặc Cầu Băng!',
'L을 눌러. 스킬 슬롯을 정리해야 한다.':'Nhấn L. Sắp xếp ô kỹ năng.',
'가방 터지겠다! N 눌러서 창고에 넣어둬!':'Túi sắp vỡ! Nhấn N cất kho!',
'ESC로 설정 열 수 있어! 난이도 바꾸기, 자동물약 조절~':'ESC mở cài đặt! Độ khó, tự dùng thuốc~',
'...아직 살아있네. 좌클릭으로 저것들 쳐봐.':'...Vẫn sống. Thử đánh bọn đó bằng chuột trái.',
'...치는 건 할 줄 아네. 피하는 건?':'...Đánh được. Nhưng né được không?',
'흥, 사슬 못 맞추면 헛수고야.':'Hừ, trượt lao thì phí.',
'...운이 좋았을 뿐이야. 아마.':'...Chỉ may thôi. Chắc vậy.',
'...고기 냄새. 싫진 않네.':'...Ngửi như thịt. Không tệ.',
'...말은 못해.':'...Nó không biết nói.',
'예쁘다고 만지면 죽어.':'Chạm vì đẹp à? Chết đấy.',
'사슬 던져! 끌려가면 무적이야!':'Phóng lao! Bất tử khi bị kéo!',
'...마시든 말든. 네 목숨이니까.':'...Uống hay không. Đời ngươi mà.',
'그게 패링이야! 타이밍이 전부야~':'Đó là đỡ! Thời điểm là tất cả~',
'화염엔 빙결! 암전엔 암흑! 기억해!':'Lửa khắc Băng! Sét khắc Bóng! Nhớ nhé!',
'...얼어붙은 놈은 오래 안 간다.':'...Bị đóng băng không trụ lâu.',
'얼었어! 빙결 중 1.5배야!':'Đóng băng! x1.5 sát thương!',
'...힘을 골라라. 전부 가질 순 없다.':'...Chọn sức mạnh. Không thể có hết.',
'스탯을 올려. 살고 싶으면.':'Nâng chỉ số. Nếu muốn sống.',
'좋은 장비는 강화해야 진짜 힘을 발휘해!':'Trang bị tốt cần nâng cấp!',
'...슬롯을 채워. 빈 손은 죽음이다.':'...Điền ô. Tay trống là chết.',
'Z 누르면 대박! 쿨타임 길어서 타이밍 봐야 해!':'Nhấn Z sát thương khủng! Hồi lâu!',
'Ctrl. 위기에 쓸 카드가 하나 늘었군.':'Ctrl. Thêm lá bài khẩn cấp.',
'스킬이 많아졌네~ L로 어디에 뭘 넣을지 골라!':'Nhiều kỹ năng quá~ Dùng L gán!',
'...버리기 아까운 건 창고에.':'...Cất gì quý quá.',
'...살아남은 것만으로도 대단하군. 설정을 확인해.':'...Sống sót là giỏi. Kiểm tra cài đặt.',
'MP 부족!':'Không đủ MP!',
'ST 부족!':'Không đủ ST!',
'악의 부족!':'Không đủ Ác Ý!',
'충전 중...':'Đang tích...',
'캔슬':'Hủy',
'아이템 선택 필요':'Chọn vật phẩm',
'악의 소진...':'Ác ý cạn...',
'비문 발견...':'Phát hiện bia ký...',
'HP물약!':'Thuốc HP!',
'HP물약 +1':'Thuốc HP +1',
'HP물약 +2':'Thuốc HP +2',
'HP/MP/ST 회복!':'Hồi HP/MP/ST!',
'보물상자 개봉!':'Mở rương!',
'익사!':'Chết đuối!',
'피웅덩이!':'Vũng máu!',
'독혈!':'Máu độc!',
'잡힘!':'Bị tóm!',
'콤보 종료':'Kết Combo',
'빙결!':'Đóng Băng!',
'화상!':'Bỏng!',
'독!':'Độc!',
'감전!':'Giật!',
'기절!':'Choáng!',
'봉인됨!':'Phong Ấn!',
'관통!':'Xuyên!',
'기검참':'Chém Khí',
'악의구':'Cầu Ác Ý',
'회전참':'Toàn Phong',
'기폭팔':'Kích Nổ',
'칼등 처내기':'Đỡ Kiếm',
'만화방창':'Mưa Kim',
'멸살광선':'Tia Hủy Diệt',
'원소추적탄':'Đạn Nguyên Tố',
'악의 보호자':'Hộ Vệ Ác Ý',
'악의 사냥':'Săn Ác Ý',
'폭풍소환':'Triệu Hồi Xoáy',
'해골무덤':'Mộ Xương',
'\u{1F47B} 유령!':'\u{1F47B} Ma!',
'\u{1F9B4} 해골무덤!':'\u{1F9B4} Mộ Xương!',
'신성폭발':'Nổ Thánh',
'블랙':'Hắc Tinh',
'용암소환':'Triệu Hồi Dung Nham',
'처형':'Hành Hình',
'악마화 부활':'Hồi Sinh Ma',
'붉은꽃':'Hoa Đỏ Thẫm',
'얼음보주':'Cầu Băng',
'뇌전걸음':'Bước Ma',
'만화방창 II':'Mưa Kim II',
'마력연사':'Loạn Xạ Pháp',
'마력광선':'Tia Laser Cung',
'업화선':'Tia Hỏa Ngục',
'지옥진':'Trận Địa Ngục',
'폭독칼날':'Kiếm Dịch',
'악의폭풍':'Bão Ác Ý',
'악의기둥':'Trụ Bóng Tối',
'회복의 영역':'Lĩnh Vực Thánh',
'구속의 영역':'Lĩnh Vực Trói',
'아이스스톰':'Bão Băng',
'대왕치기':'Đập Khổng Lồ',
'대왕치기 2':'Đập Khổng Lồ II',
'기동불꽃':'Chuỗi Lửa',
'기동파괴':'Chuỗi Nghiền',
'기동칼날개':'Chuỗi Cánh Kiếm',
'평화의보호':'Khiên Hòa Bình',
'참회':'Sám hối',
'칼등날개':'Cánh Khiên',
'폭산탄':'Đạn Nổ',
'파쇄의 영역':'Lĩnh Vực Vỡ',
'침식의 영역':'Lĩnh Vực Ăn Mòn',
'관통의 영역':'Lĩnh Vực Xuyên',
'부활의 영역':'Lĩnh Vực Hồi Sinh',
'가시덫':'Bẫy Gai',
'푸른비':'Mưa Xanh',
'버스트루프':'Vòng Nổ',
'유령 허수아비':'Bù Nhìn Ma',
'폭발 허수아비':'Bù Nhìn Nổ',
'공성쇠뇌':'Nỏ Công Thành',
'사슬기동:충돌':'Lướt Xích: Va Chạm',
'사슬기동:화염':'Lướt Xích: Lửa',
'전격이동':'Bước Chớp',
'기동칼날개!':'Cánh Kiếm!',
'기동불꽃!':'Chuỗi Lửa!',
'기동파괴!':'Chuỗi Nghiền!',
'사슬이동:강화!':'Lướt Xích!',
'사슬기동:화염!':'Xích Lửa!',
'사슬!':'Xích Móc!',
'진입!':'Vào!',
'레인라이트닝!':'Mưa Sét!',
'마력연사!':'Loạn Xạ Pháp!',
'🔷 마력광선!':'🔷 Arc Laser!',
'광선 해제':'Tắt Laser',
'MP 부족 — 광선 해제':'Hết MP — Tắt Laser',
'집중...':'Tập trung...',
'시전...':'Đang niệm...',
'만화방창!':'Mưa Kim!',
'바늘출!':'Kim Nổ!',
'칼날!':'Kiếm!',
'착지!':'Tiếp đất!',
'체간삭감!':'Thăng Bằng Break!',
'기동전폭 준비!':'Chuỗi Nổ Sẵn Sàng!',
'기동불꽃 준비!':'Chuỗi Lửa Sẵn Sàng!',
'기동파괴 준비!':'Chuỗi Nghiền Sẵn Sàng!',
'유령불꽃 ON':'Lửa Ma BẬT',
'유령불꽃 OFF':'Lửa Ma TẮT',
'기동칼날개 AUTO ON':'Cánh Kiếm TỰ ĐỘNG BẬT',
'기동칼날개 AUTO OFF':'Cánh Kiếm TỰ ĐỘNG TẮT',
'자동 버스트!':'Nổ Tự Động!',
'연사 해제':'Tắt Bắn Nhanh',
'당기기 모드':'Chế Độ Kéo',
'밀어내기 모드':'Chế Độ Đẩy',
'날개치기':'Đòn Cánh',
'처내기':'Đỡ đòn',
'Shift: 사슬 발사 → 끌려감':'Shift: Phóng lao → kéo',
'Shift: 화염길+화상':'Shift: Vệt lửa+bỏng',
'CT: 전류변신+뇌전걸음 (쿨4초)':'CT: Dạng sét+Bước Ma (hồi 4g)',
'CT: 방어구체+빙결 (재입력: 파쇄)':'CT: Cầu băng+đóng băng (nhấn lại: vỡ)',
'근접':'Cận Chiến',
'견갑':'Hộ Vệ',
'사슬':'Xích Móc',
'마법':'Pháp Thuật',
'보막':'Khiên',
'유령':'Ma',
'스킬':'Kỹ Năng',
'대장':'Lò rèn',
'인벤':'Túi đồ',
'인벤토리':'Kho Đồ',
'복수의 대장간':'Lò Rèn Báo Thù',
'패시브 스킬':'Kỹ Năng Nội Tại',
'전투 스킬':'Kỹ Năng Chiến Đấu',
'캐릭터 선택':'Chọn Nhân Vật',
'물리':'Vật Lý',
'화염':'Lửa',
'빙결':'Đóng Băng',
'암흑':'Bóng Tối',
'암전':'Sét',
'신성':'Thánh',
'대지':'Đất',
'힘':'Sức Mạnh',
'민첩':'Nhanh Nhẹn',
'지능':'Trí tuệ',
'행운':'May Mắn',
'맹공':'Mãnh Công',
'철벽':'Kiên Cường',
'돌파':'Đột Phá',
'반격':'Trả Thù',
'마력폭주':'Cuồng Pháp',
'정밀사격':'Bắn Chính Xác',
'수호':'Hộ Vệ',
'수호신':'Thần Hộ Vệ',
'회복력':'Hồi Phục',
'급소':'Đòn Hiểm',
'약탈':'Cướp Đoạt',
'관통':'Xuyên Thấu',
'마력회복':'Hồi Phục Mana',
'쇠뇌력':'Tinh Thông Nỏ',
'광전사':'Cuồng chiến',
'추적자':'Truy Vết',
'물리관통':'Xuyên Vật Lý',
'마법관통':'Xuyên Pháp',
'녹슨 대검':'Đại Kiếm Gỉ',
'강철 대검':'Đại Kiếm Thép',
'흑요석 대검':'Đại Kiếm Hắc Diện',
'낡은 석궁':'Nỏ Cũ',
'강철 석궁':'Nỏ Thép',
'흑요석 석궁':'Nỏ Hắc Diện',
'대검':'Đại Kiếm',
'석궁':'Nỏ',
'연사석궁':'Nỏ Liên Thanh',
'마력석궁':'Nỏ Ma Lực',
'악의 추출':'Trích Xuất Ác Ý',
'악의':'Ác ý',
'필살기':'Tuyệt Chiêu',
'필살기 해제':'Hủy Tuyệt Chiêu',
'이전':'Chuyển',
'강화':'Cường Hóa',
'개봉!':'Đã Mở!',
'여신의 가호':'Phước Nữ Thần',
'과부하!':'Quá Tải!',
'맹독의':'Kịch Độc',
'불꽃의':'Bùng Cháy',
'냉기의':'Giá Buốt',
'번개의':'Điện',
'암흑의':'Bị Nguyền',
'관통의':'Xuyên',
'광폭의':'Cuồng Nộ',
'파쇄의':'Vỡ Nát',
'연쇄의':'Liên Hoàn',
'학살의':'Giết Chóc',
'폭발의':'Nổ',
'집중의':'Tập Trung',
'쾌속의':'Nhanh',
'패리의':'Hất',
'추적자의':'Kẻ Rình',
'사슬의':'Xích Móc',
'궁극의':'Tối Thượng',
'집중력의':'Chú Tâm',
'강인의':'Kiên Cường',
'수호의':'Hộ Vệ',
'활력의':'Sống Còn',
'신속의':'Tăng Tốc',
'화염수호':'Hộ Vệ Lửa',
'빙결수호':'Hộ Vệ Băng',
'암전수호':'Hộ Vệ Sét',
'암흑수호':'Hộ Vệ Bóng Tối',
'독수호':'Hộ Vệ Độc',
'전원소수호':'Hộ Vệ Toàn Bộ',
'강철의':'Bọc Thép',
'반사의':'Phản Chiếu',
'가시의':'Có Gai',
'흡수의':'Hấp Thụ',
'인내의':'Bền Bỉ',
'위기의':'Tuyệt Vọng',
'피격반격의':'Trả Đũa',
'패링폭발의':'Nổ Đỡ',
'스태거폭발의':'Nổ Loạng Choạng',
'원소전환의':'Chuyển Đổi',
'정화의':'Thanh Tẩy',
'불굴의':'Bất Khuất',
'부활의':'Hồi Sinh',
'약탈의':'Cướp Phá',
'경험의':'Dày Dạn',
'골드의':'Vàng',
'포션강화의':'Mãnh Liệt',
'사슬의':'Xiềng',
'진혼의':'Thánh Hóa',
'윤회의':'Tuần Hoàn',
'생명력의':'Mạnh Mẽ',
'재생의':'Tái Tạo',
'치유의':'Chữa Lành',
'마력의':'Huyền Bí',
'절약의':'Tiết Kiệm',
'영혼의':'Linh Hồn',
'예리한':'Sắc Bén',
'맹렬한':'Tàn Bạo',
'파멸의':'Tàn Phá',
'게임 설정':'Cài Đặt Trò Chơi',
'화면 흔들림':'Rung Màn Hình',
'파티클 양':'Số Lượng Hạt',
'효과음 볼륨':'Âm Lượng SFX',
'음악 볼륨':'Âm Lượng Nhạc',
'난이도':'Độ Khó',
'자동 물약':'Tự Dùng Thuốc',
'최소 줍기 등급':'Hạng Nhặt Tối Thiểu',
'최소 줍기 티어':'Cấp Nhặt Tối Thiểu',
'FPS 제한':'Giới Hạn FPS',
'해상도 스케일':'Tỷ Lệ Phân Giải',
'펫 자동수거':'Thu Thập Tự Động',
'화면 설정':'Cài Đặt Hiển Thị',
'화면 모드':'Chế Độ Hiển Thị',
'보스 AI 디버그':'Gỡ lỗi AI Trùm',
'유령불꽃 크기':'Kích Thước Lửa Ma',
'화면 명암':'Độ Sáng',
'유령 글로우':'Phát Sáng Ma',
'기동:칼날개 AUTO':'Cánh Kiếm TỰ ĐỘNG',
'일반':'Thường',
'어려움':'Khó',
'지옥':'Địa Ngục',
'이상':'trở lên',
'사용 안 함':'Tắt',
'창 모드':'Cửa Sổ',
'보더리스':'Không Viền',
'전체화면':'Toàn Màn Hình',
'설정':'Cài Đặt',
'조작 키 설정 (클릭하여 변경)':'Phím Tắt (Nhấn để Đổi)',
'좌클릭 무기 공격':'Chuột Trái Tấn Công',
'우클릭 탭 칼등 처내기':'Chuột Phải Đỡ Kiếm',
'우클릭 홀드 연속 처내기':'Giữ Chuột Phải Đỡ Liên Tục',
'SHIFT 사슬 발사':'SHIFT Phóng Xích',
'이동':'Di Chuyển',
'아이템 줍기':'Nhặt Vật Phẩm',
'능력치 (스탯/패시브)':'Chỉ Số (Chỉ Số/Nội Tại)',
'분해':'Tháo Dỡ',
'제작':'Chế Tạo',
'사망':'Chết',
'부활':'Hồi Sinh',
'로비로':'Về Sảnh',
'가방에 공간이 없습니다!':'Hết chỗ trong túi!',
'가방이 가득 찼습니다!':'Túi đầy!',
'창고가 가득 찼습니다!':'Kho đầy!',
'퀵슬롯이 가득 찼습니다!':'Ô nhanh đầy!',
'결정 주머니가 가득 찼습니다!':'Túi pha lê đầy!',
'결정 주머니 가득!':'Túi pha lê đầy!',
'악의가 부족합니다!':'Không đủ Ác Ý!',
'가방이 비어있습니다':'Túi trống',
'창고가 비어있습니다':'Kho trống',
'비어있음':'Trống',
'어픽스 없음':'Không có hậu tố',
'장착!':'Đã Trang Bị!',
'해제':'Đã Tháo',
'보관':'Gửi',
'꺼내기':'Rút',
'현재 장착':'Đang trang bị',
'없음 — 제작하세요!':'Không có — Chế tạo!',
'리셋할 포인트가 없습니다':'Không có điểm để đặt lại',
'키 설정 초기화 완료':'Đặt lại phím',
'제작 확률':'Tỷ lệ chế tạo',
'제작 비용':'Chi phí chế tạo',
'보유 악의':'Ác ý sở hữu',
'보스방':'Phòng Boss',
'안식처':'Nơi Ẩn Náu',
'회복':'Hồi Phục',
'점화':'Đốt',
'비석':'Bia đá',
'읽기':'Đọc',
'파괴':'Phá Hủy',
'제단':'Bàn thờ',
'기원':'Cầu Nguyện',
'잔해':'Đống Đổ Nát',
'열기':'Mở',
'문지기':'Người Gác Cổng',
'부활 판정 중...':'Đang phán xét hồi sinh...',
'기폭 준비!':'Sẵn sàng kích nổ!',
'탈출':'Thoát',
'연타':'Nhấn Liên Tục',
'추적암전':'Sét Truy Vết',
'만화광선':'Tia Phát Quang',
'최종 마법':'Pháp Thuật Cuối',
'감시중':'Quan Sát',
'대기':'Chờ',
'작동중':'Hoạt Động',
'설치 가능':'Có thể lắp',
'균열 임박!':'Sắp phá vỡ!',
'흡수 중...':'Đang hấp thụ...',
'흡수 완료 — 재입력으로 회수':'Xong — nhập lại để thu',
'화상':'Bỏng',
'당기기':'Kéo',
'밀어내기':'Đẩy',
'단계':'cấp',
'단':'cấp',
'습득!':'Đã Học!',
'리셋!':'Đặt lại!',
'세팅!':'Đã Gán!',
'회수':'Thu Hồi',
'합체 해제':'Hủy Hợp',
'리셋':'Đặt lại',
'환불':'Hoàn Trả',
'파트너 클릭!':'Nhấn đối tác!',
'SP부족!':'Cần SP!',
'같은 보석 스킬 습득 시 합체 가능':'Có thể hợp khi học cùng kỹ năng đá',
'펼쳐서 초기화':'Mở rộng để đặt lại',
'슬롯:':'Ô:',
'남은 SP':'SP Còn Lại',
'맞아서 사망':'Chết vì bị đánh',
'레벨':'Cấp',
'최대HP':'HP Tối Đa',
'방랑 기사':'Hiệp Sĩ Lang Thang',
'보물 악마':'Quỷ Kho Báu',
'거울의 사도':'Tông Đồ Gương',
'상인 악마':'Quỷ Thương Nhân',
'사슬의 죄수':'Tù Nhân Xiềng',
'시간의 사도':'Tông Đồ Thời Gian',
'탐욕의 사도':'Tông Đồ Tham Lam',
'저주받은 쌍둥이':'Song Sinh Bị Nguyền',
'차원 균열체':'Vết Nứt Chiều Không',
'죽음 그 자체':'Tử Thần',
'HP결정':'Pha Lê HP',
'ST결정':'Pha Lê ST',
'MP결정':'Pha Lê MP',
'ATK결정':'Pha Lê ATK',
'DEF결정':'Pha Lê DEF',
'속도결정':'Pha Lê Tốc Độ',
'크리결정':'Pha Lê Bạo',
'치명결정':'Pha Lê Sát Thương Bạo',
'화염결정':'Pha Lê Lửa',
'냉기결정':'Pha Lê Băng',
'암흑결정':'Pha Lê Bóng Tối',
'번개결정':'Pha Lê Sét',
'신성결정':'Pha Lê Thánh',
'생명결정':'Pha Lê Sinh Mệnh',
'기력결정':'Pha Lê Thể Lực',
'마력결정':'Pha Lê Mana',
'행운결정':'Pha Lê May Mắn',
'조각':'Mảnh',
'파편':'Mảnh Vỡ',
'순수결정':'Pha Lê Thuần',
'완전결정':'Pha Lê Hoàn Hảo',
'결정 주머니':'Túi Pha Lê',
'결정이 없습니다':'Không có pha lê',
'가루':'Bụi',
'전체':'Tất Cả',
'스탯':'Chỉ số',
'원소':'Hệ',
'유틸':'Tiện ích',
'현재':'Hiện Tại',
'최대 강화 달성 (+20)':'Cường hóa tối đa (+20)',
'강화 시':'Sau cường hóa',
'합성':'Tổng Hợp',
'같은 종류·같은 성급 결정 3개 → 1성급 상승 (강화 리셋)':'3 pha lê cùng loại & hạng → nâng 1 hạng (reset cường hóa)',
'합성 가능한 결정이 없습니다 (같은 종류·성급 3개 필요)':'Không có pha lê tổng hợp được (cần 3 cùng loại & hạng)',
'결정 분해 → 결정 가루':'Phân Giải Pha Lê → Bụi Pha Lê',
'분해할 결정이 없습니다':'Không có pha lê để phân giải',
'결정 제작 (가루 → 결정)':'Chế Pha Lê (Bụi → Pha Lê)',
'탈착':'Tháo',
'빈 슬롯':'Ô trống',
'결정 선택 후 클릭':'Chọn pha lê rồi nhấn',
'클릭하여 선택결정 장착':'Nhấn để gắn pha lê đã chọn',
'획득!':'Đã Nhận!',
'제작!':'Đã Chế Tạo!',
'합성!':'Đã Tổng Hợp!',
'최상위 일괄합성':'Tổng Hợp Hàng Loạt',
'일괄합성 완료':'Tổng hợp hàng loạt xong',
'벌레굴':'Hang Giun',
'얼음굴':'Hang Băng',
'고통의 화염지대':'Vùng Lửa',
'지옥의 군단':'Quân Đoàn Địa Ngục',
'사도의 마굴':'Hang Tông Đồ',
'지옥성':'Thành Địa Ngục',
'엑소듀서 전사':'Chiến Binh Exoduser',
'포이즈':'Thăng Bằng',
'지옥창고':'Kho Địa Ngục',
'선택분해':'Tháo Chọn Lọc',
'쓰레기':'Rác',
'복구 불가!':'Không thể khôi phục!',
'중요잠금':'Khóa Quan Trọng',
'자동 장착!':'Tự động trang bị!',
'분해! 가루 +':'Đã tháo! Bụi +',
'평화보호':'Khiên Thần',
'지진폭풍':'Bão Chấn',
'회전기폭':'Xoáy Nổ',
'공격':'Tấn Công',
'보호막':'Rào Chắn',
'합체 스킬로 통합됨':'Hợp nhất vào kỹ năng đã hợp',
'얼음보주 안에선 사용 불가!':'Không thể dùng trong Cầu Băng!',
'Shift+키로 폭파':'Shift+phím để kích nổ',
'취소':'Hủy',
'쿨다운 중...':'Hồi chiêu...',
'시전 중...':'Đang niệm...',
'악의 부족! (12)':'Không đủ Ác Ý! (12)',
'악의 부족! (15)':'Không đủ Ác Ý! (15)',
'악의 부족! (20)':'Không đủ Ác Ý! (20)',
'악의 부족! (10)':'Không đủ Ác Ý! (10)',
'HP 부족!':'Không đủ HP!',
'필살기 슬롯 클릭하여 배정!':'Nhấn ô tuyệt chiêu để gán!',
'필살기 스킬을 습득하세요':'Hãy học một tuyệt chiêu',
'우클릭(칼등치기)에 합체됨':'Hợp nhất vào Chuột Phải (đỡ kiếm)',
'T(석궁자동)에 세팅하세요':'Gán vào T (nỏ tự động)',
'공성쇠뇌 철거 → 이동식':'Nỏ công thành tháo → di động',
'ST 부족! (100)':'Không đủ ST! (100)',
'HP 99% 이상!':'HP 99%+!',
'그로기 보스 없음!':'Không có boss choáng!',
'이미 폭풍 지역!':'Đã ở vùng bão!',
'이미 빙풍 지역!':'Đã ở vùng bão băng!',
'💎 푸른비 해금!':'💎 Mưa Xanh mở khóa!',
'💫 버스트루프 해금!':'💫 Vòng Nổ mở khóa!',
'👻 유령 허수아비 해금!':'👻 Ảo Ảnh Decoy unlocked!',
'쿨 ':'Hồi ',
'과부하 ':'Quá Tải ',
'🕊️💎 블루콩!':'🕊️💎 Đậu Xanh!',
'🛡️💎 빨콩→블루콩!':'🛡️💎 Đỏ→Blue Bean!',
'🛡️💎 무지개→블루콩!':'🛡️💎 Cầu Vồng→Blue Bean!',
'레어':'Hiếm',
'슬롯':'Ô',
'성공률':'Tỷ Lệ Thành Công',
'AI 자동 강화':'AI Tự Cường Hóa',
'최대 강화 달성!':'Đã đạt cường hóa tối đa!',
'최대 강화':'Cường hóa tối đa',
'회복량':'Hồi Phục',
'분해할 아이템이 없습니다.':'Không có vật phẩm để tháo.',
'🔨 제작':'🔨 Chế Tạo',
'체간':'Tư thế',
'아이템에 마우스를 올리거나 좌클릭으로 선택하세요':'Di chuột lên vật phẩm hoặc nhấn trái để chọn',
'중독':'Độc',
'지뢰':'Mìn',
'덫':'Bẫy',
'산호가시':'Gai San Hô',
'투사체':'Đạn',
'도트':'Sát Thương Liên Tục',
'레어몹':'Quái Hiếm',
'구역':'Khu vực',
'가시!':'Gai!',
'림보':'Lâm Bô',
'색욕':'Dục Vọng',
'탐식':'Tham Ăn',
'탐욕':'Tham Lam',
'분노':'Thịnh Nộ',
'이단':'Dị Giáo',
'폭력':'Bạo lực',
'분노!':'Cuồng Nộ!',
'탐욕!':'Tham Lam!',
'💀 분노 폭발!':'💀 Cuồng Nộ Burst!',
'심연의 분노!':'Cuồng Nộ Vực Sâu!',
'쌍둥이의 분노!':'Cuồng Nộ Song Sinh!',
'소환굴':'Hang Triệu Hồi',
'처치!':'Đã Hạ!',
'왕관 착용':'Đội Vương Miện',
'왕관 해제':'Tháo Vương Miện',
'맨손':'Tay Không',
'없음':'Không',
'갑옷':'Giáp',
'부츠':'Giày',
'매직':'Pháp Thuật',
'챔피언':'Quán quân',
'초속':'Tốc Độ',
'강타':'Đập',
'재생':'Hồi',
'맹독':'Nọc Độc',
'소환':'Triệu Hồi',
'기생':'Ký sinh',
'분열':'Phân Thân',
'용암자취':'Vệt Dung Nham',
'사망폭발':'Nổ Tử Vong',
'화염사슬':'Xích Lửa',
'광전':'Cuồng Nộ',
'텔레포트':'Dịch chuyển',
'소용돌이':'Lốc xoáy',
'환영':'Bóng ma',
'전격반사':'Phản Xạ Điện',
'감전':'Giật Điện',
'낙뢰':'Sấm',
'연쇄전격':'Sét Liên Hoàn',
'동료불사':'Đồng Minh Bất Tử',
'영혼포식':'Nuốt Hồn',
'시간왜곡':'Bẻ Cong Thời Gian',
'혼돈변이':'Biến Dị Hỗn Loạn',
'복수자':'Trả Thù',
'마법보초':'Lính Canh Pháp',
'환영술사':'Ảo thuật gia',
'함성':'Hô Xung Trận',
'치유':'Hồi Máu',
'신속':'Nhanh Nhẹn',
'다크 판타지 전사. 거대검+검은 갑옷':'Chiến binh dark fantasy. Đại kiếm + Giáp đen',
'⚡ 사슬이동:강화!':'⚡ Lướt Xích:Tăng Cường!',
'⚡ 사슬기동:화염!':'⚡ Xích Drive: Flame!',
'달성!':'Đạt Được!',
'ST':'ST',
'부족!':'Không Đủ!',
'타':'Đòn',
'🌀 당기기 모드':'🌀 Kéo Mode',
'💥 밀어내기 모드':'💥 Đẩy Mode',
'🕊️빨콩 흡수':'🕊️Hấp Thụ Đỏ',
'🕊️흡수':'🕊️Hấp Thụ',
'💎유도 폭발!':'💎Homing Nổ!',
'💥반사 폭발!':'💥Reflect Nổ!',
'⚡⚡ 참회 귀환!':'⚡⚡ Sám Hối Quay Về!',
'⚡ 참회!':'⚡ Sám Hối!',
'파도!':'Sóng!',
'암전!':'Sét!',
'암흑!':'Bóng Tối!',
'암흑창!':'Thương Bóng Tối!',
'빛창!':'Thương Ánh Sáng!',
'체 소환!':'Đã triệu hồi!',
'개 설치!':'Đã đặt!',
'💥 보스 그로기!':'💥 Boss Choáng!',
'💥 그로기!':'💥 Choáng váng!',
'보상':'Thưởng',
'⚡ 암전나선!':'⚡ Sét Helix!',
'🌋 지진폭풍!':'🌋 Bão Chấn!',
'SP슬롯':'Ô SP',
'F슬롯':'Ô F',
'⚔🩸 독혈해방!':'⚔🩸 Giải Phóng Độc Huyết!',
'⚔ 칼날 해방!':'⚔ Giải Phóng Kiếm!',
'🔨🌋 지옥강타!':'🔨🌋 Inferno Đập!',
'🔨 대왕치기!':'🔨 Giant Đập!',
'✟ 결계의 영역!':'✟ Lĩnh Vực Kết Giới!',
'✟ 물의 영역!':'✟ Nước Domain!',
'✟ 파쇄의 영역!':'✟ Vỡ Tan Domain!',
'✟ 침식의 영역!':'✟ Lĩnh Vực Ăn Mòn!',
'✟ 관통의 영역!':'✟ Lĩnh Vực Xuyên Thấu!',
'✟ 권능의 영역!':'✟ Lĩnh Vực Quyền Năng!',
'🛡 회복의 영역!':'🛡 Lĩnh Vực Thánh!',
'임계...!':'Tới Hạn...!',
'기폭팔!':'Kích Nổ!',
'강제기폭!':'Cưỡng Nổ!',
'자동기폭!':'Tự Nổ!',
'회전기폭!':'Xoáy Nổ!',
'해제기폭!':'Giải Nổ!',
'지진기폭!':'Chấn Nổ!',
'혼돈의 왕관':'Vương Miện Hỗn Loạn',
'전지전능의 왕관':'Vương Miện Toàn Năng',
'악마의 팔찌':'Vòng Tay Quỷ',
'생명의 팔찌':'Vòng Tay Sinh Mệnh',
'🌊 위→아래 파도!':'🌊 Top→Bottom Sóng!',
'🌊 오른→왼 파도!':'🌊 Right→Left Sóng!',
'🌊 아래→위 파도!':'🌊 Bottom→Top Sóng!',
'🌊 왼→오른 파도!':'🌊 Left→Right Sóng!',
'무적!':'Bất Bại!',
'🪞 반격!':'🪞 Phản Đòn!',
'💢 반격!':'💢 Phản Đòn!',
'흡수!':'Hấp Thụ!',
'반격 발사!':'Phản Đạn!',
'저주! 드랍률 -50%':'Nguyền! Tỷ lệ rơi -50%',
'도망!':'Chạy!',
'위상!':'Dịch chuyển pha!',
'방어!':'Phòng Thủ!',
'회수 HP+':'Thu Hồi HP+',
'이동식 복귀':'Quay Về Di Động',
'약점!':'Điểm Yếu!',
'저항!':'Kháng!',
'콤보 종료: ':'Kết Combo: ',
'악의 +':'Ác ý +',
'저주 ':'Nguyền ',
'불발...':'Thất Bại...',
'사슬 약점!':'Điểm Yếu Xích!',
'전염 x':'Dịch x',
'흡수 완료!':'Hấp Thụ Xong!',
'부활 성공!':'Hồi Sinh Thành Công!',
'부활 실패...':'Hồi Sinh Thất Bại...',
'차원 이동!':'Dịch Chuyển Chiều Không!',
'기절 해제':'Giải Choáng',
'악의 부족':'Không đủ Ác Ý',
'스킬 미습득':'Chưa học kỹ năng',
'펼치기':'Mở Rộng',
'접기':'Thu Gọn',
'조건 미달!':' chưa đạt!',
'해제!':' Đã Hủy Hợp!',
'자동 ON':' Tự Động BẬT',
'자동 OFF':' Tự Động TẮT',
'스킬 해제':' kỹ năng chưa gán',
'닫기':'Đóng',
'장착 중':'Đã Trang Bị',
'보관 아이템':'Vật Phẩm Cất Kho',
'클릭으로 선택 · ESC로 닫기':'Nhấn để chọn · ESC để đóng',
'선택됨':'Đã Chọn',
'악의 부족! (30)':'Không đủ Ác Ý! (30)',
'MP 부족! (40)':'Không đủ MP! (40)',
'MP 부족! (100)':'Không đủ MP! (100)',
'MP 부족! (10)':'Không đủ MP! (10)',
'MP 부족! (':'Không đủ MP! (',
'✟ 시전...':'✟ Đang niệm...',
'🌋 시전...':'🌋 Đang niệm...',
'⛧ 시전...':'⛧ Đang niệm...',
'❄ 진입!':'❄ Vào!',
'⛓️ 사슬!':'🔱 Xích Móc!',
'레벨 부족! (요구: Lv.':'Cấp quá thấp! (Yêu cầu: Lv.',
' 장착!':' Đã Trang Bị!',
' 해제':' Đã Tháo',
'👿 악의 추출: +':'👿 Ác Ý Extract: +',
'F 슬롯 해제':'Ô F chưa gán',
'💫 집중...':'💫 Tập trung...',
'⚡ 마력연사!':'⚡ Huyền Bí Barrage!',
'❄빙결!':'❄Đóng Băng!',
'🟢독!':'🟢Độc!',
'⚡감전!':'⚡Giật!',
'🔥화상!':'🔥Bỏng!',
'✦ 여신의 가호 — SP+5 AP+3':'✦ Phước Nữ Thần — SP+5 AP+3',
'⚔ 기동칼날개!':'⚔ Cánh Kiếm!',
'🔥 화염관통!':'🔥 Lửa Pierce!',
'🔱 관통!':'🔱 Xuyên Thấu!',
'⚔ 칼날!':'⚔ Kiếm!',
'💥 착지!':'💥 Tiếp đất!',
'💫 기절!':'💫 Choáng!',
'⚡ 체간삭감!':'⚡ Thăng Bằng Break!',
'⚡ 기동파괴! ':'⚡ Xích Crush! T',
'🔥 기동불꽃!':'🔥 Xích Blaze!',
'🔥 기동불꽃! ':'🔥 Xích Blaze! T',
'단계 ×':'cấp ×',
'⚡ 기동전폭! x':'⚡ Xích Burst! x',
'🔥🔥 3중폭!':'🔥🔥 Bùng x3!',
'🔥🔥🔥 6중폭!':'🔥🔥🔥 Bùng x6!',
'🔥🔥🔥🔥 9중폭!':'🔥🔥🔥🔥 Bùng x9!',
'💥 불꽃폭발! ':'💥 Nổ Lửa! ',
'🔥 기동불꽃 준비!':'🔥 Xích Blaze Ready!',
'🔨 기동파괴 준비!':'🔨 Xích Crush Ready!',
'⚡ 기동전폭 준비!':'⚡ Xích Burst Ready!',
'⚡ 과부하! 5초':'⚡ Quá Tải! 5s',
'💫 자동 버스트!':'💫 Tự Động Nổ!',
'🔨 칼등날개!':'🔨 Khiên Wing!',
'💥폭발!':'💥Nổ!',
'🛡️💎 유도반사!':'🛡️💎 Homing Phản Xạ!',
'⚡💎 블루콩!':'⚡💎 Đậu Xanh!',
'💎 블루콩!':'💎 Đậu Xanh!',
'⚡반사!':'⚡Phản Xạ!',
'💎 푸른비 OFF':'💎 Mưa Xanh TẮT',
'💎 푸른비 ON!':'💎 Mưa Xanh BẬT!',
'🔥 지옥진!':'🔥 Trận Địa Ngục!',
'🔥 업화선!':'🔥 Hỏa Ngục Beam!',
'✦ 평화 충격파! ':'✦ Peace Sóng Xung! ',
'⚡ 전류 방출!':'⚡ Hiện Tại Release!',
'⚡⚡ 레인라이트닝!':'⚡⚡ Rain Sét!',
'💫 광역!':'💫 Diện rộng!',
'🔥 불장판!':'🔥 Lửa Khu Vực!',
'💫 피니셔!':'💫 Kết liễu!',
'☠ 지옥에서 귀환!':'☠ Returned from Địa Ngục!',
'☠ 완전 사망!':'☠ Permanent Chết!',
'⚔ 처형! ':'⚔ Hành Hình! ',
'💥 지뢰!':'💥 Mìn!',
'⚠ 덫!':'⚠ Bẫy!',
'❌ 우클릭으로! -':'❌ Dùng Chuột Phải! -',
'❌ Q키로! -':'Dùng Q! -',
'💥무지개 폭발! ':'💥Rainbow Nổ! ',
'🛡️💎 블루콩!':'🛡️💎 Đậu Xanh!',
'⬜화이트볼!':'⬜Cầu Trắng!',
'✨💎 블루콩!':'✨💎 Đậu Xanh!',
'💜다크볼!':'💜Cầu Tối!',
'❄빙판!':'❄Sàn Băng!',
'🌨빙결!':'🌨Đóng Băng!',
'🕸둔화!':'🕸Chậm!',
'💀 역병 처형!':'💀 Hành Hình Dịch Bệnh!',
'💥 역병 Finale!':'💥 Finale Dịch Bệnh!',
'⚔ 균열 악마!':'⚔ Vết Nứt Demon!',
'자동회수 HP+':'Tự Thu Hồi HP+',
'MP 부족 — 연사 해제':'MP thấp — Tắt Bắn Nhanh',
'MP 부족 — 푸른비 OFF':'MP thấp — Tắt Mưa Xanh',
'🛡️반사!':'🛡️Phản Xạ!',
'⚡🦴 참회 귀환!':'⚡🦴 Sám Hối Quay Về!',
'🦴⚡해골번개!':'🦴⚡Bone Sét!',
'⚡악의폭풍!':'⚡Bão Ác Ý!',
'❄아이스스톰!':'❄Bão Băng!',
'⚡ 암전폭발!':'⚡ Sét Nổ!',
'⚡ 레인라이트닝! x':'⚡ Rain Sét! x',
'❄ 탈출!':'❄ Thoát!',
'⚡쉴드!':'⚡Khiên!',
'❄🌪️ 얼음보주!':'❄🌪️ Băng Orb!',
'🌪️ 전개!':'🌪️ Triển Khai!',
'❄ 빙결흡인!':'❄ Freeze Xoáy!',
'❄☄ 빙결폭발!':'❄☄ Freeze Nổ!',
'☄️ 흡인!':'☄️ Xoáy!',
'☄️ 대폭발!':'☄️ Mega Nổ!',
'❄ 얼음보주!':'❄ Băng Orb!',
'⏳ 시간왜곡!':'⏳ Bẻ Cong Thời Gian!',
'쿨다운!':'Hồi chiêu!',
'❄ 파쇄!':'❄ Vỡ Tan!',
'☄️💥 대폭발!':'☄️💥 Mega Nổ!',
'반사!':'Phản Xạ!',
'💀 도넛!':'💀 Vòng!',
'💀 전멸!':'💀 Hủy Diệt!',
'🌊 파도!':'🌊 Sóng!',
'속박!':'Trói!',
'반격!':'Phản Đòn!',
'분신!':'Phân thân!',
'분신 파괴!':'Phân Thân Bị Hủy!',
'무기 해방!':'Giải Phóng Vũ Khí!',
'❄프리즌!':'❄Ngục Băng!',
'⚡ 증표 ':'⚡ Dấu ',
'흔들!':'Rung!',
'⚠ 광역 발사!':'⚠ AoE Lửa!',
'🔥 확산!':'🔥 Lan!',
'⚠ 돌진!':'⚠ Xích!',
'🦅 도약!':'🦅 Nhảy!',
'⚡ 레이저!':'⚡ Laser!',
'🌊 충격파!':'🌊 Sóng Xung!',
'👹 소환!':'👹 Triệu Hồi!',
'☄ 유성우!':'☄ Mưa Thiên Thạch!',
'🖐 잡기!':'🖐 Tóm!',
'🌀 회전참!':'🌀 Lốc!',
'💣 지뢰!':'💣 Mìn!',
'🌀 흡인!':'🌀 Hút!',
'🔴 빨간콩 폭풍!':'🔴 Bão Đạn Đỏ!',
'🔴🔴 콩 비!':'🔴🔴 Mưa Đạn!',
'🌊 부채꼴 충격파!':'🌊 Fan Sóng Xung!',
'✴ 멸광 레이저!':'✴ Hủy Diệt Laser!',
'🔴 추적 장판!':'🔴 Tracking Khu Vực!',
'💥 속성탄!':'💥 Đạn Nguyên Tố!',
'⚔ 검기!':'⚔ Khí Kiếm!',
'⚔ 재단참!':'⚔ Reaping Chém!',
'🌀 나선탄!':'🌀 Đạn Xoắn!',
'⚠ 찌르기!':'⚠ Đâm!',
'🔥🔥 지옥기둥!':'🔥🔥 Địa Ngục Pillar!',
'⚔ 환영검!':'⚔ Ảo Ảnh Blade!',
'💢 반격자세!':'💢 Phản Đòn Stance!',
'⚔ 연격!':'⚔ Combo!',
'🌑 암흑!':'🌑 Bóng Tối!',
'👥 분신!':'👥 Phân thân!',
'🌋 균열!':'🌋 Vết Nứt!',
'🌊 파동!':'🌊 Gợn Sóng!',
'💣 추적지뢰!':'💣 Homing Mìn!',
'⏪ 되감기!':'⏪ Tua Lại!',
'🌀 중력장!':'🌀 Trường Trọng Lực!',
'🔨 벽밀기!':'🔨 Wall Đẩy!',
'☠ 독안개!':'☠ Độc Fog!',
'⛓ 감옥!':'⛓ Nhà Tù!',
'⚡ 연쇄번개!':'⚡ Xích Sét!',
'🔮 궤도탄!':'🔮 Đạn Quỹ Đạo!',
'🛡 방패돌진!':'🛡 Khiên Xích!',
'🪞 반격자세!':'🪞 Phản Đòn Stance!',
'⚓ 속박!':'⚓ Trói!',
'👤 분신!':'👤 Phân thân!',
'🖐 탈취!':'🖐 Cướp!',
'🔥🔥 용암 지대!':'🔥🔥 Dung Nham Khu Vực!',
'🌧🌧 화염 폭격!':'🌧🌧 Lửa Barrage!',
'⚡⚡ 전격 장막!':'⚡⚡ Sét Veil!',
'💀 내 곁으로!':'💀 Đến Bên Ta!',
'⭕ 안전!':'⭕ An Toàn!',
'💀💀 전멸 폭발!':'💀💀 Hủy Diệt Nổ!',
'⚡ 쐐기 소멸!':'⚡ Tiêu Diệt Nêm!',
'🌊충격파!':'🌊Sóng Xung!',
'👿악의+100':'👿Ác Ý+100',
'💥패링폭발!':'💥Parry Nổ!',
'균열 충돌! ':'Va Chạm Vết Nứt! ',
'벽 충돌! ':'Va Chạm Tường! ',
'소환!':'Triệu Hồi!',
'환영!':'Bóng ma!',
'⚡낙뢰!':'⚡Sấm!',
'⚡빔!':'⚡Tia!',
'환영술!':'Ảo ảnh!',
'💀소환!':'💀Triệu Hồi!',
'🔮주술!':'🔮Nguyền!',
'🩸산란!':'🩸Đẻ Trứng!',
'💢광폭!':'💢Cuồng Nộ!',
'🕷산란!':'🕷Đẻ Trứng!',
'❄서리!':'❄Băng giá!',
'❄빙결파!':'❄Freeze Sóng!',
'💀빙마!':'💀Quỷ Băng!',
'돌진!':'Xích!',
'충격파!':'Sóng Xung!',
'독안개!':'Sương Mù Độc!',
'연타!':'Loạn Đả!',
'포효!':'Gầm!',
'강화!':'Cường Hóa!',
'꼬리!':'Đuôi!',
'은신...':'Ẩn Thân...',
'기습!':'Phục Kích!',
'산란!':'Đẻ!',
'독가스!':'Khí Độc!',
'소멸...':'Tan Biến...',
'강타!':'Đập!',
'분비!':'Tiết!',
'채찍!':'Roi!',
'출혈!':'Chảy Máu!',
'급강하!':'Bổ Nhào!',
'방출!':'Phóng!',
'충격!':'Va chạm!',
'치유!':'Hồi Máu!',
'의식!':'Nghi thức!',
'지옥불!':'Hỏa Ngục!',
'끌려감!':'Bị Kéo!',
'혀!':'Lưỡi!',
'응시!':'Nhìn!',
'낙하!':'Rơi!',
'핏방울!':'Giọt Máu!',
'일어남!':'Dậy!',
'휩쓸기!':'Quét!',
'웅크림':'Cúi',
'뼈칼날!':'Kiếm Xương!',
'감속!':'Chậm!',
'비명!':'Hét!',
'화산탄!':'Đạn Núi Lửa!',
'자폭!':'Tự Hủy!',
'감싸기!':'Bao Bọc!',
'잡기!':'Tóm!',
'내리찍기!':'Đập!',
'브레스!':'Hơi Thở!',
'비행!':'Bay!',
'용암비!':'Mưa Dung Nham!',
'물뿜기!':'Vòi Nước!',
'빛...':'Ánh Sáng...',
'삼키기!':'Nuốt!',
'마비!':'Tê Liệt!',
'방전!':'Phóng!',
'집게찍기!':'Đập Gọng Kìm!',
'찍기!':'Đập!',
'붙잡기!':'Tóm!',
'감아올리기!':'Cuộn!',
'파편!':'Mảnh!',
'할퀴기!':'Cào!',
'기생충!':'Ký Sinh!',
'심연 해방!':'Giải Phóng Vực Sâu!',
'촉수난타!':'Mưa Xúc Tu!',
'삼지창!':'Đinh ba!',
'소용돌이!':'Xoáy!',
'해일!':'Sóng thần!',
'끼걱!':'Kẽo Kẹt!',
'폭발!':'Nổ!',
'체인!':'Xích!',
'갈기!':'Bờm!',
'공포!':'Khiếp sợ!',
'흡혈!':'Hút!',
'베기!':'Chém!',
'비이이명!!':'Reeeng!!',
'분열!':'Phân Thân!',
'3연참!':'Ba Trảm!',
'패링!':'Đỡ đòn!',
'...복사...':'..Sao Chép...',
'불균형...저주!':'Mất Cân Bằng...Nguyền!',
'저주!':'Nguyền!',
'균형...강화!':'Cân Bằng...Tăng Cường!',
'심판의 기둥!':'Trụ Phán Xét!',
'처형 선고!':'Án Tử!',
'고통의 해방!':'Giải Phóng Đau Đớn!',
'너도 느껴봐라!':'Mày cũng cảm nhận đi!',
'대검난무!':'Đại Kiếm Cuồng Nộ!',
'촉수!':'Xúc Tu!',
'전방위 빔!':'Tia Toàn Phương!',
'회피!':'Né!',
'[F] 상점':'[F] Cửa Hàng',
'거래 성공!':'Giao Dịch Thành Công!',
'악의 부족! (':'Không đủ Ác Ý! (',
'상인이 떠납니다...':'Thương nhân rời đi...',
'사슬 해방!':'Giải Phóng Xích!',
'완전 해방!':'Giải Phóng Hoàn Toàn!',
'⏪ 시간 되감기!':'⏪ Time Tua Lại!',
'전환!':'Chuyển!',
'부활 ':'Hồi Sinh ',
'🌀균열!':'🌀Vết Nứt!',
'...사라짐':'...Biến Mất',
'낫 베기!':'Liềm Trảm!',
'☠ 죽음의 선고!':'☠ Chết Sentence!',
'선고 집행...':'Thi hành án...',
'⚡패링!':'⚡Đỡ đòn!',
'경직!':'Choáng!',
'⚠ 잡혔다!':'⚠ Bị Tóm!',
'💥 내던지기!':'💥 Ném!',
'💥 소용돌이 폭발!':'💥 Xoáy Nổ!',
'👻 순간이동!':'👻 Dịch chuyển!',
'💫 기절! 5초':'💫 Choáng! 5s',
'찌르기 반격!':'Phản Đâm!',
'💢 폭발!':'💢 Nổ!',
'반격 실패':'Phản Đòn Thất Bại',
'탈취 반격!':'Phản Cướp!',
'무기 봉인!':'Phong Ấn Vũ Khí!',
'냠!':'Nhồm!',
'합체!':'Hợp Nhất!',
'출구가 열렸다!':'Lối ra mở!',
'보물상자 출현!':'Rương kho báu xuất hiện!',
'출구':'Lối Ra',
'⚠ 문지기가 살아있다!':'⚠ Người Gác Cổng still alive!',
'⏱ 타임어택 ':'⏱ Time Tấn Công ',
'처치율 ':'Tỷ Lệ Hạ ',
'불사 보호':'Hộ Vệ Bất Tử',
'환영 소멸!':'Ảo Ảnh Biến Mất!',
'부활력 ':'Lực Hồi Sinh ',
'✟ 신성력 억제! (':'✟ Thánh Suppress! (',
'부활 실패 (':'Hồi Sinh Thất Bại (',
'⚡순간이동!':'⚡Dịch chuyển!',
'👻 동반부활!':'👻 Hồi Sinh Đồng Đội!',
'✟ 신성력 억제!':'✟ Thánh Suppress!',
'💀 부활 판정 중...':'💀 Đang phán xét hồi sinh...',
'⚔ 문지기 처치!':'⚔ Người Gác Cổng Defeated!',
'🚪 보스방 개방!':'🚪 Boss Room Mở!',
'잔해 출현!':'Đống Đổ Nát Xuất Hiện!',
'🌀균열 발생!':'🌀Vết Nứt Xuất Hiện!',
'🔥복수!':'🔥Báo Thù!',
'💥폭독혈!':'💥Huyết Độc Nổ!',
'빙판!':'Sàn Băng!',
'❄최종빙결!':'❄Đóng Băng Cuối!',
'빙마 처치!':'Hạ Quỷ Băng!',
'분리!':'Tách Ra!',
'뼈 파편!':'Mảnh Xương!',
'태아 처치!':'Hạ Thai Nhi!',
'지배자 처치!':'Hạ Bá Chủ!',
'용암!':'Dung nham!',
'화룡 처치!':'Hạ Hỏa Long!',
'최후의 비명!':'Tiếng Hét Cuối!',
'산화...':'Oxy Hóa...',
'심판자 처치!':'Hạ Quan Tòa!',
'고통의 왕 처치!':'Hạ Vua Đau Đớn!',
'수역!':'Nước!',
'파편 폭발!':'Nổ Mảnh!',
'거대어 처치!':'Hạ Hải Quái!',
'대사도 처치!':'Hạ Đại Tông Đồ!',
'독웅덩이!':'Vũng Độc!',
'화염장판!':'Vùng Lửa!',
'전기장!':'Điện Trường!',
'무기 드롭!':'Rơi Vũ Khí!',
'보물 발견!':'Phát Hiện Kho Báu!',
'상인의 주머니 +':'Túi Thương Nhân +',
'속박의 파편!':'Mảnh Trói Buộc!',
'시간의 조각!':'Mảnh Thời Gian!',
'저주 해제!':'Giải Nguyền!',
'차원의 결정!':'Pha Lê Chiều Không!',
'전설 아이템!':'Vật Phẩm Huyền Thoại!',
'죽음을 이겨냈다!':'Vượt Qua Cái Chết!',
'💥대폭발!':'💥Mega Nổ!',
'⚡강화!':'⚡Tăng Cường!',
'장비 ':'Trang Bị ',
'💫 진동!':'💫 Chấn động!',
'❄ 무적!':'❄ Bất Khả Chiến Bại!',
'집중 해제!':'Tập Trung Hủy!',
'집중!':'Tập trung!',
'🕊️ 평화보호 ':'🕊️ Khiên Hòa Bình ',
'🛡 보호막 ':'🛡 Khiên ',
'🌀 회전보호막 ':'🌀 Spin Khiên ',
'💥한방캡!':'💥Giới Hạn 1 Đòn!',
'⚡쉴드 파괴!':'⚡Shield Phá Hủy!',
'💀 불굴!':'💀 Bất Khuất!',
'💀 1회부활!':'💀 1-life Hồi Sinh!',
'감시 회수':'Thu Hồi Lính Canh',
'악마화 부활!':'Hồi Sinh Ma!',
'배정 가능한 스킬 없음':'Không có kỹ năng để gán',
'칼날 없음!':'Không Có Kiếm!',
'⚔ 악의사냥!':'⚔ Ác Ý Hunt!',
'❄🌪️ 얼음소용돌이!':'❄🌪️ Băng Xoáy!',
'🌪️ 폭풍소환!':'🌪️ Xoáy Triệu Hồi!',
'🌹 붉은꽃!':'🌹 Hoa Đỏ!',
'💥 폭산탄!':'💥 Nổ Shot!',
'🪡 바늘출!':'🪡 Kim Nổ!',
'⚡ 전격이동!':'⚡ Bước Chớp!',
'기둥가시로 흡수됨':'Bị gai trụ hấp thụ',
'🌿 가시덫!':'🌿 Spike Bẫy!',
'⚡ 전격의창!':'⚡ Sấm Spear!',
'🏹 공성쇠뇌 설치!':'🏹 Siege Nỏ Placed!',
'👻 유령 허수아비!':'👻 Ảo Ảnh Decoy!',
'💥 폭발 허수아비!':'💥 Nổ Decoy!',
'축적!':'Đã Tích!',
'축적 중...':'Đang Tích...',
'만충! 재입력→폭발':'Đầy! Nhấn lại→Nổ',
'폭발! ':'Nổ! ',
'뎀':' Sát Thương',
'🩸 폭독칼날!':'🩸 Kiếm Dịch Nổ!',
'⚡날개치기!':'⚡Đòn Cánh!',
'🗡 칼등날개!':'🗡 Khiên Wing!',
'🏛️ 악의기둥!':'🏛️ Bóng Tối Pillar!',
'🌿 기둥가시!':'🌿 Gai Trụ!',
'🌋 지옥강타!':'🌋 Inferno Đập!',
'💥 체간 붕괴!':'💥 Thế Break!',
'💫 포이즈 파괴!':'💫 Thăng Bằng Phá Hủy!',
'⚡ 뇌전걸음!':'⚡ Ma Walk!',
'✟ 구속의 영역!':'✟ Lĩnh Vực Trói Buộc!',
'✟ 신성폭발!':'✟ Thánh Nổ!',
'⛧ 블랙!':'⛧ Hắc Tinh!',
'🌋 용암소환!':'🌋 Dung Nham Triệu Hồi!',
'필살기 배정!':'Đã Gán Tuyệt Chiêu!',
'완료':'Hoàn Thành',
'합체 가능':'Có Thể Hợp',
'부족':'Không Đủ',
'SP 부족! (':'Cần SP! (',
'🕊️ 히든: 평화의보호 해금!':'🕊️ Ẩn: Khiên Hòa Bình mở khóa!',
'⚡ 히든: 참회 해금!':'⚡ Ẩn: Sám Hối mở khóa!',
'배정됨':'Đã Gán',
'합체 Lv.':'Cấp Hợp',
'◆ 같은 보석 스킬 습득 시 합체 가능':'◆ Có thể hợp khi học cùng kỹ năng đá',
'▼ 가방 → 창고 보관':'▼ Túi → Kho',
'▲ 창고 → 가방 꺼내기':'▲ Kho → Túi',
'✓ 선택됨':'✓ Đã Chọn',
'⟨ 입력 대기... ⟩':'⟨ Đang Chờ... ⟩',
'⟨ 대기 ⟩':'⟨ Chờ ⟩',
'보조':'Phụ',
'키 설정 초기화 (또는 F5 키)':'Đặt Lại Phím (hoặc F5)',
'아무 키 또는 마우스 버튼을 누르세요 (ESC = 취소)':'Nhấn phím hoặc chuột (ESC = hủy)',
'WebGPU 활성':'WebGPU Hoạt Động',
'WebGL2 활성':'WebGL2 Hoạt Động',
'측정 중...':'Đang Đo...',
'불러오기 실패':'Tải Thất Bại',
'장착':'Đã Trang Bị',
'🔒 중요잠금 아이템은 분해 선택 불가!':'🔒 Vật phẩm khóa quan trọng không thể chọn tháo!',
'장비 강화 (실패 시 재료만 소멸)':'Cường Hóa (thất bại mất nguyên liệu)',
'강화 보너스 적용':'Đã Áp Dụng Thưởng Cường Hóa',
'강화 실패!':'Cường Hóa Thất Bại!',
'장착된 장비가 없습니다.':'Không có trang bị.',
'충분':'Đủ',
'더 필요':'Cần Thêm',
'장비 선택':'Chọn Trang Bị',
'목표치 설정':'Đặt Mục Tiêu',
'악의 투입':'Đầu Tư Ác Ý',
'자동 시도':'Thử Tự Động',
'목표 강화치':'Mục Tiêu Cường Hóa',
'예상 필요 악의':'Ước Tính Ác Ý Cần',
'보유':'Sở Hữu',
'강화 시작':'Bắt Đầu Cường Hóa',
'위에서 장비를 선택하세요':'Chọn trang bị ở trên',
'⬆ 물약 강화 (최대 10단)':'⬆ Nâng Cấp Thuốc (tối đa 10)',
'필요':'Cần Thiết',
'악의의 분해로 — 장비를 악의로 갈아버려라':'Lò Ác Ý — Nghiền trang bị',
'전체 선택':'Chọn Tất Cả',
'전체 해제':'Bỏ Chọn Tất Cả',
'희귀 이하':'Hiếm Trở Xuống',
'어픽스 리롤!':'Đổi Hậu Tố!',
'영웅':'Anh Hùng',
'전설':'Huyền Thoại',
'무기 타입':'Loại Vũ Khí',
'활 타입':'Loại Cung',
'ST 부족':'Không đủ ST',
'💀 광폭화!':'💀 Điên Loạn!',
'...따라오는 거 아니야. 같은 방향일 뿐이지.':'...I\'m not following you. Just going the same way.',
'공기가 달라졌어. 더 썩었군.':'The air changed. More decay.',
'여기부터는 악마 영역이야. ...맘대로 해.':'Demon territory from here. ...Do as you wish.',
'...이 냄새. 살점이 썩는 냄새야.':'...That smell. Rotting flesh.',
'여기 오래 있으면 미쳐. 나도, 너도.':'Stay too long and you\'ll go mad. Me too.',
'이 길의 끝에 뭐가 있을까. ...알고 싶지도 않어.':'What\'s at the end of this road? ...I don\'t want to know.',
'...여기가 끝이야. 돌아갈 길은 없어.':'...This is the end. No turning back.',
'사슬을 땅에 꽂으면 끌려간다.':'Stick the Xích in the ground and get pulled.',
'Shift로 사슬 던져봐!':'Try throwing the Xích with Shift!',
'패링 성공하면 ST가 회복된다. 공짜 자원이야.':'Đỡ thành công hồi ST. Tài nguyên miễn phí.',
'패링 많이 하면 ST 걱정 없어~':'Đỡ nhiều là không lo ST~',
'장비 분해하면 악의를 얻는다. 쓰레기도 자원이야.':'Tháo trang bị được Ác Ý. Rác cũng là tài nguyên.',
'TAB 열어서 안 쓰는 장비 분해해!':'Mở TAB tháo trang bị không dùng!',
'그로기 상태의 적에겐 1.5배 데미지가 들어간다.':'Địch bị choáng nhận x1.5 sát thương.',
'무릎 꿇으면 전력으로 때려!':'Khi chúng quỳ, đánh hết sức!',
'속성 상성이 있다. 화염은 빙결에 약하고, 암전은 암흑에 약하다.':'Nguyên tố có khắc chế. Lửa yếu Băng, Sét yếu Bóng Tối.',
'무기 속성 바꿔가면서 싸워봐!':'Thử đổi nguyên tố vũ khí khi chiến!',
'빙결된 적은 1.5배 데미지를 받는다.':'Địch bị đóng băng nhận x1.5 sát thương.',
'얼리고 때리는 게 기본이야!':'Đóng băng rồi đánh — cơ bản thôi!',
'보스의 빨간 공격은 패링 가능. 보라빛은 회피만.':'Đòn đỏ của boss có thể đỡ. Cầu vồng chỉ né.',
'색깔 잘 봐! 빨강은 받아치고 무지개는 피해!':'Nhìn màu! Đỏ thì đỡ, cầu vồng thì né!',
'VIT를 올리면 최대 HP가 오른다. 죽기 싫으면 찍어.':'VIT tăng HP tối đa. Muốn sống thì chấm.',
'STR은 근접, DEX는 활, INT는 마법! 골고루 말고 하나만!':'STR cận chiến, DEX nỏ, INT pháp! Tập trung một thứ!',
'E를 꾹 누르면 빔이 나간다. 짧게 누르면 투사체.':'Giữ E bắn tia. Nhấn nhanh bắn đạn.',
'마법 쓸 때 MP 잘 봐! 빔은 연속으로 깎여!':'Chú ý MP khi dùng pháp! Tia cạn nhanh!',
'핵터와 디로이가 아이템을 주워준다. 수거 범위 안이면.':'Hecter và Deroy tự nhặt đồ trong tầm.',
'우리한테 고마워해~ 안 주우면 썩잖아.':'Cảm ơn chúng tôi~ Không nhặt thì mục thôi.',
'LCK를 올리면 레어 드롭률이 오른다.':'LCK tăng tỷ lệ rơi đồ hiếm.',
'운빨 게임이긴 하지~ LCK 올려봐!':'May mắn mà~ Thử tăng LCK!',
'강화하면 공격력이 쭉쭉 올라가! 악의만 있으면 돼!':'Cường hóa tăng ATK mạnh! Chỉ cần Ác Ý!',
'강화 확률은 +1에서 99%. 높을수록 떨어진다.':'Tỷ lệ cường hóa bắt đầu 99% ở +1. Giảm dần.',
'실패하면 악의만 날아가~ 장비는 안 부서져!':'Thất bại chỉ mất Ác Ý~ Trang bị không vỡ!',
'대장간에서 장비 제작도 된다. 악의 30000개면 영웅급 이상.':'Lò rèn còn chế tạo trang bị. 30000 Ác Ý cho Anh Hùng+.',
'랜덤이지만 좋은 거 나올 수도 있어!':'Ngẫu nhiên nhưng có thể ra đồ tốt!',
'쉴드는 마법으로, HP는 물리로 깎아야 제대로 먹힌다.':'Shield needs magic, HP needs physical to be effective.',
'반대로 치면 50%만 들어가! 무기 바꿔가면서 싸워!':'Wrong type only does 50%! Switch weapons!',
'장비에 접두사, 접미사가 붙으면 특수 효과가 생긴다.':'Trang bị có tiền tố/hậu tố sẽ có hiệu ứng đặc biệt.',
'영웅급 이상 장비에만 붙어! 좋은 거 나오면 강화해!':'Chỉ xuất hiện ở Anh Hùng+! Tháo tốt thì cường hóa!',
'강화는 장비를 바꿔도 자동 이전된다. 악의만 있으면.':'Cường hóa tự chuyển khi đổi trang bị. Tốn Ác Ý thôi.',
'더 좋은 장비 나오면 바로 장착해! 강화 수치 그대로 옮겨가!':'Ra đồ tốt hơn thì trang bị ngay! Cường hóa giữ nguyên!',
'패링을 써야 자원을 흡수한다고!':'Phải đỡ mới hấp thụ được tài nguyên!',
'F키 회복의 영역을 써봐. 자원이 차올라.':'Thử F Lĩnh Vực Thánh. Tài nguyên đầy lên.',
'적이 근접하면 스페이스키야! 가시덫을 활용해!':'Địch áp sát thì Space! Dùng Bẫy Gai!',
'기절시켜! 그로기가 터지면 데미지가 1.5배야!':'Choáng chúng! Groggy kích hoạt x1.5 sát thương!',
'1번 대왕치기로 밀어버려!':'Dùng phím 1 Đập Khổng Lồ đẩy chúng ra!',
'무릎 꿇었다.':'Nó quỳ xuống.',
'지금이야! 몰아쳐!!':'Giờ! Tấn công!!',
'스킬 포인트 있어! K 눌러서 스킬 찍어봐!':'Có điểm kỹ năng! Nhấn K học kỹ năng!',
'...힘이 없으면 여기서 끝이야.':'...Không sức thì hết ở đây.',
'...쓸 거 아니면 분해해.':'...Không dùng thì tháo đi.',
'아이템 넘쳐나네~ 우리가 주워줄게!':'Đồ nhiều quá~ Chúng tôi nhặt cho!',
'악의가 바닥이다.':'Hết Ác Ý.',
'TAB 열어서 장비 분해해! 쓰레기도 악의가 돼!':'Mở TAB tháo trang bị! Rác cũng thành Ác Ý!',
'좋은 장비가 있네! G 눌러서 대장간 가봐!':'Có trang bị tốt! Nhấn G vào lò rèn!',
'...강화 안 하면 그냥 고철이야.':'...Không cường hóa chỉ là sắt vụn.',
'...멈추지 마. 여신은 기다리지 않는다.':'...Đừng dừng. Nữ thần không đợi.',
'앞으로 가자~ 나도 여기 오래 있기 싫어.':'Đi tiếp~ Tôi cũng không muốn ở đây lâu.',
'...냄새가 짙다. 큰 놈이 있어.':'...Mùi nặng. Có con to ở đây.',
'준비됐어? 물약 확인하고!':'Sẵn sàng chưa? Kiểm tra thuốc!',
'TAB을 눌러. 가방을 열고 장비를 입어야 한다.':'Nhấn TAB. Mở túi và trang bị.',
'주웠으면 껴야지! TAB!':'Nhặt rồi thì trang bị! TAB!',
'G. 대장간에서 물약도 제작할 수 있다.':'G. Lò rèn cũng chế tạo được thuốc.',
'악의로 물약 만들어! G키야!':'Làm thuốc bằng Ác Ý! Phím G!',
'기절이야! Ctrl 눌러!':'Choáng! Press Ctrl!',
'Ctrl 유령걸음으로 탈출!':'Ctrl Bước Ma để thoát!',
'Ctrl 얼음보주로 탈출!':'Ctrl Cầu Băng để thoát!',
'빨간 탄은 우클릭 패링. 무지개는 Q 패링.':'Đạn đỏ: chuột phải đỡ. Cầu vồng: Q đỡ.',
'나머지는 전부 우클릭 패링 가능해!':'Còn lại đều đỡ được bằng chuột phải!',
'빨강=우클릭, 무지개=Q 패링. 나머진 다 쳐내.':'Đỏ=Chuột Phải, Cầu Vồng=Q. Còn lại đều đỡ.',
'무지개는 Q로 패링! 나머지는 전부 우클릭!':'Cầu vồng dùng Q! Còn lại chuột phải!',
'빠져! 물약 마시고 안전한 곳에서 회복해.':'Rút lui! Uống thuốc hồi phục nơi an toàn.',
'자원 없으면 도망가는 게 답이야!':'Hết tài nguyên thì chạy là đúng!',
'스페이스! 가시덫으로 적 묶어버려!':'Space! Ghim địch bằng Bẫy Gai!',
'근접이 너무 많아! 거리 벌려!':'Cận chiến nhiều quá! Tạo khoảng cách!',
'...둘러싸이면 끝이야. 빠져나와.':'...Bị vây là xong. Thoát ra.',
'1번 대왕치기로 쓸어버려!':'Dùng phím 1 Đập Khổng Lồ quét sạch!',
'그로기 터지면 데미지 1.5배!':'Groggy kích hoạt x1.5 sát thương!',
'회전참이나 광역기로 몰아! 한 놈씩 상대하면 죽어.':'Dùng Toàn Phong hoặc kỹ năng diện rộng! Đánh từng con là chết.',
'뭉쳐있을 때가 기회야!':'Khi chúng tụ lại là cơ hội!',
'E로 마력공격을 해봐! 악의 쉴드를 해제할려면 마법 공격을 해야 해!':'Try E for magic attacks! You need magic to break Malice shields!',
'쉴드는 마법으로, HP는 물리로. 반대로 치면 데미지 안 들어간다.':'Shields need magic, HP needs physical. Wrong type does no damage.',
'L키로 스킬 슬롯에 넣어야 쓸 수 있어.':'Nhấn L để gán kỹ năng vào ô.',
'J키를 눌러. 패시브 포인트가 쌓여있다.':'Nhấn J. Điểm nội tại đã tích lại.',
'J키! 패시브 올리면 진짜 강해져!':'Nhấn J! Nội tại mạnh lắm!',
'스태미나가 부족하다. 무리하지 마.':'ST thấp. Đừng ép quá.',
'ST 없으면 스킬 못 써! 잠깐 빠져!':'Hết ST không dùng kỹ năng! Rút lui!',
'탭 장비창을 열어봐. 아이템을 주워왔어!':'Mở TAB trang bị. Nhặt được đồ!',
'좋은 거 나왔다! TAB 열어서 확인해봐!':'Ra đồ tốt! Mở TAB xem!',
'악의에 중독되면 악마가 돼서 부활력이 생긴대. 저 녀석처럼.':'Nghiện Ác Ý thành quỷ và có sức hồi sinh. Như con đó.',
'혹시 너도...?':'Có khi ngươi cũng...?',
'데미지가 부족하면 무기류 강화를 해야해!!':'Thiếu sát thương thì phải cường hóa vũ khí!!',
'G키 대장간. 강화 안 하면 여기서 계속 죽어.':'Phím G lò rèn. Không cường hóa thì cứ chết ở đây.',
'시간이 없어. 움직여.':'No time. Di Chuyển.',
'멍하게 서있으면 안 돼!':'Đừng đứng ngẩn!',
'...뭘 기다리는 거야?':'...Đang chờ gì vậy?',
'가자가자! 몬스터가 기다려!':'Đi thôi! Quái đang chờ!',
'여기 오래 있으면 위험해.':'Ở đây lâu nguy hiểm.',
'움직여야 해! 가만있으면 둘러싸여!':'Phải di chuyển! Đứng yên bị vây!',
'쉬는 건 죽고 나서 해.':'Nghỉ ngơi sau khi chết đi.',
'살아있을 때 쉬면 안 돼!':'Đang sống không được nghỉ!',
'적이 몰려오고 있어. 빨리 움직여.':'Địch đang ùa tới. Di chuyển nhanh.',
'냄새 맡고 올 거야. 빨리!':'Chúng sẽ ngửi thấy. Nhanh lên!',
'...아직 살아있는 거 맞지?':'...Vẫn còn sống chứ?',
'혹시 잠든 거야...?':'Ngủ rồi à...?',
'...나무가 썩어가고 있어. 여기는 지옥의 입구야.':'...Cây đang mục. Đây là cửa địa ngục.',
'냄새 지독해... 빨리 지나가자.':'Mùi kinh khủng... Qua nhanh thôi.',
'조심해. 벌레굴이다. 벽이랑 바닥에서 기어나와.':'Cẩn thận. Hang giun. Chúng bò từ tường và sàn.',
'으으... 벌레 싫어! 밟아버려!':'Ugh... Ghét sâu! Giẫm chết!',
'...공기가 얼어붙는다. 여기선 화염이 먹힌다.':'...Không khí đóng băng. Lửa hiệu quả ở đây.',
'추워... 빙결 조심해! 얼면 끝이야.':'Lạnh... Chú ý đóng băng! Đóng băng là xong.',
'용암이다. 바닥을 밟으면 타 죽어.':'Dung nham. Bước lên sàn là bị thiêu.',
'뜨거워! 여기 왜 이렇게 빨개!':'Nóng! Sao đỏ vậy!',
'...군단이다. 수가 많아. 광역기 없으면 밀려.':'...Quân đoàn. Đông lắm. Không có kỹ năng diện rộng thì thua.',
'우글우글... 징그러워. 한꺼번에 쓸어!':'Lúc nhúc... Ghê. Quét sạch một lúc!',
'사도의 영역이야. 여기 놈들은 머리가 좋아.':'Lãnh địa Tông Đồ. Bọn này thông minh.',
'패턴이 복잡해졌어... 집중해!':'Patterns got complex... Tập Trung!',
'...끝이다. 지옥의 심장부. 살아 돌아가는 건 포기해라.':'...Đây rồi. Trung tâm địa ngục. Bỏ hy vọng trở về.',
'여기가 마지막이야... 각오해.':'Đây là cuối cùng... Chuẩn bị tinh thần.',
'석궁 자동발사 (T)':'Nỏ tự động (T)',
'버스트루프 당기기 (H)':'Vòng bùng nổ kéo gần (H)',
'결정 자동합성':'Tinh thể tự động tổng hợp',
'결정 자동강화':'Tinh thể tự động tăng cường',
'✓ 설정 자동 저장':'✓ Cài đặt tự động lưu',
'세팅 프리셋 저장/불러오기':'Lưu/tải cài đặt sẵn',
'세팅1 저장':'Lưu cài đặt 1','세팅1':'Cài đặt 1',
'세팅2 저장':'Lưu cài đặt 2','세팅2':'Cài đặt 2',
'재진단':'Chẩn đoán lại',
'게임 리셋 (처음부터)':'Đặt lại trò chơi (từ đầu)',
'캐릭터 선택 (로비)':'Chọn nhân vật (Sảnh)',
'닫기 [ESC]':'Đóng [ESC]','닫기 [G]':'Đóng [G]','닫기 [N]':'Đóng [N]','닫기 [J]':'Đóng [J]',
'전체화면 (F11)':'Toàn màn hình (F11)',
'정말 모든 진행을 초기화하시겠습니까?':'Bạn có thực sự muốn đặt lại tất cả tiến trình không?',
'검출 중...':'Đang phát hiện...',
'마우스 커서':'Con trỏ chuột','그래픽 품질':'Chất lượng đồ họa','하드웨어 진단':'Chẩn đoán phần cứng',
'BGM 선택':'Chọn BGM',
'자동 (스테이지별)':'Tự động (theo giai đoạn)','전체 랜덤':'Tất cả ngẫu nhiên','로비':'Sảnh',
'1장 랜덤':'Chương 1 ngẫu nhiên','2장 랜덤':'Chương 2 ngẫu nhiên','3장 랜덤':'Chương 3 ngẫu nhiên',
'4장 랜덤':'Chương 4 ngẫu nhiên','5장 랜덤':'Chương 5 ngẫu nhiên','6장 랜덤':'Chương 6 ngẫu nhiên','7장 랜덤':'Chương 7 ngẫu nhiên',
'보스':'Trùm','최종보스':'Trùm cuối',
'대장간 랜덤':'Lò rèn ngẫu nhiên','사망 랜덤':'Cái chết ngẫu nhiên','승리 랜덤':'Chiến thắng ngẫu nhiên',
'지옥 추락 사망 징글':'Nhạc rơi địa ngục','탈출 성공':'Thoát thành công',
'── 1장 - 썩은 숲 ──':'── CH1 - Rừng Mục Nát ──','── 2장 - 벌레굴 ──':'── CH2 - Worm Nest ──',
'── 3장 - 얼음굴 ──':'── CH3 - Hang Băng ──','── 4장 - 화염지대 ──':'── CH4 - Infernal Wastes ──',
'── 5장 - 지옥군단 ──':'── CH5 - Quân Đoàn Địa Ngục ──','── 6장 - 사도마굴 ──':'── CH6 - Apostle Den ──',
'── 7장 - 지옥성 ──':'── CH7 - Thành Địa Ngục ──','── 공통 ──':'── Common ──',
'⌨ 조작법':'⌨ Điều khiển','클릭하면 닫힘':'Nhấp để đóng',
'전투력':'SC','가방':'Túi','결정':'Tinh thể',
'↕ 정렬':'↕ Sắp xếp','쓰레기 전체선택':'Chọn tất cả rác','쓰레기 전부 분해':'Phá dỡ tất cả rác',
'창고':'Kho','스탯 포인트':'Điểm thuộc tính','능력치 요약':'Tóm tắt chỉ số','올 리셋':'Đặt lại tất cả',
'대장간':'Lò rèn','스킬':'Kỹ năng','능력치':'Thuộc tính',
'좌클스킬 (클릭 전환)':'Kỹ năng LMB (nhấp để đổi)','우클스킬 (클릭 전환)':'Kỹ năng RMB (nhấp để đổi)',
'이동스킬 (클릭 전환)':'Kỹ năng di chuyển (nhấp để đổi)','마법스킬 (클릭 전환)':'Kỹ năng phép thuật (nhấp để đổi)',
'영역스킬 (클릭 전환)':'Kỹ năng khu vực (nhấp để đổi)','피보호막 (클릭 전환)':'Khiên máu (nhấp để đổi)',
'CT스킬 (클릭 전환)':'Kỹ năng CT (nhấp để đổi)','[J] 능력치':'[J] Thuộc tính',
'무기 공격':'Tấn công vũ khí','칼등 처내기 (투사체 반사, 홀드 연사)':'Đỡ đòn (phản đạn, giữ=loạt)',
'연속 처내기':'Đỡ đòn liên tục','영역 스킬 (폭풍소환 등)':'Kỹ năng khu vực (Lốc xoáy v.v)',
'사슬 발사':'Bắn lao','마법 (탭=투사체, 홀드=빔)':'Phép thuật (chạm=đạn, giữ=tia)',
'데빌포스 흡수':'Hấp thụ sức mạnh quỷ','물약 / 스킬슬롯':'Thuốc / Ô kỹ năng',
'스킬슬롯 5 / 필살기 / CT스킬':'Ô 5 / Tuyệt chiêu / Kỹ năng CT','스킬 슬롯 배정':'Phân công ô kỹ năng',
// --- Phase 27 additions ---
'위로 이동':'Di Chuyển Lên','아래로 이동':'Di Chuyển Xuống','왼쪽 이동':'Di Chuyển Trái','오른쪽 이동':'Di Chuyển Phải',
'칼등 처내기 (탭=처내기, 홀드=연사)':'Đỡ Đòn (chạm=đỡ, giữ=loạt)',
'영역 스킬':'Kỹ năng vùng','사슬 이동':'Xích Móc Câu',
'유령불꽃 켜기/끄기':'Ngọn Lửa Ma Bật/Tắt','기동칼날개 자동 켜기/끄기':'Lưỡi Cánh Tự Động Bật/Tắt',
'해상도':'Độ phân giải',
'빛이 꺼졌다':'Ánh Sáng Tắt Dần','누군가는 너를 기다리고 있다':'Ai đó đang chờ bạn',
'다시 일어서라':'Đứng Dậy Nào','로비로 돌아가기':'Quay về sảnh',
'☠ 사망 리플레이':'☠ Phát lại cái chết',
'지옥의 시련을 견뎌냈다':'Bạn đã chịu đựng thử thách Địa Ngục','계속 전투':'Tiếp tục chiến đấu',
'난이도를 선택하라':'Chọn độ khó',
'나중에 설정(ESC)에서 변경 가능':'Có thể thay đổi sau trong Cài đặt (ESC)',
'일괄합성':'Hợp nhất hàng loạt','일괄강화+합성':'Tăng cường+Hợp nhất hàng loạt',
'자원 부족!':'Thiếu tài nguyên!',' 뎀':' ST',
'합체 폭발!':'Nổ Hợp Nhất!','MP 부족! (50)':'Thiếu MP! (50)',
'부활력 고갈!':'Hồi Sinh Cạn Kiệt!','☠ 부활력 고갈!':'☠ Hồi Sinh Cạn Kiệt!',
'독안개':'Sương Độc','뇌전창':'Thương Sét',
'🔥 업화선 시전...':'🔥 Tia Lửa Địa Ngục đang thi triển...',
'💥 기동파괴 그로기!':'💥 Chuỗi Nghiền Choáng!',
'💥 칼등 그로기!':'💥 Đỡ Đòn Choáng!',
'⚡ 순간이동 준비!':'⚡ Dịch Chuyển Tức Thời Sẵn Sàng!',
'👿악의+1000':'👿Ác ý+1000',
'💀 내려찍기!':'💀 Giáng Đòn!',
'✟ 신성력 억제! +':'✟ Sức Mạnh Thần Thánh Bị Triệt! +',
'✟ 신성력 억제!':'✟ Sức Mạnh Thần Thánh Bị Triệt!',
'✟ 신성력 억제! (':'✟ Sức Mạnh Thần Thánh Bị Triệt! (',
'💥 지진그로기!':'💥 Địa Chấn Choáng!',
'💥 기폭그로기!':'💥 Bùng Nổ Choáng!',
'폭발! ×':'Nổ! ×',
'⚫ 기둥강타!':'⚫ Đập Cột!',
'💥 대왕치기 그로기!':'💥 Đập Đại Vương Choáng!',
'💫 미니스턴!':'💫 Choáng nhẹ!',
'⚡ 뇌전창!':'⚡ Thương Sét!',
'…절반이다. 정신차려.':'…Nửa máu rồi. Tỉnh táo lên.',
'…죽기 직전이다. 한 발만 더.':'…Gần chết rồi. Thêm một đòn nữa.',
'…다음 한 방이 마지막이야.':'…Đòn tiếp theo là cuối cùng.',
'기절! ':'Choáng! ',
'마력이 빈다. 평타 섞어.':'MP đang cạn. Pha thêm đòn thường.',
'그랩이다. 거리를 둬.':'Tấn công nắm bắt. Giữ khoảng cách.',
'광역기다. 멀어져.':'Tấn công diện rộng. Lui ra.',
'…아파? 당연하지. 여긴 지옥이야.':'…Đau không? Hiển nhiên rồi. Đây là Địa Ngục.',
'F키도 스킬 슬롯이야!':'Phím F cũng là ô kỹ năng!',
'L-CTRL로 유령걸음/얼음보주!':'L-CTRL cho Bước Chân Ma/Cầu Băng!',
'N 눌러서 창고에 넣어둬!':'Nhấn N để bỏ vào kho!',
'ESC로 설정! 난이도/자동물약!':'ESC cho cài đặt! Độ khó/Thuốc tự động!',
'잡몹이다. 먼저 정리해.':'Quái thường. Dọn sạch trước.',
'…얼어붙은 놈은 오래 안 간다.':'…Cái bị đóng băng sẽ không tồn tại lâu.',
'…냄새가 짙다. 큰 놈이 있어.':'…Mùi nồng. Có thứ gì đó to gần đây.',
'쉴드는 마법으로, HP는 물리로.':'Khiên nhận phép thuật, HP nhận vật lý.',
'스페이스! 가시덫으로 적 묶어!':'Space! Bẫy kẻ thù bằng Bẫy Gai!',
'근접 너무 많아! 거리 벌려!':'Quá nhiều kẻ ở cận chiến! Rút lui!',
'회전참이나 광역기로 몰아!':'Dùng Chém Xoáy hoặc AOE!',
'F 눌러! 회복의 영역 깔아!':'Nhấn F! Trải Vùng Thiêng Liêng!',
'F키 회복의 영역을 써봐.':'Thử phím F Vùng Thiêng Liêng.',
'빠져! 물약 마시고 회복해.':'Rút lui! Uống thuốc và hồi phục.',
'쉬프트! 사슬기동은 이동기야!':'Shift! Xung Chuỗi là kỹ năng di chuyển!',
'스킬포인트 쌓였어! K 눌러!':'Điểm kỹ năng tích lũy rồi! Nhấn K!',
'스킬 포인트 있어! K!':'Có điểm kỹ năng! K!',
'J키. 패시브 포인트가 쌓여있다.':'Phím C. Điểm bị động đã tích lũy.',
'…쓸 거 아니면 분해해.':'…Phá hủy những gì bạn không dùng.',
'…강화 안 하면 그냥 고철이야.':'…Không tăng cường thì chỉ là sắt vụn.',
'빨간 탄은 우클릭. 무지개는 Q.':'Đạn đỏ: chuột phải. Cầu vồng: Q.',
'빨강=우클릭, 무지개=Q.':'Đỏ=chuột phải, cầu vồng=Q.',
'…멈추지 마. 여신은 기다리지 않는다.':'…Đừng dừng lại. Nữ thần không chờ đợi.',
'패턴이 바뀐다. 거리를 둬.':'Mẫu đang thay đổi. Giữ khoảng cách.',
'미쳐가고 있어. 광폭화다.':'Đang phát điên. Bạo phát.',
'마지막이야! 끝장내!':'Giai đoạn cuối! Kết thúc nó!',
'…끝났다. 다음으로.':'…Xong rồi. Tiếp theo.',
'다 잡았다! 포탈 어딨어?':'Giết hết rồi! Cổng ở đâu?',
'근육으로 만든 빌드군. 베고 부숴.':'Build cơ bắp. Chém và nghiền.',
'활을 쥐었군. 거리를 둬.':'Cầm cung. Giữ khoảng cách.',
'마법사군. MP 관리부터 배워라.':'Pháp sư. Trước tiên học quản lý MP.',
'운에 기댄 빌드군. …드롭은 좋겠어.':'Build dựa vào may mắn. …Ít nhất đồ rơi sẽ tốt.',
'…VIT가 너무 낮아. 한 방에 죽는다.':'…VIT quá thấp. Sẽ chết trong một đòn.',
'다 찍으면 다 약해진다. 하나만 골라.':'Max hết thì yếu hết. Chọn một cái.',
'…3단. 적이 강해져. 정신 차려.':'…Giai đoạn 3. Kẻ thù mạnh hơn. Tập trung.',
'5단이다. …너도 강해졌단 뜻이야.':'Giai đoạn 5. …Có nghĩa là bạn cũng mạnh hơn.',
'…7단. 아직 살아있단 게 신기하군.':'…Giai đoạn 7. Vẫn còn sống. Ngạc nhiên đấy.',
'10단. …너는 이제 인간이 아니야.':'Giai đoạn 10. …Bạn không còn là người nữa.',
'…일반으로 내려왔군. 가끔은 쉬어가야지.':'…Xuống Bình Thường rồi. Đôi khi cần nghỉ ngơi.',
'…이게 진짜 패링이야.':'…Đây mới là đỡ đòn thật sự.',
'…피가 묻기 시작했군.':'…Máu bắt đầu chảy rồi.',
'100. 너는 인간이 아니야.':'100. Bạn không phải con người.',
'…피 흘리며 베는군.':'…Chém xuyên qua máu.',
'빨간콩이 푸르게 변했다. 그게 너의 무기야.':'Hạt đỏ chuyển sang xanh. Đó là vũ khí của bạn.',
'무지개를 받아쳤군. 그건 진짜 어렵다.':'Đỡ được cầu vồng. Thật sự khó đấy.',
'…너무 빨라. 닿기 직전에 눌러.':'…Quá nhanh. Nhấn ngay trước khi chạm.',
'악의가 가득 찼다. 풀어내.':'Ác ý đã đầy. Giải phóng nó.',
'사슬이 살을 뚫었어. 끌고 와.':'Móc câu xuyên thịt rồi. Kéo vào.',
'…풀차지군. 멀리 던져버려.':'…Đầy sức mạnh. Ném đi thật xa.',
'…빈틈을 그대로 빠져나갔다.':'…Trượt qua khe hở.',
'…일반 잡몹이 아니야. 모디파이어 붙었군.':'…Không phải quái thường. Có modifier rồi.',
'엘리트 하나 처리.':'Hạ được một elite.',
'…큰 놈이다. 일반 잡몹 정리부터.':'…Con lớn đó. Dọn quái thường trước.',
'미니보스 처리. 다음 길로.':'Hạ mini-boss. Tiếp tục.',
'한 번에 다섯. 깔끔해.':'Năm cái một lúc. Gọn gàng.',
'100강. 이제 뭔가 다르게 보이는군.':'+100. Giờ mọi thứ trông khác rồi.',
'…운이 없는 날이야.':'…Ngày xui xẻo.',
'…전설이다. 이런 건 처음 본다.':'…Huyền thoại. Chưa từng thấy cái này.',
'…죽었다 살아났네. 여신은 너를 포기 안 했어.':'…Chết rồi sống lại. Nữ thần không từ bỏ bạn.',
'…또야? 패턴 좀 외워!':'…Lại nữa? Học thuộc mẫu đi!',
'…한 번도 안 죽고. 그건 진짜 실력이야.':'…Chưa chết lần nào. Đó là kỹ năng thật sự.',
'…ACT1을 끝냈다. 진짜 시작은 여기서부터야.':'…Hoàn thành HỒI1. Khởi đầu thật sự là ở đây.',
'모든 보스를 무너뜨렸다. 너는 지옥의 일부야.':'Tất cả trùm đã ngã. Bạn là một phần của Địa Ngục.',
'…30초. 너 진짜 미쳤구나.':'…30 giây. Bạn thật sự điên rồi.',
'…빠르군. 효율적이야.':'…Nhanh. Hiệu quả.',
'신기록이다.':'Kỷ lục mới.',
'탭 장비창을 열어봐.':'Mở cửa sổ trang bị bằng TAB.',
'데미지 부족하면 무기 강화!':'Thiếu sát thương? Tăng cường vũ khí!',
// --- Loading screen ---
'불러오는 중...':'Đang tải...',
'로딩중...':'Đang tải...',
'맵과 몬스터 불러오는 중...':'Đang tải bản đồ và quái vật...',
'기본 데이터 준비 중...':'Đang chuẩn bị dữ liệu cơ bản...',
'저장 데이터 불러오는 중...':'Đang tải dữ liệu lưu...',
'몬스터 스킨 로딩...':'Đang tải skin quái vật...',
'맵과 몬스터 생성 중...':'Đang tạo bản đồ và quái vật...',
'맵 에셋 로딩...':'Đang tải tài nguyên bản đồ...',
'맵 환경 준비 중...':'Đang chuẩn bị môi trường bản đồ...',
'주변 청크 준비 중...':'Đang chuẩn bị các chunk lân cận...',
'맵 캐시 생성 중...':'Đang xây dựng cache bản đồ...',
'미니맵 빌드 중...':'Đang xây dựng bản đồ nhỏ...',
// Phase 28
' 으로 탈출!':' để thoát!',
'100명?! 미쳤어!':'100 mạng?! Điên rồi!',
'10단 최고난이도! 너 진짜 광기야!':'Độ khó 10 tối đa! Hoàn toàn điên!',
'1분 안에 클리어! 빠르네!':'Qua màn trong 1 phút! Nhanh quá!',
'30초!! 스피드런 가능해!':'30 giây!! Tiềm năng speedrun!',
'3단! 보상도 좋아지지만 죽기 쉬워!':'Độ khó 3! Phần thưởng tốt hơn nhưng dễ chết!',
'50명! 학살자야!':'50 mạng! Kẻ tàn sát!',
'5단!! 진짜 게이머 인증!':'Độ khó 5!! Game thủ thực thụ!',
'7단!! 다른 사람들 이 정도 못 와!':'Độ khó 7!! Người khác không đến được đây!',
'ACT1 완주! 우리가 진짜 해냈어!':'ACT1 hoàn thành! Chúng ta thực sự làm được!',
'Ctrl 얼음보주로 탈출하라.':'Ctrl — thoát bằng Cầu Băng.',
'Ctrl 유령걸음으로 탈출하라.':'Ctrl — thoát bằng Bước Ma.',
'J키! 패시브 강해져!':'Phím C! Bị động mạnh hơn!',
'DEX 빌드! 거리에서 패고, 추적탄 좋아!':'Build DEX! Tấn công tầm xa, đạn truy đuổi!',
'E로 마력공격을 해봐!':'Thử tấn công phép với E!',
'G 눌러서 대장간 가봐!':'Nhấn G — lò rèn!',
'G키 대장간. 강화 안 하면 계속 죽어.':'G — lò rèn. Không nâng cấp, cứ chết thôi.',
'HP 70%! 조심해!':'HP 70%! Cẩn thận!',
'INT 빌드! 빔이랑 폭발 마법! MP 잘 봐!':'Build INT! Tia và phép nổ! Theo dõi MP!',
'LCK 높아! 레어 드롭률 미친 거 알지?':'LCK cao! Tỷ lệ rơi đồ điên lắm!',
'L로 어디에 뭘 넣을지 골라!':'Nhấn L — chọn cài đặt ô kỹ năng!',
'MP 부족! 평타로 패면서 회복해!':'MP thấp! Đánh để hồi phục!',
'ST 없으면 스킬 못 써!':'Không ST, không kỹ năng!',
'STR 빌드! 회전참, 회오리, 광역기 추천!':'Build STR! Chém quay, lốc xoáy, AoE!',
'VIT 좀 찍어! HP 너무 적어!':'Thêm VIT! HP quá thấp!',
'Z 누르면 대박! 쿨타임 길어!':'Nhấn Z cho tuyệt chiêu! Hồi chiêu dài!',
'…고기 냄새. 싫진 않네.':'…Mùi máu. Không tệ.',
'…둘러싸이면 끝이야.':'…Bị bao vây là xong.',
'…말은 못해.':'…Không nói được.',
'…버리기 아까운 건 창고에.':'…Cất đồ quý vào kho.',
'…빈틈을 노려.':'…Chú ý sơ hở.',
'…설정을 확인해.':'…Kiểm tra cài đặt.',
'…슬롯을 채워. 빈 손은 죽음이다.':'…Lấp đầy ô. Tay trống là cái chết.',
'…아직 살아있네. 좌클릭으로 저것들 쳐봐.':'…Vẫn còn sống. Click trái để đánh chúng.',
'…운이 좋았을 뿐이야. 아마.':'…Chỉ may mắn thôi. Có lẽ vậy.',
'…치는 건 할 줄 아네. 피하는 건?':'…Biết đánh. Còn tránh thì sao?',
'…힘을 골라라. 전부 가질 순 없다.':'…Chọn sức mạnh của mình. Không thể có tất cả.',
'골고루 안 돼! 하나로 밀어!':'Đừng dàn trải! Đẩy một chỉ số!',
'그로기 터지면 1.5배!':'Groggy = thiệt hại 1.5x!',
'길이 열렸다.':'Con đường đã mở.',
'나머진 전부 우클릭 패링 가능!':'Còn lại — click phải parry!',
'나머진 전부 우클릭!':'Còn lại — click phải!',
'다섯 번 연속! 내가 본 인간 중 최고!':'Năm lần liên tiếp! Giỏi nhất ta thấy!',
'다음엔 죽지 마!':'Lần sau đừng chết!',
'소환수 왔어! 먼저 처리해야 해!':'Quái triệu hồi! Xử lý chúng trước!',
'스킬 없으면 방향키 연타뿐이야.':'Không kỹ năng? Chỉ spam phím mũi tên.',
'신기록!! 스트리머한테 보내!':'Kỷ lục mới!! Gửi cho streamer!',
'아이템 넘쳐! 우리가 주워줄게!':'Túi đầy! Chúng tôi sẽ nhặt hộ!',
'안 죽고 깼어! 진짜 천재 맞네!':'Qua màn không chết! Thiên tài thật sự!',
'앞으로 가자~':'Tiến lên thôi~',
'우리가 해냈어! 다음 챕터 가자!':'Chúng ta làm được rồi! Chương tiếp theo!','핵터 니가 진짜 해냈구나, 여왕님이 기뻐하시겠어!':'Hector, cậu thực sự đã làm được! Nữ hoàng sẽ hài lòng đấy!',
'일반 모드! 편하게 즐기자!':'Chế độ thường! Thoải mái chơi!',
'자원이 반이다. F키로 회복해.':'Tài nguyên còn nửa. F để hồi phục.',
'잡힌다! 옆으로 빠져!':'Bị bắt rồi! Né sang bên!',
'장비 분해해! 쓰레기도 악의!':'Phân giải trang bị! Rác cũng cho độc ý!',
'전부 다 잡았어! 우리가 지옥의 왕이야!':'Dọn sạch rồi! Chúng ta là vua địa ngục!',
'좋은 거 나왔다! TAB!':'Đồ tốt! TAB!',
'죽기 직전에 죽이다니! 멋져!':'Hạ địch ngay trước khi chết! Tuyệt vời!',
'체력 반 남았어! 물약 마실 타이밍!':'HP còn nửa! Uống thuốc đi!',
'큰 거 온다! 도망쳐!':'Đòn lớn đến! Chạy!',
'패링으로 돌려주고, Q 보호막도 써!':'Parry và phản chiếu, dùng khiên Q nữa!',
'패턴이 빨라졌어!':'Chiêu thức nhanh hơn rồi!',
'한 대만 맞아도 죽어! 패링이든 회피든!!':'Một đòn là chết! Parry hoặc né!!',
'한 방이면 죽어! 도망쳐!!':'Một phát là xong! Chạy!!',
'화염엔 빙결! 암전엔 암흑!':'Lửa → băng! Hư không → bóng tối!',
'기절! ':'Choáng! ',
'── 2장 - 벌레굴 ──':'── CH2 - Hang Giun ──',
'── 4장 - 화염지대 ──':'── CH4 - Vùng Lửa ──',
'── 6장 - 사도마굴 ──':'── CH6 - Hang Tông Đồ ──',
'── 공통 ──':'── Chung ──',
'☠ 부활력 고갈!':'☠ Hồi Sinh Cạn Kiệt!',
'⏳⚡ 시간걸음!':'⏳⚡ Bước Thời Gian!',
'블룸 효과':'Hiệu ứng Bloom',
'잔상 트레일':'Vệt ảnh lưu',
'슬래시 이펙트':'Hiệu ứng chém',
'후처리 효과':'Hậu xử lý',
'사망 이펙트':'Hiệu ứng chết',
'동적 조명':'Ánh sáng động',
'횃불 조명 (어둠)':'Ánh đuốc (tối)',
'앰비언트 파티클':'Hạt môi trường',
'안개 효과':'Hiệu ứng sương mù',
'필름 그레인':'Hạt phim',
'캐릭터 외곽선':'Đường viền nhân vật',
'리롤':'Tái đổ',
'물약':'Thuốc',
'으로 탈출!':'để thoát!',
'Shift 사슬':'Shift Xích',
'더블탭 전격이동':'Nhấn đúp — Lướt điện',
'Ctrl 유령걸음':'Ctrl Bước Ma',
'Ctrl 얼음보주':'Ctrl Cầu Băng',
'🔴화염→빙결 2배 | 🔵빙결→화염 2배 | ⚪물리=중립 | 악마 처치 시 악의 영혼 드롭':'🔴Lửa→Băng 2× | 🔵Băng→Lửa 2× | ⚪Vật lý=Trung tính | Giết quỷ lấy linh hồn ác ý',
  '미구현':'Chưa Có',
  '스탯 총량':'Tổng chỉ số',
  '장비':'trang bị',
  '공속':'tốc đánh',
  '크리':'chí mạng',
  '크리뎀':'sát thương chí mạng',
  '근성':'Kiên nhẫn',
  '종합 지표':'Tổng quan',
  '근접 DPS':'DPS cận chiến',
  '공격력×공속×크리':'ATK×Tốc×Crit',
  '활 DPS':'DPS cung',
  '마법 DPS':'DPS phép',
  '유효 HP (EHP)':'HP hiệu quả (EHP)',
  '쉴드':'Khiên',
  '장비 파워':'Sức mạnh đồ',
  '근접 공격력':'ATK cận chiến',
  '기본':'cơ bản',
  '무기':'vũ khí',
  '패시브':'bị động',
  '활 공격력':'ATK cung',
  '정밀':'Chính xác',
  '마법 공격력':'ATK phép',
  '왕관':'vương miện',
  '마력':'Bí thuật',
  '공격속도':'Tốc độ đánh',
  '크리티컬':'Chí mạng',
  '데미지':'sát thương',
  '확률':'Xác suất',
  '어픽스':'tiền tố',
  '레거시':'di sản',
  '추가뎀':'sát thương bổ sung',
  '패링 카운터뎀':'Sát thương Parry',
  '우클공속':'Tốc độ chuột phải',
  '무지개탄DR':'DR cầu vồng',
  '포이즈파괴':'Phá Poise',
  '방어관통':'Xuyên giáp',
  '관통력':'Xuyên thủng',
  '속성':'Nguyên tố',
  '무기속성':'Nguyên tố vũ khí',
  '독':'Độc',
  '초':'g',
  '암흑저주':'Lời nguyền tối',
  '원소집중':'Tập trung nguyên tố',
  '원소전환':'Chuyển đổi nguyên tố',
  '방어':'Phòng thủ',
  '물리방어':'DEF vật lý',
  '감소':'giảm',
  '캡':'giới hạn',
  '장갑':'găng tay',
  '바지':'quần',
  '속성방어':'DEF nguyên tố',
  '목걸이':'vòng cổ',
  '반지1':'nhẫn1',
  '반지2':'nhẫn2',
  '반사':'Phản xạ',
  '가시':'Gai',
  '배리어':'Rào cản',
  '보호막 흡수':'Hấp thụ khiên',
  '속성 저항':'Kháng nguyên tố',
  'CC저항':'Kháng CC',
  '생존':'Sinh tồn',
  '장비HP':'HP đồ',
  '임플':'Impl.',
  '에너지쉴드':'Khiên năng lượng',
  '리젠':'Hồi phục',
  '스태미나':'Thể lực',
  '성장':'Tăng trưởng',
  'MP%어픽스':'Tiền tố MP%',
  '이동속도':'Tốc độ di chuyển',
  '한방캡':'Giới hạn một phát',
  '최대HP의33%':'33% HP tối đa',
  '비용/효율':'Chi phí/Hiệu quả',
  '근접ST':'ST cận chiến',
  '활ST':'ST cung',
  '마법MP':'MP phép',
  '사슬사거리':'Tầm xa lao',
  '기동게이지':'Thanh Drive',
  '쿨감':'Giảm Hồi',
  '쇠뇌뎀':'Sát thương nỏ',
  '쇠뇌공속':'Tốc độ nỏ',
  '기타':'Khác',
  '물약쿨':'CD thuốc',
  '회복+':'Hồi phục+',
  '드롭':'Vật phẩm',
  '경험치+':'EXP+',
  '골드+':'Vàng+',
  '기동:칼날개':'Drive:Lưỡi',
  '기동:전폭':'Drive:Tấn công',
  '기동:기습':'Drive:Phục kích',
  '충전스킬':'Kỹ năng tích điện',
  '사슬게이지':'Thanh xích',
  '특수 효과':'Hiệu ứng đặc biệt',
  '처치뎀+':'Sát thương hạ gục+',
  '위기뎀+':'Sát thương nguy cấp+',
  '피격반격':'Phản đòn khi bị đánh',
  '풍요(적HP≥70%뎀+)':'Dồi dào(HP≥70%+)',
  '약자포식(적HP≤30%뎀+)':'Săn mồi(HP≤30%+)',
  '패링폭발':'Nổ tung Parry',
  '체간파괴+':'Phá Poise+',
  '콤보뎀+':'Sát thương combo+',
  '사슬뎀+':'Sát thương lao+',
  '스킬뎀+':'Sát thương kỹ năng+',
  '패리+':'Đỡ đòn+',
  '체인':'Xích',
  '정화':'Thanh tẩy',
  '회':'×',
  '불굴':'Kiên cường',
  '신성력':'Sức mạnh thần thánh',
  '악마력(부활력)':'Sức mạnh quỷ',
  '자연':'Tự nhiên',
  '악마성':'Bản chất quỷ',
  '인간성':'Nhân tính',
  '전투 통계':'Thống kê chiến đấu',
  '핵터':'Hecter',
'디로이':'Deroy',
// --- Phase 37: skill desc ---
'벤치 FPS:':'FPS thử nghiệm:',
// --- CAT-82: skill panel labels ---
'스킬 정보':'Thông Tin Kỹ Năng',
'타입':'Loại',
'미습득':'Chưa Học',
'SP 비용':'Chi Phí SP',
'악의 비용':'Chi Phí Ác Ý',
'쿨다운':'Hồi chiêu',
'요구 레벨':'Yêu Cầu Cấp',
'기본 참조뎀':'Sát Thương Tham Chiếu',
'스탯 배율':'Hệ Số Chỉ Số',
'패시브 배율':'Hệ Số Nội Tại',
'레벨 배율':'Hệ Số Cấp',
'예상 평균 뎀':'Sát Thương TB Ước Tính',
'치명타':'Bạo Kích',
'치명타 확률':'Tỷ Lệ Bạo',
'치명타 배율':'Hệ Số Bạo',
'유효 배율':'Hệ Số Hiệu Quả',
'스킬 고유':'Đặc Thù Kỹ Năng',
'1타 배율':'Hệ Số Đòn 1',
'2타 배율':'Hệ Số Đòn 2',
'3타 배율':'Hệ Số Đòn 3',
'레벨당 뎀':'Sát Thương Mỗi Cấp',
'검기 거리':'Tầm Khí Kiếm',
'레벨당 거리':'Tầm Thêm Mỗi Cấp',
'ST/틱':'ST/Tick',
'레벨당 크기':'Kích Thước Mỗi Cấp',
'넉백':'Đẩy Lùi',
'충전 시간':'Thời Gian Tích',
'레벨당 범위':'Tầm Mỗi Cấp',
'관통률':'Tỷ Lệ Xuyên',
'지속뎀':'Thời Gian DoT',
'무한':'Vô Hạn',
'타격 형식':'Loại Đánh',
'진동파':'Sóng Xung',
'스태거':'Choáng',
'높음':'Cao',
'스톡':'Dự Trữ',
'기둥 수':'Số Trụ',
'지속':'Thời Gian',
'반경':'Bán kính',
'슬로우':'Chậm',
'활':'Nỏ',
// --- CAT-83: affix desc labels ---
'독 DoT':'DoT Độc',
'화상 DoT':'DoT Bỏng',
'빙결 DoT+감속':'DoT Băng+Chậm',
'저주(힐차단)':'Nguyền(Chặn Hồi)',
'방어무시':'Bỏ Qua Giáp',
'치명타율':'Tỷ Lệ Bạo',
'스태거+':'Choáng+',
'체인타겟+':'Mục Tiêu Liên Hoàn+',
'처치 후 뎀+':'Sát Thương Sau Giết+',
'크리폭발(ATK×)':'Nổ Bạo(ATK×)',
'원소뎀+':'Sát Thương Nguyên Tố+',
'공격속도+':'Tốc Đánh+',
'패리보너스+':'Thưởng Đỡ+',
'추적콤보+10':'Combo Truy Vết+10',
'사슬뎀+':'Xích DMG+',
'쿨다운-':'Hồi Chiêu-',
'방어력+':'Phòng Thủ+',
'쉴드+':'Khiên+',
'이동속도+':'Tốc Di Chuyển+',
'크리확률+':'Tỷ Lệ Bạo+',
'크리배율+':'Bội Số Bạo+',
'화염저항':'Kháng Lửa',
'빙결저항':'Kháng Băng',
'암전저항':'Kháng Sét',
'암흑저항':'Kháng Bóng Tối',
'독저항':'Kháng Độc',
'전원소저항':'Kháng Toàn Nguyên Tố',
'물리DR':'Giảm Vật Lý',
'반사%':'Phản Xạ%',
'가시뎀':'Sát Thương Gai',


'패링폭발(ATK×)':'Nổ Đỡ(ATK×)',
'체간파괴뎀+':'Sát Thương Phá Thế+',
'상태이상해제':'Giải Trạng Thái',
'불굴(1회생존)':'Bất Khuất(Sống 1 lần)',
'부활(HP회복)':'Hồi Sinh(Hồi HP)',
'드롭률+':'Tỷ Lệ Rơi+',
'경험치+':'EXP+',
'포션회복+':'Hồi Thuốc+',
'사슬게이지+':'Thanh Xích+',
'부활억제':'Ngăn Hồi Sinh',
'부활력+':'Sức Hồi Sinh+',
'부활쿨-':'Hồi Hồi Sinh-',
'최대HP%+':'HP Tối Đa%+',
'HP리젠+':'Hồi HP+',
'회복력+':'Sức Hồi+',
'마법뎀+':'Sát Thương Pháp+',
'MP소비-':'Tiêu Hao MP-',
'화염뎀%+':'Sát Thương Lửa%+',
'화염관통%':'Xuyên Lửa%',
'적중화상':'Đánh Trúng Gây Bỏng',
'크리화폭':'Bạo Nổ Lửa',
'화상지속+':'Kéo Dài Bỏng+',
'화염뎀보너스':'Thưởng Sát Thương Lửa',
'빙결뎀%+':'Sát Thương Băng%+',
'빙결관통%':'Xuyên Băng%',
'적중빙결':'Đánh Trúng Gây Băng',
'크리빙폭':'Bạo Nổ Băng',
'빙결지속+':'Kéo Dài Băng+',
'빙결뎀보너스':'Thưởng Sát Thương Băng',
'뇌전뎀%+':'Sát Thương Sét%+',
'뇌전관통%':'Xuyên Sét%',
'적중감전':'Đánh Trúng Gây Giật',
'크리뇌폭':'Bạo Nổ Sét',
'감전지속+':'Kéo Dài Giật+',
'뇌전뎀보너스':'Thưởng Sát Thương Sét',
'암흑뎀%+':'Sát Thương Bóng Tối%+',
'암흑관통%':'Xuyên Bóng Tối%',
'적중저주':'Đánh Trúng Gây Nguyền',
'크리암폭':'Bạo Nổ Bóng Tối',
'저주지속+':'Kéo Dài Nguyền+',
'암흑뎀보너스':'Thưởng Sát Thương Bóng Tối',
'독뎀%+':'Sát Thương Độc%+',
'독관통%':'Xuyên Độc%',
'적중중독':'Đánh Trúng Gây Độc',
'크리독폭':'Bạo Nổ Độc',
'독지속+':'Kéo Dài Độc+',
'독뎀보너스':'Thưởng Sát Thương Độc',
'근접뎀%+':'Sát Thương Cận%+',
'원거리뎀%+':'Sát Thương Xa%+',
'마법뎀%+':'Sát Thương Pháp%+',
'빔뎀%+':'Sát Thương Tia%+',
'DoT뎀%+':'Sát Thương DoT%+',
'투사체뎀%+':'Sát Thương Đạn%+',
'범위반경+':'Bán Kính+',
'근접크리+':'Bạo Cận+',
'마법크리+':'Bạo Pháp+',
'석궁크리+':'Bạo Nỏ+',
'근접공속+':'Tốc Cận+',
'석궁공속+':'Tốc Nỏ+',
'시전속도+':'Tốc Niệm+',
'전속성관통':'Xuyên Toàn Nguyên Tố',
'쉴드관통':'Xuyên Khiên',
'방어력깎기':'Giảm Giáp',
'투사체속도+':'Tốc Đạn+',
'적중시화구':'Đánh Trúng Ra Cầu Lửa',
'적중시연쇄뇌격':'Đánh Trúng Ra Sét Liên Hoàn',
'적중빙결%':'Đánh Trúng Băng%',
'적중스턴%':'Đánh Trúng Choáng%',
'적중중독%':'Đánh Trúng Độc%',
'적중출혈%':'Đánh Trúng Chảy Máu%',
'적중약화%':'Đánh Trúng Làm Yếu%',
'적중감속%':'Đánh Trúng Chậm%',
'적중표적%':'Đánh Trúng Đánh Dấu%',
'크리폭발(HP%)':'Nổ Bạo(HP%)',
'크리연쇄(HP%)':'Liên Hoàn Bạo(HP%)',
'크리빙결%':'Bạo Băng%',
'크리HP+':'HP Bạo+',
'크리MP+':'MP Bạo+',
'크리쉴드+':'Khiên Bạo+',
'피격방어+':'Phòng Thủ Khi Bị Đánh+',
'반격가시':'Gai Phản Đòn',
'빙결파동%':'Sóng Băng%',
'자동암흑막':'Màn Bóng Tối Tự Động',
'주기치유':'Hồi Máu Định Kỳ',
'시체폭발%':'Nổ Xác%',
'회피뎀+':'Sát Thương Né+',
'패링폭발%':'Nổ Đỡ%',
'블록HP+':'HP Chặn+',
'블록MP+':'MP Chặn+',
'회전참뎀+':'Sát Thương Toàn Phong+',
'옴니빔뎀+':'Sát Thương Tia Toàn Diện+',
'화구뎀+':'Sát Thương Cầu Lửa+',
'미사일뎀+':'Sát Thương Tên Lửa+',
'청탄뎀+':'Sát Thương Đạn Xanh+',
'폭렬탄뎀+':'Sát Thương Đạn Nổ+',
'지옥광선뎀+':'Sát Thương Tia Địa Ngục+',
'악의폭풍뎀+':'Sát Thương Bão Ác Ý+',
'연쇄참뎀+':'Sát Thương Chém Liên Hoàn+',
'거인강타뎀+':'Sát Thương Đập Khổng Lồ+',
'유령보행뎀+':'Sát Thương Bước Ma+',
'악의박격뎀+':'Sát Thương Cối Ác Ý+',
'화염오라뎀+':'Sát Thương Hào Quang Lửa+',
'빙구뎀+':'Sát Thương Cầu Băng+',
'화염빔뎀+':'Sát Thương Tia Lửa+',
'악의사냥뎀+':'Sát Thương Săn Ác Ý+',
'암흑기둥뎀+':'Sát Thương Trụ Bóng Tối+',
'역병뎀+':'Sát Thương Dịch Bệnh+',
'가시오라뎀+':'Sát Thương Hào Quang Gai+',
'연쇄돌격뎀+':'Sát Thương돌격 Liên Hoàn+',
'회피확률+':'Tỷ Lệ Né+',
'회피쿨-':'Hồi Né-',
'쉴드%+':'Khiên%+',
'쉴드리젠%+':'Hồi Khiên%+',
'쉴드쿨-':'Hồi Khiên-',
'HP리젠%+':'Hồi HP%+',
'ST리젠+':'Hồi ST+',
'ST리젠%+':'Hồi ST%+',
'MP리젠+':'Hồi MP+',
'MP리젠%+':'Hồi MP%+',
'화염DR':'Giảm Lửa',
'빙결DR':'Giảm Băng',
'뇌전DR':'Giảm Sét',
'암흑DR':'Giảm Bóng Tối',
'독DR':'Giảm Độc',
'전체DR':'Giảm Tất Cả',
'엘리트DR':'Giảm Tinh Anh',
'스턴저항':'Kháng Choáng',
'감속저항':'Kháng Chậm',
'넉백저항':'Kháng Đẩy Lùi',
'돌진거리+':'Tầm Lướt+',
'돌진쿨-':'Hồi Lướt-',
'전투이속+':'Tốc Di Chuyển Chiến Đấu+',
'비전투이속+':'Tốc Di Chuyển Ngoài Chiến+',
'습득범위+':'Tầm Nhặt+',
'전스탯+':'Toàn Chỉ Số+',
'적중자원+':'Tài Nguyên Khi Đánh+',
'화염최대저항+':'Kháng Lửa Tối Đa+',
'빙결최대저항+':'Kháng Băng Tối Đa+',
'뇌전최대저항+':'Kháng Sét Tối Đa+',
'암흑최대저항+':'Kháng Bóng Tối Tối Đa+',
'독최대저항+':'Kháng Độc Tối Đa+',
'스킬쿨-':'Hồi Kỹ Năng-',
'물약쿨-':'Hồi Thuốc-',
'강화성공+':'Tỷ Lệ Cường Hóa+',
'악의획득+':'Nhận Ác Ý+',
'악마화뎀+':'Sát Thương Quỷ Hóa+',
'악마화DR':'Giảm Quỷ Hóa',
'영혼수확+':'Thu Hoạch Hồn+',
'생명흡혈%':'Hút Sinh Mệnh%',
'과치유→쉴드':'Hồi Dư→Khiên',
'만마나뎀+':'Sát Thương Đầy MP+',
'이동DR':'Giảm Di Chuyển',
'정지뎀+':'Sát Thương Đứng Yên+',
'회피후뎀+':'Sát Thương Sau Né+',
'패링쉴드+':'Khiên Đỡ+',
'콤보보너스+':'Thưởng Combo+',
'HP≥70%뎀+':'Sát Thương HP≥70%+',
'적HP≤30%뎀+':'Sát Thương Địch HP≤30%+',
'HP100%뎀+':'Sát Thương HP100%+',
'HP≤35%뎀+':'Sát Thương HP≤35%+',
'적HP≤20%뎀+':'Sát Thương Địch HP≤20%+',
'근접뎀+':'Sát Thương Cận+',
'원거리뎀+':'Sát Thương Xa+',
'스턴적뎀+':'Sát Thương Địch Choáng+',
'빙결적뎀+':'Sát Thương Địch Băng+',
'화상적뎀+':'Sát Thương Địch Bỏng+',
'중독적뎀+':'Sát Thương Địch Độc+',
'저주적뎀+':'Sát Thương Địch Nguyền+',
'감속적뎀+':'Sát Thương Địch Chậm+',
'보스뎀+':'Sát Thương Boss+',
'엘리트뎀+':'Sát Thương Tinh Anh+',
'일반몹뎀+':'Sát Thương Quái Thường+',
'선제뎀+':'Sát Thương Tiên Phát+',
'물리흡혈%':'Hút Vật Lý%',
'마나흡수%':'Hút Mana%',
'ST흡수%':'Hút ST%',
'적중HP+':'HP Khi Đánh+',
'처치HP+':'HP Khi Giết+',
'처치MP+':'MP Khi Giết+',
'처치ST+':'ST Khi Giết+',
'처치시폭발':'Nổ Khi Giết',
'처치이속+':'Tốc Di Chuyển Khi Giết+',
'HP≥70%방어+':'Phòng Thủ HP≥70%+',
'HP≤50%이속+':'Tốc Di Chuyển HP≤50%+',
'DoT피해감소':'Giảm Sát Thương DoT',
'보스피해감소':'Giảm Sát Thương Boss',
'근접피해감소':'Giảm Sát Thương Cận',
'원거리피해감소':'Giảm Sát Thương Xa',
'처치HP회복':'Hồi HP Khi Giết',
'처치쉴드회복':'Hồi Khiên Khi Giết',
'ST소비-':'Tiêu Hao ST-',
'HP≥70%공격+':'ATK HP≥70%+',
'HP≤35%흡혈':'Hút Máu HP≤35%',
'보스추가뎀':'Thêm Sát Thương Boss',
'엘리트추가뎀':'Thêm Sát Thương Tinh Anh',
'공격력+':'ATK+',
'크리뎀+':'Sát Thương Bạo+',
// --- CAT-84/85/86: affix names + implicit + legendary ---
'지속의':'Bền Bỉ',
'마나의':'Mana',
'원소수호의':'Hộ Vệ Nguyên Tố',
'행운의':'May Mắn',
'근성의':'Kiên Trì',
'풍요의':'Phong Nhiêu',
'약자포식의':'Săn Mồi Yếu',
'만혈의':'Đầy Máu',
'사선의':'Cận Tử',
'처형의':'Hành Hình',
'근접살의':'Sát Thương Cận',
'원거리의':'Tầm Xa',
'경직파의':'Phá Choáng',
'동파의':'Phá Băng',
'연소의':'Thiêu Đốt',
'맹독살의':'Giết Độc',
'저주살의':'Giết Nguyền',
'구속의':'Trói Buộc',
'왕살의':'Giết Boss',
'정예살의':'Giết Tinh Anh',
'군살의':'Giết Đám Đông',
'선제의':'Tiên Phát',
'흡혈의':'Hút Máu',
'흡마의':'Hút Mana',
'흡정의':'Hút ST',
'타격재생의':'Hồi Khi Đánh',
'처치회복의':'Hồi Khi Giết',
'처치흡마의':'Hút Mana Khi Giết',
'처치활력의':'ST Khi Giết',
'처치폭발의':'Nổ Khi Giết',
'처치질주의':'Nước Rút Khi Giết',
'건강방어의':'Phòng Thủ Khỏe Mạnh',
'중상보호의':'Khiên Trọng Thương',
'위기질주의':'Nước Rút Khủng Hoảng',
'지속피해방어의':'Giảm Sát Thương DoT',
'왕피해방어의':'Giảm Sát Thương Boss',
'근접방어의':'Giảm Sát Thương Cận',
'원거리방어의':'Giảm Sát Thương Xa',
'처치생명의':'HP Khi Giết',
'처치수호의':'Khiên Khi Giết',
'화염강화의':'Tăng Lửa',
'화염관통의':'Xuyên Lửa',
'발화의':'Bốc Cháy',
'화염폭발의':'Nổ Lửa',
'맹화의':'Bùng Cháy',
'화염의힘':'Sức Mạnh Lửa',
'빙결강화의':'Tăng Băng',
'빙결관통의':'Xuyên Băng',
'동결의':'Đông Cứng',
'빙결폭발의':'Nổ Băng',
'영빙의':'Băng Vĩnh Cửu',
'빙결의힘':'Sức Mạnh Băng',
'뇌전강화의':'Tăng Sét',
'뇌전관통의':'Xuyên Sét',
'감전의':'Giật Điện',
'뇌전폭발의':'Nổ Sét',
'낙뢰의':'Sấm Sét',
'뇌전의힘':'Sức Mạnh Sét',
'암흑강화의':'Tăng Bóng Tối',
'암흑관통의':'Xuyên Bóng Tối',
'침식의':'Ăn Mòn',
'암흑폭발의':'Nổ Bóng Tối',
'심연의':'Vực Sâu',
'암흑의힘':'Sức Mạnh Bóng Tối',
'맹독강화의':'Tăng Độc Mạnh',
'독관통의':'Xuyên Độc',
'중독의':'Nhiễm Độc',
'독폭발의':'Nổ Độc',
'맹독지속의':'Độc Kéo Dài',
'독의힘':'Sức Mạnh Độc',
'격투의':'Cận Chiến',
'원사의':'Bắn Xa',
'주술의':'Phép Thuật',
'광선의':'Tia',
'탄도의':'Đạn Đạo',
'확산의':'Diện Tích',
'근접회심의':'Bạo Cận',
'마법회심의':'Bạo Pháp',
'사격회심의':'Bạo Xa',
'근접쾌속의':'Tốc Cận',
'사격쾌속의':'Tốc Xa',
'영창의':'Tụng Niệm',
'전속성관통의':'Xuyên Toàn Nguyên Tố',
'쉴드파괴의':'Phá Khiên',
'갑옷분쇄의':'Nghiền Giáp',
'탄속의':'Tốc Đạn',
'화구발사의':'Bắn Cầu Lửa',
'연쇄뇌격의':'Sét Liên Hoàn',
'동결타의':'Đòn Đóng Băng',
'경직타의':'Đòn Choáng',
'독침의':'Kim Độc',
'출혈의':'Chảy Máu',
'약화의':'Làm Yếu',
'둔화의':'Làm Chậm',
'표적의':'Đánh Dấu',
'회심폭발의':'Bạo Nổ',
'회심연쇄의':'Bạo Liên Hoàn',
'회심빙결의':'Bạo Đóng Băng',
'회심치유의':'Bạo Hồi Máu',
'회심영력의':'Bạo Mana',
'회심수호의':'Bạo Khiên',
'피격강화의':'Tăng Khi Bị Đánh',
'반격가시의':'Gai Phản Đòn',
'빙결파동의':'Sóng Băng',
'암흑보호의':'Khiên Bóng Tối',
'치유파동의':'Sóng Hồi Máu',
'시체폭발의':'Nổ Xác',
'회피반격의':'Phản Đòn Né',
'패링폭파의':'Nổ Đỡ',
'블록치유의':'Hồi Máu Chặn',
'블록영력의':'Mana Chặn',
'회전참강화':'Tăng Toàn Phong',
'옴니빔강화':'Tăng Tia Toàn Diện',
'화구강화':'Tăng Cầu Lửa',
'미사일강화':'Tăng Tên Lửa',
'청탄강화':'Tăng Đạn Xanh',
'폭렬탄강화':'Tăng Đạn Nổ',
'지옥광선강화':'Tăng Tia Địa Ngục',
'악의폭풍강화':'Tăng Bão Ác Ý',
'연쇄참강화':'Tăng Chém Liên Hoàn',
'거인강타강화':'Tăng Đập Khổng Lồ',
'유령보행강화':'Tăng Bước Ma',
'악의박격강화':'Tăng Cối Ác Ý',
'화염오라강화':'Tăng Hào Quang Lửa',
'빙구강화':'Tăng Cầu Băng',
'화염빔강화':'Tăng Tia Lửa',
'악의사냥강화':'Tăng Săn Ác Ý',
'암흑기둥강화':'Tăng Trụ Bóng Tối',
'역병강화':'Tăng Dịch Bệnh',
'가시오라강화':'Tăng Hào Quang Gai',
'연쇄돌격강화':'Tăng돌격 Liên Hoàn',
'회피의':'Né Tránh',
'회피쿨감의':'Giảm Hồi Né',
'수호력의':'Sức Khiên',
'수호재생의':'Hồi Khiên',
'수호쿨감의':'Giảm Hồi Khiên',
'재생력의':'Sức Hồi',
'활력재생의':'Hồi ST',
'마력재생의':'Hồi Mana',
'화염보호의':'Khiên Lửa',
'빙결보호의':'Khiên Băng',
'뇌전보호의':'Khiên Sét',
'해독의':'Giải Độc',
'만물보호의':'Khiên Toàn Diện',
'정예보호의':'Khiên Tinh Anh',
'경직저항의':'Kháng Choáng',
'빙결저항의':'Kháng Băng',
'감속저항의':'Kháng Chậm',
'넉백저항의':'Kháng Đẩy Lùi',
'돌진거리의':'Tầm Lướt',
'돌진쿨감의':'Giảm Hồi Lướt',
'전투질주의':'Chạy Chiến Đấu',
'평화질주의':'Chạy Bình Yên',
'습득범위의':'Tầm Nhặt',
'힘의':'Sức Mạnh',
'민첩의':'Nhanh Nhẹn',
'지능의':'Trí Tuệ',
'만능의':'Đa Năng',
'지구력의':'ST Tối Đa',
'마나력의':'Sức Mana',
'타격자원의':'Tài Nguyên Khi Đánh',
'화염한계의':'Giới Hạn Lửa',
'빙결한계의':'Giới Hạn Băng',
'뇌전한계의':'Giới Hạn Sét',
'암흑한계의':'Giới Hạn Bóng Tối',
'독한계의':'Giới Hạn Độc',
'스킬쿨감의':'Giảm Hồi Kỹ Năng',
'물약쿨감의':'Giảm Hồi Thuốc',
'장인의':'Thợ Thủ Công',
'탐욕의':'Tham Lam',
'수련의':'Luyện Tập',
'수집의':'Thu Thập',
'악마의힘':'Sức Mạnh Quỷ',
'악마보호의':'Khiên Quỷ',
'영혼수확의':'Thu Hoạch Hồn',
'생명흡수의':'Hút Sinh Mệnh',
'과치유수호의':'Khiên Chữa Lành Dư',
'만마력의':'Đầy Mana Sát Thương',
'이동방어의':'Phòng Thủ Di Chuyển',
'정지공세의':'Tấn Công Đứng Yên',
'회피공세의':'Tấn Công Sau Né',
'패링보호의':'Khiên Đỡ',
'콤보폭발의':'Nổ Combo',
'물리타격의':'Đòn Vật Lý',
'화염타격의':'Đòn Lửa',
'빙결타격의':'Đòn Băng',
'뇌전타격의':'Đòn Sét',
'암흑타격의':'Đòn Bóng Tối',
'독타격의':'Đòn Độc',
'최소공격의':'ATK Tối Thiểu',
'최대공격의':'ATK Tối Đa',
'전투력의':'Chiến Lực',
'무기사거리의':'Tầm Vũ Khí',
'활사거리의':'Tầm Nỏ',
'이중타의':'Đánh Đôi',
'다중발사의':'Bắn Nhiều',
'관통횟수의':'Số Lần Xuyên',
'관통유지의':'Duy Trì Xuyên',
'연쇄유지의':'Duy Trì Liên Hoàn',
'범위확장의':'Mở Rộng Diện Tích',
'범위피해의':'Sát Thương Diện Rộng',
'돌진공격의':'Tấn Công Lướt',
'반격공격의':'Tấn Công Phản Đòn',
'후방타의':'Đánh Sau Lưng',
'침식가속의':'Tăng Tốc Ăn Mòn',
'출혈지속의':'Kéo Dài Chảy Máu',
'마법타격의':'Đòn Pháp',
'주문증폭의':'Tăng Phép',
'연살뎀의':'Sát Thương Liên Giết',
'연살속의':'Tốc Độ Liên Giết',
'기세의':'Đà',
'정지공격의':'Tấn Công Đứng Yên',
'이동공격의':'Tấn Công Di Chuyển',
'패링공세의':'Tấn Công Sau Đỡ',
'임사폭발의':'Nổ Cận Tử',
'만기력공의':'ATK Đầy ST',
'만마력공의':'ATK Đầy Mana',
'신선처치의':'Giết Tươi',
'경직연장의':'Kéo Dài Choáng',
'빙결연장의':'Kéo Dài Băng',
'둔화강화의':'Tăng Chậm',
'독중첩의':'Chồng Độc',
'출혈중첩의':'Chồng Chảy Máu',
'발화강화의':'Tăng Bốc Cháy',
'동상강화의':'Tăng Đông Cứng',
'감전강화의':'Tăng Giật Điện',
'사선회심의':'Bạo Cận Tử',
'갑옷강화의':'Tăng Giáp',
'블록흡수의':'Hấp Thụ Chặn',
'방패타격의':'Đòn Khiên',
'방패경직의':'Choáng Khiên',
'격투속의':'Tốc Cận Chiến',
'격투회심의':'Bạo Cận Chiến',
'격투경직의':'Choáng Cận Chiến',
'하반재생의':'Hồi Chân',
'CC단축의':'Giảm CC',
'돌진타의':'Đòn Lướt',
'돌진범위의':'Diện Rộng Lướt',
'은신질주의':'Chạy Ẩn',
'회피감쇠의':'Giảm Sát Thương Khi Né',
'속성감쇠의':'Giảm Sát Thương Nguyên Tố',
'마나왕관의':'Vương Miện Mana',
'시전왕관의':'Vương Miện Niệm',
'쿨감왕관의':'Vương Miện Hồi Chiêu',
'경험왕관의':'Vương Miện Kinh Nghiệm',
'공생의':'Cộng Sinh',
'수질의':'Thân Tâm',
'회심흡의':'Hút Bạo',
'체마의':'HP-Mana',
'체기의':'HP-ST',
'마기의':'Mana-ST',
'전재생의':'Hồi Toàn Bộ',
'힘민의':'STR-DEX',
'힘지의':'STR-INT',
'민지의':'DEX-INT',
'운근의':'LCK-Kiên Trì',
'수확의':'Thu Hoạch',
'빙화의':'Băng-Lửa',
'뇌암의':'Sét-Bóng Tối',
'근마의':'Kiếm-Pháp',
'속성침식의':'Ăn Mòn Nguyên Tố',
'화염반지의':'Nhẫn Lửa',
'빙결반지의':'Nhẫn Băng',
'뇌전반지의':'Nhẫn Sét',
'암흑반지의':'Nhẫn Bóng Tối',
'독반지의':'Nhẫn Độc',
'콤보반지의':'Nhẫn Combo',
'처치마나의':'Mana Khi Giết',
'관통반지의':'Nhẫn Xuyên',
'만능목걸이의':'Vòng Cổ Đa Năng',
'회심목걸이의':'Vòng Cổ Bạo',
'관통목걸이의':'Vòng Cổ Xuyên',
'스킬목걸이의':'Vòng Cổ Kỹ Năng',
'콤보한계의':'Giới Hạn Combo',
'처치치유의':'Hồi Máu Khi Giết',
'지구벨트의':'Thắt Lưng ST',
'포션벨트의':'Thắt Lưng Thuốc',
'활력벨트의':'Thắt Lưng Sinh Lực',
'탐욕벨트의':'Thắt Lưng Tham Lam',
'마나띠의':'Dây Mana',
'시전띠의':'Dây Niệm',
'마력띠의':'Dây Pháp Lực',
'주술띠의':'Dây Phép',
'속성띠의':'Dây Nguyên Tố',
'전사의힘':'Sức Mạnh Chiến Binh',
'전사생명의':'Sinh Mệnh Chiến Binh',
'전사흡혈의':'Hút Máu Chiến Binh',
'전사인내의':'Chịu Đựng Chiến Binh',
'마법사의힘':'Sức Mạnh Pháp Sư',
'마법사마나의':'Mana Pháp Sư',
'마법사수호의':'Khiên Pháp Sư',
'마법사속성의':'Nguyên Tố Pháp Sư',
'궁수의힘':'Sức Mạnh Cung Thủ',
'궁수사거리의':'Tầm Bắn Cung Thủ',
'궁수관통의':'Xuyên Cung Thủ',
'궁수질주의':'Nước Rút Cung Thủ',
'탱크생명의':'Sinh Mệnh Tăng',
'탱크방어의':'Phòng Thủ Tăng',
'탱크블록의':'Chặn Tăng',
'탱크가시의':'Gai Tăng',
'암살회심의':'Bạo Sát Thủ',
'암살후방의':'Đánh Sau Lưng Sát Thủ',
'암살독의':'Độc Sát Thủ',
'암살회피의':'Né Sát Thủ',
'종결자의':'Kẻ Kết Thúc',
'생존자의':'Người Sống Sót',
'종결수호의':'Khiên Kết Thúc',
'종결회심의':'Bạo Kết Thúc',
'종결공격의':'ATK Kết Thúc',
'종결저항의':'Kháng Kết Thúc',
'종결파괴의':'Hủy Diệt Kết Thúc',
'종결보호의':'Bảo Vệ Kết Thúc',
'종결흡혈의':'Hút Máu Kết Thúc',
'종결인내의':'Chịu Đựng Kết Thúc',
'종결쿨감의':'Giảm Hồi Kết Thúc',
'종결경험의':'Kinh Nghiệm Kết Thúc',
'종결약탈의':'Cướp Đoạt Kết Thúc',
'종결악의의':'Ác Ý Kết Thúc',
'종결힘의':'STR Kết Thúc',
'종결민첩의':'DEX Kết Thúc',
'종결지능의':'INT Kết Thúc',
'종결행운의':'LCK Kết Thúc',
'종결근성의':'Kiên Trì Kết Thúc',
'종결연살의':'Liên Giết Kết Thúc',
'건강공세의':'Tấn Công Khỏe Mạnh',
'중상폭발의':'Nổ Trọng Thương',
'중상흡혈의':'Hút Máu Trọng Thương',
'토벌의':'Tiên Phong',
'정예토벌의':'Tiên Phong Tinh Anh',
'극대화의':'Tối Đa Hóa',
'공격력 +X%':'ATK +X%',
'관통 확률 +X%':'Xuyên Thấu +X%',
'방어율 +X%':'Chặn +X%',
'물리 피해감소 +X%':'Giảm ST Vật Lý +X%',
'최대 HP +X':'HP Tối Đa +X',
'공격속도 +X%':'Tốc Đánh +X%',
'상태이상 저항 +X%':'Kháng Trạng Thái +X%',
'이동속도 +X%':'Tốc Độ Di Chuyển +X%',
'원소 저항 +X%':'Kháng Nguyên Tố +X%',
'최대 HP +X%':'HP Tối Đa +X%',
'회피 쿨다운 -X%':'Hồi Né -X%',
'물약 쿨다운 -X%':'Hồi Thuốc -X%',
'부활력 +X%':'Sức Hồi Sinh +X%',
'마법 데미지 +X%':'Sát Thương Pháp +X%',
'전설 특수':'Đặc Biệt Truyền Thuyết',
'유니크 특수':'Đặc Biệt Unique',
'5타 콤보 완성 시 데빌포스 20% 즉시 충전':'Combo 5 đòn: nạp ngay 20% DevilForce',
'처치 시 이속 +40%(3초) + 다음 공격 크리 보장':'Giết: tốc đi +40%(3g) + đòn tiếp theo bạo chắc',
'스태거 발동 시 범위 충격파 (ATK×120%)':'Kích hoạt choáng: sóng xung diện rộng (ATK×120%)',
'스태거 발동 시 범위 충격파 (ATK×100%)':'Kích hoạt choáng: sóng xung diện rộng (ATK×100%)',
'강타 시 적 넉백 거리 2배 + 벽충돌 추가뎀':'Đập mạnh: đẩy lùi ×2 + thêm sát thương va tường',
'출혈 대상 크리 시 잔여 DoT×300% 즉시 폭발':'Bạo vào mục tiêu chảy máu: còn lại DoT×300% nổ ngay',
'사슬 착지 타격 수만큼 데미지 +20% 중첩(최대5)':'Javelin landing hits: stack +20% DMG (max 5)',
'치명타 시 추가 투사체 1발 발사':'Bạo: bắn thêm 1 đạn',
'패리 성공 시 반격 데미지 ×2':'Đỡ thành công: sát thương phản đòn ×2',
'피격 시 3초 쿨로 HP 5% 즉시 회복':'Khi bị đánh (hồi 3g): hồi ngay 5% HP',
'스킬 사용 시 20% 확률로 쿨다운 미소모':'Dùng kỹ năng: 20% không tốn hồi chiêu',
'공격속도 +20% + 기본공격에 랜덤 원소 추가':'Tốc đánh +20% + đòn cơ bản thêm nguyên tố ngẫu nhiên',
'이동 중 지속 HP 재생 (초당 HP의 1%)':'Khi di chuyển: hồi HP liên tục (1% HP/giây)',
'회피 직후 첫 공격 데미지 +80%':'Đòn đầu tiên sau né: sát thương +80%',
'패리 타이밍 판정 +50% 확대':'Cửa sổ thời gian đỡ mở rộng +50%',
'원소 반응 발동 시 추가 폭발 (ATK×80%)':'Kích hoạt phản ứng nguyên tố: nổ thêm (ATK×80%)',
'처치 시 데빌포스 5% 회복':'Giết: hồi 5% DevilForce',
'HP 50% 이하 시 전 스킬 쿨다운 -30%':'HP dưới 50%: hồi toàn bộ kỹ năng -30%',
'물약 사용 시 5초간 피해 +15%':'Dùng thuốc: sát thương +15% trong 5g',
'암묵':'Ẩn',
'낡은 악마의 팔찌':'Vòng Tay Quỷ Cũ',
'흑요석 악마의 팔찌':'Vòng Tay Quỷ Hắc Diện',
'미스릴 악마의 팔찌':'Vòng Tay Quỷ Mithril',
'낡은 생명의 팔찌':'Vòng Tay Sinh Mệnh Cũ',
'확인':'Xác Nhận',
'조작법':'Hướng Dẫn',
'살아남으려면 익혀라':'Học để sống sót',
'전투':'Chiến đấu',
'이동 / 상호작용':'Di Chuyển / Tương Tác',
'메뉴':'Menu',
'시스템':'Hệ thống',
'아무 키를 눌러 시작':'Nhấn bất kỳ phím để bắt đầu',
'스테이지':'Giai đoạn',
'💪 힘 (STR)':'💪 STR',
'🏹 민첩 (DEX)':'🏹 DEX',
'🔮 지능 (INT)':'🔮 INT',
'🍀 행운 (LCK)':'🍀 LCK',
'⚔️ 맹공':'⚔️ Mãnh Công',
'🔱 돌파':'🔱 Đột Phá',
'⚡ 반격':'⚡ Trả Thù',
'🔮 마력폭주':'🔮 Cuồng Pháp',
'🎯 정밀사격':'🎯 Bắn Chính Xác',
'🛡 수호신':'🛡 Thần Hộ Vệ',
'💚 회복력':'💚 Hồi Phục',
'💥 급소':'💥 Đòn Hiểm',
'🎁 약탈':'🎁 Cướp Đoạt',
'🔱 관통':'🔱 Xuyên Thấu',
'💠 마력회복':'💠 Hồi Mana',
'🏹 쇠뇌력':'🏹 Tinh Thông Nỏ',
'⚔ 광전사':'⚔ Cuồng chiến',
'🎯 추적자':'🎯 Truy Vết',
'🗡 물리관통':'🗡 Xuyên Vật Lý',
'🔮 마법관통':'🔮 Xuyên Pháp',
'🌿 풍요':'🌿 Phong Nhiêu',
'🐺 약자포식':'🐺 Săn Mồi Yếu',
'☠ 침식':'☠ Ăn mòn',
'💎 마력그릇':'💎 Bình Mana',
'💪 힘의그릇':'💪 Bình ST',
'👿 악의중독':'👿 Nghiện Ác Ý',
'❤️ 강인':'❤️ Kiên Cường',
'🛡 철벽':'🛡 Tường Thép',
'🎯 사냥꾼':'🎯 Thợ Săn',
'✦ 인간성':'✦ Nhân Tính',
'☠ 악마성':'☠ Ma Tính',
'1. 악의폭풍':'1. Bão Ác Ý',
'2. 칼날 계열':'2. Dòng Kiếm',
'3. 역병 확장':'3. Mở Rộng Dịch Bệnh',
'4. 이동스킬 마스터':'4. Thành Thạo Di Chuyển',
'5. 사슬 확장':'5. Mở Rộng Xích',
'6. 💀 필살기 선택':'6. 💀 Chọn Tuyệt Chiêu',
'7. 멸살+만화+원소+전격이동':'7. Hủy Diệt+Mưa Kim+Nguyên Tố+Bước Chớp',
'8. 회전참+기폭+대왕':'8. Toàn Phong+Kích Nổ+Khổng Lồ',
'9. 방패 합체':'9. Hợp Khiên',
'10. 해골무덤+악의폭풍':'10. Mộ Xương+Bão Ác Ý',
'11. 폭풍소환+얼음보주':'11. Triệu Hồi Xoáy+Cầu Băng',
'12. 뇌전걸음':'12. Bước Ma',
'13. 신성 영역':'13. Lĩnh Vực Thánh',
'14. 6단합체: 폭풍빔':'14. Hợp 6 Cấp: Tia Bão',
'15. 신성+빙결':'15. Thánh+Băng',
'16. 암흑+가시+대왕2':'16. Bóng Tối+Gai+Khổng Lồ 2',
'17. 사슬 최종':'17. Xích Cuối',
'⚡ 이동스킬':'⚡ Di Chuyển',
'⚔️ 물리/근접/분노':'⚔️ Vật lý/Cận chiến/Cuồng nộ',
'🛡️ 방어':'🛡️ Phòng Thủ',
'🔮 마법':'🔮 Pháp Thuật',
'🏹 석궁/관통':'🏹 Nỏ/Xuyên',
'⚙️ 영역':'⚙️ Lãnh vực',
'💀 필살기':'💀 Tuyệt Chiêu',
'⭐ 추천':'⭐ Khuyên Dùng',
'⚔ 공격':'⚔ Tấn Công',
'🛡 방어':'🛡 Phòng Thủ',
'⚙ 특수':'⚙ Đặc biệt',
'STEAM 위시리스트':'Danh sách yêu thích Steam',
'STEAM 위시리스트로 응원해 주세요!':'Hãy thêm vào danh sách yêu thích trên Steam để ủng hộ chúng tôi!',
'⚔ 난타!':'⚔ Loạn Đả!',
'⚡ 연격!':'⚡ Liên Đòn!',
'더블탭 or Shift+방향키! 전격이동으로 탈출해!':'Nhấn đúp hoặc Shift+Hướng! Xích để thoát!',
'데모 종료':'Kết Thúc Demo',
'독사':'Rắn độc',
'방어↓':'Phòng↓',
'여기까지 데모입니다. 정식 출시를 기대해주세요!':'Đây là phần kết của bản demo. Mong chờ bản phát hành đầy đủ!',
'프레임 표시 (FPS)':'Hiển thị FPS',
'흑요염 파괴자':'Kẻ Hủy Diệt Ngọn Lửa Đen',
'🌀 휘두르기!':'🌀 Quét!',
'🐍 독사!':'🐍 Rắn độc!',
'💥 강타!':'💥 Đập Mạnh!',
'💥 공성유령 폭발!':'💥 Vụ Nổ Bóng Ma Vây Hãm!',
'👻 공성유령!':'👻 Bóng Ma Vây Hãm!',
'목표 달성!':'Đạt mục tiêu!',
'악의 고갈':'Ác ý cạn kiệt',
'시도':'Lần thử',
'소비':'Tiêu hao',
'목표':'Mục tiêu',
'미달':'Chưa đạt',
'악의를 더 모아 재시도하세요':'Thu thập thêm Ác ý và thử lại',
'습득':'Học',
'레벨업':'Lên cấp',
'⚡기동+10':'⚡Lướt+10',
'게임 종료':'Thoát game',
'영역스킬':'Kỹ năng vùng',
'석궁자동':'Nỏ tự động',
'데빌포스 흡수 (HP→에너지)':'Hấp thụ Ma lực (HP→Năng lượng)',
'스킬슬롯 5':'Ô kỹ năng 5',
'CT스킬 (유령걸음/얼음보주)':'Kỹ năng CT (Bước Ma/Cầu Băng)',
'스킬 (전투스킬 습득)':'Kỹ năng (Chiến đấu)',
'대장간 (제작)':'Lò rèn (Chế tạo)',
'클릭하여 계속':'Nhấp để tiếp tục',
'클릭하여 시작':'Nhấp để bắt đầu',
'SPACE 길게 눌러 건너뛰기':'Giữ SPACE để bỏ qua',
'패링·보호막':'Đỡ / Khiên',
'돌진 (적을 관통, 무적)':'Xích tới (xuyên qua, bất tử)',
'대왕치기 (광역 기절)':'Đại Vương Chém (choáng diện rộng)',
'가시덫 (슬로우+출혈)':'Bẫy gai (chậm+chảy máu)',
'회복의 영역 (리젠 장판)':'Vùng hồi phục (regen)',
'얼음보주 (무적+빙결)':'Cầu băng (bất tử+đông đá)',
'석궁 자동발사':'Nỏ tự động',
'선택 스킬 슬롯':'Ô kỹ năng',
'(펫이 자동 수거)':'(pet tự nhặt)',
'물약은 설정한 HP% 이하 시 자동 사용':'Thuốc tự dùng khi HP dưới % đã đặt',
'💡 Shift로 사슬 돌진! 적을 관통하며 무적':'💡 Shift lao tới! Xuyên qua, bất tử',
'💡 Q로 보호막 발동 — 기본 흡수율 70%, 패링 성공 시 HP/ST/MP/기동게이지 회복':'💡 Q cho Khiên — hấp thụ 70%, đỡ hồi HP/ST/MP/Sạc',
'💡 속성 약점을 찌르면 데미지 2배!':'💡 Đánh vào điểm yếu thuộc tính — sát thương x2!',
'💡 ESC로 설정 — 난이도, 자동물약 조절':'💡 ESC cài đặt — độ khó, thuốc tự động',
'💡 대왕치기로 기절 회복 + 포이즈를 깎아 그로기 유발!':'💡 Đại Vương Chém: hồi choáng + phá thế gây groggy!',
'💡 그로기 상태에서 기본 데미지 1.5배':'💡 Trạng thái groggy = 1.5x sát thương cơ bản',
'💡 탄막은 패링하면 되돌려 보낸다!':'💡 Đỡ đạn — bật ngược lại!',
'💡 Ctrl 얼음보주 — 무적! 재입력으로 즉시 폭파':'💡 Ctrl Cầu băng — bất tử! Nhấn lại để nổ',
'💡 합체 스킬로 더 강한 공격을 만들어보세요':'💡 Kết hợp kỹ năng tạo đòn tấn công mạnh hơn!',
'💡 엘리트 몬스터는 특수 능력을 가지고 있다':'💡 Quái vật tinh anh có kỹ năng đặc biệt',
'💡 보스의 패턴을 읽고 패링 타이밍을 잡아라':'💡 Đọc pattern boss, bắt timing đỡ đòn',
'💡 인벤토리(TAB)에서 장비를 비교하고 장착':'💡 Túi đồ(TAB) — so sánh và trang bị',
'💡 대장간에서 장비를 강화하고 분해하세요':'💡 Nâng cấp và phân hủy trang bị tại lò rèn',
'💡 R키를 누르면 펫이 아이템을 자동으로 주워줍니다':'💡 Nhấn R — pet tự nhặt vật phẩm',
'💡 물약은 설정한 HP% 이하에서 자동 사용':'💡 Thuốc tự dùng khi HP dưới % đã đặt',
'💡 집중 스킬(홀드)은 시전 중 기절 면역!':'💡 Kỹ năng tập trung (giữ) miễn nhiễm choáng!',
'🎮 전체 조작 가이드':'🎮 Hướng dẫn điều khiển',
'무기 공격 (좌클릭)':'Tấn công (Chuột trái)',
'B슬롯 스킬 (Space)':'Kỹ năng ô B (Space)',
'우클릭 스킬 (RMB)':'Kỹ năng chuột phải (RMB)',
'패링 (Q)':'Đỡ đòn (Q)',
'돌진/사슬 (Shift)':'Lướt/Xích (Shift)',
'Ctrl 스킬':'Kỹ năng Ctrl',
'필살기 (Z)':'Tuyệt chiêu (Z)',
'F 슬롯 스킬':'Kỹ năng ô F',
'스킬 슬롯 1':'Ô 1',
'스킬 슬롯 2':'Ô 2',
'스킬 슬롯 3':'Ô 3',
'스킬 슬롯 4':'Ô 4',
'처형 (X)':'Hành quyết (X)',
'방향 + 마법 자동발동 (E)':'Hướng + Ma thuật tự động (E)',
'마법 (E)':'Ma thuật (E)',
'줍기 (R)':'Nhặt (R)',
'스킬창':'Kỹ năng',
'이동 (WASD)':'Di chuyển (WASD)',
'👻 유령!':'👻 Ma!',
'🦴 해골무덤!':'🦴 Mộ Xương!',
'💥 유령총 폭발!':'💥 Nổ Súng Ma!',
'탈취!':'Trộm!',
' 스킬 해제':' Bỏ kỹ năng',
' 자동 OFF':' Tự động TẮT',
' 자동 ON':' Tự động BẬT',
'B슬롯 스킬':'Kỹ năng ô B',
'☠중독!':'☠ Trúng độc!',
'✟ 신의영역!':'✟ Lãnh thổ Thần!',
'❄ 얼음송곳!':'❄ Gai Băng!',
'⟨ 키 입력... ⟩':'⟨ Nhấn phím... ⟩',
'고정':'Cố định',
'다음 구역':'Vùng tiếp theo',
'돌진/사슬':'Xích tới/Xích',
'쓰러짐...':'Gục ngã...',
'우클릭 스킬':'Kỹ năng chuột phải',
'줍기':'Nhặt',
'패드 키 초기화':'Đặt lại phím tay cầm',
'패드 키 초기화 완료':'Đã đặt lại phím tay cầm',
'패링':'Đỡ đòn',
'🎮 게임패드 버튼 설정':'🎮 Cài đặt nút tay cầm',
'🎮 패드 연결됨':'🎮 Đã kết nối tay cầm',
'🎮 패드 연결 끊김':'🎮 Tay cầm đã ngắt kết nối',
'💀 ':'💀 ',
'🔥부활!':'🔥 Hồi sinh!',
'🔥분노 ':'🔥 Cuồng nộ ',
'🔥분노+':'🔥Cuồng nộ+',
'🚀 미사일!':'🚀 Tên lửa!',
};

const _VI_PFX={'녹슨':'Gỉ Sét','강철':'Thép','흑요석':'Hắc Diện','미스릴':'Mithril','심판의':'Phán Xét','천벌의':'Thiên Phạt','파멸의':'Hủy Diệt','불꽃':'Lửa','화염':'Hỏa Ngục','염화':'Lửa Địa Ngục','지옥불':'Lửa Địa Ngục','지옥화':'Lửa Địa Ngục','지옥':'Lửa Địa Ngục','멸화의':'Diệt Vong','냉기':'Sương Giá','빙결':'Băng Kết','빙하':'Băng Hà','서리의':'Sương Muối','서리':'Sương Muối','영겁빙':'Băng Vĩnh Cửu','그림자':'Bóng Tối','암흑':'Hắc Ám','심연':'Vực Thẳm','나락의':'Địa Phủ','나락':'Địa Phủ','무간의':'Hư Không','전기':'Tia Lửa','낙뢰':'Sấm Sét','암전':'Lôi Điện','뇌신의':'Lôi Thần','뇌신':'Lôi Thần','만뢰의':'Vạn Lôi','축복':'Chúc Phúc','성광':'Thánh Quang','신성':'Thần Thánh','천사의':'Thiên Thần','신벌의':'Thần Phạt','낡은':'Cũ','천':'Vải','가죽':'Da','강철사':'Thép Dệt','은':'Bạc','은사':'Chỉ Bạc','화염의':'Hỏa Ngục','빙결의':'Băng Kết','암흑의':'Hắc Ám','암전의':'Lôi Điện'};
const _VI_BASE={'대검':'Đại Kiếm','석궁':'Nỏ','연사석궁':'Nỏ Liên Thanh','마력석궁':'Nỏ Ma Lực','견갑':'Vai Giáp','대견갑':'Đại Vai Giáp','전투화':'Giày Chiến Đấu','갑옷':'Giáp','갑주':'Giáp','왕관':'Vương Miện','장갑':'Găng Tay','건틀릿':'Bao Tay Sắt','바지':'Quần','각반':'Xà Cạp','허리띠':'Thắt Lưng','벨트':'Thắt Lưng','부적':'Bùa Hộ Mệnh','목걸이':'Vòng Cổ','반지':'Nhẫn','망토':'Áo Choàng','악마팔찌':'Demon Bracelet','생명팔찌':'Life Bracelet','팔찌':'Vòng Tay','귀걸이':'Bông Tai',
'투구 착용':'Đội mũ giáp',
'투구 해제':'Tháo mũ giáp',
'✟ 신성한 결계!':'✟ Kết Giới Thần Thánh!',
'혼돈의 투구':'Mũ Hỗn Mang',
'전지전능의 투구':'Mũ Toàn Năng',
'방향키 연타':'Nhấn phím mũi tên liên tục',
'까마귀와 고양이가 아이템을 주워준다. 수거 범위 안이면.':'Quạ và mèo nhặt vật phẩm. Nếu trong phạm vi thu thập.',
'Ctrl 얼음보주로 탈출! 없으면 방향키 연타!':'Ctrl — Orb Băng để thoát! Không có? Nhấn mũi tên!',
'💥 폭발 허수아비!':'💥 Bù Nhìn Nổ!',
'👻 유령총!':'👻 Súng Ma!',
' 뎀 ':' STH ',
'기절!  ':'Choáng váng!  ',
'투구':'Mũ giáp',
'얼음송곳':'Gai Băng',
'⚡ 뇌전추격자!':'⚡ Truy Sét!',
'대왕치기 (분노폭발, 광역 기절)':'Đòn Khổng Lồ (Nổ Cuồng Nộ, Choáng Vùng)',
'✦ 유니크 공유!':'✦ Chia Sẻ Độc Nhất!',
'🛡️쉴드+15%':'🛡️Khiên+15%',
'👿악의+':'👿Ác Ý+',
'❄유니크 빙결!':'❄Đóng Băng Độc Nhất!',
'🔨방어무시!':'🔨Bỏ Qua DEF!',
'💥유니크 폭발!':'💥Nổ Độc Nhất!',
'👻 투명화!':'👻 Tàng Hình!',
'⚡회피 반격!':'⚡Phản Đòn Né!',
'⚠패링 실패!':'⚠Đỡ Thất Bại!',
'🔥피격→분노!':'🔥Trúng→Cuồng Nộ!',
'✦ 유니크 부활!':'✦ Hồi Sinh Độc Nhất!',
'닫기 [V]':'Đóng [V]',
'닫기 [C]':'Đóng [C]',
'\u2026\uBD84\uB178\uAC00 \uB053\uC5B4\uB118\uCE5C\uB2E4. \uC2A4\uD398\uC774\uC2A4\uB85C \uC801\uB4E4\uC5D0\uAC8C \uD3ED\uBC1C\uC2DC\uCCA8!':'…Cơn thịnh nộ tràn đầy. Hãy nổ tung nó vào kẻ thù với Space!',
'\uBD84\uB178\uAC8C\uC774\uC9C0 \uAF49 \uCC3C\uC5B4! \uC2A4\uD398\uC774\uC2A4\uB85C \uD3ED\uBC1C\uC2DC\uCCA8!':'Thanh thịnh nộ đầy! Nổ tung với Space!',
};