// 지옥의 길 — Italiano (it)
const _IT={
'썩은 숲':'Foresta Marcia',
'숲의 감시자':'Guardiano della Foresta',
'독버섯 거인':'Gigante Fungo Tossico',
'숲의 사냥꾼':'Cacciatore della Foresta',
'숲의 기생수':'Bestia Parassita',
'1장 — 썩은 숲':'CAP1 — Foresta Marcia',
'2장 — 벌레굴':'CAP2 — Nido di Vermi',
'3장 — 얼음굴':'CAP3 — Caverna di Ghiaccio',
'4장 — 고통의 화염지대':'CAP4 — Landa Infernale',
'5장 — 지옥의 군단':'CAP5 — Legione Infernale',
'6장 — 사도의 마굴':'CAP6 — Tana dell\'Apostolo',
'7장 — 지옥성':'CAP7 — Cittadella Infernale',
'탈출!':'Fuggito!',
'처치':'Uccisioni',
'경험치':'ESP',
'최대콤보':'Combo Max',
'일어나. 여신이 널 여기 보낸 건 죽으라고가 아니야.':'Svegliati. La dea non ti ha mandato qui per morire.',
'좋아, 감각이 있군. 계속 쳐!':'Bene, hai istinto. Continua a colpire!',
'Shift를 눌러. 작살이다. 땅에 꽂아서 끌려가!':'Premi Shift. È il rampone. Conficcalo e fatti trascinare!',
'작살로 끌려가는 중엔 무적이다. 위험할 때 쓰면 좋아.':'Sei invincibile mentre il rampone ti trascina. Usalo nei momenti critici.',
'...아파? 당연하지. 여긴 지옥이야.':'...Fa male? Ovvio. Questo è l\'inferno.',
'Q를 눌러! 악의로 보호막을 만들 수 있다.':'Premi Q! Crea uno scudo con la malizia.',
'보호막 없이 버틸 생각은 버려.':'Scordati di sopravvivere senza scudo.',
'우클릭이 패링이다. 적 공격이 닿기 직전에 눌러!':'Clic destro per parare. Appena prima che il nemico colpisca!',
'못 하겠으면 때려. 안 죽으면 그만이야.':'Non riesci? Colpisci. L\'importante è non morire.',
'됐어! 감 잡았구나.':'Ecco! Stai capendo.',
'하나 죽었군.':'Uno in meno.',
'유령쇠뇌야. 인사해.':'È la balestra fantasma. Salutala.',
'빨간 탄을 무서워하지 마. 악의가 강하다.':'Non temere i proiettili rossi. La malizia è forte.',
'패링으로 돌려주고, Q 보호막도 써! 악의를 잘 굴려!':'Respingili con la parata e usa lo scudo Q! Gestisci la malizia!',
'무지개빛은 패링 불가! 피해!':'I colpi arcobaleno non si parano! Schiva!',
'피가 새고 있다. Shift. 빠져.':'Stai sanguinando. Shift. Scappa.',
'물약 있잖아! 숫자키!':'Hai pozioni! Tasti numerici!',
'우클릭. 적 손목이 꺾일 때 쳐.':'Clic destro. Colpisci quando il polso si piega.',
'빨간 탄은 악의 덩어리다. 쳐내서 이용해.':'I proiettili rossi sono blocchi di malizia. Deviali e usali.',
'무지개빛만 피하면 돼! 나머지는 다 패링!':'Schiva solo l\'arcobaleno! Para tutto il resto!',
'Q 보호막도 패링이 가능해!':'Lo scudo Q può anche parare!',
'위험해! 쉬프트 사슬기동으로 피해!!':'Pericolo! Shift catena per fuggire!!',
'쉬프트! 사슬기동은 이동기야! 끌려가면서 무적이라고!':'Shift! La catena è movimento! Invincibile mentre ti trascina!',
'스킬포인트가 쌓였어! K 눌러서 스킬 배우자!':'Punti abilità pronti! Premi K!',
'속성을 읽어. 약점을 찌르면 두 배로 썩는다.':'Leggi gli elementi. Colpire debolezze fa il doppio danno.',
'K를 눌러봐! 스킬을 배울 수 있어!':'Premi K! Puoi imparare abilità!',
'C 눌러서 능력치 찍어! 패시브도 있어~':'Premi C per le stats! Anche i passivi~',
'G를 눌러. 대장간에서 장비를 강화할 수 있다.':'Premi G. Potenzia l\'equipaggiamento alla forgia.',
'F키도 스킬 슬롯이야! 스킬 많으면 L로 배정해봐~':'Anche F è uno slot! Usa L per assegnare~',
'Z. 필살기다. 아껴 써라.':'Z. La tua mossa finale. Usala con saggezza.',
'L-CTRL로 유령걸음이나 얼음보주 쓸 수 있어!':'L-CTRL per Passo Fantasma o Sfera di Ghiaccio!',
'L을 눌러. 스킬 슬롯을 정리해야 한다.':'Premi L. Organizza gli slot.',
'가방 터지겠다! V 눌러서 창고에 넣어둬!':'Lo zaino sta esplodendo! Premi V!',
'ESC로 설정 열 수 있어! 난이도 바꾸기, 자동물약 조절~':'ESC per le impostazioni! Difficoltà, pozioni auto~',
'...아직 살아있네. 좌클릭으로 저것들 쳐봐.':'...Ancora vivo. Colpiscili con clic sinistro.',
'...치는 건 할 줄 아네. 피하는 건?':'...Sai colpire. E schivare?',
'흥, 작살 못 맞추면 헛수고야.':'Hmph, manca il rampone e sprechi tutto.',
'...운이 좋았을 뿐이야. 아마.':'...Solo fortuna. Probabilmente.',
'...고기 냄새. 싫진 않네.':'...Odore di carne. Non male.',
'...말은 못해.':'...Non può parlare.',
'예쁘다고 만지면 죽어.':'Li tocchi perché sono belli? Morirai.',
'작살 던져! 끌려가면 무적이야!':'Lancia il rampone! Invincibile mentre ti trascinano!',
'...마시든 말든. 네 목숨이니까.':'...Bevi o no. È la tua vita.',
'그게 패링이야! 타이밍이 전부야~':'Quella è una parata! Il tempismo è tutto~',
'화염엔 빙결! 암전엔 암흑! 기억해!':'Fuoco vs Ghiaccio! Fulmine vs Oscurità! Ricorda!',
'...얼어붙은 놈은 오래 안 간다.':'...I congelati non durano.',
'얼었어! 빙결 중 1.5배야!':'Congelato! 1.5x danni!',
'...힘을 골라라. 전부 가질 순 없다.':'...Scegli il tuo potere. Non puoi avere tutto.',
'스탯을 올려. 살고 싶으면.':'Alza le stats. Se vuoi vivere.',
'좋은 장비는 강화해야 진짜 힘을 발휘해!':'L\'equipaggiamento buono va potenziato!',
'...슬롯을 채워. 빈 손은 죽음이다.':'...Riempi gli slot. Mani vuote = morte.',
'Z 누르면 대박! 쿨타임 길어서 타이밍 봐야 해!':'Z per danni enormi! Lungo cooldown, tempismo!',
'Ctrl. 위기에 쓸 카드가 하나 늘었군.':'Ctrl. Una carta in più per le emergenze.',
'스킬이 많아졌네~ L로 어디에 뭘 넣을지 골라!':'Tante abilità~ Usa L per assegnare!',
'...버리기 아까운 건 창고에.':'...Metti nel deposito ciò che vale.',
'...살아남은 것만으로도 대단하군. 설정을 확인해.':'...Sopravvivere è già impressionante. Controlla le impostazioni.',
'MP 부족!':'MP insufficiente!',
'ST 부족!':'ST insufficiente!',
'악의 부족!':'Malizia insufficiente!',
'충전 중...':'Caricamento...',
'캔슬':'Annulla',
'아이템 선택 필요':'Seleziona un oggetto',
'악의 소진...':'Malizia esaurita...',
'비문 발견...':'Iscrizione trovata...',
'HP물약!':'Pozione HP!',
'HP물약 +1':'Pozione HP +1',
'HP물약 +2':'Pozione HP +2',
'HP/MP/ST 회복!':'HP/MP/ST ripristinato!',
'보물상자 개봉!':'Forziere aperto!',
'익사!':'Annegamento!',
'피웅덩이!':'Pozza di sangue!',
'독혈!':'Sangue tossico!',
'잡힘!':'Afferrato!',
'콤보 종료':'Fine combo',
'빙결!':'Congelato!',
'화상!':'Bruciatura!',
'독!':'Veleno!',
'감전!':'Folgorato!',
'기절!':'Stordito!',
'봉인됨!':'Sigillato!',
'관통!':'Penetrazione!',
'기검참':'Fendente Ki',
'악의구':'Sfera Malizia',
'회전참':'Turbine',
'기폭팔':'Detonazione',
'칼등 처내기':'Parata di Lama',
'만화방창':'Raffica di Aghi',
'멸살광선':'Raggio Annientamento',
'원소추적탄':'Cercatore Elementale',
'악의 보호자':'Guardiano Malizia',
'악의 사냥':'Caccia Malizia',
'폭풍소환':'Evocazione Vortice',
'해골무덤':'Tomba d\'Ossa',
'\u{1F47B} 유령!':'\u{1F47B} Fantasma!',
'\u{1F9B4} 해골무덤!':'\u{1F9B4} Tomba d\'Ossa!',
'신성폭발':'Esplosione Sacra',
'블랙':'Stella Nera',
'용암소환':'Evocazione Lava',
'처형':'Esecuzione',
'악마화 부활':'Resurrezione Demoniaca',
'붉은꽃':'Fiore Cremisi',
'얼음보주':'Sfera di Ghiaccio',
'뇌전걸음':'Passo Fantasma',
'만화방창 II':'Raffica di Aghi II',
'마력연사':'Raffica Arcana',
'마력광선':'Laser Arcano',
'업화선':'Raggio Infernale',
'지옥진':'Formazione Infernale',
'폭독칼날':'Lama Pestilente',
'악의폭풍':'Tempesta Malizia',
'악의기둥':'Pilastro Oscuro',
'회복의 영역':'Dominio Sacro',
'구속의 영역':'Dominio Vincolante',
'아이스스톰':'Tempesta di Ghiaccio',
'대왕치기':'Colpo Gigante',
'대왕치기 2':'Colpo Gigante II',
'기동불꽃':'Fiamma a Catena',
'기동파괴':'Distruzione a Catena',
'기동칼날개':'Ala di Lama',
'평화의보호':'Egida della Pace',
'참회':'Pentimento',
'칼등날개':'Ala Scudo',
'폭산탄':'Colpo Esplosivo',
'파쇄의 영역':'Dominio Frantumazione',
'침식의 영역':'Dominio Corrosione',
'관통의 영역':'Dominio Penetrazione',
'부활의 영역':'Dominio Resurrezione',
'가시덫':'Trappola di Spine',
'푸른비':'Pioggia Azzurra',
'버스트루프':'Ciclo Raffica',
'유령 허수아비':'Esca Fantasma',
'폭발 허수아비':'Esca Esplosiva',
'공성쇠뇌':'Balestra d\'Assedio',
'사슬기동:충돌':'Catena: Impatto',
'사슬기동:화염':'Catena: Fiamma',
'전격이동':'Passo Fulmine',
'기동칼날개!':'Ala Lama!',
'기동불꽃!':'Fiamma Catena!',
'기동파괴!':'Distruzione a Catena!',
'사슬이동:강화!':'Catena Potenziata!',
'사슬기동:화염!':'Catena: Fiamma!',
'작살!':'Rampone!',
'진입!':'Ingresso!',
'레인라이트닝!':'Pioggia Fulmini!',
'마력연사!':'Raffica Arcana!',
'🔷 마력광선!':'🔷 Laser Arcano!',
'광선 해제':'Laser disattivato',
'MP 부족 — 광선 해제':'MP esaurito — Laser disattivato',
'집중...':'Concentrazione...',
'시전...':'Lancio...',
'만화방창!':'Raffica di Aghi!',
'바늘출!':'Scarica di Aghi!',
'칼날!':'Lama!',
'착지!':'Atterraggio!',
'체간삭감!':'Postura spezzata!',
'기동전폭 준비!':'Esplosione Catena pronta!',
'기동불꽃 준비!':'Fiamma Catena pronta!',
'기동파괴 준비!':'Distruzione Catena pronta!',
'유령불꽃 ON':'Fiamma Fantasma ON',
'유령불꽃 OFF':'Fiamma Fantasma OFF',
'기동칼날개 AUTO ON':'Ala Lama AUTO ON',
'기동칼날개 AUTO OFF':'Ala Lama AUTO OFF',
'자동 버스트!':'Raffica auto!',
'연사 해제':'Fuoco rapido disatt.',
'당기기 모드':'Modalità Tirare',
'밀어내기 모드':'Modalità Spingere',
'날개치기':'Colpo Ala',
'처내기':'Parata',
'Shift: 작살 발사 → 끌려감':'Shift: Rampone → trascinamento',
'Shift: 화염길+화상':'Shift: Scia fuoco+bruciatura',
'CT: 전류변신+뇌전걸음 (쿨4초)':'CT: Forma fulmine+Passo Fantasma (CD 4s)',
'CT: 방어구체+빙결 (재입력: 파쇄)':'CT: Sfera ghiaccio+congela (ri-premere: frantuma)',
'근접':'Mischia',
'견갑':'Guardia',
'작살':'Rampone',
'마법':'Magia',
'보막':'Scudo',
'유령':'Fantasma',
'스킬':'Abilità',
'대장':'Forgia',
'인벤':'Inv',
'인벤토리':'Inventario',
'복수의 대장간':'Forgia della Vendetta',
'패시브 스킬':'Abilità Passive',
'전투 스킬':'Abilità Combattimento',
'캐릭터 선택':'Selezione Personaggio',
'물리':'Fisico',
'화염':'Fuoco',
'빙결':'Congelato',
'암흑':'Oscurità',
'암전':'Fulmine',
'신성':'Sacro',
'대지':'Terra',
'힘':'Forza',
'민첩':'Destrezza',
'지능':'Intelligenza',
'행운':'Fortuna',
'맹공':'Assalto',
'철벽':'Fermezza',
'돌파':'Sfondamento',
'반격':'Ritorsione',
'마력폭주':'Impeto Arcano',
'정밀사격':'Tiro Preciso',
'수호':'Guardiano',
'수호신':'Spirito Guardiano',
'회복력':'Recupero',
'급소':'Colpo Vitale',
'약탈':'Saccheggio',
'관통':'Penetrazione',
'마력회복':'Recupero Mana',
'쇠뇌력':'Maestria Balestra',
'광전사':'Berserker',
'추적자':'Inseguitore',
'물리관통':'Pen. Fisica',
'마법관통':'Pen. Magica',
'녹슨 대검':'Spadone Arrugginito',
'강철 대검':'Spadone d\'Acciaio',
'흑요석 대검':'Spadone Ossidiana',
'낡은 석궁':'Balestra Logora',
'강철 석궁':'Balestra d\'Acciaio',
'흑요석 석궁':'Balestra Ossidiana',
'대검':'Spadone',
'석궁':'Balestra',
'연사석궁':'Balestra Ripetizione',
'마력석궁':'Balestra Arcana',
'악의 추출':'Estrazione Malizia',
'악의':'Malizia',
'필살기':'Colpo Finale',
'필살기 해제':'Colpo Finale rimosso',
'이전':'Trasferire',
'강화':'Potenziare',
'개봉!':'Aperto!',
'여신의 가호':'Benedizione della Dea',
'과부하!':'Sovraccarico!',
'맹독의':'Velenoso',
'불꽃의':'Fiammeggiante',
'냉기의':'Gelido',
'번개의':'Voltaico',
'암흑의':'Maledetto',
'관통의':'Penetrante',
'광폭의':'Furioso',
'파쇄의':'Frantumate',
'연쇄의':'Concatenato',
'학살의':'Massacrante',
'폭발의':'Esplosivo',
'집중의':'Concentrato',
'쾌속의':'Rapido',
'패리의':'Deflettente',
'추적자의':'dell\'Inseguitore',
'작살의':'Rampone',
'궁극의':'Supremo',
'집중력의':'Attento',
'강인의':'Tenace',
'수호의':'Protettivo',
'활력의':'Vitale',
'신속의':'Accelerato',
'화염수호':'Guardia Fuoco',
'빙결수호':'Guardia Ghiaccio',
'암전수호':'Guardia Fulmine',
'암흑수호':'Guardia Oscurità',
'독수호':'Guardia Veleno',
'전원소수호':'Guardia Totale',
'강철의':'Corazzato',
'반사의':'Riflettente',
'가시의':'Spinoso',
'흡수의':'Assorbente',
'인내의':'Resistente',
'위기의':'Disperato',
'피격반격의':'Contrattaccante',
'패링폭발의':'Esplosione Parata',
'스태거폭발의':'Esplosione Barcollamento',
'원소전환의':'Convertitore',
'정화의':'Purificatore',
'불굴의':'Irremovibile',
'부활의':'Rianimatore',
'약탈의':'Saccheggiante',
'경험의':'Esperto',
'골드의':'Dorato',
'포션강화의':'Potente',
'사슬의':'Incatenato',
'진혼의':'Santificante',
'윤회의':'Ciclico',
'생명력의':'Vigoroso',
'재생의':'Rigenerante',
'치유의':'Curativo',
'마력의':'Arcano',
'절약의':'Efficiente',
'영혼의':'dell\'Anima',
'예리한':'Affilato',
'맹렬한':'Brutale',
'파멸의':'Rovinoso',
'게임 설정':'Impostazioni Gioco',
'화면 흔들림':'Vibrazione Schermo',
'파티클 양':'Quantità Particelle',
'효과음 볼륨':'Volume Effetti',
'음악 볼륨':'Volume Musica',
'난이도':'Difficoltà',
'자동 물약':'Pozione Auto',
'최소 줍기 등급':'Grado Min. Raccolta',
'최소 줍기 티어':'Tier Min. Raccolta',
'FPS 제한':'Limite FPS',
'해상도 스케일':'Scala Risoluzione',
'펫 자동수거':'Auto-Raccolta Pet',
'화면 설정':'Impostazioni Schermo',
'화면 모드':'Modalità Schermo',
'보스 AI 디버그':'Debug IA Boss',
'유령불꽃 크기':'Dimensione Fiamma Fantasma',
'화면 명암':'Luminosità',
'유령 글로우':'Bagliore Fantasma',
'기동:칼날개 AUTO':'Ala Lama AUTO',
'일반':'Normale',
'어려움':'Difficile',
'지옥':'Inferno',
'이상':'o superiore',
'사용 안 함':'Disattivato',
'창 모드':'Finestra',
'보더리스':'Senza Bordi',
'전체화면':'Schermo Intero',
'설정':'Impostazioni',
'조작 키 설정 (클릭하여 변경)':'Tasti (Clicca per Cambiare)',
'좌클릭 무기 공격':'Clic Sin Attacco Arma',
'우클릭 탭 칼등 처내기':'Clic Destro Parata Lama',
'우클릭 홀드 연속 처내기':'Tenere Destro Parata Continua',
'SHIFT 작살 발사':'SHIFT Lancia Rampone',
'이동':'Movimento',
'아이템 줍기':'Raccogliere Oggetto',
'능력치 (스탯/패시브)':'Attributi (Stats/Passivi)',
'분해':'Smontare',
'제작':'Fabbricare',
'사망':'Morte',
'부활':'Resurrezione',
'로비로':'Alla Lobby',
'가방에 공간이 없습니다!':'Nessuno spazio!',
'가방이 가득 찼습니다!':'Zaino pieno!',
'창고가 가득 찼습니다!':'Deposito pieno!',
'퀵슬롯이 가득 찼습니다!':'Slot rapido pieno!',
'결정 주머니가 가득 찼습니다!':'Sacca cristalli piena!',
'결정 주머니 가득!':'Sacca cristalli piena!',
'악의가 부족합니다!':'Malizia insufficiente!',
'가방이 비어있습니다':'Zaino vuoto',
'창고가 비어있습니다':'Deposito vuoto',
'비어있음':'Vuoto',
'어픽스 없음':'Nessun affisso',
'장착!':'Equipaggiato!',
'해제':'Rimosso',
'보관':'Depositare',
'꺼내기':'Ritirare',
'현재 장착':'Equipaggiato attuale',
'없음 — 제작하세요!':'Nessuno — Fabbricane uno!',
'리셋할 포인트가 없습니다':'Nessun punto da resettare',
'키 설정 초기화 완료':'Tasti resettati',
'제작 확률':'Prob. fabbricazione',
'제작 비용':'Costo fabbricazione',
'보유 악의':'Malizia posseduta',
'보스방':'Stanza Boss',
'안식처':'Santuario',
'회복':'Recupero',
'점화':'Accendere',
'비석':'Stele',
'읽기':'Leggere',
'파괴':'Distruggere',
'제단':'Altare',
'기원':'Pregare',
'잔해':'Macerie',
'열기':'Aprire',
'문지기':'Guardiano',
'부활 판정 중...':'Giudizio resurrezione...',
'기폭 준비!':'Detonazione pronta!',
'탈출':'Fuggire',
'연타':'Premere',
'추적암전':'Fulmine Tracciante',
'만화광선':'Raggio Luminescente',
'최종 마법':'Magia Finale',
'감시중':'Sorveglianza',
'대기':'Attesa',
'작동중':'Attivo',
'설치 가능':'Installabile',
'균열 임박!':'Breccia imminente!',
'흡수 중...':'Assorbimento...',
'흡수 완료 — 재입력으로 회수':'Fatto — ri-premere per raccogliere',
'화상':'Bruciatura',
'당기기':'Tirare',
'밀어내기':'Spingere',
'단계':'livello',
'단':'livello',
'습득!':'Appreso!',
'리셋!':'Resettato!',
'세팅!':'Impostato!',
'회수':'Recuperare',
'합체 해제':'Defondere',
'리셋':'Resettare',
'환불':'Rimborso',
'파트너 클릭!':'Clicca partner!',
'SP부족!':'SP insufficiente!',
'같은 보석 스킬 습득 시 합체 가능':'Fondibile imparando stessa gemma',
'펼쳐서 초기화':'Espandi per resettare',
'슬롯:':'Slot:',
'남은 SP':'SP Rimanenti',
'맞아서 사망':'Morto per colpo',
'레벨':'Livello',
'최대HP':'HP Massimi',
'방랑 기사':'Cavaliere Errante',
'보물 악마':'Demone Tesoro',
'거울의 사도':'Apostolo Specchio',
'상인 악마':'Demone Mercante',
'사슬의 죄수':'Prigioniero Incatenato',
'시간의 사도':'Apostolo del Tempo',
'탐욕의 사도':'Apostolo Avidità',
'저주받은 쌍둥이':'Gemelli Maledetti',
'차원 균열체':'Entità Dimensionale',
'죽음 그 자체':'La Morte in Persona',
'HP결정':'Cristallo HP',
'ST결정':'Cristallo ST',
'MP결정':'Cristallo MP',
'ATK결정':'Cristallo ATK',
'DEF결정':'Cristallo DEF',
'속도결정':'Cristallo Velocità',
'크리결정':'Cristallo Critico',
'치명결정':'Cristallo DannoCrit',
'화염결정':'Cristallo Fuoco',
'냉기결정':'Cristallo Ghiaccio',
'암흑결정':'Cristallo Oscurità',
'번개결정':'Cristallo Fulmine',
'신성결정':'Cristallo Sacro',
'생명결정':'Cristallo Vita',
'기력결정':'Cristallo Resistenza',
'마력결정':'Cristallo Mana',
'행운결정':'Cristallo Fortuna',
'조각':'Frammento',
'파편':'Scheggia',
'순수결정':'Cristallo Puro',
'완전결정':'Cristallo Perfetto',
'결정 주머니':'Sacca Cristalli',
'결정이 없습니다':'Nessun cristallo',
'가루':'Polvere',
'전체':'Tutto',
'스탯':'Statistiche',
'원소':'Elemento',
'유틸':'Utilità',
'현재':'Attuale',
'최대 강화 달성 (+20)':'Potenz. max (+20)',
'강화 시':'Dopo potenziamento',
'합성':'Sintetizzare',
'같은 종류·같은 성급 결정 3개 → 1성급 상승 (강화 리셋)':'3 cristalli stesso tipo e grado → sale 1 grado (potenziamento reset)',
'합성 가능한 결정이 없습니다 (같은 종류·성급 3개 필요)':'Nessun cristallo sintetizzabile (servono 3)',
'결정 분해 → 결정 가루':'Decomporre Cristallo → Polvere',
'분해할 결정이 없습니다':'Nessun cristallo da decomporre',
'결정 제작 (가루 → 결정)':'Fabbricare Cristallo (Polvere → Cristallo)',
'탈착':'Staccare',
'빈 슬롯':'Slot vuoto',
'결정 선택 후 클릭':'Seleziona cristallo poi clicca',
'클릭하여 선택결정 장착':'Clicca per equipaggiare cristallo',
'획득!':'Ottenuto!',
'제작!':'Fabbricato!',
'합성!':'Sintetizzato!',
'최상위 일괄합성':'Sintesi massiva',
'일괄합성 완료':'Sintesi massiva completata',
'벌레굴':'Nido di Vermi',
'얼음굴':'Caverna di Ghiaccio',
'고통의 화염지대':'Landa Infernale',
'지옥의 군단':'Legione Infernale',
'사도의 마굴':'Tana dell\'Apostolo',
'지옥성':'Cittadella Infernale',
'엑소듀서 전사':'Guerriero Exoduser',
'포이즈':'Postura',
'지옥창고':'Deposito Infernale',
'선택분해':'Smontaggio Selettivo',
'쓰레기':'Spazzatura',
'복구 불가!':'Irrecuperabile!',
'중요잠금':'Blocco importante',
'자동 장착!':'Auto-equipaggiato!',
'분해! 가루 +':'Smontato! Polvere +',
'평화보호':'Egida',
'지진폭풍':'Tempesta Sismica',
'회전기폭':'Turbine-Det',
'공격':'Attacco',
'보호막':'Barriera',
'합체 스킬로 통합됨':'Fuso in abilità combinata',
'얼음보주 안에선 사용 불가!':'Non utilizzabile nella Sfera di Ghiaccio!',
'Shift+키로 폭파':'Shift+tasto per detonare',
'취소':'Annulla',
'쿨다운 중...':'Raffreddamento...',
'시전 중...':'Lancio...',
'악의 부족! (12)':'Malizia insuff.! (12)',
'악의 부족! (15)':'Malizia insuff.! (15)',
'악의 부족! (20)':'Malizia insuff.! (20)',
'악의 부족! (10)':'Malizia insuff.! (10)',
'HP 부족!':'HP insufficiente!',
'필살기 슬롯 클릭하여 배정!':'Clicca slot colpo finale!',
'필살기 스킬을 습득하세요':'Impara un colpo finale',
'우클릭(칼등치기)에 합체됨':'Fuso clic destro (parata)',
'T(석궁자동)에 세팅하세요':'Imposta su T (balestra auto)',
'공성쇠뇌 철거 → 이동식':'Balestra assedio smontata → portatile',
'ST 부족! (100)':'ST insuff.! (100)',
'HP 99% 이상!':'HP 99%+!',
'그로기 보스 없음!':'Nessun boss stordito!',
'이미 폭풍 지역!':'Già in zona tempesta!',
'이미 빙풍 지역!':'Già in zona ghiaccio!',
'💎 푸른비 해금!':'💎 Pioggia Azzurra sbloccata!',
'💫 버스트루프 해금!':'💫 Ciclo Raffica sbloccato!',
'👻 유령 허수아비 해금!':'👻 Esca Fantasma sbloccata!',
'쿨 ':'CD ',
'과부하 ':'Sovraccarico ',
'🕊️💎 블루콩!':'🕊️💎 Fagiolo Blu!',
'🛡️💎 빨콩→블루콩!':'🛡️💎 Rosso→Blu!',
'🛡️💎 무지개→블루콩!':'🛡️💎 Arcobaleno→Blu!',
'레어':'Raro',
'슬롯':'Slot',
'성공률':'Tasso Successo',
'AI 자동 강화':'Potenziamento Auto IA',
'최대 강화 달성!':'Potenziamento max raggiunto!',
'최대 강화':'Potenziamento max',
'회복량':'Recupero',
'분해할 아이템이 없습니다.':'Nessun oggetto da smontare.',
'🔨 제작':'🔨 Fabbricare',
'체간':'Postura',
'아이템에 마우스를 올리거나 좌클릭으로 선택하세요':'Passa sopra o clic sinistro per selezionare',
'중독':'Veleno',
'지뢰':'Mina',
'함정':'Trappola',
'산호가시':'Spina Corallo',
'투사체':'Proiettile',
'도트':'DoT',
'레어몹':'Mob Raro',
'구역':'Zona',
'가시!':'Spina!',
'림보':'Limbo',
'색욕':'Lussuria',
'탐식':'Gola',
'탐욕':'Avidità',
'분노':'Ira',
'이단':'Eresia',
'폭력':'Violenza',
'분노!':'Furia!',
'탐욕!':'Avidità!',
'💀 분노 폭발!':'💀 Esplosione Furia!',
'심연의 분노!':'Furia Abissale!',
'쌍둥이의 분노!':'Furia del Gemello!',
'소환굴':'Tana Evocazione',
'처치!':'Eliminato!',
'왕관 착용':'Corona Indossata',
'왕관 해제':'Corona Rimossa',
'맨손':'Mani Nude',
'없음':'Nessuno',
'갑옷':'Armatura',
'부츠':'Stivali',
'매직':'Magia',
'챔피언':'Campione',
'초속':'Celerità',
'강타':'Schianto',
'재생':'Rigenerazione',
'맹독':'Veleno',
'소환':'Evocazione',
'기생':'Parassita',
'분열':'Scissione',
'용암자취':'Scia Lava',
'사망폭발':'Esplosione Mortale',
'화염사슬':'Catena Fuoco',
'광전':'Frenesia',
'텔레포트':'Teletrasporto',
'소용돌이':'Vortice',
'환영':'Fantasma',
'전격반사':'Riflesso Shock',
'감전':'Folgorazione',
'낙뢰':'Tuono',
'연쇄전격':'Fulmine Catena',
'동료불사':'Alleato Immortale',
'영혼포식':'Divoratore Anime',
'시간왜곡':'Distorsione Temporale',
'혼돈변이':'Mutazione Caotica',
'복수자':'Vendicatore',
'마법보초':'Sentinella Magica',
'환영술사':'Illusionista',
'함성':'Grido Guerra',
'치유':'Cura',
'신속':'Rapidità',
'다크 판타지 전사. 거대검+검은 갑옷':'Guerriero dark fantasy. Spadone + Armatura nera',
'⚡ 사슬이동:강화!':'⚡ Catena: Potenziata!',
'⚡ 사슬기동:화염!':'⚡ Catena: Fiamma!',
'달성!':'Raggiunto!',
'ST':'ST',
'부족!':'Insufficiente!',
'타':'Colpo',
'🌀 당기기 모드':'🌀 Modalità Tirare',
'💥 밀어내기 모드':'💥 Modalità Spingere',
'🕊️빨콩 흡수':'🕊️Assorbimento fagiolo rosso',
'🕊️흡수':'🕊️Assorbimento',
'💎유도 폭발!':'💎Esplosione guidata!',
'💥반사 폭발!':'💥Esplosione riflesso!',
'⚡⚡ 참회 귀환!':'⚡⚡ Ritorno Pentimento!',
'⚡ 참회!':'⚡ Pentimento!',
'파도!':'Onda!',
'암전!':'Fulmine!',
'암흑!':'Oscurità!',
'암흑창!':'Lancia Oscura!',
'빛창!':'Lancia di Luce!',
'체 소환!':'evocato!',
'개 설치!':'piazzato!',
'💥 보스 그로기!':'💥 Boss Stordito!',
'💥 그로기!':'💥 Stordito!',
'보상':'Bonus',
'⚡ 암전나선!':'⚡ Elica Fulmine!',
'🌋 지진폭풍!':'🌋 Tempesta Sismica!',
'SP슬롯':'Slot SP',
'F슬롯':'Slot F',
'⚔🩸 독혈해방!':'⚔🩸 Liberazione Peste!',
'⚔ 칼날 해방!':'⚔ Liberazione Lama!',
'🔨🌋 지옥강타!':'🔨🌋 Colpo Infernale!',
'🔨 대왕치기!':'🔨 Colpo Gigante!',
'✟ 결계의 영역!':'✟ Dominio Protezione!',
'✟ 물의 영역!':'✟ Dominio Acqua!',
'✟ 파쇄의 영역!':'✟ Dominio Frantumazione!',
'✟ 침식의 영역!':'✟ Dominio Corrosione!',
'✟ 관통의 영역!':'✟ Dominio Penetrazione!',
'✟ 권능의 영역!':'✟ Dominio Sovrano!',
'🛡 회복의 영역!':'🛡 Sacred Domain!',
'임계...!':'Critico...!',
'기폭팔!':'Detonare!',
'강제기폭!':'Detonazione forzata!',
'자동기폭!':'Detonazione auto!',
'회전기폭!':'Turbine detonare!',
'해제기폭!':'Rilascio detonare!',
'지진기폭!':'Sisma detonare!',
'혼돈의 왕관':'Corona del Caos',
'전지전능의 왕관':'Corona dell\'Onnipotenza',
'악마의 팔찌':'Bracciale Demoniaco',
'생명의 팔찌':'Bracciale della Vita',
'🌊 위→아래 파도!':'🌊 Onda Alto→Basso!',
'🌊 오른→왼 파도!':'🌊 Onda Destra→Sinistra!',
'🌊 아래→위 파도!':'🌊 Onda Basso→Alto!',
'🌊 왼→오른 파도!':'🌊 Onda Sinistra→Destra!',
'무적!':'Invincibile!',
'🪞 반격!':'🪞 Contrattacco!',
'💢 반격!':'💢 Contrattacco!',
'흡수!':'Assorbimento!',
'반격 발사!':'Colpo contrat.!',
'저주! 드랍률 -50%':'Maledizione! Drop -50%',
'도망!':'Fuga!',
'위상!':'Fase!',
'방어!':'Guardia!',
'회수 HP+':'Recuperare HP+',
'이동식 복귀':'Ritorno Mobile',
'약점!':'Debolezza!',
'저항!':'Resistenza!',
'콤보 종료: ':'Fine combo: ',
'악의 +':'Malizia +',
'저주 ':'Maledizione ',
'불발...':'Mancato...',
'작살 약점!':'Debolezza Rampone!',
'전염 x':'Peste x',
'흡수 완료!':'Assorbimento completo!',
'부활 성공!':'Resurrezione riuscita!',
'부활 실패...':'Resurrezione fallita...',
'차원 이동!':'Spostamento Dimensionale!',
'기절 해제':'Stordimento rimosso',
'악의 부족':'Malizia insufficiente',
'스킬 미습득':'Nessuna abilità',
'펼치기':'Espandi',
'접기':'Comprimi',
'조건 미달!':' non soddisfatta!',
'해제!':' Defuso!',
'자동 ON':' Auto ON',
'자동 OFF':' Auto OFF',
'스킬 해제':' abilità rimossa',
'닫기':'Chiudi',
'장착 중':'Equipaggiato',
'보관 아이템':'Oggetto depositato',
'클릭으로 선택 · ESC로 닫기':'Clicca per selezionare · ESC per chiudere',
'선택됨':'Selezionato',
'악의 부족! (30)':'Malizia insuff.! (30)',
'MP 부족! (40)':'MP insuff.! (40)',
'MP 부족! (100)':'MP insuff.! (100)',
'MP 부족! (10)':'MP insuff.! (10)',
'MP 부족! (':'MP insuff.! (',
'✟ 시전...':'✟ Lancio...',
'🌋 시전...':'🌋 Lancio...',
'⛧ 시전...':'⛧ Lancio...',
'❄ 진입!':'❄ Ingresso!',
'🔱 작살!':'🔱 Rampone!',
'레벨 부족! (요구: Lv.':'Livello basso! (Req: Lv.',
' 장착!':' Equipaggiato!',
' 해제':' Rimosso',
'👿 악의 추출: +':'👿 Estrazione Malizia: +',
'F 슬롯 해제':'Slot F rimosso',
'💫 집중...':'💫 Concentrazione...',
'⚡ 마력연사!':'⚡ Raffica Arcana!',
'❄빙결!':'❄Congelato!',
'🟢독!':'🟢Veleno!',
'⚡감전!':'⚡Folgorato!',
'🔥화상!':'🔥Bruciatura!',
'✦ 여신의 가호 — SP+5 AP+3':'✦ Benedizione Dea — SP+5 AP+3',
'⚔ 기동칼날개!':'⚔ Ala Lama!',
'🔥 화염관통!':'🔥 Penetrazione Fuoco!',
'🔱 관통!':'🔱 Penetrazione!',
'⚔ 칼날!':'⚔ Lama!',
'💥 착지!':'💥 Atterraggio!',
'💫 기절!':'💫 Stordito!',
'⚡ 체간삭감!':'⚡ Postura spezzata!',
'⚡ 기동파괴! ':'⚡ Distruzione Catena! T',
'🔥 기동불꽃!':'🔥 Fiamma Catena!',
'🔥 기동불꽃! ':'🔥 Fiamma Catena! T',
'단계 ×':' x',
'⚡ 기동전폭! x':'⚡ Esplosione Catena! x',
'🔥🔥 3중폭!':'🔥🔥 Fiamma x3!',
'🔥🔥🔥 6중폭!':'🔥🔥🔥 Fiamma x6!',
'🔥🔥🔥🔥 9중폭!':'🔥🔥🔥🔥 Fiamma x9!',
'💥 불꽃폭발! ':'💥 Detonazione Fiamma! ',
'🔥 기동불꽃 준비!':'🔥 Fiamma Catena pronta!',
'🔨 기동파괴 준비!':'🔨 Distruzione Catena pronta!',
'⚡ 기동전폭 준비!':'⚡ Esplosione Catena pronta!',
'⚡ 과부하! 5초':'⚡ Sovraccarico! 5s',
'💫 자동 버스트!':'💫 Raffica auto!',
'🔨 칼등날개!':'🔨 Ala Scudo!',
'💥폭발!':'💥Esplosione!',
'🛡️💎 유도반사!':'🛡️💎 Riflesso Guidato!',
'⚡💎 블루콩!':'⚡💎 Fagiolo Blu!',
'💎 블루콩!':'💎 Fagiolo Blu!',
'⚡반사!':'⚡Riflesso!',
'💎 푸른비 OFF':'💎 Pioggia Azzurra OFF',
'💎 푸른비 ON!':'💎 Pioggia Azzurra ON!',
'🔥 지옥진!':'🔥 Formazione Infernale!',
'🔥 업화선!':'🔥 Raggio Infernale!',
'✦ 평화 충격파! ':'✦ Onda Pace! ',
'⚡ 전류 방출!':'⚡ Rilascio Corrente!',
'⚡⚡ 레인라이트닝!':'⚡⚡ Pioggia Fulmini!',
'💫 광역!':'💫 AoE!',
'🔥 불장판!':'🔥 Zona Fuoco!',
'💫 피니셔!':'💫 Finisher!',
'☠ 지옥에서 귀환!':'☠ Ritorno dall\'Inferno!',
'☠ 완전 사망!':'☠ Morte Permanente!',
'⚔ 처형! ':'⚔ Esecuzione! ',
'💥 지뢰!':'💥 Mina!',
'⚠ 함정!':'⚠ Trappola!',
'❌ 우클릭으로! -':'❌ Usa Clic Destro! -',
'❌ Q키로! -':'❌ Usa Q! -',
'💥무지개 폭발! ':'💥Esplosione Arcobaleno! ',
'🛡️💎 블루콩!':'🛡️💎 Fagiolo Blu!',
'⬜화이트볼!':'⬜White Ball!',
'✨💎 블루콩!':'✨💎 Fagiolo Blu!',
'💜다크볼!':'💜Palla Oscura!',
'❄빙판!':'❄Pavimento Ghiaccio!',
'🌨빙결!':'🌨Congelato!',
'🕸둔화!':'🕸Rallentato!',
'⚠트랩!':'⚠Trappola!',
'💀 역병 처형!':'💀 Esecuzione Peste!',
'💥 역병 Finale!':'💥 Finale Peste!',
'⚔ 균열 악마!':'⚔ Demone Faglia!',
'자동회수 HP+':'Auto-Recuperare HP+',
'MP 부족 — 연사 해제':'MP basso — Fuoco rapido OFF',
'MP 부족 — 푸른비 OFF':'MP basso — Pioggia Azzurra OFF',
'🛡️반사!':'🛡️Riflesso!',
'⚡🦴 참회 귀환!':'⚡🦴 Ritorno Pentimento!',
'🦴⚡해골번개!':'🦴⚡Fulmine Ossa!',
'⚡악의폭풍!':'⚡Tempesta Malizia!',
'❄아이스스톰!':'❄Tempesta Ghiaccio!',
'⚡ 암전폭발!':'⚡ Esplosione Fulmine!',
'⚡ 레인라이트닝! x':'⚡ Pioggia Fulmini! x',
'❄ 탈출!':'❄ Fuggire!',
'⚡쉴드!':'⚡Scudo!',
'❄🌪️ 얼음보주!':'❄🌪️ Sfera Ghiaccio!',
'🌪️ 전개!':'🌪️ Dispiegamento!',
'❄ 빙결흡인!':'❄ Vortice Ghiaccio!',
'❄☄ 빙결폭발!':'❄☄ Esplosione Ghiaccio!',
'☄️ 흡인!':'☄️ Vortice!',
'☄️ 대폭발!':'☄️ Mega Esplosione!',
'❄ 얼음보주!':'❄ Sfera Ghiaccio!',
'⏳ 시간왜곡!':'⏳ Time Warp!',
'쿨다운!':'Raffreddamento!',
'❄ 파쇄!':'❄ Frantumazione!',
'☄️💥 대폭발!':'☄️💥 Mega Esplosione!',
'반사!':'Riflesso!',
'💀 도넛!':'💀 Ciambella!',
'💀 전멸!':'💀 Annientamento!',
'🌊 파도!':'🌊 Onda!',
'속박!':'Vincolo!',
'반격!':'Contrattacco!',
'분신!':'Clone!',
'분신 파괴!':'Clone distrutto!',
'무기 해방!':'Liberazione arma!',
'❄프리즌!':'❄Prigione!',
'⚡ 증표 ':'⚡ Segno ',
'흔들!':'Scossa!',
'⚠ 광역 발사!':'⚠ Fuoco AoE!',
'🔥 확산!':'🔥 Propagazione!',
'⚠ 돌진!':'⚠ Carica!',
'🦅 도약!':'🦅 Salto!',
'⚡ 레이저!':'⚡ Laser!',
'🌊 충격파!':'🌊 Onda d\'urto!',
'👹 소환!':'👹 Evocazione!',
'☄ 유성우!':'☄ Pioggia meteoriti!',
'🖐 잡기!':'🖐 Afferrare!',
'🌀 회전참!':'🌀 Turbine!',
'💣 지뢰!':'💣 Mina!',
'🌀 흡인!':'🌀 Aspirazione!',
'🔴 빨간콩 폭풍!':'🔴 Tempesta Fagiolo Rosso!',
'🔴🔴 콩 비!':'🔴🔴 Pioggia Fagioli!',
'🌊 부채꼴 충격파!':'🌊 Onda ventaglio!',
'✴ 멸광 레이저!':'✴ Laser Annientamento!',
'🔴 추적 장판!':'🔴 Zona Tracciamento!',
'💥 속성탄!':'💥 Colpo Elementale!',
'⚔ 검기!':'⚔ Ki Spada!',
'⚔ 재단참!':'⚔ Fendente Mietitore!',
'🌀 나선탄!':'🌀 Colpo Spirale!',
'⚠ 찌르기!':'⚠ Stoccata!',
'🔥🔥 지옥기둥!':'🔥🔥 Pilastro Infernale!',
'⚔ 환영검!':'⚔ Lama Fantasma!',
'💢 반격자세!':'💢 Postura Contrat.!',
'⚔ 연격!':'⚔ Combo!',
'🌑 암흑!':'🌑 Oscurità!',
'👥 분신!':'👥 Clone!',
'🌋 균열!':'🌋 Faglia!',
'🌊 파동!':'🌊 Ondulazione!',
'💣 추적지뢰!':'💣 Mina tracciante!',
'⏪ 되감기!':'⏪ Rewind!',
'🌀 중력장!':'🌀 Campo gravitazionale!',
'🔨 벽밀기!':'🔨 Spingere muro!',
'☠ 독안개!':'☠ Nebbia velenosa!',
'⛓ 감옥!':'⛓ Prigione!',
'⚡ 연쇄번개!':'⚡ Fulmine a catena!',
'🔮 궤도탄!':'🔮 Colpo orbitale!',
'🛡 방패돌진!':'🛡 Carica scudo!',
'🪞 반격자세!':'🪞 Postura Contrat.!',
'⚓ 속박!':'⚓ Vincolo!',
'👤 분신!':'👤 Clone!',
'🖐 탈취!':'🖐 Furto!',
'🔥🔥 용암 지대!':'🔥🔥 Zona lava!',
'🌧🌧 화염 폭격!':'🌧🌧 Raffica fuoco!',
'⚡⚡ 전격 장막!':'⚡⚡ Velo fulmine!',
'💀 내 곁으로!':'💀 Vieni da me!',
'⭕ 안전!':'⭕ Sicuro!',
'💀💀 전멸 폭발!':'💀💀 Esplosione Annientamento!',
'⚡ 쐐기 소멸!':'⚡ Estinzione Cuneo!',
'🌊충격파!':'🌊Onda d\'urto!',
'👿악의+100':'👿Malizia+100',
'💥패링폭발!':'💥Esplosione Parata!',
'균열 충돌! ':'Collisione faglia! ',
'벽 충돌! ':'Collisione muro! ',
'소환!':'Evocazione!',
'환영!':'Fantasma!',
'⚡낙뢰!':'⚡Tuono!',
'⚡빔!':'⚡Raggio!',
'환영술!':'Illusione!',
'💀소환!':'💀Evocazione!',
'🔮주술!':'🔮Maledizione!',
'🩸산란!':'🩸Generazione!',
'💢광폭!':'💢Frenesia!',
'🕷산란!':'🕷Generazione!',
'❄서리!':'❄Gelo!',
'❄빙결파!':'❄Onda Ghiaccio!',
'💀빙마!':'💀Demone Ghiaccio!',
'돌진!':'Carica!',
'충격파!':'Onda d\'urto!',
'독안개!':'Nebbia velenosa!',
'연타!':'Raffica!',
'포효!':'Ruggito!',
'강화!':'Potenziamento!',
'꼬리!':'Coda!',
'은신...':'Furtività...',
'기습!':'Imboscata!',
'산란!':'Generazione!',
'독가스!':'Gas velenoso!',
'소멸...':'Dissoluzione...',
'강타!':'Schianto!',
'분비!':'Secrezione!',
'채찍!':'Frusta!',
'출혈!':'Sanguinamento!',
'급강하!':'Picchiata!',
'방출!':'Scarica!',
'충격!':'Impatto!',
'치유!':'Cura!',
'의식!':'Rituale!',
'지옥불!':'Fuoco infernale!',
'끌려감!':'Trascinato!',
'혀!':'Lingua!',
'응시!':'Sguardo!',
'낙하!':'Caduta!',
'핏방울!':'Goccia sangue!',
'일어남!':'Alzarsi!',
'휩쓸기!':'Spazzata!',
'웅크림':'Accovacciato',
'뼈칼날!':'Lama d\'osso!',
'감속!':'Rallentato!',
'비명!':'Urlo!',
'화산탄!':'Colpo vulcanico!',
'자폭!':'Autodistruzione!',
'감싸기!':'Avvolgere!',
'잡기!':'Afferrare!',
'내리찍기!':'Colpo!',
'브레스!':'Soffio!',
'비행!':'Volo!',
'용암비!':'Pioggia lava!',
'물뿜기!':'Getto acqua!',
'빛...':'Luce...',
'삼키기!':'Ingoiare!',
'마비!':'Paralisi!',
'방전!':'Scarica!',
'집게찍기!':'Tenaglia!',
'찍기!':'Colpo!',
'붙잡기!':'Afferrare!',
'감아올리기!':'Avvolgere!',
'파편!':'Frammento!',
'할퀴기!':'Graffio!',
'기생충!':'Parassita!',
'심연 해방!':'Liberazione abissale!',
'촉수난타!':'Raffica tentacoli!',
'삼지창!':'Tridente!',
'소용돌이!':'Vortice!',
'해일!':'Tsunami!',
'끼걱!':'Scricchiolio!',
'폭발!':'Esplosione!',
'체인!':'Catena!',
'갈기!':'Criniera!',
'공포!':'Terrore!',
'흡혈!':'Drenaggio!',
'베기!':'Fendente!',
'비이이명!!':'Driiiin!!',
'분열!':'Scissione!',
'3연참!':'Triplo fendente!',
'패링!':'Parata!',
'...복사...':'...Copia...',
'불균형...저주!':'Squilibrio...Maledizione!',
'저주!':'Maledizione!',
'균형...강화!':'Equilibrio...Potenziamento!',
'심판의 기둥!':'Pilastro del Giudizio!',
'처형 선고!':'Sentenza Morte!',
'고통의 해방!':'Liberazione dolore!',
'너도 느껴봐라!':'Senti anche tu!',
'대검난무!':'Frenesia spadone!',
'촉수!':'Tentacolo!',
'전방위 빔!':'Raggio totale!',
'회피!':'Schivata!',
'[F] 상점':'[F] Negozio',
'거래 성공!':'Commercio riuscito!',
'악의 부족! (':'Malizia insuff.! (',
'상인이 떠납니다...':'Il mercante se ne va...',
'사슬 해방!':'Liberazione catena!',
'완전 해방!':'Liberazione totale!',
'⏪ 시간 되감기!':'⏪ Time Rewind!',
'전환!':'Cambio!',
'부활 ':'Resurrezione ',
'🌀균열!':'🌀Faglia!',
'...사라짐':'...Scomparso',
'낫 베기!':'Fendente falce!',
'☠ 죽음의 선고!':'☠ Sentenza Morte!',
'선고 집행...':'Esecuzione sentenza...',
'⚡패링!':'⚡Parata!',
'경직!':'Barcollamento!',
'⚠ 잡혔다!':'⚠ Afferrato!',
'💥 내던지기!':'💥 Lancio!',
'💥 소용돌이 폭발!':'💥 Esplosione Vortice!',
'👻 순간이동!':'👻 Teletrasporto!',
'💫 기절! 5초':'💫 Stordito! 5s',
'찌르기 반격!':'Contrattacco spinta!',
'💢 폭발!':'💢 Esplosione!',
'반격 실패':'Contrattacco fallito',
'탈취 반격!':'Contrattacco furto!',
'무기 봉인!':'Sigillo arma!',
'냠!':'Gnam!',
'합체!':'Fuso!',
'출구가 열렸다!':'Uscita aperta!',
'보물상자 출현!':'Forziere apparso!',
'출구':'Uscita',
'⚠ 문지기가 살아있다!':'⚠ Guardiano ancora vivo!',
'⏱ 타임어택 ':'⏱ Time Attack ',
'처치율 ':'Tasso Elim. ',
'불사 보호':'Protezione immortale',
'환영 소멸!':'Fantasma scomparso!',
'부활력 ':'Potere Resurrezione ',
'✟ 신성력 억제! (':'✟ Soppressione Sacra! (',
'부활 실패 (':'Resurrezione fallita (',
'⚡순간이동!':'⚡Teletrasporto!',
'👻 동반부활!':'👻 Co-Resurrezione!',
'✟ 신성력 억제!':'✟ Soppressione Sacra!',
'💀 부활 판정 중...':'💀 Giudizio resurrezione...',
'⚔ 문지기 처치!':'⚔ Guardiano Eliminato!',
'🚪 보스방 개방!':'🚪 Stanza Boss Aperta!',
'잔해 출현!':'Macerie apparse!',
'🌀균열 발생!':'🌀Faglia aperta!',
'🔥복수!':'🔥Vendetta!',
'💥폭독혈!':'💥Sangue Peste!',
'빙판!':'Pavimento Ghiaccio!',
'❄최종빙결!':'❄Congelamento Finale!',
'빙마 처치!':'Demone Ghiaccio Eliminato!',
'분리!':'Separazione!',
'뼈 파편!':'Frammento osso!',
'태아 처치!':'Feto Eliminato!',
'지배자 처치!':'Signore Eliminato!',
'용암!':'Lava!',
'화룡 처치!':'Drago Fuoco Eliminato!',
'최후의 비명!':'Urlo Finale!',
'산화...':'Ossidazione...',
'심판자 처치!':'Giudice Eliminato!',
'고통의 왕 처치!':'Re Dolore Eliminato!',
'수역!':'Acqua!',
'파편 폭발!':'Esplosione frammento!',
'거대어 처치!':'Leviatano Eliminato!',
'대사도 처치!':'Alto Apostolo Eliminato!',
'독웅덩이!':'Pozza veleno!',
'화염장판!':'Zona Fuoco!',
'전기장!':'Campo elettrico!',
'무기 드롭!':'Arma caduta!',
'보물 발견!':'Tesoro trovato!',
'상인의 주머니 +':'Sacca mercante +',
'속박의 파편!':'Scheggia vincolo!',
'시간의 조각!':'Frammento tempo!',
'저주 해제!':'Maledizione rimossa!',
'차원의 결정!':'Cristallo dimensionale!',
'전설 아이템!':'Oggetto leggendario!',
'죽음을 이겨냈다!':'Superare la morte!',
'💥대폭발!':'💥Mega Esplosione!',
'⚡강화!':'⚡Potenziamento!',
'장비 ':'Equipagg. ',
'💫 진동!':'💫 Tremore!',
'❄ 무적!':'❄ Invincibile!',
'👻 유령!':'👻 Fantasma!',
'집중 해제!':'Concentrazione annullata!',
'집중!':'Concentrazione!',
'🕊️ 평화보호 ':'🕊️ Egida ',
'🛡 보호막 ':'🛡 Scudo ',
'🌀 회전보호막 ':'🌀 Scudo Rotante ',
'💥한방캡!':'💥Limite un colpo!',
'⚡쉴드 파괴!':'⚡Scudo distrutto!',
'💀 불굴!':'💀 Irremovibile!',
'💀 1회부활!':'💀 1 vita resurrezione!',
'감시 회수':'Recupera sentinella',
'악마화 부활!':'Resurrezione demoniaca!',
'배정 가능한 스킬 없음':'Nessuna abilità da assegnare',
'칼날 없음!':'Nessuna lama!',
'⚔ 악의사냥!':'⚔ Caccia Malizia!',
'❄🌪️ 얼음소용돌이!':'❄🌪️ Vortice Ghiaccio!',
'🌪️ 폭풍소환!':'🌪️ Evocazione Vortice!',
'🦴 해골무덤!':'🦴 Tomba Ossa!',
'🌹 붉은꽃!':'🌹 Fiore Cremisi!',
'💥 폭산탄!':'💥 Colpo Esplosivo!',
'🪡 바늘출!':'🪡 Scarica di Aghi!',
'⚡ 전격이동!':'⚡ Passo Fulmine!',
'기둥가시로 흡수됨':'Assorbito da spina pilastro',
'🌿 가시덫!':'🌿 Trappola Spine!',
'👻 유령총!':'👻 Pistola Fantasma!',
'💥 유령총 폭발!':'💥 Esplosione Pistola Fantasma!',
'⚡ 전격의창!':'⚡ Lancia Tuono!',
'🏹 공성쇠뇌 설치!':'🏹 Balestra Assedio piazzata!',
'👻 유령 허수아비!':'👻 Esca Fantasma!',
'💥 폭발 허수아비!':'💥 Esca Esplosiva!',
'축적!':'Immagazzinato!',
'축적 중...':'Immagazzinamento...',
'만충! 재입력→폭발':'Pieno! Ri-premere→Esplodere',
'폭발! ':'Esplodere! ',
'뎀':' DMG',
'🩸 폭독칼날!':'🩸 Lama Pestilente!',
'⚡날개치기!':'⚡Colpo Ala!',
'🗡 칼등날개!':'🗡 Ala Scudo!',
'🏛️ 악의기둥!':'🏛️ Pilastro Oscuro!',
'🌿 기둥가시!':'🌿 Spina Pilastro!',
'🌋 지옥강타!':'🌋 Colpo Infernale!',
'💥 체간 붕괴!':'💥 Postura Spezzata!',
'💫 포이즈 파괴!':'💫 Postura Distrutta!',
'⚡ 뇌전걸음!':'⚡ Passo Fantasma!',
'✟ 구속의 영역!':'✟ Dominio Vincolante!',
'✟ 신성폭발!':'✟ Esplosione Sacra!',
'⛧ 블랙!':'⛧ Stella Nera!',
'🌋 용암소환!':'🌋 Evocazione Lava!',
'필살기 배정!':'Colpo finale assegnato!',
'완료':'Completo',
'합체 가능':'Può Fondere',
'부족':'Insufficiente',
'SP 부족! (':'SP insuff.! (',
'🕊️ 히든: 평화의보호 해금!':'🕊️ Nascosto: Egida della Pace sbloccata!',
'⚡ 히든: 참회 해금!':'⚡ Nascosto: Pentimento sbloccato!',
'배정됨':'Assegnato',
'합체 Lv.':'Fusione Lv.',
'◆ 같은 보석 스킬 습득 시 합체 가능':'◆ Fondibile imparando stessa gemma',
'▼ 가방 → 창고 보관':'▼ Zaino → Deposito',
'▲ 창고 → 가방 꺼내기':'▲ Deposito → Zaino',
'✓ 선택됨':'✓ Selezionato',
'⟨ 입력 대기... ⟩':'⟨ Waiting... ⟩',
'⟨ 대기 ⟩':'⟨ Wait ⟩',
'보조':'Secondario',
'키 설정 초기화 (또는 F5 키)':'Resetta tasti (o F5)',
'아무 키 또는 마우스 버튼을 누르세요 (ESC = 취소)':'Premi un tasto o bottone (ESC = annulla)',
'WebGPU 활성':'WebGPU Attivo',
'WebGL2 활성':'WebGL2 Attivo',
'측정 중...':'Misurazione...',
'불러오기 실패':'Caricamento fallito',
'장착':'Equipaggiato',
'🔒 중요잠금 아이템은 분해 선택 불가!':'🔒 Oggetti con blocco importante non selezionabili!',
'장비 강화 (실패 시 재료만 소멸)':'Potenzia equipagg. (se fallisce, materiali persi)',
'강화 보너스 적용':'Bonus potenziamento applicato',
'강화 실패!':'Potenziamento fallito!',
'장착된 장비가 없습니다.':'Nessun equipagg.',
'충분':'Sufficiente',
'더 필요':'Serve di più',
'장비 선택':'Seleziona equipagg.',
'목표치 설정':'Imposta obiettivo',
'악의 투입':'Investi malizia',
'자동 시도':'Tentativo auto',
'목표 강화치':'Potenziamento obiettivo',
'예상 필요 악의':'Malizia est. necessaria',
'보유':'Posseduto',
'강화 시작':'Inizia potenziamento',
'위에서 장비를 선택하세요':'Seleziona equipagg. sopra',
'⬆ 물약 강화 (최대 10단)':'⬆ Potenzia Pozione (max livello 10)',
'필요':'Richiesto',
'악의의 분해로 — 장비를 악의로 갈아버려라':'Fornace Malizia — Macina equipagg.',
'전체 선택':'Seleziona tutto',
'전체 해제':'Deseleziona tutto',
'희귀 이하':'Raro o inferiore',
'어픽스 리롤!':'Rilancia affisso!',
'영웅':'Eroico',
'전설':'Leggendario',
'무기 타입':'Tipo Arma',
'활 타입':'Tipo Arco',
'ST 부족':'ST insufficiente',
'💀 광폭화!':'💀 Infuriato!',
'...따라오는 거 아니야. 같은 방향일 뿐이지.':'...Non ti seguo. Stessa direzione e basta.',
'공기가 달라졌어. 더 썩었군.':'L\'aria è cambiata. Più marcio.',
'여기부터는 악마 영역이야. ...맘대로 해.':'Territorio demoniaco da qui. ...Fai come vuoi.',
'...이 냄새. 살점이 썩는 냄새야.':'...Quell\'odore. Carne in decomposizione.',
'여기 오래 있으면 미쳐. 나도, 너도.':'Resta troppo e impazzirai. Anch\'io.',
'이 길의 끝에 뭐가 있을까. ...알고 싶지도 않어.':'What\'s at the end of this road? ...I don\'t want to know.',
'...여기가 끝이야. 돌아갈 길은 없어.':'...Questa è la fine. Nessun ritorno.',
'작살을 땅에 꽂으면 끌려간다.':'Conficca il rampone nel suolo e sarai trascinato.',
'Shift로 작살 던져봐!':'Prova a lanciare il rampone con Shift!',
'패링 성공하면 ST가 회복된다. 공짜 자원이야.':'Parare recupera ST. Risorse gratuite.',
'패링 많이 하면 ST 걱정 없어~':'Para spesso e niente problemi di ST~',
'장비 분해하면 악의를 얻는다. 쓰레기도 자원이야.':'Smontare equipaggiamento dà Malizia. Anche la spazzatura è risorsa.',
'TAB 열어서 안 쓰는 장비 분해해!':'Apri TAB e smonta l\'equipaggiamento inutilizzato!',
'그로기 상태의 적에겐 1.5배 데미지가 들어간다.':'I nemici storditi subiscono 1.5x danni.',
'무릎 꿇으면 전력으로 때려!':'Quando si inginocchiano, colpisci con tutto!',
'속성 상성이 있다. 화염은 빙결에 약하고, 암전은 암흑에 약하다.':'Gli elementi hanno contatori. Fuoco debole a Ghiaccio, Fulmine a Oscurità.',
'무기 속성 바꿔가면서 싸워봐!':'Prova a cambiare l\'elemento dell\'arma!',
'빙결된 적은 1.5배 데미지를 받는다.':'I nemici congelati subiscono 1.5x danni.',
'얼리고 때리는 게 기본이야!':'Congela e colpisci — è la base!',
'보스의 빨간 공격은 패링 가능. 보라빛은 회피만.':'Gli attacchi rossi del boss si parano. Arcobaleno, solo schivare.',
'색깔 잘 봐! 빨강은 받아치고 무지개는 피해!':'Guarda i colori! Para il rosso, schiva l\'arcobaleno!',
'VIT를 올리면 최대 HP가 오른다. 죽기 싫으면 찍어.':'VIT alza gli HP massimi. Investi se vuoi sopravvivere.',
'STR은 근접, DEX는 활, INT는 마법! 골고루 말고 하나만!':'STR mischia, DEX arco, INT magia! Concentrati su uno!',
'E를 꾹 누르면 빔이 나간다. 짧게 누르면 투사체.':'Tieni E per il raggio. Premi breve per proiettile.',
'마법 쓸 때 MP 잘 봐! 빔은 연속으로 깎여!':'Controlla il MP con la magia! Il raggio drena velocemente!',
'핵터와 디로이가 아이템을 주워준다. 수거 범위 안이면.':'Hecter e Deroy raccolgono oggetti nel raggio.',
'우리한테 고마워해~ 안 주우면 썩잖아.':'Ringraziaci~ Se nessuno raccoglie, marciscono.',
'LCK를 올리면 레어 드롭률이 오른다.':'LCK aumenta il tasso di drop raro.',
'운빨 게임이긴 하지~ LCK 올려봐!':'È un gioco di fortuna~ Alza LCK!',
'강화하면 공격력이 쭉쭉 올라가! 악의만 있으면 돼!':'Potenziare alza l\'ATK velocemente! Serve solo Malizia!',
'강화 확률은 +1에서 99%. 높을수록 떨어진다.':'Probabilità di potenziamento inizia al 99% per +1. Diminuisce salendo.',
'실패하면 악의만 날아가~ 장비는 안 부서져!':'Se fallisci, solo la Malizia è persa~ L\'equipaggiamento sopravvive!',
'대장간에서 장비 제작도 된다. 악의 30000개면 영웅급 이상.':'La forgia può fabbricare equipaggiamento. 30000 Malizia per Eroico+.',
'랜덤이지만 좋은 거 나올 수도 있어!':'È casuale, ma potrebbe uscire qualcosa di buono!',
'쉴드는 마법으로, HP는 물리로 깎아야 제대로 먹힌다.':'Scudo con magia, HP con fisico per essere efficace.',
'반대로 치면 50%만 들어가! 무기 바꿔가면서 싸워!':'Il tipo sbagliato fa solo 50%! Cambia arma!',
'장비에 접두사, 접미사가 붙으면 특수 효과가 생긴다.':'L\'equipaggiamento con prefisso/suffisso ha effetti speciali.',
'영웅급 이상 장비에만 붙어! 좋은 거 나오면 강화해!':'Solo su equipaggiamento Eroico+! Potenzia quelli buoni!',
'강화는 장비를 바꿔도 자동 이전된다. 악의만 있으면.':'Il potenziamento si trasferisce automaticamente. Costa solo Malizia.',
'더 좋은 장비 나오면 바로 장착해! 강화 수치 그대로 옮겨가!':'Equipaggia l\'equipaggiamento migliore subito! Il potenziamento si trasferisce!',
'패링을 써야 자원을 흡수한다고!':'Devi parare per assorbire le risorse!',
'F키 회복의 영역을 써봐. 자원이 차올라.':'Prova F Dominio Sacro. Le risorse si riempiono.',
'적이 근접하면 스페이스키야! 가시덫을 활용해!':'Quando si avvicinano, Spazio! Usa Trappola di Spine!',
'기절시켜! 그로기가 터지면 데미지가 1.5배야!':'Stordiscili! Stordito significa 1.5x danni!',
'1번 대왕치기로 밀어버려!':'Usa tasto 1 Colpo Gigante per respingere!',
'무릎 꿇었다.':'Si inginocchia.',
'지금이야! 몰아쳐!!':'Adesso! Attacca!!',
'스킬 포인트 있어! K 눌러서 스킬 찍어봐!':'Hai punti! Premi K per le abilità!',
'...힘이 없으면 여기서 끝이야.':'...Senza potere, finisce qui.',
'...쓸 거 아니면 분해해.':'...Se non lo usi, smontalo.',
'아이템 넘쳐나네~ 우리가 주워줄게!':'Tanti oggetti~ Li raccoglieremo!',
'악의가 바닥이다.':'Senza Malizia.',
'TAB 열어서 장비 분해해! 쓰레기도 악의가 돼!':'Apri TAB e smonta! Anche la spazzatura diventa Malizia!',
'좋은 장비가 있네! G 눌러서 대장간 가봐!':'Buon equipaggiamento! Premi G per la forgia!',
'...강화 안 하면 그냥 고철이야.':'...Senza potenziamento, è solo rottame.',
'...멈추지 마. 여신은 기다리지 않는다.':'...Non fermarti. La dea non aspetta.',
'앞으로 가자~ 나도 여기 오래 있기 싫어.':'Andiamo avanti~ Neanch\'io voglio restare!',
'...냄새가 짙다. 큰 놈이 있어.':'...L\'odore è denso. Qualcosa di grosso.',
'준비됐어? 물약 확인하고!':'Pronto? Controlla le pozioni!',
'TAB을 눌러. 가방을 열고 장비를 입어야 한다.':'Premi TAB. Apri lo zaino e equipaggiati.',
'주웠으면 껴야지! TAB!':'L\'hai raccolto? Equipaggialo! TAB!',
'G. 대장간에서 물약도 제작할 수 있다.':'G. Puoi fabbricare pozioni alla forgia.',
'악의로 물약 만들어! G키야!':'Fabbrica pozioni con la Malizia! Tasto G!',
'기절이야! Ctrl 눌러!':'Stordito! Premi Ctrl!',
'Ctrl 유령걸음으로 탈출!':'Ctrl Passo Fantasma per fuggire!',
'Ctrl 얼음보주로 탈출!':'Ctrl Sfera di Ghiaccio per fuggire!',
'빨간 탄은 우클릭 패링. 무지개는 Q 패링.':'Proiettili rossi: parata clic destro. Arcobaleno: Q.',
'나머지는 전부 우클릭 패링 가능해!':'Tutto il resto si para con clic destro!',
'빨강=우클릭, 무지개=Q 패링. 나머진 다 쳐내.':'Rosso=clic destro, Arcobaleno=Q. Devia il resto.',
'무지개는 Q로 패링! 나머지는 전부 우클릭!':'Arcobaleno con Q! Tutto il resto clic destro!',
'빠져! 물약 마시고 안전한 곳에서 회복해.':'Indietreggia! Bevi pozioni e recupera.',
'자원 없으면 도망가는 게 답이야!':'Senza risorse? Fuggire è la risposta!',
'스페이스! 가시덫으로 적 묶어버려!':'Spazio! Blocca i nemici con la Trappola!',
'근접이 너무 많아! 거리 벌려!':'Troppa mischia! Crea distanza!',
'...둘러싸이면 끝이야. 빠져나와.':'...Se ti circondano, è finita. Esci.',
'1번 대왕치기로 쓸어버려!':'Usa tasto 1 Colpo Gigante per spazzare!',
'그로기 터지면 데미지 1.5배!':'Stordito attiva 1.5x danni!',
'회전참이나 광역기로 몰아! 한 놈씩 상대하면 죽어.':'Usa Turbine o AoE! Uno per uno e muori!',
'뭉쳐있을 때가 기회야!':'Quando si raggruppano, è la tua occasione!',
'E로 마력공격을 해봐! 악의 쉴드를 해제할려면 마법 공격을 해야 해!':'Prova E per gli attacchi magici! Serve magia per rompere gli scudi!',
'쉴드는 마법으로, HP는 물리로. 반대로 치면 데미지 안 들어간다.':'Scudo con magia, HP con fisico. Al contrario non fa danni.',
'L키로 스킬 슬롯에 넣어야 쓸 수 있어.':'Premi L per assegnare abilità agli slot.',
'C키를 눌러. 패시브 포인트가 쌓여있다.':'Premi C. I punti passivi si sono accumulati.',
'C키! 패시브 올리면 진짜 강해져!':'C! I passivi ti rendono molto più forte!',
'스태미나가 부족하다. 무리하지 마.':'Resistenza insufficiente. Non sforzarti.',
'ST 없으면 스킬 못 써! 잠깐 빠져!':'Senza ST niente abilità! Indietreggia!',
'탭 장비창을 열어봐. 아이템을 주워왔어!':'Apri TAB. Abbiamo raccolto un oggetto!',
'좋은 거 나왔다! TAB 열어서 확인해봐!':'È caduto qualcosa di buono! Apri TAB!',
'악의에 중독되면 악마가 돼서 부활력이 생긴대. 저 녀석처럼.':'Dicono che la dipendenza dalla Malizia ti trasforma in demone con potere di resurrezione. Come quello.',
'혹시 너도...?':'Forse anche tu...?',
'데미지가 부족하면 무기류 강화를 해야해!!':'Se manca danno, potenzia le armi!!',
'G키 대장간. 강화 안 하면 여기서 계속 죽어.':'G per la forgia. Senza potenziamenti, morirai qui.',
'시간이 없어. 움직여.':'Non c\'è tempo. Muoviti.',
'멍하게 서있으면 안 돼!':'Non restare fermo!',
'...뭘 기다리는 거야?':'...Cosa aspetti?',
'가자가자! 몬스터가 기다려!':'Andiamo! I mostri aspettano!',
'여기 오래 있으면 위험해.':'Restare qui troppo a lungo è pericoloso.',
'움직여야 해! 가만있으면 둘러싸여!':'Muoviti! Resta fermo e ti circondano!',
'쉬는 건 죽고 나서 해.':'Riposa dopo la morte.',
'살아있을 때 쉬면 안 돼!':'Niente riposo finché sei vivo!',
'적이 몰려오고 있어. 빨리 움직여.':'I nemici si avvicinano. Muoviti veloce.',
'냄새 맡고 올 거야. 빨리!':'Ti fiuteranno! Veloce!',
'...아직 살아있는 거 맞지?':'...Sei ancora vivo, vero?',
'혹시 잠든 거야...?':'Ti sei addormentato...?',
'...나무가 썩어가고 있어. 여기는 지옥의 입구야.':'...Gli alberi marciscono. Questo è l\'ingresso dell\'inferno.',
'냄새 지독해... 빨리 지나가자.':'Il fetore è orribile... Passiamo veloce.',
'조심해. 벌레굴이다. 벽이랑 바닥에서 기어나와.':'Attento. Nido di vermi. Escono da muri e pavimento.',
'으으... 벌레 싫어! 밟아버려!':'Ugh... Odio gli insetti! Calpestali!',
'...공기가 얼어붙는다. 여기선 화염이 먹힌다.':'...L\'aria gela. Il fuoco funziona qui.',
'추워... 빙결 조심해! 얼면 끝이야.':'Freddo... Attenzione al congelamento! Se ti congeli, è finita!',
'용암이다. 바닥을 밟으면 타 죽어.':'Lava. Calpesta il suolo e brucerai vivo.',
'뜨거워! 여기 왜 이렇게 빨개!':'Che caldo! Perché tutto è così rosso?!',
'...군단이다. 수가 많아. 광역기 없으면 밀려.':'...La legione. Troppi. Senza AoE sarai sopraffatto.',
'우글우글... 징그러워. 한꺼번에 쓸어!':'Brulicano ovunque... Disgustoso. Spazzali via tutti!',
'사도의 영역이야. 여기 놈들은 머리가 좋아.':'Territorio dell\'Apostolo. Questi sono intelligenti.',
'패턴이 복잡해졌어... 집중해!':'I pattern sono diventati complessi... Concentrati!',
'...끝이다. 지옥의 심장부. 살아 돌아가는 건 포기해라.':'...Questa è la fine. Il cuore dell\'inferno. Abbandona ogni speranza.',
'여기가 마지막이야... 각오해.':'Questa è la fine... Preparati.',
'석궁 자동발사 (T)':'Balestra automatica (T)',
'버스트루프 당기기 (H)':'Ciclo esplosivo attirare (H)',
'결정 자동합성':'Sintesi automatica cristallo',
'결정 자동강화':'Potenziamento automatico cristallo',
'✓ 설정 자동 저장':'✓ Impostazioni salvate automaticamente',
'세팅 프리셋 저장/불러오기':'Salva/carica preimpostazione',
'세팅1 저장':'Salva Preimpostazione 1','세팅1':'Preimpostazione 1',
'세팅2 저장':'Salva Preimpostazione 2','세팅2':'Preimpostazione 2',
'재진단':'Ri-diagnostica',
'게임 리셋 (처음부터)':'Reimposta gioco (dall\'inizio)',
'캐릭터 선택 (로비)':'Selezione personaggio (Lobby)',
'닫기 [ESC]':'Chiudi [ESC]','닫기 [G]':'Chiudi [G]','닫기 [V]':'Chiudi [V]','닫기 [C]':'Chiudi [C]',
'전체화면 (F11)':'Schermo intero (F11)',
'정말 모든 진행을 초기화하시겠습니까?':'Vuoi davvero reimpostare tutti i progressi?',
'검출 중...':'Rilevamento...',
'마우스 커서':'Cursore del mouse','그래픽 품질':'Qualità grafica','하드웨어 진단':'Diagnostica hardware',
'BGM 선택':'Selezione BGM',
'자동 (스테이지별)':'Automatico (per stage)','전체 랜덤':'Tutto casuale','로비':'Lobby',
'1장 랜덤':'Capitolo 1 casuale','2장 랜덤':'Capitolo 2 casuale','3장 랜덤':'Capitolo 3 casuale',
'4장 랜덤':'Capitolo 4 casuale','5장 랜덤':'Capitolo 5 casuale','6장 랜덤':'Capitolo 6 casuale','7장 랜덤':'Capitolo 7 casuale',
'보스':'Boss','최종보스':'Boss finale',
'대장간 랜덤':'Fucina casuale','사망 랜덤':'Morte casuale','승리 랜덤':'Vittoria casuale',
'지옥 추락 사망 징글':'Jingle morte caduta inferno','탈출 성공':'Fuga riuscita',
'── 1장 - 썩은 숲 ──':'── CH1 - Rotten Forest ──',
'── 2장 - 벌레굴 ──':'── CH2 - Worm Nest ──',
'── 3장 - 얼음굴 ──':'── CH3 - Ice Cavern ──',
'── 4장 - 화염지대 ──':'── CH4 - Infernal Wastes ──',
'── 5장 - 지옥군단 ──':'── CH5 - Hell Legion ──',
'── 6장 - 사도마굴 ──':'── CH6 - Apostle Den ──',
'── 7장 - 지옥성 ──':'── CH7 - Hell Citadel ──',
'── 공통 ──':'── Common ──',
'⌨ 조작법':'⌨ Controlli','클릭하면 닫힘':'Clicca per chiudere',
'전투력':'PC','가방':'Borsa','결정':'Cristallo',
'↕ 정렬':'↕ Ordina','쓰레기 전체선택':'Seleziona tutto il ciarpame','쓰레기 전부 분해':'Smantella tutto il ciarpame',
'창고':'Magazzino','스탯 포인트':'Punti attributo','능력치 요약':'Riepilogo statistiche','올 리셋':'Azzera tutto',
'대장간':'Fucina','스킬':'Abilità','능력치':'Statistiche',
'좌클스킬 (클릭 전환)':'Abilità clic sinistro (clic per cambiare)','우클스킬 (클릭 전환)':'Abilità clic destro (clic per cambiare)',
'이동스킬 (클릭 전환)':'Abilità movimento (clic per cambiare)','마법스킬 (클릭 전환)':'Abilità magia (clic per cambiare)',
'영역스킬 (클릭 전환)':'Abilità area (clic per cambiare)','피보호막 (클릭 전환)':'Scudo di sangue (clic per cambiare)',
'CT스킬 (클릭 전환)':'Abilità CT (clic per cambiare)','[C] 능력치':'[C] Statistiche',
'무기 공격':'Attacco con arma','칼등 처내기 (투사체 반사, 홀드 연사)':'Parata (respinge proiettili, tieni=raffica)',
'연속 처내기':'Parata continua','영역 스킬 (폭풍소환 등)':'Abilità area (Vortice ecc)',
'작살 발사':'Sparare arpione','마법 (탭=투사체, 홀드=빔)':'Magia (tocco=proiettile, tieni=raggio)',
'데빌포스 흡수':'Assorbire Forza Demoniaca','물약 / 스킬슬롯':'Pozioni / Slot abilità',
'스킬슬롯 5 / 필살기 / CT스킬':'Slot 5 / Definitiva / Abilità CT','스킬 슬롯 배정':'Assegnazione slot',
// --- Phase 27 additions ---
'위로 이동':'Muovi Su','아래로 이동':'Muovi Giù','왼쪽 이동':'Muovi Sinistra','오른쪽 이동':'Muovi Destra',
'칼등 처내기 (탭=처내기, 홀드=연사)':'Parata (tap=para, tieni=raffica)',
'영역 스킬':'Abilità area','작살 이동':'Scatto arpione',
'유령불꽃 켜기/끄기':'Fantasma Fiamma On/Off','기동칼날개 자동 켜기/끄기':'Lame-ali Auto On/Off',
'해상도':'Risoluzione',
'빛이 꺼졌다':'La Luce Svanisce','누군가는 너를 기다리고 있다':'Qualcuno ti aspetta',
'다시 일어서라':'Rialzati','로비로 돌아가기':'Torna alla lobby',
'☠ 사망 리플레이':'☠ Replay morte',
'지옥의 시련을 견뎌냈다':'Hai superato la prova dell\'inferno','계속 전투':'Continua a combattere',
'난이도를 선택하라':'Scegli la difficoltà',
'나중에 설정(ESC)에서 변경 가능':'Modificabile in Impostazioni (ESC)',
'일괄합성':'Fusione massiva','일괄강화+합성':'Potenziamento+Fusione massivi',
'자원 부족!':'Risorse insufficienti!',' 뎀':' DMG',
'합체 폭발!':'Esplosione di fusione!','MP 부족! (50)':'MP insufficiente! (50)',
'부활력 고갈!':'Resurrezione esaurita!','☠ 부활력 고갈!':'☠ Resurrezione esaurita!',
'독안개':'Nebbia Velenosa','뇌전창':'Lancia del Tuono',
'🔥 업화선 시전...':'🔥 Raggio dell\'Inferno in canalizzazione...',
'💥 기동파괴 그로기!':'💥 Groggy Catena Crush!',
'💥 칼등 그로기!':'💥 Groggy Parata!',
'⚡ 순간이동 준비!':'⚡ Teletrasporto Pronto!',
'👿악의+1000':'👿Malizia+1000',
'💀 내려찍기!':'💀 Schianto!',
'✟ 신성력 억제! +':'✟ Sacro Soppresso! +',
'✟ 신성력 억제!':'✟ Sacro Soppresso!',
'✟ 신성력 억제! (':'✟ Sacro Soppresso! (',
'💥 지진그로기!':'💥 Groggy Terremoto!',
'💥 기폭그로기!':'💥 Groggy Esplosione!',
'폭발! ×':'Esplosione! ×',
'⚫ 기둥강타!':'⚫ Colpo del Pilastro!',
'💥 대왕치기 그로기!':'💥 Groggy Colossale!',
'💫 미니스턴!':'💫 Mini Stordimento!',
'⚡ 뇌전창!':'⚡ Lancia del Tuono!',
'…절반이다. 정신차려.':'…Metà salute. Concentrati.',
'…죽기 직전이다. 한 발만 더.':'…Quasi morto. Un altro colpo.',
'…다음 한 방이 마지막이야.':'…Il prossimo colpo è l\'ultimo.',
'기절! ':'Stordito! ',
'마력이 빈다. 평타 섞어.':'MP sta finendo. Mescola gli attacchi normali.',
'그랩이다. 거리를 둬.':'Attacco presa. Mantieni distanza.',
'광역기다. 멀어져.':'Attacco area. Allontanati.',
'…아파? 당연하지. 여긴 지옥이야.':'…Fa male? Ovvio. Questo è l\'inferno.',
'F키도 스킬 슬롯이야!':'Anche F è uno slot abilità!',
'L-CTRL로 유령걸음/얼음보주!':'L-CTRL per Passo Fantasma/Sfera di Ghiaccio!',
'V 눌러서 창고에 넣어둬!':'Premi V per mettere in magazzino!',
'ESC로 설정! 난이도/자동물약!':'ESC per impostazioni! Difficoltà/Auto-pozione!',
'잡몹이다. 먼저 정리해.':'Mostri normali. Prima elimina quelli.',
'…얼어붙은 놈은 오래 안 간다.':'…Un congelato non durerà a lungo.',
'…냄새가 짙다. 큰 놈이 있어.':'…L\'odore è forte. Qualcosa di grande nelle vicinanze.',
'쉴드는 마법으로, HP는 물리로.':'Lo scudo subisce magia, HP subisce fisico.',
'스페이스! 가시덫으로 적 묶어!':'Space! Intrappola i nemici con Trappola Spine!',
'근접 너무 많아! 거리 벌려!':'Troppi in mischia! Allontanati!',
'회전참이나 광역기로 몰아!':'Usa Fendente Rotante o AOE!',
'F 눌러! 회복의 영역 깔아!':'F! Piazza il Dominio Sacro!',
'F키 회복의 영역을 써봐.':'Prova F-key Dominio Sacro.',
'빠져! 물약 마시고 회복해.':'Indietro! Bevi una pozione e recupera.',
'쉬프트! 사슬기동은 이동기야!':'Shift! La catena è un movimento!',
'스킬포인트 쌓였어! K 눌러!':'Punti abilità accumulati! Premi K!',
'스킬 포인트 있어! K!':'Hai punti abilità! K!',
'C키. 패시브 포인트가 쌓여있다.':'Tasto C. I punti passivi si sono accumulati.',
'…쓸 거 아니면 분해해.':'…Smantella quello che non usi.',
'…강화 안 하면 그냥 고철이야.':'…Senza potenziamento è solo rottame.',
'빨간 탄은 우클릭. 무지개는 Q.':'Proiettili rossi: clic destro. Arcobaleno: Q.',
'빨강=우클릭, 무지개=Q.':'Rosso=clic destro, arcobaleno=Q.',
'…멈추지 마. 여신은 기다리지 않는다.':'…Non fermarti. La dea non aspetta.',
'패턴이 바뀐다. 거리를 둬.':'Il pattern cambia. Mantieni distanza.',
'미쳐가고 있어. 광폭화다.':'Sta impazzendo. Furia.',
'마지막이야! 끝장내!':'Fase finale! Finiscilo!',
'…끝났다. 다음으로.':'…È finita. Avanti.',
'다 잡았다! 포탈 어딨어?':'Tutti eliminati! Dov\'è il portale?',
'근육으로 만든 빌드군. 베고 부숴.':'Build muscolosa. Taglia e spacca.',
'활을 쥐었군. 거리를 둬.':'Ha un arco. Mantieni distanza.',
'마법사군. MP 관리부터 배워라.':'Un mago. Prima impara a gestire l\'MP.',
'운에 기댄 빌드군. …드롭은 좋겠어.':'Build basata sulla fortuna. …Almeno i drop saranno buoni.',
'…VIT가 너무 낮아. 한 방에 죽는다.':'…VIT troppo bassa. Muori in un colpo.',
'다 찍으면 다 약해진다. 하나만 골라.':'Maximi tutto e sei debole ovunque. Scegline uno.',
'…3단. 적이 강해져. 정신 차려.':'…Stadio 3. I nemici si rafforzano. Concentrati.',
'5단이다. …너도 강해졌단 뜻이야.':'Stadio 5. …Significa che anche tu sei cresciuto.',
'…7단. 아직 살아있단 게 신기하군.':'…Stadio 7. Ancora vivo. Sorprendente.',
'10단. …너는 이제 인간이 아니야.':'Stadio 10. …Non sei più umano.',
'…일반으로 내려왔군. 가끔은 쉬어가야지.':'…Sceso a Normale. A volte bisogna riposarsi.',
'…이게 진짜 패링이야.':'…Questa è una vera parata.',
'…피가 묻기 시작했군.':'…Il sangue comincia a scorrere.',
'100. 너는 인간이 아니야.':'100. Non sei umano.',
'…피 흘리며 베는군.':'…Tagli attraverso il sangue.',
'빨간콩이 푸르게 변했다. 그게 너의 무기야.':'Il fagiolo rosso è diventato blu. È la tua arma.',
'무지개를 받아쳤군. 그건 진짜 어렵다.':'Hai parato un arcobaleno. È davvero difficile.',
'…너무 빨라. 닿기 직전에 눌러.':'…Troppo veloce. Premi appena prima del contatto.',
'악의가 가득 찼다. 풀어내.':'La malizia è piena. Rilasciala.',
'작살이 살을 뚫었어. 끌고 와.':'L\'arpione ha trafitto la carne. Trascina.',
'…풀차지군. 멀리 던져버려.':'…Carica piena. Lancia lontano.',
'…빈틈을 그대로 빠져나갔다.':'…Scivolato proprio attraverso la falla.',
'…일반 잡몹이 아니야. 모디파이어 붙었군.':'…Non è un mostro normale. Ha un modificatore.',
'엘리트 하나 처리.':'Elite abbattuto.',
'…큰 놈이다. 일반 잡몹 정리부터.':'…Un pezzo grosso. Prima elimina i normali.',
'미니보스 처리. 다음 길로.':'Mini-boss abbattuto. Avanti.',
'한 번에 다섯. 깔끔해.':'Cinque in una volta. Pulito.',
'100강. 이제 뭔가 다르게 보이는군.':'+100. Le cose sembrano diverse ora.',
'…운이 없는 날이야.':'…Giornata sfortunata.',
'…전설이다. 이런 건 처음 본다.':'…Leggendario. Non ho mai visto niente del genere.',
'…죽었다 살아났네. 여신은 너를 포기 안 했어.':'…Morto e tornato. La dea non ti ha abbandonato.',
'…또야? 패턴 좀 외워!':'…Ancora? Impara il pattern!',
'…한 번도 안 죽고. 그건 진짜 실력이야.':'…Mai morto. Questa è vera abilità.',
'…ACT1을 끝냈다. 진짜 시작은 여기서부터야.':'…ATTO1 completato. Il vero inizio è qui.',
'모든 보스를 무너뜨렸다. 너는 지옥의 일부야.':'Tutti i boss caduti. Sei parte dell\'inferno.',
'…30초. 너 진짜 미쳤구나.':'…30 secondi. Sei davvero pazzo.',
'…빠르군. 효율적이야.':'…Veloce. Efficiente.',
'신기록이다.':'Nuovo record.',
'탭 장비창을 열어봐.':'Apri la finestra equipaggiamento con TAB.',
'데미지 부족하면 무기 강화!':'Danno insufficiente? Potenzia l\'arma!',
// --- Loading screen ---
'불러오는 중...':'Caricamento...',
'로딩중...':'Caricamento...',
'맵과 몬스터 불러오는 중...':'Caricamento mappa e mostri...',
'기본 데이터 준비 중...':'Preparazione dati di base...',
'저장 데이터 불러오는 중...':'Caricamento dati salvati...',
'몬스터 스킨 로딩...':'Caricamento skin dei mostri...',
'맵과 몬스터 생성 중...':'Generazione mappa e mostri...',
'맵 에셋 로딩...':'Caricamento risorse mappa...',
'맵 환경 준비 중...':'Preparazione ambiente mappa...',
'주변 청크 준비 중...':'Preparazione chunk vicini...',
'맵 캐시 생성 중...':'Costruzione cache mappa...',
'미니맵 빌드 중...':'Costruzione minimappa...',
// Phase 28
' 으로 탈출!':' per scappare!',
'100명?! 미쳤어!':'100 nemici?! Sei pazzo!',
'10단 최고난이도! 너 진짜 광기야!':'Difficoltà 10 al massimo! Sei completamente folle!',
'1분 안에 클리어! 빠르네!':'Livello completato in 1 min! Così veloce!',
'30초!! 스피드런 가능해!':'30 secondi!! Potenziale speedrun!',
'3단! 보상도 좋아지지만 죽기 쉬워!':'Diff 3! Ricompense migliori ma più facile morire!',
'50명! 학살자야!':'50 nemici! Sei un massacratore!',
'5단!! 진짜 게이머 인증!':'Diff 5!! Vero gamer certificato!',
'7단!! 다른 사람들 이 정도 못 와!':'Diff 7!! Gli altri non arrivano così lontano!',
'ACT1 완주! 우리가 진짜 해냈어!':'ACT1 completato! Ce l\'abbiamo davvero fatta!',
'Ctrl 얼음보주로 탈출하라.':'Ctrl — scappa con l\'Orbe di Ghiaccio.',
'Ctrl 유령걸음으로 탈출하라.':'Ctrl — scappa con il Passo Fantasma.',
'C키! 패시브 강해져!':'Tasto C! I passivi diventano più forti!',
'DEX 빌드! 거리에서 패고, 추적탄 좋아!':'Build DES! Attacca a distanza, i proiettili guidati sono ottimi!',
'E로 마력공격을 해봐!':'Prova l\'attacco magico con E!',
'G 눌러서 대장간 가봐!':'Premi G per visitare la fucina!',
'G키 대장간. 강화 안 하면 계속 죽어.':'G — fucina. Senza potenziamenti, continuerai a morire.',
'HP 70%! 조심해!':'HP 70%! Stai attento!',
'INT 빌드! 빔이랑 폭발 마법! MP 잘 봐!':'Build INT! Raggi e magia esplosiva! Tieni d\'occhio il MP!',
'LCK 높아! 레어 드롭률 미친 거 알지?':'FOR alta! Sai che i tassi di drop sono folli, vero?',
'L로 어디에 뭘 넣을지 골라!':'Premi L per scegliere cosa va in ogni slot!',
'MP 부족! 평타로 패면서 회복해!':'MP basso! Colpisci con attacchi base per recuperare!',
'ST 없으면 스킬 못 써!':'Senza ST, nessuna abilità!',
'STR 빌드! 회전참, 회오리, 광역기 추천!':'Build FOR! Colpo rotante, turbine, AoE raccomandato!',
'VIT 좀 찍어! HP 너무 적어!':'Aggiungi un po\' di VIT! L\'HP è troppo basso!',
'Z 누르면 대박! 쿨타임 길어!':'Premi Z per il colpo forte! Ma il cooldown è lungo!',
'…고기 냄새. 싫진 않네.':'…Odore di sangue. Non è sgradevole.',
'…둘러싸이면 끝이야.':'…Vieni circondato ed è finita.',
'…말은 못해.':'…Non riesco a parlare.',
'…버리기 아까운 건 창고에.':'…Ciò che vale la pena tenere va nel magazzino.',
'…빈틈을 노려.':'…Cerca le aperture.',
'…설정을 확인해.':'…Controlla le tue impostazioni.',
'…슬롯을 채워. 빈 손은 죽음이다.':'…Riempi i tuoi slot. Le mani vuote significano morte.',
'…아직 살아있네. 좌클릭으로 저것들 쳐봐.':'…Ancora vivo. Prova a colpirli con il clic sinistro.',
'…운이 좋았을 뿐이야. 아마.':'…Solo fortuna. Probabilmente.',
'…치는 건 할 줄 아네. 피하는 건?':'…Sai come colpire. E schivare?',
'…힘을 골라라. 전부 가질 순 없다.':'…Scegli la tua forza. Non si può avere tutto.',
'골고루 안 돼! 하나로 밀어!':'Non distribuire le statistiche! Punta su una!',
'그로기 터지면 1.5배!':'Stordito = 1,5x danni!',
'길이 열렸다.':'Il percorso è aperto.',
'나머진 전부 우클릭 패링 가능!':'Tutto il resto può essere parato con il clic destro!',
'나머진 전부 우클릭!':'Tutto il resto — clic destro!',
'다섯 번 연속! 내가 본 인간 중 최고!':'Cinque di fila! Il miglior umano che abbia mai visto!',
'다음엔 죽지 마!':'Non morire la prossima volta!',
'더블탭 전격이동으로 탈출하라.':'Doppio tocco per scivolare e scappare.',
'소환수 왔어! 먼저 처리해야 해!':'Evocazioni in arrivo! Eliminale prima!',
'스킬 없으면 방향키 연타뿐이야.':'Nessuna abilità? Tieni premuti i tasti direzionali.',
'신기록!! 스트리머한테 보내!':'Nuovo record!! Mandalo a uno streamer!',
'아이템 넘쳐! 우리가 주워줄게!':'Borsa piena! Raccoglieremo le cose per te!',
'안 죽고 깼어! 진짜 천재 맞네!':'Completato senza morire! Vero genio!',
'앞으로 가자~':'Andiamo avanti~',
'우리가 해냈어! 다음 챕터 가자!':'Ce l\'abbiamo fatta! Al prossimo capitolo!',
'일반 모드! 편하게 즐기자!':'Modalità normale! Godiamocela tranquilli!',
'자원이 반이다. F키로 회복해.':'Risorse a metà. Premi F per recuperare.',
'잡힌다! 옆으로 빠져!':'Sto per essere afferrato! Muoviti di lato!',
'장비 분해해! 쓰레기도 악의!':'Smantella l\'equipaggiamento! Anche la spazzatura dà malizia!',
'전부 다 잡았어! 우리가 지옥의 왕이야!':'Li abbiamo presi tutti! Siamo i re dell\'inferno!',
'좋은 거 나왔다! TAB!':'Bottino buono caduto! TAB!',
'죽기 직전에 죽이다니! 멋져!':'Uccidere prima di morire! Fantastico!',
'체력 반 남았어! 물약 마실 타이밍!':'Metà HP rimasti! Ora di bere una pozione!',
'큰 거 온다! 도망쳐!':'Grande attacco in arrivo! Scappa!',
'패링으로 돌려주고, Q 보호막도 써!':'Para per riflettere, e usa anche lo scudo Q!',
'패턴이 빨라졌어!':'I pattern si sono accelerati!',
'한 대만 맞아도 죽어! 패링이든 회피든!!':'Un colpo e muori! Para o schiva!!',
'한 방이면 죽어! 도망쳐!!':'Un colpo uccide! Scappa!!',
'화염엔 빙결! 암전엔 암흑!':'Fuoco → gelo! Vuoto → ombra!',
'👻 유령!':'👻 Fantasma!',
'🦴 해골무덤!':'🦴 Tomba di Ossa!',
'☠ 부활력 고갈!':'☠ Resurrezione Esaurita!',
'⏳⚡ 시간걸음!':'⏳⚡ Passo Temporale!',
'블룸 효과':'Effetto Bloom',
'잔상 트레일':'Scia residuale',
'슬래시 이펙트':'Effetto fendente',
'후처리 효과':'Post-elaborazione',
'사망 이펙트':'Effetto morte',
'동적 조명':'Illuminazione dinamica',
'횃불 조명 (어둠)':'Luce torcia (buio)',
'앰비언트 파티클':'Particelle ambientali',
'안개 효과':'Effetto nebbia',
'필름 그레인':'Grana cinematografica',
'캐릭터 외곽선':'Contorno personaggio',
'리롤':'Rilancio',
'물약':'Pozione',
'으로 탈출!':'per scappare!',
'Shift 작살':'Shift Arpione',
'더블탭 전격이동':'Doppio tap — Scatto fulmine',
'Ctrl 유령걸음':'Ctrl Passo fantasma',
'Ctrl 얼음보주':'Ctrl Sfera di ghiaccio',
'🔴화염→빙결 2배 | 🔵빙결→화염 2배 | ⚪물리=중립 | 악마 처치 시 악의 영혼 드롭':'🔴Fuoco→Ghiaccio 2× | 🔵Ghiaccio→Fuoco 2× | ⚪Fis=Neutro | Uccidi demoni per anime di malizia',
  '미구현':'N/A',
  '스탯 총량':'Statistiche totali',
  '장비':'equip.',
  '공속':'vel.atq',
  '크리':'crít',
  '크리뎀':'danno crít',
  '근성':'Tenacia',
  '종합 지표':'Panoramica',
  '근접 DPS':'DPS mischia',
  '공격력×공속×크리':'ATK×Vel×Crít',
  '활 DPS':'DPS arco',
  '마법 DPS':'DPS magia',
  '유효 HP (EHP)':'HP effettivo (EHP)',
  '쉴드':'Scudo',
  '장비 파워':'Potere equip.',
  '근접 공격력':'ATK mischia',
  '기본':'base',
  '무기':'arma',
  '패시브':'passivo',
  '활 공격력':'ATK arco',
  '정밀':'Prec',
  '마법 공격력':'ATK magia',
  '왕관':'corona',
  '마력':'Arcane',
  '공격속도':'Velocità attacco',
  '크리티컬':'Critico',
  '데미지':'danno',
  '확률':'Probabilità',
  '어픽스':'affisso',
  '레거시':'eredità',
  '추가뎀':'danno extra',
  '패링 카운터뎀':'Danno parata',
  '우클공속':'Vel. clic DX',
  '무지개탄DR':'DR arcobaleno',
  '포이즈파괴':'Rompere Poise',
  '방어관통':'Penetrazione armatura',
  '관통력':'Perforazione',
  '속성':'Elementi',
  '무기속성':'Elem. arma',
  '독':'Veleno',
  '초':'s',
  '암흑저주':'Maledizione oscura',
  '원소집중':'Focus elem.',
  '원소전환':'Conv. elem.',
  '방어':'Difesa',
  '물리방어':'DEF fisica',
  '감소':'rid',
  '캡':'limite',
  '장갑':'guanti',
  '바지':'pantaloni',
  '속성방어':'DEF elem.',
  '목걸이':'collana',
  '반지1':'anello1',
  '반지2':'anello2',
  '반사':'Riflesso',
  '가시':'Spine',
  '배리어':'Barriera',
  '보호막 흡수':'Assorbimento scudo',
  '속성 저항':'Resistenza elem',
  'CC저항':'Resistenza CC',
  '생존':'Sopravvivenza',
  '장비HP':'HP equip.',
  '임플':'Impl.',
  '에너지쉴드':'Scudo energetico',
  '리젠':'Regen',
  '스태미나':'Stamina',
  '성장':'Crescita',
  'MP%어픽스':'Affisso MP%',
  '이동속도':'Velocità movimento',
  '한방캡':'Limite singolo colpo',
  '최대HP의33%':'33% HP max',
  '비용/효율':'Costo/Eff',
  '근접ST':'ST mischia',
  '활ST':'ST arco',
  '마법MP':'MP magia',
  '작살사거리':'Gittata rampino',
  '기동게이지':'Indicatore spinta',
  '쿨감':'CDR',
  '쇠뇌뎀':'Danno balestra',
  '쇠뇌공속':'Vel. balestra',
  '기타':'Varie',
  '물약쿨':'CD pozione',
  '회복+':'Recupero+',
  '드롭':'Drop',
  '경험치+':'EXP+',
  '골드+':'Oro+',
  '기동:칼날개':'Spinta:Lama',
  '기동:전폭':'Spinta:Colpo',
  '기동:기습':'Spinta:Imboscata',
  '충전스킬':'Abilità carica',
  '사슬게이지':'Indicatore catena',
  '특수 효과':'Effetti speciali',
  '처치뎀+':'Danno uccisione+',
  '위기뎀+':'Danno crisi+',
  '피격반격':'Controgolpe al colpo',
  '풍요(적HP≥70%뎀+)':'Abbondanza(HP≥70%+)',
  '약자포식(적HP≤30%뎀+)':'Predatore(HP≤30%+)',
  '패링폭발':'Esplosione parata',
  '체간파괴+':'Rompi Poise+',
  '콤보뎀+':'Danno combo+',
  '작살뎀+':'Danno rampino+',
  '스킬뎀+':'Danno abilità+',
  '패리+':'Parata+',
  '체인':'Catena',
  '정화':'Purga',
  '회':'×',
  '불굴':'Tenacia',
  '신성력':'Potere sacro',
  '악마력(부활력)':'Forza demone',
  '자연':'Natura',
  '악마성':'Demonismo',
  '인간성':'Umanità',
  '전투 통계':'Statistiche combattimento',
  '핵터':'Hecter',
'디로이':'Deroy',
'물리 ATK +1, MAX HP +5, HP리젠 +0.002':'ATK fisico +1, HP MAX +5, Regen HP +0.002',
'석궁 ATK +1, 공격속도 +0.05%, MAX ST +2, ST리젠 +0.005, 회피 +0.05%':'ATK arco +1, Vel. attacco +0.05%, ST MAX +2, Regen ST +0.005, Schivata +0.05%',
'마법 ATK +1, MAX MP +2, MP리젠 +0.005, MAX 쉴드 +5':'ATK magia +1, MP MAX +2, Regen MP +0.005, Scudo MAX +5',
'크리확률 +0.025%, 크리뎀 +0.2%, 드롭률 +0.15%':'Prob. critico +0.025%, Danno critico +0.2%, Tasso bottino +0.15%',
'근접뎀 +15%, ST비용 -4%/lv (최대-40%)':'Danno mischia +15%, Costo ST -4%/lv (max -40%)',
'작살 사거리 +2%/lv, 기동게이지 회복 +3%/lv':'Portata arpione +2%/lv, Recupero indicatore +3%/lv',
'카운터뎀 +50%/lv, 우클릭 공속 +10%/lv, 무지개탄 피해감소 +10%/lv (최대50%)':'Danno contro +50%/lv, Vel. attacco clic destro +10%/lv, Riduzione danno proiettile arcobaleno +10%/lv (max 50%)',
'마법뎀 +15%, MP비용 -4%, 시전속도 +8%/lv':'Danno magico +15%, Costo MP -4%, Vel. lancio +8%/lv',
'투사체뎀 +15%, 공속 +10%, 사거리 +8%, ST비용 -4%/lv':'Danno proiettile +15%, Vel. attacco +10%, Portata +8%, Costo ST -4%/lv',
'보호막 흡수 +2%/lv (기본70→최대90%), 보호막 중 HP리젠 +0.1%/lv':'Assorbimento scudo +2%/lv (base 70→max 90%), Regen HP con scudo +0.1%/lv',
'HP/ST리젠 +3%/lv, 물약쿨 -3%/lv':'Regen HP/ST +3%/lv, CD pozione -3%/lv',
'크리률 +2%, 크리뎀 +8%/lv':'Prob. critico +2%, Danno critico +8%/lv',
'아이템 드롭률 +8%/lv':'Tasso bottino +8%/lv',
'투사체 관통률 +5%/lv, 관통횟수 +1/lv, 관통뎀감소 완화':'Tasso penetrazione proiettile +5%/lv, Conteggio penetrazione +1/lv, Riduzione calo danno penetrazione',
'MP리젠 +3%/lv, 쉴드리젠 +3%/lv, 쉴드쿨 -3%/lv':'Regen MP +3%/lv, Regen scudo +3%/lv, CD scudo -3%/lv',
'자동쇠뇌 뎀 +5%/lv, 공속 +5%/lv':'Danno balestra auto +5%/lv, Vel. attacco +5%/lv',
'물리뎀 +15%/lv, HP +3%/lv, ST소모 -5%/lv':'Danno fisico +15%/lv, HP +3%/lv, Consumo ST -5%/lv',
'적에게 약점노출 디버프. 직접 공격 시 스택+1, 스택당 피격뎀 +3%. 최대 Lv×5 중첩 (1렙5, 10렙50). 초당 20% 감소, 5초 미피격 시 리셋. DOT/장판 제외':'Debuff esposizione debolezza sui nemici. Attacco diretto +1 stack, +3% danno subito/stack. Massimo Lv×5 (Lv1=5, Lv10=50). -20%/s, reset dopo 5s senza attacchi. DOT escluso',
'물리→쉴드 패널티 관통 +5%/lv (기본10%, 10lv=60%)':'Penetrazione penalità fisico→scudo +5%/lv (base 10%, lv10=60%)',
'마법→HP 패널티 관통 +5%/lv (기본10%, 10lv=60%)':'Penetrazione penalità magia→HP +5%/lv (base 10%, lv10=60%)',
'적 HP 70%↑: 뎀+20%/lv, 회복력+5%/lv (합연산)':'HP nemico ≥70%: Danno+20%/lv, Recupero+5%/lv (additivo)',
'적HP 30%↓: 뎀+20%/lv. 내HP 30%↓: 회복력+10%/lv, 이속+5%/lv (합연산)':'HP nemico ≤30%: Danno+20%/lv. Mio HP ≤30%: Recup.+10%/lv, Vel.movim.+5%/lv (additivo)',
'DOT 틱뎀 +15%/lv, DOT 지속시간 +10%/lv, DOT 축적률 +5%/lv':'Danno DOT +15%/lv, Durata DOT +10%/lv, Tasso accumulazione DOT +5%/lv',
'MP +50/lv, MP회복 +1%/lv':'MP +50/lv, Regen MP +1%/lv',
'ST +50/lv, ST회복 +1%/lv':'ST +50/lv, Regen ST +1%/lv',
'악의 드롭 +8%/lv':'Drop malizia +8%/lv',
'HP +300/lv':'HP +300/lv',
'DEF +20/lv':'DEF +20/lv',
'엘리트/보스 추가뎀 +10%/lv':'Danno extra élite/boss +10%/lv',
'부활력 -10/lv, 전체 데미지 +5%/lv, HP/MP/ST +100/lv':'Potere resurrezione -10/lv, Danno totale +5%/lv, HP/MP/ST +100/lv',
'부활확률 +2%/lv, 부활HP +5%/lv, 부활쿨 -30초/lv':'Prob. resurrezione +2%/lv, HP resurrezione +5%/lv, CD resurrezione -30s/lv',
// --- Phase 37: skill desc ---
'핵심 광역기 — 먼저 배워서 정리력 확보':'Core AoE — learn first for mob clearing',
'악의 사냥 + 보호자 → 합체: 칼날 해방':'Malice Hunt + Guardian → Fuse: Blade Liberation',
'폭독혈 추가 → 합체: 독혈 해방 (칼날+독)':'Plague Burst → Fuse: Plague Liberation (blade+poison)',
'충돌+화염 → 합체: 사슬기동 (무적이동 핵심)':'Impact+Flame → Fuse: Chain Breach (invincible dash core)',
'사슬 체인 확장 → 기동:파쇄/기동:전폭':'Chain expansion → Slam/Thunder combos',
'필살기 1개 선택! 신성폭발(넉백) / 블랙(흡인) / 용암(화상) / 처형(보스킬)':'Pick 1 ultimate! Holy Blast(knockback) / Black Star(pull) / Lava(burn) / Execution(boss kill)',
'멸살광선+만화방창+원소추적탄+전격이동 → 합체: 추적빔':'Omni Beam+Barrage+Elem Missile+Blink → Fuse: Tracking Beam',
'회전참+기폭+대왕치기 → 합체: 지진폭풍':'Whirlwind+Detonate+Giant Slam → Fuse: Slam Storm',
'칼등치기 + 칼등날개 → 합체: 처내기 강화':'Blade Parry + Shield Wing → Fuse: Parry Enhanced',
'해골무덤 + 악의폭풍 → 합체: 해골번개':'Bone Wall + Malice Storm → Fuse: Bone Lightning',
'폭풍소환 + 얼음보주 → 합체: 얼음폭풍':'Malice Mortar + Ice Orb → Fuse: Ice Mortar',
'유령화 이동 + 전기 폭발':'Ghost phase movement + electric burst',
'회복 + 구속 → 합체: 결계의 영역':'Recovery + Prison → Fuse: Ward Domain',
'지진폭풍+추적암전 → 6단합체: 폭풍빔':'Slam Storm → 6-Fuse: Storm Beam',
'아이스스톰 추가 → 합체: 신성빙결':'Ice Storm → Fuse: Holy Ice',
'암흑기둥 + 가시덫 → 합체: 기둥가시. 대왕치기2는 기둥강타/지옥강타용':'Dark Pillar + Spike Trap → Fuse: Pillar Spike. Giant Slam 2 for Pillar Slam/Inferno Slam',
'기동칼날개 추가 → 5단합체: 기동:칼날개':'Chain Bladewing → 5-Fuse: Maneuver:Bladewing',
'STR 스케일. 3회 충전 + Lv3마다 사거리 1단계↑(최대4단). 이동 중 무적, 통과 적에 데미지+그로기 (쿨 5초)':'STR scale. 3 stocks + range tier up every Lv3 (max 4). Invincible while moving, DMG+groggy on pass-through (CD 5s)',
'INT 스케일. 이동 경로에 화염길 생성(3초 DOT). 통과 적 화상. MP 소모. 합체 시 착지 폭발':'INT scale. Fire trail on dash path (3s DOT). Burns passed enemies. MP cost. Fuse: landing explosion',
'5초간 유령화 — 무적+이동. 통과한 적/탄막 수만큼 종료 시 암전 폭발(+10%/회) + 전기줄기 방사(3회 체인). 카운트 캡=Lv×5(최대50). 쿨 20초. Lv당 뎀+15% 범위+10':'5s ghost form — invincible+move. Blackout explosion on end (+10%/enemy passed) + lightning arc (3 chains). Count cap=Lv×5 (max 50). CD 20s. Per Lv DMG+15% range+10',
'[이동기] 방향키 더블탭으로 발동. 경직/기절 중에도 탈출 가능. 500유닛 순간이동, 무적(15프레임). MP(10+Lv×5). 1렙10충전, 렙당+1. 쿨 8초→Lv당-0.5초(최소3초). 착지 시 전류장판(10초+Lv×0.5초): INT 틱뎀 + 방어력↓(1렙10%, 렙당+5%, 캡50%)':'[Mobility] Double-tap to activate. Escapes stagger/stun. 500-unit blink, invincible 15f. MP(10+Lv×5). Lv1=10 stocks, +1/Lv. CD 8s→-0.5s/Lv (min 3s). Landing shock field(10s+Lv×0.5s): INT tick DMG + DEF↓(Lv1=10%, +5%/Lv, cap 50%)',
'좌클 스킬: 기본공격에 3단 콤보 초승달 검기 추가. ST 10+Lv당2. Lv당 뎀+10% 거리+15px':'LMB skill: adds 3-hit crescent ki blade combo to basic attack. ST 10+2/Lv. Per Lv DMG+10% range+15px',
'[기본: E] 어둠 마법 오브 발사. 범위폭발. 넉백 0.5%. Lv당 크기+50% (뎀은 _skMul 계수 적용)':'[Default: E] Dark magic orb fired. AoE explosion. Knockback 0.5%. Per Lv size+50% (DMG uses _skMul)',
'무기 홀드 → 전진 회전 공격. 360도 광역, ST 지속소모. Lv당 범위+5 뎀+5%':'Hold weapon → forward spin attack. 360° AoE, continuous ST drain. Per Lv range+5 DMG+5%',
'패링 3초 홀드 → 흡수 데미지 광역 폭발. Lv당 범위+15 (1렙150, 10렙285)':'Parry 3s hold → absorbed DMG AoE explosion. Per Lv range+15 (Lv1: 150, Lv10: 285)',
'우클 처내기 강화. Lv당 반사 데미지 +10%. 홀드 시 연사':'RMB swipe enhanced. Per Lv reflect DMG +10%. Hold for rapid fire',
'[고정: T 자동] 물리 바늘 3방향 3발 발사. 관통 없음':'[Fixed: T auto] 3 physical needles 3-way spread. No pierce',
'[고정: E] 1발 직선 레이저. +만화방창 → 만화광선(3발 꽈배기). +원소추적탄 → 추적암전(6발 유도)':'[Fixed: E] 1 straight laser. +Barrage → Omni Beam (3 spiral). +Elem Seeker → Homing Dark (6 homing)',
'E탭 마법을 6원소 유도 미사일로 변경. 곡선 궤적으로 적을 추적. 레벨당 사거리+20 (뎀은 _skMul 계수 적용)':'Changes E-tap magic to 6-element homing missiles. Curved trajectory tracking enemies. Per Lv range+20 (DMG uses _skMul)',
'3초마다 악의 구체 생성(1렙 2개). 몸에 밀착하여 적 투사체를 자동 방어(파괴). 레벨당 구체+1':'Spawns malice orbs every 3s (Lv1: 2 orbs). Orbits body, auto-blocks (destroys) enemy projectiles. Per Lv orb+1',
'유도 물리 칼날 1발 (악의30+ST50). 관통률 800+Lv×20+장비. 지속뎀 5초. 쿨 15초':'1 homing physical blade (malice 30 + ST 50). Pierce 800+Lv×20+gear. DOT 5s. CD 15s',
'어둠 소용돌이 소환 (마우스 조준 설치, MP 소모, 쿨 11초, INT 스케일링, 1렙 200범위 +30/렙, 5초 지속, 적 흡인)':'Summon dark vortex (mouse-aim placement, MP cost, CD 11s, INT scale, Lv1 range 200 +30/Lv, 5s duration, pulls enemies)',
'포격식 조준 → 원형 해골무덤 소환. 2스택 (15초/1충전, Lv10→3스택). 둘레에서 뼈가 솟아 공간을 감쌈. 솟을 때 데미지. 적/투사체 차단. 악의 12. Lv당 범위+5% 지속+0.3초':'Artillery-aim → circular bone tomb. 2 stocks (15s/charge, Lv10→3 stocks). Bones rise around perimeter. DMG on rise. Blocks enemies/projectiles. Malice 12. Per Lv range+5% duration+0.3s',
'오망성 시전 → 신성 빛기둥 대폭발. 범위 1500+Lv×100px. 범위 끝까지 넉백(주 성능). 거리감쇠 50%. 스턴 2초. Lv당 뎀+10%. (MP 30%, 쿨 120초)':'Pentagram cast → holy light pillar mega-explosion. Range 1500+Lv×100px. Full-range knockback (main feature). 50% distance falloff. Stun 2s. Per Lv DMG+10%. (MP 30%, CD 120s)',
'검은 오망성 소환. 7초(+Lv당0.5초) 강력 흡인 (데미지 없음, 순수 유틸). 범위 1500+Lv×100px. 흡인력 기본5+Lv당0.5. (MP 30%, 쿨 120초)':'Summon black pentagram. 7s (+0.5s/Lv) strong pull (no DMG, pure utility). Range 1500+Lv×100px. Pull force base 5+0.5/Lv. (MP 30%, CD 120s)',
'빨간 오망성 시전 → 범위 1500+Lv×100px 화염폭발+10초간 화상. 틱당 적 최대HP 1.75%(+Lv당+1.5%). 10초 20틱. 거리감쇠 30%. Lv당 초기뎀+10%. (MP 30%, 쿨 120초)':'Red pentagram cast → range 1500+Lv×100px fire explosion+10s burn. Per tick enemy maxHP 1.75%(+1.5%/Lv). 10s 20 ticks. 30% distance falloff. Per Lv initial DMG+10%. (MP 30%, CD 120s)',
'X키: 그로기 보스 전용. 보스 현재HP 20%(+2%/Lv) + 무기뎀×30(+21%/Lv, 20Lv=150배) + 보스HP 30% 순수뎀. 섬광 돌진 연출. HP/MP/ST 10% 소모. 쿨 5초':'X key: Groggy boss only. Boss current HP 20%(+2%/Lv) + weapon DMG×30(+21%/Lv, Lv20=150×) + boss HP 30% pure DMG. Flash dash. HP/MP/ST 10% cost. CD 5s',
'얼음 속에 들어가 무적 상태. 다시 누르면 파쇄 → 얼음칼날 48발 부채꼴 방사 (MP 40, 쿨 20초). Lv당 칼날+2 뎀+15%':'Enter ice — invincible. Re-press to shatter → 48 ice blades fan spread (MP 40, CD 20s). Per Lv blades+2 DMG+15%',
'[고정: T 자동] 초고속 바늘 연발. 1렙 2발, 5렙마다 +1발. 관통 없음. ST 8. 쿨 1.5초. Lv당 뎀+100%':'[Fixed: T auto] Ultra-fast needles burst. Lv1 2 shots, +1 per 5 levels. No pierce. ST 8. CD 1.5s',
'E홀드: 직선 관통 레이저 채널링. MP 8+Lv/초 지속소모. 폭160+(Lv×10)px, 사거리1200+Lv×80. 관통+감전. Lv당 뎀+21%':'E hold: Straight piercing laser channeling. MP 8+Lv/s drain. Width 160+(Lv×10)px, range 1200+Lv×80. Pierce+shock. Per Lv DMG+21%',
'E탭: 화염 유도빔 발사. MP10. 쿨1초(DEX 스케일). 100% 관통+유도+화상. Lv당 사거리+50 뎀+12%':'E tap: fire homing beam. MP 10. CD 1s (DEX scale). 100% pierce+homing+burn. Per Lv range+50 DMG+12%',
'E: 10초간 대지 진동. 범위 내 용암 기둥이 순차적으로 솟아올라 화상+틱 데미지. MP 100. 쿨 12초. Lv당 범위+10% 뎀+12%':'E: 10s ground tremor. Lava pillars rise sequentially in range — burn+tick DMG. MP 100. CD 12s. Per Lv range+10% DMG+12%',
'독혈 칼날 1발 발사: 관통률 기본 800+Lv×20 + 장비 bowPierce×300/패시브 pPierce×30 반영, +100 보정. 전염+마지막 적 처형. 감염 사망 시 폭발+연쇄 전염. 악의 15. 사거리 4000. 쿨 15초(Lv당-0.5초)':'Fire 1 poison-blood blade: base pierce rate 800+Lv×20 with bowPierce×300 and pPierce×30 scaling, plus +100 bonus. Plague+execute last enemy. Infected death → explosion+chain plague. Malice 15. Range 4000. CD 15s (-0.5s/Lv)',
'마우스 조준 설치. 쿨 20초. 화면 내 클릭 위치에 암전나선 (3초, 10틱, 틱당 100+Lv*20). Lv당 범위+22. 같은 지역 중복 불가':'Mouse-aim placement. CD 20s. Dark spiral at click pos (3s, 10 ticks, 100+Lv*20/tick). Per Lv range+22. No stacking same area',
'현재 위치에 9개 기둥 순차 발동. 5초간 악의 기둥을 소환하여 반경 내 적에게 지속 암전 데미지+감속. 범위 250+(Lv-1)×22. 대왕치기와 합체→기둥강타. 쿨 15초':'9 pillars activate sequentially at current pos. 5s dark pillars deal sustained dark DMG+slow to enemies in radius. Range 250+(Lv-1)×22. Fuses with Giant Slam → Pillar Strike. CD 15s',
'현재 위치에 회복의 영역 설치 (12초 지속). 땅 위: HP/MP/ST 초당+10 리젠 + 회복력 2배 + 쿨다운 속도 2배. 쿨 30초. Lv당 범위+20 지속+0.5초':'Place holy domain at current pos (12s duration). On ground: HP/MP/ST +10/s regen + 2x recovery + 2x CD speed. CD 30s. Per Lv range+20 duration+0.5s',
'범위 내 몬스터 부활력 -15%~30%(Lv1=15%, Lv10=30%). Lv1 범위400, Lv10 범위697. Lv당 범위+33. 쿨 30초. 지속 10초':'Monsters in range: revive power -15%~30%(Lv1=15%, Lv10=30%). Lv1 range 400, Lv10 range 697. Per Lv range+33. CD 30s. Duration 10s',
'마우스 조준 설치. 2스택 (15초/1충전, Lv10→3스택). 범위 내 빙결 저항 -50%, 빙결 게이지 급속 축적. 3초 지속. MP 40. Lv당 범위+22 축적+10%':'Mouse-aim placement. 2 stocks (15s/charge, Lv10→3 stocks). Freeze resist -50% in range, rapid freeze gauge buildup. 3s duration. MP 40. Per Lv range+22 buildup+10%',
'땅을 내리쳐 원형 진동파 발생(범위400). 일반몹에게 큰 포이즈 피해, 보스 체간 파괴에 강함. 회전기폭과 합체→지진폭풍!':'Slam ground → circular shockwave (range 400). High poise DMG to mobs, strong posture break vs bosses. Fuses with Whirlwind Detonate → Earthquake Storm!',
'땅을 내리쳐 원형 진동파 발생(범위400). 일반몹에게 큰 포이즈 피해, 보스 체간 파괴에 강함. 악의기둥과 합체→기둥강타!':'Slam ground → circular shockwave (range 400). High poise DMG to mobs, strong posture break vs bosses. Fuses with Dark Pillar → Pillar Slam!',
'사슬기동 중 E → 즉시 착지하며 화염폭발. 범위200~350 INT 스케일 화염 마법데미지+넉백. 이동거리에 비례해 데미지↑(최대 x4.0). MP 소모. Lv당 범위+16 뎀+12%':'During chain dash E → instant land with fire explosion. Range 200~350 INT scale fire magic DMG+knockback. DMG scales with travel distance (max x4.0). MP cost. Per Lv range+16 DMG+12%',
'사슬기동 중 우클릭 → 땅 내려찍기. 범위200~350 데미지x8 그로기x6. 이동거리 비례 최대x6. 일반몹 즉시 기절(5초), 보스 체간 대량 삭감. Lv당 범위+16 데미지+15% 그로기+15%':'During chain dash RMB → ground slam. Range 200~350 DMG x8 groggy x6. Distance scale max x6. Instant stun mobs (5s), massive boss posture break. Per Lv range+16 DMG+15% groggy+15%',
'[히든: 5성 dimRush 합체] 사슬기동 중 좌클릭 → 이동 중 전방 광역 베기+출혈. STR 스케일 물리데미지. 다단히트. Lv당 뎀+12% 범위+15':'[Hidden: 5-star dimRush fuse] During chain dash LMB → forward AoE slash+bleed while moving. STR scale physical DMG. Multi-hit. Per Lv DMG+12% range+15',
'[히든: 암전나선 합체] Q 홀드 시 보호막이 점점 커지며 HP 초당 10% 회복. 보호막 크기에 비례해 데미지 감소. MP 소모':'[Hidden: Dark Spiral fuse] Q hold: shield grows over time + HP 10%/s regen. DMG reduction scales with shield size. MP cost',
'[히든: 암전나선 합체] E로 조준, 클릭 설치. 에너지 쐐기를 지상에 꽂아 회전+데미지. MP100. 1차지 쿨10초. 5초+Lv당0.5초 지속. Lv당 거리+50':'[Hidden: Dark Spiral fuse] E to aim, click to place. Energy wedge planted on ground — rotates+DMG. MP 100. 1 charge CD 10s. 5s+0.5s/Lv duration. Per Lv range+50',
'[고정: 칼등치기 합체] 보유 시 칼등치기에 전방 충격파 자동 발동. 제자리 처내기. 쿨 5초. Lv당 뎀+12% 범위+20':'[Fixed: Blade Parry fuse] When owned, swipe auto-triggers forward shockwave. Stationary swipe. CD 5s. Per Lv DMG+12% range+20',
'현재 위치에 파쇄 영역 설치 (10초). 범위 내 적 물리방어력 -10%. 쿨 25초. Lv당 범위+22 효과+1% 지속+0.3초':'Place shatter domain at current pos (10s). Enemy phys DEF -10% in range. CD 25s. Per Lv range+22 effect+1% duration+0.3s',
'현재 위치에 침식 영역 설치 (10초). 범위 내 적 마법저항력 -10%. 쿨 25초. Lv당 범위+22 효과+1% 지속+0.3초':'Place corrosion domain at current pos (10s). Enemy magic resist -10% in range. CD 25s. Per Lv range+22 effect+1% duration+0.3s',
'현재 위치에 관통 영역 설치 (10초). 범위 내 적 투사체저항력 -10%. 쿨 25초. Lv당 범위+22 효과+1% 지속+0.3초':'Place pierce domain at current pos (10s). Enemy projectile resist -10% in range. CD 25s. Per Lv range+22 effect+1% duration+0.3s',
'현재 위치에 부활 영역 설치 (10초). 영역 안에서 부활력 +10%. 쿨 25초. Lv당 범위+22 효과+1% 지속+0.3초':'Place revival domain at current pos (10s). Revive power +10% inside zone. CD 25s. Per Lv range+22 effect+1% duration+0.3s',
'[고정: Space] 현재 위치에 가시덫 설치 (1렙 반경200, 10렙398). 슬로우 70%(+2%/Lv, 최대90%)+출혈. INT×magicRef×3(+10%/Lv). 악의 10, 쿨 10초. Lv당 범위+22':'[Fixed: Space] Place spike trap at current pos (Lv1 radius 200, Lv10 398). Slow 70%(+2%/Lv, max 90%)+bleed. INT×magicRef×3(+10%/Lv). Malice 10, CD 10s. Per Lv range+22',
'[고정: E, Lv300 해금] 유도 파란콩 50발 순차 발사 (5초간). MP 100(+1.5/Lv) 소모. 적 추적. 쿨 5초. Lv당 사거리+30 (뎀은 _skMul 계수 적용)':'[Fixed: E, unlock Lv300] 50 homing blue shots fired sequentially (over 5s). MP 100(+1.5/Lv) cost. Tracks enemies. CD 5s. Per Lv range+30 (DMG uses _skMul)',
'[히든: E, Lv700 해금] 홀드 시 3단계 차지 범위폭발 (0.5/1.0/1.5초). 범위 600/1000/1400px. 3단 만충 자동폭발. INT 스케일, 무속성':'[Hidden: E, unlock Lv700] Hold for 3-stage charge AoE explosion (0.5/1.0/1.5s). Range 600/1000/1400px. Stage 3 full charge auto-detonates. INT scale, no element',
'유령 허수아비를 소환하여 유도탄막 어그로를 끈다. 탄막을 흡수해 자원 축적 (기본 20개, Lv당+3). 1개당 HP/MP/ST 각 100. R키로 회수. 쿨 10초':'Summon phantom scarecrow to draw homing projectile aggro. Absorbs projectiles for resource buildup (base 20, +3/Lv). Per absorbed: HP/MP/ST +100 each. R key to retrieve. CD 10s',
'폭발 허수아비 설치. 탄막을 흡수하고 재입력 시 폭발! 1스택당 (INT마법뎀+탄막뎀)×10 마법데미지. 범위 250+흡수×25 (최대1000). 최대흡수 1렙20~20렙60. 쿨 10초':'Place explosive scarecrow. Absorbs projectiles, re-press to detonate! Per stack: (INT magic DMG + proj DMG)×10. Range 250+absorbed×25 (max 1000). Max absorb Lv1=20~Lv20=60. CD 10s',
'[선택: 1~4번, Lv500 해금] 현재 위치에 공성쇠뇌 터렛 설치. 재입력 시 철거. 설치 중 플레이어 석궁 사용 불가 (터렛만 발사). 데미지+50%, 공속+50%, 사거리+50%. ST 100. 쿨 10초. Lv당 뎀+5% 공속+5% 사거리+5%':'[Select: 1~4, unlock Lv500] Deploy siege crossbow turret at current pos. Re-press to dismantle. While deployed: player crossbow disabled (turret fires only). DMG+50%, ATK SPD+50%, range+50%. ST 100. CD 10s. Per Lv DMG+5% ATK SPD+5% range+5%',
'[Ctrl, Lv500 해금] 발동 시 3초 전 상태로 되돌린다. 위치/HP/MP/ST 완전 복원. Lv당 되감기+0.105초 (1렙 3초, 20렙 5초). MP 50(+5/Lv, 20렙150). 쿨 45초':'[Ctrl, unlock Lv500] Rewind to state from 3s ago. Restores position/HP/MP/ST. Per Lv rewind+0.105s (Lv1=3s, Lv20=5s). MP 50(+5/Lv, Lv20=150). CD 45s',
'[선택: 1~4번] 마우스 조준 → 전기창을 땅에 꽂는다. 5스택(12초/1충전, Lv10→6스택). 창끼리 600px 이내면 전류 아크 발생, 경로 위 적에게 감전 틱 데미지. MP 50. 지속 10초(+0.5초/Lv). Lv당 아크뎀+10%':'[Select: 1~4] Mouse aim → plant electric spear on ground. 5 stocks (12s/charge, Lv10→6). Spears within 600px create lightning arcs dealing shock tick DMG to enemies on path. MP 50. Duration 10s (+0.5s/Lv). Per Lv arc DMG+10%',
'성능 등급:':'Perf Grade:',
'벤치 FPS:':'Bench FPS:',
// --- CAT-82: skill panel labels ---
'스킬 정보':'Skill Info',
'타입':'Type',
'미습득':'Not Learned',
'SP 비용':'SP Cost',
'악의 비용':'Malice Cost',
'쿨다운':'Cooldown',
'요구 레벨':'Req. Lv',
'기본 참조뎀':'Base Reference',
'스탯 배율':'Stat Mult',
'패시브 배율':'Passive Mult',
'레벨 배율':'Skill Lv Mult',
'예상 평균 뎀':'Estimated Avg DMG',
'치명타':'Critical',
'치명타 확률':'Crit Rate',
'치명타 배율':'Crit Dmg',
'유효 배율':'Effective Mult',
'스킬 고유':'Skill Specific',
'1타 배율':'1-Hit Mult',
'2타 배율':'2-Hit Mult',
'3타 배율':'3-Hit Mult',
'레벨당 뎀':'Per Lv DMG',
'검기 거리':'Crescent Range',
'레벨당 거리':'Lv Range Bonus',
'ST/틱':'ST/Tick',
'레벨당 크기':'Per Lv Size',
'넉백':'Knockback',
'충전 시간':'Charge Time',
'레벨당 범위':'Per Lv Range',
'관통률':'Pierce Rate',
'지속뎀':'DOT Duration',
'무한':'Infinite',
'타격 형식':'AoE Type',
'진동파':'Shockwave',
'스태거':'Stagger',
'높음':'High',
'스톡':'Stocks',
'기둥 수':'Pillars',
'지속':'Duration',
'반경':'Radius',
'슬로우':'Slow',
'활':'Bow',
// --- CAT-83: affix desc labels ---
'독 DoT':'Poison DoT',
'화상 DoT':'Fire DoT',
'빙결 DoT+감속':'Ice DoT+Slow',
'연쇄전격':'Chain Lightning',
'저주(힐차단)':'Curse(Heal Block)',
'방어무시':'Armor Ignore',
'치명타율':'Crit Rate',
'스태거+':'Stagger+',
'체인타겟+':'Chain Target+',
'처치 후 뎀+':'Kill DMG+',
'크리폭발(ATK×)':'Crit Explode(ATK×)',
'원소뎀+':'Elem DMG+',
'공격속도+':'Atk Spd+',
'패리보너스+':'Parry Bonus+',
'추적콤보+10':'Track Combo+10',
'작살뎀+':'Harpoon DMG+',
'스킬뎀+':'Skill DMG+',
'쿨다운-':'CD-',
'방어력+':'DEF+',
'쉴드+':'Shield+',
'이동속도+':'Move Spd+',
'크리확률+':'Crit Rate+',
'크리배율+':'Crit Dmg+',
'화염저항':'Fire Res',
'빙결저항':'Ice Res',
'암전저항':'Lightning Res',
'암흑저항':'Dark Res',
'독저항':'Poison Res',
'전원소저항':'All Elem Res',
'물리DR':'Phys DR',
'반사%':'Reflect%',
'가시뎀':'Thorns DMG',
'배리어':'Barrier',
'CC저항':'CC Resist',
'위기뎀+':'Crisis DMG+',
'피격반격':'Hit Counter',
'패링폭발(ATK×)':'Parry Burst(ATK×)',
'체간파괴뎀+':'Poise Break DMG+',
'원소전환':'Elem Convert',
'상태이상해제':'Status Clear',
'불굴(1회생존)':'Tenacity(Survive×1)',
'부활(HP회복)':'Revive(HP Restore)',
'드롭률+':'Drop Rate+',
'경험치+':'EXP+',
'골드+':'Gold+',
'포션회복+':'Potion Heal+',
'사슬게이지+':'Chain Gauge+',
'부활억제':'Anti-Revive',
'부활력+':'Revival Pow+',
'부활쿨-':'Revival CD-',
'최대HP%+':'Max HP%+',
'HP리젠+':'HP Regen+',
'회복력+':'Heal Pow+',
'마법뎀+':'Magic DMG+',
'MP소비-':'MP Cost-',
'화염뎀%+':'Fire DMG%+',
'화염관통%':'Fire Pen%',
'적중화상':'On-Hit Burn',
'크리화폭':'Crit Fire Burst',
'화상지속+':'Burn Duration+',
'화염뎀보너스':'Fire DMG Bonus',
'빙결뎀%+':'Ice DMG%+',
'빙결관통%':'Ice Pen%',
'적중빙결':'On-Hit Freeze',
'크리빙폭':'Crit Ice Burst',
'빙결지속+':'Freeze Duration+',
'빙결뎀보너스':'Ice DMG Bonus',
'뇌전뎀%+':'Lightning DMG%+',
'뇌전관통%':'Lightning Pen%',
'적중감전':'On-Hit Shock',
'크리뇌폭':'Crit Lightning Burst',
'감전지속+':'Shock Duration+',
'뇌전뎀보너스':'Lightning DMG Bonus',
'암흑뎀%+':'Dark DMG%+',
'암흑관통%':'Dark Pen%',
'적중저주':'On-Hit Curse',
'크리암폭':'Crit Dark Burst',
'저주지속+':'Curse Duration+',
'암흑뎀보너스':'Dark DMG Bonus',
'독뎀%+':'Poison DMG%+',
'독관통%':'Poison Pen%',
'적중중독':'On-Hit Poison',
'크리독폭':'Crit Poison Burst',
'독지속+':'Poison Duration+',
'독뎀보너스':'Poison DMG Bonus',
'근접뎀%+':'Melee DMG%+',
'원거리뎀%+':'Ranged DMG%+',
'마법뎀%+':'Magic DMG%+',
'빔뎀%+':'Beam DMG%+',
'DoT뎀%+':'DoT DMG%+',
'투사체뎀%+':'Proj DMG%+',
'범위반경+':'AoE Radius+',
'근접크리+':'Melee Crit+',
'마법크리+':'Magic Crit+',
'석궁크리+':'Xbow Crit+',
'근접공속+':'Melee Spd+',
'석궁공속+':'Xbow Spd+',
'시전속도+':'Cast Spd+',
'전속성관통':'All Elem Pen',
'쉴드관통':'Shield Pen',
'방어력깎기':'Armor Shred',
'투사체속도+':'Proj Speed+',
'적중시화구':'On-Hit Fireball',
'적중시연쇄뇌격':'On-Hit Chain Lightning',
'적중빙결%':'On-Hit Freeze%',
'적중스턴%':'On-Hit Stun%',
'적중중독%':'On-Hit Poison%',
'적중출혈%':'On-Hit Bleed%',
'적중약화%':'On-Hit Weaken%',
'적중감속%':'On-Hit Slow%',
'적중표적%':'On-Hit Mark%',
'크리폭발(HP%)':'Crit Explode(HP%)',
'크리연쇄(HP%)':'Crit Chain(HP%)',
'크리빙결%':'Crit Freeze%',
'크리HP+':'Crit HP+',
'크리MP+':'Crit MP+',
'크리쉴드+':'Crit Shield+',
'피격방어+':'Hit DEF+',
'반격가시':'Counter Thorns',
'빙결파동%':'Ice Nova%',
'자동암흑막':'Auto Dark Shield',
'주기치유':'Periodic Heal',
'시체폭발%':'Corpse Explode%',
'회피뎀+':'Dodge DMG+',
'패링폭발%':'Parry Burst%',
'블록HP+':'Block HP+',
'블록MP+':'Block MP+',
'회전참뎀+':'Whirlwind DMG+',
'옴니빔뎀+':'Omni Beam DMG+',
'화구뎀+':'Fireball DMG+',
'미사일뎀+':'Missile DMG+',
'청탄뎀+':'Blue Shot DMG+',
'폭렬탄뎀+':'Blast Shot DMG+',
'지옥광선뎀+':'Hell Ray DMG+',
'악의폭풍뎀+':'Malice Storm DMG+',
'연쇄참뎀+':'Chain Slash DMG+',
'거인강타뎀+':'Giant Slam DMG+',
'유령보행뎀+':'Ghost Walk DMG+',
'악의박격뎀+':'Malice Mortar DMG+',
'화염오라뎀+':'Fire Aura DMG+',
'빙구뎀+':'Ice Orb DMG+',
'화염빔뎀+':'Fire Beam DMG+',
'악의사냥뎀+':'Malice Hunt DMG+',
'암흑기둥뎀+':'Dark Pillar DMG+',
'역병뎀+':'Plague DMG+',
'가시오라뎀+':'Spike Aura DMG+',
'연쇄돌격뎀+':'Chain Assault DMG+',
'회피확률+':'Dodge Rate+',
'회피쿨-':'Dodge CD-',
'쉴드%+':'Shield%+',
'쉴드리젠%+':'Shield Regen%+',
'쉴드쿨-':'Shield CD-',
'HP리젠%+':'HP Regen%+',
'ST리젠+':'ST Regen+',
'ST리젠%+':'ST Regen%+',
'MP리젠+':'MP Regen+',
'MP리젠%+':'MP Regen%+',
'화염DR':'Fire DR',
'빙결DR':'Ice DR',
'뇌전DR':'Lightning DR',
'암흑DR':'Dark DR',
'독DR':'Poison DR',
'전체DR':'All DR',
'엘리트DR':'Elite DR',
'스턴저항':'Stun Res',
'감속저항':'Slow Res',
'넉백저항':'KB Res',
'돌진거리+':'Dash Range+',
'돌진쿨-':'Dash CD-',
'전투이속+':'Combat MSpd+',
'비전투이속+':'Out-Combat MSpd+',
'습득범위+':'Pickup Range+',
'전스탯+':'All Stats+',
'적중자원+':'On-Hit Resource+',
'화염최대저항+':'Fire Max Res+',
'빙결최대저항+':'Ice Max Res+',
'뇌전최대저항+':'Lightning Max Res+',
'암흑최대저항+':'Dark Max Res+',
'독최대저항+':'Poison Max Res+',
'스킬쿨-':'Skill CD-',
'물약쿨-':'Potion CD-',
'강화성공+':'Craft Rate+',
'악의획득+':'Malice Gain+',
'악마화뎀+':'Demon DMG+',
'악마화DR':'Demon DR',
'영혼수확+':'Soul Harvest+',
'생명흡혈%':'Life Leech%',
'과치유→쉴드':'Overheal→Shield',
'만마나뎀+':'Full MP DMG+',
'이동DR':'Move DR',
'정지뎀+':'Stationary DMG+',
'회피후뎀+':'After Dodge DMG+',
'패링쉴드+':'Parry Shield+',
'콤보보너스+':'Combo Bonus+',
'HP≥70%뎀+':'HP≥70% DMG+',
'적HP≤30%뎀+':'Foe HP≤30% DMG+',
'HP100%뎀+':'HP100% DMG+',
'HP≤35%뎀+':'HP≤35% DMG+',
'적HP≤20%뎀+':'Foe HP≤20% DMG+',
'근접뎀+':'Melee DMG+',
'원거리뎀+':'Ranged DMG+',
'스턴적뎀+':'vs Stunned DMG+',
'빙결적뎀+':'vs Frozen DMG+',
'화상적뎀+':'vs Burning DMG+',
'중독적뎀+':'vs Poisoned DMG+',
'저주적뎀+':'vs Cursed DMG+',
'감속적뎀+':'vs Slowed DMG+',
'보스뎀+':'Boss DMG+',
'엘리트뎀+':'Elite DMG+',
'일반몹뎀+':'Mob DMG+',
'선제뎀+':'First Strike DMG+',
'물리흡혈%':'Phys Leech%',
'마나흡수%':'Mana Leech%',
'ST흡수%':'ST Leech%',
'적중HP+':'On-Hit HP+',
'처치HP+':'On-Kill HP+',
'처치MP+':'On-Kill MP+',
'처치ST+':'On-Kill ST+',
'처치시폭발':'On-Kill Explode',
'처치이속+':'On-Kill MSpd+',
'HP≥70%방어+':'HP≥70% DEF+',
'HP≤50%이속+':'HP≤50% MSpd+',
'DoT피해감소':'DoT DMG Reduce',
'보스피해감소':'Boss DMG Reduce',
'근접피해감소':'Melee DMG Reduce',
'원거리피해감소':'Ranged DMG Reduce',
'처치HP회복':'On-Kill HP Restore',
'처치쉴드회복':'On-Kill Shield Restore',
'ST소비-':'ST Cost-',
'HP≥70%공격+':'HP≥70% ATK+',
'HP≤35%흡혈':'HP≤35% Leech',
'보스추가뎀':'vs Boss DMG+',
'엘리트추가뎀':'vs Elite DMG+',
'공격력+':'ATK+',
'크리뎀+':'Crit DMG+',
// --- CAT-84/85/86: affix names + implicit + legendary ---
'물리방패의':'Physical Shield',
'지속의':'Stamina',
'마나의':'Mana',
'원소수호의':'Elem Guard',
'행운의':'Fortune',
'근성의':'Grit',
'풍요의':'Abundance',
'약자포식의':'Predator',
'만혈의':'Full Life',
'사선의':'Low Life',
'처형의':'Execute',
'근접살의':'Melee DMG',
'원거리의':'Ranged',
'경직파의':'Stagger Break',
'동파의':'Freeze Strike',
'연소의':'Burning',
'맹독살의':'Venom Slayer',
'저주살의':'Curse Slayer',
'구속의':'Binding',
'왕살의':'Boss Slayer',
'정예살의':'Elite Slayer',
'군살의':'Mob Slayer',
'선제의':'First Strike',
'흡혈의':'Vampirism',
'흡마의':'Mana Leech',
'흡정의':'Stamina Leech',
'타격재생의':'Hit Regen',
'처치회복의':'Kill Recovery',
'처치흡마의':'Kill Mana Leech',
'처치활력의':'Kill Stamina',
'처치폭발의':'Kill Explosion',
'처치질주의':'Kill Sprint',
'건강방어의':'Healthy Defense',
'중상보호의':'Wounded Shield',
'위기질주의':'Crisis Sprint',
'지속피해방어의':'DoT DR',
'왕피해방어의':'Boss DMG DR',
'근접방어의':'Close DR',
'원거리방어의':'Ranged DR',
'처치생명의':'Kill HP',
'처치수호의':'Kill Shield',
'화염강화의':'Fire Amp',
'화염관통의':'Fire Pierce',
'발화의':'Ignition',
'화염폭발의':'Fire Burst',
'맹화의':'Blaze',
'화염의힘':'Fire Power',
'빙결강화의':'Ice Amp',
'빙결관통의':'Ice Pierce',
'동결의':'Freeze',
'빙결폭발의':'Ice Burst',
'영빙의':'Permafrost',
'빙결의힘':'Ice Power',
'뇌전강화의':'Thunder Amp',
'뇌전관통의':'Thunder Pierce',
'감전의':'Shock',
'뇌전폭발의':'Thunder Burst',
'낙뢰의':'Thunderbolt',
'뇌전의힘':'Thunder Power',
'암흑강화의':'Dark Amp',
'암흑관통의':'Dark Pierce',
'침식의':'Erosion',
'암흑폭발의':'Dark Burst',
'심연의':'Abyss',
'암흑의힘':'Dark Power',
'맹독강화의':'Venom Amp',
'독관통의':'Poison Pierce',
'중독의':'Poisoning',
'독폭발의':'Poison Burst',
'맹독지속의':'Venom Duration',
'독의힘':'Poison Power',
'격투의':'Melee',
'원사의':'Ranged Shot',
'주술의':'Spell',
'광선의':'Beam',
'탄도의':'Ballistic',
'확산의':'AoE Radius',
'근접회심의':'Melee Crit',
'마법회심의':'Spell Crit',
'사격회심의':'Ranged Crit',
'근접쾌속의':'Melee Speed',
'사격쾌속의':'Ranged Speed',
'영창의':'Chanting',
'전속성관통의':'All-Elem Pierce',
'쉴드파괴의':'Shield Bypass',
'갑옷분쇄의':'Armor Shred',
'탄속의':'Proj Speed',
'화구발사의':'Fireball Launch',
'연쇄뇌격의':'Chain Lightning',
'동결타의':'Freeze Strike',
'경직타의':'Stagger Strike',
'독침의':'Poison Sting',
'출혈의':'Bleed',
'약화의':'Weakness',
'둔화의':'Slow',
'표적의':'Marking',
'회심폭발의':'Crit Explosion',
'회심연쇄의':'Crit Chain',
'회심빙결의':'Crit Freeze',
'회심치유의':'Crit Heal',
'회심영력의':'Crit Mana',
'회심수호의':'Crit Shield',
'피격강화의':'Hit Boost',
'반격가시의':'Counter Thorns',
'빙결파동의':'Ice Nova',
'암흑보호의':'Dark Shield',
'치유파동의':'Heal Pulse',
'시체폭발의':'Corpse Explosion',
'회피반격의':'Dodge Counter',
'패링폭파의':'Parry Shatter',
'블록치유의':'Block Heal',
'블록영력의':'Block Mana',
'회전참강화':'Spin Slash Boost',
'옴니빔강화':'Omni Beam Boost',
'화구강화':'Fireball Boost',
'미사일강화':'Missile Boost',
'청탄강화':'Blue Shot Boost',
'폭렬탄강화':'Burst Shot Boost',
'지옥광선강화':'Hellray Boost',
'악의폭풍강화':'Malice Storm Boost',
'연쇄참강화':'Chain Slash Boost',
'거인강타강화':'Giant Slam Boost',
'유령보행강화':'Ghost Walk Boost',
'악의박격강화':'Malice Mortar Boost',
'화염오라강화':'Fire Aura Boost',
'빙구강화':'Ice Orb Boost',
'화염빔강화':'Fire Beam Boost',
'악의사냥강화':'Malice Hunt Boost',
'암흑기둥강화':'Dark Pillar Boost',
'역병강화':'Plague Boost',
'가시오라강화':'Thorn Aura Boost',
'연쇄돌격강화':'Chain Assault Boost',
'회피의':'Evasion',
'회피쿨감의':'Dodge CD Red',
'수호력의':'Shield Power',
'수호재생의':'Shield Regen',
'수호쿨감의':'Shield CD Red',
'재생력의':'Regen Power',
'활력재생의':'Stamina Regen',
'마력재생의':'Mana Regen',
'화염보호의':'Fire Shield',
'빙결보호의':'Ice Shield',
'뇌전보호의':'Thunder Shield',
'해독의':'Antidote',
'만물보호의':'All Protection',
'정예보호의':'Elite Shield',
'경직저항의':'Stagger Resist',
'빙결저항의':'Freeze Resist',
'감속저항의':'Slow Resist',
'넉백저항의':'Knockback Resist',
'돌진거리의':'Dash Range',
'돌진쿨감의':'Dash CD Red',
'전투질주의':'Combat Sprint',
'평화질주의':'Peace Sprint',
'습득범위의':'Pickup Radius',
'힘의':'Strength',
'민첩의':'Dexterity',
'지능의':'Intelligence',
'만능의':'Versatile',
'지구력의':'Max Stamina',
'마나력의':'Mana Power',
'타격자원의':'Hit Resource',
'화염한계의':'Fire Cap',
'빙결한계의':'Ice Cap',
'뇌전한계의':'Thunder Cap',
'암흑한계의':'Dark Cap',
'독한계의':'Poison Cap',
'스킬쿨감의':'Skill CD Red',
'물약쿨감의':'Potion CD Red',
'장인의':'Craftsmanship',
'탐욕의':'Greed',
'수련의':'Training',
'수집의':'Gathering',
'악마의힘':'Demon Power',
'악마보호의':'Demon Shield',
'영혼수확의':'Soul Harvest',
'생명흡수의':'Life Absorption',
'과치유수호의':'Overheal Shield',
'만마력의':'Full Mana DMG',
'이동방어의':'Moving DR',
'정지공세의':'Stationary Boost',
'회피공세의':'Post-Dodge Boost',
'패링보호의':'Parry Shield',
'콤보폭발의':'Combo Burst',
'물리타격의':'Phys Strike',
'화염타격의':'Fire Strike',
'빙결타격의':'Ice Strike',
'뇌전타격의':'Thunder Strike',
'암흑타격의':'Dark Strike',
'독타격의':'Poison Strike',
'최소공격의':'Min ATK',
'최대공격의':'Max ATK',
'전투력의':'Combat Power',
'무기사거리의':'Weapon Range',
'활사거리의':'Bow Range',
'이중타의':'Double Strike',
'다중발사의':'Multi Shot',
'관통횟수의':'Pierce Count',
'관통유지의':'Pierce Keep',
'연쇄유지의':'Chain Keep',
'범위확장의':'Splash Range',
'범위피해의':'Splash DMG',
'돌진공격의':'Dash ATK',
'반격공격의':'Counter ATK',
'후방타의':'Backstab',
'침식가속의':'Erosion Speed',
'출혈지속의':'Bleed Duration',
'마법타격의':'Magic Strike',
'주문증폭의':'Spell Amp',
'연살뎀의':'Kill Streak DMG',
'연살속의':'Kill Streak Speed',
'기세의':'Momentum',
'정지공격의':'Static Strike',
'이동공격의':'Mobile Strike',
'패링공세의':'Post-Parry Boost',
'임사폭발의':'Near-Death Burst',
'만기력공의':'Full Stamina ATK',
'만마력공의':'Full Mana ATK',
'신선처치의':'Fresh Kill',
'경직연장의':'Stagger Extension',
'빙결연장의':'Freeze Extension',
'둔화강화의':'Slow Amp',
'독중첩의':'Poison Stack',
'출혈중첩의':'Bleed Stack',
'발화강화의':'Ignite Amp',
'동상강화의':'Frostbite Amp',
'감전강화의':'Shock Amp',
'사선회심의':'Low HP Crit',
'갑옷강화의':'Armor Boost',
'블록흡수의':'Block Absorb',
'방패타격의':'Shield Bash',
'방패경직의':'Shield Stagger',
'격투속의':'Brawl Speed',
'격투회심의':'Brawl Crit',
'격투경직의':'Brawl Stagger',
'하반재생의':'Leg Regen',
'CC단축의':'CC Duration Red',
'돌진타의':'Dash Strike',
'돌진범위의':'Dash AoE',
'은신질주의':'Stealth Sprint',
'회피감쇠의':'Dodge DR',
'속성감쇠의':'Elem DR',
'마나왕관의':'Mana Helm',
'시전왕관의':'Cast Helm',
'쿨감왕관의':'CD Helm',
'경험왕관의':'EXP Helm',
'공생의':'Symbiosis',
'수질의':'Body-Soul',
'회심흡의':'Crit Leech',
'체마의':'HP-Mana',
'체기의':'HP-Stamina',
'마기의':'Mana-Stamina',
'전재생의':'All Regen',
'힘민의':'STR-DEX',
'힘지의':'STR-INT',
'민지의':'DEX-INT',
'운근의':'Fortune-Grit',
'수확의':'Harvest',
'빙화의':'Ice-Fire',
'뇌암의':'Thunder-Dark',
'근마의':'Blade-Magic',
'속성침식의':'Elem Erosion',
'화염반지의':'Fire Ring',
'빙결반지의':'Ice Ring',
'뇌전반지의':'Thunder Ring',
'암흑반지의':'Dark Ring',
'독반지의':'Poison Ring',
'콤보반지의':'Combo Ring',
'처치마나의':'Kill Mana',
'관통반지의':'Pierce Ring',
'만능목걸이의':'Allround Necklace',
'회심목걸이의':'Crit Necklace',
'관통목걸이의':'Pierce Necklace',
'스킬목걸이의':'Skill Necklace',
'콤보한계의':'Combo Max',
'처치치유의':'Kill Heal',
'지구벨트의':'Stamina Belt',
'포션벨트의':'Potion Belt',
'활력벨트의':'Vitality Belt',
'탐욕벨트의':'Greed Belt',
'마나띠의':'Mana Band',
'시전띠의':'Cast Band',
'마력띠의':'Magic Band',
'주술띠의':'Spell Band',
'속성띠의':'Elem Band',
'전사의힘':'Warrior Power',
'전사생명의':'Warrior Life',
'전사흡혈의':'Warrior Leech',
'전사인내의':'Warrior Poise',
'마법사의힘':'Mage Power',
'마법사마나의':'Mage Mana',
'마법사수호의':'Mage Shield',
'마법사속성의':'Mage Elem',
'궁수의힘':'Archer Power',
'궁수사거리의':'Archer Range',
'궁수관통의':'Archer Pierce',
'궁수질주의':'Archer Sprint',
'탱크생명의':'Tank Life',
'탱크방어의':'Tank Defense',
'탱크블록의':'Tank Block',
'탱크가시의':'Tank Thorns',
'암살회심의':'Assassin Crit',
'암살후방의':'Assassin Backstab',
'암살독의':'Assassin Poison',
'암살회피의':'Assassin Dodge',
'종결자의':'The Ender',
'생존자의':'Survivor',
'종결수호의':'End Shield',
'종결회심의':'End Crit',
'종결공격의':'End ATK',
'종결저항의':'End Resistance',
'종결파괴의':'End Destruction',
'종결보호의':'End Protection',
'종결흡혈의':'End Leech',
'종결인내의':'End Poise',
'종결쿨감의':'End CD Red',
'종결경험의':'End EXP',
'종결약탈의':'End Loot',
'종결악의의':'End Malice',
'종결힘의':'End STR',
'종결민첩의':'End DEX',
'종결지능의':'End INT',
'종결행운의':'End LCK',
'종결근성의':'End Grit',
'종결연살의':'End Kill Chain',
'건강공세의':'Healthy Offense',
'중상폭발의':'Wounded Burst',
'중상흡혈의':'Wounded Leech',
'토벌의':'Vanguard',
'정예토벌의':'Elite Vanguard',
'극대화의':'Maximize',
'공격력 +X%':'ATK +X%',
'관통 확률 +X%':'Pierce Chance +X%',
'방어율 +X%':'Block Rate +X%',
'물리 피해감소 +X%':'Phys DR +X%',
'최대 HP +X':'Max HP +X',
'공격속도 +X%':'ATK Speed +X%',
'상태이상 저항 +X%':'Status Resist +X%',
'이동속도 +X%':'Move Speed +X%',
'원소 저항 +X%':'Elem Resist +X%',
'최대 HP +X%':'Max HP +X%',
'회피 쿨다운 -X%':'Dodge CD -X%',
'물약 쿨다운 -X%':'Potion CD -X%',
'부활력 +X%':'Revive Power +X%',
'마법 데미지 +X%':'Magic DMG +X%',
'전설 특수':'Legendary Special',
'5타 콤보 완성 시 데빌포스 20% 즉시 충전':'5-hit combo: instantly charge DevilForce 20%',
'처치 시 이속 +40%(3초) + 다음 공격 크리 보장':'Kill: MoveSpd +40%(3s) + next attack guaranteed Crit',
'스태거 발동 시 범위 충격파 (ATK×120%)':'Stagger: AoE shockwave (ATK×120%)',
'스태거 발동 시 범위 충격파 (ATK×100%)':'Stagger: AoE shockwave (ATK×100%)',
'강타 시 적 넉백 거리 2배 + 벽충돌 추가뎀':'Heavy hit: Knockback ×2 + wall collision bonus DMG',
'출혈 대상 크리 시 잔여 DoT×300% 즉시 폭발':'Crit vs Bleeding: remaining DoT×300% instant explosion',
'작살 착지 타격 수만큼 데미지 +20% 중첩(최대5)':'Javelin landing hits: stack +20% DMG (max 5)',
'치명타 시 추가 투사체 1발 발사':'Crit: fire 1 additional projectile',
'패리 성공 시 반격 데미지 ×2':'Parry: counter DMG ×2',
'피격 시 3초 쿨로 HP 5% 즉시 회복':'On Hit (3s CD): restore 5% HP instantly',
'스킬 사용 시 20% 확률로 쿨다운 미소모':'Using skills: 20% chance no cooldown consumed',
'공격속도 +20% + 기본공격에 랜덤 원소 추가':'ATK Speed +20% + basic attacks add random element',
'이동 중 지속 HP 재생 (초당 HP의 1%)':'While moving: HP regen (1% HP/sec)',
'회피 직후 첫 공격 데미지 +80%':'First attack after Dodge: DMG +80%',
'패리 타이밍 판정 +50% 확대':'Parry timing window +50% expanded',
'원소 반응 발동 시 추가 폭발 (ATK×80%)':'Elemental reaction: bonus explosion (ATK×80%)',
'처치 시 데빌포스 5% 회복':'Kill: restore 5% DevilForce',
'HP 50% 이하 시 전 스킬 쿨다운 -30%':'Below 50% HP: all skill CD -30%',
'물약 사용 시 5초간 피해 +15%':'Using Potion: DMG +15% for 5s',
'암묵':'Implicit',
'낡은 악마의 팔찌':'Worn Demon Bracelet',
'흑요석 악마의 팔찌':'Obsidian Demon Bracelet',
'미스릴 악마의 팔찌':'Mithril Demon Bracelet',
'낡은 생명의 팔찌':'Worn Life Bracelet',
'확인':'Confirm',
'조작법':'Controls',
'살아남으려면 익혀라':'Master this to survive',
'전투':'Combat',
'이동 / 상호작용':'Move / Interact',
'메뉴':'Menu',
'시스템':'System',
'아무 키를 눌러 시작':'Press any key to start',
'스테이지':'Fase',
'💪 힘 (STR)':'💪 STR',
'🏹 민첩 (DEX)':'🏹 DEX',
'🔮 지능 (INT)':'🔮 INT',
'🍀 행운 (LCK)':'🍀 LCK',
'⚔️ 맹공':'⚔️ Onslaught',
'🔱 돌파':'🔱 Breakthrough',
'⚡ 반격':'⚡ Retaliation',
'🔮 마력폭주':'🔮 Mana Surge',
'🎯 정밀사격':'🎯 Precision',
'🛡 수호신':'🛡 Aegis',
'💚 회복력':'💚 Recovery',
'💥 급소':'💥 Vital Strike',
'🎁 약탈':'🎁 Plunder',
'🔱 관통':'🔱 Pierce',
'💠 마력회복':'💠 Mana Recovery',
'🏹 쇠뇌력':'🏹 Crossbow Mastery',
'⚔ 광전사':'⚔ Berserker',
'🎯 추적자':'🎯 Tracker',
'🗡 물리관통':'🗡 Phys Penetration',
'🔮 마법관통':'🔮 Magic Penetration',
'🌿 풍요':'🌿 Abundance',
'🐺 약자포식':'🐺 Predator',
'☠ 침식':'☠ Corrosion',
'💎 마력그릇':'💎 Mana Vessel',
'💪 힘의그릇':'💪 Stamina Vessel',
'👿 악의중독':'👿 Malice Addict',
'❤️ 강인':'❤️ Fortify',
'🛡 철벽':'🛡 Iron Wall',
'🎯 사냥꾼':'🎯 Hunter',
'✦ 인간성':'✦ Humanity',
'☠ 악마성':'☠ Demon',
'1. 악의폭풍':'1. Malice Storm',
'2. 칼날 계열':'2. Blade Skills',
'3. 역병 확장':'3. Plague Expand',
'4. 이동스킬 마스터':'4. Movement Master',
'5. 사슬 확장':'5. Chain Expand',
'6. 💀 필살기 선택':'6. 💀 Ultimate Pick',
'7. 멸살+만화+원소+전격이동':'7. Beam+Barrage+Elem+Blink',
'8. 회전참+기폭+대왕':'8. Whirl+Det+Giant',
'9. 방패 합체':'9. Shield Fuse',
'10. 해골무덤+악의폭풍':'10. Bone Wall+Malice Storm',
'11. 폭풍소환+얼음보주':'11. Storm+Ice Orb',
'12. 뇌전걸음':'12. Ghost Walk',
'13. 신성 영역':'13. Holy Domain',
'14. 6단합체: 폭풍빔':'14. 6-Fuse: Storm Beam',
'15. 신성+빙결':'15. Holy+Ice',
'16. 암흑+가시+대왕2':'16. Dark+Spike+Slam2',
'17. 사슬 최종':'17. Chain Final',
'⚡ 이동스킬':'⚡ Movement',
'⚔️ 물리':'⚔️ Physical',
'🛡️ 방어':'🛡️ Defense',
'🔮 마법':'🔮 Magic',
'🏹 석궁/투사체':'🏹 Crossbow/Projectile',
'⚙️ 영역':'⚙️ Domain',
'💀 필살기':'💀 Ultimate',
'⭐ 추천':'⭐ Recommend',
'⚔ 공격':'⚔ Attack',
'🛡 방어':'🛡 Defense',
'⚙ 특수':'⚙ Special',
  '👻 공성허수아비!':'👻 Siege Scarecrow!',
  '💥 공성허수아비 폭발!':'💥 Siege Scarecrow Blast!',
  '\u{1F47B} 유령총!':'\u{1F47B} Pistola Fantasma!',
  '👻 공성유령!':'👻 Fantasma d\'Assedio!',
  '기절!  ':'Stordito!  ',
  '✟ 신성한 결계!':'✟ Barriera Sacra!',
};

const _IT_PFX={
'녹슨':'Arrugginito','강철':'Acciaio','흑요석':'Ossidiana','미스릴':'Mithril','심판의':'Giudizio','천벌의':'Ira Divina','파멸의':'Distruzione','불꽃':'Fiamma','화염':'Inferno','염화':'Fuoco Infernale','지옥불':'Fiamma Infernale','지옥화':'Fiamma Infernale','지옥':'Fiamma Infernale','멸화의':'Annientante','냉기':'Gelo','빙결':'Congelato','빙하':'Glaciale','서리의':'Brina','서리':'Brina','영겁빙':'Ghiaccio Eterno','그림자':'Ombra','암흑':'Oscuro','심연':'Abissale','나락의':'Infero','나락':'Infero','무간의':'Vuoto','전기':'Scintilla','낙뢰':'Tuono','암전':'Fulmine','뇌신의':'Dio Tuono','뇌신':'Dio Tuono','만뢰의':'Mille Tuoni','축복':'Benedetto','성광':'Luce Sacra','신성':'Sacro','천사의':'Angelico','신벌의':'Giudizio Divino','낡은':'Logoro','천':'Tela','가죽':'Pelle','강철사':'Trama Acciaio','은':'Argento','은사':'Filo d\'Argento','화염의':'Inferno','빙결의':'Congelato','암흑의':'Oscuro','암전의':'Fulmine'
};
const _IT_BASE={
'대검':'Spadone','석궁':'Balestra','연사석궁':'Balestra Ripetizione','마력석궁':'Balestra Arcana','견갑':'Scudo','대견갑':'Grande Scudo','전투화':'Stivali Combattimento','갑옷':'Armatura','갑주':'Armatura','왕관':'Corona','장갑':'Guanti','건틀릿':'Guanti Corazzati','바지':'Pantaloni','각반':'Schinieri','허리띠':'Cintura','벨트':'Cintura','부적':'Talismano','목걸이':'Collana','반지':'Anello','망토':'Mantello','팔찌':'Bracciale','귀걸이':'Orecchino',
  '⚡ 연격!':'⚡ Rapid Strike!',
  '⚔ 난타!':'⚔ Barrage!',
  '💥 강타!':'💥 Slam!',
  '🌀 휘두르기!':'🌀 Sweep!',
  '방어↓':'DEF↓',
// --- Demo End Screen ---
'데모 종료':'Fine della Demo',
'여기까지 데모입니다. 정식 출시를 기대해주세요!':'Questa è la fine della demo. Non vediamo l\'ora del lancio completo!',
'STEAM 위시리스트로 응원해 주세요!':'Supportaci aggiungendolo alla lista dei desideri di Steam!',
'STEAM 위시리스트':'Lista dei desideri Steam',

// --- CAT-92 sync ---
'흑요염 파괴자':'Distruttore della Fiamma d\'Ossidiana',
'독사':'Serpente velenoso',
'🐍 독사!':'🐍 Serpente velenoso!',
'더블탭 or Shift+방향키! 전격이동으로 탈출해!':'Doppio tocco o Shift+Direzione! Scatta per scappare!',
'💥 공성유령 폭발!':'💥 Esplosione del fantasma assediante!',
'프레임 표시 (FPS)':'Mostra FPS',
'여기까지 데모입니다...':'Questa è la fine della demo...',
'투구 착용':'Elmo indossato',
'투구 해제':'Elmo rimosso',
'혼돈의 투구':'Elmo del Caos',
'전지전능의 투구':'Elmo dell\'Onnipotenza',
'방향키 연타':'Premi frecce rapidamente',
'까마귀와 고양이가 아이템을 주워준다. 수거 범위 안이면.':'Il corvo e il gatto raccolgono oggetti. Se nel raggio.',
'Ctrl 얼음보주로 탈출! 없으면 방향키 연타!':'Ctrl — Orbe Ghiaccio per fuggire! Niente? Premi frecce!',
'💥 폭발 허수아비!':'💥 Spaventapasseri Esplosivo!',
' 뎀 ':' DAN ',
'투구':'Elmo',
'악마팔찌':'Bracciale Demoniaco',
'생명팔찌':'Bracciale della Vita',
};