// 지옥의 길 — Română (ro)
const _RO={
// --- v7 신규 펫/UI 8종 (2026-07-05) ---
'다섯 번째군. 이번엔 바뀐 게 있어야지.':"A cincea oară. De data asta ceva trebuie să se schimbe.",
'또 와?! 이번엔 진짜 패턴 외웠어!':"Iar?! De data asta chiar am învățat tiparul!",
'…전설을 잡았다. 보상도 전설이겠지.':"…Ai doborât o legendă. Și răsplata va fi legendară.",
'전설급 잡았어!! 드롭 확인해!':"Ai doborât un legendar!! Verifică drop-ul!",
'무릎 꿇었다. 지금 처형해. X.':"A îngenuncheat. Execută-l acum. X.",
'처형각이야!! X 눌러!!':"E momentul execuției!! Apasă X!!",
'⌨ 키보드·마우스':"⌨ Tastatură și mouse",
'🎮 게임패드':"🎮 Controler",
'💫 암전폭류':'💫 Val de Fulgere','⚡ 암전나선':'⚡ Spirală Fulger','🌋 지진폭풍':'🌋 Furtună Seismică','🔥 회전기폭':'🔥 Vârtej detonare','⚔ 기동:섬멸':'⚔ Drive:Nimicire','⚔ 기동:칼날개':'⚔ Drive:Lamă','⚡ 기동:전폭':'⚡ Drive:Lovitură','🌀 기동:파쇄':'🌀 Drive:Zdrobire','🌀 기동:기습':'🌀 Drive:Ambuscadă','💫 →좌클 통합':'💫 →Unificat cu LMB','⚡ →좌클 통합':'⚡ →Unificat cu LMB','🎯 추적암전':'🎯 Fulger Urmăritor','☆ 만화광선':'☆ Rază Luminescentă','⏳⚡ 시간걸음':'⏳⚡ Pas în Timp','SSAA 슈퍼샘플':'SSAA Supraesantionare','끄기 (1x)':'Oprit (1x)','커서 크기':'Dimensiune cursor','다크 판타지 전사':'Războinic dark fantasy','거대검+검은 갑옷':'Spadă mare + Armură neagră',
'…지옥문이 열렸다. 안에서 그것이 기다리고 있어.':"...Poarta Iadului este deschisă. Te așteaptă înăuntru.",
'문 열렸어! 이제 보스 잡으러 가자!':"Poarta e deschisă! Hai să ucidem bossul!",
'\u26e7 시전...':'⛧ Incantare...',
'…죽기 직전이다. 패링해. 피를 채워.':'...Aproape mort. Parează. Recuperează HP.',
'⚔🐍 독사해방!':'⚔🐍 Eliberarea Viperei!',
'⚠패링 실패!':'⚠Parare eșuată!',
'⚡ 뇌전추격자!':'⚡ Vânător de Fulgere!',
'⚡회피 반격!':'⚡Contraatac eschivă!',
'✦ 유니크 공유!':'✦ Partajare unică!',
'✦ 유니크 부활!':'✦ Înviere unică!',
'❄유니크 빙결!':'❄Înghețare unică!',
'닫기 [C]':'Închide [C]',
'닫기 [V]':'Închide [V]',
'대왕치기 (분노폭발, 광역 기절)':'Lovitură Uriașă (explozie de furie, amețire de zonă)',
'물리방패의':'Scut Fizic',
'사슬 착지 타격 수만큼 데미지 +20% 중첩(최대읐5)':'Lovituri de aterizare în lanț: +20% daune (max 5)',
'성능 등급:':'Grad de performanță:',
'쉴드 있으면 HP 안 닳아! 쉴드 먼저 깨야 해!':'Cât timp e scut, HP e în siguranță! Sparge mai întâi scutul!',
'쉴드가 있는 적은 쉴드부터 깨야 HP가 깎여!':'Inamici cu scut — sparge mai întâi scutul ca să ajungi la HP!',
'쉴드는 추가 HP다. 쉴드부터 깎인다.':'Scutul e HP în plus. Scutul scade primul.',
'쉴드는 추가 HP야. 모든 공격이 쉴드를 먼저 깎아!':'Scutul e HP în plus. Toate atacurile lovesc mai întâi scutul!',
'얼음송곳':'Țeapă de Gheață',
'한 방이면 죽어! 패링으로 HP 채워!!':'O lovitură te ucide! Parează ca să recuperezi HP!!',
'👻 투명화!':'👻 Invizibilitate!',
'👿악의+':'👿malicie+',
'💡 Q로 보호막 발동 — 기본 흡수율 30%, 패링 성공 시 HP/ST/MP/기동게이지 회복':'💡 Q pentru scut — 30% absorbție, parare reușită reface HP/ST/MP/Încărcare',
'💥유니크 폭발!':'💥Explozie unică!',
'🔥피격→분노!':'🔥Lovit→Furie!',
'🔨방어무시!':'🔨Ignoră apărare!',
'🛡️쉴드+15%':'🛡️Scut+15%',
'썩은 숲':'Pădurea Putredă',
'숲의 감시자':'Gardianul Pădurii',
'독버섯 거인':'Gigantul Ciupercă Toxică',
'숲의 사냥꾼':'Vânătorul Pădurii',
'숲의 기생수':'Bestia Parazită',
'1장 — 썩은 숲':'CAP1 — Pădurea Putredă',
'2장 — 벌레굴':'CAP2 — Cuibul Viermilor',
'3장 — 얼음굴':'CAP3 — Caverna de Gheață',
'4장 — 고통의 화염지대':'CAP4 — Ținutul Infernal',
'5장 — 지옥의 군단':'CAP5 — Legiunea Infernului',
'6장 — 사도의 마굴':'CAP6 — Vizuina Apostolului',
'7장 — 지옥성':'CAP7 — Citadela Infernului',
'탈출!':'Scăpat!',
'처치':'Eliminări',
'경험치':'EXP',
'최대콤보':'Combo Max',
'일어나. 여신이 널 여기 보낸 건 죽으라고가 아니야.':'Trezește-te. Zeița nu te-a trimis aici să mori.',
'좋아, 감각이 있군. 계속 쳐!':'Bine, ai instinct. Continuă să lovești!',
'Shift를 눌러. 사슬이다. 땅에 꽂아서 끌려가!':'Apasă Shift. E Lanțul. Înfige-l și lasă-te tras!',
'사슬로 끌려가는 중엔 무적이다. 위험할 때 쓰면 좋아.':'Ești invincibil cât te trage Lanțul. Folosește-l când e periculos.',
'...아파? 당연하지. 여긴 지옥이야.':'...Doare? Evident. Aici e iadul.',
'Q를 눌러! 악의로 보호막을 만들 수 있다.':'Apasă Q! Creează un scut cu malicie.',
'보호막 없이 버틸 생각은 버려.':'Uită de supraviețuire fără scut.',
'E가 패링이다. 적 공격이 닿기 직전에 눌러!':'E pentru parare. Chiar înainte ca inamicul să lovească!',
'못 하겠으면 때려. 안 죽으면 그만이야.':'Nu poți para? Lovește. E suficient să nu mori.',
'됐어! 감 잡았구나.':'Gata! Înveți repede.',
'하나 죽었군.':'Unul a căzut.',
'유령쇠뇌야. 인사해.':'E arbaleta fantomă. Salut-o.',
'보물상자를 열었군. 보스급 장비가 쏟아진다.': 'Ai deschis un cufăr. Curge echipament de nivel boss.',
'상자 대박! 좋은 거 잔뜩 나와! 보이면 꼭 열어!': 'Cufăr jackpot! O grămadă de lucruri bune! Deschide-le mereu!',
'잔해도 부숴서 열어. 악의와 장비가 숨어있다.': 'Sparge și dărâmăturile. Răutate și echipament se ascund înăuntru.',
'잔해에서 악의가 나온다! 보이면 다 주워!': 'Dărâmăturile lasă Răutate! Adună fiecare pe care o vezi!',
'빨간 탄을 무서워하지 마. 악의가 강하다.':'Nu te teme de gloanțele roșii. Malicia e puternică.',
'패링으로 돌려주고, Q 보호막도 써! 악의를 잘 굴려!':'Respinge-le cu pararea și folosește scutul Q! Stăpânește malicia!',
'무지개빛은 패링 불가! 피해!':'Curcubeul nu poate fi parat! Ferește-te!',
'피가 새고 있다. Shift. 빠져.':'Sângerezi. Shift. Fugi.',
'물약 있잖아! 숫자키!':'Ai poțiuni! Tastele numerice!',
'E. 적 손목이 꺾일 때 쳐.':'E. Lovește când încheietura se îndoaie.',
'빨간 탄은 악의 덩어리다. 쳐내서 이용해.':'Gloanțele roșii sunt bucăți de malicie. Deviază-le și folosește-le.',
'무지개빛만 피하면 돼! 나머지는 다 패링!':'Ferește-te doar de curcubeu! Restul se parează!',
'Q 보호막도 패링이 가능해!':'Scutul Q poate și el para!',
'위험해! 쉬프트 사슬기동으로 피해!!':'Pericol! Shift lanț pentru a scăpa!!',
'쉬프트! 사슬기동은 이동기야! 끌려가면서 무적이라고!':'Shift! Lanțul e mișcare! Invincibil cât ești tras!',
'스킬포인트가 쌓였어! K 눌러서 스킬 배우자!':'Puncte de abilitate! Apasă K!',
'속성을 읽어. 약점을 찌르면 두 배로 썩는다.':'Citește elementele. Lovește slăbiciunile pentru daune duble.',
'K를 눌러봐! 스킬을 배울 수 있어!':'Apasă K! Poți învăța abilități!',
'J 눌러서 능력치 찍어! 패시브도 있어~':'Apasă J pentru stats! Și pasive~',
'G를 눌러. 대장간에서 장비를 강화할 수 있다.':'Apasă G. Îmbunătățește echipamentul la forjă.',
'F키도 스킬 슬롯이야! 스킬 많으면 L로 배정해봐~':'F e și el slot! Folosește L să atribui~',
'Z. 필살기다. 아껴 써라.':'Z. E ultimul tău. Folosește-l cu grijă.',
'L-CTRL로 유령걸음이나 얼음보주 쓸 수 있어!':'L-CTRL pentru Pas Fantomă sau Sferă de Gheață!',
'L을 눌러. 스킬 슬롯을 정리해야 한다.':'Apasă L. Organizează sloturile.',
'가방 터지겠다! N 눌러서 창고에 넣어둬!':'Sacul explodează! Apasă N!',
'ESC로 설정 열 수 있어! 난이도 바꾸기, 자동물약 조절~':'ESC pentru setări! Dificultate, poțiuni auto~',
'...아직 살아있네. 좌클릭으로 저것들 쳐봐.':'...Încă viu. Lovește-i cu clic stânga.',
'...치는 건 할 줄 아네. 피하는 건?':'...Știi să lovești. Dar să eviți?',
'흥, 사슬 못 맞추면 헛수고야.':'Hmph, ratezi Lanțul și e degeaba.',
'...운이 좋았을 뿐이야. 아마.':'...Doar noroc. Probabil.',
'...고기 냄새. 싫진 않네.':'...Miros de carne. Nu e rău.',
'...말은 못해.':'...Nu poate vorbi.',
'예쁘다고 만지면 죽어.':'Atingi că e frumos? Vei muri.',
'사슬 던져! 끌려가면 무적이야!':'Aruncă Lanțul! Invincibil cât ești tras!',
'...마시든 말든. 네 목숨이니까.':'...Bei sau nu. E viața ta.',
'그게 패링이야! 타이밍이 전부야~':'Asta e o parare! Temporizarea e totul~',
'화염엔 빙결! 암전엔 암흑! 기억해!':'Foc vs Gheață! Fulger vs Întuneric! Ține minte!',
'...얼어붙은 놈은 오래 안 간다.':'...Cei înghețați nu durează.',
'얼었어! 빙결 중 1.5배야!':'Înghețat! 1.5x daune!',
'...힘을 골라라. 전부 가질 순 없다.':'...Alege-ți puterea. Nu poți avea totul.',
'스탯을 올려. 살고 싶으면.':'Crește-ți stats. Dacă vrei să trăiești.',
'좋은 장비는 강화해야 진짜 힘을 발휘해!':'Echipamentul bun trebuie îmbunătățit!',
'...슬롯을 채워. 빈 손은 죽음이다.':'...Umple sloturile. Mâinile goale = moarte.',
'Z 누르면 대박! 쿨타임 길어서 타이밍 봐야 해!':'Z pentru daune masive! Cooldown lung, calculează!',
'Ctrl. 위기에 쓸 카드가 하나 늘었군.':'Ctrl. Încă o carte pentru urgențe.',
'스킬이 많아졌네~ L로 어디에 뭘 넣을지 골라!':'Multe abilități~ Folosește L!',
'...버리기 아까운 건 창고에.':'...Depozitează ce e prea bun.',
'...살아남은 것만으로도 대단하군. 설정을 확인해.':'...Să supraviețuiești e impresionant. Verifică setările.',
'MP 부족!':'MP insuficient!',
'ST 부족!':'ST insuficient!',
'악의 부족!':'Malicie insuficientă!',
'충전 중...':'Se încarcă...',
'캔슬':'Anulare',
'아이템 선택 필요':'Selectează un obiect',
'악의 소진...':'Malicie epuizată...',
'비문 발견...':'Inscripție găsită...',
'HP물약!':'Poțiune HP!',
'HP물약 +1':'Poțiune HP +1',
'HP물약 +2':'Poțiune HP +2',
'HP/MP/ST 회복!':'HP/MP/ST restaurat!',
'보물상자 개봉!':'Cufăr deschis!',
'익사!':'Înec!',
'피웅덩이!':'Baltă de sânge!',
'독혈!':'Sânge toxic!',
'잡힘!':'Prins!',
'콤보 종료':'Sfârșit combo',
'빙결!':'Înghețat!',
'화상!':'Arsură!',
'독!':'Otravă!',
'감전!':'Electrocutat!',
'기절!':'Amețit!',
'봉인됨!':'Sigilat!',
'관통!':'Penetrare!',
'기검참':'Tăietură Ki',
'악의구':'Sferă Malicie',
'회전참':'Vârtej',
'기폭팔':'Detonare',
'칼등 처내기':'Parare de Lamă',
'만화방창':'Baraj de Ace',
'멸살광선':'Rază Anihilare',
'원소추적탄':'Căutător Elemental',
'악의 보호자':'Gardian al Maliciei',
'악의 사냥':'Vânătoare de Malicie',
'폭풍소환':'Invocare Vortex',
'해골무덤':'Mormânt de Oase',
'\u{1F47B} 유령!':'\u{1F47B} Fantomă!',
'\u{1F9B4} 해골무덤!':'\u{1F9B4} Mormânt de Oase!',
'신성폭발':'Explozie Sacră',
'블랙':'Stea Neagră',
'용암소환':'Invocare Lavă',
'처형':'Execuție',
'악마화 부활':'Înviere Demonică',
'붉은꽃':'Floare Stacojie',
'얼음보주':'Sferă de Gheață',
'뇌전걸음':'Pas Fantomă',
'만화방창 II':'Baraj de Ace II',
'마력연사':'Baraj Arcan',
'마력광선':'Laser Arcan',
'업화선':'Rază Infernală',
'지옥진':'Formație Infernală',
'폭독칼날':'Lamă Pestilentă',
'악의폭풍':'Furtună Malicie',
'악의기둥':'Pilon Întunecat',
'회복의 영역':'Domeniu Sacru',
'구속의 영역':'Domeniu de Legare',
'아이스스톰':'Furtună de Gheață',
'대왕치기':'Lovitură Gigantică',
'대왕치기 2':'Lovitură Gigantică II',
'기동불꽃':'Flacără în Lanț',
'기동파괴':'Distrugere în Lanț',
'기동칼날개':'Aripă de Lamă',
'평화의보호':'Egida Păcii',
'참회':'Pocăință',
'칼등날개':'Aripă Scut',
'폭산탄':'Împușcătură Explozivă',
'파쇄의 영역':'Domeniu Sfărâmare',
'침식의 영역':'Domeniu Coroziune',
'관통의 영역':'Domeniu Penetrare',
'부활의 영역':'Domeniu Înviere',
'가시덫':'Capcană de Țepi',
'푸른비':'Ploaie Azurie',
'버스트루프':'Buclă Explozie',
'유령 허수아비':'Momeală Fantomă',
'폭발 허수아비':'Momeală Explozivă',
'공성쇠뇌':'Arbaletă de Asediu',
'사슬기동:충돌':'Lanț: Impact',
'사슬기동:화염':'Lanț: Flacără',
'전격이동':'Pas Fulger',
'기동칼날개!':'Aripă Lamă!',
'기동불꽃!':'Flacără Lanț!',
'기동파괴!':'Distrugere în Lanț!',
'사슬이동:강화!':'Lanț Îmbunătățit!',
'사슬기동:화염!':'Lanț: Flacără!',
'사슬!':'Lanț!',
'진입!':'Intrare!',
'레인라이트닝!':'Ploaie Fulgere!',
'마력연사!':'Baraj Arcan!',
'🔷 마력광선!':'🔷 Laser Arcan!',
'광선 해제':'Laser dezactivat',
'MP 부족 — 광선 해제':'MP epuizat — Laser dezactivat',
'집중...':'Concentrare...',
'시전...':'Incantare...',
'만화방창!':'Baraj de Ace!',
'바늘출!':'Salvă de Ace!',
'칼날!':'Lamă!',
'착지!':'Aterizare!',
'체간삭감!':'Postură ruptă!',
'기동전폭 준비!':'Explozie Lanț gata!',
'기동불꽃 준비!':'Flacără Lanț gata!',
'기동파괴 준비!':'Distrugere Lanț gata!',
'유령불꽃 ON':'Flacără Fantomă ON',
'유령불꽃 OFF':'Flacără Fantomă OFF',
'기동칼날개 AUTO ON':'Aripă Lamă AUTO ON',
'기동칼날개 AUTO OFF':'Aripă Lamă AUTO OFF',
'자동 버스트!':'Explozie auto!',
'연사 해제':'Foc rapid dezactivat',
'당기기 모드':'Mod Tragere',
'밀어내기 모드':'Mod Împingere',
'날개치기':'Lovitură Aripă',
'처내기':'Parare',
'Shift: 사슬 발사 → 끌려감':'Shift: Lanț → tragere',
'Shift: 화염길+화상':'Shift: Urmă foc+arsură',
'CT: 전류변신+뇌전걸음 (쿨4초)':'CT: Formă fulger+Pas Fantomă (CD 4s)',
'CT: 방어구체+빙결 (재입력: 파쇄)':'CT: Sferă gheață+îngheț (re-apasă: sfărâmă)',
'근접':'Corp',
'견갑':'Gardă',
'사슬':'Lanț',
'마법':'Magie',
'보막':'Scut',
'유령':'Fantomă',
'스킬':'Abilități',
'대장':'Forjă',
'인벤':'Inv',
'인벤토리':'Inventar',
'복수의 대장간':'Forja Răzbunării',
'패시브 스킬':'Abilități Pasive',
'전투 스킬':'Abilități de Luptă',
'캐릭터 선택':'Selectare Personaj',
'물리':'Fizic',
'화염':'Foc',
'빙결':'Înghețat',
'암흑':'Întuneric',
'암전':'Fulger',
'신성':'Sacru',
'대지':'Pământ',
'힘':'Forță',
'민첩':'Dexteritate',
'지능':'Inteligență',
'행운':'Noroc',
'맹공':'Asalt',
'철벽':'Fortitudine',
'돌파':'Străpungere',
'반격':'Represalii',
'마력폭주':'Explozie Arcană',
'정밀사격':'Tir Precis',
'수호':'Gardian',
'수호신':'Spirit Gardian',
'회복력':'Recuperare',
'급소':'Lovitură Vitală',
'약탈':'Jaf',
'관통':'Penetrare',
'마력회복':'Recup. Mana',
'쇠뇌력':'Măiestrie Arbaletă',
'광전사':'Berserker',
'추적자':'Urmăritor',
'물리관통':'Pen. Fizică',
'마법관통':'Pen. Magică',
'녹슨 대검':'Spadă Ruginită',
'강철 대검':'Spadă de Oțel',
'흑요석 대검':'Spadă de Obsidian',
'낡은 석궁':'Arbaletă Uzată',
'강철 석궁':'Arbaletă de Oțel',
'흑요석 석궁':'Arbaletă de Obsidian',
'대검':'Spadă',
'석궁':'Arbaletă',
'연사석궁':'Arbaletă Repetitivă',
'마력석궁':'Arbaletă Arcană',
'악의 추출':'Extracție Malicie',
'악의':'Răutate',
'필살기':'Ultim',
'필살기 해제':'Ultim dezactivat',
'이전':'Transferă',
'강화':'Îmbunătăți',
'개봉!':'Deschis!',
'여신의 가호':'Binecuvântarea Zeiței',
'과부하!':'Supraîncărcare!',
'맹독의':'Veninos',
'불꽃의':'Înflăcărat',
'냉기의':'Glacial',
'번개의':'Voltaic',
'암흑의':'Blestemat',
'관통의':'Penetrant',
'광폭의':'Furios',
'파쇄의':'Sfărâmător',
'연쇄의':'Înlănțuit',
'학살의':'Ucigaș',
'폭발의':'Exploziv',
'집중의':'Concentrat',
'쾌속의':'Rapid',
'패리의':'Deviant',
'추적자의':'al Urmăritorului',
'사슬의':'Lanț',
'궁극의':'Suprem',
'집중력의':'Atent',
'강인의':'Tenace',
'수호의':'Protector',
'활력의':'Vital',
'신속의':'Accelerat',
'화염수호':'Gardă Foc',
'빙결수호':'Gardă Gheață',
'암전수호':'Gardă Fulger',
'암흑수호':'Gardă Întuneric',
'독수호':'Gardă Otravă',
'전원소수호':'Gardă Totală',
'강철의':'Blindat',
'반사의':'Reflectant',
'가시의':'Țepos',
'흡수의':'Absorbant',
'인내의':'Rezistent',
'위기의':'Disperat',
'피격반격의':'Contraatacant',
'패링폭발의':'Explozie Parare',
'스태거폭발의':'Explozie Clătinare',
'원소전환의':'Convertor',
'정화의':'Purificator',
'불굴의':'De neclintit',
'부활의':'Învietor',
'약탈의':'Jefuitor',
'경험의':'Experimentat',
'골드의':'Aurit',
'포션강화의':'Potent',
'사슬의':'Înlănțuit',
'진혼의':'Sfințitor',
'윤회의':'Ciclic',
'생명력의':'Viguros',
'재생의':'Regenerator',
'치유의':'Vindecător',
'마력의':'Arcan',
'절약의':'Eficient',
'영혼의':'al Sufletului',
'예리한':'Ascuțit',
'맹렬한':'Brutal',
'파멸의':'Ruinos',
'게임 설정':'Setări Joc',
'화면 흔들림':'Vibrație Ecran',
'파티클 양':'Cantitate Particule',
'효과음 볼륨':'Volum Efecte',
'음악 볼륨':'Volum Muzică',
'난이도':'Dificultate',
'자동 물약':'Poțiune Auto',
'최소 줍기 등급':'Grad Min. Colectare',
'최소 줍기 티어':'Tier Min. Colectare',
'FPS 제한':'Limită FPS',
'해상도 스케일':'Scară Rezoluție',
'펫 자동수거':'Colectare Auto Pet',
'화면 설정':'Setări Afișare',
'화면 모드':'Mod Afișare',
'보스 AI 디버그':'Depanare IA Boss',
'유령불꽃 크기':'Dimens. Flacără Fantomă',
'화면 명암':'Luminozitate',
'유령 글로우':'Strălucire Fantomă',
'기동:칼날개 AUTO':'Aripă Lamă AUTO',
'일반':'Normal',
'어려움':'Dificil',
'지옥':'Infern',
'이상':'sau mai sus',
'사용 안 함':'Dezactivat',
'창 모드':'Fereastră',
'보더리스':'Fără Margini',
'전체화면':'Ecran Complet',
'설정':'Setări',
'조작 키 설정 (클릭하여 변경)':'Taste (Click pt. Schimbare)',
'좌클릭 무기 공격':'Clic Stânga Atac Armă',
'E 탭 칼등 처내기':'E Parare Lamă',
'E 홀드 연속 처내기':'Ține E Parare Continuă',
'SHIFT 사슬 발사':'SHIFT Lansare Lanț',
'이동':'Mișcare',
'아이템 줍기':'Colectare Obiect',
'능력치 (스탯/패시브)':'Atribute (Stats/Pasive)',
'분해':'Dezasambla',
'제작':'Fabricare',
'사망':'Moarte',
'부활':'Înviere',
'로비로':'La Lobby',
'가방에 공간이 없습니다!':'Nu e loc!',
'가방이 가득 찼습니다!':'Sacul e plin!',
'창고가 가득 찼습니다!':'Depozit plin!',
'퀵슬롯이 가득 찼습니다!':'Slot rapid plin!',
'결정 주머니가 가득 찼습니다!':'Pungă cristale plină!',
'결정 주머니 가득!':'Pungă cristale plină!',
'악의가 부족합니다!':'Malicie insuficientă!',
'가방이 비어있습니다':'Sac gol',
'창고가 비어있습니다':'Depozit gol',
'비어있음':'Gol',
'어픽스 없음':'Fără afix',
'장착!':'Echipat!',
'해제':'Dezechipat',
'보관':'Depozitare',
'꺼내기':'Retrage',
'현재 장착':'Echipat actual',
'없음 — 제작하세요!':'Niciunul — Fabrică!',
'리셋할 포인트가 없습니다':'Nu sunt puncte de resetat',
'키 설정 초기화 완료':'Taste resetate',
'제작 확률':'Șansă fabricare',
'제작 비용':'Cost fabricare',
'보유 악의':'Malicie deținută',
'보스방':'Camera Boss',
'안식처':'Sanctuar',
'회복':'Recuperare',
'점화':'Aprindere',
'비석':'Stelă',
'읽기':'Citire',
'파괴':'Distruge',
'제단':'Altar',
'기원':'Ruga',
'잔해':'Rămășițe',
'열기':'Deschide',
'문지기':'Gardian',
'부활 판정 중...':'Se judecă învierea...',
'기폭 준비!':'Detonare gata!',
'탈출':'Evadare',
'연타':'Apăsare',
'추적암전':'Fulger Urmăritor',
'만화광선':'Rază Luminescentă',
'최종 마법':'Magie Finală',
'감시중':'Supraveghere',
'대기':'În așteptare',
'작동중':'Activ',
'설치 가능':'Instalabil',
'균열 임박!':'Breșă iminentă!',
'흡수 중...':'Absorbire...',
'흡수 완료 — 재입력으로 회수':'Gata — re-apasă pt. colectare',
'화상':'Arsură',
'당기기':'Tragere',
'밀어내기':'Împingere',
'단계':'nivel',
'단':'nivel',
'습득!':'Învățat!',
'리셋!':'Resetare!',
'세팅!':'Setat!',
'회수':'Recuperare',
'합체 해제':'Defuziona',
'리셋':'Resetare',
'환불':'Rambursare',
'파트너 클릭!':'Click partener!',
'SP부족!':'SP insuficient!',
'같은 보석 스킬 습득 시 합체 가능':'Fuzionare la aceeași gemă',
'펼쳐서 초기화':'Extinde pt. resetare',
'슬롯:':'Slot:',
'남은 SP':'SP Rămase',
'맞아서 사망':'Mort de lovitură',
'레벨':'Nivel',
'최대HP':'HP Maxim',
'방랑 기사':'Cavaler Rătăcitor',
'보물 악마':'Demonul Comorii',
'거울의 사도':'Apostolul Oglinzii',
'상인 악마':'Demonul Negustor',
'사슬의 죄수':'Prizonierul Înlănțuit',
'시간의 사도':'Apostolul Timpului',
'탐욕의 사도':'Apostolul Lăcomiei',
'저주받은 쌍둥이':'Gemenii Blestemați',
'차원 균열체':'Entitate Dimensională',
'죽음 그 자체':'Moartea Însăși',
'HP결정':'Cristal HP',
'ST결정':'Cristal ST',
'MP결정':'Cristal MP',
'ATK결정':'Cristal ATK',
'DEF결정':'Cristal DEF',
'속도결정':'Cristal Viteză',
'크리결정':'Cristal Critic',
'치명결정':'Cristal DaunăCrit',
'화염결정':'Cristal Foc',
'냉기결정':'Cristal Gheață',
'암흑결정':'Cristal Întuneric',
'번개결정':'Cristal Fulger',
'신성결정':'Cristal Sacru',
'생명결정':'Cristal Viață',
'기력결정':'Cristal Rezistență',
'마력결정':'Cristal Mana',
'행운결정':'Cristal Noroc',
'조각':'Fragment',
'파편':'Ciob',
'순수결정':'Cristal Pur',
'완전결정':'Cristal Perfect',
'결정 주머니':'Pungă Cristale',
'결정이 없습니다':'Fără cristale',
'가루':'Praf',
'전체':'Tot',
'스탯':'Statistică',
'원소':'Elem',
'유틸':'Util',
'현재':'Actual',
'최대 강화 달성 (+20)':'Îmbunătățire max (+20)',
'강화 시':'După îmbunătățire',
'합성':'Sintetiza',
'같은 종류·같은 성급 결정 3개 → 1성급 상승 (강화 리셋)':'3 cristale același tip și grad → urcă 1 grad (îmbunătățire resetată)',
'합성 가능한 결정이 없습니다 (같은 종류·성급 3개 필요)':'Nu sunt cristale sintetizabile (trebuie 3)',
'결정 분해 → 결정 가루':'Descompune Cristal → Praf',
'분해할 결정이 없습니다':'Fără cristale de descompus',
'결정 제작 (가루 → 결정)':'Fabricare Cristal (Praf → Cristal)',
'탈착':'Detașa',
'빈 슬롯':'Slot gol',
'결정 선택 후 클릭':'Selectează cristal apoi click',
'클릭하여 선택결정 장착':'Click pt. a echipa cristalul',
'획득!':'Obținut!',
'제작!':'Fabricat!',
'합성!':'Sintetizat!',
'최상위 일괄합성':'Sinteză în lot max',
'일괄합성 완료':'Sinteză în lot completă',
'벌레굴':'Cuibul Viermilor',
'얼음굴':'Caverna de Gheață',
'고통의 화염지대':'Ținutul Infernal',
'지옥의 군단':'Legiunea Infernului',
'사도의 마굴':'Vizuina Apostolului',
'지옥성':'Citadela Infernului',
'엑소듀서 전사':'Războinic Exoduser',
'포이즈':'Postură',
'지옥창고':'Depozit Infernal',
'선택분해':'Dezasamblare Selectivă',
'쓰레기':'Gunoi',
'복구 불가!':'Irecuperabil!',
'중요잠금':'Blocare importantă',
'자동 장착!':'Auto-echipat!',
'분해! 가루 +':'Dezasamblat! Praf +',
'평화보호':'Egidă',
'지진폭풍':'Furtună Seismică',
'회전기폭':'Vârtej-Det',
'공격':'Atac',
'보호막':'Barieră',
'합체 스킬로 통합됨':'Fuzionat în abilitate combinată',
'얼음보주 안에선 사용 불가!':'Nu se poate folosi în Sfera de Gheață!',
'Shift+키로 폭파':'Shift+tastă pt. detonare',
'취소':'Anulare',
'쿨다운 중...':'Reîncărcare...',
'시전 중...':'Incantare...',
'악의 부족! (12)':'Malicie insuf.! (12)',
'악의 부족! (15)':'Malicie insuf.! (15)',
'악의 부족! (20)':'Malicie insuf.! (20)',
'악의 부족! (10)':'Malicie insuf.! (10)',
'HP 부족!':'HP insuficient!',
'필살기 슬롯 클릭하여 배정!':'Click slot ultim!',
'필살기 스킬을 습득하세요':'Învață un ultim',
'E(칼등치기)에 합체됨':'Fuzionat E (parare)',
'T(석궁자동)에 세팅하세요':'Setează pe T (arbaletă auto)',
'공성쇠뇌 철거 → 이동식':'Arbaletă asediu demontată → portabilă',
'ST 부족! (100)':'ST insuf.! (100)',
'HP 99% 이상!':'HP 99%+!',
'그로기 보스 없음!':'Niciun boss amețit!',
'이미 폭풍 지역!':'Deja în zona furtunii!',
'이미 빙풍 지역!':'Deja în zona gheții!',
'💎 푸른비 해금!':'💎 Ploaie Azurie deblocată!',
'💫 버스트루프 해금!':'💫 Buclă Explozie deblocată!',
'👻 유령 허수아비 해금!':'👻 Momeală Fantomă deblocată!',
'쿨 ':'CD ',
'과부하 ':'Supraîncărcare ',
'🕊️💎 블루콩!':'🕊️💎 Fasole Albastră!',
'🛡️💎 빨콩→블루콩!':'🛡️💎 Roșu→Albastru!',
'🛡️💎 무지개→블루콩!':'🛡️💎 Curcubeu→Albastru!',
'레어':'Rar',
'슬롯':'Slot',
'성공률':'Rată Succes',
'AI 자동 강화':'Îmbunătățire Auto IA',
'최대 강화 달성!':'Îmbunătățire max atinsă!',
'최대 강화':'Îmbunătățire max',
'회복량':'Recuperare',
'분해할 아이템이 없습니다.':'Fără obiecte de dezasamblat.',
'🔨 제작':'🔨 Fabricare',
'체간':'Postură',
'아이템에 마우스를 올리거나 좌클릭으로 선택하세요':'Treci cu mouse-ul sau clic stânga pt. selectare',
'중독':'Otravă',
'지뢰':'Mină',
'덫':'Capcană',
'산호가시':'Țeapă Coral',
'투사체':'Proiectil',
'도트':'DoT',
'레어몹':'Mob Rar',
'구역':'Zonă',
'가시!':'Țeapă!',
'림보':'Limb',
'색욕':'Desfrâu',
'탐식':'Lăcomie',
'탐욕':'Lăcomie',
'분노':'Furie',
'이단':'Erezie',
'폭력':'Violență',
'분노!':'Furie!',
'탐욕!':'Lăcomie!',
'💀 분노 폭발!':'💀 Explozie Furie!',
'심연의 분노!':'Furie Abisală!',
'쌍둥이의 분노!':'Furia Gemenilor!',
'소환굴':'Gaură Invocare',
'처치!':'Eliminat!',
'왕관 착용':'Coroană Pusă',
'왕관 해제':'Coroană Scoasă',
'맨손':'Mâini Goale',
'없음':'Niciunul',
'갑옷':'Armură',
'부츠':'Cizme',
'매직':'Magie',
'챔피언':'Campion',
'초속':'Grăbire',
'강타':'Izbitură',
'재생':'Regenerare',
'맹독':'Venin',
'소환':'Invocare',
'기생':'Parazit',
'분열':'Sciziune',
'용암자취':'Urmă Lavă',
'사망폭발':'Explozie Mortală',
'화염사슬':'Lanț Foc',
'광전':'Frenezie',
'텔레포트':'Teleportare',
'소용돌이':'Vârtej',
'환영':'Fantomă',
'전격반사':'Reflecție Șoc',
'감전':'Electrocutare',
'낙뢰':'Tunet',
'연쇄전격':'Fulger Lanț',
'동료불사':'Aliat Nemuritor',
'영혼포식':'Devorator Suflete',
'시간왜곡':'Distorsiune Temporală',
'혼돈변이':'Mutație Caotică',
'복수자':'Răzbunător',
'마법보초':'Santinelă Magică',
'환영술사':'Iluzionist',
'함성':'Strigăt Război',
'치유':'Vindecare',
'신속':'Iuțeală',
'다크 판타지 전사. 거대검+검은 갑옷':'Războinic dark fantasy. Spadă + Armură neagră',
'⚡ 사슬이동:강화!':'⚡ Lanț: Îmbunătățit!',
'⚡ 사슬기동:화염!':'⚡ Lanț: Flacără!',
'달성!':'Realizat!',
'ST':'ST',
'부족!':'Insuficient!',
'타':'Lovitură',
'🌀 당기기 모드':'🌀 Mod Tragere',
'💥 밀어내기 모드':'💥 Mod Împingere',
'🕊️빨콩 흡수':'🕊️Absorbire fasole roșie',
'🕊️흡수':'🕊️Absorbire',
'💎유도 폭발!':'💎Explozie ghidată!',
'💥반사 폭발!':'💥Explozie reflecție!',
'⚡⚡ 참회 귀환!':'⚡⚡ Retur Pocăință!',
'⚡ 참회!':'⚡ Pocăință!',
'파도!':'Val!',
'암전!':'Fulger!',
'암흑!':'Întuneric!',
'암흑창!':'Lanț Întunecată!',
'빛창!':'Lanț de Lumină!',
'체 소환!':'invocat!',
'개 설치!':'plasat!',
'💥 보스 그로기!':'💥 Boss Amețit!',
'💥 그로기!':'💥 Amețit!',
'보상':'Bonus',
'⚡ 암전나선!':'⚡ Spirală Fulger!',
'🌋 지진폭풍!':'🌋 Furtună Seismică!',
'SP슬롯':'Slot SP',
'F슬롯':'Slot F',
'⚔🩸 독혈해방!':'⚔🩸 Eliberare Ciumă!',
'⚔ 칼날 해방!':'⚔ Eliberare Lamă!',
'🔨🌋 지옥강타!':'🔨🌋 Lovitură Infernală!',
'🔨 대왕치기!':'🔨 Lovitură Gigantică!',
'✟ 결계의 영역!':'✟ Domeniu Protecție!',
'✟ 물의 영역!':'✟ Domeniu Apă!',
'✟ 파쇄의 영역!':'✟ Domeniu Sfărâmare!',
'✟ 침식의 영역!':'✟ Domeniu Coroziune!',
'✟ 관통의 영역!':'✟ Domeniu Penetrare!',
'✟ 권능의 영역!':'✟ Domeniu Suveran!',
'🛡 회복의 영역!':'🛡 Domeniu Sacru!',
'임계...!':'Critic...!',
'기폭팔!':'Detonare!',
'강제기폭!':'Detonare forțată!',
'자동기폭!':'Detonare auto!',
'회전기폭!':'Vârtej detonare!',
'해제기폭!':'Elibera detonare!',
'지진기폭!':'Seism detonare!',
'혼돈의 왕관':'Coroana Haosului',
'전지전능의 왕관':'Coroana Omnipotentei',
'악마의 팔찌':'Brățară Demonică',
'생명의 팔찌':'Brățară a Vieții',
'🌊 위→아래 파도!':'🌊 Val Sus→Jos!',
'🌊 오른→왼 파도!':'🌊 Val Dreapta→Stânga!',
'🌊 아래→위 파도!':'🌊 Val Jos→Sus!',
'🌊 왼→오른 파도!':'🌊 Val Stânga→Dreapta!',
'무적!':'Invincibil!',
'🪞 반격!':'🪞 Contraatac!',
'💢 반격!':'💢 Contraatac!',
'흡수!':'Absorbire!',
'반격 발사!':'Foc contra!',
'저주! 드랍률 -50%':'Blestem! Drop -50%',
'도망!':'Fugă!',
'위상!':'Fază!',
'방어!':'Gardă!',
'회수 HP+':'Recuperare HP+',
'이동식 복귀':'Retur Mobil',
'약점!':'Slăbiciune!',
'저항!':'Rezistență!',
'콤보 종료: ':'Sfârșit combo: ',
'악의 +':'Răutate +',
'저주 ':'Blestem ',
'불발...':'Ratat...',
'사슬 약점!':'Slăbiciune Lanț!',
'전염 x':'Ciumă x',
'흡수 완료!':'Absorbire completă!',
'부활 성공!':'Înviere reușită!',
'부활 실패...':'Înviere eșuată...',
'차원 이동!':'Schimbare Dimensională!',
'기절 해제':'Amețeală eliminată',
'악의 부족':'Malicie insuficientă',
'스킬 미습득':'Fără abilități',
'펼치기':'Extinde',
'접기':'Restrânge',
'조건 미달!':' neîndeplinită!',
'해제!':' Defuzionat!',
'자동 ON':' Auto ON',
'자동 OFF':' Auto OFF',
'스킬 해제':' abilitate eliminată',
'닫기':'Închide',
'장착 중':'Echipat',
'보관 아이템':'Obiect depozitat',
'클릭으로 선택 · ESC로 닫기':'Click pt. selectare · ESC pt. închidere',
'선택됨':'Selectat',
'악의 부족! (30)':'Malicie insuf.! (30)',
'MP 부족! (40)':'MP insuf.! (40)',
'MP 부족! (100)':'MP insuf.! (100)',
'MP 부족! (10)':'MP insuf.! (10)',
'MP 부족! (':'MP insuf.! (',
'✟ 시전...':'✟ Incantare...',
'🌋 시전...':'🌋 Incantare...',
'⛧ 시전...':'⛧ Incantare...',
'❄ 진입!':'❄ Intrare!',
'⛓️ 사슬!':'⛓️ Lanț!',
'레벨 부족! (요구: Lv.':'Nivel prea mic! (Req: Nv.',
' 장착!':' Echipat!',
' 해제':' Dezechipat',
'👿 악의 추출: +':'👿 Extracție Malicie: +',
'F 슬롯 해제':'Slot F eliminat',
'💫 집중...':'💫 Concentrare...',
'⚡ 마력연사!':'⚡ Baraj Arcan!',
'❄빙결!':'❄Înghețat!',
'🟢독!':'🟢Otravă!',
'⚡감전!':'⚡Electrocutat!',
'🔥화상!':'🔥Arsură!',
'✦ 여신의 가호 — SP+5 AP+3':'✦ Binecuvântare Zeiță — SP+5 AP+3',
'⚔ 기동칼날개!':'⚔ Aripă Lamă!',
'🔥 화염관통!':'🔥 Penetrare Foc!',
'🔱 관통!':'🔱 Penetrare!',
'⚔ 칼날!':'⚔ Lamă!',
'💥 착지!':'💥 Aterizare!',
'💫 기절!':'💫 Amețit!',
'⚡ 체간삭감!':'⚡ Postură ruptă!',
'⚡ 기동파괴! ':'⚡ Distrugere Lanț! T',
'🔥 기동불꽃!':'🔥 Flacără Lanț!',
'🔥 기동불꽃! ':'🔥 Flacără Lanț! T',
'단계 ×':' x',
'⚡ 기동전폭! x':'⚡ Explozie Lanț! x',
'🔥🔥 3중폭!':'🔥🔥 Flacără x3!',
'🔥🔥🔥 6중폭!':'🔥🔥🔥 Flacără x6!',
'🔥🔥🔥🔥 9중폭!':'🔥🔥🔥🔥 Flacără x9!',
'💥 불꽃폭발! ':'💥 Detonare Flacără! ',
'🔥 기동불꽃 준비!':'🔥 Flacără Lanț gata!',
'🔨 기동파괴 준비!':'🔨 Distrugere Lanț gata!',
'⚡ 기동전폭 준비!':'⚡ Explozie Lanț gata!',
'⚡ 과부하! 5초':'⚡ Supraîncărcare! 5s',
'💫 자동 버스트!':'💫 Explozie auto!',
'🔨 칼등날개!':'🔨 Aripă Scut!',
'💥폭발!':'💥Explozie!',
'🛡️💎 유도반사!':'🛡️💎 Reflecție Ghidată!',
'⚡💎 블루콩!':'⚡💎 Fasole Albastră!',
'💎 블루콩!':'💎 Fasole Albastră!',
'⚡반사!':'⚡Reflecție!',
'💎 푸른비 OFF':'💎 Ploaie Azurie OFF',
'💎 푸른비 ON!':'💎 Ploaie Azurie ON!',
'🔥 지옥진!':'🔥 Formație Infernală!',
'🔥 업화선!':'🔥 Rază Infernală!',
'✦ 평화 충격파! ':'✦ Undă Pace! ',
'⚡ 전류 방출!':'⚡ Eliberare Curent!',
'⚡⚡ 레인라이트닝!':'⚡⚡ Ploaie Fulgere!',
'💫 광역!':'💫 Zonă!',
'🔥 불장판!':'🔥 Zonă Foc!',
'💫 피니셔!':'💫 Lovitură finală!',
'☠ 지옥에서 귀환!':'☠ Întors din Infern!',
'☠ 완전 사망!':'☠ Moarte Permanentă!',
'⚔ 처형! ':'⚔ Execuție! ',
'💥 지뢰!':'💥 Mină!',
'⚠ 덫!':'⚠ Capcană!',
'❌ E키로! -':'❌ Folosește E! -',
'❌ Q키로! -':'Apasă Q! -',
'💥무지개 폭발! ':'💥Explozie Curcubeu! ',
'🛡️💎 블루콩!':'🛡️💎 Fasole Albastră!',
'⬜화이트볼!':'⬜Sferă Albă!',
'✨💎 블루콩!':'✨💎 Fasole Albastră!',
'💜다크볼!':'💜Bilă Întunecată!',
'❄빙판!':'❄Podea Gheață!',
'🌨빙결!':'🌨Înghețat!',
'🕸둔화!':'🕸Încetinit!',
'💀 역병 처형!':'💀 Execuție Ciumă!',
'💥 역병 Finale!':'💥 Final Ciumă!',
'⚔ 균열 악마!':'⚔ Demon Fisură!',
'자동회수 HP+':'Auto-Recuperare HP+',
'MP 부족 — 연사 해제':'MP scăzut — Foc rapid OFF',
'MP 부족 — 푸른비 OFF':'MP scăzut — Ploaie Azurie OFF',
'🛡️반사!':'🛡️Reflecție!',
'⚡🦴 참회 귀환!':'⚡🦴 Retur Pocăință!',
'🦴⚡해골번개!':'🦴⚡Fulger de Oase!',
'⚡악의폭풍!':'⚡Furtună Malicie!',
'❄아이스스톰!':'❄Furtună Gheață!',
'⚡ 암전폭발!':'⚡ Explozie Fulger!',
'⚡ 레인라이트닝! x':'⚡ Ploaie Fulgere! x',
'❄ 탈출!':'❄ Evadare!',
'⚡쉴드!':'⚡Scut!',
'❄🌪️ 얼음보주!':'❄🌪️ Sferă Gheață!',
'🌪️ 전개!':'🌪️ Desfășurare!',
'❄ 빙결흡인!':'❄ Vârtej Gheață!',
'❄☄ 빙결폭발!':'❄☄ Explozie Gheață!',
'☄️ 흡인!':'☄️ Vârtej!',
'☄️ 대폭발!':'☄️ Mega Explozie!',
'❄ 얼음보주!':'❄ Sferă Gheață!',
'⏳ 시간왜곡!':'⏳ Distorsiune Temporală!',
'쿨다운!':'Reîncărcare!',
'❄ 파쇄!':'❄ Sfărâmare!',
'☄️💥 대폭발!':'☄️💥 Mega Explozie!',
'반사!':'Reflecție!',
'💀 도넛!':'💀 Inel!',
'💀 전멸!':'💀 Anihilare!',
'🌊 파도!':'🌊 Val!',
'속박!':'Legare!',
'반격!':'Contraatac!',
'분신!':'Clonă!',
'분신 파괴!':'Clonă distrusă!',
'무기 해방!':'Eliberare armă!',
'❄프리즌!':'❄Închisoare!',
'⚡ 증표 ':'⚡ Marcaj ',
'흔들!':'Cutremur!',
'⚠ 광역 발사!':'⚠ Foc AoE!',
'🔥 확산!':'🔥 Răspândire!',
'⚠ 돌진!':'⚠ Atac!',
'🦅 도약!':'🦅 Salt!',
'⚡ 레이저!':'⚡ Laser!',
'🌊 충격파!':'🌊 Undă șoc!',
'👹 소환!':'👹 Invocare!',
'☄ 유성우!':'☄ Ploaie meteori!',
'🖐 잡기!':'🖐 Apucare!',
'🌀 회전참!':'🌀 Vârtej!',
'💣 지뢰!':'💣 Mină!',
'🌀 흡인!':'🌀 Aspirare!',
'🔴 빨간콩 폭풍!':'🔴 Furtună Fasole Roșie!',
'🔴🔴 콩 비!':'🔴🔴 Ploaie Fasole!',
'🌊 부채꼴 충격파!':'🌊 Undă evantai!',
'✴ 멸광 레이저!':'✴ Laser Anihilare!',
'🔴 추적 장판!':'🔴 Zonă Urmărire!',
'💥 속성탄!':'💥 Foc Elemental!',
'⚔ 검기!':'⚔ Ki Spadă!',
'⚔ 재단참!':'⚔ Tăietură Secerătoare!',
'🌀 나선탄!':'🌀 Foc Spirală!',
'⚠ 찌르기!':'⚠ Împunsătură!',
'🔥🔥 지옥기둥!':'🔥🔥 Pilon Infernal!',
'⚔ 환영검!':'⚔ Lamă Fantomă!',
'💢 반격자세!':'💢 Postură Contra!',
'⚔ 연격!':'⚔ Combo!',
'🌑 암흑!':'🌑 Întuneric!',
'👥 분신!':'👥 Clonă!',
'🌋 균열!':'🌋 Fisură!',
'🌊 파동!':'🌊 Undulație!',
'💣 추적지뢰!':'💣 Mină urmăritoare!',
'⏪ 되감기!':'⏪ Derulare!',
'🌀 중력장!':'🌀 Câmp gravitațional!',
'🔨 벽밀기!':'🔨 Împingere perete!',
'☠ 독안개!':'☠ Ceață otrăvitoare!',
'⛓ 감옥!':'⛓ Închisoare!',
'⚡ 연쇄번개!':'⚡ Fulger în lanț!',
'🔮 궤도탄!':'🔮 Foc orbital!',
'🛡 방패돌진!':'🛡 Atac scut!',
'🪞 반격자세!':'🪞 Postură Contra!',
'⚓ 속박!':'⚓ Legare!',
'👤 분신!':'👤 Clonă!',
'🖐 탈취!':'🖐 Furt!',
'🔥🔥 용암 지대!':'🔥🔥 Zonă lavă!',
'🌧🌧 화염 폭격!':'🌧🌧 Baraj foc!',
'⚡⚡ 전격 장막!':'⚡⚡ Văl fulger!',
'💀 내 곁으로!':'💀 Vino la mine!',
'⭕ 안전!':'⭕ Sigur!',
'💀💀 전멸 폭발!':'💀💀 Explozie Anihilare!',
'⚡ 쐐기 소멸!':'⚡ Extincție Pană!',
'🌊충격파!':'🌊Undă șoc!',
'👿악의+100':'👿Malicie+100',
'💥패링폭발!':'💥Explozie Parare!',
'균열 충돌! ':'Coliziune fisură! ',
'벽 충돌! ':'Coliziune perete! ',
'소환!':'Invocare!',
'환영!':'Fantomă!',
'⚡낙뢰!':'⚡Tunet!',
'⚡빔!':'⚡Rază!',
'환영술!':'Iluzie!',
'💀소환!':'💀Invocare!',
'🔮주술!':'🔮Blestem!',
'🩸산란!':'🩸Apariție!',
'💢광폭!':'💢Frenezie!',
'🕷산란!':'🕷Apariție!',
'❄서리!':'❄Ger!',
'❄빙결파!':'❄Val Gheață!',
'💀빙마!':'💀Demon Gheață!',
'돌진!':'Atac!',
'충격파!':'Undă șoc!',
'독안개!':'Ceață otrăvitoare!',
'연타!':'Rafală!',
'포효!':'Răget!',
'강화!':'Întărire!',
'꼬리!':'Coadă!',
'은신...':'Invizibilitate...',
'기습!':'Ambuscadă!',
'산란!':'Apariție!',
'독가스!':'Gaz otrăvitor!',
'소멸...':'Dizolvare...',
'강타!':'Zdrobire!',
'분비!':'Secreție!',
'채찍!':'Bici!',
'출혈!':'Sângerare!',
'급강하!':'Plonjare!',
'방출!':'Descărcare!',
'충격!':'Impact!',
'치유!':'Vindecare!',
'의식!':'Ritual!',
'지옥불!':'Foc infernal!',
'끌려감!':'Tras!',
'혀!':'Limbă!',
'응시!':'Privire!',
'낙하!':'Cădere!',
'핏방울!':'Picătură sânge!',
'일어남!':'Ridicare!',
'휩쓸기!':'Măturat!',
'웅크림':'Ghemuit',
'뼈칼날!':'Lamă de os!',
'감속!':'Încetinit!',
'비명!':'Țipăt!',
'화산탄!':'Foc vulcanic!',
'자폭!':'Autodistrugere!',
'감싸기!':'Înfășura!',
'잡기!':'Apucare!',
'내리찍기!':'Lovitură!',
'브레스!':'Suflu!',
'비행!':'Zbor!',
'용암비!':'Ploaie lavă!',
'물뿜기!':'Jet de apă!',
'빛...':'Lumină...',
'삼키기!':'Înghiți!',
'마비!':'Paralizie!',
'방전!':'Descărcare!',
'집게찍기!':'Clește!',
'찍기!':'Lovitură!',
'붙잡기!':'Prinde!',
'감아올리기!':'Înfășura!',
'파편!':'Fragment!',
'할퀴기!':'Zgârietură!',
'기생충!':'Parazit!',
'심연 해방!':'Eliberare abisală!',
'촉수난타!':'Baraj tentacule!',
'삼지창!':'Trident!',
'소용돌이!':'Vârtej!',
'해일!':'Tsunami!',
'끼걱!':'Scârțâit!',
'폭발!':'Explozie!',
'체인!':'Lanț!',
'갈기!':'Coamă!',
'공포!':'Teroare!',
'흡혈!':'Drenare!',
'베기!':'Tăietură!',
'비이이명!!':'Driiing!!',
'분열!':'Sciziune!',
'3연참!':'Triplă tăietură!',
'패링!':'Parare!',
'...복사...':'...Copie...',
'불균형...저주!':'Dezechilibru...Blestem!',
'저주!':'Blestem!',
'균형...강화!':'Echilibru...Întărire!',
'심판의 기둥!':'Pilonul Judecății!',
'처형 선고!':'Sentință Moarte!',
'고통의 해방!':'Eliberare durere!',
'너도 느껴봐라!':'Simte și tu!',
'대검난무!':'Frenezie spadă!',
'촉수!':'Tentacul!',
'전방위 빔!':'Rază totală!',
'회피!':'Ferire!',
'[F] 상점':'[F] Magazin',
'거래 성공!':'Comerț reușit!',
'악의 부족! (':'Malicie insuf.! (',
'상인이 떠납니다...':'Negustorul pleacă...',
'사슬 해방!':'Eliberare lanț!',
'완전 해방!':'Eliberare totală!',
'⏪ 시간 되감기!':'⏪ Derulare Timp!',
'전환!':'Schimbare!',
'부활 ':'Înviere ',
'🌀균열!':'🌀Fisură!',
'...사라짐':'...Dispărut',
'낫 베기!':'Tăietură coasă!',
'☠ 죽음의 선고!':'☠ Sentință Moarte!',
'선고 집행...':'Executare sentință...',
'⚡패링!':'⚡Parare!',
'경직!':'Clătinare!',
'⚠ 잡혔다!':'⚠ Prins!',
'💥 내던지기!':'💥 Aruncare!',
'💥 소용돌이 폭발!':'💥 Explozie Vârtej!',
'👻 순간이동!':'👻 Teleportare!',
'💫 기절! 5초':'💫 Amețit! 5s',
'찌르기 반격!':'Contraatac împingere!',
'💢 폭발!':'💢 Explozie!',
'반격 실패':'Contraatac eșuat',
'탈취 반격!':'Contraatac furt!',
'무기 봉인!':'Sigiliu armă!',
'냠!':'Ham!',
'합체!':'Fuzionat!',
'출구가 열렸다!':'Ieșire deschisă!',
'보물상자 출현!':'Cufăr de comori!',
'출구':'Ieșire',
'⚠ 문지기가 살아있다!':'⚠ Gardian încă viu!',
'⏱ 타임어택 ':'⏱ Cronometru ',
'처치율 ':'Rată Elim. ',
'불사 보호':'Protecție nemuritoare',
'환영 소멸!':'Fantomă dispărută!',
'부활력 ':'Putere Înviere ',
'✟ 신성력 억제! (':'✟ Suprimare Sacră! (',
'부활 실패 (':'Înviere eșuată (',
'⚡순간이동!':'⚡Teleportare!',
'👻 동반부활!':'👻 Co-Înviere!',
'✟ 신성력 억제!':'✟ Suprimare Sacră!',
'💀 부활 판정 중...':'💀 Se judecă învierea...',
'⚔ 문지기 처치!':'⚔ Gardian Eliminat!',
'🚪 보스방 개방!':'🚪 Cameră Boss Deschisă!',
'잔해 출현!':'Rămășițe apărute!',
'🌀균열 발생!':'🌀Fisură deschisă!',
'🔥복수!':'🔥Răzbunare!',
'💥폭독혈!':'💥Sânge Ciumă!',
'빙판!':'Podea Gheață!',
'❄최종빙결!':'❄Îngheț Final!',
'빙마 처치!':'Demon Gheață Eliminat!',
'분리!':'Separare!',
'뼈 파편!':'Fragment de os!',
'태아 처치!':'Fetus Eliminat!',
'지배자 처치!':'Stăpân Eliminat!',
'용암!':'Lavă!',
'화룡 처치!':'Dragon Foc Eliminat!',
'최후의 비명!':'Țipăt Final!',
'산화...':'Oxidare...',
'심판자 처치!':'Judecător Eliminat!',
'고통의 왕 처치!':'Regele Durerii Eliminat!',
'수역!':'Apă!',
'파편 폭발!':'Explozie fragment!',
'거대어 처치!':'Leviatan Eliminat!',
'대사도 처치!':'Mare Apostol Eliminat!',
'독웅덩이!':'Baltă otravă!',
'화염장판!':'Zonă Foc!',
'전기장!':'Câmp electric!',
'무기 드롭!':'Armă căzută!',
'보물 발견!':'Comoară găsită!',
'상인의 주머니 +':'Pungă negustor +',
'속박의 파편!':'Ciob de legare!',
'시간의 조각!':'Fragment de timp!',
'저주 해제!':'Blestem ridicat!',
'차원의 결정!':'Cristal dimensional!',
'전설 아이템!':'Obiect legendar!',
'죽음을 이겨냈다!':'A învins moartea!',
'💥대폭발!':'💥Mega Explozie!',
'⚡강화!':'⚡Întărire!',
'장비 ':'Echip. ',
'💫 진동!':'💫 Tremur!',
'❄ 무적!':'❄ Invincibil!',
'집중 해제!':'Concentrare anulată!',
'집중!':'Concentrare!',
'🕊️ 평화보호 ':'🕊️ Egidă ',
'🛡 보호막 ':'🛡 Scut ',
'🌀 회전보호막 ':'🌀 Scut Rotativ ',
'💥한방캡!':'💥Limită o lovitură!',
'⚡쉴드 파괴!':'⚡Scut distrus!',
'💀 불굴!':'💀 De neclintit!',
'💀 1회부활!':'💀 1 viață înviere!',
'감시 회수':'Recuperare santinelă',
'악마화 부활!':'Înviere demonică!',
'배정 가능한 스킬 없음':'Fără abilități de atribuit',
'칼날 없음!':'Fără lamă!',
'⚔ 악의사냥!':'⚔ Vânătoare Malicie!',
'❄🌪️ 얼음소용돌이!':'❄🌪️ Vârtej Gheață!',
'🌪️ 폭풍소환!':'🌪️ Invocare Vortex!',
'🌹 붉은꽃!':'🌹 Floare Stacojie!',
'💥 폭산탄!':'💥 Foc Exploziv!',
'🪡 바늘출!':'🪡 Salvă de Ace!',
'⚡ 전격이동!':'⚡ Pas Fulger!',
'기둥가시로 흡수됨':'Absorbit de țeapă pilon',
'🌿 가시덫!':'🌿 Capcană Țepi!',
'⚡ 전격의창!':'⚡ Lanț Tunet!',
'🏹 공성쇠뇌 설치!':'🏹 Arbaletă Asediu plasată!',
'👻 유령 허수아비!':'👻 Momeală Fantomă!',
'💥 폭발 허수아비!':'💥 Momeală Explozivă!',
'축적!':'Stocat!',
'축적 중...':'Stocare...',
'만충! 재입력→폭발':'Plin! Re-apasă→Explodează',
'폭발! ':'Explodează! ',
'뎀':' DMG',
'🩸 폭독칼날!':'🩸 Lamă Pestilentă!',
'⚡날개치기!':'⚡Lovitură Aripă!',
'🗡 칼등날개!':'🗡 Aripă Scut!',
'🏛️ 악의기둥!':'🏛️ Pilon Întunecat!',
'🌿 기둥가시!':'🌿 Țeapă Pilon!',
'🌋 지옥강타!':'🌋 Lovitură Infernală!',
'💥 체간 붕괴!':'💥 Postură Ruptă!',
'💫 포이즈 파괴!':'💫 Postură Distrusă!',
'⚡ 뇌전걸음!':'⚡ Pas Fantomă!',
'✟ 구속의 영역!':'✟ Domeniu Legare!',
'✟ 신성폭발!':'✟ Explozie Sacră!',
'⛧ 블랙!':'⛧ Stea Neagră!',
'🌋 용암소환!':'🌋 Invocare Lavă!',
'필살기 배정!':'Ultim atribuit!',
'완료':'Complet',
'합체 가능':'Poate Fuziona',
'부족':'Insuficient',
'SP 부족! (':'SP insuf.! (',
'🕊️ 히든: 평화의보호 해금!':'🕊️ Ascuns: Egida Păcii deblocată!',
'⚡ 히든: 참회 해금!':'⚡ Ascuns: Pocăință deblocată!',
'배정됨':'Atribuit',
'합체 Lv.':'Fuziune Nv.',
'◆ 같은 보석 스킬 습득 시 합체 가능':'◆ Fuzionare la aceeași gemă',
'▼ 가방 → 창고 보관':'▼ Sac → Depozit',
'▲ 창고 → 가방 꺼내기':'▲ Depozit → Sac',
'✓ 선택됨':'✓ Selectat',
'⟨ 입력 대기... ⟩':'⟨ Așteptare... ⟩',
'⟨ 대기 ⟩':'⟨ Pauză ⟩',
'보조':'Sec.',
'키 설정 초기화 (또는 F5 키)':'Resetare taste (sau F5)',
'아무 키 또는 마우스 버튼을 누르세요 (ESC = 취소)':'Apasă o tastă sau buton (ESC = anulare)',
'WebGPU 활성':'WebGPU Activ',
'WebGL2 활성':'WebGL2 Activ',
'측정 중...':'Măsurare...',
'불러오기 실패':'Încărcare eșuată',
'장착':'Echipat',
'🔒 중요잠금 아이템은 분해 선택 불가!':'🔒 Obiectele blocate nu pot fi selectate!',
'장비 강화 (실패 시 재료만 소멸)':'Îmbunătățire echip. (la eșec, materiale pierdute)',
'강화 보너스 적용':'Bonus îmbunătățire aplicat',
'강화 실패!':'Îmbunătățire eșuată!',
'장착된 장비가 없습니다.':'Fără echipament echipat.',
'충분':'Suficient',
'더 필요':'Trebuie mai mult',
'장비 선택':'Selectează echipament',
'목표치 설정':'Setează țintă',
'악의 투입':'Investește malicie',
'자동 시도':'Încercare auto',
'목표 강화치':'Îmbunătățire țintă',
'예상 필요 악의':'Malicie est. necesară',
'보유':'Deținut',
'강화 시작':'Începe îmbunătățire',
'위에서 장비를 선택하세요':'Selectează echipament sus',
'⬆ 물약 강화 (최대 10단)':'⬆ Îmbunătățire Poțiune (max nivel 10)',
'필요':'Necesar',
'악의의 분해로 — 장비를 악의로 갈아버려라':'Cuptor Malicie — Macină echipament',
'전체 선택':'Selectează tot',
'전체 해제':'Deselectează tot',
'희귀 이하':'Rar sau sub',
'어픽스 리롤!':'Relanseaza afix!',
'영웅':'Eroic',
'전설':'Legendar',
'무기 타입':'Tip Armă',
'활 타입':'Tip Arc',
'ST 부족':'ST insuficient',
'💀 광폭화!':'💀 Înfuriat!',
'...따라오는 거 아니야. 같은 방향일 뿐이지.':'...Nu te urmăresc. Doar aceeași direcție.',
'공기가 달라졌어. 더 썩었군.':'Aerul s-a schimbat. Mai putred.',
'여기부터는 악마 영역이야. ...맘대로 해.':'Teritoriu demonic de aici. ...Fă ce vrei.',
'...이 냄새. 살점이 썩는 냄새야.':'...Mirosul ăsta. Carne putrezindă.',
'여기 오래 있으면 미쳐. 나도, 너도.':'Stai prea mult și înnebunești. Și eu.',
'이 길의 끝에 뭐가 있을까. ...알고 싶지도 않어.':'What\'s at the end of this road? ...I don\'t want to know.',
'...여기가 끝이야. 돌아갈 길은 없어.':'...Aici e sfârșitul. Nu e cale de întoarcere.',
'사슬을 땅에 꽂으면 끌려간다.':'Înfige Lanțul în pământ și vei fi tras.',
'Shift로 사슬 던져봐!':'Încearcă să arunci Lanțul cu Shift!',
'패링 성공하면 ST가 회복된다. 공짜 자원이야.':'Pararea restaurează ST. Resurse gratuite.',
"패링은 타이밍이다. 헛치면 빈틈이 생겨.":"Parada ține de sincronizare. Dacă ratezi, rămâi descoperit.",
"잘못 패링하면 그로기가 쌓인다!":"O parare greșită îți umple bara de amețeală!",
"여기가 지옥인가":"Deci ăsta e iadul",
"아무 키나 눌러 시작":"Apasă orice tastă",
"다시 시작":"Repornire",
'패링 많이 하면 ST 걱정 없어~':'Parează mult și ST nu e niciodată o problemă~',
'장비 분해하면 악의를 얻는다. 쓰레기도 자원이야.':'Dezasamblarea echipamentului dă Malicie. Și gunoiul e resursă.',
'TAB 열어서 안 쓰는 장비 분해해!':'Deschide TAB și dezasamblează echipamentul nefolosit!',
'그로기 상태의 적에겐 1.5배 데미지가 들어간다.':'Inamicii amețiți primesc 1.5x daune.',
'무릎 꿇으면 전력으로 때려!':'Când îngenunchează, lovește cu tot!',
'속성 상성이 있다. 화염은 빙결에 약하고, 암전은 암흑에 약하다.':'Elementele au contrare. Foc slab la Gheață, Fulger la Întuneric.',
'무기 속성 바꿔가면서 싸워봐!':'Încearcă să schimbi elementul armei!',
'빙결된 적은 1.5배 데미지를 받는다.':'Inamicii înghețați primesc 1.5x daune.',
'얼리고 때리는 게 기본이야!':'Înghiață și lovește — asta e baza!',
'보스의 빨간 공격은 패링 가능. 보라빛은 회피만.':'Atacurile roșii ale bossului se parează. Curcubeu, doar ferire.',
'색깔 잘 봐! 빨강은 받아치고 무지개는 피해!':'Uită-te la culori! Parează roșu, ferește-te de curcubeu!',
'VIT를 올리면 최대 HP가 오른다. 죽기 싫으면 찍어.':'VIT crește HP maxim. Investește dacă vrei să supraviețuiești.',
'STR은 근접, DEX는 활, INT는 마법! 골고루 말고 하나만!':'STR luptă, DEX arc, INT magie! Concentrează-te pe unul!',
'우클릭을 꾹 누르면 빔이 나간다. 짧게 누르면 투사체.':'Ține clic dreapta pentru rază. Apasă scurt pentru proiectil.',
'마법 쓸 때 MP 잘 봐! 빔은 연속으로 깎여!':'Ai grijă de MP cu magia! Raza drenează rapid!',
'핵터와 디로이가 아이템을 주워준다. 수거 범위 안이면.':'Hecter și Deroy colectează obiecte în rază.',
'우리한테 고마워해~ 안 주우면 썩잖아.':'Mulțumește-ne~ Dacă nu le culegi, putrezesc.',
'LCK를 올리면 레어 드롭률이 오른다.':'LCK crește rata de drop rar.',
'운빨 게임이긴 하지~ LCK 올려봐!':'E un joc de noroc~ Crește LCK!',
'강화하면 공격력이 쭉쭉 올라가! 악의만 있으면 돼!':'Îmbunătățirea crește ATK rapid! Doar Malicie necesară!',
'강화 확률은 +1에서 99%. 높을수록 떨어진다.':'Șansa de îmbunătățire începe la 99% pt. +1. Scade pe măsură ce crește.',
'실패하면 악의만 날아가~ 장비는 안 부서져!':'Dacă eșuezi, doar Malicia se pierde~ Echipamentul supraviețuiește!',
'대장간에서 장비 제작도 된다. 악의 30000개면 영웅급 이상.':'Forja poate fabrica echipament. 30000 Malicie pt. Eroic+.',
'랜덤이지만 좋은 거 나올 수도 있어!':'E aleator, dar ceva bun poate ieși!',
'쉴드는 마법으로, HP는 물리로 깎아야 제대로 먹힌다.':'Scut cu magie, HP cu fizic pt. a fi eficient.',
'반대로 치면 50%만 들어가! 무기 바꿔가면서 싸워!':'Tipul greșit face doar 50%! Schimbă armele!',
'장비에 접두사, 접미사가 붙으면 특수 효과가 생긴다.':'Echipamentul cu prefix/sufix primește efecte speciale.',
'영웅급 이상 장비에만 붙어! 좋은 거 나오면 강화해!':'Doar pe echipament Eroic+! Îmbunătățește-le pe cele bune!',
'강화는 장비를 바꿔도 자동 이전된다. 악의만 있으면.':'Îmbunătățirea se transferă automat. Costă doar Malicie.',
'더 좋은 장비 나오면 바로 장착해! 강화 수치 그대로 옮겨가!':'Echipează echipament mai bun imediat! Îmbunătățirea se transferă!',
'패링을 써야 자원을 흡수한다고!':'Trebuie să parezi pt. a absorbi resurse!',
'F키 회복의 영역을 써봐. 자원이 차올라.':'Încearcă F Domeniu Sacru. Resursele se umple.',
'적이 근접하면 스페이스키야! 가시덫을 활용해!':'Când se apropie, Spațiu! Folosește Capcana de Țepi!',
'기절시켜! 그로기가 터지면 데미지가 1.5배야!':'Amețește-i! Amețit înseamnă 1.5x daune!',
'1번 대왕치기로 밀어버려!':'Folosește tasta 1 Lovitură Gigantică pt. a împinge!',
'무릎 꿇었다.':'Îngenunchează.',
'지금이야! 몰아쳐!!':'Acum! Atacă!!',
'스킬 포인트 있어! K 눌러서 스킬 찍어봐!':'Ai puncte! Apasă K pt. abilități!',
'...힘이 없으면 여기서 끝이야.':'...Fără putere, aici e sfârșitul.',
'...쓸 거 아니면 분해해.':'...Dacă nu-l folosești, dezasamblează.',
'아이템 넘쳐나네~ 우리가 주워줄게!':'Multe obiecte~ Le colectăm noi!',
'악의가 바닥이다.':'Fără Malicie.',
'TAB 열어서 장비 분해해! 쓰레기도 악의가 돼!':'Deschide TAB și dezasamblează! Și gunoiul devine Malicie!',
'좋은 장비가 있네! G 눌러서 대장간 가봐!':'Echipament bun! Apasă G pt. forjă!',
'...강화 안 하면 그냥 고철이야.':'...Fără îmbunătățire, e doar fier vechi.',
'...멈추지 마. 여신은 기다리지 않는다.':'...Nu te opri. Zeița nu așteaptă.',
'앞으로 가자~ 나도 여기 오래 있기 싫어.':'Hai înainte~ Nici eu nu vreau să rămân!',
'...냄새가 짙다. 큰 놈이 있어.':'...Mirosul e dens. Ceva mare e aici.',
'준비됐어? 물약 확인하고!':'Gata? Verifică poțiunile!',
'TAB을 눌러. 가방을 열고 장비를 입어야 한다.':'Apasă TAB. Deschide sacul și echipează-te.',
'주웠으면 껴야지! TAB!':'L-ai luat? Echipează-l! TAB!',
'G. 대장간에서 물약도 제작할 수 있다.':'G. La forjă poți fabrica poțiuni.',
'악의로 물약 만들어! G키야!':'Fabrică poțiuni cu Malicie! Tasta G!',
'기절이야! Ctrl 눌러!':'Amețit! Apasă Jtrl!',
'Ctrl 유령걸음으로 탈출!':'Ctrl Pas Fantomă pt. a scăpa!',
'Ctrl 얼음보주로 탈출!':'Ctrl Sferă de Gheață pt. a scăpa!',
'빨간 탄은 E 패링. 무지개는 Q 패링.':'Gloanțe roșii: parare E. Curcubeu: Q.',
'나머지는 전부 E 패링 가능해!':'Restul se parează cu E!',
'빨강=E, 무지개=Q 패링. 나머진 다 쳐내.':'Roșu=E, Curcubeu=Q. Deviază restul.',
'무지개는 Q로 패링! 나머지는 전부 E!':'Curcubeu cu Q! Restul cu E!',
'빠져! 물약 마시고 안전한 곳에서 회복해.':'Retrage-te! Bea poțiuni și recuperează-te.',
'자원 없으면 도망가는 게 답이야!':'Fără resurse? Fuga e răspunsul!',
'스페이스! 가시덫으로 적 묶어버려!':'Spațiu! Prinde inamicii cu Capcana!',
'근접이 너무 많아! 거리 벌려!':'Prea multă luptă apropiată! Creează distanță!',
'...둘러싸이면 끝이야. 빠져나와.':'...Dacă te înconjoară, e gata. Ieși.',
'1번 대왕치기로 쓸어버려!':'Folosește tasta 1 Lovitură Gigantică pt. a mătura!',
'그로기 터지면 데미지 1.5배!':'Amețit activează 1.5x daune!',
'회전참이나 광역기로 몰아! 한 놈씩 상대하면 죽어.':'Folosește Vârtej sau AoE! Unul câte unul și mori!',
'뭉쳐있을 때가 기회야!':'Când se grupează, e șansa ta!',
'E로 마력공격을 해봐! 악의 쉴드를 해제할려면 마법 공격을 해야 해!':'Încearcă E pt. atacuri magice! Ai nevoie de magie pt. a sparge scuturile!',
'쉴드는 마법으로, HP는 물리로. 반대로 치면 데미지 안 들어간다.':'Scut cu magie, HP cu fizic. Invers nu face daune.',
'L키로 스킬 슬롯에 넣어야 쓸 수 있어.':'Apasă L pt. a atribui abilități la sloturi.',
'J키를 눌러. 패시브 포인트가 쌓여있다.':'Apasă J. Punctele pasive s-au acumulat.',
'J키! 패시브 올리면 진짜 강해져!':'J! Pasivele te fac mult mai puternic!',
'스태미나가 부족하다. 무리하지 마.':'Rezistență insuficientă. Nu forța.',
'ST 없으면 스킬 못 써! 잠깐 빠져!':'Fără ST, fără abilități! Retrage-te!',
'탭 장비창을 열어봐. 아이템을 주워왔어!':'Deschide TAB. Am colectat un obiect!',
'좋은 거 나왔다! TAB 열어서 확인해봐!':'Ceva bun a căzut! Deschide TAB!',
'악의에 중독되면 악마가 돼서 부활력이 생긴대. 저 녀석처럼.':'Se spune că dependența de Malicie te transformă în demon cu putere de înviere. Ca acela.',
'혹시 너도...?':'Poate și tu...?',
'데미지가 부족하면 무기류 강화를 해야해!!':'Dacă lipsesc daunele, îmbunătățește armele!!',
'G키 대장간. 강화 안 하면 여기서 계속 죽어.':'G pt. forjă. Fără îmbunătățiri, vei muri aici.',
'시간이 없어. 움직여.':'Nu e timp. Mișcă-te.',
'멍하게 서있으면 안 돼!':'Nu sta doar acolo!',
'...뭘 기다리는 거야?':'...Ce aștepți?',
'가자가자! 몬스터가 기다려!':'Hai! Monștrii așteaptă!',
'여기 오래 있으면 위험해.':'Să stai aici prea mult e periculos.',
'움직여야 해! 가만있으면 둘러싸여!':'Trebuie să te miști! Stai pe loc și te înconjoară!',
'쉬는 건 죽고 나서 해.':'Odihnește-te după ce mori.',
'살아있을 때 쉬면 안 돼!':'Nu te odihni cât ești viu!',
'적이 몰려오고 있어. 빨리 움직여.':'Inamicii se apropie. Mișcă-te repede.',
'냄새 맡고 올 거야. 빨리!':'Te vor mirosi! Repede!',
'...아직 살아있는 거 맞지?':'...Încă ești viu, nu?',
'혹시 잠든 거야...?':'Ai adormit...?',
'...나무가 썩어가고 있어. 여기는 지옥의 입구야.':'...Copacii putrezesc. Aceasta e intrarea în iad.',
'냄새 지독해... 빨리 지나가자.':'Mirosul e oribil... Hai să trecem repede.',
'조심해. 벌레굴이다. 벽이랑 바닥에서 기어나와.':'Atenție. Cuib de viermi. Ies din pereți și podea.',
'으으... 벌레 싫어! 밟아버려!':'Ugh... Urăsc gângăniile! Calcă-le!',
'...공기가 얼어붙는다. 여기선 화염이 먹힌다.':'...Aerul îngheață. Focul funcționează aici.',
'추워... 빙결 조심해! 얼면 끝이야.':'Frig... Atenție la înghețare! Dacă înghiți, e gata!',
'용암이다. 바닥을 밟으면 타 죽어.':'Lavă. Calcă pe sol și vei arde de viu.',
'뜨거워! 여기 왜 이렇게 빨개!':'Ce cald! De ce e totul atât de roșu?!',
'...군단이다. 수가 많아. 광역기 없으면 밀려.':'...Legiunea. Prea mulți. Fără AoE vei fi copleșit.',
'우글우글... 징그러워. 한꺼번에 쓸어!':'Mișună peste tot... Dezgustător. Mătură-i pe toți!',
'사도의 영역이야. 여기 놈들은 머리가 좋아.':'Teritoriul Apostolului. Aceștia sunt deștepți.',
'패턴이 복잡해졌어... 집중해!':'Tiparele au devenit complexe... Concentrează-te!',
'...끝이다. 지옥의 심장부. 살아 돌아가는 건 포기해라.':'...Acesta e sfârșitul. Inima iadului. Abandonează orice speranță.',
'여기가 마지막이야... 각오해.':'Acesta e sfârșitul... Pregătește-te.',
'석궁 자동발사 (T)':'Arbaletă automată (T)',
'버스트루프 당기기 (H)':'Buclă explozie atrage (H)',
'결정 자동합성':'Cristal auto-sinteză',
'결정 자동강화':'Cristal auto-îmbunătățire',
'✓ 설정 자동 저장':'✓ Setări salvate automat',
'세팅 프리셋 저장/불러오기':'Salvare/încărcare presetare',
'세팅1 저장':'Salvează presetare 1','세팅1':'Presetare 1',
'세팅2 저장':'Salvează presetare 2','세팅2':'Presetare 2',
'재진단':'Rediagnosticare',
'게임 리셋 (처음부터)':'Resetare joc (de la început)',
'캐릭터 선택 (로비)':'Selectare personaj (Lobby)',
'닫기 [ESC]':'Închide [ESC]','닫기 [G]':'Închide [G]','닫기 [N]':'Închide [N]','닫기 [J]':'Închide [J]',
'전체화면 (F11)':'Ecran complet (F11)',
'정말 모든 진행을 초기화하시겠습니까?':'Chiar vrei să resetezi tot progresul?',
'검출 중...':'Se detectează...',
'마우스 커서':'Cursor mouse','그래픽 품질':'Calitate grafică','하드웨어 진단':'Diagnosticare hardware',
'BGM 선택':'Selecție BGM',
'자동 (스테이지별)':'Automat (pe etapă)','전체 랜덤':'Totul aleatoriu','로비':'Lobby',
'1장 랜덤':'Capitol 1 aleatoriu','2장 랜덤':'Capitol 2 aleatoriu','3장 랜덤':'Capitol 3 aleatoriu',
'4장 랜덤':'Capitol 4 aleatoriu','5장 랜덤':'Capitol 5 aleatoriu','6장 랜덤':'Capitol 6 aleatoriu','7장 랜덤':'Capitol 7 aleatoriu',
'보스':'Boss','최종보스':'Șef final',
'대장간 랜덤':'Forjă aleatoriu','사망 랜덤':'Moarte aleatoriu','승리 랜덤':'Victorie aleatoriu',
'지옥 추락 사망 징글':'Jingle moarte cădere iad','탈출 성공':'Evadare reușită',
'── 1장 - 썩은 숲 ──':'── CAP1 - Pădurea Putredă ──','── 2장 - 벌레굴 ──':'── CH2 - Worm Nest ──',
'── 3장 - 얼음굴 ──':'── CAP3 - Caverna de Gheață ──','── 4장 - 화염지대 ──':'── CH4 - Infernal Wastes ──',
'── 5장 - 지옥군단 ──':'── CAP5 - Legiunea Infernului ──','── 6장 - 사도마굴 ──':'── CH6 - Apostle Den ──',
'── 7장 - 지옥성 ──':'── CAP7 - Citadela Infernului ──','── 공통 ──':'── Common ──',
'⌨ 조작법':'⌨ Controale','클릭하면 닫힘':'Clic pentru a închide',
'전투력':'PS','가방':'Geantă','결정':'Cristal',
'↕ 정렬':'↕ Sortare','쓰레기 전체선택':'Selectează tot gunoiul','쓰레기 전부 분해':'Dezmembrează tot gunoiul',
'창고':'Depozit','스탯 포인트':'Puncte atribut','능력치 요약':'Rezumat statistici','올 리셋':'Resetează tot',
'대장간':'Forjă','스킬':'Abilități','능력치':'Atribute',
'좌클스킬 (클릭 전환)':'Abilit. CS (clic schimbare)','E스킬 (클릭 전환)':'Abilit. E (clic schimbare)',
'이동스킬 (클릭 전환)':'Abilit. mișcare (clic schimbare)','마법스킬 (클릭 전환)':'Abilit. magie (clic schimbare)',
'영역스킬 (클릭 전환)':'Abilit. zonă (clic schimbare)','피보호막 (클릭 전환)':'Scut sânge (clic schimbare)',
'CT스킬 (클릭 전환)':'Abilit. CT (clic schimbare)','[J] 능력치':'[J] Atribute',
'무기 공격':'Atac cu armă','칼등 처내기 (투사체 반사, 홀드 연사)':'Parare (reflectă proiectile, ținut=rafală)',
'연속 처내기':'Parare continuă','영역 스킬 (폭풍소환 등)':'Abilit. zonă (Vortex etc)',
'사슬 발사':'Tragere Lanț','마법 (탭=투사체, 홀드=빔)':'Magie (apăsare=proiectil, ținut=fascicul)',
'데빌포스 흡수':'Absorb forță demonică','물약 / 스킬슬롯':'Poțiuni / Sloturi abilități',
'스킬슬롯 5 / 필살기 / CT스킬':'Slot 5 / Ultim / Abilit. CT','스킬 슬롯 배정':'Atribuire slot',
// --- Phase 27 additions ---
'위로 이동':'Mișcare sus','아래로 이동':'Mișcare jos','왼쪽 이동':'Mișcare stânga','오른쪽 이동':'Mișcare dreapta',
'칼등 처내기 (탭=처내기, 홀드=연사)':'Parare lamă (apăsare=parare, ținut=rafală)',
'영역 스킬':'Abilitate zonă','사슬 이동':'Lanț Dash',
'유령불꽃 켜기/끄기':'Flacără Fantomă Activ/Inactiv','기동칼날개 자동 켜기/끄기':'Aripă Lamă Auto Activ/Inactiv',
'해상도':'Rezoluție',
'빛이 꺼졌다':'Lumina Se Stinge','누군가는 너를 기다리고 있다':'Cineva te așteaptă',
'다시 일어서라':'Ridică-te din nou','로비로 돌아가기':'Întoarce-te la Lobby',
'☠ 사망 리플레이':'☠ Reluare Moarte',
'지옥의 시련을 견뎌냈다':'Ai îndurat proba Iadului',
'계속 전투':'Continuă lupta','난이도를 선택하라':'Alege dificultatea',
'나중에 설정(ESC)에서 변경 가능':'Poate fi schimbat în Setări (ESC) mai târziu',
'일괄합성':'Sinteză în masă','일괄강화+합성':'Îmbunătățire în masă+Sinteză',
'자원 부족!':'Resurse Insuficiente!',' 뎀':' Dmg',
'합체 폭발!':'Detonare Fuziune!',
'MP 부족! (50)':'MP Insuficient! (50)',
'부활력 고갈!':'Reînviere Epuizată!','☠ 부활력 고갈!':'☠ Reînviere Epuizată!',
'독안개':'Ceață Otravă','뇌전창':'Lanț de Tunet',
'🔥 업화선 시전...':'🔥 Raza Iadului pregătire...',
'💥 기동파괴 그로기!':'💥 Distrugere în Lanț Groggy!',
'💥 칼등 그로기!':'💥 Parare Lamă Groggy!',
'⚡ 순간이동 준비!':'⚡ Teleportare Pregătită!',
'👿악의+1000':'👿Răutate+1000',
'💀 내려찍기!':'💀 Izbire de Sus!',
'✟ 신성력 억제! +':'✟ Putere Sfântă Suprimată! +',
'✟ 신성력 억제!':'✟ Putere Sfântă Suprimată!',
'✟ 신성력 억제! (':'✟ Putere Sfântă Suprimată! (',
'💥 지진그로기!':'💥 Cutremur Groggy!',
'💥 기폭그로기!':'💥 Detonare Groggy!',
'폭발! ×':'Explozie! ×','⚫ 기둥강타!':'⚫ Lovitură Stâlp!',
'💥 대왕치기 그로기!':'💥 Colosal Groggy!',
'💫 미니스턴!':'💫 Mini amețire!','⚡ 뇌전창!':'⚡ Lanț de Tunet!',
'…절반이다. 정신차려.':'…Jumătate. Concentrează-te.',
  '빨강은 E! Q는 안 돼!': 'Roșu = E! Q nu merge!',
  '무지개탄은 Q 패링이다. E는 안 통해.': 'Proiectilele curcubeu se parează cu Q. E nu merge.',
  '타고 있군. 화상은 점점 심해진다. 피를 채워.': '…Arzi. Arsura se agravează. Refă-ți HP-ul.',
  '화상이야! 점점 심해져! 물약으로 HP 관리해!': 'Arzi! Se agravează! Gestionează-ți HP-ul cu poțiuni!',
'…죽기 직전이다. 한 발만 더.':'…Aproape mort. Încă o lovitură.',
'…다음 한 방이 마지막이야.':'…Următoarea lovitură e ultima.',
'기절! ':'Amorțit! ',
'마력이 빈다. 평타 섞어.':'MP se golește. Amestecă atacuri normale.',
'그랩이다. 거리를 둬.':'Atac de prindere. Menține distanța.',
'광역기다. 멀어져.':'Atac de zonă. Depărtează-te.',
'…아파? 당연하지. 여긴 지옥이야.':'…Doare? Bineînțeles. Acesta e iadul.',
'F키도 스킬 슬롯이야!':'F este și un slot de abilitate!',
'L-CTRL로 유령걸음/얼음보주!':'L-CTRL pentru Mers Fantomă / Glob de Gheață!',
'N 눌러서 창고에 넣어둬!':'Apasă N pentru depozitare!',
'ESC로 설정! 난이도/자동물약!':'ESC pentru setări! Dificultate/Auto-poțiuni!',
'잡몹이다. 먼저 정리해.':'Inamici obișnuiți. Curăță-i mai întâi.',
'…얼어붙은 놈은 오래 안 간다.':'…Un inamic înghețat nu durează mult.',
'…냄새가 짙다. 큰 놈이 있어.':'…Mirosul e puternic. Ceva mare e aproape.',
'쉴드는 마법으로, HP는 물리로.':'Scut ia magie, HP ia fizic.',
'스페이스! 가시덫으로 적 묶어!':'Spațiu! Prinde inamicii cu Capcana cu Spini!',
'근접 너무 많아! 거리 벌려!':'Prea mulți aproape! Răspândește-te!',
'회전참이나 광역기로 몰아!':'Folosește Tăietură Rotativă sau Zonă!',
'F 눌러! 회복의 영역 깔아!':'Apasă F! Pune Domeniu Sacru!',
'F키 회복의 영역을 써봐.':'Încearcă tasta F Domeniu Sacru.',
'빠져! 물약 마시고 회복해.':'Retrage-te! Bea poțiuni și recuperează-te.',
'쉬프트! 사슬기동은 이동기야!':'Shift! Dash în Lanț e un instrument de mișcare!',
'스킬포인트 쌓였어! K 눌러!':'Puncte de abilitate gata! Apasă K!',
'스킬 포인트 있어! K!':'Puncte de abilitate! K!',
'J키. 패시브 포인트가 쌓여있다.':'Tasta C. Punctele pasive s-au acumulat.',
'…쓸 거 아니면 분해해.':'…Dezasamblează ce nu vei folosi.',
'…강화 안 하면 그냥 고철이야.':'…Fără îmbunătățire e doar fier vechi.',
'빨간 탄은 E. 무지개는 Q.':'Gloanțe roșii: E. Curcubeu: Q.',
'빨강=E, 무지개=Q.':'Roșu=E, curcubeu=Q.',
'…멈추지 마. 여신은 기다리지 않는다.':'…Nu te opri. Zeița nu așteaptă.',
'패턴이 바뀐다. 거리를 둬.':'Modelul se schimbă. Menține distanța.',
'미쳐가고 있어. 광폭화다.':'Înnebunește. Mod de furie.',
'마지막이야! 끝장내!':'Ultima fază! Termină-l!',
'…끝났다. 다음으로.':'…Gata. Înainte.',
'다 잡았다! 포탈 어딨어?':'Toți prinși! Unde e portalul?',
'근육으로 만든 빌드군. 베고 부숴.':'Build de mușchi. Taie și sfărâmă.',
'활을 쥐었군. 거리를 둬.':'Arc în mână. Menține distanța.',
'마법사군. MP 관리부터 배워라.':'Magician. Învață mai întâi managementul MP.',
'운에 기댄 빌드군. …드롭은 좋겠어.':'Build bazat pe noroc. …Cel puțin drops-urile vor fi bune.',
'…VIT가 너무 낮아. 한 방에 죽는다.':'…VIT e prea scăzut. Mori dintr-o lovitură.',
'다 찍으면 다 약해진다. 하나만 골라.':'Maximizezi totul și ești slab peste tot. Alege unul.',
'…3단. 적이 강해져. 정신 차려.':'…Faza 3. Inamicii mai puternici. Concentrează-te.',
'5단이다. …너도 강해졌단 뜻이야.':'Faza 5. …Înseamnă că și tu ai crescut.',
'…7단. 아직 살아있단 게 신기하군.':'…Faza 7. Încă în viață. Surprinzător.',
'10단. …너는 이제 인간이 아니야.':'Faza 10. …Nu mai ești uman.',
'…일반으로 내려왔군. 가끔은 쉬어가야지.':'…Înapoi la Normal. Uneori ai nevoie de o pauză.',
'…이게 진짜 패링이야.':'…Aceasta e o parare adevărată.',
'…피가 묻기 시작했군.':'…Sângele începe să curgă.',
'100. 너는 인간이 아니야.':'100. Nu ești uman.',
'…피 흘리며 베는군.':'…Taie prin sânge.',
'빨간콩이 푸르게 변했다. 그게 너의 무기야.':'Glonțul roșu a devenit albastru. Acesta e armamentul tău.',
'무지개를 받아쳤군. 그건 진짜 어렵다.':'Ai parat un curcubeu. E cu adevărat greu.',
'…너무 빨라. 닿기 직전에 눌러.':'…Prea rapid. Apasă chiar înainte de contact.',
'악의가 가득 찼다. 풀어내.':'Răutatea e plină. Elibereaz-o.',
'사슬이 살을 뚫었어. 끌고 와.':'Harpoane a perforat carnea. Trage-l înăuntru.',
'…풀차지군. 멀리 던져버려.':'…Complet încărcat. Aruncă-l departe.',
'…빈틈을 그대로 빠져나갔다.':'…S-a strecurat direct prin spărtură.',
'…일반 잡몹이 아니야. 모디파이어 붙었군.':'…Nu e un inamic obișnuit. Are un modificator.',
'엘리트 하나 처리.':'Un elite eliminat.',
'…큰 놈이다. 일반 잡몹 정리부터.':'…E mare. Curăță inamicii obișnuiți mai întâi.',
'미니보스 처리. 다음 길로.':'Mini-boss eliminat. La următorul drum.',
'한 번에 다섯. 깔끔해.':'Cinci dintr-o dată. Curat.',
'100강. 이제 뭔가 다르게 보이는군.':'+100. Lucrurile arată diferit acum.',
'…운이 없는 날이야.':'…Zi nefericită.',
'…전설이다. 이런 건 처음 본다.':'…Legendar. Nu am văzut niciodată așa ceva.',
'…죽었다 살아났네. 여신은 너를 포기 안 했어.':'…A murit și s-a întors. Zeița nu a renunțat la tine.',
'…또야? 패턴 좀 외워!':'…Din nou? Învață modelul!',
'…한 번도 안 죽고. 그건 진짜 실력이야.':'…Niciodată mort. Aceasta e abilitate adevărată.',
'…ACT1을 끝냈다. 진짜 시작은 여기서부터야.':'…ACT1 terminat. Adevăratul început e de aici.',
'모든 보스를 무너뜨렸다. 너는 지옥의 일부야.':'Toți bosii au căzut. Ești parte din iad.',
'…30초. 너 진짜 미쳤구나.':'…30 secunde. Ești cu adevărat nebun.',
'…빠르군. 효율적이야.':'…Rapid. Eficient.',
'신기록이다.':'Record nou.',
'탭 장비창을 열어봐.':'Deschide fereastra de echipament cu TAB.',
'데미지 부족하면 무기 강화!':'Nu suficient damage? Îmbunătățește arma!',
// --- Loading screen ---
'불러오는 중...':'Se încarcă...',
'로딩중...':'Încărcare...',
'맵과 몬스터 불러오는 중...':'Se încarcă harta și monștrii...',
'기본 데이터 준비 중...':'Se pregătesc datele de bază...',
'저장 데이터 불러오는 중...':'Se încarcă datele salvate...',
'몬스터 스킨 로딩...':'Se încarcă skin-urile monștrilor...',
'맵과 몬스터 생성 중...':'Se generează harta și monștrii...',
'맵 에셋 로딩...':'Se încarcă resursele hărții...',
'맵 환경 준비 중...':'Se pregătește mediul hărții...',
'주변 청크 준비 중...':'Se pregătesc chunk-urile apropiate...',
'맵 캐시 생성 중...':'Se construiește cache-ul hărții...',
'미니맵 빌드 중...':'Se construiește minimapa...',
// Phase 28
' 으로 탈출!':' pentru a scăpa!',
'100명?! 미쳤어!':'100 uciși?! Nebunie!',
'10단 최고난이도! 너 진짜 광기야!':'Dificultate 10 max! Total nebun!',
'1분 안에 클리어! 빠르네!':'Nivel terminat în 1 minut! Atât de rapid!',
'30초!! 스피드런 가능해!':'30 secunde!! Potențial speedrun!',
'3단! 보상도 좋아지지만 죽기 쉬워!':'Dificultate 3! Recompense mai bune dar mori mai ușor!',
'50명! 학살자야!':'50 uciși! Măcelar!',
'5단!! 진짜 게이머 인증!':'Dificultate 5!! Gamer adevărat certificat!',
'7단!! 다른 사람들 이 정도 못 와!':'Dificultate 7!! Alții nu ajung atât de departe!',
'ACT1 완주! 우리가 진짜 해냈어!':'ACT1 complet! Chiar am reușit!',
'Ctrl 얼음보주로 탈출하라.':'Ctrl — scapă cu Ice Orb.',
'Ctrl 유령걸음으로 탈출하라.':'Ctrl — scapă cu Ghost Walk.',
'J키! 패시브 강해져!':'Tasta J! Pasivele devin mai puternice!',
'DEX 빌드! 거리에서 패고, 추적탄 좋아!':'Build DEX! Atacuri la distanță, proiectile de urmărire!',
'E로 마력공격을 해봐!':'Încearcă atacul magic cu E!',
'G 눌러서 대장간 가봐!':'Apasă G — fierărie!',
'G키 대장간. 강화 안 하면 계속 죽어.':'G — fierărie. Fără îmbunătățiri, continui să mori.',
'HP 70%! 조심해!':'HP 70%! Fii atent!',
'INT 빌드! 빔이랑 폭발 마법! MP 잘 봐!':'Build INT! Magie fascicul și explozie! Urmărește MP!',
'LCK 높아! 레어 드롭률 미친 거 알지?':'LCK ridicat! Rata de drop rar e nebună!',
'L로 어디에 뭘 넣을지 골라!':'Apasă L — alege configurația sloturilor de abilități!',
'MP 부족! 평타로 패면서 회복해!':'MP scăzut! Lovește pentru a recupera!',
'ST 없으면 스킬 못 써!':'Fără ST, fără abilități!',
'STR 빌드! 회전참, 회오리, 광역기 추천!':'Build STR! Tăietură rotativă, vârtej, AoE!',
'VIT 좀 찍어! HP 너무 적어!':'Adaugă VIT! HP prea scăzut!',
'Z 누르면 대박! 쿨타임 길어!':'Apasă Z pentru ultimate! Cooldown lung!',
'…고기 냄새. 싫진 않네.':'…Miros de sânge. Nu e rău.',
'…둘러싸이면 끝이야.':'…Înconjurat înseamnă mort.',
'…말은 못해.':'…Nu pot vorbi.',
'…버리기 아까운 건 창고에.':'…Obiectele valoroase în depozit.',
'…빈틈을 노려.':'…Caută deschiderile.',
'…설정을 확인해.':'…Verifică setările.',
'…슬롯을 채워. 빈 손은 죽음이다.':'…Umple sloturile. Mâinile goale înseamnă moarte.',
'…아직 살아있네. 좌클릭으로 저것들 쳐봐.':'…Încă ești în viață. Clic stânga să îi lovești.',
'…운이 좋았을 뿐이야. 아마.':'…Ai fost doar norocos. Probabil.',
'…치는 건 할 줄 아네. 피하는 건?':'…Știi să lovești. Dar să eviți?',
'…힘을 골라라. 전부 가질 순 없다.':'…Alege-ți puterea. Nu poți avea totul.',
'골고루 안 돼! 하나로 밀어!':'Nu dispersa! Concentrează-te pe un stat!',
'그로기 터지면 1.5배!':'Groggy = 1.5x daune!',
'길이 열렸다.':'Calea este deschisă.',
'나머진 전부 E 패링 가능!':'Restul — E parry!',
'나머진 전부 E!':'Restul — E!',
'다섯 번 연속! 내가 본 인간 중 최고!':'Cinci la rând! Cel mai bun pe care l-am văzut!',
'다음엔 죽지 마!':'Nu mai muri data viitoare!',
'소환수 왔어! 먼저 처리해야 해!':'Monștri invocați! Elimină-i mai întâi!',
'스킬 없으면 방향키 연타뿐이야.':'Fără abilități? Apasă continuu săgețile.',
'신기록!! 스트리머한테 보내!':'Record nou!! Trimite streamerului!',
'아이템 넘쳐! 우리가 주워줄게!':'Geanta plină! Noi culegem pentru tine!',
'안 죽고 깼어! 진짜 천재 맞네!':'Finalizat fără moarte! Geniu adevărat!',
'앞으로 가자~':'Să mergem înainte~',
'우리가 해냈어! 다음 챕터 가자!':'Am reușit! Capitolul următor!','핵터 니가 진짜 해냈구나, 여왕님이 기뻐하시겠어!':'Hector, chiar ai reușit! Regina va fi încântată!',
'일반 모드! 편하게 즐기자!':'Modul normal! Bucură-te relaxat!',
'자원이 반이다. F키로 회복해.':'Resurse la jumătate. F pentru recuperare.',
'잡힌다! 옆으로 빠져!':'Te prind! Evadează lateral!',
'장비 분해해! 쓰레기도 악의!':'Dezasamblează echipamentul! Și gunoiul dă malice!',
'전부 다 잡았어! 우리가 지옥의 왕이야!':'Totul eliminat! Suntem regii iadului!',
'좋은 거 나왔다! TAB!':'Pradă bună! TAB!',
'죽기 직전에 죽이다니! 멋져!':'Ucizi chiar înainte să mori! Superb!',
'체력 반 남았어! 물약 마실 타이밍!':'HP jumătate! Timpul pentru poțiune!',
'큰 거 온다! 도망쳐!':'Atac mare vine! Fugi!',
'패링으로 돌려주고, Q 보호막도 써!':'Parry și reflectă, folosește și scutul Q!',
'패턴이 빨라졌어!':'Tiparele sunt mai rapide!',
'한 대만 맞아도 죽어! 패링이든 회피든!!':'O lovitură = moarte! Parry sau evită!!',
'한 방이면 죽어! 도망쳐!!':'Un foc omoară! Fugi!!',
'화염엔 빙결! 암전엔 암흑!':'Foc → gheață! Gol → umbră!',
'── 2장 - 벌레굴 ──':'── CAP2 - Cuibul Viermilor ──',
'── 4장 - 화염지대 ──':'── CAP4 - Ținutul Infernal ──',
'── 6장 - 사도마굴 ──':'── CAP6 - Vizuina Apostolului ──',
'── 공통 ──':'── Comun ──',
'난이도를 선택하라':'Alege dificultatea',
'☠ 부활력 고갈!':'☠ Revenire Epuizată!',
'⏳⚡ 시간걸음!':'⏳⚡ Pas în Timp!',
'블룸 효과':'Efect Bloom',
'잔상 트레일':'Urmă imagine reziduală',
'슬래시 이펙트':'Efect de tăiere',
'후처리 효과':'Post-procesare',
'사망 이펙트':'Efect de moarte',
'동적 조명':'Iluminare dinamică',
'횃불 조명 (어둠)':'Lumină torță (întuneric)',
'앰비언트 파티클':'Particule de ambianță',
'안개 효과':'Efect de ceață',
'필름 그레인':'Grăunțe film',
'캐릭터 외곽선':'Contur personaj',
'리롤':'Rerunare',
'물약':'Poțiune',
'으로 탈출!':'pentru a fugi!',
'Shift 사슬':'Shift Lanț',
'더블탭 전격이동':'Apăsare dublă — Săritură fulger',
'Ctrl 유령걸음':'Ctrl Pas fantomă',
'Ctrl 얼음보주':'Ctrl Sferă de gheață',
'🔴화염→빙결 2배 | 🔵빙결→화염 2배 | ⚪물리=중립 | 악마 처치 시 악의 영혼 드롭':'🔴Foc→Gheață 2× | 🔵Gheață→Foc 2× | ⚪Fiz=Neutru | Omoară demoni pentru suflete de răutate',
  '미구현':'N/A',
  '스탯 총량':'Total statistici',
  '장비':'echipament',
  '공속':'vit.atac',
  '크리':'crít',
  '크리뎀':'daune crít',
  '근성':'Tenacitate',
  '종합 지표':'Prezentare generală',
  '근접 DPS':'DPS corp',
  '공격력×공속×크리':'ATK×Vit×Crít',
  '활 DPS':'DPS arc',
  '마법 DPS':'DPS magie',
  '유효 HP (EHP)':'HP eficient (EHP)',
  '쉴드':'Scut',
  '장비 파워':'Putere echip.',
  '근접 공격력':'ATK corp',
  '기본':'bază',
  '무기':'armă',
  '패시브':'pasiv',
  '활 공격력':'ATK arc',
  '정밀':'Precizie',
  '마법 공격력':'ATK magie',
  '왕관':'coroană',
  '마력':'Arcan',
  '공격속도':'Viteză atac',
  '크리티컬':'Critic',
  '데미지':'daune',
  '확률':'Rată',
  '어픽스':'afix',
  '레거시':'moștenire',
  '추가뎀':'daune extra',
  '패링 카운터뎀':'Daune parare',
  'E공속':'Viteză E',
  '무지개탄DR':'DR curcubeu',
  '포이즈파괴':'Sparge Poise',
  '방어관통':'Penetrare armură',
  '관통력':'Penetrare',
  '속성':'Elemente',
  '무기속성':'Elem. armă',
  '독':'Otravă',
  '초':'s',
  '암흑저주':'Blestem întunecat',
  '원소집중':'Focus elem.',
  '원소전환':'Conv. elem.',
  '방어':'Apărare',
  '물리방어':'DEF fizic',
  '감소':'reducere',
  '캡':'limită',
  '장갑':'mănuși',
  '바지':'pantaloni',
  '속성방어':'DEF elem.',
  '목걸이':'colier',
  '반지1':'inel1',
  '반지2':'inel2',
  '반사':'Reflectare',
  '가시':'Spini',
  '배리어':'Barieră',
  '보호막 흡수':'Absorbție scut',
  '속성 저항':'Rezistență elem',
  'CC저항':'Rezistență CC',
  '생존':'Supraviețuire',
  '장비HP':'HP echip.',
  '임플':'Impl.',
  '에너지쉴드':'Scut de energie',
  '리젠':'Regen.',
  '스태미나':'Vigoare',
  '성장':'Creștere',
  'MP%어픽스':'Afix MP%',
  '이동속도':'Viteză mișcare',
  '한방캡':'Limita lovitură',
  '최대HP의33%':'33% HP max',
  '비용/효율':'Cost/Efic',
  '근접ST':'ST corp',
  '활ST':'ST arc',
  '마법MP':'MP magie',
  '사슬사거리':'Raza Lanț',
  '기동게이지':'Bară Drive',
  '쿨감':'Red. CD',
  '쇠뇌뎀':'Daune arbalestă',
  '쇠뇌공속':'Viteză arbalestă',
  '기타':'Diverse',
  '물약쿨':'CD poțiune',
  '회복+':'Recuperare+',
  '드롭':'Pradă',
  '경험치+':'EXP+',
  '골드+':'Aur+',
  '기동:칼날개':'Drive:Lamă',
  '기동:전폭':'Drive:Lovitură',
  '기동:기습':'Drive:Ambuscadă',
  '충전스킬':'Abilitate încărcare',
  '사슬게이지':'Bară lanț',
  '특수 효과':'Efecte speciale',
  '처치뎀+':'Daune omor+',
  '위기뎀+':'Daune criză+',
  '피격반격':'Contraatac la lovitură',
  '풍요(적HP≥70%뎀+)':'Abundență(HP≥70%+)',
  '약자포식(적HP≤30%뎀+)':'Prădător(HP≤30%+)',
  '패링폭발':'Explozie parare',
  '체간파괴+':'Sparge Poise+',
  '콤보뎀+':'Daune combo+',
  '사슬뎀+':'Daune Lanț+',
  '스킬뎀+':'Daune abilitate+',
  '패리+':'Parare+',
  '체인':'Lanț',
  '정화':'Purificare',
  '회':'×',
  '불굴':'Tenacitate',
  '신성력':'Putere sfântă',
  '악마력(부활력)':'Forță demon',
  '자연':'Natură',
  '악마성':'Caracter demonic',
  '인간성':'Umanitate',
  '전투 통계':'Statistici luptă',
  '핵터':'Hecter',
'디로이':'Deroy',
// --- Phase 37: skill desc ---
'벤치 FPS:':'FPS Bench:',
// --- CAT-82: skill panel labels ---
'스킬 정보':'Info Abilitate',
'타입':'Tip',
'미습득':'Neînvățat',
'SP 비용':'Cost SP',
'악의 비용':'Cost Malicie',
'쿨다운':'Reîncărcare',
'요구 레벨':'Niv. Cerut',
'기본 참조뎀':'Daune Referință',
'스탯 배율':'Multiplicator Stat',
'패시브 배율':'Multiplicator Pasiv',
'레벨 배율':'Multiplicator Nivel',
'예상 평균 뎀':'Daune Medii Estimate',
'치명타':'Critic',
'치명타 확률':'Rată Critic',
'치명타 배율':'Daune Critic',
'유효 배율':'Multiplicator Efectiv',
'스킬 고유':'Specific Abilitate',
'1타 배율':'Multiplicator Lovitură 1',
'2타 배율':'Multiplicator Lovitură 2',
'3타 배율':'Multiplicator Lovitură 3',
'레벨당 뎀':'Daune per Nivel',
'검기 거리':'Distanță Semilună',
'레벨당 거리':'Bonus Distanță per Nivel',
'ST/틱':'ST/Tick',
'레벨당 크기':'Dimensiune per Nivel',
'넉백':'Respingere',
'충전 시간':'Timp Încărcare',
'레벨당 범위':'Rază per Nivel',
'관통률':'Rată Penetrare',
'지속뎀':'Durată DoT',
'무한':'Infinit',
'타격 형식':'Tip AoE',
'진동파':'Undă de Șoc',
'스태거':'Clătinare',
'높음':'Ridicat',
'스톡':'Stocuri',
'기둥 수':'Piloni',
'지속':'Durată',
'반경':'Rază',
'슬로우':'Încetinire',
'활':'Arc',
// --- CAT-83: affix desc labels ---
'독 DoT':'DoT Otravă',
'화상 DoT':'DoT Foc',
'빙결 DoT+감속':'DoT Gheață+Încetinire',
'저주(힐차단)':'Blestem(Blocare Vindecare)',
'방어무시':'Ignorare Armură',
'치명타율':'Rată Critic',
'스태거+':'Clătinare+',
'체인타겟+':'Ținte Lanț+',
'처치 후 뎀+':'Daune după Kill+',
'크리폭발(ATK×)':'Explozie Critic(ATK×)',
'원소뎀+':'Daune Elem.+',
'공격속도+':'Viteză Atac+',
'패리보너스+':'Bonus Parare+',
'추적콤보+10':'Combo Urmărire+10',
'사슬뎀+':'Lanț DMG+',
'쿨다운-':'CD-',
'방어력+':'APR+',
'쉴드+':'Scut+',
'이동속도+':'Viteză Mișcare+',
'크리확률+':'Rată Critic+',
'크리배율+':'Daune Critic+',
'화염저항':'Rez. Foc',
'빙결저항':'Rez. Gheață',
'암전저항':'Rez. Fulger',
'암흑저항':'Rez. Întuneric',
'독저항':'Rez. Otravă',
'전원소저항':'Rez. Toate Elem.',
'물리DR':'Red. Fiz.',
'반사%':'Reflectare%',
'가시뎀':'Daune Țepi',


'패링폭발(ATK×)':'Explozie Parare(ATK×)',
'체간파괴뎀+':'Daune Spargere Postură+',
'상태이상해제':'Elimină Stări',
'불굴(1회생존)':'Tenacitate(Supraviețuire×1)',
'부활(HP회복)':'Înviere(Restaurare HP)',
'드롭률+':'Rată Drop+',
'경험치+':'EXP+',
'포션회복+':'Vindecare Poțiune+',
'사슬게이지+':'Indicator Lanț+',
'부활억제':'Anti-Înviere',
'부활력+':'Putere Înviere+',
'부활쿨-':'CD Înviere-',
'최대HP%+':'HP Max%+',
'HP리젠+':'Regen. HP+',
'회복력+':'Putere Vindecare+',
'마법뎀+':'Daune Magie+',
'MP소비-':'Cost MP-',
'화염뎀%+':'Daune Foc%+',
'화염관통%':'Pen. Foc%',
'적중화상':'Hit→Arsură',
'크리화폭':'Critic→Explozie Foc',
'화상지속+':'Durată Arsură+',
'화염뎀보너스':'Bonus Daune Foc',
'빙결뎀%+':'Daune Gheață%+',
'빙결관통%':'Pen. Gheață%',
'적중빙결':'Hit→Îngheț',
'크리빙폭':'Critic→Explozie Gheață',
'빙결지속+':'Durată Îngheț+',
'빙결뎀보너스':'Bonus Daune Gheață',
'뇌전뎀%+':'Daune Fulger%+',
'뇌전관통%':'Pen. Fulger%',
'적중감전':'Hit→Electrocutare',
'크리뇌폭':'Critic→Explozie Fulger',
'감전지속+':'Durată Electrocutare+',
'뇌전뎀보너스':'Bonus Daune Fulger',
'암흑뎀%+':'Daune Întuneric%+',
'암흑관통%':'Pen. Întuneric%',
'적중저주':'Hit→Blestem',
'크리암폭':'Critic→Explozie Întuneric',
'저주지속+':'Durată Blestem+',
'암흑뎀보너스':'Bonus Daune Întuneric',
'독뎀%+':'Daune Otravă%+',
'독관통%':'Pen. Otravă%',
'적중중독':'Hit→Otrăvire',
'크리독폭':'Critic→Explozie Otravă',
'독지속+':'Durată Otravă+',
'독뎀보너스':'Bonus Daune Otravă',
'근접뎀%+':'Daune Corp%+',
'원거리뎀%+':'Daune Distanță%+',
'마법뎀%+':'Daune Magie%+',
'빔뎀%+':'Daune Rază%+',
'DoT뎀%+':'Daune DoT%+',
'투사체뎀%+':'Daune Proiectil%+',
'범위반경+':'Rază AoE+',
'근접크리+':'Critic Corp+',
'마법크리+':'Critic Magie+',
'석궁크리+':'Critic Arbaletă+',
'근접공속+':'Viteză Corp+',
'석궁공속+':'Viteză Arbaletă+',
'시전속도+':'Viteză Incantare+',
'전속성관통':'Pen. Toate Elem.',
'쉴드관통':'Penetrare Scut',
'방어력깎기':'Sfărâmare Armură',
'투사체속도+':'Viteză Proiectil+',
'적중시화구':'Hit→Minge Foc',
'적중시연쇄뇌격':'Hit→Fulger în Lanț',
'적중빙결%':'Hit→Îngheț%',
'적중스턴%':'Hit→Amețire%',
'적중중독%':'Hit→Otrăvire%',
'적중출혈%':'Hit→Sângerare%',
'적중약화%':'Hit→Slăbire%',
'적중감속%':'Hit→Încetinire%',
'적중표적%':'Hit→Marcare%',
'크리폭발(HP%)':'Explozie Critic(HP%)',
'크리연쇄(HP%)':'Lanț Critic(HP%)',
'크리빙결%':'Critic→Îngheț%',
'크리HP+':'Critic→HP+',
'크리MP+':'Critic→MP+',
'크리쉴드+':'Critic→Scut+',
'피격방어+':'APR la Hit+',
'반격가시':'Țepi Contraatac',
'빙결파동%':'Undă Gheață%',
'자동암흑막':'Scut Întuneric Auto',
'주기치유':'Vindecare Periodică',
'시체폭발%':'Explozie Cadavru%',
'회피뎀+':'Daune Eschivare+',
'패링폭발%':'Explozie Parare%',
'블록HP+':'HP Blocare+',
'블록MP+':'MP Blocare+',
'회전참뎀+':'Daune Vârtej+',
'옴니빔뎀+':'Daune Rază Omni+',
'화구뎀+':'Daune Minge Foc+',
'미사일뎀+':'Daune Rachetă+',
'청탄뎀+':'Daune Glonț Albastru+',
'폭렬탄뎀+':'Daune Împușcătură Explozivă+',
'지옥광선뎀+':'Daune Rază Infernală+',
'악의폭풍뎀+':'Daune Furtună Malicie+',
'연쇄참뎀+':'Daune Tăietură Lanț+',
'거인강타뎀+':'Daune Lovitură Gigant+',
'유령보행뎀+':'Daune Pas Fantomă+',
'악의박격뎀+':'Daune Mortier Malicie+',
'화염오라뎀+':'Daune Aură Foc+',
'빙구뎀+':'Daune Sferă Gheață+',
'화염빔뎀+':'Daune Rază Foc+',
'악의사냥뎀+':'Daune Vânătoare Malicie+',
'암흑기둥뎀+':'Daune Pilon Întuneric+',
'역병뎀+':'Daune Ciumă+',
'가시오라뎀+':'Daune Aură Țepi+',
'연쇄돌격뎀+':'Daune Asalt Lanț+',
'회피확률+':'Rată Eschivare+',
'회피쿨-':'CD Eschivare-',
'쉴드%+':'Scut%+',
'쉴드리젠%+':'Regen. Scut%+',
'쉴드쿨-':'CD Scut-',
'HP리젠%+':'Regen. HP%+',
'ST리젠+':'Regen. ST+',
'ST리젠%+':'Regen. ST%+',
'MP리젠+':'Regen. MP+',
'MP리젠%+':'Regen. MP%+',
'화염DR':'Red. Foc',
'빙결DR':'Red. Gheață',
'뇌전DR':'Red. Fulger',
'암흑DR':'Red. Întuneric',
'독DR':'Red. Otravă',
'전체DR':'Red. Totală',
'엘리트DR':'Red. Elită',
'스턴저항':'Rez. Amețire',
'감속저항':'Rez. Încetinire',
'넉백저항':'Rez. Respingere',
'돌진거리+':'Distanță Dash+',
'돌진쿨-':'CD Dash-',
'전투이속+':'Viteză Luptă+',
'비전투이속+':'Viteză în Afara Luptei+',
'습득범위+':'Rază Colectare+',
'전스탯+':'Toate Stats+',
'적중자원+':'Resursă la Hit+',
'화염최대저항+':'Rez. Max Foc+',
'빙결최대저항+':'Rez. Max Gheață+',
'뇌전최대저항+':'Rez. Max Fulger+',
'암흑최대저항+':'Rez. Max Întuneric+',
'독최대저항+':'Rez. Max Otravă+',
'스킬쿨-':'CD Abilitate-',
'물약쿨-':'CD Poțiune-',
'강화성공+':'Rată Fabricare+',
'악의획득+':'Câștig Malicie+',
'악마화뎀+':'Daune Demonizare+',
'악마화DR':'Red. Demonizare',
'영혼수확+':'Recoltare Suflete+',
'생명흡혈%':'Absorb. Viață%',
'과치유→쉴드':'Supravindecare→Scut',
'만마나뎀+':'Daune Mana Plină+',
'이동DR':'Red. Mișcare',
'정지뎀+':'Daune Static+',
'회피후뎀+':'Daune Post-Eschivare+',
'패링쉴드+':'Scut Parare+',
'콤보보너스+':'Bonus Combo+',
'HP≥70%뎀+':'HP≥70% Daune+',
'적HP≤30%뎀+':'Inamic HP≤30% Daune+',
'HP100%뎀+':'HP100% Daune+',
'HP≤35%뎀+':'HP≤35% Daune+',
'적HP≤20%뎀+':'Inamic HP≤20% Daune+',
'근접뎀+':'Daune Corp+',
'원거리뎀+':'Daune Distanță+',
'스턴적뎀+':'Daune vs Amețit+',
'빙결적뎀+':'Daune vs Înghețat+',
'화상적뎀+':'Daune vs Ars+',
'중독적뎀+':'Daune vs Otrăvit+',
'저주적뎀+':'Daune vs Blestemat+',
'감속적뎀+':'Daune vs Încetinit+',
'보스뎀+':'Daune Șef+',
'엘리트뎀+':'Daune Elită+',
'일반몹뎀+':'Daune Gloată+',
'선제뎀+':'Daune Prima Lovitură+',
'물리흡혈%':'Absorb. Fizică%',
'마나흡수%':'Absorb. Mana%',
'ST흡수%':'Absorb. ST%',
'적중HP+':'HP la Hit+',
'처치HP+':'HP la Kill+',
'처치MP+':'MP la Kill+',
'처치ST+':'ST la Kill+',
'처치시폭발':'Explozie la Kill',
'처치이속+':'Viteză la Kill+',
'HP≥70%방어+':'HP≥70% APR+',
'HP≤50%이속+':'HP≤50% Viteză+',
'DoT피해감소':'Red. Daune DoT',
'화상피해감소':'Red. Daune Arsură',
'보스피해감소':'Red. Daune Șef',
'근접피해감소':'Red. Daune Corp',
'원거리피해감소':'Red. Daune Distanță',
'처치HP회복':'Restaurare HP la Kill',
'처치쉴드회복':'Restaurare Scut la Kill',
'ST소비-':'Cost ST-',
'HP≥70%공격+':'HP≥70% ATK+',
'HP≤35%흡혈':'HP≤35% Absorb.',
'보스추가뎀':'Daune Extra vs Șef',
'엘리트추가뎀':'Daune Extra vs Elită',
'공격력+':'ATK+',
'크리뎀+':'Daune Critic+',
// --- CAT-84/85/86: affix names + implicit + legendary ---
'지속의':'Rezistență',
'마나의':'Mana',
'원소수호의':'Gardă Elem.',
'행운의':'Noroc',
'근성의':'Tenacitate',
'풍요의':'Abundență',
'약자포식의':'Prădător',
'만혈의':'Viață Plină',
'사선의':'Viață Scăzută',
'처형의':'Execuție',
'근접살의':'Daune Corp',
'원거리의':'Distanță',
'경직파의':'Sparge Postură',
'동파의':'Lovitură Îngheț',
'연소의':'Ardere',
'맹독살의':'Ucigaș Venin',
'저주살의':'Ucigaș Blestem',
'구속의':'Legare',
'왕살의':'Ucigaș Șef',
'정예살의':'Ucigaș Elită',
'군살의':'Ucigaș Gloată',
'선제의':'Prima Lovitură',
'흡혈의':'Vampirism',
'흡마의':'Scurgere Mana',
'흡정의':'Scurgere ST',
'타격재생의':'Regen. la Hit',
'처치회복의':'Recuperare la Kill',
'처치흡마의':'Scurgere Mana la Kill',
'처치활력의':'ST la Kill',
'처치폭발의':'Explozie la Kill',
'처치질주의':'Sprint la Kill',
'건강방어의':'Apărare Sănătos',
'중상보호의':'Scut Rănit',
'위기질주의':'Sprint Criză',
'지속피해방어의':'Red. Daune DoT',
'왕피해방어의':'Red. Daune Șef',
'근접방어의':'Red. Corp',
'원거리방어의':'Red. Distanță',
'처치생명의':'HP la Kill',
'처치수호의':'Scut la Kill',
'화염강화의':'Amplif. Foc',
'화염관통의':'Penetrare Foc',
'발화의':'Aprindere',
'화염폭발의':'Explozie Foc',
'맹화의':'Flacără Furie',
'화염의힘':'Putere Foc',
'빙결강화의':'Amplif. Gheață',
'빙결관통의':'Penetrare Gheață',
'동결의':'Înghețare',
'빙결폭발의':'Explozie Gheață',
'영빙의':'Permafrost',
'빙결의힘':'Putere Gheață',
'뇌전강화의':'Amplif. Fulger',
'뇌전관통의':'Penetrare Fulger',
'감전의':'Electrocutare',
'뇌전폭발의':'Explozie Fulger',
'낙뢰의':'Trăsnet',
'뇌전의힘':'Putere Fulger',
'암흑강화의':'Amplif. Întuneric',
'암흑관통의':'Penetrare Întuneric',
'침식의':'Coroziune',
'암흑폭발의':'Explozie Întuneric',
'심연의':'Abis',
'암흑의힘':'Putere Întuneric',
'맹독강화의':'Amplif. Venin',
'독관통의':'Penetrare Otravă',
'중독의':'Otrăvire',
'독폭발의':'Explozie Otravă',
'맹독지속의':'Durată Venin',
'독의힘':'Putere Otravă',
'격투의':'Corp la Corp',
'원사의':'Tras Distanță',
'주술의':'Vrajă',
'광선의':'Rază',
'탄도의':'Balistic',
'확산의':'Rază AoE',
'근접회심의':'Critic Corp',
'마법회심의':'Critic Magie',
'사격회심의':'Critic Distanță',
'근접쾌속의':'Viteză Corp',
'사격쾌속의':'Viteză Distanță',
'영창의':'Incantare',
'전속성관통의':'Pen. Toate Elem.',
'쉴드파괴의':'Sparge Scut',
'갑옷분쇄의':'Sfărâmare Armură',
'탄속의':'Viteză Proiectil',
'화구발사의':'Lansare Minge Foc',
'연쇄뇌격의':'Fulger în Lanț',
'동결타의':'Lovitură Îngheț',
'경직타의':'Lovitură Postură',
'독침의':'Ac Otrăvit',
'출혈의':'Sângerare',
'약화의':'Slăbire',
'둔화의':'Încetinire',
'표적의':'Marcare',
'회심폭발의':'Explozie Critic',
'회심연쇄의':'Lanț Critic',
'회심빙결의':'Îngheț Critic',
'회심치유의':'Vindecare Critic',
'회심영력의':'Mana Critic',
'회심수호의':'Scut Critic',
'피격강화의':'Amplif. Hit',
'반격가시의':'Țepi Contraatac',
'빙결파동의':'Undă Gheață',
'암흑보호의':'Scut Întuneric',
'치유파동의':'Undă Vindecare',
'시체폭발의':'Explozie Cadavru',
'회피반격의':'Contraatac Eschivă',
'패링폭파의':'Explozie Parare',
'블록치유의':'Vindecare Blocare',
'블록영력의':'Mana Blocare',
'회전참강화':'Amplif. Vârtej',
'옴니빔강화':'Amplif. Rază Omni',
'화구강화':'Amplif. Minge Foc',
'미사일강화':'Amplif. Rachetă',
'청탄강화':'Amplif. Glonț Albastru',
'폭렬탄강화':'Amplif. Împușcătură Explozivă',
'지옥광선강화':'Amplif. Rază Infernală',
'악의폭풍강화':'Amplif. Furtună Malicie',
'연쇄참강화':'Amplif. Tăietură Lanț',
'거인강타강화':'Amplif. Lovitură Gigant',
'유령보행강화':'Amplif. Pas Fantomă',
'악의박격강화':'Amplif. Mortier Malicie',
'화염오라강화':'Amplif. Aură Foc',
'빙구강화':'Amplif. Sferă Gheață',
'화염빔강화':'Amplif. Rază Foc',
'악의사냥강화':'Amplif. Vânătoare Malicie',
'암흑기둥강화':'Amplif. Pilon Întuneric',
'역병강화':'Amplif. Ciumă',
'가시오라강화':'Amplif. Aură Țepi',
'연쇄돌격강화':'Amplif. Asalt Lanț',
'회피의':'Eschivare',
'회피쿨감의':'Red. CD Eschivare',
'수호력의':'Putere Scut',
'수호재생의':'Regen. Scut',
'수호쿨감의':'Red. CD Scut',
'재생력의':'Putere Regen.',
'활력재생의':'Regen. ST',
'마력재생의':'Regen. Mana',
'화염보호의':'Scut Foc',
'빙결보호의':'Scut Gheață',
'뇌전보호의':'Scut Fulger',
'해독의':'Antidot',
'만물보호의':'Protecție Totală',
'정예보호의':'Scut Elită',
'경직저항의':'Rez. Postură',
'빙결저항의':'Rez. Îngheț',
'화상저항의':'Rez. Arsură',
'감속저항의':'Rez. Încetinire',
'넉백저항의':'Rez. Respingere',
'돌진거리의':'Distanță Dash',
'돌진쿨감의':'Red. CD Dash',
'전투질주의':'Sprint Luptă',
'평화질주의':'Sprint Pace',
'습득범위의':'Rază Colectare',
'힘의':'Forță',
'민첩의':'Dexteritate',
'지능의':'Inteligență',
'만능의':'Versatil',
'지구력의':'Rezistență Max',
'마나력의':'Putere Mana',
'타격자원의':'Resursă la Hit',
'화염한계의':'Limită Foc',
'빙결한계의':'Limită Gheață',
'뇌전한계의':'Limită Fulger',
'암흑한계의':'Limită Întuneric',
'독한계의':'Limită Otravă',
'스킬쿨감의':'Red. CD Abilitate',
'물약쿨감의':'Red. CD Poțiune',
'장인의':'Meșteșug',
'탐욕의':'Lăcomie',
'수련의':'Antrenament',
'수집의':'Colectare',
'악마의힘':'Putere Demonică',
'악마보호의':'Scut Demonic',
'영혼수확의':'Recoltare Suflete',
'생명흡수의':'Absorb. Viață',
'과치유수호의':'Scut Supravindecare',
'만마력의':'Daune Mana Plină',
'이동방어의':'Red. Mișcare',
'정지공세의':'Amplif. Static',
'회피공세의':'Amplif. Post-Eschivare',
'패링보호의':'Scut Parare',
'콤보폭발의':'Explozie Combo',
'물리타격의':'Lovitură Fizică',
'화염타격의':'Lovitură Foc',
'빙결타격의':'Lovitură Gheață',
'뇌전타격의':'Lovitură Fulger',
'암흑타격의':'Lovitură Întuneric',
'독타격의':'Lovitură Otravă',
'최소공격의':'ATK Min.',
'최대공격의':'ATK Max.',
'전투력의':'Putere Luptă',
'무기사거리의':'Rază Armă',
'활사거리의':'Rază Arc',
'이중타의':'Lovitură Dublă',
'다중발사의':'Foc Multiplu',
'관통횟수의':'Penetrare Nr.',
'관통유지의':'Menținere Penetrare',
'연쇄유지의':'Menținere Lanț',
'범위확장의':'Rază Splash',
'범위피해의':'Daune Splash',
'돌진공격의':'Atac Dash',
'반격공격의':'Atac Contraatac',
'후방타의':'Lovitură Spate',
'침식가속의':'Viteză Coroziune',
'출혈지속의':'Durată Sângerare',
'마법타격의':'Lovitură Magică',
'주문증폭의':'Amplif. Vrajă',
'연살뎀의':'Daune Lanț Kill',
'연살속의':'Viteză Lanț Kill',
'기세의':'Avânt',
'정지공격의':'Atac Static',
'이동공격의':'Atac în Mișcare',
'패링공세의':'Amplif. Post-Parare',
'임사폭발의':'Explozie Aproape Moarte',
'만기력공의':'Atac ST Plin',
'만마력공의':'Atac Mana Plin',
'신선처치의':'Kill Rapid',
'경직연장의':'Extindere Postură',
'빙결연장의':'Extindere Îngheț',
'둔화강화의':'Amplif. Încetinire',
'독중첩의':'Stivuire Otravă',
'출혈중첩의':'Stivuire Sângerare',
'발화강화의':'Amplif. Aprindere',
'동상강화의':'Amplif. Degerătură',
'감전강화의':'Amplif. Electrocutare',
'사선회심의':'Critic HP Scăzut',
'갑옷강화의':'Amplif. Armură',
'블록흡수의':'Absorb. Blocare',
'방패타격의':'Lovitură Scut',
'방패경직의':'Postură Scut',
'격투속의':'Viteză Corp la Corp',
'격투회심의':'Critic Corp la Corp',
'격투경직의':'Postură Corp la Corp',
'하반재생의':'Regen. Picioare',
'CC단축의':'Red. Durată CC',
'돌진타의':'Lovitură Dash',
'돌진범위의':'AoE Dash',
'은신질주의':'Sprint Ascuns',
'회피감쇠의':'Red. Eschivare',
'속성감쇠의':'Red. Elem.',
'마나왕관의':'Coroană Mana',
'시전왕관의':'Coroană Incantare',
'쿨감왕관의':'Coroană CD',
'경험왕관의':'Coroană EXP',
'공생의':'Simbioză',
'수질의':'Corp-Suflet',
'회심흡의':'Scurgere Critic',
'체마의':'HP-Mana',
'체기의':'HP-ST',
'마기의':'Mana-ST',
'전재생의':'Regen. Totală',
'힘민의':'FOR-DEX',
'힘지의':'FOR-INT',
'민지의':'DEX-INT',
'운근의':'Noroc-Tenacitate',
'수확의':'Recoltare',
'빙화의':'Gheață-Foc',
'뇌암의':'Fulger-Întuneric',
'근마의':'Lamă-Magie',
'속성침식의':'Coroziune Elem.',
'화염반지의':'Inel Foc',
'빙결반지의':'Inel Gheață',
'뇌전반지의':'Inel Fulger',
'암흑반지의':'Inel Întuneric',
'독반지의':'Inel Otravă',
'콤보반지의':'Inel Combo',
'처치마나의':'Mana la Kill',
'관통반지의':'Inel Penetrare',
'만능목걸이의':'Colier Universal',
'회심목걸이의':'Colier Critic',
'관통목걸이의':'Colier Penetrare',
'스킬목걸이의':'Colier Abilitate',
'콤보한계의':'Combo Max',
'처치치유의':'Vindecare la Kill',
'지구벨트의':'Centură ST',
'포션벨트의':'Centură Poțiune',
'활력벨트의':'Centură Vitalitate',
'탐욕벨트의':'Centură Lăcomie',
'마나띠의':'Bandă Mana',
'시전띠의':'Bandă Incantare',
'마력띠의':'Bandă Arcanică',
'주술띠의':'Bandă Vrajă',
'속성띠의':'Bandă Elem.',
'전사의힘':'Putere Războinic',
'전사생명의':'Viață Războinic',
'전사흡혈의':'Vampirism Războinic',
'전사인내의':'Postură Războinic',
'마법사의힘':'Putere Mag',
'마법사마나의':'Mana Mag',
'마법사수호의':'Scut Mag',
'마법사속성의':'Elem. Mag',
'궁수의힘':'Putere Arcaș',
'궁수사거리의':'Rază Arcaș',
'궁수관통의':'Penetrare Arcaș',
'궁수질주의':'Sprint Arcaș',
'탱크생명의':'Viață Tank',
'탱크방어의':'Apărare Tank',
'탱크블록의':'Blocare Tank',
'탱크가시의':'Țepi Tank',
'암살회심의':'Critic Asasin',
'암살후방의':'Spate Asasin',
'암살독의':'Otravă Asasin',
'암살회피의':'Eschivare Asasin',
'종결자의':'Finalizatorul',
'생존자의':'Supraviețuitorul',
'종결수호의':'Scut Final',
'종결회심의':'Critic Final',
'종결공격의':'Atac Final',
'종결저항의':'Rez. Finală',
'종결파괴의':'Distrugere Finală',
'종결보호의':'Protecție Finală',
'종결흡혈의':'Vampirism Final',
'종결인내의':'Postură Finală',
'종결쿨감의':'Red. CD Final',
'종결경험의':'EXP Final',
'종결약탈의':'Jaf Final',
'종결악의의':'Malicie Finală',
'종결힘의':'FOR Final',
'종결민첩의':'DEX Final',
'종결지능의':'INT Final',
'종결행운의':'LCK Final',
'종결근성의':'Tenacitate Finală',
'종결연살의':'Lanț Kill Final',
'건강공세의':'Ofensivă Sănătos',
'중상폭발의':'Explozie Rănit',
'중상흡혈의':'Vampirism Rănit',
'토벌의':'Avangardă',
'정예토벌의':'Avangardă Elită',
'극대화의':'Maximizare',
'공격력 +X%':'ATK +X%',
'관통 확률 +X%':'Șansă Penetrare +X%',
'방어율 +X%':'Rată Blocare +X%',
'물리 피해감소 +X%':'Red. Daune Fiz. +X%',
'최대 HP +X':'HP Max +X',
'공격속도 +X%':'Viteză Atac +X%',
'상태이상 저항 +X%':'Rez. Stări +X%',
'이동속도 +X%':'Viteză Mișcare +X%',
'원소 저항 +X%':'Rez. Elem. +X%',
'최대 HP +X%':'HP Max +X%',
'회피 쿨다운 -X%':'CD Eschivare -X%',
'물약 쿨다운 -X%':'CD Poțiune -X%',
'부활력 +X%':'Putere Înviere +X%',
'마법 데미지 +X%':'Daune Magie +X%',
'전설 특수':'Special Legendar',
'유니크 특수':'Special Unic',
'5타 콤보 완성 시 데빌포스 20% 즉시 충전':'5 lovituri combo: DevilForce +20% instant',
'처치 시 이속 +40%(3초) + 다음 공격 크리 보장':'Kill: Viteză +40%(3s) + următor atac garantat Critic',
'스태거 발동 시 범위 충격파 (ATK×120%)':'Clătinare: undă de șoc AoE (ATK×120%)',
'스태거 발동 시 범위 충격파 (ATK×100%)':'Clătinare: undă de șoc AoE (ATK×100%)',
'강타 시 적 넉백 거리 2배 + 벽충돌 추가뎀':'Lovitură grea: Respingere ×2 + daune coliziune zid',
'출혈 대상 크리 시 잔여 DoT×300% 즉시 폭발':'Critic vs Sângerare: DoT rămas ×300% explozie instant',
'사슬 착지 타격 수만큼 데미지 +20% 중첩(최대5)':'Javelin landing hits: stack +20% DMG (max 5)',
'치명타 시 추가 투사체 1발 발사':'Critic: lansează 1 proiectil suplimentar',
'패리 성공 시 반격 데미지 ×2':'Parare: daune contraatac ×2',
'피격 시 3초 쿨로 HP 5% 즉시 회복':'Lovit (CD 3s): restaurează 5% HP instant',
'스킬 사용 시 20% 확률로 쿨다운 미소모':'Abilitate: 20% șansă fără CD consumat',
'공격속도 +20% + 기본공격에 랜덤 원소 추가':'Viteză Atac +20% + atacuri de bază cu element aleator',
'이동 중 지속 HP 재생 (초당 HP의 1%)':'În mișcare: regen. HP (1% HP/s)',
'회피 직후 첫 공격 데미지 +80%':'Prima lovitură după Eschivare: Daune +80%',
'패리 타이밍 판정 +50% 확대':'Fereastra de timp Parare +50% extinsă',
'원소 반응 발동 시 추가 폭발 (ATK×80%)':'Reacție Elem.: explozie bonus (ATK×80%)',
'처치 시 데빌포스 5% 회복':'Kill: restaurează 5% DevilForce',
'HP 50% 이하 시 전 스킬 쿨다운 -30%':'Sub 50% HP: toate CD abilități -30%',
'물약 사용 시 5초간 피해 +15%':'Poțiune: Daune +15% pentru 5s',
'암묵':'Implicit',
'낡은 악마의 팔찌':'Brățară Demonică Uzată',
'흑요석 악마의 팔찌':'Brățară Demonică Obsidian',
'미스릴 악마의 팔찌':'Brățară Demonică Mitril',
'낡은 생명의 팔찌':'Brățară Vieții Uzată',
'확인':'Confirmă',
'조작법':'Comenzi',
'살아남으려면 익혀라':'Însușește-le ca să supraviețuiești',
'전투':'Luptă',
'이동 / 상호작용':'Mișcare / Interacțiune',
'메뉴':'Meniu',
'시스템':'Sistem',
'아무 키를 눌러 시작':'Apasă orice tastă pentru start',
'스테이지':'Etapă',
'💪 힘 (STR)':'💪 FOR',
'🏹 민첩 (DEX)':'🏹 DEX',
'🔮 지능 (INT)':'🔮 INT',
'🍀 행운 (LCK)':'🍀 NOR',
'⚔️ 맹공':'⚔️ Asalt',
'🔱 돌파':'🔱 Străpungere',
'⚡ 반격':'⚡ Represalii',
'🔮 마력폭주':'🔮 Explozie Arcană',
'🎯 정밀사격':'🎯 Tir Precis',
'🛡 수호신':'🛡 Spirit Gardian',
'💚 회복력':'💚 Recuperare',
'💥 급소':'💥 Lovitură Vitală',
'🎁 약탈':'🎁 Jaf',
'🔱 관통':'🔱 Penetrare',
'💠 마력회복':'💠 Recup. Mana',
'🏹 쇠뇌력':'🏹 Măiestrie Arbaletă',
'⚔ 광전사':'⚔ Berserker',
'🎯 추적자':'🎯 Urmăritor',
'🗡 물리관통':'🗡 Pen. Fizică',
'🔮 마법관통':'🔮 Pen. Magică',
'🌿 풍요':'🌿 Abundență',
'🐺 약자포식':'🐺 Prădător',
'☠ 침식':'☠ Coroziune',
'💎 마력그릇':'💎 Recipient Mana',
'💪 힘의그릇':'💪 Recipient ST',
'👿 악의중독':'👿 Dependent Malicie',
'❤️ 강인':'❤️ Fortitudine',
'🛡 철벽':'🛡 Zid de Fier',
'🎯 사냥꾼':'🎯 Vânător',
'✦ 인간성':'✦ Umanitate',
'☠ 악마성':'☠ Demonic',
'1. 악의폭풍':'1. Furtună Malicie',
'2. 칼날 계열':'2. Abilități Lamă',
'3. 역병 확장':'3. Extindere Ciumă',
'4. 이동스킬 마스터':'4. Maestru Mișcare',
'5. 사슬 확장':'5. Extindere Lanț',
'6. 💀 필살기 선택':'6. 💀 Alege Ultim',
'7. 멸살+만화+원소+전격이동':'7. Rază+Baraj+Elem.+Blink',
'8. 회전참+기폭+대왕':'8. Vârtej+Det.+Gigant',
'9. 방패 합체':'9. Fuziune Scut',
'10. 해골무덤+악의폭풍':'10. Mormânt+Furtună Malicie',
'11. 폭풍소환+얼음보주':'11. Furtună+Sferă Gheață',
'12. 뇌전걸음':'12. Pas Fulger',
'13. 신성 영역':'13. Domeniu Sacru',
'14. 6단합체: 폭풍빔':'14. 6-Fuziune: Rază Furtună',
'15. 신성+빙결':'15. Sacru+Gheață',
'16. 암흑+가시+대왕2':'16. Întuneric+Țepi+Gigant2',
'17. 사슬 최종':'17. Lanț Final',
'⚡ 이동스킬':'⚡ Mișcare',
'⚔️ 물리/근접/분노':'⚔️ Fizic/Corp la corp/Furie',
'🛡️ 방어':'🛡️ Apărare',
'🔮 마법':'🔮 Magie',
'🏹 석궁/관통':'🏹 Arbaletă/Penetrare',
'⚙️ 영역':'⚙️ Domeniu',
'💀 필살기':'💀 Ultim',
'⭐ 추천':'⭐ Recomandat',
'⚔ 공격':'⚔ Atac',
'🛡 방어':'🛡 Apărare',
'⚙ 특수':'⚙ Special',
'STEAM 위시리스트':'Lista de dorințe Steam',
'STEAM 위시리스트로 응원해 주세요!':'Susține-ne adăugând jocul pe lista de dorințe Steam!',
'⚔ 난타!':'⚔ Baraj!',
'⚡ 연격!':'⚡ Combo Rapid!',
'더블탭 or Shift+방향키! 전격이동으로 탈출해!':'Dublu tap sau Shift+Direcție! Dash să scapi!',
'데모 종료':'Sfârşitul Demo-ului',
'독사':'Șarpe veninos',
'방어↓':'APR↓',
'여기까지 데모입니다. 정식 출시를 기대해주세요!':'Acesta este sfârșitul demo-ului. Abia așteptăm lansarea completă!',
'프레임 표시 (FPS)':'Arată FPS',
'흑요염 파괴자':'Distrugătorul Flăcărilor de Obsidian',
'🌀 휘두르기!':'🌀 Rotire!',
'🐍 독사!':'🐍 Șarpe veninos!',
'💥 강타!':'💥 Lovitură!',
'💥 공성유령 폭발!':'💥 Explozia Fantomei Asediului!',
'👻 공성유령!':'👻 Fantoma Asediului!',
'목표 달성!':'Obiectiv atins!',
'악의 고갈':'Răutate epuizată',
'시도':'Încercări',
'소비':'Cheltuit',
'목표':'Obiectiv',
'미달':'Neatins',
'악의를 더 모아 재시도하세요':'Adună mai multă Răutate și încearcă din nou',
'습득':'Învață',
'레벨업':'Nivel+',
'⚡기동+10':'⚡Dash+10',
'게임 종료':'Ieșire din joc',
'영역스킬':'Abilitate de zonă',
'석궁자동':'Arbaletă auto',
'데빌포스 흡수 (HP→에너지)':'Forță Demonică (HP→Energie)',
'스킬슬롯 5':'Slot abilitate 5',
'CT스킬 (유령걸음/얼음보주)':'Ab. CT (Pas Fantomă/Sferă de Gheață)',
'스킬 (전투스킬 습득)':'Abilități (Luptă)',
'대장간 (제작)':'Fierărie (Fabricare)',
'클릭하여 계속':'Click pentru a continua',
'클릭하여 시작':'Click pentru a începe',
'SPACE 길게 눌러 건너뛰기':'Ține SPACE pentru a sări',
'패링·보호막':'Parare / Scut',
'돌진 (적을 관통, 무적)':'Asalt (străpunge inamicii, invincibil)',
'대왕치기 (광역 기절)':'Lovitură Gigantică (asomare zonală)',
'가시덫 (슬로우+출혈)':'Capcană cu spini (încetinire+sângerare)',
'회복의 영역 (리젠 장판)':'Domeniu sacru (zonă regen)',
'얼음보주 (무적+빙결)':'Sferă de gheață (invincibil+înghețare)',
'석궁 자동발사':'Arbaletă automată',
'선택 스킬 슬롯':'Sloturi abilități',
'(펫이 자동 수거)':'(animalul colectează auto)',
'물약은 설정한 HP% 이하 시 자동 사용':'Poțiunile se folosesc auto când HP scade sub % setat',
'💡 Shift로 사슬 돌진! 적을 관통하며 무적':'💡 Shift pentru asalt! Străpunge inamicii, invincibil',
'💡 Q로 보호막 발동 — 기본 흡수율 70%, 패링 성공 시 HP/ST/MP/기동게이지 회복':'💡 Q pentru Scut — absorbție 70%, parare recuperează HP/ST/MP/Încărcare',
'💡 속성 약점을 찌르면 데미지 2배!':'💡 Lovește slăbiciunea elementală — 2x daune!',
'💡 ESC로 설정 — 난이도, 자동물약 조절':'💡 ESC setări — dificultate, poțiuni auto',
'💡 대왕치기로 기절 회복 + 포이즈를 깎아 그로기 유발!':'💡 Lovitură Gigantică: recuperare asomare + sparge postura pentru groggy!',
'💡 그로기 상태에서 기본 데미지 1.5배':'💡 Stare groggy = 1.5x daune de bază',
'💡 탄막은 패링하면 되돌려 보낸다!':'💡 Parează gloanțele — se întorc!',
'💡 Ctrl 얼음보주 — 무적! 재입력으로 즉시 폭파':'💡 Ctrl Sferă de gheață — invincibil! Apasă din nou pentru a sparge',
'💡 합체 스킬로 더 강한 공격을 만들어보세요':'💡 Fuzionează abilitățile pentru atacuri mai puternice!',
'💡 엘리트 몬스터는 특수 능력을 가지고 있다':'💡 Monștrii de elită au abilități speciale',
'💡 보스의 패턴을 읽고 패링 타이밍을 잡아라':'💡 Citește tiparele bossului, nimerește timing-ul de parare',
'💡 인벤토리(TAB)에서 장비를 비교하고 장착':'💡 Inventar(TAB) — compară și echipează',
'💡 대장간에서 장비를 강화하고 분해하세요':'💡 Îmbunătățește și dezmembrează echipamentul la fierărie',
'💡 R키를 누르면 펫이 아이템을 자동으로 주워줍니다':'💡 Apasă R — animalul tău colectează obiecte automat',
'💡 물약은 설정한 HP% 이하에서 자동 사용':'💡 Poțiunile se folosesc auto când HP scade sub % setat',
'💡 집중 스킬(홀드)은 시전 중 기절 면역!':'💡 Abilitățile canalizate oferă imunitate la asomare!',
'🎮 전체 조작 가이드':'🎮 Ghid Comenzi',
'무기 공격 (좌클릭)':'Atac armă (Stânga)',
'B슬롯 스킬 (Space)':'Ab. Slot B (Space)',
'우클릭 스킬 (RMB)':'Ab. Clic Dreapta (RMB)',
'패링 (Q)':'Parare (Q)',
'돌진/사슬 (Shift)':'Dash/Lanț (Shift)',
'Ctrl 스킬':'Ab. Ctrl',
'필살기 (Z)':'Supremă (Z)',
'F 슬롯 스킬':'Ab. Slot F',
'스킬 슬롯 1':'Slot 1',
'스킬 슬롯 2':'Slot 2',
'스킬 슬롯 3':'Slot 3',
'스킬 슬롯 4':'Slot 4',
'처형 (X)':'Execuție (X)',
'방향 + 마법 자동발동 (E)':'Dir. + Magie auto (E)',
'마법 (E)':'Magie (E)',
'줍기 (R)':'Ridică (R)',
'스킬창':'Abilități',
'이동 (WASD)':'Mișcare (WASD)',
'👻 유령!':'👻 Fantomă!',
'🦴 해골무덤!':'🦴 Mormânt de oase!',
'💥 유령총 폭발!':'💥 Explozie Pistol Fantomă!',
'탈취!':'Furt!',
' 스킬 해제':' Elimină abilitate',
' 자동 OFF':' Auto OPRIT',
' 자동 ON':' Auto PORNIT',
'B슬롯 스킬':'Abilitate slot B',
'☠중독!':'☠ Otrăvire!',
'✟ 신의영역!':'✟ Domeniu Divin!',
'❄ 얼음송곳!':'❄ Ac de Gheață!',
'⟨ 키 입력... ⟩':'⟨ Apasă tasta... ⟩',
'고정':'Fix',
'다음 구역':'Zona următoare',
'돌진/사슬':'Asalt/Lanț',
'쓰러짐...':'Cădere...',
'우클릭 스킬':'Abilitate clic dreapta',
'줍기':'Ridicare',
'패드 키 초기화':'Resetare taste gamepad',
'패드 키 초기화 완료':'Taste gamepad resetate',
'패링':'Parare',
'🎮 게임패드 버튼 설정':'🎮 Setări butoane gamepad',
'🎮 패드 연결됨':'🎮 Gamepad conectat',
'🎮 패드 연결 끊김':'🎮 Gamepad deconectat',
'💀 ':'💀 ',
'🔥부활!':'🔥 Înviere!',
'🔥분노 ':'🔥 Furie ',
'🔥분노+':'🔥Furie+',
'🚀 미사일!':'🚀 Rachetă!',
// --- Pet dialogue: death screen (death_dual) ---
'…죽었군. 하지만 여신은 아직 널 안 놓았어.':"…Ai murit. Dar zeița încă nu ți-a dat drumul.",
'괜찮아?! 다시 일어설 수 있어, 포기하지 마!':"Ești bine?! Te poți ridica, nu renunța!",
'…한 끗이었어. 아까워 말고 다시 해.':"…La un pas. Nu regreta — încearcă din nou.",
'아아! 조금만 더였는데!! 다음엔 진짜 잡자!':"Aah! Mai era puțin!! Data viitoare chiar îl prindem!",
'보스는 원래 이렇게 죽이는 거다. 여러 번.':"Așa se omoară un boss. Iar și iar.",
'저 녀석 패턴 봤지?! 다음엔 안 당해!':"I-ai văzut tiparul, nu?! Data viitoare nu te mai prinde!",
'…이름값 하는 놈이었군.':"…Ăsta chiar și-a meritat numele.",
'레어몹한테?! 센 만큼 좋은 걸 떨군다니까!':"De la un monstru rar?! Cu cât e mai tare, cu atât lasă lucruri mai bune!",
'잡졸한테 죽다니. …방심했군.':"Ucis de un pârlit. …Ai lăsat garda jos.",
'저런 애들한테?! 정신 좀 차려어!':"De la ăștia?! Adună-te odată!",
'…발밑을 봐. 서 있던 자리가 널 죽였어.':"…Uită-te la picioare. Pământul pe care stăteai te-a ucis.",
'장판 위에 서 있었잖아! 빨리 빠졌어야지!':"Stăteai în zonă! Trebuia să ieși!",
'탄을 못 읽었어. 눈을 크게 떠.':"N-ai citit proiectilul. Deschide bine ochii.",
'날아오는 거 봤어야지! 패링이든 회피든!':"Trebuia să-l vezi venind! Parează sau ferește-te!",
'잡히면 끝이야. 거리를 배워.':"Odată prins, s-a terminat. Învață distanța.",
'붙잡혔어! 다음엔 옆으로 굴러!':"Ai fost prins! Data viitoare rostogolește-te în lateral!",
'…이 챕터가 네 무덤이 되고 있다.':"…Capitolul ăsta devine mormântul tău.",
'여기서 또?! 이 구간 진짜 조심해!':"Iar aici?! Fii foarte atent pe porțiunea asta!",
'열 번. …죽는 것도 재능이군.':"De zece ori. …Și moartea e un talent.",
'또?! 우리 진짜 같이 좀 살자아!':"Iar?! Hai să supraviețuim odată împreună, te rog!",
'…또야. 같은 실수는 그만.':"…Iar. Gata cu aceeași greșeală.",
'다섯 번째야! 패턴 좀 외워줘!':"E a cincea oară! Învață odată tiparul!",
'잘 나가다 한 방에. …끝까지 방심 마.':"Mergeai bine, apoi o lovitură. …Nu lăsa garda jos până la capăt.",
'그렇게 잘하다가!! 아까워 죽겠어!':"Te descurcai atât de bine!! Ce păcat!",
'…지옥에 망자 하나 더 늘릴 셈이야?':"…Vrei să mai adaugi un cadavru în Iad?",
'그런 소리 마! 얜 아직 안 죽었어! 일어나!':"Nu spune asta! Ăsta încă n-a murit! Ridică-te!",
'…여왕님이 실망하시겠군.':"…Regina va fi dezamăgită.",
'실망은 무슨! 다시 일어나면 되잖아, 얼른!':"Ce dezamăgire! Doar ridică-te la loc — haide!",
'잠은 집에 가서 자. …일어나.':"Dormi acasă. …Ridică-te.",
'여기서 자면 진짜 집 못 가! 얼른 일어나!':"Dacă adormi aici, nu mai ajungi acasă! Ridică-te!",
'여기서 포기하면… 누가 가족의 원수를 갚지?':"Dacă renunți aici… cine îți răzbună familia?",
'우리가 있잖아! 다시 일어나 끝까지 가!':"Ne ai pe noi! Ridică-te și du-o până la capăt!",
'네가 멈추면, 가족을 위해 싸울 자는 없어.':"Dacă te oprești, nu mai rămâne nimeni să lupte pentru familia ta.",
'너밖에 없어! 여기서 주저앉지 마!':"Doar tu ai rămas! Nu te prăbuși aici!",
'…복수는 살아남은 자만이 한다.':"…Doar cel care supraviețuiește se răzbună.",
'죽은 채로는 아무것도 못 갚아! 일어나!':"Mort nu poți plăti nimic! Ridică-te!",
'가족의 얼굴을 떠올려. 그게 네가 일어날 이유야.':"Amintește-ți chipurile familiei. Ăsta e motivul tău să te ridici.",
'잊지 마! 우리가 왜 여기 있는지!':"Nu uita de ce suntem aici!",
'포기하는 건… 결국 습관이 돼.':"Renunțarea… devine până la urmă un obicei.",
'한 번 포기하면 계속 포기하게 돼! 여기서 끊어!':"Renunți o dată și tot renunți! Oprește-o aici!",
'일어나. 복수만이 정의다.':"Ridică-te. Răzbunarea e singura dreptate.",
'맞아! 여기서 끝낼 순 없어! 일어나!':"Așa e! Nu se poate termina aici! Ridică-te!",
'썩은 숲이 첫 무덤이라니. 일어나.':"Pădurea Putredă să-ți fie primul mormânt? Ridică-te.",
'아직 시작인데! 다시 가자!':"Abia e începutul! Hai din nou!",
'벌레 밥이 될 뻔했군.':"Era să ajungi hrană pentru viermi.",
'으으 여기서 죽기 싫어! 다시!':"Uh, nu vreau să mor aici! Din nou!",
'얼어붙기 전에 일어나.':"Ridică-te înainte să îngheți.",
'추운 데서 쓰러지지 마! 얼른!':"Nu te prăbuși în frig! Repede!",
'잿더미가 되기 전에.':"Înainte să te faci scrum.",
'뜨거운 데서 눕지 좀 마아!':"Nu te mai întinde pe atâta căldură!",
'수에 삼켜졌군. 다시.':"Înghițit de mulțime. Din nou.",
'너무 많았어! 이번엔 뭉칠 때 노리자!':"Erau prea mulți! Data viitoare lovim când se strâng grămadă!",
'사도들이 널 비웃고 있어.':"Apostolii râd de tine.",
'여기 진짜 까다로워! 정신 바짝!':"Locul ăsta chiar e complicat! Rămâi concentrat!",
'지옥성이 널 붙잡았어. 놓지 않게 해.':"Castelul Iadului te-a prins. Nu-l lăsa să te țină.",
'최종장이야! 여기서 무너지면 안 돼!':"E capitolul final! Nu te poți nărui aici!",
};

const _RO_PFX={
'녹슨':'Ruginit','강철':'Oțel','흑요석':'Obsidian','미스릴':'Mithril','심판의':'Judecată','천벌의':'Mânie Divină','파멸의':'Distrugere','불꽃':'Flacără','화염':'Infern','염화':'Foc Infernal','지옥불':'Flacără Infernală','지옥화':'Flacără Infernală','지옥':'Flacără Infernală','멸화의':'Anihilant','냉기':'Ger','빙결':'Înghețat','빙하':'Glaciar','서리의':'Chiciură','서리':'Chiciură','영겁빙':'Gheață Eternă','그림자':'Umbră','암흑':'Întuneric','심연':'Abisal','나락의':'Submundan','나락':'Submundan','무간의':'Vid','전기':'Scânteie','낙뢰':'Tunet','암전':'Fulger','뇌신의':'Zeul Tunetului','뇌신':'Zeul Tunetului','만뢰의':'O Mie de Tunete','축복':'Binecuvântat','성광':'Lumină Sacră','신성':'Sacru','천사의':'Angelic','신벌의':'Judecată Divină','낡은':'Uzat','천':'Pânză','가죽':'Piele','강철사':'Țesătură Oțel','은':'Argint','은사':'Fir de Argint','화염의':'Infern','빙결의':'Înghețat','암흑의':'Întuneric','암전의':'Fulger'
};
const _RO_BASE={
'대검':'Spadă','석궁':'Arbaletă','연사석궁':'Arbaletă Repetitivă','마력석궁':'Arbaletă Arcană','견갑':'Scut','대견갑':'Scut Mare','전투화':'Cizme Luptă','갑옷':'Armură','갑주':'Armură','왕관':'Coroană','장갑':'Mănuși','건틀릿':'Mănuși Blindate','바지':'Pantaloni','각반':'Jambiere','허리띠':'Centură','벨트':'Centură','부적':'Talisman','목걸이':'Colier','반지':'Inel','망토':'Mantie','팔찌':'Brățară','귀걸이':'Cercel',
'투구 착용':'Coif echipat',
'투구 해제':'Coif scos',
'✟ 신성한 결계!':'✟ Barieră Sacră!',
'혼돈의 투구':'Coiful Haosului',
'전지전능의 투구':'Coiful Atotputerniciei',
'방향키 연타':'Apasă rapid săgețile',
'까마귀와 고양이가 아이템을 주워준다. 수거 범위 안이면.':'Corbul și pisica ridică obiecte. Dacă în raza de colectare.',
'Ctrl 얼음보주로 탈출! 없으면 방향키 연타!':'Ctrl — Orb de Gheață să scapi! Nu ai? Apasă săgețile!',
'💥 폭발 허수아비!':'💥 Sperietoare Explozivă!',
'👻 유령총!':'👻 Pistol Fantomă!',
' 뎀 ':' DAN ',
'기절!  ':'Amețit!  ',
'투구':'Coif',
'악마팔찌':'Brățară Demonică',
'생명팔찌':'Brățară a Vieții',
'얼음송곳':'Țepușă de gheață',
'⚡ 뇌전추격자!':'⚡ Vânătorul de fulgere!',
'대왕치기 (분노폭발, 광역 기절)':'Lovitură gigantică (Explozie de furie, Asomare pe zonă)',
'✦ 유니크 공유!':'✦ Împărtășire unică!',
'🛡️쉴드+15%':'🛡️Scut+15%',
'👿악의+':'👿Răutate+',
'❄유니크 빙결!':'❄Îngheț unic!',
'🔨방어무시!':'🔨Ignoră DEF!',
'💥유니크 폭발!':'💥Explozie unică!',
'👻 투명화!':'👻 Invizibilitate!',
'⚡회피 반격!':'⚡Contraatac de eschivă!',
'⚠패링 실패!':'⚠Parare eșuată!',
'🔥피격→분노!':'🔥Lovitură→Furie!',
'✦ 유니크 부활!':'✦ Înviere unică!',
'닫기 [V]':'Închide [V]',
'닫기 [C]':'Închide [C]',
'\u2026\uBD84\uB178\uAC00 \uB053\uC5B4\uB118\uCE5C\uB2E4. \uC2A4\uD398\uC774\uC2A4\uB85C \uC801\uB4E4\uC5D0\uAC8C \uD3ED\uBC1C\uC2DC\uCCA8!':'…Furia se revarsă. Dezlănțuie-o asupra dușmanilor cu Space!',
'\uBD84\uB178\uAC8C\uC774\uC9C0 \uAF49 \uCC3C\uC5B4! \uC2A4\uD398\uC774\uC2A4\uB85C \uD3ED\uBC1C\uC2DC\uCCA8!':'Indicatorul de furie plin! Explodează-l cu Space!',

};
