// 지옥의 길 — Magyar (hu)
const _HU={
'썩은 숲':'Rothadt Erdő',
'숲의 감시자':'Erdő Őre',
'독버섯 거인':'Mérgező Gomba Óriás',
'숲의 사냥꾼':'Erdei Vadász',
'숲의 기생수':'Élősködő Bestia',
'1장 — 썩은 숲':'1.F — Rothadt Erdő',
'2장 — 벌레굴':'2.F — Féregjárat',
'3장 — 얼음굴':'3.F — Jégbarlang',
'4장 — 고통의 화염지대':'4.F — Pokoli Pusztaság',
'5장 — 지옥의 군단':'5.F — Pokoli Légió',
'6장 — 사도의 마굴':'6.F — Apostol Barlangja',
'7장 — 지옥성':'7.F — Pokoli Citadella',
'탈출!':'Megmenekült!',
'처치':'Legyőzés',
'경험치':'TPSZ',
'최대콤보':'Max Kombó',
'일어나. 여신이 널 여기 보낸 건 죽으라고가 아니야.':'Kelj fel. Az istennő nem meghalni küldött ide.',
'좋아, 감각이 있군. 계속 쳐!':'Jó, van ösztönöd. Üss tovább!',
'Shift를 눌러. 작살이다. 땅에 꽂아서 끌려가!':'Nyomd meg a Shift-et. Ez a szigony. Szúrd be és húzasd magad!',
'작살로 끌려가는 중엔 무적이다. 위험할 때 쓰면 좋아.':'A szigonnyal húzás közben sebezhetetelen vagy. Veszély esetén használd.',
'...아파? 당연하지. 여긴 지옥이야.':'...Fáj? Persze. Ez a pokol.',
'Q를 눌러! 악의로 보호막을 만들 수 있다.':'Nyomd meg a Q-t! Rosszindulatból pajzsot hozhatsz létre.',
'보호막 없이 버틸 생각은 버려.':'Pajzs nélkül ne is gondolj a túlélésre.',
'우클릭이 패링이다. 적 공격이 닿기 직전에 눌러!':'A jobb klikk a hárítás. Közvetlenül az ellenség csapása előtt nyomd!',
'못 하겠으면 때려. 안 죽으면 그만이야.':'Ha nem megy, csak üss. Az a lényeg, hogy ne halj meg.',
'됐어! 감 잡았구나.':'Megvan! Kezded érezni.',
'하나 죽었군.':'Egy lent van.',
'유령쇠뇌야. 인사해.':'Ez a szellem számszeríj. Köszönj.',
'빨간 탄을 무서워하지 마. 악의가 강하다.':'Ne félj a piros lövedékektől. A rosszindulat erős.',
'패링으로 돌려주고, Q 보호막도 써! 악의를 잘 굴려!':'Hárítsd vissza, használd a Q pajzsot is! Kezeld jól a rosszindulatot!',
'무지개빛은 패링 불가! 피해!':'A szivárványszínűt nem lehet hárítani! Kerüld el!',
'피가 새고 있다. Shift. 빠져.':'Vérzik. Shift. Menekülj.',
'물약 있잖아! 숫자키!':'Van bájitalod! Számgombok!',
'우클릭. 적 손목이 꺾일 때 쳐.':'Jobb klikk. Üss, mikor az ellenfél csuklója meghajlik.',
'빨간 탄은 악의 덩어리다. 쳐내서 이용해.':'A piros lövedékek rosszindulat-csomók. Verd vissza és használd.',
'무지개빛만 피하면 돼! 나머지는 다 패링!':'Csak a szivárványszínűt kerüld! A többit mind hárítsd!',
'Q 보호막도 패링이 가능해!':'A Q pajzzsal is lehet hárítani!',
'위험해! 쉬프트 사슬기동으로 피해!!':'Veszély! Shift lánc-kitéréssel menekülj!!',
'쉬프트! 사슬기동은 이동기야! 끌려가면서 무적이라고!':'Shift! A lánc-kitérés mozgás! Húzás közben sebezhetetelen vagy!',
'스킬포인트가 쌓였어! K 눌러서 스킬 배우자!':'Képességpontok gyűltek! K gomb, tanulj képességeket!',
'속성을 읽어. 약점을 찌르면 두 배로 썩는다.':'Olvasd az elemeket. A gyengeséget kihasználva dupla a sebzés.',
'K를 눌러봐! 스킬을 배울 수 있어!':'Nyomd meg a K-t! Képességeket tanulhatsz!',
'C 눌러서 능력치 찍어! 패시브도 있어~':'C gomb a statokhoz! Passzívok is vannak~',
'G를 눌러. 대장간에서 장비를 강화할 수 있다.':'Nyomd meg a G-t. A kovácsműhelyben fejlesztheted a felszerelésedet.',
'F키도 스킬 슬롯이야! 스킬 많으면 L로 배정해봐~':'Az F gomb is képesség-hely! Ha sok van, L-lel oszd be~',
'Z. 필살기다. 아껴 써라.':'Z. Ez az elsöprő csapásod. Takarékoskodj vele.',
'L-CTRL로 유령걸음이나 얼음보주 쓸 수 있어!':'L-CTRL-lal Szellemjárást vagy Jéggömböt használhatsz!',
'L을 눌러. 스킬 슬롯을 정리해야 한다.':'Nyomd meg az L-t. Rendezd a képesség-helyeket.',
'가방 터지겠다! V 눌러서 창고에 넣어둬!':'A táskád szétrobban! V gomb, tedd a raktárba!',
'ESC로 설정 열 수 있어! 난이도 바꾸기, 자동물약 조절~':'ESC a beállításokhoz! Nehézség, auto-bájital~',
'...아직 살아있네. 좌클릭으로 저것들 쳐봐.':'...Még élsz. Bal klikkel üsd meg őket.',
'...치는 건 할 줄 아네. 피하는 건?':'...Ütni tudsz. De kitérni?',
'흥, 작살 못 맞추면 헛수고야.':'Hmpf, ha nem találsz a szigonnyal, kárba megy.',
'...운이 좋았을 뿐이야. 아마.':'...Csak szerencséd volt. Valószínűleg.',
'...고기 냄새. 싫진 않네.':'...Hússzag. Nem rossz.',
'...말은 못해.':'...Nem tud beszélni.',
'예쁘다고 만지면 죽어.':'Ha megérinted, mert szép, meghalsz.',
'작살 던져! 끌려가면 무적이야!':'Dobd a szigonyt! Húzás közben sebezhetetelen vagy!',
'...마시든 말든. 네 목숨이니까.':'...Idd meg vagy ne. A te életed.',
'그게 패링이야! 타이밍이 전부야~':'Ez a hárítás! Minden az időzítésen múlik~',
'화염엔 빙결! 암전엔 암흑! 기억해!':'Tűz ellen jég! Villám ellen sötét! Jegyezd meg!',
'...얼어붙은 놈은 오래 안 간다.':'...A befagyott nem bírja sokáig.',
'얼었어! 빙결 중 1.5배야!':'Befagyott! Fagyás közben 1.5×!',
'...힘을 골라라. 전부 가질 순 없다.':'...Válaszd meg az erődet. Mindent nem kaphatsz.',
'스탯을 올려. 살고 싶으면.':'Emeld a statokat. Ha élni akarsz.',
'좋은 장비는 강화해야 진짜 힘을 발휘해!':'A jó felszerelés fejlesztve mutatja meg igazi erejét!',
'...슬롯을 채워. 빈 손은 죽음이다.':'...Töltsd meg a helyeket. Üres kéz = halál.',
'Z 누르면 대박! 쿨타임 길어서 타이밍 봐야 해!':'Z-vel hatalmas sebzés! Hosszú lehűlés, jó időzítés kell!',
'Ctrl. 위기에 쓸 카드가 하나 늘었군.':'Ctrl. Még egy ász a tarsolyban vészhelyzetekre.',
'스킬이 많아졌네~ L로 어디에 뭘 넣을지 골라!':'Sok képességed van~ L-lel oszd be!',
'...버리기 아까운 건 창고에.':'...Amit kár kidobni, tedd a raktárba.',
'...살아남은 것만으로도 대단하군. 설정을 확인해.':'...Már az is bravúr, hogy élsz. Nézd meg a beállításokat.',
'MP 부족!':'Nincs elég MP!',
'ST 부족!':'Nincs elég ST!',
'악의 부족!':'Nincs elég Rosszindulat!',
'충전 중...':'Töltés...',
'캔슬':'Mégse',
'아이템 선택 필요':'Válassz tárgyat',
'악의 소진...':'Rosszindulat kimerült...',
'비문 발견...':'Felirat felfedezve...',
'HP물약!':'HP Bájital!',
'HP물약 +1':'HP Bájital +1',
'HP물약 +2':'HP Bájital +2',
'HP/MP/ST 회복!':'HP/MP/ST Helyreállítva!',
'보물상자 개봉!':'Kincsesláda kinyitva!',
'익사!':'Fulladás!',
'피웅덩이!':'Vértócsa!',
'독혈!':'Mérgezett Vér!',
'잡힘!':'Elkapva!',
'콤보 종료':'Kombó Vége',
'빙결!':'Befagyva!',
'화상!':'Égés!',
'독!':'Méreg!',
'감전!':'Áramütés!',
'기절!':'Kábulás!',
'봉인됨!':'Lepecsételve!',
'관통!':'Átütés!',
'기검참':'Pengeszelet',
'악의구':'Rosszindulat Gömb',
'회전참':'Forgószél',
'기폭팔':'Detonáció',
'칼등 처내기':'Penge Hárítás',
'만화방창':'Tűszúrás Sortűz',
'멸살광선':'Megsemmisítő Sugár',
'원소추적탄':'Elem Kereső',
'악의 보호자':'Rosszindulat Őr',
'악의 사냥':'Rosszindulat Vadászat',
'폭풍소환':'Örvény Idézés',
'해골무덤':'Csont Sírbolt',
'\u{1F47B} 유령!':'\u{1F47B} Szellem!',
'\u{1F9B4} 해골무덤!':'\u{1F9B4} Csont Sírbolt!',
'신성폭발':'Szent Robbanás',
'블랙':'Fekete Csillag',
'용암소환':'Láva Idézés',
'처형':'Kivégzés',
'악마화 부활':'Démon Feltámadás',
'붉은꽃':'Bíbor Virág',
'얼음보주':'Jéggömb',
'뇌전걸음':'Szellemjárás',
'만화방창 II':'Tűszúrás Sortűz II',
'마력연사':'Arkán Sorozat',
'마력광선':'Ív Lézer',
'업화선':'Pokoltűz Sugár',
'지옥진':'Pokol Tömb',
'폭독칼날':'Pestis Penge',
'악의폭풍':'Rosszindulat Vihar',
'악의기둥':'Sötét Oszlop',
'회복의 영역':'Szent Terület',
'구속의 영역':'Kötés Terület',
'아이스스톰':'Jégvihar',
'대왕치기':'Óriás Csapás',
'대왕치기 2':'Óriás Csapás II',
'기동불꽃':'Lánc Láng',
'기동파괴':'Lánc Zúzás',
'기동칼날개':'Lánc Pengeszárny',
'평화의보호':'Béke Védelme',
'참회':'Bűnbánat',
'칼등날개':'Pajzsszárny',
'폭산탄':'Robbanó Lövés',
'파쇄의 영역':'Zúzás Terület',
'침식의 영역':'Korrózió Terület',
'관통의 영역':'Átütés Terület',
'부활의 영역':'Feltámadás Terület',
'가시덫':'Tüskecsapda',
'푸른비':'Azúr Eső',
'버스트루프':'Sorozat Hurok',
'유령 허수아비':'Szellem Bábu',
'폭발 허수아비':'Robbanó Bábu',
'공성쇠뇌':'Ostrom Számszeríj',
'사슬기동:충돌':'Lánc Kitérés: Becsapódás',
'사슬기동:화염':'Lánc Kitérés: Láng',
'전격이동':'Villám Lépés',
'기동칼날개!':'Pengeszárny!',
'기동불꽃!':'Lánc Láng!',
'기동파괴!':'Lánc Zúzás!',
'사슬이동:강화!':'Lánc Kitérés!',
'사슬기동:화염!':'Lánc Láng!',
'작살!':'Szigony!',
'진입!':'Belépés!',
'레인라이트닝!':'Villám Eső!',
'마력연사!':'Arkán Sorozat!',
'🔷 마력광선!':'🔷 Ív Lézer!',
'광선 해제':'Lézer Ki',
'MP 부족 — 광선 해제':'MP kimerült — Lézer Ki',
'집중...':'Koncentrálás...',
'시전...':'Varázslás...',
'만화방창!':'Tűszúrás Sortűz!',
'바늘출!':'Tűlövés!',
'칼날!':'Penge!',
'착지!':'Földet érés!',
'체간삭감!':'Tartás Törés!',
'기동전폭 준비!':'Lánc Robbanás Kész!',
'기동불꽃 준비!':'Lánc Láng Kész!',
'기동파괴 준비!':'Lánc Zúzás Kész!',
'유령불꽃 ON':'Szellem Láng BE',
'유령불꽃 OFF':'Szellem Láng KI',
'기동칼날개 AUTO ON':'Pengeszárny AUTO BE',
'기동칼날개 AUTO OFF':'Pengeszárny AUTO KI',
'자동 버스트!':'Auto Sorozat!',
'연사 해제':'Gyorstűz Ki',
'당기기 모드':'Húzás Mód',
'밀어내기 모드':'Lökés Mód',
'날개치기':'Szárnycsapás',
'처내기':'Hárítás',
'Shift: 작살 발사 → 끌려감':'Shift: Szigony → húzás',
'Shift: 화염길+화상':'Shift: Tűzcsóva+égés',
'CT: 전류변신+뇌전걸음 (쿨4초)':'CT: Villámforma+Szellemjárás (lh 4mp)',
'CT: 방어구체+빙결 (재입력: 파쇄)':'CT: Jéggömb+fagyás (újra: zúzás)',
'근접':'Közel',
'견갑':'Pajzs',
'작살':'Szigony',
'마법':'Mágia',
'보막':'Védelem',
'유령':'Szellem',
'스킬':'Képesség',
'대장':'Kovács',
'인벤':'Táska',
'인벤토리':'Felszerelés',
'복수의 대장간':'Bosszú Kovácsműhelye',
'패시브 스킬':'Passzív Képességek',
'전투 스킬':'Harci Képességek',
'캐릭터 선택':'Karakter Választás',
'물리':'Fizikai',
'화염':'Tűz',
'빙결':'Jég',
'암흑':'Sötét',
'암전':'Villám',
'신성':'Szent',
'대지':'Föld',
'힘':'Erő',
'민첩':'Ügyesség',
'지능':'Értelem',
'행운':'Szerencse',
'맹공':'Roham',
'철벽':'Erőd',
'돌파':'Áttörés',
'반격':'Megtorlás',
'마력폭주':'Arkán Kitörés',
'정밀사격':'Precíz Lövés',
'수호':'Őrzés',
'수호신':'Őrszellem',
'회복력':'Gyógyulás',
'급소':'Létfontosságú Csapás',
'약탈':'Zsákmány',
'관통':'Átütés',
'마력회복':'Mana Visszanyerés',
'쇠뇌력':'Számszeríj Mesteri',
'광전사':'Berzerker',
'추적자':'Nyomkövető',
'물리관통':'Fizikai Áth.',
'마법관통':'Mágikus Áth.',
'녹슨 대검':'Rozsdás Nagykard',
'강철 대검':'Acél Nagykard',
'흑요석 대검':'Obszidián Nagykard',
'낡은 석궁':'Elnyűtt Számszeríj',
'강철 석궁':'Acél Számszeríj',
'흑요석 석궁':'Obszidián Számszeríj',
'대검':'Nagykard',
'석궁':'Számszeríj',
'연사석궁':'Ismétlő',
'마력석궁':'Arkán Számszeríj',
'악의 추출':'Rosszindulat Kinyerés',
'악의':'Rosszindulat',
'필살기':'Elsöprő',
'필살기 해제':'Elsöprő Nincs',
'이전':'Átvitel',
'강화':'Fejlesztés',
'개봉!':'Kinyitva!',
'여신의 가호':'Istennő Áldása',
'과부하!':'Túlterhelés!',
'맹독의':'Mérges',
'불꽃의':'Lángoló',
'냉기의':'Fagyos',
'번개의':'Villamos',
'암흑의':'Átkozott',
'관통의':'Átütő',
'광폭의':'Dühöngő',
'파쇄의':'Zúzó',
'연쇄의':'Láncoló',
'학살의':'Öldöklő',
'폭발의':'Robbanó',
'집중의':'Fókuszált',
'쾌속의':'Gyors',
'패리의':'Hárító',
'추적자의':'Nyomkövető',
'작살의':'Szigony',
'궁극의':'Legfőbb',
'집중력의':'Tudatos',
'강인의':'Szívós',
'수호의':'Védő',
'활력의':'Életerős',
'신속의':'Fürge',
'화염수호':'Tűz Őr',
'빙결수호':'Jég Őr',
'암전수호':'Villám Őr',
'암흑수호':'Sötét Őr',
'독수호':'Méreg Őr',
'전원소수호':'Teljes Őr',
'강철의':'Acélos',
'반사의':'Visszaverő',
'가시의':'Tüskés',
'흡수의':'Elnyelő',
'인내의':'Kitartó',
'위기의':'Kétségbeesett',
'피격반격의':'Visszacsapó',
'패링폭발의':'Hárítás Robbanás',
'스태거폭발의':'Ingás Robbanás',
'원소전환의':'Átalakító',
'정화의':'Tisztító',
'불굴의':'Megtörhetetlen',
'부활의':'Feltámasztó',
'약탈의':'Zsákmányoló',
'경험의':'Tapasztalt',
'골드의':'Aranyos',
'포션강화의':'Bájital+',
'사슬의':'Láncolt',
'진혼의':'Megszentelő',
'윤회의':'Körkörös',
'생명력의':'Életerős',
'재생의':'Újjáépülő',
'치유의':'Gyógyító',
'마력의':'Arkán',
'절약의':'Takarékos',
'영혼의':'Lélekhez Kötött',
'예리한':'Éles',
'맹렬한':'Kegyetlen',
'파멸의':'Romboló',
'게임 설정':'Játék Beállítások',
'화면 흔들림':'Képernyő Rázás',
'파티클 양':'Részecske Mennyiség',
'효과음 볼륨':'Hangeffektus Hangerő',
'음악 볼륨':'Zene Hangerő',
'난이도':'Nehézség',
'자동 물약':'Auto Bájital',
'최소 줍기 등급':'Min Felszedés Fokozat',
'최소 줍기 티어':'Min Felszedés Szint',
'FPS 제한':'FPS Korlát',
'해상도 스케일':'Felbontás Skála',
'펫 자동수거':'Kisállat Auto-Gyűjtés',
'화면 설정':'Kijelző Beállítások',
'화면 모드':'Kijelző Mód',
'보스 AI 디버그':'Főellenség AI Debug',
'유령불꽃 크기':'Szellem Láng Méret',
'화면 명암':'Fényerő',
'유령 글로우':'Szellem Ragyogás',
'기동:칼날개 AUTO':'Pengeszárny AUTO',
'일반':'Normál',
'어려움':'Nehéz',
'지옥':'Pokol',
'이상':'vagy felette',
'사용 안 함':'Kikapcsolva',
'창 모드':'Ablakos',
'보더리스':'Keret Nélküli',
'전체화면':'Teljes Képernyő',
'설정':'Beállítások',
'조작 키 설정 (클릭하여 변경)':'Billentyű Kiosztás (Kattints a módosításhoz)',
'좌클릭 무기 공격':'Bal Klikk Fegyver Támadás',
'우클릭 탭 칼등 처내기':'Jobb Klikk Penge Hárítás',
'우클릭 홀드 연속 처내기':'Jobb Klikk Tartás Folyamatos Hárítás',
'SHIFT 작살 발사':'SHIFT Szigony Lövés',
'이동':'Mozgás',
'아이템 줍기':'Tárgy Felvétel',
'능력치 (스탯/패시브)':'Tulajdonságok (Stat/Passzív)',
'분해':'Szétszedés',
'제작':'Készítés',
'사망':'Halál',
'부활':'Feltámadás',
'로비로':'Lobbyba',
'가방에 공간이 없습니다!':'Nincs hely a táskában!',
'가방이 가득 찼습니다!':'A táska megtelt!',
'창고가 가득 찼습니다!':'A raktár megtelt!',
'퀵슬롯이 가득 찼습니다!':'A gyorshely megtelt!',
'결정 주머니가 가득 찼습니다!':'A kristálytasak megtelt!',
'결정 주머니 가득!':'Kristálytasak tele!',
'악의가 부족합니다!':'Nincs elég rosszindulat!',
'가방이 비어있습니다':'A táska üres',
'창고가 비어있습니다':'A raktár üres',
'비어있음':'Üres',
'어픽스 없음':'Nincs tulajdonság',
'장착!':'Felszerelve!',
'해제':'Levéve',
'보관':'Berak',
'꺼내기':'Kivesz',
'현재 장착':'Jelenleg felszerelve',
'없음 — 제작하세요!':'Nincs — Készíts egyet!',
'리셋할 포인트가 없습니다':'Nincs visszaállítható pont',
'키 설정 초기화 완료':'Billentyű beállítások visszaállítva',
'제작 확률':'Készítés esély',
'제작 비용':'Készítés költség',
'보유 악의':'Birtokolt rosszindulat',
'보스방':'Főellenség Szoba',
'안식처':'Menedék',
'회복':'Gyógyulás',
'점화':'Begyújtás',
'비석':'Sztélé',
'읽기':'Olvasás',
'파괴':'Rombolás',
'제단':'Oltár',
'기원':'Ima',
'잔해':'Törmelék',
'열기':'Nyitás',
'문지기':'Kapuőr',
'부활 판정 중...':'Feltámadás elbírálás...',
'기폭 준비!':'Detonáció kész!',
'탈출':'Menekülés',
'연타':'Nyomkodás',
'추적암전':'Követő Villám',
'만화광선':'Fénysugár',
'최종 마법':'Végső Mágia',
'감시중':'Figyelés',
'대기':'Készenlét',
'작동중':'Aktív',
'설치 가능':'Telepíthető',
'균열 임박!':'Repedés közeledik!',
'흡수 중...':'Elnyelés...',
'흡수 완료 — 재입력으로 회수':'Kész — újra nyomva visszahívás',
'화상':'Égés',
'당기기':'Húzás',
'밀어내기':'Lökés',
'단계':'szint',
'단':'szint',
'습득!':'Megtanulva!',
'리셋!':'Visszaállítva!',
'세팅!':'Beállítva!',
'회수':'Visszahívás',
'합체 해제':'Egyesítés Bontás',
'리셋':'Visszaállítás',
'환불':'Visszatérítés',
'파트너 클릭!':'Kattints a partnerre!',
'SP부족!':'SP kell!',
'같은 보석 스킬 습득 시 합체 가능':'Ugyanazon drágakő képesség tanulásakor egyesíthető',
'펼쳐서 초기화':'Kinyit és visszaállít',
'슬롯:':'Hely:',
'남은 SP':'Maradék SP',
'맞아서 사망':'Csapástól halt meg',
'레벨':'Szint',
'최대HP':'Max HP',
'방랑 기사':'Vándor Lovag',
'보물 악마':'Kincs Démon',
'거울의 사도':'Tükör Apostol',
'상인 악마':'Kereskedő Démon',
'사슬의 죄수':'Láncos Fogoly',
'시간의 사도':'Idő Apostol',
'탐욕의 사도':'Kapzsi Apostol',
'저주받은 쌍둥이':'Átkozott Ikrek',
'차원 균열체':'Dimenziós Repedés',
'죽음 그 자체':'Maga a Halál',
'HP결정':'HP Kristály',
'ST결정':'ST Kristály',
'MP결정':'MP Kristály',
'ATK결정':'TÁM Kristály',
'DEF결정':'VÉD Kristály',
'속도결정':'Sebesség Kristály',
'크리결정':'Krit Kristály',
'치명결정':'KritSeb Kristály',
'화염결정':'Tűz Kristály',
'냉기결정':'Jég Kristály',
'암흑결정':'Sötét Kristály',
'번개결정':'Villám Kristály',
'신성결정':'Szent Kristály',
'생명결정':'Élet Kristály',
'기력결정':'Kitartás Kristály',
'마력결정':'Mana Kristály',
'행운결정':'Szerencse Kristály',
'조각':'Töredék',
'파편':'Szilánk',
'순수결정':'Tiszta Kristály',
'완전결정':'Tökéletes Kristály',
'결정 주머니':'Kristálytasak',
'결정이 없습니다':'Nincs kristály',
'가루':'Por',
'전체':'Összes',
'스탯':'Stat',
'원소':'Elem',
'유틸':'Segéd',
'현재':'Jelenlegi',
'최대 강화 달성 (+20)':'Max fejlesztés (+20)',
'강화 시':'Fejlesztés után',
'합성':'Szintézis',
'같은 종류·같은 성급 결정 3개 → 1성급 상승 (강화 리셋)':'3 azonos típusú és fokozatú kristály → 1 fokozat emelés (fejlesztés nullázódik)',
'합성 가능한 결정이 없습니다 (같은 종류·성급 3개 필요)':'Nincs szintetizálható kristály (3 azonos típus és fokozat kell)',
'결정 분해 → 결정 가루':'Kristály Szétbontás → Kristálypor',
'분해할 결정이 없습니다':'Nincs szétbontható kristály',
'결정 제작 (가루 → 결정)':'Kristály Készítés (Por → Kristály)',
'탈착':'Levétel',
'빈 슬롯':'Üres hely',
'결정 선택 후 클릭':'Kristály kiválasztása után kattints',
'클릭하여 선택결정 장착':'Kattints a kiválasztott kristály felszereléséhez',
'획득!':'Megszerezve!',
'제작!':'Elkészítve!',
'합성!':'Szintetizálva!',
'최상위 일괄합성':'Csúcs Csoportos Szintézis',
'일괄합성 완료':'Csoportos szintézis kész',
'벌레굴':'Féregjárat',
'얼음굴':'Jégbarlang',
'고통의 화염지대':'Pokoli Pusztaság',
'지옥의 군단':'Pokoli Légió',
'사도의 마굴':'Apostol Barlangja',
'지옥성':'Pokoli Citadella',
'엑소듀서 전사':'Exoduser Harcos',
'포이즈':'Tartás',
'지옥창고':'Pokol Raktár',
'선택분해':'Szelektív Szétszedés',
'쓰레기':'Szemét',
'복구 불가!':'Nem állítható helyre!',
'중요잠금':'Fontos-zárolva',
'자동 장착!':'Auto felszerelve!',
'분해! 가루 +':'Szétszedve! Por +',
'평화보호':'Védelem',
'지진폭풍':'Földrengés Vihar',
'회전기폭':'Forgás-Robbanás',
'공격':'Támadás',
'보호막':'Akadály',
'합체 스킬로 통합됨':'Egyesített képességbe olvadt',
'얼음보주 안에선 사용 불가!':'Jéggömbben nem használható!',
'Shift+키로 폭파':'Shift+gomb robbantáshoz',
'취소':'Mégse',
'쿨다운 중...':'Lehűlés...',
'시전 중...':'Varázslás...',
'악의 부족! (12)':'Nincs elég Rosszindulat! (12)',
'악의 부족! (15)':'Nincs elég Rosszindulat! (15)',
'악의 부족! (20)':'Nincs elég Rosszindulat! (20)',
'악의 부족! (10)':'Nincs elég Rosszindulat! (10)',
'HP 부족!':'Nincs elég HP!',
'필살기 슬롯 클릭하여 배정!':'Kattints az elsöprő helyre a kiosztáshoz!',
'필살기 스킬을 습득하세요':'Tanulj meg egy elsöprő képességet',
'우클릭(칼등치기)에 합체됨':'Jobb klikkbe (penge hárítás) egyesítve',
'T(석궁자동)에 세팅하세요':'Állítsd be T-re (auto számszeríj)',
'공성쇠뇌 철거 → 이동식':'Ostrom számszeríj elbontva → hordozható',
'ST 부족! (100)':'Nincs elég ST! (100)',
'HP 99% 이상!':'HP 99%+!',
'그로기 보스 없음!':'Nincs kótyagós főellenség!',
'이미 폭풍 지역!':'Már viharterületen!',
'이미 빙풍 지역!':'Már jégvihar területen!',
'💎 푸른비 해금!':'💎 Azúr Eső feloldva!',
'💫 버스트루프 해금!':'💫 Sorozat Hurok feloldva!',
'👻 유령 허수아비 해금!':'👻 Szellem Bábu feloldva!',
'쿨 ':'LH ',
'과부하 ':'Túlterhelés ',
'🕊️💎 블루콩!':'🕊️💎 Kék Bab!',
'🛡️💎 빨콩→블루콩!':'🛡️💎 Piros→Kék Bab!',
'🛡️💎 무지개→블루콩!':'🛡️💎 Szivárvány→Kék Bab!',
'레어':'Ritka',
'슬롯':'Hely',
'성공률':'Sikerráta',
'AI 자동 강화':'AI Auto Fejlesztés',
'최대 강화 달성!':'Max fejlesztés elérve!',
'최대 강화':'Max fejlesztés',
'회복량':'Gyógyulás',
'분해할 아이템이 없습니다.':'Nincs szétszedendő tárgy.',
'🔨 제작':'🔨 Készítés',
'체간':'Tartás',
'아이템에 마우스를 올리거나 좌클릭으로 선택하세요':'Húzd az egeret a tárgyra vagy kattints bal gombbal',
'중독':'Mérgezés',
'지뢰':'Akna',
'함정':'Csapda',
'산호가시':'Korall Tüske',
'투사체':'Lövedék',
'도트':'Időzített',
'레어몹':'Ritka Szörny',
'구역':'Zóna',
'가시!':'Tüske!',
'림보':'Limbus',
'색욕':'Bujaság',
'탐식':'Falánkság',
'탐욕':'Kapzsiság',
'분노':'Harag',
'이단':'Eretnekség',
'폭력':'Erőszak',
'분노!':'Düh!',
'탐욕!':'Kapzsiság!',
'💀 분노 폭발!':'💀 Düh Robbanás!',
'심연의 분노!':'Mélység Dühe!',
'쌍둥이의 분노!':'Ikrek Dühe!',
'소환굴':'Idéző Üreg',
'처치!':'Legyőzve!',
'왕관 착용':'Korona Fel',
'왕관 해제':'Korona Le',
'맨손':'Puszta Kéz',
'없음':'Nincs',
'갑옷':'Páncél',
'부츠':'Csizma',
'매직':'Mágikus',
'챔피언':'Bajnok',
'초속':'Gyorsaság',
'강타':'Csapás',
'재생':'Újjáépülés',
'맹독':'Méreg',
'소환':'Idézés',
'기생':'Parazita',
'분열':'Hasadás',
'용암자취':'Láva Nyom',
'사망폭발':'Halál Robbanás',
'화염사슬':'Tűz Lánc',
'광전':'Őrjöngés',
'텔레포트':'Teleport',
'소용돌이':'Örvény',
'환영':'Fantom',
'전격반사':'Sokk Visszaverés',
'감전':'Áramütés',
'낙뢰':'Mennydörgés',
'연쇄전격':'Lánc Villám',
'동료불사':'Szövetséges Halhatatlan',
'영혼포식':'Lélek Felfal',
'시간왜곡':'Időtorzítás',
'혼돈변이':'Káosz Mutáció',
'복수자':'Bosszúálló',
'마법보초':'Mágikus Őr',
'환영술사':'Illuzionista',
'함성':'Harci Kiáltás',
'치유':'Gyógyítás',
'신속':'Fürgeség',
'다크 판타지 전사. 거대검+검은 갑옷':'Sötét fantázia harcos. Nagykard + Fekete páncél',
'⚡ 사슬이동:강화!':'⚡ Lánc: Erősített!',
'⚡ 사슬기동:화염!':'⚡ Lánc: Láng!',
'달성!':'Elérve!',
'ST':'ST',
'부족!':'Hiányzik!',
'타':'Találat',
'🌀 당기기 모드':'🌀 Húzás Mód',
'💥 밀어내기 모드':'💥 Lökés Mód',
'🕊️빨콩 흡수':'🕊️Piros bab elnyelés',
'🕊️흡수':'🕊️Elnyelés',
'💎유도 폭발!':'💎Irányított robbanás!',
'💥반사 폭발!':'💥Visszaverés robbanás!',
'⚡⚡ 참회 귀환!':'⚡⚡ Bűnbánat Visszatérés!',
'⚡ 참회!':'⚡ Bűnbánat!',
'파도!':'Hullám!',
'암전!':'Villám!',
'암흑!':'Sötét!',
'암흑창!':'Sötét Lándzsa!',
'빛창!':'Fény Lándzsa!',
'체 소환!':'idézve!',
'개 설치!':'elhelyezve!',
'💥 보스 그로기!':'💥 Főellenség Kótyagos!',
'💥 그로기!':'💥 Kótyagos!',
'보상':'Jutalom',
'⚡ 암전나선!':'⚡ Villám Spirál!',
'🌋 지진폭풍!':'🌋 Földrengés Vihar!',
'SP슬롯':'SP Hely',
'F슬롯':'F Hely',
'⚔🩸 독혈해방!':'⚔🩸 Pestis Felszabadítás!',
'⚔ 칼날 해방!':'⚔ Penge Felszabadítás!',
'🔨🌋 지옥강타!':'🔨🌋 Pokol Csapás!',
'🔨 대왕치기!':'🔨 Óriás Csapás!',
'✟ 결계의 영역!':'✟ Védkör Terület!',
'✟ 물의 영역!':'✟ Víz Terület!',
'✟ 파쇄의 영역!':'✟ Zúzás Terület!',
'✟ 침식의 영역!':'✟ Korrózió Terület!',
'✟ 관통의 영역!':'✟ Átütés Terület!',
'✟ 권능의 영역!':'✟ Uralom Terület!',
'🛡 회복의 영역!':'🛡 Szent Terület!',
'임계...!':'Kritikus...!',
'기폭팔!':'Detonáció!',
'강제기폭!':'Kényszer Detonáció!',
'자동기폭!':'Auto Detonáció!',
'회전기폭!':'Forgás Detonáció!',
'해제기폭!':'Feloldás Detonáció!',
'지진기폭!':'Földrengés Detonáció!',
'혼돈의 왕관':'Káosz Korona',
'전지전능의 왕관':'Mindenhatóság Korona',
'악마의 팔찌':'Démon Karkötő',
'생명의 팔찌':'Élet Karkötő',
'🌊 위→아래 파도!':'🌊 Fent→Lent Hullám!',
'🌊 오른→왼 파도!':'🌊 Jobb→Bal Hullám!',
'🌊 아래→위 파도!':'🌊 Lent→Fent Hullám!',
'🌊 왼→오른 파도!':'🌊 Bal→Jobb Hullám!',
'무적!':'Sebezhetetelen!',
'🪞 반격!':'🪞 Visszacsapás!',
'💢 반격!':'💢 Visszacsapás!',
'흡수!':'Elnyelés!',
'반격 발사!':'Visszacsapás Lövés!',
'저주! 드랍률 -50%':'Átok! Ejtés -50%',
'도망!':'Menekülés!',
'위상!':'Fázis!',
'방어!':'Védés!',
'회수 HP+':'Visszahívás HP+',
'이동식 복귀':'Hordozható Visszatérés',
'약점!':'Gyengeség!',
'저항!':'Ellenállás!',
'콤보 종료: ':'Kombó Vége: ',
'악의 +':'Rosszindulat +',
'저주 ':'Átok ',
'불발...':'Csütörtök...',
'작살 약점!':'Szigony Gyengeség!',
'전염 x':'Fertőzés x',
'흡수 완료!':'Elnyelés Kész!',
'부활 성공!':'Feltámadás Sikeres!',
'부활 실패...':'Feltámadás Sikertelen...',
'차원 이동!':'Dimenzió Ugrás!',
'기절 해제':'Kábulás Feloldva',
'악의 부족':'Nincs elég rosszindulat',
'스킬 미습득':'Nincs megtanult képesség',
'펼치기':'Kinyitás',
'접기':'Összecsukás',
'조건 미달!':' nem teljesül!',
'해제!':' Bontva!',
'자동 ON':' Auto BE',
'자동 OFF':' Auto KI',
'스킬 해제':' képesség levéve',
'닫기':'Bezárás',
'장착 중':'Felszerelve',
'보관 아이템':'Raktárazott Tárgy',
'클릭으로 선택 · ESC로 닫기':'Kattints a kiválasztáshoz · ESC bezárás',
'선택됨':'Kiválasztva',
'악의 부족! (30)':'Nincs elég Rosszindulat! (30)',
'MP 부족! (40)':'Nincs elég MP! (40)',
'MP 부족! (100)':'Nincs elég MP! (100)',
'MP 부족! (10)':'Nincs elég MP! (10)',
'MP 부족! (':'Nincs elég MP! (',
'✟ 시전...':'✟ Varázslás...',
'🌋 시전...':'🌋 Varázslás...',
'⛧ 시전...':'⛧ Varázslás...',
'❄ 진입!':'❄ Belépés!',
'🔱 작살!':'🔱 Szigony!',
'레벨 부족! (요구: Lv.':'Szint alacsony! (Kell: Lv.',
' 장착!':' Felszerelve!',
' 해제':' Levéve',
'👿 악의 추출: +':'👿 Rosszindulat Kinyerés: +',
'F 슬롯 해제':'F Hely levéve',
'💫 집중...':'💫 Koncentrálás...',
'⚡ 마력연사!':'⚡ Arkán Sorozat!',
'❄빙결!':'❄Befagyva!',
'🟢독!':'🟢Méreg!',
'⚡감전!':'⚡Áramütés!',
'🔥화상!':'🔥Égés!',
'✦ 여신의 가호 — SP+5 AP+3':'✦ Istennő Áldása — SP+5 AP+3',
'⚔ 기동칼날개!':'⚔ Pengeszárny!',
'🔥 화염관통!':'🔥 Tűz Átütés!',
'🔱 관통!':'🔱 Átütés!',
'⚔ 칼날!':'⚔ Penge!',
'💥 착지!':'💥 Földet Érés!',
'💫 기절!':'💫 Kábulás!',
'⚡ 체간삭감!':'⚡ Tartás Törés!',
'⚡ 기동파괴! ':'⚡ Lánc Zúzás! ',
'🔥 기동불꽃!':'🔥 Lánc Láng!',
'🔥 기동불꽃! ':'🔥 Lánc Láng! ',
'단계 ×':' x',
'⚡ 기동전폭! x':'⚡ Lánc Robbanás! x',
'🔥🔥 3중폭!':'🔥🔥 3x Láng!',
'🔥🔥🔥 6중폭!':'🔥🔥🔥 6x Láng!',
'🔥🔥🔥🔥 9중폭!':'🔥🔥🔥🔥 9x Láng!',
'💥 불꽃폭발! ':'💥 Láng Robbanás! ',
'🔥 기동불꽃 준비!':'🔥 Lánc Láng Kész!',
'🔨 기동파괴 준비!':'🔨 Lánc Zúzás Kész!',
'⚡ 기동전폭 준비!':'⚡ Lánc Robbanás Kész!',
'⚡ 과부하! 5초':'⚡ Túlterhelés! 5mp',
'💫 자동 버스트!':'💫 Auto Sorozat!',
'🔨 칼등날개!':'🔨 Pajzsszárny!',
'💥폭발!':'💥Robbanás!',
'🛡️💎 유도반사!':'🛡️💎 Irányított Visszaverés!',
'⚡💎 블루콩!':'⚡💎 Kék Bab!',
'💎 블루콩!':'💎 Kék Bab!',
'⚡반사!':'⚡Visszaverés!',
'💎 푸른비 OFF':'💎 Azúr Eső KI',
'💎 푸른비 ON!':'💎 Azúr Eső BE!',
'🔥 지옥진!':'🔥 Pokol Tömb!',
'🔥 업화선!':'🔥 Pokoltűz Sugár!',
'✦ 평화 충격파! ':'✦ Béke Lökéshullám! ',
'⚡ 전류 방출!':'⚡ Áram Kibocsátás!',
'⚡⚡ 레인라이트닝!':'⚡⚡ Villám Eső!',
'💫 광역!':'💫 Területi!',
'🔥 불장판!':'🔥 Tűz Zóna!',
'💫 피니셔!':'💫 Befejező!',
'☠ 지옥에서 귀환!':'☠ Visszatérés a pokolból!',
'☠ 완전 사망!':'☠ Végleges Halál!',
'⚔ 처형! ':'⚔ Kivégzés! ',
'💥 지뢰!':'💥 Akna!',
'⚠ 함정!':'⚠ Csapda!',
'❌ 우클릭으로! -':'❌ Jobb klikkel! -',
'❌ Q키로! -':'❌ Q gombbal! -',
'💥무지개 폭발! ':'💥Szivárvány Robbanás! ',
'🛡️💎 블루콩!':'🛡️💎 Kék Bab!',
'⬜화이트볼!':'⬜Fehér Gömb!',
'✨💎 블루콩!':'✨💎 Kék Bab!',
'💜다크볼!':'💜Sötét Gömb!',
'❄빙판!':'❄Jégfelület!',
'🌨빙결!':'🌨Befagyva!',
'🕸둔화!':'🕸Lassítás!',
'⚠트랩!':'⚠Csapda!',
'💀 역병 처형!':'💀 Pestis Kivégzés!',
'💥 역병 Finale!':'💥 Pestis Finálé!',
'⚔ 균열 악마!':'⚔ Repedés Démon!',
'자동회수 HP+':'Auto-visszahívás HP+',
'MP 부족 — 연사 해제':'MP alacsony — Gyorstűz Ki',
'MP 부족 — 푸른비 OFF':'MP alacsony — Azúr Eső KI',
'🛡️반사!':'🛡️Visszaverés!',
'⚡🦴 참회 귀환!':'⚡🦴 Bűnbánat Visszatérés!',
'🦴⚡해골번개!':'🦴⚡Csont Villám!',
'⚡악의폭풍!':'⚡Rosszindulat Vihar!',
'❄아이스스톰!':'❄Jégvihar!',
'⚡ 암전폭발!':'⚡ Villám Robbanás!',
'⚡ 레인라이트닝! x':'⚡ Villám Eső! x',
'❄ 탈출!':'❄ Menekülés!',
'⚡쉴드!':'⚡Pajzs!',
'❄🌪️ 얼음보주!':'❄🌪️ Jéggömb!',
'🌪️ 전개!':'🌪️ Kibontás!',
'❄ 빙결흡인!':'❄ Fagyasztó Örvény!',
'❄☄ 빙결폭발!':'❄☄ Fagyasztó Robbanás!',
'☄️ 흡인!':'☄️ Örvény!',
'☄️ 대폭발!':'☄️ Mega Robbanás!',
'❄ 얼음보주!':'❄ Jéggömb!',
'⏳ 시간왜곡!':'⏳ Időtorzítás!',
'쿨다운!':'Lehűlés!',
'❄ 파쇄!':'❄ Zúzás!',
'☄️💥 대폭발!':'☄️💥 Mega Robbanás!',
'반사!':'Visszaverés!',
'💀 도넛!':'💀 Fánk!',
'💀 전멸!':'💀 Megsemmisítés!',
'🌊 파도!':'🌊 Hullám!',
'속박!':'Megkötés!',
'반격!':'Visszacsapás!',
'분신!':'Klón!',
'분신 파괴!':'Klón Megsemmisítve!',
'무기 해방!':'Fegyver Felszabadítás!',
'❄프리즌!':'❄Börtön!',
'⚡ 증표 ':'⚡ Jegy ',
'흔들!':'Rázás!',
'⚠ 광역 발사!':'⚠ Területi Tűz!',
'🔥 확산!':'🔥 Terjedés!',
'⚠ 돌진!':'⚠ Roham!',
'🦅 도약!':'🦅 Ugrás!',
'⚡ 레이저!':'⚡ Lézer!',
'🌊 충격파!':'🌊 Lökéshullám!',
'👹 소환!':'👹 Idézés!',
'☄ 유성우!':'☄ Meteorhullás!',
'🖐 잡기!':'🖐 Megragadás!',
'🌀 회전참!':'🌀 Forgószél!',
'💣 지뢰!':'💣 Akna!',
'🌀 흡인!':'🌀 Szívás!',
'🔴 빨간콩 폭풍!':'🔴 Piros Bab Vihar!',
'🔴🔴 콩 비!':'🔴🔴 Bab Eső!',
'🌊 부채꼴 충격파!':'🌊 Legyező Lökéshullám!',
'✴ 멸광 레이저!':'✴ Megsemmisítő Lézer!',
'🔴 추적 장판!':'🔴 Követő Zóna!',
'💥 속성탄!':'💥 Elem Lövés!',
'⚔ 검기!':'⚔ Kardenergia!',
'⚔ 재단참!':'⚔ Aratás!',
'🌀 나선탄!':'🌀 Spirál Lövés!',
'⚠ 찌르기!':'⚠ Szúrás!',
'🔥🔥 지옥기둥!':'🔥🔥 Pokol Oszlop!',
'⚔ 환영검!':'⚔ Fantom Penge!',
'💢 반격자세!':'💢 Visszacsapás Tartás!',
'⚔ 연격!':'⚔ Kombó!',
'🌑 암흑!':'🌑 Sötétség!',
'👥 분신!':'👥 Klón!',
'🌋 균열!':'🌋 Repedés!',
'🌊 파동!':'🌊 Hullámzás!',
'💣 추적지뢰!':'💣 Követő Akna!',
'⏪ 되감기!':'⏪ Visszatekerés!',
'🌀 중력장!':'🌀 Gravitációs Mező!',
'🔨 벽밀기!':'🔨 Fal Lökés!',
'☠ 독안개!':'☠ Mérgező Köd!',
'⛓ 감옥!':'⛓ Börtön!',
'⚡ 연쇄번개!':'⚡ Lánc Villám!',
'🔮 궤도탄!':'🔮 Orbitális Lövés!',
'🛡 방패돌진!':'🛡 Pajzs Roham!',
'🪞 반격자세!':'🪞 Visszacsapás Tartás!',
'⚓ 속박!':'⚓ Megkötés!',
'👤 분신!':'👤 Klón!',
'🖐 탈취!':'🖐 Lopás!',
'🔥🔥 용암 지대!':'🔥🔥 Láva Zóna!',
'🌧🌧 화염 폭격!':'🌧🌧 Tűz Bombázás!',
'⚡⚡ 전격 장막!':'⚡⚡ Villám Fátyol!',
'💀 내 곁으로!':'💀 Hozzám!',
'⭕ 안전!':'⭕ Biztonságos!',
'💀💀 전멸 폭발!':'💀💀 Megsemmisítő Robbanás!',
'⚡ 쐐기 소멸!':'⚡ Ék Eltűnés!',
'🌊충격파!':'🌊Lökéshullám!',
'👿악의+100':'👿Rosszindulat+100',
'💥패링폭발!':'💥Hárítás Robbanás!',
'균열 충돌! ':'Repedés Ütközés! ',
'벽 충돌! ':'Fal Ütközés! ',
'소환!':'Idézés!',
'환영!':'Fantom!',
'⚡낙뢰!':'⚡Mennydörgés!',
'⚡빔!':'⚡Sugár!',
'환영술!':'Illúzió!',
'💀소환!':'💀Idézés!',
'🔮주술!':'🔮Átok!',
'🩸산란!':'🩸Szaporodás!',
'💢광폭!':'💢Őrjöngés!',
'🕷산란!':'🕷Szaporodás!',
'❄서리!':'❄Dér!',
'❄빙결파!':'❄Fagyasztó Hullám!',
'💀빙마!':'💀Jég Démon!',
'돌진!':'Roham!',
'충격파!':'Lökéshullám!',
'독안개!':'Mérgező Köd!',
'연타!':'Sorozat!',
'포효!':'Üvöltés!',
'강화!':'Erősítés!',
'꼬리!':'Farok!',
'은신...':'Rejtőzés...',
'기습!':'Rajtaütés!',
'산란!':'Szaporodás!',
'독가스!':'Mérgező Gáz!',
'소멸...':'Feloszlás...',
'강타!':'Csapás!',
'분비!':'Kiválasztás!',
'채찍!':'Ostor!',
'출혈!':'Vérzés!',
'급강하!':'Zuhanás!',
'방출!':'Kibocsátás!',
'충격!':'Sokk!',
'치유!':'Gyógyítás!',
'의식!':'Szertartás!',
'지옥불!':'Pokoltűz!',
'끌려감!':'Elhúzva!',
'혀!':'Nyelv!',
'응시!':'Bámulás!',
'낙하!':'Zuhanás!',
'핏방울!':'Vércsepp!',
'일어남!':'Felállás!',
'휩쓸기!':'Söprés!',
'웅크림':'Összekuporodás',
'뼈칼날!':'Csont Penge!',
'감속!':'Lassítás!',
'비명!':'Sikoly!',
'화산탄!':'Vulkán Lövés!',
'자폭!':'Önrobbanás!',
'감싸기!':'Beburkolás!',
'잡기!':'Megragadás!',
'내리찍기!':'Lecsapás!',
'브레스!':'Lehelet!',
'비행!':'Repülés!',
'용암비!':'Láva Eső!',
'물뿜기!':'Vízsugár!',
'빛...':'Fény...',
'삼키기!':'Lenyelés!',
'마비!':'Bénulás!',
'방전!':'Kisülés!',
'집게찍기!':'Fogó Csapás!',
'찍기!':'Csapás!',
'붙잡기!':'Megragadás!',
'감아올리기!':'Feltekerés!',
'파편!':'Szilánk!',
'할퀴기!':'Karmolás!',
'기생충!':'Parazita!',
'심연 해방!':'Mélység Felszabadítás!',
'촉수난타!':'Csáp Ütlegelés!',
'삼지창!':'Háromágú!',
'소용돌이!':'Örvény!',
'해일!':'Cunami!',
'끼걱!':'Nyikorgás!',
'폭발!':'Robbanás!',
'체인!':'Lánc!',
'갈기!':'Sörény!',
'공포!':'Rettegés!',
'흡혈!':'Vérszívás!',
'베기!':'Vágás!',
'비이이명!!':'Csengés!!',
'분열!':'Hasadás!',
'3연참!':'Hármas Vágás!',
'패링!':'Hárítás!',
'...복사...':'...Másolás...',
'불균형...저주!':'Egyensúlyzavar...Átok!',
'저주!':'Átok!',
'균형...강화!':'Egyensúly...Erősítés!',
'심판의 기둥!':'Ítélet Oszlopa!',
'처형 선고!':'Halálos Ítélet!',
'고통의 해방!':'Fájdalom Felszabadítás!',
'너도 느껴봐라!':'Érezd te is!',
'대검난무!':'Nagykard Őrjöngés!',
'촉수!':'Csáp!',
'전방위 빔!':'Körbesugár!',
'회피!':'Kitérés!',
'[F] 상점':'[F] Bolt',
'거래 성공!':'Kereskedés Sikeres!',
'악의 부족! (':'Nincs elég Rosszindulat! (',
'상인이 떠납니다...':'A kereskedő elmegy...',
'사슬 해방!':'Lánc Felszabadítás!',
'완전 해방!':'Teljes Felszabadítás!',
'⏪ 시간 되감기!':'⏪ Idő Visszatekerés!',
'전환!':'Váltás!',
'부활 ':'Feltámadás ',
'🌀균열!':'🌀Repedés!',
'...사라짐':'...Eltűnt',
'낫 베기!':'Kasza Vágás!',
'☠ 죽음의 선고!':'☠ Halálos Ítélet!',
'선고 집행...':'Ítélet végrehajtás...',
'⚡패링!':'⚡Hárítás!',
'경직!':'Megmerevedés!',
'⚠ 잡혔다!':'⚠ Elkapva!',
'💥 내던지기!':'💥 Dobás!',
'💥 소용돌이 폭발!':'💥 Örvény Robbanás!',
'👻 순간이동!':'👻 Teleport!',
'💫 기절! 5초':'💫 Kábulás! 5mp',
'찌르기 반격!':'Szúrás Visszacsapás!',
'💢 폭발!':'💢 Robbanás!',
'반격 실패':'Visszacsapás Sikertelen',
'탈취 반격!':'Lopás Visszacsapás!',
'무기 봉인!':'Fegyver Lezárás!',
'냠!':'Nyam!',
'합체!':'Egyesítés!',
'출구가 열렸다!':'Kijárat megnyílt!',
'보물상자 출현!':'Kincsesláda megjelent!',
'출구':'Kijárat',
'⚠ 문지기가 살아있다!':'⚠ A kapuőr még él!',
'⏱ 타임어택 ':'⏱ Időtámadás ',
'처치율 ':'Legyőzés Arány ',
'불사 보호':'Halhatatlan Védelem',
'환영 소멸!':'Fantom Eltűnt!',
'부활력 ':'Feltámadás Erő ',
'✟ 신성력 억제! (':'✟ Szent Erő Elnyomva! (',
'부활 실패 (':'Feltámadás Sikertelen (',
'⚡순간이동!':'⚡Teleport!',
'👻 동반부활!':'👻 Társfeltámadás!',
'✟ 신성력 억제!':'✟ Szent Erő Elnyomva!',
'💀 부활 판정 중...':'💀 Feltámadás elbírálás...',
'⚔ 문지기 처치!':'⚔ Kapuőr Legyőzve!',
'🚪 보스방 개방!':'🚪 Főellenség Szoba Nyitva!',
'잔해 출현!':'Törmelék megjelent!',
'🌀균열 발생!':'🌀Repedés nyílt!',
'🔥복수!':'🔥Bosszú!',
'💥폭독혈!':'💥Pestis Vér!',
'빙판!':'Jégfelület!',
'❄최종빙결!':'❄Végső Fagyás!',
'빙마 처치!':'Jég Démon Legyőzve!',
'분리!':'Szétválás!',
'뼈 파편!':'Csont Szilánk!',
'태아 처치!':'Magzat Legyőzve!',
'지배자 처치!':'Uralkodó Legyőzve!',
'용암!':'Láva!',
'화룡 처치!':'Tűzsárkány Legyőzve!',
'최후의 비명!':'Utolsó Sikoly!',
'산화...':'Oxidálódás...',
'심판자 처치!':'Bíró Legyőzve!',
'고통의 왕 처치!':'Fájdalom Királya Legyőzve!',
'수역!':'Vízterület!',
'파편 폭발!':'Szilánk Robbanás!',
'거대어 처치!':'Leviatán Legyőzve!',
'대사도 처치!':'Főapostol Legyőzve!',
'독웅덩이!':'Mérgező Tó!',
'화염장판!':'Tűz Zóna!',
'전기장!':'Elektromos Mező!',
'무기 드롭!':'Fegyver Ejtés!',
'보물 발견!':'Kincs Találva!',
'상인의 주머니 +':'Kereskedő Erszénye +',
'속박의 파편!':'Megkötés Szilánkja!',
'시간의 조각!':'Idő Töredéke!',
'저주 해제!':'Átok Feloldva!',
'차원의 결정!':'Dimenziós Kristály!',
'전설 아이템!':'Legendás Tárgy!',
'죽음을 이겨냈다!':'Legyőzted a halált!',
'💥대폭발!':'💥Mega Robbanás!',
'⚡강화!':'⚡Erősítés!',
'장비 ':'Felszerelés ',
'💫 진동!':'💫 Remegés!',
'❄ 무적!':'❄ Sebezhetetelen!',
'👻 유령!':'👻 Szellem!',
'집중 해제!':'Koncentrálás Vége!',
'집중!':'Koncentrálás!',
'🕊️ 평화보호 ':'🕊️ Béke Védelem ',
'🛡 보호막 ':'🛡 Pajzs ',
'🌀 회전보호막 ':'🌀 Forgó Pajzs ',
'💥한방캡!':'💥Egylövés Korlát!',
'⚡쉴드 파괴!':'⚡Pajzs Megsemmisítve!',
'💀 불굴!':'💀 Megtörhetetlen!',
'💀 1회부활!':'💀 1x Feltámadás!',
'감시 회수':'Őr Visszahívás',
'악마화 부활!':'Démon Feltámadás!',
'배정 가능한 스킬 없음':'Nincs kiosztható képesség',
'칼날 없음!':'Nincs Penge!',
'⚔ 악의사냥!':'⚔ Rosszindulat Vadászat!',
'❄🌪️ 얼음소용돌이!':'❄🌪️ Jég Örvény!',
'🌪️ 폭풍소환!':'🌪️ Örvény Idézés!',
'🦴 해골무덤!':'🦴 Csont Sírbolt!',
'🌹 붉은꽃!':'🌹 Bíbor Virág!',
'💥 폭산탄!':'💥 Robbanó Lövés!',
'🪡 바늘출!':'🪡 Tűlövés!',
'⚡ 전격이동!':'⚡ Villám Lépés!',
'기둥가시로 흡수됨':'Oszloptüske által elnyelve',
'🌿 가시덫!':'🌿 Tüskecsapda!',
'👻 유령총!':'👻 Szellem Fegyver!',
'💥 유령총 폭발!':'💥 Szellem Fegyver Robbanás!',
'⚡ 전격의창!':'⚡ Villám Lándzsa!',
'🏹 공성쇠뇌 설치!':'🏹 Ostrom Számszeríj Elhelyezve!',
'👻 유령 허수아비!':'👻 Szellem Bábu!',
'💥 폭발 허수아비!':'💥 Robbanó Bábu!',
'축적!':'Tárolva!',
'축적 중...':'Tárolás...',
'만충! 재입력→폭발':'Tele! Újra nyomva→Robbanás',
'폭발! ':'Robbanás! ',
'뎀':' SEB',
'🩸 폭독칼날!':'🩸 Pestis Penge!',
'⚡날개치기!':'⚡Szárnycsapás!',
'🗡 칼등날개!':'🗡 Pajzsszárny!',
'🏛️ 악의기둥!':'🏛️ Sötét Oszlop!',
'🌿 기둥가시!':'🌿 Oszlop Tüske!',
'🌋 지옥강타!':'🌋 Pokol Csapás!',
'💥 체간 붕괴!':'💥 Tartás Összeomlás!',
'💫 포이즈 파괴!':'💫 Tartás Megsemmisítve!',
'⚡ 뇌전걸음!':'⚡ Szellemjárás!',
'✟ 구속의 영역!':'✟ Kötés Terület!',
'✟ 신성폭발!':'✟ Szent Robbanás!',
'⛧ 블랙!':'⛧ Fekete Csillag!',
'🌋 용암소환!':'🌋 Láva Idézés!',
'필살기 배정!':'Elsöprő Kiosztva!',
'완료':'Kész',
'합체 가능':'Egyesíthető',
'부족':'Hiányzik',
'SP 부족! (':'SP kell! (',
'🕊️ 히든: 평화의보호 해금!':'🕊️ Rejtett: Béke Védelme feloldva!',
'⚡ 히든: 참회 해금!':'⚡ Rejtett: Bűnbánat feloldva!',
'배정됨':'Kiosztva',
'합체 Lv.':'Egyesítés Sz.',
'◆ 같은 보석 스킬 습득 시 합체 가능':'◆ Ugyanazon drágakő képesség tanulásakor egyesíthető',
'▼ 가방 → 창고 보관':'▼ Táska → Raktár',
'▲ 창고 → 가방 꺼내기':'▲ Raktár → Táska',
'✓ 선택됨':'✓ Kiválasztva',
'⟨ 입력 대기... ⟩':'⟨ Várakozás... ⟩',
'⟨ 대기 ⟩':'⟨ Várakozás ⟩',
'보조':'Segéd',
'키 설정 초기화 (또는 F5 키)':'Billentyű Visszaállítás (vagy F5)',
'아무 키 또는 마우스 버튼을 누르세요 (ESC = 취소)':'Nyomj bármilyen billentyűt vagy egérgombot (ESC = mégse)',
'WebGPU 활성':'WebGPU Aktív',
'WebGL2 활성':'WebGL2 Aktív',
'측정 중...':'Mérés...',
'불러오기 실패':'Betöltés Sikertelen',
'장착':'Felszerelve',
'🔒 중요잠금 아이템은 분해 선택 불가!':'🔒 Fontos-zárolt tárgyak nem szedhetők szét!',
'장비 강화 (실패 시 재료만 소멸)':'Felszerelés Fejlesztés (kudarc: anyag elvész)',
'강화 보너스 적용':'Fejlesztés Bónusz Alkalmazva',
'강화 실패!':'Fejlesztés Sikertelen!',
'장착된 장비가 없습니다.':'Nincs felszerelt tárgy.',
'충분':'Elég',
'더 필요':'Több Kell',
'장비 선택':'Felszerelés Választás',
'목표치 설정':'Cél Beállítás',
'악의 투입':'Rosszindulat Befektetés',
'자동 시도':'Auto Próba',
'목표 강화치':'Cél Fejlesztési Szint',
'예상 필요 악의':'Becsült Rosszindulat Igény',
'보유':'Birtokolt',
'강화 시작':'Fejlesztés Indítás',
'위에서 장비를 선택하세요':'Válassz felszerelést fent',
'⬆ 물약 강화 (최대 10단)':'⬆ Bájital Fejlesztés (max 10 szint)',
'필요':'Szükséges',
'악의의 분해로 — 장비를 악의로 갈아버려라':'Rosszindulat Kemence — Őröld felszereléssé a rosszindulatot',
'전체 선택':'Összes Kiválasztás',
'전체 해제':'Összes Törlés',
'희귀 이하':'Ritka vagy alatta',
'어픽스 리롤!':'Tulajdonság Újradobás!',
'영웅':'Hősi',
'전설':'Legendás',
'무기 타입':'Fegyver Típus',
'활 타입':'Íj Típus',
'ST 부족':'Nincs elég ST',
'💀 광폭화!':'💀 Dühöngés!',
'...따라오는 거 아니야. 같은 방향일 뿐이지.':'...Nem követlek. Csak egy irányba megyünk.',
'공기가 달라졌어. 더 썩었군.':'A levegő megváltozott. Rothadtabb.',
'여기부터는 악마 영역이야. ...맘대로 해.':'Innentől démon terület. ...Csinálj, amit akarsz.',
'...이 냄새. 살점이 썩는 냄새야.':'...Ez a szag. Rothadt hús.',
'여기 오래 있으면 미쳐. 나도, 너도.':'Sokáig maradni őrültséget hoz. Nekem is, neked is.',
'이 길의 끝에 뭐가 있을까. ...알고 싶지도 않어.':'Mi van az út végén? ...Nem is akarom tudni.',
'...여기가 끝이야. 돌아갈 길은 없어.':'...Ez a vég. Nincs visszaút.',
'작살을 땅에 꽂으면 끌려간다.':'Ha a szigonyt a földbe szúrod, húzva leszel.',
'Shift로 작살 던져봐!':'Próbáld ki a Shift-et a szigonyhoz!',
'패링 성공하면 ST가 회복된다. 공짜 자원이야.':'Sikeres hárítás ST-t ad. Ingyenes erőforrás.',
'패링 많이 하면 ST 걱정 없어~':'Sokat hárítva soha nem fogy el az ST~',
'장비 분해하면 악의를 얻는다. 쓰레기도 자원이야.':'Felszerelés szétszedése rosszindulatot ad. A szemét is erőforrás.',
'TAB 열어서 안 쓰는 장비 분해해!':'TAB-bal bontsd szét a felesleges felszerelést!',
'그로기 상태의 적에겐 1.5배 데미지가 들어간다.':'Kótyagos ellenségekre 1.5× sebzés jár.',
'무릎 꿇으면 전력으로 때려!':'Ha letérdelnek, üss teljes erővel!',
'속성 상성이 있다. 화염은 빙결에 약하고, 암전은 암흑에 약하다.':'Az elemeknek van gyengéjük. Tűz gyenge jéggel szemben, villám sötéttel.',
'무기 속성 바꿔가면서 싸워봐!':'Próbálj fegyver elemeket váltogatni!',
'빙결된 적은 1.5배 데미지를 받는다.':'Befagyott ellenségek 1.5× sebzést kapnak.',
'얼리고 때리는 게 기본이야!':'Fagyaszd be és üsd — ez az alap!',
'보스의 빨간 공격은 패링 가능. 보라빛은 회피만.':'Főellenség piros támadásai háríthatók. Szivárványt csak kitérni.',
'색깔 잘 봐! 빨강은 받아치고 무지개는 피해!':'Figyelj a színekre! Pirosat hárítsd, szivárványt kerüld!',
'VIT를 올리면 최대 HP가 오른다. 죽기 싫으면 찍어.':'VIT emelése max HP-t ad. Fektesd be, ha élni akarsz.',
'STR은 근접, DEX는 활, INT는 마법! 골고루 말고 하나만!':'STR közelharc, DEX íj, INT mágia! Egyre koncentrálj!',
'E를 꾹 누르면 빔이 나간다. 짧게 누르면 투사체.':'E tartva sugár. E röviden lövedék.',
'마법 쓸 때 MP 잘 봐! 빔은 연속으로 깎여!':'Mágiánál figyeld az MP-t! A sugár folyamatosan fogyasztja!',
'핵터와 디로이가 아이템을 주워준다. 수거 범위 안이면.':'Hector és Deroy felszedik a tárgyakat hatótávon belül.',
'우리한테 고마워해~ 안 주우면 썩잖아.':'Légy hálás nekünk~ Ha nem szedik fel, elrothadnak.',
'LCK를 올리면 레어 드롭률이 오른다.':'LCK emelése növeli a ritka ejtési esélyt.',
'운빨 게임이긴 하지~ LCK 올려봐!':'Szerencsejáték ez~ Próbáld emelni az LCK-t!',
'강화하면 공격력이 쭉쭉 올라가! 악의만 있으면 돼!':'Fejlesztés gyorsan emeli a támadást! Csak rosszindulat kell!',
'강화 확률은 +1에서 99%. 높을수록 떨어진다.':'Fejlesztés esélye +1-nél 99%. Magasabbnál csökken.',
'실패하면 악의만 날아가~ 장비는 안 부서져!':'Kudarc esetén csak a rosszindulat vész el~ A felszerelés megmarad!',
'대장간에서 장비 제작도 된다. 악의 30000개면 영웅급 이상.':'A kovácsban készíthetsz felszerelést. 30000 rosszindulattal hősi+.',
'랜덤이지만 좋은 거 나올 수도 있어!':'Véletlenszerű, de jó is jöhet!',
'쉴드는 마법으로, HP는 물리로 깎아야 제대로 먹힌다.':'Pajzsot mágiával, HP-t fizikailag kell csökkenteni.',
'반대로 치면 50%만 들어가! 무기 바꿔가면서 싸워!':'Rossz típussal csak 50%! Váltogasd a fegyvereket!',
'장비에 접두사, 접미사가 붙으면 특수 효과가 생긴다.':'Felszerelésre előtag/utótag kerülhet, ami különleges hatást ad.',
'영웅급 이상 장비에만 붙어! 좋은 거 나오면 강화해!':'Csak hősi+ felszerelésen! Ha jó dob jön, fejleszd!',
'강화는 장비를 바꿔도 자동 이전된다. 악의만 있으면.':'Fejlesztés automatikusan átkerül új felszerelésre. Csak rosszindulat kell.',
'더 좋은 장비 나오면 바로 장착해! 강화 수치 그대로 옮겨가!':'Ha jobb jön, egyből vedd fel! A fejlesztés vele megy!',
'패링을 써야 자원을 흡수한다고!':'Hárítanod kell az erőforrások elnyeléséhez!',
'F키 회복의 영역을 써봐. 자원이 차올라.':'Próbáld az F gomb Szent Területet. Erőforrások feltöltődnek.',
'적이 근접하면 스페이스키야! 가시덫을 활용해!':'Ha közel az ellenség, Space! Használd a Tüskecsapdát!',
'기절시켜! 그로기가 터지면 데미지가 1.5배야!':'Kábítsd el! Kótyagos állapotban 1.5× sebzés!',
'1번 대왕치기로 밀어버려!':'1-es Óriás Csapással told el!',
'무릎 꿇었다.':'Letérdelt.',
'지금이야! 몰아쳐!!':'Most! Támadj!!',
'스킬 포인트 있어! K 눌러서 스킬 찍어봐!':'Van képességpontod! K gombbal tanulj!',
'...힘이 없으면 여기서 끝이야.':'...Erő nélkül itt a vége.',
'...쓸 거 아니면 분해해.':'...Ami nem kell, szedd szét.',
'아이템 넘쳐나네~ 우리가 주워줄게!':'Annyi tárgy~ Mi összeszedjük!',
'악의가 바닥이다.':'Elfogyott a rosszindulat.',
'TAB 열어서 장비 분해해! 쓰레기도 악의가 돼!':'TAB-bal bontsd szét! A szemét is rosszindulattá válik!',
'좋은 장비가 있네! G 눌러서 대장간 가봐!':'Jó felszerelés van! G gomb a kovácshoz!',
'...강화 안 하면 그냥 고철이야.':'...Fejlesztés nélkül csak ócskafém.',
'...멈추지 마. 여신은 기다리지 않는다.':'...Ne állj meg. Az istennő nem vár.',
'앞으로 가자~ 나도 여기 오래 있기 싫어.':'Menjünk tovább~ Én sem akarok itt maradni.',
'...냄새가 짙다. 큰 놈이 있어.':'...Erős a szag. Valami nagy van itt.',
'준비됐어? 물약 확인하고!':'Kész vagy? Ellenőrizd a bájitalokat!',
'TAB을 눌러. 가방을 열고 장비를 입어야 한다.':'Nyomd meg a TAB-ot. Nyisd ki a táskát és vedd fel a felszerelést.',
'주웠으면 껴야지! TAB!':'Ha felszedted, vedd fel! TAB!',
'G. 대장간에서 물약도 제작할 수 있다.':'G. A kovácsban bájitalt is készíthetsz.',
'악의로 물약 만들어! G키야!':'Készíts bájitalt rosszindulatból! G gomb!',
'기절이야! Ctrl 눌러!':'Elkábultál! Ctrl!',
'Ctrl 유령걸음으로 탈출!':'Ctrl Szellemjárással menekülj!',
'Ctrl 얼음보주로 탈출!':'Ctrl Jéggömbbel menekülj!',
'빨간 탄은 우클릭 패링. 무지개는 Q 패링.':'Piros lövedék: jobb klikk hárítás. Szivárvány: Q hárítás.',
'나머지는 전부 우클릭 패링 가능해!':'A többit mind jobb klikkel háríthatod!',
'빨강=우클릭, 무지개=Q 패링. 나머진 다 쳐내.':'Piros=jobb klikk, szivárvány=Q hárítás. A többit verd vissza.',
'무지개는 Q로 패링! 나머지는 전부 우클릭!':'Szivárványt Q-val hárítsd! A többit mind jobb klikkel!',
'빠져! 물약 마시고 안전한 곳에서 회복해.':'Menekülj! Igyál bájitalt és gyógyulj biztonságban.',
'자원 없으면 도망가는 게 답이야!':'Ha nincs erőforrás, a menekülés a válasz!',
'스페이스! 가시덫으로 적 묶어버려!':'Space! Tüskecsapdával fogd meg az ellenséget!',
'근접이 너무 많아! 거리 벌려!':'Túl sok közeli ellenség! Tartsd a távolságot!',
'...둘러싸이면 끝이야. 빠져나와.':'...Ha bekerítik, vége. Törj ki.',
'1번 대왕치기로 쓸어버려!':'1-es Óriás Csapással söpörd el!',
'그로기 터지면 데미지 1.5배!':'Kótyagos kiváltva 1.5× sebzés!',
'회전참이나 광역기로 몰아! 한 놈씩 상대하면 죽어.':'Forgószéllel vagy területivel támadj! Egyenként meghalsz.',
'뭉쳐있을 때가 기회야!':'Ha összegyűlnek, az a lehetőség!',
'E로 마력공격을 해봐! 악의 쉴드를 해제할려면 마법 공격을 해야 해!':'E-vel használj mágiát! A rosszindulat pajzsot mágiával kell törni!',
'쉴드는 마법으로, HP는 물리로. 반대로 치면 데미지 안 들어간다.':'Pajzsot mágiával, HP-t fizikailag. Fordítva nincs sebzés.',
'L키로 스킬 슬롯에 넣어야 쓸 수 있어.':'L gombbal oszd be a képességeket a helyekre.',
'C키를 눌러. 패시브 포인트가 쌓여있다.':'Nyomd meg a C-t. Passzív pontok gyűltek.',
'C키! 패시브 올리면 진짜 강해져!':'C gomb! Passzívokkal igazán erőssé válsz!',
'스태미나가 부족하다. 무리하지 마.':'Kevés a kitartás. Ne erőltesd.',
'ST 없으면 스킬 못 써! 잠깐 빠져!':'ST nélkül nincs képesség! Húzódj vissza!',
'탭 장비창을 열어봐. 아이템을 주워왔어!':'Nyisd meg a TAB felszerelés menüt. Szedtünk tárgyakat!',
'좋은 거 나왔다! TAB 열어서 확인해봐!':'Valami jó jött! TAB-bal nézd meg!',
'악의에 중독되면 악마가 돼서 부활력이 생긴대. 저 녀석처럼.':'Állítólag a rosszindulat-függőség démonná változtat, feltámadás erővel. Mint az ott.',
'혹시 너도...?':'Talán te is...?',
'데미지가 부족하면 무기류 강화를 해야해!!':'Ha a sebzés kevés, fejleszd a fegyvereket!!',
'G키 대장간. 강화 안 하면 여기서 계속 죽어.':'G gomb kovács. Fejlesztés nélkül itt fogsz meghalni.',
'시간이 없어. 움직여.':'Nincs idő. Mozogj.',
'멍하게 서있으면 안 돼!':'Ne állj bambán!',
'...뭘 기다리는 거야?':'...Mire vársz?',
'가자가자! 몬스터가 기다려!':'Gyerünk! A szörnyek várnak!',
'여기 오래 있으면 위험해.':'Sokáig itt maradni veszélyes.',
'움직여야 해! 가만있으면 둘러싸여!':'Mozognod kell! Állva bekerítik!',
'쉬는 건 죽고 나서 해.':'Pihenj a halál után.',
'살아있을 때 쉬면 안 돼!':'Életben nem pihenhetsz!',
'적이 몰려오고 있어. 빨리 움직여.':'Az ellenségek közelednek. Gyorsan mozogj.',
'냄새 맡고 올 거야. 빨리!':'Megszagolnak. Siess!',
'...아직 살아있는 거 맞지?':'...Még élsz, ugye?',
'혹시 잠든 거야...?':'Elaludtál...?',
'...나무가 썩어가고 있어. 여기는 지옥의 입구야.':'...A fák rothadnak. Ez a pokol bejárata.',
'냄새 지독해... 빨리 지나가자.':'Rettenetes szag... Gyorsan haladjunk.',
'조심해. 벌레굴이다. 벽이랑 바닥에서 기어나와.':'Vigyázz. Féregjárat. A falakból és padlóból másznak elő.',
'으으... 벌레 싫어! 밟아버려!':'Ugh... Utálom a férgeket! Taposs rájuk!',
'...공기가 얼어붙는다. 여기선 화염이 먹힌다.':'...A levegő megfagy. Itt a tűz hatásos.',
'추워... 빙결 조심해! 얼면 끝이야.':'Hideg... Vigyázz a fagyással! Ha befagysz, vége.',
'용암이다. 바닥을 밟으면 타 죽어.':'Láva. Ha rálépesz, elégeti.',
'뜨거워! 여기 왜 이렇게 빨개!':'Forró! Miért olyan piros itt minden!',
'...군단이다. 수가 많아. 광역기 없으면 밀려.':'...A légió. Sokan vannak. Területi nélkül lenyomnak.',
'우글우글... 징그러워. 한꺼번에 쓸어!':'Hemzseg... Gusztustalan. Söpörd el egyszerre!',
'사도의 영역이야. 여기 놈들은 머리가 좋아.':'Apostol területe. Ezek okosak.',
'패턴이 복잡해졌어... 집중해!':'A minták bonyolultabbak lettek... Koncentrálj!',
'...끝이다. 지옥의 심장부. 살아 돌아가는 건 포기해라.':'...Ez a vég. A pokol szíve. Add fel a visszatérés reményét.',
'여기가 마지막이야... 각오해.':'Ez az utolsó... Készülj fel.',
'석궁 자동발사 (T)':'Számszeríj automatikus (T)',
'버스트루프 당기기 (H)':'Robbanás-hurok vonz (H)',
'결정 자동합성':'Kristály auto-szintézis',
'결정 자동강화':'Kristály auto-erősítés',
'✓ 설정 자동 저장':'✓ Beállítások automatikusan mentve',
'세팅 프리셋 저장/불러오기':'Előbeállítás mentése/betöltése',
'세팅1 저장':'1. előbeállítás mentése','세팅1':'1. előbeállítás',
'세팅2 저장':'2. előbeállítás mentése','세팅2':'2. előbeállítás',
'재진단':'Újradiagnosztika',
'게임 리셋 (처음부터)':'Játék visszaállítása (elejétől)',
'캐릭터 선택 (로비)':'Karakter kiválasztása (Lobby)',
'닫기 [ESC]':'Bezárás [ESC]','닫기 [G]':'Bezárás [G]','닫기 [V]':'Bezárás [V]','닫기 [C]':'Bezárás [C]',
'전체화면 (F11)':'Teljes képernyő (F11)',
'정말 모든 진행을 초기화하시겠습니까?':'Valóban visszaállítod az összes haladást?',
'검출 중...':'Észlelés...',
'마우스 커서':'Egérkurzor','그래픽 품질':'Grafikai minőség','하드웨어 진단':'Hardver diagnosztika',
'BGM 선택':'BGM kiválasztása',
'자동 (스테이지별)':'Automatikus (szint szerint)','전체 랜덤':'Minden véletlenszerű','로비':'Lobby',
'1장 랜덤':'1. fejezet véletlenszerű','2장 랜덤':'2. fejezet véletlenszerű','3장 랜덤':'3. fejezet véletlenszerű',
'4장 랜덤':'4. fejezet véletlenszerű','5장 랜덤':'5. fejezet véletlenszerű','6장 랜덤':'6. fejezet véletlenszerű','7장 랜덤':'7. fejezet véletlenszerű',
'보스':'Főellenség','최종보스':'Végső főellenség',
'대장간 랜덤':'Kovácsműhely véletlenszerű','사망 랜덤':'Halál véletlenszerű','승리 랜덤':'Győzelem véletlenszerű',
'지옥 추락 사망 징글':'Pokol zuhanás halál jingle','탈출 성공':'Menekülés sikeres',
'── 1장 - 썩은 숲 ──':'── CH1 - Rotten Forest ──','── 2장 - 벌레굴 ──':'── CH2 - Worm Nest ──',
'── 3장 - 얼음굴 ──':'── CH3 - Ice Cavern ──','── 4장 - 화염지대 ──':'── CH4 - Infernal Wastes ──',
'── 5장 - 지옥군단 ──':'── CH5 - Hell Legion ──','── 6장 - 사도마굴 ──':'── CH6 - Apostle Den ──',
'── 7장 - 지옥성 ──':'── CH7 - Hell Citadel ──','── 공통 ──':'── Common ──',
'⌨ 조작법':'⌨ Vezérlés','클릭하면 닫힘':'Kattints a bezáráshoz',
'전투력':'HE','가방':'Táska','결정':'Kristály',
'↕ 정렬':'↕ Rendezés','쓰레기 전체선택':'Összes szemét kijelölése','쓰레기 전부 분해':'Összes szemét szétszerelése',
'창고':'Raktár','스탯 포인트':'Attribútum pontok','능력치 요약':'Statisztika összefoglaló','올 리셋':'Összes visszaállítása',
'대장간':'Kovácsműhely','스킬':'Képességek','능력치':'Attribútumok',
'좌클스킬 (클릭 전환)':'BKM képesség (katt. a váltáshoz)','우클스킬 (클릭 전환)':'JKM képesség (katt. a váltáshoz)',
'이동스킬 (클릭 전환)':'Mozgás képesség (katt. a váltáshoz)','마법스킬 (클릭 전환)':'Mágikus képesség (katt. a váltáshoz)',
'영역스킬 (클릭 전환)':'Terület képesség (katt. a váltáshoz)','피보호막 (클릭 전환)':'Vérpajzs (katt. a váltáshoz)',
'CT스킬 (클릭 전환)':'CT képesség (katt. a váltáshoz)','[C] 능력치':'[C] Attribútumok',
'무기 공격':'Fegyveres támadás','칼등 처내기 (투사체 반사, 홀드 연사)':'Hárítás (visszaveri lövedékek, tart=sorozat)',
'연속 처내기':'Folyamatos hárítás','영역 스킬 (폭풍소환 등)':'Terület képesség (Örvény stb)',
'작살 발사':'Szigony lövés','마법 (탭=투사체, 홀드=빔)':'Mágia (érint=lövedék, tart=sugár)',
'데빌포스 흡수':'Ördögi erő elnyelése','물약 / 스킬슬롯':'Bájitalok / Képességhelyek',
'스킬슬롯 5 / 필살기 / CT스킬':'Hely 5 / Végső / CT képesség','스킬 슬롯 배정':'Hely kiosztása',
// --- Phase 27 additions ---
'위로 이동':'Mozgás felfelé','아래로 이동':'Mozgás lefelé','왼쪽 이동':'Mozgás balra','오른쪽 이동':'Mozgás jobbra',
'칼등 처내기 (탭=처내기, 홀드=연사)':'Pengeparírozás (koppintás=paríroz, tartás=sorozat)',
'영역 스킬':'Terület képesség','작살 이동':'Szigony Dash',
'유령불꽃 켜기/끄기':'Szellemláng Be/Ki','기동칼날개 자동 켜기/끄기':'Pengeszárny Auto Be/Ki',
'해상도':'Felbontás',
'빛이 꺼졌다':'A Fény Kialszik','누군가는 너를 기다리고 있다':'Valaki vár rád',
'다시 일어서라':'Kelj fel újra','로비로 돌아가기':'Vissza a Lobbyba',
'☠ 사망 리플레이':'☠ Halál Visszajátszás',
'지옥의 시련을 견뎌냈다':'Kiállottad a Pokol próbáját',
'계속 전투':'Harc Folytatása','난이도를 선택하라':'Válassz nehézséget',
'나중에 설정(ESC)에서 변경 가능':'Később módosítható a Beállításokban (ESC)',
'일괄합성':'Tömeges Szintézis','일괄강화+합성':'Tömeges Fejlesztés+Szintézis',
'자원 부족!':'Erőforrás Kevés!',' 뎀':' Seb',
'합체 폭발!':'Fúziós Detonáció!',
'MP 부족! (50)':'Nincs elég MP! (50)',
'부활력 고갈!':'Feltámadás Kimerült!','☠ 부활력 고갈!':'☠ Feltámadás Kimerült!',
'독안개':'Mérgező Köd','뇌전창':'Mennydörgő Lándzsa',
'🔥 업화선 시전...':'🔥 Pokol Sugár készülés...',
'💥 기동파괴 그로기!':'💥 Lánc Rombolás Groggy!',
'💥 칼등 그로기!':'💥 Pengeparírozás Groggy!',
'⚡ 순간이동 준비!':'⚡ Teleportálás Kész!',
'👿악의+1000':'👿Gonoszság+1000',
'💀 내려찍기!':'💀 Lecsapás!',
'✟ 신성력 억제! +':'✟ Szent Erő Elnyomva! +',
'✟ 신성력 억제!':'✟ Szent Erő Elnyomva!',
'✟ 신성력 억제! (':'✟ Szent Erő Elnyomva! (',
'💥 지진그로기!':'💥 Földrengés Groggy!',
'💥 기폭그로기!':'💥 Detonáció Groggy!',
'폭발! ×':'Robbanás! ×','⚫ 기둥강타!':'⚫ Oszlopcsapás!',
'💥 대왕치기 그로기!':'💥 Kolosszális Groggy!',
'💫 미니스턴!':'💫 Mini Stun!','⚡ 뇌전창!':'⚡ Mennydörgő Lándzsa!',
'…절반이다. 정신차려.':'…Félúton. Szedd össze magad.',
'…죽기 직전이다. 한 발만 더.':'…Majdnem halott. Még egy ütés.',
'…다음 한 방이 마지막이야.':'…A következő ütés az utolsó.',
'기절! ':'Elkábítva! ',
'마력이 빈다. 평타 섞어.':'Az MP kiürül. Keverj normál támadásokat.',
'그랩이다. 거리를 둬.':'Megragadó támadás. Tartsd a távolságot.',
'광역기다. 멀어져.':'Területi támadás. Távolodj.',
'…아파? 당연하지. 여긴 지옥이야.':'…Fáj? Természetesen. Ez a pokol.',
'F키도 스킬 슬롯이야!':'Az F is egy képességhely!',
'L-CTRL로 유령걸음/얼음보주!':'L-CTRL Szellemjáráshoz / Jéggolyóhoz!',
'V 눌러서 창고에 넣어둬!':'Nyomd meg V-t tároláshoz!',
'ESC로 설정! 난이도/자동물약!':'ESC a beállításokhoz! Nehézség/Auto-italok!',
'잡몹이다. 먼저 정리해.':'Közönséges ellenségek. Tisztítsd el őket először.',
'…얼어붙은 놈은 오래 안 간다.':'…Egy lefagyasztott ellenség nem tart sokáig.',
'…냄새가 짙다. 큰 놈이 있어.':'…Az illat erős. Valami nagy van közel.',
'쉴드는 마법으로, HP는 물리로.':'A pajzs mágiát vesz fel, a HP fizikait.',
'스페이스! 가시덫으로 적 묶어!':'Szóköz! Fogd be az ellenségeket Tüskefogóval!',
'근접 너무 많아! 거리 벌려!':'Túl sok van közel! Szóródj szét!',
'회전참이나 광역기로 몰아!':'Használj Forgócsapást vagy Területet!',
'F 눌러! 회복의 영역 깔아!':'Nyomd F-et! Fektess le Szent Tartományt!',
'F키 회복의 영역을 써봐.':'Próbáld ki az F-billentyű Szent Tartományát.',
'빠져! 물약 마시고 회복해.':'Vonulj vissza! Igyál italokat és regenerálódj.',
'쉬프트! 사슬기동은 이동기야!':'Shift! A Lánc Dash egy mozgáseszköz!',
'스킬포인트 쌓였어! K 눌러!':'Képességpontok készen! Nyomd K-t!',
'스킬 포인트 있어! K!':'Képességpontok! K!',
'C키. 패시브 포인트가 쌓여있다.':'C-billentyű. Passzív pontok felhalmozódtak.',
'…쓸 거 아니면 분해해.':'…Szedd szét amit nem használsz.',
'…강화 안 하면 그냥 고철이야.':'…Fejlesztés nélkül csak ócskavas.',
'빨간 탄은 우클릭. 무지개는 Q.':'Piros lövedékek: jobb egérgomb. Szivárvány: Q.',
'빨강=우클릭, 무지개=Q.':'Piros=jobb egérgomb, szivárvány=Q.',
'…멈추지 마. 여신은 기다리지 않는다.':'…Ne állj meg. Az istennő nem vár.',
'패턴이 바뀐다. 거리를 둬.':'A minta változik. Tartsd a távolságot.',
'미쳐가고 있어. 광폭화다.':'Megőrül. Dühöngő mód.',
'마지막이야! 끝장내!':'Utolsó fázis! Fejezd be!',
'…끝났다. 다음으로.':'…Vége. Tovább.',
'다 잡았다! 포탈 어딨어?':'Mindenki megvan! Hol van a portál?',
'근육으로 만든 빌드군. 베고 부숴.':'Izomépítmény. Vágj és törj.',
'활을 쥐었군. 거리를 둬.':'Íj a kézben. Tartsd a távolságot.',
'마법사군. MP 관리부터 배워라.':'Varázsló. Előbb tanuld meg az MP-kezelést.',
'운에 기댄 빌드군. …드롭은 좋겠어.':'Szerencsén alapuló építmény. …Legalább a drops jó lesz.',
'…VIT가 너무 낮아. 한 방에 죽는다.':'…A VIT túl alacsony. Egy ütéssel meghalsz.',
'다 찍으면 다 약해진다. 하나만 골라.':'Mindent maximalizálsz és mindenhol gyenge leszel. Válassz egyet.',
'…3단. 적이 강해져. 정신 차려.':'…3. szakasz. Az ellenségek erősebbek. Fókuszálj.',
'5단이다. …너도 강해졌단 뜻이야.':'5. szakasz. …Ez azt jelenti, hogy te is megerősödtél.',
'…7단. 아직 살아있단 게 신기하군.':'…7. szakasz. Még mindig életben. Meglepő.',
'10단. …너는 이제 인간이 아니야.':'10. szakasz. …Már nem vagy ember.',
'…일반으로 내려왔군. 가끔은 쉬어가야지.':'…Vissza Normálba. Néha szükség van egy szünetre.',
'…이게 진짜 패링이야.':'…Ez egy igazi parírázás.',
'…피가 묻기 시작했군.':'…A vér kezd folyni.',
'100. 너는 인간이 아니야.':'100. Nem vagy ember.',
'…피 흘리며 베는군.':'…Vágás vérön át.',
'빨간콩이 푸르게 변했다. 그게 너의 무기야.':'A piros golyó kékké vált. Ez a te fegyvered.',
'무지개를 받아쳤군. 그건 진짜 어렵다.':'Parírázál egy szivárványt. Ez tényleg nehéz.',
'…너무 빨라. 닿기 직전에 눌러.':'…Túl gyors. Nyomd meg éppen érintkezés előtt.',
'악의가 가득 찼다. 풀어내.':'A Gonoszság tele van. Engedd szabadon.',
'작살이 살을 뚫었어. 끌고 와.':'A szigony áthatolt a húson. Húzd be.',
'…풀차지군. 멀리 던져버려.':'…Teljesen feltöltve. Dobd messzire.',
'…빈틈을 그대로 빠져나갔다.':'…Egyenesen átcsúszott a résen.',
'…일반 잡몹이 아니야. 모디파이어 붙었군.':'…Nem közönséges ellenség. Van egy módosítója.',
'엘리트 하나 처리.':'Elit le.',
'…큰 놈이다. 일반 잡몹 정리부터.':'…Nagy egy. Tisztítsd el előbb a közönséges ellenségeket.',
'미니보스 처리. 다음 길로.':'Mini-boss le. A következő útra.',
'한 번에 다섯. 깔끔해.':'Öt egyszerre. Tiszta.',
'100강. 이제 뭔가 다르게 보이는군.':'+100. A dolgok most másképp néznek ki.',
'…운이 없는 날이야.':'…Szerencsétlen nap.',
'…전설이다. 이런 건 처음 본다.':'…Legendás. Sosem láttam ilyet.',
'…죽었다 살아났네. 여신은 너를 포기 안 했어.':'…Meghalt és visszatért. Az istennő nem adta fel.',
'…또야? 패턴 좀 외워!':'…Megint? Tanuld meg a mintát!',
'…한 번도 안 죽고. 그건 진짜 실력이야.':'…Egyszer sem halt meg. Ez igazi tudás.',
'…ACT1을 끝냈다. 진짜 시작은 여기서부터야.':'…ACT1 kész. Az igazi kezdet innen van.',
'모든 보스를 무너뜨렸다. 너는 지옥의 일부야.':'Minden boss elesett. A pokol része vagy.',
'…30초. 너 진짜 미쳤구나.':'…30 másodperc. Tényleg őrült vagy.',
'…빠르군. 효율적이야.':'…Gyors. Hatékony.',
'신기록이다.':'Új rekord.',
'탭 장비창을 열어봐.':'Nyisd meg a felszerelés ablakot TAB-bal.',
'데미지 부족하면 무기 강화!':'Nincs elég sebzés? Fejleszd a fegyvert!',
// --- Loading screen ---
'불러오는 중...':'Betöltés...',
'로딩중...':'Betöltés...',
'맵과 몬스터 불러오는 중...':'Térkép és szörnyek betöltése...',
'기본 데이터 준비 중...':'Alap adatok előkészítése...',
'저장 데이터 불러오는 중...':'Mentett adatok betöltése...',
'몬스터 스킨 로딩...':'Szörny skinek betöltése...',
'맵과 몬스터 생성 중...':'Térkép és szörnyek generálása...',
'맵 에셋 로딩...':'Térkép erőforrások betöltése...',
'맵 환경 준비 중...':'Térkép környezet előkészítése...',
'주변 청크 준비 중...':'Közeli chunkok előkészítése...',
'맵 캐시 생성 중...':'Térképgyorsítótár felépítése...',
'미니맵 빌드 중...':'Minimap felépítése...',
// Phase 28
' 으로 탈출!':' a meneküléshez!',
'100명?! 미쳤어!':'100 legyilkolva?! Őrültség!',
'10단 최고난이도! 너 진짜 광기야!':'10-es nehézség max! Teljesen őrült!',
'1분 안에 클리어! 빠르네!':'1 percen belül teljesítve! Olyan gyors!',
'30초!! 스피드런 가능해!':'30 másodperc!! Speedrun potenciál!',
'3단! 보상도 좋아지지만 죽기 쉬워!':'3-as nehézség! Jobb jutalmak, de könnyebb meghalni!',
'50명! 학살자야!':'50 megölve! Mészáros!',
'5단!! 진짜 게이머 인증!':'5-ös nehézség!! Igazi gamer tanúsítva!',
'7단!! 다른 사람들 이 정도 못 와!':'7-es nehézség!! Mások nem jutnak idáig!',
'ACT1 완주! 우리가 진짜 해냈어!':'ACT1 teljesítve! Tényleg megcsináltuk!',
'Ctrl 얼음보주로 탈출하라.':'Ctrl — menekülj Ice Orb-bal.',
'Ctrl 유령걸음으로 탈출하라.':'Ctrl — menekülj Ghost Walk-kal.',
'C키! 패시브 강해져!':'C gomb! A passzívok erősödnek!',
'DEX 빌드! 거리에서 패고, 추적탄 좋아!':'DEX build! Távolsági támadások, követő lövedékek!',
'E로 마력공격을 해봐!':'Próbáld ki a mágikus támadást E-vel!',
'G 눌러서 대장간 가봐!':'Nyomd meg G-t — kovácsműhely!',
'G키 대장간. 강화 안 하면 계속 죽어.':'G — kovácsműhely. Fejlesztés nélkül tovább halsz.',
'HP 70%! 조심해!':'HP 70%! Vigyázz!',
'INT 빌드! 빔이랑 폭발 마법! MP 잘 봐!':'INT build! Sugár és robbanó mágia! Figyelj az MP-re!',
'LCK 높아! 레어 드롭률 미친 거 알지?':'Magas LCK! A ritka drop ráta őrületes!',
'L로 어디에 뭘 넣을지 골라!':'Nyomd meg L-t — válaszd ki a skill slot beállítást!',
'MP 부족! 평타로 패면서 회복해!':'Alacsony MP! Üsd vissza!',
'ST 없으면 스킬 못 써!':'ST nélkül nincs skill!',
'STR 빌드! 회전참, 회오리, 광역기 추천!':'STR build! Forgó csapás, forgószél, AoE!',
'VIT 좀 찍어! HP 너무 적어!':'Adj VIT-et! A HP túl alacsony!',
'Z 누르면 대박! 쿨타임 길어!':'Nyomd Z-t az ultimátéhoz! Hosszú visszatöltési idő!',
'…고기 냄새. 싫진 않네.':'…Vér szaga. Nem rossz.',
'…둘러싸이면 끝이야.':'…Bekerítve vége.',
'…말은 못해.':'…Nem tudok beszélni.',
'…버리기 아까운 건 창고에.':'…Az értékeseket tárold a raktárban.',
'…빈틈을 노려.':'…Figyeld a réseket.',
'…설정을 확인해.':'…Ellenőrizd a beállításokat.',
'…슬롯을 채워. 빈 손은 죽음이다.':'…Töltsd fel a slotokat. Az üres kéz halál.',
'…아직 살아있네. 좌클릭으로 저것들 쳐봐.':'…Még élsz. Bal kattintással üsd meg őket.',
'…운이 좋았을 뿐이야. 아마.':'…Csak szerencsés voltál. Valószínűleg.',
'…치는 건 할 줄 아네. 피하는 건?':'…Tudod ütni. De kitérni is tudsz?',
'…힘을 골라라. 전부 가질 순 없다.':'…Válaszd meg az erőd. Nem lehet mindent megszerezni.',
'골고루 안 돼! 하나로 밀어!':'Ne oszd szét! Fókuszálj egy statsra!',
'그로기 터지면 1.5배!':'Groggy = 1.5x sebzés!',
'길이 열렸다.':'Az út megnyílt.',
'나머진 전부 우클릭 패링 가능!':'A többi — jobb kattintás parry!',
'나머진 전부 우클릭!':'A többi — jobb kattintás!',
'다섯 번 연속! 내가 본 인간 중 최고!':'Öt egymás után! A legjobb, amit valaha láttam!',
'다음엔 죽지 마!':'Legközelebb ne halj meg!',
'더블탭 전격이동으로 탈출하라.':'Dupla koppintással dash-elj el.',
'소환수 왔어! 먼저 처리해야 해!':'Idézett szörnyek! Először végezz velük!',
'스킬 없으면 방향키 연타뿐이야.':'Nincs skill? Csak spameld a nyílbillentyűket.',
'신기록!! 스트리머한테 보내!':'Új rekord!! Küldd el a streamernek!',
'아이템 넘쳐! 우리가 주워줄게!':'Tele a táska! Mi felszedünk neked!',
'안 죽고 깼어! 진짜 천재 맞네!':'Halál nélkül teljesítve! Igazi zseni!',
'앞으로 가자~':'Menjünk előre~',
'우리가 해냈어! 다음 챕터 가자!':'Megcsináltuk! Következő fejezet!',
'일반 모드! 편하게 즐기자!':'Normál mód! Élvezd kényelmesen!',
'자원이 반이다. F키로 회복해.':'Az erőforrások fele. F-fel gyógyulj.',
'잡힌다! 옆으로 빠져!':'Megfognak! Ugord el oldalra!',
'장비 분해해! 쓰레기도 악의!':'Bontsd szét a felszerelést! Szemétből is jön malice!',
'전부 다 잡았어! 우리가 지옥의 왕이야!':'Minden megtisztítva! A pokol királyai vagyunk!',
'좋은 거 나왔다! TAB!':'Jó zsákmány! TAB!',
'죽기 직전에 죽이다니! 멋져!':'Megölni közvetlenül a halál előtt! Nagyszerű!',
'체력 반 남았어! 물약 마실 타이밍!':'HP fele! Ideje az elixírnek!',
'큰 거 온다! 도망쳐!':'Nagy támadás jön! Fuss!',
'패링으로 돌려주고, Q 보호막도 써!':'Parry és visszaverés, használd a Q pajzsot is!',
'패턴이 빨라졌어!':'A minták gyorsabbak!',
'한 대만 맞아도 죽어! 패링이든 회피든!!':'Egy találat = halál! Parry vagy kitérés!!',
'한 방이면 죽어! 도망쳐!!':'Egy lövés öl! Fuss!!',
'화염엔 빙결! 암전엔 암흑!':'Tűz → jég! Üresség → árnyék!',
'👻 유령!':'👻 Szellem!',
'🦴 해골무덤!':'🦴 Csontosír!',
'── 2장 - 벌레굴 ──':'── CH2 - Worm Nest ──',
'── 4장 - 화염지대 ──':'── CH4 - Infernal Wastes ──',
'── 6장 - 사도마굴 ──':'── CH6 - Apostle Den ──',
'── 공통 ──':'── Common ──',
'난이도를 선택하라':'Válassz nehézséget',
'☠ 부활력 고갈!':'☠ Feltámadás Kimerült!',
'⏳⚡ 시간걸음!':'⏳⚡ Időlépés!',
'블룸 효과':'Bloom hatás',
'잔상 트레일':'Utókép nyom',
'슬래시 이펙트':'Vágás hatás',
'후처리 효과':'Utófeldolgozás',
'사망 이펙트':'Halál hatás',
'동적 조명':'Dinamikus világítás',
'횃불 조명 (어둠)':'Fáklya fény (sötét)',
'앰비언트 파티클':'Környezeti részecskék',
'안개 효과':'Köd hatás',
'필름 그레인':'Filmszem',
'캐릭터 외곽선':'Karakterkontúr',
'리롤':'Újradobás',
'물약':'Bájital',
'으로 탈출!':'a meneküléshez!',
'Shift 작살':'Shift Szigony',
'더블탭 전격이동':'Dupla érintés — Villám-roham',
'Ctrl 유령걸음':'Ctrl Szellemlépés',
'Ctrl 얼음보주':'Ctrl Jéggömb',
'🔴화염→빙결 2배 | 🔵빙결→화염 2배 | ⚪물리=중립 | 악마 처치 시 악의 영혼 드롭':'🔴Tűz→Jég 2× | 🔵Jég→Tűz 2× | ⚪Fiz=Semleges | Öld meg a démonokat gonoszság-lelkekért',
  '미구현':'N/A',
  '스탯 총량':'Összes statisztika',
  '장비':'felszerelés',
  '공속':'tám.seb.',
  '크리':'krit',
  '크리뎀':'krit.seb.',
  '근성':'Kitartás',
  '종합 지표':'Áttekintés',
  '근접 DPS':'Közelharc DPS',
  '공격력×공속×크리':'ATK×Seb×Krit',
  '활 DPS':'Íj DPS',
  '마법 DPS':'Mágia DPS',
  '유효 HP (EHP)':'Hatékony HP (EHP)',
  '쉴드':'Pajzs',
  '장비 파워':'Felszer. erő',
  '근접 공격력':'Közelharc ATK',
  '기본':'alap',
  '무기':'fegyver',
  '패시브':'passzív',
  '활 공격력':'Íj ATK',
  '정밀':'Prec',
  '마법 공격력':'Mágia ATK',
  '왕관':'korona',
  '마력':'Arkán',
  '공격속도':'Támadási sebesség',
  '크리티컬':'Kritikus',
  '데미지':'kár',
  '확률':'Arány',
  '어픽스':'affixum',
  '레거시':'örökség',
  '추가뎀':'plusz kár',
  '패링 카운터뎀':'Parry visszacsapás kár',
  '우클공속':'Jobb kattintás seb.',
  '무지개탄DR':'Szivárvány DR',
  '포이즈파괴':'Poise törés',
  '방어관통':'Páncéltörés',
  '관통력':'Áthatolóerő',
  '속성':'Elemek',
  '무기속성':'Fegyver elem',
  '독':'Méreg',
  '초':'s',
  '암흑저주':'Sötét átok',
  '원소집중':'Elem. fókusz',
  '원소전환':'Elem. konverzió',
  '방어':'Védekezés',
  '물리방어':'Fizikai véd.',
  '감소':'csökkent.',
  '캡':'max',
  '장갑':'kesztyű',
  '바지':'nadrág',
  '속성방어':'Elem. véd.',
  '목걸이':'nyaklánc',
  '반지1':'gyűrű1',
  '반지2':'gyűrű2',
  '반사':'Visszaverés',
  '가시':'Tüskék',
  '배리어':'Akadály',
  '보호막 흡수':'Pajzs abszorpció',
  '속성 저항':'Elem. ellenállás',
  'CC저항':'CC ellenállás',
  '생존':'Túlélés',
  '장비HP':'Felszer. HP',
  '임플':'Impl.',
  '에너지쉴드':'Energiapajzs',
  '리젠':'Regen',
  '스태미나':'Kitartás',
  '성장':'Növekedés',
  'MP%어픽스':'MP% affixum',
  '이동속도':'Mozgási sebesség',
  '한방캡':'Együtemes limit',
  '최대HP의33%':'33% max HP',
  '비용/효율':'Költség/Hatás',
  '근접ST':'Közelharc ST',
  '활ST':'Íj ST',
  '마법MP':'Mágia MP',
  '작살사거리':'Szigony hatótáv',
  '기동게이지':'Drive kijelző',
  '쿨감':'CDR',
  '쇠뇌뎀':'Nyílpuska kár',
  '쇠뇌공속':'Nyílpuska seb.',
  '기타':'Egyéb',
  '물약쿨':'Bájital CD',
  '회복+':'Gyógyulás+',
  '드롭':'Elhullás',
  '경험치+':'EXP+',
  '골드+':'Arany+',
  '기동:칼날개':'Drive:Penge',
  '기동:전폭':'Drive:Csapás',
  '기동:기습':'Drive:Lesvetés',
  '충전스킬':'Töltés képesség',
  '사슬게이지':'Lánc kijelző',
  '특수 효과':'Különleges hatások',
  '처치뎀+':'Ölési kár+',
  '위기뎀+':'Krízis kár+',
  '피격반격':'Találat-visszavágás',
  '풍요(적HP≥70%뎀+)':'Bőség(HP≥70%+)',
  '약자포식(적HP≤30%뎀+)':'Ragadozó(HP≤30%+)',
  '패링폭발':'Parry robbanás',
  '체간파괴+':'Poise törés+',
  '콤보뎀+':'Kombó kár+',
  '작살뎀+':'Szigony kár+',
  '스킬뎀+':'Képesség kár+',
  '패리+':'Hárítás+',
  '체인':'Lánc',
  '정화':'Megtisztítás',
  '회':'×',
  '불굴':'Elszántság',
  '신성력':'Szent erő',
  '악마력(부활력)':'Démon erő',
  '자연':'Természet',
  '악마성':'Démonikum',
  '인간성':'Emberiség',
  '전투 통계':'Harci statisztikák',
  '스테이지':'Szakasz',
  '👻 공성허수아비!':'👻 Siege Scarecrow!',
  '💥 공성허수아비 폭발!':'💥 Siege Scarecrow Blast!',
};


const _HU_PFX={
'녹슨':'Rozsdás','강철':'Acél','흑요석':'Obszidián','미스릴':'Mithril','심판의':'Ítélet','천벌의':'Isteni Harag','파멸의':'Pusztítás','불꽃':'Láng','화염':'Pokoltűz','염화':'Pokoltűz','지옥불':'Pokollángja','지옥화':'Pokollángja','지옥':'Pokollángja','멸화의':'Megsemmisítő','냉기':'Fagy','빙결':'Jég','빙하':'Gleccser','서리의':'Dér','서리':'Dér','영겁빙':'Örökkévaló Jég','그림자':'Árnyék','암흑':'Sötét','심연':'Mélységi','나락의':'Alvilági','나락':'Alvilági','무간의':'Ürességi','전기':'Szikra','낙뢰':'Mennydörgés','암전':'Villám','뇌신의':'Viharisteni','뇌신':'Viharisteni','만뢰의':'Ezernyi Villám','축복':'Áldott','성광':'Szentfény','신성':'Szent','천사의':'Angyali','신벌의':'Isteni Ítélet','낡은':'Elnyűtt','천':'Vászon','가죽':'Bőr','강철사':'Acélszövés','은':'Ezüst','은사':'Ezüstfonál','화염의':'Pokoltűz','빙결의':'Jég','암흑의':'Sötét','암전의':'Villám'};
const _HU_BASE={
'대검':'Nagykard','석궁':'Számszeríj','연사석궁':'Ismétlő','마력석궁':'Arkán Számszeríj','견갑':'Pajzs','대견갑':'Nagypajzs','전투화':'Harci Csizma','갑옷':'Páncél','갑주':'Páncélzat','왕관':'Korona','장갑':'Kesztyű','건틀릿':'Vaskeztyű','바지':'Nadrág','각반':'Lábvért','허리띠':'Öv','벨트':'Öv','부적':'Talizmán','목걸이':'Nyaklánc','반지':'Gyűrű','망토':'Köpeny','팔찌':'Karkötő','귀걸이':'Fülbevaló'};
