// 지옥의 길 — Čeština (cs)
const _CS={
// --- Stage / Boss ---
'썩은 숲':'Shnilý les','숲의 감시자':'Strážce lesa','독버섯 거인':'Jedovatý houbový obr','숲의 사냥꾼':'Lesní lovec','숲의 기생수':'Lesní parazit',
'1장 — 썩은 숲':'K.1 — Shnilý les','2장 — 벌레굴':'K.2 — Červí doupě','3장 — 얼음굴':'K.3 — Ledová jeskyně',
'4장 — 고통의 화염지대':'K.4 — Pekelné pustiny','5장 — 지옥의 군단':'K.5 — Pekelná legie','6장 — 사도의 마굴':'K.6 — Apoštolovo doupě','7장 — 지옥성':'K.7 — Pekelná citadela',
'탈출!':'Útěk!','처치':'Zabití','경험치':'Zkušenosti','최대콤보':'Max. kombo',
// --- Tutorial (Crow) ---
'일어나. 여신이 널 여기 보낸 건 죽으라고가 아니야.':'Vstávej. Bohyně tě sem neposlala, abys umřel.',
'좋아, 감각이 있군. 계속 쳐!':'Dobře, máš instinkt. Pokračuj v boji!',
'Shift를 눌러. 작살이다. 땅에 꽂아서 끌려가!':'Stiskni Shift. To je harpuna. Zaboř ji a nech se táhnout!',
'작살로 끌려가는 중엔 무적이다. 위험할 때 쓰면 좋아.':'Během tažení harpunou jsi nezranitelný. Používej v nebezpečí.',
'...아파? 당연하지. 여긴 지옥이야.':'...Bolí to? Samozřejmě. Tady je peklo.',
'Q를 눌러! 악의로 보호막을 만들 수 있다.':'Stiskni Q! Vytvoř štít ze zlosti.',
'보호막 없이 버틸 생각은 버려.':'Zapomeň na přežití bez štítu.',
'우클릭이 패링이다. 적 공격이 닿기 직전에 눌러!':'Pravé tl. je parírování. Stiskni těsně před úderem nepřítele!',
'못 하겠으면 때려. 안 죽으면 그만이야.':'Neumíš parírovat? Prostě bij. Hlavní je neumřít.',
'됐어! 감 잡았구나.':'Tak! Už to chytáš.',
'하나 죽었군.':'Jeden hotový.',
'유령쇠뇌야. 인사해.':'To je přízračná kuše. Pozdrav ji.',
'빨간 탄을 무서워하지 마. 악의가 강하다.':'Neboj se červených střel. Zlost je silná.',
'패링으로 돌려주고, Q 보호막도 써! 악의를 잘 굴려!':'Paríruj zpět, používej Q štít! Ovládej zlost!',
'무지개빛은 패링 불가! 피해!':'Duhové nelze parírovat! Uhni!',
'피가 새고 있다. Shift. 빠져.':'Krvácíš. Shift. Ustup.',
'물약 있잖아! 숫자키!':'Máš lektvary! Číselné klávesy!',
'우클릭. 적 손목이 꺾일 때 쳐.':'Pravé tl. Bij, když se zápěstí nepřítele ohne.',
'빨간 탄은 악의 덩어리다. 쳐내서 이용해.':'Červené střely jsou kusy zlosti. Odraz a využij.',
'무지개빛만 피하면 돼! 나머지는 다 패링!':'Prostě uhni duhovým! Zbytek paríruj!',
'Q 보호막도 패링이 가능해!':'Q štít může taky parírovat!',
'위험해! 쉬프트 사슬기동으로 피해!!':'Nebezpečí! Shift řetězový výpad k úniku!!',
'쉬프트! 사슬기동은 이동기야! 끌려가면서 무적이라고!':'Shift! Řetězový výpad je pohyb! Nezranitelný během tažení!',
'스킬포인트가 쌓였어! K 눌러서 스킬 배우자!':'Body dovedností se nasbíraly! Stiskni K pro učení!',
'속성을 읽어. 약점을 찌르면 두 배로 썩는다.':'Čti živly. Zasáhni slabiny — dvojité poškození.',
'K를 눌러봐! 스킬을 배울 수 있어!':'Stiskni K! Můžeš se učit dovednosti!',
'C 눌러서 능력치 찍어! 패시브도 있어~':'Stiskni C pro statistiky! Pasivky taky~',
'G를 눌러. 대장간에서 장비를 강화할 수 있다.':'Stiskni G. Vylepši vybavení v kovárně.',
'F키도 스킬 슬롯이야! 스킬 많으면 L로 배정해봐~':'F je taky slot dovednosti! Použij L pro přiřazení~',
'Z. 필살기다. 아껴 써라.':'Z. To je ultimátní útok. Používej moudře.',
'L-CTRL로 유령걸음이나 얼음보주 쓸 수 있어!':'L-CTRL pro Přízračný krok nebo Ledovou sféru!',
'L을 눌러. 스킬 슬롯을 정리해야 한다.':'Stiskni L. Uspořádej sloty dovedností.',
'가방 터지겠다! V 눌러서 창고에 넣어둬!':'Taška praskne! Stiskni V pro uložení do skladu!',
'ESC로 설정 열 수 있어! 난이도 바꾸기, 자동물약 조절~':'ESC pro nastavení! Obtížnost, auto-lektvary~',
// --- Tutorial (Cat) ---
'...아직 살아있네. 좌클릭으로 저것들 쳐봐.':'...Ještě žiješ. Zkus na ně levé tl.',
'...치는 건 할 줄 아네. 피하는 건?':'...Bít umíš. A uhýbat?',
'흥, 작살 못 맞추면 헛수고야.':'Hmf, mineš harpunu — marná snaha.',
'...운이 좋았을 뿐이야. 아마.':'...Jen štěstí. Asi.',
'...고기 냄새. 싫진 않네.':'...Vůně masa. Není špatná.',
'...말은 못해.':'...Neumí mluvit.',
'예쁘다고 만지면 죽어.':'Dotkneš se, protože je to hezké? Umřeš.',
'작살 던져! 끌려가면 무적이야!':'Hoď harpunu! Nezranitelný během tažení!',
'...마시든 말든. 네 목숨이니까.':'...Pij nebo ne. Je to tvůj život.',
'그게 패링이야! 타이밍이 전부야~':'To je parírování! Načasování je vše~',
'화염엔 빙결! 암전엔 암흑! 기억해!':'Oheň bije led! Blesk bije tmu! Pamatuj!',
'...얼어붙은 놈은 오래 안 간다.':'...Zmrzlí dlouho nevydrží.',
'얼었어! 빙결 중 1.5배야!':'Zmrzlý! 1.5x poškození během zmrazení!',
'...힘을 골라라. 전부 가질 순 없다.':'...Vyber si sílu. Nemůžeš mít vše.',
'스탯을 올려. 살고 싶으면.':'Zvedni statistiky. Pokud chceš žít.',
'좋은 장비는 강화해야 진짜 힘을 발휘해!':'Dobré vybavení potřebuje vylepšení pro skutečnou sílu!',
'...슬롯을 채워. 빈 손은 죽음이다.':'...Zaplň sloty. Prázdné ruce znamenají smrt.',
'Z 누르면 대박! 쿨타임 길어서 타이밍 봐야 해!':'Z pro silný úder! Dlouhá obnova, zvol moment!',
'Ctrl. 위기에 쓸 카드가 하나 늘었군.':'Ctrl. Další karta pro nouzové situace.',
'스킬이 많아졌네~ L로 어디에 뭘 넣을지 골라!':'Tolik dovedností~ Použij L pro přiřazení!',
'...버리기 아까운 건 창고에.':'...Co je škoda zahodit — do skladu.',
'...살아남은 것만으로도 대단하군. 설정을 확인해.':'...Přežít je samo o sobě úspěch. Zkontroluj nastavení.',
// --- System Messages ---
'MP 부족!':'Nedostatek MP!','ST 부족!':'Nedostatek ST!','악의 부족!':'Nedostatek zlosti!',
'충전 중...':'Nabíjení...','캔슬':'Zrušit','아이템 선택 필요':'Vyber předmět',
'악의 소진...':'Zlost vyčerpána...','비문 발견...':'Nápis nalezen...',
'HP물약!':'HP lektvar!','HP물약 +1':'HP lektvar +1','HP물약 +2':'HP lektvar +2',
'HP/MP/ST 회복!':'HP/MP/ST obnoveno!','보물상자 개봉!':'Truhla otevřena!',
'익사!':'Topení!','피웅덩이!':'Krvavá louže!','독혈!':'Toxická krev!','잡힘!':'Chycen!',
'콤보 종료':'Konec komba',
// --- Status Effects ---
'빙결!':'Zmrzlý!','화상!':'Popálenina!','독!':'Jed!','감전!':'Šok!',
'기절!':'Omráčení!','봉인됨!':'Zapečetěn!','관통!':'Průraz!',
// --- Skill Names ---
'기검참':'Ki úder','악의구':'Koule zlosti','회전참':'Vír','기폭팔':'Detonace',
'칼등 처내기':'Parírování čepelí','만화방창':'Příval jehel','멸살광선':'Paprsek zkázy',
'원소추적탄':'Živlový hledač','악의 보호자':'Strážce zlosti','악의 사냥':'Lov zlosti',
'폭풍소환':'Přivolání víru','해골무덤':'Kostěná hrobka','신성폭발':'Svatý výbuch',
'블랙':'Černá hvězda','용암소환':'Přivolání lávy','처형':'Poprava','악마화 부활':'Démonické vzkříšení',
'붉은꽃':'Šarlatový květ','얼음보주':'Ledová sféra','뇌전걸음':'Přízračný krok',
'만화방창 II':'Příval jehel II','마력연사':'Arkanová palba','마력광선':'Arkanový laser','업화선':'Pekelný paprsek',
'지옥진':'Pekelná formace','폭독칼날':'Morové ostří','악의폭풍':'Bouře zlosti',
'악의기둥':'Temný sloup','회복의 영역':'Svatá doména','구속의 영역':'Doména pout',
'아이스스톰':'Ledová bouře','대왕치기':'Úder obra','대왕치기 2':'Úder obra II',
'기동불꽃':'Řetězový plamen','기동파괴':'Řetězové ničení','기동칼날개':'Řetězové ostří',
'평화의보호':'Aegida míru','참회':'Pokání','칼등날개':'Křídlo štítu',
'폭산탄':'Výbušný výstřel','파쇄의 영역':'Doména drcení','침식의 영역':'Doména koroze',
'관통의 영역':'Doména průrazu','부활의 영역':'Doména vzkříšení','가시덫':'Trnová past',
'푸른비':'Azurový déšť','버스트루프':'Smyčka výbuchu','유령 허수아비':'Přízračná návnada','폭발 허수아비':'Výbušná návnada',
'공성쇠뇌':'Obléhací kuše','사슬기동:충돌':'Řetězový výpad: Náraz',
'사슬기동:화염':'Řetězový výpad: Plamen','전격이동':'Bleskový krok',
// --- Skill Activation ---
'기동칼날개!':'Řetězové ostří!','기동불꽃!':'Řetězový plamen!','기동파괴!':'Řetězové ničení!',
'사슬이동:강화!':'Řetězový výpad!','사슬기동:화염!':'Řetězový plamen!',
'작살!':'Harpuna!','진입!':'Vstup!','레인라이트닝!':'Déšť blesků!',
'마력연사!':'Arkanová palba!','🔷 마력광선!':'🔷 Arkanový laser!','광선 해제':'Laser vyp.','MP 부족 — 광선 해제':'MP vyčerpáno — Laser vyp.','집중...':'Soustředění...','시전...':'Sesílání...',
'만화방창!':'Příval jehel!','바늘출!':'Jehlový výbuch!','칼날!':'Ostří!',
'착지!':'Přistání!','체간삭감!':'Zlomení postoje!',
'기동전폭 준비!':'Řetězový výbuch připraven!','기동불꽃 준비!':'Řetězový plamen připraven!',
'기동파괴 준비!':'Řetězové ničení připraveno!',
'유령불꽃 ON':'Přízračný plamen ZAP','유령불꽃 OFF':'Přízračný plamen VYP',
'기동칼날개 AUTO ON':'Řetězové ostří AUTO ZAP','기동칼날개 AUTO OFF':'Řetězové ostří AUTO VYP',
'자동 버스트!':'Auto výbuch!','연사 해제':'Rychlopalba vyp.',
'당기기 모드':'Režim tažení','밀어내기 모드':'Režim tlačení',
// --- Skill Slot Tooltips ---
'날개치기':'Úder křídlem','처내기':'Parírování',
'Shift: 작살 발사 → 끌려감':'Shift: Hod harpunou → tažení',
'Shift: 화염길+화상':'Shift: Ohnivá stopa+popálenina',
'CT: 전류변신+뇌전걸음 (쿨4초)':'CT: Elektroforma+Přízračný krok (CD 4s)',
'CT: 방어구체+빙결 (재입력: 파쇄)':'CT: Ledová sféra+zmrazení (opakovat: drcení)',
// --- HUD ---
'근접':'Blízký','견갑':'Obrana','작살':'Harpuna','마법':'Magie','보막':'Štít','유령':'Přízrak',
'스킬':'Dovednosti','대장':'Kovárna','인벤':'Výbava',
// --- Menu ---
'인벤토리':'Inventář','복수의 대장간':'Kovárna pomsty','패시브 스킬':'Pasivní dovednosti',
'전투 스킬':'Bojové dovednosti','캐릭터 선택':'Výběr postavy',
// --- Elements ---
'물리':'Fyzické','화염':'Oheň','빙결':'Led','암흑':'Tma','암전':'Blesk','신성':'Svaté','대지':'Země',
// --- Passives ---
'힘':'Síla','민첩':'Obratnost','지능':'Inteligence','행운':'Štěstí',
'맹공':'Nápor','철벽':'Neústupnost','돌파':'Průlom','반격':'Protiúder',
'마력폭주':'Arkanový příval','정밀사격':'Přesná střelba','수호':'Ochrana','수호신':'Strážný duch',
'회복력':'Regenerace','급소':'Přesný zásah','약탈':'Loupež','관통':'Průraz',
'마력회복':'Obnova many','쇠뇌력':'Mistrovství kuše','광전사':'Berserk','추적자':'Stopař',
'물리관통':'Fyz. průraz','마법관통':'Mag. průraz',
// --- Weapons ---
'녹슨 대검':'Rezavý obouruční meč','강철 대검':'Ocelový obouruční meč','흑요석 대검':'Obsidiánový obouruční meč',
'낡은 석궁':'Opotřebovaná kuše','강철 석궁':'Ocelová kuše','흑요석 석궁':'Obsidiánová kuše',
'대검':'Obouruční meč','석궁':'Kuše','연사석궁':'Opakovací kuše','마력석궁':'Arkanová kuše',
// --- Misc ---
'악의 추출':'Extrakce zlosti','악의':'Zlost','필살기':'Ultimátní útok','필살기 해제':'Ultimátní útok odebrán',
'이전':'Přenos','강화':'Vylepšení','개봉!':'Otevřeno!',
'여신의 가호':'Bohyniino požehnání','과부하!':'Přetížení!',
// --- Affix Names ---
'맹독의':'Jedovatý','불꽃의':'Plamenný','냉기의':'Mrazivý','번개의':'Elektrický','암흑의':'Prokletý',
'관통의':'Průrazný','광폭의':'Zuřivý','파쇄의':'Drtivý','연쇄의':'Řetězový',
'학살의':'Zabijácký','폭발의':'Výbušný','집중의':'Soustředěný','쾌속의':'Rychlý','패리의':'Odrazný',
'추적자의':'Stopaře','작살의':'Harpunový','궁극의':'Nejvyšší','집중력의':'Pozorný',
'강인의':'Houževnatý','수호의':'Ochranný','활력의':'Životný','신속의':'Zrychlený',
'화염수호':'Ohnivá ochrana','빙결수호':'Ledová ochrana','암전수호':'Blesková ochrana','암흑수호':'Ochrana tmy','독수호':'Ochrana jedu','전원소수호':'Plná živ. ochrana',
'강철의':'Železný','반사의':'Odrážecí','가시의':'Trnový','흡수의':'Pohlcující','인내의':'Vytrvalý',
'위기의':'Zoufalý','피격반격의':'Protiútočný',
'패링폭발의':'Výbuch parírování','스태거폭발의':'Výbuch omráčení','원소전환의':'Konvertor','정화의':'Očistný',
'불굴의':'Neústupný','부활의':'Vzkřísivý',
'약탈의':'Loupežný','경험의':'Zkušený','골드의':'Zlatý','포션강화의':'Zesílený lektvar','사슬의':'Řetězový',
'진혼의':'Posvěcující','윤회의':'Cyklický',
'생명력의':'Vitální','재생의':'Regenerující','치유의':'Léčivý',
'마력의':'Arkanový','절약의':'Úsporný','영혼의':'Duševní',
'예리한':'Ostrý','맹렬한':'Brutální','파멸의':'Ničivý',
// --- Settings UI ---
'게임 설정':'Nastavení hry','화면 흔들림':'Třes obrazovky','파티클 양':'Množství částic',
'효과음 볼륨':'Hlasitost SFX','음악 볼륨':'Hlasitost hudby','난이도':'Obtížnost',
'자동 물약':'Auto lektvar','최소 줍기 등급':'Min. stupeň sbírání','최소 줍기 티어':'Min. tier sbírání',
'FPS 제한':'Limit FPS','해상도 스케일':'Škálování rozlišení','펫 자동수거':'Auto-sběr mazlíčka',
'화면 설정':'Nastavení displeje','화면 모드':'Režim displeje','보스 AI 디버그':'Debug AI bosse',
'유령불꽃 크기':'Velikost přízračného plamene','화면 명암':'Jas','유령 글로우':'Přízračná záře',
'기동:칼날개 AUTO':'Řetězové ostří AUTO',
'일반':'Normální','어려움':'Těžká','지옥':'Peklo','이상':'a výše','사용 안 함':'Vypnuto',
'창 모드':'V okně','보더리스':'Bez okrajů','전체화면':'Celá obrazovka',
'설정':'Nastavení','조작 키 설정 (클릭하여 변경)':'Přiřazení kláves (klikni pro změnu)',
// --- Key Guide ---
'좌클릭 무기 공격':'Levé tl. Útok zbraní','우클릭 탭 칼등 처내기':'Pravé tl. Tap parírování',
'우클릭 홀드 연속 처내기':'Pravé tl. Držení parírování','SHIFT 작살 발사':'SHIFT Hod harpunou',
'이동':'Pohyb','아이템 줍기':'Sebrat předmět','능력치 (스탯/패시브)':'Atributy (Staty/Pasivky)',
// --- Forge ---
'복수의 대장간':'Kovárna pomsty','분해':'Rozebrat','제작':'Vytvořit',
// --- Death Screen ---
'사망':'Smrt','부활':'Vzkříšení','로비로':'Do lobby',
// --- Inventory/Storage ---
'가방에 공간이 없습니다!':'Není místo v tašce!','가방이 가득 찼습니다!':'Taška je plná!',
'창고가 가득 찼습니다!':'Sklad je plný!','퀵슬롯이 가득 찼습니다!':'Rychlý slot je plný!',
'결정 주머니가 가득 찼습니다!':'Váček krystalů plný!','결정 주머니 가득!':'Váček krystalů plný!',
'악의가 부족합니다!':'Nedostatek zlosti!','가방이 비어있습니다':'Taška je prázdná',
'창고가 비어있습니다':'Sklad je prázdný','비어있음':'Prázdné','어픽스 없음':'Bez afixu',
'장착!':'Nasazeno!','해제':'Sundáno','보관':'Uložit','꺼내기':'Vyjmout',
'현재 장착':'Právě nasazeno','없음 — 제작하세요!':'Žádné — vytvořte!',
'리셋할 포인트가 없습니다':'Žádné body k resetu','키 설정 초기화 완료':'Klávesy resetovány',
// --- Forge/Craft ---
'제작 확률':'Šance vytvoření','제작 비용':'Cena vytvoření','보유 악의':'Vlastněná zlost',
// --- Canvas UI ---
'보스방':'Místnost bosse','안식처':'Útočiště','회복':'Obnovit','점화':'Zapálit',
'비석':'Stéla','읽기':'Číst','파괴':'Zničit','제단':'Oltář','기원':'Modlitba',
'잔해':'Trosky','열기':'Otevřít','문지기':'Strážce brány',
'부활 판정 중...':'Hodnocení vzkříšení...','기폭 준비!':'Detonace připravena!',
'탈출':'Útěk','연타':'Mačkej',
'추적암전':'Sledující blesk','만화광선':'Paprsek záře','최종 마법':'Finální magie',
'감시중':'Sledování','대기':'Pohotovost','작동중':'Aktivní','설치 가능':'Lze instalovat',
'균열 임박!':'Zlom blízko!','흡수 중...':'Pohlcování...',
'흡수 완료 — 재입력으로 회수':'Hotovo — stiskni znovu pro sběr',
'화상':'Popálenina','당기기':'Táhnout','밀어내기':'Tlačit',
'단계':'úroveň','단':'úroveň',
// --- Skill Panel ---
'습득!':'Naučeno!','리셋!':'Resetováno!','세팅!':'Nastaveno!','회수':'Získat zpět',
'합체 해제':'Zrušit fúzi','리셋':'Reset','환불':'Vrátit',
'파트너 클릭!':'Klikni partnera!','SP부족!':'Potřeba SP!',
'같은 보석 스킬 습득 시 합체 가능':'Fúze možná po naučení dovednosti stejného drahokamu',
'펼쳐서 초기화':'Rozbal pro reset','슬롯:':'Slot:',
// --- Stats ---
'남은 SP':'Zbývající SP','맞아서 사망':'Smrt úderem','레벨':'Úroveň','최대HP':'Max. HP',
// --- Enemy Names ---
'방랑 기사':'Putující rytíř','보물 악마':'Démon pokladů','거울의 사도':'Zrcadlový apoštol',
'상인 악마':'Démon obchodník','사슬의 죄수':'Spoutaný vězeň','시간의 사도':'Apoštol času',
'탐욕의 사도':'Apoštol chamtivosti','저주받은 쌍둥이':'Prokletá dvojčata','차원 균열체':'Dimenzionální zlom','죽음 그 자체':'Sama smrt',
// --- Crystals ---
'HP결정':'HP krystal','ST결정':'ST krystal','MP결정':'MP krystal',
'ATK결정':'ATK krystal','DEF결정':'DEF krystal','속도결정':'Krystal rychlosti',
'크리결정':'Krystal kritu','치명결정':'Krystal krit. poškoz.','화염결정':'Krystal ohně',
'냉기결정':'Krystal ledu','암흑결정':'Krystal tmy','번개결정':'Krystal blesku',
'신성결정':'Krystal svatého','생명결정':'Krystal života','기력결정':'Krystal výdrže',
'마력결정':'Krystal many','행운결정':'Krystal štěstí',
'조각':'Úlomek','파편':'Střep','순수결정':'Čistý krystal','완전결정':'Dokonalý krystal',
'결정 주머니':'Váček krystalů','결정이 없습니다':'Žádné krystaly','가루':'Prášek',
'전체':'Vše','스탯':'Stat','원소':'Živel','유틸':'Nástroje',
'현재':'Aktuálně','최대 강화 달성 (+20)':'Max. vylepšení (+20)','강화 시':'Po vylepšení',
'합성':'Syntéza',
'같은 종류·같은 성급 결정 3개 → 1성급 상승 (강화 리셋)':'3 krystaly stejného typu a stupně → +1 stupeň (vylepšení reset)',
'합성 가능한 결정이 없습니다 (같은 종류·성급 3개 필요)':'Žádné krystaly k syntéze (potřeba 3 stejného typu a stupně)',
'결정 분해 → 결정 가루':'Rozebrat krystal → prášek','분해할 결정이 없습니다':'Žádné krystaly k rozebrání',
'결정 제작 (가루 → 결정)':'Vytvořit krystal (prášek → krystal)',
'탈착':'Sundat','빈 슬롯':'Prázdný slot',
'결정 선택 후 클릭':'Vyber krystal a klikni','클릭하여 선택결정 장착':'Klikni pro nasazení krystalu',
'획득!':'Získáno!','제작!':'Vytvořeno!','합성!':'Syntezováno!','최상위 일괄합성':'Hromadná syntéza na max.','일괄합성 완료':'Hromadná syntéza dokončena',
// --- Stage Names ---
'벌레굴':'Červí doupě','얼음굴':'Ledová jeskyně','고통의 화염지대':'Pekelné pustiny',
'지옥의 군단':'Pekelná legie','사도의 마굴':'Apoštolovo doupě','지옥성':'Pekelná citadela',
// --- Misc ---
'엑소듀서 전사':'Válečník Exoduser','포이즈':'Postoj','신성폭발':'Svatý výbuch','뇌전걸음':'Přízračný krok',
'지옥창고':'Pekelný sklad','선택분해':'Selektivní rozebírání','쓰레기':'Odpad',
'복구 불가!':'Nelze obnovit!','중요잠금':'Důležité-zamčeno',
'자동 장착!':'Auto-nasazeno!','분해! 가루 +':'Rozebráno! Prášek +',
'평화보호':'Aegida','지진폭풍':'Zemětřesení','회전기폭':'Vírová det.',
'공격':'Útok','보호막':'Štít',
'합체 스킬로 통합됨':'Sloučeno do fúzní dovednosti','얼음보주 안에선 사용 불가!':'Nelze použít v Ledové sféře!',
'Shift+키로 폭파':'Shift+klávesa pro detonaci','취소':'Zrušit',
'쿨다운 중...':'Obnova...','시전 중...':'Sesílání...',
'악의 부족! (12)':'Nedostatek zlosti! (12)','악의 부족! (15)':'Nedostatek zlosti! (15)',
'악의 부족! (20)':'Nedostatek zlosti! (20)','악의 부족! (10)':'Nedostatek zlosti! (10)',
'ST 부족!':'Nedostatek ST!','HP 부족!':'Nedostatek HP!',
'필살기 슬롯 클릭하여 배정!':'Klikni na slot ultimátního útoku!',
'필살기 스킬을 습득하세요':'Nauč se ultimátní dovednost',
'우클릭(칼등치기)에 합체됨':'Sloučeno s pravým tl. (parírování)',
'T(석궁자동)에 세팅하세요':'Nastav na T (auto-kuše)',
'공성쇠뇌 철거 → 이동식':'Obléhací kuše demontována → přenosná',
'ST 부족! (100)':'Nedostatek ST! (100)',
'HP 99% 이상!':'HP 99%+!','그로기 보스 없음!':'Žádný omráčený boss!',
'이미 폭풍 지역!':'Už v zóně bouře!','이미 빙풍 지역!':'Už v zóně ledové bouře!',
'💎 푸른비 해금!':'💎 Azurový déšť odemčen!','💫 버스트루프 해금!':'💫 Smyčka výbuchu odemčena!',
'👻 유령 허수아비 해금!':'👻 Přízračná návnada odemčena!',
'쿨 ':'CD ','과부하 ':'Přetížení ',
'🕊️💎 블루콩!':'🕊️💎 Modrý fazol!','🛡️💎 빨콩→블루콩!':'🛡️💎 Červený→Modrý fazol!','🛡️💎 무지개→블루콩!':'🛡️💎 Duhový→Modrý fazol!',
'레어':'Vzácný','슬롯':'Slot',
'성공률':'Šance úspěchu','AI 자동 강화':'AI auto-vylepšení','최대 강화 달성!':'Max. vylepšení dosaženo!',
'최대 강화':'Max. vylepšení','회복량':'Obnovení',
'분해할 아이템이 없습니다.':'Žádné předměty k rozebrání.','🔨 제작':'🔨 Vytvořit',
'체간':'Postoj','아이템에 마우스를 올리거나 좌클릭으로 선택하세요':'Najeď na předmět nebo klikni levým tl.',
'중독':'Jed','지뢰':'Mina','함정':'Past','산호가시':'Korálový trn',
'투사체':'Projektil','도트':'DoT','레어몹':'Vzácný mob','구역':'Zóna','가시!':'Trn!',
'림보':'Limbo','색욕':'Chtíč','탐식':'Obžerství','탐욕':'Chamtivost','분노':'Hněv','이단':'Kacířství','폭력':'Násilí',
'분노!':'Zuřivost!','탐욕!':'Chamtivost!','💀 분노 폭발!':'💀 Výbuch zuřivosti!','심연의 분노!':'Zuřivost propasti!','쌍둥이의 분노!':'Zuřivost dvojčat!',
'소환굴':'Vyvolávací nora',
'처치!':'Poražen!','왕관 착용':'Koruna zap.','왕관 해제':'Koruna vyp.',
'맨손':'Holé ruce','없음':'Žádné','갑옷':'Brnění','부츠':'Boty',
'매직':'Magický','챔피언':'Šampion',
'초속':'Zrychlení','강타':'Úder','재생':'Regenerace','맹독':'Jed','소환':'Přivolání',
'기생':'Parazit','분열':'Dělení','용암자취':'Lávová stopa','사망폭발':'Smrtelný výbuch',
'화염사슬':'Ohnivý řetěz','광전':'Šílenství','텔레포트':'Teleportace',
'소용돌이':'Vír','환영':'Fantom','전격반사':'Odraz blesku','감전':'Elektrošok',
'낙뢰':'Hrom','연쇄전격':'Řetězový blesk','동료불사':'Nesmrtelnost spojence',
'영혼포식':'Požírání duší','시간왜곡':'Zakřivení času','혼돈변이':'Chaotická mutace',
'복수자':'Mstitel','마법보초':'Magická stráž','환영술사':'Iluzionista',
'함성':'Válečný pokřik','치유':'Léčení','신속':'Rychlost','수호':'Strážce',
'다크 판타지 전사. 거대검+검은 갑옷':'Temný fantasy válečník. Obouruční meč + Černé brnění',
'⚡ 사슬이동:강화!':'⚡ Řetěz:Zesílení!','⚡ 사슬기동:화염!':'⚡ Řetěz: Plamen!',
'달성!':'Dosaženo!','ST':'ST','부족!':'Nedostatek!','타':'Zásah',
'🌀 당기기 모드':'🌀 Režim tažení','💥 밀어내기 모드':'💥 Režim tlačení',
'🕊️빨콩 흡수':'🕊️Pohlcení červ. fazolu','🕊️흡수':'🕊️Pohlcení',
'💎유도 폭발!':'💎Naváděný výbuch!','💥반사 폭발!':'💥Odrazený výbuch!',
'⚡⚡ 참회 귀환!':'⚡⚡ Návrat pokání!','⚡ 참회!':'⚡ Pokání!',
'파도!':'Vlna!','암전!':'Blesk!','암흑!':'Tma!','암흑창!':'Temné kopí!','빛창!':'Světelné kopí!',
'체 소환!':'přivoláno!','개 설치!':'instalováno!',
'💥 보스 그로기!':'💥 Boss omráčen!','💥 그로기!':'💥 Omráčení!','보상':'Bonus',
'⚡ 암전나선!':'⚡ Blesková spirála!','🌋 지진폭풍!':'🌋 Zemětřesení!',
'SP슬롯':'SP Slot','F슬롯':'F Slot',
'⚔🩸 독혈해방!':'⚔🩸 Morové osvobození!','⚔ 칼날 해방!':'⚔ Osvobození ostří!',
'🔨🌋 지옥강타!':'🔨🌋 Pekelný úder!','🔨 대왕치기!':'🔨 Úder obra!',
'✟ 결계의 영역!':'✟ Doména bariéry!','✟ 물의 영역!':'✟ Doména vody!','✟ 파쇄의 영역!':'✟ Doména drcení!','✟ 침식의 영역!':'✟ Doména koroze!','✟ 관통의 영역!':'✟ Doména průrazu!','✟ 권능의 영역!':'✟ Doména svrchovanosti!',
'🛡 회복의 영역!':'🛡 Svatá doména!',
'임계...!':'Kritické...!',
'기폭팔!':'Detonace!','강제기폭!':'Vynucená detonace!','자동기폭!':'Auto-detonace!',
'회전기폭!':'Vírová detonace!','해제기폭!':'Detonace uvolnění!','지진기폭!':'Seizmická detonace!',
'혼돈의 왕관':'Koruna chaosu','전지전능의 왕관':'Koruna všemohoucnosti',
'악마의 팔찌':'Démonický náramek','생명의 팔찌':'Náramek života',
'🌊 위→아래 파도!':'🌊 Shora→dolů vlna!','🌊 오른→왼 파도!':'🌊 Zprava→doleva vlna!',
'🌊 아래→위 파도!':'🌊 Zdola→nahoru vlna!','🌊 왼→오른 파도!':'🌊 Zleva→doprava vlna!',
'무적!':'Nezranitelný!','🪞 반격!':'🪞 Protiúder!','💢 반격!':'💢 Protiúder!',
'흡수!':'Pohlcení!','반격 발사!':'Odvetný výstřel!',
'저주! 드랍률 -50%':'Kletba! Šance dropu -50%','도망!':'Útěk!',
'위상!':'Fáze!','방어!':'Obrana!',
'회수 HP+':'Získání HP+','이동식 복귀':'Návrat přenosné','캔슬':'Zrušit',
'약점!':'Slabina!','저항!':'Odolnost!',
'콤보 종료: ':'Konec komba: ',
'악의 +':'Zlost +','저주 ':'Kletba ','불발...':'Selhal...',
'작살 약점!':'Slabina harpuny!',
'전염 x':'Nákaza x','흡수 완료!':'Pohlcení dokončeno!',
'부활 성공!':'Vzkříšení úspěšné!','부활 실패...':'Vzkříšení neúspěšné...',
'산호가시':'Korálový trn','차원 이동!':'Dimenzionální skok!',
'기절 해제':'Omráčení odstraněno',
'악의 부족':'Nedostatek zlosti',
'스킬 미습득':'Žádné naučené dovednosti','펼치기':'Rozbalit','접기':'Sbalit',
'조건 미달!':'Podmínka nesplněna!','해제!':'Odstraněno!',
'자동 ON':'Auto ZAP','자동 OFF':'Auto VYP','스킬 해제':'Dovednost odebrána',
'닫기':'Zavřít','장착 중':'Nasazeno','보관 아이템':'Uložený předmět',
'클릭으로 선택 · ESC로 닫기':'Klikni pro výběr · ESC pro zavření','선택됨':'Vybráno',
'악의 부족! (30)':'Nedostatek zlosti! (30)',
'MP 부족! (40)':'Nedostatek MP! (40)','MP 부족! (100)':'Nedostatek MP! (100)','MP 부족! (10)':'Nedostatek MP! (10)',
'MP 부족! (':'Nedostatek MP! (',
'✟ 시전...':'✟ Sesílání...','🌋 시전...':'🌋 Sesílání...','⛧ 시전...':'⛧ Sesílání...',
'❄ 진입!':'❄ Vstup!','🔱 작살!':'🔱 Harpuna!',
'레벨 부족! (요구: Lv.':'Úroveň příliš nízká! (Potřeba: Lv.',
' 장착!':' Nasazeno!',' 해제':' Sundáno',
'👿 악의 추출: +':'👿 Extrakce zlosti: +','F 슬롯 해제':'F Slot odebrán',
'💫 집중...':'💫 Soustředění...','⚡ 마력연사!':'⚡ Arkanová palba!',
'❄빙결!':'❄Zmrzlý!','🟢독!':'🟢Jed!','⚡감전!':'⚡Šok!','🔥화상!':'🔥Popálenina!',
'✦ 여신의 가호 — SP+5 AP+3':'✦ Požehnání bohyně — SP+5 AP+3',
'⚔ 기동칼날개!':'⚔ Řetězové ostří!','🔥 화염관통!':'🔥 Ohnivý průraz!',
'🔱 관통!':'🔱 Průraz!','⚔ 칼날!':'⚔ Ostří!','💥 착지!':'💥 Přistání!',
'💫 기절!':'💫 Omráčení!','⚡ 체간삭감!':'⚡ Zlomení postoje!',
'⚡ 기동파괴! ':'⚡ Řetězové ničení! ',
'🔥 기동불꽃!':'🔥 Řetězový plamen!','🔥 기동불꽃! ':'🔥 Řetězový plamen! ',
'단계 ×':' x','⚡ 기동전폭! x':'⚡ Řetězový výbuch! x',
'🔥🔥 3중폭!':'🔥🔥 Trojitý plamen!','🔥🔥🔥 6중폭!':'🔥🔥🔥 6x plamen!','🔥🔥🔥🔥 9중폭!':'🔥🔥🔥🔥 9x plamen!','💥 불꽃폭발! ':'💥 Výbuch plamene! ',
'🔥 기동불꽃 준비!':'🔥 Řetězový plamen připraven!','🔨 기동파괴 준비!':'🔨 Řetězové ničení připraveno!','⚡ 기동전폭 준비!':'⚡ Řetězový výbuch připraven!',
'⚡ 과부하! 5초':'⚡ Přetížení! 5s','💫 자동 버스트!':'💫 Auto výbuch!',
'🔨 칼등날개!':'🔨 Křídlo štítu!','💥폭발!':'💥Výbuch!',
'🛡️💎 유도반사!':'🛡️💎 Naváděný odraz!',
'⚡💎 블루콩!':'⚡💎 Modrý fazol!','💎 블루콩!':'💎 Modrý fazol!',
'⚡반사!':'⚡Odraz!',
'💎 푸른비 OFF':'💎 Azurový déšť VYP','💎 푸른비 ON!':'💎 Azurový déšť ZAP!',
'🔥 지옥진!':'🔥 Pekelná formace!','🔥 업화선!':'🔥 Pekelný paprsek!',
'✦ 평화 충격파! ':'✦ Vlna míru! ','⚡ 전류 방출!':'⚡ Elektrický výboj!',
'⚡⚡ 레인라이트닝!':'⚡⚡ Déšť blesků!','💫 광역!':'💫 Plošný útok!',
'🔥 불장판!':'🔥 Ohnivá zóna!','💫 피니셔!':'💫 Finisher!',
'☠ 지옥에서 귀환!':'☠ Návrat z pekla!','☠ 완전 사망!':'☠ Trvalá smrt!',
'⚔ 처형! ':'⚔ Poprava! ','💥 지뢰!':'💥 Mina!','⚠ 함정!':'⚠ Past!',
'❌ 우클릭으로! -':'❌ Použij pravé tl.! -','❌ Q키로! -':'❌ Použij Q! -',
'💥무지개 폭발! ':'💥Duhový výbuch! ','🛡️💎 블루콩!':'🛡️💎 Modrý fazol!',
'⬜화이트볼!':'⬜Bílý míč!','✨💎 블루콩!':'✨💎 Modrý fazol!','💜다크볼!':'💜Temný míč!',
'❄빙판!':'❄Ledová podlaha!','🌨빙결!':'🌨Zmrzlý!','🕸둔화!':'🕸Zpomalení!','⚠트랩!':'⚠Past!',
'💀 역병 처형!':'💀 Morová poprava!','💥 역병 Finale!':'💥 Morový finále!',
'⚔ 균열 악마!':'⚔ Démon zlomu!','자동회수 HP+':'Auto-získání HP+',
'MP 부족 — 연사 해제':'MP málo — Rychlopalba vyp.','MP 부족 — 푸른비 OFF':'MP málo — Azurový déšť VYP',
'🛡️반사!':'🛡️Odraz!','⚡🦴 참회 귀환!':'⚡🦴 Návrat pokání!',
'🦴⚡해골번개!':'🦴⚡Kostěný blesk!','⚡악의폭풍!':'⚡Bouře zlosti!',
'❄아이스스톰!':'❄Ledová bouře!','⚡ 암전폭발!':'⚡ Výbuch blesku!',
'⚡ 레인라이트닝! x':'⚡ Déšť blesků! x','❄ 탈출!':'❄ Útěk!',
'⚡쉴드!':'⚡Štít!','❄🌪️ 얼음보주!':'❄🌪️ Ledová sféra!',
'🌪️ 전개!':'🌪️ Rozvinutí!','❄ 빙결흡인!':'❄ Ledový vír!',
'❄☄ 빙결폭발!':'❄☄ Ledový výbuch!','☄️ 흡인!':'☄️ Vír!','☄️ 대폭발!':'☄️ Mega výbuch!',
'❄ 얼음보주!':'❄ Ledová sféra!','⏳ 시간왜곡!':'⏳ Zakřivení času!','쿨다운!':'Obnova!',
'❄ 파쇄!':'❄ Drcení!','☄️💥 대폭발!':'☄️💥 Mega výbuch!','반사!':'Odraz!',
'💀 도넛!':'💀 Donut!','💀 전멸!':'💀 Vyhlazení!',
'🌊 파도!':'🌊 Vlna!','속박!':'Pouta!','반격!':'Protiúder!',
'분신!':'Klon!','분신 파괴!':'Klon zničen!','무기 해방!':'Osvobození zbraně!',
'❄프리즌!':'❄Vězení!','⚡ 증표 ':'⚡ Značka ',
'흔들!':'Otřes!','⚠ 광역 발사!':'⚠ Plošná palba!',
'🔥 확산!':'🔥 Šíření!','⚠ 돌진!':'⚠ Výpad!',
'🦅 도약!':'🦅 Skok!','⚡ 레이저!':'⚡ Laser!',
'🌊 충격파!':'🌊 Rázová vlna!','👹 소환!':'👹 Přivolání!',
'☄ 유성우!':'☄ Meteorický déšť!','🖐 잡기!':'🖐 Chycení!',
'🌀 회전참!':'🌀 Vír!','💣 지뢰!':'💣 Mina!',
'🌀 흡인!':'🌀 Vakuum!','🔴 빨간콩 폭풍!':'🔴 Bouře červených fazolů!',
'🔴🔴 콩 비!':'🔴🔴 Déšť fazolů!',
'🌊 부채꼴 충격파!':'🌊 Vějířová rázová vlna!',
'✴ 멸광 레이저!':'✴ Laser zkázy!','🔴 추적 장판!':'🔴 Sledující zóna!',
'💥 속성탄!':'💥 Živlový projektil!',
'⚔ 검기!':'⚔ Ki meče!','⚔ 재단참!':'⚔ Žnivý úder!',
'🌀 나선탄!':'🌀 Spirálový projektil!','⚠ 찌르기!':'⚠ Bodnutí!',
'🔥🔥 지옥기둥!':'🔥🔥 Pekelný sloup!','⚔ 환영검!':'⚔ Fantomová čepel!',
'💢 반격자세!':'💢 Postoj protiútoku!',
'⚔ 연격!':'⚔ Kombo!','🌑 암흑!':'🌑 Tma!',
'👥 분신!':'👥 Klon!','🌋 균열!':'🌋 Zlom!',
'🌊 파동!':'🌊 Pulsace!','💣 추적지뢰!':'💣 Sledující mina!',
'⏪ 되감기!':'⏪ Přetočení!','🌀 중력장!':'🌀 Gravitační pole!',
'🔨 벽밀기!':'🔨 Tlak stěny!','☠ 독안개!':'☠ Jedovatá mlha!',
'⛓ 감옥!':'⛓ Vězení!','⚡ 연쇄번개!':'⚡ Řetězový blesk!',
'🔮 궤도탄!':'🔮 Orbitální projektil!','🛡 방패돌진!':'🛡 Výpad se štítem!',
'🪞 반격자세!':'🪞 Postoj protiútoku!','⚓ 속박!':'⚓ Pouta!',
'👤 분신!':'👤 Klon!','🖐 탈취!':'🖐 Krádež!',
'🔥🔥 용암 지대!':'🔥🔥 Lávová zóna!','🌧🌧 화염 폭격!':'🌧🌧 Ohnivé bombardování!',
'⚡⚡ 전격 장막!':'⚡⚡ Elektrická clona!','💀 내 곁으로!':'💀 Ke mně!',
'⭕ 안전!':'⭕ Bezpečí!','💀💀 전멸 폭발!':'💀💀 Výbuch vyhlazení!',
'⚡ 쐐기 소멸!':'⚡ Klín zaniká!','🌊충격파!':'🌊Rázová vlna!',
'👿악의+100':'👿Zlost+100','💥패링폭발!':'💥Výbuch parírování!',
'균열 충돌! ':'Kolize zlomu! ','벽 충돌! ':'Kolize se stěnou! ',
'소환!':'Přivolání!','환영!':'Fantom!',
'⚡낙뢰!':'⚡Hrom!','⚡빔!':'⚡Paprsek!',
'환영술!':'Iluze!','💀소환!':'💀Přivolání!',
'🔮주술!':'🔮Kletba!','🩸산란!':'🩸Rozmnožování!',
'💢광폭!':'💢Šílenství!','🕷산란!':'🕷Rozmnožování!',
'❄서리!':'❄Jinovatka!','❄빙결파!':'❄Ledová vlna!','💀빙마!':'💀Ledový démon!',
'돌진!':'Výpad!','충격파!':'Rázová vlna!','독안개!':'Jedovatá mlha!',
'연타!':'Příval!','포효!':'Řev!','강화!':'Zesílení!',
'꼬리!':'Ocas!','은신...':'Neviditelnost...','기습!':'Přepadení!',
'산란!':'Rozmnožování!','독가스!':'Jedovatý plyn!','소멸...':'Rozpuštění...',
'강타!':'Úder!','분비!':'Vylučování!','채찍!':'Bič!',
'출혈!':'Krvácení!','급강하!':'Střemhlavý pád!','방출!':'Výboj!',
'충격!':'Náraz!','치유!':'Léčení!','의식!':'Rituál!',
'지옥불!':'Pekelný oheň!','끌려감!':'Tažen!','혀!':'Jazyk!',
'응시!':'Pohled!','낙하!':'Pád!','핏방울!':'Kapka krve!',
'일어남!':'Vstání!','휩쓸기!':'Zametení!','웅크림':'Přikrčení',
'뼈칼날!':'Kostěné ostří!','감속!':'Zpomalení!','비명!':'Výkřik!',
'화산탄!':'Vulkanický projektil!','자폭!':'Sebezničení!','감싸기!':'Obalení!',
'잡기!':'Chycení!','내리찍기!':'Úder shora!','브레스!':'Dech!',
'비행!':'Let!','용암비!':'Lávový déšť!','물뿜기!':'Vodní proud!',
'빛...':'Světlo...','삼키기!':'Spolknutí!','마비!':'Paralýza!',
'방전!':'Výboj!','집게찍기!':'Úder klepety!','찍기!':'Úder!',
'붙잡기!':'Chycení!','감아올리기!':'Obtočení!','파편!':'Střep!',
'할퀴기!':'Škrábnutí!','기생충!':'Parazit!',
'심연 해방!':'Osvobození propasti!','촉수난타!':'Příval chapadel!',
'삼지창!':'Trojzubec!','소용돌이!':'Vír!','해일!':'Tsunami!',
'끼걱!':'Vrzání!','폭발!':'Výbuch!','체인!':'Řetěz!',
'갈기!':'Hříva!','공포!':'Hrůza!','흡혈!':'Vysávání krve!',
'베기!':'Řez!','비이이명!!':'Zvonění!!','분열!':'Dělení!',
'3연참!':'Trojitý řez!','패링!':'Parírování!',
'...복사...':'...Kopírování...','불균형...저주!':'Nerovnováha...Kletba!',
'저주!':'Kletba!','균형...강화!':'Rovnováha...Zesílení!',
'심판의 기둥!':'Sloup soudu!','처형 선고!':'Rozsudek smrti!',
'고통의 해방!':'Osvobození bolesti!','너도 느껴봐라!':'Pociť to taky!',
'대검난무!':'Šílenství obouručního meče!','촉수!':'Chapadlo!',
'전방위 빔!':'Všesměrový paprsek!','회피!':'Úhyb!',
'[F] 상점':'[F] Obchod','거래 성공!':'Obchod úspěšný!',
'악의 부족! (':'Nedostatek zlosti! (',
'상인이 떠납니다...':'Obchodník odchází...',
'사슬 해방!':'Osvobození řetězu!','완전 해방!':'Plné osvobození!',
'⏪ 시간 되감기!':'⏪ Přetočení času!','전환!':'Přepnutí!',
'부활 ':'Vzkříšení ','🌀균열!':'🌀Zlom!','...사라짐':'...Zmizení',
'낫 베기!':'Řez kosou!','☠ 죽음의 선고!':'☠ Rozsudek smrti!',
'선고 집행...':'Vykonání rozsudku...',
'⚡패링!':'⚡Parírování!','경직!':'Omráčení!',
'⚠ 잡혔다!':'⚠ Chycen!','💥 내던지기!':'💥 Hod!',
'💥 소용돌이 폭발!':'💥 Výbuch víru!',
'👻 순간이동!':'👻 Teleportace!','💫 기절! 5초':'💫 Omráčení! 5s',
'찌르기 반격!':'Protiúder bodnutím!','💢 폭발!':'💢 Výbuch!',
'반격 실패':'Protiúder selhal','탈취 반격!':'Proti-krádež!',
'무기 봉인!':'Zbraň zapečetěna!','냠!':'Ňam!',
'합체!':'Fúze!','출구가 열렸다!':'Východ otevřen!',
'보물상자 출현!':'Truhla s pokladem se objevila!','출구':'Východ',
'⚠ 문지기가 살아있다!':'⚠ Strážce brány žije!',
'⏱ 타임어택 ':'⏱ Časový útok ','처치율 ':'Procento zabití ',
'불사 보호':'Nesmrtelná ochrana','환영 소멸!':'Fantom zmizel!',
'부활력 ':'Síla vzkříšení ',
'✟ 신성력 억제! (':'✟ Svaté potlačení! (','부활 실패 (':'Vzkříšení neúspěšné (',
'⚡순간이동!':'⚡Teleportace!','👻 동반부활!':'👻 Společné vzkříšení!',
'✟ 신성력 억제!':'✟ Svaté potlačení!',
'💀 부활 판정 중...':'💀 Hodnocení vzkříšení...',
'⚔ 문지기 처치!':'⚔ Strážce brány poražen!','🚪 보스방 개방!':'🚪 Místnost bosse otevřena!',
'잔해 출현!':'Trosky se objevily!','🌀균열 발생!':'🌀Zlom otevřen!',
'🔥복수!':'🔥Pomsta!','💥폭독혈!':'💥Morová krev!','빙판!':'Ledová podlaha!',
'❄최종빙결!':'❄Finální zmrazení!','빙마 처치!':'Ledový démon poražen!',
'분리!':'Rozdělení!','뼈 파편!':'Kostěný střep!',
'태아 처치!':'Zárodek poražen!','지배자 처치!':'Vládce poražen!',
'용암!':'Láva!','화룡 처치!':'Ohnivý drak poražen!',
'최후의 비명!':'Poslední výkřik!','산화...':'Oxidace...',
'심판자 처치!':'Soudce poražen!','고통의 왕 처치!':'Král bolesti poražen!',
'수역!':'Vodní zóna!','파편 폭발!':'Výbuch střepů!',
'거대어 처치!':'Leviatan poražen!','대사도 처치!':'Velký apoštol poražen!',
'독웅덩이!':'Jedovatá louže!','화염장판!':'Ohnivá zóna!','전기장!':'Elektrické pole!',
'무기 드롭!':'Zbraň padla!','보물 발견!':'Poklad nalezen!',
'상인의 주머니 +':'Obchodníkův váček +',
'속박의 파편!':'Střep pout!','시간의 조각!':'Fragment času!',
'저주 해제!':'Kletba odstraněna!','차원의 결정!':'Dimenzionální krystal!',
'전설 아이템!':'Legendární předmět!','죽음을 이겨냈다!':'Smrt překonána!',
'💥대폭발!':'💥Mega výbuch!','⚡강화!':'⚡Zesílení!',
'장비 ':'Vybavení ',
'💫 진동!':'💫 Chvění!','❄ 무적!':'❄ Nezranitelný!',
'\u{1F47B} 유령!':'\u{1F47B} Přízrak!',
'집중 해제!':'Soustředění zrušeno!','집중!':'Soustředění!',
'🕊️ 평화보호 ':'🕊️ Aegida ','🛡 보호막 ':'🛡 Štít ','🌀 회전보호막 ':'🌀 Rotační štít ',
'💥한방캡!':'💥Limit zásahu!','⚡쉴드 파괴!':'⚡Štít zničen!',
'💀 불굴!':'💀 Neústupný!','💀 1회부활!':'💀 Jednorázové vzkříšení!',
'감시 회수':'Stažení stráže','악마화 부활!':'Démonické vzkříšení!',
'배정 가능한 스킬 없음':'Žádné dovednosti k přiřazení','칼날 없음!':'Žádné ostří!',
'⚔ 악의사냥!':'⚔ Lov zlosti!','❄🌪️ 얼음소용돌이!':'❄🌪️ Ledový vír!',
'🌪️ 폭풍소환!':'🌪️ Přivolání víru!',
'\u{1F9B4} 해골무덤!':'\u{1F9B4} Kostěná hrobka!',
'🌹 붉은꽃!':'🌹 Šarlatový květ!','💥 폭산탄!':'💥 Výbušný výstřel!',
'🪡 바늘출!':'🪡 Jehlový výbuch!','⚡ 전격이동!':'⚡ Bleskový krok!',
'기둥가시로 흡수됨':'Pohlceno trnem sloupu',
'🌿 가시덫!':'🌿 Trnová past!',
'👻 유령총!':'👻 Přízračné dělo!','💥 유령총 폭발!':'💥 Výbuch přízračného děla!',
'⚡ 전격의창!':'⚡ Hromové kopí!',
'🏹 공성쇠뇌 설치!':'🏹 Obléhací kuše instalována!',
'👻 유령 허수아비!':'👻 Přízračná návnada!','💥 폭발 허수아비!':'💥 Výbušná návnada!',
'축적!':'Nahromaděno!','축적 중...':'Hromadění...','만충! 재입력→폭발':'Plné! Opakuj→Výbuch',
'폭발! ':'Výbuch! ','불발...':'Selhal...','뎀':' DMG',
'🩸 폭독칼날!':'🩸 Morové ostří!','⚡날개치기!':'⚡Úder křídlem!',
'🗡 칼등날개!':'🗡 Křídlo štítu!','🏛️ 악의기둥!':'🏛️ Temný sloup!',
'🌿 기둥가시!':'🌿 Trn sloupu!','🌋 지옥강타!':'🌋 Pekelný úder!',
'💥 체간 붕괴!':'💥 Zhroucení postoje!','💫 포이즈 파괴!':'💫 Postoj zničen!',
'⚡ 뇌전걸음!':'⚡ Přízračný krok!','✟ 구속의 영역!':'✟ Doména pout!',
'✟ 신성폭발!':'✟ Svatý výbuch!','⛧ 블랙!':'⛧ Černá hvězda!',
'🌋 용암소환!':'🌋 Přivolání lávy!','필살기 배정!':'Ultimátní útok přiřazen!',
'완료':'Hotovo','합체 가능':'Fúze možná','부족':'Nedostatek',
'SP 부족! (':'Potřeba SP! (',
'🕊️ 히든: 평화의보호 해금!':'🕊️ Skryté: Aegida míru odemčena!',
'⚡ 히든: 참회 해금!':'⚡ Skryté: Pokání odemčeno!',
'배정됨':'Přiřazeno','합체 Lv.':'Fúze Úr.',
'◆ 같은 보석 스킬 습득 시 합체 가능':'◆ Fúze možná po naučení dovednosti stejného drahokamu',
'▼ 가방 → 창고 보관':'▼ Taška → Sklad','▲ 창고 → 가방 꺼내기':'▲ Sklad → Taška',
'✓ 선택됨':'✓ Vybráno',
'⟨ 입력 대기... ⟩':'⟨ Čekání... ⟩','⟨ 대기 ⟩':'⟨ Čekání ⟩',
'보조':'Podpůrný',
'키 설정 초기화 (또는 F5 키)':'Reset kláves (nebo F5)',
'아무 키 또는 마우스 버튼을 누르세요 (ESC = 취소)':'Stiskni libovolnou klávesu nebo tl. myši (ESC = zrušit)',
'WebGPU 활성':'WebGPU aktivní','WebGL2 활성':'WebGL2 aktivní',
'측정 중...':'Měření...','불러오기 실패':'Načtení selhalo','장착':'Nasazeno',
'🔒 중요잠금 아이템은 분해 선택 불가!':'🔒 Důležitě zamčené předměty nelze rozebrat!',
'장비 강화 (실패 시 재료만 소멸)':'Vylepšení (při selhání zmizí jen materiály)',
'강화 보너스 적용':'Bonus vylepšení aplikován','강화 실패!':'Vylepšení selhalo!',
'장착된 장비가 없습니다.':'Žádné nasazené vybavení.',
'충분':'Dostatečné','더 필요':'Potřeba více',
'장비 선택':'Vyber vybavení','목표치 설정':'Nastav cíl',
'악의 투입':'Investovat zlost','자동 시도':'Auto-pokus',
'목표 강화치':'Cíl vylepšení','예상 필요 악의':'Odhadovaná zlost',
'보유':'Vlastněno','강화 시작':'Začít vylepšení',
'위에서 장비를 선택하세요':'Vyber vybavení nahoře',
'⬆ 물약 강화 (최대 10단)':'⬆ Vylepšení lektvaru (max. úroveň 10)',
'필요':'Potřeba',
'악의의 분해로 — 장비를 악의로 갈아버려라':'Pec zlosti — rozmělni vybavení na zlost',
'전체 선택':'Vybrat vše','전체 해제':'Zrušit vše','희귀 이하':'Vzácný a nižší',
'어픽스 리롤!':'Přehodit afix!',
'영웅':'Hrdinský','전설':'Legendární',
'무기 타입':'Typ zbraně','활 타입':'Typ luku','보스방':'Místnost bosse','ST 부족':'Nedostatek ST',
'💀 광폭화!':'💀 Zuřivost!',
'...따라오는 거 아니야. 같은 방향일 뿐이지.':'...Nesleduji tě. Jen jdu stejným směrem.',
'공기가 달라졌어. 더 썩었군.':'Vzduch se změnil. Víc hniloby.',
'여기부터는 악마 영역이야. ...맘대로 해.':'Odsud démonické území. ...Dělej co chceš.',
'...이 냄새. 살점이 썩는 냄새야.':'...Ten pach. Hnijící maso.',
'여기 오래 있으면 미쳐. 나도, 너도.':'Zůstaň tu dlouho a zešílíš. Já taky.',
'이 길의 끝에 뭐가 있을까. ...알고 싶지도 않어.':'Co je na konci cesty? ...Nechci vědět.',
'...여기가 끝이야. 돌아갈 길은 없어.':'...Tady je konec. Cesta zpět neexistuje.',
'작살을 땅에 꽂으면 끌려간다.':'Zaboř harpunu do země a nech se táhnout.',
'Shift로 작살 던져봐!':'Zkus hodit harpunu se Shift!',
'패링 성공하면 ST가 회복된다. 공짜 자원이야.':'Úspěšné parírování obnoví ST. Zdarma.',
'패링 많이 하면 ST 걱정 없어~':'Hodně paríruj — ST nebude problém~',
'장비 분해하면 악의를 얻는다. 쓰레기도 자원이야.':'Rozebrání vybavení dá zlost. I odpad je zdroj.',
'TAB 열어서 안 쓰는 장비 분해해!':'Otevři TAB a rozeber nepoužívané vybavení!',
'그로기 상태의 적에겐 1.5배 데미지가 들어간다.':'Omráčení nepřátelé dostávají 1.5x poškoz.',
'무릎 꿇으면 전력으로 때려!':'Když kleknou — bij naplno!',
'속성 상성이 있다. 화염은 빙결에 약하고, 암전은 암흑에 약하다.':'Živly mají protiklady. Oheň slabý na led, blesk na tmu.',
'무기 속성 바꿔가면서 싸워봐!':'Zkus měnit živel zbraně!',
'빙결된 적은 1.5배 데미지를 받는다.':'Zmrzlí nepřátelé dostávají 1.5x poškoz.',
'얼리고 때리는 게 기본이야!':'Zmraz a bij — to je základ!',
'보스의 빨간 공격은 패링 가능. 보라빛은 회피만.':'Červené útoky bosse lze parírovat. Duhové jen uhýbat.',
'색깔 잘 봐! 빨강은 받아치고 무지개는 피해!':'Sleduj barvy! Červené paríruj, duhové uhni!',
'VIT를 올리면 최대 HP가 오른다. 죽기 싫으면 찍어.':'VIT zvyšuje max. HP. Investuj, pokud chceš žít.',
'STR은 근접, DEX는 활, INT는 마법! 골고루 말고 하나만!':'STR na blízko, DEX na luk, INT na magii! Soustřeď se na jedno!',
'E를 꾹 누르면 빔이 나간다. 짧게 누르면 투사체.':'Drž E pro paprsek. Ťukni E pro projektil.',
'마법 쓸 때 MP 잘 봐! 빔은 연속으로 깎여!':'Sleduj MP s magií! Paprsek rychle spotřebovává!',
'핵터와 디로이가 아이템을 주워준다. 수거 범위 안이면.':'Hecter a Deroy automaticky sbírají předměty v dosahu.',
'우리한테 고마워해~ 안 주우면 썩잖아.':'Děkuj nám~ Předměty shnijí, když je neposbíráš.',
'LCK를 올리면 레어 드롭률이 오른다.':'LCK zvyšuje šanci vzácného dropu.',
'운빨 게임이긴 하지~ LCK 올려봐!':'Je to o štěstí~ Zkus zvednout LCK!',
'강화하면 공격력이 쭉쭉 올라가! 악의만 있으면 돼!':'Vylepšení rychle zvýší ATK! Potřebuješ jen zlost!',
'강화 확률은 +1에서 99%. 높을수록 떨어진다.':'Šance vylepšení začíná na 99% pro +1. Pak klesá.',
'실패하면 악의만 날아가~ 장비는 안 부서져!':'Při selhání zmizí jen zlost~ Vybavení přežije!',
'대장간에서 장비 제작도 된다. 악의 30000개면 영웅급 이상.':'Kovárna tvoří vybavení. 30000 zlosti pro hrdinské+.',
'랜덤이지만 좋은 거 나올 수도 있어!':'Náhodné, ale může padnout něco skvělého!',
'쉴드는 마법으로, HP는 물리로 깎아야 제대로 먹힌다.':'Štít potřebuje magii, HP fyzické. Pak účinné.',
'반대로 치면 50%만 들어가! 무기 바꿔가면서 싸워!':'Špatný typ je jen 50%! Měň zbraně!',
'장비에 접두사, 접미사가 붙으면 특수 효과가 생긴다.':'Vybavení s předponou/příponou získává speciální efekty.',
'영웅급 이상 장비에만 붙어! 좋은 거 나오면 강화해!':'Jen na hrdinském+ vybavení! Vylepši dobré výsledky!',
'강화는 장비를 바꿔도 자동 이전된다. 악의만 있으면.':'Vylepšení se automaticky přenáší. Stačí zlost.',
'더 좋은 장비 나오면 바로 장착해! 강화 수치 그대로 옮겨가!':'Lepší vybavení — rovnou nasaď! Vylepšení se přenese!',
'패링을 써야 자원을 흡수한다고!':'Musíš parírovat pro pohlcení zdrojů!',
'F키 회복의 영역을 써봐. 자원이 차올라.':'Zkus F — Svatá doména. Zdroje se doplní.',
'적이 근접하면 스페이스키야! 가시덫을 활용해!':'Nepřátelé blízko — Mezerník! Trnová past!',
'기절시켜! 그로기가 터지면 데미지가 1.5배야!':'Omrač! Omráčení dává 1.5x poškoz.!',
'1번 대왕치기로 밀어버려!':'Klávesa 1 — Úder obra, odstrč je!',
'무릎 꿇었다.':'Kleklo.','지금이야! 몰아쳐!!':'Teď! Útočit!!',
'스킬 포인트 있어! K 눌러서 스킬 찍어봐!':'Máš body dovedností! Stiskni K!',
'...힘이 없으면 여기서 끝이야.':'...Bez síly tu konec.',
'...쓸 거 아니면 분해해.':'...Nepotřebuješ — rozeber.',
'아이템 넘쳐나네~ 우리가 주워줄게!':'Tolik předmětů~ Posbíráme!',
'악의가 바닥이다.':'Zlost došla.',
'TAB 열어서 장비 분해해! 쓰레기도 악의가 돼!':'Otevři TAB a rozeber! I odpad se stane zlostí!',
'좋은 장비가 있네! G 눌러서 대장간 가봐!':'Pěkné vybavení! Stiskni G pro kovárnu!',
'...강화 안 하면 그냥 고철이야.':'...Bez vylepšení je to šrot.',
'...멈추지 마. 여신은 기다리지 않는다.':'...Nezastavuj. Bohyně nečeká.',
'앞으로 가자~ 나도 여기 오래 있기 싫어.':'Pojďme dál~ Já tu taky nechci zůstávat.',
'...냄새가 짙다. 큰 놈이 있어.':'...Silný zápach. Něco velkého tu je.',
'준비됐어? 물약 확인하고!':'Připraven? Zkontroluj lektvary!',
'TAB을 눌러. 가방을 열고 장비를 입어야 한다.':'Stiskni TAB. Otevři tašku a nasaď vybavení.',
'주웠으면 껴야지! TAB!':'Sebral? Nasaď! TAB!',
'G. 대장간에서 물약도 제작할 수 있다.':'G. V kovárně lze taky tvořit lektvary.',
'악의로 물약 만들어! G키야!':'Tvoř lektvary ze zlosti! Klávesa G!',
'기절이야! Ctrl 눌러!':'Omráčení! Stiskni Ctrl!',
'Ctrl 유령걸음으로 탈출!':'Ctrl Přízračný krok k útěku!',
'Ctrl 얼음보주로 탈출!':'Ctrl Ledová sféra k útěku!',
'빨간 탄은 우클릭 패링. 무지개는 Q 패링.':'Červené: pravé tl. parírování. Duhové: Q parírování.',
'나머지는 전부 우클릭 패링 가능해!':'Zbytek lze parírovat pravým tl.!',
'빨강=우클릭, 무지개=Q 패링. 나머진 다 쳐내.':'Červené=pravé tl., Duhové=Q. Zbytek odraž.',
'무지개는 Q로 패링! 나머지는 전부 우클릭!':'Duhové — Q! Zbytek — pravé tl.!',
'빠져! 물약 마시고 안전한 곳에서 회복해.':'Ustup! Pij lektvary a regeneruj v bezpečí.',
'자원 없으면 도망가는 게 답이야!':'Žádné zdroje? Útěk je odpověď!',
'스페이스! 가시덫으로 적 묶어버려!':'Mezerník! Chyť nepřátele Trnovou pastí!',
'근접이 너무 많아! 거리 벌려!':'Příliš mnoho blízkých! Zvětši vzdálenost!',
'...둘러싸이면 끝이야. 빠져나와.':'...Obklíčí tě — konec. Vymaň se.',
'1번 대왕치기로 쓸어버려!':'Klávesa 1 — Úder obra, smeť je!',
'그로기 터지면 데미지 1.5배!':'Omráčení — 1.5x poškoz.!',
'회전참이나 광역기로 몰아! 한 놈씩 상대하면 죽어.':'Vír nebo plošný útok! Jeden po jednom — zemřeš.',
'뭉쳐있을 때가 기회야!':'Když se shluknou — to je šance!',
'E로 마력공격을 해봐! 악의 쉴드를 해제할려면 마법 공격을 해야 해!':'Zkus E pro magický útok! Magie pro rozbití štítu zlosti!',
'쉴드는 마법으로, HP는 물리로. 반대로 치면 데미지 안 들어간다.':'Štít — magií, HP — fyzicky. Špatný typ — žádné poškoz.',
'L키로 스킬 슬롯에 넣어야 쓸 수 있어.':'Stiskni L pro přiřazení dovedností.',
'C키를 눌러. 패시브 포인트가 쌓여있다.':'Stiskni C. Pasivní body se nasbíraly.',
'C키! 패시브 올리면 진짜 강해져!':'Klávesa C! Pasivky opravdu posilují!',
'스태미나가 부족하다. 무리하지 마.':'Málo výdrže. Nepřeháněj.',
'ST 없으면 스킬 못 써! 잠깐 빠져!':'Bez ST žádné dovednosti! Ustup!',
'탭 장비창을 열어봐. 아이템을 주워왔어!':'Otevři TAB. Sebrali jsme předmět!',
'좋은 거 나왔다! TAB 열어서 확인해봐!':'Něco dobrého padlo! Otevři TAB!',
'악의에 중독되면 악마가 돼서 부활력이 생긴대. 저 녀석처럼.':'Říká se, že závislost na zlosti přemění v démona se silou vzkříšení. Jako tamten.',
'혹시 너도...?':'Možná i ty...?',
'데미지가 부족하면 무기류 강화를 해야해!!':'Málo poškoz. — vylepši zbraně!!',
'G키 대장간. 강화 안 하면 여기서 계속 죽어.':'Klávesa G — kovárna. Bez vylepšení tu budeš umírat.',
'시간이 없어. 움직여.':'Není čas. Pohni se.',
'멍하게 서있으면 안 돼!':'Nestůj jako sloup!',
'...뭘 기다리는 거야?':'...Na co čekáš?',
'가자가자! 몬스터가 기다려!':'Pojďme! Příšery čekají!',
'여기 오래 있으면 위험해.':'Zůstávat tu je nebezpečné.',
'움직여야 해! 가만있으면 둘러싸여!':'Pohni se! Budeš stát — obklíčí tě!',
'쉬는 건 죽고 나서 해.':'Odpočinek po smrti.',
'살아있을 때 쉬면 안 돼!':'Žádný odpočinek dokud žiješ!',
'적이 몰려오고 있어. 빨리 움직여.':'Nepřátelé se blíží. Pohni se.',
'냄새 맡고 올 거야. 빨리!':'Ucítí tě. Rychle!',
'...아직 살아있는 거 맞지?':'...Opravdu ještě žiješ?',
'혹시 잠든 거야...?':'Snad jsi neusnul...?',
'...나무가 썩어가고 있어. 여기는 지옥의 입구야.':'...Stromy hnijí. Tady je vchod do pekla.',
'냄새 지독해... 빨리 지나가자.':'Smrad je hrozný... Pojďme rychle.',
'조심해. 벌레굴이다. 벽이랑 바닥에서 기어나와.':'Pozor. Červí doupě. Lezou ze stěn a podlahy.',
'으으... 벌레 싫어! 밟아버려!':'Fuj... Nesnáším hmyz! Pošlapej je!',
'...공기가 얼어붙는다. 여기선 화염이 먹힌다.':'...Vzduch mrzne. Tady funguje oheň.',
'추워... 빙결 조심해! 얼면 끝이야.':'Zima... Pozor na zmrazení! Zmrzneš — konec.',
'용암이다. 바닥을 밟으면 타 죽어.':'Láva. Šlápneš na zem — uhořeš.',
'뜨거워! 여기 왜 이렇게 빨개!':'Horko! Proč je tu vše červené!',
'...군단이다. 수가 많아. 광역기 없으면 밀려.':'...Legie. Hodně jich. Bez plošných útoků zaplaví.',
'우글우글... 징그러워. 한꺼번에 쓸어!':'Hemží se... Odporné. Smeť je naráz!',
'사도의 영역이야. 여기 놈들은 머리가 좋아.':'Území apoštola. Tihle jsou chytří.',
'패턴이 복잡해졌어... 집중해!':'Vzorce se zkomplikovaly... Soustřeď se!',
'...끝이다. 지옥의 심장부. 살아 돌아가는 건 포기해라.':'...Tohle je konec. Srdce pekla. Zapomeň na návrat.',
'여기가 마지막이야... 각오해.':'Tohle je finále... Připrav se.',
};
const _CS_PFX={
'녹슨':'Rezavý','강철':'Ocelový','흑요석':'Obsidiánový','미스릴':'Mithrilový','심판의':'Soudný','천벌의':'Boží trest','파멸의':'Ničivý',
'불꽃':'Plamenný','화염':'Pekelný','염화':'Pekelný plamen','지옥불':'Pekelný žár','지옥화':'Pekelný žár','지옥':'Pekelný žár','멸화의':'Spalující',
'냉기':'Mrazivý','빙결':'Ledový','빙하':'Ledovcový','서리의':'Jinovatý','서리':'Jinovatý','영겁빙':'Věčný led',
'그림자':'Stínový','암흑':'Temný','심연':'Propastný','나락의':'Podzemní','나락':'Podzemní','무간의':'Prázdnotový',
'전기':'Jiskřivý','낙뢰':'Hromový','암전':'Bleskový','뇌신의':'Boha hromů','뇌신':'Boha hromů','만뢰의':'Tisícebleskový',
'축복':'Požehnaný','성광':'Svaté světlo','신성':'Posvátný','천사의':'Andělský','신벌의':'Boží soud',
'낡은':'Opotřebovaný','천':'Plátěný','가죽':'Kožený','강철사':'Ocelotkaninový','은':'Stříbrný','은사':'Stříbronit','화염의':'Pekelný','빙결의':'Ledový','암흑의':'Temný','암전의':'Bleskový'};
const _CS_BASE={
'대검':'Obouruční meč','석궁':'Kuše','연사석궁':'Opakovací kuše','마력석궁':'Arkanová kuše',
'견갑':'Nárameník','대견갑':'Velký nárameník','전투화':'Bojové boty','갑옷':'Brnění','갑주':'Plátová zbroj',
'왕관':'Koruna','장갑':'Rukavice','건틀릿':'Plátové rukavice','바지':'Kalhoty','각반':'Holenní chrániče',
'허리띠':'Opasek','벨트':'Pás','부적':'Talisman','목걸이':'Náhrdelník','반지':'Prsten',
'망토':'Plášť','팔찌':'Náramek','귀걸이':'Náušnice'};
