// 지옥의 길 — Čeština (cs)
const _CS={
// --- Stage / Boss ---
'썩은 숲':'Shnilý les','숲의 감시자':'Strážce lesa','독버섯 거인':'Jedovatý houbový obr','숲의 사냥꾼':'Lesní lovec','숲의 기생수':'Lesní parazit',
'1장 — 썩은 숲':'K.1 — Shnilý les','2장 — 벌레굴':'K.2 — Červí doupě','3장 — 얼음굴':'K.3 — Ledová jeskyně',
'4장 — 고통의 화염지대':'K.4 — Pekelné pustiny','5장 — 지옥의 군단':'K.5 — Pekelná legie','6장 — 사도의 마굴':'K.6 — Apoštolovo doupě','7장 — 지옥성':'K.7 — Pekelná citadela',
'탈출!':'Útěk!','처치':'Zabití','경험치':'Zkušenosti','최대콤보':'Max. kombo',
// --- Tutorial (Crow) ---
'일어나. 여신이 널 여기 보낸 건 죽으라고가 아니야.':'Vstávej. Bohyně tě sem neposlala, abys umřel.',
'좋아, 감각이 있군. 계속 쳐!':'Dobře, máš instinkt. Pokračuj v boji!',
'Shift를 눌러. 작살이다. 땅에 꽂아서 끌려가!':'Stiskni Shift. To je harpuna. Zaboř ji a nech se táhnout!',
'작살로 끌려가는 중엔 무적이다. 위험할 때 쓰면 좋아.':'Během tažení harpunou jsi nezranitelný. Používej v nebezpečí.',
'...아파? 당연하지. 여긴 지옥이야.':'...Bolí to? Samozřejmě. Tady je peklo.',
'Q를 눌러! 악의로 보호막을 만들 수 있다.':'Stiskni Q! Vytvoř štít ze zlosti.',
'보호막 없이 버틸 생각은 버려.':'Zapomeň na přežití bez štítu.',
'우클릭이 패링이다. 적 공격이 닿기 직전에 눌러!':'Pravé tl. je parírování. Stiskni těsně před úderem nepřítele!',
'못 하겠으면 때려. 안 죽으면 그만이야.':'Neumíš parírovat? Prostě bij. Hlavní je neumřít.',
'됐어! 감 잡았구나.':'Tak! Už to chytáš.',
'하나 죽었군.':'Jeden hotový.',
'유령쇠뇌야. 인사해.':'To je přízračná kuše. Pozdrav ji.',
'빨간 탄을 무서워하지 마. 악의가 강하다.':'Neboj se červených střel. Zlost je silná.',
'패링으로 돌려주고, Q 보호막도 써! 악의를 잘 굴려!':'Paríruj zpět, používej Q štít! Ovládej zlost!',
'무지개빛은 패링 불가! 피해!':'Duhové nelze parírovat! Uhni!',
'피가 새고 있다. Shift. 빠져.':'Krvácíš. Shift. Ustup.',
'물약 있잖아! 숫자키!':'Máš lektvary! Číselné klávesy!',
'우클릭. 적 손목이 꺾일 때 쳐.':'Pravé tl. Bij, když se zápěstí nepřítele ohne.',
'빨간 탄은 악의 덩어리다. 쳐내서 이용해.':'Červené střely jsou kusy zlosti. Odraz a využij.',
'무지개빛만 피하면 돼! 나머지는 다 패링!':'Prostě uhni duhovým! Zbytek paríruj!',
'Q 보호막도 패링이 가능해!':'Q štít může taky parírovat!',
'위험해! 쉬프트 사슬기동으로 피해!!':'Nebezpečí! Shift řetězový výpad k úniku!!',
'쉬프트! 사슬기동은 이동기야! 끌려가면서 무적이라고!':'Shift! Řetězový výpad je pohyb! Nezranitelný během tažení!',
'스킬포인트가 쌓였어! K 눌러서 스킬 배우자!':'Body dovedností se nasbíraly! Stiskni K pro učení!',
'속성을 읽어. 약점을 찌르면 두 배로 썩는다.':'Čti živly. Zasáhni slabiny — dvojité poškození.',
'K를 눌러봐! 스킬을 배울 수 있어!':'Stiskni K! Můžeš se učit dovednosti!',
'C 눌러서 능력치 찍어! 패시브도 있어~':'Stiskni C pro statistiky! Pasivky taky~',
'G를 눌러. 대장간에서 장비를 강화할 수 있다.':'Stiskni G. Vylepši vybavení v kovárně.',
'F키도 스킬 슬롯이야! 스킬 많으면 L로 배정해봐~':'F je taky slot dovednosti! Použij L pro přiřazení~',
'Z. 필살기다. 아껴 써라.':'Z. To je ultimátní útok. Používej moudře.',
'L-CTRL로 유령걸음이나 얼음보주 쓸 수 있어!':'L-CTRL pro Přízračný krok nebo Ledovou sféru!',
'L을 눌러. 스킬 슬롯을 정리해야 한다.':'Stiskni L. Uspořádej sloty dovedností.',
'가방 터지겠다! V 눌러서 창고에 넣어둬!':'Taška praskne! Stiskni V pro uložení do skladu!',
'ESC로 설정 열 수 있어! 난이도 바꾸기, 자동물약 조절~':'ESC pro nastavení! Obtížnost, auto-lektvary~',
// --- Tutorial (Cat) ---
'...아직 살아있네. 좌클릭으로 저것들 쳐봐.':'...Ještě žiješ. Zkus na ně levé tl.',
'...치는 건 할 줄 아네. 피하는 건?':'...Bít umíš. A uhýbat?',
'흥, 작살 못 맞추면 헛수고야.':'Hmf, mineš harpunu — marná snaha.',
'...운이 좋았을 뿐이야. 아마.':'...Jen štěstí. Asi.',
'...고기 냄새. 싫진 않네.':'...Vůně masa. Není špatná.',
'...말은 못해.':'...Neumí mluvit.',
'예쁘다고 만지면 죽어.':'Dotkneš se, protože je to hezké? Umřeš.',
'작살 던져! 끌려가면 무적이야!':'Hoď harpunu! Nezranitelný během tažení!',
'...마시든 말든. 네 목숨이니까.':'...Pij nebo ne. Je to tvůj život.',
'그게 패링이야! 타이밍이 전부야~':'To je parírování! Načasování je vše~',
'화염엔 빙결! 암전엔 암흑! 기억해!':'Oheň bije led! Blesk bije tmu! Pamatuj!',
'...얼어붙은 놈은 오래 안 간다.':'...Zmrzlí dlouho nevydrží.',
'얼었어! 빙결 중 1.5배야!':'Zmrzlý! 1.5x poškození během zmrazení!',
'...힘을 골라라. 전부 가질 순 없다.':'...Vyber si sílu. Nemůžeš mít vše.',
'스탯을 올려. 살고 싶으면.':'Zvedni statistiky. Pokud chceš žít.',
'좋은 장비는 강화해야 진짜 힘을 발휘해!':'Dobré vybavení potřebuje vylepšení pro skutečnou sílu!',
'...슬롯을 채워. 빈 손은 죽음이다.':'...Zaplň sloty. Prázdné ruce znamenají smrt.',
'Z 누르면 대박! 쿨타임 길어서 타이밍 봐야 해!':'Z pro silný úder! Dlouhá obnova, zvol moment!',
'Ctrl. 위기에 쓸 카드가 하나 늘었군.':'Ctrl. Další karta pro nouzové situace.',
'스킬이 많아졌네~ L로 어디에 뭘 넣을지 골라!':'Tolik dovedností~ Použij L pro přiřazení!',
'...버리기 아까운 건 창고에.':'...Co je škoda zahodit — do skladu.',
'...살아남은 것만으로도 대단하군. 설정을 확인해.':'...Přežít je samo o sobě úspěch. Zkontroluj nastavení.',
// --- System Messages ---
'MP 부족!':'Nedostatek MP!','ST 부족!':'Nedostatek ST!','악의 부족!':'Nedostatek zlosti!',
'충전 중...':'Nabíjení...','캔슬':'Zrušit','아이템 선택 필요':'Vyber předmět',
'악의 소진...':'Zlost vyčerpána...','비문 발견...':'Nápis nalezen...',
'HP물약!':'HP lektvar!','HP물약 +1':'HP lektvar +1','HP물약 +2':'HP lektvar +2',
'HP/MP/ST 회복!':'HP/MP/ST obnoveno!','보물상자 개봉!':'Truhla otevřena!',
'익사!':'Topení!','피웅덩이!':'Krvavá louže!','독혈!':'Toxická krev!','잡힘!':'Chycen!',
'콤보 종료':'Konec komba',
// --- Status Effects ---
'빙결!':'Zmrzlý!','화상!':'Popálenina!','독!':'Jed!','감전!':'Šok!',
'기절!':'Omráčení!','봉인됨!':'Zapečetěn!','관통!':'Průraz!',
// --- Skill Names ---
'기검참':'Ki úder','악의구':'Koule zlosti','회전참':'Vír','기폭팔':'Detonace',
'칼등 처내기':'Parírování čepelí','만화방창':'Příval jehel','멸살광선':'Paprsek zkázy',
'원소추적탄':'Živlový hledač','악의 보호자':'Strážce zlosti','악의 사냥':'Lov zlosti',
'폭풍소환':'Přivolání víru','해골무덤':'Kostěná hrobka','신성폭발':'Svatý výbuch',
'블랙':'Černá hvězda','용암소환':'Přivolání lávy','처형':'Poprava','악마화 부활':'Démonické vzkříšení',
'붉은꽃':'Šarlatový květ','얼음보주':'Ledová sféra','뇌전걸음':'Přízračný krok',
'만화방창 II':'Příval jehel II','마력연사':'Arkanová palba','마력광선':'Arkanový laser','업화선':'Pekelný paprsek',
'지옥진':'Pekelná formace','폭독칼날':'Morové ostří','악의폭풍':'Bouře zlosti',
'악의기둥':'Temný sloup','회복의 영역':'Svatá doména','구속의 영역':'Doména pout',
'아이스스톰':'Ledová bouře','대왕치기':'Úder obra','대왕치기 2':'Úder obra II',
'기동불꽃':'Řetězový plamen','기동파괴':'Řetězové ničení','기동칼날개':'Řetězové ostří',
'평화의보호':'Aegida míru','참회':'Pokání','칼등날개':'Křídlo štítu',
'폭산탄':'Výbušný výstřel','파쇄의 영역':'Doména drcení','침식의 영역':'Doména koroze',
'관통의 영역':'Doména průrazu','부활의 영역':'Doména vzkříšení','가시덫':'Trnová past',
'푸른비':'Azurový déšť','버스트루프':'Smyčka výbuchu','유령 허수아비':'Přízračná návnada','폭발 허수아비':'Výbušná návnada',
'공성쇠뇌':'Obléhací kuše','사슬기동:충돌':'Řetězový výpad: Náraz',
'사슬기동:화염':'Řetězový výpad: Plamen','전격이동':'Bleskový krok',
// --- Skill Activation ---
'기동칼날개!':'Řetězové ostří!','기동불꽃!':'Řetězový plamen!','기동파괴!':'Řetězové ničení!',
'사슬이동:강화!':'Řetězový výpad!','사슬기동:화염!':'Řetězový plamen!',
'작살!':'Harpuna!','진입!':'Vstup!','레인라이트닝!':'Déšť blesků!',
'마력연사!':'Arkanová palba!','🔷 마력광선!':'🔷 Arkanový laser!','광선 해제':'Laser vyp.','MP 부족 — 광선 해제':'MP vyčerpáno — Laser vyp.','집중...':'Soustředění...','시전...':'Sesílání...',
'만화방창!':'Příval jehel!','바늘출!':'Jehlový výbuch!','칼날!':'Ostří!',
'착지!':'Přistání!','체간삭감!':'Zlomení postoje!',
'기동전폭 준비!':'Řetězový výbuch připraven!','기동불꽃 준비!':'Řetězový plamen připraven!',
'기동파괴 준비!':'Řetězové ničení připraveno!',
'유령불꽃 ON':'Přízračný plamen ZAP','유령불꽃 OFF':'Přízračný plamen VYP',
'기동칼날개 AUTO ON':'Řetězové ostří AUTO ZAP','기동칼날개 AUTO OFF':'Řetězové ostří AUTO VYP',
'자동 버스트!':'Auto výbuch!','연사 해제':'Rychlopalba vyp.',
'당기기 모드':'Režim tažení','밀어내기 모드':'Režim tlačení',
// --- Skill Slot Tooltips ---
'날개치기':'Úder křídlem','처내기':'Parírování',
'Shift: 작살 발사 → 끌려감':'Shift: Hod harpunou → tažení',
'Shift: 화염길+화상':'Shift: Ohnivá stopa+popálenina',
'CT: 전류변신+뇌전걸음 (쿨4초)':'CT: Elektroforma+Přízračný krok (CD 4s)',
'CT: 방어구체+빙결 (재입력: 파쇄)':'CT: Ledová sféra+zmrazení (opakovat: drcení)',
// --- HUD ---
'근접':'Blízký','견갑':'Obrana','작살':'Harpuna','마법':'Magie','보막':'Štít','유령':'Přízrak',
'스킬':'Dovednosti','대장':'Kovárna','인벤':'Výbava',
// --- Menu ---
'인벤토리':'Inventář','복수의 대장간':'Kovárna pomsty','패시브 스킬':'Pasivní dovednosti',
'전투 스킬':'Bojové dovednosti','캐릭터 선택':'Výběr postavy',
// --- Elements ---
'물리':'Fyzické','화염':'Oheň','빙결':'Led','암흑':'Tma','암전':'Blesk','신성':'Svaté','대지':'Země',
// --- Passives ---
'힘':'Síla','민첩':'Obratnost','지능':'Inteligence','행운':'Štěstí',
'맹공':'Nápor','철벽':'Neústupnost','돌파':'Průlom','반격':'Protiúder',
'마력폭주':'Arkanový příval','정밀사격':'Přesná střelba','수호':'Ochrana','수호신':'Strážný duch',
'회복력':'Regenerace','급소':'Přesný zásah','약탈':'Loupež','관통':'Průraz',
'마력회복':'Obnova many','쇠뇌력':'Mistrovství kuše','광전사':'Berserk','추적자':'Stopař',
'물리관통':'Fyz. průraz','마법관통':'Mag. průraz',
// --- Weapons ---
'녹슨 대검':'Rezavý obouruční meč','강철 대검':'Ocelový obouruční meč','흑요석 대검':'Obsidiánový obouruční meč',
'낡은 석궁':'Opotřebovaná kuše','강철 석궁':'Ocelová kuše','흑요석 석궁':'Obsidiánová kuše',
'대검':'Obouruční meč','석궁':'Kuše','연사석궁':'Opakovací kuše','마력석궁':'Arkanová kuše',
// --- Misc ---
'악의 추출':'Extrakce zlosti','악의':'Zlost','필살기':'Ultimátní útok','필살기 해제':'Ultimátní útok odebrán',
'이전':'Přenos','강화':'Vylepšení','개봉!':'Otevřeno!',
'여신의 가호':'Bohyniino požehnání','과부하!':'Přetížení!',
// --- Affix Names ---
'맹독의':'Jedovatý','불꽃의':'Plamenný','냉기의':'Mrazivý','번개의':'Elektrický','암흑의':'Prokletý',
'관통의':'Průrazný','광폭의':'Zuřivý','파쇄의':'Drtivý','연쇄의':'Řetězový',
'학살의':'Zabijácký','폭발의':'Výbušný','집중의':'Soustředěný','쾌속의':'Rychlý','패리의':'Odrazný',
'추적자의':'Stopaře','작살의':'Harpunový','궁극의':'Nejvyšší','집중력의':'Pozorný',
'강인의':'Houževnatý','수호의':'Ochranný','활력의':'Životný','신속의':'Zrychlený',
'화염수호':'Ohnivá ochrana','빙결수호':'Ledová ochrana','암전수호':'Blesková ochrana','암흑수호':'Ochrana tmy','독수호':'Ochrana jedu','전원소수호':'Plná živ. ochrana',
'강철의':'Železný','반사의':'Odrážecí','가시의':'Trnový','흡수의':'Pohlcující','인내의':'Vytrvalý',
'위기의':'Zoufalý','피격반격의':'Protiútočný',
'패링폭발의':'Výbuch parírování','스태거폭발의':'Výbuch omráčení','원소전환의':'Konvertor','정화의':'Očistný',
'불굴의':'Neústupný','부활의':'Vzkřísivý',
'약탈의':'Loupežný','경험의':'Zkušený','골드의':'Zlatý','포션강화의':'Zesílený lektvar','사슬의':'Řetězový',
'진혼의':'Posvěcující','윤회의':'Cyklický',
'생명력의':'Vitální','재생의':'Regenerující','치유의':'Léčivý',
'마력의':'Arkanový','절약의':'Úsporný','영혼의':'Duševní',
'예리한':'Ostrý','맹렬한':'Brutální','파멸의':'Ničivý',
// --- Settings UI ---
'게임 설정':'Nastavení hry','화면 흔들림':'Třes obrazovky','파티클 양':'Množství částic',
'효과음 볼륨':'Hlasitost SFX','음악 볼륨':'Hlasitost hudby','난이도':'Obtížnost',
'자동 물약':'Auto lektvar','최소 줍기 등급':'Min. stupeň sbírání','최소 줍기 티어':'Min. tier sbírání',
'FPS 제한':'Limit FPS','해상도 스케일':'Škálování rozlišení','펫 자동수거':'Auto-sběr mazlíčka',
'화면 설정':'Nastavení displeje','화면 모드':'Režim displeje','보스 AI 디버그':'Debug AI bosse',
'유령불꽃 크기':'Velikost přízračného plamene','화면 명암':'Jas','유령 글로우':'Přízračná záře',
'기동:칼날개 AUTO':'Řetězové ostří AUTO',
'일반':'Normální','어려움':'Těžká','지옥':'Peklo','이상':'a výše','사용 안 함':'Vypnuto',
'창 모드':'V okně','보더리스':'Bez okrajů','전체화면':'Celá obrazovka',
'설정':'Nastavení','조작 키 설정 (클릭하여 변경)':'Přiřazení kláves (klikni pro změnu)',
// --- Key Guide ---
'좌클릭 무기 공격':'Levé tl. Útok zbraní','우클릭 탭 칼등 처내기':'Pravé tl. Tap parírování',
'우클릭 홀드 연속 처내기':'Pravé tl. Držení parírování','SHIFT 작살 발사':'SHIFT Hod harpunou',
'이동':'Pohyb','아이템 줍기':'Sebrat předmět','능력치 (스탯/패시브)':'Atributy (Staty/Pasivky)',
// --- Forge ---
'복수의 대장간':'Kovárna pomsty','분해':'Rozebrat','제작':'Vytvořit',
// --- Death Screen ---
'사망':'Smrt','부활':'Vzkříšení','로비로':'Do lobby',
// --- Inventory/Storage ---
'가방에 공간이 없습니다!':'Není místo v tašce!','가방이 가득 찼습니다!':'Taška je plná!',
'창고가 가득 찼습니다!':'Sklad je plný!','퀵슬롯이 가득 찼습니다!':'Rychlý slot je plný!',
'결정 주머니가 가득 찼습니다!':'Váček krystalů plný!','결정 주머니 가득!':'Váček krystalů plný!',
'악의가 부족합니다!':'Nedostatek zlosti!','가방이 비어있습니다':'Taška je prázdná',
'창고가 비어있습니다':'Sklad je prázdný','비어있음':'Prázdné','어픽스 없음':'Bez afixu',
'장착!':'Nasazeno!','해제':'Sundáno','보관':'Uložit','꺼내기':'Vyjmout',
'현재 장착':'Právě nasazeno','없음 — 제작하세요!':'Žádné — vytvořte!',
'리셋할 포인트가 없습니다':'Žádné body k resetu','키 설정 초기화 완료':'Klávesy resetovány',
// --- Forge/Craft ---
'제작 확률':'Šance vytvoření','제작 비용':'Cena vytvoření','보유 악의':'Vlastněná zlost',
// --- Canvas UI ---
'보스방':'Místnost bosse','안식처':'Útočiště','회복':'Obnovit','점화':'Zapálit',
'비석':'Stéla','읽기':'Číst','파괴':'Zničit','제단':'Oltář','기원':'Modlitba',
'잔해':'Trosky','열기':'Otevřít','문지기':'Strážce brány',
'부활 판정 중...':'Hodnocení vzkříšení...','기폭 준비!':'Detonace připravena!',
'탈출':'Útěk','연타':'Mačkej',
'추적암전':'Sledující blesk','만화광선':'Paprsek záře','최종 마법':'Finální magie',
'감시중':'Sledování','대기':'Pohotovost','작동중':'Aktivní','설치 가능':'Lze instalovat',
'균열 임박!':'Zlom blízko!','흡수 중...':'Pohlcování...',
'흡수 완료 — 재입력으로 회수':'Hotovo — stiskni znovu pro sběr',
'화상':'Popálenina','당기기':'Táhnout','밀어내기':'Tlačit',
'단계':'úroveň','단':'úroveň',
// --- Skill Panel ---
'습득!':'Naučeno!','리셋!':'Resetováno!','세팅!':'Nastaveno!','회수':'Získat zpět',
'합체 해제':'Zrušit fúzi','리셋':'Reset','환불':'Vrátit',
'파트너 클릭!':'Klikni partnera!','SP부족!':'Potřeba SP!',
'같은 보석 스킬 습득 시 합체 가능':'Fúze možná po naučení dovednosti stejného drahokamu',
'펼쳐서 초기화':'Rozbal pro reset','슬롯:':'Slot:',
// --- Stats ---
'남은 SP':'Zbývající SP','맞아서 사망':'Smrt úderem','레벨':'Úroveň','최대HP':'Max. HP',
// --- Enemy Names ---
'방랑 기사':'Putující rytíř','보물 악마':'Démon pokladů','거울의 사도':'Zrcadlový apoštol',
'상인 악마':'Démon obchodník','사슬의 죄수':'Spoutaný vězeň','시간의 사도':'Apoštol času',
'탐욕의 사도':'Apoštol chamtivosti','저주받은 쌍둥이':'Prokletá dvojčata','차원 균열체':'Dimenzionální zlom','죽음 그 자체':'Sama smrt',
// --- Crystals ---
'HP결정':'HP krystal','ST결정':'ST krystal','MP결정':'MP krystal',
'ATK결정':'ATK krystal','DEF결정':'DEF krystal','속도결정':'Krystal rychlosti',
'크리결정':'Krystal kritu','치명결정':'Krystal krit. poškoz.','화염결정':'Krystal ohně',
'냉기결정':'Krystal ledu','암흑결정':'Krystal tmy','번개결정':'Krystal blesku',
'신성결정':'Krystal svatého','생명결정':'Krystal života','기력결정':'Krystal výdrže',
'마력결정':'Krystal many','행운결정':'Krystal štěstí',
'조각':'Úlomek','파편':'Střep','순수결정':'Čistý krystal','완전결정':'Dokonalý krystal',
'결정 주머니':'Váček krystalů','결정이 없습니다':'Žádné krystaly','가루':'Prášek',
'전체':'Vše','스탯':'Stat','원소':'Živel','유틸':'Nástroje',
'현재':'Aktuálně','최대 강화 달성 (+20)':'Max. vylepšení (+20)','강화 시':'Po vylepšení',
'합성':'Syntéza',
'같은 종류·같은 성급 결정 3개 → 1성급 상승 (강화 리셋)':'3 krystaly stejného typu a stupně → +1 stupeň (vylepšení reset)',
'합성 가능한 결정이 없습니다 (같은 종류·성급 3개 필요)':'Žádné krystaly k syntéze (potřeba 3 stejného typu a stupně)',
'결정 분해 → 결정 가루':'Rozebrat krystal → prášek','분해할 결정이 없습니다':'Žádné krystaly k rozebrání',
'결정 제작 (가루 → 결정)':'Vytvořit krystal (prášek → krystal)',
'탈착':'Sundat','빈 슬롯':'Prázdný slot',
'결정 선택 후 클릭':'Vyber krystal a klikni','클릭하여 선택결정 장착':'Klikni pro nasazení krystalu',
'획득!':'Získáno!','제작!':'Vytvořeno!','합성!':'Syntezováno!','최상위 일괄합성':'Hromadná syntéza na max.','일괄합성 완료':'Hromadná syntéza dokončena',
// --- Stage Names ---
'벌레굴':'Červí doupě','얼음굴':'Ledová jeskyně','고통의 화염지대':'Pekelné pustiny',
'지옥의 군단':'Pekelná legie','사도의 마굴':'Apoštolovo doupě','지옥성':'Pekelná citadela',
// --- Misc ---
'엑소듀서 전사':'Válečník Exoduser','포이즈':'Postoj','신성폭발':'Svatý výbuch','뇌전걸음':'Přízračný krok',
'지옥창고':'Pekelný sklad','선택분해':'Selektivní rozebírání','쓰레기':'Odpad',
'복구 불가!':'Nelze obnovit!','중요잠금':'Důležité-zamčeno',
'자동 장착!':'Auto-nasazeno!','분해! 가루 +':'Rozebráno! Prášek +',
'평화보호':'Aegida','지진폭풍':'Zemětřesení','회전기폭':'Vírová det.',
'공격':'Útok','보호막':'Štít',
'합체 스킬로 통합됨':'Sloučeno do fúzní dovednosti','얼음보주 안에선 사용 불가!':'Nelze použít v Ledové sféře!',
'Shift+키로 폭파':'Shift+klávesa pro detonaci','취소':'Zrušit',
'쿨다운 중...':'Obnova...','시전 중...':'Sesílání...',
'악의 부족! (12)':'Nedostatek zlosti! (12)','악의 부족! (15)':'Nedostatek zlosti! (15)',
'악의 부족! (20)':'Nedostatek zlosti! (20)','악의 부족! (10)':'Nedostatek zlosti! (10)',
'ST 부족!':'Nedostatek ST!','HP 부족!':'Nedostatek HP!',
'필살기 슬롯 클릭하여 배정!':'Klikni na slot ultimátního útoku!',
'필살기 스킬을 습득하세요':'Nauč se ultimátní dovednost',
'우클릭(칼등치기)에 합체됨':'Sloučeno s pravým tl. (parírování)',
'T(석궁자동)에 세팅하세요':'Nastav na T (auto-kuše)',
'공성쇠뇌 철거 → 이동식':'Obléhací kuše demontována → přenosná',
'ST 부족! (100)':'Nedostatek ST! (100)',
'HP 99% 이상!':'HP 99%+!','그로기 보스 없음!':'Žádný omráčený boss!',
'이미 폭풍 지역!':'Už v zóně bouře!','이미 빙풍 지역!':'Už v zóně ledové bouře!',
'💎 푸른비 해금!':'💎 Azurový déšť odemčen!','💫 버스트루프 해금!':'💫 Smyčka výbuchu odemčena!',
'👻 유령 허수아비 해금!':'👻 Přízračná návnada odemčena!',
'쿨 ':'CD ','과부하 ':'Přetížení ',
'🕊️💎 블루콩!':'🕊️💎 Modrý fazol!','🛡️💎 빨콩→블루콩!':'🛡️💎 Červený→Modrý fazol!','🛡️💎 무지개→블루콩!':'🛡️💎 Duhový→Modrý fazol!',
'레어':'Vzácný','슬롯':'Slot',
'성공률':'Šance úspěchu','AI 자동 강화':'AI auto-vylepšení','최대 강화 달성!':'Max. vylepšení dosaženo!',
'최대 강화':'Max. vylepšení','회복량':'Obnovení',
'분해할 아이템이 없습니다.':'Žádné předměty k rozebrání.','🔨 제작':'🔨 Vytvořit',
'체간':'Postoj','아이템에 마우스를 올리거나 좌클릭으로 선택하세요':'Najeď na předmět nebo klikni levým tl.',
'중독':'Jed','지뢰':'Mina','함정':'Past','산호가시':'Korálový trn',
'투사체':'Projektil','도트':'DoT','레어몹':'Vzácný mob','구역':'Zóna','가시!':'Trn!',
'림보':'Limbo','색욕':'Chtíč','탐식':'Obžerství','탐욕':'Chamtivost','분노':'Hněv','이단':'Kacířství','폭력':'Násilí',
'분노!':'Zuřivost!','탐욕!':'Chamtivost!','💀 분노 폭발!':'💀 Výbuch zuřivosti!','심연의 분노!':'Zuřivost propasti!','쌍둥이의 분노!':'Zuřivost dvojčat!',
'소환굴':'Vyvolávací nora',
'처치!':'Poražen!','왕관 착용':'Koruna zap.','왕관 해제':'Koruna vyp.',
'맨손':'Holé ruce','없음':'Žádné','갑옷':'Brnění','부츠':'Boty',
'매직':'Magický','챔피언':'Šampion',
'초속':'Zrychlení','강타':'Úder','재생':'Regenerace','맹독':'Jed','소환':'Přivolání',
'기생':'Parazit','분열':'Dělení','용암자취':'Lávová stopa','사망폭발':'Smrtelný výbuch',
'화염사슬':'Ohnivý řetěz','광전':'Šílenství','텔레포트':'Teleportace',
'소용돌이':'Vír','환영':'Fantom','전격반사':'Odraz blesku','감전':'Elektrošok',
'낙뢰':'Hrom','연쇄전격':'Řetězový blesk','동료불사':'Nesmrtelnost spojence',
'영혼포식':'Požírání duší','시간왜곡':'Zakřivení času','혼돈변이':'Chaotická mutace',
'복수자':'Mstitel','마법보초':'Magická stráž','환영술사':'Iluzionista',
'함성':'Válečný pokřik','치유':'Léčení','신속':'Rychlost','수호':'Strážce',
'다크 판타지 전사. 거대검+검은 갑옷':'Temný fantasy válečník. Obouruční meč + Černé brnění',
'⚡ 사슬이동:강화!':'⚡ Řetěz:Zesílení!','⚡ 사슬기동:화염!':'⚡ Řetěz: Plamen!',
'달성!':'Dosaženo!','ST':'ST','부족!':'Nedostatek!','타':'Zásah',
'🌀 당기기 모드':'🌀 Režim tažení','💥 밀어내기 모드':'💥 Režim tlačení',
'🕊️빨콩 흡수':'🕊️Pohlcení červ. fazolu','🕊️흡수':'🕊️Pohlcení',
'💎유도 폭발!':'💎Naváděný výbuch!','💥반사 폭발!':'💥Odrazený výbuch!',
'⚡⚡ 참회 귀환!':'⚡⚡ Návrat pokání!','⚡ 참회!':'⚡ Pokání!',
'파도!':'Vlna!','암전!':'Blesk!','암흑!':'Tma!','암흑창!':'Temné kopí!','빛창!':'Světelné kopí!',
'체 소환!':'přivoláno!','개 설치!':'instalováno!',
'💥 보스 그로기!':'💥 Boss omráčen!','💥 그로기!':'💥 Omráčení!','보상':'Bonus',
'⚡ 암전나선!':'⚡ Blesková spirála!','🌋 지진폭풍!':'🌋 Zemětřesení!',
'SP슬롯':'SP Slot','F슬롯':'F Slot',
'⚔🩸 독혈해방!':'⚔🩸 Morové osvobození!','⚔ 칼날 해방!':'⚔ Osvobození ostří!',
'🔨🌋 지옥강타!':'🔨🌋 Pekelný úder!','🔨 대왕치기!':'🔨 Úder obra!',
'✟ 결계의 영역!':'✟ Doména bariéry!','✟ 물의 영역!':'✟ Doména vody!','✟ 파쇄의 영역!':'✟ Doména drcení!','✟ 침식의 영역!':'✟ Doména koroze!','✟ 관통의 영역!':'✟ Doména průrazu!','✟ 권능의 영역!':'✟ Doména svrchovanosti!',
'🛡 회복의 영역!':'🛡 Svatá doména!',
'임계...!':'Kritické...!',
'기폭팔!':'Detonace!','강제기폭!':'Vynucená detonace!','자동기폭!':'Auto-detonace!',
'회전기폭!':'Vírová detonace!','해제기폭!':'Detonace uvolnění!','지진기폭!':'Seizmická detonace!',
'혼돈의 왕관':'Koruna chaosu','전지전능의 왕관':'Koruna všemohoucnosti',
'악마의 팔찌':'Démonický náramek','생명의 팔찌':'Náramek života',
'🌊 위→아래 파도!':'🌊 Shora→dolů vlna!','🌊 오른→왼 파도!':'🌊 Zprava→doleva vlna!',
'🌊 아래→위 파도!':'🌊 Zdola→nahoru vlna!','🌊 왼→오른 파도!':'🌊 Zleva→doprava vlna!',
'무적!':'Nezranitelný!','🪞 반격!':'🪞 Protiúder!','💢 반격!':'💢 Protiúder!',
'흡수!':'Pohlcení!','반격 발사!':'Odvetný výstřel!',
'저주! 드랍률 -50%':'Kletba! Šance dropu -50%','도망!':'Útěk!',
'위상!':'Fáze!','방어!':'Obrana!',
'회수 HP+':'Získání HP+','이동식 복귀':'Návrat přenosné','캔슬':'Zrušit',
'약점!':'Slabina!','저항!':'Odolnost!',
'콤보 종료: ':'Konec komba: ',
'악의 +':'Zlost +','저주 ':'Kletba ','불발...':'Selhal...',
'작살 약점!':'Slabina harpuny!',
'전염 x':'Nákaza x','흡수 완료!':'Pohlcení dokončeno!',
'부활 성공!':'Vzkříšení úspěšné!','부활 실패...':'Vzkříšení neúspěšné...',
'산호가시':'Korálový trn','차원 이동!':'Dimenzionální skok!',
'기절 해제':'Omráčení odstraněno',
'악의 부족':'Nedostatek zlosti',
'스킬 미습득':'Žádné naučené dovednosti','펼치기':'Rozbalit','접기':'Sbalit',
'조건 미달!':'Podmínka nesplněna!','해제!':'Odstraněno!',
'자동 ON':'Auto ZAP','자동 OFF':'Auto VYP','스킬 해제':'Dovednost odebrána',
'닫기':'Zavřít','장착 중':'Nasazeno','보관 아이템':'Uložený předmět',
'클릭으로 선택 · ESC로 닫기':'Klikni pro výběr · ESC pro zavření','선택됨':'Vybráno',
'악의 부족! (30)':'Nedostatek zlosti! (30)',
'MP 부족! (40)':'Nedostatek MP! (40)','MP 부족! (100)':'Nedostatek MP! (100)','MP 부족! (10)':'Nedostatek MP! (10)',
'MP 부족! (':'Nedostatek MP! (',
'✟ 시전...':'✟ Sesílání...','🌋 시전...':'🌋 Sesílání...','⛧ 시전...':'⛧ Sesílání...',
'❄ 진입!':'❄ Vstup!','🔱 작살!':'🔱 Harpuna!',
'레벨 부족! (요구: Lv.':'Úroveň příliš nízká! (Potřeba: Lv.',
' 장착!':' Nasazeno!',' 해제':' Sundáno',
'👿 악의 추출: +':'👿 Extrakce zlosti: +','F 슬롯 해제':'F Slot odebrán',
'💫 집중...':'💫 Soustředění...','⚡ 마력연사!':'⚡ Arkanová palba!',
'❄빙결!':'❄Zmrzlý!','🟢독!':'🟢Jed!','⚡감전!':'⚡Šok!','🔥화상!':'🔥Popálenina!',
'✦ 여신의 가호 — SP+5 AP+3':'✦ Požehnání bohyně — SP+5 AP+3',
'⚔ 기동칼날개!':'⚔ Řetězové ostří!','🔥 화염관통!':'🔥 Ohnivý průraz!',
'🔱 관통!':'🔱 Průraz!','⚔ 칼날!':'⚔ Ostří!','💥 착지!':'💥 Přistání!',
'💫 기절!':'💫 Omráčení!','⚡ 체간삭감!':'⚡ Zlomení postoje!',
'⚡ 기동파괴! ':'⚡ Řetězové ničení! ',
'🔥 기동불꽃!':'🔥 Řetězový plamen!','🔥 기동불꽃! ':'🔥 Řetězový plamen! ',
'단계 ×':' x','⚡ 기동전폭! x':'⚡ Řetězový výbuch! x',
'🔥🔥 3중폭!':'🔥🔥 Trojitý plamen!','🔥🔥🔥 6중폭!':'🔥🔥🔥 6x plamen!','🔥🔥🔥🔥 9중폭!':'🔥🔥🔥🔥 9x plamen!','💥 불꽃폭발! ':'💥 Výbuch plamene! ',
'🔥 기동불꽃 준비!':'🔥 Řetězový plamen připraven!','🔨 기동파괴 준비!':'🔨 Řetězové ničení připraveno!','⚡ 기동전폭 준비!':'⚡ Řetězový výbuch připraven!',
'⚡ 과부하! 5초':'⚡ Přetížení! 5s','💫 자동 버스트!':'💫 Auto výbuch!',
'🔨 칼등날개!':'🔨 Křídlo štítu!','💥폭발!':'💥Výbuch!',
'🛡️💎 유도반사!':'🛡️💎 Naváděný odraz!',
'⚡💎 블루콩!':'⚡💎 Modrý fazol!','💎 블루콩!':'💎 Modrý fazol!',
'⚡반사!':'⚡Odraz!',
'💎 푸른비 OFF':'💎 Azurový déšť VYP','💎 푸른비 ON!':'💎 Azurový déšť ZAP!',
'🔥 지옥진!':'🔥 Pekelná formace!','🔥 업화선!':'🔥 Pekelný paprsek!',
'✦ 평화 충격파! ':'✦ Vlna míru! ','⚡ 전류 방출!':'⚡ Elektrický výboj!',
'⚡⚡ 레인라이트닝!':'⚡⚡ Déšť blesků!','💫 광역!':'💫 Plošný útok!',
'🔥 불장판!':'🔥 Ohnivá zóna!','💫 피니셔!':'💫 Finisher!',
'☠ 지옥에서 귀환!':'☠ Návrat z pekla!','☠ 완전 사망!':'☠ Trvalá smrt!',
'⚔ 처형! ':'⚔ Poprava! ','💥 지뢰!':'💥 Mina!','⚠ 함정!':'⚠ Past!',
'❌ 우클릭으로! -':'❌ Použij pravé tl.! -','❌ Q키로! -':'❌ Použij Q! -',
'💥무지개 폭발! ':'💥Duhový výbuch! ','🛡️💎 블루콩!':'🛡️💎 Modrý fazol!',
'⬜화이트볼!':'⬜Bílý míč!','✨💎 블루콩!':'✨💎 Modrý fazol!','💜다크볼!':'💜Temný míč!',
'❄빙판!':'❄Ledová podlaha!','🌨빙결!':'🌨Zmrzlý!','🕸둔화!':'🕸Zpomalení!','⚠트랩!':'⚠Past!',
'💀 역병 처형!':'💀 Morová poprava!','💥 역병 Finale!':'💥 Morový finále!',
'⚔ 균열 악마!':'⚔ Démon zlomu!','자동회수 HP+':'Auto-získání HP+',
'MP 부족 — 연사 해제':'MP málo — Rychlopalba vyp.','MP 부족 — 푸른비 OFF':'MP málo — Azurový déšť VYP',
'🛡️반사!':'🛡️Odraz!','⚡🦴 참회 귀환!':'⚡🦴 Návrat pokání!',
'🦴⚡해골번개!':'🦴⚡Kostěný blesk!','⚡악의폭풍!':'⚡Bouře zlosti!',
'❄아이스스톰!':'❄Ledová bouře!','⚡ 암전폭발!':'⚡ Výbuch blesku!',
'⚡ 레인라이트닝! x':'⚡ Déšť blesků! x','❄ 탈출!':'❄ Útěk!',
'⚡쉴드!':'⚡Štít!','❄🌪️ 얼음보주!':'❄🌪️ Ledová sféra!',
'🌪️ 전개!':'🌪️ Rozvinutí!','❄ 빙결흡인!':'❄ Ledový vír!',
'❄☄ 빙결폭발!':'❄☄ Ledový výbuch!','☄️ 흡인!':'☄️ Vír!','☄️ 대폭발!':'☄️ Mega výbuch!',
'❄ 얼음보주!':'❄ Ledová sféra!','⏳ 시간왜곡!':'⏳ Zakřivení času!','쿨다운!':'Obnova!',
'❄ 파쇄!':'❄ Drcení!','☄️💥 대폭발!':'☄️💥 Mega výbuch!','반사!':'Odraz!',
'💀 도넛!':'💀 Donut!','💀 전멸!':'💀 Vyhlazení!',
'🌊 파도!':'🌊 Vlna!','속박!':'Pouta!','반격!':'Protiúder!',
'분신!':'Klon!','분신 파괴!':'Klon zničen!','무기 해방!':'Osvobození zbraně!',
'❄프리즌!':'❄Vězení!','⚡ 증표 ':'⚡ Značka ',
'흔들!':'Otřes!','⚠ 광역 발사!':'⚠ Plošná palba!',
'🔥 확산!':'🔥 Šíření!','⚠ 돌진!':'⚠ Výpad!',
'🦅 도약!':'🦅 Skok!','⚡ 레이저!':'⚡ Laser!',
'🌊 충격파!':'🌊 Rázová vlna!','👹 소환!':'👹 Přivolání!',
'☄ 유성우!':'☄ Meteorický déšť!','🖐 잡기!':'🖐 Chycení!',
'🌀 회전참!':'🌀 Vír!','💣 지뢰!':'💣 Mina!',
'🌀 흡인!':'🌀 Vakuum!','🔴 빨간콩 폭풍!':'🔴 Bouře červených fazolů!',
'🔴🔴 콩 비!':'🔴🔴 Déšť fazolů!',
'🌊 부채꼴 충격파!':'🌊 Vějířová rázová vlna!',
'✴ 멸광 레이저!':'✴ Laser zkázy!','🔴 추적 장판!':'🔴 Sledující zóna!',
'💥 속성탄!':'💥 Živlový projektil!',
'⚔ 검기!':'⚔ Ki meče!','⚔ 재단참!':'⚔ Žnivý úder!',
'🌀 나선탄!':'🌀 Spirálový projektil!','⚠ 찌르기!':'⚠ Bodnutí!',
'🔥🔥 지옥기둥!':'🔥🔥 Pekelný sloup!','⚔ 환영검!':'⚔ Fantomová čepel!',
'💢 반격자세!':'💢 Postoj protiútoku!',
'⚔ 연격!':'⚔ Kombo!','🌑 암흑!':'🌑 Tma!',
'👥 분신!':'👥 Klon!','🌋 균열!':'🌋 Zlom!',
'🌊 파동!':'🌊 Pulsace!','💣 추적지뢰!':'💣 Sledující mina!',
'⏪ 되감기!':'⏪ Přetočení!','🌀 중력장!':'🌀 Gravitační pole!',
'🔨 벽밀기!':'🔨 Tlak stěny!','☠ 독안개!':'☠ Jedovatá mlha!',
'⛓ 감옥!':'⛓ Vězení!','⚡ 연쇄번개!':'⚡ Řetězový blesk!',
'🔮 궤도탄!':'🔮 Orbitální projektil!','🛡 방패돌진!':'🛡 Výpad se štítem!',
'🪞 반격자세!':'🪞 Postoj protiútoku!','⚓ 속박!':'⚓ Pouta!',
'👤 분신!':'👤 Klon!','🖐 탈취!':'🖐 Krádež!',
'🔥🔥 용암 지대!':'🔥🔥 Lávová zóna!','🌧🌧 화염 폭격!':'🌧🌧 Ohnivé bombardování!',
'⚡⚡ 전격 장막!':'⚡⚡ Elektrická clona!','💀 내 곁으로!':'💀 Ke mně!',
'⭕ 안전!':'⭕ Bezpečí!','💀💀 전멸 폭발!':'💀💀 Výbuch vyhlazení!',
'⚡ 쐐기 소멸!':'⚡ Klín zaniká!','🌊충격파!':'🌊Rázová vlna!',
'👿악의+100':'👿Zlost+100','💥패링폭발!':'💥Výbuch parírování!',
'균열 충돌! ':'Kolize zlomu! ','벽 충돌! ':'Kolize se stěnou! ',
'소환!':'Přivolání!','환영!':'Fantom!',
'⚡낙뢰!':'⚡Hrom!','⚡빔!':'⚡Paprsek!',
'환영술!':'Iluze!','💀소환!':'💀Přivolání!',
'🔮주술!':'🔮Kletba!','🩸산란!':'🩸Rozmnožování!',
'💢광폭!':'💢Šílenství!','🕷산란!':'🕷Rozmnožování!',
'❄서리!':'❄Jinovatka!','❄빙결파!':'❄Ledová vlna!','💀빙마!':'💀Ledový démon!',
'돌진!':'Výpad!','충격파!':'Rázová vlna!','독안개!':'Jedovatá mlha!',
'연타!':'Příval!','포효!':'Řev!','강화!':'Zesílení!',
'꼬리!':'Ocas!','은신...':'Neviditelnost...','기습!':'Přepadení!',
'산란!':'Rozmnožování!','독가스!':'Jedovatý plyn!','소멸...':'Rozpuštění...',
'강타!':'Úder!','분비!':'Vylučování!','채찍!':'Bič!',
'출혈!':'Krvácení!','급강하!':'Střemhlavý pád!','방출!':'Výboj!',
'충격!':'Náraz!','치유!':'Léčení!','의식!':'Rituál!',
'지옥불!':'Pekelný oheň!','끌려감!':'Tažen!','혀!':'Jazyk!',
'응시!':'Pohled!','낙하!':'Pád!','핏방울!':'Kapka krve!',
'일어남!':'Vstání!','휩쓸기!':'Zametení!','웅크림':'Přikrčení',
'뼈칼날!':'Kostěné ostří!','감속!':'Zpomalení!','비명!':'Výkřik!',
'화산탄!':'Vulkanický projektil!','자폭!':'Sebezničení!','감싸기!':'Obalení!',
'잡기!':'Chycení!','내리찍기!':'Úder shora!','브레스!':'Dech!',
'비행!':'Let!','용암비!':'Lávový déšť!','물뿜기!':'Vodní proud!',
'빛...':'Světlo...','삼키기!':'Spolknutí!','마비!':'Paralýza!',
'방전!':'Výboj!','집게찍기!':'Úder klepety!','찍기!':'Úder!',
'붙잡기!':'Chycení!','감아올리기!':'Obtočení!','파편!':'Střep!',
'할퀴기!':'Škrábnutí!','기생충!':'Parazit!',
'심연 해방!':'Osvobození propasti!','촉수난타!':'Příval chapadel!',
'삼지창!':'Trojzubec!','소용돌이!':'Vír!','해일!':'Tsunami!',
'끼걱!':'Vrzání!','폭발!':'Výbuch!','체인!':'Řetěz!',
'갈기!':'Hříva!','공포!':'Hrůza!','흡혈!':'Vysávání krve!',
'베기!':'Řez!','비이이명!!':'Zvonění!!','분열!':'Dělení!',
'3연참!':'Trojitý řez!','패링!':'Parírování!',
'...복사...':'...Kopírování...','불균형...저주!':'Nerovnováha...Kletba!',
'저주!':'Kletba!','균형...강화!':'Rovnováha...Zesílení!',
'심판의 기둥!':'Sloup soudu!','처형 선고!':'Rozsudek smrti!',
'고통의 해방!':'Osvobození bolesti!','너도 느껴봐라!':'Pociť to taky!',
'대검난무!':'Šílenství obouručního meče!','촉수!':'Chapadlo!',
'전방위 빔!':'Všesměrový paprsek!','회피!':'Úhyb!',
'[F] 상점':'[F] Obchod','거래 성공!':'Obchod úspěšný!',
'악의 부족! (':'Nedostatek zlosti! (',
'상인이 떠납니다...':'Obchodník odchází...',
'사슬 해방!':'Osvobození řetězu!','완전 해방!':'Plné osvobození!',
'⏪ 시간 되감기!':'⏪ Přetočení času!','전환!':'Přepnutí!',
'부활 ':'Vzkříšení ','🌀균열!':'🌀Zlom!','...사라짐':'...Zmizení',
'낫 베기!':'Řez kosou!','☠ 죽음의 선고!':'☠ Rozsudek smrti!',
'선고 집행...':'Vykonání rozsudku...',
'⚡패링!':'⚡Parírování!','경직!':'Omráčení!',
'⚠ 잡혔다!':'⚠ Chycen!','💥 내던지기!':'💥 Hod!',
'💥 소용돌이 폭발!':'💥 Výbuch víru!',
'👻 순간이동!':'👻 Teleportace!','💫 기절! 5초':'💫 Omráčení! 5s',
'찌르기 반격!':'Protiúder bodnutím!','💢 폭발!':'💢 Výbuch!',
'반격 실패':'Protiúder selhal','탈취 반격!':'Proti-krádež!',
'무기 봉인!':'Zbraň zapečetěna!','냠!':'Ňam!',
'합체!':'Fúze!','출구가 열렸다!':'Východ otevřen!',
'보물상자 출현!':'Truhla s pokladem se objevila!','출구':'Východ',
'⚠ 문지기가 살아있다!':'⚠ Strážce brány žije!',
'⏱ 타임어택 ':'⏱ Časový útok ','처치율 ':'Procento zabití ',
'불사 보호':'Nesmrtelná ochrana','환영 소멸!':'Fantom zmizel!',
'부활력 ':'Síla vzkříšení ',
'✟ 신성력 억제! (':'✟ Svaté potlačení! (','부활 실패 (':'Vzkříšení neúspěšné (',
'⚡순간이동!':'⚡Teleportace!','👻 동반부활!':'👻 Společné vzkříšení!',
'✟ 신성력 억제!':'✟ Svaté potlačení!',
'💀 부활 판정 중...':'💀 Hodnocení vzkříšení...',
'⚔ 문지기 처치!':'⚔ Strážce brány poražen!','🚪 보스방 개방!':'🚪 Místnost bosse otevřena!',
'잔해 출현!':'Trosky se objevily!','🌀균열 발생!':'🌀Zlom otevřen!',
'🔥복수!':'🔥Pomsta!','💥폭독혈!':'💥Morová krev!','빙판!':'Ledová podlaha!',
'❄최종빙결!':'❄Finální zmrazení!','빙마 처치!':'Ledový démon poražen!',
'분리!':'Rozdělení!','뼈 파편!':'Kostěný střep!',
'태아 처치!':'Zárodek poražen!','지배자 처치!':'Vládce poražen!',
'용암!':'Láva!','화룡 처치!':'Ohnivý drak poražen!',
'최후의 비명!':'Poslední výkřik!','산화...':'Oxidace...',
'심판자 처치!':'Soudce poražen!','고통의 왕 처치!':'Král bolesti poražen!',
'수역!':'Vodní zóna!','파편 폭발!':'Výbuch střepů!',
'거대어 처치!':'Leviatan poražen!','대사도 처치!':'Velký apoštol poražen!',
'독웅덩이!':'Jedovatá louže!','화염장판!':'Ohnivá zóna!','전기장!':'Elektrické pole!',
'무기 드롭!':'Zbraň padla!','보물 발견!':'Poklad nalezen!',
'상인의 주머니 +':'Obchodníkův váček +',
'속박의 파편!':'Střep pout!','시간의 조각!':'Fragment času!',
'저주 해제!':'Kletba odstraněna!','차원의 결정!':'Dimenzionální krystal!',
'전설 아이템!':'Legendární předmět!','죽음을 이겨냈다!':'Smrt překonána!',
'💥대폭발!':'💥Mega výbuch!','⚡강화!':'⚡Zesílení!',
'장비 ':'Vybavení ',
'💫 진동!':'💫 Chvění!','❄ 무적!':'❄ Nezranitelný!',
'\u{1F47B} 유령!':'\u{1F47B} Přízrak!',
'집중 해제!':'Soustředění zrušeno!','집중!':'Soustředění!',
'🕊️ 평화보호 ':'🕊️ Aegida ','🛡 보호막 ':'🛡 Štít ','🌀 회전보호막 ':'🌀 Rotační štít ',
'💥한방캡!':'💥Limit zásahu!','⚡쉴드 파괴!':'⚡Štít zničen!',
'💀 불굴!':'💀 Neústupný!','💀 1회부활!':'💀 Jednorázové vzkříšení!',
'감시 회수':'Stažení stráže','악마화 부활!':'Démonické vzkříšení!',
'배정 가능한 스킬 없음':'Žádné dovednosti k přiřazení','칼날 없음!':'Žádné ostří!',
'⚔ 악의사냥!':'⚔ Lov zlosti!','❄🌪️ 얼음소용돌이!':'❄🌪️ Ledový vír!',
'🌪️ 폭풍소환!':'🌪️ Přivolání víru!',
'\u{1F9B4} 해골무덤!':'\u{1F9B4} Kostěná hrobka!',
'🌹 붉은꽃!':'🌹 Šarlatový květ!','💥 폭산탄!':'💥 Výbušný výstřel!',
'🪡 바늘출!':'🪡 Jehlový výbuch!','⚡ 전격이동!':'⚡ Bleskový krok!',
'기둥가시로 흡수됨':'Pohlceno trnem sloupu',
'🌿 가시덫!':'🌿 Trnová past!',
'👻 유령총!':'👻 Přízračné dělo!','💥 유령총 폭발!':'💥 Výbuch přízračného děla!',
'⚡ 전격의창!':'⚡ Hromové kopí!',
'🏹 공성쇠뇌 설치!':'🏹 Obléhací kuše instalována!',
'👻 유령 허수아비!':'👻 Přízračná návnada!','💥 폭발 허수아비!':'💥 Výbušná návnada!',
'축적!':'Nahromaděno!','축적 중...':'Hromadění...','만충! 재입력→폭발':'Plné! Opakuj→Výbuch',
'폭발! ':'Výbuch! ','불발...':'Selhal...','뎀':' DMG',
'🩸 폭독칼날!':'🩸 Morové ostří!','⚡날개치기!':'⚡Úder křídlem!',
'🗡 칼등날개!':'🗡 Křídlo štítu!','🏛️ 악의기둥!':'🏛️ Temný sloup!',
'🌿 기둥가시!':'🌿 Trn sloupu!','🌋 지옥강타!':'🌋 Pekelný úder!',
'💥 체간 붕괴!':'💥 Zhroucení postoje!','💫 포이즈 파괴!':'💫 Postoj zničen!',
'⚡ 뇌전걸음!':'⚡ Přízračný krok!','✟ 구속의 영역!':'✟ Doména pout!',
'✟ 신성폭발!':'✟ Svatý výbuch!','⛧ 블랙!':'⛧ Černá hvězda!',
'🌋 용암소환!':'🌋 Přivolání lávy!','필살기 배정!':'Ultimátní útok přiřazen!',
'완료':'Hotovo','합체 가능':'Fúze možná','부족':'Nedostatek',
'SP 부족! (':'Potřeba SP! (',
'🕊️ 히든: 평화의보호 해금!':'🕊️ Skryté: Aegida míru odemčena!',
'⚡ 히든: 참회 해금!':'⚡ Skryté: Pokání odemčeno!',
'배정됨':'Přiřazeno','합체 Lv.':'Fúze Úr.',
'◆ 같은 보석 스킬 습득 시 합체 가능':'◆ Fúze možná po naučení dovednosti stejného drahokamu',
'▼ 가방 → 창고 보관':'▼ Taška → Sklad','▲ 창고 → 가방 꺼내기':'▲ Sklad → Taška',
'✓ 선택됨':'✓ Vybráno',
'⟨ 입력 대기... ⟩':'⟨ Čekání... ⟩','⟨ 대기 ⟩':'⟨ Čekání ⟩',
'보조':'Podpůrný',
'키 설정 초기화 (또는 F5 키)':'Reset kláves (nebo F5)',
'아무 키 또는 마우스 버튼을 누르세요 (ESC = 취소)':'Stiskni libovolnou klávesu nebo tl. myši (ESC = zrušit)',
'WebGPU 활성':'WebGPU aktivní','WebGL2 활성':'WebGL2 aktivní',
'측정 중...':'Měření...','불러오기 실패':'Načtení selhalo','장착':'Nasazeno',
'🔒 중요잠금 아이템은 분해 선택 불가!':'🔒 Důležitě zamčené předměty nelze rozebrat!',
'장비 강화 (실패 시 재료만 소멸)':'Vylepšení (při selhání zmizí jen materiály)',
'강화 보너스 적용':'Bonus vylepšení aplikován','강화 실패!':'Vylepšení selhalo!',
'장착된 장비가 없습니다.':'Žádné nasazené vybavení.',
'충분':'Dostatečné','더 필요':'Potřeba více',
'장비 선택':'Vyber vybavení','목표치 설정':'Nastav cíl',
'악의 투입':'Investovat zlost','자동 시도':'Auto-pokus',
'목표 강화치':'Cíl vylepšení','예상 필요 악의':'Odhadovaná zlost',
'보유':'Vlastněno','강화 시작':'Začít vylepšení',
'위에서 장비를 선택하세요':'Vyber vybavení nahoře',
'⬆ 물약 강화 (최대 10단)':'⬆ Vylepšení lektvaru (max. úroveň 10)',
'필요':'Potřeba',
'악의의 분해로 — 장비를 악의로 갈아버려라':'Pec zlosti — rozmělni vybavení na zlost',
'전체 선택':'Vybrat vše','전체 해제':'Zrušit vše','희귀 이하':'Vzácný a nižší',
'어픽스 리롤!':'Přehodit afix!',
'영웅':'Hrdinský','전설':'Legendární',
'무기 타입':'Typ zbraně','활 타입':'Typ luku','보스방':'Místnost bosse','ST 부족':'Nedostatek ST',
'💀 광폭화!':'💀 Zuřivost!',
'...따라오는 거 아니야. 같은 방향일 뿐이지.':'...Nesleduji tě. Jen jdu stejným směrem.',
'공기가 달라졌어. 더 썩었군.':'Vzduch se změnil. Víc hniloby.',
'여기부터는 악마 영역이야. ...맘대로 해.':'Odsud démonické území. ...Dělej co chceš.',
'...이 냄새. 살점이 썩는 냄새야.':'...Ten pach. Hnijící maso.',
'여기 오래 있으면 미쳐. 나도, 너도.':'Zůstaň tu dlouho a zešílíš. Já taky.',
'이 길의 끝에 뭐가 있을까. ...알고 싶지도 않어.':'Co je na konci cesty? ...Nechci vědět.',
'...여기가 끝이야. 돌아갈 길은 없어.':'...Tady je konec. Cesta zpět neexistuje.',
'작살을 땅에 꽂으면 끌려간다.':'Zaboř harpunu do země a nech se táhnout.',
'Shift로 작살 던져봐!':'Zkus hodit harpunu se Shift!',
'패링 성공하면 ST가 회복된다. 공짜 자원이야.':'Úspěšné parírování obnoví ST. Zdarma.',
'패링 많이 하면 ST 걱정 없어~':'Hodně paríruj — ST nebude problém~',
'장비 분해하면 악의를 얻는다. 쓰레기도 자원이야.':'Rozebrání vybavení dá zlost. I odpad je zdroj.',
'TAB 열어서 안 쓰는 장비 분해해!':'Otevři TAB a rozeber nepoužívané vybavení!',
'그로기 상태의 적에겐 1.5배 데미지가 들어간다.':'Omráčení nepřátelé dostávají 1.5x poškoz.',
'무릎 꿇으면 전력으로 때려!':'Když kleknou — bij naplno!',
'속성 상성이 있다. 화염은 빙결에 약하고, 암전은 암흑에 약하다.':'Živly mají protiklady. Oheň slabý na led, blesk na tmu.',
'무기 속성 바꿔가면서 싸워봐!':'Zkus měnit živel zbraně!',
'빙결된 적은 1.5배 데미지를 받는다.':'Zmrzlí nepřátelé dostávají 1.5x poškoz.',
'얼리고 때리는 게 기본이야!':'Zmraz a bij — to je základ!',
'보스의 빨간 공격은 패링 가능. 보라빛은 회피만.':'Červené útoky bosse lze parírovat. Duhové jen uhýbat.',
'색깔 잘 봐! 빨강은 받아치고 무지개는 피해!':'Sleduj barvy! Červené paríruj, duhové uhni!',
'VIT를 올리면 최대 HP가 오른다. 죽기 싫으면 찍어.':'VIT zvyšuje max. HP. Investuj, pokud chceš žít.',
'STR은 근접, DEX는 활, INT는 마법! 골고루 말고 하나만!':'STR na blízko, DEX na luk, INT na magii! Soustřeď se na jedno!',
'E를 꾹 누르면 빔이 나간다. 짧게 누르면 투사체.':'Drž E pro paprsek. Ťukni E pro projektil.',
'마법 쓸 때 MP 잘 봐! 빔은 연속으로 깎여!':'Sleduj MP s magií! Paprsek rychle spotřebovává!',
'핵터와 디로이가 아이템을 주워준다. 수거 범위 안이면.':'Hecter a Deroy automaticky sbírají předměty v dosahu.',
'우리한테 고마워해~ 안 주우면 썩잖아.':'Děkuj nám~ Předměty shnijí, když je neposbíráš.',
'LCK를 올리면 레어 드롭률이 오른다.':'LCK zvyšuje šanci vzácného dropu.',
'운빨 게임이긴 하지~ LCK 올려봐!':'Je to o štěstí~ Zkus zvednout LCK!',
'강화하면 공격력이 쭉쭉 올라가! 악의만 있으면 돼!':'Vylepšení rychle zvýší ATK! Potřebuješ jen zlost!',
'강화 확률은 +1에서 99%. 높을수록 떨어진다.':'Šance vylepšení začíná na 99% pro +1. Pak klesá.',
'실패하면 악의만 날아가~ 장비는 안 부서져!':'Při selhání zmizí jen zlost~ Vybavení přežije!',
'대장간에서 장비 제작도 된다. 악의 30000개면 영웅급 이상.':'Kovárna tvoří vybavení. 30000 zlosti pro hrdinské+.',
'랜덤이지만 좋은 거 나올 수도 있어!':'Náhodné, ale může padnout něco skvělého!',
'쉴드는 마법으로, HP는 물리로 깎아야 제대로 먹힌다.':'Štít potřebuje magii, HP fyzické. Pak účinné.',
'반대로 치면 50%만 들어가! 무기 바꿔가면서 싸워!':'Špatný typ je jen 50%! Měň zbraně!',
'장비에 접두사, 접미사가 붙으면 특수 효과가 생긴다.':'Vybavení s předponou/příponou získává speciální efekty.',
'영웅급 이상 장비에만 붙어! 좋은 거 나오면 강화해!':'Jen na hrdinském+ vybavení! Vylepši dobré výsledky!',
'강화는 장비를 바꿔도 자동 이전된다. 악의만 있으면.':'Vylepšení se automaticky přenáší. Stačí zlost.',
'더 좋은 장비 나오면 바로 장착해! 강화 수치 그대로 옮겨가!':'Lepší vybavení — rovnou nasaď! Vylepšení se přenese!',
'패링을 써야 자원을 흡수한다고!':'Musíš parírovat pro pohlcení zdrojů!',
'F키 회복의 영역을 써봐. 자원이 차올라.':'Zkus F — Svatá doména. Zdroje se doplní.',
'적이 근접하면 스페이스키야! 가시덫을 활용해!':'Nepřátelé blízko — Mezerník! Trnová past!',
'기절시켜! 그로기가 터지면 데미지가 1.5배야!':'Omrač! Omráčení dává 1.5x poškoz.!',
'1번 대왕치기로 밀어버려!':'Klávesa 1 — Úder obra, odstrč je!',
'무릎 꿇었다.':'Kleklo.','지금이야! 몰아쳐!!':'Teď! Útočit!!',
'스킬 포인트 있어! K 눌러서 스킬 찍어봐!':'Máš body dovedností! Stiskni K!',
'...힘이 없으면 여기서 끝이야.':'...Bez síly tu konec.',
'...쓸 거 아니면 분해해.':'...Nepotřebuješ — rozeber.',
'아이템 넘쳐나네~ 우리가 주워줄게!':'Tolik předmětů~ Posbíráme!',
'악의가 바닥이다.':'Zlost došla.',
'TAB 열어서 장비 분해해! 쓰레기도 악의가 돼!':'Otevři TAB a rozeber! I odpad se stane zlostí!',
'좋은 장비가 있네! G 눌러서 대장간 가봐!':'Pěkné vybavení! Stiskni G pro kovárnu!',
'...강화 안 하면 그냥 고철이야.':'...Bez vylepšení je to šrot.',
'...멈추지 마. 여신은 기다리지 않는다.':'...Nezastavuj. Bohyně nečeká.',
'앞으로 가자~ 나도 여기 오래 있기 싫어.':'Pojďme dál~ Já tu taky nechci zůstávat.',
'...냄새가 짙다. 큰 놈이 있어.':'...Silný zápach. Něco velkého tu je.',
'준비됐어? 물약 확인하고!':'Připraven? Zkontroluj lektvary!',
'TAB을 눌러. 가방을 열고 장비를 입어야 한다.':'Stiskni TAB. Otevři tašku a nasaď vybavení.',
'주웠으면 껴야지! TAB!':'Sebral? Nasaď! TAB!',
'G. 대장간에서 물약도 제작할 수 있다.':'G. V kovárně lze taky tvořit lektvary.',
'악의로 물약 만들어! G키야!':'Tvoř lektvary ze zlosti! Klávesa G!',
'기절이야! Ctrl 눌러!':'Omráčení! Stiskni Ctrl!',
'Ctrl 유령걸음으로 탈출!':'Ctrl Přízračný krok k útěku!',
'Ctrl 얼음보주로 탈출!':'Ctrl Ledová sféra k útěku!',
'빨간 탄은 우클릭 패링. 무지개는 Q 패링.':'Červené: pravé tl. parírování. Duhové: Q parírování.',
'나머지는 전부 우클릭 패링 가능해!':'Zbytek lze parírovat pravým tl.!',
'빨강=우클릭, 무지개=Q 패링. 나머진 다 쳐내.':'Červené=pravé tl., Duhové=Q. Zbytek odraž.',
'무지개는 Q로 패링! 나머지는 전부 우클릭!':'Duhové — Q! Zbytek — pravé tl.!',
'빠져! 물약 마시고 안전한 곳에서 회복해.':'Ustup! Pij lektvary a regeneruj v bezpečí.',
'자원 없으면 도망가는 게 답이야!':'Žádné zdroje? Útěk je odpověď!',
'스페이스! 가시덫으로 적 묶어버려!':'Mezerník! Chyť nepřátele Trnovou pastí!',
'근접이 너무 많아! 거리 벌려!':'Příliš mnoho blízkých! Zvětši vzdálenost!',
'...둘러싸이면 끝이야. 빠져나와.':'...Obklíčí tě — konec. Vymaň se.',
'1번 대왕치기로 쓸어버려!':'Klávesa 1 — Úder obra, smeť je!',
'그로기 터지면 데미지 1.5배!':'Omráčení — 1.5x poškoz.!',
'회전참이나 광역기로 몰아! 한 놈씩 상대하면 죽어.':'Vír nebo plošný útok! Jeden po jednom — zemřeš.',
'뭉쳐있을 때가 기회야!':'Když se shluknou — to je šance!',
'E로 마력공격을 해봐! 악의 쉴드를 해제할려면 마법 공격을 해야 해!':'Zkus E pro magický útok! Magie pro rozbití štítu zlosti!',
'쉴드는 마법으로, HP는 물리로. 반대로 치면 데미지 안 들어간다.':'Štít — magií, HP — fyzicky. Špatný typ — žádné poškoz.',
'L키로 스킬 슬롯에 넣어야 쓸 수 있어.':'Stiskni L pro přiřazení dovedností.',
'C키를 눌러. 패시브 포인트가 쌓여있다.':'Stiskni C. Pasivní body se nasbíraly.',
'C키! 패시브 올리면 진짜 강해져!':'Klávesa C! Pasivky opravdu posilují!',
'스태미나가 부족하다. 무리하지 마.':'Málo výdrže. Nepřeháněj.',
'ST 없으면 스킬 못 써! 잠깐 빠져!':'Bez ST žádné dovednosti! Ustup!',
'탭 장비창을 열어봐. 아이템을 주워왔어!':'Otevři TAB. Sebrali jsme předmět!',
'좋은 거 나왔다! TAB 열어서 확인해봐!':'Něco dobrého padlo! Otevři TAB!',
'악의에 중독되면 악마가 돼서 부활력이 생긴대. 저 녀석처럼.':'Říká se, že závislost na zlosti přemění v démona se silou vzkříšení. Jako tamten.',
'혹시 너도...?':'Možná i ty...?',
'데미지가 부족하면 무기류 강화를 해야해!!':'Málo poškoz. — vylepši zbraně!!',
'G키 대장간. 강화 안 하면 여기서 계속 죽어.':'Klávesa G — kovárna. Bez vylepšení tu budeš umírat.',
'시간이 없어. 움직여.':'Není čas. Pohni se.',
'멍하게 서있으면 안 돼!':'Nestůj jako sloup!',
'...뭘 기다리는 거야?':'...Na co čekáš?',
'가자가자! 몬스터가 기다려!':'Pojďme! Příšery čekají!',
'여기 오래 있으면 위험해.':'Zůstávat tu je nebezpečné.',
'움직여야 해! 가만있으면 둘러싸여!':'Pohni se! Budeš stát — obklíčí tě!',
'쉬는 건 죽고 나서 해.':'Odpočinek po smrti.',
'살아있을 때 쉬면 안 돼!':'Žádný odpočinek dokud žiješ!',
'적이 몰려오고 있어. 빨리 움직여.':'Nepřátelé se blíží. Pohni se.',
'냄새 맡고 올 거야. 빨리!':'Ucítí tě. Rychle!',
'...아직 살아있는 거 맞지?':'...Opravdu ještě žiješ?',
'혹시 잠든 거야...?':'Snad jsi neusnul...?',
'...나무가 썩어가고 있어. 여기는 지옥의 입구야.':'...Stromy hnijí. Tady je vchod do pekla.',
'냄새 지독해... 빨리 지나가자.':'Smrad je hrozný... Pojďme rychle.',
'조심해. 벌레굴이다. 벽이랑 바닥에서 기어나와.':'Pozor. Červí doupě. Lezou ze stěn a podlahy.',
'으으... 벌레 싫어! 밟아버려!':'Fuj... Nesnáším hmyz! Pošlapej je!',
'...공기가 얼어붙는다. 여기선 화염이 먹힌다.':'...Vzduch mrzne. Tady funguje oheň.',
'추워... 빙결 조심해! 얼면 끝이야.':'Zima... Pozor na zmrazení! Zmrzneš — konec.',
'용암이다. 바닥을 밟으면 타 죽어.':'Láva. Šlápneš na zem — uhořeš.',
'뜨거워! 여기 왜 이렇게 빨개!':'Horko! Proč je tu vše červené!',
'...군단이다. 수가 많아. 광역기 없으면 밀려.':'...Legie. Hodně jich. Bez plošných útoků zaplaví.',
'우글우글... 징그러워. 한꺼번에 쓸어!':'Hemží se... Odporné. Smeť je naráz!',
'사도의 영역이야. 여기 놈들은 머리가 좋아.':'Území apoštola. Tihle jsou chytří.',
'패턴이 복잡해졌어... 집중해!':'Vzorce se zkomplikovaly... Soustřeď se!',
'...끝이다. 지옥의 심장부. 살아 돌아가는 건 포기해라.':'...Tohle je konec. Srdce pekla. Zapomeň na návrat.',
'여기가 마지막이야... 각오해.':'Tohle je finále... Připrav se.',
'석궁 자동발사 (T)':'Kuše automatická (T)',
'버스트루프 당기기 (H)':'Výbušná smyčka přitahování (H)',
'결정 자동합성':'Krystal auto-syntéza',
'결정 자동강화':'Krystal auto-posílení',
'✓ 설정 자동 저장':'✓ Nastavení uloženo automaticky',
'세팅 프리셋 저장/불러오기':'Uložit/načíst předvolbu',
'세팅1 저장':'Uložit předvolbu 1','세팅1':'Předvolba 1',
'세팅2 저장':'Uložit předvolbu 2','세팅2':'Předvolba 2',
'재진단':'Opakovaná diagnostika',
'게임 리셋 (처음부터)':'Resetovat hru (od začátku)',
'캐릭터 선택 (로비)':'Výběr postavy (Lobby)',
'닫기 [ESC]':'Zavřít [ESC]','닫기 [G]':'Zavřít [G]','닫기 [V]':'Zavřít [V]','닫기 [C]':'Zavřít [C]',
'전체화면 (F11)':'Celá obrazovka (F11)',
'정말 모든 진행을 초기화하시겠습니까?':'Opravdu chcete resetovat veškerý postup?',
'검출 중...':'Detekce...',
'마우스 커서':'Kurzor myši','그래픽 품질':'Kvalita grafiky','하드웨어 진단':'Diagnostika hardwaru',
'BGM 선택':'Výběr BGM',
'자동 (스테이지별)':'Automaticky (dle fáze)','전체 랜덤':'Vše náhodně','로비':'Lobby',
'1장 랜덤':'Kapitola 1 náhodně','2장 랜덤':'Kapitola 2 náhodně','3장 랜덤':'Kapitola 3 náhodně',
'4장 랜덤':'Kapitola 4 náhodně','5장 랜덤':'Kapitola 5 náhodně','6장 랜덤':'Kapitola 6 náhodně','7장 랜덤':'Kapitola 7 náhodně',
'보스':'Šéf','최종보스':'Závěrečný šéf',
'대장간 랜덤':'Kovárna náhodně','사망 랜덤':'Smrt náhodně','승리 랜덤':'Vítězství náhodně',
'지옥 추락 사망 징글':'Jingle smrt pád peklo','탈출 성공':'Útěk úspěšný',
'── 1장 - 썩은 숲 ──':'── CH1 - Rotten Forest ──','── 2장 - 벌레굴 ──':'── CH2 - Worm Nest ──',
'── 3장 - 얼음굴 ──':'── CH3 - Ice Cavern ──','── 4장 - 화염지대 ──':'── CH4 - Infernal Wastes ──',
'── 5장 - 지옥군단 ──':'── CH5 - Hell Legion ──','── 6장 - 사도마굴 ──':'── CH6 - Apostle Den ──',
'── 7장 - 지옥성 ──':'── CH7 - Hell Citadel ──','── 공통 ──':'── Common ──',
'⌨ 조작법':'⌨ Ovládání','클릭하면 닫힘':'Klikněte pro zavření',
'전투력':'BS','가방':'Taška','결정':'Krystal',
'↕ 정렬':'↕ Seřadit','쓰레기 전체선택':'Vybrat veškerý odpad','쓰레기 전부 분해':'Rozložit veškerý odpad',
'창고':'Sklad','스탯 포인트':'Body atributů','능력치 요약':'Přehled statistik','올 리셋':'Resetovat vše',
'대장간':'Kovárna','스킬':'Schopnosti','능력치':'Atributy',
'좌클스킬 (클릭 전환)':'Schopn. LMB (klik pro změnu)','우클스킬 (클릭 전환)':'Schopn. PMB (klik pro změnu)',
'이동스킬 (클릭 전환)':'Schopn. pohybu (klik pro změnu)','마법스킬 (클릭 전환)':'Magická schopn. (klik pro změnu)',
'영역스킬 (클릭 전환)':'Schopn. oblasti (klik pro změnu)','피보호막 (클릭 전환)':'Krevní štít (klik pro změnu)',
'CT스킬 (클릭 전환)':'CT schopn. (klik pro změnu)','[C] 능력치':'[C] Atributy',
'무기 공격':'Útok zbraní','칼등 처내기 (투사체 반사, 홀드 연사)':'Parírování (odráží střely, drž=salva)',
'연속 처내기':'Nepřetržité parírování','영역 스킬 (폭풍소환 등)':'Schopn. oblasti (Vír atd)',
'작살 발사':'Výstřel harpunou','마법 (탭=투사체, 홀드=빔)':'Magie (klik=střela, drž=paprsek)',
'데빌포스 흡수':'Absorbovat ďábelskou sílu','물약 / 스킬슬롯':'Lektvary / Sloty schopností',
'스킬슬롯 5 / 필살기 / CT스킬':'Slot 5 / Ultimátní / CT schopn.','스킬 슬롯 배정':'Přiřazení slotu',
// --- Phase 27 additions ---
'위로 이동':'Pohyb nahoru','아래로 이동':'Pohyb dolů','왼쪽 이동':'Pohyb vlevo','오른쪽 이동':'Pohyb vpravo',
'칼등 처내기 (탭=처내기, 홀드=연사)':'Parírování čepelí (klik=parírovat, drž=salva)',
'영역 스킬':'Schopnost oblasti','작살 이동':'Harpuna Dash',
'유령불꽃 켜기/끄기':'Duch Plamen Zap/Vyp','기동칼날개 자동 켜기/끄기':'Čepelní Křídlo Auto Zap/Vyp',
'해상도':'Rozlišení',
'빛이 꺼졌다':'Světlo Zhasíná','누군가는 너를 기다리고 있다':'Někdo na tebe čeká',
'다시 일어서라':'Vstaň znovu','로비로 돌아가기':'Návrat do Lobby',
'☠ 사망 리플레이':'☠ Přehrání Smrti',
'지옥의 시련을 견뎌냈다':'Přežil jsi zkoušku Pekla',
'계속 전투':'Pokračovat v boji','난이도를 선택하라':'Zvolte obtížnost',
'나중에 설정(ESC)에서 변경 가능':'Lze změnit v Nastavení (ESC) později',
'일괄합성':'Hromadná Syntéza','일괄강화+합성':'Hromadné Posílení+Syntéza',
'자원 부족!':'Zdroje Nízké!',' 뎀':' Pkž',
'합체 폭발!':'Fúzní Detonace!',
'MP 부족! (50)':'Nedostatek MP! (50)',
'부활력 고갈!':'Vzkříšení Vyčerpáno!','☠ 부활력 고갈!':'☠ Vzkříšení Vyčerpáno!',
'독안개':'Jedovatá Mlha','뇌전창':'Hromový Oštěp',
'🔥 업화선 시전...':'🔥 Pekelný Paprsek příprava...',
'💥 기동파괴 그로기!':'💥 Řetězové Ničení Groggy!',
'💥 칼등 그로기!':'💥 Parírování Čepelí Groggy!',
'⚡ 순간이동 준비!':'⚡ Teleportace Připravena!',
'👿악의+1000':'👿Zlo+1000',
'💀 내려찍기!':'💀 Sestřelení!',
'✟ 신성력 억제! +':'✟ Svatá Síla Potlačena! +',
'✟ 신성력 억제!':'✟ Svatá Síla Potlačena!',
'✟ 신성력 억제! (':'✟ Svatá Síla Potlačena! (',
'💥 지진그로기!':'💥 Zemětřesení Groggy!',
'💥 기폭그로기!':'💥 Detonace Groggy!',
'폭발! ×':'Výbuch! ×','⚫ 기둥강타!':'⚫ Úder Pilíře!',
'💥 대왕치기 그로기!':'💥 Kolosální Groggy!',
'💫 미니스턴!':'💫 Mini Stun!','⚡ 뇌전창!':'⚡ Hromový Oštěp!',
'…절반이다. 정신차려.':'…Polovina. Soustřeď se.',
'…죽기 직전이다. 한 발만 더.':'…Téměř mrtvý. Ještě jeden úder.',
'…다음 한 방이 마지막이야.':'…Další úder bude poslední.',
'기절! ':'Omráčen! ',
'마력이 빈다. 평타 섞어.':'MP se vyprazdňuje. Přimíchej normální útoky.',
'그랩이다. 거리를 둬.':'Útok chycením. Drž si odstup.',
'광역기다. 멀어져.':'Útok oblasti. Odejdi.',
'…아파? 당연하지. 여긴 지옥이야.':'…Bolí to? Samozřejmě. To je peklo.',
'F키도 스킬 슬롯이야!':'F je také slot schopností!',
'L-CTRL로 유령걸음/얼음보주!':'L-CTRL pro Duch Chůzi / Ledová Koule!',
'V 눌러서 창고에 넣어둬!':'Stiskni V pro uložení!',
'ESC로 설정! 난이도/자동물약!':'ESC pro nastavení! Obtížnost/Auto-lektvary!',
'잡몹이다. 먼저 정리해.':'Běžní nepřátelé. Vyčisti je nejdříve.',
'…얼어붙은 놈은 오래 안 간다.':'…Zmrazený nepřítel nevydrží dlouho.',
'…냄새가 짙다. 큰 놈이 있어.':'…Vůně je silná. Něco velkého je blízko.',
'쉴드는 마법으로, HP는 물리로.':'Štít bere magii, HP bere fyzické.',
'스페이스! 가시덫으로 적 묶어!':'Mezerník! Uvěznit nepřátele Ostnatou Pastí!',
'근접 너무 많아! 거리 벌려!':'Příliš mnoho v blízkosti! Rozptyl se!',
'회전참이나 광역기로 몰아!':'Použij Vírový Sek nebo Oblast!',
'F 눌러! 회복의 영역 깔아!':'Stiskni F! Polož Svatou Doménu!',
'F키 회복의 영역을 써봐.':'Vyzkoušej F-klávesu Svatou Doménu.',
'빠져! 물약 마시고 회복해.':'Ustup! Vypij lektvary a zregeneruj se.',
'쉬프트! 사슬기동은 이동기야!':'Shift! Řetězový Dash je pohybový nástroj!',
'스킬포인트 쌓였어! K 눌러!':'Body schopností připraveny! Stiskni K!',
'스킬 포인트 있어! K!':'Body schopností! K!',
'C키. 패시브 포인트가 쌓여있다.':'Klávesa C. Pasivní body se nahromadily.',
'…쓸 거 아니면 분해해.':'…Rozlož co nepoužiješ.',
'…강화 안 하면 그냥 고철이야.':'…Bez posílení je to jen šrot.',
'빨간 탄은 우클릭. 무지개는 Q.':'Červené střely: pravé tlačítko. Duha: Q.',
'빨강=우클릭, 무지개=Q.':'Červené=pravé tlačítko, duha=Q.',
'…멈추지 마. 여신은 기다리지 않는다.':'…Nezastavuj se. Bohyně nečeká.',
'패턴이 바뀐다. 거리를 둬.':'Vzor se mění. Drž si odstup.',
'미쳐가고 있어. 광폭화다.':'Zblázní se. Režim vzteku.',
'마지막이야! 끝장내!':'Poslední fáze! Dokonči to!',
'…끝났다. 다음으로.':'…Hotovo. Dál.',
'다 잡았다! 포탈 어딨어?':'Všichni chyceni! Kde je portál?',
'근육으로 만든 빌드군. 베고 부숴.':'Svalové sestavení. Sečkni a rozbij.',
'활을 쥐었군. 거리를 둬.':'Luk v ruce. Drž si odstup.',
'마법사군. MP 관리부터 배워라.':'Čaroděj. Nauč se nejdříve správu MP.',
'운에 기댄 빌드군. …드롭은 좋겠어.':'Sestavení na štěstí. …Alespoň odměny budou dobré.',
'…VIT가 너무 낮아. 한 방에 죽는다.':'…VIT je příliš nízké. Zemřeš z jednoho úderu.',
'다 찍으면 다 약해진다. 하나만 골라.':'Maximalizuj vše a budeš slabý všude. Zvol jedno.',
'…3단. 적이 강해져. 정신 차려.':'…Fáze 3. Nepřátelé silnější. Soustřeď se.',
'5단이다. …너도 강해졌단 뜻이야.':'Fáze 5. …To znamená, že jsi také zesílil.',
'…7단. 아직 살아있단 게 신기하군.':'…Fáze 7. Stále naživu. Překvapující.',
'10단. …너는 이제 인간이 아니야.':'Fáze 10. …Nejsi už člověk.',
'…일반으로 내려왔군. 가끔은 쉬어가야지.':'…Zpět na Normální. Někdy je třeba přestávka.',
'…이게 진짜 패링이야.':'…To je skutečné parírování.',
'…피가 묻기 시작했군.':'…Krev začíná téct.',
'100. 너는 인간이 아니야.':'100. Nejsi člověk.',
'…피 흘리며 베는군.':'…Seká skrze krev.',
'빨간콩이 푸르게 변했다. 그게 너의 무기야.':'Červená kulka zmodrala. To je tvá zbraň.',
'무지개를 받아쳤군. 그건 진짜 어렵다.':'Paríroval jsi duhu. To je opravdu těžké.',
'…너무 빨라. 닿기 직전에 눌러.':'…Příliš rychlé. Stiskni těsně před kontaktem.',
'악의가 가득 찼다. 풀어내.':'Zlo je plné. Uvolni ho.',
'작살이 살을 뚫었어. 끌고 와.':'Harpuna pronikla masem. Přitáhni to.',
'…풀차지군. 멀리 던져버려.':'…Plně nabitá. Hoď ji daleko.',
'…빈틈을 그대로 빠져나갔다.':'…Prokouzl přímo přes mezeru.',
'…일반 잡몹이 아니야. 모디파이어 붙었군.':'…Není to běžný nepřítel. Má modifikátor.',
'엘리트 하나 처리.':'Elita pryč.',
'…큰 놈이다. 일반 잡몹 정리부터.':'…Velký jeden. Vyčisti nejdříve běžné nepřátele.',
'미니보스 처리. 다음 길로.':'Mini-boss pryč. Na další cestu.',
'한 번에 다섯. 깔끔해.':'Pět najednou. Čisté.',
'100강. 이제 뭔가 다르게 보이는군.':'+100. Věci teď vypadají jinak.',
'…운이 없는 날이야.':'…Smolný den.',
'…전설이다. 이런 건 처음 본다.':'…Legendární. Nikdy jsem něco takového neviděl.',
'…죽었다 살아났네. 여신은 너를 포기 안 했어.':'…Zemřel a vrátil se. Bohyně tě nevzdala.',
'…또야? 패턴 좀 외워!':'…Znovu? Nauč se vzor!',
'…한 번도 안 죽고. 그건 진짜 실력이야.':'…Ani jednou nezemřel. To je skutečná dovednost.',
'…ACT1을 끝냈다. 진짜 시작은 여기서부터야.':'…ACT1 hotovo. Skutečný začátek je odtud.',
'모든 보스를 무너뜨렸다. 너는 지옥의 일부야.':'Všichni bossové padli. Jsi součástí pekla.',
'…30초. 너 진짜 미쳤구나.':'…30 sekund. Jsi opravdu šílený.',
'…빠르군. 효율적이야.':'…Rychlý. Efektivní.',
'신기록이다.':'Nový rekord.',
'탭 장비창을 열어봐.':'Otevři okno výbavy stisknutím TAB.',
'데미지 부족하면 무기 강화!':'Málo poškození? Posil svou zbraň!',
// --- Loading screen ---
'불러오는 중...':'Načítání...',
'로딩중...':'Načítání...',
'맵과 몬스터 불러오는 중...':'Načítání mapy a příšer...',
'기본 데이터 준비 중...':'Příprava základních dat...',
'저장 데이터 불러오는 중...':'Načítání uložených dat...',
'몬스터 스킨 로딩...':'Načítání skinů příšer...',
'맵과 몬스터 생성 중...':'Generování mapy a příšer...',
'맵 에셋 로딩...':'Načítání zdrojů mapy...',
'맵 환경 준비 중...':'Příprava prostředí mapy...',
'주변 청크 준비 중...':'Příprava okolních chunků...',
'맵 캐시 생성 중...':'Tvorba mezipaměti mapy...',
'미니맵 빌드 중...':'Tvorba minimapy...',
// Phase 28
' 으로 탈출!':' k útěku!',
'100명?! 미쳤어!':'100 zabití?! To je šílenství!',
'10단 최고난이도! 너 진짜 광기야!':'Obtížnost 10 max! Naprostý šílenec!',
'1분 안에 클리어! 빠르네!':'Průchod za 1 minutu! To je rychlé!',
'30초!! 스피드런 가능해!':'30 sekund!! Potenciál speedrunu!',
'3단! 보상도 좋아지지만 죽기 쉬워!':'Obtížnost 3! Lepší odměny, ale snáze umřeš!',
'50명! 학살자야!':'50 zabitých! Masakr!',
'5단!! 진짜 게이머 인증!':'Obtížnost 5!! Certifikovaný hráč!',
'7단!! 다른 사람들 이 정도 못 와!':'Obtížnost 7!! Ostatní sem nedojdou!',
'ACT1 완주! 우리가 진짜 해냈어!':'ACT1 dokončen! Opravdu se nám to povedlo!',
'Ctrl 얼음보주로 탈출하라.':'Ctrl — uteč s Ice Orb.',
'Ctrl 유령걸음으로 탈출하라.':'Ctrl — uteč s Ghost Walk.',
'C키! 패시브 강해져!':'Klávesa C! Pasivní schopnosti silnější!',
'DEX 빌드! 거리에서 패고, 추적탄 좋아!':'Build DEX! Útoky na dálku, sledovací střely!',
'E로 마력공격을 해봐!':'Zkus magický útok s E!',
'G 눌러서 대장간 가봐!':'Stiskni G — kovárna!',
'G키 대장간. 강화 안 하면 계속 죽어.':'G — kovárna. Bez vylepšení pořád umíráš.',
'HP 70%! 조심해!':'HP 70%! Opatrně!',
'INT 빌드! 빔이랑 폭발 마법! MP 잘 봐!':'Build INT! Paprsky a výbušná magie! Hlídej MP!',
'LCK 높아! 레어 드롭률 미친 거 알지?':'Vysoké LCK! Šance na vzácný drop je šílená!',
'L로 어디에 뭘 넣을지 골라!':'Stiskni L — vyber rozmístění slotů dovedností!',
'MP 부족! 평타로 패면서 회복해!':'Nízké MP! Útočením si ho doplň!',
'ST 없으면 스킬 못 써!':'Bez ST žádné schopnosti!',
'STR 빌드! 회전참, 회오리, 광역기 추천!':'Build STR! Rotační seknutí, vír, AoE!',
'VIT 좀 찍어! HP 너무 적어!':'Přidej VIT! HP je příliš nízké!',
'Z 누르면 대박! 쿨타임 길어!':'Stiskni Z pro ultimate! Dlouhý cooldown!',
'…고기 냄새. 싫진 않네.':'…Cítím krev. Není to tak špatné.',
'…둘러싸이면 끝이야.':'…Obklíčení znamená konec.',
'…말은 못해.':'…Mluvit neumím.',
'…버리기 아까운 건 창고에.':'…Cennosti ulož do skladu.',
'…빈틈을 노려.':'…Hledej mezery.',
'…설정을 확인해.':'…Zkontroluj nastavení.',
'…슬롯을 채워. 빈 손은 죽음이다.':'…Vyplň sloty. Prázdné ruce jsou smrt.',
'…아직 살아있네. 좌클릭으로 저것들 쳐봐.':'…Stále žiješ. Levým kliknutím je udař.',
'…운이 좋았을 뿐이야. 아마.':'…Jen štěstí. Asi.',
'…치는 건 할 줄 아네. 피하는 건?':'…Bít umíš. A vyhýbat se?',
'…힘을 골라라. 전부 가질 순 없다.':'…Vyber si sílu. Nemůžeš mít vše.',
'골고루 안 돼! 하나로 밀어!':'Nerozkládej to! Tlač jeden stat!',
'그로기 터지면 1.5배!':'Groggy = 1.5x poškození!',
'길이 열렸다.':'Cesta je otevřena.',
'나머진 전부 우클릭 패링 가능!':'Zbytek — pravý klik parry!',
'나머진 전부 우클릭!':'Zbytek — pravý klik!',
'다섯 번 연속! 내가 본 인간 중 최고!':'Pětkrát v řadě! Nejlepší, co jsem viděl!',
'다음엔 죽지 마!':'Příště neumírej!',
'더블탭 전격이동으로 탈출하라.':'Dvojité klepnutí pro dash k útěku.',
'소환수 왔어! 먼저 처리해야 해!':'Přivolaní nepřátelé! Nejdřív je eliminuj!',
'스킬 없으면 방향키 연타뿐이야.':'Bez schopností? Jen mačkej šipky.',
'신기록!! 스트리머한테 보내!':'Nový rekord!! Pošli streamerovi!',
'아이템 넘쳐! 우리가 주워줄게!':'Taška plná! My posbíráme!',
'안 죽고 깼어! 진짜 천재 맞네!':'Průchod bez smrti! Opravdový génius!',
'앞으로 가자~':'Pojďme vpřed~',
'우리가 해냈어! 다음 챕터 가자!':'Povedlo se! Další kapitola!',
'일반 모드! 편하게 즐기자!':'Normální režim! Užívej si!',
'자원이 반이다. F키로 회복해.':'Zdroje napůl. Stiskni F k obnově.',
'잡힌다! 옆으로 빠져!':'Chytají tě! Uhni do strany!',
'장비 분해해! 쓰레기도 악의!':'Rozlož vybavení! I odpad dává malice!',
'전부 다 잡았어! 우리가 지옥의 왕이야!':'Vše vyčištěno! Jsme králové pekla!',
'좋은 거 나왔다! TAB!':'Dobrý loot! TAB!',
'죽기 직전에 죽이다니! 멋져!':'Zabít těsně před smrtí! Skvělé!',
'체력 반 남았어! 물약 마실 타이밍!':'HP napůl! Čas na lektvar!',
'큰 거 온다! 도망쳐!':'Velký útok přichází! Uteč!',
'패링으로 돌려주고, Q 보호막도 써!':'Parry a odraz, použij i štít Q!',
'패턴이 빨라졌어!':'Vzory jsou rychlejší!',
'한 대만 맞아도 죽어! 패링이든 회피든!!':'Jeden zásah = smrt! Parry nebo uhni!!',
'한 방이면 죽어! 도망쳐!!':'Jeden výstřel zabíjí! Uteč!!',
'화염엔 빙결! 암전엔 암흑!':'Oheň → mráz! Prázdnota → tma!',
'과부하!':'Přetížení!',
'키 설정 초기화 완료':'Nastavení kláves obnoveno',
'맞아서 사망':'Zabit zásahem',
'죽음 그 자체':'Samotná Smrt',
'강화':'Posílit',
'분해할 결정이 없습니다':'Žádné krystaly k rozložení',
'신성폭발':'Posvátný Výbuch',
'🛡️💎 무지개→블루콩!':'🛡️💎 Duha→Modrý Hrách!',
'없음 — 제작하세요!':'Žádný — Vyrobte!',
'처치':'Zabití',
'구역':'Zóna',
'빙결':'Zmražení',
'⚡ 사슬기동:화염!':'⚡ Řetězový Pohon: Plamen!',
'ST':'ST',
'타':'Zásah',
'💥 밀어내기 모드':'💥 Režim Odmrštění',
'🕊️흡수':'🕊️Absorpce',
'💥반사 폭발!':'💥Odrazová Exploze!',
'⚡ 참회!':'⚡ Pokání!',
'암전!':'Blesk!',
'암흑!':'Tma!',
'암흑창!':'Temné Kopí!',
'빛창!':'Světelné Kopí!',
'개 설치!':'nasazeno!',
'💥 그로기!':'💥 Omráčení!',
'보상':'Bonus',
'🌋 지진폭풍!':'🌋 Seismická Bouře!',
'F슬롯':'F Slot',
'⚔ 칼날 해방!':'⚔ Osvobození Čepele!',
'🔨 대왕치기!':'🔨 Gigantický Úder!',
'전지전능의 왕관':'Koruna Všemohoucnosti',
'생명의 팔찌':'Náramek Života',
'유령불꽃 OFF':'Duch Plamen VYP',
'피웅덩이!':'Krvavá Louže!',
'보물상자 개봉!':'Truhla Otevřena!',
'저주 ':'Kletba ',
'아이템 선택 필요':'Vyberte předmět',
'슬롯':'Slot',
'필살기':'Ultimátní',
'연사 해제':'Rychlopalba VYP',
'선택됨':'Vybráno',
'🔱 작살!':'🔱 Harpuna!',
' 해제':' Sundáno',
'F 슬롯 해제':'F Slot Zrušen',
'⚡ 마력연사!':'⚡ Mystická Palba!',
'🔥 화염관통!':'🔥 Ohnivý Průraz!',
'⚔ 칼날!':'⚔ Čepel!',
'💥 착지!':'💥 Přistání!',
'⚡ 체간삭감!':'⚡ Rozbití Rovnováhy!',
'🔥 기동불꽃! ':'🔥 Řetězový Plamen! ',
'⚡ 기동전폭! x':'⚡ Řetězový Výbuch! x',
'🔨 기동파괴 준비!':'🔨 Řetězové Drcení Připraveno!',
'⚡ 기동전폭 준비!':'⚡ Řetězový Výbuch Připraven!',
'💫 자동 버스트!':'💫 Automatický Výbuch!',
'💥폭발!':'💥Exploze!',
'💎 블루콩!':'💎 Modrý Hrách!',
'💎 푸른비 ON!':'💎 Azurový Déšť ZAP!',
'🔥 업화선!':'🔥 Paprsek Pekelného Ohně!',
'⚡ 전류 방출!':'⚡ Výboj Proudu!',
'💫 광역!':'💫 Plošný!',
'💫 피니셔!':'💫 Doražení!',
'☠ 완전 사망!':'☠ Trvalá Smrt!',
'💥 지뢰!':'💥 Mina!',
'⚠ 함정!':'⚠ Past!',
'❌ Q키로! -':'❌ Použijte Q! -',
'🛡️💎 블루콩!':'🛡️💎 Modrý Hrách!',
'✨💎 블루콩!':'✨💎 Modrý Hrách!',
'💜다크볼!':'💜Temná Koule!',
'🌨빙결!':'🌨Zmražení!',
'🕸둔화!':'🕸Zpomalení!',
'⚠트랩!':'⚠Past!',
'💥 역병 Finale!':'💥 Finále Moru!',
'자동회수 HP+':'Auto HP+',
'MP 부족 — 푸른비 OFF':'MP nízko — Azurový Déšť VYP',
'⚡🦴 참회 귀환!':'⚡🦴 Návrat Pokání!',
'⚡악의폭풍!':'⚡Bouře Zloby!',
'⚡ 암전폭발!':'⚡ Blesková Exploze!',
'❄ 탈출!':'❄ Únik!',
'❄🌪️ 얼음보주!':'❄🌪️ Ledová Koule!',
'❄ 빙결흡인!':'❄ Mrazivý Vír!',
'☄️ 흡인!':'☄️ Vír!',
'☄️ 대폭발!':'☄️ Megaexploze!',
'☄️💥 대폭발!':'☄️💥 Megaexploze!',
'반사!':'Odraz!',
'🔴 추적 장판!':'🔴 Sledovací Zóna!',
'⚔ 환영검!':'⚔ Fantomový Meč!',
'🌧🌧 화염 폭격!':'🌧🌧 Ohnivá Palba!',
'💀 내 곁으로!':'💀 Pojď ke Mně!',
'💀💀 전멸 폭발!':'💀💀 Zničující Exploze!',
'🌊충격파!':'🌊Rázová Vlna!',
'💥패링폭발!':'💥Výbuch Odrazu!',
'벽 충돌! ':'Kolize se Zdí! ',
'💀빙마!':'💀Ledový Démon!',
'처치율 ':'Míra Zabití ',
'부활 실패 (':'Oživení Selhalo (',
'👻 동반부활!':'👻 Spolu-Oživení!',
'🚪 보스방 개방!':'🚪 Místnost Bosse Otevřena!',
'🌀균열 발생!':'🌀Trhlina Otevřena!',
'빙판!':'Ledová Podlaha!',
'🛡 보호막 ':'🛡 Štít ',
'🌀 회전보호막 ':'🌀 Rotující Štít ',
'⚡쉴드 파괴!':'⚡Zničení Štítu!',
'💀 1회부활!':'💀 Oživení 1 Život!',
'악마화 부활!':'Démonické Oživení!',
'칼날 없음!':'Žádná Čepel!',
'❄🌪️ 얼음소용돌이!':'❄🌪️ Ledový Vír!',
'💥 폭산탄!':'💥 Výbušný Výstřel!',
'⚡ 전격이동!':'⚡ Bleskový Krok!',
'💥 폭발 허수아비!':'💥 Výbušná Návnada!',
'⚡날개치기!':'⚡Úder Křídlem!',
'🏛️ 악의기둥!':'🏛️ Temný Pilíř!',
'🌋 지옥강타!':'🌋 Pekelný Úder!',
'💫 포이즈 파괴!':'💫 Zničení Rovnováhy!',
'✟ 구속의 영역!':'✟ Oblast Pouta!',
'⛧ 블랙!':'⛧ Černá Hvězda!',
'필살기 배정!':'Ultimátní Přiřazena!',
'합체 Lv.':'Úroveň Fúze.',
'▲ 창고 → 가방 꺼내기':'▲ Sklad → Taška',
'⟨ 대기 ⟩':'⟨ Čekat ⟩',
'불러오기 실패':'Načtení Selhalo',
'장착':'Vybaveno',
'강화 실패!':'Posílení Selhalo!',
'예상 필요 악의':'Odh. potřebná Zlovolnost',
'희귀 이하':'Vzácné nebo nižší',
'지금이야! 몰아쳐!!':'Teď! Útočte!!',
'── 2장 - 벌레굴 ──':'── CH2 - Worm Nest ──',
'── 4장 - 화염지대 ──':'── CH4 - Infernal Wastes ──',
'── 6장 - 사도마굴 ──':'── CH6 - Apostle Den ──',
'── 공통 ──':'── Common ──',
'난이도를 선택하라':'Vyberte obtížnost',
'☠ 부활력 고갈!':'☠ Oživení Vyčerpáno!',
'⏳⚡ 시간걸음!':'⏳⚡ Časový Krok!',
'블룸 효과':'Bloom efekt',
'잔상 트레일':'Stopa doznívání',
'슬래시 이펙트':'Efekt seku',
'후처리 효과':'Post-processing',
'사망 이펙트':'Efekt smrti',
'동적 조명':'Dynamické osvětlení',
'횃불 조명 (어둠)':'Světlo pochodně (tma)',
'앰비언트 파티클':'Ambientní částice',
'안개 효과':'Efekt mlhy',
'필름 그레인':'Filmové zrno',
'캐릭터 외곽선':'Obrys postavy',
'리롤':'Znovu hodit',
'물약':'Lektvar',
'으로 탈출!':'k úniku!',
'Shift 작살':'Shift Harpuna',
'더블탭 전격이동':'Dvojité klepnutí — Bleskový skok',
'Ctrl 유령걸음':'Ctrl Krok přízraku',
'Ctrl 얼음보주':'Ctrl Ledová koule',
'🔴화염→빙결 2배 | 🔵빙결→화염 2배 | ⚪물리=중립 | 악마 처치 시 악의 영혼 드롭':'🔴Oheň→Led 2× | 🔵Led→Oheň 2× | ⚪Fyz=Neutrální | Zabíjej démony pro duše zloby',
  '미구현':'N/A',
  '스탯 총량':'Celkem statistiky',
  '장비':'vybavení',
  '공속':'rych.útoku',
  '크리':'krit',
  '크리뎀':'krit.poš.',
  '근성':'Vytrvalost',
  '종합 지표':'Přehled',
  '근접 DPS':'DPS zblízka',
  '공격력×공속×크리':'ATK×Rych×Krit',
  '활 DPS':'DPS luku',
  '마법 DPS':'DPS magie',
  '유효 HP (EHP)':'Efekt. HP (EHP)',
  '쉴드':'Štít',
  '장비 파워':'Síla vybavení',
  '근접 공격력':'ATK zblízka',
  '기본':'základ',
  '무기':'zbraň',
  '패시브':'pasivní',
  '활 공격력':'ATK luku',
  '정밀':'Prec',
  '마법 공격력':'ATK magie',
  '왕관':'koruna',
  '마력':'Arkána',
  '공격속도':'Rychlost útoku',
  '크리티컬':'Kritický',
  '데미지':'poškoz.',
  '확률':'Rychlost',
  '어픽스':'affix',
  '레거시':'odkaz',
  '추가뎀':'dod. poškoz.',
  '패링 카운터뎀':'Poškoz. protiútoku',
  '우클공속':'Rychlost PPM',
  '무지개탄DR':'DR duha',
  '포이즈파괴':'Proraz. Poise',
  '방어관통':'Průnik brnění',
  '관통력':'Proražení',
  '속성':'Živly',
  '무기속성':'Elem. zbraně',
  '독':'Jed',
  '초':'s',
  '암흑저주':'Temná kletba',
  '원소집중':'Elem. fokus',
  '원소전환':'Konv. elem.',
  '방어':'Obrana',
  '물리방어':'Fyzická OBR',
  '감소':'snížení',
  '캡':'limit',
  '장갑':'rukavice',
  '바지':'kalhoty',
  '속성방어':'Elem. OBR',
  '목걸이':'náhrdelník',
  '반지1':'prsten1',
  '반지2':'prsten2',
  '반사':'Odraz',
  '가시':'Trny',
  '배리어':'Bariéra',
  '보호막 흡수':'Absorpce štítu',
  '속성 저항':'Elem. odpor',
  'CC저항':'Odpor CC',
  '생존':'Přežití',
  '장비HP':'Vybavení HP',
  '임플':'Impl.',
  '에너지쉴드':'Energetický štít',
  '리젠':'Regen',
  '스태미나':'Výdrž',
  '성장':'Růst',
  'MP%어픽스':'Affix MP%',
  '이동속도':'Rychlost pohybu',
  '한방캡':'Limit jednoho úderu',
  '최대HP의33%':'33% max HP',
  '비용/효율':'Cena/Efekt',
  '근접ST':'ST zblízka',
  '활ST':'ST luku',
  '마법MP':'MP magie',
  '작살사거리':'Dosah harpuny',
  '기동게이지':'Drive ukazatel',
  '쿨감':'CDR',
  '쇠뇌뎀':'Poškoz. kuše',
  '쇠뇌공속':'Rychlost kuše',
  '기타':'Ostatní',
  '물약쿨':'CD lektvaru',
  '회복+':'Regenerace+',
  '드롭':'Drop',
  '경험치+':'EXP+',
  '골드+':'Zlato+',
  '기동:칼날개':'Drive:Čepel',
  '기동:전폭':'Drive:Úder',
  '기동:기습':'Drive:Záloha',
  '충전스킬':'Nabíjení dovednost',
  '사슬게이지':'Ukazatel řetězu',
  '특수 효과':'Speciální efekty',
  '처치뎀+':'Poškoz. zabití+',
  '위기뎀+':'Poškoz. krize+',
  '피격반격':'Kontra na zásah',
  '풍요(적HP≥70%뎀+)':'Hojnost(HP≥70%+)',
  '약자포식(적HP≤30%뎀+)':'Predátor(HP≤30%+)',
  '패링폭발':'Exploze odrazu',
  '체간파괴+':'Proraz. Poise+',
  '콤보뎀+':'Poškoz. komba+',
  '작살뎀+':'Poškoz. harpuny+',
  '스킬뎀+':'Poškoz. dovednosti+',
  '패리+':'Odraz+',
  '체인':'Řetěz',
  '정화':'Čištění',
  '회':'×',
  '불굴':'Vytrvalost',
  '신성력':'Svatá síla',
  '악마력(부활력)':'Síla démona',
  '자연':'Příroda',
  '악마성':'Démoničnost',
  '인간성':'Lidskost',
  '전투 통계':'Bojové statistiky',
  '핵터':'Hecter',
'디로이':'Deroy',
'물리 ATK +1, MAX HP +5, HP리젠 +0.002':'Phys ATK +1, MAX HP +5, HP regen +0.002',
'석궁 ATK +1, 공격속도 +0.05%, MAX ST +2, ST리젠 +0.005, 회피 +0.05%':'Bow ATK +1, ATK speed +0.05%, MAX ST +2, ST regen +0.005, Dodge +0.05%',
'마법 ATK +1, MAX MP +2, MP리젠 +0.005, MAX 쉴드 +5':'Magic ATK +1, MAX MP +2, MP regen +0.005, MAX Shield +5',
'크리확률 +0.025%, 크리뎀 +0.2%, 드롭률 +0.15%':'Crit rate +0.025%, Crit DMG +0.2%, Drop rate +0.15%',
'근접뎀 +15%, ST비용 -4%/lv (최대-40%)':'Melee DMG +15%, ST cost -4%/lv (max -40%)',
'작살 사거리 +2%/lv, 기동게이지 회복 +3%/lv':'Harpoon range +2%/lv, Mobility gauge recovery +3%/lv',
'카운터뎀 +50%/lv, 우클릭 공속 +10%/lv, 무지개탄 피해감소 +10%/lv (최대50%)':'Counter DMG +50%/lv, RMB ATK speed +10%/lv, Rainbow shot DMG reduction +10%/lv (max 50%)',
'마법뎀 +15%, MP비용 -4%, 시전속도 +8%/lv':'Magic DMG +15%, MP cost -4%, Cast speed +8%/lv',
'투사체뎀 +15%, 공속 +10%, 사거리 +8%, ST비용 -4%/lv':'Projectile DMG +15%, ATK speed +10%, Range +8%, ST cost -4%/lv',
'보호막 흡수 +2%/lv (기본70→최대90%), 보호막 중 HP리젠 +0.1%/lv':'Shield absorb +2%/lv (base 70 to max 90%), HP regen during shield +0.1%/lv',
'HP/ST리젠 +3%/lv, 물약쿨 -3%/lv':'HP/ST regen +3%/lv, Potion cooldown -3%/lv',
'크리률 +2%, 크리뎀 +8%/lv':'Crit rate +2%, Crit DMG +8%/lv',
'아이템 드롭률 +8%/lv':'Item drop rate +8%/lv',
'투사체 관통률 +5%/lv, 관통횟수 +1/lv, 관통뎀감소 완화':'Projectile pierce rate +5%/lv, Pierce count +1/lv, Pierce DMG falloff reduced',
'MP리젠 +3%/lv, 쉴드리젠 +3%/lv, 쉴드쿨 -3%/lv':'MP regen +3%/lv, Shield regen +3%/lv, Shield cooldown -3%/lv',
'자동쇠뇌 뎀 +5%/lv, 공속 +5%/lv':'Auto crossbow DMG +5%/lv, ATK speed +5%/lv',
'물리뎀 +15%/lv, HP +3%/lv, ST소모 -5%/lv':'Phys DMG +15%/lv, HP +3%/lv, ST cost -5%/lv',
'적에게 약점노출 디버프. 직접 공격 시 스택+1, 스택당 피격뎀 +3%. 최대 Lv×5 중첩 (1렙5, 10렙50). 초당 20% 감소, 5초 미피격 시 리셋. DOT/장판 제외':'Weakness debuff on enemies. +1 stack per direct hit, +3% DMG/stack. Max Lv×5 (Lv1=5, Lv10=50). -20%/s decay, reset after 5s. DOT excluded',
'물리→쉴드 패널티 관통 +5%/lv (기본10%, 10lv=60%)':'Phys to Shield penalty pierce +5%/lv (base 10%, lv10=60%)',
'마법→HP 패널티 관통 +5%/lv (기본10%, 10lv=60%)':'Magic to HP penalty pierce +5%/lv (base 10%, lv10=60%)',
'적 HP 70%↑: 뎀+20%/lv, 회복력+5%/lv (합연산)':'Enemy HP≥70%: DMG+20%/lv, Recovery+5%/lv (additive)',
'적HP 30%↓: 뎀+20%/lv. 내HP 30%↓: 회복력+10%/lv, 이속+5%/lv (합연산)':'Enemy HP≤30%: DMG+20%/lv. My HP≤30%: Recovery+10%/lv, Move SPD+5%/lv (additive)',
'DOT 틱뎀 +15%/lv, DOT 지속시간 +10%/lv, DOT 축적률 +5%/lv':'DOT tick DMG +15%/lv, DOT duration +10%/lv, DOT pool rate +5%/lv',
'MP +50/lv, MP회복 +1%/lv':'MP +50/lv, MP regen +1%/lv',
'ST +50/lv, ST회복 +1%/lv':'ST +50/lv, ST regen +1%/lv',
'악의 드롭 +8%/lv':'Malice drop +8%/lv',
'HP +300/lv':'HP +300/lv',
'DEF +20/lv':'DEF +20/lv',
'엘리트/보스 추가뎀 +10%/lv':'Elite/Boss bonus DMG +10%/lv',
'부활력 -10/lv, 전체 데미지 +5%/lv, HP/MP/ST +100/lv':'Revive power -10/lv, All DMG +5%/lv, HP/MP/ST +100/lv',
'부활확률 +2%/lv, 부활HP +5%/lv, 부활쿨 -30초/lv':'Revive chance +2%/lv, Revive HP +5%/lv, Revive CD -30s/lv',
// --- Phase 37: skill desc ---
'핵심 광역기 — 먼저 배워서 정리력 확보':'Core AoE — learn first for mob clearing',
'악의 사냥 + 보호자 → 합체: 칼날 해방':'Malice Hunt + Guardian → Fuse: Blade Liberation',
'폭독혈 추가 → 합체: 독혈 해방 (칼날+독)':'Plague Burst → Fuse: Plague Liberation (blade+poison)',
'충돌+화염 → 합체: 사슬기동 (무적이동 핵심)':'Impact+Flame → Fuse: Chain Breach (invincible dash core)',
'사슬 체인 확장 → 기동:파쇄/기동:전폭':'Chain expansion → Slam/Thunder combos',
'필살기 1개 선택! 신성폭발(넉백) / 블랙(흡인) / 용암(화상) / 처형(보스킬)':'Pick 1 ultimate! Holy Blast(knockback) / Black Star(pull) / Lava(burn) / Execution(boss kill)',
'멸살광선+만화방창+원소추적탄+전격이동 → 합체: 추적빔':'Omni Beam+Barrage+Elem Missile+Blink → Fuse: Tracking Beam',
'회전참+기폭+대왕치기 → 합체: 지진폭풍':'Whirlwind+Detonate+Giant Slam → Fuse: Slam Storm',
'칼등치기 + 칼등날개 → 합체: 처내기 강화':'Blade Parry + Shield Wing → Fuse: Parry Enhanced',
'해골무덤 + 악의폭풍 → 합체: 해골번개':'Bone Wall + Malice Storm → Fuse: Bone Lightning',
'폭풍소환 + 얼음보주 → 합체: 얼음폭풍':'Malice Mortar + Ice Orb → Fuse: Ice Mortar',
'유령화 이동 + 전기 폭발':'Ghost phase movement + electric burst',
'회복 + 구속 → 합체: 결계의 영역':'Recovery + Prison → Fuse: Ward Domain',
'지진폭풍+추적암전 → 6단합체: 폭풍빔':'Slam Storm → 6-Fuse: Storm Beam',
'아이스스톰 추가 → 합체: 신성빙결':'Ice Storm → Fuse: Holy Ice',
'암흑기둥 + 가시덫 → 합체: 기둥가시. 대왕치기2는 기둥강타/지옥강타용':'Dark Pillar + Spike Trap → Fuse: Pillar Spike. Giant Slam 2 for Pillar Slam/Inferno Slam',
'기동칼날개 추가 → 5단합체: 기동:칼날개':'Chain Bladewing → 5-Fuse: Maneuver:Bladewing',
'STR 스케일. 3회 충전 + Lv3마다 사거리 1단계↑(최대4단). 이동 중 무적, 통과 적에 데미지+그로기 (쿨 5초)':'STR scale. 3 stocks + range tier up every Lv3 (max 4). Invincible while moving, DMG+groggy on pass-through (CD 5s)',
'INT 스케일. 이동 경로에 화염길 생성(3초 DOT). 통과 적 화상. MP 소모. 합체 시 착지 폭발':'INT scale. Fire trail on dash path (3s DOT). Burns passed enemies. MP cost. Fuse: landing explosion',
'5초간 유령화 — 무적+이동. 통과한 적/탄막 수만큼 종료 시 암전 폭발(+10%/회) + 전기줄기 방사(3회 체인). 카운트 캡=Lv×5(최대50). 쿨 20초. Lv당 뎀+15% 범위+10':'5s ghost form — invincible+move. Blackout explosion on end (+10%/enemy passed) + lightning arc (3 chains). Count cap=Lv×5 (max 50). CD 20s. Per Lv DMG+15% range+10',
'[이동기] 방향키 더블탭으로 발동. 경직/기절 중에도 탈출 가능. 500유닛 순간이동, 무적(15프레임). MP(10+Lv×5). 1렙10충전, 렙당+1. 쿨 8초→Lv당-0.5초(최소3초). 착지 시 전류장판(10초+Lv×0.5초): INT 틱뎀 + 방어력↓(1렙10%, 렙당+5%, 캡50%)':'[Mobility] Double-tap to activate. Escapes stagger/stun. 500-unit blink, invincible 15f. MP(10+Lv×5). Lv1=10 stocks, +1/Lv. CD 8s→-0.5s/Lv (min 3s). Landing shock field(10s+Lv×0.5s): INT tick DMG + DEF↓(Lv1=10%, +5%/Lv, cap 50%)',
'좌클 스킬: 기본공격에 3단 콤보 초승달 검기 추가. ST 10+Lv당2. Lv당 뎀+10% 거리+15px':'LMB skill: adds 3-hit crescent ki blade combo to basic attack. ST 10+2/Lv. Per Lv DMG+10% range+15px',
'[기본: E] 어둠 마법 오브 발사. 범위폭발. 넉백 0.5%. Lv당 크기+50% (뎀은 _skMul 계수 적용)':'[Default: E] Dark magic orb fired. AoE explosion. Knockback 0.5%. Per Lv size+50% (DMG uses _skMul)',
'무기 홀드 → 전진 회전 공격. 360도 광역, ST 지속소모. Lv당 범위+5 뎀+5%':'Hold weapon → forward spin attack. 360° AoE, continuous ST drain. Per Lv range+5 DMG+5%',
'패링 3초 홀드 → 흡수 데미지 광역 폭발. Lv당 범위+15 (1렙150, 10렙285)':'Parry 3s hold → absorbed DMG AoE explosion. Per Lv range+15 (Lv1: 150, Lv10: 285)',
'우클 처내기 강화. Lv당 반사 데미지 +10%. 홀드 시 연사':'RMB swipe enhanced. Per Lv reflect DMG +10%. Hold for rapid fire',
'[고정: T 자동] 물리 바늘 3방향 3발 발사. 관통 없음':'[Fixed: T auto] 3 physical needles 3-way spread. No pierce',
'[고정: E] 1발 직선 레이저. +만화방창 → 만화광선(3발 꽈배기). +원소추적탄 → 추적암전(6발 유도)':'[Fixed: E] 1 straight laser. +Barrage → Omni Beam (3 spiral). +Elem Seeker → Homing Dark (6 homing)',
'E탭 마법을 6원소 유도 미사일로 변경. 곡선 궤적으로 적을 추적. 레벨당 사거리+20 (뎀은 _skMul 계수 적용)':'Changes E-tap magic to 6-element homing missiles. Curved trajectory tracking enemies. Per Lv range+20 (DMG uses _skMul)',
'3초마다 악의 구체 생성(1렙 2개). 몸에 밀착하여 적 투사체를 자동 방어(파괴). 레벨당 구체+1':'Spawns malice orbs every 3s (Lv1: 2 orbs). Orbits body, auto-blocks (destroys) enemy projectiles. Per Lv orb+1',
'유도 물리 칼날 1발 (악의30+ST50). 관통률 800+Lv×20+장비. 지속뎀 5초. 쿨 15초':'1 homing physical blade (malice 30 + ST 50). Pierce 800+Lv×20+gear. DOT 5s. CD 15s',
'어둠 소용돌이 소환 (마우스 조준 설치, MP 소모, 쿨 11초, INT 스케일링, 1렙 200범위 +30/렙, 5초 지속, 적 흡인)':'Summon dark vortex (mouse-aim placement, MP cost, CD 11s, INT scale, Lv1 range 200 +30/Lv, 5s duration, pulls enemies)',
'포격식 조준 → 원형 해골무덤 소환. 2스택 (15초/1충전, Lv10→3스택). 둘레에서 뼈가 솟아 공간을 감쌈. 솟을 때 데미지. 적/투사체 차단. 악의 12. Lv당 범위+5% 지속+0.3초':'Artillery-aim → circular bone tomb. 2 stocks (15s/charge, Lv10→3 stocks). Bones rise around perimeter. DMG on rise. Blocks enemies/projectiles. Malice 12. Per Lv range+5% duration+0.3s',
'오망성 시전 → 신성 빛기둥 대폭발. 범위 1500+Lv×100px. 범위 끝까지 넉백(주 성능). 거리감쇠 50%. 스턴 2초. Lv당 뎀+10%. (MP 30%, 쿨 120초)':'Pentagram cast → holy light pillar mega-explosion. Range 1500+Lv×100px. Full-range knockback (main feature). 50% distance falloff. Stun 2s. Per Lv DMG+10%. (MP 30%, CD 120s)',
'검은 오망성 소환. 7초(+Lv당0.5초) 강력 흡인 (데미지 없음, 순수 유틸). 범위 1500+Lv×100px. 흡인력 기본5+Lv당0.5. (MP 30%, 쿨 120초)':'Summon black pentagram. 7s (+0.5s/Lv) strong pull (no DMG, pure utility). Range 1500+Lv×100px. Pull force base 5+0.5/Lv. (MP 30%, CD 120s)',
'빨간 오망성 시전 → 범위 1500+Lv×100px 화염폭발+10초간 화상. 틱당 적 최대HP 1.75%(+Lv당+1.5%). 10초 20틱. 거리감쇠 30%. Lv당 초기뎀+10%. (MP 30%, 쿨 120초)':'Red pentagram cast → range 1500+Lv×100px fire explosion+10s burn. Per tick enemy maxHP 1.75%(+1.5%/Lv). 10s 20 ticks. 30% distance falloff. Per Lv initial DMG+10%. (MP 30%, CD 120s)',
'X키: 그로기 보스 전용. 보스 현재HP 20%(+2%/Lv) + 무기뎀×30(+21%/Lv, 20Lv=150배) + 보스HP 30% 순수뎀. 섬광 돌진 연출. HP/MP/ST 10% 소모. 쿨 5초':'X key: Groggy boss only. Boss current HP 20%(+2%/Lv) + weapon DMG×30(+21%/Lv, Lv20=150×) + boss HP 30% pure DMG. Flash dash. HP/MP/ST 10% cost. CD 5s',
'얼음 속에 들어가 무적 상태. 다시 누르면 파쇄 → 얼음칼날 48발 부채꼴 방사 (MP 40, 쿨 20초). Lv당 칼날+2 뎀+15%':'Enter ice — invincible. Re-press to shatter → 48 ice blades fan spread (MP 40, CD 20s). Per Lv blades+2 DMG+15%',
'[고정: T 자동] 초고속 바늘 연발. 1렙 2발, 5렙마다 +1발. 관통 없음. ST 8. 쿨 1.5초. Lv당 뎀+100%':'[Fixed: T auto] Ultra-fast needles burst. Lv1 2 shots, +1 per 5 levels. No pierce. ST 8. CD 1.5s',
'E홀드: 직선 관통 레이저 채널링. MP 8+Lv/초 지속소모. 폭160+(Lv×10)px, 사거리1200+Lv×80. 관통+감전. Lv당 뎀+21%':'E hold: Straight piercing laser channeling. MP 8+Lv/s drain. Width 160+(Lv×10)px, range 1200+Lv×80. Pierce+shock. Per Lv DMG+21%',
'E탭: 화염 유도빔 발사. MP10. 쿨1초(DEX 스케일). 100% 관통+유도+화상. Lv당 사거리+50 뎀+12%':'E tap: fire homing beam. MP 10. CD 1s (DEX scale). 100% pierce+homing+burn. Per Lv range+50 DMG+12%',
'E: 10초간 대지 진동. 범위 내 용암 기둥이 순차적으로 솟아올라 화상+틱 데미지. MP 100. 쿨 12초. Lv당 범위+10% 뎀+12%':'E: 10s ground tremor. Lava pillars rise sequentially in range — burn+tick DMG. MP 100. CD 12s. Per Lv range+10% DMG+12%',
'독혈 칼날 1발 발사: 관통률 기본 800+Lv×20 + 장비 bowPierce×300/패시브 pPierce×30 반영, +100 보정. 전염+마지막 적 처형. 감염 사망 시 폭발+연쇄 전염. 악의 15. 사거리 4000. 쿨 15초(Lv당-0.5초)':'Fire 1 poison-blood blade: base pierce rate 800+Lv×20 with bowPierce×300 and pPierce×30 scaling, plus +100 bonus. Plague+execute last enemy. Infected death → explosion+chain plague. Malice 15. Range 4000. CD 15s (-0.5s/Lv)',
'마우스 조준 설치. 쿨 20초. 화면 내 클릭 위치에 암전나선 (3초, 10틱, 틱당 100+Lv*20). Lv당 범위+22. 같은 지역 중복 불가':'Mouse-aim placement. CD 20s. Dark spiral at click pos (3s, 10 ticks, 100+Lv*20/tick). Per Lv range+22. No stacking same area',
'현재 위치에 9개 기둥 순차 발동. 5초간 악의 기둥을 소환하여 반경 내 적에게 지속 암전 데미지+감속. 범위 250+(Lv-1)×22. 대왕치기와 합체→기둥강타. 쿨 15초':'9 pillars activate sequentially at current pos. 5s dark pillars deal sustained dark DMG+slow to enemies in radius. Range 250+(Lv-1)×22. Fuses with Giant Slam → Pillar Strike. CD 15s',
'현재 위치에 회복의 영역 설치 (12초 지속). 땅 위: HP/MP/ST 초당+10 리젠 + 회복력 2배 + 쿨다운 속도 2배. 쿨 30초. Lv당 범위+20 지속+0.5초':'Place holy domain at current pos (12s duration). On ground: HP/MP/ST +10/s regen + 2x recovery + 2x CD speed. CD 30s. Per Lv range+20 duration+0.5s',
'범위 내 몬스터 부활력 -15%~30%(Lv1=15%, Lv10=30%). Lv1 범위400, Lv10 범위697. Lv당 범위+33. 쿨 30초. 지속 10초':'Monsters in range: revive power -15%~30%(Lv1=15%, Lv10=30%). Lv1 range 400, Lv10 range 697. Per Lv range+33. CD 30s. Duration 10s',
'마우스 조준 설치. 2스택 (15초/1충전, Lv10→3스택). 범위 내 빙결 저항 -50%, 빙결 게이지 급속 축적. 3초 지속. MP 40. Lv당 범위+22 축적+10%':'Mouse-aim placement. 2 stocks (15s/charge, Lv10→3 stocks). Freeze resist -50% in range, rapid freeze gauge buildup. 3s duration. MP 40. Per Lv range+22 buildup+10%',
'땅을 내리쳐 원형 진동파 발생(범위400). 일반몹에게 큰 포이즈 피해, 보스 체간 파괴에 강함. 회전기폭과 합체→지진폭풍!':'Slam ground → circular shockwave (range 400). High poise DMG to mobs, strong posture break vs bosses. Fuses with Whirlwind Detonate → Earthquake Storm!',
'땅을 내리쳐 원형 진동파 발생(범위400). 일반몹에게 큰 포이즈 피해, 보스 체간 파괴에 강함. 악의기둥과 합체→기둥강타!':'Slam ground → circular shockwave (range 400). High poise DMG to mobs, strong posture break vs bosses. Fuses with Dark Pillar → Pillar Slam!',
'사슬기동 중 E → 즉시 착지하며 화염폭발. 범위200~350 INT 스케일 화염 마법데미지+넉백. 이동거리에 비례해 데미지↑(최대 x4.0). MP 소모. Lv당 범위+16 뎀+12%':'During chain dash E → instant land with fire explosion. Range 200~350 INT scale fire magic DMG+knockback. DMG scales with travel distance (max x4.0). MP cost. Per Lv range+16 DMG+12%',
'사슬기동 중 우클릭 → 땅 내려찍기. 범위200~350 데미지x8 그로기x6. 이동거리 비례 최대x6. 일반몹 즉시 기절(5초), 보스 체간 대량 삭감. Lv당 범위+16 데미지+15% 그로기+15%':'During chain dash RMB → ground slam. Range 200~350 DMG x8 groggy x6. Distance scale max x6. Instant stun mobs (5s), massive boss posture break. Per Lv range+16 DMG+15% groggy+15%',
'[히든: 5성 dimRush 합체] 사슬기동 중 좌클릭 → 이동 중 전방 광역 베기+출혈. STR 스케일 물리데미지. 다단히트. Lv당 뎀+12% 범위+15':'[Hidden: 5-star dimRush fuse] During chain dash LMB → forward AoE slash+bleed while moving. STR scale physical DMG. Multi-hit. Per Lv DMG+12% range+15',
'[히든: 암전나선 합체] Q 홀드 시 보호막이 점점 커지며 HP 초당 10% 회복. 보호막 크기에 비례해 데미지 감소. MP 소모':'[Hidden: Dark Spiral fuse] Q hold: shield grows over time + HP 10%/s regen. DMG reduction scales with shield size. MP cost',
'[히든: 암전나선 합체] E로 조준, 클릭 설치. 에너지 쐐기를 지상에 꽂아 회전+데미지. MP100. 1차지 쿨10초. 5초+Lv당0.5초 지속. Lv당 거리+50':'[Hidden: Dark Spiral fuse] E to aim, click to place. Energy wedge planted on ground — rotates+DMG. MP 100. 1 charge CD 10s. 5s+0.5s/Lv duration. Per Lv range+50',
'[고정: 칼등치기 합체] 보유 시 칼등치기에 전방 충격파 자동 발동. 제자리 처내기. 쿨 5초. Lv당 뎀+12% 범위+20':'[Fixed: Blade Parry fuse] When owned, swipe auto-triggers forward shockwave. Stationary swipe. CD 5s. Per Lv DMG+12% range+20',
'현재 위치에 파쇄 영역 설치 (10초). 범위 내 적 물리방어력 -10%. 쿨 25초. Lv당 범위+22 효과+1% 지속+0.3초':'Place shatter domain at current pos (10s). Enemy phys DEF -10% in range. CD 25s. Per Lv range+22 effect+1% duration+0.3s',
'현재 위치에 침식 영역 설치 (10초). 범위 내 적 마법저항력 -10%. 쿨 25초. Lv당 범위+22 효과+1% 지속+0.3초':'Place corrosion domain at current pos (10s). Enemy magic resist -10% in range. CD 25s. Per Lv range+22 effect+1% duration+0.3s',
'현재 위치에 관통 영역 설치 (10초). 범위 내 적 투사체저항력 -10%. 쿨 25초. Lv당 범위+22 효과+1% 지속+0.3초':'Place pierce domain at current pos (10s). Enemy projectile resist -10% in range. CD 25s. Per Lv range+22 effect+1% duration+0.3s',
'현재 위치에 부활 영역 설치 (10초). 영역 안에서 부활력 +10%. 쿨 25초. Lv당 범위+22 효과+1% 지속+0.3초':'Place revival domain at current pos (10s). Revive power +10% inside zone. CD 25s. Per Lv range+22 effect+1% duration+0.3s',
'[고정: Space] 현재 위치에 가시덫 설치 (1렙 반경200, 10렙398). 슬로우 70%(+2%/Lv, 최대90%)+출혈. INT×magicRef×3(+10%/Lv). 악의 10, 쿨 10초. Lv당 범위+22':'[Fixed: Space] Place spike trap at current pos (Lv1 radius 200, Lv10 398). Slow 70%(+2%/Lv, max 90%)+bleed. INT×magicRef×3(+10%/Lv). Malice 10, CD 10s. Per Lv range+22',
'[고정: E, Lv300 해금] 유도 파란콩 50발 순차 발사 (5초간). MP 100(+1.5/Lv) 소모. 적 추적. 쿨 5초. Lv당 사거리+30 (뎀은 _skMul 계수 적용)':'[Fixed: E, unlock Lv300] 50 homing blue shots fired sequentially (over 5s). MP 100(+1.5/Lv) cost. Tracks enemies. CD 5s. Per Lv range+30 (DMG uses _skMul)',
'[히든: E, Lv700 해금] 홀드 시 3단계 차지 범위폭발 (0.5/1.0/1.5초). 범위 600/1000/1400px. 3단 만충 자동폭발. INT 스케일, 무속성':'[Hidden: E, unlock Lv700] Hold for 3-stage charge AoE explosion (0.5/1.0/1.5s). Range 600/1000/1400px. Stage 3 full charge auto-detonates. INT scale, no element',
'유령 허수아비를 소환하여 유도탄막 어그로를 끈다. 탄막을 흡수해 자원 축적 (기본 20개, Lv당+3). 1개당 HP/MP/ST 각 100. R키로 회수. 쿨 10초':'Summon phantom scarecrow to draw homing projectile aggro. Absorbs projectiles for resource buildup (base 20, +3/Lv). Per absorbed: HP/MP/ST +100 each. R key to retrieve. CD 10s',
'폭발 허수아비 설치. 탄막을 흡수하고 재입력 시 폭발! 1스택당 (INT마법뎀+탄막뎀)×10 마법데미지. 범위 250+흡수×25 (최대1000). 최대흡수 1렙20~20렙60. 쿨 10초':'Place explosive scarecrow. Absorbs projectiles, re-press to detonate! Per stack: (INT magic DMG + proj DMG)×10. Range 250+absorbed×25 (max 1000). Max absorb Lv1=20~Lv20=60. CD 10s',
'[선택: 1~4번, Lv500 해금] 현재 위치에 공성쇠뇌 터렛 설치. 재입력 시 철거. 설치 중 플레이어 석궁 사용 불가 (터렛만 발사). 데미지+50%, 공속+50%, 사거리+50%. ST 100. 쿨 10초. Lv당 뎀+5% 공속+5% 사거리+5%':'[Select: 1~4, unlock Lv500] Deploy siege crossbow turret at current pos. Re-press to dismantle. While deployed: player crossbow disabled (turret fires only). DMG+50%, ATK SPD+50%, range+50%. ST 100. CD 10s. Per Lv DMG+5% ATK SPD+5% range+5%',
'[Ctrl, Lv500 해금] 발동 시 3초 전 상태로 되돌린다. 위치/HP/MP/ST 완전 복원. Lv당 되감기+0.105초 (1렙 3초, 20렙 5초). MP 50(+5/Lv, 20렙150). 쿨 45초':'[Ctrl, unlock Lv500] Rewind to state from 3s ago. Restores position/HP/MP/ST. Per Lv rewind+0.105s (Lv1=3s, Lv20=5s). MP 50(+5/Lv, Lv20=150). CD 45s',
'[선택: 1~4번] 마우스 조준 → 전기창을 땅에 꽂는다. 5스택(12초/1충전, Lv10→6스택). 창끼리 600px 이내면 전류 아크 발생, 경로 위 적에게 감전 틱 데미지. MP 50. 지속 10초(+0.5초/Lv). Lv당 아크뎀+10%':'[Select: 1~4] Mouse aim → plant electric spear on ground. 5 stocks (12s/charge, Lv10→6). Spears within 600px create lightning arcs dealing shock tick DMG to enemies on path. MP 50. Duration 10s (+0.5s/Lv). Per Lv arc DMG+10%',
'성능 등급:':'Perf Grade:',
'벤치 FPS:':'Bench FPS:',
// --- CAT-82: skill panel labels ---
'스킬 정보':'Skill Info',
'타입':'Type',
'미습득':'Not Learned',
'SP 비용':'SP Cost',
'악의 비용':'Malice Cost',
'쿨다운':'Cooldown',
'요구 레벨':'Req. Lv',
'기본 참조뎀':'Base Reference',
'스탯 배율':'Stat Mult',
'패시브 배율':'Passive Mult',
'레벨 배율':'Skill Lv Mult',
'예상 평균 뎀':'Estimated Avg DMG',
'치명타':'Critical',
'치명타 확률':'Crit Rate',
'치명타 배율':'Crit Dmg',
'유효 배율':'Effective Mult',
'스킬 고유':'Skill Specific',
'1타 배율':'1-Hit Mult',
'2타 배율':'2-Hit Mult',
'3타 배율':'3-Hit Mult',
'레벨당 뎀':'Per Lv DMG',
'검기 거리':'Crescent Range',
'레벨당 거리':'Lv Range Bonus',
'ST/틱':'ST/Tick',
'레벨당 크기':'Per Lv Size',
'넉백':'Knockback',
'충전 시간':'Charge Time',
'레벨당 범위':'Per Lv Range',
'관통률':'Pierce Rate',
'지속뎀':'DOT Duration',
'무한':'Infinite',
'타격 형식':'AoE Type',
'진동파':'Shockwave',
'스태거':'Stagger',
'높음':'High',
'스톡':'Stocks',
'기둥 수':'Pillars',
'지속':'Duration',
'반경':'Radius',
'슬로우':'Slow',
'활':'Bow',
// --- CAT-83: affix desc labels ---
'독 DoT':'Poison DoT',
'화상 DoT':'Fire DoT',
'빙결 DoT+감속':'Ice DoT+Slow',
'연쇄전격':'Chain Lightning',
'저주(힐차단)':'Curse(Heal Block)',
'방어무시':'Armor Ignore',
'치명타율':'Crit Rate',
'스태거+':'Stagger+',
'체인타겟+':'Chain Target+',
'처치 후 뎀+':'Kill DMG+',
'크리폭발(ATK×)':'Crit Explode(ATK×)',
'원소뎀+':'Elem DMG+',
'공격속도+':'Atk Spd+',
'패리보너스+':'Parry Bonus+',
'추적콤보+10':'Track Combo+10',
'작살뎀+':'Harpoon DMG+',
'스킬뎀+':'Skill DMG+',
'쿨다운-':'CD-',
'방어력+':'DEF+',
'쉴드+':'Shield+',
'이동속도+':'Move Spd+',
'크리확률+':'Crit Rate+',
'크리배율+':'Crit Dmg+',
'화염저항':'Fire Res',
'빙결저항':'Ice Res',
'암전저항':'Lightning Res',
'암흑저항':'Dark Res',
'독저항':'Poison Res',
'전원소저항':'All Elem Res',
'물리DR':'Phys DR',
'반사%':'Reflect%',
'가시뎀':'Thorns DMG',
'배리어':'Barrier',
'CC저항':'CC Resist',
'위기뎀+':'Crisis DMG+',
'피격반격':'Hit Counter',
'패링폭발(ATK×)':'Parry Burst(ATK×)',
'체간파괴뎀+':'Poise Break DMG+',
'원소전환':'Elem Convert',
'상태이상해제':'Status Clear',
'불굴(1회생존)':'Tenacity(Survive×1)',
'부활(HP회복)':'Revive(HP Restore)',
'드롭률+':'Drop Rate+',
'경험치+':'EXP+',
'골드+':'Gold+',
'포션회복+':'Potion Heal+',
'사슬게이지+':'Chain Gauge+',
'부활억제':'Anti-Revive',
'부활력+':'Revival Pow+',
'부활쿨-':'Revival CD-',
'최대HP%+':'Max HP%+',
'HP리젠+':'HP Regen+',
'회복력+':'Heal Pow+',
'마법뎀+':'Magic DMG+',
'MP소비-':'MP Cost-',
'화염뎀%+':'Fire DMG%+',
'화염관통%':'Fire Pen%',
'적중화상':'On-Hit Burn',
'크리화폭':'Crit Fire Burst',
'화상지속+':'Burn Duration+',
'화염뎀보너스':'Fire DMG Bonus',
'빙결뎀%+':'Ice DMG%+',
'빙결관통%':'Ice Pen%',
'적중빙결':'On-Hit Freeze',
'크리빙폭':'Crit Ice Burst',
'빙결지속+':'Freeze Duration+',
'빙결뎀보너스':'Ice DMG Bonus',
'뇌전뎀%+':'Lightning DMG%+',
'뇌전관통%':'Lightning Pen%',
'적중감전':'On-Hit Shock',
'크리뇌폭':'Crit Lightning Burst',
'감전지속+':'Shock Duration+',
'뇌전뎀보너스':'Lightning DMG Bonus',
'암흑뎀%+':'Dark DMG%+',
'암흑관통%':'Dark Pen%',
'적중저주':'On-Hit Curse',
'크리암폭':'Crit Dark Burst',
'저주지속+':'Curse Duration+',
'암흑뎀보너스':'Dark DMG Bonus',
'독뎀%+':'Poison DMG%+',
'독관통%':'Poison Pen%',
'적중중독':'On-Hit Poison',
'크리독폭':'Crit Poison Burst',
'독지속+':'Poison Duration+',
'독뎀보너스':'Poison DMG Bonus',
'근접뎀%+':'Melee DMG%+',
'원거리뎀%+':'Ranged DMG%+',
'마법뎀%+':'Magic DMG%+',
'빔뎀%+':'Beam DMG%+',
'DoT뎀%+':'DoT DMG%+',
'투사체뎀%+':'Proj DMG%+',
'범위반경+':'AoE Radius+',
'근접크리+':'Melee Crit+',
'마법크리+':'Magic Crit+',
'석궁크리+':'Xbow Crit+',
'근접공속+':'Melee Spd+',
'석궁공속+':'Xbow Spd+',
'시전속도+':'Cast Spd+',
'전속성관통':'All Elem Pen',
'쉴드관통':'Shield Pen',
'방어력깎기':'Armor Shred',
'투사체속도+':'Proj Speed+',
'적중시화구':'On-Hit Fireball',
'적중시연쇄뇌격':'On-Hit Chain Lightning',
'적중빙결%':'On-Hit Freeze%',
'적중스턴%':'On-Hit Stun%',
'적중중독%':'On-Hit Poison%',
'적중출혈%':'On-Hit Bleed%',
'적중약화%':'On-Hit Weaken%',
'적중감속%':'On-Hit Slow%',
'적중표적%':'On-Hit Mark%',
'크리폭발(HP%)':'Crit Explode(HP%)',
'크리연쇄(HP%)':'Crit Chain(HP%)',
'크리빙결%':'Crit Freeze%',
'크리HP+':'Crit HP+',
'크리MP+':'Crit MP+',
'크리쉴드+':'Crit Shield+',
'피격방어+':'Hit DEF+',
'반격가시':'Counter Thorns',
'빙결파동%':'Ice Nova%',
'자동암흑막':'Auto Dark Shield',
'주기치유':'Periodic Heal',
'시체폭발%':'Corpse Explode%',
'회피뎀+':'Dodge DMG+',
'패링폭발%':'Parry Burst%',
'블록HP+':'Block HP+',
'블록MP+':'Block MP+',
'회전참뎀+':'Whirlwind DMG+',
'옴니빔뎀+':'Omni Beam DMG+',
'화구뎀+':'Fireball DMG+',
'미사일뎀+':'Missile DMG+',
'청탄뎀+':'Blue Shot DMG+',
'폭렬탄뎀+':'Blast Shot DMG+',
'지옥광선뎀+':'Hell Ray DMG+',
'악의폭풍뎀+':'Malice Storm DMG+',
'연쇄참뎀+':'Chain Slash DMG+',
'거인강타뎀+':'Giant Slam DMG+',
'유령보행뎀+':'Ghost Walk DMG+',
'악의박격뎀+':'Malice Mortar DMG+',
'화염오라뎀+':'Fire Aura DMG+',
'빙구뎀+':'Ice Orb DMG+',
'화염빔뎀+':'Fire Beam DMG+',
'악의사냥뎀+':'Malice Hunt DMG+',
'암흑기둥뎀+':'Dark Pillar DMG+',
'역병뎀+':'Plague DMG+',
'가시오라뎀+':'Spike Aura DMG+',
'연쇄돌격뎀+':'Chain Assault DMG+',
'회피확률+':'Dodge Rate+',
'회피쿨-':'Dodge CD-',
'쉴드%+':'Shield%+',
'쉴드리젠%+':'Shield Regen%+',
'쉴드쿨-':'Shield CD-',
'HP리젠%+':'HP Regen%+',
'ST리젠+':'ST Regen+',
'ST리젠%+':'ST Regen%+',
'MP리젠+':'MP Regen+',
'MP리젠%+':'MP Regen%+',
'화염DR':'Fire DR',
'빙결DR':'Ice DR',
'뇌전DR':'Lightning DR',
'암흑DR':'Dark DR',
'독DR':'Poison DR',
'전체DR':'All DR',
'엘리트DR':'Elite DR',
'스턴저항':'Stun Res',
'감속저항':'Slow Res',
'넉백저항':'KB Res',
'돌진거리+':'Dash Range+',
'돌진쿨-':'Dash CD-',
'전투이속+':'Combat MSpd+',
'비전투이속+':'Out-Combat MSpd+',
'습득범위+':'Pickup Range+',
'전스탯+':'All Stats+',
'적중자원+':'On-Hit Resource+',
'화염최대저항+':'Fire Max Res+',
'빙결최대저항+':'Ice Max Res+',
'뇌전최대저항+':'Lightning Max Res+',
'암흑최대저항+':'Dark Max Res+',
'독최대저항+':'Poison Max Res+',
'스킬쿨-':'Skill CD-',
'물약쿨-':'Potion CD-',
'강화성공+':'Craft Rate+',
'악의획득+':'Malice Gain+',
'악마화뎀+':'Demon DMG+',
'악마화DR':'Demon DR',
'영혼수확+':'Soul Harvest+',
'생명흡혈%':'Life Leech%',
'과치유→쉴드':'Overheal→Shield',
'만마나뎀+':'Full MP DMG+',
'이동DR':'Move DR',
'정지뎀+':'Stationary DMG+',
'회피후뎀+':'After Dodge DMG+',
'패링쉴드+':'Parry Shield+',
'콤보보너스+':'Combo Bonus+',
'HP≥70%뎀+':'HP≥70% DMG+',
'적HP≤30%뎀+':'Foe HP≤30% DMG+',
'HP100%뎀+':'HP100% DMG+',
'HP≤35%뎀+':'HP≤35% DMG+',
'적HP≤20%뎀+':'Foe HP≤20% DMG+',
'근접뎀+':'Melee DMG+',
'원거리뎀+':'Ranged DMG+',
'스턴적뎀+':'vs Stunned DMG+',
'빙결적뎀+':'vs Frozen DMG+',
'화상적뎀+':'vs Burning DMG+',
'중독적뎀+':'vs Poisoned DMG+',
'저주적뎀+':'vs Cursed DMG+',
'감속적뎀+':'vs Slowed DMG+',
'보스뎀+':'Boss DMG+',
'엘리트뎀+':'Elite DMG+',
'일반몹뎀+':'Mob DMG+',
'선제뎀+':'First Strike DMG+',
'물리흡혈%':'Phys Leech%',
'마나흡수%':'Mana Leech%',
'ST흡수%':'ST Leech%',
'적중HP+':'On-Hit HP+',
'처치HP+':'On-Kill HP+',
'처치MP+':'On-Kill MP+',
'처치ST+':'On-Kill ST+',
'처치시폭발':'On-Kill Explode',
'처치이속+':'On-Kill MSpd+',
'HP≥70%방어+':'HP≥70% DEF+',
'HP≤50%이속+':'HP≤50% MSpd+',
'DoT피해감소':'DoT DMG Reduce',
'보스피해감소':'Boss DMG Reduce',
'근접피해감소':'Melee DMG Reduce',
'원거리피해감소':'Ranged DMG Reduce',
'처치HP회복':'On-Kill HP Restore',
'처치쉴드회복':'On-Kill Shield Restore',
'ST소비-':'ST Cost-',
'HP≥70%공격+':'HP≥70% ATK+',
'HP≤35%흡혈':'HP≤35% Leech',
'보스추가뎀':'vs Boss DMG+',
'엘리트추가뎀':'vs Elite DMG+',
'공격력+':'ATK+',
'크리뎀+':'Crit DMG+',
// --- CAT-84/85/86: affix names + implicit + legendary ---
'물리방패의':'Physical Shield',
'지속의':'Stamina',
'마나의':'Mana',
'원소수호의':'Elem Guard',
'행운의':'Fortune',
'근성의':'Grit',
'풍요의':'Abundance',
'약자포식의':'Predator',
'만혈의':'Full Life',
'사선의':'Low Life',
'처형의':'Execute',
'근접살의':'Melee DMG',
'원거리의':'Ranged',
'경직파의':'Stagger Break',
'동파의':'Freeze Strike',
'연소의':'Burning',
'맹독살의':'Venom Slayer',
'저주살의':'Curse Slayer',
'구속의':'Binding',
'왕살의':'Boss Slayer',
'정예살의':'Elite Slayer',
'군살의':'Mob Slayer',
'선제의':'First Strike',
'흡혈의':'Vampirism',
'흡마의':'Mana Leech',
'흡정의':'Stamina Leech',
'타격재생의':'Hit Regen',
'처치회복의':'Kill Recovery',
'처치흡마의':'Kill Mana Leech',
'처치활력의':'Kill Stamina',
'처치폭발의':'Kill Explosion',
'처치질주의':'Kill Sprint',
'건강방어의':'Healthy Defense',
'중상보호의':'Wounded Shield',
'위기질주의':'Crisis Sprint',
'지속피해방어의':'DoT DR',
'왕피해방어의':'Boss DMG DR',
'근접방어의':'Close DR',
'원거리방어의':'Ranged DR',
'처치생명의':'Kill HP',
'처치수호의':'Kill Shield',
'화염강화의':'Fire Amp',
'화염관통의':'Fire Pierce',
'발화의':'Ignition',
'화염폭발의':'Fire Burst',
'맹화의':'Blaze',
'화염의힘':'Fire Power',
'빙결강화의':'Ice Amp',
'빙결관통의':'Ice Pierce',
'동결의':'Freeze',
'빙결폭발의':'Ice Burst',
'영빙의':'Permafrost',
'빙결의힘':'Ice Power',
'뇌전강화의':'Thunder Amp',
'뇌전관통의':'Thunder Pierce',
'감전의':'Shock',
'뇌전폭발의':'Thunder Burst',
'낙뢰의':'Thunderbolt',
'뇌전의힘':'Thunder Power',
'암흑강화의':'Dark Amp',
'암흑관통의':'Dark Pierce',
'침식의':'Erosion',
'암흑폭발의':'Dark Burst',
'심연의':'Abyss',
'암흑의힘':'Dark Power',
'맹독강화의':'Venom Amp',
'독관통의':'Poison Pierce',
'중독의':'Poisoning',
'독폭발의':'Poison Burst',
'맹독지속의':'Venom Duration',
'독의힘':'Poison Power',
'격투의':'Melee',
'원사의':'Ranged Shot',
'주술의':'Spell',
'광선의':'Beam',
'탄도의':'Ballistic',
'확산의':'AoE Radius',
'근접회심의':'Melee Crit',
'마법회심의':'Spell Crit',
'사격회심의':'Ranged Crit',
'근접쾌속의':'Melee Speed',
'사격쾌속의':'Ranged Speed',
'영창의':'Chanting',
'전속성관통의':'All-Elem Pierce',
'쉴드파괴의':'Shield Bypass',
'갑옷분쇄의':'Armor Shred',
'탄속의':'Proj Speed',
'화구발사의':'Fireball Launch',
'연쇄뇌격의':'Chain Lightning',
'동결타의':'Freeze Strike',
'경직타의':'Stagger Strike',
'독침의':'Poison Sting',
'출혈의':'Bleed',
'약화의':'Weakness',
'둔화의':'Slow',
'표적의':'Marking',
'회심폭발의':'Crit Explosion',
'회심연쇄의':'Crit Chain',
'회심빙결의':'Crit Freeze',
'회심치유의':'Crit Heal',
'회심영력의':'Crit Mana',
'회심수호의':'Crit Shield',
'피격강화의':'Hit Boost',
'반격가시의':'Counter Thorns',
'빙결파동의':'Ice Nova',
'암흑보호의':'Dark Shield',
'치유파동의':'Heal Pulse',
'시체폭발의':'Corpse Explosion',
'회피반격의':'Dodge Counter',
'패링폭파의':'Parry Shatter',
'블록치유의':'Block Heal',
'블록영력의':'Block Mana',
'회전참강화':'Spin Slash Boost',
'옴니빔강화':'Omni Beam Boost',
'화구강화':'Fireball Boost',
'미사일강화':'Missile Boost',
'청탄강화':'Blue Shot Boost',
'폭렬탄강화':'Burst Shot Boost',
'지옥광선강화':'Hellray Boost',
'악의폭풍강화':'Malice Storm Boost',
'연쇄참강화':'Chain Slash Boost',
'거인강타강화':'Giant Slam Boost',
'유령보행강화':'Ghost Walk Boost',
'악의박격강화':'Malice Mortar Boost',
'화염오라강화':'Fire Aura Boost',
'빙구강화':'Ice Orb Boost',
'화염빔강화':'Fire Beam Boost',
'악의사냥강화':'Malice Hunt Boost',
'암흑기둥강화':'Dark Pillar Boost',
'역병강화':'Plague Boost',
'가시오라강화':'Thorn Aura Boost',
'연쇄돌격강화':'Chain Assault Boost',
'회피의':'Evasion',
'회피쿨감의':'Dodge CD Red',
'수호력의':'Shield Power',
'수호재생의':'Shield Regen',
'수호쿨감의':'Shield CD Red',
'재생력의':'Regen Power',
'활력재생의':'Stamina Regen',
'마력재생의':'Mana Regen',
'화염보호의':'Fire Shield',
'빙결보호의':'Ice Shield',
'뇌전보호의':'Thunder Shield',
'해독의':'Antidote',
'만물보호의':'All Protection',
'정예보호의':'Elite Shield',
'경직저항의':'Stagger Resist',
'빙결저항의':'Freeze Resist',
'감속저항의':'Slow Resist',
'넉백저항의':'Knockback Resist',
'돌진거리의':'Dash Range',
'돌진쿨감의':'Dash CD Red',
'전투질주의':'Combat Sprint',
'평화질주의':'Peace Sprint',
'습득범위의':'Pickup Radius',
'힘의':'Strength',
'민첩의':'Dexterity',
'지능의':'Intelligence',
'만능의':'Versatile',
'지구력의':'Max Stamina',
'마나력의':'Mana Power',
'타격자원의':'Hit Resource',
'화염한계의':'Fire Cap',
'빙결한계의':'Ice Cap',
'뇌전한계의':'Thunder Cap',
'암흑한계의':'Dark Cap',
'독한계의':'Poison Cap',
'스킬쿨감의':'Skill CD Red',
'물약쿨감의':'Potion CD Red',
'장인의':'Craftsmanship',
'탐욕의':'Greed',
'수련의':'Training',
'수집의':'Gathering',
'악마의힘':'Demon Power',
'악마보호의':'Demon Shield',
'영혼수확의':'Soul Harvest',
'생명흡수의':'Life Absorption',
'과치유수호의':'Overheal Shield',
'만마력의':'Full Mana DMG',
'이동방어의':'Moving DR',
'정지공세의':'Stationary Boost',
'회피공세의':'Post-Dodge Boost',
'패링보호의':'Parry Shield',
'콤보폭발의':'Combo Burst',
'물리타격의':'Phys Strike',
'화염타격의':'Fire Strike',
'빙결타격의':'Ice Strike',
'뇌전타격의':'Thunder Strike',
'암흑타격의':'Dark Strike',
'독타격의':'Poison Strike',
'최소공격의':'Min ATK',
'최대공격의':'Max ATK',
'전투력의':'Combat Power',
'무기사거리의':'Weapon Range',
'활사거리의':'Bow Range',
'이중타의':'Double Strike',
'다중발사의':'Multi Shot',
'관통횟수의':'Pierce Count',
'관통유지의':'Pierce Keep',
'연쇄유지의':'Chain Keep',
'범위확장의':'Splash Range',
'범위피해의':'Splash DMG',
'돌진공격의':'Dash ATK',
'반격공격의':'Counter ATK',
'후방타의':'Backstab',
'침식가속의':'Erosion Speed',
'출혈지속의':'Bleed Duration',
'마법타격의':'Magic Strike',
'주문증폭의':'Spell Amp',
'연살뎀의':'Kill Streak DMG',
'연살속의':'Kill Streak Speed',
'기세의':'Momentum',
'정지공격의':'Static Strike',
'이동공격의':'Mobile Strike',
'패링공세의':'Post-Parry Boost',
'임사폭발의':'Near-Death Burst',
'만기력공의':'Full Stamina ATK',
'만마력공의':'Full Mana ATK',
'신선처치의':'Fresh Kill',
'경직연장의':'Stagger Extension',
'빙결연장의':'Freeze Extension',
'둔화강화의':'Slow Amp',
'독중첩의':'Poison Stack',
'출혈중첩의':'Bleed Stack',
'발화강화의':'Ignite Amp',
'동상강화의':'Frostbite Amp',
'감전강화의':'Shock Amp',
'사선회심의':'Low HP Crit',
'갑옷강화의':'Armor Boost',
'블록흡수의':'Block Absorb',
'방패타격의':'Shield Bash',
'방패경직의':'Shield Stagger',
'격투속의':'Brawl Speed',
'격투회심의':'Brawl Crit',
'격투경직의':'Brawl Stagger',
'하반재생의':'Leg Regen',
'CC단축의':'CC Duration Red',
'돌진타의':'Dash Strike',
'돌진범위의':'Dash AoE',
'은신질주의':'Stealth Sprint',
'회피감쇠의':'Dodge DR',
'속성감쇠의':'Elem DR',
'마나왕관의':'Mana Helm',
'시전왕관의':'Cast Helm',
'쿨감왕관의':'CD Helm',
'경험왕관의':'EXP Helm',
'공생의':'Symbiosis',
'수질의':'Body-Soul',
'회심흡의':'Crit Leech',
'체마의':'HP-Mana',
'체기의':'HP-Stamina',
'마기의':'Mana-Stamina',
'전재생의':'All Regen',
'힘민의':'STR-DEX',
'힘지의':'STR-INT',
'민지의':'DEX-INT',
'운근의':'Fortune-Grit',
'수확의':'Harvest',
'빙화의':'Ice-Fire',
'뇌암의':'Thunder-Dark',
'근마의':'Blade-Magic',
'속성침식의':'Elem Erosion',
'화염반지의':'Fire Ring',
'빙결반지의':'Ice Ring',
'뇌전반지의':'Thunder Ring',
'암흑반지의':'Dark Ring',
'독반지의':'Poison Ring',
'콤보반지의':'Combo Ring',
'처치마나의':'Kill Mana',
'관통반지의':'Pierce Ring',
'만능목걸이의':'Allround Necklace',
'회심목걸이의':'Crit Necklace',
'관통목걸이의':'Pierce Necklace',
'스킬목걸이의':'Skill Necklace',
'콤보한계의':'Combo Max',
'처치치유의':'Kill Heal',
'지구벨트의':'Stamina Belt',
'포션벨트의':'Potion Belt',
'활력벨트의':'Vitality Belt',
'탐욕벨트의':'Greed Belt',
'마나띠의':'Mana Band',
'시전띠의':'Cast Band',
'마력띠의':'Magic Band',
'주술띠의':'Spell Band',
'속성띠의':'Elem Band',
'전사의힘':'Warrior Power',
'전사생명의':'Warrior Life',
'전사흡혈의':'Warrior Leech',
'전사인내의':'Warrior Poise',
'마법사의힘':'Mage Power',
'마법사마나의':'Mage Mana',
'마법사수호의':'Mage Shield',
'마법사속성의':'Mage Elem',
'궁수의힘':'Archer Power',
'궁수사거리의':'Archer Range',
'궁수관통의':'Archer Pierce',
'궁수질주의':'Archer Sprint',
'탱크생명의':'Tank Life',
'탱크방어의':'Tank Defense',
'탱크블록의':'Tank Block',
'탱크가시의':'Tank Thorns',
'암살회심의':'Assassin Crit',
'암살후방의':'Assassin Backstab',
'암살독의':'Assassin Poison',
'암살회피의':'Assassin Dodge',
'종결자의':'The Ender',
'생존자의':'Survivor',
'종결수호의':'End Shield',
'종결회심의':'End Crit',
'종결공격의':'End ATK',
'종결저항의':'End Resistance',
'종결파괴의':'End Destruction',
'종결보호의':'End Protection',
'종결흡혈의':'End Leech',
'종결인내의':'End Poise',
'종결쿨감의':'End CD Red',
'종결경험의':'End EXP',
'종결약탈의':'End Loot',
'종결악의의':'End Malice',
'종결힘의':'End STR',
'종결민첩의':'End DEX',
'종결지능의':'End INT',
'종결행운의':'End LCK',
'종결근성의':'End Grit',
'종결연살의':'End Kill Chain',
'건강공세의':'Healthy Offense',
'중상폭발의':'Wounded Burst',
'중상흡혈의':'Wounded Leech',
'토벌의':'Vanguard',
'정예토벌의':'Elite Vanguard',
'극대화의':'Maximize',
'공격력 +X%':'ATK +X%',
'관통 확률 +X%':'Pierce Chance +X%',
'방어율 +X%':'Block Rate +X%',
'물리 피해감소 +X%':'Phys DR +X%',
'최대 HP +X':'Max HP +X',
'공격속도 +X%':'ATK Speed +X%',
'상태이상 저항 +X%':'Status Resist +X%',
'이동속도 +X%':'Move Speed +X%',
'원소 저항 +X%':'Elem Resist +X%',
'최대 HP +X%':'Max HP +X%',
'회피 쿨다운 -X%':'Dodge CD -X%',
'물약 쿨다운 -X%':'Potion CD -X%',
'부활력 +X%':'Revive Power +X%',
'마법 데미지 +X%':'Magic DMG +X%',
'전설 특수':'Legendary Special',
'5타 콤보 완성 시 데빌포스 20% 즉시 충전':'5-hit combo: instantly charge DevilForce 20%',
'처치 시 이속 +40%(3초) + 다음 공격 크리 보장':'Kill: MoveSpd +40%(3s) + next attack guaranteed Crit',
'스태거 발동 시 범위 충격파 (ATK×120%)':'Stagger: AoE shockwave (ATK×120%)',
'스태거 발동 시 범위 충격파 (ATK×100%)':'Stagger: AoE shockwave (ATK×100%)',
'강타 시 적 넉백 거리 2배 + 벽충돌 추가뎀':'Heavy hit: Knockback ×2 + wall collision bonus DMG',
'출혈 대상 크리 시 잔여 DoT×300% 즉시 폭발':'Crit vs Bleeding: remaining DoT×300% instant explosion',
'작살 착지 타격 수만큼 데미지 +20% 중첩(최대5)':'Javelin landing hits: stack +20% DMG (max 5)',
'치명타 시 추가 투사체 1발 발사':'Crit: fire 1 additional projectile',
'패리 성공 시 반격 데미지 ×2':'Parry: counter DMG ×2',
'피격 시 3초 쿨로 HP 5% 즉시 회복':'On Hit (3s CD): restore 5% HP instantly',
'스킬 사용 시 20% 확률로 쿨다운 미소모':'Using skills: 20% chance no cooldown consumed',
'공격속도 +20% + 기본공격에 랜덤 원소 추가':'ATK Speed +20% + basic attacks add random element',
'이동 중 지속 HP 재생 (초당 HP의 1%)':'While moving: HP regen (1% HP/sec)',
'회피 직후 첫 공격 데미지 +80%':'First attack after Dodge: DMG +80%',
'패리 타이밍 판정 +50% 확대':'Parry timing window +50% expanded',
'원소 반응 발동 시 추가 폭발 (ATK×80%)':'Elemental reaction: bonus explosion (ATK×80%)',
'처치 시 데빌포스 5% 회복':'Kill: restore 5% DevilForce',
'HP 50% 이하 시 전 스킬 쿨다운 -30%':'Below 50% HP: all skill CD -30%',
'물약 사용 시 5초간 피해 +15%':'Using Potion: DMG +15% for 5s',
'암묵':'Implicit',
'낡은 악마의 팔찌':'Worn Demon Bracelet',
'흑요석 악마의 팔찌':'Obsidian Demon Bracelet',
'미스릴 악마의 팔찌':'Mithril Demon Bracelet',
'낡은 생명의 팔찌':'Worn Life Bracelet',
'스테이지':'Fáze',
'💪 힘 (STR)':'💪 STR',
'🏹 민첩 (DEX)':'🏹 DEX',
'🔮 지능 (INT)':'🔮 INT',
'🍀 행운 (LCK)':'🍀 LCK',
'⚔️ 맹공':'⚔️ Onslaught',
'🔱 돌파':'🔱 Breakthrough',
'⚡ 반격':'⚡ Retaliation',
'🔮 마력폭주':'🔮 Mana Surge',
'🎯 정밀사격':'🎯 Precision',
'🛡 수호신':'🛡 Aegis',
'💚 회복력':'💚 Recovery',
'💥 급소':'💥 Vital Strike',
'🎁 약탈':'🎁 Plunder',
'🔱 관통':'🔱 Pierce',
'💠 마력회복':'💠 Mana Recovery',
'🏹 쇠뇌력':'🏹 Crossbow Mastery',
'⚔ 광전사':'⚔ Berserker',
'🎯 추적자':'🎯 Tracker',
'🗡 물리관통':'🗡 Phys Penetration',
'🔮 마법관통':'🔮 Magic Penetration',
'🌿 풍요':'🌿 Abundance',
'🐺 약자포식':'🐺 Predator',
'☠ 침식':'☠ Corrosion',
'💎 마력그릇':'💎 Mana Vessel',
'💪 힘의그릇':'💪 Stamina Vessel',
'👿 악의중독':'👿 Malice Addict',
'❤️ 강인':'❤️ Fortify',
'🛡 철벽':'🛡 Iron Wall',
'🎯 사냥꾼':'🎯 Hunter',
'✦ 인간성':'✦ Humanity',
'☠ 악마성':'☠ Demon',
'1. 악의폭풍':'1. Malice Storm',
'2. 칼날 계열':'2. Blade Skills',
'3. 역병 확장':'3. Plague Expand',
'4. 이동스킬 마스터':'4. Movement Master',
'5. 사슬 확장':'5. Chain Expand',
'6. 💀 필살기 선택':'6. 💀 Ultimate Pick',
'7. 멸살+만화+원소+전격이동':'7. Beam+Barrage+Elem+Blink',
'8. 회전참+기폭+대왕':'8. Whirl+Det+Giant',
'9. 방패 합체':'9. Shield Fuse',
'10. 해골무덤+악의폭풍':'10. Bone Wall+Malice Storm',
'11. 폭풍소환+얼음보주':'11. Storm+Ice Orb',
'12. 뇌전걸음':'12. Ghost Walk',
'13. 신성 영역':'13. Holy Domain',
'14. 6단합체: 폭풍빔':'14. 6-Fuse: Storm Beam',
'15. 신성+빙결':'15. Holy+Ice',
'16. 암흑+가시+대왕2':'16. Dark+Spike+Slam2',
'17. 사슬 최종':'17. Chain Final',
'⚡ 이동스킬':'⚡ Movement',
'⚔️ 물리':'⚔️ Physical',
'🛡️ 방어':'🛡️ Defense',
'🔮 마법':'🔮 Magic',
'🏹 석궁/투사체':'🏹 Crossbow/Projectile',
'⚙️ 영역':'⚙️ Domain',
'💀 필살기':'💀 Ultimate',
'⭐ 추천':'⭐ Recommend',
'⚔ 공격':'⚔ Attack',
'🛡 방어':'🛡 Defense',
'⚙ 특수':'⚙ Special',
  '👻 공성허수아비!':'👻 Siege Scarecrow!',
  '💥 공성허수아비 폭발!':'💥 Siege Scarecrow Blast!',
};

const _CS_PFX={
'녹슨':'Rezavý','강철':'Ocelový','흑요석':'Obsidiánový','미스릴':'Mithrilový','심판의':'Soudný','천벌의':'Boží trest','파멸의':'Ničivý',
'불꽃':'Plamenný','화염':'Pekelný','염화':'Pekelný plamen','지옥불':'Pekelný žár','지옥화':'Pekelný žár','지옥':'Pekelný žár','멸화의':'Spalující',
'냉기':'Mrazivý','빙결':'Ledový','빙하':'Ledovcový','서리의':'Jinovatý','서리':'Jinovatý','영겁빙':'Věčný led',
'그림자':'Stínový','암흑':'Temný','심연':'Propastný','나락의':'Podzemní','나락':'Podzemní','무간의':'Prázdnotový',
'전기':'Jiskřivý','낙뢰':'Hromový','암전':'Bleskový','뇌신의':'Boha hromů','뇌신':'Boha hromů','만뢰의':'Tisícebleskový',
'축복':'Požehnaný','성광':'Svaté světlo','신성':'Posvátný','천사의':'Andělský','신벌의':'Boží soud',
'낡은':'Opotřebovaný','천':'Plátěný','가죽':'Kožený','강철사':'Ocelotkaninový','은':'Stříbrný','은사':'Stříbronit','화염의':'Pekelný','빙결의':'Ledový','암흑의':'Temný','암전의':'Bleskový'};
const _CS_BASE={
'대검':'Obouruční meč','석궁':'Kuše','연사석궁':'Opakovací kuše','마력석궁':'Arkanová kuše',
'견갑':'Nárameník','대견갑':'Velký nárameník','전투화':'Bojové boty','갑옷':'Brnění','갑주':'Plátová zbroj',
'왕관':'Koruna','장갑':'Rukavice','건틀릿':'Plátové rukavice','바지':'Kalhoty','각반':'Holenní chrániče',
'허리띠':'Opasek','벨트':'Pás','부적':'Talisman','목걸이':'Náhrdelník','반지':'Prsten',
'망토':'Plášť','악마팔찌':'Demon Bracelet','생명팔찌':'Life Bracelet','팔찌':'Náramek','귀걸이':'Náušnice'};

