// 지옥의 길 — Nederlands (nl)
const _NL={
// --- Stage / Boss ---
'썩은 숲':'Verrot Bos','숲의 감시자':'Boswachter','독버섯 거인':'Giftzwam Reus','숲의 사냥꾼':'Bosjager','숲의 기생수':'Parasitair Beest',
'1장 — 썩은 숲':'H1 — Verrot Bos','2장 — 벌레굴':'H2 — Wormennest','3장 — 얼음굴':'H3 — IJsgrot',
'4장 — 고통의 화염지대':'H4 — Infernale Vlakte','5장 — 지옥의 군단':'H5 — Hellegioen','6장 — 사도의 마굴':'H6 — Apostelhol','7장 — 지옥성':'H7 — Helburcht',
'탈출!':'Ontsnapt!','처치':'Kills','경험치':'EXP','최대콤보':'Max Combo',
// --- Tutorial (Crow) ---
'일어나. 여신이 널 여기 보낸 건 죽으라고가 아니야.':'Sta op. De godin stuurde je hier niet naartoe om te sterven.',
'좋아, 감각이 있군. 계속 쳐!':'Goed, je hebt instinct. Blijf slaan!',
'Shift를 눌러. 작살이다. 땅에 꽂아서 끌려가!':'Druk Shift. Dat is de harpoen. Steek hem erin en word meegetrokken!',
'작살로 끌려가는 중엔 무적이다. 위험할 때 쓰면 좋아.':'Terwijl de harpoen je trekt ben je onsterfelijk. Gebruik het in gevaar.',
'...아파? 당연하지. 여긴 지옥이야.':'...Doet het pijn? Natuurlijk. Dit is de hel.',
'Q를 눌러! 악의로 보호막을 만들 수 있다.':'Druk Q! Maak een schild van kwaad.',
'보호막 없이 버틸 생각은 버려.':'Vergeet overleven zonder schild.',
'우클릭이 패링이다. 적 공격이 닿기 직전에 눌러!':'Rechtsklik om te pareren. Druk vlak voordat de vijand raakt!',
'못 하겠으면 때려. 안 죽으면 그만이야.':'Kan je niet pareren? Sla gewoon. Niet sterven is genoeg.',
'됐어! 감 잡았구나.':'Zo! Je krijgt het door.',
'하나 죽었군.':'Eentje neer.',
'유령쇠뇌야. 인사해.':'Dat is de geestarmborst. Zeg hallo.',
'빨간 탄을 무서워하지 마. 악의가 강하다.':'Wees niet bang voor rode kogels. Kwaad is sterk.',
'패링으로 돌려주고, Q 보호막도 써! 악의를 잘 굴려!':'Pareer ze terug, gebruik ook het Q-schild! Beheers je kwaad!',
'무지개빛은 패링 불가! 피해!':'Regenboogschoten kunnen niet gepareerd worden! Ontwijken!',
'피가 새고 있다. Shift. 빠져.':'Je bloedt leeg. Shift. Wegwezen.',
'물약 있잖아! 숫자키!':'Je hebt drankjes! Cijfertoetsen!',
'우클릭. 적 손목이 꺾일 때 쳐.':'Rechtsklik. Sla wanneer hun pols buigt.',
'빨간 탄은 악의 덩어리다. 쳐내서 이용해.':'Rode kogels zijn brokken kwaad. Kaats ze terug en gebruik ze.',
'무지개빛만 피하면 돼! 나머지는 다 패링!':'Ontwijken alleen de regenboog! Al het andere pareren!',
'Q 보호막도 패링이 가능해!':'Het Q-schild kan ook pareren!',
'위험해! 쉬프트 사슬기동으로 피해!!':'Gevaar! Shift kettendash om te ontsnappen!!',
'쉬프트! 사슬기동은 이동기야! 끌려가면서 무적이라고!':'Shift! Kettendash is beweging! Onsterfelijk terwijl je wordt meegetrokken!',
'스킬포인트가 쌓였어! K 눌러서 스킬 배우자!':'Vaardigheidspunten klaar! Druk K om vaardigheden te leren!',
'속성을 읽어. 약점을 찌르면 두 배로 썩는다.':'Lees de elementen. Zwakke punten raken voor dubbele schade.',
'K를 눌러봐! 스킬을 배울 수 있어!':'Druk K! Je kunt vaardigheden leren!',
'C 눌러서 능력치 찍어! 패시브도 있어~':'Druk C voor stats! Passieven ook~',
'G를 눌러. 대장간에서 장비를 강화할 수 있다.':'Druk G. Verbeter uitrusting bij de smidse.',
'F키도 스킬 슬롯이야! 스킬 많으면 L로 배정해봐~':'F is ook een vaardigheidssleuf! Gebruik L om toe te wijzen~',
'Z. 필살기다. 아껴 써라.':'Z. Dat is je ultiem. Gebruik het verstandig.',
'L-CTRL로 유령걸음이나 얼음보주 쓸 수 있어!':'L-CTRL voor Geestenstap of IJsbol!',
'L을 눌러. 스킬 슬롯을 정리해야 한다.':'Druk L. Orden je vaardigheidssleuten.',
'가방 터지겠다! V 눌러서 창고에 넣어둬!':'Tas staat op barsten! Druk V om op te slaan!',
'ESC로 설정 열 수 있어! 난이도 바꾸기, 자동물약 조절~':'ESC voor instellingen! Moeilijkheid, auto-drankjes~',
// --- Tutorial (Cat) ---
'...아직 살아있네. 좌클릭으로 저것들 쳐봐.':'...Nog in leven. Probeer die te slaan met linksklik.',
'...치는 건 할 줄 아네. 피하는 건?':'...Je kunt slaan. Maar kun je ontwijken?',
'흥, 작살 못 맞추면 헛수고야.':'Hmph, mis de harpoen en het is verspild.',
'...운이 좋았을 뿐이야. 아마.':'...Gewoon geluk. Waarschijnlijk.',
'...고기 냄새. 싫진 않네.':'...Ruikt naar vlees. Niet slecht.',
'...말은 못해.':'...Het kan niet praten.',
'예쁘다고 만지면 죽어.':'Ze aanraken omdat ze mooi zijn? Je gaat dood.',
'작살 던져! 끌려가면 무적이야!':'Gooi de harpoen! Onsterfelijk terwijl je wordt meegetrokken!',
'...마시든 말든. 네 목숨이니까.':'...Drink of niet. Het is jouw leven.',
'그게 패링이야! 타이밍이 전부야~':'Dat is een pareer! Timing is alles~',
'화염엔 빙결! 암전엔 암흑! 기억해!':'Vuur slaat Ijs! Bliksem slaat Donker! Onthoud!',
'...얼어붙은 놈은 오래 안 간다.':'...Bevroren vijanden houden het niet lang uit.',
'얼었어! 빙결 중 1.5배야!':'Bevroren! 1,5x schade terwijl bevroren!',
'...힘을 골라라. 전부 가질 순 없다.':'...Kies je kracht. Je kunt niet alles hebben.',
'스탯을 올려. 살고 싶으면.':'Verhoog je stats. Als je wilt leven.',
'좋은 장비는 강화해야 진짜 힘을 발휘해!':'Goede uitrusting heeft verbeteringen nodig voor echt potentieel!',
'...슬롯을 채워. 빈 손은 죽음이다.':'...Vul je sleuven. Lege handen betekenen dood.',
'Z 누르면 대박! 쿨타임 길어서 타이밍 봐야 해!':'Druk Z voor enorme schade! Lange herlaadtijd, kies het moment!',
'Ctrl. 위기에 쓸 카드가 하나 늘었군.':'Ctrl. Nog een kaart voor noodgevallen.',
'스킬이 많아졌네~ L로 어디에 뭘 넣을지 골라!':'Zoveel vaardigheden~ Gebruik L om toe te wijzen!',
'...버리기 아까운 건 창고에.':'...Sla op wat te goed is om te droppen.',
'...살아남은 것만으로도 대단하군. 설정을 확인해.':'...Alleen overleven is al indrukwekkend. Controleer de instellingen.',
// --- System Messages ---
'MP 부족!':'Niet genoeg MP!','ST 부족!':'Niet genoeg ST!','악의 부족!':'Niet genoeg Kwaad!',
'충전 중...':'Opladen...','캔슬':'Annuleren','아이템 선택 필요':'Selecteer een item',
'악의 소진...':'Kwaad uitgeput...','비문 발견...':'Inscriptie gevonden...',
'HP물약!':'HP Drankje!','HP물약 +1':'HP Drankje +1','HP물약 +2':'HP Drankje +2',
'HP/MP/ST 회복!':'HP/MP/ST Hersteld!','보물상자 개봉!':'Kist Geopend!',
'익사!':'Verdrinkt!','피웅덩이!':'Bloedplas!','독혈!':'Giftig Bloed!','잡힘!':'Gegrepen!',
'콤보 종료':'Combo Einde',
// --- Status Effects ---
'빙결!':'Bevroren!','화상!':'Brandend!','독!':'Vergif!','감전!':'Geschokt!',
'기절!':'Verdoofd!','봉인됨!':'Verzegeld!','관통!':'Doorboord!',
// --- Skill Names ---
'기검참':'Ki Slash','악의구':'Kwaadbol','회전참':'Wervelwind','기폭팔':'Detoneer',
'칼등 처내기':'Kling Pareer','만화방창':'Naaldbestorming','멸살광선':'Vernietigingsstraal',
'원소추적탄':'Elementzoeker','악의 보호자':'Kwaadwachter','악의 사냥':'Kwaadjacht',
'폭풍소환':'Wervelwindoproep','해골무덤':'Botgraf','신성폭발':'Heilige Explosie',
'블랙':'Zwarte Ster','용암소환':'Lava Oproep','처형':'Executie','악마화 부활':'Demon Herrijzenis',
'붉은꽃':'Karmijnbloei','얼음보주':'IJsbol','뇌전걸음':'Geestenstap',
'만화방창 II':'Naaldbestorming II','마력연사':'Magische Beschieting','마력광선':'Magische Laser','업화선':'Helstraal',
'지옥진':'Inferno Formatie','폭독칼날':'Pestkling','악의폭풍':'Kwaaadstorm',
'악의기둥':'Donkere Zuil','회복의 영역':'Heilig Domein','구속의 영역':'Bindend Domein',
'아이스스톰':'IJsstorm','대왕치기':'Reuzenslag','대왕치기 2':'Reuzenslag II',
'기동불꽃':'Kettenvlam','기동파괴':'Kettenvernieling','기동칼날개':'Kettenvleugelkling',
'평화의보호':'Vredes Schild','참회':'Berouw','칼등날개':'Schild Vleugel',
'폭산탄':'Explosieve Schot','파쇄의 영역':'Verbrijzelingsdomein','침식의 영역':'Erosiedomein',
'관통의 영역':'Doorboordomein','부활의 영역':'Herrijzenisdomein','가시덫':'Stekelval',
'푸른비':'Azuurblauwe Regen','버스트루프':'Uitbarstingslus','유령 허수아비':'Fantoom Lokvogel','폭발 허수아비':'Explosieve Lokvogel',
'공성쇠뇌':'Belegeringsarmborst','사슬기동:충돌':'Kettendash: Inslag',
'사슬기동:화염':'Kettendash: Vlam','전격이동':'Bliksemdash',
// --- Skill Activation ---
'기동칼날개!':'Vleugelkling!','기동불꽃!':'Kettenvlam!','기동파괴!':'Kettenvernieling!',
'사슬이동:강화!':'Kettendash!','사슬기동:화염!':'Kettenvlam!',
'작살!':'Harpoen!','진입!':'Invoer!','레인라이트닝!':'Regenbliksem!',
'마력연사!':'Magische Beschieting!','🔷 마력광선!':'🔷 Magische Laser!','광선 해제':'Laser Uit','MP 부족 — 광선 해제':'MP leeg — Laser Uit','집중...':'Focus...','시전...':'Gieten...',
'만화방창!':'Naaldbestorming!','바늘출!':'Naalduitbarsting!','칼날!':'Kling!',
'착지!':'Landen!','체간삭감!':'Houding Breuk!',
'기동전폭 준비!':'Kettenexplosie Klaar!','기동불꽃 준비!':'Kettenvlam Klaar!',
'기동파괴 준비!':'Kettenvernieling Klaar!',
'유령불꽃 ON':'Geestenvlam AAN','유령불꽃 OFF':'Geestenvlam UIT',
'기동칼날개 AUTO ON':'Vleugelkling AUTO AAN','기동칼날개 AUTO OFF':'Vleugelkling AUTO UIT',
'자동 버스트!':'Auto Uitbarsting!','연사 해제':'Snelvuur Uit',
'당기기 모드':'Trkmodus','밀어내기 모드':'Duwmodus',
// --- Skill Slot Tooltips ---
'날개치기':'Vleugelslag','처내기':'Pareer',
'Shift: 작살 발사 → 끌려감':'Shift: Harpoen gooien → meegezogen',
'Shift: 화염길+화상':'Shift: Vlamspoor+brandwond',
'CT: 전류변신+뇌전걸음 (쿨4초)':'CT: Bliksemvorm+Geestenstap (CD 4s)',
'CT: 방어구체+빙결 (재입력: 파쇄)':'CT: IJsbol+bevriezing (herdruk: verbrijzeling)',
// --- HUD ---
'근접':'Nabij','견갑':'Schild','작살':'Harpoen','마법':'Magie','보막':'Schild','유령':'Geest',
'스킬':'Vaardigheden','대장':'Smidse','인벤':'Inv',
// --- Menu ---
'인벤토리':'Inventaris','복수의 대장간':'Smidse van Wraak','패시브 스킬':'Passieve Vaardigheden',
'전투 스킬':'Gevechtsvaardigheden','캐릭터 선택':'Karakter Selectie',
// --- Elements ---
'물리':'Fysiek','화염':'Vuur','빙결':'Ijs','암흑':'Donker','암전':'Bliksem','신성':'Heilig','대지':'Aarde',
// --- Passives ---
'힘':'Kracht','민첩':'Behendigheid','지능':'Intelligentie','행운':'Geluk',
'맹공':'Aanval','철벽':'Bolwerk','돌파':'Doorbraak','반격':'Tegenaanval',
'마력폭주':'Magische Uitbarsting','정밀사격':'Precisie Schot','수호':'Bescherming','수호신':'Beschermgeest',
'회복력':'Herstel','급소':'Vitale Slag','약탈':'Plundering','관통':'Penetratie',
'마력회복':'Mana Herstel','쇠뇌력':'Armborst Meesterschap','광전사':'Berserker','추적자':'Spoorzoeker',
'물리관통':'Fysieke Pen.','마법관통':'Magische Pen.',
// --- Weapons (Tier 0) ---
'녹슨 대검':'Roestig Grootzwaard','강철 대검':'Stalen Grootzwaard','흑요석 대검':'Obsidiaan Grootzwaard',
'낡은 석궁':'Versleten Armborst','강철 석궁':'Stalen Armborst','흑요석 석궁':'Obsidiaan Armborst',
'대검':'Grootzwaard','석궁':'Armborst','연사석궁':'Repeteerarmborst','마력석궁':'Magische Armborst',
// --- Misc ---
'악의 추출':'Kwaad Extractie','악의':'Kwaad','필살기':'Ultiem','필살기 해제':'Ultiem Leeg',
'이전':'Overdragen','강화':'Versterken','개봉!':'Geopend!',
'여신의 가호':'Zegen van de Godin',
'과부하!':'Overbelast!',
// --- Affix Names ---
'맹독의':'Giftig','불꽃의':'Vlammend','냉기의':'Bevriezend','번개의':'Elektrisch','암흑의':'Vervloekt',
'관통의':'Doorboorend','광폭의':'Woest','파쇄의':'Verbrijzelend','연쇄의':'Kettend',
'학살의':'Slagend','폭발의':'Explosief','집중의':'Gefocust','쾌속의':'Snel','패리의':'Paterend',
'추적자의':"Spoorzoeker's",'작살의':'Harpoen','궁극의':'Opperste','집중력의':'Aandachtig',
'강인의':'Stoer','수호의':'Bewakend','활력의':'Vitaal','신속의':'Gehaast',
'화염수호':'Vuurwacht','빙결수호':'IJswacht','암전수호':'Bliksemwacht','암흑수호':'Donkerwacht','독수호':'Gifwacht','전원소수호':'Alwacht',
'강철의':'Ijzersterk','반사의':'Reflecterend','가시의':'Doornig','흡수의':'Absorberend','인내의':'Volhardend',
'위기의':'Wanhopig','피격반격의':'Vergeldend',
'패링폭발의':'Pareerexplosie','스태거폭발의':'Staggerexplosie','원소전환의':'Omzetter','정화의':'Zuiverend',
'불굴의':'Onverzettelijk','부활의':'Herrijzend',
'약탈의':'Plunderend','경험의':'Ervaren','골드의':'Gouden','포션강화의':'Krachtig','사슬의':'Geketend',
'진혼의':'Heiligend','윤회의':'Cyclisch',
'생명력의':'Levenskrachtig','재생의':'Herstellend','치유의':'Genezend',
'마력의':'Magisch','절약의':'Efficiënt','영혼의':'Zielgebonden',
'예리한':'Scherp','맹렬한':'Bruut','파멸의':'Verderfelijk',
// --- Settings UI ---
'게임 설정':'Spelinstellingen','화면 흔들림':'Schermschudding','파티클 양':'Deeltjeshoeveelheid',
'효과음 볼륨':'Geluidseffect Volume','음악 볼륨':'Muziek Volume','난이도':'Moeilijkheid',
'자동 물약':'Auto Drankje','최소 줍기 등급':'Min Ophaal Rang','최소 줍기 티어':'Min Ophaal Tier',
'FPS 제한':'FPS Limiet','해상도 스케일':'Resolutieschaal','펫 자동수거':'Huisdier Auto-Verzamelen',
'화면 설정':'Weergave-instellingen','화면 모드':'Weergavemodus','보스 AI 디버그':'Baas AI Debug',
'유령불꽃 크기':'Geestenvlam Grootte','화면 명암':'Helderheid','유령 글로우':'Geest Gloed',
'기동:칼날개 AUTO':'Vleugelkling AUTO',
'일반':'Normaal','어려움':'Moeilijk','지옥':'Hel','이상':'of hoger','사용 안 함':'Uitgeschakeld',
'창 모드':'Venster','보더리스':'Randloos','전체화면':'Volledig scherm',
'설정':'Instellingen','조작 키 설정 (클릭하여 변경)':'Toetsbinding (Klik om te wijzigen)',
// --- Key Guide ---
'좌클릭 무기 공격':'LMB Wapenanval','우클릭 탭 칼등 처내기':'RMB Tik Klingpareer',
'우클릭 홀드 연속 처내기':'RMB Houd Continu Pareer','SHIFT 작살 발사':'SHIFT Harpoenlancering',
'이동':'Bewegen','아이템 줍기':'Item Oprapen','능력치 (스탯/패시브)':'Stats (Stats/Passieven)',
// --- Forge ---
'복수의 대장간':'Smidse van Wraak','강화':'Versterken','분해':'Ontmantelen','제작':'Maken',
// --- Death Screen ---
'사망':'Dood','부활':'Herleving','로비로':'Naar Lobby',
// --- Inventory/Storage ---
'가방에 공간이 없습니다!':'Geen ruimte in tas!','가방이 가득 찼습니다!':'Tas is vol!',
'창고가 가득 찼습니다!':'Opslag is vol!','퀵슬롯이 가득 찼습니다!':'Snelsleuf is vol!',
'결정 주머니가 가득 찼습니다!':'Kristalzak is vol!','결정 주머니 가득!':'Kristalzak vol!',
'악의가 부족합니다!':'Niet genoeg Kwaad!','가방이 비어있습니다':'Tas is leeg',
'창고가 비어있습니다':'Opslag is leeg','비어있음':'Leeg','어픽스 없음':'Geen affix',
'장착!':'Uitgerust!','해제':'Uitgerust verwijderd','보관':'Opslaan','꺼내기':'Opnemen',
'현재 장착':'Momenteel uitgerust','없음 — 제작하세요!':'Geen — Maak er een!',
'리셋할 포인트가 없습니다':'Geen punten om te resetten',
'키 설정 초기화 완료':'Toetsinstellingen gereset',
// --- Forge/Craft ---
'제작 확률':'Maakkans','제작 비용':'Maakkosten','보유 악의':'Kwaad in bezit',
// --- Canvas UI ---
'보스방':'Baasverdediging','안식처':'Heiligdom','회복':'Herstel','점화':'Aansteken',
'비석':'Steen','읽기':'Lezen','파괴':'Vernielen','제단':'Altaar','기원':'Bidden',
'잔해':'Puin','열기':'Openen','문지기':'Poortwachter',
'부활 판정 중...':'Herrijzenis beoordelen...','기폭 준비!':'Detoneer Klaar!',
'탈출':'Ontsnappen','연타':'Rammen',
'추적암전':'Bliksemvolgend','만화방창':'Luminantiestraal','최종 마법':'Finale Magie',
'감시중':'Bewaken','대기':'Standby','작동중':'Actief','설치 가능':'Kan installeren',
'균열 임박!':'Barst nakend!','흡수 중...':'Absorberen...',
'흡수 완료 — 재입력으로 회수':'Klaar — herdruk om op te nemen',
'화상':'Brandwond','당기기':'Trekken','밀어내기':'Duwen',
'단계':'tier','단':'tier',
// --- Skill Panel ---
'습득!':'Geleerd!','리셋!':'Gereset!','세팅!':'Ingesteld!','회수':'Terugroepen',
'합체 해제':'Fusie opheffen','리셋':'Resetten','환불':'Terugbetalen',
'파트너 클릭!':'Klik partner!','SP부족!':'SP nodig!',
'같은 보석 스킬 습득 시 합체 가능':'Kan fuseren bij gelijk juweel vaardigheid',
'펼쳐서 초기화':'Uitvouwen om te resetten','슬롯:':'Sleuf:',
// --- Stats ---
'남은 SP':'SP Resterend','처치':'Kills','경험치':'EXP','최대콤보':'Max Combo',
'맞아서 사망':'Gestorven door aanval','레벨':'Niveau','최대HP':'Max HP',
// --- Enemy Names ---
'방랑 기사':'Zwervende Ridder','보물 악마':'Schattendemon','거울의 사도':'Spiegelapostel',
'상인 악마':'Koopmansdemon','사슬의 죄수':'Geketende Gevangene','시간의 사도':'Tijdsapostel',
'탐욕의 사도':'Gierigheidsapostel','저주받은 쌍둥이':'Vervloekte Tweeling','차원 균열체':'Dimensionale Barst',
'죽음 그 자체':'Dood Zelf',
// --- Crystals ---
'HP결정':'HP Kristal','ST결정':'ST Kristal','MP결정':'MP Kristal',
'ATK결정':'ATK Kristal','DEF결정':'DEF Kristal','속도결정':'Snelheidskristal',
'크리결정':'Krit Kristal','치명결정':'KritSchade Kristal','화염결정':'Vuurkristal',
'냉기결정':'IJskristal','암흑결정':'Donkerkristal','번개결정':'Bliksemkristal',
'신성결정':'Heilig Kristal','생명결정':'Levenskristal','기력결정':'Uithoudings Kristal',
'마력결정':'Mana Kristal','행운결정':'Gelukskristal',
'조각':'Fragment','파편':'Scherf','순수결정':'Puur Kristal','완전결정':'Perfect Kristal',
'결정 주머니':'Kristalzak','결정이 없습니다':'Geen kristallen','가루':'Stof',
'전체':'Alles','스탯':'Stat','원소':'Elem','유틸':'Util',
'현재':'Huidig','최대 강화 달성 (+20)':'Max versterkt (+20)','강화 시':'Na versterking',
'강화':'Versterken','합성':'Synthetiseren','제작':'Maken',
'같은 종류·같은 성급 결정 3개 → 1성급 상승 (강화 리셋)':'3 kristallen van zelfde type & rang → 1 rang hoger (versterking gereset)',
'합성 가능한 결정이 없습니다 (같은 종류·성급 3개 필요)':'Geen kristallen om te synthetiseren (3 van zelfde type & rang nodig)',
'결정 분해 → 결정 가루':'Kristal Ontmantelen → Kristalstof',
'분해할 결정이 없습니다':'Geen kristallen om te ontmantelen',
'결정 제작 (가루 → 결정)':'Kristal Maken (Stof → Kristal)',
'탈착':'Loskoppelen','빈 슬롯':'Lege sleuf',
'결정 선택 후 클릭':'Selecteer kristal dan klik','클릭하여 선택결정 장착':'Klik om geselecteerd kristal uit te rusten',
'획득!':'Verkregen!','제작!':'Gemaakt!','합성!':'Gesynthetiseerd!','최상위 일괄합성':'Bulk Synth naar Top','일괄합성 완료':'Bulk synth klaar',
// --- Stage Names ---
'벌레굴':'Wormennest','얼음굴':'IJsgrot','고통의 화염지대':'Infernale Vlakte',
'지옥의 군단':'Hellegioen','사도의 마굴':'Apostelhol','지옥성':'Helburcht',
// --- Misc ---
'엑소듀서 전사':'Exoduser Krijger','포이즈':'Houding',
'신성폭발':'Heilige Explosie','뇌전걸음':'Geestenstap',
'지옥창고':'Helopslag','선택분해':'Selectieve Ontmanteling','쓰레기':'Rommel',
'복구 불가!':'Kan niet herstellen!','중요잠금':'Belangrijk-vergrendeld',
// --- Phase 9 additions ---
'획득!':'Verkregen!','자동 장착!':'Auto-uitgerust!','분해! 가루 +':'Ontmanteld! Stof +',
'추적암전':'Bliksemvolgend','암전':'Bliksem',
'평화보호':'Schild','지진폭풍':'Aardbevingstorm','회전기폭':'Wervel-Det',
'공격':'Aanval','보호막':'Schild','필살기':'Ultiem',
'합체 스킬로 통합됨':'Samengevoegd in gefuseerde vaardigheid','얼음보주 안에선 사용 불가!':'Kan niet gebruiken in IJsbol!',
'Shift+키로 폭파':'Shift+toets om te detoneren','취소':'Annuleren','충전 중...':'Opladen...',
'쿨다운 중...':'Herladen...','시전 중...':'Gieten...','악의 부족!':'Niet genoeg Kwaad!',
'악의 부족! (12)':'Niet genoeg Kwaad! (12)','악의 부족! (15)':'Niet genoeg Kwaad! (15)',
'악의 부족! (20)':'Niet genoeg Kwaad! (20)','악의 부족! (10)':'Niet genoeg Kwaad! (10)',
'ST 부족!':'Niet genoeg ST!','HP 부족!':'Niet genoeg HP!',
'필살기 슬롯 클릭하여 배정!':'Klik ultimatief sleuf om toe te wijzen!',
'필살기 스킬을 습득하세요':'Leer een ultimatieve vaardigheid',
'우클릭(칼등치기)에 합체됨':'Samengevoegd in RMB (klingpareer)',
'T(석궁자동)에 세팅하세요':'Stel in op T (auto armborst)',
'공성쇠뇌 철거 → 이동식':'Belegeringsarmborst afgebroken → draagbaar',
'ST 부족! (100)':'Niet genoeg ST! (100)',
'HP 99% 이상!':'HP 99%+!','그로기 보스 없음!':'Geen verdoofde baas!',
'이미 폭풍 지역!':'Al in storrngebied!','이미 빙풍 지역!':'Al in ijsstormgebied!',
'💎 푸른비 해금!':'💎 Azuurblauwe Regen ontgrendeld!','💫 버스트루프 해금!':'💫 Uitbarstingslus ontgrendeld!',
'👻 유령 허수아비 해금!':'👻 Fantoom Lokvogel ontgrendeld!',
'쿨 ':'CD ','과부하 ':'Overbelast ',
'🕊️💎 블루콩!':'🕊️💎 Blauwe Boon!','🛡️💎 빨콩→블루콩!':'🛡️💎 Rood→Blauwe Boon!',
'🛡️💎 무지개→블루콩!':'🛡️💎 Regenboog→Blauwe Boon!',
'레어':'Zeldzaam','슬롯':'Sleuf',
'성공률':'Slagingskans','AI 자동 강화':'AI Auto-Versterken','최대 강화 달성!':'Max versterking bereikt!',
'최대 강화':'Max versterkt','회복량':'Herstelhoeveelheid','현재 장착':'Momenteel uitgerust',
'없음 — 제작하세요!':'Geen — Maak er een!','제작 확률':'Maakkans',
'분해할 아이템이 없습니다.':'Geen items om te ontmantelen.','🔨 제작':'🔨 Maken',
'체간':'Houding','아이템에 마우스를 올리거나 좌클릭으로 선택하세요':'Beweeg de muis over een item of linksklik om te selecteren',
// --- Phase 10: death/levelup/intro screen ---
'중독':'Vergiftiging','지뢰':'Mijn','함정':'Val','산호가시':'Koraalstekel',
'투사체':'Projectiel','도트':'DoT','레어몹':'Zeldzame Mob',
'처치':'kills','경험치':'EXP','최대콤보':'Max Combo',
'구역':'Zone','가시!':'Stekel!',
// --- Hell circle / palette names ---
'림보':'Limbo','색욕':'Wellust','탐식':'Gulzigheid','탐욕':'Hebzucht','분노':'Woede','이단':'Ketterij','폭력':'Geweld',
'분노!':'Razernij!','탐욕!':'Hebzucht!','💀 분노 폭발!':'💀 Razernij Uitbarsting!','심연의 분노!':'Afgrond Razernij!','쌍둥이의 분노!':'Tweeling Razernij!',
// --- HUD / misc ---
'소환굴':'Spawngat',
'레어':'Zeldzaam','처치!':'Verslagen!','왕관 착용':'Kroon Aan','왕관 해제':'Kroon Uit',
'맨손':'Blote Handen','없음':'Geen','갑옷':'Pantser','부츠':'Laarzen',
// --- Elite / Mod / Aura ---
'매직':'Magisch','챔피언':'Kampioen',
'빙결':'Bevroren','초속':'Haast','강타':'Slag','재생':'Herstel','맹독':'Vergif','소환':'Oproep',
'기생':'Parasiet','분열':'Splitsing','용암자취':'Lavaspoor','사망폭발':'Doodsexplosie',
'화염사슬':'Vuurketting','광전':'Razernij','텔레포트':'Teleportatie','보호막':'Barrière',
'소용돌이':'Wervelwind','환영':'Fantoom','전격반사':'Schokterugkaatsing','감전':'Elektrificeren',
'낙뢰':'Donder','연쇄전격':'Kettingbliksem','동료불사':'Bondgenoot Onsterfelijk',
'영혼포식':'Zielverslinder','시간왜곡':'Tijdvervorming','혼돈변이':'Chaosmutatie',
'복수자':'Wreker','마법보초':'Magische Schildwacht','환영술사':'Illusionist',
'함성':'Oorlogskreet','치유':'Genezen','신속':'Snelheid','수호':'Beschermer',
// --- Character ---
'다크 판타지 전사. 거대검+검은 갑옷':'Donker fantasie krijger. Grootzwaard + Zwart pantser',
// --- Phase 11: missing addTxt/showPH/notify translations ---
'⚡ 사슬이동:강화!':'⚡ Ketting:Versterkt!',
'⚡ 사슬기동:화염!':'⚡ Kettendrive: Vlam!',
'달성!':'Bereikt!',
'ST':'ST','부족!':'Onvoldoende!',
'타':'Treffer',
'🌀 당기기 모드':'🌀 Trkmodus',
'💥 밀어내기 모드':'💥 Duwmodus',
'🕊️빨콩 흡수':'🕊️Rode boon absorberen',
'🕊️흡수':'🕊️Absorberen',
'💎유도 폭발!':'💎Geleid explosie!',
'💥반사 폭발!':'💥Terugkaats explosie!',
'⚡⚡ 참회 귀환!':'⚡⚡ Berouw Terugkeer!',
'⚡ 참회!':'⚡ Berouw!',
'파도!':'Golf!',
'암전!':'Bliksem!',
'암흑!':'Donker!',
'암흑창!':'Donkerspeer!',
'빛창!':'Lichtspeer!',
'체 소환!':'opgeroepen!',
'개 설치!':'geplaatst!',
'💥 보스 그로기!':'💥 Baas Verdoofd!',
'💥 그로기!':'💥 Verdoofd!',
'보상':'Bonus',
'⚡ 암전나선!':'⚡ Bliksemspiraal!',
'🌋 지진폭풍!':'🌋 Aardbevingstorm!',
'SP슬롯':'SP Sleuf',
'F슬롯':'F Sleuf',
'⚔🩸 독혈해방!':'⚔🩸 Pestbloedvrijmaking!',
'⚔ 칼날 해방!':'⚔ Klingvrijmaking!',
'🔨🌋 지옥강타!':'🔨🌋 Helslag!',
'🔨 대왕치기!':'🔨 Reuzenslag!',
'✟ 결계의 영역!':'✟ Bewakingsdomein!','✟ 물의 영역!':'✟ Waterdomein!','✟ 파쇄의 영역!':'✟ Verbrijzelingsdomein!','✟ 침식의 영역!':'✟ Erosiedomein!','✟ 관통의 영역!':'✟ Doorboordomein!','✟ 권능의 영역!':'✟ Soevereindomein!',
'🛡 회복의 영역!':'🛡 Heilig Domein!',
'임계...!':'Kritisch...!',
'기폭팔!':'Detoneer!','강제기폭!':'Geforceerde Detonatie!','자동기폭!':'Auto Detonatie!',
'회전기폭!':'Wervel Detonatie!','해제기폭!':'Vrijgave Detonatie!','지진기폭!':'Aardbeving Detonatie!',
'혼돈의 왕관':'Kroon van Chaos',
'전지전능의 왕관':'Kroon van Alwetendheid',
'악마의 팔찌':'Demonenarmband',
'생명의 팔찌':'Levensarmband',
// --- wave direction names ---
'🌊 위→아래 파도!':'🌊 Boven→Onder Golf!','🌊 오른→왼 파도!':'🌊 Rechts→Links Golf!',
'🌊 아래→위 파도!':'🌊 Onder→Boven Golf!','🌊 왼→오른 파도!':'🌊 Links→Rechts Golf!',
// --- Phase 12 ---
'⚡ 사슬이동:강화!':'⚡ Ketting:Versterkt!','⚡ 사슬기동:화염!':'⚡ Kettendrive: Vlam!',
'🌀 당기기 모드':'🌀 Trkmodus','💥 밀어내기 모드':'💥 Duwmodus',
'💎유도 폭발!':'💎Geleid Explosie!','💥반사 폭발!':'💥Terugkaats Explosie!',
'⚡⚡ 참회 귀환!':'⚡⚡ Berouw Terugkeer!','⚡ 참회!':'⚡ Berouw!',
'암전!':'Bliksem!','암흑!':'Donker!','암흑창!':'Donkerspeer!','빛창!':'Lichtspeer!',
'💥 보스 그로기!':'💥 Baas Verdoofd!','💥 그로기!':'💥 Verdoofd!',
'⚡ 암전나선!':'⚡ Bliksemspiraal!','🌋 지진폭풍!':'🌋 Aardbevingstorm!',
'⚔🩸 독혈해방!':'⚔🩸 Pestbloedvrijmaking!','⚔ 칼날 해방!':'⚔ Klingvrijmaking!',
'🔨🌋 지옥강타!':'🔨🌋 Helslag!','🔨 대왕치기!':'🔨 Reuzenslag!',
'✟ 결계의 영역!':'✟ Bewakingsdomein!','✟ 물의 영역!':'✟ Waterdomein!','✟ 파쇄의 영역!':'✟ Verbrijzelingsdomein!','✟ 침식의 영역!':'✟ Erosiedomein!','✟ 관통의 영역!':'✟ Doorboordomein!','✟ 권능의 영역!':'✟ Soevereindomein!','🛡 회복의 영역!':'🛡 Heilig Domein!',
'파도!':'Golf!',
// --- rare mob / special ---
'무적!':'Onsterfelijk!','🪞 반격!':'🪞 Tegenaanval!','💢 반격!':'💢 Tegenaanval!',
'흡수!':'Absorberen!','반격 발사!':'Tegenaanval Schot!',
'저주! 드랍률 -50%':'Vloek! Dropkans -50%','도망!':'Vluchten!',
'위상!':'Fase!','방어!':'Verdedigen!',
'회수 HP+':'Terugroepen HP+','이동식 복귀':'Draagbaar Terugkeer','캔슬':'Annuleren',
'약점!':'Zwakte!','저항!':'Weerstand!','관통!':'Doorboord!',
'유령불꽃 OFF':'Geestenvlam UIT','유령불꽃 ON':'Geestenvlam AAN',
'기동칼날개 AUTO ON':'Vleugelkling AUTO AAN','기동칼날개 AUTO OFF':'Vleugelkling AUTO UIT',
'콤보 종료: ':'Combo Einde: ','익사!':'Verdrinkt!',
'피웅덩이!':'Bloedplas!','독혈!':'Giftig Bloed!','비문 발견...':'Inscriptie gevonden...',
'보물상자 개봉!':'Kist Geopend!','악의 +':'Kwaad +','잡힘!':'Gegrepen!',
'저주 ':'Vloek ','충전 중...':'Opladen...','불발...':'Misschot...',
'작살 약점!':'Harpoen Zwakte!',
'전염 x':'Plaag x','흡수 완료!':'Absorptie Voltooid!',
'부활 성공!':'Herleving Geslaagd!','부활 실패...':'Herleving Mislukt...',
'산호가시':'Koraalstekel','가시!':'Stekel!','차원 이동!':'Dimensionale Verschuiving!','독!':'Vergif!',
'탈출!':'Ontsnapt!','기절 해제':'Verdoving Opgeheven',
'아이템 선택 필요':'Selecteer een item','악의 부족':'Niet genoeg Kwaad','악의 소진...':'Kwaad uitgeput...',
'스킬 미습득':'Geen vaardigheden geleerd','펼치기':'Uitvouwen','접기':'Samenvouwen',
'조건 미달!':' niet voldaan!','해제!':' Opgeheven!',
'슬롯':'Sleuf','자동 ON':' Auto AAN','자동 OFF':' Auto UIT','스킬 해제':' vaardigheid verwijderd',
'필살기':'Ultiem','필살기 해제':'Ultiem Leeg',
'연사 해제':'Snelvuur Uit',
'닫기':'Sluiten','장착 중':'Uitgerust','보관 아이템':'Opgeslagen Item',
// --- Phase 13: massive batch ---
'클릭으로 선택 · ESC로 닫기':'Klik om te selecteren · ESC om te sluiten',
'선택됨':'Geselecteerd',
'MP 부족!':'Niet genoeg MP!','악의 부족! (30)':'Niet genoeg Kwaad! (30)',
'MP 부족! (40)':'Niet genoeg MP! (40)','MP 부족! (100)':'Niet genoeg MP! (100)','MP 부족! (10)':'Niet genoeg MP! (10)',
'MP 부족! (':'Niet genoeg MP! (',
'✟ 시전...':'✟ Gieten...','🌋 시전...':'🌋 Gieten...','⛧ 시전...':'⛧ Gieten...',
'❄ 진입!':'❄ Invoer!',
'🔱 작살!':'🔱 Harpoen!',
'레벨 부족! (요구: Lv.':'Niveau te laag! (Vereist: Lv.',
' 장착!':' Uitgerust!',
'가방에 공간이 없습니다!':'Geen ruimte in tas!',
' 해제':' Verwijderd',
'👿 악의 추출: +':'👿 Kwaad Extractie: +',
'F 슬롯 해제':'F Sleuf verwijderd',
'💫 집중...':'💫 Focus...',
'⚡ 마력연사!':'⚡ Magische Beschieting!',
'❄빙결!':'❄Bevroren!','🟢독!':'🟢Vergif!','⚡감전!':'⚡Geschokt!','🔥화상!':'🔥Brandend!',
'✦ 여신의 가호 — SP+5 AP+3':'✦ Godinzegen — SP+5 AP+3',
'⚔ 기동칼날개!':'⚔ Vleugelkling!',
'🔥 화염관통!':'🔥 Vuurdoorboord!',
'🔱 관통!':'🔱 Doorboord!',
'⚔ 칼날!':'⚔ Kling!',
'💥 착지!':'💥 Landing!',
'💫 기절!':'💫 Verdoofd!',
'⚡ 체간삭감!':'⚡ Houdingbreuk!',
'⚡ 기동파괴! ':'⚡ Kettenvernieling! T',
'🔥 기동불꽃!':'🔥 Kettenvlam!',
'🔥 기동불꽃! ':'🔥 Kettenvlam! T',
'단계 ×':' x',
'⚡ 기동전폭! x':'⚡ Kettenexplosie! x',
'🔥🔥 3중폭!':'🔥🔥 Vlam x3!','🔥🔥🔥 6중폭!':'🔥🔥🔥 Vlam x6!','🔥🔥🔥🔥 9중폭!':'🔥🔥🔥🔥 Vlam x9!','💥 불꽃폭발! ':'💥 Vlam Detonatie! ',
'🔥 기동불꽃 준비!':'🔥 Kettenvlam Klaar!',
'🔨 기동파괴 준비!':'🔨 Kettenvernieling Klaar!',
'⚡ 기동전폭 준비!':'⚡ Kettenexplosie Klaar!',
'콤보 종료: ':'Combo Einde: ',
'중독':'Vergiftiging',
'⚡ 과부하! 5초':'⚡ Overbelast! 5s',
'💫 자동 버스트!':'💫 Auto Uitbarsting!',
'🔨 칼등날개!':'🔨 Schild Vleugel!',
'💥폭발!':'💥Explosie!',
'🛡️💎 유도반사!':'🛡️💎 Geleid Terugkaats!',
'⚡💎 블루콩!':'⚡💎 Blauwe Boon!',
'💎 블루콩!':'💎 Blauwe Boon!',
'⚡반사!':'⚡Terugkaats!',
'💎 푸른비 OFF':'💎 Azuurblauwe Regen UIT',
'💎 푸른비 ON!':'💎 Azuurblauwe Regen AAN!',
'🔥 지옥진!':'🔥 Inferno Formatie!',
'🔥 업화선!':'🔥 Helstraal!',
'✦ 평화 충격파! ':'✦ Vrede Schokgolf! ',
'⚡ 전류 방출!':'⚡ Stroom Vrijgave!',
'⚡⚡ 레인라이트닝!':'⚡⚡ Regenbliksem!',
'💫 광역!':'💫 Gebied!',
'🔥 불장판!':'🔥 Vuurzone!',
'💫 피니셔!':'💫 Afmaker!',
'☠ 지옥에서 귀환!':'☠ Terug uit de Hel!',
'☠ 완전 사망!':'☠ Permanente Dood!',
'⚔ 처형! ':'⚔ Executie! ',
'💥 지뢰!':'💥 Mijn!',
'⚠ 함정!':'⚠ Val!',
'❌ 우클릭으로! -':'❌ Gebruik RMB! -',
'❌ Q키로! -':'❌ Gebruik Q! -',
'💥무지개 폭발! ':'💥Regenboog Explosie! ',
'🛡️💎 블루콩!':'🛡️💎 Blauwe Boon!',
'⬜화이트볼!':'⬜Witte Bal!',
'✨💎 블루콩!':'✨💎 Blauwe Boon!',
'💜다크볼!':'💜Donkere Bal!',
'❄빙판!':'❄IJsvloer!',
'🌨빙결!':'🌨Bevroren!',
'🕸둔화!':'🕸Langzaam!',
'⚠트랩!':'⚠Val!',
'💀 역병 처형!':'💀 Pesteecutie!',
'💥 역병 Finale!':'💥 Pest Finale!',
'⚔ 균열 악마!':'⚔ Barst Demon!',
'자동회수 HP+':'Auto-Terugroepen HP+',
'MP 부족 — 연사 해제':'MP laag — Snelvuur Uit',
'MP 부족 — 푸른비 OFF':'MP laag — Azuurblauwe Regen UIT',
'🛡️반사!':'🛡️Terugkaats!',
'⚡🦴 참회 귀환!':'⚡🦴 Berouw Terugkeer!',
'🦴⚡해골번개!':'🦴⚡Botbliksem!',
'⚡악의폭풍!':'⚡Kwaaadstorm!',
'❄아이스스톰!':'❄IJsstorm!',
'⚡ 암전폭발!':'⚡ Bliksemexplosie!',
'⚡ 레인라이트닝! x':'⚡ Regenbliksem! x',
'❄ 탈출!':'❄ Ontsnappen!',
'⚡쉴드!':'⚡Schild!',
'❄🌪️ 얼음보주!':'❄🌪️ IJsbol!',
'🌪️ 전개!':'🌪️ Ontplooien!',
'❄ 빙결흡인!':'❄ Bevriezingszuig!',
'❄☄ 빙결폭발!':'❄☄ Bevriezingsexplosie!',
'☄️ 흡인!':'☄️ Zuig!',
'☄️ 대폭발!':'☄️ Mega Explosie!',
'❄ 얼음보주!':'❄ IJsbol!','⏳ 시간왜곡!':'⏳ Tijdvervorming!','쿨다운!':'Herladen!',
'❄ 파쇄!':'❄ Verbrijzelen!',
'☄️💥 대폭발!':'☄️💥 Mega Explosie!',
'반사!':'Terugkaats!',
// --- Phase 13: boss moves ---
'💀 도넛!':'💀 Donut!','💀 전멸!':'💀 Vernietiging!',
'🌊 파도!':'🌊 Golf!','속박!':'Binden!','반격!':'Tegenaanval!',
'분신!':'Kloon!','분신 파괴!':'Kloon Vernield!','무기 해방!':'Wapen Vrijmaking!',
'❄프리즌!':'❄Gevangenis!','⚡ 증표 ':'⚡ Markering ',
'흔들!':'Schudden!','⚠ 광역 발사!':'⚠ Gebied Vuur!',
'🔥 확산!':'🔥 Verspreiding!','⚠ 돌진!':'⚠ Aanval!',
'🦅 도약!':'🦅 Sprong!','⚡ 레이저!':'⚡ Laser!',
'🌊 충격파!':'🌊 Schokgolf!','👹 소환!':'👹 Oproepen!',
'☄ 유성우!':'☄ Meteorenregen!','🖐 잡기!':'🖐 Grijpen!',
'🌀 회전참!':'🌀 Wervelwind!','💣 지뢰!':'💣 Mijn!',
'🌀 흡인!':'🌀 Vacuüm!','🔴 빨간콩 폭풍!':'🔴 Rode Boon Storm!',
'🔴🔴 콩 비!':'🔴🔴 Boon Regen!',
'🌊 부채꼴 충격파!':'🌊 Waaier Schokgolf!',
'✴ 멸광 레이저!':'✴ Vernietigingslaser!',
'🔴 추적 장판!':'🔴 Volgzone!',
'💥 속성탄!':'💥 Elementaire Schot!',
'⚔ 검기!':'⚔ Zwaard Ki!','⚔ 재단참!':'⚔ Oogst Houw!',
'🌀 나선탄!':'🌀 Spiraalsschot!','⚠ 찌르기!':'⚠ Stoten!',
'🔥🔥 지옥기둥!':'🔥🔥 Helzuil!',
'⚔ 환영검!':'⚔ Fantoomzwaard!',
'💢 반격자세!':'💢 Tegenaanvalhouding!',
'⚔ 연격!':'⚔ Combo!','🌑 암흑!':'🌑 Duisternis!',
'👥 분신!':'👥 Kloon!','🌋 균열!':'🌋 Barst!',
'🌊 파동!':'🌊 Golf!','💣 추적지뢰!':'💣 Volgmijn!',
'⏪ 되감기!':'⏪ Terugspoelen!','🌀 중력장!':'🌀 Zwaartekrachtveld!',
'🔨 벽밀기!':'🔨 Muur Duw!','☠ 독안개!':'☠ Gifmist!',
'⛓ 감옥!':'⛓ Gevangenis!','⚡ 연쇄번개!':'⚡ Kettingbliksem!',
'🔮 궤도탄!':'🔮 Orbitaal Schot!','🛡 방패돌진!':'🛡 Schild Aanval!',
'🪞 반격자세!':'🪞 Tegenaanvalhouding!','⚓ 속박!':'⚓ Binden!',
'👤 분신!':'👤 Kloon!','🖐 탈취!':'🖐 Stelen!',
'🔥🔥 용암 지대!':'🔥🔥 Lavazone!',
'🌧🌧 화염 폭격!':'🌧🌧 Vuurbombardering!',
'⚡⚡ 전격 장막!':'⚡⚡ Bliksemgordijn!',
'💀 내 곁으로!':'💀 Kom naar mij!',
'⭕ 안전!':'⭕ Veilig!',
'💀💀 전멸 폭발!':'💀💀 Vernietigingsexplosie!',
'⚡ 쐐기 소멸!':'⚡ Wig Extinctie!',
'🌊충격파!':'🌊Schokgolf!',
'👿악의+100':'👿Kwaad+100',
'💥패링폭발!':'💥Pareerexplosie!',
'균열 충돌! ':'Barst Botsing! ',
'벽 충돌! ':'Muur Botsing! ',
'소환!':'Oproepen!','환영!':'Fantoom!',
'⚡낙뢰!':'⚡Donder!','⚡빔!':'⚡Straal!',
'환영술!':'Illusie!','💀소환!':'💀Oproepen!',
'🔮주술!':'🔮Vloek!','🩸산란!':'🩸Voortplanting!',
'💢광폭!':'💢Razernij!','🕷산란!':'🕷Voortplanting!',
'❄서리!':'❄Vorst!','❄빙결파!':'❄Bevriezingsgolf!',
'💀빙마!':'💀IJsdemon!',
// --- Phase 13: mob actions ---
'돌진!':'Aanval!','충격파!':'Schokgolf!','독안개!':'Gifmist!',
'연타!':'Salvo!','포효!':'Gebrul!','강화!':'Versterken!',
'꼬리!':'Staart!','은신...':'Sluipen...','기습!':'Hinderlaag!',
'산란!':'Voortplanting!','독가스!':'Gifgas!','소멸...':'Verdwijnen...',
'강타!':'Slag!','분비!':'Afscheiding!','채찍!':'Zweep!',
'출혈!':'Bloeden!','급강하!':'Duikvlucht!','방출!':'Ontlading!',
'충격!':'Impact!','치유!':'Genezen!','의식!':'Ritueel!',
'지옥불!':'Hellevuur!','끌려감!':'Meegetrokken!','혀!':'Tong!',
'응시!':'Staren!','낙하!':'Vallen!','핏방울!':'Bloeddruppel!',
'일어남!':'Opstaan!','휩쓸기!':'Vegen!','웅크림':'Hurken',
'뼈칼날!':'Botkling!','감속!':'Vertragen!','비명!':'Schreeuwen!',
'화산탄!':'Vulkaanschot!','자폭!':'Zelfvernietiging!','감싸기!':'Omhullen!',
'잡기!':'Grijpen!','내리찍기!':'Neerslagen!','브레스!':'Adem!',
'비행!':'Vluchten!','용암비!':'Lavaregen!','물뿜기!':'Waterstraal!',
'빛...':'Licht...','삼키기!':'Slikken!','마비!':'Verlammig!',
'방전!':'Ontlading!','집게찍기!':'Tang Slag!','찍기!':'Neerslagen!',
'붙잡기!':'Grijpen!','감아올리기!':'Oprollen!','파편!':'Fragment!',
'할퀴기!':'Krabben!','기생충!':'Parasiet!',
'심연 해방!':'Afgrond Vrijmaking!','촉수난타!':'Tentakel Bestorming!',
'삼지창!':'Drietand!','소용돌이!':'Wervelwind!','해일!':'Tsunami!',
'끼걱!':'Kraak!','폭발!':'Explosie!','체인!':'Ketting!',
'갈기!':'Manen!','공포!':'Terror!','흡혈!':'Drinken!',
'베기!':'Hakken!','비이이명!!':'Riiing!!','분열!':'Splitsen!',
'3연참!':'Drievoudige Houw!','패링!':'Pareren!',
'...복사...':'...Kopiëren...','불균형...저주!':'Onbalans...Vloek!',
'저주!':'Vloek!','균형...강화!':'Balans...Versterken!',
'심판의 기둥!':'Zuil van Oordeel!','처형 선고!':'Doodvonnis!',
'고통의 해방!':'Pijnvrijmaking!','너도 느껴봐라!':'Voel dit ook!',
'대검난무!':'Grootzwaard Razernij!','촉수!':'Tentakel!',
'전방위 빔!':'Omni-Straal!','회피!':'Ontwijken!',
// --- Phase 13: rare mob / merchant ---
'[F] 상점':'[F] Winkel','거래 성공!':'Handel Geslaagd!',
'악의 부족! (':'Niet genoeg Kwaad! (',
'상인이 떠납니다...':'De koopman vertrekt...',
'사슬 해방!':'Ketting Vrijmaking!','완전 해방!':'Volledige Vrijmaking!',
'⏪ 시간 되감기!':'⏪ Tijd Terugspoelen!','전환!':'Wisselen!',
'부활 ':'Herleving ','🌀균열!':'🌀Barst!','...사라짐':'...Verdwenen',
'낫 베기!':'Zeis Hak!','☠ 죽음의 선고!':'☠ Doodvonnis!',
'선고 집행...':'Vonnis uitvoeren...',
'⚡패링!':'⚡Pareren!','경직!':'Stagger!',
'⚠ 잡혔다!':'⚠ Gegrepen!','💥 내던지기!':'💥 Gooien!',
'💥 소용돌이 폭발!':'💥 Wervelwind Explosie!',
'👻 순간이동!':'👻 Teleportatie!','💫 기절! 5초':'💫 Verdoofd! 5s',
'찌르기 반격!':'Stoot Tegenaanval!','💢 폭발!':'💢 Explosie!',
'반격 실패':'Tegenaanval Mislukt','탈취 반격!':'Stelen Tegenaanval!',
'무기 봉인!':'Wapen Afdichting!','냠!':'Nom!',
// --- Phase 13: stage/room/map ---
'합체!':'Gefuseerd!','출구가 열렸다!':'Uitgang geopend!',
'보물상자 출현!':'Schatkist verschenen!','출구':'Uitgang',
'⚠ 문지기가 살아있다!':'⚠ Poortwachter nog levend!',
'⏱ 타임어택 ':'⏱ Tijdaanval ',
'처치율 ':'Killratio ',
'무적!':'Onsterfelijk!','불사 보호':'Onsterfelijke Bescherming',
'빙결!':'Bevroren!','환영 소멸!':'Fantoom Verdwenen!',
'부활력 ':'Herrijzeniskracht ',
'✟ 신성력 억제! (':'✟ Heilige Onderdrukking! (',
'부활 실패 (':'Herleving Mislukt (',
'⚡순간이동!':'⚡Teleportatie!',
'👻 동반부활!':'👻 Mede-Herleving!',
'✟ 신성력 억제!':'✟ Heilige Onderdrukking!',
'💀 부활 판정 중...':'💀 Herrijzenis beoordelen...',
'⚔ 문지기 처치!':'⚔ Poortwachter Verslagen!',
'🚪 보스방 개방!':'🚪 Baasverdediging Geopend!',
'잔해 출현!':'Puin verschenen!',
'🌀균열 발생!':'🌀Barst geopend!',
'🔥복수!':'🔥Wraak!','💥폭독혈!':'💥Pestbloed!',
'빙판!':'IJsvloer!','❄빙결파!':'❄Bevriezingsgolf!',
'❄최종빙결!':'❄Finale Bevriezing!','빙마 처치!':'IJsdemon Verslagen!',
'분리!':'Scheiden!','뼈 파편!':'Bot Fragment!',
'태아 처치!':'Foetus Verslagen!','지배자 처치!':'Heerser Verslagen!',
'용암!':'Lava!','화룡 처치!':'Vuurdraken Verslagen!',
'최후의 비명!':'Laatste Schreeuw!','산화...':'Oxideren...',
'심판자 처치!':'Rechter Verslagen!','고통의 왕 처치!':'Pijnkoning Verslagen!',
'수역!':'Water!','파편 폭발!':'Fragment Explosie!',
'거대어 처치!':'Leviathan Verslagen!','대사도 처치!':'Hoge Apostel Verslagen!',
'독웅덩이!':'Gifplas!','화염장판!':'Vuurzone!','전기장!':'Elektrisch Veld!',
'무기 드롭!':'Wapen Drop!','보물 발견!':'Schat Gevonden!',
'상인의 주머니 +':'Koopmanszak +',
'속박의 파편!':'Bindingscherf!','시간의 조각!':'Tijdfragment!',
'저주 해제!':'Vloek Opgeheven!','차원의 결정!':'Dimensionaal Kristal!',
'전설 아이템!':'Legendarisch Item!','죽음을 이겨냈다!':'Dood Overwonnen!',
'💥대폭발!':'💥Mega Explosie!','⚡강화!':'⚡Versterken!',
// --- Phase 13: combat/defense ---
'장비 ':'Uitrusting ',
'💫 진동!':'💫 Trilling!','❄ 무적!':'❄ Onsterfelijk!',
'\u{1F47B} 유령!':'\u{1F47B} Geest!',
'집중 해제!':'Focus Annuleren!','집중!':'Focus!',
'🕊️ 평화보호 ':'🕊️ Vredes Schild ',
'🛡 보호막 ':'🛡 Schild ',
'🌀 회전보호막 ':'🌀 Draai Schild ',
'💥한방캡!':'💥Eén-Slag Limiet!',
'⚡쉴드 파괴!':'⚡Schild Vernieling!',
'💀 불굴!':'💀 Onverzettelijk!',
'💀 1회부활!':'💀 1-Leven Herleving!',
'감시 회수':'Wacht Terugroepen',
'악마화 부활!':'Demon Herleving!',
// --- Phase 13: skill panel ---
'기검참':'Ki Slash','날개치기':'Vleugelslag',
'배정 가능한 스킬 없음':'Geen vaardigheden om toe te wijzen',
'칼날 없음!':'Geen Kling!',
'⚔ 악의사냥!':'⚔ Kwaadjacht!',
'❄🌪️ 얼음소용돌이!':'❄🌪️ IJswervelwind!',
'🌪️ 폭풍소환!':'🌪️ Wervelwindoproep!',
'\u{1F9B4} 해골무덤!':'\u{1F9B4} Botgraf!',
'🌹 붉은꽃!':'🌹 Karmijnbloei!',
'💥 폭산탄!':'💥 Explosieve Schot!',
'🪡 바늘출!':'🪡 Naalduitbarsting!',
'⚡ 전격이동!':'⚡ Bliksemdash!',
'기둥가시로 흡수됨':'Geabsorbeerd door zuil stekel',
'🌿 가시덫!':'🌿 Stekelval!',
'👻 유령총!':'👻 Geestenpistool!','💥 유령총 폭발!':'💥 Geestenpistool Explosie!',
'⚡ 전격의창!':'⚡ Donderspeer!',
'🏹 공성쇠뇌 설치!':'🏹 Belegeringsarmborst Geplaatst!',
'👻 유령 허수아비!':'👻 Fantoom Lokvogel!',
'💥 폭발 허수아비!':'💥 Explosieve Lokvogel!',
'축적!':'Opgeslagen!','축적 중...':'Opslaan...','만충! 재입력→폭발':'Vol! Herdruk→Explosie',
'폭발! ':'Explosie! ','불발...':'Misschot...','뎀':' SCH',
'🩸 폭독칼날!':'🩸 Pestkling!',
'⚡날개치기!':'⚡Vleugelslag!',
'🗡 칼등날개!':'🗡 Schild Vleugel!',
'🏛️ 악의기둥!':'🏛️ Donkere Zuil!',
'🌿 기둥가시!':'🌿 Zuil Stekel!',
'🌋 지옥강타!':'🌋 Helslag!',
'💥 체간 붕괴!':'💥 Houding Instorting!',
'💫 포이즈 파괴!':'💫 Houding Vernieling!',
'⚡ 뇌전걸음!':'⚡ Geestenstap!',
'✟ 구속의 영역!':'✟ Bindend Domein!',
'✟ 신성폭발!':'✟ Heilige Explosie!',
'⛧ 블랙!':'⛧ Zwarte Ster!',
'🌋 용암소환!':'🌋 Lava Oproep!',
'필살기 배정!':'Ultiem Toegewezen!',
'완료':'Voltooid','합체 가능':'Kan Fuseren','부족':'Onvoldoende',
'SP 부족! (':'SP nodig! (',
'🕊️ 히든: 평화의보호 해금!':'🕊️ Verborgen: Vredes Schild ontgrendeld!',
'⚡ 히든: 참회 해금!':'⚡ Verborgen: Berouw ontgrendeld!',
'배정됨':'Toegewezen',
'합체 Lv.':'Fusie Lv.',
'◆ 같은 보석 스킬 습득 시 합체 가능':'◆ Kan fuseren bij gelijk juweel vaardigheid',
// --- Phase 13: inventory/forge/storage ---
'▼ 가방 → 창고 보관':'▼ Tas → Opslag',
'▲ 창고 → 가방 꺼내기':'▲ Opslag → Tas',
'✓ 선택됨':'✓ Geselecteerd',
'⟨ 입력 대기... ⟩':'⟨ Wachten... ⟩',
'⟨ 대기 ⟩':'⟨ Wachten ⟩',
'보조':'Sub',
'키 설정 초기화 (또는 F5 키)':'Toetsbinding resetten (of F5)',
'아무 키 또는 마우스 버튼을 누르세요 (ESC = 취소)':'Druk een toets of muisknop (ESC = annuleren)',
'WebGPU 활성':'WebGPU Actief','WebGL2 활성':'WebGL2 Actief',
'측정 중...':'Meten...',
'불러오기 실패':'Laden Mislukt',
'장착':'Uitgerust',
'🔒 중요잠금 아이템은 분해 선택 불가!':'🔒 Belangrijke vergrendelde items kunnen niet worden geselecteerd voor ontmanteling!',
'장비 강화 (실패 시 재료만 소멸)':'Uitrusting Versterken (bij mislukking alleen materialen verloren)',
'강화 보너스 적용':'Versterkingsbonus Toegepast',
'강화 실패!':'Versterking Mislukt!',
'장착된 장비가 없습니다.':'Geen uitrusting aangelegd.',
'충분':'Genoeg','더 필요':'Meer nodig',
'장비 선택':'Uitrusting Selecteren','목표치 설정':'Doel Instellen',
'악의 투입':'Kwaad Investeren','자동 시도':'Auto Poging',
'목표 강화치':'Doel Versterking',
'예상 필요 악의':'Geschatte Kwaad Nodig',
'보유':'In bezit','강화 시작':'Versterking Starten',
'위에서 장비를 선택하세요':'Selecteer uitrusting hierboven',
'⬆ 물약 강화 (최대 10단)':'⬆ Drankje Versterken (max niveau 10)',
'필요':'Vereist',
'악의의 분해로 — 장비를 악의로 갈아버려라':'Kwaad Oven — Maal uitrusting in kwaad',
'전체 선택':'Alles Selecteren','전체 해제':'Alles Deselecteren',
'희귀 이하':'Zeldzaam of Lager',
'어픽스 리롤!':'Affix Herrol!',
'결정 분해 → 결정 가루':'Kristal Ontmantelen → Kristalstof',
'결정 제작 (가루 → 결정)':'Kristal Maken (Stof → Kristal)',
'물리':'Fysiek','영웅':'Heroïsch','전설':'Legendarisch',
'무기 타입':'Wapentype','활 타입':'Boogtype',
'보스방':'Baasverdediging','ST 부족':'Niet genoeg ST',
// --- Phase 14: boss phase labels ---
'💀 광폭화!':'💀 Razend!',
// --- Phase 14: chapter pet dialogue ---
'...따라오는 거 아니야. 같은 방향일 뿐이지.':'...Ik volg je niet. Gewoon dezelfde richting.',
'공기가 달라졌어. 더 썩었군.':'De lucht is veranderd. Meer verrotting.',
'여기부터는 악마 영역이야. ...맘대로 해.':'Demonengebied vanaf hier. ...Doe wat je wilt.',
'...이 냄새. 살점이 썩는 냄새야.':'...Die geur. Rottend vlees.',
'여기 오래 있으면 미쳐. 나도, 너도.':'Te lang hier en je wordt gek. Ik ook.',
'이 길의 끝에 뭐가 있을까. ...알고 싶지도 않어.':'Wat is er aan het einde van deze weg? ...Ik wil het niet weten.',
'...여기가 끝이야. 돌아갈 길은 없어.':'...Dit is het einde. Geen weg terug.',
// --- Phase 14: idle tips (crow) ---
'작살을 땅에 꽂으면 끌려간다.':'Steek de harpoen in de grond en word meegetrokken.',
'Shift로 작살 던져봐!':'Probeer de harpoen te gooien met Shift!',
'패링 성공하면 ST가 회복된다. 공짜 자원이야.':'Pareren herstelt ST. Gratis middelen.',
'패링 많이 하면 ST 걱정 없어~':'Veel pareren en ST is nooit een probleem~',
'장비 분해하면 악의를 얻는다. 쓰레기도 자원이야.':'Uitrusting ontmantelen geeft Kwaad. Zelfs rommel is middelen.',
'TAB 열어서 안 쓰는 장비 분해해!':'Open TAB en ontmantel ongebruikte uitrusting!',
'그로기 상태의 적에겐 1.5배 데미지가 들어간다.':'Verdoofde vijanden nemen 1,5x schade.',
'무릎 꿧으면 전력으로 때려!':'Als ze knielen, sla met alles!',
'속성 상성이 있다. 화염은 빙결에 약하고, 암전은 암흑에 약하다.':'Elementen hebben tegenhangers. Vuur is zwak tegen Ijs, Bliksem tegen Donker.',
'무기 속성 바꿔가면서 싸워봐!':'Probeer wapenelementen te wisselen!',
'빙결된 적은 1.5배 데미지를 받는다.':'Bevroren vijanden nemen 1,5x schade.',
'얼리고 때리는 게 기본이야!':'Bevriezen en slaan — dat zijn de basis!',
'보스의 빨간 공격은 패링 가능. 보라빛은 회피만.':'Rode baasaanvallen kunnen worden gepareerd. Regenboog alleen ontwijken.',
'색깔 잘 봐! 빨강은 받아치고 무지개는 피해!':'Let op de kleuren! Rood pareren, regenboog ontwijken!',
'VIT를 올리면 최대 HP가 오른다. 죽기 싫으면 찍어.':'VIT verhoogt max HP. Investeer als je wilt leven.',
'STR은 근접, DEX는 활, INT는 마법! 골고루 말고 하나만!':'STR voor nabij, DEX voor bogen, INT voor magie! Concentreer op één!',
'E를 꾹 누르면 빔이 나간다. 짧게 누르면 투사체.':'Houd E vast voor straal. Tik E voor projectiel.',
'마법 쓸 때 MP 잘 봐! 빔은 연속으로 깎여!':'Let op MP met magie! Straal verbruikt snel!',
'핵터와 디로이가 아이템을 주워준다. 수거 범위 안이면.':'Hecter en Deroy verzamelen automatisch items in bereik.',
'우리한테 고마워해~ 안 주우면 썩잖아.':'Dank ons~ Items verrotten als niemand ze oppakt.',
'LCK를 올리면 레어 드롭률이 오른다.':'LCK verhoogt de zeldzame dropkans.',
'운빨 게임이긴 하지~ LCK 올려봐!':'Het is allemaal geluk~ Probeer LCK te verhogen!',
'강화하면 공격력이 쭉쭉 올라가! 악의만 있으면 돼!':'Versterking verhoogt ATK snel! Heb alleen Kwaad nodig!',
'강화 확률은 +1에서 99%. 높을수록 떨어진다.':'Versterkingskans begint bij 99% voor +1. Daalt daarna.',
'실패하면 악의만 날아가~ 장비는 안 부서져!':'Bij mislukking alleen Kwaad verloren~ Uitrusting overleeft!',
'대장간에서 장비 제작도 된다. 악의 30000개면 영웅급 이상.':'Smidse kan ook maken. 30000 Kwaad voor Heroïsch+.',
'랜덤이지만 좋은 거 나올 수도 있어!':'Willekeurig, maar misschien iets goeds!',
'쉴드는 마법으로, HP는 물리로 깎아야 제대로 먹힌다.':'Schild heeft magie nodig, HP heeft fysiek nodig.',
'반대로 치면 50%만 들어가! 무기 바꿔가면서 싸워!':'Verkeerd type doet slechts 50%! Wissel wapens!',
'장비에 접두사, 접미사가 붙으면 특수 효과가 생긴다.':'Uitrusting met voor-/achtervoegsel krijgt speciale effecten.',
'영웅급 이상 장비에만 붙어! 좋은 거 나오면 강화해!':'Alleen op Heroïsch+ uitrusting! Verbeter de goede resultaten!',
'강화는 장비를 바꿔도 자동 이전된다. 악의만 있으면.':'Versterking wordt automatisch overgedragen. Kost alleen Kwaad.',
'더 좋은 장비 나오면 바로 장착해! 강화 수치 그대로 옮겨가!':'Equip betere uitrusting meteen! Versterking wordt overgedragen!',
// --- Phase 14: additional tutorial lines ---
'패링을 써야 자원을 흡수한다고!':'Je moet pareren om middelen te absorberen!',
'F키 회복의 영역을 써봐. 자원이 차올라.':'Probeer F-toets Heilig Domein. Middelen vullen zich.',
'적이 근접하면 스페이스키야! 가시덫을 활용해!':'Als vijanden dichtbij komen, gebruik Spatiebalk! Gebruik Stekelval!',
'기절시켜! 그로기가 터지면 데미지가 1.5배야!':'Verdoof ze! Verdoofd betekent 1,5x schade!',
'1번 대왕치기로 밀어버려!':'Gebruik toets 1 Reuzenslag om ze terug te duwen!',
'무릎 꿇었다.':'Het knielt.',
'지금이야! 몰아쳐!!':'Nu! Druk de aanval!!',
'스킬 포인트 있어! K 눌러서 스킬 찍어봐!':'Vaardigheidspunten beschikbaar! Druk K om vaardigheden te leren!',
'...힘이 없으면 여기서 끝이야.':'...Zonder kracht eindigt het hier.',
'...쓸 거 아니면 분해해.':'...Ontmantel wat je niet nodig hebt.',
'아이템 넘쳐나네~ 우리가 주워줄게!':'Zoveel items~ Wij verzamelen voor jou!',
'악의가 바닥이다.':'Kwaad op.',
'TAB 열어서 장비 분해해! 쓰레기도 악의가 돼!':'Open TAB en ontmantel uitrusting! Zelfs rommel wordt Kwaad!',
'좋은 장비가 있네! G 눌러서 대장간 가봐!':'Goede uitrusting! Druk G voor de smidse!',
'...강화 안 하면 그냥 고철이야.':'...Zonder versterking is het gewoon schroot.',
'...멈추지 마. 여신은 기다리지 않는다.':'...Stop niet. De godin wacht niet.',
'앞으로 가자~ 나도 여기 오래 있기 싫어.':'Laten we verder gaan~ Ik wil ook niet lang hier blijven.',
'...냄새가 짙다. 큰 놈이 있어.':'...De geur is sterk. Er is iets groots hier.',
'준비됐어? 물약 확인하고!':'Klaar? Controleer je drankjes!',
// --- Phase 15: missing pet dialogue translations ---
'TAB을 눌러. 가방을 열고 장비를 입어야 한다.':'Druk TAB. Open je tas en doe je uitrusting aan.',
'주웠으면 껴야지! TAB!':'Opgepakt? Doe het aan! TAB!',
'G. 대장간에서 물약도 제작할 수 있다.':'G. Je kunt ook drankjes maken bij de smidse.',
'악의로 물약 만들어! G키야!':'Maak drankjes met Kwaad! G-toets!',
'기절이야! Ctrl 눌러!':'Verdoofd! Druk Ctrl!',
'Ctrl 유령걸음으로 탈출!':'Ctrl Geestenstap om te ontsnappen!',
'Ctrl 얼음보주로 탈출!':'Ctrl IJsbol om te ontsnappen!',
'빨간 탄은 우클릭 패링. 무지개는 Q 패링.':'Rode kogels: RMB pareren. Regenboog: Q pareren.',
'나머지는 전부 우클릭 패링 가능해!':'Alles andere kan worden gepareerd met RMB!',
'빨강=우클릭, 무지개=Q 패링. 나머진 다 쳐내.':'Rood=RMB, Regenboog=Q pareren. Rest afweren.',
'무지개는 Q로 패링! 나머지는 전부 우클릭!':'Regenboog met Q! Alles andere met RMB!',
'빠져! 물약 마시고 안전한 곳에서 회복해.':'Terugtrekken! Drink drankjes en herstel op een veilige plek.',
'자원 없으면 도망가는 게 답이야!':'Geen middelen? Weglopen is het antwoord!',
'스페이스! 가시덫으로 적 묶어버려!':'Spatiebalk! Bind ze vast met Stekelval!',
'근접이 너무 많아! 거리 벌려!':'Te veel nabijkamp! Creëer afstand!',
'...둘러싸이면 끝이야. 빠져나와.':'...Omsingeld en het is voorbij. Ontsnap.',
'1번 대왕치기로 쓸어버려!':'Gebruik toets 1 Reuzenslag om ze weg te vegen!',
'그로기 터지면 데미지 1.5배!':'Verdoofd geeft 1,5x schade!',
'회전참이나 광역기로 몰아! 한 놈씩 상대하면 죽어.':'Gebruik Wervelwind of Gebied! Één voor één en je bent dood.',
'뭉쳐있을 때가 기회야!':'Als ze samenkomen, is dat je kans!',
'E로 마력공격을 해봐! 악의 쉴드를 해제할려면 마법 공격을 해야 해!':'Probeer E voor magische aanvallen! Je hebt magie nodig om Kwaad schilden te breken!',
'쉴드는 마법으로, HP는 물리로. 반대로 치면 데미지 안 들어간다.':'Schilden met magie, HP met fysiek. Verkeerd type doet geen schade.',
'L키로 스킬 슬롯에 넣어야 쓸 수 있어.':'Druk L om vaardigheden aan sleuven toe te wijzen.',
'C키를 눌러. 패시브 포인트가 쌓여있다.':'Druk C. Passieve punten hebben zich opgestapeld.',
'C키! 패시브 올리면 진짜 강해져!':'Druk C! Passieven maken je veel sterker!',
'스태미나가 부족하다. 무리하지 마.':'Laag uithouding. Overdrijf het niet.',
'ST 없으면 스킬 못 써! 잠깐 빠져!':'Geen ST betekent geen vaardigheden! Korte terugtrekking!',
'탭 장비창을 열어봐. 아이템을 주워왔어!':'Open TAB uitrustingsmenu. We hebben een item opgepakt!',
'좋은 거 나왔다! TAB 열어서 확인해봐!':'Iets goeds gedropt! Open TAB om te controleren!',
'악의에 중독되면 악마가 돼서 부활력이 생긴대. 저 녀석처럼.':'Ze zeggen dat Kwaadverslaving je tot een demon maakt met herlevingskracht. Zoals die.',
'혹시 너도...?':'Misschien jij ook...?',
'데미지가 부족하면 무기류 강화를 해야해!!':'Als schade tekortschiet, verbeter je wapens!!',
'G키 대장간. 강화 안 하면 여기서 계속 죽어.':'G-toets smidse. Zonder versterking blijf je hier sterven.',
'시간이 없어. 움직여.':'Geen tijd. Beweeg.',
'멍하게 서있으면 안 돼!':'Sta niet gewoon te staan!',
'...뭘 기다리는 거야?':'...Waar wacht je op?',
'가자가자! 몬스터가 기다려!':'Laten we gaan! Monsters wachten!',
'여기 오래 있으면 위험해.':'Te lang hier blijven is gevaarlijk.',
'움직여야 해! 가만있으면 둘러싸여!':'Moet bewegen! Stilstaan en ze omsingelen je!',
'쉬는 건 죽고 나서 해.':'Rusten na je dood.',
'살아있을 때 쉬면 안 돼!':'Niet rusten terwijl je leeft!',
'적이 몰려오고 있어. 빨리 움직여.':'Vijanden komen dichterbij. Beweeg snel.',
'냄새 맡고 올 거야. 빨리!':'Ze ruiken je. Snel!',
'...아직 살아있는 거 맞지?':'...Je leeft nog, toch?',
'혹시 잠든 거야...?':'Ben je in slaap gevallen...?',
// --- Chapter entry dialogues ---
'...나무가 썩어가고 있어. 여기는 지옥의 입구야.':'...De bomen verrotten. Dit is de ingang naar de hel.',
'냄새 지독해... 빨리 지나가자.':'De stank is afschuwelijk... Laten we snel doorgaan.',
'조심해. 벌레굴이다. 벽이랑 바닥에서 기어나와.':'Voorzichtig. Wormennest. Ze kruipen uit muren en vloeren.',
'으으... 벌레 싫어! 밟아버려!':'Ugh... Ik haat insecten! Vertrappel ze!',
'...공기가 얼어붙는다. 여기선 화염이 먹힌다.':'...De lucht bevriest. Vuur werkt hier.',
'추워... 빙결 조심해! 얼면 끝이야.':'Koud... Let op voor bevriezing! Bevriezen en het is voorbij.',
'용암이다. 바닥을 밟으면 타 죽어.':'Lava. Stap op de grond en je verbrandt.',
'뜨거워! 여기 왜 이렇게 빨개!':'Zo heet! Waarom is alles hier zo rood!',
'...군단이다. 수가 많아. 광역기 없으면 밀려.':'...Het legioen. Te veel. Zonder Gebied word je overweldigd.',
'우글우글... 징그러워. 한꺼번에 쓸어!':'Overal gewimmel... Walgelijk. Veeg ze allemaal weg!',
'사도의 영역이야. 여기 놈들은 머리가 좋아.':'Apostelgebied. Deze zijn slim.',
'패턴이 복잡해졌어... 집중해!':'Patronen werden complex... Concentreer je!',
'...끝이다. 지옥의 심장부. 살아 돌아가는 건 포기해라.':'...Dit is het. Het hart van de hel. Geef de hoop op terugkeer op.',
'여기가 마지막이야... 각오해.':'Dit is het einde... Bereid je voor.',
// --- Remaining ---
'단계 ×':' x',
'⚡ 기동전폭! x':'⚡ Kettenexplosie! x',
'🔥🔥 3중폭!':'🔥🔥 Vlam x3!','🔥🔥🔥 6중폭!':'🔥🔥🔥 Vlam x6!','🔥🔥🔥🔥 9중폭!':'🔥🔥🔥🔥 Vlam x9!','💥 불꽃폭발! ':'💥 Vlam Detonatie! ',
'🔥 기동불꽃 준비!':'🔥 Kettenvlam Klaar!',
'🔨 기동파괴 준비!':'🔨 Kettenvernieling Klaar!',
'⚡ 기동전폭 준비!':'⚡ Kettenexplosie Klaar!',
'⚡ 기동파괴! ':'⚡ Kettenvernieling! T',
'🔥 기동불꽃!':'🔥 Kettenvlam!',
'🔥 기동불꽃! ':'🔥 Kettenvlam! T',
'❄빙결!':'❄Bevroren!','🟢독!':'🟢Vergif!','⚡감전!':'⚡Geschokt!','🔥화상!':'🔥Brandend!',
'✦ 여신의 가호 — SP+5 AP+3':'✦ Godinzegen — SP+5 AP+3',
'⚔ 기동칼날개!':'⚔ Vleugelkling!',
'🔥 화염관통!':'🔥 Vuurdoorboord!',
'🔱 관통!':'🔱 Doorboord!',
'⚔ 칼날!':'⚔ Kling!',
'💥 착지!':'💥 Landing!',
'💫 기절!':'💫 Verdoofd!',
'⚡ 체간삭감!':'⚡ Houdingbreuk!',
'클릭으로 선택 · ESC로 닫기':'Klik om te selecteren · ESC om te sluiten',
'선택됨':'Geselecteerd',
'악의 부족! (30)':'Niet genoeg Kwaad! (30)',
'MP 부족! (40)':'Niet genoeg MP! (40)','MP 부족! (100)':'Niet genoeg MP! (100)','MP 부족! (10)':'Niet genoeg MP! (10)',
'MP 부족! (':'Niet genoeg MP! (',
'✟ 시전...':'✟ Gieten...','🌋 시전...':'🌋 Gieten...','⛧ 시전...':'⛧ Gieten...',
'❄ 진입!':'❄ Invoer!',
'🔱 작살!':'🔱 Harpoen!',
'레벨 부족! (요구: Lv.':'Niveau te laag! (Vereist: Lv.',
' 장착!':' Uitgerust!',
' 해제':' Verwijderd',
'👿 악의 추출: +':'👿 Kwaad Extractie: +',
'F 슬롯 해제':'F Sleuf verwijderd',
'💫 집중...':'💫 Focus...',
'⚡ 마력연사!':'⚡ Magische Beschieting!',
'🪞 반격!':'🪞 Tegenaanval!','💢 반격!':'💢 Tegenaanval!',
'흡수!':'Absorberen!','반격 발사!':'Tegenaanval Schot!',
'저주! 드랍률 -50%':'Vloek! Dropkans -50%','도망!':'Vluchten!',
'위상!':'Fase!','방어!':'Verdedigen!',
'회수 HP+':'Terugroepen HP+','이동식 복귀':'Draagbaar Terugkeer',
'약점!':'Zwakte!','저항!':'Weerstand!',
'콤보 종료: ':'Combo Einde: ',
'악의 +':'Kwaad +',
'저주 ':'Vloek ','불발...':'Misschot...',
'작살 약점!':'Harpoen Zwakte!',
'전염 x':'Plaag x','흡수 완료!':'Absorptie Voltooid!',
'부활 성공!':'Herleving Geslaagd!','부활 실패...':'Herleving Mislukt...',
'차원 이동!':'Dimensionale Verschuiving!',
'기절 해제':'Verdoving Opgeheven',
'악의 부족':'Niet genoeg Kwaad',
'스킬 미습득':'Geen vaardigheden geleerd','펼치기':'Uitvouwen','접기':'Samenvouwen',
'조건 미달!':' niet voldaan!','해제!':' Opgeheven!',
'자동 ON':' Auto AAN','자동 OFF':' Auto UIT','스킬 해제':' vaardigheid verwijderd',
'닫기':'Sluiten','장착 중':'Uitgerust','보관 아이템':'Opgeslagen Item',
'🔨 제작':'🔨 Maken',
'분해할 아이템이 없습니다.':'Geen items om te ontmantelen.',
'스킬 미습득':'Geen vaardigheden geleerd',
'석궁 자동발사 (T)':'Kruisboog automatisch (T)',
'버스트루프 당기기 (H)':'Burst-lus aantrekken (H)',
'결정 자동합성':'Kristal auto-synthese',
'결정 자동강화':'Kristal auto-versterking',
'✓ 설정 자동 저장':'✓ Instellingen automatisch opgeslagen',
'세팅 프리셋 저장/불러오기':'Voorinstelling opslaan/laden',
'세팅1 저장':'Voorinstelling 1 opslaan','세팅1':'Voorinstelling 1',
'세팅2 저장':'Voorinstelling 2 opslaan','세팅2':'Voorinstelling 2',
'재진단':'Opnieuw diagnosticeren',
'게임 리셋 (처음부터)':'Spel resetten (van begin)',
'캐릭터 선택 (로비)':'Karakterselectie (Lobby)',
'닫기 [ESC]':'Sluiten [ESC]','닫기 [G]':'Sluiten [G]','닫기 [V]':'Sluiten [V]','닫기 [C]':'Sluiten [C]',
'전체화면 (F11)':'Volledig scherm (F11)',
'정말 모든 진행을 초기화하시겠습니까?':'Wil je echt alle voortgang resetten?',
'검출 중...':'Detecteren...',
'마우스 커서':'Muiscursor','그래픽 품질':'Grafische kwaliteit','하드웨어 진단':'Hardware diagnose',
'BGM 선택':'BGM-selectie',
'자동 (스테이지별)':'Automatisch (per level)','전체 랜덤':'Alles willekeurig','로비':'Lobby',
'1장 랜덤':'Hoofdstuk 1 willekeurig','2장 랜덤':'Hoofdstuk 2 willekeurig','3장 랜덤':'Hoofdstuk 3 willekeurig',
'4장 랜덤':'Hoofdstuk 4 willekeurig','5장 랜덤':'Hoofdstuk 5 willekeurig','6장 랜덤':'Hoofdstuk 6 willekeurig','7장 랜덤':'Hoofdstuk 7 willekeurig',
'보스':'Baas','최종보스':'Eindbaas',
'대장간 랜덤':'Smidse willekeurig','사망 랜덤':'Dood willekeurig','승리 랜덤':'Overwinning willekeurig',
'지옥 추락 사망 징글':'Hel val dood jingle','탈출 성공':'Ontsnapping geslaagd',
'── 1장 - 썩은 숲 ──':'── CH1 - Rotten Forest ──','── 2장 - 벌레굴 ──':'── CH2 - Worm Nest ──',
'── 3장 - 얼음굴 ──':'── CH3 - Ice Cavern ──','── 4장 - 화염지대 ──':'── CH4 - Infernal Wastes ──',
'── 5장 - 지옥군단 ──':'── CH5 - Hell Legion ──','── 6장 - 사도마굴 ──':'── CH6 - Apostle Den ──',
'── 7장 - 지옥성 ──':'── CH7 - Hell Citadel ──','── 공통 ──':'── Common ──',
'⌨ 조작법':'⌨ Besturing','클릭하면 닫힘':'Klik om te sluiten',
'전투력':'GV','가방':'Tas','결정':'Kristal',
'↕ 정렬':'↕ Sorteren','쓰레기 전체선택':'Alle rommel selecteren','쓰레기 전부 분해':'Alle rommel slopen',
'창고':'Opslag','스탯 포인트':'Attribuutpunten','능력치 요약':'Statusoverzicht','올 리셋':'Alles resetten',
'대장간':'Smidse','스킬':'Vaardigheden','능력치':'Attributen',
'좌클스킬 (클릭 전환)':'LMB-vaardigheid (klik om te wisselen)','우클스킬 (클릭 전환)':'RMB-vaardigheid (klik om te wisselen)',
'이동스킬 (클릭 전환)':'Bewegingsvaardigheid (klik om te wisselen)','마법스킬 (클릭 전환)':'Magievaardigheid (klik om te wisselen)',
'영역스킬 (클릭 전환)':'Gebiedsvaardigheid (klik om te wisselen)','피보호막 (클릭 전환)':'Bloedschild (klik om te wisselen)',
'CT스킬 (클릭 전환)':'CT-vaardigheid (klik om te wisselen)','[C] 능력치':'[C] Attributen',
'무기 공격':'Wapenaanval','칼등 처내기 (투사체 반사, 홀드 연사)':'Pareren (reflecteert projectielen, houd=salvo)',
'연속 처내기':'Doorlopend pareren','영역 스킬 (폭풍소환 등)':'Gebiedsvaardigheid (Wervelstorm etc)',
'작살 발사':'Harpoen schieten','마법 (탭=투사체, 홀드=빔)':'Magie (tik=projectiel, houd=straal)',
'데빌포스 흡수':'Duivelskracht absorberen','물약 / 스킬슬롯':'Drankjes / Vaardigheidsslots',
'스킬슬롯 5 / 필살기 / CT스킬':'Slot 5 / Ultiem / CT-vaardigheid','스킬 슬롯 배정':'Slottoewijzing',
'만화광선':'Luminescentiebundel',
'무릎 꿇으면 전력으로 때려!':'Als ze knielen, sla met alles!',
// --- Phase 27 additions ---
'위로 이동':'Beweeg omhoog','아래로 이동':'Beweeg omlaag','왼쪽 이동':'Beweeg links','오른쪽 이동':'Beweeg rechts',
'칼등 처내기 (탭=처내기, 홀드=연사)':'Lemmet Pareren (tik=pareren, houd=salvo)',
'영역 스킬':'Gebiedsvaardigheid','작살 이동':'Harpoen Dash',
'유령불꽃 켜기/끄기':'Geestenvlam Aan/Uit','기동칼날개 자동 켜기/끄기':'Lemmetvleugel Auto Aan/Uit',
'해상도':'Resolutie',
'빛이 꺼졌다':'Het Licht Dooft','누군가는 너를 기다리고 있다':'Iemand wacht op je',
'다시 일어서라':'Sta opnieuw op','로비로 돌아가기':'Terug naar de Lobby',
'☠ 사망 리플레이':'☠ Doodsherhal',
'지옥의 시련을 견뎌냈다':'Je hebt de beproeving van de Hel doorstaan',
'계속 전투':'Doorgaan met vechten','난이도를 선택하라':'Kies moeilijkheidsgraad',
'나중에 설정(ESC)에서 변경 가능':'Kan later worden gewijzigd in Instellingen (ESC)',
'일괄합성':'Massasynthese','일괄강화+합성':'Massaversterking+Synthese',
'자원 부족!':'Bronnen Laag!',' 뎀':' Schd',
'합체 폭발!':'Fusiedetonatie!',
'MP 부족! (50)':'Niet genoeg MP! (50)',
'부활력 고갈!':'Opstanding Uitgeput!','☠ 부활력 고갈!':'☠ Opstanding Uitgeput!',
'독안개':'Giftnevel','뇌전창':'Donderspeer',
'🔥 업화선 시전...':'🔥 Helstraal voorbereiding...',
'💥 기동파괴 그로기!':'💥 Kettingvernietiging Groggy!',
'💥 칼등 그로기!':'💥 Lemmet Pareren Groggy!',
'⚡ 순간이동 준비!':'⚡ Teleportatie Klaar!',
'👿악의+1000':'👿Kwaad+1000',
'💀 내려찍기!':'💀 Neerhak!',
'✟ 신성력 억제! +':'✟ Heilige Kracht Onderdrukt! +',
'✟ 신성력 억제!':'✟ Heilige Kracht Onderdrukt!',
'✟ 신성력 억제! (':'✟ Heilige Kracht Onderdrukt! (',
'💥 지진그로기!':'💥 Aardbeving Groggy!',
'💥 기폭그로기!':'💥 Detonatie Groggy!',
'폭발! ×':'Explosie! ×','⚫ 기둥강타!':'⚫ Pijlerslag!',
'💥 대왕치기 그로기!':'💥 Kolossaal Groggy!',
'💫 미니스턴!':'💫 Mini Stun!','⚡ 뇌전창!':'⚡ Donderspeer!',
'…절반이다. 정신차려.':'…Halverwege. Hou je focus.',
'…죽기 직전이다. 한 발만 더.':'…Bijna dood. Nog één slag.',
'…다음 한 방이 마지막이야.':'…De volgende slag is de laatste.',
'기절! ':'Verdoofd! ',
'마력이 빈다. 평타 섞어.':'MP raakt leeg. Meng normale aanvallen.',
'그랩이다. 거리를 둬.':'Grijpaanval. Houd afstand.',
'광역기다. 멀어져.':'Gebiedsaanval. Kom weg.',
'…아파? 당연하지. 여긴 지옥이야.':'…Pijn? Natuurlijk. Dit is de hel.',
'F키도 스킬 슬롯이야!':'F is ook een vaardigheidsslot!',
'L-CTRL로 유령걸음/얼음보주!':'L-CTRL voor Geestenwandeling / IJsbal!',
'V 눌러서 창고에 넣어둬!':'Druk V om op te slaan!',
'ESC로 설정! 난이도/자동물약!':'ESC voor instellingen! Moeilijkheid/Auto-drankjes!',
'잡몹이다. 먼저 정리해.':'Gewone vijanden. Ruim ze eerst op.',
'…얼어붙은 놈은 오래 안 간다.':'…Een bevroren vijand duurt niet lang.',
'…냄새가 짙다. 큰 놈이 있어.':'…De geur is sterk. Iets groots is nabij.',
'쉴드는 마법으로, HP는 물리로.':'Schild neemt magie, HP neemt fysiek.',
'스페이스! 가시덫으로 적 묶어!':'Spatiebalk! Vang vijanden met Stekeldval!',
'근접 너무 많아! 거리 벌려!':'Te veel dichtbij! Spreid uit!',
'회전참이나 광역기로 몰아!':'Gebruik Draaiende Slag of Gebied!',
'F 눌러! 회복의 영역 깔아!':'Druk F! Leg Heilig Domein neer!',
'F키 회복의 영역을 써봐.':'Probeer F-toets Heilig Domein.',
'빠져! 물약 마시고 회복해.':'Terugtrekken! Drink drankjes en herstel.',
'쉬프트! 사슬기동은 이동기야!':'Shift! Kettingdash is een bewegingswerktuig!',
'스킬포인트 쌓였어! K 눌러!':'Vaardigheidspunten klaar! Druk K!',
'스킬 포인트 있어! K!':'Vaardigheidspunten! K!',
'C키. 패시브 포인트가 쌓여있다.':'C-toets. Passieve punten hebben zich opgebouwd.',
'…쓸 거 아니면 분해해.':'…Demonteer wat je niet gebruikt.',
'…강화 안 하면 그냥 고철이야.':'…Zonder versterking is het gewoon schroot.',
'빨간 탄은 우클릭. 무지개는 Q.':'Rode kogels: rechtermuisknop. Regenboog: Q.',
'빨강=우클릭, 무지개=Q.':'Rood=rechtermuisknop, regenboog=Q.',
'…멈추지 마. 여신은 기다리지 않는다.':'…Stop niet. De godin wacht niet.',
'패턴이 바뀐다. 거리를 둬.':'Het patroon verandert. Houd afstand.',
'미쳐가고 있어. 광폭화다.':'Het wordt gek. Rasende modus.',
'마지막이야! 끝장내!':'Laatste fase! Maak het af!',
'…끝났다. 다음으로.':'…Klaar. Verder.',
'다 잡았다! 포탈 어딨어?':'Allemaal gevangen! Waar is de portal?',
'근육으로 만든 빌드군. 베고 부숴.':'Spierbouw. Hak en verbrijzel.',
'활을 쥐었군. 거리를 둬.':'Boog in hand. Houd afstand.',
'마법사군. MP 관리부터 배워라.':'Magiër. Leer eerst MP-beheer.',
'운에 기댄 빌드군. …드롭은 좋겠어.':'Geluksbouw. …In ieder geval worden drops goed.',
'…VIT가 너무 낮아. 한 방에 죽는다.':'…VIT is te laag. Je sterft van één slag.',
'다 찍으면 다 약해진다. 하나만 골라.':'Alles maximaliseren en je bent overal zwak. Kies één.',
'…3단. 적이 강해져. 정신 차려.':'…Fase 3. Vijanden worden sterker. Concentreer je.',
'5단이다. …너도 강해졌단 뜻이야.':'Fase 5. …Dat betekent dat jij ook sterker bent geworden.',
'…7단. 아직 살아있단 게 신기하군.':'…Fase 7. Nog steeds in leven. Verrassend.',
'10단. …너는 이제 인간이 아니야.':'Fase 10. …Je bent niet langer menselijk.',
'…일반으로 내려왔군. 가끔은 쉬어가야지.':'…Terug naar Normaal. Soms heb je een pauze nodig.',
'…이게 진짜 패링이야.':'…Dat is een echte parering.',
'…피가 묻기 시작했군.':'…Het bloed begint te vloeien.',
'100. 너는 인간이 아니야.':'100. Je bent niet menselijk.',
'…피 흘리며 베는군.':'…Hakt door bloed.',
'빨간콩이 푸르게 변했다. 그게 너의 무기야.':'De rode kogel werd blauw. Dat is je wapen.',
'무지개를 받아쳤군. 그건 진짜 어렵다.':'Pareerde een regenboog. Dat is echt moeilijk.',
'…너무 빨라. 닿기 직전에 눌러.':'…Te snel. Druk net voor contact.',
'악의가 가득 찼다. 풀어내.':'Het Kwaad is vol. Laat het los.',
'작살이 살을 뚫었어. 끌고 와.':'Het harpoen drong door het vlees. Trek het naar binnen.',
'…풀차지군. 멀리 던져버려.':'…Volledig opgeladen. Gooi het ver weg.',
'…빈틈을 그대로 빠져나갔다.':'…Gleed direct door de opening.',
'…일반 잡몹이 아니야. 모디파이어 붙었군.':'…Geen gewone vijand. Het heeft een modifier.',
'엘리트 하나 처리.':'Elite neer.',
'…큰 놈이다. 일반 잡몹 정리부터.':'…Een grote. Ruim de gewone vijanden eerst op.',
'미니보스 처리. 다음 길로.':'Mini-boss neer. Op naar het volgende pad.',
'한 번에 다섯. 깔끔해.':'Vijf tegelijk. Netjes.',
'100강. 이제 뭔가 다르게 보이는군.':'+100. Dingen zien er nu anders uit.',
'…운이 없는 날이야.':'…Ongeluksdag.',
'…전설이다. 이런 건 처음 본다.':'…Legendarisch. Zoiets nooit gezien.',
'…죽었다 살아났네. 여신은 너를 포기 안 했어.':'…Gestorven en teruggekeerd. De godin gaf je niet op.',
'…또야? 패턴 좀 외워!':'…Weer? Leer het patroon!',
'…한 번도 안 죽고. 그건 진짜 실력이야.':'…Geen enkele keer gestorven. Dat is echte vaardigheid.',
'…ACT1을 끝냈다. 진짜 시작은 여기서부터야.':'…ACT1 klaar. De echte start is hier.',
'모든 보스를 무너뜨렸다. 너는 지옥의 일부야.':'Alle bazen gevallen. Je bent een deel van de hel.',
'…30초. 너 진짜 미쳤구나.':'…30 seconden. Je bent echt gek.',
'…빠르군. 효율적이야.':'…Snel. Efficiënt.',
'신기록이다.':'Nieuw record.',
'탭 장비창을 열어봐.':'Open het uitrustingsvenster met TAB.',
'데미지 부족하면 무기 강화!':'Niet genoeg schade? Versterk je wapen!',
// --- Loading screen ---
'불러오는 중...':'Laden...',
'로딩중...':'Laden...',
'맵과 몬스터 불러오는 중...':'Kaart en monsters laden...',
'기본 데이터 준비 중...':'Basisgegevens voorbereiden...',
'저장 데이터 불러오는 중...':'Opgeslagen gegevens laden...',
'몬스터 스킨 로딩...':'Monsterskins laden...',
'맵과 몬스터 생성 중...':'Kaart en monsters genereren...',
'맵 에셋 로딩...':'Kaartbronnen laden...',
'맵 환경 준비 중...':'Kaartomgeving voorbereiden...',
'주변 청크 준비 중...':'Nabije chunks voorbereiden...',
'맵 캐시 생성 중...':'Kaartcache bouwen...',
'미니맵 빌드 중...':'Minimap bouwen...',
// Phase 28
' 으로 탈출!':' — ontsnap!',
'100명?! 미쳤어!':'100 kills?! Waanzinnig!',
'10단 최고난이도! 너 진짜 광기야!':'Moeilijkheid 10 max! Absoluut gestoord!',
'1분 안에 클리어! 빠르네!':'Level in 1 min! Zo snel!',
'30초!! 스피드런 가능해!':'30 seconden!! Speedrun potentieel!',
'3단! 보상도 좋아지지만 죽기 쉬워!':'Moeilijkheid 3! Betere beloningen maar makkelijker te sterven!',
'50명! 학살자야!':'50 kills! Slachter!',
'5단!! 진짜 게이머 인증!':'Moeilijkheid 5!! Echte gamer gecertificeerd!',
'7단!! 다른 사람들 이 정도 못 와!':'Moeilijkheid 7!! Anderen komen niet zo ver!',
'ACT1 완주! 우리가 진짜 해냈어!':'ACT 1 voltooid! We hebben het echt gedaan!',
'Ctrl 얼음보주로 탈출하라.':'Ctrl — ontsnap met IJsbol.',
'Ctrl 유령걸음으로 탈출하라.':'Ctrl — ontsnap met Geestenstap.',
'C키! 패시브 강해져!':'Toets C! Passives worden sterker!',
'DEX 빌드! 거리에서 패고, 추적탄 좋아!':'DEX build! Afstandsaanvallen, volgende projectielen!',
'E로 마력공격을 해봐!':'Probeer magische aanval met E!',
'G 눌러서 대장간 가봐!':'Druk G — smidse!',
'G키 대장간. 강화 안 하면 계속 죽어.':'G — smidse. Geen upgrades, blijf sterven.',
'HP 70%! 조심해!':'HP 70%! Wees voorzichtig!',
'INT 빌드! 빔이랑 폭발 마법! MP 잘 봐!':'INT build! Stralen en explosieve magie! Let op MP!',
'LCK 높아! 레어 드롭률 미친 거 알지?':'Hoge LCK! Dropkansen zijn waanzinnig!',
'L로 어디에 뭘 넣을지 골라!':'Druk L — kies vaardigheidsslot indeling!',
'MP 부족! 평타로 패면서 회복해!':'MP laag! Sla om te herstellen!',
'ST 없으면 스킬 못 써!':'Geen ST, geen vaardigheden!',
'STR 빌드! 회전참, 회오리, 광역기 추천!':'STR build! Draai slash, wervelwind, AoE!',
'VIT 좀 찍어! HP 너무 적어!':'Voeg VIT toe! HP te laag!',
'Z 누르면 대박! 쿨타임 길어!':'Druk Z voor ultiem! Lange cooldown!',
'…고기 냄새. 싫진 않네.':'…Bloedgeur. Niet slecht.',
'…둘러싸이면 끝이야.':'…Omringd betekent dood.',
'…말은 못해.':'…Kan niet praten.',
'…버리기 아까운 건 창고에.':'…Waardevolles in opslag.',
'…빈틈을 노려.':'…Wacht op openingen.',
'…설정을 확인해.':'…Controleer instellingen.',
'…슬롯을 채워. 빈 손은 죽음이다.':'…Vul slots. Lege handen is dood.',
'…아직 살아있네. 좌클릭으로 저것들 쳐봐.':'…Nog in leven. Linksklik om ze te slaan.',
'…운이 좋았을 뿐이야. 아마.':'…Gewoon geluk. Waarschijnlijk.',
'…치는 건 할 줄 아네. 피하는 건?':'…Kan slaan. Kan ontwijken?',
'…힘을 골라라. 전부 가질 순 없다.':'…Kies je kracht. Kan niet alles hebben.',
'골고루 안 돼! 하나로 밀어!':'Niet spreiden! Duw op één stat!',
'그로기 터지면 1.5배!':'Groggy = 1,5x schade!',
'길이 열렸다.':'Pad is open.',
'나머진 전부 우클릭 패링 가능!':'Rest — rechtsklik pareren!',
'나머진 전부 우클릭!':'Rest — rechtsklik!',
'다섯 번 연속! 내가 본 인간 중 최고!':'Vijf op rij! Beste die ik ooit heb gezien!',
'다음엔 죽지 마!':'Stier de volgende keer niet!',
'더블탭 전격이동으로 탈출하라.':'Dubbelklik dash om te ontsnappen.',
'소환수 왔어! 먼저 처리해야 해!':'Oproepen! Ruim ze eerst op!',
'스킬 없으면 방향키 연타뿐이야.':'Geen vaardigheden? Spam gewoon pijltjestoetsen.',
'신기록!! 스트리머한테 보내!':'Nieuw record!! Stuur naar streamer!',
'아이템 넘쳐! 우리가 주워줄게!':'Tas vol! Wij rapen voor jou op!',
'안 죽고 깼어! 진짜 천재 맞네!':'Geen dood clear! Echte genie!',
'앞으로 가자~':'Vooruit~',
'우리가 해냈어! 다음 챕터 가자!':'We hebben het gedaan! Volgend hoofdstuk!',
'일반 모드! 편하게 즐기자!':'Normale modus! Geniet rustig!',
'자원이 반이다. F키로 회복해.':'Middelen half. F om te herstellen.',
'잡힌다! 옆으로 빠져!':'Gegrepen! Ontwijken opzij!',
'장비 분해해! 쓰레기도 악의!':'Ontmantelen uitrusting! Rommel geeft ook kwaadaardigheid!',
'전부 다 잡았어! 우리가 지옥의 왕이야!':'Alles geklaard! Koningen van de hel!',
'좋은 거 나왔다! TAB!':'Goed buit! TAB!',
'죽기 직전에 죽이다니! 멋져!':'Gedood vlak voor sterven! Geweldig!',
'체력 반 남았어! 물약 마실 타이밍!':'Half HP! Potiontijd!',
'큰 거 온다! 도망쳐!':'Grote aanval! Ren!',
'패링으로 돌려주고, Q 보호막도 써!':'Pareer en reflecteer, gebruik Q schild!',
'패턴이 빨라졌어!':'Patronen sneller!',
'한 대만 맞아도 죽어! 패링이든 회피든!!':'Één klap = dood! Pareer of ontwijkt!!',
'한 방이면 죽어! 도망쳐!!':'Één schot doodt! Ren!!',
'화염엔 빙결! 암전엔 암흑!':'Vuur → vorst! Leegte → schaduw!',
'── 2장 - 벌레굴 ──':'── CH2 - Worm Nest ──',
'── 4장 - 화염지대 ──':'── CH4 - Infernal Wastes ──',
'── 6장 - 사도마굴 ──':'── CH6 - Apostle Den ──',
'── 공통 ──':'── Common ──',
'난이도를 선택하라':'Kies moeilijkheidsgraad',
'☠ 부활력 고갈!':'☠ Heropleving Uitgeput!',
'⏳⚡ 시간걸음!':'⏳⚡ Tijdstap!',

'블룸 효과':'Bloom-effect',
'잔상 트레일':'Nabeeldspoor',
'슬래시 이펙트':'Slash-effect',
'후처리 효과':'Nabewerking',
'사망 이펙트':'Doodseffect',
'동적 조명':'Dynamische verlichting',
'횃불 조명 (어둠)':'Fakkelverlichting (donker)',
'앰비언트 파티클':'Omgevingsdeeltjes',
'안개 효과':'Misteffect',
'필름 그레인':'Filmkorrel',
'캐릭터 외곽선':'Karakteromtrek',
'리롤':'Opnieuw gooien',
'물약':'Drankje',
'으로 탈출!':'om te ontsnappen!',
'Shift 작살':'Shift Harpoen',
'더블탭 전격이동':'Dubbeltik — Bliksemdash',
'Ctrl 유령걸음':'Ctrl Geestenstap',
'Ctrl 얼음보주':'Ctrl Ijsbol',
'🔴화염→빙결 2배 | 🔵빙결→화염 2배 | ⚪물리=중립 | 악마 처치 시 악의 영혼 드롭':'🔴Vuur→Ijs 2× | 🔵Ijs→Vuur 2× | ⚪Fys=Neutraal | Dood demonen voor kwaadaardige zielen',
  '미구현':'N/A',
  '스탯 총량':'Totaal statistieken',
  '장비':'uitrusting',
  '공속':'aanvalssnelh.',
  '크리':'krit',
  '크리뎀':'krit.schade',
  '근성':'Taaiheid',
  '종합 지표':'Overzicht',
  '근접 DPS':'Melee DPS',
  '공격력×공속×크리':'ATK×Snel×Krit',
  '활 DPS':'Boog DPS',
  '마법 DPS':'Magie DPS',
  '유효 HP (EHP)':'Effectief HP (EHP)',
  '쉴드':'Schild',
  '장비 파워':'Uitrustingskracht',
  '근접 공격력':'Melee ATK',
  '기본':'basis',
  '무기':'wapen',
  '패시브':'passief',
  '활 공격력':'Boog ATK',
  '정밀':'Prec',
  '마법 공격력':'Magie ATK',
  '왕관':'kroon',
  '마력':'Arcane',
  '공격속도':'Aanvalssnelheid',
  '크리티컬':'Kritisch',
  '데미지':'schade',
  '확률':'Kans',
  '어픽스':'affix',
  '레거시':'erfenis',
  '추가뎀':'extra schade',
  '패링 카운터뎀':'Parry-tegenaanval schade',
  '우클공속':'Rechtermuisknopsnelh.',
  '무지개탄DR':'Regenboog DR',
  '포이즈파괴':'Poise breken',
  '방어관통':'Wapenrusting penetratie',
  '관통력':'Doorboring',
  '속성':'Elementen',
  '무기속성':'Wapen element',
  '독':'Gif',
  '초':'s',
  '암흑저주':'Donkere vloek',
  '원소집중':'Element focus',
  '원소전환':'Element conversie',
  '방어':'Verdediging',
  '물리방어':'Fysieke verdediging',
  '감소':'reductie',
  '캡':'limiet',
  '장갑':'handschoenen',
  '바지':'broek',
  '속성방어':'Element verdediging',
  '목걸이':'halsketting',
  '반지1':'ring1',
  '반지2':'ring2',
  '반사':'Reflectie',
  '가시':'Doornen',
  '배리어':'Barrière',
  '보호막 흡수':'Schild absorptie',
  '속성 저항':'Element weerstand',
  'CC저항':'CC weerstand',
  '생존':'Overleving',
  '장비HP':'Uitrusting HP',
  '임플':'Impl.',
  '에너지쉴드':'Energieschild',
  '리젠':'Regen',
  '스태미나':'Stamina',
  '성장':'Groei',
  'MP%어픽스':'MP% affix',
  '이동속도':'Bewegingssnelheid',
  '한방캡':'Eén-schot limiet',
  '최대HP의33%':'33% Max HP',
  '비용/효율':'Kosten/Eff',
  '근접ST':'Melee ST',
  '활ST':'Boog ST',
  '마법MP':'Magie MP',
  '작살사거리':'Harpoenbereik',
  '기동게이지':'Drive-balk',
  '쿨감':'CDR',
  '쇠뇌뎀':'Kruisboogschade',
  '쇠뇌공속':'Kruisboogsnelheid',
  '기타':'Overig',
  '물약쿨':'Drankje CD',
  '회복+':'Herstel+',
  '드롭':'Drop',
  '경험치+':'EXP+',
  '골드+':'Goud+',
  '기동:칼날개':'Drive:Kling',
  '기동:전폭':'Drive:Slag',
  '기동:기습':'Drive:Hinderlaag',
  '충전스킬':'Laad-skill',
  '사슬게이지':'Ketting-balk',
  '특수 효과':'Speciale effecten',
  '처치뎀+':'Kill schade+',
  '위기뎀+':'Crisis schade+',
  '피격반격':'Treffer-tegenaanval',
  '풍요(적HP≥70%뎀+)':'Overvloed(HP≥70%+)',
  '약자포식(적HP≤30%뎀+)':'Roofdier(HP≤30%+)',
  '패링폭발':'Parry-explosie',
  '체간파괴+':'Poise breken+',
  '콤보뎀+':'Combo schade+',
  '작살뎀+':'Harpoenschade+',
  '스킬뎀+':'Skill schade+',
  '패리+':'Pareren+',
  '체인':'Ketting',
  '정화':'Zuivering',
  '회':'×',
  '불굴':'Taaiheid',
  '신성력':'Heilige kracht',
  '악마력(부활력)':'Demonenkracht',
  '자연':'Natuur',
  '악마성':'Demoniciteit',
  '인간성':'Menselijkheid',
  '전투 통계':'Gevechtsstatistieken',
  '핵터':'Hecter',
'디로이':'Deroy',
'물리 ATK +1, MAX HP +5, HP리젠 +0.002':'Phys ATK +1, MAX HP +5, HP regen +0.002',
'석궁 ATK +1, 공격속도 +0.05%, MAX ST +2, ST리젠 +0.005, 회피 +0.05%':'Bow ATK +1, ATK speed +0.05%, MAX ST +2, ST regen +0.005, Dodge +0.05%',
'마법 ATK +1, MAX MP +2, MP리젠 +0.005, MAX 쉴드 +5':'Magic ATK +1, MAX MP +2, MP regen +0.005, MAX Shield +5',
'크리확률 +0.025%, 크리뎀 +0.2%, 드롭률 +0.15%':'Crit rate +0.025%, Crit DMG +0.2%, Drop rate +0.15%',
'근접뎀 +15%, ST비용 -4%/lv (최대-40%)':'Melee DMG +15%, ST cost -4%/lv (max -40%)',
'작살 사거리 +2%/lv, 기동게이지 회복 +3%/lv':'Harpoon range +2%/lv, Mobility gauge recovery +3%/lv',
'카운터뎀 +50%/lv, 우클릭 공속 +10%/lv, 무지개탄 피해감소 +10%/lv (최대50%)':'Counter DMG +50%/lv, RMB ATK speed +10%/lv, Rainbow shot DMG reduction +10%/lv (max 50%)',
'마법뎀 +15%, MP비용 -4%, 시전속도 +8%/lv':'Magic DMG +15%, MP cost -4%, Cast speed +8%/lv',
'투사체뎀 +15%, 공속 +10%, 사거리 +8%, ST비용 -4%/lv':'Projectile DMG +15%, ATK speed +10%, Range +8%, ST cost -4%/lv',
'보호막 흡수 +2%/lv (기본70→최대90%), 보호막 중 HP리젠 +0.1%/lv':'Shield absorb +2%/lv (base 70 to max 90%), HP regen during shield +0.1%/lv',
'HP/ST리젠 +3%/lv, 물약쿨 -3%/lv':'HP/ST regen +3%/lv, Potion cooldown -3%/lv',
'크리률 +2%, 크리뎀 +8%/lv':'Crit rate +2%, Crit DMG +8%/lv',
'아이템 드롭률 +8%/lv':'Item drop rate +8%/lv',
'투사체 관통률 +5%/lv, 관통횟수 +1/lv, 관통뎀감소 완화':'Projectile pierce rate +5%/lv, Pierce count +1/lv, Pierce DMG falloff reduced',
'MP리젠 +3%/lv, 쉴드리젠 +3%/lv, 쉴드쿨 -3%/lv':'MP regen +3%/lv, Shield regen +3%/lv, Shield cooldown -3%/lv',
'자동쇠뇌 뎀 +5%/lv, 공속 +5%/lv':'Auto crossbow DMG +5%/lv, ATK speed +5%/lv',
'물리뎀 +15%/lv, HP +3%/lv, ST소모 -5%/lv':'Phys DMG +15%/lv, HP +3%/lv, ST cost -5%/lv',
'적에게 약점노출 디버프. 직접 공격 시 스택+1, 스택당 피격뎀 +3%. 최대 Lv×5 중첩 (1렙5, 10렙50). 초당 20% 감소, 5초 미피격 시 리셋. DOT/장판 제외':'Weakness debuff on enemies. +1 stack per direct hit, +3% DMG/stack. Max Lv×5 (Lv1=5, Lv10=50). -20%/s decay, reset after 5s. DOT excluded',
'물리→쉴드 패널티 관통 +5%/lv (기본10%, 10lv=60%)':'Phys to Shield penalty pierce +5%/lv (base 10%, lv10=60%)',
'마법→HP 패널티 관통 +5%/lv (기본10%, 10lv=60%)':'Magic to HP penalty pierce +5%/lv (base 10%, lv10=60%)',
'적 HP 70%↑: 뎀+20%/lv, 회복력+5%/lv (합연산)':'Enemy HP≥70%: DMG+20%/lv, Recovery+5%/lv (additive)',
'적HP 30%↓: 뎀+20%/lv. 내HP 30%↓: 회복력+10%/lv, 이속+5%/lv (합연산)':'Enemy HP≤30%: DMG+20%/lv. My HP≤30%: Recovery+10%/lv, Move SPD+5%/lv (additive)',
'DOT 틱뎀 +15%/lv, DOT 지속시간 +10%/lv, DOT 축적률 +5%/lv':'DOT tick DMG +15%/lv, DOT duration +10%/lv, DOT pool rate +5%/lv',
'MP +50/lv, MP회복 +1%/lv':'MP +50/lv, MP regen +1%/lv',
'ST +50/lv, ST회복 +1%/lv':'ST +50/lv, ST regen +1%/lv',
'악의 드롭 +8%/lv':'Malice drop +8%/lv',
'HP +300/lv':'HP +300/lv',
'DEF +20/lv':'DEF +20/lv',
'엘리트/보스 추가뎀 +10%/lv':'Elite/Boss bonus DMG +10%/lv',
'부활력 -10/lv, 전체 데미지 +5%/lv, HP/MP/ST +100/lv':'Revive power -10/lv, All DMG +5%/lv, HP/MP/ST +100/lv',
'부활확률 +2%/lv, 부활HP +5%/lv, 부활쿨 -30초/lv':'Revive chance +2%/lv, Revive HP +5%/lv, Revive CD -30s/lv',
// --- Phase 37: skill desc ---
'핵심 광역기 — 먼저 배워서 정리력 확보':'Core AoE — learn first for mob clearing',
'악의 사냥 + 보호자 → 합체: 칼날 해방':'Malice Hunt + Guardian → Fuse: Blade Liberation',
'폭독혈 추가 → 합체: 독혈 해방 (칼날+독)':'Plague Burst → Fuse: Plague Liberation (blade+poison)',
'충돌+화염 → 합체: 사슬기동 (무적이동 핵심)':'Impact+Flame → Fuse: Chain Breach (invincible dash core)',
'사슬 체인 확장 → 기동:파쇄/기동:전폭':'Chain expansion → Slam/Thunder combos',
'필살기 1개 선택! 신성폭발(넉백) / 블랙(흡인) / 용암(화상) / 처형(보스킬)':'Pick 1 ultimate! Holy Blast(knockback) / Black Star(pull) / Lava(burn) / Execution(boss kill)',
'멸살광선+만화방창+원소추적탄+전격이동 → 합체: 추적빔':'Omni Beam+Barrage+Elem Missile+Blink → Fuse: Tracking Beam',
'회전참+기폭+대왕치기 → 합체: 지진폭풍':'Whirlwind+Detonate+Giant Slam → Fuse: Slam Storm',
'칼등치기 + 칼등날개 → 합체: 처내기 강화':'Blade Parry + Shield Wing → Fuse: Parry Enhanced',
'해골무덤 + 악의폭풍 → 합체: 해골번개':'Bone Wall + Malice Storm → Fuse: Bone Lightning',
'폭풍소환 + 얼음보주 → 합체: 얼음폭풍':'Malice Mortar + Ice Orb → Fuse: Ice Mortar',
'유령화 이동 + 전기 폭발':'Ghost phase movement + electric burst',
'회복 + 구속 → 합체: 결계의 영역':'Recovery + Prison → Fuse: Ward Domain',
'지진폭풍+추적암전 → 6단합체: 폭풍빔':'Slam Storm → 6-Fuse: Storm Beam',
'아이스스톰 추가 → 합체: 신성빙결':'Ice Storm → Fuse: Holy Ice',
'암흑기둥 + 가시덫 → 합체: 기둥가시. 대왕치기2는 기둥강타/지옥강타용':'Dark Pillar + Spike Trap → Fuse: Pillar Spike. Giant Slam 2 for Pillar Slam/Inferno Slam',
'기동칼날개 추가 → 5단합체: 기동:칼날개':'Chain Bladewing → 5-Fuse: Maneuver:Bladewing',
'STR 스케일. 3회 충전 + Lv3마다 사거리 1단계↑(최대4단). 이동 중 무적, 통과 적에 데미지+그로기 (쿨 5초)':'STR scale. 3 stocks + range tier up every Lv3 (max 4). Invincible while moving, DMG+groggy on pass-through (CD 5s)',
'INT 스케일. 이동 경로에 화염길 생성(3초 DOT). 통과 적 화상. MP 소모. 합체 시 착지 폭발':'INT scale. Fire trail on dash path (3s DOT). Burns passed enemies. MP cost. Fuse: landing explosion',
'5초간 유령화 — 무적+이동. 통과한 적/탄막 수만큼 종료 시 암전 폭발(+10%/회) + 전기줄기 방사(3회 체인). 카운트 캡=Lv×5(최대50). 쿨 20초. Lv당 뎀+15% 범위+10':'5s ghost form — invincible+move. Blackout explosion on end (+10%/enemy passed) + lightning arc (3 chains). Count cap=Lv×5 (max 50). CD 20s. Per Lv DMG+15% range+10',
'[이동기] 방향키 더블탭으로 발동. 경직/기절 중에도 탈출 가능. 500유닛 순간이동, 무적(15프레임). MP(10+Lv×5). 1렙10충전, 렙당+1. 쿨 8초→Lv당-0.5초(최소3초). 착지 시 전류장판(10초+Lv×0.5초): INT 틱뎀 + 방어력↓(1렙10%, 렙당+5%, 캡50%)':'[Mobility] Double-tap to activate. Escapes stagger/stun. 500-unit blink, invincible 15f. MP(10+Lv×5). Lv1=10 stocks, +1/Lv. CD 8s→-0.5s/Lv (min 3s). Landing shock field(10s+Lv×0.5s): INT tick DMG + DEF↓(Lv1=10%, +5%/Lv, cap 50%)',
'좌클 스킬: 기본공격에 3단 콤보 초승달 검기 추가. ST 10+Lv당2. Lv당 뎀+10% 거리+15px':'LMB skill: adds 3-hit crescent ki blade combo to basic attack. ST 10+2/Lv. Per Lv DMG+10% range+15px',
'[기본: E] 어둠 마법 오브 발사. 범위폭발. 넉백 0.5%. Lv당 크기+50% (뎀은 _skMul 계수 적용)':'[Default: E] Dark magic orb fired. AoE explosion. Knockback 0.5%. Per Lv size+50% (DMG uses _skMul)',
'무기 홀드 → 전진 회전 공격. 360도 광역, ST 지속소모. Lv당 범위+5 뎀+5%':'Hold weapon → forward spin attack. 360° AoE, continuous ST drain. Per Lv range+5 DMG+5%',
'패링 3초 홀드 → 흡수 데미지 광역 폭발. Lv당 범위+15 (1렙150, 10렙285)':'Parry 3s hold → absorbed DMG AoE explosion. Per Lv range+15 (Lv1: 150, Lv10: 285)',
'우클 처내기 강화. Lv당 반사 데미지 +10%. 홀드 시 연사':'RMB swipe enhanced. Per Lv reflect DMG +10%. Hold for rapid fire',
'[고정: T 자동] 물리 바늘 3방향 3발 발사. 관통 없음':'[Fixed: T auto] 3 physical needles 3-way spread. No pierce',
'[고정: E] 1발 직선 레이저. +만화방창 → 만화광선(3발 꽈배기). +원소추적탄 → 추적암전(6발 유도)':'[Fixed: E] 1 straight laser. +Barrage → Omni Beam (3 spiral). +Elem Seeker → Homing Dark (6 homing)',
'E탭 마법을 6원소 유도 미사일로 변경. 곡선 궤적으로 적을 추적. 레벨당 사거리+20 (뎀은 _skMul 계수 적용)':'Changes E-tap magic to 6-element homing missiles. Curved trajectory tracking enemies. Per Lv range+20 (DMG uses _skMul)',
'3초마다 악의 구체 생성(1렙 2개). 몸에 밀착하여 적 투사체를 자동 방어(파괴). 레벨당 구체+1':'Spawns malice orbs every 3s (Lv1: 2 orbs). Orbits body, auto-blocks (destroys) enemy projectiles. Per Lv orb+1',
'유도 물리 칼날 1발 (악의30+ST50). 관통률 800+Lv×20+장비. 지속뎀 5초. 쿨 15초':'1 homing physical blade (malice 30 + ST 50). Pierce 800+Lv×20+gear. DOT 5s. CD 15s',
'어둠 소용돌이 소환 (마우스 조준 설치, MP 소모, 쿨 11초, INT 스케일링, 1렙 200범위 +30/렙, 5초 지속, 적 흡인)':'Summon dark vortex (mouse-aim placement, MP cost, CD 11s, INT scale, Lv1 range 200 +30/Lv, 5s duration, pulls enemies)',
'포격식 조준 → 원형 해골무덤 소환. 2스택 (15초/1충전, Lv10→3스택). 둘레에서 뼈가 솟아 공간을 감쌈. 솟을 때 데미지. 적/투사체 차단. 악의 12. Lv당 범위+5% 지속+0.3초':'Artillery-aim → circular bone tomb. 2 stocks (15s/charge, Lv10→3 stocks). Bones rise around perimeter. DMG on rise. Blocks enemies/projectiles. Malice 12. Per Lv range+5% duration+0.3s',
'오망성 시전 → 신성 빛기둥 대폭발. 범위 1500+Lv×100px. 범위 끝까지 넉백(주 성능). 거리감쇠 50%. 스턴 2초. Lv당 뎀+10%. (MP 30%, 쿨 120초)':'Pentagram cast → holy light pillar mega-explosion. Range 1500+Lv×100px. Full-range knockback (main feature). 50% distance falloff. Stun 2s. Per Lv DMG+10%. (MP 30%, CD 120s)',
'검은 오망성 소환. 7초(+Lv당0.5초) 강력 흡인 (데미지 없음, 순수 유틸). 범위 1500+Lv×100px. 흡인력 기본5+Lv당0.5. (MP 30%, 쿨 120초)':'Summon black pentagram. 7s (+0.5s/Lv) strong pull (no DMG, pure utility). Range 1500+Lv×100px. Pull force base 5+0.5/Lv. (MP 30%, CD 120s)',
'빨간 오망성 시전 → 범위 1500+Lv×100px 화염폭발+10초간 화상. 틱당 적 최대HP 1.75%(+Lv당+1.5%). 10초 20틱. 거리감쇠 30%. Lv당 초기뎀+10%. (MP 30%, 쿨 120초)':'Red pentagram cast → range 1500+Lv×100px fire explosion+10s burn. Per tick enemy maxHP 1.75%(+1.5%/Lv). 10s 20 ticks. 30% distance falloff. Per Lv initial DMG+10%. (MP 30%, CD 120s)',
'X키: 그로기 보스 전용. 보스 현재HP 20%(+2%/Lv) + 무기뎀×30(+21%/Lv, 20Lv=150배) + 보스HP 30% 순수뎀. 섬광 돌진 연출. HP/MP/ST 10% 소모. 쿨 5초':'X key: Groggy boss only. Boss current HP 20%(+2%/Lv) + weapon DMG×30(+21%/Lv, Lv20=150×) + boss HP 30% pure DMG. Flash dash. HP/MP/ST 10% cost. CD 5s',
'얼음 속에 들어가 무적 상태. 다시 누르면 파쇄 → 얼음칼날 48발 부채꼴 방사 (MP 40, 쿨 20초). Lv당 칼날+2 뎀+15%':'Enter ice — invincible. Re-press to shatter → 48 ice blades fan spread (MP 40, CD 20s). Per Lv blades+2 DMG+15%',
'[고정: T 자동] 초고속 바늘 연발. 1렙 2발, 5렙마다 +1발. 관통 없음. ST 8. 쿨 1.5초. Lv당 뎀+100%':'[Fixed: T auto] Ultra-fast needles burst. Lv1 2 shots, +1 per 5 levels. No pierce. ST 8. CD 1.5s',
'E홀드: 직선 관통 레이저 채널링. MP 8+Lv/초 지속소모. 폭160+(Lv×10)px, 사거리1200+Lv×80. 관통+감전. Lv당 뎀+21%':'E hold: Straight piercing laser channeling. MP 8+Lv/s drain. Width 160+(Lv×10)px, range 1200+Lv×80. Pierce+shock. Per Lv DMG+21%',
'E탭: 화염 유도빔 발사. MP10. 쿨1초(DEX 스케일). 100% 관통+유도+화상. Lv당 사거리+50 뎀+12%':'E tap: fire homing beam. MP 10. CD 1s (DEX scale). 100% pierce+homing+burn. Per Lv range+50 DMG+12%',
'E: 10초간 대지 진동. 범위 내 용암 기둥이 순차적으로 솟아올라 화상+틱 데미지. MP 100. 쿨 12초. Lv당 범위+10% 뎀+12%':'E: 10s ground tremor. Lava pillars rise sequentially in range — burn+tick DMG. MP 100. CD 12s. Per Lv range+10% DMG+12%',
'독혈 칼날 1발 발사: 관통률 기본 800+Lv×20 + 장비 bowPierce×300/패시브 pPierce×30 반영, +100 보정. 전염+마지막 적 처형. 감염 사망 시 폭발+연쇄 전염. 악의 15. 사거리 4000. 쿨 15초(Lv당-0.5초)':'Fire 1 poison-blood blade: base pierce rate 800+Lv×20 with bowPierce×300 and pPierce×30 scaling, plus +100 bonus. Plague+execute last enemy. Infected death → explosion+chain plague. Malice 15. Range 4000. CD 15s (-0.5s/Lv)',
'마우스 조준 설치. 쿨 20초. 화면 내 클릭 위치에 암전나선 (3초, 10틱, 틱당 100+Lv*20). Lv당 범위+22. 같은 지역 중복 불가':'Mouse-aim placement. CD 20s. Dark spiral at click pos (3s, 10 ticks, 100+Lv*20/tick). Per Lv range+22. No stacking same area',
'현재 위치에 9개 기둥 순차 발동. 5초간 악의 기둥을 소환하여 반경 내 적에게 지속 암전 데미지+감속. 범위 250+(Lv-1)×22. 대왕치기와 합체→기둥강타. 쿨 15초':'9 pillars activate sequentially at current pos. 5s dark pillars deal sustained dark DMG+slow to enemies in radius. Range 250+(Lv-1)×22. Fuses with Giant Slam → Pillar Strike. CD 15s',
'현재 위치에 회복의 영역 설치 (12초 지속). 땅 위: HP/MP/ST 초당+10 리젠 + 회복력 2배 + 쿨다운 속도 2배. 쿨 30초. Lv당 범위+20 지속+0.5초':'Place holy domain at current pos (12s duration). On ground: HP/MP/ST +10/s regen + 2x recovery + 2x CD speed. CD 30s. Per Lv range+20 duration+0.5s',
'범위 내 몬스터 부활력 -15%~30%(Lv1=15%, Lv10=30%). Lv1 범위400, Lv10 범위697. Lv당 범위+33. 쿨 30초. 지속 10초':'Monsters in range: revive power -15%~30%(Lv1=15%, Lv10=30%). Lv1 range 400, Lv10 range 697. Per Lv range+33. CD 30s. Duration 10s',
'마우스 조준 설치. 2스택 (15초/1충전, Lv10→3스택). 범위 내 빙결 저항 -50%, 빙결 게이지 급속 축적. 3초 지속. MP 40. Lv당 범위+22 축적+10%':'Mouse-aim placement. 2 stocks (15s/charge, Lv10→3 stocks). Freeze resist -50% in range, rapid freeze gauge buildup. 3s duration. MP 40. Per Lv range+22 buildup+10%',
'땅을 내리쳐 원형 진동파 발생(범위400). 일반몹에게 큰 포이즈 피해, 보스 체간 파괴에 강함. 회전기폭과 합체→지진폭풍!':'Slam ground → circular shockwave (range 400). High poise DMG to mobs, strong posture break vs bosses. Fuses with Whirlwind Detonate → Earthquake Storm!',
'땅을 내리쳐 원형 진동파 발생(범위400). 일반몹에게 큰 포이즈 피해, 보스 체간 파괴에 강함. 악의기둥과 합체→기둥강타!':'Slam ground → circular shockwave (range 400). High poise DMG to mobs, strong posture break vs bosses. Fuses with Dark Pillar → Pillar Slam!',
'사슬기동 중 E → 즉시 착지하며 화염폭발. 범위200~350 INT 스케일 화염 마법데미지+넉백. 이동거리에 비례해 데미지↑(최대 x4.0). MP 소모. Lv당 범위+16 뎀+12%':'During chain dash E → instant land with fire explosion. Range 200~350 INT scale fire magic DMG+knockback. DMG scales with travel distance (max x4.0). MP cost. Per Lv range+16 DMG+12%',
'사슬기동 중 우클릭 → 땅 내려찍기. 범위200~350 데미지x8 그로기x6. 이동거리 비례 최대x6. 일반몹 즉시 기절(5초), 보스 체간 대량 삭감. Lv당 범위+16 데미지+15% 그로기+15%':'During chain dash RMB → ground slam. Range 200~350 DMG x8 groggy x6. Distance scale max x6. Instant stun mobs (5s), massive boss posture break. Per Lv range+16 DMG+15% groggy+15%',
'[히든: 5성 dimRush 합체] 사슬기동 중 좌클릭 → 이동 중 전방 광역 베기+출혈. STR 스케일 물리데미지. 다단히트. Lv당 뎀+12% 범위+15':'[Hidden: 5-star dimRush fuse] During chain dash LMB → forward AoE slash+bleed while moving. STR scale physical DMG. Multi-hit. Per Lv DMG+12% range+15',
'[히든: 암전나선 합체] Q 홀드 시 보호막이 점점 커지며 HP 초당 10% 회복. 보호막 크기에 비례해 데미지 감소. MP 소모':'[Hidden: Dark Spiral fuse] Q hold: shield grows over time + HP 10%/s regen. DMG reduction scales with shield size. MP cost',
'[히든: 암전나선 합체] E로 조준, 클릭 설치. 에너지 쐐기를 지상에 꽂아 회전+데미지. MP100. 1차지 쿨10초. 5초+Lv당0.5초 지속. Lv당 거리+50':'[Hidden: Dark Spiral fuse] E to aim, click to place. Energy wedge planted on ground — rotates+DMG. MP 100. 1 charge CD 10s. 5s+0.5s/Lv duration. Per Lv range+50',
'[고정: 칼등치기 합체] 보유 시 칼등치기에 전방 충격파 자동 발동. 제자리 처내기. 쿨 5초. Lv당 뎀+12% 범위+20':'[Fixed: Blade Parry fuse] When owned, swipe auto-triggers forward shockwave. Stationary swipe. CD 5s. Per Lv DMG+12% range+20',
'현재 위치에 파쇄 영역 설치 (10초). 범위 내 적 물리방어력 -10%. 쿨 25초. Lv당 범위+22 효과+1% 지속+0.3초':'Place shatter domain at current pos (10s). Enemy phys DEF -10% in range. CD 25s. Per Lv range+22 effect+1% duration+0.3s',
'현재 위치에 침식 영역 설치 (10초). 범위 내 적 마법저항력 -10%. 쿨 25초. Lv당 범위+22 효과+1% 지속+0.3초':'Place corrosion domain at current pos (10s). Enemy magic resist -10% in range. CD 25s. Per Lv range+22 effect+1% duration+0.3s',
'현재 위치에 관통 영역 설치 (10초). 범위 내 적 투사체저항력 -10%. 쿨 25초. Lv당 범위+22 효과+1% 지속+0.3초':'Place pierce domain at current pos (10s). Enemy projectile resist -10% in range. CD 25s. Per Lv range+22 effect+1% duration+0.3s',
'현재 위치에 부활 영역 설치 (10초). 영역 안에서 부활력 +10%. 쿨 25초. Lv당 범위+22 효과+1% 지속+0.3초':'Place revival domain at current pos (10s). Revive power +10% inside zone. CD 25s. Per Lv range+22 effect+1% duration+0.3s',
'[고정: Space] 현재 위치에 가시덫 설치 (1렙 반경200, 10렙398). 슬로우 70%(+2%/Lv, 최대90%)+출혈. INT×magicRef×3(+10%/Lv). 악의 10, 쿨 10초. Lv당 범위+22':'[Fixed: Space] Place spike trap at current pos (Lv1 radius 200, Lv10 398). Slow 70%(+2%/Lv, max 90%)+bleed. INT×magicRef×3(+10%/Lv). Malice 10, CD 10s. Per Lv range+22',
'[고정: E, Lv300 해금] 유도 파란콩 50발 순차 발사 (5초간). MP 100(+1.5/Lv) 소모. 적 추적. 쿨 5초. Lv당 사거리+30 (뎀은 _skMul 계수 적용)':'[Fixed: E, unlock Lv300] 50 homing blue shots fired sequentially (over 5s). MP 100(+1.5/Lv) cost. Tracks enemies. CD 5s. Per Lv range+30 (DMG uses _skMul)',
'[히든: E, Lv700 해금] 홀드 시 3단계 차지 범위폭발 (0.5/1.0/1.5초). 범위 600/1000/1400px. 3단 만충 자동폭발. INT 스케일, 무속성':'[Hidden: E, unlock Lv700] Hold for 3-stage charge AoE explosion (0.5/1.0/1.5s). Range 600/1000/1400px. Stage 3 full charge auto-detonates. INT scale, no element',
'유령 허수아비를 소환하여 유도탄막 어그로를 끈다. 탄막을 흡수해 자원 축적 (기본 20개, Lv당+3). 1개당 HP/MP/ST 각 100. R키로 회수. 쿨 10초':'Summon phantom scarecrow to draw homing projectile aggro. Absorbs projectiles for resource buildup (base 20, +3/Lv). Per absorbed: HP/MP/ST +100 each. R key to retrieve. CD 10s',
'폭발 허수아비 설치. 탄막을 흡수하고 재입력 시 폭발! 1스택당 (INT마법뎀+탄막뎀)×10 마법데미지. 범위 250+흡수×25 (최대1000). 최대흡수 1렙20~20렙60. 쿨 10초':'Place explosive scarecrow. Absorbs projectiles, re-press to detonate! Per stack: (INT magic DMG + proj DMG)×10. Range 250+absorbed×25 (max 1000). Max absorb Lv1=20~Lv20=60. CD 10s',
'[선택: 1~4번, Lv500 해금] 현재 위치에 공성쇠뇌 터렛 설치. 재입력 시 철거. 설치 중 플레이어 석궁 사용 불가 (터렛만 발사). 데미지+50%, 공속+50%, 사거리+50%. ST 100. 쿨 10초. Lv당 뎀+5% 공속+5% 사거리+5%':'[Select: 1~4, unlock Lv500] Deploy siege crossbow turret at current pos. Re-press to dismantle. While deployed: player crossbow disabled (turret fires only). DMG+50%, ATK SPD+50%, range+50%. ST 100. CD 10s. Per Lv DMG+5% ATK SPD+5% range+5%',
'[Ctrl, Lv500 해금] 발동 시 3초 전 상태로 되돌린다. 위치/HP/MP/ST 완전 복원. Lv당 되감기+0.105초 (1렙 3초, 20렙 5초). MP 50(+5/Lv, 20렙150). 쿨 45초':'[Ctrl, unlock Lv500] Rewind to state from 3s ago. Restores position/HP/MP/ST. Per Lv rewind+0.105s (Lv1=3s, Lv20=5s). MP 50(+5/Lv, Lv20=150). CD 45s',
'[선택: 1~4번] 마우스 조준 → 전기창을 땅에 꽂는다. 5스택(12초/1충전, Lv10→6스택). 창끼리 600px 이내면 전류 아크 발생, 경로 위 적에게 감전 틱 데미지. MP 50. 지속 10초(+0.5초/Lv). Lv당 아크뎀+10%':'[Select: 1~4] Mouse aim → plant electric spear on ground. 5 stocks (12s/charge, Lv10→6). Spears within 600px create lightning arcs dealing shock tick DMG to enemies on path. MP 50. Duration 10s (+0.5s/Lv). Per Lv arc DMG+10%',
'성능 등급:':'Perf Grade:',
'벤치 FPS:':'Bench FPS:',
// --- CAT-82: skill panel labels ---
'스킬 정보':'Skill Info',
'타입':'Type',
'미습득':'Not Learned',
'SP 비용':'SP Cost',
'악의 비용':'Malice Cost',
'쿨다운':'Cooldown',
'요구 레벨':'Req. Lv',
'기본 참조뎀':'Base Reference',
'스탯 배율':'Stat Mult',
'패시브 배율':'Passive Mult',
'레벨 배율':'Skill Lv Mult',
'예상 평균 뎀':'Estimated Avg DMG',
'치명타':'Critical',
'치명타 확률':'Crit Rate',
'치명타 배율':'Crit Dmg',
'유효 배율':'Effective Mult',
'스킬 고유':'Skill Specific',
'1타 배율':'1-Hit Mult',
'2타 배율':'2-Hit Mult',
'3타 배율':'3-Hit Mult',
'레벨당 뎀':'Per Lv DMG',
'검기 거리':'Crescent Range',
'레벨당 거리':'Lv Range Bonus',
'ST/틱':'ST/Tick',
'레벨당 크기':'Per Lv Size',
'넉백':'Knockback',
'충전 시간':'Charge Time',
'레벨당 범위':'Per Lv Range',
'관통률':'Pierce Rate',
'지속뎀':'DOT Duration',
'무한':'Infinite',
'타격 형식':'AoE Type',
'진동파':'Shockwave',
'스태거':'Stagger',
'높음':'High',
'스톡':'Stocks',
'기둥 수':'Pillars',
'지속':'Duration',
'반경':'Radius',
'슬로우':'Slow',
'활':'Bow',
// --- CAT-83: affix desc labels ---
'독 DoT':'Poison DoT',
'화상 DoT':'Fire DoT',
'빙결 DoT+감속':'Ice DoT+Slow',
'연쇄전격':'Chain Lightning',
'저주(힐차단)':'Curse(Heal Block)',
'방어무시':'Armor Ignore',
'치명타율':'Crit Rate',
'스태거+':'Stagger+',
'체인타겟+':'Chain Target+',
'처치 후 뎀+':'Kill DMG+',
'크리폭발(ATK×)':'Crit Explode(ATK×)',
'원소뎀+':'Elem DMG+',
'공격속도+':'Atk Spd+',
'패리보너스+':'Parry Bonus+',
'추적콤보+10':'Track Combo+10',
'작살뎀+':'Harpoon DMG+',
'스킬뎀+':'Skill DMG+',
'쿨다운-':'CD-',
'방어력+':'DEF+',
'쉴드+':'Shield+',
'이동속도+':'Move Spd+',
'크리확률+':'Crit Rate+',
'크리배율+':'Crit Dmg+',
'화염저항':'Fire Res',
'빙결저항':'Ice Res',
'암전저항':'Lightning Res',
'암흑저항':'Dark Res',
'독저항':'Poison Res',
'전원소저항':'All Elem Res',
'물리DR':'Phys DR',
'반사%':'Reflect%',
'가시뎀':'Thorns DMG',
'배리어':'Barrier',
'CC저항':'CC Resist',
'위기뎀+':'Crisis DMG+',
'피격반격':'Hit Counter',
'패링폭발(ATK×)':'Parry Burst(ATK×)',
'체간파괴뎀+':'Poise Break DMG+',
'원소전환':'Elem Convert',
'상태이상해제':'Status Clear',
'불굴(1회생존)':'Tenacity(Survive×1)',
'부활(HP회복)':'Revive(HP Restore)',
'드롭률+':'Drop Rate+',
'경험치+':'EXP+',
'골드+':'Gold+',
'포션회복+':'Potion Heal+',
'사슬게이지+':'Chain Gauge+',
'부활억제':'Anti-Revive',
'부활력+':'Revival Pow+',
'부활쿨-':'Revival CD-',
'최대HP%+':'Max HP%+',
'HP리젠+':'HP Regen+',
'회복력+':'Heal Pow+',
'마법뎀+':'Magic DMG+',
'MP소비-':'MP Cost-',
'화염뎀%+':'Fire DMG%+',
'화염관통%':'Fire Pen%',
'적중화상':'On-Hit Burn',
'크리화폭':'Crit Fire Burst',
'화상지속+':'Burn Duration+',
'화염뎀보너스':'Fire DMG Bonus',
'빙결뎀%+':'Ice DMG%+',
'빙결관통%':'Ice Pen%',
'적중빙결':'On-Hit Freeze',
'크리빙폭':'Crit Ice Burst',
'빙결지속+':'Freeze Duration+',
'빙결뎀보너스':'Ice DMG Bonus',
'뇌전뎀%+':'Lightning DMG%+',
'뇌전관통%':'Lightning Pen%',
'적중감전':'On-Hit Shock',
'크리뇌폭':'Crit Lightning Burst',
'감전지속+':'Shock Duration+',
'뇌전뎀보너스':'Lightning DMG Bonus',
'암흑뎀%+':'Dark DMG%+',
'암흑관통%':'Dark Pen%',
'적중저주':'On-Hit Curse',
'크리암폭':'Crit Dark Burst',
'저주지속+':'Curse Duration+',
'암흑뎀보너스':'Dark DMG Bonus',
'독뎀%+':'Poison DMG%+',
'독관통%':'Poison Pen%',
'적중중독':'On-Hit Poison',
'크리독폭':'Crit Poison Burst',
'독지속+':'Poison Duration+',
'독뎀보너스':'Poison DMG Bonus',
'근접뎀%+':'Melee DMG%+',
'원거리뎀%+':'Ranged DMG%+',
'마법뎀%+':'Magic DMG%+',
'빔뎀%+':'Beam DMG%+',
'DoT뎀%+':'DoT DMG%+',
'투사체뎀%+':'Proj DMG%+',
'범위반경+':'AoE Radius+',
'근접크리+':'Melee Crit+',
'마법크리+':'Magic Crit+',
'석궁크리+':'Xbow Crit+',
'근접공속+':'Melee Spd+',
'석궁공속+':'Xbow Spd+',
'시전속도+':'Cast Spd+',
'전속성관통':'All Elem Pen',
'쉴드관통':'Shield Pen',
'방어력깎기':'Armor Shred',
'투사체속도+':'Proj Speed+',
'적중시화구':'On-Hit Fireball',
'적중시연쇄뇌격':'On-Hit Chain Lightning',
'적중빙결%':'On-Hit Freeze%',
'적중스턴%':'On-Hit Stun%',
'적중중독%':'On-Hit Poison%',
'적중출혈%':'On-Hit Bleed%',
'적중약화%':'On-Hit Weaken%',
'적중감속%':'On-Hit Slow%',
'적중표적%':'On-Hit Mark%',
'크리폭발(HP%)':'Crit Explode(HP%)',
'크리연쇄(HP%)':'Crit Chain(HP%)',
'크리빙결%':'Crit Freeze%',
'크리HP+':'Crit HP+',
'크리MP+':'Crit MP+',
'크리쉴드+':'Crit Shield+',
'피격방어+':'Hit DEF+',
'반격가시':'Counter Thorns',
'빙결파동%':'Ice Nova%',
'자동암흑막':'Auto Dark Shield',
'주기치유':'Periodic Heal',
'시체폭발%':'Corpse Explode%',
'회피뎀+':'Dodge DMG+',
'패링폭발%':'Parry Burst%',
'블록HP+':'Block HP+',
'블록MP+':'Block MP+',
'회전참뎀+':'Whirlwind DMG+',
'옴니빔뎀+':'Omni Beam DMG+',
'화구뎀+':'Fireball DMG+',
'미사일뎀+':'Missile DMG+',
'청탄뎀+':'Blue Shot DMG+',
'폭렬탄뎀+':'Blast Shot DMG+',
'지옥광선뎀+':'Hell Ray DMG+',
'악의폭풍뎀+':'Malice Storm DMG+',
'연쇄참뎀+':'Chain Slash DMG+',
'거인강타뎀+':'Giant Slam DMG+',
'유령보행뎀+':'Ghost Walk DMG+',
'악의박격뎀+':'Malice Mortar DMG+',
'화염오라뎀+':'Fire Aura DMG+',
'빙구뎀+':'Ice Orb DMG+',
'화염빔뎀+':'Fire Beam DMG+',
'악의사냥뎀+':'Malice Hunt DMG+',
'암흑기둥뎀+':'Dark Pillar DMG+',
'역병뎀+':'Plague DMG+',
'가시오라뎀+':'Spike Aura DMG+',
'연쇄돌격뎀+':'Chain Assault DMG+',
'회피확률+':'Dodge Rate+',
'회피쿨-':'Dodge CD-',
'쉴드%+':'Shield%+',
'쉴드리젠%+':'Shield Regen%+',
'쉴드쿨-':'Shield CD-',
'HP리젠%+':'HP Regen%+',
'ST리젠+':'ST Regen+',
'ST리젠%+':'ST Regen%+',
'MP리젠+':'MP Regen+',
'MP리젠%+':'MP Regen%+',
'화염DR':'Fire DR',
'빙결DR':'Ice DR',
'뇌전DR':'Lightning DR',
'암흑DR':'Dark DR',
'독DR':'Poison DR',
'전체DR':'All DR',
'엘리트DR':'Elite DR',
'스턴저항':'Stun Res',
'감속저항':'Slow Res',
'넉백저항':'KB Res',
'돌진거리+':'Dash Range+',
'돌진쿨-':'Dash CD-',
'전투이속+':'Combat MSpd+',
'비전투이속+':'Out-Combat MSpd+',
'습득범위+':'Pickup Range+',
'전스탯+':'All Stats+',
'적중자원+':'On-Hit Resource+',
'화염최대저항+':'Fire Max Res+',
'빙결최대저항+':'Ice Max Res+',
'뇌전최대저항+':'Lightning Max Res+',
'암흑최대저항+':'Dark Max Res+',
'독최대저항+':'Poison Max Res+',
'스킬쿨-':'Skill CD-',
'물약쿨-':'Potion CD-',
'강화성공+':'Craft Rate+',
'악의획득+':'Malice Gain+',
'악마화뎀+':'Demon DMG+',
'악마화DR':'Demon DR',
'영혼수확+':'Soul Harvest+',
'생명흡혈%':'Life Leech%',
'과치유→쉴드':'Overheal→Shield',
'만마나뎀+':'Full MP DMG+',
'이동DR':'Move DR',
'정지뎀+':'Stationary DMG+',
'회피후뎀+':'After Dodge DMG+',
'패링쉴드+':'Parry Shield+',
'콤보보너스+':'Combo Bonus+',
'HP≥70%뎀+':'HP≥70% DMG+',
'적HP≤30%뎀+':'Foe HP≤30% DMG+',
'HP100%뎀+':'HP100% DMG+',
'HP≤35%뎀+':'HP≤35% DMG+',
'적HP≤20%뎀+':'Foe HP≤20% DMG+',
'근접뎀+':'Melee DMG+',
'원거리뎀+':'Ranged DMG+',
'스턴적뎀+':'vs Stunned DMG+',
'빙결적뎀+':'vs Frozen DMG+',
'화상적뎀+':'vs Burning DMG+',
'중독적뎀+':'vs Poisoned DMG+',
'저주적뎀+':'vs Cursed DMG+',
'감속적뎀+':'vs Slowed DMG+',
'보스뎀+':'Boss DMG+',
'엘리트뎀+':'Elite DMG+',
'일반몹뎀+':'Mob DMG+',
'선제뎀+':'First Strike DMG+',
'물리흡혈%':'Phys Leech%',
'마나흡수%':'Mana Leech%',
'ST흡수%':'ST Leech%',
'적중HP+':'On-Hit HP+',
'처치HP+':'On-Kill HP+',
'처치MP+':'On-Kill MP+',
'처치ST+':'On-Kill ST+',
'처치시폭발':'On-Kill Explode',
'처치이속+':'On-Kill MSpd+',
'HP≥70%방어+':'HP≥70% DEF+',
'HP≤50%이속+':'HP≤50% MSpd+',
'DoT피해감소':'DoT DMG Reduce',
'보스피해감소':'Boss DMG Reduce',
'근접피해감소':'Melee DMG Reduce',
'원거리피해감소':'Ranged DMG Reduce',
'처치HP회복':'On-Kill HP Restore',
'처치쉴드회복':'On-Kill Shield Restore',
'ST소비-':'ST Cost-',
'HP≥70%공격+':'HP≥70% ATK+',
'HP≤35%흡혈':'HP≤35% Leech',
'보스추가뎀':'vs Boss DMG+',
'엘리트추가뎀':'vs Elite DMG+',
'공격력+':'ATK+',
'크리뎀+':'Crit DMG+',
// --- CAT-84/85/86: affix names + implicit + legendary ---
'물리방패의':'Physical Shield',
'지속의':'Stamina',
'마나의':'Mana',
'원소수호의':'Elem Guard',
'행운의':'Fortune',
'근성의':'Grit',
'풍요의':'Abundance',
'약자포식의':'Predator',
'만혈의':'Full Life',
'사선의':'Low Life',
'처형의':'Execute',
'근접살의':'Melee DMG',
'원거리의':'Ranged',
'경직파의':'Stagger Break',
'동파의':'Freeze Strike',
'연소의':'Burning',
'맹독살의':'Venom Slayer',
'저주살의':'Curse Slayer',
'구속의':'Binding',
'왕살의':'Boss Slayer',
'정예살의':'Elite Slayer',
'군살의':'Mob Slayer',
'선제의':'First Strike',
'흡혈의':'Vampirism',
'흡마의':'Mana Leech',
'흡정의':'Stamina Leech',
'타격재생의':'Hit Regen',
'처치회복의':'Kill Recovery',
'처치흡마의':'Kill Mana Leech',
'처치활력의':'Kill Stamina',
'처치폭발의':'Kill Explosion',
'처치질주의':'Kill Sprint',
'건강방어의':'Healthy Defense',
'중상보호의':'Wounded Shield',
'위기질주의':'Crisis Sprint',
'지속피해방어의':'DoT DR',
'왕피해방어의':'Boss DMG DR',
'근접방어의':'Close DR',
'원거리방어의':'Ranged DR',
'처치생명의':'Kill HP',
'처치수호의':'Kill Shield',
'화염강화의':'Fire Amp',
'화염관통의':'Fire Pierce',
'발화의':'Ignition',
'화염폭발의':'Fire Burst',
'맹화의':'Blaze',
'화염의힘':'Fire Power',
'빙결강화의':'Ice Amp',
'빙결관통의':'Ice Pierce',
'동결의':'Freeze',
'빙결폭발의':'Ice Burst',
'영빙의':'Permafrost',
'빙결의힘':'Ice Power',
'뇌전강화의':'Thunder Amp',
'뇌전관통의':'Thunder Pierce',
'감전의':'Shock',
'뇌전폭발의':'Thunder Burst',
'낙뢰의':'Thunderbolt',
'뇌전의힘':'Thunder Power',
'암흑강화의':'Dark Amp',
'암흑관통의':'Dark Pierce',
'침식의':'Erosion',
'암흑폭발의':'Dark Burst',
'심연의':'Abyss',
'암흑의힘':'Dark Power',
'맹독강화의':'Venom Amp',
'독관통의':'Poison Pierce',
'중독의':'Poisoning',
'독폭발의':'Poison Burst',
'맹독지속의':'Venom Duration',
'독의힘':'Poison Power',
'격투의':'Melee',
'원사의':'Ranged Shot',
'주술의':'Spell',
'광선의':'Beam',
'탄도의':'Ballistic',
'확산의':'AoE Radius',
'근접회심의':'Melee Crit',
'마법회심의':'Spell Crit',
'사격회심의':'Ranged Crit',
'근접쾌속의':'Melee Speed',
'사격쾌속의':'Ranged Speed',
'영창의':'Chanting',
'전속성관통의':'All-Elem Pierce',
'쉴드파괴의':'Shield Bypass',
'갑옷분쇄의':'Armor Shred',
'탄속의':'Proj Speed',
'화구발사의':'Fireball Launch',
'연쇄뇌격의':'Chain Lightning',
'동결타의':'Freeze Strike',
'경직타의':'Stagger Strike',
'독침의':'Poison Sting',
'출혈의':'Bleed',
'약화의':'Weakness',
'둔화의':'Slow',
'표적의':'Marking',
'회심폭발의':'Crit Explosion',
'회심연쇄의':'Crit Chain',
'회심빙결의':'Crit Freeze',
'회심치유의':'Crit Heal',
'회심영력의':'Crit Mana',
'회심수호의':'Crit Shield',
'피격강화의':'Hit Boost',
'반격가시의':'Counter Thorns',
'빙결파동의':'Ice Nova',
'암흑보호의':'Dark Shield',
'치유파동의':'Heal Pulse',
'시체폭발의':'Corpse Explosion',
'회피반격의':'Dodge Counter',
'패링폭파의':'Parry Shatter',
'블록치유의':'Block Heal',
'블록영력의':'Block Mana',
'회전참강화':'Spin Slash Boost',
'옴니빔강화':'Omni Beam Boost',
'화구강화':'Fireball Boost',
'미사일강화':'Missile Boost',
'청탄강화':'Blue Shot Boost',
'폭렬탄강화':'Burst Shot Boost',
'지옥광선강화':'Hellray Boost',
'악의폭풍강화':'Malice Storm Boost',
'연쇄참강화':'Chain Slash Boost',
'거인강타강화':'Giant Slam Boost',
'유령보행강화':'Ghost Walk Boost',
'악의박격강화':'Malice Mortar Boost',
'화염오라강화':'Fire Aura Boost',
'빙구강화':'Ice Orb Boost',
'화염빔강화':'Fire Beam Boost',
'악의사냥강화':'Malice Hunt Boost',
'암흑기둥강화':'Dark Pillar Boost',
'역병강화':'Plague Boost',
'가시오라강화':'Thorn Aura Boost',
'연쇄돌격강화':'Chain Assault Boost',
'회피의':'Evasion',
'회피쿨감의':'Dodge CD Red',
'수호력의':'Shield Power',
'수호재생의':'Shield Regen',
'수호쿨감의':'Shield CD Red',
'재생력의':'Regen Power',
'활력재생의':'Stamina Regen',
'마력재생의':'Mana Regen',
'화염보호의':'Fire Shield',
'빙결보호의':'Ice Shield',
'뇌전보호의':'Thunder Shield',
'해독의':'Antidote',
'만물보호의':'All Protection',
'정예보호의':'Elite Shield',
'경직저항의':'Stagger Resist',
'빙결저항의':'Freeze Resist',
'감속저항의':'Slow Resist',
'넉백저항의':'Knockback Resist',
'돌진거리의':'Dash Range',
'돌진쿨감의':'Dash CD Red',
'전투질주의':'Combat Sprint',
'평화질주의':'Peace Sprint',
'습득범위의':'Pickup Radius',
'힘의':'Strength',
'민첩의':'Dexterity',
'지능의':'Intelligence',
'만능의':'Versatile',
'지구력의':'Max Stamina',
'마나력의':'Mana Power',
'타격자원의':'Hit Resource',
'화염한계의':'Fire Cap',
'빙결한계의':'Ice Cap',
'뇌전한계의':'Thunder Cap',
'암흑한계의':'Dark Cap',
'독한계의':'Poison Cap',
'스킬쿨감의':'Skill CD Red',
'물약쿨감의':'Potion CD Red',
'장인의':'Craftsmanship',
'탐욕의':'Greed',
'수련의':'Training',
'수집의':'Gathering',
'악마의힘':'Demon Power',
'악마보호의':'Demon Shield',
'영혼수확의':'Soul Harvest',
'생명흡수의':'Life Absorption',
'과치유수호의':'Overheal Shield',
'만마력의':'Full Mana DMG',
'이동방어의':'Moving DR',
'정지공세의':'Stationary Boost',
'회피공세의':'Post-Dodge Boost',
'패링보호의':'Parry Shield',
'콤보폭발의':'Combo Burst',
'물리타격의':'Phys Strike',
'화염타격의':'Fire Strike',
'빙결타격의':'Ice Strike',
'뇌전타격의':'Thunder Strike',
'암흑타격의':'Dark Strike',
'독타격의':'Poison Strike',
'최소공격의':'Min ATK',
'최대공격의':'Max ATK',
'전투력의':'Combat Power',
'무기사거리의':'Weapon Range',
'활사거리의':'Bow Range',
'이중타의':'Double Strike',
'다중발사의':'Multi Shot',
'관통횟수의':'Pierce Count',
'관통유지의':'Pierce Keep',
'연쇄유지의':'Chain Keep',
'범위확장의':'Splash Range',
'범위피해의':'Splash DMG',
'돌진공격의':'Dash ATK',
'반격공격의':'Counter ATK',
'후방타의':'Backstab',
'침식가속의':'Erosion Speed',
'출혈지속의':'Bleed Duration',
'마법타격의':'Magic Strike',
'주문증폭의':'Spell Amp',
'연살뎀의':'Kill Streak DMG',
'연살속의':'Kill Streak Speed',
'기세의':'Momentum',
'정지공격의':'Static Strike',
'이동공격의':'Mobile Strike',
'패링공세의':'Post-Parry Boost',
'임사폭발의':'Near-Death Burst',
'만기력공의':'Full Stamina ATK',
'만마력공의':'Full Mana ATK',
'신선처치의':'Fresh Kill',
'경직연장의':'Stagger Extension',
'빙결연장의':'Freeze Extension',
'둔화강화의':'Slow Amp',
'독중첩의':'Poison Stack',
'출혈중첩의':'Bleed Stack',
'발화강화의':'Ignite Amp',
'동상강화의':'Frostbite Amp',
'감전강화의':'Shock Amp',
'사선회심의':'Low HP Crit',
'갑옷강화의':'Armor Boost',
'블록흡수의':'Block Absorb',
'방패타격의':'Shield Bash',
'방패경직의':'Shield Stagger',
'격투속의':'Brawl Speed',
'격투회심의':'Brawl Crit',
'격투경직의':'Brawl Stagger',
'하반재생의':'Leg Regen',
'CC단축의':'CC Duration Red',
'돌진타의':'Dash Strike',
'돌진범위의':'Dash AoE',
'은신질주의':'Stealth Sprint',
'회피감쇠의':'Dodge DR',
'속성감쇠의':'Elem DR',
'마나왕관의':'Mana Helm',
'시전왕관의':'Cast Helm',
'쿨감왕관의':'CD Helm',
'경험왕관의':'EXP Helm',
'공생의':'Symbiosis',
'수질의':'Body-Soul',
'회심흡의':'Crit Leech',
'체마의':'HP-Mana',
'체기의':'HP-Stamina',
'마기의':'Mana-Stamina',
'전재생의':'All Regen',
'힘민의':'STR-DEX',
'힘지의':'STR-INT',
'민지의':'DEX-INT',
'운근의':'Fortune-Grit',
'수확의':'Harvest',
'빙화의':'Ice-Fire',
'뇌암의':'Thunder-Dark',
'근마의':'Blade-Magic',
'속성침식의':'Elem Erosion',
'화염반지의':'Fire Ring',
'빙결반지의':'Ice Ring',
'뇌전반지의':'Thunder Ring',
'암흑반지의':'Dark Ring',
'독반지의':'Poison Ring',
'콤보반지의':'Combo Ring',
'처치마나의':'Kill Mana',
'관통반지의':'Pierce Ring',
'만능목걸이의':'Allround Necklace',
'회심목걸이의':'Crit Necklace',
'관통목걸이의':'Pierce Necklace',
'스킬목걸이의':'Skill Necklace',
'콤보한계의':'Combo Max',
'처치치유의':'Kill Heal',
'지구벨트의':'Stamina Belt',
'포션벨트의':'Potion Belt',
'활력벨트의':'Vitality Belt',
'탐욕벨트의':'Greed Belt',
'마나띠의':'Mana Band',
'시전띠의':'Cast Band',
'마력띠의':'Magic Band',
'주술띠의':'Spell Band',
'속성띠의':'Elem Band',
'전사의힘':'Warrior Power',
'전사생명의':'Warrior Life',
'전사흡혈의':'Warrior Leech',
'전사인내의':'Warrior Poise',
'마법사의힘':'Mage Power',
'마법사마나의':'Mage Mana',
'마법사수호의':'Mage Shield',
'마법사속성의':'Mage Elem',
'궁수의힘':'Archer Power',
'궁수사거리의':'Archer Range',
'궁수관통의':'Archer Pierce',
'궁수질주의':'Archer Sprint',
'탱크생명의':'Tank Life',
'탱크방어의':'Tank Defense',
'탱크블록의':'Tank Block',
'탱크가시의':'Tank Thorns',
'암살회심의':'Assassin Crit',
'암살후방의':'Assassin Backstab',
'암살독의':'Assassin Poison',
'암살회피의':'Assassin Dodge',
'종결자의':'The Ender',
'생존자의':'Survivor',
'종결수호의':'End Shield',
'종결회심의':'End Crit',
'종결공격의':'End ATK',
'종결저항의':'End Resistance',
'종결파괴의':'End Destruction',
'종결보호의':'End Protection',
'종결흡혈의':'End Leech',
'종결인내의':'End Poise',
'종결쿨감의':'End CD Red',
'종결경험의':'End EXP',
'종결약탈의':'End Loot',
'종결악의의':'End Malice',
'종결힘의':'End STR',
'종결민첩의':'End DEX',
'종결지능의':'End INT',
'종결행운의':'End LCK',
'종결근성의':'End Grit',
'종결연살의':'End Kill Chain',
'건강공세의':'Healthy Offense',
'중상폭발의':'Wounded Burst',
'중상흡혈의':'Wounded Leech',
'토벌의':'Vanguard',
'정예토벌의':'Elite Vanguard',
'극대화의':'Maximize',
'공격력 +X%':'ATK +X%',
'관통 확률 +X%':'Pierce Chance +X%',
'방어율 +X%':'Block Rate +X%',
'물리 피해감소 +X%':'Phys DR +X%',
'최대 HP +X':'Max HP +X',
'공격속도 +X%':'ATK Speed +X%',
'상태이상 저항 +X%':'Status Resist +X%',
'이동속도 +X%':'Move Speed +X%',
'원소 저항 +X%':'Elem Resist +X%',
'최대 HP +X%':'Max HP +X%',
'회피 쿨다운 -X%':'Dodge CD -X%',
'물약 쿨다운 -X%':'Potion CD -X%',
'부활력 +X%':'Revive Power +X%',
'마법 데미지 +X%':'Magic DMG +X%',
'전설 특수':'Legendary Special',
'5타 콤보 완성 시 데빌포스 20% 즉시 충전':'5-hit combo: instantly charge DevilForce 20%',
'처치 시 이속 +40%(3초) + 다음 공격 크리 보장':'Kill: MoveSpd +40%(3s) + next attack guaranteed Crit',
'스태거 발동 시 범위 충격파 (ATK×120%)':'Stagger: AoE shockwave (ATK×120%)',
'스태거 발동 시 범위 충격파 (ATK×100%)':'Stagger: AoE shockwave (ATK×100%)',
'강타 시 적 넉백 거리 2배 + 벽충돌 추가뎀':'Heavy hit: Knockback ×2 + wall collision bonus DMG',
'출혈 대상 크리 시 잔여 DoT×300% 즉시 폭발':'Crit vs Bleeding: remaining DoT×300% instant explosion',
'작살 착지 타격 수만큼 데미지 +20% 중첩(최대5)':'Javelin landing hits: stack +20% DMG (max 5)',
'치명타 시 추가 투사체 1발 발사':'Crit: fire 1 additional projectile',
'패리 성공 시 반격 데미지 ×2':'Parry: counter DMG ×2',
'피격 시 3초 쿨로 HP 5% 즉시 회복':'On Hit (3s CD): restore 5% HP instantly',
'스킬 사용 시 20% 확률로 쿨다운 미소모':'Using skills: 20% chance no cooldown consumed',
'공격속도 +20% + 기본공격에 랜덤 원소 추가':'ATK Speed +20% + basic attacks add random element',
'이동 중 지속 HP 재생 (초당 HP의 1%)':'While moving: HP regen (1% HP/sec)',
'회피 직후 첫 공격 데미지 +80%':'First attack after Dodge: DMG +80%',
'패리 타이밍 판정 +50% 확대':'Parry timing window +50% expanded',
'원소 반응 발동 시 추가 폭발 (ATK×80%)':'Elemental reaction: bonus explosion (ATK×80%)',
'처치 시 데빌포스 5% 회복':'Kill: restore 5% DevilForce',
'HP 50% 이하 시 전 스킬 쿨다운 -30%':'Below 50% HP: all skill CD -30%',
'물약 사용 시 5초간 피해 +15%':'Using Potion: DMG +15% for 5s',
'스테이지':'Fase',
'💪 힘 (STR)':'💪 STR',
'🏹 민첩 (DEX)':'🏹 DEX',
'🔮 지능 (INT)':'🔮 INT',
'🍀 행운 (LCK)':'🍀 LCK',
'⚔️ 맹공':'⚔️ Onslaught',
'🔱 돌파':'🔱 Breakthrough',
'⚡ 반격':'⚡ Retaliation',
'🔮 마력폭주':'🔮 Mana Surge',
'🎯 정밀사격':'🎯 Precision',
'🛡 수호신':'🛡 Aegis',
'💚 회복력':'💚 Recovery',
'💥 급소':'💥 Vital Strike',
'🎁 약탈':'🎁 Plunder',
'🔱 관통':'🔱 Pierce',
'💠 마력회복':'💠 Mana Recovery',
'🏹 쇠뇌력':'🏹 Crossbow Mastery',
'⚔ 광전사':'⚔ Berserker',
'🎯 추적자':'🎯 Tracker',
'🗡 물리관통':'🗡 Phys Penetration',
'🔮 마법관통':'🔮 Magic Penetration',
'🌿 풍요':'🌿 Abundance',
'🐺 약자포식':'🐺 Predator',
'☠ 침식':'☠ Corrosion',
'💎 마력그릇':'💎 Mana Vessel',
'💪 힘의그릇':'💪 Stamina Vessel',
'👿 악의중독':'👿 Malice Addict',
'❤️ 강인':'❤️ Fortify',
'🛡 철벽':'🛡 Iron Wall',
'🎯 사냥꾼':'🎯 Hunter',
'✦ 인간성':'✦ Humanity',
'☠ 악마성':'☠ Demon',
'1. 악의폭풍':'1. Malice Storm',
'2. 칼날 계열':'2. Blade Skills',
'3. 역병 확장':'3. Plague Expand',
'4. 이동스킬 마스터':'4. Movement Master',
'5. 사슬 확장':'5. Chain Expand',
'6. 💀 필살기 선택':'6. 💀 Ultimate Pick',
'7. 멸살+만화+원소+전격이동':'7. Beam+Barrage+Elem+Blink',
'8. 회전참+기폭+대왕':'8. Whirl+Det+Giant',
'9. 방패 합체':'9. Shield Fuse',
'10. 해골무덤+악의폭풍':'10. Bone Wall+Malice Storm',
'11. 폭풍소환+얼음보주':'11. Storm+Ice Orb',
'12. 뇌전걸음':'12. Ghost Walk',
'13. 신성 영역':'13. Holy Domain',
'14. 6단합체: 폭풍빔':'14. 6-Fuse: Storm Beam',
'15. 신성+빙결':'15. Holy+Ice',
'16. 암흑+가시+대왕2':'16. Dark+Spike+Slam2',
'17. 사슬 최종':'17. Chain Final',
'⚡ 이동스킬':'⚡ Movement',
'⚔️ 물리':'⚔️ Physical',
'🛡️ 방어':'🛡️ Defense',
'🔮 마법':'🔮 Magic',
'🏹 석궁/투사체':'🏹 Crossbow/Projectile',
'⚙️ 영역':'⚙️ Domain',
'💀 필살기':'💀 Ultimate',
'⭐ 추천':'⭐ Recommend',
'⚔ 공격':'⚔ Attack',
'🛡 방어':'🛡 Defense',
'⚙ 특수':'⚙ Special',
  '👻 공성허수아비!':'👻 Siege Scarecrow!',
  '💥 공성허수아비 폭발!':'💥 Siege Scarecrow Blast!',
};

const _NL_PFX={
'녹슨':'Roestig','강철':'Staal','흑요석':'Obsidiaan','미스릴':'Mithril','심판의':'Oordeel','천벌의':'Goddelijke Toorn','파멸의':'Verderfelijk',
'불꽃':'Vlam','화염':'Vuur','염화':'Hellevuur','지옥불':'Helgloed','지옥화':'Helgloed','지옥':'Hel','멸화의':'Vernietigend',
'냉기':'Vorst','빙결':'Ijs','빙하':'Glaciaal','서리의':'Rijp','서리':'Rijp','영겁빙':'Eeuwig Ijs',
'그림자':'Schaduw','암흑':'Donker','심연':'Afgrond','나락의':'Nether','나락':'Nether','무간의':'Leegte',
'전기':'Vonk','낙뢰':'Donder','암전':'Bliksem','뇌신의':'Stormgod','뇌신':'Stormgod','만뢰의':'Duizend Donder',
'축복':'Gezegend','성광':'Heilig Licht','신성':'Heilig','천사의':'Engelachtig','신벌의':'Goddelijk Oordeel',
'낡은':'Versleten','천':'Stof','가죽':'Leer','강철사':'Staalgeweven','은':'Zilver','은사':'Zilverdraad',
'화염의':'Inferno','빙결의':'Bevroren','암흑의':'Vervloekt','암전의':'Bliksem'};
const _NL_BASE={
'대검':'Grootzwaard','석궁':'Armborst','연사석궁':'Repeteerarmborst','마력석궁':'Magische Armborst',
'견갑':'Schild','대견갑':'Groot Schild','전투화':'Gevechtslaars','갑옷':'Pantser','갑주':'Pantser',
'왕관':'Kroon','장갑':'Handschoenen','건틀릿':'Pantserwanten','바지':'Broek','각반':'Beenbescherming',
'허리띠':'Riem','벨트':'Riem','부적':'Talisman','목걸이':'Ketting','반지':'Ring',
'망토':'Mantel','팔찌':'Armband','귀걸이':'Oorbel'
};
