// 지옥의 길 — Svenska (sv)
const _SV={
// --- Stage / Boss ---
'썩은 숲':'Ruttnande Skog','숲의 감시자':'Skogsvakt','독버섯 거인':'Giftsvamp Jätte','숲의 사냥꾼':'Skogsjägare','숲의 기생수':'Parasitiskt Odjur',
'1장 — 썩은 숲':'KAP1 — Ruttnande Skog','2장 — 벌레굴':'KAP2 — Maskhåla','3장 — 얼음굴':'KAP3 — Isgrottan',
'4장 — 고통의 화염지대':'KAP4 — Infernalisk Ödemark','5장 — 지옥의 군단':'KAP5 — Helveteslegion','6장 — 사도의 마굴':'KAP6 — Apostelns Håla','7장 — 지옥성':'KAP7 — Helvetesfästning',
'탈출!':'Flydde!','처치':'Kills','경험치':'EXP','최대콤보':'Max Kombo',
// --- Tutorial (Crow) ---
'일어나. 여신이 널 여기 보낸 건 죽으라고가 아니야.':'Res dig. Gudinnan skickade dig inte hit för att dö.',
'좋아, 감각이 있군. 계속 쳐!':'Bra, du har instinkt. Fortsätt slå!',
'Shift를 눌러. 작살이다. 땅에 꽂아서 끌려가!':'Tryck Shift. Det är harpunen. Stick in den och bli dragen!',
'작살로 끌려가는 중엔 무적이다. 위험할 때 쓰면 좋아.':'Du är osårbar medan harpunen drar dig. Använd det i fara.',
'...아파? 당연하지. 여긴 지옥이야.':'...Gör det ont? Naturligtvis. Det här är helvetet.',
'Q를 눌러! 악의로 보호막을 만들 수 있다.':'Tryck Q! Skapa en sköld med ondska.',
'보호막 없이 버틸 생각은 버려.':'Glöm att överleva utan sköld.',
'우클릭이 패링이다. 적 공격이 닿기 직전에 눌러!':'Högerklick för att parera. Tryck precis innan fienden träffar!',
'못 하겠으면 때려. 안 죽으면 그만이야.':'Kan du inte parera? Slå dem bara. Att inte dö räcker.',
'됐어! 감 잡았구나.':'Där! Du fattar det.',
'하나 죽었군.':'En ner.',
'유령쇠뇌야. 인사해.':'Det är gestarmborstet. Säg hej.',
'빨간 탄을 무서워하지 마. 악의가 강하다.':'Frukta inte röda kulor. Ondskan är stark.',
'패링으로 돌려주고, Q 보호막도 써! 악의를 잘 굴려!':'Parera tillbaka dem, använd Q-sköld också! Bemästra din ondska!',
'무지개빛은 패링 불가! 피해!':'Regnbågsskott kan inte pareras! Undvik!',
'피가 새고 있다. Shift. 빠져.':'Du blöder ut. Shift. Undan härifrån.',
'물약 있잖아! 숫자키!':'Du har drycker! Siffertangenter!',
'우클릭. 적 손목이 꺾일 때 쳐.':'Högerklick. Slå när deras handled böjer sig.',
'빨간 탄은 악의 덩어리다. 쳐내서 이용해.':'Röda kulor är klumpar av ondska. Slå tillbaka dem och använd dem.',
'무지개빛만 피하면 돼! 나머지는 다 패링!':'Undvik bara regnbågen! Parera allt annat!',
'Q 보호막도 패링이 가능해!':'Q-skölden kan också parera!',
'위험해! 쉬프트 사슬기동으로 피해!!':'Fara! Shift kedjedash för att fly!!',
'쉬프트! 사슬기동은 이동기야! 끌려가면서 무적이라고!':'Shift! Kedjedash är rörelse! Osårbar medan du dras!',
'스킬포인트가 쌓였어! K 눌러서 스킬 배우자!':'Färdighetspoäng redo! Tryck K för att lära dig färdigheter!',
'속성을 읽어. 약점을 찌르면 두 배로 썩는다.':'Läs elementen. Träffa svagheter för dubbel skada.',
'K를 눌러봐! 스킬을 배울 수 있어!':'Tryck K! Du kan lära dig färdigheter!',
'C 눌러서 능력치 찍어! 패시브도 있어~':'Tryck C för stats! Passiva också~',
'G를 눌러. 대장간에서 장비를 강화할 수 있다.':'Tryck G. Uppgradera utrustning vid smedjan.',
'F키도 스킬 슬롯이야! 스킬 많으면 L로 배정해봐~':'F är också ett färdighetsfack! Använd L för att tilldela~',
'Z. 필살기다. 아껴 써라.':'Z. Det är ditt ultimat. Använd det klokt.',
'L-CTRL로 유령걸음이나 얼음보주 쓸 수 있어!':'L-CTRL för Andevandring eller Iskula!',
'L을 눌러. 스킬 슬롯을 정리해야 한다.':'Tryck L. Organisera dina färdighetsfack.',
'가방 터지겠다! V 눌러서 창고에 넣어둬!':'Väskan sprängs! Tryck V för att lagra!',
'ESC로 설정 열 수 있어! 난이도 바꾸기, 자동물약 조절~':'ESC för inställningar! Svårighet, auto-drycker~',
// --- Tutorial (Cat) ---
'...아직 살아있네. 좌클릭으로 저것들 쳐봐.':'...Fortfarande vid liv. Försök träffa dem med vänsterklick.',
'...치는 건 할 줄 아네. 피하는 건?':'...Du kan slå. Men kan du undvika?',
'흥, 작살 못 맞추면 헛수고야.':'Hmph, missa harpunen och det är bortkastrat.',
'...운이 좋았을 뿐이야. 아마.':'...Bara tur. Förmodligen.',
'...고기 냄새. 싫진 않네.':'...Luktar kött. Inte illa.',
'...말은 못해.':'...Den kan inte prata.',
'예쁘다고 만지면 죽어.':'Röra dem för att de är fina? Du dör.',
'작살 던져! 끌려가면 무적이야!':'Kasta harpunen! Osårbar medan du dras!',
'...마시든 말든. 네 목숨이니까.':'...Drick eller inte. Det är ditt liv.',
'그게 패링이야! 타이밍이 전부야~':'Det är en parering! Timing är allt~',
'화염엔 빙결! 암전엔 암흑! 기억해!':'Eld slår Is! Blixt slår Mörker! Kom ihåg!',
'...얼어붙은 놈은 오래 안 간다.':'...Frusna fiender håller inte länge.',
'얼었어! 빙결 중 1.5배야!':'Fryst! 1,5x skada medan fryst!',
'...힘을 골라라. 전부 가질 순 없다.':'...Välj din kraft. Du kan inte ha allt.',
'스탯을 올려. 살고 싶으면.':'Höj dina stats. Om du vill leva.',
'좋은 장비는 강화해야 진짜 힘을 발휘해!':'Bra utrustning behöver uppgraderingar för verklig potential!',
'...슬롯을 채워. 빈 손은 죽음이다.':'...Fyll dina fack. Tomma händer betyder döden.',
'Z 누르면 대박! 쿨타임 길어서 타이밍 봐야 해!':'Tryck Z för enorm skada! Lång nedkylning, tajma det!',
'Ctrl. 위기에 쓸 카드가 하나 늘었군.':'Ctrl. Ytterligare ett kort för nödsituationer.',
'스킬이 많아졌네~ L로 어디에 뭘 넣을지 골라!':'Så många färdigheter~ Använd L för att tilldela!',
'...버리기 아까운 건 창고에.':'...Lagra det som är för bra att tappa.',
'...살아남은 것만으로도 대단하군. 설정을 확인해.':'...Bara att överleva är imponerande. Kontrollera inställningar.',
// --- System Messages ---
'MP 부족!':'Inte tillräckligt MP!','ST 부족!':'Inte tillräckligt ST!','악의 부족!':'Inte tillräckligt Ondska!',
'충전 중...':'Laddar...','캔슬':'Avbryt','아이템 선택 필요':'Välj ett föremål',
'악의 소진...':'Ondska uttömd...','비문 발견...':'Inskription hittad...',
'HP물약!':'HP Dryck!','HP물약 +1':'HP Dryck +1','HP물약 +2':'HP Dryck +2',
'HP/MP/ST 회복!':'HP/MP/ST Återställt!','보물상자 개봉!':'Kista Öppnad!',
'익사!':'Drunknar!','피웅덩이!':'Blodpöl!','독혈!':'Giftigt Blod!','잡힘!':'Gripen!',
'콤보 종료':'Kombo Slut',
// --- Status Effects ---
'빙결!':'Fryst!','화상!':'Brinnande!','독!':'Gift!','감전!':'Chockad!',
'기절!':'Bedövad!','봉인됨!':'Förseglad!','관통!':'Genomborrande!',
// --- Skill Names ---
'기검참':'Ki Hugg','악의구':'Ondskeboll','회전참':'Virvelvind','기폭팔':'Detonera',
'칼등 처내기':'Bladparering','만화방창':'Nålstorm','멸살광선':'Förintelsestråle',
'원소추적탄':'Elementjägare','악의 보호자':'Ondskas Väktare','악의 사냥':'Ondskas Jakt',
'폭풍소환':'Virvelvindsframkallning','해골무덤':'Bengrav','신성폭발':'Helig Explosion',
'블랙':'Svart Stjärna','용암소환':'Lava Framkallning','처형':'Avrättning','악마화 부활':'Demon Uppståndelse',
'붉은꽃':'Karmosinblomning','얼음보주':'Iskula','뇌전걸음':'Andevandring',
'만화방창 II':'Nålstorm II','마력연사':'Magisk Beskjutning','마력광선':'Magisk Laser','업화선':'Helvetesstråle',
'지옥진':'Inferno Formation','폭독칼날':'Pestblad','악의폭풍':'Ondskestorm',
'악의기둥':'Mörk Pelare','회복의 영역':'Heligt Domän','구속의 영역':'Bindande Domän',
'아이스스톰':'Isstorm','대왕치기':'Jätteslag','대왕치기 2':'Jätteslag II',
'기동불꽃':'Kedjebrand','기동파괴':'Kedjeförstöring','기동칼날개':'Kedjebladsvinge',
'평화의보호':'Fredens Sköld','참회':'Ånger','칼등날개':'Sköldvinge',
'폭산탄':'Explosivt Skott','파쇄의 영역':'Krossningsdomän','침식의 영역':'Erosionsdomän',
'관통의 영역':'Genomborringdomän','부활의 영역':'Uppståndelsesdomän','가시덫':'Taggfälla',
'푸른비':'Azurblå Regn','버스트루프':'Utbrott Loop','유령 허수아비':'Fantom Lockbete','폭발 허수아비':'Explosivt Lockbete',
'공성쇠뇌':'Belägringsarmborst','사슬기동:충돌':'Kedjedash: Kollision',
'사슬기동:화염':'Kedjedash: Flamma','전격이동':'Blixtdash',
// --- Skill Activation ---
'기동칼날개!':'Bladsvinge!','기동불꽃!':'Kedjebrand!','기동파괴!':'Kedjeförstöring!',
'사슬이동:강화!':'Kedjedash!','사슬기동:화염!':'Kedjeflamma!',
'작살!':'Harpun!','진입!':'Ingång!','레인라이트닝!':'Regnblixt!',
'마력연사!':'Magisk Beskjutning!','🔷 마력광선!':'🔷 Magisk Laser!','광선 해제':'Laser Av','MP 부족 — 광선 해제':'MP tömd — Laser Av','집중...':'Fokus...','시전...':'Gjutning...',
'만화방창!':'Nålstorm!','바늘출!':'Nålutbrott!','칼날!':'Blad!',
'착지!':'Landning!','체간삭감!':'Hållning Brott!',
'기동전폭 준비!':'Kedjeexplosion Redo!','기동불꽃 준비!':'Kedjebrand Redo!',
'기동파괴 준비!':'Kedjeförstöring Redo!',
'유령불꽃 ON':'Andeflamma PÅ','유령불꽃 OFF':'Andeflamma AV',
'기동칼날개 AUTO ON':'Bladsvinge AUTO PÅ','기동칼날개 AUTO OFF':'Bladsvinge AUTO AV',
'자동 버스트!':'Auto Utbrott!','연사 해제':'Snabdeld Av',
'당기기 모드':'Dragläge','밀어내기 모드':'Skjutläge',
// --- Skill Slot Tooltips ---
'날개치기':'Vingeslag','처내기':'Parera',
'Shift: 작살 발사 → 끌려감':'Shift: Harpunkast → dras',
'Shift: 화염길+화상':'Shift: Brandspår+brännskada',
'CT: 전류변신+뇌전걸음 (쿨4초)':'CT: Blixtform+Andevandring (CD 4s)',
'CT: 방어구체+빙결 (재입력: 파쇄)':'CT: Iskula+frysning (återtyck: krossning)',
// --- HUD ---
'근접':'Närstrid','견갑':'Sköld','작살':'Harpun','마법':'Magi','보막':'Sköld','유령':'Ande',
'스킬':'Färdigheter','대장':'Smedja','인벤':'Inv',
// --- Menu ---
'인벤토리':'Inventarium','복수의 대장간':'Hämdens Smedja','패시브 스킬':'Passiva Färdigheter',
'전투 스킬':'Stridsfärdigheter','캐릭터 선택':'Karaktärsval',
// --- Elements ---
'물리':'Fysisk','화염':'Eld','빙결':'Is','암흑':'Mörker','암전':'Blixt','신성':'Helig','대지':'Jord',
// --- Passives ---
'힘':'Styrka','민첩':'Fingerfärdighet','지능':'Intelligens','행운':'Tur',
'맹공':'Anfall','철벽':'Fästning','돌파':'Genombrott','반격':'Motangrepp',
'마력폭주':'Magisk Rusning','정밀사격':'Precisionskytte','수호':'Skydd','수호신':'Skyddsande',
'회복력':'Återhämtning','급소':'Vital Träff','약탈':'Plundring','관통':'Genomträngning',
'마력회복':'Mana Återhämtning','쇠뇌력':'Armborstbehärskning','광전사':'Bärsärk','추적자':'Spårare',
'물리관통':'Fysisk Pen.','마법관통':'Magisk Pen.',
// --- Weapons (Tier 0) ---
'녹슨 대검':'Rostigt Tvåhandssvärd','강철 대검':'Stål Tvåhandssvärd','흑요석 대검':'Obsidian Tvåhandssvärd',
'낡은 석궁':'Slitet Armborst','강철 석궁':'Stål Armborst','흑요석 석궁':'Obsidian Armborst',
'대검':'Tvåhandssvärd','석궁':'Armborst','연사석궁':'Repeterarmborst','마력석궁':'Magiskt Armborst',
// --- Misc ---
'악의 추출':'Ondska Extraktion','악의':'Ondska','필살기':'Ultimat','필살기 해제':'Ultimat Tömt',
'이전':'Överföring','강화':'Förbättring','개봉!':'Öppnad!',
'여신의 가호':'Gudinnans Välsignelse',
'과부하!':'Överbelastning!',
// --- Affix Names ---
'맹독의':'Giftig','불꽃의':'Flammande','냉기의':'Isande','번개의':'Elektrisk','암흑의':'Förbannad',
'관통의':'Genomborring','광폭의':'Rasande','파쇄의':'Krossande','연쇄의':'Länkande',
'학살의':'Slaktande','폭발의':'Explosiv','집중의':'Fokuserad','쾌속의':'Snabb','패리의':'Parerande',
'추적자의':"Spårarens",'작살의':'Harpun','궁극의':'Yttersta','집중력의':'Uppmärksam',
'강인의':'Tålig','수호의':'Väktande','활력의':'Vital','신속의':'Skyndsam',
'화염수호':'Eldvakt','빙결수호':'Isvakt','암전수호':'Blixtvakt','암흑수호':'Mörkervakt','독수호':'Giftvakt','전원소수호':'Allvakt',
'강철의':'Järnhård','반사의':'Reflekterande','가시의':'Taggig','흡수의':'Absorberande','인내의':'Uthållande',
'위기의':'Desperat','피격반격의':'Hämndlysten',
'패링폭발의':'Parerexplosion','스태거폭발의':'Staggerexplosion','원소전환의':'Konverterare','정화의':'Renande',
'불굴의':'Orubblig','부활의':'Uppståndande',
'약탈의':'Plundrande','경험의':'Erfaren','골드의':'Gyllene','포션강화의':'Potent','사슬의':'Kedjad',
'진혈의':'Helgande','윤회의':'Cyklisk',
'생명력의':'Livsfulll','재생의':'Regenererande','치유의':'Helande',
'마력의':'Magisk','절약의':'Effektiv','영혼의':'Själsbunden',
'예리한':'Vass','맹렬한':'Brutal','파멸의':'Fördärvlig',
// --- Settings UI ---
'게임 설정':'Spelinställningar','화면 흔들림':'Skärmskak','파티클 양':'Partikel Mängd',
'효과음 볼륨':'Ljudeffekt Volym','음악 볼륨':'Musik Volym','난이도':'Svårighet',
'자동 물약':'Auto Dryck','최소 줍기 등급':'Min Upphämtning Rang','최소 줍기 티어':'Min Upphämtning Tier',
'FPS 제한':'FPS Gräns','해상도 스케일':'Upplösningsskala','펫 자동수거':'Husdjur Auto-Samla',
'화면 설정':'Visningsinställningar','화면 모드':'Visningsläge','보스 AI 디버그':'Boss AI Debug',
'유령불꽃 크기':'Andeflamma Storlek','화면 명암':'Ljusstyrka','유령 글로우':'Ande Glöd',
'기동:칼날개 AUTO':'Bladsvinge AUTO',
'일반':'Normal','어려움':'Svårt','지옥':'Helvete','이상':'eller högre','사용 안 함':'Inaktiverat',
'창 모드':'Fönster','보더리스':'Kantlöst','전체화면':'Helskärm',
'설정':'Inställningar','조작 키 설정 (클릭하여 변경)':'Tangentbindning (Klicka för att ändra)',
// --- Key Guide ---
'좌클릭 무기 공격':'LMB Vapenanfall','우클릭 탭 칼등 처내기':'RMB Tryck Bladparering',
'우클릭 홀드 연속 처내기':'RMB Håll Kontinuerlig Parering','SHIFT 작살 발사':'SHIFT Harpunuppskjutning',
'이동':'Rörelse','아이템 줍기':'Plocka upp Föremål','능력치 (스탯/패시브)':'Stats (Stats/Passiva)',
// --- Forge ---
'복수의 대장간':'Hämdens Smedja','강화':'Förbättring','분해':'Demontering','제작':'Tillverkning',
// --- Death Screen ---
'사망':'Död','부활':'Återuppståndelse','로비로':'Till Lobby',
// --- Inventory/Storage ---
'가방에 공간이 없습니다!':'Inget utrymme i väska!','가방이 가득 찼습니다!':'Väska är full!',
'창고가 가득 찼습니다!':'Lagret är fullt!','퀵슬롯이 가득 찼습니다!':'Snabbfack är fullt!',
'결정 주머니가 가득 찼습니다!':'Kristallpung är full!','결정 주머니 가득!':'Kristallpung full!',
'악의가 부족합니다!':'Inte tillräckligt Ondska!','가방이 비어있습니다':'Väska är tom',
'창고가 비어있습니다':'Lagret är tomt','비어있음':'Tom','어픽스 없음':'Ingen affix',
'장착!':'Utrustad!','해제':'Avrustad','보관':'Förvara','꺼내기':'Hämta',
'현재 장착':'Aktuellt utrustad','없음 — 제작하세요!':'Ingen — Tillverka en!',
'리셋할 포인트가 없습니다':'Inga poäng att återställa',
'키 설정 초기화 완료':'Tangentinställningar återställda',
// --- Forge/Craft ---
'제작 확률':'Tillverkningschans','제작 비용':'Tillverkningskostnad','보유 악의':'Ondska ägd',
// --- Canvas UI ---
'보스방':'Bossrum','안식처':'Helgedom','회복':'Återhämtning','점화':'Antändning',
'비석':'Stele','읽기':'Läs','파괴':'Förstör','제단':'Altare','기원':'Bön',
'잔해':'Skräp','열기':'Öppna','문지기':'Grindvakt',
'부활 판정 중...':'Uppståndelse bedömning...','기폭 준비!':'Detonering Redo!',
'탈출':'Fly','연타':'Mash',
'추적암전':'Spårande Blixt','만화방창':'Luminansstråle','최종 마법':'Slutgiltig Magi',
'감시중':'Bevakar','대기':'Standby','작동중':'Aktiv','설치 가능':'Kan installera',
'균열 임박!':'Spricka förestående!','흡수 중...':'Absorberar...',
'흡수 완료 — 재입력으로 회수':'Klar — återinmatning för att samla in',
'화상':'Brännskada','당기기':'Dra','밀어내기':'Skjuta',
'단계':'tier','단':'tier',
// --- Skill Panel ---
'습득!':'Lärd!','리셋!':'Återställd!','세팅!':'Inställd!','회수':'Återkalla',
'합체 해제':'Avfusionera','리셋':'Återställ','환불':'Återbetalning',
'파트너 클릭!':'Klicka partner!','SP부족!':'SP behövs!',
'같은 보석 스킬 습득 시 합체 가능':'Kan fusionera vid inlärning av samma juvel färdighet',
'펼쳐서 초기화':'Expandera för att återställa','슬롯:':'Fack:',
// --- Stats ---
'남은 SP':'SP Kvar','처치':'Kills','경험치':'EXP','최대콤보':'Max Kombo',
'맞아서 사망':'Dog av träff','레벨':'Nivå','최대HP':'Max HP',
// --- Enemy Names ---
'방랑 기사':'Vandrande Riddare','보물 악마':'Skattedemon','거울의 사도':'Spegelapostel',
'상인 악마':'Köpmansdemon','사슬의 죄수':'Kedjad Fånge','시간의 사도':'Tidsapostel',
'탐욕의 사도':'Girighetens Apostel','저주받은 쌍둥이':'Förbannade Tvillingar','차원 균열체':'Dimensionell Spricka',
'죽음 그 자체':'Döden Själv',
// --- Crystals ---
'HP결정':'HP Kristall','ST결정':'ST Kristall','MP결정':'MP Kristall',
'ATK결정':'ATK Kristall','DEF결정':'DEF Kristall','속도결정':'Hastighetskristall',
'크리결정':'Krit Kristall','치명결정':'KritSkada Kristall','화염결정':'Eldkristall',
'냉기결정':'Iskristall','암흑결정':'Mörkerkristall','번개결정':'Blixtrkristall',
'신성결정':'Helig Kristall','생명결정':'Livskristall','기력결정':'Uthållighetskristall',
'마력결정':'Mana Kristall','행운결정':'Turkristall',
'조각':'Fragment','파편':'Skärva','순수결정':'Ren Kristall','완전결정':'Perfekt Kristall',
'결정 주머니':'Kristallpung','결정이 없습니다':'Inga kristaller','가루':'Damm',
'전체':'Alla','스탯':'Stat','원소':'Elem','유틸':'Util',
'현재':'Nuvarande','최대 강화 달성 (+20)':'Max förbättrad (+20)','강화 시':'Efter förbättring',
'강화':'Förbättring','합성':'Syntetisera','제작':'Tillverkning',
'같은 종류·같은 성급 결정 3개 → 1성급 상승 (강화 리셋)':'3 kristaller av samma typ och rang → 1 rang uppgrading (förbättring återställd)',
'합성 가능한 결정이 없습니다 (같은 종류·성급 3개 필요)':'Inga kristaller att syntetisera (behöver 3 av samma typ och rang)',
'결정 분해 → 결정 가루':'Kristall Demontering → Kristalldamm',
'분해할 결정이 없습니다':'Inga kristaller att demontera',
'결정 제작 (가루 → 결정)':'Tillverka Kristall (Damm → Kristall)',
'탈착':'Koppla ur','빈 슬롯':'Tomt fack',
'결정 선택 후 클릭':'Välj kristall sedan klicka','클릭하여 선택결정 장착':'Klicka för att utrusta vald kristall',
'획득!':'Erhållen!','제작!':'Tillverkad!','합성!':'Syntetiserad!','최상위 일괄합성':'Bulk Synth till Topp','일괄합성 완료':'Bulk synth klar',
// --- Stage Names ---
'벌레굴':'Maskhåla','얼음굴':'Isgrottan','고통의 화염지대':'Infernalisk Ödemark',
'지옥의 군단':'Helveteslegion','사도의 마굴':'Apostelns Håla','지옥성':'Helvetesfästning',
// --- Misc ---
'엑소듀서 전사':'Exoduser Krigare','포이즈':'Hållning',
'신성폭발':'Helig Explosion','뇌전걸음':'Andevandring',
'지옥창고':'Helveteslager','선택분해':'Selektiv Demontering','쓰레기':'Skräp',
'복구 불가!':'Kan inte återhämta!','중요잠금':'Viktigt-låst',
// --- Phase 9 additions ---
'획득!':'Erhållen!','자동 장착!':'Auto-utrustad!','분해! 가루 +':'Demonterad! Damm +',
'추적암전':'Spårande Blixt','암전':'Blixt',
'평화보호':'Sköld','지진폭풍':'Jordbävningsstorm','회전기폭':'Virvelföstering',
'공격':'Anfall','보호막':'Sköld','필살기':'Ultimat',
'합체 스킬로 통합됨':'Sammanfogad till fusionerad färdighet','얼음보주 안에선 사용 불가!':'Kan inte använda inuti Iskula!',
'Shift+키로 폭파':'Shift+tangent för att detonera','취소':'Avbryt','충전 중...':'Laddar...',
'쿨다운 중...':'Nedkylning...','시전 중...':'Gjutning...','악의 부족!':'Inte tillräckligt Ondska!',
'악의 부족! (12)':'Inte tillräckligt Ondska! (12)','악의 부족! (15)':'Inte tillräckligt Ondska! (15)',
'악의 부족! (20)':'Inte tillräckligt Ondska! (20)','악의 부족! (10)':'Inte tillräckligt Ondska! (10)',
'ST 부족!':'Inte tillräckligt ST!','HP 부족!':'Inte tillräckligt HP!',
'필살기 슬롯 클릭하여 배정!':'Klicka ultimatfack för att tilldela!',
'필살기 스킬을 습득하세요':'Lär dig en ultimat färdighet',
'우클릭(칼등치기)에 합체됨':'Sammanfogad till RMB (bladparering)',
'T(석궁자동)에 세팅하세요':'Ställ in på T (auto armborst)',
'공성쇠뇌 철거 → 이동식':'Belägringsarmborst demonterat → bärbar',
'ST 부족! (100)':'Inte tillräckligt ST! (100)',
'HP 99% 이상!':'HP 99%+!','그로기 보스 없음!':'Ingen bedövad boss!',
'이미 폭풍 지역!':'Redan i stormzon!','이미 빙풍 지역!':'Redan i isstormzon!',
'💎 푸른비 해금!':'💎 Azurblå Regn upplåst!','💫 버스트루프 해금!':'💫 Utbrott Loop upplåst!',
'👻 유령 허수아비 해금!':'👻 Fantom Lockbete upplåst!',
'쿨 ':'CD ','과부하 ':'Överbelastning ',
'🕊️💎 블루콩!':'🕊️💎 Blå Böna!','🛡️💎 빨콩→블루콩!':'🛡️💎 Röd→Blå Böna!',
'🛡️💎 무지개→블루콩!':'🛡️💎 Regnbåge→Blå Böna!',
'레어':'Sällsynt','슬롯':'Fack',
'성공률':'Framgångschans','AI 자동 강화':'AI Auto-Förbättring','최대 강화 달성!':'Max förbättring uppnådd!',
'최대 강화':'Max förbättrad','회복량':'Återhämtningsmängd','현재 장착':'Aktuellt utrustad',
'없음 — 제작하세요!':'Ingen — Tillverka en!','제작 확률':'Tillverkningschans',
'분해할 아이템이 없습니다.':'Inga föremål att demontera.','🔨 제작':'🔨 Tillverka',
'체간':'Hållning','아이템에 마우스를 올리거나 좌클릭으로 선택하세요':'Håll muspekaren över ett föremål eller vänsterklicka för att välja',
// --- Phase 10 ---
'중독':'Gift','지뢰':'Mina','함정':'Fälla','산호가시':'Koralltagg',
'투사체':'Projektil','도트':'DoT','레어몹':'Sällsynt Mob',
'처치':'kills','경험치':'EXP','최대콤보':'Max Kombo',
'구역':'Zon','가시!':'Tagg!',
// --- Hell circle ---
'림보':'Limbo','색욕':'Vällust','탐식':'Glupskhet','탐욕':'Girighet','분노':'Vrede','이단':'Kätteri','폭력':'Våld',
'분노!':'Raseri!','탐욕!':'Girighet!','💀 분노 폭발!':'💀 Raseriutbrott!','심연의 분노!':'Avgrunds Raseri!','쌍둥이의 분노!':'Tvillingarnas Raseri!',
// --- HUD ---
'소환굴':'Spawngrop',
'레어':'Sällsynt','처치!':'Besegrad!','왕관 착용':'Krona På','왕관 해제':'Krona Av',
'맨손':'Bara Händerna','없음':'Ingen','갑옷':'Rustning','부츠':'Stövlar',
// --- Elite / Mod / Aura ---
'매직':'Magisk','챔피언':'Mästare',
'빙결':'Fryst','초속':'Hast','강타':'Slag','재생':'Regeneration','맹독':'Gift','소환':'Framkallning',
'기생':'Parasit','분열':'Splittring','용암자취':'Lavaspår','사망폭발':'Dödsexplosion',
'화염사슬':'Eldkedja','광전':'Raseri','텔레포트':'Teleportering','보호막':'Barriär',
'소용돌이':'Virvel','환영':'Fantom','전격반사':'Chockreflexion','감전':'Elektrifiering',
'낙뢰':'Åska','연쇄전격':'Kedjeblixtar','동료불사':'Allierad Odödlig',
'영혼포식':'Själsuppslukare','시간왜곡':'Tidsförvrängning','혼돈변이':'Chaosmutation',
'복수자':'Hämnare','마법보초':'Magisk Vakt','환영술사':'Illusionist',
'함성':'Krigsskrik','치유':'Helning','신속':'Snabbhet','수호':'Väktare',
// --- Character ---
'다크 판타지 전사. 거대검+검은 갑옷':'Mörk fantasy krigare. Tvåhandssvärd + Svart rustning',
// --- Phase 11 ---
'⚡ 사슬이동:강화!':'⚡ Kedja:Förstärkt!',
'⚡ 사슬기동:화염!':'⚡ Kedjekörning: Flamma!',
'달성!':'Uppnådd!',
'ST':'ST','부족!':'Otillräcklig!',
'타':'Träff',
'🌀 당기기 모드':'🌀 Dragläge',
'💥 밀어내기 모드':'💥 Skjutläge',
'🕊️빨콩 흡수':'🕊️Röd böna absorbera',
'🕊️흡수':'🕊️Absorbera',
'💎유도 폭발!':'💎Styrd explosion!',
'💥반사 폭발!':'💥Reflektionsexplosion!',
'⚡⚡ 참회 귀환!':'⚡⚡ Ånger Återvändo!',
'⚡ 참회!':'⚡ Ånger!',
'파도!':'Våg!',
'암전!':'Blixt!',
'암흑!':'Mörker!',
'암흑창!':'Mörkerspjut!',
'빛창!':'Ljusspjut!',
'체 소환!':'Framkallad!',
'개 설치!':'Placerad!',
'💥 보스 그로기!':'💥 Boss Bedövad!',
'💥 그로기!':'💥 Bedövad!',
'보상':'Bonus',
'⚡ 암전나선!':'⚡ Blixtspiral!',
'🌋 지진폭풍!':'🌋 Jordbävningsstorm!',
'SP슬롯':'SP Fack',
'F슬롯':'F Fack',
'⚔🩸 독혈해방!':'⚔🩸 Pestblodsbefrielelse!',
'⚔ 칼날 해방!':'⚔ Bladsbefrielse!',
'🔨🌋 지옥강타!':'🔨🌋 Helvetesslag!',
'🔨 대왕치기!':'🔨 Jätteslag!',
'✟ 결계의 영역!':'✟ Bevakningsdomän!','✟ 물의 영역!':'✟ Vattendomän!','✟ 파쇄의 영역!':'✟ Krossningsdomän!','✟ 침식의 영역!':'✟ Erosionsdomän!','✟ 관통의 영역!':'✟ Genomborringdomän!','✟ 권능의 영역!':'✟ Suverändomän!',
'🛡 회복의 영역!':'🛡 Heligt Domän!',
'임계...!':'Kritisk...!',
'기폭팔!':'Detonera!','강제기폭!':'Tvingad Detonering!','자동기폭!':'Auto Detonering!',
'회전기폭!':'Virvelföstering!','해제기폭!':'Frigörande Detonering!','지진기폭!':'Jordbävningsdetonering!',
'혼돈의 왕관':'Chaosets Krona',
'전지전능의 왕관':'Allvetandes Krona',
'악마의 팔찌':'Demonarmband',
'생명의 팔찌':'Livsarmband',
// --- wave direction names ---
'🌊 위→아래 파도!':'🌊 Upp→Ner Våg!','🌊 오른→왼 파도!':'🌊 Höger→Vänster Våg!',
'🌊 아래→위 파도!':'🌊 Ner→Upp Våg!','🌊 왼→오른 파도!':'🌊 Vänster→Höger Våg!',
// --- Phase 12 ---
'⚡ 사슬이동:강화!':'⚡ Kedja:Förstärkt!','⚡ 사슬기동:화염!':'⚡ Kedjekörning: Flamma!',
'🌀 당기기 모드':'🌀 Dragläge','💥 밀어내기 모드':'💥 Skjutläge',
'💎유도 폭발!':'💎Styrd Explosion!','💥반사 폭발!':'💥Reflektionsexplosion!',
'⚡⚡ 참회 귀환!':'⚡⚡ Ånger Återvändo!','⚡ 참회!':'⚡ Ånger!',
'암전!':'Blixt!','암흑!':'Mörker!','암흑창!':'Mörkerspjut!','빛창!':'Ljusspjut!',
'💥 보스 그로기!':'💥 Boss Bedövad!','💥 그로기!':'💥 Bedövad!',
'⚡ 암전나선!':'⚡ Blixtspiral!','🌋 지진폭풍!':'🌋 Jordbävningsstorm!',
'⚔🩸 독혈해방!':'⚔🩸 Pestblodsbefrielelse!','⚔ 칼날 해방!':'⚔ Bladsbefrielse!',
'🔨🌋 지옥강타!':'🔨🌋 Helvetesslag!','🔨 대왕치기!':'🔨 Jätteslag!',
'✟ 결계의 영역!':'✟ Bevakningsdomän!','✟ 물의 영역!':'✟ Vattendomän!','✟ 파쇄의 영역!':'✟ Krossningsdomän!','✟ 침식의 영역!':'✟ Erosionsdomän!','✟ 관통의 영역!':'✟ Genomborringdomän!','✟ 권능의 영역!':'✟ Suverändomän!','🛡 회복의 영역!':'🛡 Heligt Domän!',
'파도!':'Våg!',
// --- rare mob / special ---
'무적!':'Osårbar!','🪞 반격!':'🪞 Motangrepp!','💢 반격!':'💢 Motangrepp!',
'흡수!':'Absorbera!','반격 발사!':'Motangreppskytte!',
'저주! 드랍률 -50%':'Förbannelse! Droppchans -50%','도망!':'Fly!',
'위상!':'Fas!','방어!':'Försvar!',
'회수 HP+':'Återkalla HP+','이동식 복귀':'Bärbar Återvändo','캔슬':'Avbryt',
'약점!':'Svaghet!','저항!':'Motstånd!','관통!':'Genomborring!',
'유령불꽃 OFF':'Andeflamma AV','유령불꽃 ON':'Andeflamma PÅ',
'기동칼날개 AUTO ON':'Bladsvinge AUTO PÅ','기동칼날개 AUTO OFF':'Bladsvinge AUTO AV',
'콤보 종료: ':'Kombo Slut: ','익사!':'Drunknar!',
'피웅덩이!':'Blodpöl!','독혈!':'Giftigt Blod!','비문 발견...':'Inskription hittad...',
'보물상자 개봉!':'Kista Öppnad!','악의 +':'Ondska +','잡힘!':'Gripen!',
'저주 ':'Förbannelse ','충전 중...':'Laddar...','불발...':'Försök misslyckades...',
'작살 약점!':'Harpun Svaghet!',
'전염 x':'Pest x','흡수 완료!':'Absorption Slutförd!',
'부활 성공!':'Återuppståndelse Lyckad!','부활 실패...':'Återuppståndelse Misslyckad...',
'산호가시':'Koralltagg','가시!':'Tagg!','차원 이동!':'Dimensionellt Skifte!','독!':'Gift!',
'탈출!':'Flydde!','기절 해제':'Bedövning Upphävd',
'아이템 선택 필요':'Välj ett föremål','악의 부족':'Inte tillräckligt Ondska','악의 소진...':'Ondska uttömd...',
'스킬 미습득':'Inga färdigheter lärda','펼치기':'Expandera','접기':'Kollapsera',
'조건 미달!':' ej uppfylld!','해제!':' Avfusionerad!',
'슬롯':'Fack','자동 ON':' Auto PÅ','자동 OFF':' Auto AV','스킬 해제':' färdighet avaktiverad',
'필살기':'Ultimat','필살기 해제':'Ultimat Tömt',
'연사 해제':'Snabdeld Av',
'닫기':'Stäng','장착 중':'Utrustad','보관 아이템':'Lagrat Föremål',
// --- Phase 13 ---
'클릭으로 선택 · ESC로 닫기':'Klicka för att välja · ESC för att stänga',
'선택됨':'Vald',
'MP 부족!':'Inte tillräckligt MP!','악의 부족! (30)':'Inte tillräckligt Ondska! (30)',
'MP 부족! (40)':'Inte tillräckligt MP! (40)','MP 부족! (100)':'Inte tillräckligt MP! (100)','MP 부족! (10)':'Inte tillräckligt MP! (10)',
'MP 부족! (':'Inte tillräckligt MP! (',
'✟ 시전...':'✟ Gjutning...','🌋 시전...':'🌋 Gjutning...','⛧ 시전...':'⛧ Gjutning...',
'❄ 진입!':'❄ Ingång!',
'🔱 작살!':'🔱 Harpun!',
'레벨 부족! (요구: Lv.':'Nivå för låg! (Krav: Lv.',
' 장착!':' Utrustad!',
'가방에 공간이 없습니다!':'Inget utrymme i väska!',
' 해제':' Avrustad',
'👿 악의 추출: +':'👿 Ondska Extraktion: +',
'F 슬롯 해제':'F Fack avaktiverat',
'💫 집중...':'💫 Fokus...',
'⚡ 마력연사!':'⚡ Magisk Beskjutning!',
'❄빙결!':'❄Fryst!','🟢독!':'🟢Gift!','⚡감전!':'⚡Chockad!','🔥화상!':'🔥Brinnande!',
'✦ 여신의 가호 — SP+5 AP+3':'✦ Gudinnans Välsignelse — SP+5 AP+3',
'⚔ 기동칼날개!':'⚔ Bladsvinge!',
'🔥 화염관통!':'🔥 Eldgenomborring!',
'🔱 관통!':'🔱 Genomborring!',
'⚔ 칼날!':'⚔ Blad!',
'💥 착지!':'💥 Landning!',
'💫 기절!':'💫 Bedövad!',
'⚡ 체간삭감!':'⚡ Hållningsbrott!',
'⚡ 기동파괴! ':'⚡ Kedjeförstöring! T',
'🔥 기동불꽃!':'🔥 Kedjebrand!',
'🔥 기동불꽃! ':'🔥 Kedjebrand! T',
'단계 ×':' x',
'⚡ 기동전폭! x':'⚡ Kedjeexplosion! x',
'🔥🔥 3중폭!':'🔥🔥 Brand x3!','🔥🔥🔥 6중폭!':'🔥🔥🔥 Brand x6!','🔥🔥🔥🔥 9중폭!':'🔥🔥🔥🔥 Brand x9!','💥 불꽃폭발! ':'💥 Branddetonering! ',
'🔥 기동불꽃 준비!':'🔥 Kedjebrand Redo!',
'🔨 기동파괴 준비!':'🔨 Kedjeförstöring Redo!',
'⚡ 기동전폭 준비!':'⚡ Kedjeexplosion Redo!',
'콤보 종료: ':'Kombo Slut: ',
'중독':'Gift',
'⚡ 과부하! 5초':'⚡ Överbelastning! 5s',
'💫 자동 버스트!':'💫 Auto Utbrott!',
'🔨 칼등날개!':'🔨 Sköldvinge!',
'💥폭발!':'💥Explosion!',
'🛡️💎 유도반사!':'🛡️💎 Styrd Reflex!',
'⚡💎 블루콩!':'⚡💎 Blå Böna!',
'💎 블루콩!':'💎 Blå Böna!',
'⚡반사!':'⚡Reflex!',
'💎 푸른비 OFF':'💎 Azurblå Regn AV',
'💎 푸른비 ON!':'💎 Azurblå Regn PÅ!',
'🔥 지옥진!':'🔥 Inferno Formation!',
'🔥 업화선!':'🔥 Helvetesstråle!',
'✦ 평화 충격파! ':'✦ Freds Chockvåg! ',
'⚡ 전류 방출!':'⚡ Strömfrisättning!',
'⚡⚡ 레인라이트닝!':'⚡⚡ Regnblixt!',
'💫 광역!':'💫 Område!',
'🔥 불장판!':'🔥 Eldzon!',
'💫 피니셔!':'💫 Avslutare!',
'☠ 지옥에서 귀환!':'☠ Återvände från Helvetet!',
'☠ 완전 사망!':'☠ Permanent Dödsfall!',
'⚔ 처형! ':'⚔ Avrättning! ',
'💥 지뢰!':'💥 Mina!',
'⚠ 함정!':'⚠ Fälla!',
'❌ 우클릭으로! -':'❌ Använd RMB! -',
'❌ Q키로! -':'❌ Använd Q! -',
'💥무지개 폭발! ':'💥Regnbågeexplosion! ',
'🛡️💎 블루콩!':'🛡️💎 Blå Böna!',
'⬜화이트볼!':'⬜Vit Boll!',
'✨💎 블루콩!':'✨💎 Blå Böna!',
'💜다크볼!':'💜Mörk Boll!',
'❄빙판!':'❄Isgolv!',
'🌨빙결!':'🌨Fryst!',
'🕸둔화!':'🕸Långsam!',
'⚠트랩!':'⚠Fälla!',
'💀 역병 처형!':'💀 Pestavrättning!',
'💥 역병 Finale!':'💥 Pest Finale!',
'⚔ 균열 악마!':'⚔ Sprickdemon!',
'자동회수 HP+':'Auto-Återkalla HP+',
'MP 부족 — 연사 해제':'MP låg — Snabdeld Av',
'MP 부족 — 푸른비 OFF':'MP låg — Azurblå Regn AV',
'🛡️반사!':'🛡️Reflex!',
'⚡🦴 참회 귀환!':'⚡🦴 Ånger Återvändo!',
'🦴⚡해골번개!':'🦴⚡Benblixt!',
'⚡악의폭풍!':'⚡Ondskestorm!',
'❄아이스스톰!':'❄Isstorm!',
'⚡ 암전폭발!':'⚡ Blixtexplosion!',
'⚡ 레인라이트닝! x':'⚡ Regnblixt! x',
'❄ 탈출!':'❄ Fly!',
'⚡쉴드!':'⚡Sköld!',
'❄🌪️ 얼음보주!':'❄🌪️ Iskula!',
'🌪️ 전개!':'🌪️ Deployment!',
'❄ 빙결흡인!':'❄ Fryssugning!',
'❄☄ 빙결폭발!':'❄☄ Frysexplosion!',
'☄️ 흡인!':'☄️ Sugning!',
'☄️ 대폭발!':'☄️ Megaexplosion!',
'❄ 얼음보주!':'❄ Iskula!','⏳ 시간왜곡!':'⏳ Tidsförvrängning!','쿨다운!':'Nedkylning!',
'❄ 파쇄!':'❄ Krossning!',
'☄️💥 대폭발!':'☄️💥 Megaexplosion!',
'반사!':'Reflex!',
// --- boss moves ---
'💀 도넛!':'💀 Munk!','💀 전멸!':'💀 Utrotning!',
'🌊 파도!':'🌊 Våg!','속박!':'Binda!','반격!':'Motangrepp!',
'분신!':'Klon!','분신 파괴!':'Klon Förstörd!','무기 해방!':'Vapenbefrielse!',
'❄프리즌!':'❄Fängelse!','⚡ 증표 ':'⚡ Märkning ',
'흔들!':'Skaka!','⚠ 광역 발사!':'⚠ Område Eld!',
'🔥 확산!':'🔥 Spridning!','⚠ 돌진!':'⚠ Anfall!',
'🦅 도약!':'🦅 Hopp!','⚡ 레이저!':'⚡ Laser!',
'🌊 충격파!':'🌊 Chockvåg!','👹 소환!':'👹 Framkallning!',
'☄ 유성우!':'☄ Meteorregn!','🖐 잡기!':'🖐 Greppa!',
'🌀 회전참!':'🌀 Virvelvind!','💣 지뢰!':'💣 Mina!',
'🌀 흡인!':'🌀 Vakuum!','🔴 빨간콩 폭풍!':'🔴 Röd Böna Storm!',
'🔴🔴 콩 비!':'🔴🔴 Böna Regn!',
'🌊 부채꼴 충격파!':'🌊 Fläkt Chockvåg!',
'✴ 멸광 레이저!':'✴ Förintelselaser!',
'🔴 추적 장판!':'🔴 Spårzon!',
'💥 속성탄!':'💥 Elementskott!',
'⚔ 검기!':'⚔ Svärd Ki!','⚔ 재단참!':'⚔ Skörde Hugg!',
'🌀 나선탄!':'🌀 Spiralskott!','⚠ 찌르기!':'⚠ Stöt!',
'🔥🔥 지옥기둥!':'🔥🔥 Helvetespelare!',
'⚔ 환영검!':'⚔ Fantasmsvärd!',
'💢 반격자세!':'💢 Motangreppshållning!',
'⚔ 연격!':'⚔ Kombo!','🌑 암흑!':'🌑 Mörker!',
'👥 분신!':'👥 Klon!','🌋 균열!':'🌋 Spricka!',
'🌊 파동!':'🌊 Ripple!','💣 추적지뢰!':'💣 Spårande Mina!',
'⏪ 되감기!':'⏪ Spola tillbaka!','🌀 중력장!':'🌀 Gravitationsfält!',
'🔨 벽밀기!':'🔨 Väggknuff!','☠ 독안개!':'☠ Giftdimma!',
'⛓ 감옥!':'⛓ Fängelse!','⚡ 연쇄번개!':'⚡ Kedjeblixt!',
'🔮 궤도탄!':'🔮 Orbitalt Skott!','🛡 방패돌진!':'🛡 Sköldanfall!',
'🪞 반격자세!':'🪞 Motangreppshållning!','⚓ 속박!':'⚓ Binda!',
'👤 분신!':'👤 Klon!','🖐 탈취!':'🖐 Stjäla!',
'🔥🔥 용암 지대!':'🔥🔥 Lavazon!',
'🌧🌧 화염 폭격!':'🌧🌧 Eldbarrage!',
'⚡⚡ 전격 장막!':'⚡⚡ Blixtgardinen!',
'💀 내 곁으로!':'💀 Kom till mig!',
'⭕ 안전!':'⭕ Säker!',
'💀💀 전멸 폭발!':'💀💀 Utrotningsexplosion!',
'⚡ 쐐기 소멸!':'⚡ Kil Utrotning!',
'🌊충격파!':'🌊Chockvåg!',
'👿악의+100':'👿Ondska+100',
'💥패링폭발!':'💥Pareringsexplosion!',
'균열 충돌! ':'Spricke Kollision! ',
'벽 충돌! ':'Vägg Kollision! ',
'소환!':'Framkallning!','환영!':'Fantom!',
'⚡낙뢰!':'⚡Åska!','⚡빔!':'⚡Stråle!',
'환영술!':'Illusion!','💀소환!':'💀Framkallning!',
'🔮주술!':'🔮Förbannelse!','🩸산란!':'🩸Fortplantning!',
'💢광폭!':'💢Raseri!','🕷산란!':'🕷Fortplantning!',
'❄서리!':'❄Frost!','❄빙결파!':'❄Frysningsvåg!',
'💀빙마!':'💀Isdemon!',
// --- mob actions ---
'돌진!':'Anfall!','충격파!':'Chockvåg!','독안개!':'Giftdimma!',
'연타!':'Salva!','포효!':'Bröl!','강화!':'Förstärkt!',
'꼬리!':'Svans!','은신...':'Smyger...','기습!':'Bakhåll!',
'산란!':'Fortplantning!','독가스!':'Giftgas!','소멸...':'Upplöser...',
'강타!':'Slag!','분비!':'Utsöndring!','채찍!':'Piska!',
'출혈!':'Blödning!','급강하!':'Dykning!','방출!':'Urladdning!',
'충격!':'Påverkan!','치유!':'Helning!','의식!':'Ritual!',
'지옥불!':'Helveteseld!','끌려감!':'Dragen!','혀!':'Tunga!',
'응시!':'Stirrar!','낙하!':'Fall!','핏방울!':'Blodsdroppe!',
'일어남!':'Reser sig!','휩쓸기!':'Svep!','웅크림':'Kryper ihop',
'뼈칼날!':'Benblad!','감속!':'Sakta ner!','비명!':'Skrik!',
'화산탄!':'Vulkanskott!','자폭!':'Självförstöring!','감싸기!':'Omsluta!',
'잡기!':'Greppa!','내리찍기!':'Nedslag!','브레스!':'Andetag!',
'비행!':'Flykt!','용암비!':'Lavaregn!','물뿜기!':'Vattenstråle!',
'빛...':'Ljus...','삼키기!':'Svälja!','마비!':'Förlamning!',
'방전!':'Urladdning!','집게찍기!':'Tangslag!','찍기!':'Nedslag!',
'붙잡기!':'Greppa!','감아올리기!':'Lindar upp!','파편!':'Fragment!',
'할퀴기!':'Riva!','기생충!':'Parasit!',
'심연 해방!':'Avgrunds Befrielse!','촉수난타!':'Tentakelstorm!',
'삼지창!':'Trident!','소용돌이!':'Virvel!','해일!':'Tsunami!',
'끼걱!':'Knarrande!','폭발!':'Explosion!','체인!':'Kedja!',
'갈기!':'Man!','공포!':'Terror!','흡혈!':'Dränkning!',
'베기!':'Hugg!','비이이명!!':'Riiing!!','분열!':'Delning!',
'3연참!':'Triple Hugg!','패링!':'Parering!',
'...복사...':'...Kopiering...','불균형...저주!':'Obalans...Förbannelse!',
'저주!':'Förbannelse!','균형...강화!':'Balans...Förstärkt!',
'심판의 기둥!':'Domspelare!','처형 선고!':'Dödsdom!',
'고통의 해방!':'Smärtbefrielse!','너도 느껴봐라!':'Känn detta också!',
'대검난무!':'Tvåhandssvärd Raseri!','촉수!':'Tentakel!',
'전방위 빔!':'Omni-Stråle!','회피!':'Undvik!',
// --- rare mob / merchant ---
'[F] 상점':'[F] Butik','거래 성공!':'Handel Lyckad!',
'악의 부족! (':'Inte tillräckligt Ondska! (',
'상인이 떠납니다...':'Köpmannen lämnar...',
'사슬 해방!':'Kedjebefrielse!','완전 해방!':'Full Befrielse!',
'⏪ 시간 되감기!':'⏪ Tidsspolning!','전환!':'Byte!',
'부활 ':'Återuppståndelse ','🌀균열!':'🌀Spricka!','...사라짐':'...Försvann',
'낫 베기!':'Lie Hugg!','☠ 죽음의 선고!':'☠ Dödsdom!',
'선고 집행...':'Verkställer dom...',
'⚡패링!':'⚡Parering!','경직!':'Stagger!',
'⚠ 잡혔다!':'⚠ Gripen!','💥 내던지기!':'💥 Kast!',
'💥 소용돌이 폭발!':'💥 Virvle Explosion!',
'👻 순간이동!':'👻 Teleportering!','💫 기절! 5초':'💫 Bedövad! 5s',
'찌르기 반격!':'Stötmotangrepp!','💢 폭발!':'💢 Explosion!',
'반격 실패':'Motangrepp Misslyckat','탈취 반격!':'Stjäl Motangrepp!',
'무기 봉인!':'Vapentätning!','냠!':'Nom!',
// --- stage/room/map ---
'합체!':'Fusionerad!','출구가 열렸다!':'Utgång öppnad!',
'보물상자 출현!':'Skattkista dök upp!','출구':'Utgång',
'⚠ 문지기가 살아있다!':'⚠ Grindvakt fortfarande vid liv!',
'⏱ 타임어택 ':'⏱ Tidsangrepp ',
'처치율 ':'Kill-andel ',
'무적!':'Osårbar!','불사 보호':'Odödligt Skydd',
'빙결!':'Fryst!','환영 소멸!':'Fantom Försvann!',
'부활력 ':'Uppståndelsekraft ',
'✟ 신성력 억제! (':'✟ Helig Undertryckning! (',
'부활 실패 (':'Återuppståndelse Misslyckad (',
'⚡순간이동!':'⚡Teleportering!',
'👻 동반부활!':'👻 Med-Återuppståndelse!',
'✟ 신성력 억제!':'✟ Helig Undertryckning!',
'💀 부활 판정 중...':'💀 Uppståndelse bedömning...',
'⚔ 문지기 처치!':'⚔ Grindvakt Besegrad!',
'🚪 보스방 개방!':'🚪 Bossrum Öppnat!',
'잔해 출현!':'Skräp dök upp!',
'🌀균열 발생!':'🌀Spricka öppnad!',
'🔥복수!':'🔥Hämnd!','💥폭독혈!':'💥Pestblod!',
'빙판!':'Isgolv!','❄빙결파!':'❄Frysningsvåg!',
'❄최종빙결!':'❄Slutgiltig Frysning!','빙마 처치!':'Isdemon Besegrad!',
'분리!':'Separera!','뼈 파편!':'Benfragment!',
'태아 처치!':'Foster Besegrad!','지배자 처치!':'Överherre Besegrad!',
'용암!':'Lava!','화룡 처치!':'Elddrak Besegrad!',
'최후의 비명!':'Sista Skrik!','산화...':'Oxidering...',
'심판자 처치!':'Domare Besegrad!','고통의 왕 처치!':'Smärtkung Besegrad!',
'수역!':'Vatten!','파편 폭발!':'Fragmentexplosion!',
'거대어 처치!':'Leviathan Besegrad!','대사도 처치!':'Höga Aposteln Besegrad!',
'독웅덩이!':'Giftpöl!','화염장판!':'Eldzon!','전기장!':'Elektriskt Fält!',
'무기 드롭!':'Vapendropp!','보물 발견!':'Skatt Hittad!',
'상인의 주머니 +':'Köpmannspung +',
'속박의 파편!':'Bindningsskärva!','시간의 조각!':'Tidsfragment!',
'저주 해제!':'Förbannelse Upphävd!','차원의 결정!':'Dimensionell Kristall!',
'전설 아이템!':'Legendärt Föremål!','죽음을 이겨냈다!':'Besegrade Döden!',
'💥대폭발!':'💥Megaexplosion!','⚡강화!':'⚡Förstärkt!',
// --- combat/defense ---
'장비 ':'Utrustning ',
'💫 진동!':'💫 Vibration!','❄ 무적!':'❄ Osårbar!',
'\u{1F47B} 유령!':'\u{1F47B} Ande!',
'집중 해제!':'Fokus Avbryt!','집중!':'Fokus!',
'🕊️ 평화보호 ':'🕊️ Freds Sköld ',
'🛡 보호막 ':'🛡 Sköld ',
'🌀 회전보호막 ':'🌀 Snurrsköld ',
'💥한방캡!':'💥En-Träff Gräns!',
'⚡쉴드 파괴!':'⚡Sköldförstöring!',
'💀 불굴!':'💀 Orubblig!',
'💀 1회부활!':'💀 1-Liv Återuppståndelse!',
'감시 회수':'Vakt Återkalla',
'악마화 부활!':'Demonisk Återuppståndelse!',
// --- skill panel ---
'기검참':'Ki Hugg','날개치기':'Vingeslag',
'배정 가능한 스킬 없음':'Inga färdigheter att tilldela',
'칼날 없음!':'Inget Blad!',
'⚔ 악의사냥!':'⚔ Ondskejakt!',
'❄🌪️ 얼음소용돌이!':'❄🌪️ Isvirvelvind!',
'🌪️ 폭풍소환!':'🌪️ Virvelvindsframkallning!',
'\u{1F9B4} 해골무덤!':'\u{1F9B4} Bengrav!',
'🌹 붉은꽃!':'🌹 Karmosinblomning!',
'💥 폭산탄!':'💥 Explosivt Skott!',
'🪡 바늘출!':'🪡 Nålutbrott!',
'⚡ 전격이동!':'⚡ Blixtdash!',
'기둥가시로 흡수됨':'Absorberad av pelartagg',
'🌿 가시덫!':'🌿 Taggfälla!',
'👻 유령총!':'👻 Andepistol!','💥 유령총 폭발!':'💥 Andepistol Explosion!',
'⚡ 전격의창!':'⚡ Åskaspjut!',
'🏹 공성쇠뇼 설치!':'🏹 Belägringsarmborst Placerat!',
'👻 유령 허수아비!':'👻 Fantom Lockbete!',
'💥 폭발 허수아비!':'💥 Explosivt Lockbete!',
'축적!':'Lagrat!','축적 중...':'Lagrar...','만충! 재입력→폭발':'Full! Återtyck→Explosion',
'폭발! ':'Explosion! ','불발...':'Försök misslyckades...','뎀':' SKA',
'🩸 폭독칼날!':'🩸 Pestblad!',
'⚡날개치기!':'⚡Vingeslag!',
'🗡 칼등날개!':'🗡 Sköldvinge!',
'🏛️ 악의기둥!':'🏛️ Mörk Pelare!',
'🌿 기둥가시!':'🌿 Pelartagg!',
'🌋 지옥강타!':'🌋 Helvetesslag!',
'💥 체간 붕괴!':'💥 Hållningskollaps!',
'💫 포이즈 파괴!':'💫 Hållningsförstöring!',
'⚡ 뇌전걸음!':'⚡ Andevandring!',
'✟ 구속의 영역!':'✟ Bindande Domän!',
'✟ 신성폭발!':'✟ Helig Explosion!',
'⛧ 블랙!':'⛧ Svart Stjärna!',
'🌋 용암소환!':'🌋 Lava Framkallning!',
'필살기 배정!':'Ultimat Tilldelad!',
'완료':'Slutförd','합체 가능':'Kan Fusionera','부족':'Otillräcklig',
'SP 부족! (':'SP behövs! (',
'🕊️ 히든: 평화의보호 해금!':'🕊️ Dold: Fredens Sköld upplåst!',
'⚡ 히든: 참회 해금!':'⚡ Dold: Ånger upplåst!',
'배정됨':'Tilldelad',
'합체 Lv.':'Fusion Lv.',
'◆ 같은 보석 스킬 습득 시 합체 가능':'◆ Kan fusionera vid inlärning av samma juvel färdighet',
// --- inventory/forge/storage ---
'▼ 가방 → 창고 보관':'▼ Väska → Lager',
'▲ 창고 → 가방 꺼내기':'▲ Lager → Väska',
'✓ 선택됨':'✓ Vald',
'⟨ 입력 대기... ⟩':'⟨ Väntar... ⟩',
'⟨ 대기 ⟩':'⟨ Vänta ⟩',
'보조':'Sub',
'키 설정 초기화 (또는 F5 키)':'Återställ tangentbindning (eller F5)',
'아무 키 또는 마우스 버튼을 누르세요 (ESC = 취소)':'Tryck en tangent eller musknapp (ESC = avbryt)',
'WebGPU 활성':'WebGPU Aktiv','WebGL2 활성':'WebGL2 Aktiv',
'측정 중...':'Mäter...',
'불러오기 실패':'Inläsning Misslyckad',
'장착':'Utrustad',
'🔒 중요잠금 아이템은 분해 선택 불가!':'🔒 Viktigt-låsta föremål kan inte väljas för demontering!',
'장비 강화 (실패 시 재료만 소멸)':'Förbättra Utrustning (vid misslyckande förlorar bara material)',
'강화 보너스 적용':'Förbättringsbonus Tillämpat',
'강화 실패!':'Förbättring Misslyckad!',
'장착된 장비가 없습니다.':'Ingen utrustning utrustad.',
'충분':'Tillräckligt','더 필요':'Behöver Mer',
'장비 선택':'Välj Utrustning','목표치 설정':'Ange Mål',
'악의 투입':'Investera Ondska','자동 시도':'Auto Försök',
'목표 강화치':'Mål Förbättring',
'예상 필요 악의':'Uppskattad Ondska Behövd',
'보유':'Ägd','강화 시작':'Starta Förbättring',
'위에서 장비를 선택하세요':'Välj utrustning ovan',
'⬆ 물약 강화 (최대 10단)':'⬆ Förbättra Dryck (max nivå 10)',
'필요':'Krävs',
'악의의 분해로 — 장비를 악의로 갈아버려라':'Ondska Ugn — Mal utrustning till ondska',
'전체 선택':'Välj Alla','전체 해제':'Avmarkera Alla',
'희귀 이하':'Sällsynt eller Lägre',
'어픽스 리롤!':'Affix Omrullning!',
'결정 분해 → 결정 가루':'Kristall Demontering → Kristalldamm',
'결정 제작 (가루 → 결정)':'Tillverka Kristall (Damm → Kristall)',
'물리':'Fysisk','영웅':'Heroisk','전설':'Legendär',
'무기 타입':'Vapentyp','활 타입':'Bågtyp',
'보스방':'Bossrum','ST 부족':'Inte tillräckligt ST',
// --- Phase 14 ---
'💀 광폭화!':'💀 Rasande!',
'...따라오는 거 아니야. 같은 방향일 뿐이지.':'...Jag följer dig inte. Bara samma riktning.',
'공기가 달라졌어. 더 썩었군.':'Luften har förändrats. Mer förrutnelse.',
'여기부터는 악마 영역이야. ...맘대로 해.':'Demonomräde härifrån. ...Gör som du vill.',
'...이 냄새. 살점이 썩는 냄새야.':'...Den lukten. Ruttnande kött.',
'여기 오래 있으면 미쳐. 나도, 너도.':'För länge här och du blir galen. Jag också.',
'이 길의 끝에 뭐가 있을까. ...알고 싶지도 않어.':'Vad finns i slutet av den här vägen? ...Vill inte veta.',
'...여기가 끝이야. 돌아갈 길은 없어.':'...Det här är slutet. Ingen väg tillbaka.',
// --- idle tips ---
'작살을 땅에 꽂으면 끌려간다.':'Stick in harpunen i marken och bli dragen.',
'Shift로 작살 던져봐!':'Försök kasta harpunen med Shift!',
'패링 성공하면 ST가 회복된다. 공짜 자원이야.':'Parering återställer ST. Gratis resurser.',
'패링 많이 하면 ST 걱정 없어~':'Parera mycket och ST är aldrig ett problem~',
'장비 분해하면 악의를 얻는다. 쓰레기도 자원이야.':'Demontera utrustning för Ondska. Även skräp är resurser.',
'TAB 열어서 안 쓰는 장비 분해해!':'Öppna TAB och demontera oanvänd utrustning!',
'그로기 상태의 적에겐 1.5배 데미지가 들어간다.':'Bedövade fiender tar 1,5x skada.',
'무릎 꿇으면 전력으로 때려!':'När de knäfaller, slå med allt!',
'속성 상성이 있다. 화염은 빙결에 약하고, 암전은 암흑에 약하다.':'Element har motdelar. Eld är svagt mot Is, Blixt mot Mörker.',
'무기 속성 바꿔가면서 싸워봐!':'Försök byta vapenelement!',
'빙결된 적은 1.5배 데미지를 받는다.':'Frusna fiender tar 1,5x skada.',
'얼리고 때리는 게 기본이야!':'Frysa och slå — det är grunderna!',
'보스의 빨간 공격은 패링 가능. 보라빛은 회피만.':'Röda bossangrepp kan pareras. Regnbåge undvik bara.',
'색깔 잘 봐! 빨강은 받아치고 무지개는 피해!':'Se på färgerna! Parera rött, undvik regnbågen!',
'VIT를 올리면 최대 HP가 오른다. 죽기 싫으면 찍어.':'VIT höjer max HP. Investera om du vill leva.',
'STR은 근접, DEX는 활, INT는 마법! 골고루 말고 하나만!':'STR för närstrid, DEX för bågar, INT för magi! Fokusera på ett!',
'E를 꾹 누르면 빔이 나간다. 짧게 누르면 투사체.':'Håll E för stråle. Tryck E för projektil.',
'마법 쓸 때 MP 잘 봐! 빔은 연속으로 깎여!':'Se upp med MP med magi! Stråle dränker snabbt!',
'핵터와 디로이가 아이템을 주워준다. 수거 범위 안이면.':'Hecter och Deroy samlar automatiskt föremål i räckhåll.',
'우리한테 고마워해~ 안 주우면 썩잖아.':'Tacka oss~ Föremål ruttnar om ingen plockar upp dem.',
'LCK를 올리면 레어 드롭률이 오른다.':'LCK ökar sällsynt droppchans.',
'운빨 게임이긴 하지~ LCK 올려봐!':'Det är allt tur~ Försök höja LCK!',
'강화하면 공격력이 쭉쭉 올라가! 악의만 있으면 돼!':'Förbättring ökar ATK snabbt! Behöver bara Ondska!',
'강화 확률은 +1에서 99%. 높을수록 떨어진다.':'Förbättringschans börjar vid 99% för +1. Sjunker efter det.',
'실패하면 악의만 날아가~ 장비는 안 부서져!':'Vid misslyckande förlorar bara Ondska~ Utrustning överlever!',
'대장간에서 장비 제작도 된다. 악의 30000개면 영웅급 이상.':'Smedjan kan också tillverka. 30000 Ondska för Heroisk+.',
'랜덤이지만 좋은 거 나올 수도 있어!':'Slumpmässigt, men kanske något bra!',
'쉴드는 마법으로, HP는 물리로 깎아야 제대로 먹힌다.':'Sköld behöver magi, HP behöver fysisk.',
'반대로 치면 50%만 들어가! 무기 바꿔가면서 싸워!':'Fel typ ger bara 50%! Byt vapen!',
'장비에 접두사, 접미사가 붙으면 특수 효과가 생긴다.':'Utrustning med för-/suffix får specialeffekter.',
'영웅급 이상 장비에만 붙어! 좋은 거 나오면 강화해!':'Bara på Heroisk+ utrustning! Förbättra bra resultat!',
'강화는 장비를 바꿔도 자동 이전된다. 악의만 있으면.':'Förbättring överförs automatiskt. Kostar bara Ondska.',
'더 좋은 장비 나오면 바로 장착해! 강화 수치 그대로 옮겨가!':'Utrusta bättre gear direkt! Förbättring överförs!',
// --- Phase 14 additional tutorial ---
'패링을 써야 자원을 흡수한다고!':'Du måste parera för att absorbera resurser!',
'F키 회복의 영역을 써봐. 자원이 차올라.':'Prova F-tangent Heligt Domän. Resurser fylls på.',
'적이 근접하면 스페이스키야! 가시덫을 활용해!':'När fiender kommer nära, använd Mellanslagstangenten! Använd Taggfälla!',
'기절시켜! 그로기가 터지면 데미지가 1.5배야!':'Bedöva dem! Bedövning ger 1,5x skada!',
'1번 대왕치기로 밀어버려!':'Använd tangent 1 Jätteslag för att knuffa tillbaka!',
'무릎 꿇었다.':'Det knäfaller.',
'지금이야! 몰아쳐!!':'Nu! Driv på angreppet!!',
'스킬 포인트 있어! K 눌러서 스킬 찍어봐!':'Färdighetspoäng tillgängliga! Tryck K för att lära!',
'...힘이 없으면 여기서 끝이야.':'...Utan kraft slutar det här.',
'...쓸 거 아니면 분해해.':'...Demontera vad du inte behöver.',
'아이템 넘쳐나네~ 우리가 주워줄게!':'Så många föremål~ Vi samlar åt dig!',
'악의가 바닥이다.':'Ondska slut.',
'TAB 열어서 장비 분해해! 쓰레기도 악의가 돼!':'Öppna TAB och demontera utrustning! Även skräp blir Ondska!',
'좋은 장비가 있네! G 눌러서 대장간 가봐!':'Bra utrustning! Tryck G för smedjan!',
'...강화 안 하면 그냥 고철이야.':'...Utan förbättring är det bara skrot.',
'...멈추지 마. 여신은 기다리지 않는다.':'...Stanna inte. Gudinnan väntar inte.',
'앞으로 가자~ 나도 여기 오래 있기 싫어.':'Låt oss gå vidare~ Jag vill inte heller stanna länge här.',
'...냄새가 짙다. 큰 놈이 있어.':'...Lukten är stark. Något stort är här.',
'준비됐어? 물약 확인하고!':'Redo? Kontrollera dina drycker!',
// --- Phase 15 ---
'TAB을 눌러. 가방을 열고 장비를 입어야 한다.':'Tryck TAB. Öppna din väska och sätt på utrustningen.',
'주웠으면 껴야지! TAB!':'Plockade upp det? Sätt på det! TAB!',
'G. 대장간에서 물약도 제작할 수 있다.':'G. Du kan också tillverka drycker vid smedjan.',
'악의로 물약 만들어! G키야!':'Tillverka drycker med Ondska! G-tangent!',
'기절이야! Ctrl 눌러!':'Bedövad! Tryck Ctrl!',
'Ctrl 유령걸음으로 탈출!':'Ctrl Andevandring för att fly!',
'Ctrl 얼음보주로 탈출!':'Ctrl Iskula för att fly!',
'빨간 탄은 우클릭 패링. 무지개는 Q 패링.':'Röda kulor: RMB parera. Regnbåge: Q parera.',
'나머지는 전부 우클릭 패링 가능해!':'Allt annat kan pareras med RMB!',
'빨강=우클릭, 무지개=Q 패링. 나머진 다 쳐내.':'Rött=RMB, Regnbåge=Q parera. Avvärja resten.',
'무지개는 Q로 패링! 나머지는 전부 우클릭!':'Regnbåge med Q! Allt annat RMB!',
'빠져! 물약 마시고 안전한 곳에서 회복해.':'Dra dig tillbaka! Drick drycker och återhämta på säker plats.',
'자원 없으면 도망가는 게 답이야!':'Inga resurser? Fly är svaret!',
'스페이스! 가시덫으로 적 묶어버려!':'Mellanslagstangent! Fäst dem med Taggfälla!',
'근접이 너무 많아! 거리 벌려!':'För många närstridare! Skapa avstånd!',
'...둘러싸이면 끝이야. 빠져나와.':'...Omringad och det är slut. Bryt ut.',
'1번 대왕치기로 쓸어버려!':'Använd tangent 1 Jätteslag för att svepa bort dem!',
'그로기 터지면 데미지 1.5배!':'Bedövning ger 1,5x skada!',
'회전참이나 광역기로 몰아! 한 놈씩 상대하면 죽어.':'Använd Virvelvind eller Område! En i taget och du dör.',
'뭉쳐있을 때가 기회야!':'När de klumpar sig, är det din chans!',
'E로 마력공격을 해봐! 악의 쉴드를 해제할려면 마법 공격을 해야 해!':'Prova E för magiangrepp! Du behöver magi för att bryta Ondskasköldarna!',
'쉴드는 마법으로, HP는 물리로. 반대로 치면 데미지 안 들어간다.':'Sköldarna med magi, HP med fysisk. Fel typ ger ingen skada.',
'L키로 스킬 슬롯에 넣어야 쓸 수 있어.':'Tryck L för att tilldela färdigheter till fack.',
'C키를 눌러. 패시브 포인트가 쌓여있다.':'Tryck C. Passiva poäng har ansamlats.',
'C키! 패시브 올리면 진짜 강해져!':'Tryck C! Passiva gör dig mycket starkare!',
'스태미나가 부족하다. 무리하지 마.':'Låg uthållighet. Överdriva inte.',
'ST 없으면 스킬 못 써! 잠깐 빠져!':'Ingen ST innebär inga färdigheter! Dra dig tillbaka!',
'탭 장비창을 열어봐. 아이템을 주워왔어!':'Öppna TAB utrustningsmenyn. Vi plockade upp ett föremål!',
'좋은 거 나왔다! TAB 열어서 확인해봐!':'Något bra droppade! Öppna TAB för att kontrollera!',
'악의에 중독되면 악마가 돼서 부활력이 생긴대. 저 녀석처럼.':'De säger att Ondskasberoende gör dig till en demon med uppståndelsekraft. Som den där.',
'혹시 너도...?':'Kanske du också...?',
'데미지가 부족하면 무기류 강화를 해야해!!':'Om skada är bristfällig, förbättra vapnen!!',
'G키 대장간. 강화 안 하면 여기서 계속 죽어.':'G-tangent smedja. Utan förbättring fortsätter du dö här.',
'시간이 없어. 움직여.':'Ingen tid. Rör dig.',
'멍하게 서있으면 안 돼!':'Stå inte bara där!',
'...뭘 기다리는 거야?':'...Vad väntar du på?',
'가자가자! 몬스터가 기다려!':'Kör igång! Monster väntar!',
'여기 오래 있으면 위험해.':'Att stanna för länge här är farligt.',
'움직여야 해! 가만있으면 둘러싸여!':'Måste röra sig! Stå stilla och de omringar dig!',
'쉬는 건 죽고 나서 해.':'Vila efter att du är död.',
'살아있을 때 쉬면 안 돼!':'Ingen vila medan du lever!',
'적이 몰려오고 있어. 빨리 움직여.':'Fiender är på väg. Rör dig snabbt.',
'냄새 맡고 올 거야. 빨리!':'De luktar dig. Skynda!',
'...아직 살아있는 거 맞지?':'...Du lever fortfarande, eller?',
'혹시 잠든 거야...?':'Somnade du...?',
// --- Chapter entry ---
'...나무가 썩어가고 있어. 여기는 지옥의 입구야.':'...Träden ruttnar. Det här är ingången till helvetet.',
'냄새 지독해... 빨리 지나가자.':'Stanken är fruktansvärd... Låt oss snabbt passera.',
'조심해. 벌레굴이다. 벽이랑 바닥에서 기어나와.':'Försiktig. Maskhåla. De kryper från väggar och golv.',
'으으... 벌레 싫어! 밟아버려!':'Ugh... Jag hatar insekter! Trampa på dem!',
'...공기가 얼어붙는다. 여기선 화염이 먹힌다.':'...Luften fryser. Eld fungerar här.',
'추워... 빙결 조심해! 얼면 끝이야.':'Kallt... Se upp för frysning! Frys och det är slut.',
'용암이다. 바닥을 밟으면 타 죽어.':'Lava. Trampa på golvet och du bränner ihjäl dig.',
'뜨거워! 여기 왜 이렇게 빨개!':'Så varmt! Varför är allt så rött här!',
'...군단이다. 수가 많아. 광역기 없으면 밀려.':'...Legionen. För många. Utan Område blir du överväldigad.',
'우글우글... 징그러워. 한꺼번에 쓸어!':'Överallt vimmel... Äckligt. Sopa bort alla på en gång!',
'사도의 영역이야. 여기 놈들은 머리가 좋아.':'Apostelns territorium. Dessa är smarta.',
'패턴이 복잡해졌어... 집중해!':'Mönster blev komplexa... Fokusera!',
'...끝이다. 지옥의 심장부. 살아 돌아가는 건 포기해라.':'...Det här är det. Helvetets hjärta. Ge upp hoppet om återvändo.',
'여기가 마지막이야... 각오해.':'Det här är slutet... Förbered dig.',
// --- Remaining ---
'단계 ×':' x',
'⚡ 기동전폭! x':'⚡ Kedjeexplosion! x',
'🔥🔥 3중폭!':'🔥🔥 Brand x3!','🔥🔥🔥 6중폭!':'🔥🔥🔥 Brand x6!','🔥🔥🔥🔥 9중폭!':'🔥🔥🔥🔥 Brand x9!','💥 불꽃폭발! ':'💥 Branddetonering! ',
'🔥 기동불꽃 준비!':'🔥 Kedjebrand Redo!',
'🔨 기동파괴 준비!':'🔨 Kedjeförstöring Redo!',
'⚡ 기동전폭 준비!':'⚡ Kedjeexplosion Redo!',
'⚡ 기동파괴! ':'⚡ Kedjeförstöring! T',
'🔥 기동불꽃!':'🔥 Kedjebrand!',
'🔥 기동불꽃! ':'🔥 Kedjebrand! T',
'❄빙결!':'❄Fryst!','🟢독!':'🟢Gift!','⚡감전!':'⚡Chockad!','🔥화상!':'🔥Brinnande!',
'✦ 여신의 가호 — SP+5 AP+3':'✦ Gudinnans Välsignelse — SP+5 AP+3',
'⚔ 기동칼날개!':'⚔ Bladsvinge!',
'🔥 화염관통!':'🔥 Eldgenomborring!',
'🔱 관통!':'🔱 Genomborring!',
'⚔ 칼날!':'⚔ Blad!',
'💥 착지!':'💥 Landning!',
'💫 기절!':'💫 Bedövad!',
'⚡ 체간삭감!':'⚡ Hållningsbrott!',
'클릭으로 선택 · ESC로 닫기':'Klicka för att välja · ESC för att stänga',
'선택됨':'Vald',
'악의 부족! (30)':'Inte tillräckligt Ondska! (30)',
'MP 부족! (40)':'Inte tillräckligt MP! (40)','MP 부족! (100)':'Inte tillräckligt MP! (100)','MP 부족! (10)':'Inte tillräckligt MP! (10)',
'MP 부족! (':'Inte tillräckligt MP! (',
'✟ 시전...':'✟ Gjutning...','🌋 시전...':'🌋 Gjutning...','⛧ 시전...':'⛧ Gjutning...',
'❄ 진입!':'❄ Ingång!',
'🔱 작살!':'🔱 Harpun!',
'레벨 부족! (요구: Lv.':'Nivå för låg! (Krav: Lv.',
' 장착!':' Utrustad!',
' 해제':' Avrustad',
'👿 악의 추출: +':'👿 Ondska Extraktion: +',
'F 슬롯 해제':'F Fack avaktiverat',
'💫 집중...':'💫 Fokus...',
'⚡ 마력연사!':'⚡ Magisk Beskjutning!',
'🪞 반격!':'🪞 Motangrepp!','💢 반격!':'💢 Motangrepp!',
'흡수!':'Absorbera!','반격 발사!':'Motangreppskytte!',
'저주! 드랍률 -50%':'Förbannelse! Droppchans -50%','도망!':'Fly!',
'위상!':'Fas!','방어!':'Försvar!',
'회수 HP+':'Återkalla HP+','이동식 복귀':'Bärbar Återvändo',
'약점!':'Svaghet!','저항!':'Motstånd!',
'콤보 종료: ':'Kombo Slut: ',
'악의 +':'Ondska +',
'저주 ':'Förbannelse ','불발...':'Försök misslyckades...',
'작살 약점!':'Harpun Svaghet!',
'전염 x':'Pest x','흡수 완료!':'Absorption Slutförd!',
'부활 성공!':'Återuppståndelse Lyckad!','부활 실패...':'Återuppståndelse Misslyckad...',
'차원 이동!':'Dimensionellt Skifte!',
'기절 해제':'Bedövning Upphävd',
'악의 부족':'Inte tillräckligt Ondska',
'스킬 미습득':'Inga färdigheter lärda','펼치기':'Expandera','접기':'Kollapsera',
'조건 미달!':' ej uppfylld!','해제!':' Avfusionerad!',
'자동 ON':' Auto PÅ','자동 OFF':' Auto AV','스킬 해제':' färdighet avaktiverad',
'닫기':'Stäng','장착 중':'Utrustad','보관 아이템':'Lagrat Föremål',
'🔨 제작':'🔨 Tillverka',
'분해할 아이템이 없습니다.':'Inga föremål att demontera.',
'스킬 미습득':'Inga färdigheter lärda',
'석궁 자동발사 (T)':'Armborst automatisk (T)',
'버스트루프 당기기 (H)':'Burst-slinga dra (H)',
'결정 자동합성':'Kristall auto-syntes',
'결정 자동강화':'Kristall auto-förstärkning',
'✓ 설정 자동 저장':'✓ Inställningar auto-sparade',
'세팅 프리셋 저장/불러오기':'Spara/ladda förinställning',
'세팅1 저장':'Spara förinställning 1','세팅1':'Förinställning 1',
'세팅2 저장':'Spara förinställning 2','세팅2':'Förinställning 2',
'재진단':'Omdiagnostisera',
'게임 리셋 (처음부터)':'Återställ spel (från början)',
'캐릭터 선택 (로비)':'Karaktärsval (Lobby)',
'닫기 [ESC]':'Stäng [ESC]','닫기 [G]':'Stäng [G]','닫기 [V]':'Stäng [V]','닫기 [C]':'Stäng [C]',
'전체화면 (F11)':'Helskärm (F11)',
'정말 모든 진행을 초기화하시겠습니까?':'Vill du verkligen återställa all framsteg?',
'검출 중...':'Detekterar...',
'마우스 커서':'Muspekare','그래픽 품질':'Grafikkvalitet','하드웨어 진단':'Maskinvarudiagnostik',
'BGM 선택':'BGM-val',
'자동 (스테이지별)':'Automatisk (per etapp)','전체 랜덤':'Allt slumpmässigt','로비':'Lobby',
'1장 랜덤':'Kapitel 1 slumpmässigt','2장 랜덤':'Kapitel 2 slumpmässigt','3장 랜덤':'Kapitel 3 slumpmässigt',
'4장 랜덤':'Kapitel 4 slumpmässigt','5장 랜덤':'Kapitel 5 slumpmässigt','6장 랜덤':'Kapitel 6 slumpmässigt','7장 랜덤':'Kapitel 7 slumpmässigt',
'보스':'Boss','최종보스':'Slutboss',
'대장간 랜덤':'Smedja slumpmässigt','사망 랜덤':'Döden slumpmässigt','승리 랜덤':'Seger slumpmässigt',
'지옥 추락 사망 징글':'Helvetesfalls-dödsjingel','탈출 성공':'Flykt lyckades',
'── 1장 - 썩은 숲 ──':'── CH1 - Rotten Forest ──','── 2장 - 벌레굴 ──':'── CH2 - Worm Nest ──',
'── 3장 - 얼음굴 ──':'── CH3 - Ice Cavern ──','── 4장 - 화염지대 ──':'── CH4 - Infernal Wastes ──',
'── 5장 - 지옥군단 ──':'── CH5 - Hell Legion ──','── 6장 - 사도마굴 ──':'── CH6 - Apostle Den ──',
'── 7장 - 지옥성 ──':'── CH7 - Hell Citadel ──','── 공통 ──':'── Common ──',
'⌨ 조작법':'⌨ Kontroller','클릭하면 닫힘':'Klicka för att stänga',
'전투력':'SV','가방':'Väska','결정':'Kristall',
'↕ 정렬':'↕ Sortera','쓰레기 전체선택':'Välj allt skräp','쓰레기 전부 분해':'Demontera allt skräp',
'창고':'Lager','스탯 포인트':'Attributpoäng','능력치 요약':'Statsöversikt','올 리셋':'Återställ allt',
'대장간':'Smedja','스킬':'Färdigheter','능력치':'Attribut',
'좌클스킬 (클릭 전환)':'VK-färdighet (klick för att byta)','우클스킬 (클릭 전환)':'HK-färdighet (klick för att byta)',
'이동스킬 (클릭 전환)':'Rörelsefärdighet (klick för att byta)','마법스킬 (클릭 전환)':'Magifärdighet (klick för att byta)',
'영역스킬 (클릭 전환)':'Områdesfärdighet (klick för att byta)','피보호막 (클릭 전환)':'Blodsköld (klick för att byta)',
'CT스킬 (클릭 전환)':'CT-färdighet (klick för att byta)','[C] 능력치':'[C] Attribut',
'무기 공격':'Vapenangrepp','칼등 처내기 (투사체 반사, 홀드 연사)':'Parera (reflekterar projektiler, håll=salva)',
'연속 처내기':'Kontinuerlig parera','영역 스킬 (폭풍소환 등)':'Områdesfärdighet (Virvelvind etc)',
'작살 발사':'Skjuta harpun','마법 (탭=투사체, 홀드=빔)':'Magi (tryck=projektil, håll=stråle)',
'데빌포스 흡수':'Absorbera djävulskraft','물약 / 스킬슬롯':'Drycker / Färdighetsplatser',
'스킬슬롯 5 / 필살기 / CT스킬':'Plats 5 / Ultimat / CT-färdighet','스킬 슬롯 배정':'Platstilldelning',
'진혼의':'Helgande',
'만화광선':'Luminescensstråle',
'🏹 공성쇠뇌 설치!':'🏹 Belägringsarmborst Placerad!',
// --- Phase 27 additions ---
'위로 이동':'Rör uppåt','아래로 이동':'Rör nedåt','왼쪽 이동':'Rör vänster','오른쪽 이동':'Rör höger',
'칼등 처내기 (탭=처내기, 홀드=연사)':'Bladparera (tryck=parera, håll=salva)',
'영역 스킬':'Områdesfärdighet','작살 이동':'Harpun Dash',
'유령불꽃 켜기/끄기':'Spökflamma Av/På','기동칼날개 자동 켜기/끄기':'Bladsvinge Auto Av/På',
'해상도':'Upplösning',
'빛이 꺼졌다':'Ljuset slocknar','누군가는 너를 기다리고 있다':'Någon väntar på dig',
'다시 일어서라':'Res dig igen','로비로 돌아가기':'Återgå till Lobbyn',
'☠ 사망 리플레이':'☠ Dödsrepris',
'지옥의 시련을 견뎌냈다':'Du har uthärdat Helvetets prövning',
'계속 전투':'Fortsätt strid','난이도를 선택하라':'Välj svårighetsgrad',
'나중에 설정(ESC)에서 변경 가능':'Kan ändras i Inställningar (ESC) senare',
'일괄합성':'Bulksyntes','일괄강화+합성':'Bulkförstärk+Syntes',
'자원 부족!':'Resurser Slut!',' 뎀':' Skd',
'합체 폭발!':'Fusionsdetonation!',
'MP 부족! (50)':'Inte tillräckligt MP! (50)',
'부활력 고갈!':'Återuppståndelse Tömd!','☠ 부활력 고갈!':'☠ Återuppståndelse Tömd!',
'독안개':'Giftdimma','뇌전창':'Åskspjut',
'🔥 업화선 시전...':'🔥 Helvetesstråle gjutning...',
'💥 기동파괴 그로기!':'💥 Kedjeförstöring Groggy!',
'💥 칼등 그로기!':'💥 Bladparera Groggy!',
'⚡ 순간이동 준비!':'⚡ Teleportering Redo!',
'👿악의+1000':'👿Ondska+1000',
'💀 내려찍기!':'💀 Nedhack!',
'✟ 신성력 억제! +':'✟ Helig Kraft Undertryckt! +',
'✟ 신성력 억제!':'✟ Helig Kraft Undertryckt!',
'✟ 신성력 억제! (':'✟ Helig Kraft Undertryckt! (',
'💥 지진그로기!':'💥 Jordbävnings-Groggy!',
'💥 기폭그로기!':'💥 Detonations-Groggy!',
'폭발! ×':'Explosion! ×','⚫ 기둥강타!':'⚫ Pelarsmash!',
'💥 대왕치기 그로기!':'💥 Kolossalt Groggy!',
'💫 미니스턴!':'💫 Mini Stun!','⚡ 뇌전창!':'⚡ Åskspjut!',
'…절반이다. 정신차려.':'…Halvt liv. Skärp dig.',
'…죽기 직전이다. 한 발만 더.':'…Nästan död. Ett slag till.',
'…다음 한 방이 마지막이야.':'…Nästa träff är den sista.',
'기절! ':'Bedövad! ',
'마력이 빈다. 평타 섞어.':'MP töms. Blanda in normalattacker.',
'그랩이다. 거리를 둬.':'Greppattack. Håll avstånd.',
'광역기다. 멀어져.':'Områdesattack. Drag dig undan.',
'…아파? 당연하지. 여긴 지옥이야.':'…Ont? Självklart. Det här är helvetet.',
'F키도 스킬 슬롯이야!':'F är ett färdighetsfack!',
'L-CTRL로 유령걸음/얼음보주!':'L-CTRL för Spökvandring / Iskula!',
'V 눌러서 창고에 넣어둬!':'Tryck V för att lagra!',
'ESC로 설정! 난이도/자동물약!':'ESC för inställningar! Svårighet/Auto-drycker!',
'잡몹이다. 먼저 정리해.':'Vanliga fiender. Rensa dem först.',
'…얼어붙은 놈은 오래 안 간다.':'…En fryst fiende håller inte länge.',
'…냄새가 짙다. 큰 놈이 있어.':'…Lukten är stark. Något stort är nära.',
'쉴드는 마법으로, HP는 물리로.':'Sköld tar magi, HP tar fysisk.',
'스페이스! 가시덫으로 적 묶어!':'Mellanslag! Fäst fiender med Taggfälla!',
'근접 너무 많아! 거리 벌려!':'För många på nära håll! Sprid ut dig!',
'회전참이나 광역기로 몰아!':'Använd Virvelvind eller Område!',
'F 눌러! 회복의 영역 깔아!':'Tryck F! Lägg ut Heligt Domän!',
'F키 회복의 영역을 써봐.':'Prova F-tangent Heligt Domän.',
'빠져! 물약 마시고 회복해.':'Dra dig tillbaka! Drick drycker och återhämta.',
'쉬프트! 사슬기동은 이동기야!':'Shift! Kedjedash är ett rörelseverktyg!',
'스킬포인트 쌓였어! K 눌러!':'Färdighetspoäng redo! Tryck K!',
'스킬 포인트 있어! K!':'Färdighetspoäng! K!',
'C키. 패시브 포인트가 쌓여있다.':'C-tangent. Passiva poäng har samlats.',
'…쓸 거 아니면 분해해.':'…Demontera det du inte ska använda.',
'…강화 안 하면 그냥 고철이야.':'…Utan förstärkning är det bara skrot.',
'빨간 탄은 우클릭. 무지개는 Q.':'Röda kulor: högerklick. Regnbåge: Q.',
'빨강=우클릭, 무지개=Q.':'Röd=högerklick, regnbåge=Q.',
'…멈추지 마. 여신은 기다리지 않는다.':'…Stoppa inte. Gudinnan väntar inte.',
'패턴이 바뀐다. 거리를 둬.':'Mönstret ändras. Håll avstånd.',
'미쳐가고 있어. 광폭화다.':'Det blir galet. Raseriläge.',
'마지막이야! 끝장내!':'Sista fasen! Avsluta det!',
'…끝났다. 다음으로.':'…Klart. Vidare.',
'다 잡았다! 포탈 어딨어?':'Alla fångade! Var är portalen?',
'근육으로 만든 빌드군. 베고 부숴.':'Muskelbygge. Hugg och krossa.',
'활을 쥐었군. 거리를 둬.':'Båge i hand. Håll avstånd.',
'마법사군. MP 관리부터 배워라.':'Magiker. Lär dig MP-hantering först.',
'운에 기댄 빌드군. …드롭은 좋겠어.':'Tursbaserat bygge. …Åtminstone blir droppen bra.',
'…VIT가 너무 낮아. 한 방에 죽는다.':'…VIT är för lågt. Du dör på ett slag.',
'다 찍으면 다 약해진다. 하나만 골라.':'Maxa allt och du är svag överallt. Välj ett.',
'…3단. 적이 강해져. 정신 차려.':'…Etapp 3. Fiender starkare. Fokusera.',
'5단이다. …너도 강해졌단 뜻이야.':'Etapp 5. …Det betyder att du också blivit starkare.',
'…7단. 아직 살아있단 게 신기하군.':'…Etapp 7. Fortfarande vid liv. Förvånande.',
'10단. …너는 이제 인간이 아니야.':'Etapp 10. …Du är inte längre mänsklig.',
'…일반으로 내려왔군. 가끔은 쉬어가야지.':'…Tillbaka till Normal. Ibland behöver man en paus.',
'…이게 진짜 패링이야.':'…Det är en riktig parera.',
'…피가 묻기 시작했군.':'…Blodet börjar rinna.',
'100. 너는 인간이 아니야.':'100. Du är inte mänsklig.',
'…피 흘리며 베는군.':'…Hugger genom blod.',
'빨간콩이 푸르게 변했다. 그게 너의 무기야.':'Den röda kulan blev blå. Det är ditt vapen.',
'무지개를 받아쳤군. 그건 진짜 어렵다.':'Parerade en regnbåge. Det är verkligen svårt.',
'…너무 빨라. 닿기 직전에 눌러.':'…För snabbt. Tryck precis innan kontakt.',
'악의가 가득 찼다. 풀어내.':'Ondskan är full. Släpp lös den.',
'작살이 살을 뚫었어. 끌고 와.':'Harpunen trängde igenom köttet. Dra in den.',
'…풀차지군. 멀리 던져버려.':'…Fulladdad. Kasta den långt.',
'…빈틈을 그대로 빠져나갔다.':'…Smög rakt igenom glipan.',
'…일반 잡몹이 아니야. 모디파이어 붙었군.':'…Inte en vanlig fiende. Den har en modifikator.',
'엘리트 하나 처리.':'Elite ner.',
'…큰 놈이다. 일반 잡몹 정리부터.':'…Stor en. Rensa de vanliga fienderna först.',
'미니보스 처리. 다음 길로.':'Mini-boss ner. Vidare till nästa väg.',
'한 번에 다섯. 깔끔해.':'Fem på en gång. Snyggt.',
'100강. 이제 뭔가 다르게 보이는군.':'+100. Saker ser annorlunda ut nu.',
'…운이 없는 날이야.':'…Otur idag.',
'…전설이다. 이런 건 처음 본다.':'…Legendarisk. Aldrig sett en sådan.',
'…죽었다 살아났네. 여신은 너를 포기 안 했어.':'…Dog och kom tillbaka. Gudinnan gav inte upp dig.',
'…또야? 패턴 좀 외워!':'…Igen? Lär dig mönstret!',
'…한 번도 안 죽고. 그건 진짜 실력이야.':'…Inte dött en enda gång. Det är verklig skicklighet.',
'…ACT1을 끝냈다. 진짜 시작은 여기서부터야.':'…ACT1 klar. Det riktiga starten är härifrån.',
'모든 보스를 무너뜨렸다. 너는 지옥의 일부야.':'Alla bossar nedlagda. Du är en del av helvetet.',
'…30초. 너 진짜 미쳤구나.':'…30 sekunder. Du är verkligen galen.',
'…빠르군. 효율적이야.':'…Snabb. Effektiv.',
'신기록이다.':'Nytt rekord.',
'탭 장비창을 열어봐.':'Öppna utrustningsfönstret med TAB.',
'데미지 부족하면 무기 강화!':'Inte tillräckligt skada? Förstärk vapnet!',
// --- Loading screen ---
'불러오는 중...':'Laddar...',
'로딩중...':'Laddar...',
'맵과 몬스터 불러오는 중...':'Laddar karta och monster...',
'기본 데이터 준비 중...':'Förbereder grunddata...',
'저장 데이터 불러오는 중...':'Laddar sparad data...',
'몬스터 스킨 로딩...':'Laddar monsterskins...',
'맵과 몬스터 생성 중...':'Genererar karta och monster...',
'맵 에셋 로딩...':'Laddar kartresurser...',
'맵 환경 준비 중...':'Förbereder kartmiljön...',
'주변 청크 준비 중...':'Förbereder närliggande chunks...',
'맵 캐시 생성 중...':'Bygger kartcache...',
'미니맵 빌드 중...':'Bygger minimapa...',
// Phase 28
' 으로 탈출!':' — fly!',
'100명?! 미쳤어!':'100 kills?! Galet!',
'10단 최고난이도! 너 진짜 광기야!':'Svårighet 10 max! Fullständigt galen!',
'1분 안에 클리어! 빠르네!':'Bana klar på 1 min! Så snabbt!',
'30초!! 스피드런 가능해!':'30 sekunder!! Speedrun-potential!',
'3단! 보상도 좋아지지만 죽기 쉬워!':'Svårighet 3! Bättre belöningar men lättare att dö!',
'50명! 학살자야!':'50 kills! Slaktare!',
'5단!! 진짜 게이머 인증!':'Svårighet 5!! Äkta gamer certifierad!',
'7단!! 다른 사람들 이 정도 못 와!':'Svårighet 7!! Andra tar sig inte så långt!',
'ACT1 완주! 우리가 진짜 해냈어!':'AKT 1 klar! Vi klarade det verkligen!',
'Ctrl 얼음보주로 탈출하라.':'Ctrl — fly med Iskula.',
'Ctrl 유령걸음으로 탈출하라.':'Ctrl — fly med Spökvandring.',
'C키! 패시브 강해져!':'Tangent C! Passives blir starkare!',
'DEX 빌드! 거리에서 패고, 추적탄 좋아!':'DEX-build! Distansattacker, spårande projektiler!',
'E로 마력공격을 해봐!':'Prova magisk attack med E!',
'G 눌러서 대장간 가봐!':'Tryck G — smedja!',
'G키 대장간. 강화 안 하면 계속 죽어.':'G — smedja. Inga uppgraderingar, fortsätt dö.',
'HP 70%! 조심해!':'HP 70%! Var försiktig!',
'INT 빌드! 빔이랑 폭발 마법! MP 잘 봐!':'INT-build! Strålar och explosiv magi! Kolla MP!',
'LCK 높아! 레어 드롭률 미친 거 알지?':'Högt LCK! Dropchanserna är galna!',
'L로 어디에 뭘 넣을지 골라!':'Tryck L — välj färdighetsslot-layout!',
'MP 부족! 평타로 패면서 회복해!':'MP lågt! Slå för att återhämta!',
'ST 없으면 스킬 못 써!':'Inget ST, inga färdigheter!',
'STR 빌드! 회전참, 회오리, 광역기 추천!':'STR-build! Snurrhugg, virvelstorm, AoE!',
'VIT 좀 찍어! HP 너무 적어!':'Lägg till VIT! HP för lågt!',
'Z 누르면 대박! 쿨타임 길어!':'Tryck Z för ultimat! Lång avkylningstid!',
'…고기 냄새. 싫진 않네.':'…Blodlukt. Inte dåligt.',
'…둘러싸이면 끝이야.':'…Omringad betyder död.',
'…말은 못해.':'…Kan inte prata.',
'…버리기 아까운 건 창고에.':'…Värdefulla saker i lagret.',
'…빈틈을 노려.':'…Vänta på öppningar.',
'…설정을 확인해.':'…Kontrollera inställningar.',
'…슬롯을 채워. 빈 손은 죽음이다.':'…Fyll slots. Tomma händer är död.',
'…아직 살아있네. 좌클릭으로 저것들 쳐봐.':'…Fortfarande vid liv. Vänsterklicka för att slå dem.',
'…운이 좋았을 뿐이야. 아마.':'…Bara tur. Förmodligen.',
'…치는 건 할 줄 아네. 피하는 건?':'…Kan slå. Kan undvika?',
'…힘을 골라라. 전부 가질 순 없다.':'…Välj din styrka. Kan inte ha allt.',
'골고루 안 돼! 하나로 밀어!':'Sprid inte! Satsa på ett!',
'그로기 터지면 1.5배!':'Groggy = 1,5x skada!',
'길이 열렸다.':'Vägen är öppen.',
'나머진 전부 우클릭 패링 가능!':'Resten — högerklick parra!',
'나머진 전부 우클릭!':'Resten — högerklick!',
'다섯 번 연속! 내가 본 인간 중 최고!':'Fem i rad! Bäste jag sett!',
'다음엔 죽지 마!':'Dö inte nästa gång!',
'더블탭 전격이동으로 탈출하라.':'Dubbeltryck dash för att fly.',
'소환수 왔어! 먼저 처리해야 해!':'Besvärjelser! Rensa dem först!',
'스킬 없으면 방향키 연타뿐이야.':'Inga färdigheter? Spamma bara piltangenter.',
'신기록!! 스트리머한테 보내!':'Nytt rekord!! Skicka till streamern!',
'아이템 넘쳐! 우리가 주워줄게!':'Väskan full! Vi plockar upp åt dig!',
'안 죽고 깼어! 진짜 천재 맞네!':'Klar utan dödsfall! Äkta geni!',
'앞으로 가자~':'Framåt~',
'우리가 해냈어! 다음 챕터 가자!':'Vi klarade det! Nästa kapitel!',
'일반 모드! 편하게 즐기자!':'Normalläge! Ta det lugnt!',
'자원이 반이다. F키로 회복해.':'Resurser halvfulla. Tryck F för att återhämta.',
'잡힌다! 옆으로 빠져!':'Fångas! Dodga åt sidan!',
'장비 분해해! 쓰레기도 악의!':'Demontera utrustning! Skräp ger också ondska!',
'전부 다 잡았어! 우리가 지옥의 왕이야!':'Allt rensat! Helvetets kungar!',
'좋은 거 나왔다! TAB!':'Bra loot! TAB!',
'죽기 직전에 죽이다니! 멋져!':'Dödade precis innan döden! Imponerande!',
'체력 반 남았어! 물약 마실 타이밍!':'Halvt HP! Drickdags för potion!',
'큰 거 온다! 도망쳐!':'Stort anfall! Spring!',
'패링으로 돌려주고, Q 보호막도 써!':'Parra och reflektera, använd Q-sköld!',
'패턴이 빨라졌어!':'Mönster snabbare!',
'한 대만 맞아도 죽어! 패링이든 회피든!!':'Ett träff = död! Parra eller undvik!!',
'한 방이면 죽어! 도망쳐!!':'Ett skott dödar! Spring!!',
'화염엔 빙결! 암전엔 암흑!':'Eld → is! Tomhet → skugga!',
'── 2장 - 벌레굴 ──':'── CH2 - Worm Nest ──',
'── 4장 - 화염지대 ──':'── CH4 - Infernal Wastes ──',
'── 6장 - 사도마굴 ──':'── CH6 - Apostle Den ──',
'── 공통 ──':'── Common ──',
'난이도를 선택하라':'Välj svårighetsgrad',
'☠ 부활력 고갈!':'☠ Återupplivning Slut!',
'⏳⚡ 시간걸음!':'⏳⚡ Tidssteg!',

'블룸 효과':'Bloom-effekt',
'잔상 트레일':'Eftersläpningsspår',
'슬래시 이펙트':'Slash-effekt',
'후처리 효과':'Efterbehandling',
'사망 이펙트':'Dödseffekt',
'동적 조명':'Dynamisk belysning',
'횃불 조명 (어둠)':'Fackelljus (mörker)',
'앰비언트 파티클':'Miljöpartiklar',
'안개 효과':'Dimmaeffekt',
'필름 그레인':'Filmkorn',
'캐릭터 외곽선':'Karaktärskontур',
'리롤':'Kasta om',
'물약':'Trolldryck',
'으로 탈출!':'för att fly!',
'Shift 작살':'Shift Harpun',
'더블탭 전격이동':'Dubbeltryck — Blixtdash',
'Ctrl 유령걸음':'Ctrl Spöksteg',
'Ctrl 얼음보주':'Ctrl Isklot',
'🔴화염→빙결 2배 | 🔵빙결→화염 2배 | ⚪물리=중립 | 악마 처치 시 악의 영혼 드롭':'🔴Eld→Is 2× | 🔵Is→Eld 2× | ⚪Fys=Neutral | Döda demoner för illviljesjälar',
};

_SV_PFX={
'녹슨':'Rostig','강철':'Stål','흑요석':'Obsidian','미스릴':'Mithril','심판의':'Domen','천벌의':'Gudomlig Vrede','파멸의':'Förstörelse',
'불꽃':'Flamma','화염':'Inferno','염화':'Helveteseld','지옥불':'Helvetesglöd','지옥화':'Helvetesglöd','지옥':'Helvetesglöd','멸화의':'Utrotande',
'냉기':'Frost','빙결':'Fryst','빙하':'Glacial','서리의':'Rim','서리':'Rim','영겁빙':'Evigt Is',
'그림자':'Skugga','암흑':'Mörker','심연':'Avgrund','나락의':'Nether','나락':'Nether','무간의':'Tomrum',
'전기':'Gnista','낙뢰':'Åska','암전':'Blixt','뇌신의':'Stormguden','뇌신':'Stormguden','만뢰의':'Tusen Åskor',
'축복':'Välsignad','성광':'Heligt Ljus','신성':'Sakral','천사의':'Änglalik','신벌의':'Gudomlig Dom',
'낡은':'Sliten','천':'Tyg','가죽':'Läder','강철사':'Stålvävd','은':'Silver','은사':'Silvertråd','화염의':'Inferno','빙결의':'Fryst','암흑의':'Mörker','암전의':'Blixt'
};
const _SV_PFX={
'녹슨':'Rostig','강철':'Stål','흑요석':'Obsidian','미스릴':'Mithril','심판의':'Domen','천벌의':'Gudomlig Vrede','파멸의':'Fördärvlig',
'불꽃':'Flamma','화염':'Eld','염화':'Helveteseld','지옥불':'Helvetesglöd','지옥화':'Helvetesglöd','지옥':'Helvete','멸화의':'Utrotande',
'냉기':'Frost','빙결':'Is','빙하':'Glacial','서리의':'Rim','서리':'Rim','영겁빙':'Evigt Is',
'그림자':'Skugga','암흑':'Mörker','심연':'Avgrund','나락의':'Nether','나락':'Nether','무간의':'Tomrum',
'전기':'Gnista','낙뢰':'Åska','암전':'Blixt','뇌신의':'Stormguden','뇌신':'Stormguden','만뢰의':'Tusen Åskor',
'축복':'Välsignad','성광':'Heligt Ljus','신성':'Helig','천사의':'Änglalik','신벌의':'Gudomlig Dom',
'낡은':'Sliten','천':'Tyg','가죽':'Läder','강철사':'Stålvävd','은':'Silver','은사':'Silvertråd',
'화염의':'Inferno','빙결의':'Fryst','암흑의':'Förbannad','암전의':'Blixt'};
const _SV_BASE={
'대검':'Tvåhandssvärd','석궁':'Armborst','연사석궁':'Repeterarmborst','마력석궁':'Magiskt Armborst',
'견갑':'Sköld','대견갑':'Stor Sköld','전투화':'Stridsstövlar','갑옷':'Rustning','갑주':'Rustning',
'왕관':'Krona','장갑':'Handskar','건틀릿':'Pansarhandskar','바지':'Byxor','각반':'Benskydd',
'허리띠':'Bälte','벨트':'Bälte','부적':'Talisman','목걸이':'Halsband','반지':'Ring',
'망토':'Kappa','팔찌':'Armband','귀걸이':'Örhänge'
};
