const fs = require('fs');
const path = require('path');
const BASE = 'G:/hell';

// 언어별 번역 (key = 한국어 원문)
const TRANS = {
  '블룸 효과': {zh:'泛光效果',ja:'ブルームエフェクト',es:'Efecto Bloom',zht:'泛光效果',ru:'Эффект свечения',de:'Bloom-Effekt',ptbr:'Efeito Bloom',fr:'Effet Bloom',pl:'Efekt Bloom',it:'Effetto Bloom',uk:'Ефект свічення',tr:'Bloom Efekti',vi:'Hiệu ứng Bloom',th:'เอฟเฟกต์บลูม',id:'Efek Bloom',ar:'تأثير الإشراق',sv:'Bloom-effekt',da:'Bloom-effekt',no:'Bloom-effekt',fi:'Bloom-efekti',cs:'Bloom efekt',hu:'Bloom hatás',ro:'Efect Bloom',nl:'Bloom-effect',el:'Εφέ Bloom',bg:'Блум ефект'},
  '잔상 트레일': {zh:'残影轨迹',ja:'残像トレイル',es:'Rastro de imagen residual',zht:'殘影軌跡',ru:'След от остаточного изображения',de:'Nachbild-Spur',ptbr:'Rastro de imagem residual',fr:'Traîne d\'image rémanente',pl:'Ślad powidoku',it:'Scia residuale',uk:'Слід залишкового зображення',tr:'Artık İz',vi:'Vệt ảnh lưu',th:'แสงลากหาง',id:'Jejak Bayangan',ar:'أثر الصورة اللاحقة',sv:'Eftersläpningsspår',da:'Efterbilledspor',no:'Etterbildespor',fi:'Jälkikuvaraita',cs:'Stopa doznívání',hu:'Utókép nyom',ro:'Urmă imagine reziduală',nl:'Nabeeldspoor',el:'Ίχνος αμυδρής εικόνας',bg:'Следа от残像'},
  '슬래시 이펙트': {zh:'斩击特效',ja:'スラッシュエフェクト',es:'Efecto de tajo',zht:'斬擊特效',ru:'Эффект удара',de:'Hieb-Effekt',ptbr:'Efeito de corte',fr:'Effet de taille',pl:'Efekt cięcia',it:'Effetto fendente',uk:'Ефект удару',tr:'Kesme Efekti',vi:'Hiệu ứng chém',th:'เอฟเฟกต์ฟัน',id:'Efek Tebas',ar:'تأثير الشرطة',sv:'Slash-effekt',da:'Slash-effekt',no:'Slash-effekt',fi:'Viiltoefekti',cs:'Efekt seku',hu:'Vágás hatás',ro:'Efect de tăiere',nl:'Slash-effect',el:'Εφέ κοπής',bg:'Ефект на удар'},
  '후처리 효과': {zh:'后处理效果',ja:'ポストプロセス',es:'Efectos de postproceso',zht:'後處理效果',ru:'Пост-обработка',de:'Nachbearbeitung',ptbr:'Pós-processamento',fr:'Post-traitement',pl:'Post-processing',it:'Post-elaborazione',uk:'Постобробка',tr:'Post-işlem',vi:'Hậu xử lý',th:'เอฟเฟกต์หลังประมวลผล',id:'Efek Pasca-proses',ar:'معالجة ما بعد التقديم',sv:'Efterbehandling',da:'Efterbehandling',no:'Etterbehandling',fi:'Jälkikäsittely',cs:'Post-processing',hu:'Utófeldolgozás',ro:'Post-procesare',nl:'Nabewerking',el:'Μεταεπεξεργασία',bg:'Постобработка'},
  '사망 이펙트': {zh:'死亡特效',ja:'死亡エフェクト',es:'Efecto de muerte',zht:'死亡特效',ru:'Эффект смерти',de:'Todeseffekt',ptbr:'Efeito de morte',fr:'Effet de mort',pl:'Efekt śmierci',it:'Effetto morte',uk:'Ефект смерті',tr:'Ölüm Efekti',vi:'Hiệu ứng chết',th:'เอฟเฟกต์ตาย',id:'Efek Kematian',ar:'تأثير الموت',sv:'Dödseffekt',da:'Dødseffekt',no:'Dødseffekt',fi:'Kuolinefekti',cs:'Efekt smrti',hu:'Halál hatás',ro:'Efect de moarte',nl:'Doodseffect',el:'Εφέ θανάτου',bg:'Ефект смърт'},
  '동적 조명': {zh:'动态光照',ja:'ダイナミックライティング',es:'Iluminación dinámica',zht:'動態光照',ru:'Динамическое освещение',de:'Dynamische Beleuchtung',ptbr:'Iluminação dinâmica',fr:'Éclairage dynamique',pl:'Dynamiczne oświetlenie',it:'Illuminazione dinamica',uk:'Динамічне освітлення',tr:'Dinamik Işıklandırma',vi:'Ánh sáng động',th:'แสงไดนามิก',id:'Pencahayaan Dinamis',ar:'إضاءة ديناميكية',sv:'Dynamisk belysning',da:'Dynamisk belysning',no:'Dynamisk belysning',fi:'Dynaaminen valaistus',cs:'Dynamické osvětlení',hu:'Dinamikus világítás',ro:'Iluminare dinamică',nl:'Dynamische verlichting',el:'Δυναμικός φωτισμός',bg:'Динамично осветление'},
  '횃불 조명 (어둠)': {zh:'火炬光照(暗)',ja:'松明ライト（暗闇）',es:'Luz de antorcha (oscuridad)',zht:'火炬光照（暗）',ru:'Свет факела (тьма)',de:'Fackelbeleuchtung (Dunkel)',ptbr:'Luz de tocha (escuridão)',fr:'Lumière torche (obscurité)',pl:'Światło pochodni (ciemność)',it:'Luce torcia (buio)',uk:'Світло смолоскипа (темрява)',tr:'Meşale Işığı (Karanlık)',vi:'Ánh đuốc (tối)',th:'แสงคบเพลิง (มืด)',id:'Cahaya Obor (Gelap)',ar:'ضوء المشعل (ظلام)',sv:'Fackelljus (mörker)',da:'Fakkelbelysning (mørke)',no:'Fakkelbelysning (mørke)',fi:'Soihtuvalot (pimeys)',cs:'Světlo pochodně (tma)',hu:'Fáklya fény (sötét)',ro:'Lumină torță (întuneric)',nl:'Fakkelverlichting (donker)',el:'Φως δαδιού (σκοτάδι)',bg:'Светлина на факла (тъмнина)'},
  '앰비언트 파티클': {zh:'环境粒子',ja:'アンビエントパーティクル',es:'Partículas ambientales',zht:'環境粒子',ru:'Атмосферные частицы',de:'Umgebungspartikel',ptbr:'Partículas ambiente',fr:'Particules d\'ambiance',pl:'Cząstki otoczenia',it:'Particelle ambientali',uk:'Частинки навколишнього середовища',tr:'Ortam Partikülleri',vi:'Hạt môi trường',th:'อนุภาคสภาพแวดล้อม',id:'Partikel Ambient',ar:'جزيئات الأجواء',sv:'Miljöpartiklar',da:'Miljøpartikler',no:'Omgivelsespartikler',fi:'Ympäristöhiukkaset',cs:'Ambientní částice',hu:'Környezeti részecskék',ro:'Particule de ambianță',nl:'Omgevingsdeeltjes',el:'Σωματίδια περιβάλλοντος',bg:'Атмосферни частици'},
  '안개 효과': {zh:'雾效',ja:'フォグ効果',es:'Efecto de niebla',zht:'霧效',ru:'Эффект тумана',de:'Nebeleffekt',ptbr:'Efeito de névoa',fr:'Effet de brouillard',pl:'Efekt mgły',it:'Effetto nebbia',uk:'Ефект туману',tr:'Sis Efekti',vi:'Hiệu ứng sương mù',th:'เอฟเฟกต์หมอก',id:'Efek Kabut',ar:'تأثير الضباب',sv:'Dimmaeffekt',da:'Tågeeffekt',no:'Tåkeeffekt',fi:'Sumuefekti',cs:'Efekt mlhy',hu:'Köd hatás',ro:'Efect de ceață',nl:'Misteffect',el:'Εφέ ομίχλης',bg:'Ефект мъгла'},
  '필름 그레인': {zh:'胶片颗粒',ja:'フィルムグレイン',es:'Grano de película',zht:'底片顆粒',ru:'Зернистость плёнки',de:'Filmkorn',ptbr:'Grão de filme',fr:'Grain cinématographique',pl:'Ziarno filmowe',it:'Grana cinematografica',uk:'Зернистість плівки',tr:'Film Tanesi',vi:'Hạt phim',th:'เกรนฟิล์ม',id:'Butiran Film',ar:'حبيبات الفيلم',sv:'Filmkorn',da:'Filmkorn',no:'Filmkorn',fi:'Filmijyvä',cs:'Filmové zrno',hu:'Filmszem',ro:'Grăunțe film',nl:'Filmkorrel',el:'Κόκκος φιλμ',bg:'Зърно на филм'},
  '캐릭터 외곽선': {zh:'角色轮廓',ja:'キャラクターアウトライン',es:'Contorno del personaje',zht:'角色輪廓',ru:'Контур персонажа',de:'Charakterumriss',ptbr:'Contorno do personagem',fr:'Contour du personnage',pl:'Kontur postaci',it:'Contorno personaggio',uk:'Контур персонажа',tr:'Karakter Konturu',vi:'Đường viền nhân vật',th:'เส้นขอบตัวละคร',id:'Garis Tepi Karakter',ar:'مخطط الشخصية',sv:'Karaktärskontур',da:'Karakteromrids',no:'Karakterkontur',fi:'Hahmon ääriviiva',cs:'Obrys postavy',hu:'Karakterkontúr',ro:'Contur personaj',nl:'Karakteromtrek',el:'Περίγραμμα χαρακτήρα',bg:'Контур на герой'},
  '리롤': {zh:'重投',ja:'リロール',es:'Relanzar',zht:'重投',ru:'Перебросить',de:'Neu würfeln',ptbr:'Relançar',fr:'Relancer',pl:'Przerzut',it:'Rilancio',uk:'Перекинути',tr:'Yeniden At',vi:'Tái đổ',th:'โยนใหม่',id:'Lempar Ulang',ar:'إعادة الرمي',sv:'Kasta om',da:'Kast igen',no:'Kast om',fi:'Heita uudelleen',cs:'Znovu hodit',hu:'Újradobás',ro:'Rerunare',nl:'Opnieuw gooien',el:'Ανακύλισε',bg:'Преметни'},
  '물약': {zh:'药水',ja:'ポーション',es:'Poción',zht:'藥水',ru:'Зелье',de:'Trank',ptbr:'Poção',fr:'Potion',pl:'Mikstura',it:'Pozione',uk:'Зілля',tr:'İksir',vi:'Thuốc',th:'ยา',id:'Ramuan',ar:'جرعة',sv:'Trolldryck',da:'Eliksir',no:'Eliksir',fi:'Juoma',cs:'Lektvar',hu:'Bájital',ro:'Poțiune',nl:'Drankje',el:'Φίλτρο',bg:'Зелие'},
  '기절!': {zh:'眩晕!',ja:'スタン!',es:'¡Aturdido!',zht:'眩暈!',ru:'Оглушение!',de:'Betäubt!',ptbr:'Atordoado!',fr:'Étourdi!',pl:'Ogłuszony!',it:'Stordito!',uk:'Оглушено!',tr:'Sersemletildi!',vi:'Choáng!',th:'มึนงง!',id:'Pingsan!',ar:'مذهول!',sv:'Bedövad!',da:'Bedøvet!',no:'Bedøvet!',fi:'Tainnutettu!',cs:'Omráčen!',hu:'Elkábítva!',ro:'Ameţit!',nl:'Verdoofd!',el:'Ζάλη!',bg:'Зашеметен!'},
  '으로 탈출!': {zh:'逃脱!',ja:'で脱出!',es:'¡para escapar!',zht:'逃脫!',ru:'для побега!',de:'zum Entkommen!',ptbr:'para escapar!',fr:'pour s\'échapper!',pl:'żeby uciec!',it:'per scappare!',uk:'для втечі!',tr:'kaçmak için!',vi:'để thoát!',th:'เพื่อหนี!',id:'untuk kabur!',ar:'للهروب!',sv:'för att fly!',da:'for at flygte!',no:'for å flykte!',fi:'paetaksesi!',cs:'k úniku!',hu:'a meneküléshez!',ro:'pentru a fugi!',nl:'om te ontsnappen!',el:'για να ξεφύγεις!',bg:'за бягство!'},
  'Shift 작살': {zh:'Shift鱼叉',ja:'Shiftハープーン',es:'Shift Arpón',zht:'Shift魚叉',ru:'Shift Гарпун',de:'Shift Harpune',ptbr:'Shift Arpão',fr:'Shift Harpon',pl:'Shift Harpun',it:'Shift Arpione',uk:'Shift Гарпун',tr:'Shift Zıpkın',vi:'Shift Lao',th:'Shift ฉมวก',id:'Shift Tombak',ar:'Shift الحربة',sv:'Shift Harpun',da:'Shift Harpun',no:'Shift Harpun',fi:'Shift Harppuuna',cs:'Shift Harpuna',hu:'Shift Szigony',ro:'Shift Harpon',nl:'Shift Harpoen',el:'Shift Αγκίστρι',bg:'Shift Харпун'},
  '더블탭 전격이동': {zh:'双击冲刺',ja:'ダブルタップ瞬間移動',es:'Doble tap — Dash relámpago',zht:'雙擊衝刺',ru:'Двойной тап — Молниеносный рывок',de:'Doppeltippen — Blitz-Dash',ptbr:'Toque duplo — Avanço relâmpago',fr:'Double appui — Dash éclair',pl:'Podwójne dotknięcie — Błyskawiczny skok',it:'Doppio tap — Scatto fulmine',uk:'Подвійне натискання — Блискавичний ривок',tr:'Çift Dokunuş — Şimşek Koşusu',vi:'Nhấn đúp — Lướt điện',th:'แตะสองครั้ง — วิ่งฟ้าผ่า',id:'Ketuk Dua Kali — Melesat',ar:'نقر مزدوج — اندفاع صاعقة',sv:'Dubbeltryck — Blixtdash',da:'Dobbelttryk — Lynnedstyr',no:'Dobbeltrykk — Lynglimt',fi:'Kaksoisnäppäys — Salama-piikata',cs:'Dvojité klepnutí — Bleskový skok',hu:'Dupla érintés — Villám-roham',ro:'Apăsare dublă — Săritură fulger',nl:'Dubbeltik — Bliksemdash',el:'Διπλό πάτημα — Αστραπένια ορμή',bg:'Двойно докосване — Мълниеносен рив'},
  'Ctrl 유령걸음': {zh:'Ctrl幽灵步',ja:'Ctrlゴーストウォーク',es:'Ctrl Paso fantasma',zht:'Ctrl幽靈步',ru:'Ctrl Шаг призрака',de:'Ctrl Geisterschritt',ptbr:'Ctrl Passo fantasma',fr:'Ctrl Pas fantôme',pl:'Ctrl Krok ducha',it:'Ctrl Passo fantasma',uk:'Ctrl Крок привида',tr:'Ctrl Hayalet Adımı',vi:'Ctrl Bước Ma',th:'Ctrl ก้าวผี',id:'Ctrl Langkah Hantu',ar:'Ctrl خطوة الشبح',sv:'Ctrl Spöksteg',da:'Ctrl Spøgelsegang',no:'Ctrl Spøkelsegang',fi:'Ctrl Aaveaskellus',cs:'Ctrl Krok přízraku',hu:'Ctrl Szellemlépés',ro:'Ctrl Pas fantomă',nl:'Ctrl Geestenstap',el:'Ctrl Βήμα Φαντάσματος',bg:'Ctrl Стъпка призрак'},
  'Ctrl 얼음보주': {zh:'Ctrl冰球',ja:'Ctrlアイスオーブ',es:'Ctrl Orbe de hielo',zht:'Ctrl冰球',ru:'Ctrl Ледяная сфера',de:'Ctrl Eisorb',ptbr:'Ctrl Orbe de gelo',fr:'Ctrl Orbe de glace',pl:'Ctrl Kula lodu',it:'Ctrl Sfera di ghiaccio',uk:'Ctrl Крижана сфера',tr:'Ctrl Buz Küre',vi:'Ctrl Cầu Băng',th:'Ctrl ลูกกลมน้ำแข็ง',id:'Ctrl Bola Es',ar:'Ctrl كرة الجليد',sv:'Ctrl Isklot',da:'Ctrl Iskugle',no:'Ctrl Iskule',fi:'Ctrl Jääpallo',cs:'Ctrl Ledová koule',hu:'Ctrl Jéggömb',ro:'Ctrl Sferă de gheață',nl:'Ctrl Ijsbol',el:'Ctrl Σφαίρα πάγου',bg:'Ctrl Ледена сфера'},
  'Ctrl 유령걸음으로 탈출하라.': {zh:'按Ctrl用幽灵步逃脱。',ja:'Ctrlゴーストウォークで脱出せよ。',es:'Ctrl: escapa con Paso Fantasma.',zht:'按Ctrl以幽靈步逃脫。',ru:'Ctrl — уйди через Шаг призрака.',de:'Ctrl — entkommen mit Geisterschritt.',ptbr:'Ctrl — escape com Passo Fantasma.',fr:'Ctrl — échapper avec Pas Fantôme.',pl:'Ctrl — ucieknij Krokiem Ducha.',it:'Ctrl — fuggi con Passo Fantasma.',uk:'Ctrl — тікай через Крок привида.',tr:'Ctrl — Hayalet Adımıyla kaç.',vi:'Ctrl — thoát bằng Bước Ma.',th:'Ctrl — หนีด้วย ก้าวผี',id:'Ctrl — kabur dengan Langkah Hantu.',ar:'Ctrl — اهرب بخطوة الشبح.',sv:'Ctrl — fly med Spöksteg.',da:'Ctrl — flugt med Spøgelsegang.',no:'Ctrl — flykt med Spøkelsegang.',fi:'Ctrl — pakene Aaveaskelluksella.',cs:'Ctrl — uteč Krokem přízraku.',hu:'Ctrl — menekülj Szellemlépéssel.',ro:'Ctrl — fugi cu Pasul Fantomă.',nl:'Ctrl — ontsnapt met Geestenstap.',el:'Ctrl — δράπετευσε με Βήμα Φαντάσματος.',bg:'Ctrl — избягай с Крачка призрак.'},
  '더블탭 전격이동으로 탈출하라.': {zh:'双击方向键冲刺脱身。',ja:'ダブルタップで瞬間移動して脱出せよ。',es:'Doble tap para escapar con el dash.',zht:'雙擊方向鍵衝刺脫身。',ru:'Двойной тап — используй рывок.',de:'Doppeltippen — nutze den Blitz-Dash.',ptbr:'Duplo toque — use o dash para escapar.',fr:'Double appui — utilise le dash pour t\'échapper.',pl:'Podwójne dotknięcie — skocz, by uciec.',it:'Doppio tap — usa lo scatto per scappare.',uk:'Двічі натисни — рвонь і тікай.',tr:'Çift dokunuş — kaçmak için dash kullan.',vi:'Nhấn đúp — dùng dash để thoát.',th:'แตะสองครั้ง — วิ่งหนีด้วยดาช',id:'Ketuk dua kali — gunakan dash untuk kabur.',ar:'انقر نقراً مزدوجاً — استخدم الاندفاع للهروب.',sv:'Dubbeltryck — ta dig ur med dash.',da:'Dobbelttryk — brug dash til at flygte.',no:'Dobbeltrykk — bruk dash for å flykte.',fi:'Kaksoisnäppäys — käytä dash-liikettä paetaksesi.',cs:'Dvojité klepnutí — ujdi skokem.',hu:'Dupla érintés — használd a rohamot meneküléshez.',ro:'Apăsare dublă — fugi cu dash.',nl:'Dubbeltik — gebruik dash om te ontsnappen.',el:'Διπλό πάτημα — χρησιμοποίησε το dash.',bg:'Двойно натискане — избягай с рив.'},
  'Ctrl 얼음보주로 탈출하라.': {zh:'按Ctrl用冰球逃脱。',ja:'Ctrlアイスオーブで脱出せよ。',es:'Ctrl: escapa con Orbe de Hielo.',zht:'按Ctrl以冰球逃脫。',ru:'Ctrl — уйди через Ледяную сферу.',de:'Ctrl — entkommen mit Eisorb.',ptbr:'Ctrl — escape com Orbe de Gelo.',fr:'Ctrl — échapper avec l\'Orbe de Glace.',pl:'Ctrl — ucieknij Kulą Lodu.',it:'Ctrl — fuggi con la Sfera di Ghiaccio.',uk:'Ctrl — тікай через Крижану сферу.',tr:'Ctrl — Buz Küreyle kaç.',vi:'Ctrl — thoát bằng Cầu Băng.',th:'Ctrl — หนีด้วย ลูกกลมน้ำแข็ง',id:'Ctrl — kabur dengan Bola Es.',ar:'Ctrl — اهرب بكرة الجليد.',sv:'Ctrl — fly med Isklot.',da:'Ctrl — flugt med Iskugle.',no:'Ctrl — flykt med Iskule.',fi:'Ctrl — pakene Jääpallolla.',cs:'Ctrl — uteč Ledovou koulí.',hu:'Ctrl — menekülj Jéggömbbel.',ro:'Ctrl — fugi cu Sfera de Gheață.',nl:'Ctrl — ontsnapt met Ijsbol.',el:'Ctrl — δράπετευσε με Σφαίρα Πάγου.',bg:'Ctrl — избягай с Ледена сфера.'},
  '스킬 없으면 방향키 연타뿐이야.': {zh:'没有逃脱技能——只能狂按方向键。',ja:'脱出スキルがない——方向キー連打しかないよ。',es:'Sin habilidad de escape — solo machaca las teclas.',zht:'沒有逃脫技能——只能狂按方向鍵。',ru:'Нет навыка побега — только жми стрелки.',de:'Kein Fluchtskill — einfach Richtungstasten hämmern.',ptbr:'Sem habilidade de fuga — só marte as teclas direcionais.',fr:'Pas de compétence de fuite — martelez les touches directionnelles.',pl:'Brak umiejętności ucieczki — walcz przyciskami kierunkowymi.',it:'Nessuna abilità di fuga — premi rapidamente le frecce.',uk:'Немає навички втечі — лише жми стрілки.',tr:'Kaçış becerisi yok — yön tuşlarına art arda bas.',vi:'Không có kỹ năng thoát — chỉ có thể liên bấm phím hướng.',th:'ไม่มีสกิลหนี — กดปุ่มทิศทางถี่ๆ เอา',id:'Tanpa skill kabur — tekan tombol arah berulang kali.',ar:'لا توجد مهارة هروب — فقط اضغط مفاتيح الاتجاه باستمرار.',sv:'Ingen flyktteknik — bara hamra riktningsknapparna.',da:'Ingen flugtteknik — bare hamr retningsknapperne.',no:'Ingen fluktferdighet — bare hamre piltastene.',fi:'Ei pakotaitoa — paina vain suuntanäppäimiä nopeasti.',cs:'Žádná úniková schopnost — jen mačkej šipky.',hu:'Nincs menekülési képesség — csak nyomkod az irányokat.',ro:'Fără abilitate de fugă — apasă repetat tastele direcționale.',nl:'Geen vluchtskill — hamer gewoon op de richtingstoetsen.',el:'Χωρίς δεξιότητα διαφυγής — απλά πάτα τα κατευθυντήρια πλήκτρα.',bg:'Няма умение за бягство — просто удряй посочните клавиши.'},
};

const LANGS = [
  {code:'zh',up:'ZH'},{code:'ja',up:'JA'},{code:'es',up:'ES'},{code:'zht',up:'ZHT'},
  {code:'ru',up:'RU'},{code:'de',up:'DE'},{code:'ptbr',up:'PTBR'},{code:'fr',up:'FR'},
  {code:'pl',up:'PL'},{code:'it',up:'IT'},{code:'uk',up:'UK'},{code:'tr',up:'TR'},
  {code:'vi',up:'VI'},{code:'th',up:'TH'},{code:'id',up:'ID'},{code:'ar',up:'AR'},
  {code:'sv',up:'SV'},{code:'da',up:'DA'},{code:'no',up:'NO'},{code:'fi',up:'FI'},
  {code:'cs',up:'CS'},{code:'hu',up:'HU'},{code:'ro',up:'RO'},{code:'nl',up:'NL'},
  {code:'el',up:'EL'},{code:'bg',up:'BG'},
];

for(const {code,up} of LANGS){
  const file = `${BASE}/lang_${code}.js`;
  if(!fs.existsSync(file)){console.log(`${code}: 없음`);continue;}
  let src = fs.readFileSync(file,'utf8');

  // Find anchor: last entry before "};" of main table
  // Insert before first "};
  const anchor = `\nconst _${up}_PFX={`;
  const anchorIdx = src.indexOf(anchor);
  if(anchorIdx===-1){console.log(`${code}: PFX 앵커 못 찾음`);continue;}

  // Build insert lines
  const lines=[];
  for(const [ko, trs] of Object.entries(TRANS)){
    const val = trs[code]||'';
    if(!val){console.log(`  ${code}: '${ko}' 번역 없음`);continue;}
    // Check if already exists
    if(src.includes(`'${ko}':`)){continue;} // skip if already there
    // escape single quotes in val
    const escaped = val.replace(/'/g,"\\'");
    lines.push(`'${ko}':'${escaped}',`);
  }

  if(lines.length===0){console.log(`✅ ${code}: 이미 있음`);continue;}

  // Insert before _LANG_PFX
  src = src.slice(0,anchorIdx)+'\n'+lines.join('\n')+src.slice(anchorIdx);
  fs.writeFileSync(file,src,'utf8');
  console.log(`✅ ${code}: ${lines.length}개 추가`);
}
console.log('\n완료');
