const fs = require('fs');

let lines = fs.readFileSync('game.html', 'utf-8').split('\n');

// Find start line (구울 전용 렌더)
let startLine = -1, endLine = -1;
for (let i = 0; i < lines.length; i++) {
  if (lines[i].includes('구울 전용 렌더')) { startLine = i; }
  if (startLine >= 0 && lines[i].includes('슬라임 괴물 전용 렌더')) { endLine = i; break; }
}
if (startLine === -1 || endLine === -1) { console.log('ERROR: markers not found', startLine, endLine); process.exit(1); }

// The ghoul block is from startLine to endLine-1 (endLine is the slime comment)
// But we need to find the closing "    }" + "continue;" just before endLine
// Looking at the code: line endLine-1 should be "    }" and endLine-2 "      continue;"
console.log('Replacing lines', startLine+1, 'to', endLine, '(1-indexed)');

const newBlock = [
'    // ── 구울 전용 렌더 (3종 차별화) ──',
'    if(e._isGhoul){',
'      const gt=GHOUL_DEFS[e.etype]||GHOUL_DEFS[101];',
'      const _gT=_now/1000;',
'      e._ghoulT=(e._ghoulT||0)+_dtSp;',
'      // 그림자 (공통)',
'      X.globalAlpha=.2;X.fillStyle=\'#000\';X.beginPath();',
'      X.ellipse(e.x,e.y+e.r*.6,e.r*(e.etype===100?1.4:1.1),e.r*.25,0,0,Math.PI*2);X.fill();',
'',
'      if(e.etype===100){',
'        // ═══ 소형 구울: 네 발 야수형, 빠르고 날렵 ═══',
'        const _gBob=Math.sin(_gT*4+e.x*.05)*1.5;',
'        const _gScurry=Math.sin(_gT*6)*.12;',
'        X.save();X.translate(e.x,e.y+_gBob);X.rotate(_gScurry);',
'        X.globalAlpha=.85;X.fillStyle=\'#778844\';',
'        X.beginPath();X.ellipse(0,e.r*.05,e.r*1.0,e.r*.5,0,0,Math.PI*2);X.fill();',
'        X.globalAlpha=.5;X.strokeStyle=\'#aabb88\';X.lineWidth=1;',
'        for(let _sp2=-.6;_sp2<=.6;_sp2+=.3){X.beginPath();X.moveTo(e.r*_sp2,-e.r*.3);X.lineTo(e.r*_sp2,-e.r*.55);X.stroke()}',
'        X.globalAlpha=.85;X.fillStyle=\'#889944\';',
'        X.beginPath();X.ellipse(e.r*.7,-e.r*.15,e.r*.4,e.r*.35,-.2,0,Math.PI*2);X.fill();',
'        X.globalAlpha=.95;X.fillStyle=\'#ffcc00\';',
'        X.beginPath();X.arc(e.r*.85,-e.r*.25,e.r*.1,0,Math.PI*2);X.fill();',
'        X.beginPath();X.arc(e.r*.85,-e.r*.05,e.r*.1,0,Math.PI*2);X.fill();',
'        X.fillStyle=\'#220000\';',
'        X.beginPath();X.arc(e.r*.87,-e.r*.25,e.r*.04,0,Math.PI*2);X.fill();',
'        X.beginPath();X.arc(e.r*.87,-e.r*.05,e.r*.04,0,Math.PI*2);X.fill();',
'        X.globalAlpha=.8;X.strokeStyle=\'#443300\';X.lineWidth=1;',
'        X.beginPath();X.moveTo(e.r*.95,-e.r*.2);X.lineTo(e.r*1.15,-e.r*.15);X.stroke();',
'        X.fillStyle=\'#ffffcc\';',
'        for(let t=0;t<3;t++){X.beginPath();X.arc(e.r*(1.0+t*.05),-e.r*(.2-t*.03),e.r*.04,0,Math.PI*2);X.fill()}',
'        X.globalAlpha=.7;X.strokeStyle=\'#667733\';X.lineWidth=e.r*.18;X.lineCap=\'round\';',
'        const _legSpd=_gT*8;',
'        X.beginPath();X.moveTo(-e.r*.6,e.r*.3);X.lineTo(-e.r*.8,e.r*.7+Math.sin(_legSpd)*3);X.stroke();',
'        X.beginPath();X.moveTo(-e.r*.2,e.r*.3);X.lineTo(-e.r*.35,e.r*.7+Math.sin(_legSpd+Math.PI)*3);X.stroke();',
'        X.beginPath();X.moveTo(e.r*.2,e.r*.3);X.lineTo(e.r*.35,e.r*.7+Math.sin(_legSpd+Math.PI*.5)*3);X.stroke();',
'        X.beginPath();X.moveTo(e.r*.6,e.r*.3);X.lineTo(e.r*.8,e.r*.7+Math.sin(_legSpd+Math.PI*1.5)*3);X.stroke();',
'        X.globalAlpha=.5;X.strokeStyle=\'#556622\';X.lineWidth=e.r*.12;',
'        X.beginPath();X.moveTo(-e.r*.9,0);X.quadraticCurveTo(-e.r*1.3,Math.sin(_gT*3)*4,-e.r*1.1,-e.r*.2);X.stroke();',
'        X.restore();',
'        if(Math.random()<.05*_dtSp){poolPart(e.x+Math.cos(e.facing)*e.r,e.y+Math.sin(e.facing)*e.r,Math.random()*2-1,-.3,\'#887744\',1.5,8)}',
'',
'      }else if(e.etype===102){',
'        // ═══ 대형 구울: 거대 육중 괴물, 뼈 돌기+두꺼운 팔 ═══',
'        const _gBob=Math.sin(_gT*1.5+e.x*.02)*3;',
'        const _gLean=Math.sin(_gT*1.0)*.08;',
'        X.save();X.translate(e.x,e.y+_gBob);X.rotate(_gLean);',
'        X.globalAlpha=.9;',
'        const _bgrd=X.createRadialGradient(-e.r*.2,-e.r*.2,0,0,0,e.r*1.1);',
'        _bgrd.addColorStop(0,\'#556633\');_bgrd.addColorStop(.5,\'#445522\');_bgrd.addColorStop(1,\'#2a3311\');',
'        X.fillStyle=_bgrd;',
'        X.beginPath();',
'        for(let a=0;a<Math.PI*2;a+=.2){',
'          const _br=e.r*(.85+Math.sin(a*3+e.x*.1)*.12+Math.sin(a*5)*.06);',
'          const px=Math.cos(a)*_br*.75,py=Math.sin(a)*_br*1.05-e.r*.05;',
'          a<.01?X.moveTo(px,py):X.lineTo(px,py);',
'        }X.closePath();X.fill();',
'        X.globalAlpha=.7;X.fillStyle=\'#ccbb88\';',
'        X.beginPath();X.moveTo(-e.r*.6,-e.r*.6);X.lineTo(-e.r*.75,-e.r*1.15);X.lineTo(-e.r*.45,-e.r*.7);X.fill();',
'        X.beginPath();X.moveTo(e.r*.6,-e.r*.6);X.lineTo(e.r*.75,-e.r*1.15);X.lineTo(e.r*.45,-e.r*.7);X.fill();',
'        X.fillStyle=\'#aa9966\';',
'        for(let _sp3=0;_sp3<3;_sp3++){const sx=e.r*(-.2+_sp3*.2);X.beginPath();X.moveTo(sx,-e.r*.8);X.lineTo(sx-e.r*.06,-e.r*1.05);X.lineTo(sx+e.r*.06,-e.r*1.05);X.fill()}',
'        const _hR2=e.r*.32;',
'        X.globalAlpha=.85;X.fillStyle=\'#4a5520\';X.beginPath();X.arc(0,-e.r*1.0,_hR2,0,Math.PI*2);X.fill();',
'        X.globalAlpha=.5;X.fillStyle=\'#bbaa77\';',
'        X.beginPath();X.ellipse(_hR2*.3,-e.r*1.05,_hR2*.35,_hR2*.25,.3,0,Math.PI*2);X.fill();',
'        X.globalAlpha=.95;X.fillStyle=\'#ff1100\';',
'        X.beginPath();X.arc(-_hR2*.4,-e.r*1.05,_hR2*.25,0,Math.PI*2);X.fill();',
'        X.fillStyle=\'#ffdd00\';',
'        X.beginPath();X.arc(-_hR2*.4,-e.r*1.05,_hR2*.12,0,Math.PI*2);X.fill();',
'        X.globalAlpha=.8;X.fillStyle=\'#1a0800\';',
'        X.beginPath();X.ellipse(0,-e.r*.82,_hR2*.5,_hR2*.25+Math.sin(_gT*2)*.06*_hR2,0,0,Math.PI*2);X.fill();',
'        X.fillStyle=\'#ffffcc\';',
'        for(let t=-2;t<=2;t++){X.beginPath();X.arc(_hR2*.15*t,-e.r*.82-_hR2*.2,_hR2*.08,0,Math.PI*2);X.fill()}',
'        X.globalAlpha=.7;X.strokeStyle=\'#3d4a1a\';X.lineWidth=e.r*.35;X.lineCap=\'round\';',
'        X.beginPath();X.moveTo(-e.r*.65,-e.r*.1);',
'        X.quadraticCurveTo(-e.r*1.2,e.r*.3,-e.r*1.0,e.r*.9+Math.sin(_gT*1.5)*3);X.stroke();',
'        X.beginPath();X.moveTo(e.r*.65,-e.r*.1);',
'        X.quadraticCurveTo(e.r*1.2,e.r*.3,e.r*1.0,e.r*.9+Math.sin(_gT*1.5+1.5)*3);X.stroke();',
'        X.globalAlpha=.75;X.fillStyle=\'#3d4a1a\';',
'        X.beginPath();X.arc(-e.r*1.0,e.r*.9,e.r*.22,0,Math.PI*2);X.fill();',
'        X.beginPath();X.arc(e.r*1.0,e.r*.9,e.r*.22,0,Math.PI*2);X.fill();',
'        X.fillStyle=\'#ccbb88\';',
'        for(let c=0;c<3;c++){const ca=-.3+c*.3;',
'          X.beginPath();X.moveTo(-e.r*1.0+Math.cos(ca)*e.r*.2,e.r*.9+Math.sin(ca)*e.r*.2);X.lineTo(-e.r*1.0+Math.cos(ca)*e.r*.35,e.r*.9+Math.sin(ca)*e.r*.35);X.lineTo(-e.r*1.0+Math.cos(ca+.15)*e.r*.2,e.r*.9+Math.sin(ca+.15)*e.r*.2);X.fill();',
'          X.beginPath();X.moveTo(e.r*1.0+Math.cos(Math.PI-ca)*e.r*.2,e.r*.9+Math.sin(Math.PI-ca)*e.r*.2);X.lineTo(e.r*1.0+Math.cos(Math.PI-ca)*e.r*.35,e.r*.9+Math.sin(Math.PI-ca)*e.r*.35);X.lineTo(e.r*1.0+Math.cos(Math.PI-ca-.15)*e.r*.2,e.r*.9+Math.sin(Math.PI-ca-.15)*e.r*.2);X.fill()}',
'        X.globalAlpha=.25;X.fillStyle=\'#221100\';',
'        X.beginPath();X.arc(e.r*.3,e.r*.2,e.r*.2,0,Math.PI*2);X.fill();',
'        X.beginPath();X.arc(-e.r*.25,-e.r*.35,e.r*.18,0,Math.PI*2);X.fill();',
'        X.beginPath();X.arc(e.r*.1,e.r*.5,e.r*.15,0,Math.PI*2);X.fill();',
'        X.restore();',
'        if(Math.random()<.04*_dtSp){const pa=Math.random()*Math.PI*2;poolPart(e.x+Math.cos(pa)*e.r*1.2,e.y+Math.sin(pa)*e.r,Math.cos(pa)*.3,-1,\'#334422\',3+Math.random()*2,20)}',
'',
'      }else{',
'        // ═══ 구울 중형 (101): 표준 비틀거리는 언데드 ═══',
'        const _gBob=Math.sin(_gT*2.5+e.x*.03)*2;',
'        const _gLean=Math.sin(_gT*1.8)*.15;',
'        X.save();X.translate(e.x,e.y+_gBob);X.rotate(_gLean);',
'        X.globalAlpha=.85;X.fillStyle=gt.col;',
'        X.beginPath();X.ellipse(0,-e.r*.1,e.r*.7,e.r*.9,0,0,Math.PI*2);X.fill();',
'        X.globalAlpha=.3;X.strokeStyle=\'#aabb88\';X.lineWidth=1;',
'        for(let rb=-2;rb<=2;rb++){X.beginPath();X.ellipse(0,-e.r*.1+rb*e.r*.15,e.r*.55,e.r*.08,rb*.1,0,Math.PI);X.stroke()}',
'        const _hR=e.r*.45;',
'        X.globalAlpha=.85;X.fillStyle=gt.col;X.beginPath();X.arc(0,-e.r*.9,_hR,0,Math.PI*2);X.fill();',
'        X.globalAlpha=.9;X.fillStyle=\'#ff2200\';',
'        X.beginPath();X.arc(-_hR*.35,-e.r*.95,_hR*.2,0,Math.PI*2);X.fill();',
'        X.beginPath();X.arc(_hR*.35,-e.r*.95,_hR*.2,0,Math.PI*2);X.fill();',
'        X.fillStyle=\'#ffaa00\';',
'        X.beginPath();X.arc(-_hR*.35,-e.r*.95,_hR*.1,0,Math.PI*2);X.fill();',
'        X.beginPath();X.arc(_hR*.35,-e.r*.95,_hR*.1,0,Math.PI*2);X.fill();',
'        X.globalAlpha=.7;X.strokeStyle=\'#331100\';X.lineWidth=1.5;',
'        X.beginPath();X.moveTo(-_hR*.4,-e.r*.75);',
'        X.quadraticCurveTo(0,-e.r*.65+Math.sin(_gT*4)*2,_hR*.4,-e.r*.75);X.stroke();',
'        X.globalAlpha=.6;X.strokeStyle=gt.col;X.lineWidth=e.r*.2;X.lineCap=\'round\';',
'        X.beginPath();X.moveTo(-e.r*.5,0);X.lineTo(-e.r*1.1,e.r*.4+Math.sin(_gT*2.2)*4);X.stroke();',
'        X.beginPath();X.moveTo(e.r*.5,0);X.lineTo(e.r*1.1,e.r*.4+Math.sin(_gT*2.2+1)*4);X.stroke();',
'        X.globalAlpha=.3;X.fillStyle=\'#332211\';',
'        X.beginPath();X.arc(e.r*.2,e.r*.1,e.r*.15,0,Math.PI*2);X.fill();',
'        X.beginPath();X.arc(-e.r*.15,-e.r*.3,e.r*.1,0,Math.PI*2);X.fill();',
'        X.restore();',
'        if(Math.random()<.03*_dtSp){const pa=Math.random()*Math.PI*2;poolPart(e.x+Math.cos(pa)*e.r,e.y+Math.sin(pa)*e.r,Math.cos(pa)*.5,-.5,\'#445533\',2,15)}',
'      }',
'',
'      X.globalAlpha=1;',
'      // HP바 (공통)',
'      {const bw=e.r*2+6,bx=e.x-bw/2;let by=e.y-e.r-14;',
'      if(e.hp<e.mhp){X.fillStyle=\'rgba(0,0,0,.6)\';X.fillRect(bx,by,bw,4);X.fillStyle=gt.col;X.fillRect(bx,by,bw*(e.hp/e.mhp),4);by-=5}',
'      if(e.eShield>0&&e.eShieldMax>0){X.fillStyle=\'rgba(0,0,0,.5)\';X.fillRect(bx,by,bw,3);X.fillStyle=\'#44aaff\';X.fillRect(bx,by,bw*(e.eShield/e.eShieldMax),3);by-=4}',
'      if(e.stunned>0){const _grMax=90;X.fillStyle=\'rgba(0,0,0,.5)\';X.fillRect(bx,by,bw,3);X.fillStyle=\'#ff8800\';X.fillRect(bx,by,bw*Math.min(1,e.stunned/_grMax),3);by-=4}',
'      if(e.maxPoise<Infinity&&e.maxPoise>0){X.fillStyle=\'rgba(0,0,0,.5)\';X.fillRect(bx,by,bw,3);X.fillStyle=\'#ffdd44\';X.fillRect(bx,by,bw*(e.poise/e.maxPoise),3)}}',
'      continue;',
'    }',
];

// Replace lines from startLine to endLine-1 (exclusive of endLine which is slime)
const before = lines.slice(0, startLine);
const after = lines.slice(endLine);
const result = [...before, ...newBlock, ...after];
fs.writeFileSync('game.html', result.join('\n'), 'utf-8');
console.log('OK: replaced lines', startLine+1, 'to', endLine, '→', newBlock.length, 'new lines');
