// Preserved successful stdin harness; only the read-only DOM module import is relocated for this file.
// Run from /Users/fordeargamers/Projects/exoduser-migration-20261001. This saved file has not been rerun.
import fs from 'node:fs';import crypto from 'node:crypto';import vm from 'node:vm';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {createDocument} from '../../../../team-followup-20261001/UIUX/inventory-dom/node-dom.mjs';
const startedUTC=new Date().toISOString(),source=fs.readFileSync('index.html','utf8'),sha=s=>crypto.createHash('sha256').update(s).digest('hex'),{parse}=createRequire(process.cwd()+'/package.json')('acorn'),f=new Map();
for(const m of source.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/g)){for(const n of parse(m[1],{ecmaVersion:'latest',sourceType:'module'}).body)if(n.type==='FunctionDeclaration')f.set(n.id.name,m[1].slice(n.start,n.end));}
const document=createDocument(),base=document.createElement;document.createElement=tag=>{const n=base(tag),matches=n.matches.bind(n);n.matches=selector=>/^\.[\w-]+(?:\.[\w-]+)+$/.test(selector)?selector.slice(1).split('.').every(c=>n.classList.contains(c)):matches(selector);return n;};
const el=(tag,id,parent=document.body)=>{const n=document.createElement(tag);n.id=id;parent.append(n);return n;},pop=el('div','charVisualPop'),grid=el('div','visualGrid',pop),left=el('div','csLeft',pop),right=el('div','csRight',pop),cancel=el('button','visualCancelBtn',pop),create=el('button','visualCreateBtn',pop);pop.style.display='none';left.scrollIntoView=right.scrollIntoView=()=>{};
for(const id of ['csIdleVid','csSceneVid']){const v=el('video',id,pop);v.pause=()=>{};v.load=()=>{};}
const context=vm.createContext({document,$:id=>document.getElementById(id),clearTimeout:()=>{},CHAR_VISUALS:[{name:'fixture-a'},{name:'fixture-b'}],_TL:s=>s,_spawnEmbers:()=>{},_resetVisualInfoScroll:()=>{},selectVisual:ci=>grid.children.forEach((c,i)=>c.classList.toggle('sel',i===ci))});
const names=['openVisualSelect','_closeVisualSelect','stopMediaVideo','_visualSelectKeydown'];vm.runInContext('let _visualReturnFocus=null,_visualPreviewSeq=0,_pendingVisualIdx=0;\n'+names.map(n=>f.get(n)).join('\n'),context);
let prevented=0,stopped=0;const key=(key,shiftKey=false)=>context._visualSelectKeydown({key,shiftKey,isComposing:false,keyCode:0,repeat:false,preventDefault(){prevented++;},stopPropagation(){stopped++;}}),label=n=>n===document.body?'BODY':n.id||'icon'+grid.children.indexOf(n);
context.openVisualSelect();assert.equal(label(document.activeElement),'icon0');
create.focus();const forward=[];for(let i=0;i<6;i++){key('Tab');forward.push(label(document.activeElement));}assert.deepEqual(forward,['csLeft','csRight','icon0','icon1','visualCancelBtn','visualCreateBtn']);
left.focus();const reverse=[];for(let i=0;i<6;i++){key('Tab',true);reverse.push(label(document.activeElement));}assert.deepEqual(reverse,['visualCreateBtn','visualCancelBtn','icon1','icon0','csRight','csLeft']);
const oldIcon=grid.children[0];context._closeVisualSelect();const p=prevented,s=stopped;key('Tab');assert.equal(prevented,p);assert.equal(stopped,s);assert.equal(label(document.activeElement),'BODY');
context.openVisualSelect();assert.equal(oldIcon.isConnected,false);assert.equal(label(document.activeElement),'icon0');key('Tab');assert.equal(label(document.activeElement),'icon1');key('Tab',true);assert.equal(label(document.activeElement),'icon0');
document.body.focus();key('Tab');assert.equal(label(document.activeElement),'csLeft');document.body.focus();key('Tab',true);assert.equal(label(document.activeElement),'visualCreateBtn');
console.log(JSON.stringify({task:'UIUX-autonomous-tab-reopen-memory-1126',startedUTC,endedUTC:new Date().toISOString(),sourceSHA256:sha(source),fragments:names.map(name=>({name,sha256:sha(f.get(name))})),results:{forward,reverse,hiddenHandlerIgnored:true,reopenedCurrentIcons:true,externalFocusRecovery:true,prevented,stopped},status:'NOFIX-inspected-boundary',syntheticCharacters:2,doubles:['node-dom plus compound class selector','CHAR_VISUALS2','selectVisual','spawnEmbers','resetVisualInfoScroll','media','clearTimeout','scrollIntoView'],nativeAccepted:false,newFiles:0,productionApplied:false}));
